### ISSUE TITLE
🐛 [REALTIME_DATABASE] Type error on nested values when interacting with emulator

### ISSUE THREAD

**Issue by Solutionstbd** [firebase/flutterfire#10002]
## Bug report

**Describe the bug**
Realtime Listener failing to listen due to type error while using firebase emulator. I have only tested Chrome and Android. The type error appears on both platforms but chrome continues listening while android breaks the listening stream before providing my ui with its first value. 
This issue is specific to nested values where my database reference is pointing to a value with child values involved. When I reference the specific child I have interest in listening to, this issue does not appear, or at least does not crash the listener.

### Steps to reproduce

1. Utilize sample code below. 
2. Run on android emulator while connecting to firebase emulator
3. Listener fails to provide a value for parent node
4. The run without firebase emulator, and it works without a hiccup

### Expected behavior

While running the sample code, both values within the UI should update.

firebase tool version = 11.16.1 (CLI - emulator)

firebase_database: ^10.0.6
firebase_core: ^2.1.1

### Sample project

```dart
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  if (kIsWeb) FirebaseAuth.instance.setPersistence(Persistence.SESSION);
  await SetUpPortsForDatabaseEmulation();
  runApp(const App());
}

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyPage(),
    );
  }
}

class MyPage extends StatefulWidget {
  const MyPage({super.key});

  @override
  State<MyPage> createState() => _MyPageState();
}

class _MyPageState extends State<MyPage> {
  int childCounter = 0;
  int parentCounter = 0;
  void setParentValue(int value) {
    setState(() {
      parentCounter = value;
    });
  }

  void setChildValue(int value) {
    setState(() {
      childCounter = value;
    });
  }

  bool isListening = false;

  void listenToParent() async {
    final ref = FirebaseDatabase.instance.ref('/user/xxxxxxxxxxx');

    await for (DatabaseEvent event in ref.onValue) {
      print('Something received from parent stream');
      final data = Map.from(event.snapshot.value as dynamic);
      final desiredValue = data['count'];
      setParentValue(desiredValue);
    }
  }

  void listenToChild() async {
    final ref = FirebaseDatabase.instance.ref('/user/xxxxxxxxxxx/count');

    await for (DatabaseEvent event in ref.onValue) {
      print('Something received from child stream');
      final desiredValue = event.snapshot.value as int;
      setChildValue(desiredValue);
    }
  }

  int trueCount = 0;

  void pressButton() {
    trueCount++;
    FirebaseDatabase.instance.ref('/user/xxxxxxxxxxx/count').set(trueCount);
    if (!isListening) {
      listenToParent();
      listenToChild();
    }
  }

  @override
  Widget build(BuildContext context) {
    // print('Press: trueCount = $trueCount & listenCounter: $childCounter');
    return Scaffold(
        body: SafeArea(
            child: Center(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Text('Child Count: $childCounter'),
              Text('Parent Count: $parentCounter'),
            ],
          ),
        )),
        floatingActionButton: FloatingActionButton(
          onPressed: pressButton,
        ));
  }
}
```

```dart
Future<void> SetUpPortsForDatabaseEmulation() async {
  FirebaseFirestore.instance.settings = const Settings(
    host: '127.0.0.1:8080',
    sslEnabled: false,
    persistenceEnabled: false,
  );

  FirebaseDatabase.instance.useDatabaseEmulator('127.0.0.1', 9000);
  await FirebaseAuth.instance.useAuthEmulator('127.0.0.1', 9099);
  FirebaseFunctions.instance.useFunctionsEmulator('127.0.0.1', 5001);
  FirebaseStorage.instance.useStorageEmulator('127.0.0.1', 9199);
}
```

---

## Additional context

The error is always a type issue and varies slightly between platforms. 
Within my production code, I am trying to access a parent node with two child nodes.
```
databasePath/userId{
status : (int value),
message : (string value)
}
```
While trying to access this on android, I get the following error
```
type '_InternalLinkedHashMap<Object?, Object?>' is not a subtype of type 'String?'
```
While trying to access this on chrome, I get the following error
```
Expected a value of type 'String?', but got one of type 'IdentityMap<String, dynamic>'
```
I assume this has to due with the nested values being typed incorrectly?

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 3.5.0-12.0.pre.119, on
    Microsoft Windows [Version 10.0.19045.2251], locale
    en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor  
      --android-licenses
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.6)
[!] Android Studio (version 4.0)
    X Unable to find bundled Java version.
[√] Android Studio (version 2021.3)
[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
[√] Connected device (4 available)
[√] HTTP Host Availability
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
  cloud_firestore: ^4.0.4
  cloud_functions: ^4.0.3
  firebase_auth: ^4.1.1
  firebase_database: ^10.0.6
  firebase_storage: ^11.0.4
  firebase_core: ^2.1.1
```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the report @Solutionstbd 


> type '_InternalLinkedHashMap<Object?, Object?>' is not a subtype of type 'String?'

`_InternalLinkedHashMap <Object?, Object?>` can also be interpreted as `Map <Object?, Object?>).`, so if you know the value of the Map properties are `String`, you can do something like below:

`final value = Map<String, String>.from(event.snapshot.value! as Map<Object?, Object?>);`, because we leave upto the user to cast the value correctly and is not done explicitly by the plugin.

**Comment by Solutionstbd** [comment]
Then I assume I am dealing with two issues. 
1.)The _InternalLinkedHashMap <Object?, Object?> is workable, or at least I have dealt with before. I can likely find a way to deal with it this time. So we can ignore that for the purpose of this report.
2.) The real issue that is stopping me is the mentioned prior to the mentioning of _InternalLinkedHashMap within my report. When I use the firebase emulator along with android, the value retrieved is not even provided to me in order to work with it. There is no option for me to decide how to cast because no value is provided.

**Comment by darshankawar** [comment]
Thanks for the update. Considering the fact that the error is occuring only using `firebase_emulators` and not using local emulator or physical device, I would also suggest to reach out to https://github.com/firebase/firebase-tools/issues
