### ISSUE TITLE
🐛 [firebase_ui_oauth_google] clientId is required but not supported on Android

### ISSUE THREAD

**Issue by sgrodzicki** [firebase/flutterfire#10005]
## Bug report

**Describe the bug**
`clientId` is a required parameter for `GoogleProvider` but is not supported on Android and is interpreted as `serverClientId` instead.

### Steps to reproduce

1. Setup `GoogleProvider` as in example: https://github.com/firebase/flutterfire/blob/26087bb2d1747eb5db82c98424b6d63071137529/packages/firebase_ui_auth/example/lib/main.dart#L37
1. Run app on Android
1. See `W/google_sign_in( 9388): clientId is not supported on Android and is interpreted as serverClientId. Use serverClientId instead to suppress this warning.` in console and `An unknown error occurred` on device/emulator

### Expected behavior

The `clientId` parameter should be optional (to set for iOS and skip for Android) or have separate methods for each platform.

### Sample project

https://github.com/firebase/flutterfire/tree/26087bb2d1747eb5db82c98424b6d63071137529/packages/firebase_ui_auth/example

**Comment by darshankawar** [comment]
Thanks for the report @sgrodzicki . Seeing the same behavior as reported.

**Comment by Lyokone** [comment]
Should be fixed with #10017, will be released Thursday

**Comment by sgrodzicki** [comment]
Thanks for the rapid fix however the workaround seems a bit hacky. How about letting the `google_sign_in` plugin handle this directly (which by default reads the client ID from GoogleService-Info.plist)? If one would only use the `firebase_ui_oauth_google` with Android they would need to provide a client ID although they don't need one.
