### ISSUE TITLE
🐛 [firebase_core_web] Firebase.initializeApp issue within Flutter Web

### ISSUE THREAD

**Issue by oopchi** [firebase/flutterfire#10007]
## Bug report

**Describe the bug**
This is actually a duplicate of [#7701](https://github.com/firebase/flutterfire/issues/7701#issue-1088690194), but there has been no conclusion there and the issue was closed so i open another one here as I'm struggling across this exact same issue right now.

context['flutterfire_ignore_scripts'] is null, so this crashes

List get _ignoredServiceScripts {
try {
JsObject ignored =
JsObject.fromBrowserObject(context['flutterfire_ignore_scripts']); < -- crash

This issue doesn't appear (it's still there but the app still works fine) only if it's run with the --verbose options enabled (flutter run -d chrome --verbose), otherwise it crashes the app.

Here is some minor details that might help :

<img width="471" alt="Screen Shot 2022-11-28 at 09 53 45" src="https://user-images.githubusercontent.com/61549998/204181544-89262a9b-cf66-4f10-9b7b-9145b6979817.png">

With this exact code, there is no issue running it on iOS and android, only web seems to suffer from this issue.

I've also tried adding the name parameter (using the project name inside firebase console) inside the Firebase.initializeApp, but the exact same error still persists.

I've tried switching to several other version of flutter only to no avails:
- 3.3.9
- 3.3.1
- 3.6.0-0.1.pre
- 3.4.0-34.1.pre
- 3.3.8

I've also tried to manually insert this line of code inside web/index.html
`window.flutterfire_ignore_scripts = ['analytics'];`

such as
```
<body>
  <script>
    window.flutterfire_ignore_scripts = ['analytics']; --> this one i added manually
    window.addEventListener('load', function(ev) {
      // Download main.dart.js
      _flutter.loader.loadEntrypoint({
        serviceWorker: {
          serviceWorkerVersion: serviceWorkerVersion,
        }
      }).then(function(engineInitializer) {
        return engineInitializer.initializeEngine();
      }).then(function(appRunner) {
        return appRunner.runApp();
      });
    });
  </script>
</body>
```

With this addition, the error shifted into:

<img width="907" alt="Screen Shot 2022-11-28 at 10 04 39" src="https://user-images.githubusercontent.com/61549998/204182647-33846803-0578-4e72-8979-16b2b2d81bcb.png">

pubspec.yaml:

```
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.4
  cloud_firestore: ^4.1.0
```

**Comment by darshankawar** [comment]
@oopchi 
I am unable to replicate this using the details you provided. I used the firebase_core plugin example and ran it on web.
Can you try the same and see if using it, you still get same error ? 
Also, please provide exact steps to replicate if possible that triggers the error.
