### ISSUE TITLE
🐛 [firebase_storage] [connection] nw_resolver_start_query_timer_block_invoke [C1.1] Query fired: did not receive all answers in time for firebasestorage.googleapis.com:443

### ISSUE THREAD

**Issue by hassanyassiin** [firebase/flutterfire#10003]
## Bug report

**Describe the bug**
When trying to upload an image into the firebase storage then this error occur.

### Expected behavior

The image is saved in the firebase storage and url is returned back without an error.

### Actual behavior
The image is saved in the firebase storage and url is returned back but with this error.

### Sample project

 ```
try {
    // First we create a folder into the database and name it as the savedFolderName suggests.
    final ref = FirebaseStorage.instance
        .ref()
        .child(savedFolderName)
        .child(DateTime.now().toString());

    await ref.putFile(File(image.path));

    final url = await ref.getDownloadURL();

    return url;
  } on FirebaseException catch (_) {
    rethrow;
  } catch (error) {
    rethrow;
  }
```
### Flutter doctor
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.0.1 22A400 darwin-arm, locale
    en-LB)
    • Flutter version 3.3.9 on channel stable at
      /Users/hassanyassin/Desktop/Flutter/Development/Tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (4 days ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/hassanyassin/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

[✓] Connected device (3 available)
    • iPhone (19) (mobile) • 08f6d5d4e6ac65273a8757fc2424f2f593e6ca56 • ios
      • iOS 16.1.1 20B101
    • macOS (desktop)      • macos                                    •
      darwin-arm64   • macOS 13.0.1 22A400 darwin-arm
    • Chrome (web)         • chrome                                   •
      web-javascript • Google Chrome 106.0.5249.103

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

**Comment by darshankawar** [comment]
@hassanyassiin 
Thanks for the report. What platform are you seeing this behavior on ? Can you provide complete error log in properly formatted text ?

Also can you try the plugin's [official example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_storage/firebase_storage/example) and see if using it, you get same behavior as reported ?

**Comment by hassanyassiin** [comment]
@darshankawar In IOS Platform this error is happening, only in the real IOS device not in the emulator. and yes I tries the same example and the same error is happening.
error logs : **[connection] nw_resolver_start_query_timer_block_invoke [C1.1.1] Query fired: did not receive all answers in time for firebasestorage.googleapis.com:443**

**Comment by hassanyassiin** [comment]
and there's another issue that I'm getting ** [FirebaseCore][I-COR000005] No app has been configured yet.** whenever I launch the app for the first time but I'm Initializing the firebase in my app. 

`Future<void> main() async {
  SystemChrome.setSystemUIOverlayStyle(
      const SystemUiOverlayStyle(statusBarColor: Colors.transparent));
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const MyApp());
}`

**Note:** when trying to import the FirebaseCore in the AppDelegate.swift and make FirebaseApp.configure() then this error will not occur ** [FirebaseCore][I-COR000005] No app has been configured yet.**  but why should I configure the firebase in AppDelegate if I initialize it in the main function.

**Comment by darshankawar** [comment]
@hassanyassiin 
I am unable to replicate the error using the plugin example and running it on physical iOS device. Can you provide a complete minimal reproducible code sample that we can directly use to verify this ?



> and there's another issue that I'm getting

Please file new issue for this for better tracking.

**Comment by hassanyassiin** [comment]
I don't know why I'm getting this message only in the IOS device and my code is simple.

The message is occurred when the **await ref.putFile(File(image.path))** is called.

    try {

    final ref = FirebaseStorage.instance
        .ref()
        .child(savedFolderName)
        .child(DateTime.now().toString());
    
    // HERE I'M GETTING THE ERROR MESSAGE // 
    await ref.putFile(File(image.path));

    final url = await ref.getDownloadURL();

    return url;
     } on FirebaseException catch (_) {
    rethrow;
    } 

**Note:** That the image is stored successfully into the database and the url is being return successfully also.

**Comment by darshankawar** [comment]
> await ref.putFile(File(image.path));

Can you provide what exactly is being passed through `image.path` ?

According to [documentation](https://firebase.google.com/docs/storage/flutter/upload-files#upload_from_a_file), it must be the direct reference to child url, ie, something like below:

```
String filePath = '${appDocDir.absolute}/file-to-upload.png';
File file = File(filePath);

try {
  await mountainsRef.putFile(file);
```

Also, looking at the log you are getting, it most probably seems to be coming from native SDK and not from client, ie, Flutterfire.

**Comment by hassanyassiin** [comment]
You mean from the IOS sdk ? so what should I do in this case ? I initialized firebase with iOS like the documentation mentioned in the flutterFire Cli website.

Also the function is correct I used to upload a string into the firebase-storage instead of file and the message is the same, so the issue is not with the file .

**Comment by darshankawar** [comment]
Can you try using the `path_provider` package as mentioned in the document because in order to use upload file feature along with `putFile()`, the package's usage could be important as shown below:

```
Directory appDocDir = await getApplicationDocumentsDirectory();
String filePath = '${appDocDir.absolute}/file-to-upload.png';
File file = File(filePath);

try {
  await mountainsRef.putFile(file);
} on firebase_core.FirebaseException catch (e) {
  // ...
}
```

The `getApplicationDocumentsDirectory()` method is coming from `path_provider`, so please try the same implementation at your end and see if using that implementation, you still get same error or not.

**Comment by hassanyassiin** [comment]
I didn't realized that path_provider is used in the [official example](https://github.com/firebase/flutterfire/blob/master/packages/firebase_storage/firebase_storage/example/lib/main.dart) so I didn't used it in my app, However now I used it but I'm getting this error **Failed assertion: line 127 pos 12: 'file.absolute.existsSync()': is not true.** when uploading the file.

    String filePath = '${appDocDir.absolute}/${File(image.path)}';

I'm doing something wrong ?

**Comment by hassanyassiin** [comment]
I created a new flutter project and keep it like the default one and just I add the function for the firebase storage. and the error stay the same


// Please check the onPressed function in the FloatingActionButton
<img width="1512" alt="Screenshot 2022-11-30 at 3 07 54 PM" src="https://user-images.githubusercontent.com/94860683/204804593-a20d6a70-dda2-423d-aab9-c8f3040418bf.png">

**Comment by darshankawar** [comment]
Try something like below which I tried myself and worked properly:

```
floatingActionButton: FloatingActionButton(
        onPressed: () async {
          Reference ref = FirebaseStorage.instance.ref().child('images');
          Directory appDocDir = await getApplicationDocumentsDirectory();
          print(appDocDir);
          String filePath = '/Users/dhs/Library/Developer/CoreSimulator/Devices/640AC26E-2012-4D9F-965A-20029B7408C4/data/Containers/Data/Application/177E85D7-92FE-4C21-97F6-1F6B580F4C5B/Documents/bangalore.jpeg';
          print(filePath);
          File file = File(filePath);
          ref.putFile(file);
          print(file);
          print('file added');
```

Above is using `path_provider` and you'll first need to get the `applicationDocumentsDirectory()` that will be returned based on the device / simulator you are using. Try to have a sample image or file in that path as I mentioned above as an example and then try to run and see if you get expected behavior or not.

**Comment by hassanyassiin** [comment]
@darshankawar  Thanks for your help, can you please tell me where did you add the XFile that the user is selected from the gallery into the path ? because I'm getting an error before the ` ref.putFile(file);` function telling me `flutter: 'package:firebase_storage/src/reference.dart': Failed assertion: line 127 pos 12: 'file.absolute.existsSync()': is not true.`

    XFile selectedImage = image;
    Reference ref = FirebaseStorage.instance.ref().child('images');
    Directory appDocDir = await getApplicationDocumentsDirectory();
    print(appDocDir);
    String filePath = '$appDocDir${File(selectedImage.path)}';
    print(filePath);
    File file = File(filePath);
    ref.putFile(file);
    print(file);
    print('file added');

// Can you tell me please where and how should I add the XFile into the filePath inOrder to send it with the putFile function because I'm getting error, and I tried like the documentation mentioned. Please check my example above and tell me where should I modify.

**Comment by hassanyassiin** [comment]
I will tell you the steps I did in order to get firebase/ firebase storage into my flutter app.

1 - Get into [Firebase](https://firebase.google.com/?gclsrc=aw.ds&gclid=CjwKCAjw3cSSBhBGEiwAVII0Z4kWU6wEPcO4Xs_YP9VypbgsVd_HUJyp5J3FMwWRHLYlnwZVIzO33RoCOrEQAvD_BwE) and create a project there.
2 - Get into the [Storage`](https://console.firebase.google.com/project/asdsd-3b696/storage) in the project and press on Get Started, then choose start with test mode.
3 - Return back to the flutter project and import FirebaseCore and Firebase-Storage from [pub.dev](https://pub.dev).
4 - Go to the terminal in the flutter project and run the command **dart pub global activate flutterfire_cli**.
5 - Then run **flutterfire configure** and select the project that we created in the second step.
6 - Add  **WidgetsFlutterBinding.ensureInitialized();** and  **await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform);** in the main function.
7 - Finally start using the firebase like the comment above and as you mentioned.

**Comment by darshankawar** [comment]
`Directory appDocDir = await getApplicationDocumentsDirectory();` will print a path, for example, if you are running on simulator, it will show a below path:

`/Users/dhs/Library/Developer/CoreSimulator/Devices/640AC26E-2012-4D9F-965A-20029B7408C4/data/Containers/Data/Application/177E85D7-92FE-4C21-97F6-1F6B580F4C5B`. Here in the `Documents` folder, you may just put a sample image and then run app again, don't hot restart. Stop execution and re-run which most probably should get rid of the `'file.absolute.existsSync()':` error.

Or maybe try to give the exact path directly instead of:

`String filePath = '$appDocDir${File(selectedImage.path)}';`

do:

String filePath = '/Users/dhs/Library/Developer/CoreSimulator/Devices/640AC26E-2012-4D9F-965A-20029B7408C4/data/Containers/Data/Application/177E85D7-92FE-4C21-97F6-1F6B580F4C5B/Documents/<image>';

**Comment by hassanyassiin** [comment]
@darshankawar Thanks for your help and your time.
