### ISSUE TITLE
FlutterFire docs contradict main Firebase docs on data message priority.

### ISSUE THREAD

**Issue by Turburlar** [firebase/flutterfire#10000]
From the FlutterFire docs on [background messages](https://firebase.flutter.dev/docs/messaging/usage#background-messages), under the Low Priority Message sub-section, the following is stated:

_"As mentioned above, data only messages are classed as "low priority". Devices can throttle and ignore these messages if your application is in the background, terminated, or a variety of other conditions such as low battery or currently high CPU usage.

You should not rely on data only messages to be delivered. They should only be used to support your application's non-critical functionality, e.g. pre-fetching data so the next time the user opens your app the data is ready to be displayed and if the message never gets delivered then your app still functions and fetches data on open.

To help improve delivery, you can bump the priority of messages. Note: this still does not guarantee delivery.

For example, if using the firebase-admin NodeJS SDK package to send notifications via your server, add additional properties to the message payload:"_

This statement implies data messages are low priority.

This same information is not presented anywhere in the main Firebase Cloud Messaging docs.

Under the ['Set and Manage Message Priority'](https://firebase.google.com/docs/cloud-messaging/android/message-priority), any info about reduced reliability and low priority nature of data messages is completely ommited.

I feel like these two sections should be more clear and consistent in their wording.

**Comment by Lyokone** [comment]
As mentioned on the [FlutterFire website](https://firebase.flutter.dev/), this documentation is outdated, you can find the latest documentation here:
https://firebase.google.com/docs/cloud-messaging/flutter/receive
