### ISSUE TITLE
[flutterfire] "Firebase.initializeApp" exception "Expected a value of type 'Object', but got one of type 'Null'"

### ISSUE THREAD

**Issue by arslankaleem7229** [firebase/flutterfire#10009]
I have seen many posts related to this but didn't find any solution

```
Exception has occurred.
"Error: Expected a value of type 'Object', but got one of type 'Null'
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 99:3        castError
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 452:10  cast
dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 73:24                 as
packages/firebase_core_web/src/firebase_core_web.dart 64:20                       get [_ignoredServiceScripts]
packages/firebase_core_web/src/firebase_core_web.dart 115:28                      _initializeCore
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                _async
packages/firebase_core_web/src/firebase_core_web.dart 107:31                      [_initializeCore]
packages/firebase_core_web/src/firebase_core_web.dart 149:11                      initializeApp
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                _async
packages/firebase_core_web/src/firebase_core_web.dart 145:44                      initializeApp
packages/firebase_core/src/firebase.dart 43:47                                    initializeApp
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                _async
packages/firebase_core/src/firebase.dart 39:43                                    initializeApp
packages/holistic_mobile_app/main_development.dart 30:18                          main
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                _async
packages/holistic_mobile_app/main_development.dart 27:10                          main
web_entrypoint.dart 24:31                                                         <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 334:14  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 339:39  dcall
lib/ui/initialization.dart 77:15                                                  <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                <fn>
dart-sdk/lib/async/zone.dart 1653:54                                              runUnary
dart-sdk/lib/async/future_impl.dart 147:18                                        handleValue
dart-sdk/lib/async/future_impl.dart 766:44                                        handleValueCallback
dart-sdk/lib/async/future_impl.dart 795:13                                        _propagateToListeners
dart-sdk/lib/async/future_impl.dart 566:5                                         [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 639:7                                         callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                                  _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                                   _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15               <fn>
"
```

![Screenshot 2022-11-28 at 3 31 36 PM](https://user-images.githubusercontent.com/49631685/204255774-1e43f535-8b39-4ba8-bbe7-df1c8ebd08a0.png)

**Comment by darshankawar** [comment]
@arslankaleem7229 
When you open an issue, please try to use new issue template and fill out requested details so that we'll have enough details to work with. Just posting error screenshot with no other details isn't much helpful.

Please provide `flutter doctor -v`, complete reproducible code sample along with steps to replicate that shows the reported error.

**Comment by arslankaleem7229** [comment]
<details>
<summary>flutter doctor -v</summary>
<p>


[✓] Flutter (Channel stable, 3.3.8, on macOS 13.0 22A380 darwin-arm, locale en-PK)
    • Flutter version 3.3.8 on channel stable at /Users/arslankaleem/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (3 weeks ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/arslankaleem/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Brave Browser 107.1.45.131

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

</p>
</details>

**Comment by brijeshsoni1300** [comment]
any way to solve this error ???
i m getting the same error 
while using firebase web

**Comment by arslankaleem7229** [comment]
@brijeshsoni1300 not yet

**Comment by darshankawar** [comment]
@arslankaleem7229 
Do you get this error in a new project ? ie, run `flutter create <projectname>, run `dart pub global activate flutterfire_cli` followed by `flutterfire configure` and select the firebase project. Then add `firebase_core` and run it on web to see if you get same error or not.
Else, provide exact steps to replicate.



> I am using `firebase_core` and `firebase_messaging`

Does it occur using both plugins or only with one as well ? ie, `firebase_core` only ?

**Comment by arslankaleem7229** [comment]
Here are all exceptions that I am getting

<details>
<summary>Firebase.initializeApp</summary>
<p>


Exception has occurred.
"Error: Expected a value of type 'Object', but got one of type 'Null'
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 99:3        castError
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 452:10  cast
dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 73:24                 as
packages/firebase_core_web/src/firebase_core_web.dart 64:20                       get [_ignoredServiceScripts]
packages/firebase_core_web/src/firebase_core_web.dart 115:28                      _initializeCore
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                _async
packages/firebase_core_web/src/firebase_core_web.dart 107:31                      [_initializeCore]
packages/firebase_core_web/src/firebase_core_web.dart 149:11                      initializeApp
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                _async
packages/firebase_core_web/src/firebase_core_web.dart 145:44                      initializeApp
packages/firebase_core/src/firebase.dart 43:47                                    initializeApp
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                _async
packages/firebase_core/src/firebase.dart 39:43                                    initializeApp
packages/firebase_setup/main.dart 8:18                                            main
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                _async
packages/firebase_setup/main.dart 6:10                                            main$
web_entrypoint.dart 24:31                                                         <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 334:14  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 339:39  dcall
lib/ui/initialization.dart 77:15                                                  <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                <fn>
dart-sdk/lib/async/zone.dart 1653:54                                              runUnary
dart-sdk/lib/async/future_impl.dart 147:18                                        handleValue
dart-sdk/lib/async/future_impl.dart 766:44                                        handleValueCallback
dart-sdk/lib/async/future_impl.dart 795:13                                        _propagateToListeners
dart-sdk/lib/async/future_impl.dart 566:5                                         [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 639:7                                         callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                                  _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                                   _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15               <fn>
"


</p>
</details>

<details>
<summary>Firebase.initializeApp</summary>
<p>


Exception has occurred.
"FirebaseError: Firebase: Need to provide options, when not being deployed to hosting via source. (app/no-options).
https://www.gstatic.com/firebasejs/9.11.0/firebase-app.js 1944:29    initializeApp
https://www.gstatic.com/firebasejs/9.11.0/firebase-app.js 1997:16    getApp
packages/firebase_core_web/src/interop/core.dart 57:69               app$
packages/firebase_core_web/src/firebase_core_web.dart 186:24         initializeApp
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50   <fn>
dart-sdk/lib/async/zone.dart 1653:54                                 runUnary
dart-sdk/lib/async/future_impl.dart 147:18                           handleValue
dart-sdk/lib/async/future_impl.dart 766:44                           handleValueCallback
dart-sdk/lib/async/future_impl.dart 795:13                           _propagateToListeners
dart-sdk/lib/async/future_impl.dart 566:5                            [_completeWithValue]
dart-sdk/lib/async/future.dart 528:22                                <fn>
dart-sdk/lib/async/zone.dart 1653:54                                 runUnary
dart-sdk/lib/async/future_impl.dart 147:18                           handleValue
dart-sdk/lib/async/future_impl.dart 766:44                           handleValueCallback
dart-sdk/lib/async/future_impl.dart 795:13                           _propagateToListeners
dart-sdk/lib/async/future_impl.dart 566:5                            [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 639:7                            callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                     _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                      _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15  <fn>
"


</p>
</details>

<details>
<summary>
FirebaseMessaging.instance.getToken
</summary>
<p>


Exception has occurred.
"Error: [firebase_messaging/failed-service-worker-registration] Messaging: We are unable to register the default service worker. Failed to register a ServiceWorker for scope ('http://localhost:55525/firebase-cloud-messaging-push-scope') with script ('http://localhost:55525/firebase-messaging-sw.js'): The script has an unsupported MIME type ('text/html'). .
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 299:10  createErrorWithStack
dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 341:28            _throw
dart-sdk/lib/core/errors.dart 116:5                                           throwWithStackTrace
packages/_flutterfire_internals/_flutterfire_internals.dart 116:31            <fn>
dart-sdk/lib/async/zone.dart 1658:54                                          runBinary
dart-sdk/lib/async/future_impl.dart 162:22                                    handleError
dart-sdk/lib/async/future_impl.dart 778:46                                    handleError
dart-sdk/lib/async/future_impl.dart 799:13                                    _propagateToListeners
dart-sdk/lib/async/future_impl.dart 574:5                                     [_completeError]
dart-sdk/lib/async/future_impl.dart 665:7                                     callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>
"


</p>
</details>


<details>
<summary>FirebaseMessaging.instance.getToken</summary>
<p>


Exception has occurred.
"Error: [firebase_messaging/failed-service-worker-registration] Messaging: We are unable to register the default service worker. Failed to register a ServiceWorker for scope ('http://localhost:55525/firebase-cloud-messaging-push-scope') with script ('http://localhost:55525/firebase-messaging-sw.js'): The script has an unsupported MIME type ('text/html'). .
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 299:10  createErrorWithStack
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 60:38            <fn>
dart-sdk/lib/async/zone.dart 1658:54                                          runBinary
dart-sdk/lib/async/future_impl.dart 162:22                                    handleError
dart-sdk/lib/async/future_impl.dart 778:46                                    handleError
dart-sdk/lib/async/future_impl.dart 799:13                                    _propagateToListeners
dart-sdk/lib/async/future_impl.dart 574:5                                     [_completeError]
dart-sdk/lib/async/future_impl.dart 665:7                                     callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>
"



</p>
</details>

**Comment by darshankawar** [comment]
I have all uncaught exceptions checked using AS as below:

<img width="267" alt="Screenshot 2022-11-30 at 1 20 37 PM" src="https://user-images.githubusercontent.com/67046386/204738812-eaf0fe1d-15f4-43ef-a6b2-ebc03069e500.png">

And running `firebase_core` example or `firebase_messaging` example on web is not throwing me the same error as reported.
But based on above report and log, I am keeping this issue open for team's attention and insights.

/cc @russellwheatley

**Comment by brijeshsoni1300** [comment]
i am getting error like
![image](https://user-images.githubusercontent.com/51873202/204760630-73208712-3d21-4c9f-9370-bdc14f73de70.png)

**Comment by zariweyo** [comment]
Review this.

Instead of import 
<script src="https://www.gstatic.com/firebasejs/9.11.0/firebase-appt.js"></script>

use this
<script src="https://www.gstatic.com/firebasejs/9.11.0/firebase-app-compat.js"></script>

You need to add "-compat" in all scripts links for firebase version 9 in index.html
https://firebase.google.com/docs/web/modular-upgrade#window-compat

**Comment by russellwheatley** [comment]
If someone can provide a repro, we can look into this issue.

**Comment by brijeshsoni1300** [comment]
for me 
flutterfire configure generates the default firebase options for different options
the thing is, even it gives us error in firebase.initalizeapp() if you run it without debug one its working somehow 
idk how!!!

so this cmd
![image](https://user-images.githubusercontent.com/51873202/205260188-e58fd302-1400-447e-b521-b1a530835b5e.png)

generates
![image](https://user-images.githubusercontent.com/51873202/205260288-284993d2-681a-466d-8a5b-e5e08d31041f.png)


and update in your main.dart

```
void main() async {
await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform); 
 runApp(const MyApp());
}
```

and run without debugger 
it will throw the error but somehow its working

i checked it using remote config 
![image](https://user-images.githubusercontent.com/51873202/205260664-ed33a29e-493f-4643-bd2d-14bfe7c84143.png)

so in above image if firebase is not there it wont able to fetch from firebase
but the thing is even there is an error 
i m getting config from firebase 

so somehow its working
