### ISSUE TITLE
🐛 [firebase_dynamic_links] Email sign-in deep link fails to be handled on iOS due to null utm parameter values

### ISSUE THREAD

**Issue by anni-tim** [firebase/flutterfire#10013]
## Bug report

I am using passwordless / email link sign-in with a custom domain on Android and iOS.

Generating an email link for sign-in works correctly on Android. Clicking on the link opens the app and the app is notified of the deep link by Firebase Dynamic Links (FDL).

On iOS the sign-in link is not passed onto the application by FDL. After debugging the native iOS code I can see the link is picked up as a universal link and is sent to the method channel handler for the FDL Flutter plugin. However the Flutter side fails with 'type 'Null' is not a subtype of type 'String' in type cast'.

Debugging shows that the iOS native plugin passes a dictionary with null values for utmParameters which fails on the Flutter side to be converted into a (not nullable) Map<String, String>.

As a workaround I am now generating my email sign-in links on the server-side and manually setting dummy UTM parameters so that the link parses correctly on iOS.

I believe a fix should be made on the Flutter side (in _getPendingDynamicLinkDataFromMap of method_channel_firebase_dynamic_links.dart) to allow null UTM values and/or on the iOS plugin side to prevent sending a dictionary with null utmParameter values.

The issue appears similar to this:
[7272](https://github.com/firebase/flutterfire/issues/7272)

### Steps to reproduce

I have not provided a full project to reproduce as the error is evident from the code and debug session output. If necessary an example project could be built using [7272](https://github.com/firebase/flutterfire/issues/7272).

### Expected behavior

The email link should be propagated to the application on iOS to allow the email link sign-in to complete.

### Sample project

See [7272](https://github.com/firebase/flutterfire/issues/7272)

---

## Additional context

Screenshots of the debugging output attached.
![Screenshot 2022-11-29 at 12 34 56 pm](https://user-images.githubusercontent.com/104549346/204417754-9dd568a9-6dae-4644-bc08-999a93b0460d.png)
![Screenshot 2022-11-29 at 12 39 27 pm](https://user-images.githubusercontent.com/104549346/204417781-7e3a755b-f60f-4d1f-aeb4-0101bbcfbe98.png)

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.0.1 22A400 darwin-arm, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.3)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.18.5
Flutter SDK 3.3.9
xxx

dependencies:
- cloud_functions 4.0.5 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- firebase_analytics 10.0.6 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 4.1.4 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.3.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 3.0.6 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_dynamic_links 5.0.6 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_messaging 14.1.2 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_bloc 8.1.1 [flutter bloc provider]
- flutter_local_notifications 12.0.4 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_native_timezone 2.0.0 [flutter_web_plugins flutter js]
- flutter_stripe 6.0.0 [flutter stripe_android stripe_ios stripe_platform_interface]
- flutter_svg 1.1.6 [flutter meta path_drawing vector_math xml]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]
- mocktail 0.3.0 [collection matcher test]


```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the report @anni-tim 
There's a similar [issue](https://github.com/firebase/flutterfire/issues/8954) open, but for Android. Please check that and see if underlying comments helps in your case.

**Comment by guerraglucas** [comment]
I'm having the same problem. I'm using a dynamic link for custom reset password for Firebase Auth.
My dynamic link doesn't have UTM parameters configured neither on firebase console or code, so it returns the same error as @anni-tim .
Android works fine.

**Comment by anni-tim** [comment]
Hey @darshankawar, the issue you have referenced does not seem to be related.

To be clear, I am not setting any UTM parameters in the link but the FDL iOS plugin is creating a dictionary with null values for the UTM parameters e.g. "utm_term" -> null. This dictionary then fails to be cast into a Dart Map<String, String> inside _getPendingDynamicLinkDataFromMap of method_channel_firebase_dynamic_links.dart.

I can fix the issue server side by appending dummy UTM parameters to the link, which avoids the iOS plugin sending null values in the UTM parameter dictionary (it correctly parses the dummy values so the dictionary can be converted to Map<String, String>).

```
    const actionLink = await admin.auth().generateSignInWithEmailLink(email, actionCodeSettings);

    // Add dummy utmParameters to ensure iOS can process the deep link
    const fixedLink = `${actionLink}&utm_campaign=a&utm_medium=a&utm_source=login&utm_term=a&utm_content=a`
```

Looks like a pretty simple bug to me. Either prevent the iOS side sending a null valued dictionary where there are no UTM parameters in the link. Or update the _getPendingDynamicLinkDataFromMap parsing of the iOS method callback to filter out null values before converting to Map<String, String>.

Hope that helps provide a bit more context.

**Comment by darshankawar** [comment]
Thanks for the feedback @anni-tim.
Based on the explaination above and in `additional context` section, I am keeping this issue open and for team's attention and insights on possible expected behavior / resolution.

/cc @russellwheatley

**Comment by Lyokone** [comment]
Thanks for the report, I'm investigating it

**Comment by anni-tim** [comment]
Great thank you!

Also not sure if this helps, but noticed this pull request may have changed the behaviour on the iOS side (see changes to FIRDynamicLinks.m)?
[10413](https://github.com/firebase/firebase-ios-sdk/pull/10413/files)
