### ISSUE TITLE
[firebase_messaging] Please update the plugin example regarding its dependencies

### ISSUE THREAD

**Issue by rivella50** [firebase/flutterfire#10030]
Regarding the package [flutter_local_notifications](https://pub.dev/packages/flutter_local_notifications) in the plugin example the used version is quite old (9.7.0), and there have been made quite some changes there.
I kindly ask you to update the example app and use the most recent version of the mentioned plugin (currently 12.0.4).
Thank you very much.

**Comment by SaumyaBhushan** [comment]
Hi @rivella50 Can I work on this issue ?

**Comment by rivella50** [comment]
@SaumyaBhushan Sure, give it a try.

**Comment by SaumyaBhushan** [comment]
Hi @rivella50 ! I think it should be done by someone who has some knowledge about flutter code . I am new to it .

**Comment by rivella50** [comment]
@SaumyaBhushan Sorry, i don't have time to guide to, that's why i opened the ticket.

**Comment by Lyokone** [comment]
Hey 👋 I'll update the code, you can check the PR to learn from it then ;)

**Comment by rivella50** [comment]
@Lyokone That's great news, thank you very much.

**Comment by SaumyaBhushan** [comment]
Sure @Lyokone . Thanks a lot.

**Comment by Lyokone** [comment]
@rivella50 The demo app runs fine by upgrading the `pubspec.yaml` to 12.0.4. 
They were no breaking changes to the function we use. Did you expect something special?

**Comment by rivella50** [comment]
@Lyokone Did you test on Android? When i check the Android setup the demo app misses at least
- introduce desugaring
- update to com.android.tools.build:gradle:4.2.2

**Comment by Lyokone** [comment]
I've tried it on Android, could receive messages properly and display them through FLN.
I'll update the dependencies 👍

**Comment by rivella50** [comment]
@Lyokone Hmmmm, interesting. I even didn't try since i was so sure that it wouldn't work.
I'll wait for your PR and then try in my own project. Thanks a lot.

**Comment by Lyokone** [comment]
> [desugaring](https://developer.android.com/studio/releases/gradle-plugin#j8-library-desugaring) to support scheduled notifications

Since we don't schedule notifications I don't think it matters a lot for the demo plugin

**Comment by rivella50** [comment]
@Lyokone Seems to work fine, except that the registered `FirebaseMessaging.onMessageOpenedApp` listener is not called when i click on a created notification if the app is in foreground mode.
