### ISSUE TITLE
🐛 [firebase_messaging] `onRefreshToken` doesn't invoke when the app opens for the first time.  

### ISSUE THREAD

**Issue by iLoveDocs** [firebase/flutterfire#10043]
## Bug report

When the app is opened for the first time, the `onRefreshToken` callback doesn't get called. 

### Steps to reproduce

Uninstall the app (if it is already installed) and run the following code. 
The `print` statement doesn't print the token. 

```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  FirebaseMessaging.instance.onTokenRefresh.listen((token) {
    print('token = $token'); // Doesn't print
  });

  runApp(...);
}
```

### Expected behavior

The `onRefreshToken` should fire when the app opens (launches) for the first time. 

### Version: 

```
firebase_messaging: ^14.0.3
```

### Additional context: 

I have this code in a java file and this does print the new token: 

```java
public class MessagingService extends FirebaseMessagingService {
    @Override
    public void onNewToken(@NonNull String s) {
        super.onNewToken(s);
        Log.i("Tag", "New FCM token = " + s);
    }
}
```

**Comment by darshankawar** [comment]
@iLoveDocs 
On what platform are you seeing this behavior ?
Can you also provide `flutter doctor -v` and verify the same using latest plugin version ?

**Comment by darshankawar** [comment]
Thanks for the update. Keeping this issue open and labeling based on the report.

**Comment by MichealReed** [comment]
Also seeing this on `firebase_messaging: ^14.5.0` platform web. I have to use getToken on each run and update the token in my db as it is different than the previous.
