### ISSUE TITLE
🐛 [firebase_ui_oauth_apple] Displayname is null

### ISSUE THREAD

**Issue by kovilevi98** [firebase/flutterfire#10050]
## Bug report

I am using the new flutterfire version for signing into my app. I have an issue with the apple login. (firebase_ui_oauth_apple: ^1.0.8)
I need to get the user's name after the registration because without that the Appstore is not allowed to upload the new release.
I saw in the source code that the provider contains the necessary scopes, however FirebaseAuth.instance.currentUser.displayname is always null. With the GoogleProvider() everything is working well and I can get the display name.
My code:

### Steps to reproduce

```
 return AuthFlowBuilder<OAuthController>(
      provider: AppleProvider(),
        listener: (oldState, state, controller) {
          if (state is SignedIn) {
              //HERE THE state.user.displayName IS EMPTY
              //AFTER THE FirebaseAuth.instance.currentUser.display name IS ALSO EMPTY
        },
        builder: (context, state, controller, _) {
          return ElevatedButton(
              style: AppThemes.BUTTON_FULL_WIDTH_THEME.copyWith(
                  backgroundColor: MaterialStateProperty.all(Colors.white)
              ),
              onPressed: (){
                controller.signIn(Platform.isAndroid ? TargetPlatform.android : TargetPlatform.iOS);
              },
              child: Row(
                children: [
                  Images.image(Images.ICON_LOGIN_APPLE,width: 30),
                  Expanded(
                      child: Center(
                          child: state is SigningIn ?
                          const SizedBox(
                            width: 17,
                            height: 17,
                            child: CircularProgressIndicator(
                              strokeWidth: 2,
                              valueColor: AlwaysStoppedAnimation<Color?>(AppColors.BLUE_DARK),
                            ),
                          )
                        :
                          Text(AppLocalizations.of(context)!.login_apple,style: const TextStyle(color: Colors.black)))),
                ],
              )
          );
        }
    );
```

### Expected behavior

It should contain the display name, because without that I can not upload the app for the appstore

**Comment by darshankawar** [comment]
Thanks for the report @kovilevi98 
This is an issue with underlying iOS SDK for which you can follow-up in https://github.com/firebase/firebase-ios-sdk/issues/4393 for further updates. Since `firebase_ui_oauth_apple` or `firebase_auth` plugins are wrappers around native SDKs, the existing functionality is leveraged and we are not doing anything at client side to display the user details.
Closing from here.

**Comment by ben55j** [comment]
Hello @darshankawar, Is there any work around for getting the **displayName** of the User ?
