### ISSUE TITLE
🐛 [firebase_auth] Apple sign in throws "unknown" exception when user cancels the sign in

### ISSUE THREAD

**Issue by rich-j** [firebase/flutterfire#10055]
## Bug report

Apple sign in on iOS opens a separate dialog for processing the user authenticating with Apple sign in. The user can choose to cancel the sign in by clicking off of the dialog or clicking the dialog's "X" button. FlutterFire returns a `FirebaseAuthException` with `code` set to "unknown". Since cancelling is a valid user choice we would choose to catch this exception and silently take no action - effectively ignoring this "unknown" exception. However, it appears that the "unknown" exception can occur in many other cases that should not be ignored.

### Steps to reproduce

```dart
    try {
      final appleProvider = AppleAuthProvider();
      return firebaseAuth.signInWithProvider(appleProvider);
    } on FirebaseAuthException catch (ex, stackTrace) {
      if (ex.code == "unknown") return;
      rethrow;
    }
```

Running on an iOS simulator when the user cancels the above sign in, the console displays:
```
Sign in with Apple errored: Error Domain=com.apple.AuthenticationServices.AuthorizationError Code=1001 "(null)"
FLTFirebaseAuth: An error occurred while calling method Auth#signInWithProvider, errorOrNil => {
}
```

and the exception thrown is `FirebaseAuthException` with code "unknown" that when printed gives `[firebase_auth/unknown] An unknown error has occurred.`

### Expected behavior

We should be able to know when the user has taken a valid user action to cancel the sign in.

One way to know would be to have the `signInWithProvider` return a `Future<UserCredential?>` <-- note nullable. A `null` would indicate that no sign in was made - i.e. cancel. Yes, this would require an API change.

Another option would be to return an explicit cancel exception such as an `FirebaseAuthException` code of "cancel".

This same issue is present on other methods such as `signInWithPopup`.

## Additional context

Looking at the underlying platform code the catch-all exception code that is returned is "unknown" (also capitalized "Unknown" is also sometimes returned which could be a separate issue). We would generally choose that these "unknown" exceptions at least be logged and investigated. But we shouldn't need to waste our time investigating valid user cancel choices.

### Flutter dependencies

  firebase_auth: ^4.1.5

**Comment by darshankawar** [comment]
Thanks for the report. I am able to replicate it using plugin example running on iOS device. The console error log is below:

<details>
<summary> console error log </summary>

```

Syncing files to device Darshan's iphone...
[core] Authorization failed: Error Domain=AKAuthenticationError Code=-7003 "(null)" UserInfo={AKClientBundleID=com.nevercode.triage}
Sign in with Apple errored: Error Domain=com.apple.AuthenticationServices.AuthorizationError Code=1001 "(null)"
FLTFirebaseAuth: An error occurred while calling method Auth#signInWithProvider, errorOrNil => {
}
flutter: Error [firebase_auth/unknown] An unknown error has occurred. 
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
<asynchronous suspension>
#2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:518:43)
<asynchronous suspension>
#3      MethodChannelFirebaseAuth.signInWithProvider (package:firebase_auth_platform_interface/src/method_channel/method_channel_firebase_auth.dart:590:12)
<asynchronous suspension>
#4      FirebaseAuth.signInWithProvider (package:firebase_auth/src/firebase_auth.dart:648:9)
<asynchronous suspension>
#5      main (package:triage/main.dart:38:39)
<asynchronous suspension>
fopen failed for data file: errno = 2 (No such file or directory)
Errors found! Invalidating cache...
fopen failed for data file: errno = 2 (No such file or directory)
Errors found! Invalidating cache...
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service

```

</details>

**Comment by Lyokone** [comment]
@rich-j 
For Desktop you can check how it's done by the firebase_ui package: `packages/firebase_ui_oauth/lib/src/platform_oauth_sign_in.dart`

I've opened a PR to have more details on iOS

**Comment by rich-j** [comment]
@Lyokone the `ui` package that you reference shows a sign in call for the desktop that explicitly returns `null` when the user cancelled. For our Google sign in we have similar code since the call to `GoogleSignIn().signIn()` explicitly returns `Future<GoogleSignInAccount?>` that returns a `null` when the user cancels. Also note the Google sign in implementation has two parts: get Google authentication (`null` on cancel), then call Firebase auth `signInWithCredential`. (Facebook is also 2 part)

[Apple sign in (doc link)](https://firebase.google.com/docs/auth/flutter/federated-auth#apple) is a single call to `.signInWithProvider()` or `.signInWithPopup()` that does not return a `null` on user cancel. A user cancel instead throws an `unknown` exception that also appears to be thrown under more critical error conditions. The documentation suggests that other providers (Microsoft, Twitter, GitHub, ...) and platforms (iOS, Android, Web) will also have this issue.
