### ISSUE TITLE
🐛 [firebase_dynamic_links] problem with targetSdkVersion 33

### ISSUE THREAD

**Issue by flenairMacif** [firebase/flutterfire#10062]
## Bug report

**Describe the bug**
Hello, i'm using flutter 3.0.7 with that dependencies to create a dynamic link
  firebase_core: 2.3.0
  firebase_dynamic_links: 5.0.7

when i click on my dynamic link, i have this error and nothing happened:

```
START u0 {act=com.google.firebase.dynamiclinks.VIEW_DYNAMIC_LINK cat=[android.intent.category.BROWSABLE] dat=https://xxx.page.link/... flg=0x14000000 pkg=com.google.android.gms cmp=com.google.android.gms/.appinvite.AppInviteAcceptInvitationActivity (has extras)} from uid 10195
15:24:56.131  W  Intent does not match component's intent filter: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] dat=https://xxx.page.link/... flg=0x14000000 pkg=com.macif.mobile.application.android.ent cmp=com.macif.mobile.application.android.ent/com.macif.mobile.application.android.MainActivity (has extras) }
15:24:56.131  W  Access blocked: ComponentInfo{com.macif.mobile.application.android.ent/com.macif.mobile.application.android.MainActivity}
15:24:56.131  I  START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] dat=https://xxx.page.link/... flg=0x14000000 pkg=com.macif.mobile.application.android.ent cmp=com.macif.mobile.application.android.ent/com.macif.mobile.application.android.MainActivity (has extras)} from uid 10161
15:24:56.136  E  Activity not found to handle Intent action [CONTEXT service_id=77 ]
                 android.content.ActivityNotFoundException: Unable to find explicit activity class {com.macif.mobile.application.android.ent/com.macif.mobile.application.android.MainActivity}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-filter>?
```

I found this issue https://github.com/firebase/firebase-android-sdk/issues/4198 and i try to downgrade the targetSdkVersion from 33 to 32, and now it works perfectly.

Is there a problem with targetSdkVersion?

Thanks

**Comment by darshankawar** [comment]
Thanks for the report @flenairMacif 
Can you try [this](https://github.com/firebase/flutterfire/issues/9465#issuecomment-1310093556) solution and see if it works in your case ?

**Comment by chenop** [comment]
I had this issue - my mistake was to upgrade the targetSdkVersion to 33 but I left:
compileSdkVersion = 31

Fixing to:
compileSdkVersion = 33
has resolved the issue

**Comment by Letalus** [comment]
I also experienced this issue, when upgrading the permission_handler package to 10.2.0 where I had to upgrade the targetSdkVersion and compileSkdVersion to 33. Then suddendly the deep linking didnt work anymore and I had to deactivate it entirely (clients decision). It was working perfectly fine on version 32 though, yet I cant turn it back because version 33 is needed for the permission_handler package, otherwise the permissions wont work anymore.

Tbh. it is weird, that not more people have experienced this issue. Could be that right now alot of apps deep links are not working correctly with the latest 33 version.

**Comment by flenairMacif** [comment]
Hello,

I added this with targetSdkVersion=33
<img width="668" alt="image" src="https://user-images.githubusercontent.com/48446573/209638631-70181025-15bd-4dd5-8e0b-ac45e6405e7f.png">

And i still have the problem

Logcat:

START u0 {act=android.intent.action.VIEW cat=[android.intent.category.BROWSABLE] dat=https://macifmobiappxxx.page.link/... flg=0x90400 (has extras)} from uid 10213
09:36:55.099  I  START u0 {act=android.intent.action.VIEW dat=https://macifmobiappxxx.page.link/... pkg=com.android.chrome cmp=com.android.chrome/com.google.android.apps.chrome.IntentDispatcher (has extras)} from uid 10213
09:36:55.167  I  START u0 {act=android.intent.action.VIEW dat=https://macifmobiappxxx.page.link/... flg=0x800000 pkg=com.android.chrome cmp=com.android.chrome/org.chromium.chrome.browser.customtabs.CustomTabActivity (has extras)} from uid 10195
09:36:55.477  I  START u0 {act=com.google.firebase.dynamiclinks.VIEW_DYNAMIC_LINK cat=[android.intent.category.BROWSABLE] dat=https://macifmobiappxxx.page.link/... flg=0x14000000 pkg=com.google.android.gms cmp=com.google.android.gms/.appinvite.AppInviteAcceptInvitationActivity (has extras)} from uid 10195
09:36:55.951  W  Intent does not match component's intent filter: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] dat=https://macifmobiappxxx.page.link/... flg=0x14000000 pkg=com.macif.mobile.application.android.ent cmp=com.macif.mobile.application.android.ent/com.macif.mobile.application.android.MainActivity (has extras) }
09:36:55.951  W  Access blocked: ComponentInfo{com.macif.mobile.application.android.ent/com.macif.mobile.application.android.MainActivity}
09:36:55.951  I  START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] dat=https://macifmobiappxxxpage.link/... flg=0x14000000 pkg=com.macif.mobile.application.android.ent cmp=com.macif.mobile.application.android.ent/com.macif.mobile.application.android.MainActivity (has extras)} from uid 10161
09:36:55.952  E  Activity not found to handle Intent action [CONTEXT service_id=77 ]
                 android.content.ActivityNotFoundException: Unable to find explicit activity class {com.macif.mobile.application.android.ent/com.macif.mobile.application.android.MainActivity}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-filter>?
                 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2197)
                 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1839)
                 	at android.app.Activity.startActivityForResult(Activity.java:5471)

**Comment by chenop** [comment]
@flenairMacif Have you changed also `compileSdkVersion = 33`?

**Comment by flenairMacif** [comment]
@chenop yes
<img width="694" alt="image" src="https://user-images.githubusercontent.com/48446573/209640340-95199515-281d-43a8-8ad4-b20175a9edc5.png">

**Comment by chenop** [comment]
@flenairMacif Sorry dont see it in the image

**Comment by flenairMacif** [comment]
@chenop 
defaultConfig {
        applicationId "com.xxx.xxx.application.android"
        minSdkVersion 26
        targetSdkVersion 33
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }

**Comment by chenop** [comment]
@flenairMacif we are miss communicating :-)
Where is compileSdkVersion?

**Comment by flenairMacif** [comment]
oups sorry @chenop 
android {
    compileSdkVersion 33

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

**Comment by darshankawar** [comment]
@flenairMacif 
I think this probably needs to be reported in native Firebase sdk as already did here: https://github.com/firebase/firebase-android-sdk/issues/4198. If you are still facing the issue after going through the comments / solution mentioned in that issue, I suggest to open a new issue in it for further resolution. Check also if [this](https://github.com/firebase/firebase-android-sdk/issues/4198#issuecomment-1278762724) solution mentioned in it works in your case or not.

**Comment by ArAmM7** [comment]
I have the same issue with an app I'm working on. Running the app on an API 33 emulator, when the url is launched from inside the app deep linking works fine, when the url is typed into chrome the circular loading thingy of Google Play Services starts and continues infinitely, opening the app manually after that triggers the deep linking functionality. 

P.S. I have AndroidManifest.xml setup like [this](https://github.com/firebase/flutterfire/pull/9879/files#diff-83a49d9d74fb383bd251db938499a7b7baf986e7b99dccb4d986f41bc08f0cafR35-R41)

**Comment by orestesgaolin** [comment]
We're also having this issue. 

After setting targetSdkVersion to 33 and handling the deep link a following exception can be seen in logcat:

```
Activity not found to handle Intent action [CONTEXT service_id=77 ]
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.makevisible.visible.tst/com.makevisible.visible.MainActivity}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-filter>?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2171)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1805)
	at android.app.Activity.startActivityForResult(Activity.java:5583)
	at hai.platform_startActivityForResult(:com.google.android.gms@225014045@22.50.14 (190408-499278674):2)
	at hah.startActivityForResult(:com.google.android.gms@225014045@22.50.14 (190408-499278674):2)
	at com.google.android.chimera.android.Activity.startActivityForResult(:com.google.android.gms@225014045@22.50.14 (190408-499278674):2)
	at het.startActivityForResult(:com.google.android.gms@225014045@22.50.14 (190408-499278674):2)
	at hah.public_startActivityForResult(:com.google.android.gms@225014045@22.50.14 (190408-499278674):2)
	at hai.startActivityForResult(:com.google.android.gms@225014045@22.50.14 (190408-499278674):3)
	at android.app.Activity.startActivityForResult(Activity.java:5541)
	at hai.platform_startActivityForResult(:com.google.android.gms@225014045@22.50.14 (190408-499278674):1)
	at hah.startActivityForResult(:com.google.android.gms@225014045@22.50.14 (190408-499278674):1)
	at com.google.android.chimera.android.Activity.startActivityForResult(:com.google.android.gms@225014045@22.50.14 (190408-499278674):1)
	at het.startActivityForResult(:com.google.android.gms@225014045@22.50.14 (190408-499278674):1)
	at hah.public_startActivityForResult(:com.google.android.gms@225014045@22.50.14 (190408-499278674):1)
	at hai.startActivityForResult(:com.google.android.gms@225014045@22.50.14 (190408-499278674):1)
	at android.app.Activity.startActivity(Activity.java:6039)
	at hai.platform_startActivity(:com.google.android.gms@225014045@22.50.14 (190408-499278674):2)
	at hah.startActivity(:com.google.android.gms@225014045@22.50.14 (190408-499278674):2)
	at com.google.android.chimera.android.Activity.startActivity(:com.google.android.gms@225014045@22.50.14 (190408-499278674):2)
	at hah.public_startActivity(:com.google.android.gms@225014045@22.50.14 (190408-499278674):2)
	at hai.startActivity(:com.google.android.gms@225014045@22.50.14 (190408-499278674):3)
	at android.app.Activity.startActivity(Activity.java:6006)
	at hai.platform_startActivity(:com.google.android.gms@225014045@22.50.14 (190408-499278674):1)
	at hah.startActivity(:com.google.android.gms@225014045@22.50.14 (190408-499278674):1)
	at com.google.android.chimera.android.Activity.startActivity(:com.google.android.gms@225014045@22.50.14 (190408-499278674):1)
	at kkj.x(:com.google.android.gms@225014045@22.50.14 (190408-499278674):4)
	at kkl.onPostExecute(:com.google.android.gms@225014045@22.50.14 (190408-499278674):3)
	at android.os.AsyncTask.finish(AsyncTask.java:771)
	at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

build.gradle:

```
android {
    compileSdkVersion 33

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        applicationId "com.makevisible.visible"
        minSdkVersion 28
        targetSdkVersion 33
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
    }
...
```

When testing the deep link with App Links Assistant I'm getting a positive result:

![CleanShot 2023-01-16 at 18 00 01](https://user-images.githubusercontent.com/16854239/212731800-6eee43b6-42df-4bf6-b644-56f6b64ca925.png)


and this is the AndroidManifest.xml

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.makevisible.visible">

    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.FLASHLIGHT" />

    <uses-feature
        android:name="android.hardware.camera"
        android:required="false" />
    <uses-feature
        android:name="android.hardware.camera.flash"
        android:required="false" />

    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.POST_NOTIFICATIONS" />
    <uses-permission android:name="com.google.android.gms.permission.AD_ID" />

    <application
        android:name="${applicationName}"
        android:icon="@mipmap/ic_launcher"
        android:label="${appName}">
        <service
            android:name="com.example.bluetooth_foreground_service.BluetoothForegroundService"
            android:enabled="true"
            android:exported="true" />
        <activity
            android:name=".MainActivity"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:exported="true"
            android:hardwareAccelerated="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
                android:name="io.flutter.embedding.android.NormalTheme"
                android:resource="@style/NormalTheme" />

            <intent-filter
                android:autoVerify="true"
                android:label="Sign Up">
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <!-- Accepts URIs that ends with "*makevisible.com/sign-up -->
                <data
                    android:host="www.makevisible.com"
                    android:pathPrefix="/sign-up"
                    android:scheme="https" />
                <data
                    android:host="www.makevisible.com"
                    android:pathPrefix="/sign-up"
                    android:scheme="http" />
                <data
                    android:host="makevisible.com"
                    android:pathPrefix="/sign-up"
                    android:scheme="http" />
                <data
                    android:host="makevisible.com"
                    android:pathPrefix="/sign-up"
                    android:scheme="https" />
                <data
                    android:host="makevisibletest.page.link"
                    android:pathPrefix="/sign-up"
                    android:scheme="https" />
                <data
                    android:host="makevisible.page.link"
                    android:pathPrefix="/sign-up"
                    android:scheme="https" />
                <!-- note that the leading "/" is required for pathPrefix-->
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>

            <!-- An intent filter that is used to navigate from pacing alerts -->
            <intent-filter>
                <action android:name="com.makevisible.visible.pacing.alert" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
```

**Comment by orestesgaolin** [comment]
Found a solution. In my case I had to add a following intent using our Firebase PROJECT_ID without a `path` component despite my dynamic link to have a completely different structure:

```
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data android:scheme="https" android:host="PROJECT_ID.firebaseapp.com" />
            </intent-filter>
```

**Comment by jawwad-hassan89** [comment]
If anyone using Flutter is facing the issue of dynamic links not opening properly if the app is already running, even after applying the fixes on this thread, then change the launch mode `android:launchMode="singleTop"` to `android:launchMode="singleInstance"` in the `activity` tag. This will ensure that the Flutter activity is always instantiated as a new activity, even if it is already running.

```
<activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleInstance"
            ...
            android:windowSoftInputMode="adjustResize"
</activity>
```

**Comment by rsyd29** [comment]
> If anyone using Flutter is facing the issue of dynamic links not opening properly if the app is already running, even after applying the fixes on this thread, then change the launch mode `android:launchMode="singleTop"` to `android:launchMode="singleInstance"` in the `activity` tag. This will ensure that the Flutter activity is always instantiated as a new activity, even if it is already running.
> 
> ```
> <activity
>             android:name=".MainActivity"
>             android:exported="true"
>             android:launchMode="singleInstance"
>             ...
>             android:windowSoftInputMode="adjustResize"
> </activity>
> ```

@jawwad-hassan89 I have replaced what you did, but it still doesn't work. Still error `Activity not found to handle Intent action [CONTEXT service_id=77 ]`

**Comment by calvin-verticalscope** [comment]
> 

@orestesgaolin Thank you for the solution! It worked for me as well. Do you happen to know why that made it work again on API 33?

**Comment by flenairMacif** [comment]
I solved my problem.

My mistake was to put in AndroidManifest.xml a wrong android:host

i was putting urlPrefix/path instead of urlPrefix

WRONG:
 <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                **<data android:host="urlprefix.page.link/path" android:scheme="https"/>**
 </intent-filter>

CORRECT:
 <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                **<data android:host="urlprefix.page.link" android:scheme="https"/>**
 </intent-filter>

**Comment by darshankawar** [comment]
Thanks for the update. Closing this as resolved based on above comment.

**Comment by vineelk8** [comment]
The below solution worked for me in react native.

[#4198](https://github.com/firebase/firebase-android-sdk/issues/4198#issuecomment-1278762724)

Till Android 12 without the intent-filter after clicking on the dynamic link, it is navigating back to the app. Since android 13 after clicking on the link, it is not navigating. With the above changes, the issue got fixed.

We need to keep the domain URL www.youtube.com in the host instead of youtube.page.link.
