### ISSUE TITLE
🐛 [firebase_app_check] App check is not working with cloud functions, Error: Unauthenticated

### ISSUE THREAD

**Issue by Patrick386** [firebase/flutterfire#10070]
Flutter Web: 
 - App check setup
 - 
<img width="954" alt="스크린샷 2022-12-08 오전 12 16 44" src="https://user-images.githubusercontent.com/49754877/206217811-3af26fe8-9556-476b-b758-1f19a7cdf25a.png">
<img width="953" alt="스크린샷 2022-12-08 오전 12 16 25" src="https://user-images.githubusercontent.com/49754877/206217372-75a2605e-afc0-466a-9d10-b3f423d02c49.png">

**Cloud Functions**
```
exports.getConfiguration = functions.region("asia-northeast3")
    .runWith({enforceAppCheck: true})
    .https.onCall(async(data, context) => {
        let accountData: any;
        let accountSettingsData: any;
        let systemSettingsData: any;
        // context.app will be undefined if the request doesn't include an
        // App Check token. (If the request includes an invalid App Check
        // token, the request will be rejected with HTTP error 401.)
        if (context.app == undefined) {
            throw new functions.https.HttpsError(
                'failed-precondition',
                'The function must be called from an App Check verified app.');
        }

.....
});

**Package.json**
  "dependencies": {
    "algoliasearch": "^4.14.2",
    "firebase-admin": "^11.3.0",
    "firebase-functions": "^4.1.0"
  },
```

**Flutter main**
```
Future<void> main() async {

  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  // **AppCheck**
  await FirebaseAppCheck.instance.activate(
    webRecaptchaSiteKey: '6LdDe2dBBBBCCCNfGbT2MYY2A4ADFAtsj-5hvMyj5',
    // Default provider for Android is the Play Integrity provider.
    // You can use the "AndroidProvider" enum to choose
    // your preferred provider. Choose from:
    // 1. debug provider
    // 2. safety net provider
    // 3. play integrity provider
    androidProvider: AndroidProvider.debug,
  );

  runApp(ProviderScope(child: MyApp()));
}
```

**Error output**
  INFO: Function Error: 
     code: unauthenticated 
     details: null 
     message: Unauthenticated

cloud function debug:

```
{
insertId: "b44ou9fo3x2r6"
labels: {
execution_id: "c1hql56hpurk"
}
logName: "projects/pronto-app-8880/logs/cloudfunctions.googleapis.com%2Fcloud-functions"
receiveTimestamp: "2022-12-07T15:32:22.963623027Z"
resource: {
labels: {3}
type: "cloud_function"
}
severity: "DEBUG"
textPayload: "Function execution took 331 ms. Finished with status code: 401"
timestamp: "2022-12-07T15:32:22.668858179Z"
trace: "projects/pronto-app-8880/traces/2464ac13dee34acc9ac1352b9fe9f1b7"
}
```

**Comment by darshankawar** [comment]
Thanks for the report @Patrick386 
Have you enabled the debug token in index.html as also mentioned [here](https://github.com/firebase/flutterfire/issues/9369#issuecomment-1219481968) and see if it helps in your case ?

**Comment by Patrick386** [comment]
> Thanks for the report @Patrick386 Have you enabled the debug token in index.html as also mentioned [here](https://github.com/firebase/flutterfire/issues/9369#issuecomment-1219481968) and see if it helps in your case ?

**I followed the instructions, but it still doesn't work.**

```
  const debugToken = '-----------------';
  const liveToken = '-----------------';
 await FirebaseAppCheck.instance.activate(
    webRecaptchaSiteKey: kReleaseMode ? liveToken : debugToken,
    androidProvider: AndroidProvider.debug,
  );
```

**Error message**
`Function Error:appCheck/fetch-status-error null AppCheck: Fetch server returned an HTTP error status. HTTP status: 403. .`

<img width="1501" alt="스크린샷 2022-12-08 오후 8 40 49" src="https://user-images.githubusercontent.com/49754877/206441757-741ce18c-c36e-4bad-9134-9cb9a276ce87.png">
<img width="973" alt="스크린샷 2022-12-08 오후 8 42 31" src="https://user-images.githubusercontent.com/49754877/206441856-79590cf5-4ed2-4a31-9aaf-082cf4f744c9.png">

**Comment by darshankawar** [comment]
> Function Error:appCheck/fetch-status-error null AppCheck: Fetch server returned an HTTP error status. HTTP status: 403. .

This I think indicates, the error could be coming from server itself and hence an unauthenticated error at the client side. I am not sure if this is actionable from here or from js side. Keeping this issue open for team's attention based on the report and error message being received.

**Comment by Patrick386** [comment]
> > Function Error:appCheck/fetch-status-error null AppCheck: Fetch server returned an HTTP error status. HTTP status: 403. .
> 
> This I think indicates, the error could be coming from server itself and hence an unauthenticated error at the client side. I am not sure if this is actionable from here or from js side. Keeping this issue open for team's attention based on the report and error message being received.
<img width="965" alt="스크린샷 2022-12-09 오후 9 00 58" src="https://user-images.githubusercontent.com/49754877/206700198-1d7bad27-b31a-4497-a5f3-636051ee157d.png">


I think I’ve tried everything I can for a while.
The biggest problem is that once you start this, you can‘t turn it around.
- **The option to initialize App check is required.**

The website went down due to an initial App Check error. So, I cannot proceed the development.

**Comment by Patrick386** [comment]
I am developing the Flutter web.

All the packages have been updated to the latest version, and I noticed that some of the auth property names have been changed during this process. I think 403 issues is because of that. 

Additionally, I looked it up and found that the app initialization (including AppCheck) was solved within index.html, not dart.
https://github.com/firebase/flutterfire/issues/6310

I tried again, but the 'Unauthenticated' error occured, and it was not the solution I wanted. 

Initializing in index.html is not what we want.

After deploying the app, it stopped during initialization of site execution.
What is the correct way to start app check on the Flutter web?

**Comment by darshankawar** [comment]
Check [this](https://firebase.google.com/docs/app-check/flutter/debug-provider#web) document and see if it helps.

**Comment by Patrick386** [comment]
> Check [this](https://firebase.google.com/docs/app-check/flutter/debug-provider#web) document and see if it helps.

Still having problems.
Error:  The function must be called from an App Check verified app.

index.html

```
  <script>self.FIREBASE_APPCHECK_DEBUG_TOKEN = "10205845-1965-4d3d-8a0b-c5cd46ee6a9d";</script>
  <script src="https://www.gstatic.com/firebasejs/8.10.0/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.10.0/firebase-functions.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.10.0/firebase-app-check.js"></script>
```

main.dart

```
Future<void> main() async { 
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  const debugToken = '10205845-1965-4d3d-8a0b-c5cd46ee6a9d';

  /// Recaptcha Site Key
  const liveToken = '-----------------------';

  await FirebaseAppCheck.instance.activate(   
      webRecaptchaSiteKey: kReleaseMode ? liveToken : debugToken,
      androidProvider: AndroidProvider.debug,
    );
....
}
```

cloud functions

```
exports.onCreateCompany = functions
    .region("asia-northeast3")
    .runWith({enforceAppCheck: true})
    .firestore.document(companiesDocPath)
    .onCreate(async (snapshot: FirebaseFirestore.DocumentSnapshot<FirebaseFirestore.DocumentData>, context: any) => {
        if (context.app == undefined) {
            throw new functions.https.HttpsError(
                'failed-precondition',
                'The function must be called from an App Check verified app.');
        }
        console.log(searchClient.listApiKeys());
        await saveCompanyDocumentInAlgolia(snapshot);
    });
```

Error logo
```
{
insertId: "639dcfe8000826f087581b7e"
labels: {2}
logName: "projects/pronto-app-8880/logs/cloudfunctions.googleapis.com%2Fcloud-functions"
receiveTimestamp: "2022-12-17T14:19:20.759942634Z"
resource: {2}
severity: "ERROR"
textPayload: "Error: The function must be called from an App Check verified app.
    at /workspace/lib/companies.js:39:15
    at cloudFunction (/workspace/node_modules/firebase-functions/lib/v1/cloud-functions.js:79:23)
    at /layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/function_wrappers.js:144:25
    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
timestamp: "2022-12-17T14:19:20.534256Z"
trace: "projects/pronto-app-8880/traces/490508c6131fb94c8c6e9bd20c5238f7"
}
```


package.json
```
{
  "name": "functions",
  "scripts": {
    "lint": "eslint --ext .js,.ts .",
    "build": "tsc",
    "build:watch": "tsc --watch",
    "serve": "npm run build && firebase emulators:start --only functions",
    "shell": "npm run build && firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "16"
  },
  "main": "lib/index.js",
  "dependencies": {
    "algoliasearch": "^4.14.2",
    "firebase-admin": "^11.3.0",
    "firebase-functions": "^4.1.1"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^5.12.0",
    "@typescript-eslint/parser": "^5.12.0",
    "eslint": "^8.9.0",
    "eslint-config-google": "^0.14.0",
    "eslint-plugin-import": "^2.25.4",
    "firebase-functions-test": "^0.2.0",
    "typescript": "^4.5.4"
  },
  "private": true
}
```

**Comment by Patrick386** [comment]
The problem appears to have been resolved.
I found out that function triggers do not need app check. I hope this part is described in the manual for first-time users.

In addition, for onCall, permission to call functions was required.(Identity and Access Management(IAM))
Thank you.
