### ISSUE TITLE
🐛 [firebase_app_check] Too many unverified requests

### ISSUE THREAD

**Issue by cnkygmr** [firebase/flutterfire#10084]
Too many unverified requests in Storage while Realtime Database and Cloud Firestore are normal?
I'm using Resize Images as a plugin, is that why?
It can't be unreasonable this high even if I use it

![bbbbbbbbbbbbb](https://user-images.githubusercontent.com/6883162/206723547-af5ee18f-669d-4b06-a322-b07f6a5c14e0.PNG)
![aaaaaaaaaaaaa](https://user-images.githubusercontent.com/6883162/206723550-02cf519e-d13a-4f6f-b30e-d46f360c9fac.PNG)

**Comment by darshankawar** [comment]
@cnkygmr 


> I'm using Resize Images as a plugin, is that why?

If you remove this, do you still get same behavior ?

Have you also enforced app check verification already per the [documentation](https://firebase.google.com/docs/app-check/flutter/default-providers#next_steps) ?

**Comment by cnkygmr** [comment]
@darshankawar 
I can't remove it in an app currently running live.
This is firebase own plugin so that's why I asked.

**Comment by cnkygmr** [comment]
@darshankawar 
How can I see where these queries are coming from?

**Comment by darshankawar** [comment]
> How can I see where these requests are coming from?

I am not completely sure about it. Is this for Android or iOS ? Can you take a look at [this](https://github.com/firebase/flutterfire/issues/9484) issue and see if it helps in your case ?

**Comment by cnkygmr** [comment]
@darshankawar 
There are 2 sides, both ios and android.
It occurred to me that after the photos are uploaded, I save their urls in the database and have it taken like that. Could this be the reason?

**Comment by darshankawar** [comment]
Can't tell for sure. If you can try to access those urls locally and see if it makes any difference to the requests.

**Comment by cnkygmr** [comment]
Has anyone tried it before?
Does it create an unverified request when you pull the urls registered to the database in the firebase appcheck feature?

**Comment by darshankawar** [comment]
I have not seen such issues / use case yet, but a concrete steps to replicate and code sample will be useful to analyze further and to make this issue actionable.

**Comment by cnkygmr** [comment]
```
taskSnapshot.ref.getDownloadURL().then((downloadUrl) {
   //Here I am registering the url to the database
 });
```

```
CachedNetworkImage(
    imageUrl: images),
```

I save to the database as above and display it.

**Comment by cnkygmr** [comment]
[https://firebase.google.com/docs/app-check/flutter/custom-resource#send_app_check_tokens_with_backend_requests](https://firebase.google.com/docs/app-check/flutter/custom-resource#send_app_check_tokens_with_backend_requests)

I'm also wondering if we should use appcheck tokens like this in urls?

**Comment by darshankawar** [comment]
Considering the fact that you are seeing many unverified requests, you may probably try using the appcheck token for the request in urls and see if it helps in your case.

**Comment by cnkygmr** [comment]
My main question here is that under normal conditions, when the url is fired from an application with appcheck token, shouldn't this request be valid?

After all, it has a standard.

Does it have to be valid or not?

**Comment by darshankawar** [comment]
I am unable to conclude anything from the discussion and details provided, so keeping this issue open and labeling for team's attention.

**Comment by cnkygmr** [comment]
> I am unable to conclude anything from the discussion and details provided, so keeping this issue open and labeling for team's attention.

I didn't understand what to do

**Comment by cnkygmr** [comment]
Does anyone know? Is appcheck unverifed when I take a file with the url given by the download url?

**Comment by russellwheatley** [comment]
@cnkygmr - are you still experiencing this issue?

**Comment by cnkygmr** [comment]
@russellwheatley I solved it by sending headers appCheckToken to CachedNetworkImage.
