### ISSUE TITLE
[📚] [cloud_firestore_odm] Document how to use transaction in the update method 

### ISSUE THREAD

**Issue by iLoveDocs** [firebase/flutterfire#10088]
If I want to use `transactionUpdate()` method, I need to provide a `Transaction` object, but there is no documentation on how to create this object. For example, this code doesn't compile: 

```dart
usersRef 
  .doc('foo_id')
  .transactionUpdate(
    transaction, // How to create this object? 
    name: 'John',
  );
```

I can create a `Transaction` object, using 

```dart
var transaction = FirebaseFirestore.instance.runTransaction((txn) async {
  return txn;  
});
``` 

but using this object doesn't work in the first code. Here's the [question on StackOverflow](https://stackoverflow.com/q/74715162/12483095).

**Comment by TarekkMA** [comment]
Moved to: https://github.com/FirebaseExtended/firestoreodm-flutter/issues/28
