### ISSUE TITLE
🐛 [firebase_in_app_messaging] Unable to receive the in-app-message after killing the application

### ISSUE THREAD

**Issue by anmolguptach** [firebase/flutterfire#10114]
## Bug report

**Describe the bug**
Unable to receive the in-app-message after killing the application in debug mode and release mode.

### Steps to reproduce

Step-1 Sending the in-app message through the firebase console
Step-2 when building the application for the first time the in-app-message is displayed
Step-3 closing the app
Step-4 Sending a new in-app message through the firebase console
Step-5 On building the app or re-opening the app the in-app message does not display.
Step-6 Uninstall the app  
Step-7 On building the app or re-opening the app the in-app message display.

### Expected behavior

Must receive an in-app message after the app is killed, in release mode.

**Comment by darshankawar** [comment]
Thanks for the report @anmolguptach 
I am not sure if the use case is valid for this plugin. Can you provide what exactly is the use case you are trying to achieve with this plugin ?
