### ISSUE TITLE
[📚] want to have firestore error handling page

### ISSUE THREAD

**Issue by hatano0x06** [firebase/flutterfire#10112]
I'm looking at this site.
https://firebase.google.com/docs/storage/flutter/handle-errors

But there doesn't seem to be an errorhandling page on fireStore
(Storage does).
https://firebase.google.com/docs/firestore

It is possible that my app is the cause of the problem, but I also experienced an inaccessibility problem around 11/10 and would like to address it if possible.

I would appreciate it if you could add documentation on how to artificially cause the error and how to handle the error.

**Comment by russellwheatley** [comment]
We don't have control over the Firestore documentation I'm afraid. Here is a list of exception codes for [android](https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/FirebaseFirestoreException.Code) and [ios](https://firebase.google.com/docs/reference/ios/firebasefirestore/api/reference/Enums/FIRFirestoreErrorCode).
