### ISSUE TITLE
🐛 [firebase_ui_firestore] on fetching scroll position is reset to start on Web

### ISSUE THREAD

**Issue by Ayman-Barghout** [firebase/flutterfire#10110]
## Bug report

**Describe the bug**
When using `FirestoreListView` on the web, the scroll position resets to the start when the view is fetching more results for the query.

### Steps to reproduce

1. Depend on `firebase_ui_firestore`
2. Build on the web.
4. Scroll a long list of data on the web.
5. Described bug is seen instead of it scrolling normally.

### Expected behavior

It should scroll normally and the scroll position doesn't reset to the start of the page.

**Comment by darshankawar** [comment]
Thanks for the report @Ayman-Barghout 
Can you provide a complete minimal reproducible code sample along with `flutter doctor -v` that shows the reported behavior ?
