### ISSUE TITLE
🐛 [cloud_functions] Is there no user id token in context ?

### ISSUE THREAD

**Issue by Patrick386** [firebase/flutterfire#10115]
Is there no user id token in context ?

**Client: ex**
  String token = await user.getIdToken();

**Server**

The context automagically [contains metadata](https://firebase.google.com/docs/reference/functions/providers_https_.callablecontext.html) about the request such as uid and token.

exports.getConfiguration = functions
    .runWith({enforceAppCheck: true})
    .https.onCall(async(data, context) => {

     const token = context.IdToken ???

.....
}

**Comment by darshankawar** [comment]
@Patrick386 
Can you take a look at [this](https://medium.com/super-declarative/dev-snack-testing-firebase-cloud-functions-with-user-id-tokens-83841d3f06c) article and see if it helps in your case ?
