### ISSUE TITLE
🐛 [firebase_analytics] Support dart only init on Android

### ISSUE THREAD

**Issue by JulianBissekkou** [firebase/flutterfire#10120]
## Bug report

**Describe the bug**

### Steps to reproduce

1. Setup dart only init for firebase and try to use the firebase analytics SDK
2. It provides an error that it doesn't work since the setup wasn't done on the native side.

### Expected behavior

Dart only init works for analytics as well.

---

## Additional context

This issue was already submitted but closed by updating the UI. I would like to keep this issue open and track progress of this specific integration since its needed for most of our apps.
Other issue: https://github.com/firebase/flutterfire/issues/7639

Can you maybe describe what needs to be done. I am open to contributing it. Should be one or multiple method channel calls? 🤔 

---

### Flutter doctor
Not relevant

---

### Flutter dependencies
Not relevant
---

**Comment by Lyokone** [comment]
@JulianBissekkou: The native Android and iOS SDK don't support manual initialization. To add support to dart-only init, we would need modifications in the native SDK.

**Comment by JulianBissekkou** [comment]
Correct me if I am wrong, but iOS should work when looking at the documentation PR that was used to close the issue.
PR: https://github.com/firebase/flutterfire/pull/7745/files
Table: 
<img width="462" alt="image" src="https://user-images.githubusercontent.com/36447137/207821054-efb82db5-908a-409e-a265-59d8edec6a1f.png">

I think this is the corresponding android issue that we are waiting for to implement support for dart only init for analytics:
https://github.com/firebase/firebase-android-sdk/issues/66

**Comment by FarzaneGhb** [comment]
Any update on this?

**Comment by russellwheatley** [comment]
There are no plans to init Analytics from Dart as t requires major changes to how the native Firebase SDKs work. See this comment for details: https://github.com/invertase/flutterfire_cli/issues/14#issuecomment-1270781026
