### ISSUE TITLE
[📚] Guidance around topic subscription calls

### ISSUE THREAD

**Issue by madushans** [firebase/flutterfire#10125]
Hey I've noticed that calls to `subscribeToTopic` and `unsubscribeFromTopic` take a long time to complete. (the `Future`s they return take long). Calls to them when device is disconnected from the network usually never complete and sometimes until device is reconnected.

My questions around this is as below

1. Is it expected that application code `await`s these calls?
2. If multiple calls are made to these functions, does the library maintain the order they were called?
   - For example, if the application does not `await` these calls (i.e from a Settings page where the user may click through a lot of options and don't want to wait 45 seconds for each click or if the device is disconnected). In this case is the app expected to wait before the next call?
   - Another example is if the app wants to "reset" the subscriptions with unsubscibing from a list of subs, then subscribing again for a subset. In this case should the app await all calls to `unsubscribeFromTopic` before calling `subscribeToTopic` or is the package handle ordering?
3. If the device is disconnected at the time of these calls and the app is terminated, are the calls made later when the app is initialized next time?

I'm thinking of "resetting" topic subscriptions in a background handler if a notification was received on a topic the app is not expecting. However since the calls take a long time, and background execution time is limited?, not sure if this is viable.

**Comment by madushans** [comment]
hey thanks @darshankawar. My use case is that I want to let the user customize the topics in a settings screen.

So when certain options are selected, the app 
- unsubscribes from all topics
- resubscribes to the selected topics

(Selecting some options mean the app should subscribe to multiple topics, but unsubscribe from  others.)


the issue is that if I do the following
```dart
   final unsubs = allTopics.map((name) => firebase.FirebaseMessaging.instance
        .unsubscribeFromTopic(name));
    await Future.wait(unsubs);
    
   final subs = selectedTopics.map((name) => firebase.FirebaseMessaging.instance
        .subscribeToTopic(name)); 
   await Future.wait(subs);
```

Few issues with this is that
- User could tap a few options in succession which means this code could be invoked again before the last call finished. Should I be blocking the user from selecting till the last call completes? Since there's no API that takes multiple topic names, I believe this has to do multiple HTTP calls?
- If the device is disconnected, the first call may not complete, so the subscribe calls are never reached? What is the recommended approach for this? Should the settings be locked until user is online? what if the user is online but the connection drops half way thru this function?
- if I remove the `await`s does the SDK keep track of the order of calls? i.e if unsubscribe was called on topic 1, 2 and 3, then subscribe is called on topic 1 4, 6, without `await`, I don't want subscribe to topic 1 to be called before unsubscribe on it.

Hope this clarifies it.

**Comment by madushans** [comment]
Thinking again, I think I can reduce the number of calls by excluding the topics to sub, from the list of ones that are unsubscribing, but the connectivity and race condition issues still wouldn't go away since user could select thru options available. (unless I block the options until prev calls finish, but device may not have a connection to complete those calls.)

**Comment by darshankawar** [comment]
Thanks for the update. I think the use case you mentioned and the issue with network, does not seem to be specific to flutterfire, so I am not sure if anything would be actionable from client side (ie, flutterfire). Do you by any chance can confirm if this behavior also occurs using native firebase api for android or iOS depending on the platform you are using ?

**Comment by madushans** [comment]
Sorry I haven't used the native ones. only the flutter one on Android. If the APIs are thin wrappers, likely the behavior is in the native SDK.

**Comment by darshankawar** [comment]
Yes, I think it is best to raise this in native sdk for further resolution. If you get directed here, please write in comments and I'll reopen it.
