### ISSUE TITLE
[📚] Cloud Messaging - Notifications: Android code sample broken

### ISSUE THREAD

**Issue by ksilz** [firebase/flutterfire#10128]
The ["Foreground Notifications" section](https://firebase.flutter.dev/docs/messaging/notifications#foreground-notifications) shows an Android code sample:

```dart
const AndroidNotificationChannel channel = AndroidNotificationChannel(
  'high_importance_channel', // id
  'High Importance Notifications', // title
  'This channel is used for important notifications.', // description
  importance: Importance.max,
);
```

With `flutter_local_notifications: 12.0.4`, this doesn't compile anymore: The third parameter `description` is now a named parameter:

![image](https://user-images.githubusercontent.com/1061209/208079448-9d4cfcdf-9a4d-42cf-9ea4-810794b43883.png)

Here's a version that does compile &mdash; with the named parameter for `description`:

```dart
const AndroidNotificationChannel channel = AndroidNotificationChannel(
  'high_importance_channel', // id
  'High Importance Notifications', // title
  description: 'This channel is used for important notifications.', // description
  importance: Importance.max,
);
```

**Comment by darshankawar** [comment]
Same as https://github.com/firebase/flutterfire/issues/10127#issuecomment-1354568629.
Please take a look at new domain for documentation help and see if examples mentioned in it works for you or not.
