### ISSUE TITLE
FlutterFirebaseDynamicLinksPlugin.java uses unchecked or unsafe operations.

### ISSUE THREAD

**Issue by rtessler** [firebase/flutterfire#10123]
## Bug report

while running: 

$ flutter build appbundle 

I get a warning:

Note: /Users/roberttessler/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_dynamic_links-5.0.8/android/src/main/java/io/flutter/plugins/firebase/dynamiclinks/FlutterFirebaseDynamicLinksPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

### Steps to reproduce

$ flutter build appbundle

### Expected behavior

no warning

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by darshankawar** [comment]
Same as https://github.com/firebase/flutterfire/issues/10122#issuecomment-1354488306
