### ISSUE TITLE
[📚] Flutterfire docs edit link broken

### ISSUE THREAD

**Issue by ksilz** [firebase/flutterfire#10127]
The ["Edit this page" link](https://github.com/FirebaseExtended/flutterfire/edit/master/docs/messaging/notifications.mdx) in [this part of the Flutterfire docs](https://firebase.flutter.dev/docs/messaging/notifications) is broken:

https://user-images.githubusercontent.com/1061209/208078647-ddc92170-ba09-43b7-8987-a380a7a7d5d0.mp4

**Comment by ksilz** [comment]
@darshankawar Ah, my bad. The problem is that an **individual** page doesn't show the link. So if I have a link to any page within the documentation, I wouldn't know it's archived. Is it possible to display the archive notice on **every** page?

**Comment by darshankawar** [comment]
Not sure if that will be done any time soon, considering that domain is now archived and your best bet is to refer the new domain I linked earlier.
With that being said, I am going ahead and closing this issue. If you disagree, write in comments and I'll reopen it.
