### ISSUE TITLE
[📚] Firebase Messaging - official example code trigger show notification twice

### ISSUE THREAD

**Issue by AhmedLSayed9** [firebase/flutterfire#10137]
The official `firebase messaging` example triggers `showFlutterNotification` maually in the background handler:
```
@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  await setupFlutterNotifications();
  showFlutterNotification(message);
  // If you're going to use other Firebase services in the background, such as Firestore,
  // make sure you call `initializeApp` before using other Firebase services.
  print('Handling a background message ${message.messageId}');
}
```

While the example is using `Notification message`, FCM is handling displaying the notification in the background/terminated automatically.

so, using `setupFlutterNotifications` and `showFlutterNotification` in the `firebaseMessagingBackgroundHandler` is not needed. Otherwise, using it leads to duplicate notification in background.

**Comment by darshankawar** [comment]
Thanks for the report. Keeping it open for team's attention and insights on current behavior.

**Comment by Lyokone** [comment]
On Android, sending a notification with title/body displays the notification automatically (which is not the case for iOS). We are using flutter_location_notification to display the notification manually.
That's why you see a duplicate notification. 

We keep it that way because it allows us to check if we haven't broken the automatic display of notifications on Android, but also that the background thread is still working.

**Comment by AhmedLSayed9** [comment]
> which is not the case for iOS

Are you sure about this?
The FlutterFire [doc](https://firebase.flutter.dev/docs/messaging/notifications/#displaying-notifications) says that when sending a notification message: `The default behavior on all platforms is to display a notification only when the app is in the background or terminated.`

I've tested it on both Android/iOS in background/terminated modes and the notification is displayed in all cases without the need to send it manually in the background handler.

If that's true, then displaying a notification manually in the handler is not needed at all (in case of notification message ofc) and it's just there for testing purposes, right?
