### ISSUE TITLE
🐛 [firebase_messaging] (iOS) Display translated with `Localizable.strings` notifications on the app Locale, not on the phone one.

### ISSUE THREAD

**Issue by awaik** [firebase/flutterfire#10147]
## Bug report

**Describe the bug**

If we localize messages with `Localizable.strings`, as suggested in the FCM documentation https://firebase.google.com/docs/cloud-messaging/flutter/receive#ios then we have a logical issue with displaying messages on the app language.

For example:

1. Phone language is English.
2. The app language is German.

When the app is opened we can handle the messages, translate the and display them when we need in German.

But, when the app is terminated, FCM uses a phone locale for taking the translation from the `Localizable.strings`.

**Comment by darshankawar** [comment]
Thanks for the report @awaik 
I am trying to replicate this use case using the plugin example wherein I set the `Localizable.strings` as below:

<img width="307" alt="Screenshot 2022-12-21 at 3 50 17 PM" src="https://user-images.githubusercontent.com/67046386/208881913-ef543e5c-2c36-4d4b-ad66-b0cf266a91ec.png">

Sending payload as below per documentation:

```
{
      "data": {
          "title_loc_key": "NOTIFICATION_TITLE",
          "body_loc_key": "NOTIFICATION_MESSAGE"
        },
      notification: {
        title: 'A great title',
        body: 'Great content',
      },
```

Per your steps to replicate, I need to set the app language to any non-English language which I am not sure how to achieve. If with above setup, I try to send notification, it does not show me the notification in localized language as I set above, so I am not completely sure how to make this case replicable. Probably you can provide a sample app or repo that we can use to verify this properly.

**Comment by awaik** [comment]
Hi!
Yes, that is the problem this issue about.

If we have an app with two locales (EN, DE) made with Flutter
https://docs.flutter.dev/development/accessibility-and-localization/internationalization

and:
1. In the app we set up DE as a default.
2. Phone default locale EN default.

The phone OS doesn't have info about the default app's locale and will display notifications in EN.

For example, if we use SWIFT in the iOS app we can create an extension, and before displaying notifications check the app's locale and display the correct one.

But how to achieve this with FCM & Flutter?

**Comment by darshankawar** [comment]
Thanks for the update. I am unsure as how to achieve localized notification, so keeping this issue open for team's attention and insights on expected behavior.

**Comment by Lyokone** [comment]
The only way to adapt to the user-selected language is to store the language in your server.

Then, you can send the proper notification, correctly translated from your server.
