### ISSUE TITLE
🐛 [firebase_messaging] FirebaseMessaging.onMessageOpenedApp.listen((message){} triggering more than once

### ISSUE THREAD

**Issue by irvine5k** [firebase/flutterfire#10150]
## Bug report

**Describe the bug**
This relates to #7243 

When FirebaseMessaging.onMessageOpenedApp.listen is called more than once, the registered callback will be triggered more than once.

If it's the intended behavior, maybe this behavior deserves mention in the documentation.

### Steps to reproduce

I couldn't reproduce the bug in debug mode on Android, so I'd recommend reproducing it on iOS. 

Steps to reproduce the behavior (iOS):

1. Call FirebaseMessaging.onMessageOpenedApp.listen(print) or FirebaseMessaging.onMessage.listen(print) twice in the code.
2. Open a notification.
3. See the message printed twice.

### Expected behavior

If the aforementioned behavior it's intended, I think would be good to see it in the documentation.

## Additional context

We call `FirebaseMessaging.onMessageOpenedApp.listen()` in the home screen's` initState(),` after the user authentication, there are some cases where the home is rebuilt, which retriggers the `initState()`. This scenario ended up in multiple calls to the registered onMessageOpenedApp's callback after clicking on the push notification.

---

### Flutter doctor

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale en-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2)
[✓] IntelliJ IDEA Community Edition (version 2022.1)
[✓] IntelliJ IDEA Community Edition (version 2022.2.1)
[✓] IntelliJ IDEA Community Edition (version 2022.2)
[✓] VS Code (version 1.73.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
firebase_messaging: ^14.0.4
flutter_local_notifications: ^10.0.0-dev.14
```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the report @irvine5k 
I do see the method printing the log twice as below:

```
flutter: Handling a background message 1671618785853095
flutter: A new onMessageOpenedApp event was published!
flutter: A new onMessageOpenedApp event was published!
```

After changing the code as below:

```
FirebaseMessaging.onMessageOpenedApp.listen((RemoteMessage message) {
      print('A new onMessageOpenedApp event was published!');
      print('A new onMessageOpenedApp event was published!');
      Navigator.pushNamed(
        context,
        '/message',
        arguments: MessageArguments(message, true),
      );
    });
```

Can you check [this](https://github.com/firebase/flutterfire/issues/10137#issuecomment-1359065385) comment from team member and see if it helps to know why it triggers twice ?

**Comment by irvine5k** [comment]
@darshankawar 

It was an interesting read, thanks for sharing it but I don't think it has a direct relationship with what I brought up.

I don't receive duplicated push notifications, only the handler is called multiple times. 

In my case, if the method FirebaseMessaging.onMessageOpenedApp.listen(print) is called N times, clicking on the notification will lead to N printed messages. So, if I have a navigation triggered by a notification, I'll navigate multiple times to the same screen.

Sorry if it's an obvious behavior but I think it deserves a warning in the method documentation.

**Comment by darshankawar** [comment]
Thanks for the feedback. I will keep this issue open for team's attention on expected behavior or this need to be added in the docs.

**Comment by Lyokone** [comment]
Hello @irvine5k,
If you are using `onMessageOpenedApp.listen` multiple times, you are listening to the same stream multiple times.

Being a static method returning a Stream, I don't think we need to say that it's the same stream in the documentation. 
When using a stream with `listen` in a Widget that could be rebuilt, you should cancel the StreamSubscription on `dispose`.
