### ISSUE TITLE
bug on onBackgroundMessage for android 12 & 13

### ISSUE THREAD

**Issue by kimalphaville** [firebase/flutterfire#10161]
Devices: 
Android 11 = Working
Android 12 = Not working
Android 13 = Not working

i deffinitely followed this step on onBackgroundMessage 

https://firebase.flutter.dev/docs/messaging/usage/

It is working well in development mode. 
however it DOES NOT trigger in release build.

Dev/Debug mode = Working
Release Mode = Not Working (Background handler is not invoking)

**Comment by darshankawar** [comment]
@kimalphaville 


> https://firebase.flutter.dev/docs/messaging/usage/

This link is not updated documentation to follow, as it has been archived. You should follow https://firebase.google.com/docs/cloud-messaging/flutter/client henceforth.



> Android 12 = Not working
> Android 13 = Not working

Have you set `targetSdkVersion` and `compileSdkVersion` to `33` and `android:exported="true"` property in app manifest ?
Also, make sure you are using the annotation as mentioned below:

https://github.com/firebase/flutterfire/blob/4289881f388f0751876400a49ae38d9603128f68/packages/firebase_messaging/firebase_messaging/example/lib/main.dart#L45
