### ISSUE TITLE
Firebase Windows doesn't work well 

### ISSUE THREAD

**Issue by seifibrahim32** [firebase/flutterfire#10171]
Firebase doesn't work on Desktop Windows well

**Comment by X-Wei** [comment]
check https://github.com/invertase/flutterfire_desktop?

**Comment by darshankawar** [comment]
@seifibrahim32 
What issues are you facing while running on windows desktop ? Can you provide more details including error log, UI glitches along with your `flutter doctor -v` and `pubspec.yaml` ?

**Comment by marb2000** [comment]
Thanks for opening the request. **Unfortunately, Firebase does not have official Windows desktop support for production applications. Consequently, there is no guarantee that the API set (in this case, the Flutter for Firebase SDK) will work in this scenario.**

We encourage you to vote on [Windows/Linux Support Feature Request](https://github.com/firebase/flutterfire/discussions/5557) to let our team know that your app requires it, so we can prioritize work accordingly. Sharing details about your scenario (e.g., which Firebase products need desktop support) will also help us prioritize products. Given the current engineering plan, we do not plan to invest in this during the first half of 2023 (we will review the engineering plan again after that).

In the meantime, you can use other open-source projects (like [Invertase's FlutterFire Desktop](https://github.com/invertase/flutterfire_desktop) ) in the hope that it meets your needs.

**Comment by cbenhagen** [comment]
@marb2000 Thanks for the insight. Hearing that despite desktop support being the most upvoted feature request here and in the [C++ SDK](https://github.com/firebase/firebase-cpp-sdk/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) it is not even on the engineering plan is not very reassuring though.

https://github.com/invertase/flutterfire_desktop looks like an abandoned project. It was announced with big words and support from Canonical etc but there hasn't been any progress for more than 7 months now. Requests about the status or ideas on how to collaborate with people outside of Inverase to advance the project, and even pull requests are completely ignored. Please see the comments in https://github.com/invertase/flutterfire_desktop/issues/52

We really love Firebase and have been a paying customer for years. We also contributed to the Flutter macOS support as much as possible. But adding Linux and Windows support is out of our capapbilities right now.

What open-source project would you recommend to use Firestore on Linux? Did you consider collaborating with @rbellens or @cachapa on a Dart implementation? @rbellens offered already [offered help](https://github.com/invertase/flutterfire_desktop/issues/52#issuecomment-1368831590) if his work could be funded.

**Comment by cbenhagen** [comment]
A quick update: Invertase has very recently created a new [Discord server ](https://invertase.link/discord) where some discussion is happening about the future of `flutterfire_desktop`. The good news is: It hasen't been abandoned and there is some ongoing work. But they could definitely use some more support by Google.

@marb2000 I would love to invite you to join the [discussion](https://discord.com/channels/295953187817521152/1059855806683676702) on their Discord to talk how we as a community backed by the support of Google / Firebase can advance the adoption of Firebase on Desktops.

**Comment by cachapa** [comment]
Thanks for the mention. I'd love to pick up Firedart again but it's tough to justify doing it by myself since I'm not currently using it for any projects and am a bit swamped with work.

**Comment by cbenhagen** [comment]
@cachapa glad to hear that! Doing it all on your own is certainly not as fun as doing it together. Also the world does not really need three Firebase Dart implementations. I think joining forces would make a lot of sense! Please also join the  [discussion](https://discord.com/channels/295953187817521152/1059855806683676702). I also invited Rik Bellens, the creator of `firebase_dart` `firebase_dart_flutter` and `firebase_admin`.

**Comment by cachapa** [comment]
Anyway these discussions can happen over a more async channel, like email or even GitHub?
I don't have a Discord account and honestly low availability for direct messaging.

**Comment by marb2000** [comment]
Thanks @cbenhagen and @cachapa for sharing these updates with me and the insights. Definitely I will read the thread in Discord.
