### ISSUE TITLE
firebase_messaging 14.2.0 

### ISSUE THREAD

**Issue by avadhworkzone** [firebase/flutterfire#10172]
## Bug report

**Describe the bug**
Firebase Notification come with background mode as well in forground mode but once app in kill mode we not get notification, kindly please check this issue with latest version of package.

### Steps to reproduce

2. '...'
4. See error or incorrect behavior

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by darshankawar** [comment]
@avadhworkzone 
What platform are you seeing this behavior on ? Android or iOS ?
Can you also take a look at the plugin example and run at your end and see if using it, you get same behavior as reported ?
If not, we will need a complete minimal reproducible code sample that shows the behavior.

**Comment by yogeshButani** [comment]
same issue,in  firebase_messaging 14.2.1, on background notifcation app is not openning
