### ISSUE TITLE
🐛 [firebase_auth] Can not login twitter in web

### ISSUE THREAD

**Issue by hatano0x06** [firebase/flutterfire#10179]
## Bug report

**Describe the bug**
Open the popup with `FirebaseAuth.instance.signInWithPopup(TwitterAuthProvider())` and after a few seconds `[firebase_auth/popup-closed-by-user] The popup has been closed by the user before finalizing the operation.` error occue

### Steps to reproduce

1. run `flutter run -d chrome --web-port=5000 --web-renderer=canvaskit`
2. press login button
3. wait few second

### Expected behavior
E-mail address can be entered without error

### Sample project

```
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';

class SamplePage extends StatefulWidget {

  SamplePage(): super();

  @override
  SamplePageState createState() => SamplePageState();
}

class SamplePageState extends State<SamplePage> with WidgetsBindingObserver {

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        padding: EdgeInsets.only(top:50,left:50),
        child: ElevatedButton(
          child   : Text("twitter login"),
          onPressed: (){ 
            print("000");
            FirebaseAuth.instance.signInWithPopup(TwitterAuthProvider()).then((_user){
              print("111 $_user");
            }).onError((error, stackTrace){
              print("222 $error");
            }).catchError((_error){
              print("3333 $_error");
            });            
          },
        ),
      ),
    );
  }
}


```
---

## Additional context
I took a video, but it was too big, so I put it on GoogleDrive
https://drive.google.com/file/d/1GFoTtaBmzBBu-gDPoPrzKC5Blh4MWKTL/view?usp=share_link

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.22000.1335], locale ja-JP)
Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.1)
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.74.2)
[√] Connected device (3 available)
[√] HTTP Host Availability
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by Lyokone** [comment]
Hello @hatano0x06,
It seems that it is only happening in Chrome Debug, if you are opening the URL in your web browser, everything works fine.

Do you see the same thing?

**Comment by hatano0x06** [comment]
@Lyokone 
It's happen everytime

I create url that you can try it
https://storyplotter-cdddb--twitterlogin-report1-4jjs4wcs.web.app/

**Comment by Lyokone** [comment]
Thanks it helps! 🙏

**Comment by Lyokone** [comment]
After investigation, I've opened an issue in the native JS repository.

**Comment by Lyokone** [comment]
@hatano0x06 do you still face this issue?

**Comment by hatano0x06** [comment]
@Lyokone 
No problem occurred!

Thank you very much!

```
Flutter 3.7.8 • channel stable
firebase_auth: ^4.4.0
```
