### ISSUE TITLE
🐛 [FirebaseAuth] SMS Autentication don't work with App Check deactivate on Android

### ISSUE THREAD

**Issue by yamauchieduardo** [firebase/flutterfire#10174]
I have a Flutter application that is being released on the Play Store. In Google Cloud Platform (GCP), I deactivated the SafetyNet and Google Play Integraty APIs in order to prevent the application from being validated with these services. However, when users try to login using SMS on Android, they receive the following error message:

`[firebase_auth/missing-client-identifier] This request is missing a valid app identifier, meaning that neither SafetyNet checks nor reCAPTCHA checks succeeded. Please try again, or check the logcat for more details.`

- [Play Integrity API](https://console.cloud.google.com/marketplace/product/google/playintegrity.googleapis.com) 

<img width="318" alt="image" src="https://user-images.githubusercontent.com/44825178/209392832-db5c850c-9d37-4a7d-a23c-ae118a3e9d09.png">

- [Firebase App Check API](https://console.cloud.google.com/apis/library/firebaseappcheck.googleapis.com)

<img width="335" alt="image" src="https://user-images.githubusercontent.com/44825178/209392817-9279dcf3-4008-4c6e-be13-b1cf45fb434e.png">

I have deactivated both the API for SafetyNet that are enable by default and the service, so I am not sure why this error is occurring. Is it possible to release a Flutter/Firebase application without enabling the App Check and Google Play Integrity APIs?

**Comment by darshankawar** [comment]
@yamauchieduardo 
Is this error occuring specifically on a particular device or on other devices as well ? Just trying to confirm if this could be device specific issue or not.

**Comment by yamauchieduardo** [comment]
@darshankawar Just appears on Android Devices. in iOS works as expected.

**Comment by darshankawar** [comment]
Thanks for the update. Can you take a look at [this](https://stackoverflow.com/questions/65490555/this-request-is-missing-a-valid-app-identifier-meaning-that-neither-safetynet-c) and see if it helps in your case ?

**Comment by yamauchieduardo** [comment]
I deactivated the SafetyNet and Google Play Integrity APIs to prevent the application from being validated by these services. I do not want this technology in my application. However, Firebase Auth sometimes tries to validate when users attempt to login using this API.

This is not the expected behavior, as I have deactivated and do not want this in my Flutter application.

**Comment by darshankawar** [comment]
Thanks for the update. I am keeping this issue open and labeling for team's attention and insights on the expected behavior if app check is deactivated.

/cc @Lyokone

**Comment by Lyokone** [comment]
Hello @yamauchieduardo 
As [per documentation](https://firebase.google.com/docs/auth/android/phone-auth#enable-app-verification), have you added the SHA1 in your app and downloaded the google-services.json file after?

To prevent abuse, Google will verify with one method the user before sending the SMS.

**Comment by yamauchieduardo** [comment]
Like I said: **I do not want AppCheck in my application.** It's not possible to release a Flutter application that uses Firebase Auth without AppCheck?

**Comment by Lyokone** [comment]
The default method is a Captcha, not AppCheck. The catpcha needs a SHA1 and SH256 in your console to authenticate your calls.

It is possible to release a Flutter App without AppCheck, but not without Captcha if you're using SMS auth

**Comment by snosey** [comment]
i have the same problem , how did you solve it?

**Comment by JoorgeFerrari** [comment]
Still facing this problem as well.
