### ISSUE TITLE
Mute Notification not working in android device.

### ISSUE THREAD

**Issue by 97loser** [firebase/flutterfire#10180]
I'm using the below version of firebase core & messaging.

  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.1
  
  I'm sending mute push notification using firebase console (sound - enabled/disabled) but unable to get mute notification.
  
  
  **_flutter doctor -v logs :_**
  
  
  [✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-x64, locale en-GB)
    • Flutter version 3.0.5 at /Users/admin/Documents/application/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (6 months ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    
    
    
    **Device details :** 
    Redmi A1
    Android version - Android 12

**Comment by darshankawar** [comment]
@97loser 
Can you provide `flutter doctor -v`, a complete minimal reproducible code sample along with a payload that shows the reported behavior and what's the expected result are you looking after you send the mute / silent notification ?

Also provide your Android device details such as OS version.
