### ISSUE TITLE
🐛 [FCM] Failed to Build AAR in flutter module using firebase messaging

### ISSUE THREAD

**Issue by jordynympasor** [firebase/flutterfire#10188]
Failed to build AAR during the assembleAarDebug stage with:
Firebase messaging 9.0.0-11.2.6
Firebase core 1.12.0

```
**ERROR:

FAILURE: Build failed with an exception.

What went wrong:

Execution failed for task ':firebase_messaging:uploadArchives'.

Could not publish configuration 'archives'

Could not write to file '/root/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-11.2.6/android/build/poms/pom-default.xml'.**
```
### Steps to reproduce

1. Create fresh flutter module
2. Add firebase_messaging 9.0.0 - 11.2.6
4. Build AAR

### Expected behavior
```
FAILURE: Build failed with an exception.

What went wrong:

Execution failed for task ':firebase_messaging:uploadArchives'.

Could not publish configuration 'archives'

Could not write to file '/root/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-11.2.6/android/build/poms/pom-
```
## Additional context

We are using a flutter module that connects to a native app. Upon adding firebase, the build aar fails. However, the flutter sdk we are using is 2.5.3, so the firebase messaging version that we can use is around 11.2.6 and below.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.6.1 21G217 darwin-arm, locale en-PH)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[!] Android Studio
    ✗ Android Studio not found at /Applications/Android/Contents
[✓] VS Code (version 1.74.2)
[✓] Connected device (1 available)

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.14.4
Flutter SDK 2.5.3
sendbird_module 1.0.0+1

dependencies:
- firebase_core 1.12.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 10.0.2 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_messaging_platform_interface 3.0.2 [firebase_core flutter meta plugin_platform_interface]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.8.1 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.15.0
- fake_async 1.2.0 [clock collection]
- firebase_core_platform_interface 4.2.4 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.6.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_web 2.0.2 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.7.0
- path 1.8.0
- plugin_platform_interface 2.1.3 [meta]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.2 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the report @jordynympasor 


> we are using is 2.5.3, so the firebase messaging version that we can use is around 11.2.6 and below.

This could be one of the reasons as why you are seeing the behavior. Current stable is 3.3.10 and plugin version is 14.2.0. The framework along with plugin have gone through lot of changes since the version you are on, so upgrading to latest configuration would most probably fix your issue, since all dependencies, gradle and kotlin versions have been upgraded, so you'll most probably need to upgrade, because even though there would have been an issue in framework or plugin version you are using, the potential fix would be made using the latest versions and not the ones you are on.

So I recommend to upgrade your project setup, be on latest and greatest versions of framework along with all plugins from your `pubspec.yaml` and try again to see if you still see the same error or not.

**Comment by jordynympasor** [comment]
> Thanks for the report @jordynympasor
> 
> > we are using is 2.5.3, so the firebase messaging version that we can use is around 11.2.6 and below.
> 
> This could be one of the reasons as why you are seeing the behavior. Current stable is 3.3.10 and plugin version is 14.2.0. The framework along with plugin have gone through lot of changes since the version you are on, so upgrading to latest configuration would most probably fix your issue, since all dependencies, gradle and kotlin versions have been upgraded, so you'll most probably need to upgrade, because even though there would have been an issue in framework or plugin version you are using, the potential fix would be made using the latest versions and not the ones you are on.
> 
> So I recommend to upgrade your project setup, be on latest and greatest versions of framework along with all plugins from your `pubspec.yaml` and try again to see if you still see the same error or not.

Yep, you are right. Upon checking with flutter version 3.3.10, it worked. Unfortunately we need to work with version 2.5.3 for now. So in the meantime I think we'll just use this workaround https://github.com/firebase/flutterfire/issues/3978#issuecomment-825601559
