### ISSUE TITLE
🐛 [firebase_auth] Not compatible with intl version latest

### ISSUE THREAD

**Issue by zakblacki** [firebase/flutterfire#10199]
Please upgrade firebase_auth with intl 0.18

`Because firebase_auth >=4.2.4 depends on firebase_auth_web ^5.2.4 which depends on intl ^0.17.0, firebase_auth >=4.2.4 requires intl ^0.17.0.
`

**Comment by darshankawar** [comment]
Thanks for the report. Using plugin example, if we run `flutter pub add intl`, it by default adds `intl: ^0.17.0`. But if we manually try to add `intl: ^0.18.0`, it gives below compile error:

```
Because every version of firebase_auth_web from path depends on intl ^0.17.0 and firebase_auth_example depends on intl ^0.18.0, firebase_auth_web from path is forbidden.
So, because firebase_auth_example depends on firebase_auth_web from path, version solving failed.
pub get failed
command: "/Users/dhs/Documents/Fluttersdk/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --directory . get --example"
pub env: {
  "FLUTTER_ROOT": "/Users/dhs/Documents/Fluttersdk/flutter",
  "PUB_ENVIRONMENT": "flutter_cli:get",
  "PUB_CACHE": "/Users/dhs/.pub-cache",
}
exit code: 1

Process finished with exit code 1
```

`firebase_auth_web` seems to depend on `intl: ^0.17.0` as shown below:

<img width="224" alt="Screenshot 2023-01-02 at 4 19 26 PM" src="https://user-images.githubusercontent.com/67046386/210221817-23e6e11d-bcbd-4e1c-9248-4677c2866804.png">

**Comment by Lyokone** [comment]
@zakblacki We [reverted the upgrade](https://github.com/firebase/flutterfire/pull/10165) to intl 0.18 since it was incompatible with flutter_localization. I guess you are on the master channel. You can force override to intl 0.18 if needed or go back to stable.

**Comment by Sun3** [comment]
Any updates on this issue? We should be able to use intl ^0.18.0

Thank you.

**Comment by Lyokone** [comment]
If you need to use ^0.18.0 you can always use dependency override to force the update. As long as the stable version is 3.7, we can only ship the intl version that is compatible with flutter_localization :)

**Comment by Sun3** [comment]
I understand... I am hoping in the near future the firebase_auth will upgrade to intl ^0.18.0

Thanks.

**Comment by jhonsabowsla** [comment]
any updates on this one ?

**Comment by Lyokone** [comment]
No new stable version of Flutter has been released, so we are still using 0.17.0. As said before, you can use 
```
dependency_overrides:
  intl: ^0.18.0
```

if you really need the latest version (it should not be breaking with previous release)

**Comment by Fraa-124** [comment]
I have updated to Flutter 3.10.0, but I still cannot compile due to the dependency issue with firebase_auth 4.5.0, which relies on firebase_auth_web 5.4.0. In turn, firebase_auth_web 5.4.0 depends on intl 0.17.0, while Flutter 3.10.0 depends on intl 0.18.0.

Is it really that difficult to update firebase_auth_web to use intl 0.18.0?

**Comment by MagnusJohansson** [comment]
Now that Flutter 3.0.0 stable is out, I think it's time to wake up and finally update [firebase_auth] to use intl 0.18.0

```
Because firebase_auth >=4.5.0 depends on firebase_auth_web ^5.4.0 which depends on intl ^0.17.0, firebase_auth >=4.5.0 requires intl ^0.17.0.
So, because my_app depends on both firebase_auth >=4.5.0 and intl >=0.18.0, version solving failed.
```

And, of course, as you know, when using flutter 3.0.0 with flutter_localizations one can't use intl 0.17.0 anymore.
```
Because my_app  depends on flutter_localizations from sdk which depends on intl 0.18.0, intl 0.18.0 is required.
So, because my_app depends on intl ^0.17.0, version solving failed.
```

So,  please update [firebase_auth] / [firebase_auth_web] to be flutter 3.0.0 compatible.

**Comment by Yegorisa** [comment]
Agree with the last post, we can't compile the project at all with flutter 3.10.0 because of this issue

**Comment by Lyokone** [comment]
I've opened #10944 to update the last few things needed for Flutter 3.10.0. I hope you understand that we couldn't update to intl 0.18.0 before the stable release last night.

It is not that it's "really that difficult to update"

Again, you can always override your dependencies if you cannot wait for a library to update.
```
dependency_overrides:
  intl: ^0.18.1
```

**Comment by BirjuVachhani** [comment]
Overriding it didn't work for me. I had to add this as well in addition to the `dependency_overrides`

```yaml
dependencies:
  flutter_localizations:
    sdk: flutter

```

**Comment by Lyokone** [comment]
We will shortly deploy a new version. This new version will not depend on intl anymore, so it will not cause any issues in the future.

**Comment by jhonsabowsla** [comment]
thak god its no longer dependant on intl anymore, kudos!

**Comment by jhonsabowsla** [comment]
awesomees
