### ISSUE TITLE
Pub installs executables into $HOME/.pub-cache/bin, which is not on your path.

### ISSUE THREAD

**Issue by hisnameispum** [firebase/flutterfire#10194]
Pub installs executables into $HOME/.pub-cache/bin, which is not on your path.
You can fix that by adding this to your shell's config file (.bashrc, .bash_profile, etc.):

  export PATH="$PATH":"$HOME/.pub-cache/bin"

**Comment by danagbemava-nc** [comment]
See this SO post for possible solutions https://stackoverflow.com/questions/52794266/pub-global-activate-command-home-pub-cache-bin-not-on-path. 

Closing this as this is not an issue with any flutterfire plugin but a message that comes from the pub tool. 

Thank you
