### ISSUE TITLE
🐛 [firebase_crashlytics] Error traces are obfuscated

### ISSUE THREAD

**Issue by svprdga** [firebase/flutterfire#10192]
## Bug report

**Describe the bug**
I have followed the steps described [here](https://firebase.google.com/docs/crashlytics/get-started?platform=flutter) in order to deobfuscate the error traces in Firebase Crashlytics, but they still are shown with obfuscated symbol names instead of the real ones.

### Steps to reproduce

1. Create an Android Flutter app and install `firebase_crashlytics: 3.0.6`
2. Generate a version with `flutter build appbundle --obfuscate --split-debug-info=debug-info`
3. Upload debug symbols with `firebase crashlytics:symbols:upload --app=APP_ID debug-info`

### Expected behavior

Error info in Crashlytics dashboard should be unobfuscated.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.3.10, on Linux Mint 21 5.15.0-56-generic, locale en_US.UTF-8)
    • Flutter version 3.3.10 on channel stable at /home/svprdga/opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (2 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/svprdga/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /home/svprdga/opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/brave-browser-stable

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.3)
    • Android Studio at /home/svprdga/opt/android-studio
    • Flutter plugin version 70.2.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.74.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.54.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux Mint 21 5.15.0-56-generic
    • Chrome (web)    • chrome • web-javascript • Brave Browser 108.1.46.144

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

---

**Comment by darshankawar** [comment]
@svprdga 
There's similar issue open describing your case, https://github.com/firebase/flutterfire/issues/8934, so please follow-up in it for further updates. You may also share your findings in that issue for better tracking.
Closing this as a duplicate.
