### ISSUE TITLE
Windows support questions

### ISSUE THREAD

**Issue by vd3d** [firebase/flutterfire#10215]
Hello there :-)

I'm trying to use Firebase with a Windows application, but looking at the documentation it is not clear if it is supported or not?

So, I have tried 2 solutions:

1) I used the flutterfire (core & auth) standard packages. But I got an exception when I start the application.

PlatformException (PlatformException(channel-error, Unable to establish connection on channel., null, null))

2) I tried to use https://github.com/invertase/flutterfire_desktop, but I got a build error:

/C:/FlutterSDK/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.24.0/lib/src/firebase_app.dart(18,25): error G75B77105: Member not found: 'FirebaseAppPlatform.verifyExtends'. [C:\Dev\KiipIt\KiipIt\build\windows\flutter\flutter_assemble.vcxproj]

And anyway, it does not support all the other firebase services (realtime db etc).

So, if you have any idea and/or solution?

**Comment by darshankawar** [comment]
> 3\. I tried to use https://github.com/invertase/flutterfire_desktop, but I got a build error:
> 
> /C:/FlutterSDK/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.24.0/lib/src/firebase_app.dart(18,25): error G75B77105: Member not found: 'FirebaseAppPlatform.verifyExtends'. [C:\Dev\KiipIt\KiipIt\build\windows\flutter\flutter_assemble.vcxproj]

The github repo you are using seems to be correct one for now to try out flutterfire packages on Windows. You can checkout [this](https://invertase.io/blog/announcing-flutterfire-desktop) article for further reference and see if it helps.

Regarding the error, it has been fixed already as part of [this](https://github.com/firebase/flutterfire/issues/9806) issue, so make sure you are using latest versions of all flutterfire packages as also mentioned in that [issue comment](https://github.com/firebase/flutterfire/issues/9806#issuecomment-1319642334).
