### ISSUE TITLE
🐛 [firebase_storage] No error handling on snapshotEvents.listen possible

### ISSUE THREAD

**Issue by Vera-uveye** [firebase/flutterfire#10222]
## Bug report

**Describe the bug**
When listening to snapshotEvents on uploading a file to the storage, it never catches errors, even though the exception is thrown and can be seen in the debug console:

```
E/StorageException(20373): StorageException has occurred.
E/StorageException(20373): User does not have permission to access this object.
E/StorageException(20373):  Code: -13021 HttpResult: 403
E/StorageException(20373): The server has terminated the upload session
E/StorageException(20373): java.io.IOException: The server has terminated the upload session
E/StorageException(20373): 	at com.google.firebase.storage.UploadTask.serverStateValid(UploadTask.java:339)
E/StorageException(20373): 	at com.google.firebase.storage.UploadTask.shouldContinue(UploadTask.java:308)
E/StorageException(20373): 	at com.google.firebase.storage.UploadTask.run(UploadTask.java:232)
E/StorageException(20373): 	at com.google.firebase.storage.StorageTask.lambda$getRunnable$7$com-google-firebase-storage-StorageTask(StorageTask.java:1072)
E/StorageException(20373): 	at com.google.firebase.storage.StorageTask$$ExternalSyntheticLambda3.run(Unknown Source:2)
E/StorageException(20373): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/StorageException(20373): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/StorageException(20373): 	at java.lang.Thread.run(Thread.java:923)
E/StorageException(20373): Caused by: java.io.IOException: {  "error": {    "code": 403,    "message": "Permission denied."  }}
E/StorageException(20373): 	at com.google.firebase.storage.network.NetworkRequest.parseResponse(NetworkRequest.java:445)
E/StorageException(20373): 	at com.google.firebase.storage.network.NetworkRequest.parseErrorResponse(NetworkRequest.java:462)
E/StorageException(20373): 	at com.google.firebase.storage.network.NetworkRequest.processResponseStream(NetworkRequest.java:453)
E/StorageException(20373): 	at com.google.firebase.storage.network.NetworkRequest.performRequest(NetworkRequest.java:272)
E/StorageException(20373): 	at com.google.firebase.storage.network.NetworkRequest.performRequest(NetworkRequest.java:289)
E/StorageException(20373): 	at com.google.firebase.storage.UploadTask.send(UploadTask.java:469)
E/StorageException(20373): 	at com.google.firebase.storage.UploadTask.uploadChunk(UploadTask.java:428)
E/StorageException(20373): 	at com.google.firebase.storage.UploadTask.run(UploadTask.java:231)
E/StorageException(20373): 	... 5 more
E/StorageException(20373): StorageException has occurred.
```

### Steps to reproduce

I followed the [documentation](https://firebase.flutter.dev/docs/storage/upload-files/#full-example) and tried to upload a file to a storage bucket where the user doesn't have permission. An error is thrown as can be seen in the debug console, but it doesn't enter the error case of the task snapshot's state.

### Expected behavior

I expect to enter the case TaskState.error to be able to handle the error there.

### Sample project

---

## Additional context
I chose snapshotEvents.listen and not the await option inside the try-catch block because I need the updates on the upload progress.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the report @Vera-uveye 
The log you provided is the Java stacktrace coming from native Firebase SDK. It logs errors by default, the plugin code itself for FlutterFire isn't logging/printing these. Also, it seems to be WAI since you can catch the error but it still logs it.



> I followed the [documentation](https://firebase.flutter.dev/docs/storage/upload-files/#full-example)

This documentation link is now archived and you should be following the link as mentioned in the screenshot.

<img width="825" alt="Screenshot 2023-01-06 at 3 38 39 PM" src="https://user-images.githubusercontent.com/67046386/210982128-2997dd96-9645-4886-a9af-f1198fbe5f5d.png">

So checkout [this](https://firebase.google.com/docs/storage/flutter/upload-files) documentation and [error handling section](https://firebase.google.com/docs/storage/flutter/upload-files#error_handling) in it and see if it helps.

**Comment by Vera-uveye** [comment]
Hi,
The documentation is the same like the archived one. I cannot catch the
errors on the plugin. See what I marked in the attached screenshot. It
never enters that case.

Thanks for your help,
Vera

**Comment by darshankawar** [comment]
Thanks for the update. I am unable to replicate this issue using the plugin example, so can you try the same and see if using it, you still get same error or not ? If not, and the error is triggering from your own code, we would need a minimal code sample along with exact steps to replicate.

**Comment by Vera-uveye** [comment]
Solved it by adding the .onError to handle these kinds of errors. The plugin apparently isn't catching/handling those. 
Think if you want to add them, it would be nice!
Thanks.

**Comment by darshankawar** [comment]
Good to know you resolved the issue. Closing based on above comment.
