### ISSUE TITLE
[firebase_auth] Reset password doesn't logout active connections

### ISSUE THREAD

**Issue by loic-hamdi** [firebase/flutterfire#10230]
When you reset the password of a user, the current logged-in sessions are not automatically disconnected, therefore it creates an obvious security issue.

I listen to these 3 streams to detect any change on the user:

```dart
  auth.authStateChanges().listen((User? user) async => await updateAuthStatus(user));
  auth.idTokenChanges().listen((User? user) async => await updateAuthStatus(user));
  auth.userChanges().listen((User? user) async => await updateAuthStatus(user));
```

Do you experience the same behavior?
How can we force to have all sessions disconnected or all tokens revoked?

⚠️  Another security issue, if you disable a user account in the firebase console, the user is not automatically logged out

**Comment by darshankawar** [comment]
> When you reset the password of a user, the current logged-in sessions are not automatically disconnected

@loic-hamdi Are you reseting the password from your running app or via firebase console (admin sdk) ?  If it is through your firebase console, then `idTokenChanges()`, `userChanges()` & `authStateChanges()` will not fire and you will have to force a reload using the following `FirebaseAuth.instance.currentUser.reload()`.
