### ISSUE TITLE
🐛 [flutterfire configure] Missing xcodeproj dependency

### ISSUE THREAD

**Issue by j-mastr** [firebase/flutterfire#10239]
## Bug report

**Describe the bug**
When running `flutterfire configure` on a fresh installation, it terminates with the exception `cannot load such file -- xcodeproj (LoadError)`. Since `sudo gem install xcodeproj` solved the issue for me, it looks like an unmet dependency, which is missing in your cli bundle.

### Steps to reproduce

1. Install flutterfire CLI using `dart pub global activate flutterfire_cli`
2. (Add `$PATH` if prompted by previous command)
3. Run `flutterfire configure` in an existing Firebase+Flutter project (not yet using Flutterfire CLI)

### Expected behavior

All dependencies to be bundled into the Flutterfire CLI.

### Sample project

*-- n/a --*

---

## Additional context

**OS:** macOS 13.1

<details><summary>Full Stacktrace</summary>

```
Unhandled exception:
Exception: /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- xcodeproj (LoadError)
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from -e:1:in `<main>'

#0      ConfigCommand.run (package:flutterfire_cli/src/commands/config.dart:540:11)
<asynchronous suspension>
#1      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#2      main (file:///Users/my-user/.pub-cache/hosted/pub.dartlang.org/flutterfire_cli-0.2.7/bin/flutterfire.dart:57:5)
<asynchronous suspension>
```

</details>

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-arm, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.74.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

*-- Shouldn't be relevant --*

---

**Comment by darshankawar** [comment]
@j-mastr 
`flutterfire configure` related issues need to be filed in dedicated repo: https://github.com/invertase/flutterfire_cli/issues
Closing from here.
