### ISSUE TITLE
🐛 [flutter_crashlytic] Bad handling 'reason' field in recordError

### ISSUE THREAD

**Issue by Olosss** [firebase/flutterfire#10246]
## Bug report

Flutter code badly supports null value field reason to native implementation

In firebase_crashlytics.dart recordError method has dynamic field 'reason', and inside it It is parsed to reason.toString()

https://github.com/firebase/flutterfire/blob/a2ce410479d33d87987bfc90fcc9c41954c041d1/packages/firebase_crashlytics/firebase_crashlytics/lib/src/firebase_crashlytics.dart#L79-L85
https://github.com/firebase/flutterfire/blob/a2ce410479d33d87987bfc90fcc9c41954c041d1/packages/firebase_crashlytics/firebase_crashlytics/lib/src/firebase_crashlytics.dart#L127-L134

If we do not pass this value it will parse "null" as string and conditions if(reason != null) in the native code will never be executed 

https://github.com/firebase/flutterfire/blob/a2ce410479d33d87987bfc90fcc9c41954c041d1/packages/firebase_crashlytics/firebase_crashlytics/android/src/main/java/io/flutter/plugins/firebase/crashlytics/FlutterFirebaseCrashlyticsPlugin.java#L150-L158

### Steps to reproduce

Log in error with recordError method without passing reason field
It will always display "Error throw null information in firebase crashlytics console"
![Screenshot 2023-01-10 at 17 31 18](https://user-images.githubusercontent.com/32511807/211608205-e225f13b-6aca-436e-95d8-5f280bfbbfd5.png)

Same behaviour for the iOS implementation

### Expected behavior

Do not show 'reason' information if it is null

---

**Comment by Olosss** [comment]
I will try elaborate this. Its not basically null error 

Maybe this part of code will explain it more to you 

`dynamic reason;`
 `String reasonString = reason.toString();`
 `print(reasonString);`

it will print "null"

You are passing null but as String reason = "null" to native code implementation;
So for proper operation it should be in native implementation something like this.

`if (reason != null && !reason.equals("null"))`

instead of 

https://github.com/firebase/flutterfire/blob/a2ce410479d33d87987bfc90fcc9c41954c041d1/packages/firebase_crashlytics/firebase_crashlytics/android/src/main/java/io/flutter/plugins/firebase/crashlytics/FlutterFirebaseCrashlyticsPlugin.java#L151

☝️ Just for explanation, ofc better will be passing it as real null value not as "null" string text.

**Comment by pawlowskim** [comment]
I don't think that created PR is the right way to patch the issue. The root cause is passing non nullable string to native implementation, and this should be fixed. Beside, this PR only workarounds Android implementation, it's also broken on iOS side.

**Comment by Lyokone** [comment]
@pawlowskim Thanks for pointing that out. I misinterpreted the issue report. I'll have another look.

**Comment by Lyokone** [comment]
@pawlowskim Opened another PR that should properly closed that: https://github.com/firebase/flutterfire/pull/10264
