### ISSUE TITLE
🐛 [firebase_dynamic_links] IOS and android do not detect dynamic links used to open the app

### ISSUE THREAD

**Issue by Henrydykee** [firebase/flutterfire#10244]
## Bug report

**Describe the bug**
when app is launched from a deeplink in a terminated state, IOS and android are unable to detect the links used to open the application

### Steps to reproduce

2. '...'
4. See error or incorrect behavior

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by darshankawar** [comment]
@Henrydykee 
Thanks for the report, but there's no details, code sample provided which we need in order to make issue actionable. Please provide the details requested in the template which you kept empty along with expected and actual results.

**Comment by Henrydykee** [comment]
so this is happening on one of my private projects..i can share my deeplink class ,

firebase is unable to pick up the link used to open the application when the application is in a terminated state…I have tried using app links but still doesn’t work 

`class DeepLinkManager {
  static final DeepLinkManager instance = new DeepLinkManager._internal();

  factory DeepLinkManager() => instance;

  DeepLinkManager._internal() {
    _appLinks = AppLinks();
  }

  late AppLinks _appLinks;

  void initDynamicLinks({Function? linkReceived}) async {
    print(_appLinks);

    final appLink = await _appLinks.getInitialAppLink();

    print(appLink);

    if (appLink != null) {
      linkReceived!(appLink, true);
    }

    PendingDynamicLinkData? data = await FirebaseDynamicLinks.instance.getInitialLink();
    final Uri? deepLink = data?.link;
    if (deepLink != null) {
      linkReceived!(deepLink, true);
    }

    FirebaseDynamicLinks.instance.onLink.listen((dynamicLinkData) {
      final Uri? deepLink = dynamicLinkData.link;
      if (deepLink != null) {
        linkReceived!(deepLink, true);
      }
    }).onError((error) {
      logger.e(error.message);
    });
  }
}`

**Comment by darshankawar** [comment]
> so this is happening on one of my private projects..

Thanks for the update, but in order to properly analyze the issue, we would need a complete minimal reproducible code sample that we can directly use that shows the behavior, so please provide one. You can try to create a new flutter project and just implement minimal required code that triggers the behavior.
Alternatively, you can also check out the [plugin example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_dynamic_links/firebase_dynamic_links/example) and implementation to see if using it, you still get same behavior or not.
