### ISSUE TITLE
🐛 [firebase_messaging] WEB: do something when notification is clicked

### ISSUE THREAD

**Issue by SeriousMonk** [firebase/flutterfire#10267]
I have integrated the firebase_messaging package in my flutter web app. I am able to display notifications both when app is in foregroung or background.

I would now like to open a specific page in my application when the user clicks on the notification. For now, when I click on the notification, the notification is dismissed and nothing happens.

I tried declaring an event handler for the ```notificationclick``` event, but it never gets triggered.

This is the code in my ```firebase-messaging-sw.js``` file:
```javascript
//Code for adding event on click of notification
self.addEventListener('notificationclick', function(event) {
    console.log('Notification clicked');
});

importScripts("https://www.gstatic.com/firebasejs/9.15.0/firebase-app-compat.js");
importScripts("https://www.gstatic.com/firebasejs/9.15.0/firebase-messaging-compat.js");

firebase.initializeApp({
  apiKey: "...",
  authDomain: "...",
  databaseURL: "...",
  projectId: "...",
  storageBucket: "...",
  messagingSenderId: "...",
  appId: "...",
  measurementId: "..."
});

const messaging = firebase.messaging();

messaging.onBackgroundMessage(function(message) {
    console.log('Received background message ', message);

    const content = JSON.parse(message.data.content);
    const notificationTitle = content.payload.summary ? content.payload.summary : content.payload.title;
    const notificationOptions = {
      body: content.payload.body,
      data: message.data,
    };

    self.registration.showNotification(notificationTitle, notificationOptions);
});
```

And then I send test notifications using Postman like this:
```json

{
    "registration_ids" : ["..."],
    "priority": "high",
    "mutable_content": true,
    "data" : {
        "content": {
            "id": 1,
            "badge": 42,
            "channelKey": "alerts",
            "layout": "BigText",
            "showWhen": true,
            "autoDismissible": true,
            "payload": {
                "redirectTo": "contractDetails",
                "id": "00322860-4a11-11ed-b06b-a77c38cad970",
                "title": "Huston! The eagle has landed!",
                "body": "A small step for a man, but a giant leap to Flutter's community!"
            }
        },
        "actions": [
            {
                "key": "REPLY",
                "label": "Reply",
                "autoDismissible": true,
                "requireInputText": true
            }
        ]

    }
}
```

Is there a way to push a route based on the notification payload when the notification is clicked (just like it is possible on android and iOS), or at least to focus my app...?

I've been stuck on this for 5 days now, so any help is greatly appreciated :)

**Comment by darshankawar** [comment]
Currently, the documentation does not seem to show how to handle interaction for web.

https://firebase.google.com/docs/cloud-messaging/flutter/receive#handling_interaction

Keeping this issue open for team's attention and insights on expected behavior.

Related: https://github.com/firebase/flutterfire/issues/10268

**Comment by Joseph-Nathan** [comment]
hi @jorgeroncero  
step 2 : Run a bash scrip
run it in which dir. & it is after the build or before it .

**Comment by SeriousMonk** [comment]
I ended up using awesome_notifications and awesome_notifications_fcm to handle notifications on Android and iOS. For web i then integrated the Google JavaScript SDK directly using js and dart interop to handle the callback functions.
Using this setup, the notificationclick handler defined in the service worker works perfectly.

It must be something with this package intercepting the notificationclick event I'd guess that doesn't make it work.

**Comment by russellwheatley** [comment]
Closing this out in favour of this issue: https://github.com/firebase/flutterfire/issues/10268. They're effectively the same.
