### ISSUE TITLE
🐛 [firebase_auth] Future error when reauthenticating

### ISSUE THREAD

**Issue by gabri1135** [firebase/flutterfire#10295]
## Bug report

on web platform when called reauthenticateWithCredential,
if error is caught, after it also return `Error: Bad state: Future already completed`

### Steps to reproduce

```
try {
  final user = authApi.currentUser!;
  final credential = EmailAuthProvider.credential(
      email: user.email!, password: oldPassword);

  await user.reauthenticateWithCredential(credential);
} on FirebaseAuthException catch (error, stack) {
  print('error');
}
```

get error:
`Error: Bad state: Future already completed
`
### Expected behavior
error not called

### Probably error

file: \firebase_auth_web-5.2.4\lib\firebase_auth_web.dart

```
@override
Future<UserCredentialPlatform> reauthenticateWithCredential(
    AuthCredential credential) async {
  _assertIsSignedOut(auth);
  try {
    auth_interop.UserCredential userCredential = await _webUser
        .reauthenticateWithCredential(convertPlatformCredential(credential)!);
    return UserCredentialWeb(auth, userCredential, _webAuth);
  } catch (e) {
    throw getFirebaseAuthException(e, _webAuth);
  }
```
  

### Personal solution

file: \firebase_auth_web-5.2.4\lib\firebase_auth_web.dart

 ```
@override
Future<UserCredentialPlatform> reauthenticateWithCredential(
    AuthCredential credential) async {
  _assertIsSignedOut(auth);
  try {
    return UserCredentialWeb(
        auth,
        await _webUser.reauthenticateWithCredential(
            convertPlatformCredential(credential)!),
        _webAuth);
  } catch (e) {
    throw getFirebaseAuthException(e, _webAuth);
  }
}
```

**Comment by darshankawar** [comment]
Thanks for the report @gabri1135 
I am unable to replicate the error as reported. Can you provide `flutter doctor -v` and plugin versions you are using that triggers this error along with complete error log ? Also, does it trigger consistently everytime ?

**Comment by gabri1135** [comment]
I caught AutoDisposeAsyncNotifier error bad.
My mistake
