### ISSUE TITLE
🐛 [firebase_messaging] cannot getToken on iOS device only

### ISSUE THREAD

**Issue by KingkanB** [firebase/flutterfire#10291]
## Bug report

**Describe the bug**
Only iOS device get this error when application execute these lines of code below:

```
await FirebaseMessaging.instance
      .getToken(
    vapidKey: AppStrings.vapidKey,
  )
```

Here is the error log:

FLTFirebaseMessaging: An error occurred while calling method Messaging#getToken, errorOrNil => {
    NSLocalizedFailureReason = **"Invalid fetch response, expected 'token' or 'Error' key";**
}

```
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
<asynchronous suspension>
#2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:367:43)
<asynchronous suspension>
#3      MethodChannelFirebaseMessaging.getToken (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:224:11)
<asynchronous suspension>
```

### Steps to reproduce

1. Delete the app
2. Install new app
3. get the error

### Expected behavior

App can get token.

Note. It just happed today. 18 Jan 2023

**Comment by darshankawar** [comment]
@KingkanB 
Can you provide `flutter doctor -v` and plugin's version you are using that shows this error ?

**Comment by similishetty** [comment]
Facing same issue.

**Comment by KingkanB** [comment]
@darshankawar 

![flutter-v](https://user-images.githubusercontent.com/122978483/213173178-9455d8ab-ca59-46a1-b48c-8c31bd51e513.png)

firebase_messaging: **14.1.3**

Note that:  
1. The application on production, worked fine before.  
2. I investigated on my side, there is no code changed and this bug happened only ios App.

**Comment by DaVaMa1** [comment]
The same issue has been reported both in the [firebase-ios-sdk](https://github.com/firebase/firebase-ios-sdk/issues/10679) as well as in the [react-native-firebase](https://github.com/invertase/react-native-firebase/issues/6830) repo.

**Comment by BinaryBlock** [comment]
Having same issue:

flutter firebase packages being used:
```
  firebase_analytics: 10.1.0
  firebase_core: 2.4.1
  firebase_messaging: 14.2.1
```

Line of code cause initial exception:
(in file `lib/main.dart`)
```
    // Get device specific message registration token
    final fcmToken = await FirebaseMessaging.instance.getToken();
```

Error:
```
FLTFirebaseMessaging: An error occurred while calling method Messaging#getToken, errorOrNil => {
    NSLocalizedFailureReason = "Invalid fetch response, expected 'token' or 'Error' key";
}
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: [firebase_messaging/unknown] An unknown error has occurred.
#0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:653
#1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:296
<asynchronous suspension>
#2      MethodChannel.invokeMapMethod
package:flutter/…/services/platform_channel.dart:499
<asynchronous suspension>
#3      MethodChannelFirebaseMessaging.getToken
package:firebase_messaging_platform_interface/…/method_channel/method_channel_messaging.dart:224
<asynchronous suspension>
```

`$ flutter doctor`
yields....
```
flutter doctor -v
[✓] Flutter (Channel stable, 3.3.10, on macOS 12.6.2 21G320 darwin-x64, locale en-US)
    • Flutter version 3.3.10 on channel stable at /Users/xxxxxxxxx/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (5 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
    • Android SDK at /Users/xxxxxxxxx/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0-rc1
    • ANDROID_HOME = /Users/xxxxxxxxx/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment 
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment 

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (4 available)
    •  • ios            • iOS 16.2 20C65
    • iPhone 13 (mobile)                       • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • macOS (desktop)                      • macos                                    • darwin-x64     • macOS 12.6.2 21G320 darwin-x64
    • Chrome (web)                         • chrome                                   • web-javascript • Google Chrome 

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

**Please help... any assistance is appreciated.**

**Comment by thakdanaik** [comment]
I investigated yesterday and found this error in the firebase library.
`{ "Error": "Missing a required parameter: apns_token"}`

today I tried to reproduce it, the issue is gone.
i assume that there is something went wrong in the library itself.

**Comment by darshankawar** [comment]
Thanks for all the reports and mentioning the related issues in other repos : https://github.com/firebase/flutterfire/issues/10291#issuecomment-1387056303.

Looking at it, it could be related to native Firebase sdk and server and not specifically to flutterfire plugin, as, this plugin is a thin wrapper around native Firebase sdks.

Looking at the most recent comments from firebase-ios-sdk issue: https://github.com/firebase/firebase-ios-sdk/issues/10679, the issue seem to have been resolved, so please check the thread and try at your end accordingly and confirm.

/cc @Lyokone

**Comment by KingkanB** [comment]
@darshankawar  the issue solved. the application works fine.

**Comment by Tahir-7cTech** [comment]
Thanks issue is fixed
