### ISSUE TITLE
🐛 [firebase_auth] Flutter web losses the user logged in on page refresh

### ISSUE THREAD

**Issue by mhmzdev** [firebase/flutterfire#10310]
## Bug report

**Describe the bug**
Firebase user doesn't stay persistent when the web page is refreshed on Flutter web, although this #9089 PR has been closed. I'm currently using `firebase_auth 4.1.5`

### Steps to reproduce

Steps to reproduce the behaviour:

1. Login
2. Refresh the page, the `user` is null now

### Expected behaviour
Logged in user must stay logged in, until logged out intentionally

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.0.1 22A400 darwin-arm, locale en-PK)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.74.3)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
  # Firebase
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.5
  cloud_firestore: ^4.1.0
```

</details>

---

**Comment by mhmzdev** [comment]
Its working fine now, I tried with flutter clean. I guess the problem is with `Bloc` its somehow refreshes the state on page refresh the state loses the data.

Thanks @darshankawar 
Closing the issue

**Comment by muriloventuroso** [comment]
I'm having the same problem if I use the emulator. Using the production service is fine.
