### ISSUE TITLE
Unhandled Exception: [core/duplicate-app] A Firebase App named "[DEFAULT]" already exists, after deleting the app from firebase console and re-running flutterfire configure in my existing flutter project root

### ISSUE THREAD

**Issue by sivang** [firebase/flutterfire#10313]
## Steps to Reproduce

Create a new app in firebase console.
Start a new flutter app locally in your development environment.
Install all required dependencies for `flutterfire` (-and ofc flutter cli etc)
Configure your flutter app using `flutterfire configure` , choose the app you created previously in firebase console.
Run your app (I'm doing this always to a MacOS target as I'm trying to develop a desktop app) make sure it initialized with Firebase (basically, no runtime exception on the init Future)
Shut down your app.
Delete your firebase console app.
recreate the firebase console app with the same base name as before, this doesn't matter as firebase ass a random uid with hyphen to the app's name.
Reconfigure you flutter local app with `fireflutter configure`, this time choose the newly created app after deleting the previous by the same name from your firebase console.
Rerun your app with `flutter run`.
 
**Expected results:** App runs and displays UI etc.

**Actual results:** App hangs up in suspension on the async await of the firebase init, giving the logged error in console:
```ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [core/duplicate-app] A Firebase App named "[DEFAULT]" already exists
#0      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:134:11)
```

**Extra Notes**: Before this change I could actually store stuff to my cloud firestore and retrieve some items from it, but nowhere in the firebase console could these documents and collection be found. Despite this, again - it was possible to store documents to a collection and retrieve them programmatically in Flutter(!!) Where is this `[DEFAULT]` app? is it an in memory thing or does it refer to some sort of cloud instance at the firebase backend?

<details>
<summary>Code sample</summary>

I'm initializing the app as `firebase_options.dart` was created successfully and includes all the required data.

```dart
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  // await FirebaseApi.addRandomUsers(Users.initUsers);
  runApp(const MyApp());
}
```

</details>

<details>
  <summary>Logs</summary>

```
Building macOS application...                                           
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [core/duplicate-app] A Firebase App named "[DEFAULT]" already exists
#0      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:134:11)
<asynchronous suspension>
#1      Firebase.initializeApp (package:firebase_core/src/firebase.dart:43:31)
<asynchronous suspension>
#2      main (package:executiveapp/main.dart:11:3)
<asynchronous suspension>
```

Attached analyze issues, however they are widget and style stuff not related (AFAICT) to the existing app issue.

```
   info • Avoid `print` calls in production code • lib/api/firebase_api.dart:17:5 • avoid_print
   info • Avoid `print` calls in production code • lib/api/firebase_api.dart:24:9 • avoid_print
   info • Unused import: 'package:meta/meta.dart' • lib/model/user.dart:1:8 • unused_import
   info • Avoid using private types in public APIs • lib/page/chat_page.dart:16:3 • library_private_types_in_public_api
   info • Avoid `print` calls in production code • lib/page/chats_page.dart:22:23 • avoid_print
   info • Unused import: 'dart:async' • lib/utils.dart:1:8 • unused_import
   info • Unused import: 'dart:convert' • lib/utils.dart:2:8 • unused_import
   info • Prefer const with constant constructors • lib/widget/chat_body_widget.dart:29:18 • prefer_const_constructors
   info • SizedBox for whitespace • lib/widget/chat_body_widget.dart:33:18 • sized_box_for_whitespace
   info • SizedBox for whitespace • lib/widget/chat_header_widget.dart:20:13 • sized_box_for_whitespace
   info • SizedBox for whitespace • lib/widget/chat_header_widget.dart:32:13 • sized_box_for_whitespace

11 issues found. (ran in 4.3s)

```

```
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-x64, locale en-IL)
    • Flutter version 3.3.10 on channel stable at /Users/sivan/FlutterInstall2/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (5 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.1 22C65 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 109.0.5414.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available


```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @sivang 



> Where is this `[DEFAULT]` app? is it an in memory thing or does it refer to some sort of cloud instance at the firebase backend?

Check this plugin example's implementation in initializing default and secondary apps to understand more on it.

https://github.com/firebase/flutterfire/blob/fd3026a4c281fcd90b7fc9007ae39d226b19a66f/packages/firebase_core/firebase_core/example/lib/main.dart#L18



> Configure your flutter app using `flutterfire configure` , choose the app you created previously in firebase console.
> Run your app (I'm doing this always to a MacOS target as I'm trying to develop a desktop app) make sure it initialized with Firebase (basically, no runtime exception on the init Future)

`flutterfire configure` also adds a `google-services.json` and `GoogleService-Info.plist` file for your respective platform, so even if you delete the app, it might be referring to this file in which the `[DEFAULT]` probably exists and hence you might be seeing `[core/duplicate-app]` error.

**Comment by sivang** [comment]
@darshankawar  thank you for your response
I had tried removing those files, and now getting some mysterious build errors. Could this be related?:
```
Running pod install...                                             19.8s
/Users/sivan/FlutterInstall2/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-2.4.1/macos/Classes/FLTFirebaseCorePlugin.m:229:50: warning: incompatible pointer to integer conversion sending 'NSNumber * _Nonnull __strong' to parameter of type 'BOOL' (aka 'signed char') [-Wint-conversion]
    [firebaseApp setDataCollectionDefaultEnabled:enabled];
                                                 ^~~~~~~
In module 'FirebaseCore' imported from /Users/sivan/FlutterInstall2/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-2.4.1/macos/Classes/FLTFirebasePlugin.h:10:
    BOOL dataCollectionDefaultEnabled;
         ^
1 warning generated.
/Users/sivan/FlutterInstall2/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-4.3.1/macos/Classes/FLTFirebaseFirestorePlugin.m:490:29: warning: comparison of distinct pointer types ('FIRQuery *' and 'NSNull * _Nonnull') [-Wcompare-distinct-pointer-types]
  if (query == nil || query == [NSNull null]) {
                      ~~~~~ ^  ~~~~~~~~~~~~~
1 warning generated.
```

**Comment by sivang** [comment]
The app now refuses to build altogether. This a grave bug in terms of usability, as there's also no hint whatsoever to how to remedy it.I could create an app from scratch in a new folder, in the hope it will work and copy over all my source files, but after already spending ~3 days trying to figure this out the plugins so far have hindered me rather than expediting my development process. 

```
....
....
 project 'Runner')
/Users/sivan/VitakkaProjects/Flutter/executiveapp/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.11, but the range of supported deployment target versions is 10.13 to 13.1.99. (in target 'FlutterMacOS' from project 'Pods')
** BUILD FAILED **

Building macOS application...                                           
Exception: Build process failed
```

**Comment by darshankawar** [comment]
> @darshankawar thank you for your response I had tried removing those files, and now getting some mysterious build errors. Could this be related?:
> 
> ```
> Running pod install...                                             19.8s
> /Users/sivan/FlutterInstall2/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-2.4.1/macos/Classes/FLTFirebaseCorePlugin.m:229:50: warning: incompatible pointer to integer conversion sending 'NSNumber * _Nonnull __strong' to parameter of type 'BOOL' (aka 'signed char') [-Wint-conversion]
>     [firebaseApp setDataCollectionDefaultEnabled:enabled];
>                                                  ^~~~~~~
> In module 'FirebaseCore' imported from /Users/sivan/FlutterInstall2/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-2.4.1/macos/Classes/FLTFirebasePlugin.h:10:
>     BOOL dataCollectionDefaultEnabled;
>          ^
> 1 warning generated.
> /Users/sivan/FlutterInstall2/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-4.3.1/macos/Classes/FLTFirebaseFirestorePlugin.m:490:29: warning: comparison of distinct pointer types ('FIRQuery *' and 'NSNull * _Nonnull') [-Wcompare-distinct-pointer-types]
>   if (query == nil || query == [NSNull null]) {
>                       ~~~~~ ^  ~~~~~~~~~~~~~
> 1 warning generated.
> ```

These seem to be warnings. Are there any errors that fails to build ? Please share complete log that shows the failure entires as well.



> warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.11, but the range of supported deployment target versions is 10.13 to 13.1.99. (in target 'FlutterMacOS' from project 'Pods')

This indicates you'll need to update or uncomment the line which shows the current target platform which in your case does not meet the minimum required. So please update the same and try again to see if you get any other errors or not.

**Comment by NicoEssi** [comment]
I'm experiencing a similar issue. I simply set up firebase on a brand new flutter project (flutter create --org com.identifier test), added the following dependencies to pubspec:
```
  firebase_core: ^2.5.0
  firebase_auth: ^4.2.6
  cloud_firestore: ^4.3.2
```

and upon running the app for the first time without debugging, I got the following warning:
```
/.pub-cache/hosted/pub.dev/cloud_firestore-4.3.2/macos/Classes/FLTFirebaseFirestorePlugin.m:490:29: warning: comparison of distinct pointer types ('FIRQuery *' and 'NSNull * _Nonnull') [-Wcompare-distinct-pointer-types]
  if (query == nil || query == [NSNull null]) {
                      ~~~~~ ^  ~~~~~~~~~~~~~
```
in addition to the following error:
`/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.12, but the range of supported deployment target versions is 10.13 to 13.1.99. (in target 'GTMSessionFetcher' from project 'Pods')`

**Comment by darshankawar** [comment]
@NicoEssi, please file a new issue by providing all relevant details mentioned in issue template so that we can take a look. Even if the error is similar, root-cause could be different.
