### ISSUE TITLE
🐛 [Cloud firestore]  How to compare two geopoints , compare and equal method not available for geopoint 

### ISSUE THREAD

**Issue by sadaqatdev** [firebase/flutterfire#10329]
How to compare two geopoints , compare and equal method not available for geopoint

**Comment by darshankawar** [comment]
@sadaqatdev 
Can you elaborate on your question by providing a practical example as what are you trying to achieve and what is the current limitation you are facing ?

**Comment by sadaqatdev** [comment]
i want to fetch all document where given LatLang is greater than or equal to all GeoPoint in  cloud firestore,

**Comment by sadaqatdev** [comment]
also we cannot compare tow LaLlang in flutter , e.g equal , compare to , grater than , less than methods are not available

**Comment by darshankawar** [comment]
@sadaqatdev 
I think your question is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here.
