### ISSUE TITLE
🐛 [firebase_dynamic_links] onLink listener not signaling faulty dynamic link data URI

### ISSUE THREAD

**Issue by toebgen** [firebase/flutterfire#10323]
## Bug report

We have set up Firebase Authentication as well as Dynamic Links as described in the respective tutorials ([here](https://firebase.google.com/docs/auth/flutter/start) and [here](https://firebase.google.com/docs/dynamic-links/flutter/receive)). Logins (Social, Email Link) as well as deep links into the app work fine.

However, we encountered an issue as described for `firebase-js` already: https://github.com/firebase/firebase-js-sdk/issues/5054. In this case, a faulty URL is given as dynamic link data. For example `https://link.[xyz].app/?link=https://xyz.firebaseapp.com/__/[...]` becomes `https:/link.[xyz].app/?link=https://xyz.firebaseapp.com/__/[...]` (note the missing `/`). 

The listener for the latest dynamic link events `FirebaseDynamicLinks.instance.onLink.listen()` does not emit anything in this case, the faulty URL seems to be silently failing the internal parsing.

### Expected behavior

It would be really helpful, if one would get some information about this, instead. `FirebaseDynamicLinks.instance.onLink.listen()` should emit some information about a faulty URL being received, maybe even an error.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.10, on macOS 12.6.2 21G320 darwin-arm, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.74.3)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report. Treating this as an enhancement for the plugin to detect and emit some information about a faulty URL being received, maybe even an error.

**Comment by russellwheatley** [comment]
Hey @toebgen, do you mind providing steps to reproduce this issue and I can take a look?
