### ISSUE TITLE
🐛 [firebase_ui_oauth_google] I think `clientId` should be optional, not required

### ISSUE THREAD

**Issue by kyle-seongwoo-jun** [firebase/flutterfire#10320]
May be related: #9823

I would like to suggest making the `clientId` parameter optional in the firebase_ui_oauth_google package, as it is not required according to the documentation for the [google_sign_in](https://pub.dev/packages/google_sign_in) package. 

The [documentation](https://pub.dev/documentation/google_sign_in/latest/google_sign_in/GoogleSignIn/clientId.html) states that _"It is optional if file-based configuration is used. The value specified here has precedence over a value from a configuration file."_ 

This means that if a developer wants to use file-based configuration, such as a `GoogleService-Info.plist` file, they are currently unable to do so because the `clientId` parameter is required. 

Making this parameter optional would provide more flexibility for developers using the firebase_ui_oauth_google package.

Thank you.

**Comment by darshankawar** [comment]
Thanks for the report @kyle-seongwoo-jun 
Can you check [this](https://github.com/firebase/flutterfire/pull/10017) similar issue that has been fixed already to see if it helps to answer your case ?

**Comment by kyle-seongwoo-jun** [comment]
@darshankawar Yes, unfortunately I checked issue #10017, but it does not appear to be related to my issue because it is an Android-specific issue and this issue is related to an iOS project.

**Comment by darshankawar** [comment]
Thanks for the feedback.

/cc @Lyokone

**Comment by lesnitsky** [comment]
@kyle-seongwoo-jun The `clientId` will stay required, since we want a seamless integration on desktop platforms without any desktop-specific configuration, so the Firebase UI library follows the Flutter's `build once, run everywhere` motto.

For the cases when `GoogleService-Info.plist` is preferred, #10360 introduces `iOSPreferPlist` option: when set to `true`, `clientId` will be ignored on iOS.

**Comment by kyle-seongwoo-jun** [comment]
@lesnitsky Thank you for clarifying the reasoning behind keeping the "clientId" parameter required in the firebase_ui_oauth_google package. I understand that having a seamless integration on desktop platforms is important for the library to follow the Flutter motto of "build once, run everywhere." 

It's great to hear that the #10360 issue introduces the "iOSPreferPlist" option, which will allow developers to use "GoogleService-Info.plist" on iOS by ignoring the "clientId" parameter. I appreciate the time and effort put into improving the library.

Thank you 😍

**Comment by kyle-seongwoo-jun** [comment]
Hi @lesnitsky, can I get an update on the status of PR #10360? 

It was approved a few days ago, but it hasn't been merged yet, so I'm just curious about the status. 

Thank you!

**Comment by lesnitsky** [comment]
@kyle-seongwoo-jun I have no idea why it wasn't merged after 2nd approval, probably @Lyokone just forgot to merge it :)

it's merged now
