### ISSUE TITLE
[firebase_auth] linkWithCredential doesn't provide the user's email address when auth.user().onCreate is triggered

### ISSUE THREAD

**Issue by mikron123** [firebase/flutterfire#10332]
When I use `linkWithCredential` to link an anonymous authentication to a new email one, the trigger function on the Firebase Functions side using `auth.user().onCreate` is not getting the user.email (it's null)

Am I using a bad practice?
1. I'm creating the credential of the email `EmailAuthProvider.credential(email: email, password: pass);`
2. `linkAccountWithCredential(credential, email: email, pass: pass);`

It works well, but the email returns null in the trigger function.

**Comment by darshankawar** [comment]
@mikron123 
Can you provide `flutter doctor -v`, plugin versions, and a minimal reproducible code sample along with steps to replicate that shows the behavior you are reporting ?

**Comment by mikron123** [comment]
@darshankawar 

flutter doctor -v:
````
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.22621.1105], locale en-IL)
    • Flutter version 3.3.10 on channel stable at c:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (6 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\m\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.74.3)
    • VS Code at C:\Users\m\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.58.0

[√] Connected device (4 available)
    • Pixel 4a (mobile) • 0B141JEC205998 • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows        • windows-x64    • Microsoft Windows [Version 10.0.22621.1105]
    • Chrome (web)      • chrome         • web-javascript • Google Chrome 109.0.5414.119
    • Edge (web)        • edge           • web-javascript • Microsoft Edge 108.0.1462.76

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
````



The code is VERY simple, all I have a is a trigger on the a new user authentication on the Firebase Functions side:



````
exports.handleNewAuth = functions.auth.user().onCreate((user) => {
	const email = user.email; // The email of the user.

	// email returns null when using linkWithCredential (email auth method) after an anonymous login
	console.log("new auth - " + email);

	return true;
});
````

Android client side code:

````
final AuthCredential credential = EmailAuthProvider.credential(email: email, password: pass);

await _auth.currentUser?.linkWithCredential(credential)
        .then((usercred)  {
      print("Anonymous account successfully upgraded ");
})
````

No problem with the linkage as the Firebase Console also displays the right email under the Authentication section.

**Comment by darshankawar** [comment]
Thanks for the update.
Can you try to use [fetchSignInMethodsForEmail](https://pub.dev/documentation/firebase_auth/latest/firebase_auth/FirebaseAuth/fetchSignInMethodsForEmail.html) and then `User.linkWithCredential` the one returned from above method to see if it helps in your case ?

**Comment by mikron123** [comment]
> 

I don't understand the relevance. it says the above method will simply provide the available method for auth for email (passwordless or email + pass)

The authentication and linkage works great. The only problem is that the trigger on the Firebase Functions does not contain the email, while you can clearly see it on the Firebase Console.
It looks like a bug.

**Comment by darshankawar** [comment]
Thanks for the feedback. Keeping this issue open for team's attention and insights on expected behavior.

**Comment by Lyokone** [comment]
I don't think there is much we can do on the FlutterFire side if it's related to [Firebase Function triggers](https://firebase.google.com/docs/functions/auth-events) I suggest you open an issue on the [relevant repository](https://github.com/firebase/firebase-functions).
