### ISSUE TITLE
🐛 [Dynamic Links] Reference data lost in iOS

### ISSUE THREAD

**Issue by amilkarSingular** [firebase/flutterfire#10336]
## Bug report

**Describe the bug**
I have been using Firebase dynamic links in android and ios. The issue is in iOS
### Steps to reproduce

If have not app installed and I click the link, it redirect to store and then the app with data link, It is working fine in Android, but in iOS the reference and the data lost. 

Also in Android after the link redirect to store and I dont click in CONTINUE button, the data is lost too

### Expected behavior

Get the reference and data once I install the app 

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.19044.2486], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.74.3)
[√] Connected device (4 available)
[√] HTTP Host Availability

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

firebase_dynamic_links: ^5.0.5

</details>

---

**Comment by darshankawar** [comment]
Thanks for the report @amilkarSingular 
Can you provide a minimal code sample that shows the behavior you are reporting ?
Also please elaborate on when you says `reference data is lost` ? What should be the expected result ?

**Comment by amilkarSingular** [comment]
This is my code:

```
Future<void> initDynamicLinks() async {
    final PendingDynamicLinkData? data = await FirebaseDynamicLinks.instance.getInitialLink();
    final Uri? dynamicLinkData = data?.link;
    if (dynamicLinkData != null && dynamicLinkData.queryParameters != null) {
      Map<String, dynamic> data = dynamicLinkData.queryParameters;
      if(dynamicLinkData.path == '/signUp'){
        Navigator.push(context, MaterialPageRoute(builder: (context) => SignUpView(data: data),));
      }
    }
    dynamicLinks.onLink.listen((dynamicLinkData) {
      print(dynamicLinkData.link.path);
      Map<String, dynamic> data = dynamicLinkData.link.queryParameters;
      print(data);
      if(dynamicLinkData.link.path == '/signUp'){
        Navigator.push(context, MaterialPageRoute(builder: (context) => SignUpView(data: data),));
      }
    }).onError((error) {
      debugPrint('onLink error');
      debugPrint(error.message.toString());
    });
  }
```

And when I say the data is lost, is because when the app is redirecting from Store to App after install, the data in dynamic link is lost. It is just in iOS

**Comment by darshankawar** [comment]
Please check if [this](https://github.com/firebase/flutterfire/issues/7546) issue and underlying comments helps in your case.
