### ISSUE TITLE
🐛 [firebase_auth] Flutter web: "Firebase: initializeAuth() has already been called with different options."

### ISSUE THREAD

**Issue by tgpsantos** [firebase/flutterfire#10335]
## Bug report

**Describe the bug**
Hey guys,

I recently updated the firebase plugins/dependencies (core, auth, etc) and everything kept working great for the mobile version. 

However, recently I noticed that auth is giving me troubles in the same web project

```dart

    defaultFirebase = await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );

    firebase_auth.FirebaseAuth _auth = firebase_auth.FirebaseAuth.instanceFor(
      app: defaultFirebase,
      persistence: firebase_auth.Persistence.INDEXED_DB,
    );

    firebase_auth.User? user = await _auth.authStateChanges().first;

```

I get the following firebase error when running the `_auth.authStateChanges().first`:
```txt
FirebaseError: Firebase: initializeAuth() has already been called with different options. To avoid this error, call initializeAuth() with the same options as when it was originally called, or call getAuth() to return the already initialized instance. (auth/already-initialized).
```

<details>
<summary>Full stack error</summary>

```

FirebaseError: Firebase: initializeAuth() has already been called with different options. To avoid this error, call initializeAuth() with the same options as when it was originally called, or call getAuth() to return the already initialized instance. (auth/already-initialized).
https://www.gstatic.com/firebasejs/9.15.0/firebase-auth.js 1:26585                                                G
https://www.gstatic.com/firebasejs/9.15.0/firebase-auth.js 1:26048                                                j
https://www.gstatic.com/firebasejs/9.15.0/firebase-auth.js 1:27098                                                X
packages/firebase_auth_web/src/interop/auth.dart 40:42                                                            getAuthInstance
packages/firebase_auth_web/firebase_auth_web.dart 119:31                                                          get delegate
packages/firebase_auth_web/firebase_auth_web.dart 67:8                                                            new
packages/firebase_auth_web/firebase_auth_web.dart 128:12                                                          delegateFor
packages/firebase_auth_platform_interface/src/platform_interface/platform_interface_firebase_auth.dart 57:10      instanceFor
packages/firebase_auth/src/firebase_auth.dart 27:55                                                               get [_delegate]
packages/firebase_auth/src/firebase_auth.dart 296:36                                                              authStateChanges
packages/camera/services/firebase/firebase_instances.dart 25:16                                                   initSingleton
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50   <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1653:54                                 runUnary
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 147:18                           handleValue
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 766:44                           handleValueCallback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 795:13                           _propagateToListeners
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 566:5                            [_completeWithValue]
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future.dart 528:22                                <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1653:54                                 runUnary
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 147:18                           handleValue
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 766:44                           handleValueCallback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 795:13                           _propagateToListeners
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 566:5                            [_completeWithValue]
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 639:7                            callback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 40:11                     _microtaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 49:5                      _startMicrotaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15  <fn>

```

</details>

Dependencies
```yaml
  firebase_auth: 4.2.5
  firebase_core: 2.4.1
```

Any idea on why this stopped working in a recent firebase upgrade? 
Why it happens only for web?

Thanks in advance!

**Comment by darshankawar** [comment]
Thanks for the report @tgpsantos 

> ```dart
> firebase_auth.FirebaseAuth _auth = firebase_auth.FirebaseAuth.instanceFor(
> ```

I did not completely understand this implementation. Instead can you try `FirebaseAuth.instanceFor(app: Firebase.app(), persistence:` and see if it helps ?

Also please check [this](https://github.com/firebase/firebase-js-sdk/discussions/4529) link and see if it helps in your case.

**Comment by tgpsantos** [comment]
@darshankawar 

What do you mean by `persistence:` ? Anyway, I tried Local persistency and problem persisted.

**Comment by tgpsantos** [comment]
Removing `persistence` fixes the error.

Both INDEXED_DB and LOCAL give the aforementioned same error.

**Comment by darshankawar** [comment]
Thanks for the update. 

> @darshankawar
> 
> What do you mean by `persistence:` ? Anyway, I tried Local persistency and problem persisted.

I meant passing the optional `persistence` value while using `instanceFor`.



> Removing `persistence` fixes the error.

Does that mean we can safely close this issue as resolved ? Since `persistence` is optional field and also the fact that I was unable to replicate the behavior too.

**Comment by tgpsantos** [comment]
> Thanks for the update.
> 
> > @darshankawar
> > What do you mean by `persistence:` ? Anyway, I tried Local persistency and problem persisted.
> 
> I meant passing the optional `persistence` value while using `instanceFor`.
> 
> > Removing `persistence` fixes the error.
> 
> Does that mean we can safely close this issue as resolved ? Since `persistence` is optional field and also the fact that I was unable to replicate the behavior too.

@darshankawar removing persistence fixed the error but now there's no persistence accross logins, which is not intended.

I think it's fairly easy to replicate the behaviour following the steps I described in the initial post. 
Are you saying you are able to use `Persistence.INDEXED_DB` while in Flutter Web? Don't forget to use the same dependency version :)

I'll reaffirm what I said before: this was working before a recent firebase upgrade. 
- firebase_core went from `1.22.0` to `2.4.1`
- firebase_auth went from `3.11.2` to `4.2.5`

**Comment by darshankawar** [comment]
I am unable to replicate this behavior, but based on the report, I'll keep this issue open and label for team's thoughts.

/cc @Lyokone

**Comment by Lyokone** [comment]
@tgpsantos  Thanks for raising this issue.
You can try this hotfix in your pubspec.yaml to check if this fixes it:
```
  firebase_auth_web:
    git:
      url: https://github.com/firebase/flutterfire.git
      ref: hotfix/web-user-null
      path: packages/firebase_auth/firebase_auth_web
```

We are currently waiting for some input from Google to fix the issue https://github.com/firebase/flutterfire/issues/10200 properly

**Comment by tgpsantos** [comment]
I've added it to pubspec.yaml and now I'm getting a 

`Because *project* depends on firebase_auth 4.2.5 which depends on firebase_auth_web ^5.2.4, firebase_auth_web from hosted is required.`

Am I supposed to change something in the other dependencies ?

**Comment by Greismorr** [comment]
Same, @tgpsantos.

**Comment by Lyokone** [comment]
The fix has now be published in the latest version of firebase_auth. I'll close this.
