### ISSUE TITLE
[firebase_app_check] Missing functionality to check device integrity?

### ISSUE THREAD

**Issue by chagaj** [firebase/flutterfire#10330]
Hello,

I would like to use google play integrity to obtain the integrity verdict on android devices as mentioned here - https://developer.android.com/google/play/integrity/verdict.

This topic has also been mentioned in a previous (internal) discussion, but it is not clear if it has been implemented - https://github.com/firebase/flutterfire/pull/9646#issuecomment-1311918193

I would like to check if a device meets one of the following:
"MEETS_BASIC_INTEGRITY"
"MEETS_STRONG_INTEGRITY"
"MEETS_VIRTUAL_INTEGRITY"

I am unable to find any reliable resources suggesting how to achieve this in a flutter app. Is this possible to do using the `firebase_app_check` package?

Thanks in advance.

**Comment by darshankawar** [comment]
Thanks for the report. I am keeping this issue open for team's insights whether this can be implemented at plugin level or need to be reported in native Firebase sdk repo.

**Comment by russellwheatley** [comment]
Hey @chagaj, as far as I can tell, this isn't available on android Firebase App Check (`firebase_app_check ` plugin is a wrapper around this). I would suggest opening an issue on the [native android Firebase SDK](https://github.com/firebase/firebase-android-sdk) if you are looking to make a feature request.

**Comment by chagaj** [comment]
Hey @russellwheatley, I just noticed that the Firebase SDK appears to support Play Integrity on Android according to this documentation - https://firebase.google.com/docs/app-check/android/play-integrity-provider

Perhaps I missed this the last time, or perhaps it is a new addition. Could this mean that it could/would be made available on the Flutter SDK too?

**Comment by russellwheatley** [comment]
Yes, Play Integrity is supported for App Check on FlutterFire. [See documentation](https://firebase.google.com/docs/app-check/flutter/default-providers).
