### ISSUE TITLE
[📚] Crashlytics documentation logs non-fatal errors as fatal

### ISSUE THREAD

**Issue by hmbadhon** [firebase/flutterfire#10343]
https://firebase.google.com/docs/crashlytics/get-started?platform=flutter#configure-crash-handlers
I'm following this documentation but my non fatal errors also record as a fatal errors for both Android and IOS. This issue previously mentioned : https://github.com/firebase/flutterfire/issues/9417 but closed. I'm facing this issue now. please help me.
![SCR-20230129-nik](https://user-images.githubusercontent.com/24831033/215321803-1818c06f-0cba-490b-ba03-11844f0c6080.png)
![SCR-20230129-niq](https://user-images.githubusercontent.com/24831033/215321805-6cbec3ed-9344-49d7-a78d-7c1c0bf30759.png)

**Comment by darshankawar** [comment]
@hmbadhon 
Thanks for the report. Please check [this](https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=flutter#report-uncaught-exceptions) section of the document and see if it helps in your case.
