### ISSUE TITLE
Apple badge value setting

### ISSUE THREAD

**Issue by Dalton-Vo** [firebase/flutterfire#10349]

**Comment by Dalton-Vo** [comment]
<img width="738" alt="Screen Shot 2023-01-31 at 13 37 54" src="https://user-images.githubusercontent.com/74093060/215685143-9f402323-6a5a-463d-8920-fe39e5e973ff.png">

**Comment by Dalton-Vo** [comment]
<img width="580" alt="Screen Shot 2023-01-31 at 13 44 43" src="https://user-images.githubusercontent.com/74093060/215686320-bbdc8cea-12fb-48e9-8e6c-023e66d345e5.png">

**Comment by darshankawar** [comment]
@Dalton-Vo 
I think [this](https://github.com/firebase/flutterfire/issues/768#issuecomment-617646751) and [this](https://github.com/firebase/flutterfire/issues/768#issuecomment-722245108) comment should answer your question.

Based on it, I am going ahead and closing this issue. You may also ask this question on support channels like StackOverflow.

**Comment by Dalton-Vo** [comment]
Can you help me answer my question : https://github.com/firebase/flutterfire/issues/10345#issuecomment-1410357128
