### ISSUE TITLE
[firebase_messaging]: <Push notification from FCM without having "content_available">

### ISSUE THREAD

**Issue by Dalton-Vo** [firebase/flutterfire#10345]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you aware of the differences between iOS and Android background message handling?

- [X] I understand that iOS and Android background messages behave differently, and I've designed my application with that in mind.

### Do you have an active Apple Developer account?

- [X] I have an active Apple Developer account.

### Are you using a physical iOS device to test background messages?

- [X] I am using a physical iOS device to test background messages.

### Have you enabled "Remote Notifications" & "Background Mode" (Checking options for "Background Processing" & "Remote Notifications") in your app's Xcode project?

<img width="716" alt="Screen Shot 2023-01-30 at 15 55 17" src="https://user-images.githubusercontent.com/74093060/215431311-73ce5401-272f-4636-9063-7ce576550e38.png">
<img width="659" alt="Screen Shot 2023-01-30 at 15 55 37" src="https://user-images.githubusercontent.com/74093060/215431661-c1452edb-3771-40f1-a4c6-ad06cf7a2665.png">

### Have you created an APNs key in your Apple Developer account & uploaded this APNs key to your Firebase console?

<img width="779" alt="Screen Shot 2023-01-30 at 15 58 31" src="https://user-images.githubusercontent.com/74093060/215432180-def735b2-49b0-43a7-a961-54877cbe9992.png">

### Have you disabled method swizzling for Firebase in your app?

<img width="367" alt="Screen Shot 2023-01-30 at 16 00 53" src="https://user-images.githubusercontent.com/74093060/215432486-1d150892-4dba-4749-be3c-397ddb0c644b.png">

### Are you sending messages to your app from the Firebase Admin SDK?

![Screen Shot 2023-01-30 at 16 08 56](https://user-images.githubusercontent.com/74093060/215434268-d79bfe37-6d9b-4f3f-9e20-d7a94e40f22e.png)

### Have you requested permission from the user to receive notifications?

- [x] I have the relevant permission to receive notifications.

### Have you used the 'Console' application on your macOS device to check if the iOS device's system is throttling your background messages?

<img width="426" alt="Screen Shot 2023-01-30 at 16 27 37" src="https://user-images.githubusercontent.com/74093060/215438613-1719a0a9-a2d7-4586-b83e-e61000e1faf0.png">

### Additional context and comments

- I have a problem that when I push notification using API with field "content-aivailble" : true, when in background (IOS) I can get data. 

![Screen Shot 2023-01-30 at 16 07 15](https://user-images.githubusercontent.com/74093060/215433889-d2acd492-bf81-40b2-9761-9d811659dda9.png)

- When I push notification using Firebase Cloud messaging, there is no "content-aivailable" field for me to set up for IOS. Can anyone explain problemto me ?

<img width="1024" alt="Screen Shot 2023-01-30 at 16 07 56" src="https://user-images.githubusercontent.com/74093060/215434026-ca125caa-569a-4d9d-87b6-293ab76fa6cb.png">

**Comment by darshankawar** [comment]
@Dalton-Vo 
Thanks for the report. I think the field should be `contentAvailable` and not `content_available`. See it's implementation [here](https://firebase.flutter.dev/docs/messaging/usage/) and [here](https://github.com/firebase/flutterfire/blob/3339bfeb81624e6e706d335139c087e4f3ea53eb/packages/firebase_messaging/firebase_messaging/example/scripts/send-message.js#L32) for your reference.

I hope above should resolve your issue / query, so will go ahead and close this issue. If you disagree, write in comments and I'll reopen it.

**Comment by Dalton-Vo** [comment]
Where can I put **contentAvailable** in Firebase cloud messaging on browser to query when push notification ?

**Comment by Dalton-Vo** [comment]
> @darshankawar Thank for your reply. But I have a question about Firebase cloud messaging. Where field that I put contentAvailable in Firebase cloud messaging on browser to query when push notification ? Because I only see custom data.
![image](https://user-images.githubusercontent.com/74093060/215773790-003cb552-f189-41d8-82f4-aee8e7ab2ee5.png)
