### ISSUE TITLE
 [firestore_auth_platform_interface] missing method FallThroughError

### ISSUE THREAD

**Issue by yakou32** [firebase/flutterfire#10354]
Following from  #10140 

## Bug report

**Describe the bug**
firebase_auth_platform_interface-6.11.3/lib/src/action_code_info.dart:65:15
Error: The method 'FallThroughError' isn't defined for the class 'ActionCodeInfo'.

### Steps to reproduce

Compile with these after pub cache cleaning:
dependencies:
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.5
  firebase_storage: ^11.0.10

According to the initial issue, wouldn't it be fixed already with these dependencies versions?

**Comment by yakou32** [comment]
Adding an explicit dependency to the latest firebase_auth_platform_interface (6.11.7) fixes the issue.

But this is not the right way...

**Comment by darshankawar** [comment]
@yakou32 
I am unable to replicate the error on latest stable and master using the plugins you mentioned above. Which platform are you running on that shows this error ? Also, what flutter version are you on ?
