### ISSUE TITLE
[cloud_firestore] Cannot update a field with a dot in its name

### ISSUE THREAD

**Issue by cubuspl42** [firebase/flutterfire#10367]
## Bug report

If my Firestore has a field with a dot (`.`) in its name, there's no way to _update_ it. By updating, I mean an operation available in all Firestore client implementations, which allows to update a specific field in a document with a new content, without recursive merging behavior.

[`DocumentReference.update`](https://pub.dev/documentation/cloud_firestore/latest/cloud_firestore/DocumentReference/update.html) doesn't accept `FieldPath`s. Dots in keys are interpreted as accessing nested document fields.

I consider this to be a bug, not a feature request, because updating a field is a fundamental Firestore functionality, and this specific client, to the best of my understanding, doesn't allow updating fields containing dots.

### Expected behavior

Updating all fields in any existing Firestore database should be possible with this client.

### Flutter doctor

Not relevant, this is not specific to my workstation.

### Flutter dependencies

Not relevant, I'm linking to the `latest` docs.

**Comment by darshankawar** [comment]
Thanks for the report @cubuspl42 
This probably seems to be a native Firebase SDK bug or current behavior instead of client side plugins. Please check [this](https://stackoverflow.com/questions/49643235/firestore-how-to-update-a-field-that-contains-period-in-its-key-from-andro) similar issue / link for your further reference.

**Comment by cubuspl42** [comment]
@darshankawar It's not the issue on the native side. The issue is that the Dart API does not expose a variant of the `update` method which accepts `FieldPath`s, reflecting the native side API.

**Comment by darshankawar** [comment]
Thanks for the feedback. Keeping this issue open for team's insights on expected behavior.

/cc @Lyokone

**Comment by cubuspl42** [comment]
Thank you! That was quick

**Comment by Lyokone** [comment]
Thanks for reporting this :)
