### ISSUE TITLE
Firebase_app_check for Flutter web [cloud_firestore/unavailable] Failed to get document because the client is offline. when implemented.

### ISSUE THREAD

**Issue by v-luis** [firebase/flutterfire#10374]
## Bug report

**Describe the bug**
Appcheck for  flutter web presents strange behavior. 
Throws [cloud_firestore/unavailable] Failed to get document because the client is offline error when implemented on Web App. Android and Ios both work fine with AppCheck Implemented. 
Different configurations have been tested:

1.- App Check implemented in Flutter Web App and Cloud Firestore enforced on Firebase Console/AppCheck throws : 
[cloud_firestore/unavailable] Failed to get document because the client is offline.
2.- App Check not implemented in Flutter Web App and Cloud Firestore enforced on Firebase Console/AppCheck throws:  [cloud_firestore/permission-denied] Missing or insufficient permissions.
3.- App Check implemented in Flutter Web App and Cloud Firestore not enforced on Firebase Console/AppCheck throws:  [cloud_firestore/unavailable] Failed to get document because the client is offline.
4.- App Check not implemented in Flutter Web App and Cloud Firestore not enforced on Firebase Console/AppCheck: works well, but no security is added (this was to test Firestore rules not interfering). 
5.- Running on chrome emulator with App Check in Flutter Web App implemented and Cloud Firestore enforced on Firebase Console/Appcheck (with previous debug token configuration in Firebase console): works well.

For all the above scenarios, when Appcheck is implemented, Android and Ios apps work well. 

### Steps to reproduce
1.- Configure Firebase Appcheck in Firebase Console as per https://firebase.google.com/docs/app-check/web/recaptcha-provider
2.- Configure Recaptcha in Recaptcha v3 Admin Console. 
3.- Configure Firebase Appcheck in Flutter app:
  
 ```
await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  await FirebaseAppCheck.instance.activate(
        webRecaptchaSiteKey: 'Key',
        androidProvider: AndroidProvider.playIntegrity,
  );
```

4.- Try read a document from Cloud Firestore (either enforced or not on AppCheck)

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

### Flutter doctor

<details><summary>Click To Expand</summary>

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-arm (Rosetta), locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.74.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>
dependencies:
- bloc 8.1.0 [meta]
- cloud_firestore 4.3.1 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cloud_functions 4.0.7 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- firebase_app_check 0.1.1+8 [firebase_app_check_platform_interface firebase_app_check_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 4.2.5 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.4.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_ui_auth 1.1.9 [email_validator firebase_auth firebase_core firebase_dynamic_links firebase_ui_localizations --- firebase_ui_oauth flutter flutter_localizations flutter_svg]
- firebase_ui_oauth_apple 1.0.16 [firebase_auth firebase_ui_oauth flutter]
- firebase_ui_oauth_facebook 1.0.16 [firebase_auth firebase_ui_oauth flutter flutter_facebook_auth]
- firebase_ui_oauth_google 1.0.16 [firebase_auth firebase_ui_oauth flutter google_sign_in]

</details>

---

**Comment by darshankawar** [comment]
Thanks for the report @v-luis 


> 2.- App Check not implemented in Flutter Web App and Cloud Firestore enforced on Firebase Console/AppCheck throws: [cloud_firestore/permission-denied] Missing or insufficient permissions.

Do you get any HTTP status code back for this scenario ?



> 1.- App Check implemented in Flutter Web App and Cloud Firestore enforced on Firebase Console/AppCheck throws :
> [cloud_firestore/unavailable] Failed to get document because the client is offline.

This most probably indicates no internet issue and I would have advised you to check by removing the appCheck to see what behavior do you get. That's probably your number 2 scenario though. Do you get this error consistently everytime you run the scenario ?

**Comment by v-luis** [comment]
Thanks for the reply @darshankawar 

While doing some more tests to answer back, I noticed something in the html file and found the solution. 
I was doing the firebase hosting deploy with the following script in the body:
```
<script>
    self.FIREBASE_APPCHECK_DEBUG_TOKEN = true;
  </script>
```
When I removed it, it started working fine. Asking about the HTTP status code helped me notice this, thanks.
Do you know if there is a way that the deployed web app and the debug app can work with Appcheck without having to change the index.html file every time?

**Comment by darshankawar** [comment]
Good to know that your issue is resolved.



> Do you know if there is a way that the deployed web app and the debug app can work with Appcheck without having to change the index.html file every time?

Please check below documentation links and see if they help to answer your question.

https://firebase.google.com/docs/app-check/flutter/default-providers#debug
https://firebase.google.com/docs/app-check/flutter/debug-provider

Closing this issue since it has been resolved.
