### ISSUE TITLE
🐛 [FIREBASE_MESSAGING] getToken() performance in iOS is slower than Android

### ISSUE THREAD

**Issue by alloza95** [firebase/flutterfire#10373]
## Bug report

getToken() performance in iOS is slower than Android. I've monitored it with 113 tests in several devices and I got the following results:

- iOS: 1200ms-2000ms average with peaks of 10000ms
- Android: 1ms average with peaks of 200-300ms.

As you can see, there is a big difference between platforms.

### Steps to reproduce

Use getToken() in Flutter app.

### Expected behavior

A similar performance in both platforms.

**Comment by darshankawar** [comment]
Thanks for the report @alloza95 
Can you provide on which flutter and plugin version you are seeing this behavior ?

**Comment by alloza95** [comment]
Yes, I'm using the following versions:

```
Flutter: 3.3.6
Firebase Core:  2.1.1
Firebase Messaging: 14.2.1
```

**Comment by darshankawar** [comment]
@alloza95 
When I run [plugin example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example) on iOS simulator, the FCM token generated is almost instant after the app is loaded, so I am not sure how are you seeing the slowness while fetching it.  Please try the example at your end and check if you still get same behavior or not.

**Comment by alloza95** [comment]
Hi, thanks for your time.

I ran plugin example on iOS simulator and I got times between 300ms-500ms, so this is better than my app.

Also I ran on Android emulator and I got times between 500-700ms, so is slowness performance than iOS simulator, while in my app Android was an average of 1ms with peaks of 200-300ms.

The tests of my app are in release mode with real users and real devices. And the piece of code that I'm monitoring is the following:

```dart
Future<String?> getToken() async {
    // Stopwatch to monitor performance.    
    final watch = Stopwatch()..start();

    _firebaseMessaging.onTokenRefresh.listen((token) {
       _fcmToken = token;
    });

    _fcmToken = await _firebaseMessaging.getToken();
     
    // Finish performance monitoring.
    watch.stop();

   return _fcmToken;
}
```

As you can see, I'm monitoring basically the getToken() method of Firebase Messaging plugin. 
In my app also I'm using Firebase Remote Config and Firebase Analytics, maybe they are penalizing the firebase messaging plugin performance?

Regards.

**Comment by darshankawar** [comment]
> In my app also I'm using Firebase Remote Config and Firebase Analytics, maybe they are penalizing the firebase messaging plugin performance?

Maybe segregating these two plugins and only trying with messaging plugin would help to narrow it down.
