### ISSUE TITLE
[firebase_ui_storage] Upload/download progress indicators

### ISSUE THREAD

**Issue by lesnitsky** [firebase/flutterfire#10379]
Firebase UI Storage should provide drop-in progress indicators as well as provide an easy way to build custom ones.

**Comment by abinvs-2019** [comment]
There does not exist a folder with firebse_ui_storage.
I can make a PR on that is someone could help.

**Comment by kroikie** [comment]
The folder exists on the [ui/storage](https://github.com/firebase/flutterfire/tree/ui/storage/packages) branch.
