### ISSUE TITLE
🐛 [Flutter Fire UI] Sign in with Google is not working

### ISSUE THREAD

**Issue by Wild-in-Programming** [firebase/flutterfire#10393]
Greetings,

I am a newcomer to Firebase UI and I am currently facing a problem in the Sign In Page. I am encountering an error message that reads "An unknown error occurred" whenever I attempt to sign in using Google.

For your reference, I have attached a screenshot of the issue.

I would greatly appreciate your assistance in resolving this matter.

Thank you for your time and support.

![Screenshot_20230207-170705](https://user-images.githubusercontent.com/68590772/217235016-173f2108-516e-43df-be64-ff757bd40a92.jpg)

**Comment by darshankawar** [comment]
@Wild-in-Programming 
The error `An unknown error occurred` most likely indicates you have not setup SHA1  fingerprints to the app from firebase console.
This isn't an issue with the plugin but your setup / config doesn't seem to be complete. Please take a look at Firebase documentation for flutter for proper steps to configure your app with Firebase.
Closing from here.
