### ISSUE TITLE
BugReportIntuitiveToken

### ISSUE THREAD

**Issue by GuilaMonstar** [firebase/flutterfire#10409]
https://github.com/settings/applications/2108759/advanced

**Comment by GuilaMonstar** [comment]
> https://github.com/settings/applications/2108759/advanced

branch:main1

**Comment by darshankawar** [comment]
@GuilaMonstar 
Please use new issue template and fill out requested details so that we'll have enough info to work with.
The link you shared is giving me 404 and it is not clear what the issue you are reporting.

Closing due to lack of details.
