### ISSUE TITLE
🐛 [FIREBASE_REMOTE_CONFIG] Inconsistent Get Data in android 7.1.1 (Nougat)

### ISSUE THREAD

**Issue by samueljiwandono0310** [firebase/flutterfire#10408]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.1, on macOS 13.2 22D49 darwin-arm64, locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.75.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

android : 
    compileSdkVersion 33
    minSdkVersion 23

i use function : 

remoteconfigInstance = await FirebaseRemoteConfig.instance;
  await remoteconfigInstance.setConfigSettings(RemoteConfigSettings(
    fetchTimeout: const Duration(minutes: 2),
    minimumFetchInterval: const Duration(seconds: 1),
  ));
  
  and i using 
  await remoteconfigInstance.fetchAndActivate();

and i get this log : 
D/FRCPlugin(12307): Sending fetchTimeout: 60
D/FRCPlugin(12307): Sending fetchTimeout: 120

**Comment by darshankawar** [comment]
@samueljiwandono0310 
Thanks for the report. Is this behavior only occuring in Android 7.1.1 ? Have you already verified on other device (OS and make) to check if the same behavior persists on them as well ?

Also provide your `flutter doctor -v` and plugin version.

**Comment by samueljiwandono0310** [comment]
hai, thanks for the response this information for flutter doctor -v : 
samueljiwandono@Samuels-MacBook-Pro cha-mobile-flutter % flutter doctor -v
[✓] Flutter (Channel stable, 3.7.1, on macOS 13.2 22D49 darwin-arm64, locale en-ID)
    • Flutter version 3.7.1 on channel stable at /Users/samueljiwandono/Documents/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7048ed95a5 (2 weeks ago), 2023-02-01 09:07:31 -0800
    • Engine revision 800594f1f4
    • Dart version 2.19.1
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/samueljiwandono/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/samueljiwandono/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.75.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (4 available)
    • Android SDK built for arm64 (mobile) • emulator-5554                        • android-arm64  • Android 7.1.1 (API 25) (emulator)
    • iPhone 14 Plus (mobile)              • 4C80C689-BADC-4EC8-873B-C69F9B6CD325 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)                      • macos                                • darwin-arm64   • macOS 13.2 22D49 darwin-arm64
    • Chrome (web)                         • chrome                               • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

and i use flutter firebase_remote_config: ^3.0.9

**Comment by samueljiwandono0310** [comment]
@darshankawar

**Comment by darshankawar** [comment]
> Is this behavior only occuring in Android 7.1.1 ? Have you already verified on other device (OS and make) to check if the same behavior persists on them as well ?

@samueljiwandono0310

**Comment by samueljiwandono0310** [comment]
Hi @darshankawar  sorry for the later response, sure i already check, but in have problem only from android 7.1.1

**Comment by darshankawar** [comment]
Since this is specific to only Android 7.1.1, I doubt if this is a plugin issue but looks more like device specific issue. you may want to reach out to firebase support on this one for further resolution.
