### ISSUE TITLE
[Firebase background message handler in flutter spawns duplicate isolate and runs the app twice]

### ISSUE THREAD

**Issue by manhtran-itr** [firebase/flutterfire#10412]
When my app uses:
  firebase_core: 2.5.0
  amplify_analytics_pinpoint: 0.6.12
  firebase_messaging: 14.2.2

when calling FirebaseMessaging.onBackgroundMessage(...) make main method run twice =. it causes all plugins in my app to run twice.

**Comment by darshankawar** [comment]
@manhtran-itr 


> amplify_analytics_pinpoint: 0.6.12

This is a third party plugin for Flutterfire, so can you check by removing this plugin and its corresponding code in your app to see if you still get same behavior or not ?

**Comment by manhtran-itr** [comment]
> 

I tried to remove third party plugin as you asked me for checking it but it still causes the same issue.  But when I remove FirebaseMessaging.onBackgroundMessage(...)  it doesn't happen anymore. Please help me to fix it.

**Comment by darshankawar** [comment]
@manhtran-itr 
Make sure you have configured following:

- `targetSdkVersion` & `compileSdkVersion` targeting android API 33.
- `android:exported="true"` property set in app manifest on apps running on android 12 or higher.
- `@pragma('vm:entry-point')` annotation just before calling background message handler.

**Comment by manhtran-itr** [comment]
> @manhtran-itr Make sure you have configured following:
> 
> * `targetSdkVersion` & `compileSdkVersion` targeting android API 33.
> * `android:exported="true"` property set in app manifest on apps running on android 12 or higher.
> * `@pragma('vm:entry-point')` annotation just before calling background message handler.

I checked all the information. My app configured those.

**Comment by manhtran-itr** [comment]
> @manhtran-itr I think your issue probably is similar to #8175 or #9964 so please check that. Also see if this could be also one of the reasons as why you are seeing the behavior: #9816

yes, it's the same behavior. I read those and try all the solutions but it won't work.

**Comment by darshankawar** [comment]
Both the linked issues are open, so I suggest you to follow-up in them for further updates. You may upvote the linked issues and also share your findings for better tracking.
Closing this as a duplicate.
