### ISSUE TITLE
🐛cant register for safetynet from  this month

### ISSUE THREAD

**Issue by MI-Soft** [firebase/flutterfire#10449]
I am using firebase auth for phone authentication in flutter app, every time it goes to google and verify i am not robot.
google says to enable safetynet to avoid recaptcha verification. but as safety net is going to shutdown in june, it stops allowing us to registering safetynet for new users. now i cant register safetynet. is there any other options to avoid recaptcha while phone auth?

**Comment by darshankawar** [comment]
@MI-Soft 
Please track in this native issue for updates on SafetyNet usage: https://github.com/firebase/firebase-android-sdk/issues/3890



> is there any other options to avoid recaptcha while phone auth?

Please check [this](https://www.google.com/search?q=How+to+disable+/+Remove+reCaptcha+in+firebase+phone-auth+(OTP)+android?+site:stackoverflow.com) link and see if it helps in your case.

Closing from here.

**Comment by nicks258** [comment]
Hello I tried every possible solutions:

- Enabling App Check in firebase console and in my project using 
` await FirebaseAppCheck.instance.activate(
    androidProvider: AndroidProvider.playIntegrity,
  );`
-  Enabling **Google Play Integrity API** from google console.
- Adding SHA1 & SHA256 keys
But still I am seeing **Recaptcha** screen please help. @darshankawar
