### ISSUE TITLE
[📚] Flutterfire github repo's `readMe` has broken link

### ISSUE THREAD

**Issue by darshankawar** [firebase/flutterfire#10459]
https://github.com/firebase/flutterfire#documentation

<img width="231" alt="Screenshot 2023-02-15 at 5 56 10 PM" src="https://user-images.githubusercontent.com/67046386/219027039-4391c094-97d7-495a-96c2-6750c35674a5.png">

Tries to access: https://github.com/firebase/flutterfire/blob/master/packages/flutterfire_ui/README.md which shows 404 page not found.

**Comment by TheClerici** [comment]
Hello! I can help with it, as I was searching, i found this [link](https://pub.dev/packages/flutterfire_ui). There's 2 approaches I can do, add a Readme.md to the package folder that explains that is deprecated or simply send if clicked to the link I provided.

**Comment by TomBeckett** [comment]
Thanks for the report @darshankawar 

Please take a look at https://github.com/firebase/flutterfire/issues/10471 similar issue and underlying comments to check if they help in your case.

Also [this](https://firebase.google.com/docs/flutter/setup?platform=ios) document for further reference.
