### ISSUE TITLE
🐛 [Firebase FireStore] App Crash in 16.1 [iphone 11]

### ISSUE THREAD

**Issue by Mehrankhan-METRA-RGB** [firebase/flutterfire#10454]
The Appstore Testflight crash report tells me this error.
The app works fine up to IOS 15.0 

FirebaseFirestore: firebase::firestore::util::ObjcThrowHandler(firebase::firestore::util::ExceptionType, char const*, char const*, int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<ch... + 112

**Comment by darshankawar** [comment]
@Mehrankhan-METRA-RGB Thanks for the report.

Is that the only log you get or there's more ? If possible please provide entire crash log in properly formatted text.
Also provide your `flutter doctor -v` on which the app is built and pushed to testflight.

**Comment by Mehrankhan-METRA-RGB** [comment]
here is  all info I got from test-flight

<img width="1120" alt="Screenshot 2023-02-25 at 12 49 33 PM" src="https://user-images.githubusercontent.com/73336909/221345659-3eedcf0f-af53-49a4-8d5a-c2da6bf55a6f.png">

**Comment by darshankawar** [comment]
Sorry for coming back late on this issue. Can you provide the error stacktrace in properly formatted text instead of in screenshots ?

**Comment by dev-namba** [comment]
me too
