### ISSUE TITLE
🐛 [cloud_firestore] DocumentReference.set docs is misleading

### ISSUE THREAD

**Issue by cubuspl42** [firebase/flutterfire#10471]
## Bug report

The [documentation](https://pub.dev/documentation/cloud_firestore/latest/cloud_firestore/DocumentReference/set.html) of `DocumentReference.set` states (emphasis mine)...

> Sets data on the document, overwriting any existing data. If the document does not yet exist, it will be created.
>
> If [SetOptions](https://pub.dev/documentation/cloud_firestore_platform_interface/5.11.0/cloud_firestore_platform_interface/SetOptions-class.html) are provided, the data **will** be merged into an existing document instead of overwriting.

The analogous comment in the Java implementation [documentation](https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/DocumentReference#set(java.lang.Object,com.google.firebase.firestore.SetOptions)) states (emphasis mine)...

> Writes to the document referred to by this DocumentReference. If the document does not yet exist, it will be created. If you pass SetOptions, the provided data **can** be merged into an existing document.

The Dart comment suggests that the method will do the merging even if `SetOptions(merge: false)` is passed.

**Comment by adar2378** [comment]
Also merge will update the `createdAt` timestamp with `merge:true`
