### ISSUE TITLE
🐛 Firebase Core & All Other Plugins :Uncaught (in promise) TypeError: Failed to resolve module specifier 'Instance of 'TrustedScriptURL''

### ISSUE THREAD

**Issue by irajeshh** [firebase/flutterfire#10477]
In flutter web release mode, web is crashing and nothing loads.
In console it shows the following errors for all the firebase plugins used:

`Uncaught (in promise) TypeError: Failed to resolve module specifier 'Instance of 'TrustedScriptURL''`
![image](https://user-images.githubusercontent.com/85046336/219477718-e0521a06-3f08-49d7-bcaf-13501fd4885b.png)

The error was not found before 7 days.
Nothing was changed, flutter sdk, firebase plugin versions, flutter codes. Everything is same, but appears on release mode and also on the hosted [site.](https://admin-meradigitalstore.web.app/)

Working Devices:
iOS: Brave & Safari
MacOs: Safari & Firefox

If I remove `await Firebase.initializeApp(options: FirebaseService.web);` nothing is crashing.

Tested on
Flutter Stable: 3.3.10 & 3.7.3

Firebase plugins:
  ```
 firebase_core: 2.6.0
  firebase_messaging: 14.2.3
  firebase_auth: 4.2.7
  cloud_firestore: 4.4.1
  firebase_storage: 11.0.12

```

Flutter Doctor Output
```
[✓] Flutter (Channel stable, 3.7.3, on macOS 13.1 22C65 darwin-arm64, locale en-IN)
Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.75.1)
[✓] Connected device (2 available)
    ! Error: Rajesh’s iPhone is busy: Fetching debug symbols for Rajesh’s iPhone. Xcode will continue when Rajesh’s iPhone is finished.
      (code -10)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by PROGrand** [comment]
This [peace of code](https://github.com/firebase/flutterfire/blob/0300445c6647dd0e52a1c73eb5e345798de60574/packages/firebase_core/firebase_core_web/lib/src/firebase_core_web.dart#L129-L133) calls `toString` which renders as 'Instance of 'TrustedScriptURL'', not the correct JavaScript's `[TrustedScriptURL.toString()](https://developer.mozilla.org/en-US/docs/Web/API/TrustedScriptURL/toString)`

It is possible to make toString to be external (calls JS toString)?

firebase_core_web: 2.1.0 still works...

**Comment by irajeshh** [comment]
Closing as Duplicate of #10474 
Also forcing to use the below versions temporarily solved the issue.
[Reference](https://github.com/firebase/flutterfire/issues/10474#issuecomment-1433436250)


```
firebase_core: 2.5.0
firebase_core_platform_interface: 4.5.2
firebase_core_web: 2.1.0
```
