### ISSUE TITLE
🐛 [FIREBASE_ANALYTIC] Can't DebugView mobile

### ISSUE THREAD

**Issue by bwrelawan** [firebase/flutterfire#10498]
I trying to DebugView via mobile, but not working. Even on another laptop. Please help me

1. I have implement this on terminal : `adb shell setprop debug.firebase.analytics.app com.example.app_name` but it still doesnt work
2. Uninstall then install again application

but still doesnt work to debugview

**Comment by darshankawar** [comment]
@bwrelawan 
This doesn't look like a bug in analytics, but maybe need correct setup / config, so I suggest you to ask this question on support channels like StackOverflow for solution.
Closing from here.
