### ISSUE TITLE
is it possible to handle firebase_messaging in flutter app onbackground state with my own localnotification handler??

### ISSUE THREAD

**Issue by RjMakwana2660** [firebase/flutterfire#10508]
Dear community,

I am currently working on a project that requires me to implement local notifications in Flutter. I need to show notifications both when the app is running in the foreground and background. I have researched and found out that the Firebase Cloud Messaging (FCM) SDK handles notifications when the app is running in the background.

However, I want to override this default behavior and use my own Flutter Local Notification handler to achieve the required functionality for my app. Can anyone guide me on how to set up my own notification handler for local notifications in Flutter so that I can achieve this requirement?

Thank you in advance for your help and suggestions.

**Comment by darshankawar** [comment]
@RjMakwana2660 
Your question is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here.
