### ISSUE TITLE
🐛 [firebase_messaging] onBackgroundMessage is never working in ios 

### ISSUE THREAD

**Issue by anhkhoi159** [firebase/flutterfire#10516]
I want save notification from Firebase to localDB but onBackgroundMessage wasn't called

```
@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp();
  if (Platform.isAndroid) SharedPreferencesAndroid.registerWith();
  if (Platform.isIOS) SharedPreferencesIOS.registerWith();
  // FlutterRingtonePlayer.playNotification();
  NotifyModel model = NotifyModel.fromJson(jsonDecode(message.data["Body"]));
  sendInfoReceiver(message.data["ID"]);
  saveNotify(model, 0);
}
```

and then call 
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

**Comment by darshankawar** [comment]
@anhkhoi159 
For background handler issues related to iOS, there's a separate template that you need to follow and fill: https://github.com/firebase/flutterfire/issues/new?assignees=&labels=Needs+Attention%2Ctype%3A+bug%2Cplugin%3A+messaging%2Cplatform%3A+ios&template=ios_background_message_handling.yml&title=%5Bfirebase_messaging%5D%3A+%3CYOUR+TITLE+HERE%3E

So I suggest you to use the above link and raise new issue. Closing this issue for now.
