### ISSUE TITLE
[firebase_dynamic_links] Send Sign In With Email keeps failing

### ISSUE THREAD

**Issue by brijq** [firebase/flutterfire#10518]
## Bug report

**Describe the bug**
Using the firebase auth sign in with email link sendSignInLinkToEmail, the link sent to user's email has its query params mode and oobCode, however when using firebase_dynamic_links onLink stream, I just get the path and no query params. mode and oobCode are required to signInWithEmailLink and verified with the isSignInWithEmailLink.

### Steps to reproduce

Follow basic implementation: https://firebase.google.com/docs/auth/flutter/email-link-auth and https://firebase.google.com/docs/dynamic-links/flutter/receive
### Expected behavior

The received link from onLink stream of firebase_dynamic_links should contain the query params mode and oobCode for sign in with email link to work.

 This is something that already specifically mentioned its a flutter auth library issue.

I have did some testing on IOS it seems fine. The problem lies on Android.

In Android, there is this settings > opening links > (your app) > Add link.

This needs to ensure that your firebase link need to be added manually.. Which obviously is still a very bad user experience.

However , that will only work if you use chrome to open up your email. Native email app will still be an issue..

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

Function Logic

1. Send Link to email upon user activation

```
  Future<bool> sendSignInLinkToEmail(String email) async {
    (await SharedPreferences.getInstance()).setString("auth_email", email);
    final String packageId = await AppUtils.getPackageIdentifier();
    String url;
    url = "https://myurl/myurl";

    try {
      ActionCodeSettings actionCodeSettings = ActionCodeSettings(
        url: url,
        handleCodeInApp: true,
        iOSBundleId: packageId,
        androidPackageName: packageId,
        androidInstallApp: false,
        androidMinimumVersion: "23",
      );

      await FirebaseAuth.instance.sendSignInLinkToEmail(
          email: email, actionCodeSettings: actionCodeSettings);
    } catch (e) {
      serviceLocator<AnalyticsService>()
          .logError(name: "sendSignInLinkToEmail", detail: e.toString());
      return false;
    }
    return true;
  }
```

2. Function to check and init Dynamic Link

```
  void initDynamicLinks() async {
    final PendingDynamicLinkData data =
        await FirebaseDynamicLinks.instance.getInitialLink();
    final Uri deepLink = data?.link;

    if (deepLink?.toString() != null) {
      if (await serviceLocator<AuthService>()
          .isSignInWithEmail(link: deepLink.toString())) {
        routingLogicDecision(deepLink.toString());
      }
    }

    FirebaseDynamicLinks.instance.onLink.listen((dynamicLinkData) async {
      final Uri deepLink = dynamicLinkData?.link;

      if (deepLink?.toString() != null) {
        var isSignInWithEmail =
            await AuthService().isSignInWithEmail(link: deepLink?.toString());
        if (isSignInWithEmail) {
          routingLogicDecision(deepLink.toString());
        } else {
          Fluttertoast.showToast(
              msg: 'There seems to be some error. Please try again');
        }
      }
    }).onError((error) {
      print('onLink error');
      print(error.message);
    });
}
```

3. Check logic if isSignInWithEmailLink given is true 

```
  Future<bool> signInWith({String link}) async {
    final String email =
        (await SharedPreferences.getInstance()).getString("auth_email");
    if (_firebaseAuth.isSignInWithEmailLink(link) && email != null) {
      final UserCredential authResult = await _firebaseAuth.signInWithEmailLink(
          email: email, emailLink: link);
      serviceLocator<DeviceInfoService>().updateDeviceInfo();
      return authResult.user != null;
    }
    return false;
  }

```

4. Helper function to check  ( Problem now lies here! )

It was previously working ok with these set of versions

```
dependency_overrides:
  firebase_core_platform_interface: 4.5.1

  cloud_firestore: ^3.1.17
  firebase_core: ^1.17.1
  firebase_analytics: ^9.1.9
  firebase_auth: ^3.3.19
  firebase_crashlytics: ^2.8.1
  firebase_messaging: ^11.4.1
  firebase_performance: ^0.8.0+13
  firebase_storage: ^10.2.17
  firebase_dynamic_links: ^4.2.5
  firebase_app_check: ^0.0.6+13
```

```
  Future<bool> isSignInWithEmail({String link}) async {
    return _firebaseAuth.isSignInWithEmailLink(link);
  }
```

6. Finally route base on outcome

```
 void routingLogicDecision(String deepLink) async {
    bool result =
        await serviceLocator<AuthService>().signInWith(link: deepLink);

    bool isUserProfileCreatedResult = await UserService.isUserProfileCreated();

    if (result && !isUserProfileCreatedResult) {
      Navigator.pushReplacementNamed(
          context, AdditionalRequirementsScreen.routeName);
    } else if (result && isUserProfileCreatedResult) {
      Navigator.pushReplacementNamed(context, BaseScreen.routeName);
    } else {
      SnackBarBuilderUtils.buildSnackBar(context, "Failed to sign in");
    }
  }
```

---

**Comment by darshankawar** [comment]
@brijq 
Can you set `androidMinimumVersion` to `0` and run your scenario again to see if the behavior still persists or not ?
Alternatively, make sure `androidMinimumVersion` and your app are on same version and try again.

**Comment by brijq** [comment]
@darshankawar 
Nope it doesn help.

As of now, in android opening the email intent in mobile browser works fine provided user allow application (which is poor user experience ) to open link with the firebase link. 

```
                  AndroidIntent intent = AndroidIntent(
                      action: 'action_view',
                      data: Uri.encodeFull('https://mail.google.com/mail/'),
                      package: 'com.android.chrome'
                  );
```
However previously with this method: 
Direct into gmail directly works fine in older firebase app links version
```
                 AndroidIntent intent = AndroidIntent(
                      action: 'android.intent.action.MAIN',
                      category: 'android.intent.category.APP_EMAIL',
                  );
```

Using Android intent plus as follows:

```
  android_intent_plus: ^3.1.6
```

**Comment by darshankawar** [comment]
Thanks for the update @brijq 
I tried to use the code sample you provided, but it seems to contain custom implementation that I can't use directly. Would be good to provide us a complete sample (ex: main.dart) that we can directly copy paste and run to verify this.

**Comment by brijq** [comment]
Hi @darshankawar 

Please refer to the initial post for the flow.
As requested, the following provided are with the complete dart files needed to run the code

---

## Additional context

Function Logic

1. Include (service_locator.dart)

```
GetIt serviceLocator = GetIt.instance;

void setupServiceLocator() {
  serviceLocator.registerLazySingleton<AuthService>(() => AuthService());
}
```

2. Include the whole class AuthService in (auth_service.dart)

```
class AuthService {
  final FirebaseAuth _firebaseAuth = FirebaseAuth.instance;

  Future<bool> get isAuthenticated async => _firebaseAuth.currentUser != null;

  Future<User> get currentUser async => _firebaseAuth.currentUser;

  Future<bool> isSignInWithEmail({String link}) async {
    return _firebaseAuth.isSignInWithEmailLink(link);
  }

  Future<bool> sendSignInLinkToEmail(String email) async {
    (await SharedPreferences.getInstance()).setString("auth_email", email);
    final String packageId = await AppUtils.getPackageIdentifier();
    String url;
    url = "https://your.dynamic.url/login";

    try {
      ActionCodeSettings actionCodeSettings = ActionCodeSettings(
        url: url,
        handleCodeInApp: true,
        iOSBundleId: packageId,
        androidPackageName: packageId,
        androidInstallApp: false,
        androidMinimumVersion: "23",
      );

      await FirebaseAuth.instance.sendSignInLinkToEmail(
          email: email, actionCodeSettings: actionCodeSettings);
    } catch (e) {
      return false;
    }
    return true;
  }

  Future<bool> signInWith({String link}) async {
    final String email =
        (await SharedPreferences.getInstance()).getString("auth_email");
    if (_firebaseAuth.isSignInWithEmailLink(link) && email != null) {
      final UserCredential authResult = await _firebaseAuth.signInWithEmailLink(
          email: email, emailLink: link);
      serviceLocator<DeviceInfoService>().updateDeviceInfo();
      return authResult.user != null;
    }
    return false;
  }
}
```

3. Function to check and init Dynamic Link (check_email_screen.dart)

```
  void routingLogicDecision(String deepLink) async {
    bool result =
        await serviceLocator<AuthService>().signInWith(link: deepLink);

    if (result) {
      Navigator.pushReplacementNamed(
          context, ScreenA);
    } else if (result && isUserProfileCreatedResult) {
      Navigator.pushReplacementNamed(context, ScreenB);
    } else {
      // Failed to sign in
    }
  }

  void initDynamicLinks() async {
    final PendingDynamicLinkData data =
        await FirebaseDynamicLinks.instance.getInitialLink();
    final Uri deepLink = data?.link;

    if (deepLink?.toString() != null) {
      if (await serviceLocator<AuthService>()
          .isSignInWithEmail(link: deepLink.toString())) {
        routingLogicDecision(deepLink.toString());
      }
    }

    FirebaseDynamicLinks.instance.onLink.listen((dynamicLinkData) async {
      final Uri deepLink = dynamicLinkData?.link;

      if (deepLink?.toString() != null) {
        var isSignInWithEmail =
            await AuthService().isSignInWithEmail(link: deepLink?.toString());
        if (isSignInWithEmail) {
          routingLogicDecision(deepLink.toString());
        } else {
          //There seems to be some error. Please try again
        }
      }
    }).onError((error) {
      print('onLink error');
      print(error.message);
    });
}
```

4. Please include with all the dependencies needed

```
dependency_overrides:

  cloud_firestore: ^4.4.3
  firebase_core: ^2.7.0
  firebase_analytics: ^10.1.4
  firebase_auth: ^4.2.9
  firebase_crashlytics: ^3.0.15
  firebase_messaging: ^14.2.5
  firebase_performance: ^0.9.0+14
  firebase_storage: ^11.0.14
  firebase_dynamic_links: ^5.0.15
  firebase_app_check: ^0.1.1+12
  get_it: ^7.2.0
  shared_preferences: ^2.0.15
  package_info_plus: ^3.0.1

```

5. Include this file for getting application info (app_utils.dart)

```
  static Future<String> getPackageIdentifier() async {
    PackageInfo packageInfo = await PackageInfo.fromPlatform();
    return packageInfo.packageName;
  }
```

7. Finally route base on outcome

```
 void routingLogicDecision(String deepLink) async {
    bool result =
        await serviceLocator<AuthService>().signInWith(link: deepLink);

    bool isUserProfileCreatedResult = await UserService.isUserProfileCreated();

    if (result && !isUserProfileCreatedResult) {
      Navigator.pushReplacementNamed(
          context, AdditionalRequirementsScreen.routeName);
    } else if (result && isUserProfileCreatedResult) {
      Navigator.pushReplacementNamed(context, BaseScreen.routeName);
    } else {
      SnackBarBuilderUtils.buildSnackBar(context, "Failed to sign in");
    }
  }
```

---

**Comment by darshankawar** [comment]
Thanks for the update. Couple of things that still need to be sorted:

1. The code sample you shared above uses `get` which is external to FF. In order to narrow down the behavior to the plugin implementation, does the behavior persist without `get` package code ?
2. I am trying to setup a demo app with the code sample above, and in order for it to work seamlessly, there are settings / configs we need to do such as setting up `SHA-256` as mentioned in this PR: https://github.com/firebase/flutterfire/pull/9911/files and other setup as mentioned in [this](https://github.com/firebase/flutterfire/issues/9465#issuecomment-1310093556) comment. So please confirm if you already have the required config / setup.
3. `Native email app will still be an issue..` coming back to this statement, is this only happening with other email apps when you are trying to open the link received in email in that app ? With `gmail` does it work ? but not maybe with let's say `outlook` ?

**Comment by brijq** [comment]
hi @darshankawar 

1. Yes the issue still persist.
2. Yes this step have already been done
3. The situation now is as follows:

- Only happens in android platform
- User have to go to settings -> apps -> default apps -> opening liinks -> (choose the app) -> Check open supported links -> add link ( Your firebase dynamic link)  Base on Pixel pure android version then it will work
- Opening browser through native chrome os and log in into email and tap the links works fine
- Directly navigate user to the native gmail app does not work after tapping on the link in the email.

**Comment by darshankawar** [comment]
Thanks for the update and patience. I am going ahead and keeping this issue open for team's thoughts on expected behavior on the scenario mentioned above.

**Comment by Lyokone** [comment]
@brijq Firebase Auth has been heavily changed, do you still have this issue? Thanks
