### ISSUE TITLE
bug build jdk 11

### ISSUE THREAD

**Issue by rezadevelopers2** [firebase/flutterfire#10525]
android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:39: error: cannot access BroadcastReceiver
      flutterEngine.getPlugins().add(new io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingPlugin());
                                ^
  class file for android.content.BroadcastReceiver not found

**Comment by darshankawar** [comment]
Closing as duplicate of https://github.com/firebase/flutterfire/issues/8324.
Please check https://github.com/firebase/flutterfire/issues/8324#issuecomment-1079818361 for solution.
