### ISSUE TITLE
🐛 [firebase_dynamic_link] Dynamic Link not working in IOS when install and launched from appstore

### ISSUE THREAD

**Issue by mmustafaget** [firebase/flutterfire#10522]
## Bug report

**Describe the bug**
I have implemented Firebase Dynamic Links in my iOS app, and it is working perfectly fine when I run the already installed app from a dynamic link. However, when I install the app from the App Store with a dynamic link and try to launch it, the Dynamic Links don't seem to work. The links simply open the app but don't trigger the intended functionality.

I have ensured that the Dymaic Links are correctly set up for my app, and the associated domains have been added to the entitlements file. I have also tried testing the Dynamic Links working perfectly on Android(if installed from the play store with the dynamic link)

I would appreciate any help in resolving this issue. Thank you.

### Steps to reproduce

1. Click on the dynamic link
2. Appstore is open
4. Download the app from app store
5. open the app from app store
6. but it doesn't trigger the intended functionality

### Expected behavior

1. Click on the dynamic link
2. Appstore is open
4. Download the app from app store
5. open the app from app store
6. Trigger the intended functionality same as working in Android

### Flutter doctor
![Screenshot 2023-02-24 at 1 31 50 pm](https://user-images.githubusercontent.com/84316313/221130505-229501ab-7601-4d35-8df4-a9428cf17ec5.png)

### Flutter dependencies

firebase_dynamic_links: ^5.0.4

**Comment by darshankawar** [comment]
Thanks for the report @mmustafaget 
Please check if your use case resembles https://github.com/firebase/flutterfire/issues/7546 or not.

**Comment by mmustafaget** [comment]
Thank you for taking the time to address this issue.

I've successfully created a dynamic link using Firebase, but we seem to be encountering a problem with our backend. Specifically, the backend is not generating the dynamic link correctly, potentially due to the "isForceRedirect" setting being true on curl requests. As a result, the preview page is not appearing on iOS, and the deep link is not functioning correctly after installing the app from the app store.
