### ISSUE TITLE
[firebase_messaging]: onBackgroundMessage is never working in ios

### ISSUE THREAD

**Issue by anhkhoi159** [firebase/flutterfire#10520]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you aware of the differences between iOS and Android background message handling?

- [X] I understand that iOS and Android background messages behave differently, and I've designed my application with that in mind.

### Do you have an active Apple Developer account?

- [X] I have an active Apple Developer account.

### Are you using a physical iOS device to test background messages?

- [X] I am using a physical iOS device to test background messages.

### Have you enabled "Remote Notifications" & "Background Mode" (Checking options for "Background Processing" & "Remote Notifications") in your app's Xcode project?

![image](https://user-images.githubusercontent.com/55753138/221082096-a05439b7-f4c0-471a-a44d-6ac0c0ca00e4.png)

### Have you created an APNs key in your Apple Developer account & uploaded this APNs key to your Firebase console?

I did it. 

### Have you disabled method swizzling for Firebase in your app?

![image](https://user-images.githubusercontent.com/55753138/221082310-fa1bbbd2-dc85-4f08-8c2b-8d7411d4e22e.png)

### Are you sending messages to your app from the Firebase Admin SDK?

![image](https://user-images.githubusercontent.com/55753138/221082402-db3b0f29-ca8b-432f-a46f-9133aa7921bf.png)

### Have you requested permission from the user to receive notifications?

- [X] I have the relevant permission to receive notifications.

### Have you used the 'Console' application on your macOS device to check if the iOS device's system is throttling your background messages?

I didn't see any logs

**Comment by darshankawar** [comment]
@anhkhoi159 
Can you also elaborate on what's the state of the app when onBackgroundMessage does not work ?
Is the state of the app minimized, terminated ?
Can you also try the [plugin example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example) and check if using it, do you see the same behavior or not ?

**Comment by anhkhoi159** [comment]
> @anhkhoi159 Can you also elaborate on what's the state of the app when onBackgroundMessage does not work ? Is the state of the app minimized, terminated ? Can you also try the [plugin example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example) and check if using it, do you see the same behavior or not ?

I save my notifications in local DB and then call my API to sever, but I had checked and onBackgroundMessage wasn't called. Can you have me check ?

**Comment by darshankawar** [comment]
> I save my notifications in local DB and then call my API to sever, but I had checked and onBackgroundMessage wasn't called

@anhkhoi159 
We also will not support non-FCM messages from third party packages. We specifically only support messages received from the Firebase APIs since we cannot guarantee that messages received from third party packages will not have any unintended side-effects on other Firebase products such as messaging delivery reporting and Analytics data. Hence, the implementation of storing notifications in local db and then calling your api may be out of scope for the plugin to properly work with and that might be the reason as why you are seeing the reported behavior.

That was also one of the reason as why I suggested you to take a look at plugin example and run at your end because using it, the background message handler works as expected, so it indicates there's no issue with the firebase api and could be related to external implementation you are using.

**Comment by anhkhoi159** [comment]
> > I save my notifications in local DB and then call my API to sever, but I had checked and onBackgroundMessage wasn't called
> 
> @anhkhoi159 We also will not support non-FCM messages from third party packages. We specifically only support messages received from the Firebase APIs since we cannot guarantee that messages received from third party packages will not have any unintended side-effects on other Firebase products such as messaging delivery reporting and Analytics data. Hence, the implementation of storing notifications in local db and then calling your api may be out of scope for the plugin to properly work with and that might be the reason as why you are seeing the reported behavior.
> 
> That was also one of the reason as why I suggested you to take a look at plugin example and run at your end because using it, the background message handler works as expected, so it indicates there's no issue with the firebase api and could be related to external implementation you are using.

![image](https://user-images.githubusercontent.com/55753138/222316218-bb6a450e-1110-468c-88e6-0d174769137b.png)
Hi @darshankawar  I only print message in onBackgroundMessage but it doesn't work too

**Comment by darshankawar** [comment]
@anhkhoi159 
I ran the plugin example on physical iOS device. The background handler has a print statement in it as below:

```
@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  await setupFlutterNotifications();
//  showFlutterNotification(message);
  // If you're going to use other Firebase services in the background, such as Firestore,
  // make sure you call `initializeApp` before using other Firebase services.
  print('Handling a background message ${message.messageId}');
}
```

I ran the npm command which sends a notification and it called the background handler as expected printing below:


```
flutter: Handling a background message 1677757256346055
flutter: Handling a background message 1677757268627107
```

**Comment by darshankawar** [comment]
This indicates the firebase api is working properly and it could be a setting / config issue at your end. I suggest you to try a new barebone project and use the documentation instructions and then run a simple notification to see if it works at your end or not.

**Comment by anhkhoi159** [comment]
> 

<img width="673" alt="image" src="https://user-images.githubusercontent.com/55753138/222420143-ca073521-d498-4074-8af8-42764e778d0b.png">
this is my config FCM can you help me check

**Comment by StigUK** [comment]
I have the same issue. I use flutter 3.7.6 and latest firebase_messaging version.
At some point, the application stopped processing notifications when the application is in the background or foreground on the release version.
This problem exists only on the release build. When I try to debug everything works.
I am aware of the need to use @pragma('vm:entry-point'). However, this does not help.
The application used to process push notifications a few months ago, but now it has stopped working again.
I have the same issue. I use flutter 3.7.6 and latest firebase_messaging version.
At some point, the application stopped processing notifications when the application is in the background or foreground on the release version.
This problem exists only on the release build. When I try to debug everything works.
I am aware of the need to use @pragma('vm:entry-point'). However, this does not help.
The application used to process push notifications a few months ago with flutter 3.3.x, but now it has stopped working again. Also, builds that were released a few months ago stopped processing notifications.

**Comment by darshankawar** [comment]
Please go through [this](https://github.com/firebase/flutterfire/issues/10082) issue and underlying comments and see if they help you in your case.
I am going ahead and closing this as not an issue with the plugin based on the verification done earlier. It could well be related to setting / implementation / config as mentioned in the linked issue.

If anybody disagree, write in comments and I'll reopen it.
