### ISSUE TITLE
🐛 [firebase_storage] MissingPluginException

### ISSUE THREAD

**Issue by FalgunT** [firebase/flutterfire#10535]
## Bug report

**Describe the bug**
No implementation found for method Reference#list on channel plugins.flutter.io/firebase_storage

After adding the library and related method in the class when i try to read the firebase storage data using
final ref = FirebaseStorage.instance.ref('/Temp');
    var files = await ref.list(const ListOptions(maxResults: 5));

It should give me the result from the Temp Folder, but it is giving the exeception

**Comment by darshankawar** [comment]
@FalgunT 
Can you provide `flutter doctor -v` and a complete minimal reproducible code sample that we can use to verify the issue ?
Also, check the [plugin example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_storage/firebase_storage/example) and see if using it too, you get same error or not.

**Comment by FalgunT** [comment]
@darshankawar, Thank You for the reply. This issue was found on the latest flutter version: 3.7.5. I applied flutter clean and deleted all the cache folders and reimport the project, then after the' pub get' command automatically project running successfully on the device.
