### ISSUE TITLE
🐛 [firebase_auth] throw PlatformException when unenroll a multiFactor

### ISSUE THREAD

**Issue by ASE55471** [firebase/flutterfire#10543]
## Bug report

**Describe the bug**
When call firebaseAuth.currentUser!.multiFactor.unenroll it throws PlatformException. I am not able to catch error in dart side then give user information about that.

### Steps to reproduce

1. Call `firebaseAuth.currentUser!.multiFactor.unenroll(multiFactorInfo:phoneMultiFactorInfo);` without reauthenticate.
2. It throws `PlatformException(FirebaseAuthRecentLoginRequiredException, com.google.firebase.auth.FirebaseAuthRecentLoginRequiredException: This operation is sensitive and requires recent authentication. Log in again before retrying this request., Cause: null, Stacktrace: com.google.firebase.auth.FirebaseAuthRecentLoginRequiredException: This operation is sensitive and requires recent authentication. Log in again before retrying this request.`

### Expected behavior

I should able to catch error like this.
```
try {
  await firebaseAuth.currentUser!.multiFactor.unenroll(multiFactorInfo:phoneMultiFactorInfo);
} on FirebaseAuthRecentLoginRequiredException catch (e) {
  // Give user corresponding info about error
}
```

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel stable, 3.3.7, on Microsoft Windows [version 10.0.19045.2604], locale zh-TW)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)                         
[√] Chrome - develop for the web                                                                         
[X] Visual Studio - develop for Windows                                                                  
    X Visual Studio not installed; this is necessary for Windows development.                            
      Download at https://visualstudio.microsoft.com/downloads/.                                         
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.3)                                                                      
[√] VS Code (version 1.75.1)                                                                             
[√] Connected device (6 available)                                                                       
[√] HTTP Host Availability
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
firebase_core 2.7.0 
firebase_auth 4.2.9
```

</details>

---

**Comment by darshankawar** [comment]
> 2\. t throws `PlatformException(FirebaseAuthRecentLoginRequiredException, com.google.firebase.auth.FirebaseAuthRecentLoginRequiredException: This operation is sensitive and requires recent authentication. Log in again before retrying this request., Cause: null, Stacktrace: com.google.firebase.auth.FirebaseAuthRecentLoginRequiredException: This operation is sensitive and requires recent authentication. Log in again before retrying this request.`

@ASE55471 
As the exception says `This operation is sensitive and requires recent authentication. Login again before retrying this request`, since you are trying to unenroll which is considered to be sensitive operation and hence you are getting the exception. Another operation such as password change would probably also lead to this exception.

What is the expected behavior are you looking for ? If you log in and try to unenroll, do you get same exception ?

**Comment by ASE55471** [comment]
What I tring to do is catch `FirebaseAuthRecentLoginRequiredException` in dart side, Like 
`FirebaseAuth.signInWithCredential(credential)` it throws `FirebaseAuthException` I am able to catch it using `on FirebaseAuthException catch (e)`, But `.unenroll` only throws `PlatformException`, Seems the `FirebaseAuthRecentLoginRequiredException` is not transfrom to the dart side exception, I can't use 'on FirebaseAuthRecentLoginRequiredException catch (e)' to catch an error.

**Comment by darshankawar** [comment]
Thanks for the explaination.

From native documentation: https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseAuthRecentLoginRequiredException

This exception is thrown after doing sensitive operation, but it seems currently it throws `PlatformException`.

/cc @Lyokone
