### ISSUE TITLE
🐛 [firebase_crashlytics] flutter_error_reason shows "thrown Instance of 'ErrorDescription'"

### ISSUE THREAD

**Issue by orestesgaolin** [firebase/flutterfire#10552]
## Bug report

**Describe the bug**
When Flutter related error is thrown in the widget tree, the resulting `flutter_error_reason` is not able to handle `ErrorDescription` correctly. Instead of showing the underlying description it only shows `
thrown Instance of 'ErrorDescription'` which hides the real reason.

![CleanShot 2023-03-02 at 10 47 30](https://user-images.githubusercontent.com/16854239/222392667-365d1e39-cc69-4c2e-aa80-399fd65f46bb.png)

### Steps to reproduce

1. Register Crashlytics to report Flutter errors like this:
```
  FlutterError.onError = (details) {
      FirebaseCrashlytics.instance.recordFlutterFatalError(details);
  };
```
2. Throw error in the widget tree e.g. try to call `!` on a null value
3. Observe the report in Crashlytics to not include the real reason in the field `flutter_error_reason`

### Expected behavior

The reason should be the result of calling `.toString()` on the `ErrorDetails` or `details.context.toStringDeep(minLevel: DiagnosticLevel.info)`

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.7.6, on macOS 13.0.1 22A400 darwin-arm64, locale pl-PL)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.75.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
- firebase_auth 4.2.6 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.5.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 3.0.12 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_messaging 14.2.2 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the report @orestesgaolin 
Can you take a look at [this](https://github.com/firebase/flutterfire/issues/9026#issuecomment-1267014667) and see if it helps in your case ?

**Comment by orestesgaolin** [comment]
Hi there! Not sure what should I look at, can you please elaborate? I'm using `recordFlutterFatalError` but the only difference to `recordFlutterError` is that it passes flag `fatal` equal to `true` (`recordFlutterError(flutterErrorDetails, fatal: true)`).

**Comment by orestesgaolin** [comment]
Just to give a hint to other people looking for a solution, for now I just call lower level method:

```
FlutterError.onError = (details) {
  FlutterError.presentError(details);

  final information = details.informationCollector?.call() ?? [];

  FirebaseCrashlytics.instance.recordError(
    details.exceptionAsString(),
    details.stack,
    reason: details.context?.toStringDeep(minLevel: DiagnosticLevel.info),
    information: information,
    printDetails: false,
    fatal: true,
  );
  // FirebaseCrashlytics.instance.recordFlutterFatalError(details);
}
```

**Comment by arshad-dqot** [comment]
My Crashlyrics cross 1 million network image crashes 😂
