### ISSUE TITLE
🐛 [flutter pub get] Because firebase_auth >=4.2.9 depends on firebase_auth_web ^5.2.8 which depends on intl ^0.17.0, firebase_auth >=4.2.9 requires intl ^0.17.0.

### ISSUE THREAD

**Issue by karokojnr** [firebase/flutterfire#10559]
## Bug report

**Describe the bug**
With the current Dart SDK version 3.0.0-283.0.dev, flutterfire_ui ^0.4.3+20 requires intl 0.18.0, and the current firebase_auth_web: ^5.2.8 version supports int 0.17.0  

### Steps to reproduce

1. Change flutter version to `master`

### Console output
```
Because no versions of flutterfire_ui match >0.4.3+20 <0.5.0 and flutterfire_ui 0.4.3+20 depends on flutter_localizations from sdk, flutterfire_ui ^0.4.3+20 requires flutter_localizations from sdk.
And because every version of flutter_localizations from sdk depends on intl 0.18.0, flutterfire_ui ^0.4.3+20 requires intl 0.18.0.
So, because partner_dashboard depends on both flutterfire_ui ^0.4.3+20 and intl ^0.17.0, version solving failed.
```
 ---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.8.0-18.0.pre.38, on Ubuntu 22.04.2 LTS
    5.19.0-32-generic, locale en_GB.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.3)
[✓] Android Studio
[✓] VS Code (version 1.74.0)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
@karokojnr 
please check https://github.com/firebase/flutterfire/issues/10199#issuecomment-1368981937 issue comment for current workaround.

There's an open PR to upgrade intl to latest version that you can track for further updates: https://github.com/firebase/flutterfire/pull/10443

I am closing this as a duplicate.
