### ISSUE TITLE
🐛 [firebase_storage]  'FirebaseStorage/FIRStorageTypedefs.h' file not found 

### ISSUE THREAD

**Issue by Nagao-yuma** [firebase/flutterfire#10557]
## Bug report

**Describe the bug**
With the latest version firebase_storage 11.0.14 iOS build fails with this error: 'FirebaseStorage/FIRStorageTypedefs.h' file not found.

### Steps to reproduce

1. `pub upgrade` and `pod install` to get the latest dependecies
2. After that archive with Xcode, the archive failed with the title error.

###  Console output
```
1. Did not find header 'FIRStorageTypedefs.h' in framework 'FirebaseStorage' (loaded from '/Users/proseedsmac/Library/Developer/Xcode/DerivedData/Runner-ezfrotlkyrsvgrgsbaffskucenco/Index.noindex/Build/Products/Debug-iphoneos/FirebaseStorage')
```

### Flutter doctor
<details><summary>Click To Expand</summary>

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.6, on macOS 13.1 22C65 darwin-x64, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.75.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

</details>

### Flutter dependencies

<details><summary>Click To Expand</summary>

- firebase_auth_web 5.2.8 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_web 2.2.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_database 10.0.14 [firebase_core firebase_core_platform_interface firebase_database_platform_interface firebase_database_web flutter]
- firebase_database_platform_interface 0.2.2+21 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_database_web 0.2.1+23 [firebase_core firebase_core_web firebase_database_platform_interface flutter flutter_web_plugins js]
- firebase_dynamic_links 5.0.15 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_dynamic_links_platform_interface 0.2.3+30 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.2.14 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.2.15 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 4.1.30 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.3.23 [_flutterfire_internals async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]

</details>

**Comment by darshankawar** [comment]
@Nagao-yuma 
I am unable to replicate the reported behavior. I tried archiving using plugin example with latest plugin versions which archived properly without any issues:

```
dhs@Dhss-MacBook-Pro firebase_storage_example % flutter build ipa

💪 Building with sound null safety 💪

Archiving com.nevercode.triage...
Automatically signing iOS for device deployment using specified development team in Xcode project: X8NNQ9CYL2
Running pod install...                                           1,721ms
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        15.5s
Xcode archive done.                                         89.2s
Built /Users/dhs/Documents/NCFlutter/triage-examples/flutterfire_examples/firebase_storage_example/build/storybook/ios/archive/Runner.xcarchive.

┌─ App Settings ───────────────────────────────────────────────────────────────────────┐
│ Version Number: 1.0.0                                                                │
│ Build Number: 1                                                                      │
│ Display Name: Missing                                                                │
│ Deployment Target: 10.0                                                              │
│ Bundle Identifier: com.nevercode.triage                                              │
│                                                                                      │
│ You must set up the missing settings.                                                │
│                                                                                      │
│ Warning: App icon is set to the default placeholder icon. Replace with unique icons. │
│                                                                                      │
│ To update the settings, please refer to https://docs.flutter.dev/deployment/ios      │
└──────────────────────────────────────────────────────────────────────────────────────┘
Building App Store IPA...                                          71.1s
Built IPA to /Users/dhs/Documents/NCFlutter/triage-examples/flutterfire_examples/firebase_storage_example/build/storybook/ios/ipa.
To upload to the App Store either:
    1. Drag and drop the "build/storybook/ios/ipa/*.ipa" bundle into the Apple Transporter macOS app https://apps.apple.com/us/app/transporter/id1450874784
    2. Run "xcrun altool --upload-app --type ios -f build/storybook/ios/ipa/*.ipa --apiKey your_api_key --apiIssuer your_issuer_id".
       See "man altool" for details about how to authenticate with the App Store Connect API key.
dhs@Dhss-MacBook-Pro firebase_storage_example % 

```

For your case, try to remove `podfile.lock`, then run `flutter clean`, `flutter pub cache repair` and then try again to see if it helps.

**Comment by Nagao-yuma** [comment]
@darshankawar 
Sorry for the late reply.
Thank you for answering.
I tried what you suggested, but the error did not go away.
I would like to review and consider the dependency part of firebase_core again.
Please let me know if there is anything else.
thank you very much.

**Comment by darshankawar** [comment]
@Nagao-yuma 
This seems to be a cache issue so try `pod install --repo-update` and see if it helps. Also look for similarly logged issues on support channels like StackOverflow as well.

**Comment by Nagao-yuma** [comment]
@darshankawar 
Thank you for contacting me.
Here, I was able to resolve it.
The cause was that the FirebaseSDKVersion in the Podfile specified '8.15.0'. Therefore, by specifying the latest '10.6.0' and clearing the cache as advised, the build was successfully completed.
Sorry for not being able to understand the rudimentary part.
I'm really thankful to you.

**Comment by darshankawar** [comment]
Good to know your issue is resolved. Closing based on above comment.
