### ISSUE TITLE
🐛 [firebase_auth] authStateChanges is not called after linkWithCredential 

### ISSUE THREAD

**Issue by guenth39** [firebase/flutterfire#10561]
## Bug report

**Describe the bug**
`authStateChanges` gets not notified about a user changed from anonymous to authenticated by calling `linkWithCredential`.

### Steps to reproduce

1. Add a listener to `FirebaseAuth.instance.authStateChanges()`
2. Call `FirebaseAuth.instance.signInAnonymously()`
3. Call `FirebaseAuth.instance.linkWithCredential()`
4. See that `FirebaseAuth.instance.currentUser?.isAnonymous` has changed, but the listener was not called

### Expected behavior

`FirebaseAuth.instance.authStateChanges()` should emit an event when the user is linked to credentials.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.5, on macOS 13.2 22D49 darwin-arm64 (Rosetta), locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.75.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues **found!**
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @guenth39 
I tried the [plugin example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_auth/firebase_auth/example) by including the steps to replicate you mentioned, but was unable to replicate the reported behavior. Can you provide us complete code sample that we can use to verify this ?

**Comment by Flucadetena** [comment]
In case someone is looking for the answer to the same problem. authStateChanges doesn't fire when this events happend:
```
reload()
linkWithCredential()
unlink()
updateEmail()
updatePassword()
updatePhoneNumber()
updateProfile()
```
But the event that will fire is userChanges(). It works the same as authStateChanges.

Hope it helps. Already made a suggestion to change it in the docs.

**Comment by Flucadetena** [comment]
In case someone is looking for the answer to the same problem. authStateChanges doesn't fire when this events happened:
```
reload()
linkWithCredential()
unlink()
updateEmail()
updatePassword()
updatePhoneNumber()
updateProfile()
```
But the event that will fire is userChanges(). It works the same as authStateChanges.

Hope it helps. Already made a suggestion to change it in the docs.
