### ISSUE TITLE
🐛 [firebase_messaging] Notification is shown twice

### ISSUE THREAD

**Issue by furkanKotic** [firebase/flutterfire#10564]
## Bug report

**Describe the bug**
When I send notification, firebase shows notification and flutterLocalNotificationsPlugin in onBackgroundMessage function is triggered. That's why a notification is shown twice. I need to do some checks in the function I specified in onBackgroundMessage, so how can I turn off firebase_message itself from showing notifications?

### Steps to reproduce

1. Go to Firebase console
2. Create new notification
4. Send test or directly notification

### Expected behavior

Notification should be shown once.

### Sample project

Same codes below:

https://pub.dev/packages/firebase_messaging/example

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.6, on Microsoft Windows [Version 10.0.19045.2673], locale tr-TR)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 2022.1)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
  firebase_core: ^2.7.0
  flutter_local_notifications: ^13.0.0
  firebase_messaging: ^14.2.5
```

</details>

---

**Comment by darshankawar** [comment]
> so how can I turn off firebase_message itself from showing notifications?

@furkanKotic 
There's [this](https://github.com/firebase/flutterfire/discussions/6113) discussion thread you can follow-up in and see underlying comments to know if they help in your case. You can share your findings and any comments in it for further updates.
Closing from here.

**Comment by furkanKotic** [comment]
I don't understand. The problem in the link you provided is not resolved.
It is written in the documents that the onBackgroundMessage function must be defined, but if we define it, both the firebase and the function I defined show notification. then onBackgroundMessage should not be defined, am I right?
