### ISSUE TITLE
🐛 [google_sign_in] Google consent screen popup is not opening for second time login of another account

### ISSUE THREAD

**Issue by saravanakumark100** [firebase/flutterfire#10570]
## Bug report

**Describe the bug**
First time, i can able to connect with an account and again when i am trying to connect with some other account, google consent screen is not opening for second time.

**Comment by darshankawar** [comment]
@saravanakumark100 
This doesn't seem to be an issue with flutterfire as `google_sign_in` is not part of the packages. You should ask this support question on stackoverflow. Closing from here. If you think there's a genuine bug in the plugin, open an issue in flutter repo using the template and fill out requested details.
