### ISSUE TITLE
🐛 [firebase_storage] example does not upload the file

### ISSUE THREAD

**Issue by nilsreichardt** [firebase/flutterfire#10576]
## Bug report

**Describe the bug**

I tried to upload a file with the `firebase_storage` example. However, it's always stuck at 0 bytes.

https://user-images.githubusercontent.com/24459435/223843053-1239cca4-542e-4e73-b9f6-bf1a674ec135.mov

### Steps to reproduce

1. Use example
2. Try to upload a file (I tested it via web)

### Expected behavior

Should upload the file.

### Sample project

Use the example of `firebase_storage` or https://zapp.run/edit/firebasestorage-11015-zj6y060aj6z0?entry=lib/main.dart&file=lib/main.dart

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Flutter 3.7.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 12cb4eb7a0 (7 days ago) • 2023-03-01 10:29:26 -0800
Engine • revision ada363ee93
Tools • Dart 2.19.3 • DevTools 2.20.1
```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the report. I am seeing same behavior running the example on web:

<img width="574" alt="Screenshot 2023-03-09 at 3 35 45 PM" src="https://user-images.githubusercontent.com/67046386/223990834-92b33420-2ed3-4e82-ad8f-bedb669591ea.png">

While, on mobile (iOS simulator), I get below:

<img width="343" alt="Screenshot 2023-03-09 at 3 40 31 PM" src="https://user-images.githubusercontent.com/67046386/223990949-57ec72e2-5700-48ea-bc5a-a37c171fe94c.png">

`flutter: [firebase_storage/unknown] An unknown error occurred, please check the server response.`
