### ISSUE TITLE
error in android build

### ISSUE THREAD

**Issue by syedajmal1998** [firebase/flutterfire#10587]
error with firebase_auth version 4.2.10

```
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':firebase_auth' of type org.gradle.api.Project.
   > Could not find method implementation() for arguments [project ':firebase_core'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
   > Could not get unknown property 'android' for project ':firebase_auth' of type org.gradle.api.Project.

```
env:
- gradle: 7.5.1
- flutter: 3.7.7

**Comment by syedajmal1998** [comment]
sorry this error is for firebase_auth

**Comment by darshankawar** [comment]
@syedajmal1998 
I am unable to replicate this error. My sample has same env as you mentioned and then added `firebase_auth` and ran `flutter run` as well as `flutter build apk` which were successful without any issues.

Make sure all other flutterfire plugins are on latest versions and there is no cache. Try cleaning your pub cache and then run `flutter clean` to see if it helps or not.
