### ISSUE TITLE
[App_Check] Play integrity - Error 403: Failure to Recognize App Check Data

### ISSUE THREAD

**Issue by iAmTosuj** [firebase/flutterfire#10584]
## Bug report

**Describe the bug**
Debug and SefetyNet providers works well, but play integrity doesn't work in production (from Google play)

Error getting App Check token. Error: com.google.firebase.FirebaseException: Error returned from API. code: 403 body: App attestation failed.

### Expected behavior

It should be able to sign in correctly without any bug.

### Sample project

there is no way to upload the example in google play

---

## Additional context

Debug provider with debug token work well
SefetyNet in production work well
Play Integrity in production doesn't work

Google play linked with Google cloud play integrity api

All settings and SHA-256 similar with SefetyNet. 

<img width="889" alt="image" src="https://user-images.githubusercontent.com/54905525/224244109-fd247f75-a2f8-4371-b7d7-3193cd96a794.png">

all settings do with 
https://firebase.google.com/docs/app-check/flutter/default-providers?hl=en
https://firebase.google.com/docs/app-check/android/play-integrity-provider?hl=en

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.7.6, on macOS 12.5.1 21G83 darwin-x64, locale ru-RU)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
  firebase_core: ^2.7.0
  firebase_app_check: ^0.1.1+13
  firebase_messaging: 14.0.4
  firebase_analytics: ^10.1.4
  firebase_crashlytics: ^3.0.15
  firebase_remote_config: ^3.0.13
  firebase_app_installations: ^0.2.1+12
```

</details>

---

**Comment by darshankawar** [comment]
@iAmTosuj 
Looking at the error you are getting `Error returned from API. code: 403 body: App attestation failed.`, take a look at this native issue and comment for your further reference: https://github.com/firebase/firebase-js-sdk/issues/6708#issuecomment-1376123046



> but play integrity doesn't work in production (from Google play)

This may not be related to flutterfire and unactionable. You can also check https://stackoverflow.com/questions/72631258/android-app-check-play-integrity-not-work for your reference and see if it helps.
I'll go ahead and close from here. If you disagree, write in comments and I'll reopen it.
