### ISSUE TITLE
🐛 [firebase_messaging] Missing support for communication notifications (dynamic icon avatar)

### ISSUE THREAD

**Issue by fullflash** [firebase/flutterfire#10608]
Hi.
it seems firebase service or client side plugin has no support for push notifications with dynamic icon.
Like you can see in slack whatsapp the users avatar instead of application icon.

Did not find anything in docs.

Will there be a support ?

**Comment by darshankawar** [comment]
@fullflash 
Take a look at [this](https://stackoverflow.com/questions/43303218/dynamic-notification-icon-for-firebase-cloud-messaging) link and see if it helps.

**Comment by fullflash** [comment]
Yes but you cannot release an app with users avatar all the time)
It should be dynamic like whatsapp does
And this is push notifications should be natively implemented inside plugin.

**Comment by darshankawar** [comment]
> It should be dynamic like whatsapp does

I am not sure what this means. I couldn't find any reference for such request in native SDK as well. 


> And this is push notifications should be natively implemented inside plugin.

Do you mean at Dart side or native (Android or iOS) ?

**Comment by fullflash** [comment]
Hi. this is communication notifications request like in many communication apps.
there is a ios plugin https://github.com/lambiengcode/ios_communication_notification
also you can see the apple docs https://developer.apple.com/documentation/usernotifications/implementing_communication_notifications

Everyone is using whatsapp and you can see the senders avatar in push notifications for android and ios platforms.

P.S
it is a feature like notification service but it is for using custom avatar you can see in the apple docs. 

 https://firebase.flutter.dev/docs/messaging/apple-integration/#step-1---add-a-notification-service-extension

**Comment by darshankawar** [comment]
@fullflash 
Since the plugin is a thin wrapper around native SDK, I think the said feature will need to be implemented at native side which the client side can leverage.
