### ISSUE TITLE
no  Document found  how to  call all data from a  firestore  collection  cache  when app is online

### ISSUE THREAD

**Issue by samithe7** [firebase/flutterfire#10602]
https://github.com/firebase/flutterfire/discussions/10601

**Comment by samithe7** [comment]
https://github.com/firebase/flutterfire/discussions/10601

**Comment by samithe7** [comment]
```dart

final snapshot = await documentReference.get(GetOptions(source: Source.serverAndCache));
```


this solve  my   issue  . thanks 
but  firebase  Documentation how to handle   cache is very poor

**Comment by darshankawar** [comment]
Good to know your issue is resolved. Closing as such.
