### ISSUE TITLE
🐛 [firebase_dynamic_links] Empty utmParameters

### ISSUE THREAD

**Issue by GustekDev** [firebase/flutterfire#10627]
## Bug report

**Describe the bug**
App opens correctly when using dynamic link but `utmParameters` is always empty.

### Steps to reproduce

1. Create Dynamic link with UTM parameters
2. Open app using this link, you may be able to use the link I created (https://flutterfiretests.page.link/4D6z or https://flutterfiretests.page.link?utm_campaign=test_campaing&amv=0&apn=io.flutter.plugins.firebase.dynamiclinksexample&ibi=io.flutter.plugins.firebase.dynamiclinksexample&imv=0&link=https%3A%2F%2Fexample%2Fhelloworld&utm_medium=test_medium&utm_source=test_source )

### Expected behavior

`utmParamters` property should have the parameters you set but is an empty map.

### Sample project

Cloned example and added the following changes to create a dynamic link with UTM parameters:
https://github.com/firebase/flutterfire/commit/46f64fceab3a54127c41f29a03cbd9038e44cbe5

You can see the link got created correctly by clicking on getLongLink
<img width="481" alt="image" src="https://user-images.githubusercontent.com/1414810/226488388-1b3f76b8-1962-4b09-b15a-920be50fbdc6.png">
In logs after opening the app using the link we get:
```
I/flutter (22865): PendingDynamicLinkData({ios: null, android: {clickTimestamp: 1679355108966, minimumVersion: 0}, link: https://example/helloworld, utmParameters: {}})
```

---

## Additional context

In my own app I can see it gets correctly logged in DebugView 
<img width="682" alt="image" src="https://user-images.githubusercontent.com/1414810/226486383-2a230ba8-568b-4281-addd-60d81f30466e.png">

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.7, on macOS 13.2.1 22D68 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
[✓] VS Code (version 1.75.1)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
flutter pub deps -- --style=compact
Dart SDK 2.19.4
Flutter SDK 3.7.7
firebase_dynamic_links_example 0.0.0

dependencies:
- firebase_core 2.8.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_dynamic_links 5.0.17 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- flutter 0.0.0 [characters collection js material_color_utilities meta vector_math sky_engine]
- url_launcher 6.1.10 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]

transitive dependencies:
- _flutterfire_internals 1.0.18 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.10.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.2.1
- clock 1.1.1
- collection 1.17.0
- fake_async 1.3.1 [clock collection]
- firebase_core_platform_interface 4.5.3 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.2.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_dynamic_links_platform_interface 0.2.3+32 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection js matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- js 0.6.5 [meta]
- matcher 0.12.13 [meta stack_trace]
- material_color_utilities 0.2.0
- meta 1.8.0
- path 1.8.2
- plugin_platform_interface 2.1.4 [meta]
- sky_engine 0.0.99
- source_span 1.9.1 [collection path term_glyph]
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.4.16 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- url_launcher_android 6.0.25 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.1.3 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.4 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.4 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.2 [flutter plugin_platform_interface]
- url_launcher_web 2.0.16 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.5 [flutter url_launcher_platform_interface]
- vector_math 2.1.4
```

</details>

---

**Comment by GustekDev** [comment]
I did see it but I don't see any solutions there.
Looks like it works for some people, but no one seems to know why.

In my provided sample I have used example app, and it is not working, in that issues someone got it working supposedly out of box, so I don't know what is missing, did I setup the example project incorrectly?

**Comment by darshankawar** [comment]
Thanks for the update. In the example you shared, I see that you have also included analytics to send the events. If you remove the analytics code implementation and try again ?
From [this](https://github.com/firebase/flutterfire/issues/8954#issuecomment-1412041357) comment, the team member used the example app too.

**Comment by GustekDev** [comment]
These analytics are what is meant to be in `utmParameters` I have no idea how he got them without ever setting them. Maybe he created the link by some other means.

Anyway, I made this change https://github.com/firebase/flutterfire/commit/96480c95618ff3abb36256dcb58acd8533d4634a

Long link that was generated is:
https://flutterfiretests.page.link?amv=0&apn=io.flutter.plugins.firebase.dynamiclinksexample&ibi=io.flutter.plugins.firebase.dynamiclinksexample&imv=0&link=https%3A%2F%2Fexample%2Fhelloworld

and I received `I/flutter ( 6953): YYYY: {}`
which is expected in this case as you can see `utmParameters` are not set in this this long link.

In my initial example I have set them, you can see them in the long link but they are not present in the  `utmParameters` map.

**Comment by darshankawar** [comment]
Using the example you shared [here](https://github.com/firebase/flutterfire/commit/46f64fceab3a54127c41f29a03cbd9038e44cbe5) and running on Android emulator, I am seeing `link: https://example/helloworld, utmParameters: {}}`,

But then using the example without changes, I the long link generated doesn't have utm param set so get same behavior as commented [above](https://github.com/firebase/flutterfire/issues/10627#issuecomment-1483821042).

Will keep this issue open for team's thoughts.

/cc @russellwheatley

**Comment by flodaniel** [comment]
We are also seeing this with the latest versions of firebase. It works perfectly on iOS but on android the utmParameters are always `{}`, no matter if we generate the link through the REST API or the web console.

**Comment by russellwheatley** [comment]
If it is empty, I'm not sure this is an FF issue. We correctly parse out the values and pass back through the method channel. I've tested this before and it works. The question is; what is different about your setup from the one I am using? I create the UTM parameters on the dynamic link in the Firebase console.
