### ISSUE TITLE
🐛 [firebase_analytics] Purchase event custom dimensions

### ISSUE THREAD

**Issue by ndilworth** [firebase/flutterfire#10634]
## Bug report

**Describe the bug**
The firebase analytics package provides a preconfigured logPurchase event which does not have the full set of GA4 variables or allow for custom dimensions. We created our own 'purchase' event using logEvent to send these custom dimensions, including the list of items. A recent minor version change to the package has added an assert to block sending non-string, non-num values to logEvent, meaning we cannot use our own purchase event to send items, and we cannot use the preconfigured logPurchase event as it does not have our custom dimensions.

Related bug: https://github.com/firebase/flutterfire/issues/10270
Related PR: https://github.com/firebase/flutterfire/pull/9520

Was using: firebase_analytics: 10.0.6
Now using: firebase_analytics: 10.1.4

### Steps to reproduce

1. Try to send items list to logEvent, assertion fails
2. Unable to send custom dimensions to logPurchase

### Expected behavior

Options:
1. Remove assert
2. Allow sending items to logEvent
3. Able to send custom dimensions to logPurchase, and probably all events as the firebase_analytics package does not support all the available GA4 variables.

**Comment by darshankawar** [comment]
@ndilworth 
There's similar open issue describing your case, https://github.com/firebase/flutterfire/issues/10629 so follow-up in it for further updates. Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.
