### ISSUE TITLE
🐛 Error Expected a value of type 'object'

### ISSUE THREAD

**Issue by nagy1991** [firebase/flutterfire#10632]
If I run it in Visual Studio Code, in debug operation mode, I get the following error.
<img width="1281" alt="Képernyőfotó 2023-03-21 - 17 29 29" src="https://user-images.githubusercontent.com/33298622/226706115-dc8f97ab-20ed-4f77-9f84-4429bb963271.png">

**Comment by danagbemava-nc** [comment]
Hi @nagy1991, 

I just ran the firebase_core example and it worked just fine for me. 

Please provide a complete code sample preferably in a repo that we can clone and run so that we can investigate this issue. 

Thank you
