### ISSUE TITLE
🐛 FirebaseError: Firebase: Need to provide options

### ISSUE THREAD

**Issue by nagy1991** [firebase/flutterfire#10633]
If I run it in Visual Studio Code, in debug operation mode, I get the following error.
<img width="1313" alt="Képernyőfotó 2023-03-21 - 17 30 12" src="https://user-images.githubusercontent.com/33298622/226706647-f84cbfe9-949a-4921-89d8-cd0ce2a73120.png">

**Comment by darshankawar** [comment]
Closing this as duplicate of https://github.com/firebase/flutterfire/issues/10228. Follow-up in it for further updates and see underlying comments for further reference.
