### ISSUE TITLE
🐛 [firebase_notification] "Notifications are not allowed for this application" - how fix it?

### ISSUE THREAD

**Issue by FetFrumos** [firebase/flutterfire#10669]
I have flutter app. It is working for iOS. now I try to run it on macos - I have problems:

1. I added GoogleService-Info.plist to my macos/runner

2. my app uses firebase_messaging(for push notification)

      ```
     final settings = await FirebaseMessaging.instance.requestPermission(
     announcement: true,
     carPlay: true,
     sound: true,
    criticalAlert: true,);
    ```
    
  this code returns an error:
  
  `[firebase_messaging/unknown] Notifications are not allowed for this application  `
  
  Found this [discussion](https://github.com/firebase/flutterfire/issues/5473)
  
  but I don't see my app there. i installed it via TestFlight - but that didn't help either, the app is not listed.

how do i solve this problem? any advice - I will be grateful

also i don't know how to configure my app properly. I found this [document](https://firebase.flutter.dev/docs/manual-installation/macos/) but there are no details (what permissions are needed and other details)

**Comment by darshankawar** [comment]
> I found this [document](https://firebase.flutter.dev/docs/manual-installation/macos/) but there are no details (what permissions are needed and other details)

The document you referred is archived. You should refer to https://firebase.google.com/docs/cloud-messaging/flutter/client going forward. Although it also doesn't have specific steps related to macOS desktop in general.

I think you should refer to https://github.com/invertase/flutterfire_desktop for desktop related plugin usage and see if it helps in your case.

Regarding the issue you reported, I don't think there's any action required from flutterfire client side on this. You can refer the discussion you linked.
Closing for now. If you disagree, write in comments and I'll reopen it.
