### ISSUE TITLE
🐛 [firebase_messaging 14.3.0] C:\Users\Admin\AppData\Local\Pub\Cache\hosted\pub.dev\firebase_messaging-14.3.0\android\src\main\java\io\flutter\plugins\firebase\messaging\FlutterFirebaseMessagingPlugin.java uses unchecked or unsafe operations.

### ISSUE THREAD

**Issue by k2209** [firebase/flutterfire#10660]
## Bug report

When taking the build  i am facing this error
![image](https://user-images.githubusercontent.com/88879550/227785740-9bf7c6b1-7dc4-4aaa-b597-9d10c7759e80.png)

the build is getting completed but when i change the build.gradle config to release the i take the build but when i try to install it in my device it's giving me this kind of error 

![WhatsApp Image 2023-03-26 at 20 55 47](https://user-images.githubusercontent.com/88879550/227786012-7b25fa80-fba7-4e7b-b1a2-5d2d416ebb5d.jpg)

i tried cleaning the project even i made the new project still the same error

**Comment by darshankawar** [comment]
@k2209
For `firebase_messaging-14.3.0\android\src\main\java\io\flutter\plugins\firebase\messaging\FlutterFirebaseMessagingPlugin.java uses unchecked or unsafe operations`, follow-up in [original](https://github.com/firebase/flutterfire/issues/8073) issue.

For `Play Protect doesn't recognise this app's developer.`, issue, this isn't specific to messaging plugin or flutterfire, you should search on support channels like StackOverflow for solution: https://www.google.com/search?q=Play+Protect+doesn%27t+recognise+this+app%27s+developer.&oq=Play+Protect+doesn%27t+recognise+this+app%27s+developer.&aqs=chrome..69i57j0i22i30l2j0i390i650l3j69i60.253j0j7&sourceid=chrome&ie=UTF-8
