### ISSUE TITLE
firebase storage image not showing on iOS when Apple reviewer review the app

### ISSUE THREAD

**Issue by hussenIbrahim** [firebase/flutterfire#10672]
all API work without any issue on android and simulator and real iOS devices
TestFlight version also works
only during review process firebase storage image links throw error

SocketException: Connection refused (OS Error: Connection refused, errno= 61), address = firebasestorage.googleapis.com, port = 63689
iPad iOS 16.3.1

**Comment by Fr099y** [comment]
@hussenIbrahim  Did you solve this problem? I have the same issue and tried a few times but no luck.

**Comment by hussenIbrahim** [comment]
No its related to Apple reviewers networks
Check this [Thread](https://developer.apple.com/forums/thread/725134)
