### ISSUE TITLE
🐛 [Housekeeping] Workflows should only run when relevant files are changed

### ISSUE THREAD

**Issue by jhuleatt** [firebase/flutterfire#10681]
## Bug report

To make it easier to contribute to the repository with faster CI, only relevant checks should run on a PR.

### Expected behavior

Only the checks relevant to a specific PR should run.

**Comment by russellwheatley** [comment]
I think we have suitable checks for when to run e2e tests which is the workflow that takes the most amount of time. See: https://github.com/firebase/flutterfire/blob/master/.github/workflows/e2e_tests.yaml#L7-L25

I'll reopen if you have any further suggestions 😄
