### ISSUE TITLE
[cloud_firestore] "An initial event is immediately sent" is not clear if it's synchronous or asynchronous

### ISSUE THREAD

**Issue by tony-ditchlabs** [firebase/flutterfire#10689]
[In document_reference.dart](https://github.com/firebase/flutterfire/blob/master/packages/cloud_firestore/cloud_firestore/lib/src/document_reference.dart), line  55 or so, the documentation for `snapshots` reads as follows:

```
/// Notifies of document updates at this location.
///
/// An initial event is immediately sent, and further events will be
/// sent whenever the document is modified.
```

It's not clear what "immediately" means - if an empty snapshot will be returned at once, and then another snapshot will be sent once the data is retrieved from Firestore, or if a snapshot will be returned *nearly* immediately, with a short async break while the data is retrieved from Firestore. In short, is it returning immediately sync or async?

**Comment by tony-ditchlabs** [comment]
When this doc comment is updated, it would be helpful to include other information about the stream, specifically if it's a broadcast stream or not, what errors are possible, and under what conditions (if any) the stream is closed and the `onDone` handler would ever be fired.

**Comment by tony-ditchlabs** [comment]
Oh no, I found something even more peculiar. This might be a bug?

Psudeo-code:

```
var sub = _firestore.collection("somePath") .where("uid", isEqualTo: "x").listen(handler);
// [handler] is triggered immediately
await Future.delayed(Duration(seconds:5));
sub.cancel();
// Stream subscription is cancelled... right?
// Let's re-create it:
sub = _firestore.collection("somePath") .where("uid", isEqualTo: "x").listen(handler);
// [handler] is not triggered... at all
```

It seems like I'm expecting each instance of the stream to fire an event "immediately", but the streams are cached, so the first one fires an event, and the second one re-uses the first stream, so no event is fired.

**Comment by russellwheatley** [comment]
It is asynchronous, it has to go to the native platform. Furthermore, it isn't blocking the program unlike a synchronous API call. Ultimately, this is just a wrapper around the Firebase native SDKs `onSnapshot` handlers which you can read about [here](https://firebase.google.com/docs/firestore/query-data/listen)
