### ISSUE TITLE
[housekeeping] Workflow permissions

### ISSUE THREAD

**Issue by jhuleatt** [firebase/flutterfire#10684]
As part of the [OSSF recommendations](https://github.com/firebase/flutterfire/pull/10682), we've changed the default permissions to workflows to read-only. That means that any workflow that needs write permissions will have to set it in their yaml file ([docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions)). This issue is an FYI in case workflows break as a result of this change.

**Comment by Lyokone** [comment]
Hello @jhuleatt thanks for the heads up.
