### ISSUE TITLE
🐛 [firebase_app_check] `Semantic Issue (Xcode): 'new' is unavailable` after upgrading xcode

### ISSUE THREAD

**Issue by mdddj** [firebase/flutterfire#10694]
![image](https://user-images.githubusercontent.com/29020213/229021899-5210b2d0-67c2-4c26-b3f2-a7641c632441.png)

```dart
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.8, on macOS 13.3 22E252 darwin-arm64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)                           [✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.3)
[✓] VS Code (version 1.76.2)
[!] Proxy Configuration
    ! NO_PROXY does not contain ::1
[✓] Connected device (4 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

**Comment by baekjungkim** [comment]
same issue.
I changed it to 'alloc' and using it.

**Comment by danagbemava-nc** [comment]
Hi @mdddj, is this error only on Xcode 14.3? or did you get this error before the upgrade?

**Comment by mdddj** [comment]
> 

Yes, it didn't appear until xcode was upgraded.

**Comment by jpetro416** [comment]
Same issue here

**Comment by jpetro416** [comment]
> same issue. I changed it to 'alloc' and using it.

Will this "stick" for the compile process? Or does compiling ignore a manual change like that?

**Comment by Jethro87** [comment]
Same issue here since upgrading xcode:

```
Failed to build iOS app
Could not build the precompiled application for the device.
Semantic Issue (Xcode): 'new' is unavailable
```

**Comment by YDA93** [comment]
Happened to me after I upgraded Xcode.
I updated my iPhone and Mac as well but no results.

**Comment by YDA93** [comment]
My current workaround is to switch to older version of Xcode.

And here is the way:

[https://stackoverflow.com/questions/14756026/how-to-downgrade-xcode-to-previous-version](url)

**Comment by StevenSnary** [comment]
Same issue here - I can confirm this occurred after updating to the latest Xcode version 14.3 (14E222b).
Note: I am also using iOS 16.4

**Comment by Theunodb** [comment]
> same issue.
> I changed it to 'alloc' and using it.

This tmp workaround will get your app to compile while we wait for an update

**Comment by danagbemava-nc** [comment]
I attempted to reproduce this locally but I'm running into an issue with cocoapods. Similar to https://github.com/CocoaPods/CocoaPods/issues/11808#issuecomment-1481244508

Labeling for further investigation from the team. 

cc @Lyokone 

```
Launching lib/main.dart on Nexus in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: X8NNQ9CYL2
Running pod install...
Running Xcode build...
Xcode build done.                                            6.1s
Failed to build iOS app
Could not build the precompiled application for the device.
Error (Xcode): File not found: /Applications/Xcode-14.3.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphoneos.a

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

Error launching application on Nexus.
```

**Comment by bifrostyyy** [comment]
> I attempted to reproduce this locally but I'm running into an issue with cocoapods. Similar to [CocoaPods/CocoaPods#11808 (comment)](https://github.com/CocoaPods/CocoaPods/issues/11808#issuecomment-1481244508)
> 
> Labeling for further investigation from the team.
> 
> cc @Lyokone
> 
> ```
> Launching lib/main.dart on Nexus in debug mode...
> Automatically signing iOS for device deployment using specified development team in Xcode project: X8NNQ9CYL2
> Running pod install...
> Running Xcode build...
> Xcode build done.                                            6.1s
> Failed to build iOS app
> Could not build the precompiled application for the device.
> Error (Xcode): File not found: /Applications/Xcode-14.3.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphoneos.a
> 
> Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)
> 
> Error launching application on Nexus.
> ```

This has to do with https://github.com/flutter/flutter/issues/123903 . Solution is to upgrade min deployment target for all Pods to `11.0` (or greater) by adding the following to your `Podfile`:
```
installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
         end
    end
  end
```

The issue is, once you do this and get past the CocoaPods error, if you depend on `firebase_app_check`, you get this error.

**Comment by bifrostyyy** [comment]
In the meantime, I'm personally just downgrading to XCode 14.2 until Flutter + CocoaPods update to not require these workarounds. Easier than trying to play whack-a-mole w/ different libraries :)

**Comment by loolooii** [comment]
Every time there's an update from Xcode we are forced to download it (because we can't run the app on our device), it's at least 7GB large, it's slow, AND it causes problems every time. Apple should be more careful about doing this.

A temporary solution is to replace those `new` keywords to `alloc`.

**Comment by danagbemava-nc** [comment]
After working around the issue with `level-db`, I can reproduce the issue.

Changing `new` to `alloc` at the lines in the error allowed the app to run.

```
Launching lib/main.dart on Nexus in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: X8NNQ9CYL2
Running Xcode build...
Xcode build done.                                           164.4s
Failed to build iOS app
Could not build the precompiled application for the device.
Semantic Issue (Xcode): 'new' is unavailable
/Users/nexus/.pub-cache/hosted/pub.dev/firebase_app_check-0.1.2/ios/Classes/FLTAppCheckProvider.m:18:55

Semantic Issue (Xcode): 'new' is unavailable
/Users/nexus/.pub-cache/hosted/pub.dev/firebase_app_check-0.1.2/ios/Classes/FLTAppCheckProvider.m:22:53

Semantic Issue (Xcode): 'new' is unavailable
/Users/nexus/.pub-cache/hosted/pub.dev/firebase_app_check-0.1.2/ios/Classes/FLTAppCheckProvider.m:30:57


Error launching application on Nexus.
```

**Comment by Lyokone** [comment]
Flutter issued a new release supposed to fix this: https://groups.google.com/g/flutter-announce/c/9qZL8GOVNb4
Can you check if it also fixes the issue with firebase_app_check?

**Comment by mdddj** [comment]
> Flutter issued a new release supposed to fix this: https://groups.google.com/g/flutter-announce/c/9qZL8GOVNb4 Can you check if it also fixes the issue with firebase_app_check?

After updating to version 3.3.10, there were no noticeable changes.

**Comment by dsgriffin** [comment]
> Flutter issued a new release supposed to fix this: https://groups.google.com/g/flutter-announce/c/9qZL8GOVNb4 Can you check if it also fixes the issue with firebase_app_check?

Sadly the Flutter `3.10` upgrade didn't fix this app `firebase_app_check`

**Comment by AresVampire** [comment]
it still happens with Flutter 3.7.10

**Comment by otopba** [comment]
Same issue

**Comment by FetFrumos** [comment]
when can we expect an update?
