### ISSUE TITLE
🐛 [firebase_crashlytics] unable to upload symbols [Android] [iOS]

### ISSUE THREAD

**Issue by juliansteenbakker** [firebase/flutterfire#10691]
## Bug report

I have followed [all steps provided here](https://firebase.google.com/docs/crashlytics/get-started?platform=flutter#add-sdk), however when i execute `firebase crashlytics:symbols:upload --app=1:{redacted}:android:{redacted} /{redacted}/v0.8.17+76/` i get the following error:
```sh
i  Generating symbols for /{redacted}/v0.8.17+76
⚠  [CRASHLYTICS LOG DEBUG] Crashlytics Buildtools initialized.
[CRASHLYTICS LOG DEBUG] Skipping dumpsyms extraction, file exists: /{redacted}/.crashlytics/dump_syms.bin
[CRASHLYTICS LOG DEBUG] Breakpad symbol generator initialized: /{redacted}/.crashlytics/dump_syms.bin
java.io.IOException: Unstripped native library path does not exist: /{redacted}/v0.8.17+76. Either specify the correct unstrippedNativeLibsDir or disable Crashlytics symbol uploading.
        at com.google.firebase.crashlytics.buildtools.Buildtools.generateNativeSymbolFiles(Buildtools.java:230)
        at com.google.firebase.crashlytics.buildtools.CommandLineHelper.executeGenerateSymbols(CommandLineHelper.java:185)
        at com.google.firebase.crashlytics.buildtools.CommandLineHelper.executeCommand(CommandLineHelper.java:118)
        at com.google.firebase.crashlytics.buildtools.CommandLineHelper.main(CommandLineHelper.java:65)
        at com.google.firebase.crashlytics.buildtools.Buildtools.main(Buildtools.java:111)


Error: java command failed with args: -jar,/{redacted}/.cache/firebase/crashlytics/buildtools/crashlytics-buildtools-2.9.2.jar,-symbolGenerator,breakpad,-symbolFileCacheDir,/var/folders/jv/ybbxkhb102q2phfpjr8nqdyr0000gn/T/crashlytics-2041827f-7af0-439f-8de5-f70ae8173287/nativeSymbols/1-{redacted}android-{redacted}/breakpad,-verbose,-generateNativeSymbols,-unstrippedLibrary,/{redacted}/v0.8.17+76,-clientName,firebase-cli;crashlytics-buildtools

Having trouble? Try firebase [command] --help
```

This is the same for iOS.
All my dart code is obfuscated in crashlytics, which makes it difficult to debug due to having to symbolize it all manually.

---

## Additional context

The files in my directory:
<img width="280" alt="image" src="https://user-images.githubusercontent.com/20091319/228844308-2e7ee657-e759-45f9-a635-12b53a3562d3.png">

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.8, on macOS 13.2.1 22D68 darwin-x64, locale nl-NL)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.74.3)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

```

</details>

**Comment by danagbemava-nc** [comment]
Hi @juliansteenbakker, what version of firebase tools are you using? I just attempted to upload the symbols and it worked just fine (for android, I haven't tested iOS yet). 

```
firebase crashlytics:symbols:upload --app=1:810996112226:android:94897a50bd464125deaa3b ./debug_symbols/
i  Generating symbols for ./debug_symbols/
i  Generated symbols for ./debug_symbols/
i  Output Path: /var/folders/p0/m30kv62s231_1_zc_vxb_xqw0000gn/T/crashlytics-b896d06e-13f8-43d0-87f0-6183c3ba9e32/nativeSymbols/1-810996112226-android-94897a50bd464125deaa3b/breakpad
i  Uploading all generated symbols...
i  Successfully uploaded all symbols
```

**Comment by juliansteenbakker** [comment]
Im using version `11.25.2`. Do you have the same files in the `./debug_symbols/` directory as me?

**Comment by danagbemava-nc** [comment]
These are the files I have in that folder. 

If you move the `app-release.aab`  & the `Runner.archive` files to a different folder, does it have any effect on the upload? I'm wondering if the non-symbol files are intefering somehow

<img width="430" alt="Screenshot 2023-03-31 at 12 49 05" src="https://user-images.githubusercontent.com/88313112/229124329-47bf58f9-3136-4c66-9947-54ec303b6f8f.png">

**Comment by juliansteenbakker** [comment]
Hmm, i have moved the files to another location so i only have the exact same files you have. However, i still get the exact same error message..

However, i started thinking it has something to do with the special characters in the folder name `v0.8.17+76`, and it turns out the `+` symbol causes this issue!

I renamed the folder to `v0.8.17`, and now its working! Thanks for your help.

```
i  Generating symbols for /Users/x/Documents/version_history/v0.8.17
i  Generated symbols for /Users/x/Documents/version_history/v0.8.17
i  Output Path: /var/folders/jv/x/T/crashlytics-x-cfff-42fe-949f-a52e40cefca9/nativeSymbols/1-x-android-x/breakpad
i  Uploading all generated symbols...
i  Successfully uploaded all symbols
```
