### ISSUE TITLE
🐛 [firebase_app_check] Getting errors from users while calling getToken on iOS

### ISSUE THREAD

**Issue by yaylaselcuk** [firebase/flutterfire#10710]
There is no problem while testing and trying locally however after we sent it live we started getting following errors from real users on iOS.
These errors are collected by Crashlytics, can't be reproduced by me.

**Error Logs:**
Fatal Exception: FlutterError
[firebase_app_check/server-unreachable] The operation couldn’t be completed. API request error.

Fatal Exception: FlutterError
[firebase_app_check/unknown] The operation couldn’t be completed. The server responded with an error: - URL: https://firebaseappcheck.googleapis.com/v1/projects/project_name/apps/app_id:exchangeDeviceCheckToken - HTTP status code: 500 - Response body: { "error": { "code": 500, "message": "Internal error encountered.", "status": "INTERNAL" } }

**Comment by darshankawar** [comment]
Thanks for the report @yaylaselcuk 



> **Error Logs:** Fatal Exception: FlutterError [firebase_app_check/server-unreachable] The operation couldn’t be completed. API request error.
> 
> Fatal Exception: FlutterError [firebase_app_check/unknown] The operation couldn’t be completed. The server responded with an error: - URL: https://firebaseappcheck.googleapis.com/v1/projects/project_name/apps/app_id:exchangeDeviceCheckToken - HTTP status code: 500 - Response body: { "error": { "code": 500, "message": "Internal error encountered.", "status": "INTERNAL" } }

These errors probably indicate there could server side glitch as the HTTP status code is 500, so it could be due to various reasons.

As also you mentioned, there's no problem while testing and trying locally, I suggest you to reach out to [firebase support](https://firebase.google.com/support) to check if they can help.

**Comment by pitazzo** [comment]
We are getting exactly same error on iOS devices when trying to get the AppCheck token, no specific conditions

**Comment by yaylaselcuk** [comment]
Now I started to get only one type of error on Crashlytics. It is;

`Fatal Exception: FlutterError
[firebase_app_check/server-unreachable] The operation couldn’t be completed. API request error.`

There is no other details in the error description.

I will contact Firebase Support, let you guys know if I can get some answers from them.

**Comment by pitazzo** [comment]
I also contacted Firebase Support, and their response was quite poor. Somethings is wrong on the side of the DeviceCheck server, and there isn't much they can do about it.

> I have checked your case and everything points to these issues being due to a [server error](https://developer.apple.com/documentation/devicecheck/assessing_fraud_risk) from the DeviceCheck side, when these kinds of errors happen, you may try to get the token again as it is probable that something went wrong on the server side. 
>
> Unfortunately, this is something out of our control, however, if this issue continues to happen, be so kind as to share with me more details about it, like a timestamp, device model, OS version and SDK version where you're seeing the error. We can share this information to our engineering team so that they can take a look at it.
>
> I hope this information works for you, if you have more questions, don't hesitate to ask.
