### ISSUE TITLE
🐛 [firebase_messaging] Firebase Android app terminated or closed app notifications are not able to be received!

### ISSUE THREAD

**Issue by chanrlc2015** [firebase/flutterfire#10717]
## Bug report

**Describe the bug**
Firebase Android app terminated or closed app notifications are not able to be received! nothings can receive from FCM! 
I am using the example code still have this issues.

### Steps to reproduce

 I am tested in debug mode!

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example/lib

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.8, on Microsoft Windows [Version 10.0.19044.2728], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[!] Visual Studio - develop for Windows (Visual Studio Community 2017 15.9.10)
    X Visual Studio 2019 or later is required.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2020.3)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.71.0)
[√] Connected device (4 available)
[√] HTTP Host Availability

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

 
  cupertino_icons: ^1.0.2
  screen_brightness: 0.2.2
  screen_brightness_platform_interface: ">=0.1.0 <1.0.0"
  flutter_web_browser: ^0.15.0
  flutter_session_manager: ^1.0.1
  webview_flutter: ^3.0.1
  shared_preferences: ^2.0.0
  encrypt: ^5.0.0
  http: ^0.13.4
  intl: ^0.17.0
  qr_flutter: ^4.0.0
  firebase_core: ^2.1.0
  firebase_messaging: ^14.2.6
  flutter_local_notifications: ^12.0.3
  client_information: ^2.0.0
  firebase_core_platform_interface: ^4.5.3
  flutter_clean_calendar: ^1.1.0

</details>

---

**Comment by darshankawar** [comment]
Thanks for the report @chanrlc2015 
Is it occuring on emulators or with physical devices too ?
Can you also confirm that the device you are seeing this on, doesn't have any settings that might be preventing notifications to trigger / arrive ?

Also, I see there are lot of other / community packages you shared as dependencies, so try without using any of those package implementations and check if you still get same behavior or not.

**Comment by chanrlc2015** [comment]
I tested, message can be resumed. However, the terminated notifications still not able to receive! But the iOS notifications is able to receive via APN.

**Comment by darshankawar** [comment]
@chanrlc2015 
Can you provide a sample payload that you are sending ? Also can you try to use `getNotificationAppLaunchDetails()` method to check whether app was launched by notification and see if it helps ?

**Comment by chanrlc2015** [comment]
I didn't place anything in payload, `getNotificationAppLaunchDetails()` didn't return anything!

```
{ 
    "to" :  %device token%,      
    "notification": {       
        "body": "This is a MPU body!!!!!",
        "title": "This is a MPU title!!!",
        "sound": "default"
    },
    "priority": "high"
}
```

```
final NotificationAppLaunchDetails? notificationAppLaunchDetails = await flutterLocalNotificationsPlugin.getNotificationAppLaunchDetails();

  if (notificationAppLaunchDetails?.didNotificationLaunchApp ?? false) {

    log('getNotificationAppLaunchDetails: '+ notificationAppLaunchDetails!.notificationResponse!.payload.toString());
  }
```

**Comment by darshankawar** [comment]
@chanrlc2015 
According to the [documentation](https://firebase.google.com/docs/cloud-messaging/flutter/receive):

`On Android, if the user force-quits the app from device settings, it must be manually reopened for messages to start working.`

See it it helps. If not, can you try something like below and see if it works or not ?

```
data = {
      "message": {
        "topic": topic,
        "data": {
          "title": "Title",
          "body": "Body",
        },
        "android": {"priority": "high"},
        "apns": {
          "headers": {"apns-priority": "10"},
          "payload": {
            "aps": {"badge": 1},
            "content-available": true
          }
        }
      }
    };

headers = {
      'content-type': 'application/json',
      'Authorization': 'Bearer $token'
    };
```

**Comment by chanrlc2015** [comment]
I tried. This code doesn't work, device token is not there.

**Comment by chanrlc2015** [comment]
I have another question is how to test it in the release mode since terminated app can't be tested in debug mode on Android device?

**Comment by darshankawar** [comment]
> E/FrameEvents(21478): updateAcquireFence: Did not find frame.

This log isn't related to the plugin but from native. You may check for similar issues filed in flutter repo or on stackoverflow.



> how to test it in the release mode since terminated app can't be tested in debug mode on Android device?
> 
> `flutter build apk --release && flutter install` can run the app in release mode.

That is correct. It will build an apk and once installed on your device, you can send notifications and confirm if all the handlers are being triggered properly.

Coming back to your original issue, I tried with the plugin example on Android device, but can't seem to replicate the reported behavior.

I'll keep this open for team's input / feedback.

**Comment by chanrlc2015** [comment]
Now, I'm using `FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);` to handle when the app is in the background or terminated state, I tested background message is work using data payload.
`https://www.youtube.com/watch?v=BVZ160KG5Kc&t=513s`

**Comment by chanrlc2015** [comment]
I tested terminated app notification on my VM Pixel phone. It is ok!

**Comment by AlvaroVasconcelos** [comment]
@darshankawar 
Any updates? I have the same problem!

**Comment by russellwheatley** [comment]
I've just tested this via `flutter run --release` on android 10 and 13. I was able to open the app via notifications from a terminated state. Closing out as it isn't an issue.

**Comment by chanrlc2015** [comment]
I changed to the latest version of FCM HTTP V1, It can be received both Android and iOS,  opened and terminated state notifications!

**Comment by dwkim891220** [comment]
in my case, can not received background or killed app state on only android.
did setting `click_action` to "OPEN_ACTIVITY" in data android payload json from fcm push server.
working correctly when delete `click_action` of fcm push send server.
who find solution of this related issue, please check server sdk, data format.

i want this comment is help to someone
