### ISSUE TITLE
🐛 [App_Check] Firebase Auth SMS authentication with PlayIntegrity 

### ISSUE THREAD

**Issue by yamauchieduardo** [firebase/flutterfire#10724]
**Description:**

I have been experiencing a significant increase in reCaptcha-related issues with numerous clients over the past few months (see issue [#10593](https://github.com/firebase/flutterfire/issues/10593)). My app currently only supports SMS authentication, and I am unable to use PlayIntegrity due to its limitations (see issues [#10467](https://github.com/firebase/flutterfire/issues/10467) and [#10174](https://github.com/firebase/flutterfire/issues/10174)).

![SMS Play Integraty limitation](https://user-images.githubusercontent.com/44825178/229919214-b752c172-2511-4aad-98a3-74d6cbf42636.png)

**Questions:**

1. Is there a roadmap for implementing Firebase Auth using PlayIntegrity?
2. As the reCaptcha API will be disabled in June, how can we address the issue of not being able to use PlayIntegrity for SMS login?

I am looking forward to your response and guidance on resolving these issues. Thank you!

**Comment by darshankawar** [comment]
@yamauchieduardo 
See [this](https://github.com/firebase/flutterfire/issues/10593) related / similar issue and below comments and check if they help:

https://github.com/firebase/flutterfire/issues/10593#issuecomment-1496102493
https://github.com/firebase/flutterfire/issues/10593#issuecomment-1496665701

**Comment by yamauchieduardo** [comment]
The play integraty have seraveral bugs, but I think in the future will be stable. Thanks for sharing @darshankawar
