### ISSUE TITLE
🐛 [firabase_auth] Apple Sign In not working on Android

### ISSUE THREAD

**Issue by tudor07** [firebase/flutterfire#10736]
## Bug report

Sign in with Apple is not working on Android.
It works fine on iOS.
It used to work with my previous implementation when I used `flutter_auth` + `sign_in_with_apple` plugin.
But now with the latest `firebase_auth` using the `AppleAuthProvider` class as per the documentation it does not work. The error is:
```
[firebase_auth/operation-not-allowed] The given sign-in provider is disabled for this Firebase project. Enable it in the Firebase console, under the sign-in method tab of the Auth section. [ Code flow is not enabled for Apple. ]
```

Which does not make any sense because the method is enabled in Firebase and it works on iOS or with my old implementation as I said.

### Sample project

This is my code:

```
  Future<UserInfo> loginWithApple() async {
    final appleProvider = AppleAuthProvider();
    appleProvider.addScope('email');
    appleProvider.addScope('fullName');
    try {
      final fbUser = await auth.signInWithProvider(appleProvider);
      final authProviderToken = await fbUser.user.getIdToken();

      return UserInfo(authProviderToken, fbUser.user.email);
    } on FirebaseAuthException catch (e) {
      print('ERROR: $e');
  }
```

---

## Additional context

`firebase_auth: 4.4.0`

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
octor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.7.9, on macOS 13.2 22D49 darwin-arm64, locale en-RO)
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.18.6/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/tudorwork/dev/flutter. Consider adding /Users/tudorwork/dev/flutter/bin to the front of your
      path.
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Community Edition (version 2023.1)
[✓] VS Code (version 1.77.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
- firebase_analytics 10.2.0 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 4.4.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.9.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 3.1.0 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_dynamic_links 5.1.0 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_messaging 14.4.0 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
```

</details>

---

**Comment by darshankawar** [comment]
@tudor07 
Thanks for the report. Are you getting the `IdToken` properly ? See this similar issue for your reference: https://github.com/firebase/flutterfire/issues/8865

**Comment by tudor07** [comment]
@darshankawar yes, `IdToken` works

**Comment by darshankawar** [comment]
Thanks for the update. I tried to replicate this using the plugin example running on Android, but seem to be getting a compile error `GetAuthDomainTask] Error getting project config. Failed with INVALID_CERT_HASH 400` which I'll look into to figure out and fix.

Meantime, I'll label this issue for team's thoughts.

/cc @Lyokone

**Comment by russellwheatley** [comment]
I've just tested this and it works fine. Have you enabled Apple sign in from your Firebase console? The message is saying you haven't configured the Apple provider.

**Comment by tudor07** [comment]
@russellwheatley I clearly mentioned in my ticket that it is enabled and working **with the old plugin**.

**Comment by russellwheatley** [comment]
It looks to me like something is misconfigured. It works on my end. It could be something cached (make a clean build), or maybe something is misconfigured on the Apple portal or maybe the values provided in the Apple sign in on the Firebase console are misconfigured. Please double check.

**Comment by tudor07** [comment]
if there were issues on Apple portal or Apple Sign In config in Firebase then the old plugin would also not work, but it does

**Comment by Zambrella** [comment]
> Thanks for the update. I tried to replicate this using the plugin example running on Android, but seem to be getting a compile error `GetAuthDomainTask] Error getting project config. Failed with INVALID_CERT_HASH 400` which I'll look into to figure out and fix.
> 
> Meantime, I'll label this issue for team's thoughts.
> 
> /cc @Lyokone

@darshankawar Did you get to the bottom of this? I'm running into this error when initiating the apple auth process on Android. It works fine on iOS and web.

**Comment by russellwheatley** [comment]
Closing out as no reproduction has been provided.
