### ISSUE TITLE
🐛 [firebase_messaging: ^14.4.0] onbackgroundmessage issue

### ISSUE THREAD

**Issue by asarkar101** [firebase/flutterfire#10735]
## Bug report

**Describe the bug**

### Steps to reproduce

firebasemessaging.onbackgroundmessage not working  on firebase_messaging: ^14.4.0 

### Expected behavior

on background receive massage firebasemessaging.onbackgroundmessage should be fire.

---

**Comment by danagbemava-nc** [comment]
Closing this since the information requested in the template has not been provided.

**Comment by Joseph-Nathan** [comment]
@asarkar101  are you found any solution ?

**Comment by asarkar101** [comment]
{
    "message": {
        "token": "fcm token",
        "notification": {
                      "title":"test"
                            },
        "data": {
            "Title": "orders",
            "Message": "Body of Your Notification in Data",
        },
        "android": {
            "notification": {
                        "title":"test"
                           }
        },
        "apns": {
            "payload": {
                "aps": {
                    "mutable-content": 1,
                   "content-available": 1    ///// should add this line in aps
                }
            },
            "fcm_options": {
                "image": "https://foo.bar/pizza-monster.png"
            }
        },
        "webpush": {
            "headers": {
                "image": "https://foo.bar/pizza-monster.png"
            }
        }
    }
}
