### ISSUE TITLE
🐛 [cloud_firestore] Error launching application on iPhone 14 Pro.

### ISSUE THREAD

**Issue by greatgipson** [firebase/flutterfire#10739]
## Bug report

**Describe the bug**
I am trying to run a flutter project which uses cloud_firestore-4.3.2 plugin and it fails with the below error.

Error (Xcode): ../../.pub-cache/hosted/pub.dev/cloud_firestore-4.3.2/lib/src/document_reference.dart:175:67: Error: The argument type 'Map<String, dynamic>' can't be assigned to the parameter type 'Map<FieldPath, dynamic>'.

Below is my environment details:

Machine: Apple M1
OS: Ventura 13.2.1
Flutter version: 3.7.10
Dart version: 2.19.6

Android Studio Electric Eel | 2022.1.1 Patch 1
Build #AI-221.6008.13.2211.9514443, built on January 21, 2023
Runtime version: 11.0.15+0-b2043.56-8887301 aarch64
Memory: 1280M
Cores: 8

---

**Comment by darshankawar** [comment]
@greatgipson 
What's the `pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag` version are you using ?

Also, please provide the `minimum global deployment target` you have set in your podfile, which should be minimum 11.

**Comment by darshankawar** [comment]
Also, try to upgrade the plugin version to latest including other flutterfire plugins you are using. Currently it seems to be using 4.3.2.
