### ISSUE TITLE
🐛 [firebase_dynamic_links] Adding the plugin causes often crashes at apps start

### ISSUE THREAD

**Issue by dmitry-fbm** [firebase/flutterfire#10747]
## Bug report

This bug isn't reproducible locally, but causes VERY often crashes upon startup in production. Google console reports the following:

<details><summary>java.lang.RuntimeException</summary>

```
Exception java.lang.RuntimeException:
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:4237)
  at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:4269)
  at android.app.servertransaction.ResumeActivityItem.execute (ResumeActivityItem.java:52)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:176)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2045)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7403)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:502)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:980)
Caused by java.lang.IllegalStateException:
  at com.google.firebase.FirebaseApp.getInstance (FirebaseApp.java)
  at com.google.firebase.dynamiclinks.FirebaseDynamicLinks.getInstance (FirebaseDynamicLinks.java)
  at io.flutter.plugins.firebase.dynamiclinks.FlutterFirebaseDynamicLinksPlugin.getDynamicLinkInstance (FlutterFirebaseDynamicLinksPlugin.java)
  at io.flutter.plugins.firebase.dynamiclinks.FlutterFirebaseDynamicLinksPlugin.onNewIntent (FlutterFirebaseDynamicLinksPlugin.java)
  at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onNewIntent
  at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onNewIntent
  at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onNewIntent
  at io.flutter.embedding.android.FlutterActivity.onNewIntent
  at android.app.Activity.performNewIntent (Activity.java:7876)
  at android.app.Instrumentation.callActivityOnNewIntent (Instrumentation.java:1406)
  at android.app.Instrumentation.callActivityOnNewIntent (Instrumentation.java:1419)
  at android.app.ActivityThread.deliverNewIntents (ActivityThread.java:3504)
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:4220)
```

</details>

Below is our code that causes the crash. Note that we never had dynamic links used in production, the feature was added to the app but we didn't yet start distribution of the links among real users. Hence just one thing that happened was initialization. Moreover, in most recent release we even skipped initialization in production versions so it sounds like just binding the plugin is enough to cause the crash at apps startup.
The issue is somehow hardware dependent: recently one user complained that the crashes started after she switched from Motto to SGS23. The list of affected devices is pretty long though, takes several screens in Google console and featuring multiple platforms/OS versions.
<details><summary>Devices list for one of the affected apps</summary>

samsung a13x
6
8.0%
12
6.2%
4,096 MB (3,792 MB)
Mediatek MT6833V/NZA

samsung a03su
5
6.7%
20
10.3%
3,072 MB (2,918 MB)
Mediatek MT6765

motorola denver
5
6.7%
21
10.8%
4,096 MB (3,674 MB)
Qualcomm SM4350

samsung a32x
3
4.0%
20
10.3%
6,144 MB (3,694 MB)
Mediatek MT6853V/NZA

T-Mobile Bethpage
3
4.0%
5
2.6%
4,096 MB (3,853 MB)
Mediatek MT6833

samsung beyond1q
3
4.0%
5
2.6%
8,192 MB (7,823 MB)
Qualcomm SM8150

motorola austin
2
2.7%
2
1.0%
4,096 MB (3,835 MB)
Mediatek MT6833V/NZA

motorola ellis
2
2.7%
6
3.1%
3,072 MB (2,920 MB)
Mediatek MT6765

samsung a52xq
2
2.7%
6
3.1%
6,144 MB (5,688 MB)
Qualcomm SM7225

samsung a14xm
2
2.7%
4
2.1%
4,096 MB (3,783 MB)
Mediatek MT6833V/NZA

motorola milan
2
2.7%
3
1.5%
4,096 MB (3,906 MB)
Mediatek MT6769V/CZ

BLU B130DL
2
2.7%
2
1.0%
- (3,001 MB)
Mediatek MT6761

samsung a02q
1
1.3%
4
2.1%
- (3,741 MB)
Qualcomm SDM450

Xiaomi grus
1
1.3%
4
2.1%
6,144 MB (5,892 MB)
Qualcomm SDM712

Cricket EC211001
1
1.3%
8
4.1%
- (3,866 MB)
Mediatek MT6833V/MNZA

motorola borneo
1
1.3%
16
8.2%
4,096 MB (3,906 MB)
Qualcomm SM6115

POCO veux
1
1.3%
3
1.5%
- (7,794 MB)
QTI SM6375

samsung a23xq
1
1.3%
3
1.5%
4,096 MB (3,628 MB)
QTI SM6375

samsung q4q
1
1.3%
3
1.5%
12,288 MB (11,805 MB)
QTI SM8475

samsung b0q
1
1.3%
5
2.6%
- (11,757 MB)
QTI SM8450

samsung g0q
1
1.3%
12
6.2%
8,192 MB (7,580 MB)
QTI SM8450

Cricket EC211003
1
1.3%
2
1.0%
3,072 MB (2,936 MB)
Mediatek MT6761D

motorola tonga
1
1.3%
2
1.0%
4,096 MB (3,943 MB)
Mediatek MT6765

samsung a12u
1
1.3%
2
1.0%
3,072 MB (2,867 MB)
Mediatek MT6765

samsung a71xq
1
1.3%
2
1.0%
6,144 MB (5,681 MB)
Qualcomm SM7250

samsung crownqlteue
1
1.3%
2
1.0%
6,144 MB (5,847 MB)
Qualcomm SDM845

samsung gtasliteltetmo
1
1.3%
2
1.0%
2,048 MB (1,934 MB)
Qualcomm MSM8917

samsung o1q
1
1.3%
2
1.0%
8,192 MB (7,719 MB)
Qualcomm SM8350

samsung z3q
1
1.3%
1
0.5%
12,288 MB (11,117 MB)
Qualcomm SM8250

Coolpad lithium
1
1.3%
1
0.5%
3,072 MB (2,959 MB)
Qualcomm SDM450

JREN JR-J71
1
1.3%
1
0.5%
2,048 MB (2,070 MB)
Allwinner A133

Lenovo X306F
1
1.3%
1
0.5%
- (4,040 MB)
Mediatek MT8768T

NUU S6303LA_Go
1
1.3%
1
0.5%
3,072 MB (3,048 MB)
Mediatek MT6739WW

T-Mobile Tokyo_Lite_4G
1
1.3%
1
0.5%
2,048 MB (1,915 MB)
Mediatek MT6761

TECNO TECNO-KE5
1
1.3%
1
0.5%
2,048 MB (1,921 MB)
Mediatek MT6761D

motorola berlna
1
1.3%
1
0.5%
8,192 MB (5,622 MB)
Qualcomm SM7325

motorola kiev
1
1.3%
1
0.5%
- (5,726 MB)
Qualcomm SM7225

samsung a13
1
1.3%
1
0.5%
- (3,887 MB)
Samsung Exynos 850

samsung a33x
1
1.3%
1
0.5%
6,144 MB (5,642 MB)
Samsung s5e8825

samsung a51x
1
1.3%
1
0.5%
6,144 MB (5,582 MB)
Samsung Exynos 980

samsung beyond2q
1
1.3%
1
0.5%
8,192 MB (7,823 MB)
Qualcomm SM8150

samsung j4corelte
1
1.3%
1
0.5%
1,024 MB (900 MB)
Qualcomm MSM8917

samsung r0q
1
1.3%
1
0.5%
8,192 MB (7,580 MB)
QTI SM8450

ATT U319AA
1
1.3%
1
0.5%
2,048 MB (1,947 MB)
Mediatek MT6761
</details>

```dart
  Future<void> _init() async {
    if (!App.isTest) {
      await Firebase.initializeApp(options: await _getFirebaseOptions());
      analytics = FirebaseAnalytics.instance;
      // This is where we start FDL initialization; now restricted with non-production versions only, but still crashes on real users
      if (!kIsWeb && app.env.versionName.startsWith('3.0.')) {
        // This is NASTY hack guys - you need to address this too. 
        // The links just don't work without such delay, and who knows how long it should be to work everywhere.
        Duration delay = Platform.isIOS ? const Duration(seconds: 2) : const Duration(milliseconds: 1500);
        Future.delayed(delay).then((_) async {
          await retrieveDynamicLink();
        });
      }
    }
  }

  Future<void> retrieveDynamicLink() async {
    try {
      // The only line that ever been executed in production environment, but now even this is skipped
      final PendingDynamicLinkData? initialLinkData = await FirebaseDynamicLinks.instance.getInitialLink();
      if (initialLinkData != null) {
        initialUrl = setInitialDynamicLink(initialLinkData.link.toString());
        try {
          app.nav.to(initialUrl);
        } on EContextMissing catch (_) {
          app.initRoute = initialUrl;
        }
      }
    } catch (e, stackTrace) {
      // Never reaches this point, the app just falls apart at startup
      app.log.fatal(e.toString(), 'firebase',
          details: e.toString(), isNetworkError: App.isNetworkError(e), error: e, stackTrace: stackTrace);
    }
  }
```

Flutter versions up to 3.7.9, all most recent versions of packages/plugins.

We're going to remove FDL entirely from next release, it doesn't look production ready. Please try to address this ASAP, it's absolutely critical. Thanks

**Comment by dmitry-fbm** [comment]
Just noticed, there actually are two types of crashes, a bit different from each other, below is another:

<details><summary>java.lang.RuntimeException</summary>

```
Exception java.lang.RuntimeException: Unable to resume activity {com.company.app/com.company.app.MainActivity}: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.company.app. Make sure to call FirebaseApp.initializeApp(Context) first.
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:5365)
  at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:5431)
  at android.app.servertransaction.ResumeActivityItem.execute (ResumeActivityItem.java:54)
  at android.app.servertransaction.ActivityTransactionItem.execute (ActivityTransactionItem.java:45)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:176)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2571)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:226)
  at android.os.Looper.loop (Looper.java:313)
  at android.app.ActivityThread.main (ActivityThread.java:8741)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:571)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1067)
Caused by java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.company.app. Make sure to call FirebaseApp.initializeApp(Context) first.
  at com.google.firebase.FirebaseApp.getInstance (FirebaseApp.java)
  at com.google.firebase.dynamiclinks.FirebaseDynamicLinks.getInstance (FirebaseDynamicLinks.java)
  at io.flutter.plugins.firebase.dynamiclinks.FlutterFirebaseDynamicLinksPlugin.getDynamicLinkInstance (FlutterFirebaseDynamicLinksPlugin.java)
  at io.flutter.plugins.firebase.dynamiclinks.FlutterFirebaseDynamicLinksPlugin.onNewIntent (FlutterFirebaseDynamicLinksPlugin.java)
  at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onNewIntent
  at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onNewIntent
  at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onNewIntent
  at io.flutter.embedding.android.FlutterActivity.onNewIntent
  at android.app.Activity.performNewIntent (Activity.java:8594)
  at android.app.Instrumentation.callActivityOnNewIntent (Instrumentation.java:1484)
  at android.app.Instrumentation.callActivityOnNewIntent (Instrumentation.java:1497)
  at android.app.ActivityThread.deliverNewIntents (ActivityThread.java:4352)
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:5331)
```
</details>

**Comment by darshankawar** [comment]
Labeling this issue based on the report and crash log for team's attention.

/cc @Lyokone

**Comment by Lyokone** [comment]
Hello @dmitry-fbm ,
Could you confirm that you ran `flutterfire configure` using the latest FlutterFire CLI version? 
Can you also confirm that you have the necessary `google-services.json` file in you android/app folder?

Also, do you run `await Firebase.initializeApp(options: await _getFirebaseOptions());` before running `runApp`?
Have you tried to compile your app locally using "flutter run --release" to see if you can reproduce it locally?

**Comment by dmitry-fbm** [comment]
@Lyokone ok as per [most recent docs](https://firebase.flutter.dev/docs/manual-installation/#migrating-to-dart-only-initialization) google-services.json (as well as GoogleService-Info.plist) has to be removed from the project - which is what we have done, as otherwise it triggers this error: `Firebase App named ‘[DEFAULT]’ already exists`. There is no mention of it [here](https://firebase.google.com/docs/flutter/setup?platform=ios) anymore as well. So I believe you have to make the plugin work accordingly. 
FYI, after the plugin was removed, the crashes stopped.

**Comment by dmitry-fbm** [comment]
Hello @Lyokone - any update on this please?

**Comment by Lyokone** [comment]
@dmitry-fbm You are looking at deprecated documentation as said on the top of the page
<img width="1012" alt="Screenshot 2023-04-28 at 10 23 27" src="https://user-images.githubusercontent.com/3680002/235095377-8994ecf1-a0c1-485f-8412-58ae65e7374d.png">
, you should keep both service files (which are automatically generated by `flutterfire configure`)

**Comment by dmitry-fbm** [comment]
@Lyokone sorry for slow response, been busy with other stuff. You're correct that flutterfire generates service files, however having both them and `FireBaseServices.init()` in dart code triggers this error: A Firebase App named "[DEFAULT]" already exists. The call is necessary for instance to initialize service worker in flutter web so we cannot get rid of it. In the same time both FCM and analytics work perfectly without those service files. Should we initialize a separate instance of firebase app? Won't they conflict with each other?

**Comment by dmitry-fbm** [comment]
Ok let me get back to this. So, firstly, @Lyokone is correct: if configured properly with `flutterfire`, nothing crashes. Still, I'd argue that crash (especially intermittent) isn't right way to manifest misconfiguration. 
But, things are getting worse yet after [this announcement](https://firebase.google.com/support/dynamic-links-faq). Don't you guys have some insight/suggestions what can be used to substitute the FDL? We currently use AppsFlyer to track installs but it has a number of drawbacks compared to FDL; using standard deep linking techniques the announcement refers to doesn't let attribute installs to a specific user at all so not an equivalent substitution. Any suggestion would be greatly appreciated.

**Comment by EskAere** [comment]
@dmitry-fbm I have the exact same crash as you in production. 2000+ occurrences this week…
May I know what you've done to have the proper configuration ?? 

Following official documentation doesn't seem enough. Have you changed `firebase_options.dart` ? Have you added any file ? 
I appreciate the help, thank you :)

**Comment by russellwheatley** [comment]
Hi folks, we'd like to inform you that the Firebase Dynamic Links service will be shutdown on August 25, 2025. In the meantime, only critical or security issues will be fixed in the SDK.

More at [firebase.google.com/support/dynamic-links-faq](https://firebase.google.com/support/dynamic-links-faq)
