### ISSUE TITLE
🐛 [firebase_auth] Unhandled Exception: Null is not a subtype of String when calling verifyPhoneNumber

### ISSUE THREAD

**Issue by ErahimKsaab** [firebase/flutterfire#10779]
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'Null' is not a subtype of type 'String' E/flutter ( 1180): #0 MethodChannelFirebaseAuth.verifyPhoneNumber.<anonymous closure>

**Comment by danagbemava-nc** [comment]
Hi @ErahimKsaab, please provide a complete minimal reproducible code sample along with the output of `flutter pub deps -- --style=compact`. 

Also, is this bug occurring in release mode or debug mode as well? 

How did you setup your project? 

Can you also check https://github.com/firebase/flutterfire/issues/10139 to see if any of the solutions work for you?

**Comment by ErahimKsaab** [comment]
Dart SDK 2.16.2
Flutter SDK 2.10.5
ahlachat 1.0.102+102

dependencies:
- agora_rtc_engine 5.1.0 [flutter flutter_web_plugins js json_annotation]
- animate_do 2.1.0 [flutter]
- animated_overflow 2.0.0 [flutter simple_animations]
- animated_text_kit 4.2.1 [flutter characters]
- audio_video_progress_bar 0.10.0 [flutter]
- auto_size_text 3.0.0 [flutter]
- avatar_glow 2.0.2 [flutter]
- badges 2.0.3 [flutter]
- banner_carousel 1.2.1 [flutter]
- cached_network_image 3.2.0 [flutter flutter_cache_manager octo_image
cached_network_image_platform_interface cached_network_image_web]
- carousel_slider 4.1.1 [flutter]
- cherry_toast 1.0.9 [flutter]
- circular_countdown 2.1.0 [flutter]
- collection 1.15.0
- connectivity_plus 2.3.9 [flutter connectivity_plus_platform_interface
connectivity_plus_linux connectivity_plus_macos connectivity_plus_web
connectivity_plus_windows]
- country_calling_code_picker 2.0.1 [flutter flutter_sim_country_code]
- country_code_picker 2.0.2 [flutter modal_bottom_sheet collection
universal_platform]
- country_list_pick 1.0.1+6 [flutter]
- country_picker 2.0.19 [flutter collection]
- cupertino_icons 1.0.5
- declarative_refresh_indicator 0.1.0 [flutter]
- delayed_display 2.0.0 [flutter]
- device_info_plus 3.2.4 [flutter device_info_plus_platform_interface
device_info_plus_macos device_info_plus_linux device_info_plus_web
device_info_plus_windows]
- dio 4.0.6 [http_parser path]
- draggable_widget 2.0.0 [flutter]
- filling_slider 0.0.3 [flutter]
- firebase_app_check 0.0.9+1 [firebase_app_check_platform_interface
firebase_app_check_web firebase_core firebase_core_platform_interface
flutter]
- firebase_auth 3.4.2 [firebase_auth_platform_interface firebase_auth_web
firebase_core firebase_core_platform_interface flutter meta]
- firebase_auth_platform_interface 6.3.2 [firebase_core flutter meta
plugin_platform_interface]
- firebase_core_platform_interface 4.5.1 [collection flutter flutter_test
meta plugin_platform_interface]
- firebase_messaging 13.1.0 [firebase_core firebase_core_platform_interface
firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta
typed_data vector_math sky_engine]
- flutter_circle_color_picker 0.3.0 [flutter]
- flutter_custom_clippers 2.0.0 [flutter]
- flutter_fortune_wheel 1.2.0 [flutter flutter_hooks quiver]
- flutter_image_slideshow 0.1.4 [flutter]
- flutter_jailbreak_detection 1.10.0 [flutter]
- flutter_keyboard_visibility 5.4.0 [meta
flutter_keyboard_visibility_platform_interface
flutter_keyboard_visibility_linux flutter_keyboard_visibility_macos
flutter_keyboard_visibility
_web flutter_keyboard_visibility_windows flutter]
- flutter_local_notifications 9.9.1 [clock flutter
flutter_local_notifications_linux
flutter_local_notifications_platform_interface timezone]
- flutter_mentions 2.0.1 [flutter flutter_portal]
- flutter_native_splash 2.1.6 [args flutter flutter_web_plugins image js
lint meta path universal_io xml yaml]
- flutter_smart_dialog 4.2.5 [flutter]
- flutter_sound 9.2.13 [path_provider recase uuid provider path
synchronized logger flutter flutter_sound_platform_interface
flutter_sound_web]
- flutter_svg 1.0.3 [flutter meta path_drawing vector_math xml]
- fluttertoast 8.1.1 [flutter flutter_web_plugins]
- font_awesome_flutter 10.2.1 [flutter]
- get_ip_address 0.0.5 [http]
- google_fonts 3.0.1 [flutter http path_provider crypto]
- google_sign_in 5.4.2 [flutter google_sign_in_android google_sign_in_ios
google_sign_in_platform_interface google_sign_in_web]
- http 0.13.5 [async http_parser meta path]
- image_cropper 3.0.1 [flutter image_cropper_platform_interface
image_cropper_for_web]
- image_picker 0.8.5+3 [flutter image_picker_android image_picker_for_web
image_picker_ios image_picker_platform_interface]
- in_app_update 3.0.0 [flutter]
- just_audio 0.9.30 [just_audio_platform_interface just_audio_web
audio_session rxdart path path_provider async uuid crypto meta flutter]
- lottie 1.4.2 [archive flutter path vector_math]
- marquee 2.2.1 [fading_edge_scrollview flutter]
- motion_toast 2.6.5 [flutter]
- new_version_plus 0.0.1+4 [flutter package_info_plus http html
url_launcher collection]
- on_audio_query 2.6.1 [on_audio_query_platform_interface
on_audio_query_web flutter]
- package_info_plus 1.4.2 [flutter package_info_plus_platform_interface
package_info_plus_linux package_info_plus_macos package_info_plus_windows
package_info_plus_web]
- palestine_trusted_device 0.1.1 [flutter]
- path_provider 2.0.11 [flutter path_provider_android path_provider_ios
path_provider_linux path_provider_macos path_provider_platform_interface
path_provider_windows]
- percent_indicator 4.0.1 [flutter]
- permission_handler 10.2.0 [flutter meta permission_handler_android
permission_handler_apple permission_handler_windows
permission_handler_platform_interface]
- photo_view 0.14.0 [flutter]
- pin_code_fields 7.4.0 [flutter]
- popover 0.2.6+3 [flutter]
- provider 6.0.4 [collection flutter nested]
- pull_to_refresh 2.0.0 [flutter]
- purchases_flutter 4.4.1 [flutter freezed_annotation json_annotation]
- pusher_channels 0.3.0
- pusher_client 2.0.0 [flutter]
- readmore 2.2.0 [flutter]
- roulette 0.1.3 [flutter]
- rxdart 0.27.7
- shared_preferences 2.0.15 [flutter shared_preferences_android
shared_preferences_ios shared_preferences_linux shared_preferences_macos
shared_preferences_platform_interface shared_pr
eferences_web shared_preferences_windows]
- simple_timer 2.0.0 [flutter]
- slider_controller 0.0.4 [flutter]
- spring 2.0.2 [simple_animations supercharged universal_platform
vector_math flutter]
- svgaplayer_flutter 2.2.0 [flutter protobuf http path_drawing archive]
- tab_indicator_styler 2.0.0 [flutter]
- timeago 3.3.0 [intl]
- url_launcher 6.1.7 [flutter url_launcher_android url_launcher_ios
url_launcher_linux url_launcher_macos url_launcher_platform_interface
url_launcher_web url_launcher_windows]
- video_player 2.4.8 [flutter html video_player_android
video_player_avfoundation video_player_platform_interface video_player_web]
- wakelock 0.6.2 [flutter meta wakelock_macos wakelock_platform_interface
wakelock_web wakelock_windows]
- webview_flutter 3.0.4 [flutter webview_flutter_android
webview_flutter_platform_interface webview_flutter_wkwebview]
- wp_pivot_flutter 1.0.0 [flutter scrollable_positioned_list]
- zoom_pinch_overlay 1.3.2 [flutter vector_math]

dev dependencies:
- flutter_localizations 0.0.0 [flutter intl characters clock collection
material_color_utilities meta path typed_data vector_math]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace
vector_math async boolean_selector characters charcode collection matcher
material_color_utilities meta source_
span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- _flutterfire_internals 1.0.2 [cloud_firestore_platform_interface
cloud_firestore_web collection firebase_core
firebase_core_platform_interface flutter meta]
- archive 3.3.5 [crypto path pointycastle]
- args 2.3.1
- async 2.8.2 [collection meta]
- audio_session 0.1.11 [flutter flutter_web_plugins rxdart meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- cached_network_image_platform_interface 1.0.0 [flutter
flutter_cache_manager]
- cached_network_image_web 1.0.1 [flutter flutter_cache_manager
cached_network_image_platform_interface]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- cloud_firestore_platform_interface 5.7.7 [_flutterfire_internals
collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.8.10 [_flutterfire_internals
cloud_firestore_platform_interface collection firebase_core
firebase_core_web flutter flutter_web_plugins js]
- connectivity_plus_linux 1.3.1 [flutter
connectivity_plus_platform_interface meta nm]
- connectivity_plus_macos 1.2.6 [connectivity_plus_platform_interface
flutter]
- connectivity_plus_platform_interface 1.2.2 [flutter meta
plugin_platform_interface]
- connectivity_plus_web 1.2.5 [connectivity_plus_platform_interface
flutter_web_plugins flutter js]
- connectivity_plus_windows 1.2.2 [connectivity_plus_platform_interface
flutter]
- convert 3.1.0 [typed_data]
- cross_file 0.3.3+2 [js meta]
- crypto 3.0.2 [typed_data]
- csslib 0.17.2 [source_span]
- dbus 0.7.3 [args ffi meta xml]
- device_info_plus_linux 2.1.1 [device_info_plus_platform_interface file
flutter meta]
- device_info_plus_macos 2.2.3 [device_info_plus_platform_interface flutter]
- device_info_plus_platform_interface 2.6.1 [flutter meta
plugin_platform_interface]
- device_info_plus_web 2.1.0 [device_info_plus_platform_interface
flutter_web_plugins flutter]
- device_info_plus_windows 2.1.1 [device_info_plus_platform_interface ffi
flutter win32]
- fading_edge_scrollview 2.0.1 [flutter]
- fake_async 1.2.0 [clock collection]
- ffi 1.2.1
- file 6.1.4 [meta path]
- firebase_app_check_platform_interface 0.0.5+1 [_flutterfire_internals
firebase_core flutter meta plugin_platform_interface]
- firebase_app_check_web 0.0.7+1 [_flutterfire_internals
firebase_app_check_platform_interface firebase_core firebase_core_web
flutter flutter_web_plugins js]
- firebase_auth_web 4.0.0 [firebase_auth_platform_interface firebase_core
firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core 1.24.0 [firebase_core_platform_interface firebase_core_web
flutter meta]
- firebase_core_web 1.7.3 [firebase_core_platform_interface flutter
flutter_web_plugins js meta]
- firebase_messaging_platform_interface 4.2.0 [_flutterfire_internals
firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.2.0 [_flutterfire_internals firebase_core
firebase_core_web firebase_messaging_platform_interface flutter
flutter_web_plugins js meta]
- fixnum 1.0.1
- flutter_blurhash 0.7.0 [flutter]
- flutter_cache_manager 3.3.0 [clock collection file flutter http path
path_provider pedantic rxdart sqflite uuid]
- flutter_hooks 0.18.3 [flutter]
- flutter_keyboard_visibility_linux 1.0.0
[flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_macos 1.0.0
[flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta
plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0
[flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_keyboard_visibility_windows 1.0.0
[flutter_keyboard_visibility_platform_interface flutter]
- flutter_lints 1.0.4 [lints]
- flutter_local_notifications_linux 0.5.1 [flutter
flutter_local_notifications_platform_interface dbus path xdg_directories]
- flutter_local_notifications_platform_interface 5.0.0 [flutter
plugin_platform_interface]
- flutter_plugin_android_lifecycle 2.0.7 [flutter]
- flutter_portal 0.4.0 [flutter]
- flutter_sim_country_code 0.1.2 [flutter]
- flutter_sound_platform_interface 9.2.13 [flutter meta
plugin_platform_interface logger]
- flutter_sound_web 9.2.13 [flutter_sound_platform_interface flutter logger
flutter_web_plugins meta js]
- flutter_web_plugins 0.0.0 [flutter js characters collection
material_color_utilities meta typed_data vector_math]
- freezed_annotation 2.1.0 [collection json_annotation meta]
- google_sign_in_android 6.1.4 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.5.1 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.3.0 [flutter
plugin_platform_interface quiver]
- google_sign_in_web 0.10.2 [flutter flutter_web_plugins
google_sign_in_platform_interface js]
- html 0.15.1 [csslib source_span]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- id3 1.0.2
- image 3.1.3 [archive meta xml]
- image_cropper_for_web 1.0.3 [flutter flutter_web_plugins
image_cropper_platform_interface js]
- image_cropper_platform_interface 3.0.3 [flutter plugin_platform_interface
http]
- image_picker_android 0.8.5+3 [flutter flutter_plugin_android_lifecycle
image_picker_platform_interface]
- image_picker_for_web 2.1.10 [flutter flutter_web_plugins
image_picker_platform_interface]
- image_picker_ios 0.8.6+1 [flutter image_picker_platform_interface]
- image_picker_platform_interface 2.6.2 [cross_file flutter http
plugin_platform_interface]
- intl 0.17.0 [clock path]
- js 0.6.3
- json_annotation 4.6.0 [meta]
- just_audio_platform_interface 4.2.0 [flutter plugin_platform_interface]
- just_audio_web 0.4.7 [just_audio_platform_interface flutter
flutter_web_plugins]
- lint 1.9.0
- lints 1.0.1
- logger 1.1.0
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.3
- meta 1.7.0
- modal_bottom_sheet 2.0.1 [flutter]
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- octo_image 1.0.2 [flutter flutter_blurhash]
- on_audio_query_platform_interface 1.4.0 [plugin_platform_interface
flutter]
- on_audio_query_web 1.3.2+2 [on_audio_query_platform_interface path id3
flutter flutter_web_plugins]
- package_info_plus_linux 1.0.5 [package_info_plus_platform_interface
flutter path]
- package_info_plus_macos 1.3.0 [flutter]
- package_info_plus_platform_interface 1.0.2 [flutter meta
plugin_platform_interface]
- package_info_plus_web 1.0.6 [flutter flutter_web_plugins http meta
package_info_plus_platform_interface]
- package_info_plus_windows 1.0.5 [package_info_plus_platform_interface ffi
flutter win32]
- path 1.8.0
- path_drawing 1.0.1 [vector_math meta path_parsing flutter]
- path_parsing 1.0.1 [vector_math meta]
- path_provider_android 2.0.22 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.11 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path
path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.6 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.5 [flutter platform
plugin_platform_interface]
- path_provider_windows 2.0.7 [ffi flutter path
path_provider_platform_interface win32]
- pedantic 1.11.1
- permission_handler_android 10.2.0 [flutter
permission_handler_platform_interface]
- permission_handler_apple 9.0.7 [flutter
permission_handler_platform_interface]
- permission_handler_platform_interface 3.9.0 [flutter meta
plugin_platform_interface]
- permission_handler_windows 0.1.2 [flutter
permission_handler_platform_interface]
- petitparser 4.4.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.3 [meta]
- pointycastle 3.6.2 [collection convert js]
- process 4.2.4 [file path platform]
- protobuf 2.1.0 [fixnum collection meta]
- quiver 3.1.0 [matcher]
- recase 4.1.0
- scrollable_positioned_list 0.2.3 [flutter collection]
- shared_preferences_android 2.0.14 [flutter
shared_preferences_platform_interface]
- shared_preferences_ios 2.1.1 [flutter
shared_preferences_platform_interface]
- shared_preferences_linux 2.1.1 [file flutter path path_provider_linux
path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_macos 2.0.4 [flutter
shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.1.0 [flutter
plugin_platform_interface]
- shared_preferences_web 2.0.4 [flutter flutter_web_plugins
shared_preferences_platform_interface]
- shared_preferences_windows 2.1.1 [file flutter path
path_provider_platform_interface path_provider_windows
shared_preferences_platform_interface]
- simple_animations 3.2.0 [flutter supercharged flutter_lints]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- sqflite 2.0.2+1 [flutter sqflite_common path]
- sqflite_common 2.4.0 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- supercharged 2.1.1 [supercharged_dart flutter]
- supercharged_dart 2.1.1
- synchronized 3.0.0+3
- term_glyph 1.2.0
- video_player_web 2.0.12 [flutter flutter_web_plugins
video_player_platform_interface]
- wakelock_macos 0.4.0 [flutter flutter_web_plugins
wakelock_platform_interface]
- wakelock_platform_interface 0.3.0 [flutter meta]
- wakelock_web 0.4.0 [flutter flutter_web_plugins js
wakelock_platform_interface]
- wakelock_windows 0.2.0 [flutter wakelock_platform_interface win32]
- webview_flutter_android 2.8.14 [flutter
webview_flutter_platform_interface]
- webview_flutter_platform_interface 1.9.5 [flutter meta
plugin_platform_interface]
- webview_flutter_wkwebview 2.7.5 [flutter path
webview_flutter_platform_interface]
- win32 2.5.2 [ffi]
- xdg_directories 0.2.0+2 [meta path process]
- xml 5.3.1 [collection meta petitparser]
- yaml 3.1.1 [collection source_span string_scanner]

‫في الخميس، 13 أبريل 2023 في 11:53 ص تمت كتابة ما يلي بواسطة ‪Daniel
Agbemava‬‏ ***@***.***‬‏>:‬

**Comment by ErahimKsaab** [comment]
i manually set up my project
 yes i uploaded my sha-1 and sha-256 keys to the firebase console
FirebaseAuth auth = FirebaseAuth.instance;
await auth.verifyPhoneNumber(
phoneNumber: '+201227243731',
timeout: const Duration(seconds: 60),
codeAutoRetrievalTimeout: (String verificationId) {
},
);

‫في الجمعة، 14 أبريل 2023 في 12:20 م تمت كتابة ما يلي بواسطة ‪Daniel
Agbemava‬‏ ***@***.***‬‏>:‬

**Comment by danagbemava-nc** [comment]
Hi @ErahimKsaab, please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)  in a github repo so that we can clone and run to verify this issue. 

Thank you
