### ISSUE TITLE
[firebase_remote_config] Unable to connect to the server 

### ISSUE THREAD

**Issue by phamconganh** [firebase/flutterfire#10780]
## Bug report

**firebase_remote_config realtime**

After adding realtime firebase_remote_config to my app, the error "firebase_remote_config, Unable to connect to the server. Check your connection and try again." happened many times. I listen for one time subscription in main and not close in app lifecycle.
I found in android sdk, it also exists, https://github.com/firebase/firebase-android-sdk/issues/4864

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.19.6
Flutter SDK 3.7.10

dependencies:
- firebase_analytics 10.2.0 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 2.9.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 3.1.0 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_remote_config 4.0.0 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]

dev dependencies:
- flutter_lints 2.0.1 [lints]

transitive dependencies:
- firebase_analytics_platform_interface 3.4.0 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.2 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_core_platform_interface 4.6.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.3.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.4.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_platform_interface 1.2.0 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.2.0 [firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins js]
```

</details>

---

**Comment by danagbemava-nc** [comment]
Hi @phamconganh, can you share the full logs when you run the app? 

Can you also provide a minimal complete reproducible code sample? I tested with the firebase_remote_config sample code and I did not get any issues. 

Is your project properly setup on gcp? The android issue you linked to appears to be resolved so it could be unrelated to what you're experiencing.

**Comment by phamconganh** [comment]
@danagbemava-nc sorry for the late response, sample code is here https://github.com/phamconganh/firebase_test

**Comment by danagbemava-nc** [comment]
Hi @phamconganh, I used the code sample in your repo but I do not see any issue. Kindly check the video below to see if I used the right steps to reproduce the issue. 

<details>
<summary>video</summary>

https://user-images.githubusercontent.com/88313112/233974892-301dbbcd-bf38-495b-8ca5-034e4ff51d56.mp4
</details>


<details>
<summary>logs</summary>

```
Launching lib/main.dart on Pixel 7 in debug mode...
Running Gradle task 'assembleDebug'...                              3.4s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
I/e.firebase_test(19108): Compiler allocated 4413KB to compile void android.view.ViewRootImpl.performTraversals()
E/SurfaceSyncer(19108): Failed to find sync for id=0
Syncing files to device Pixel 7...                                 148ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on Pixel 7 is available at: http://127.0.0.1:51053/GXZBNiyxRwA=/
The Flutter DevTools debugger and profiler on Pixel 7 is available at:
http://127.0.0.1:9100?uri=http://127.0.0.1:51053/GXZBNiyxRwA=/
D/FRCPlugin(19108): Sending fetchTimeout: 10
D/FRCPlugin(19108): Sending fetchTimeout: 10
D/TrafficStats(19108): tagSocket(129) with statsTag=0xffffffff, statsUid=-1
D/FRCPlugin(19108): Sending fetchTimeout: 10
D/FirebaseRemoteConfig(19108): Exception connecting to real-time RC backend. Retrying the connection...
D/FRCPlugin(19108): Sending fetchTimeout: 10
D/TrafficStats(19108): tagSocket(5) with statsTag=0xffffffff, statsUid=-1
D/FRCPlugin(19108): Sending fetchTimeout: 10

Application finished.
```
</details>

**Comment by JaidynBluesky** [comment]
@phamconganh have you made sure to enable the Firebase Remote Config Realtime API in the Google Cloud project?

**Comment by phamconganh** [comment]
I have definitely enabled `Firebase Remote Configuration Realtime API` in `Google Cloud` project. And I have successfully tested `Realtime Configuration`. But sometimes `Unable to connect to the server` and when debugging Restart this problem also happens. I released my app to production and saw some logs in `firebase crashlytics`: `PlatformException(firebase_remote_config, Unable to connect to the server. Check your connection and try again., null, null)`

**Comment by phamconganh** [comment]
In `firebase_core 2.9.0` and `firebase_remote_config 4.0.0`, I see it a few times but not often. In production release I see logs about 200 times with 100 users in 7 days. In the latest `firebase_core 2.11.0` and `firebase_remote_config 4.1.0`, I've never seen it in debug mode. I'm releasing a new app version and waiting a week to read this log issue.

**Comment by danagbemava-nc** [comment]
Kindly update here if you see it with the newer versions

**Comment by davidmigloz** [comment]
If you don't set an `onError` callback when consuming the stream (`onConfigUpdated.listen()`), any errors on the stream are considered unhandled and passed to the current Zone's error handler.

If you just want to ignore Remote Config errors in the stream add an empty `onError` callback:

```dart
subscription = remoteConfig.onConfigUpdated.listen(
  (final event) {
    // ...
  },
  onError: (final e) {
    // Ignore RC errors
  },
);
```

**Comment by phamconganh** [comment]
Thanks @davidmigloz, I will add this to catch unhandled errors.

@danagbemava-nc, after release 4 days my app logs `Unable to connect to server` 30 events/5 users (out of 2500 users per day). I think maybe it's the network connection or the certificate. And on my mac with custom certificate and the lastest firebase it will logs as after:
```
D/FRCPlugin(32166): Sending fetchTimeout: 60
E/EventChannel#plugins.flutter.io/firebase_remote_config_updated(32166): Failed to close existing event stream
E/EventChannel#plugins.flutter.io/firebase_remote_config_updated(32166): java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
E/EventChannel#plugins.flutter.io/firebase_remote_config_updated(32166): 	at io.flutter.plugins.firebase.firebaseremoteconfig.FirebaseRemoteConfigPlugin.onCancel(FirebaseRemoteConfigPlugin.java:308)
E/EventChannel#plugins.flutter.io/firebase_remote_config_updated(32166): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:212)
E/EventChannel#plugins.flutter.io/firebase_remote_config_updated(32166): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:197)
E/EventChannel#plugins.flutter.io/firebase_remote_config_updated(32166): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/EventChannel#plugins.flutter.io/firebase_remote_config_updated(32166): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/EventChannel#plugins.flutter.io/firebase_remote_config_updated(32166): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/EventChannel#plugins.flutter.io/firebase_remote_config_updated(32166): 	at android.os.Handler.handleCallback(Handler.java:938)
E/EventChannel#plugins.flutter.io/firebase_remote_config_updated(32166): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/EventChannel#plugins.flutter.io/firebase_remote_config_updated(32166): 	at android.os.Looper.loopOnce(Looper.java:201)
E/EventChannel#plugins.flutter.io/firebase_remote_config_updated(32166): 	at android.os.Looper.loop(Looper.java:288)
E/EventChannel#plugins.flutter.io/firebase_remote_config_updated(32166): 	at android.app.ActivityThread.main(ActivityThread.java:7842)
E/EventChannel#plugins.flutter.io/firebase_remote_config_updated(32166): 	at java.lang.reflect.Method.invoke(Native Method)
E/EventChannel#plugins.flutter.io/firebase_remote_config_updated(32166): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/EventChannel#plugins.flutter.io/firebase_remote_config_updated(32166): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
[main] recordError
[main] PlatformException (PlatformException(firebase_remote_config, Unable to connect to the server. Check your connection and try again., null, null))
I/flutter (32166): ----------------FIREBASE CRASHLYTICS----------------
I/flutter (32166): PlatformException(firebase_remote_config, Unable to connect to the server. Check your connection and try again., null, null)
[main] _StringStackTrace
I/flutter (32166):
I/flutter (32166): ----------------------------------------------------
```
I don't know if it is possible to config `badCertificateCallback` for debug and read the error code of `socket connection error` for ignore

**Comment by Spitzbua** [comment]
I have the same misbehaviour. I just wanted to implement Real Time Updates but no events come up in the onConfigUpdated listener.

Device: Pixel 4 API 33 Emulator

My error log:
```
D/FRCPlugin( 3938): Sending fetchTimeout: 60
E/EventChannel#plugins.flutter.io/firebase_remote_config_updated( 3938): Failed to close existing event stream
E/EventChannel#plugins.flutter.io/firebase_remote_config_updated( 3938): java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
E/EventChannel#plugins.flutter.io/firebase_remote_config_updated( 3938): 	at io.flutter.plugins.firebase.firebaseremoteconfig.FirebaseRemoteConfigPlugin.onCancel(FirebaseRemoteConfigPlugin.java:308)
E/EventChannel#plugins.flutter.io/firebase_remote_config_updated( 3938): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:212)
E/EventChannel#plugins.flutter.io/firebase_remote_config_updated( 3938): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:197)
E/EventChannel#plugins.flutter.io/firebase_remote_config_updated( 3938): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/EventChannel#plugins.flutter.io/firebase_remote_config_updated( 3938): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/EventChannel#plugins.flutter.io/firebase_remote_config_updated( 3938): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/EventChannel#plugins.flutter.io/firebase_remote_config_updated( 3938): 	at android.os.Handler.handleCallback(Handler.java:942)
E/EventChannel#plugins.flutter.io/firebase_remote_config_updated( 3938): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/EventChannel#plugins.flutter.io/firebase_remote_config_updated( 3938): 	at android.os.Looper.loopOnce(Looper.java:201)
E/EventChannel#plugins.flutter.io/firebase_remote_config_updated( 3938): 	at android.os.Looper.loop(Looper.java:288)
E/EventChannel#plugins.flutter.io/firebase_remote_config_updated( 3938): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/EventChannel#plugins.flutter.io/firebase_remote_config_updated( 3938): 	at java.lang.reflect.Method.invoke(Native Method)
E/EventChannel#plugins.flutter.io/firebase_remote_config_updated( 3938): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/EventChannel#plugins.flutter.io/firebase_remote_config_updated( 3938): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

> Thanks @davidmigloz, I will add this to catch unhandled errors.
> 
> @danagbemava-nc, after release 4 days my app logs `Unable to connect to server` 30 events/5 users (out of 2500 users per day). I think maybe it's the network connection or the certificate. And on my mac with custom certificate and the lastest firebase it will logs as after:
> 
> ```
> D/FRCPlugin(32166): Sending fetchTimeout: 60
> E/EventChannel#plugins.flutter.io/firebase_remote_config_updated(32166): Failed to close existing event stream
> E/EventChannel#plugins.flutter.io/firebase_remote_config_updated(32166): java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
> E/EventChannel#plugins.flutter.io/firebase_remote_config_updated(32166): 	at io.flutter.plugins.firebase.firebaseremoteconfig.FirebaseRemoteConfigPlugin.onCancel(FirebaseRemoteConfigPlugin.java:308)
> E/EventChannel#plugins.flutter.io/firebase_remote_config_updated(32166): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:212)
> E/EventChannel#plugins.flutter.io/firebase_remote_config_updated(32166): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:197)
> E/EventChannel#plugins.flutter.io/firebase_remote_config_updated(32166): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
> E/EventChannel#plugins.flutter.io/firebase_remote_config_updated(32166): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
> E/EventChannel#plugins.flutter.io/firebase_remote_config_updated(32166): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
> E/EventChannel#plugins.flutter.io/firebase_remote_config_updated(32166): 	at android.os.Handler.handleCallback(Handler.java:938)
> E/EventChannel#plugins.flutter.io/firebase_remote_config_updated(32166): 	at android.os.Handler.dispatchMessage(Handler.java:99)
> E/EventChannel#plugins.flutter.io/firebase_remote_config_updated(32166): 	at android.os.Looper.loopOnce(Looper.java:201)
> E/EventChannel#plugins.flutter.io/firebase_remote_config_updated(32166): 	at android.os.Looper.loop(Looper.java:288)
> E/EventChannel#plugins.flutter.io/firebase_remote_config_updated(32166): 	at android.app.ActivityThread.main(ActivityThread.java:7842)
> E/EventChannel#plugins.flutter.io/firebase_remote_config_updated(32166): 	at java.lang.reflect.Method.invoke(Native Method)
> E/EventChannel#plugins.flutter.io/firebase_remote_config_updated(32166): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
> E/EventChannel#plugins.flutter.io/firebase_remote_config_updated(32166): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
> [main] recordError
> [main] PlatformException (PlatformException(firebase_remote_config, Unable to connect to the server. Check your connection and try again., null, null))
> I/flutter (32166): ----------------FIREBASE CRASHLYTICS----------------
> I/flutter (32166): PlatformException(firebase_remote_config, Unable to connect to the server. Check your connection and try again., null, null)
> [main] _StringStackTrace
> I/flutter (32166):
> I/flutter (32166): ----------------------------------------------------
> ```
> 
> I don't know if it is possible to config `badCertificateCallback` for debug and read the error code of `socket connection error` for ignore

**Comment by danagbemava-nc** [comment]
Thanks for the details. Labeling for further investigation and insight from the team

**Comment by Lyokone** [comment]
Some issues were fixed on the backend of Firebase, do you still experience this issue?

**Comment by phamconganh** [comment]
@Lyokone Thank. I just tested in debug mode. It seems this issue has been resolved. I will monitor the error analytics on Firebase over the next week, I think the error log will gradually decrease

**Comment by phamconganh** [comment]
@Lyokone The number of logs about this issue in my application has decreased significantly over the past week, I think I can close this issue now.

**Comment by danagbemava-nc** [comment]
Thanks for the update. 

Please feel free to update us if this issue pops up again. 

Closing based on https://github.com/firebase/flutterfire/issues/10780#issuecomment-1839238525

**Comment by Fernandomr88** [comment]
FYI: my app is showing the same behavior.
![image](https://github.com/firebase/flutterfire/assets/14304128/c8bc4c71-665e-4630-b678-8a4921ca117c)

Using: 

```console
firebase_analytics_platform_interface 3.8.2 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.5+9 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_app_installations_platform_interface 0.1.4+14 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_app_installations_web 0.1.3+14 [_flutterfire_internals firebase_app_installations_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.9.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.6.14 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.5.15 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.5.15 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_performance_platform_interface 0.1.4+14 [_flutterfire_internals firebase_core flutter plugin_platform_interface]
- firebase_performance_web 0.1.4+14 [_flutterfire_internals firebase_core firebase_core_web firebase_performance_platform_interface flutter flutter_web_plugins js]
- firebase_remote_config_platform_interface 1.4.14 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.4.14 [firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins js]
- fixnum 1.1.0
- flutter_local_notifications_linux 4.0.0+1 [dbus ffi flutter flutter_local_notifications_platform_interface path xdg_directories]
- flutter_local_notifications_platform_interface 7.0.0+1 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 2.0.17 [flutter]
- flutter_secure_storage_linux 1.2.0 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_macos 3.0.1 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_platform_interface 1.0.2 [flutter plugin_platform_interface]
- flutter_secure_storage_web 1.1.2 [flutter flutter_secure_storage_platform_interface flutter_web_plugins js]
- flutter_secure_storage_windows 3.0.0 [ffi flutter flutter_secure_storage_platform_interface path path_provider win32]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math async boolean_selector characters collection material_color_utilities meta source_span stream_channel string_scanner term_glyph web]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math web]
```

**Comment by naveeez10** [comment]
hi @danagbemava-nc .  I am facing the same issue with `firebase_core: 2.16.0` and `firebase_remote_config: 4.2.6`
