### ISSUE TITLE
🐛 [PHONE AUTH] unknown status code : 17028 ! "SMS verification code request failed: unknown status code: 17028 Invalid request fields in play_integrity_token"

### ISSUE THREAD

**Issue by hyderali0889** [firebase/flutterfire#10786]
## I've added the SHA-1 and SHA-256 to my firebase project and enabled the auth check with play integrity also checked the app name and SHA-1, SHA256 keys nothing seems to work and this error keeps on popping. I've redownloaded the google-service.json file also cleaned my project and recompiled it with every new update but nothing works.

My Code is

```
 void signInWithPhone() async {
      try {    
        FirebaseAuth auth = FirebaseAuth.instance;
        await auth.verifyPhoneNumber(
            forceResendingToken: token,
            phoneNumber: "+92${widget.phoneController.text.trim()}",
            verificationCompleted: (credential) async {
              await auth.signInWithCredential(credential);
              setState(() {
                hello = "Logged In";
              });
            },
            verificationFailed: (verificationFailed) {
              setState(() {
                hello = "Error Occured $verificationFailed";
              });
            },
            codeSent: (codeSent, otp) {
              setState(() {
                hello = "Code sent";
                token = otp;
              });
            },
            codeAutoRetrievalTimeout: (codeAutoRetrievalTimeout) {});
        widget.controller.startLoading(false);
      } catch (e) {
print(e);        
      }
    }
```
the error says

>[SmsRetrieverHelper] SMS verification code request failed: unknown status code: 17028 Invalid request fields in play_integrity_token

and

>Invoking original failure callbacks after phone verification failure for [My Phone Number], error - This app is not authorized to use Firebase Authentication. Please verify that the correct package name and SHA-1 are configured in the Firebase Console. [ Invalid request fields in play_integrity_token ]

Does anyone has any idea how to resolve this Issue

**Comment by Badis14** [comment]
I am experiencing a similar issue, as I recently upgraded Fire Auth to version 4.4.1 and encountered an error.

**Comment by danagbemava-nc** [comment]
Hi @hyderali0889, is this in debug or release mode? Can you also check the following StackOverflow links to see if any of the solutions stated in there work for you?
https://stackoverflow.com/questions/66848376/unknown-status-code-17028-a-safety-net-token-was-passed-but-no-matching-sha-25 

https://stackoverflow.com/questions/46751766/this-app-is-not-authorized-to-use-firebase-authentication-please-verify-that-the/53513327#53513327

**Comment by hyderali0889** [comment]
> Hi @hyderali0889, is this in debug or release mode? Can you also check the following StackOverflow links to see if any of the solutions stated in there work for you? https://stackoverflow.com/questions/66848376/unknown-status-code-17028-a-safety-net-token-was-passed-but-no-matching-sha-25
> 
> https://stackoverflow.com/questions/46751766/this-app-is-not-authorized-to-use-firebase-authentication-please-verify-that-the/53513327#53513327

As Safety net's support is depreciated the first one is not the sol and my app is not on play store.

**Comment by danagbemava-nc** [comment]
Hi @hyderali0889, 

Please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with steps to reproduce so that we can investigate this issue. 

Please also provide the output of `flutter pub deps -- --style=compact`

Also, have you uploaded your debug token for app check?

Thank you
