### ISSUE TITLE
🐛 [firebase_ui_auth & firebase_ui_oauth] use an older version of flutter_svg dependency

### ISSUE THREAD

**Issue by elodieferrais** [firebase/flutterfire#10794]
## Bug report

**Describe the bug**
I see an error message when adding Firebase package to flutter app:

_Because flutterfire_ui >=0.3.0 depends on flutter_svg ^1.0.0 and flutterfire_ui <0.3.0 depends on flutter_svg ^0.22.0, every version of flutterfire_ui requires flutter_svg ^0.22.0 or ^1.0.0_

### Steps to reproduce

1. Create a flutter project 
2. add the dependency `flutter_svg: ^2.0.2`
3. Add the package `flutterfire_ui` using flutter command line `flutter pub add flutterfire_ui`

### Expected behavior

no error and package added
### Sample project

any project using `flutter_svg: ^2.0.2`

---

**Comment by danagbemava-nc** [comment]
Hi @elodieferrais, flutterfire_ui has been deprecated so you'll need to use one of the specific UI libraries. See https://pub.dev/packages/flutterfire_ui#-flutterfire-ui-is-deprecated


That being said, it looks like the `firebase_ui_oauth` & `firebase_ui_auth` packages are using older versions of `flutter_svg`. 

https://github.com/firebase/flutterfire/blob/a1363b02fdb12602df535f12bf875f85857524a5/packages/firebase_ui_oauth/pubspec.yaml#L15

```
flutter pub add firebase_ui_oauth
Because every version of firebase_ui_oauth depends on flutter_svg ^1.1.2 and uit depends on flutter_svg ^2.0.5, firebase_ui_oauth is forbidden.
So, because uit depends on firebase_ui_oauth any, version solving failed.
pub finished with exit code 65
```

https://github.com/firebase/flutterfire/blob/a1363b02fdb12602df535f12bf875f85857524a5/packages/firebase_ui_auth/pubspec.yaml#L23

```
flutter pub add firebase_ui_auth
Because every version of firebase_ui_auth depends on flutter_svg ^1.1.1 and uit depends on flutter_svg ^2.0.5, firebase_ui_auth is forbidden.
So, because uit depends on firebase_ui_auth any, version solving failed.
pub finished with exit code 65
```

**Comment by elodieferrais** [comment]
Thank you @danagbemava-nc ,
I will open the same issue for these 2 packages 👍

**Comment by vduseev** [comment]
While we are at it, could we please also update all other dependencies? Such as `google_sign_in` and `firebase_auth`? 🙏

**Comment by JSlast** [comment]
Hi Team

Any update on this?

I have Stream Chat and Firebase Ui Auth Conflicting as Stream Chat depends on flutter_svg: ^ 2.0.4 and Firebase_ui_auth depends on flutter_svg: ^1.1.1.

Thank you for looking into this.

**Comment by rubenaster** [comment]
Same issue here.

Fix shouldn't be too complicated, IMHO.
