### ISSUE TITLE
🐛 [firebase_ui_auth] example on pub.dev 

### ISSUE THREAD

**Issue by jarrodcolburn** [firebase/flutterfire#10796]
## Bug report
the following line is producing an error.

https://github.com/firebase/flutterfire/blob/a1363b02fdb12602df535f12bf875f85857524a5/packages/firebase_ui_auth/README.md?plain=1#L43

```const providers = [EmailAuthProvider()];```

See screencast for description 

[Screen recording 2023-04-16 08.21.31.webm](https://user-images.githubusercontent.com/16673615/232314327-9562d5f3-16f6-4d3d-91f2-47a8e36489dc.webm)

**Comment by jarrodcolburn** [comment]
If you want to use the proposed change of swapping cost to final, please see PR.
https://github.com/firebase/flutterfire/pull/10797

if a different solution is required please close PR 10797. thanks

**Comment by darshankawar** [comment]
@jarrodcolburn 
Thanks for the report. The usage `const providers = [EmailAuthProvider()];` only seems to be present in the readMe section of the plugin: https://pub.dev/packages/firebase_ui_auth

But if you take a look at actual example : https://pub.dev/packages/firebase_ui_auth/example, it is implemented as below:

https://github.com/firebase/flutterfire/blob/a1363b02fdb12602df535f12bf875f85857524a5/packages/firebase_ui_auth/example/lib/main.dart#L38

Which is coming from:

https://github.com/firebase/flutterfire/blob/master/packages/firebase_ui_auth/lib/src/providers/email_auth_provider.dart

But you are right it seems. The readMe example from pub.dev can be fixed per your suggestion. We can keep the PR open for team to look at and provide any feedback if required.

**Comment by lesnitsky** [comment]
You need to hide `EmalAuthProvider` from `firebase_auth` (line 2 of the example code on readme)
