### ISSUE TITLE
🐛 [firebase_auth] signInWithEmailAndPassword doesn't return AuthCredential

### ISSUE THREAD

**Issue by puf** [firebase/flutterfire#10798]
## Bug report

After calling `signInWithEmailAndPassword`, the resulting [`UserCredential`](https://pub.dev/documentation/firebase_auth/latest/firebase_auth/UserCredential-class.html) should have a `AuthCredential` object in its `credential` property, but (on web at least) it is empty. The native JavaScript SDK *does* populate the `credential` property, so the Flutter SDK behaves differently here

### Steps to reproduce

Sign in to your project with code like this:

  ```
  var cred = await FirebaseAuth.instance.signInWithEmailAndPassword(
                  email: "user@acme.com", password: "CorrectHorseBatteryStaple");
  print(cred.credential);
 ```

### Expected behavior

The Dart code should print the `EmailAuthCredential` that was used to sign in the user (similar to what the JavaScript repro does), but instead it prints `null`.

### Sample project

Minimal repro: https://zapp.run/edit/firestore-auth-emailpassword-zd1406n6d150?file=lib/main.dart
Equivalent JavaScript repro: https://stackblitz.com/edit/auth-v9-signinwithemailandpassword?file=index.js

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.1
```

</details>

---

**Comment by Lyokone** [comment]
Hi @puf,

Looking at other platforms, they don't return the `credential` object during `signInWithEmailAndPassword` (even if the key exists).
<img width="398" alt="Screenshot 2023-04-17 at 09 40 05" src="https://user-images.githubusercontent.com/3680002/232420018-7a0ece01-01f4-4e82-ab8d-987d045c96a5.png">

Looking at the reference for the JS SDK, the UserCredential result does not contain a `credential` object as well: https://firebase.google.com/docs/reference/js/auth.usercredential

And looking at your example, the "cred" object also does not contain a `credential` key.
<img width="597" alt="Screenshot 2023-04-17 at 09 52 06" src="https://user-images.githubusercontent.com/3680002/232420797-50a08c97-945b-455d-99dd-ff350c870465.png">

I'm not sure if I'm missing something here.

**Comment by SiffatAhmed** [comment]
Hi, @Lyokone ,
I had initially posted base version of this problem on [stackoverflow ](https://stackoverflow.com/questions/76027992/flutter-credentials-returning-null-whereas-sign-in-successful) and then thanks to @puf who raised it here.

If we assume that credential.credential is ought to be null then how do we accessToken once user is logged in? because accessToken is accessed as credential.credential!.accessToken? I'm new to firebase use correct me if I'm wrong.

**Comment by puf** [comment]
Hey @Lyokone, I have no idea where I got the idea from that the JavaScript SDK returns a `credential` property. I think I might have been confused about the `UserCredentialImpl` itself. :-(

@SiffatAhmed: there's no way to get an OAuth2 access token when signing in to Firebase with email+password, as Firebase only generates a refresh token and the ID token JWT in that scenario.

**Comment by SiffatAhmed** [comment]
Thanks for clarifying @puf Much appreciated. 👍 

Leaving below for other devs:
Here's the code for this token in flutter:
`await credential.user!.getIdToken()`
