### ISSUE TITLE
[firebase_messaging]: Question: Messages with alert and `content-available`

### ISSUE THREAD

**Issue by MarcinusX** [firebase/flutterfire#10806]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you aware of the differences between iOS and Android background message handling?

- [X] I understand that iOS and Android background messages behave differently, and I've designed my application with that in mind.

### Do you have an active Apple Developer account?

- [X] I have an active Apple Developer account.

### Are you using a physical iOS device to test background messages?

- [X] I am using a physical iOS device to test background messages.

### Have you enabled "Remote Notifications" & "Background Mode" (Checking options for "Background Processing" & "Remote Notifications") in your app's Xcode project?

![image](https://user-images.githubusercontent.com/16286046/232724718-b0fe5a5d-52e2-4b6d-aa2f-458c66988b3b.png)

### Have you created an APNs key in your Apple Developer account & uploaded this APNs key to your Firebase console?

Yes

### Have you disabled method swizzling for Firebase in your app?

Yes

### Are you sending messages to your app from the Firebase Admin SDK?

Yes

### Have you requested permission from the user to receive notifications?

- [X] I have the relevant permission to receive notifications.

### Have you used the 'Console' application on your macOS device to check if the iOS device's system is throttling your background messages?

No.

### Additional context and comments

Sorry if I shouldn't use the "Bug" form, since this issue is meant to be a question, not a bug.

I can see in that form mentions on risks of throttling background messages (messages that have `content-available` only).

What I can't find is whether the same risks are applied to messages that do have alert, badge, sound AND `content-available`. If I add `content-available` to my message that is designed to be displayed and acted on by the user, does it make it subjective to all the ios background risks like throttling?

More context: I want to send an Analytics event every time I receive a notification (therefore hooking into background message). But I don't want it to cause the drawbacks mentioned above.

**Comment by darshankawar** [comment]
> ### Additional context and comments
> Sorry if I shouldn't use the "Bug" form, since this issue is meant to be a question, not a bug.
> 
> I can see in that form mentions on risks of throttling background messages (messages that have `content-available` only).
> 
> What I can't find is whether the same risks are applied to messages that do have alert, badge, sound AND `content-available`. If I add `content-available` to my message that is designed to be displayed and acted on by the user, does it make it subjective to all the ios background risks like throttling?
> 
> More context: I want to send an Analytics event every time I receive a notification (therefore hooking into background message). But I don't want it to cause the drawbacks mentioned above.

Treating this as a documentation / question for the team.

/cc @Lyokone for thoughts.

**Comment by russellwheatley** [comment]
Yes, you will definitely still be subject to iOS throttling policy, `content-available` doesn't allow you to send unlimited amount of messages. There isn't a policy as such for how they throttle messages.

As far as I'm aware, Apple does throttle for spammy notifications and excessive volume.

My advice would be to pay attention to the level of notifications you send and when it becomes obvious notifications are being throttled. Then you can design your app to stay within the upper bounds of that limit.
