### ISSUE TITLE
[📚] Cloud Function Gen2 in Firebase - Limited Supported Regions

### ISSUE THREAD

**Issue by jbaptisteroesch** [firebase/flutterfire#10811]
Hi,

I have been trying to get a Cloud Function Gen2 to work with Flutter for the past few days. Although the community has been helpful in addressing several issues, I still have a question about making a function work in the eu-west-3 region with Firebase. I am opening a new issue since this question is related to the same topic but differs in focus. You can find the history of our previous discussions here:

- https://github.com/firebase/flutterfire/issues/10795
- https://github.com/firebase/flutterfire/issues/10541

As Loykone pointed out in issue 10541, the supposedly supported regions for Firebase Functions Gen2 are listed on the following documentation page:

- https://firebase.google.com/docs/reference/functions/2nd-gen/node/firebase-functions.md#supportedregion

The supported regions listed are: "asia-northeast1", "europe-north1", "europe-west1", "europe-west4", "us-central1", "us-east1", and "us-west1". However, the Google Cloud documentation for Cloud Functions shows a broader list of supported regions.

My question is: Why does Firebase only support a subset of the available regions? I tried using eu-west-3, and it didn't work, while eu-west-1 did. However, the response time for eu-west-1 is twice as long as for eu-west-3, which is not ideal for my use case.

Is there a specific reason for this limitation in the Firebase SDK? Should I consider using the Google APIs package directly instead?

Thank you for your assistance!

**Comment by darshankawar** [comment]
I am not sure if this is actionable from client side. This should be a question for native SDK team, but I'll keep it open and label for team's input on this.

/cc @Lyokone

**Comment by Lyokone** [comment]
@jbaptisteroesch This is not a limitation of FlutterFire but a limitation of Google Cloud directly (the link I shared is from the Node SDK, for instance). 

> the Google Cloud documentation for Cloud Functions shows a broader list of supported regions.

Do you have a link to this documentation?

**Comment by jbaptisteroesch** [comment]
@Lyokone 
> Do you have a link to this documentation?

https://cloud.google.com/functions/docs/locations#tier_2_pricing

**Comment by Lyokone** [comment]
Thanks, I'll see internally if those informations are up to date

**Comment by Lyokone** [comment]
@jbaptisteroesch I didn't hear back, I'll ping again.

**Comment by Lyokone** [comment]
@jbaptisteroesch An issue was opened to track this https://github.com/firebase/firebase-functions/issues/1397

**Comment by nohe427** [comment]
Looks like this was merged into the functions SDK last week. Are you still experiencing issues with making a function work in the eu-west-3 region?

**Comment by jbaptisteroesch** [comment]
The issue seems to be resolved, thank you for your help.
