### ISSUE TITLE
🐛 [firebase_storage] Slow upload speed

### ISSUE THREAD

**Issue by iLoveDocs** [firebase/flutterfire#10828]
## Bug report

**Describe the bug**
The upload speed is way too slow. It took over ~5 seconds to upload a ~40 KB file. I am not sure if this is related to AppCheck.

### Steps to reproduce
Call this function:
```dart
Future<void> _uploadFile() async {
  final XFile? xFile = await ImagePicker().pickImage(
    source: ImageSource.gallery,
  );

  if (xFile != null) {
    final File image = File(xFile.path);
    final int size = image.readAsBytesSync().lengthInBytes ~/ 1024;
    print('image size = $size kb');

    final FirebaseStorage instance = FirebaseStorage.instance;
    final storageRef = instance.ref('test/foo');

    final DateTime d = DateTime.now();
    await storageRef.putFile(image);
    print('upload took = ${DateTime.now().difference(d).inMilliseconds} ms');
  }
}
```

### Android:
```
I/flutter (19168): image size = 44 kb
W/StorageUtil(19168): Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: Error returned from API. code: 403 body: App attestation failed.
D/UploadTask(19168): Waiting 0 milliseconds
W/StorageUtil(19168): Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: Too many attempts.
I/flutter (19168): upload took = 4714 ms
```

### iOS (different file)
```
flutter: image size = 103 kb
flutter: upload took = 2550 ms
image_picker: compressing is not supported for type .png. Returning the image with original quality
flutter: image size = 398 kb
flutter: upload took = 2789 ms
flutter: image size = 6578 kb
flutter: upload took = 12433 ms
```

### iOS (same file)
```
flutter: image size = 103 kb
flutter: upload took = 1997 ms
flutter: image size = 103 kb
flutter: upload took = 2863 ms
flutter: image size = 103 kb
flutter: upload took = 2235 ms
flutter: image size = 103 kb
flutter: upload took = 2159 ms
```

## Additional context
- Using `firebase_storage: "11.1.0"` version.
- Tested in both Emulator and Physical device (Android and iOS) 
- My network upload speed is a little over 5 Mbps.

![telegram-cloud-photo-size-5-6205996257323890646-x](https://user-images.githubusercontent.com/65380329/233799471-83ebe845-975d-4a6d-8cd4-4d34cb918cb2.jpg)

---

### Flutter doctor
```
[✓] Flutter (Channel master, 3.8.0-13.0.pre.79, on macOS 13.3.1 22E261 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Community Edition (version 2022.3)
[✓] VS Code (version 1.77.1)
[✓] Connected device (3 available)
[✓] Network resources
```

**Comment by darshankawar** [comment]
Thanks for the report @iLoveDocs 


> The upload speed is way too slow. It took over ~5 seconds to upload a ~40 KB file.

This is not in the control of the code we write. The speed is related to your machine's network and server to which the request is being sent. Can you provide the details as to which region are you connected to / using ? Maybe try using another region and see if it helps in improving the speed or if it gives you same results ?

**Comment by iLoveDocs** [comment]
Hi @darshankawar 

Sorry, I didn't get you by "region"?

**Comment by darshankawar** [comment]
> I didn't get you by "region"?

@iLoveDocs I meant, like below:

<img width="170" alt="Screenshot 2023-04-25 at 1 23 01 PM" src="https://user-images.githubusercontent.com/67046386/234211124-d1422276-4d33-4d9a-b2ee-729b9a948641.png">

**Comment by darshankawar** [comment]
Thanks for the feedback. As I mentioned earlier, I am not sure if there's anything actionable from flutterfire side on slow upload / download speed. Please check [this](https://groups.google.com/g/firebase-talk/c/o-T4qe0WxBg/m/a2jqmuSmBwAJ) link and see if it helps.

**Comment by iLoveDocs** [comment]
Thanks but that didn't help. What should I do, close the issue?

**Comment by darshankawar** [comment]
Maybe you can reach out to firebase support for further resolution and see what they say.
