### ISSUE TITLE
🐛 [cloud_firestore_odm] Why is build.yaml needed?

### ISSUE THREAD

**Issue by jarrodcolburn** [firebase/flutterfire#10844]
## Bug report

Please see video 
[Screen recording 2023-04-25 08.43.06.webm](https://user-images.githubusercontent.com/16673615/234296183-deee24a4-4c26-436d-ac89-baa8b4084625.webm)

I get a errors, for example:
`Undefined name '_$ShowFieldMap'.`
`Try correcting the name to one that is defined, or defining the name.`

### Steps to reproduce

After running ` flutter pub run build_runner build --delete-conflicting-outputs`

### Solution 

Copy `build.yaml` file from example

https://github.com/firebase/flutterfire/blob/master/packages/cloud_firestore_odm/cloud_firestore_odm/example/build.yaml

Why is this build.yaml needed? If it is intended not to be needed in the future, but must be for now, can it be included in the documentation at https://firebase.flutter.dev/docs/firestore-odm/overview/ please?

**Comment by rrousselGit** [comment]
The ODM relies on `create_field_map` to be enabled to work.

I'll update the docs. But do note that the website is no-longer updated. Docs are found here instead: https://github.com/firebase/flutterfire/tree/master/packages/cloud_firestore_odm

**Comment by jarrodcolburn** [comment]
@rrousselGit 
Quick question about your comment...
> But do note that the website is no-longer updated.

...what about the package `cloud_firestore_odm` itself (not the website)?

Should I continue to use the package, or is it being deprecated? If it is being deprecated, maybe I'm missing it, but can you please tell me what is the recommended alternative way forward to connect `firestore` and `flutter` ?

thanks so much

**Comment by rrousselGit** [comment]
the package can be used. It's the website that isn't maintained

**Comment by jarrodcolburn** [comment]
@rrousselGit 

Thanks, but can you please clarify. What is the recommended way to connect `firestore` and `flutter`? I see that many new `firebse_ui_[product]` packages are coming out. Is the `firebase_ui_firestore` package the new recommended way? 

This seems to lack the features of `odm`. Are we supposed to use them together, if so I don't really understand how, as the `odm` abstracts away a lot of the interaction with the Firestore `instance`

Please understand, I don't want to spend more time integrating the `odm` if another path forward is recommended.
