### ISSUE TITLE
🐛 [firebase_auth]  Android SDK down

### ISSUE THREAD

**Issue by NaosFr** [firebase/flutterfire#10846]
https://status.firebase.google.com/incidents/UY1LTFan8X5oybhphzfV

it's been 9 days, we need updates on the situation thanks, too many users on android never receive sms

**Comment by darshankawar** [comment]
@NaosFr 
This is something not in control of FltuterFire team. Please reach out to [Firebase support](https://firebase.google.com/support).
Closing from here.
