### ISSUE TITLE
[firebase_messaging]: FirebaseMessaging.onBackgroundMessage not working in terminated state for iOS

### ISSUE THREAD

**Issue by Vipulwaghmare** [firebase/flutterfire#10840]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you aware of the differences between iOS and Android background message handling?

- [X] I understand that iOS and Android background messages behave differently, and I've designed my application with that in mind.

### Do you have an active Apple Developer account?

- [X] I have an active Apple Developer account.

### Are you using a physical iOS device to test background messages?

- [X] I am using a physical iOS device to test background messages.

### Have you enabled "Remote Notifications" & "Background Mode" (Checking options for "Background Processing" & "Remote Notifications") in your app's Xcode project?

<img width="1439" alt="Screenshot 2023-04-25 at 10 59 28 AM" src="https://user-images.githubusercontent.com/66200734/234182604-b5f2c4cf-96c7-476f-9e9a-37a97293b0d1.png">

### Have you created an APNs key in your Apple Developer account & uploaded this APNs key to your Firebase console?

<img width="952" alt="Screenshot 2023-04-25 at 11 02 32 AM" src="https://user-images.githubusercontent.com/66200734/234183138-ba41e0bf-e01d-4f6e-b752-7288e82d5298.png">

### Have you disabled method swizzling for Firebase in your app?

<img width="965" alt="Screenshot 2023-04-25 at 11 06 45 AM" src="https://user-images.githubusercontent.com/66200734/234183599-c0245475-248e-4305-9f0e-a13cbf75c82a.png">

### Are you sending messages to your app from the Firebase Admin SDK?

![backendcallnotificaion](https://user-images.githubusercontent.com/66200734/234183894-97755146-716c-44b4-9c43-135ad95e6083.png)

```
fcm.send({
    data: data.payload,
    token: data.token,
    android: {
      data: data.payload,
    },
    apns: {
      headers: {
        "apns-priority": "5",
      },
      payload: {
        aps: {
          contentAvailable: true,
          mutableContent: true,
          alert: {
            title: "TITLE",
            subtitle: "SUBTITLE",
            body: "BODY",
          }, 
          category: "FLUTTER_NOTIFICATION_CLICK",
        },
      },
    },
  });
```

### Have you requested permission from the user to receive notifications?

- [X] I have the relevant permission to receive notifications.

### Have you used the 'Console' application on your macOS device to check if the iOS device's system is throttling your background messages?

<img width="1712" alt="Screenshot 2023-04-25 at 11 21 38 AM" src="https://user-images.githubusercontent.com/66200734/234190298-558745bb-5c78-4faa-84e6-2d3e8ee9a07c.png">

default	11:48:02.216264+0530	SpringBoard	Received incoming message on topic com.influentialbrands.ibapp at priority 5
default	11:48:02.232266+0530	SpringBoard	[com.influentialbrands.ibapp] Received remote notification request BA86-E6A6 [ waking: 0, hasAlertContent: 0, hasSound: 0 hasBadge: 0 hasContentAvailable: 1 hasMutableContent: 1 pushType: Background]
default	11:48:02.232435+0530	SpringBoard	[com.influentialbrands.ibapp] Process delivery of push notification BA86-E6A6
default	11:48:02.232489+0530	SpringBoard	[com.influentialbrands.ibapp] Request DUET delivers content-available push notification to application
default	11:48:02.232784+0530	SpringBoard	SUBMITTING: com.apple.pushLaunch.com.influentialbrands.ibapp:A70163
default	11:48:02.234155+0530	dasd	Submitted Activity: com.apple.pushLaunch.com.influentialbrands.ibapp:A70163 at priority 5 (Tue Apr 25 11:48:02 2023 - Wed Apr 26 11:48:02 2023)
default	11:48:02.239975+0530	dasd	Daemon Canceling Activities: {(
    com.apple.pushLaunch.com.influentialbrands.ibapp:C83A41
)}
default	11:48:02.240175+0530	dasd	CANCELED: com.apple.pushLaunch.com.influentialbrands.ibapp:C83A41 at priority 10 <private>!
default	11:48:02.247837+0530	dasd	com.apple.pushLaunch.com.influentialbrands.ibapp:A70163:[
	{name: ApplicationPolicy, policyWeight: 50.000, response: {Decision: Absolutely Must Not Proceed, Score: 0.00, Rationale: [{[pushDisallowed]: Required:0.00, Observed:1.00},]}}
 ], FinalDecision: Absolutely Must Not Proceed}

### Additional context and comments

The  FirebaseMessaging.onBackgroundMessage is not getting called only when app is terminated.
It works perfectly fine when app goes in the background. 
I have tried sending notifications with different payloads, but still it doesn't run.
When I send both data and notifications in the payload, it shows the notification due to the notification in the payload, but the
onBackgroundMessage is still not getting run. I have tried adding "contentAvailable" and "mutableContent" as true like it is said in most of the answers and I have implemented all the settings above.

**Comment by darshankawar** [comment]
Thanks for the report @Vipulwaghmare 
Check [this](https://github.com/firebase/flutterfire/issues/9718#issuecomment-1429906876) comment to see if it helps to answer your query.

Also, see this issue for your reference: https://github.com/firebase/flutterfire/issues/7407

**Comment by Joseph-Nathan** [comment]
```
I/FLTFireMsgService(xxxxx): FlutterFirebaseMessagingBackgroundService started!
```
not appears when i run ios .

**Comment by Joseph-Nathan** [comment]
@Vipulwaghmare are you found any solution ?
