### ISSUE TITLE
ptrauth.h FILE NOT FOUND ERROR

### ISSUE THREAD

**Issue by mHassan20896** [firebase/flutterfire#10850]
1. Create a new project
2. Add firebase_crashlytics package
3. Then run the project on iOS simulator, you will get the following error

Lexical or Preprocessor Issue (Xcode): 'ptrauth.h' file not found
/Users/muhammadhassanshakeel/Desktop/hello_world/ios/Pods/FirebaseCrashlytics/Cr
ashlytics/Crashlytics/Helpers/FIRCLSThreadState.c:20:9

**Comment by danagbemava-nc** [comment]
Hi @mHassan20896, I followed the steps you have outlined above and I was able to run the app successfully on both an iOS simulator and a physical iOS device. 

Please provide the output of `flutter doctor -v` and the output of `flutter pub -- --deps style=compact`. 

If you could also provide the code sample you're facing the issue with, that would be ideal.

Thank you

<details>
<summary>logs</summary>

```
Multiple devices found:
Nexus (mobile)             • 00008020-001875E83A38002E            • ios            • iOS 16.4.1 20E252
iPhone 14 Pro Max (mobile) • 2BCD9772-DE01-4F2E-BE19-E81B9B9C0535 • ios            •
com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.3.1 22E261 darwin-arm64
Chrome (web)               • chrome                               • web-javascript • Google Chrome 112.0.5615.137
[1]: Nexus (00008020-001875E83A38002E)
[2]: iPhone 14 Pro Max (2BCD9772-DE01-4F2E-BE19-E81B9B9C0535)
[3]: macOS (macos)
[4]: Chrome (chrome)
Please choose one (To quit, press "q/Q"): 2
Launching lib/main.dart on iPhone 14 Pro Max in debug mode...
Running Xcode build...
 └─Compiling, linking and signing...                        10.0s
Xcode build done.                                           83.7s
Syncing files to device iPhone 14 Pro Max...                       319ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on iPhone 14 Pro Max is available at: http://127.0.0.1:52040/snZPl7d6Bwo=/
The Flutter DevTools debugger and profiler on iPhone 14 Pro Max is available at:
http://127.0.0.1:9100?uri=http://127.0.0.1:52040/snZPl7d6Bwo=/

Application finished.
```
</details>

**Comment by mHassan20896** [comment]
**Output of flutter doctor -v**

✓] Flutter (Channel stable, 3.7.12, on macOS 13.3.1
    22E261 darwin-arm64, locale en-GB)
    • Flutter version 3.7.12 on channel stable at
      /Users/muhammadhassanshakeel/flutter
    • Upstream repository
      https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (8 days ago),
      2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices
    (Android SDK version 33.0.2)
    • Android SDK at
      /Users/muhammadhassanshakeel/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at
      /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google
      Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨
      https://plugins.jetbrains.com/plugin/9212-flutte
      r
    • Dart plugin can be installed from:
      🔨
      https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio
      Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) •
      225F31FB-C11C-44C3-81DA-91E109C9591D • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4
      (simulator)
    • macOS (desktop)        • macos
      • darwin-arm64   • macOS 13.3.1 22E261
      darwin-arm64
    • Chrome (web)           • chrome
      • web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!


**Output of flutter pub deps**

Dart SDK 2.19.6
Flutter SDK 3.7.12
quran 1.1.8+35
├── app_tracking_transparency 2.0.3
│   └── flutter...
├── audio_session 0.1.13
│   ├── flutter...
│   ├── flutter_web_plugins...
│   ├── meta...
│   └── rxdart...
├── audio_wave 0.1.5
│   └── flutter...
├── audio_waveforms 0.1.5+1
│   └── flutter...
├── audioplayers 0.20.1
│   ├── flutter_web_plugins 0.0.0
│   │   ├── characters...
│   │   ├── collection...
│   │   ├── flutter...
│   │   ├── js...
│   │   ├── material_color_utilities...
│   │   ├── meta...
│   │   └── vector_math...
│   ├── uuid 3.0.7
│   │   └── crypto...
│   ├── flutter...
│   ├── http...
│   └── path_provider...
├── bloc_test 8.5.0
│   ├── diff_match_patch 0.4.1
│   ├── test 1.22.0
│   │   ├── analyzer 5.10.0
│   │   │   ├── _fe_analyzer_shared 58.0.0
│   │   │   │   └── meta...
│   │   │   ├── convert 3.1.1
│   │   │   │   └── typed_data...
│   │   │   ├── glob 2.1.1
│   │   │   │   ├── async...
│   │   │   │   ├── collection...
│   │   │   │   ├── file...
│   │   │   │   ├── path...
│   │   │   │   └── string_scanner...
│   │   │   ├── pub_semver 2.1.3
│   │   │   │   ├── collection...
│   │   │   │   └── meta...
│   │   │   ├── watcher 1.0.2
│   │   │   │   ├── async...
│   │   │   │   └── path...
│   │   │   ├── collection...
│   │   │   ├── crypto...
│   │   │   ├── meta...
│   │   │   ├── package_config...
│   │   │   ├── path...
│   │   │   ├── source_span...
│   │   │   └── yaml...
│   │   ├── coverage 1.6.3
│   │   │   ├── args 2.4.0
│   │   │   ├── logging 1.1.1
│   │   │   ├── source_maps 0.10.12
│   │   │   │   └── source_span...
│   │   │   ├── package_config...
│   │   │   ├── path...
│   │   │   ├── stack_trace...
│   │   │   └── vm_service...
│   │   ├── http_multi_server 3.2.1
│   │   │   └── async...
│   │   ├── io 1.0.4
│   │   │   ├── meta...
│   │   │   ├── path...
│   │   │   └── string_scanner...
│   │   ├── node_preamble 2.0.2
│   │   ├── package_config 2.1.0
│   │   │   └── path...
│   │   ├── pool 1.5.1
│   │   │   ├── async...
│   │   │   └── stack_trace...
│   │   ├── shelf 1.4.0
│   │   │   ├── async...
│   │   │   ├── collection...
│   │   │   ├── http_parser...
│   │   │   ├── path...
│   │   │   ├── stack_trace...
│   │   │   └── stream_channel...
│   │   ├── shelf_packages_handler 3.0.1
│   │   │   ├── path...
│   │   │   ├── shelf...
│   │   │   └── shelf_static...
│   │   ├── shelf_static 1.1.1
│   │   │   ├── convert...
│   │   │   ├── http_parser...
│   │   │   ├── mime...
│   │   │   ├── path...
│   │   │   └── shelf...
│   │   ├── shelf_web_socket 1.0.3
│   │   │   ├── shelf...
│   │   │   ├── stream_channel...
│   │   │   └── web_socket_channel...
│   │   ├── test_core 0.4.20
│   │   │   ├── frontend_server_client 3.2.0
│   │   │   │   ├── async...
│   │   │   │   └── path...
│   │   │   ├── source_map_stack_trace 2.1.1
│   │   │   │   ├── path...
│   │   │   │   ├── source_maps...
│   │   │   │   └── stack_trace...
│   │   │   ├── analyzer...
│   │   │   ├── args...
│   │   │   ├── async...
│   │   │   ├── boolean_selector...
│   │   │   ├── collection...
│   │   │   ├── coverage...
│   │   │   ├── glob...
│   │   │   ├── io...
│   │   │   ├── matcher...
│   │   │   ├── meta...
│   │   │   ├── package_config...
│   │   │   ├── path...
│   │   │   ├── pool...
│   │   │   ├── source_maps...
│   │   │   ├── source_span...
│   │   │   ├── stack_trace...
│   │   │   ├── stream_channel...
│   │   │   ├── test_api...
│   │   │   ├── vm_service...
│   │   │   └── yaml...
│   │   ├── web_socket_channel 2.3.0
│   │   │   ├── async...
│   │   │   ├── crypto...
│   │   │   └── stream_channel...
│   │   ├── webkit_inspection_protocol 1.2.0
│   │   │   └── logging...
│   │   ├── yaml 3.1.1
│   │   │   ├── collection...
│   │   │   ├── source_span...
│   │   │   └── string_scanner...
│   │   ├── async...
│   │   ├── boolean_selector...
│   │   ├── collection...
│   │   ├── js...
│   │   ├── path...
│   │   ├── source_span...
│   │   ├── stack_trace...
│   │   ├── stream_channel...
│   │   ├── test_api...
│   │   └── typed_data...
│   ├── bloc...
│   ├── meta...
│   └── mocktail...
├── carousel_slider 4.2.1
│   └── flutter...
├── connectivity_plus 2.3.9
│   ├── connectivity_plus_linux 1.3.1
│   │   ├── nm 0.5.0
│   │   │   └── dbus 0.7.8
│   │   │       ├── args...
│   │   │       ├── ffi...
│   │   │       ├── meta...
│   │   │       └── xml...
│   │   ├── connectivity_plus_platform_interface...
│   │   ├── flutter...
│   │   └── meta...
│   ├── connectivity_plus_macos 1.2.6
│   │   ├── connectivity_plus_platform_interface...
│   │   └── flutter...
│   ├── connectivity_plus_platform_interface 1.2.4
│   │   ├── flutter...
│   │   ├── meta...
│   │   └── plugin_platform_interface...
│   ├── connectivity_plus_web 1.2.5
│   │   ├── connectivity_plus_platform_interface...
│   │   ├── flutter...
│   │   ├── flutter_web_plugins...
│   │   └── js...
│   ├── connectivity_plus_windows 1.2.2
│   │   ├── connectivity_plus_platform_interface...
│   │   └── flutter...
│   └── flutter...
├── cupertino_icons 1.0.5
├── customized_package 0.0.1
│   └── flutter...
├── device_info_plus 6.0.0
│   ├── device_info_plus_linux 5.0.0
│   │   ├── device_info_plus_platform_interface...
│   │   ├── file...
│   │   ├── flutter...
│   │   └── meta...
│   ├── device_info_plus_macos 5.0.0
│   │   ├── device_info_plus_platform_interface...
│   │   └── flutter...
│   ├── device_info_plus_platform_interface 5.0.0
│   │   ├── flutter...
│   │   ├── meta...
│   │   └── plugin_platform_interface...
│   ├── device_info_plus_web 5.0.0
│   │   ├── device_info_plus_platform_interface...
│   │   ├── flutter...
│   │   └── flutter_web_plugins...
│   ├── device_info_plus_windows 6.0.0
│   │   ├── device_info_plus_platform_interface...
│   │   ├── ffi...
│   │   ├── flutter...
│   │   ├── meta...
│   │   └── win32...
│   └── flutter...
├── equatable 2.0.5
│   ├── collection...
│   └── meta...
├── firebase_analytics 10.0.3
│   ├── firebase_analytics_platform_interface 3.4.0
│   │   ├── _flutterfire_internals 1.1.0
│   │   │   ├── collection...
│   │   │   ├── firebase_core...
│   │   │   ├── firebase_core_platform_interface...
│   │   │   ├── flutter...
│   │   │   └── meta...
│   │   ├── firebase_core...
│   │   ├── flutter...
│   │   ├── meta...
│   │   └── plugin_platform_interface...
│   ├── firebase_analytics_web 0.5.2
│   │   ├── _flutterfire_internals...
│   │   ├── firebase_analytics_platform_interface...
│   │   ├── firebase_core...
│   │   ├── firebase_core_web...
│   │   ├── flutter...
│   │   ├── flutter_web_plugins...
│   │   └── js...
│   ├── firebase_core_platform_interface 4.6.0
│   │   ├── collection...
│   │   ├── flutter...
│   │   ├── flutter_test...
│   │   ├── meta...
│   │   └── plugin_platform_interface...
│   ├── firebase_core...
│   └── flutter...
├── firebase_auth 4.4.0
│   ├── firebase_auth_platform_interface 6.13.0
│   │   ├── _flutterfire_internals...
│   │   ├── collection...
│   │   ├── firebase_core...
│   │   ├── flutter...
│   │   ├── meta...
│   │   └── plugin_platform_interface...
│   ├── firebase_auth_web 5.3.0
│   │   ├── firebase_auth_platform_interface...
│   │   ├── firebase_core...
│   │   ├── firebase_core_web...
│   │   ├── flutter...
│   │   ├── flutter_web_plugins...
│   │   ├── http_parser...
│   │   ├── intl...
│   │   ├── js...
│   │   └── meta...
│   ├── firebase_core...
│   ├── firebase_core_platform_interface...
│   ├── flutter...
│   └── meta...
├── firebase_core 2.9.0
│   ├── firebase_core_web 2.3.0
│   │   ├── firebase_core_platform_interface...
│   │   ├── flutter...
│   │   ├── flutter_web_plugins...
│   │   ├── js...
│   │   └── meta...
│   ├── firebase_core_platform_interface...
│   ├── flutter...
│   └── meta...
├── firebase_crashlytics 3.1.0
│   ├── firebase_crashlytics_platform_interface 3.4.0
│   │   ├── _flutterfire_internals...
│   │   ├── collection...
│   │   ├── firebase_core...
│   │   ├── flutter...
│   │   ├── meta...
│   │   └── plugin_platform_interface...
│   ├── stack_trace 1.11.0
│   │   └── path...
│   ├── firebase_core...
│   ├── firebase_core_platform_interface...
│   └── flutter...
├── firebase_dynamic_links 5.1.0
│   ├── firebase_dynamic_links_platform_interface 0.2.4
│   │   ├── _flutterfire_internals...
│   │   ├── firebase_core...
│   │   ├── flutter...
│   │   ├── meta...
│   │   └── plugin_platform_interface...
│   ├── plugin_platform_interface 2.1.4
│   │   └── meta...
│   ├── firebase_core...
│   ├── firebase_core_platform_interface...
│   ├── flutter...
│   └── meta...
├── firebase_messaging 14.4.0
│   ├── firebase_messaging_platform_interface 4.3.0
│   │   ├── _flutterfire_internals...
│   │   ├── firebase_core...
│   │   ├── flutter...
│   │   ├── meta...
│   │   └── plugin_platform_interface...
│   ├── firebase_messaging_web 3.3.0
│   │   ├── _flutterfire_internals...
│   │   ├── firebase_core...
│   │   ├── firebase_core_web...
│   │   ├── firebase_messaging_platform_interface...
│   │   ├── flutter...
│   │   ├── flutter_web_plugins...
│   │   ├── js...
│   │   └── meta...
│   ├── firebase_core...
│   ├── firebase_core_platform_interface...
│   ├── flutter...
│   └── meta...
├── firebase_remote_config 3.0.15
│   ├── firebase_remote_config_platform_interface 1.2.0
│   │   ├── _flutterfire_internals...
│   │   ├── firebase_core...
│   │   ├── flutter...
│   │   ├── meta...
│   │   └── plugin_platform_interface...
│   ├── firebase_remote_config_web 1.2.0
│   │   ├── firebase_core...
│   │   ├── firebase_core_web...
│   │   ├── firebase_remote_config_platform_interface...
│   │   ├── flutter...
│   │   ├── flutter_web_plugins...
│   │   └── js...
│   ├── firebase_core...
│   ├── firebase_core_platform_interface...
│   └── flutter...
├── flutter 0.0.0
│   ├── characters 1.2.1
│   ├── collection 1.17.0
│   ├── js 0.6.5
│   │   └── meta...
│   ├── material_color_utilities 0.2.0
│   ├── meta 1.8.0
│   ├── sky_engine 0.0.99
│   └── vector_math 2.1.4
├── flutter_asa_attribution 0.0.3
│   └── flutter...
├── flutter_bloc 7.3.3
│   ├── bloc 7.2.1
│   │   └── meta...
│   ├── provider 6.0.5
│   │   ├── nested 1.0.0
│   │   │   └── flutter...
│   │   ├── collection...
│   │   └── flutter...
│   └── flutter...
├── flutter_cache_manager 3.3.0
│   ├── clock 1.1.1
│   ├── file 6.1.4
│   │   ├── meta...
│   │   └── path...
│   ├── pedantic 1.11.1
│   ├── rxdart 0.27.7
│   ├── collection...
│   ├── flutter...
│   ├── http...
│   ├── path...
│   ├── path_provider...
│   ├── sqflite...
│   └── uuid...
├── flutter_driver 0.0.0
│   ├── archive 3.3.2
│   │   ├── crypto...
│   │   └── path...
│   ├── boolean_selector 2.1.1
│   │   ├── source_span...
│   │   └── string_scanner...
│   ├── fuchsia_remote_debug_protocol 0.0.0
│   │   ├── file...
│   │   ├── meta...
│   │   ├── path...
│   │   ├── platform...
│   │   ├── process...
│   │   └── vm_service...
│   ├── matcher 0.12.13
│   │   ├── meta...
│   │   └── stack_trace...
│   ├── platform 3.1.0
│   ├── process 4.2.4
│   │   ├── file...
│   │   ├── path...
│   │   └── platform...
│   ├── source_span 1.9.1
│   │   ├── collection...
│   │   ├── path...
│   │   └── term_glyph...
│   ├── stream_channel 2.1.1
│   │   └── async...
│   ├── string_scanner 1.2.0
│   │   └── source_span...
│   ├── sync_http 0.3.1
│   ├── term_glyph 1.2.1
│   ├── test_api 0.4.16
│   │   ├── async...
│   │   ├── boolean_selector...
│   │   ├── collection...
│   │   ├── matcher...
│   │   ├── meta...
│   │   ├── source_span...
│   │   ├── stack_trace...
│   │   ├── stream_channel...
│   │   ├── string_scanner...
│   │   └── term_glyph...
│   ├── typed_data 1.3.1
│   │   └── collection...
│   ├── vm_service 9.4.0
│   ├── webdriver 3.0.1
│   │   ├── archive...
│   │   ├── matcher...
│   │   ├── path...
│   │   ├── stack_trace...
│   │   └── sync_http...
│   ├── async...
│   ├── characters...
│   ├── clock...
│   ├── collection...
│   ├── crypto...
│   ├── file...
│   ├── flutter...
│   ├── flutter_test...
│   ├── js...
│   ├── material_color_utilities...
│   ├── meta...
│   ├── path...
│   ├── stack_trace...
│   └── vector_math...
├── flutter_email_sender 5.2.0
│   └── flutter...
├── flutter_inappwebview 5.7.2+3
│   └── flutter...
├── flutter_lints 2.0.1
│   └── lints 2.0.1
├── flutter_svg 1.1.6
│   ├── path_drawing 1.0.1
│   │   ├── path_parsing 1.0.1
│   │   │   ├── meta...
│   │   │   └── vector_math...
│   │   ├── flutter...
│   │   ├── meta...
│   │   └── vector_math...
│   ├── xml 6.2.2
│   │   ├── petitparser 5.1.0
│   │   │   └── meta...
│   │   ├── collection...
│   │   └── meta...
│   ├── flutter...
│   ├── meta...
│   └── vector_math...
├── flutter_test 0.0.0
│   ├── fake_async 1.3.1
│   │   ├── clock...
│   │   └── collection...
│   ├── async...
│   ├── boolean_selector...
│   ├── characters...
│   ├── clock...
│   ├── collection...
│   ├── flutter...
│   ├── js...
│   ├── matcher...
│   ├── material_color_utilities...
│   ├── meta...
│   ├── path...
│   ├── source_span...
│   ├── stack_trace...
│   ├── stream_channel...
│   ├── string_scanner...
│   ├── term_glyph...
│   ├── test_api...
│   └── vector_math...
├── flutter_widget_from_html_core 0.8.5+3
│   ├── csslib 0.17.2
│   │   └── source_span...
│   ├── fwfh_text_style 2.22.08+1
│   │   └── flutter...
│   ├── html 0.15.2
│   │   ├── csslib...
│   │   └── source_span...
│   └── flutter...
├── fluttertoast 8.2.1
│   ├── flutter...
│   └── flutter_web_plugins...
├── google_sign_in 5.4.4
│   ├── google_sign_in_android 6.1.8
│   │   ├── flutter...
│   │   └── google_sign_in_platform_interface...
│   ├── google_sign_in_ios 5.6.1
│   │   ├── flutter...
│   │   └── google_sign_in_platform_interface...
│   ├── google_sign_in_platform_interface 2.3.1
│   │   ├── quiver 3.2.1
│   │   │   └── matcher...
│   │   ├── flutter...
│   │   └── plugin_platform_interface...
│   ├── google_sign_in_web 0.10.2+1
│   │   ├── flutter...
│   │   ├── flutter_web_plugins...
│   │   ├── google_sign_in_platform_interface...
│   │   └── js...
│   └── flutter...
├── grouped_list 5.1.2
│   └── flutter...
├── http 0.13.5
│   ├── async 2.10.0
│   │   ├── collection...
│   │   └── meta...
│   ├── http_parser 4.0.2
│   │   ├── collection...
│   │   ├── source_span...
│   │   ├── string_scanner...
│   │   └── typed_data...
│   ├── path 1.8.2
│   └── meta...
├── in_app_purchase 3.1.5
│   ├── in_app_purchase_android 0.2.4+3
│   │   ├── json_annotation 4.8.0
│   │   │   └── meta...
│   │   ├── collection...
│   │   ├── flutter...
│   │   └── in_app_purchase_platform_interface...
│   ├── in_app_purchase_platform_interface 1.3.3
│   │   ├── flutter...
│   │   └── plugin_platform_interface...
│   ├── in_app_purchase_storekit 0.3.6+2
│   │   ├── collection...
│   │   ├── flutter...
│   │   ├── in_app_purchase_platform_interface...
│   │   └── json_annotation...
│   └── flutter...
├── intl 0.17.0
│   ├── clock...
│   └── path...
├── introduction_screen 3.1.7
│   ├── dots_indicator 2.1.0
│   │   └── flutter...
│   ├── flutter_keyboard_visibility 5.4.0
│   │   ├── flutter_keyboard_visibility_linux 1.0.0
│   │   │   ├── flutter...
│   │   │   └── flutter_keyboard_visibility_platform_interface...
│   │   ├── flutter_keyboard_visibility_macos 1.0.0
│   │   │   ├── flutter...
│   │   │   └── flutter_keyboard_visibility_platform_interface...
│   │   ├── flutter_keyboard_visibility_platform_interface 2.0.0
│   │   │   ├── flutter...
│   │   │   ├── meta...
│   │   │   └── plugin_platform_interface...
│   │   ├── flutter_keyboard_visibility_web 2.0.0
│   │   │   ├── flutter...
│   │   │   ├── flutter_keyboard_visibility_platform_interface...
│   │   │   └── flutter_web_plugins...
│   │   ├── flutter_keyboard_visibility_windows 1.0.0
│   │   │   ├── flutter...
│   │   │   └── flutter_keyboard_visibility_platform_interface...
│   │   ├── flutter...
│   │   └── meta...
│   ├── collection...
│   └── flutter...
├── jaguar_jwt 3.0.0
│   ├── auth_header 3.0.1
│   └── crypto 3.0.2
│       └── typed_data...
├── launch_review 3.0.1
│   └── flutter...
├── lint 1.10.0
├── mocktail 0.2.0
│   ├── collection...
│   ├── matcher...
│   └── test...
├── package_info_plus 2.0.0
│   ├── package_info_plus_linux 2.0.0
│   │   ├── flutter...
│   │   ├── package_info_plus_platform_interface...
│   │   └── path...
│   ├── package_info_plus_macos 2.0.0
│   │   └── flutter...
│   ├── package_info_plus_platform_interface 2.0.1
│   │   ├── flutter...
│   │   ├── meta...
│   │   └── plugin_platform_interface...
│   ├── package_info_plus_web 2.0.0
│   │   ├── flutter...
│   │   ├── flutter_web_plugins...
│   │   ├── http...
│   │   ├── meta...
│   │   └── package_info_plus_platform_interface...
│   ├── package_info_plus_windows 3.0.0
│   │   ├── ffi...
│   │   ├── flutter...
│   │   ├── package_info_plus_platform_interface...
│   │   └── win32...
│   └── flutter...
├── path_provider 2.0.14
│   ├── path_provider_android 2.0.24
│   │   ├── flutter...
│   │   └── path_provider_platform_interface...
│   ├── path_provider_foundation 2.2.1
│   │   ├── flutter...
│   │   └── path_provider_platform_interface...
│   ├── path_provider_linux 2.1.10
│   │   ├── ffi 2.0.1
│   │   ├── xdg_directories 1.0.0
│   │   │   ├── meta...
│   │   │   ├── path...
│   │   │   └── process...
│   │   ├── flutter...
│   │   ├── path...
│   │   └── path_provider_platform_interface...
│   ├── path_provider_platform_interface 2.0.6
│   │   ├── flutter...
│   │   ├── platform...
│   │   └── plugin_platform_interface...
│   ├── path_provider_windows 2.1.5
│   │   ├── win32 2.7.0
│   │   │   └── ffi...
│   │   ├── ffi...
│   │   ├── flutter...
│   │   ├── path...
│   │   └── path_provider_platform_interface...
│   └── flutter...
├── percent_indicator 4.2.3
│   └── flutter...
├── permission_handler 10.2.0
│   ├── permission_handler_android 10.2.0
│   │   ├── flutter...
│   │   └── permission_handler_platform_interface...
│   ├── permission_handler_apple 9.0.8
│   │   ├── flutter...
│   │   └── permission_handler_platform_interface...
│   ├── permission_handler_platform_interface 3.9.0
│   │   ├── flutter...
│   │   ├── meta...
│   │   └── plugin_platform_interface...
│   ├── permission_handler_windows 0.1.2
│   │   ├── flutter...
│   │   └── permission_handler_platform_interface...
│   ├── flutter...
│   └── meta...
├── pull_to_refresh 2.0.0
│   └── flutter...
├── record 4.4.4
│   ├── record_linux 0.4.1
│   │   ├── flutter...
│   │   ├── path...
│   │   └── record_platform_interface...
│   ├── record_macos 0.2.2
│   │   ├── flutter...
│   │   └── record_platform_interface...
│   ├── record_platform_interface 0.5.0
│   │   ├── flutter...
│   │   └── plugin_platform_interface...
│   ├── record_web 0.5.0
│   │   ├── flutter...
│   │   ├── flutter_web_plugins...
│   │   └── record_platform_interface...
│   ├── record_windows 0.7.1
│   │   ├── flutter...
│   │   ├── path...
│   │   └── record_platform_interface...
│   └── flutter...
├── scrollable_positioned_list 0.3.5
│   ├── collection...
│   └── flutter...
├── share_plus 5.0.0
│   ├── cross_file 0.3.3+4
│   │   ├── js...
│   │   └── meta...
│   ├── mime 1.0.4
│   ├── share_plus_linux 3.0.1
│   │   ├── cross_file...
│   │   ├── file...
│   │   ├── flutter...
│   │   ├── meta...
│   │   ├── share_plus_platform_interface...
│   │   └── url_launcher...
│   ├── share_plus_macos 3.0.1
│   │   ├── flutter...
│   │   └── share_plus_platform_interface...
│   ├── share_plus_platform_interface 3.2.0
│   │   ├── cross_file...
│   │   ├── flutter...
│   │   ├── meta...
│   │   ├── mime...
│   │   ├── path_provider...
│   │   ├── plugin_platform_interface...
│   │   └── uuid...
│   ├── share_plus_web 3.1.0
│   │   ├── cross_file...
│   │   ├── flutter...
│   │   ├── flutter_web_plugins...
│   │   ├── meta...
│   │   ├── mime...
│   │   ├── share_plus_platform_interface...
│   │   └── url_launcher...
│   ├── share_plus_windows 4.0.0
│   │   ├── cross_file...
│   │   ├── ffi...
│   │   ├── flutter...
│   │   ├── meta...
│   │   ├── share_plus_platform_interface...
│   │   ├── url_launcher...
│   │   └── win32...
│   ├── flutter...
│   └── meta...
├── shared_preferences 2.1.0
│   ├── shared_preferences_android 2.1.0
│   │   ├── flutter...
│   │   └── shared_preferences_platform_interface...
│   ├── shared_preferences_foundation 2.2.0
│   │   ├── flutter...
│   │   └── shared_preferences_platform_interface...
│   ├── shared_preferences_linux 2.2.0
│   │   ├── file...
│   │   ├── flutter...
│   │   ├── path...
│   │   ├── path_provider_linux...
│   │   ├── path_provider_platform_interface...
│   │   └── shared_preferences_platform_interface...
│   ├── shared_preferences_platform_interface 2.2.0
│   │   ├── flutter...
│   │   └── plugin_platform_interface...
│   ├── shared_preferences_web 2.1.0
│   │   ├── flutter...
│   │   ├── flutter_web_plugins...
│   │   └── shared_preferences_platform_interface...
│   ├── shared_preferences_windows 2.2.0
│   │   ├── file...
│   │   ├── flutter...
│   │   ├── path...
│   │   ├── path_provider_platform_interface...
│   │   ├── path_provider_windows...
│   │   └── shared_preferences_platform_interface...
│   └── flutter...
├── shimmer 2.0.0
│   └── flutter...
├── sign_in_with_apple 4.3.0
│   ├── sign_in_with_apple_platform_interface 1.0.0
│   │   ├── flutter...
│   │   ├── meta...
│   │   └── plugin_platform_interface...
│   ├── sign_in_with_apple_web 1.0.1
│   │   ├── flutter...
│   │   ├── flutter_web_plugins...
│   │   ├── js...
│   │   └── sign_in_with_apple_platform_interface...
│   ├── flutter...
│   └── meta...
├── sqflite 2.2.6
│   ├── sqflite_common 2.4.3
│   │   ├── synchronized 3.0.1
│   │   ├── meta...
│   │   └── path...
│   ├── flutter...
│   └── path...
├── syncfusion_flutter_sliders 20.4.54
│   ├── syncfusion_flutter_core 20.4.54
│   │   ├── flutter...
│   │   └── vector_math...
│   ├── flutter...
│   └── intl...
├── timer_builder 2.0.0
│   └── flutter...
├── url_launcher 6.1.10
│   ├── url_launcher_android 6.0.26
│   │   ├── flutter...
│   │   └── url_launcher_platform_interface...
│   ├── url_launcher_ios 6.1.3
│   │   ├── flutter...
│   │   └── url_launcher_platform_interface...
│   ├── url_launcher_linux 3.0.4
│   │   ├── flutter...
│   │   └── url_launcher_platform_interface...
│   ├── url_launcher_macos 3.0.4
│   │   ├── flutter...
│   │   └── url_launcher_platform_interface...
│   ├── url_launcher_platform_interface 2.1.2
│   │   ├── flutter...
│   │   └── plugin_platform_interface...
│   ├── url_launcher_web 2.0.16
│   │   ├── flutter...
│   │   ├── flutter_web_plugins...
│   │   └── url_launcher_platform_interface...
│   ├── url_launcher_windows 3.0.5
│   │   ├── flutter...
│   │   └── url_launcher_platform_interface...
│   └── flutter...
├── video_player 2.6.0
│   ├── video_player_android 2.4.3
│   │   ├── flutter...
│   │   └── video_player_platform_interface...
│   ├── video_player_avfoundation 2.4.2
│   │   ├── flutter...
│   │   └── video_player_platform_interface...
│   ├── video_player_platform_interface 6.1.0
│   │   ├── flutter...
│   │   └── plugin_platform_interface...
│   ├── video_player_web 2.0.15
│   │   ├── flutter...
│   │   ├── flutter_web_plugins...
│   │   └── video_player_platform_interface...
│   ├── flutter...
│   └── html...
└── visibility_detector 0.3.3
    └── flutter...

**Comment by danagbemava-nc** [comment]
Hi @mHassan20896, please provide the full output of `flutter run -v`. The output may be huge so kindly put it into a .log file an attach it here. 

Please also share your Podfile & Podfile.lock

Thank you

**Comment by mHassan20896** [comment]
[Podfile_lock.log](https://github.com/firebase/flutterfire/files/11397980/Podfile_lock.log)
[Podfile.log](https://github.com/firebase/flutterfire/files/11397981/Podfile.log)

**Comment by danagbemava-nc** [comment]
Hi @mHassan20896, I'm curious, why do you have `pod GoogleSignIn` in your podfile? This should not be necessary since you've already included the `google_sign_in` plugin in your `pubspec.yaml`. Can you try removing that pod from the `Podfile` & running `pod cache clean --all` & try running the app again?

It also seems like you've setup flavors in your project? Can you select a flavor when you run the app?

**Comment by mHassan20896** [comment]
[output.log](https://github.com/firebase/flutterfire/files/11455134/output.log)

Here is a log file of a simple flutter project. I ran the project before adding firebase_crashlytics and it ran. As soon as I added firebase_crashlytics, it stopped working.

**Comment by mHassan20896** [comment]
[Podfile_code.log](https://github.com/firebase/flutterfire/files/11455160/Podfile_code.log)
[Podfile.log](https://github.com/firebase/flutterfire/files/11455164/Podfile.log)

**Comment by danagbemava-nc** [comment]
Hi @mHassan20896, one final thing, can you provide a sample repo that contains any code sample you're experiencing this issue with? It could be the new flutter app that you created.

**Comment by mHassan20896** [comment]
https://github.com/mHassan20896/hello

Here is the repo that's generating the error. It was working before added firebase_crashlytics to pubspec.yaml, once added it stopped building on iOS

**Comment by mHassan20896** [comment]
Is there any update?
