### ISSUE TITLE
🐛 [firebase_auth] FLUTTER: Sign in with credential throws to An unknown error has occurred.

### ISSUE THREAD

**Issue by swiftyui** [firebase/flutterfire#10865]
## Bug report

When trying to use FirebaseAuth.instance.signInWithCredential an unknown error is thrown 
FLTFirebaseAuth: An error occurred while calling method Auth#signInWithCredential, errorOrNil => (null)
[firebase_auth/unknown] An unknown error has occurred.

When calling the following code:

        OAuthProvider oAuthProvider = OAuthProvider('microsoft.com');

        final AuthCredential credential = oAuthProvider.credential(
          accessToken: accessToken,
        );

        UserCredential result;

        result = await _auth.signInWithCredential(credential);

Within Firebase console the following sign in methods are allowed:

![image](https://user-images.githubusercontent.com/32429591/235120922-1d2bd568-a705-4a81-a5e9-11db2690e30d.png)

Within the project we use https://pub.dev/packages/aad_oauth to acquire an access token from Microsoft, the login here works perfectly, however when trying to use the access token and Firebase Auth an error occurs.

It should be noted, if we use the Firebase Emulators, the user is signed in perfectly:

![image](https://user-images.githubusercontent.com/32429591/235121462-080120f1-69b6-4b23-ba19-433bb90e9e44.png)

Within Azure the redirect uri is also set:
![image](https://user-images.githubusercontent.com/32429591/235121885-7374763c-1cda-4d6d-b1ef-34f01d7f60dc.png)

The tenant ID of the Azure instance is added as the Application ID and the Application Secret is added correctly.

To get the create the OAuth instance for Microsoft we call:
```
  static final Config config = new Config(
    tenant: "YOUR_TENANT_ID",
    clientId: "YOUR_CLIENT_ID",
    scope: "openid profile offline_access",
    // redirectUri is Optional as a default is calculated based on app type/web location
    redirectUri: "your redirect url available in azure portal",
    navigatorKey: navigatorKey,
    webUseRedirect: true, // default is false - on web only, forces a redirect flow instead of popup auth
    //Optional parameter: Centered CircularProgressIndicator while rendering web page in WebView
    loader: Center(child: CircularProgressIndicator()),
    postLogoutRedirectUri: 'http://your_base_url/logout', //optional
  );

  final AadOAuth oauth = new AadOAuth(config);
```
And to get the required access token:
```
final result = await oauth.login();
result.fold(
  (failure) => showError(failure.toString()),
  (token) => showMessage('Logged in successfully, your access token: $token'),
);
String accessToken = await oauth.getAccessToken();
```

This all works fine, but using this access token in a user credential, and calling the signInWithCredential does not work.

**Comment by darshankawar** [comment]
Thanks for the report @swiftyui 
Can you provide the complete error log here ?
Also, please check [this](https://github.com/firebase/flutterfire/issues/7453) issue and underlying comment and see if they help you in your case.

**Comment by swiftyui** [comment]
Hi @darshankawar, thank you so much for the quick reply, I'm scratching my brain at this....

This is the full terminal printout of the error:
```
FLTFirebaseAuth: An error occurred while calling method Auth#signInWithCredential, errorOrNil => (null)
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: [firebase_auth/unknown] An unknown error has occurred.
#0      StandardMethodCodec.decodeEnvelope
message_codecs.dart:653
#1      MethodChannel._invokeMethod
platform_channel.dart:315
<asynchronous suspension>
#2      MethodChannel.invokeMapMethod
platform_channel.dart:518
<asynchronous suspension>
#3      MethodChannelFirebaseAuth.signInWithCredential
method_channel_firebase_auth.dart:459
<asynchronous suspension>
```

**Comment by swiftyui** [comment]
@darshankawar this might be barking up the wrong tree, but when I look at the invokeMethod and the associated method and arguments (platform_channel.dart) I get:
**Method:** Auth#signInWithCredential
**Arguments**
`{appName: [DEFAULT], tenantId: null, credential: {providerId: microsoft.com, signInMethod: oauth, idToken: null, accessToken: accessTokenHere<…>`

The channel is plugins.flutter.io/firebase_auth.

I hope this info helps!

**Comment by darshankawar** [comment]
Thanks for the update and feedback. Keeping this issue open for team's input on current behavior as mentioned in the original post: https://github.com/firebase/flutterfire/issues/10865#issue-1688291491

/cc @Lyokone

**Comment by swiftyui** [comment]
Hi @Lyokone @darshankawar 😁

I just wanted to follow up on this, is someone having a look at this?

**Comment by swiftyui** [comment]
Hi @Lyokone @darshankawar  has there been an update on this?

**Comment by Shilpa26v** [comment]
@swiftyui 
Any update for this 
i am getting same error for FirebaseAuth.instance.signInWithCredential method

**Comment by swiftyui** [comment]
@Shilpa26v no update so far, I've also been waiting for a response

**Comment by devsideal** [comment]
@darshankawar  This way working for me in Android but in iOS it's crashing the app:
https://stackoverflow.com/a/76629310/1427776

Do I need any configuration for ios?

**Comment by Lyokone** [comment]
Closing since it's was fixed with: https://github.com/firebase/flutterfire/pull/12920
