### ISSUE TITLE
🐛 firebase_messaging  Flutter app crashes on Android when receiving push notifications

### ISSUE THREAD

**Issue by gowthaman13** [firebase/flutterfire#10864]
My Flutter app is crashing on Android devices when it receives a push notification. The error message I receive is:
```
D/FLTFireMsgReceiver(11789): broadcast received for message
I/flutter (11789): onMessage: Instance of 'RemoteMessage'
W/m.starfish.ryb(11789): Accessing hidden method Landroid/os/WorkSource;->add(I)Z (greylist, reflection, allowed)
W/m.starfish.ryb(11789): Accessing hidden method Landroid/os/WorkSource;->add(ILjava/lang/String;)Z (greylist, reflection, allowed)
W/m.starfish.ryb(11789): Accessing hidden method Landroid/os/WorkSource;->size()I (greylist, reflection, allowed)
W/m.starfish.ryb(11789): Accessing hidden method Landroid/os/WorkSource;->get(I)I (greylist, reflection, allowed)
W/m.starfish.ryb(11789): Accessing hidden method Landroid/os/WorkSource;->getName(I)Ljava/lang/String; (greylist, reflection, allowed)
W/m.starfish.ryb(11789): Accessing hidden method Landroid/os/WorkSource;->isEmpty()Z (greylist-max-o, reflection, denied)
W/FirebaseMessaging(11789): Notification Channel set in AndroidManifest.xml has not been created by the app. Default value will be used.
I/m.starfish.ryb(11789): Thread[3,tid=11804,WaitingInMainSignalCatcherLoop,Thread*=0x79d2e29c00,peer=0x13f021f8,"Signal Catcher"]: reacting to signal 3
I/m.starfish.ryb(11789):
I/m.starfish.ryb(11789): Wrote stack traces to tombstoned
```
I have already tried the following steps to resolve the issue:
```
1. Ensured proper setup of push notifications in the Flutter app using `firebase_messaging`.
2. Checked the AndroidManifest.xml file for necessary permissions and service declarations related to push notifications.
3. Initialized the Firebase Messaging instance in the `main.dart` file and implemented necessary event listeners (onMessage, onResume, and onLaunch).
4. Inspected the Android native code to ensure proper handling of push notifications.
5. Examined the dependencies in the `pubspec.yaml` file to make sure they are up-to-date and compatible.
```
![Capture](https://user-images.githubusercontent.com/30084475/235061037-e2863967-4d21-42b9-87a2-84be92757987.PNG)
![Capture2](https://user-images.githubusercontent.com/30084475/235061129-da4a3860-c1d4-4605-bf85-551d9cdca240.PNG)
![Capture3](https://user-images.githubusercontent.com/30084475/235061165-ed0dd8c1-10ca-4e0c-b9b9-209bab753256.PNG)
![Capture5](https://user-images.githubusercontent.com/30084475/235061224-eb370874-67af-4d5a-b504-7ee95025dfea.PNG)
![Capture4](https://user-images.githubusercontent.com/30084475/235061754-73c5230f-ba3c-4431-93da-166f4d3ab9ff.PNG)

This is output of flutter run -v
[run.txt](https://github.com/firebase/flutterfire/files/11350230/run.txt)

Despite trying these steps, the issue persists. I would appreciate any guidance on how to resolve this problem. Please let me know if you need more information or code snippets to help diagnose the issue.

**Comment by darshankawar** [comment]
@gowthaman13 
Can you provide the Android device details on which the crash occurs ? Are you by any chance using mi / redmi /Xiaomi device running MIUI OS ?
Does it replicate on any other physical device or only on the one you are using ?
Also, please don't provide screenshots of the code, post them in properly formatted text so that we can use it to verify properly as required.
