### ISSUE TITLE
🐛 [cloud_firestore] Retrieving a document that doesn't exist while offline permanently throws an exception (and breaks apps)

### ISSUE THREAD

**Issue by stx** [firebase/flutterfire#10887]
## Bug report

When attempting to get a document that doesn't exist while offline, the error below will be permanently thrown even though the cache is populated correctly, and even after returning online:

```[cloud_firestore/unavailable] The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff.```

This issue has been ongoing for years in a discussion @ https://github.com/firebase/flutterfire/discussions/5708 but has not been fully identified or understood until now. Thanks to @cammoore54 [here](https://github.com/firebase/flutterfire/discussions/5708#discussioncomment-5162613) we now have reproduction steps.

We can also confirm that this is a critical app breaking issue. In our commercial app, with over a thousand instances recorded across many cloud_firestore and Flutter versions, and it prevents users from loading data.

This causes apps to break since if a user tries to log in or do anything with a new document while offline, they will receive `cloud_firestore/unavailable`, but will still receive it when going back online until the app is killed or uninstalled and reinstalled.

### Steps to reproduce

Credit to @cammoore54:

The below DOESN'T raise the error:

```
var collectionRef = FirebaseFirestore.instance.collection('tags');
var tags = await collectionRef.get(GetOptions(source: source)));
```

The below DOES raise the error (only when offline):

```
var collectionRef = FirebaseFirestore.instance.collection('tags');
var doc = await collectionRef.doc(id).get(GetOptions(source: source)); //where id doesn't exist for this collection
```

For both of the above I have confirmed that the correct data is stored in the cache when offline.

Making this call online first, then going offline doesn't cause the error but if the device is offline the first time the call is made raises the error.

### Expected behavior

No error should be thrown since the cache is populated and working in offline mode.

**Comment by darshankawar** [comment]
Thanks for the report. Using the code sample provided and trying to run in offline mode gave me the same reported error:

`[cloud_firestore/unavailable] The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff.`

More reference on the issue: https://github.com/firebase/flutterfire/discussions/5708

**Comment by Chuckame** [comment]
No need to go offline, just do a `get(GetOptions(source: Source.cache))` and then the same error comes.

**Comment by Mijawel** [comment]
Facing a similar error but slightly different message.

```
[cloud_firestore/unavailable] Failed to get documents from server. (However, these documents mi exist in the local cache. Run again without setting source to "server" to retrieve the cached documents.)
```

**Comment by russellwheatley** [comment]
Could you specify what platform(s) this is occurring on?

**Comment by Mijawel** [comment]
Web

**Comment by stx** [comment]
@russellwheatley Did you try without specifying cache? In our app and in other repros that isn't being specified.

**Comment by russellwheatley** [comment]
I didn't because in your initial post you specified with `source` as a way to reproduce. Please provide an exact code sample for me to drop into the Firestore example and let me know what platforms this occurring on for you.
