### ISSUE TITLE
[firebase_crashlytics] Expected encodable string, but found NSNull instead. crashes not showing in iOS

### ISSUE THREAD

**Issue by DukeJeon** [firebase/flutterfire#10888]
errorMessage
`Expected encodable string, but found NSNull instead.`

Android is good, but iOS Crashlytics not showing in 2.9.0

i added `"${PODS_ROOT}/FirebaseCrashlytics/run"` this script is in the end of Build Phases.
and run Release mode

How to fixed this issue?

testCode

`   WidgetsFlutterBinding.ensureInitialized();

    await Firebase.initializeApp();
    await FirebaseCrashlytics.instance.setCrashlyticsCollectionEnabled(true);
    FlutterError.onError = _onError;

    try {
      throw Exception("Crash test");
    } catch (error, stack) {
      FirebaseCrashlytics.instance.recordError(
        error,
        stack,
        reason: "Test",
        fatal: true
      );
    }`
    
    
result

flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: The following exception was thrown Test:
flutter: error

**Comment by 217wjs** [comment]
10.7.0 - [FirebaseCrashlytics][I-CLS000000] Expected encodable string, but found NSNull instead. Set a symbolic breakpoint at FIRCLSEncodeString to debug.

[✓] Flutter (Channel stable, 3.3.10, on macOS 13.3.1 22E772610a darwin-x64, locale ko-KR)
    • Flutter version 3.3.10 on channel stable at /Users/duke/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (5 months ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/duke/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (3 available)
    • iPhone (mobile) • 00008030-000964380A92802E • ios            • iOS 16.3.1 20D67
    • macOS (desktop) • macos                     • darwin-x64     • macOS 13.3.1 22E772610a darwin-x64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by DukeJeon** [comment]
I'm still got this Error when app starts in iOS Real Device (IPhone 11 pro)

`
10.7.0 - [FirebaseCrashlytics][I-CLS000000] Expected encodable string, but found NSNull instead. Set a symbolic breakpoint at FIRCLSEncodeString to debug.`

**TestCode**

`    await FirebaseCrashlytics.instance.recordError(
      "Record error to Crashlytics",
      StackTrace.fromString("No StackTrace."),
      reason: "Init Crashlytics !",
    );`

**Comment by DukeJeon** [comment]
@darshankawar 
I'm still got this Error when app starts in iOS Real Device (IPhone 11 pro)

`
10.7.0 - [FirebaseCrashlytics][I-CLS000000] Expected encodable string, but found NSNull instead. Set a symbolic breakpoint at FIRCLSEncodeString to debug.`

**TestCode**

`    await FirebaseCrashlytics.instance.recordError(
      "Record error to Crashlytics",
      StackTrace.fromString("No StackTrace."),
      reason: "Init Crashlytics !",
    );`

**Comment by DukeJeon** [comment]
okay
I solved this problem.
