### ISSUE TITLE
SendPasswordResetEmail argument type String? can't be assigned to the parameter type String for Firebase String? get email

### ISSUE THREAD

**Issue by scrabbleknight** [firebase/flutterfire#10906]
## Bug report

The method SendPasswordResetEmail takes in a non-nullable string, but the Firebase email is a nullable string. Cannot enter the nullable string FirebaseAuth.instance.currentUser!.email to the method as it only takes a non-nullable as an input. To get around this, I used "${FirebaseAuth.instance.currentUser!.email}", but this shouldn't be needed.

My recommendation would be to make the input method's string nullable in firebase_auth.dart from this:

Future<void> sendPasswordResetEmail({
    required String email,
    ActionCodeSettings? actionCodeSettings,
  }) {
    return _delegate.sendPasswordResetEmail(email, actionCodeSettings);
  }

to this:

Future<void> sendPasswordResetEmail({
    required String? email,
    ActionCodeSettings? actionCodeSettings,
  }) {
    return _delegate.sendPasswordResetEmail(email, actionCodeSettings);
  }
---

**Comment by danagbemava-nc** [comment]
The native sdk methods that are called do not take nullable strings so the delegate cannot do that either. 

You should check if the email is not null before sending a password reset email. See the references from the native sdks below.

You cannot send a reset email to a null email address. 

https://firebase.google.com/docs/reference/ios/firebaseauth/api/reference/Classes/FIRAuth#-sendpasswordresetwithemail:completion:
https://firebase.google.com/docs/reference/kotlin/com/google/firebase/auth/FirebaseAuth.html#sendpasswordresetemail_1

Closing as this is working as designed.
