### ISSUE TITLE
Firebase Auth Handle isnt working

### ISSUE THREAD

**Issue by arslanrazacrew** [firebase/flutterfire#10902]
Hello!
I'm trying to log in with Twitter and give all the required details to Firebase Console to the active Twitter Provider. I'm using the **twitter_login** package. this requires redirectURI to return back accessToken. and I got redirectURI from Firebase Console that is 
https://myapp.firebaseapp.com/__/auth/handler.
This auth handler is not working and giving me an error that is 

**Unable to process the request due to missing initial state. This may happen if browser sessionStorage is inaccessible or accidentally cleared.**

**Comment by danagbemava-nc** [comment]
Hi @arslanrazacrew, can you take a look at this [thread](https://github.com/firebase/firebase-js-sdk/issues/4256) and this [comment](https://github.com/firebase/firebase-js-sdk/issues/4256#issuecomment-1495054934) to see if you get a solution?

**Comment by arslanrazacrew** [comment]
Hi!
Yes i have checked with this but still not working

**Comment by danagbemava-nc** [comment]
Hi @arslanrazacrew, are you using any flutterfire plugins? If so, what are their versions?

Can you also provide a minimal complete reproducible code sample so that we can investigate this?

**Comment by arslanrazacrew** [comment]
Yes, I'm using  twitter_login: ^4.3.2 to login with twitter. 


   final twitterLogin = TwitterLoginV2(
        clientId: "Consumer API keys",
        redirectURI: "https://nebulum--.firebaseapp.com/__/auth/handler", /// Registered Callback URLs in TwitterApp
        scopes: ["tweet.read","follows.read", "users.read"]
    );
 final authResult = await twitterLogin.loginV2();

**Comment by danagbemava-nc** [comment]
That is unrelated to this repo

**Comment by arslanrazacrew** [comment]
Thanks for your help!
