### ISSUE TITLE
Firestore's get(/databases/) call on a sub-collection #firestore assignee: MilaGGL

### ISSUE THREAD

**Issue by mathems-m** [firebase/flutterfire#10926]
[testdevelop_security_rules.txt](https://github.com/firebase/flutterfire/files/11425041/testdevelop_security_rules.txt)
Hi @MilaGGL

I am finding an unusual result when calling Firestore's get(/databases/) function for data that is two sub-collections deep.  For some reason, the data that is meant to be read isn't allowed, with Firestore confirming that the caller does not have permission to perform the operation.

To replicate the situation, please arrange Firestore collections with the following arrangement:

                                                                             /users/

                              /userA/                                                                                            /userB/

/signInData/   /otherDetails/   /exclusiveA/                                 /signInData/   /otherDetails/   /exclusiveB/  

Please note: collections 'users', 'userA' and 'userB' are empty.

The contents of collections 'signInData', 'otherDetails', 'exclusiveA' and 'exclusiveB' are confirmed in the attached images, and, the 'userA' collection does not have any user-data but collection 'userB' does.

So, the get(/databases/) call is meant to permit the reading of documents in collection 'exclusiveA' if the boolean field-value of 'creditCard' in collection 'exclusiveB' is set to false.  This is where the failure is occurring.

The code querying my security rules is within file: stream_results.txt

The security that have been set are within file: testdevelop_security_rules.txt

Please share your feedback on this situation and whether there is a way that this problem can be worked around.  The main thing is the conditional reading of collection 'exclusiveA'.

Thank you for your time and for your assistance.

The Flutter code querying my Firestore security rules is:
<img width="1258" alt="Screenshot 2023-05-08 at 10 27 15" src="https://user-images.githubusercontent.com/106067897/236906153-e238242e-0be3-4c78-a2de-f8b39e4e869d.png">
<img width="1258" alt="Screenshot 2023-05-08 at 10 27 34" src="https://user-images.githubusercontent.com/106067897/236906164-036b5342-d655-4ff1-9e7b-d9865539137d.png">
<img width="1258" alt="Screenshot 2023-05-08 at 10 28 11" src="https://user-images.githubusercontent.com/106067897/236906173-1fb672ff-57af-40b3-8cae-44727bf1bd99.png">
<img width="1258" alt="Screenshot 2023-05-08 at 10 29 02" src="https://user-images.githubusercontent.com/106067897/236906181-6b32de4a-2e2c-4ab5-86d2-132687c2b8b2.png">
[testdevelop_security_rules.txt](https://github.com/firebase/flutterfire/files/11424215/testdevelop_security_rules.txt)
[stream_results.txt](https://github.com/firebase/flutterfire/files/11424218/stream_results.txt)

**Comment by darshankawar** [comment]
@mathems-m 
Can you provide `flutter doctor -v`, any logs that are generated including the permission error you mentioned ?

**Comment by mathems-m** [comment]
Hi

Thank you for your response.

The flutter doctor -v response is:

***@***.*** developer_testing % flutter doctor -v
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.3.1 21E258 darwin-x64,
locale en-GB)
    • Flutter version 3.0.5 at /Users/m.mathems/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (10 months ago), 2022-07-13 11:24:16
-0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version
33.0.0)
    • Android SDK at /Users/m.mathems/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/m.mathems/Library/Android/sdk/
    • Java binary at: /Users/m.mathems/Library/Application
Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683/Android
Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/m.mathems/Library/Application
Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683/Android
Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2 EAP)
    • IntelliJ at /Users/m.mathems/Applications/JetBrains Toolbox/IntelliJ
IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version EAP IU-222.3153.4)
    • IntelliJ at /Users/m.mathems/Library/Application
Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.3153.4/IntelliJ IDEA 2022.2
EAP.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.3)
    • IntelliJ at /Users/m.mathems/Library/Application
Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/221.5921.17/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (7 available)
    • sdk gphone64 x86 64 (mobile)        • emulator-5554
      • android-x64    • Android 12 (API 32) (emulator)
    • iPhone 12 Pro Max (mobile)          •
4BB077E1-56E6-468B-A35A-A8F533ACD849 • ios            •
com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • iPhone SE (3rd generation) (mobile) •
E0095356-C638-46CD-9601-C43A14EE4641 • ios            •
com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • iPad Pro (10.5-inch) (mobile)       •
67B76729-B225-4F02-86EE-380A7F0724FC • ios            •
com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • iPad mini (5th generation) (mobile) •
2975B3C2-C864-481A-8BBC-6C4B9752441F • ios            •
com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)                     • macos
      • darwin-x64     • macOS 12.3.1 21E258 darwin-x64
    • Chrome (web)                        • chrome
     • web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!


The error message when I am using the iOS emulator is: flutter:
[cloud_firestore/permission-denied]
The caller does not have permission to execute the specified operation.

The error message when I am using the Android emulator is:  W/Firestore(24205):
(24.4.3) [Firestore]: Listen for
Query(target=Query(users/l9NzQFjN4iB0JlJaY3AI/userA/2VzSHur3RllcF5PojT61/exclusiveA
order by *name*);limitType=LIMIT_TO_FIRST) failed:
Status{code=PERMISSION_DENIED, description=Missing or insufficient
permissions., cause=null} D/EGL_emulation(24205): app_time_stats:
avg=15753.46ms min=383.96ms max=31122.96ms count=2

**Comment by mathems-m** [comment]
The flutter doctor -v response is:

m.mathems@Ms-MacBook-Pro developer_testing % flutter doctor -v
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.3.1 21E258 darwin-x64, locale en-GB)
    • Flutter version 3.0.5 at /Users/m.mathems/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (10 months ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/m.mathems/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/m.mathems/Library/Android/sdk/
    • Java binary at: /Users/m.mathems/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/m.mathems/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2 EAP)
    • IntelliJ at /Users/m.mathems/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version EAP IU-222.3153.4)
    • IntelliJ at /Users/m.mathems/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.3153.4/IntelliJ IDEA 2022.2 EAP.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.3)
    • IntelliJ at /Users/m.mathems/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/221.5921.17/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (7 available)
    • sdk gphone64 x86 64 (mobile)        • emulator-5554                        • android-x64    • Android 12 (API 32) (emulator)
    • iPhone 12 Pro Max (mobile)          • 4BB077E1-56E6-468B-A35A-A8F533ACD849 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • iPhone SE (3rd generation) (mobile) • E0095356-C638-46CD-9601-C43A14EE4641 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • iPad Pro (10.5-inch) (mobile)       • 67B76729-B225-4F02-86EE-380A7F0724FC • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • iPad mini (5th generation) (mobile) • 2975B3C2-C864-481A-8BBC-6C4B9752441F • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)                     • macos                                • darwin-x64     • macOS 12.3.1 21E258 darwin-x64
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!


The error message when I am using the iOS emulator is: flutter: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.

The error message when I am using the Android emulator is:  W/Firestore(24205): (24.4.3) [Firestore]: Listen for Query(target=Query(users/l9NzQFjN4iB0JlJaY3AI/userA/2VzSHur3RllcF5PojT61/exclusiveA order by name);limitType=LIMIT_TO_FIRST) failed: Status{code=PERMISSION_DENIED, description=Missing or insufficient permissions., cause=null} D/EGL_emulation(24205): app_time_stats: avg=15753.46ms min=383.96ms max=31122.96ms count=2

**Comment by darshankawar** [comment]
Thanks for the update and feedback. I am going ahead and keeping this issue open for team's input on reported behavior.

**Comment by mathems-m** [comment]
Hi Darshan

Thank you for your response and for handling my enquiry.

Could you tell me about what you have found/noticed so far please?

With regards to what I am trying to achieve (pending data in an external
collection), is there an explanation for why it is not working?

With regards to what I am trying to achieve (pending data in an external
collection), is there an alternative way of achieving the same goal please?

And lastly, with this get(/databases/) call being problematic and causing
delay to progress, would Firebase invent other ways (new ways) for
customers to achieve the same outcome (as it is in Flutter), so that if one
technique isn't working then another technique can be tried instead, so
that it will not matter so much if customers cannot get the
get(/databases/) function call to work?

Many thanks for your time and for your patience and for your assistance.

Kind regards

M Mathems

**Comment by mathems-m** [comment]
Hi Darshan

I am still looking into this, but I think I have found two alternative
explanations for why I have been receiving the permission-denied message
from Firestore.

I hope to know more with a little more testing, but I will e-mail what I
find if it sheds light.

With thanks.

Kind regards

M Mathems

**Comment by russellwheatley** [comment]
> Hi
> 
> Thank you for getting back to me. I have provided a detailed response to your enquiry.
> 
> Based on the error messages received thru Flutter, the source of the problem is the current version of Firestore, so that this situation should be possible to replicate where an application relies on Firestore.
> 
> As you are aware, I have completed my testing using Flutter and smartphone emulators, and the results have been the same for both emulators, however, for some reason, the iOS emulator responds to Firestore's security rules, so that a denial by Firestore prevents the read from occurring on the iOS emulator, whereas the Android emulator does not respond to Firestore's security rules, and grants the read, but later discovers the Firestore rule which creates the denial, and then confirms that the relevant permission has been denied.
> 
> The Android emulator's exact error feedback is, "W/veloper_testin( 987): Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (unsupported, reflection, allowed) W/veloper_testin( 987): Accessing hidden method Ljava/security/spec/ECParameterSpec;->setCurveName(Ljava/lang/String;)V (unsupported, reflection, allowed) W/Firestore( 987): (24.4.3) [Firestore]: Listen for Query(target=Query(users/l9NzQFjN4iB0JlJaY3AI/userA/2VzSHur3RllcF5PojT61/exclusiveA order by **name**);limitType=LIMIT_TO_FIRST) failed: Status{code=PERMISSION_DENIED, description=Missing or insufficient permissions., cause=null}"
> 
> And the iOS emulator's exact feedback is, "flutter: Login successful. flutter: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation."
> 
> I believe that the situation I have presented can be replicated perfectly by recreating the Firestore collection-formation illustrated in my primary text, and with reliance on the files attached here.
> 
> Please note: the 'exclusiveA' sub-collection contains the documents relevant to the get(/databases/) call at the heart of this enquiry.
> 
> **The Attached Files**
> 
> My written Firestore security rules My main.dart file My UI's login screen My UI's stream query My flutter -v response (confirms SDK version, Language Platform + Development Environment) Screenshots (confirms Firestore collection-formation + field-value titles for documents)
> 
> A link to the attached files is [here](https://drive.google.com/drive/folders/1RWsP0QIrZFzK_ILtGvKOErZi1-AAv1Dc?usp=share_link). [Please confirm when you finish with these files so that I can hide them from the public]
> 
> This Firestore project features the following field-values holding the following types of data:
> 
> docRefID - string horsePower - number preferredCurrency - string topSpeed - number vehicleBrand - string vehicleName - string eAddress - string eName2 - string id - string sex - string eID - string eName1 - string loginEmail - string amount - number creditCard - boolean currency - string uid - string wantsVehicle - boolean
> 
> **Further Background**
> 
> I believe that the above answers your requests for further information.
> 
> For further clarity of the situation, I was trying to find the way to offer access to the collection on the basis of a field in another collection, so that in a real application, a user could be 'subscribed' or 'admin' or some other important status and have access granted/denied on that basis.
> 
> My original enquiry was to code so that only the documents in exclusiveA holding a particular string could be read, but it was later explained to me that Firestore would deny access entirely if a user would not be permitted to read every document within the collection where a rule grants permission to read. Hearing this, I thought that that was the cause of the permission-denied message I was noticing, so then I changed things so that a rule to read would be so that every document within the collection could be read by the user, and then I found that the same error message was still being received. What I learnt around that time, was that a query featuring 'where' for filtering, should be drafted at the UI code instead of at Firestore.
> 
> Lastly, I found a similar case example in the Firestore forum that was responded to by Todd Kerpelman, where he explained that Firestore tends not to accept a get(/databases/) call unless it has an example/instance of the relevant data first. This might help. You can notice the case [here](https://groups.google.com/g/google-cloud-firestore-discuss/c/6tPpMTuTsik).
> 
> I believe you now have all of the information that you require and I hope that there is some mistake on my part that has caused this error to arise, so that with some embarrassment I can remember and learn from this. Please confirm what you find, and any other advice for guidance would also be greatly appreciated.
> 
> In the case that you can find no solution here, could I request a replicable working example of the get(/databases/) call instead please? I would then assemble the example at a Firestore near me.
> 
> Many thanks for your time and for your assistance.
> 
> Kind regards
> 
> M Mathems

Reading the logs received by both iOS and android, it appears permission is being denied on both platforms. It would be ideal if you gave concrete steps on a reproduction (i.e. no screenshots, just code to run including data to fill the firestore database). that way we can quickly reproduce your issue. I would also add that FlutterFire is a thin wrapper around the native SDKs, any discrepancy with the rules is highly likely to be an issue with the native SDK, not FlutterFire.
