### ISSUE TITLE
[firebase_auth] [firebase_dynamic_links] Handling Firebase Auth generated dynamic links in app

### ISSUE THREAD

**Issue by pyciko** [firebase/flutterfire#10922]
I'm developing an email link login flow and there's a thing that I don't understand about Dynamic Links.
Docs say I should add Dynamic Links in-app handling via AppLinks on Android and Universal Links on iOS. But here's the thing:

When I send a login-by-link email, it has a link that is

> https://go.MYDOMAIN.com/?link=https://APPNAME.firebaseapp.com/__/auth/action?apiKey%3DKEY%26mode%3DsignIn%26oobCode%3CODE%26continueUrl%3Dhttps://MYDOMAIN.com/auth/finishLink%26lang%3Duk&apn=PACKAGENAME&amv

Then in browser, it redirects to 

> https://APPNAME.firebaseapp.com/__/auth/action?apiKey=KEY&mode=signIn&oobCode=CODE&continueUrl=https://MYDOMAIN.com/auth/finishLink&lang=uk

And then this page finally redirects to 

> https://MYDOMAIN.com/auth/finishLink?apiKey=KEY&oobCode=CODE&mode=signIn&lang=uk

The last domain is the link I can perfectly handle: it opens in app, goes to /auth/finishLink page, then the app reads oobCode parameter and signs the user in. 

But if I add go.MYDOMAIN.com (Dynamic Link) to the links handled by the app, it breaks everything because it simply does not know how to handle this. And it makes sense because in browser it does a double redirect to the continue url I set, but the app itself doesn't have any logic to do such redirects. Moreover, if we just look at the link itself, " https://go.MYDOMAIN.com**/?link=**https://AP....." we see that it's just a plain root page ("/") with a "link" parameter which I never wrote a code to handle.

My assumption is that I don't actually need to handle such Dynamic Links in app, I need to allow all the redirects to work on all redirects in browser and only jump to the app after the last redirect. But then, if I need to handle other user-generated links in app, that means I can't just avoid adding Dynamic Links in-app handling at all. Then how do I separate Firebase Auth dynamic links from other types of links to make other links open in app while allowing links from Auth to be processed in browser? Make a special dynamic link prefix for auth and a separate one for everything else?

**Comment by russellwheatley** [comment]
Hi folks, we'd like to inform you that the Firebase Dynamic Links service will be shutdown on August 25, 2025. In the meantime, only critical or security issues will be fixed in the SDK.

More at [firebase.google.com/support/dynamic-links-faq](https://firebase.google.com/support/dynamic-links-faq)
