### ISSUE TITLE
[firebase_messaging]: FCM push notification not working when app is closed and user on another apps

### ISSUE THREAD

**Issue by himanshupapreja** [firebase/flutterfire#10929]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you aware of the differences between iOS and Android background message handling?

- [X] I understand that iOS and Android background messages behave differently, and I've designed my application with that in mind.

### Do you have an active Apple Developer account?

- [x] I have an active Apple Developer account.

### Are you using a physical iOS device to test background messages?

- [X] I am using a physical iOS device to test background messages.

### Have you enabled "Remote Notifications" & "Background Mode" (Checking options for "Background Processing" & "Remote Notifications") in your app's Xcode project?

![image](https://github.com/firebase/flutterfire/assets/52091189/aa4070d4-ba81-4fa2-857f-545e4bf59767)

### Have you created an APNs key in your Apple Developer account & uploaded this APNs key to your Firebase console?

![image](https://github.com/firebase/flutterfire/assets/52091189/a3113d17-851b-4b68-8d64-d8bf32bd9cbd)

### Have you disabled method swizzling for Firebase in your app?

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CADisableMinimumFrameDurationOnPhone</key>
	<true/>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleDisplayName</key>
	<string>Alecom Panic</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>alecom_panic</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
	<key>FirebaseAppDelegateProxyEnabled</key>
	<true/>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>UIApplicationSupportsIndirectInputEvents</key>
	<true/>
	<key>UIBackgroundModes</key>
	<array>
		<string>fetch</string>
		<string>remote-notification</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
</dict>
</plist>

### Are you sending messages to your app from the Firebase Admin SDK?

var message = new MulticastMessage()
            {
                Tokens = registrationTokens,
                Data = new Dictionary<string, string>()
                {
                    { "body", signalRjsonPayload.body },
                    { "title", signalRjsonPayload.title },
                    { "sound", "default" },
                    { "notification", signalRjsonPayload.notification },
                    { "jsonData", jsonData },
                    { "silent", "true" }
                },
                Android = new AndroidConfig
                {
                    Priority = Priority.High,
                },
                Apns = new ApnsConfig
                {
                    Aps = new Aps
                    {
                        ContentAvailable = true,
                        Sound = signalRjsonPayload.notification == NotificationTypes.InsertAlarm.ToString() ? "alert_alarm.aiff" : "alert_bell.aiff"
                    },
                    Headers = new Dictionary<string, string>()
                    {
                        { "apns-push-type", "alert" },
                        { "apns-priority", "5" },
                        { "apns-topic", "com.alecom.alecompanic" }
                    },
                }
            };

            var json = JsonConvert.SerializeObject(message);

            var failedTokens = new List<string>();
            try
            {
                var response = await FirebaseMessaging.DefaultInstance.SendMulticastAsync(message);
                if (response.FailureCount > 0)
                {
                    for (var i = 0; i < response.Responses.Count; i++)
                    {
                        if (!response.Responses[i].IsSuccess)
                        {
                            failedTokens.Add(registrationTokens[i]);
                        }
                    }
                }
            }
            catch (Exception)
            {

            }

### Have you requested permission from the user to receive notifications?

- [X] I have the relevant permission to receive notifications.

### Have you used the 'Console' application on your macOS device to check if the iOS device's system is throttling your background messages?

i don't have

### Additional context and comments

Hi, I had implemented FCM in flutter. In android push notification is working fine in all modes(foreground, background and terminated). And in iOS push notification is working fine in all modes(foreground, background and terminated). but issue is when we are on another app like safari or gmail or any other app then no notification coming in iOS. Please help me out of this kind of issue.

**Comment by darshankawar** [comment]
> but issue is when we are on another app like safari or gmail or any other app then no notification coming in iOS. Please help me out of this kind of issue.

@himanshupapreja This case may not be in control of the plugin. See similar issue raised earlier and team's response on it.

https://github.com/firebase/flutterfire/issues/9536
https://github.com/firebase/flutterfire/issues/9536#issuecomment-1259319290

Also, another similar [issue](https://github.com/firebase/flutterfire/issues/9625) with a [potential solution](https://github.com/firebase/flutterfire/issues/9625#issuecomment-1307095122)

Furthermore, if your app is closed / terminated, you'll manually need to open it in order for push notifications to arrive again, as mentioned in the [documentation](https://firebase.google.com/docs/cloud-messaging/flutter/receive).

```
There are a few preconditions which must be met before the application can receive message payloads via FCM:

The application must have opened at least once (to allow for registration with FCM).
On iOS, if the user swipes away the application from the app switcher, it must be manually reopened for background messages to start working again.
```

Based on above, I am going ahead and closing this as not a plugin issue. If you disagree, write in comments and I'll reopen it.

**Comment by himanshupapreja** [comment]
hey @darshankawar I test it background mode...its working fine if we switches another app but in terminated state its not working

**Comment by Joseph-Nathan** [comment]
i have the same problem .
