### ISSUE TITLE
🐛 AUTH PHONE [SmsRetrieverHelper] Timed out waiting for SMS.

### ISSUE THREAD

**Issue by GrandeSamarone** [firebase/flutterfire#10936]
## Bug report
I'm receiving the code by sms like this in the image, and it's not in the app, I can't validate the code received and at the end it's timed out, what could it be?
AppCheck and Google Play Integrity active in the project,
Is there anything we have to add in the native? am I forgetting something?

![image](https://github.com/firebase/flutterfire/assets/30990831/db291b40-ce15-48fc-a6b7-93dd3cb4ca3e)

### Flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.12, on Microsoft Windows [versÆo 10.0.22621.1555], locale pt-BR)
[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.2)
[√] VS Code (version 1.77.3)
[√] Connected device (4 available)
[√] HTTP Host Availability

### Flutter dependencies

dependencies:
- another_flushbar 1.12.29 [flutter]
- avatar_glow 2.0.2 [flutter]
- cloud_firestore 4.4.5 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cloud_functions 4.1.1 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- cupertino_icons 1.0.5
- dartz 0.10.1
- encrypt 5.0.1 [args asn1lib clock collection crypto pointycastle]
- equatable 2.0.5 [collection meta]
- extended_masked_text 2.3.1 [flutter]
- firebase_analytics 10.1.4 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_app_check 0.1.3 [firebase_app_check_platform_interface firebase_app_check_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 4.5.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.11.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 14.5.0 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_remote_config 3.0.13 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]      
- flutter 0.0.0 [characters collection js material_color_utilities meta vector_math sky_engine]
- flutter_localizations 0.0.0 [flutter intl characters clock collection js material_color_utilities meta path vector_math]
- flutter_polyline_points 1.0.0 [flutter http]
- geolocator 9.0.2 [flutter geolocator_platform_interface geolocator_android geolocator_apple geolocator_web geolocator_windows]
- get 4.6.5 [flutter]
- google_maps_flutter 2.2.5 [flutter google_maps_flutter_android google_maps_flutter_ios google_maps_flutter_platform_interface]
- hive 2.2.3 [meta crypto]
- http 0.13.5 [async http_parser meta path]
- internet_connection_checker 1.0.0+1
- intl 0.17.0 [clock path]
- package_info_plus 3.0.3 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface win32]
- path_provider 2.0.14 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- permission_handler 10.2.0 [flutter meta permission_handler_android permission_handler_apple permission_handler_windows permission_handler_platform_interface]    
- provider 6.0.5 [collection flutter nested]
- socket_io_client 2.0.1 [logging socket_io_common js]
- timelines 0.1.0 [flutter]
- timer_count_down 2.2.2 [flutter]
- url_launcher 6.1.10 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]

dev dependencies:
- flutter_lints 2.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection js matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- _flutterfire_internals 1.2.0 [collection firebase_core firebase_core_platform_interface flutter meta]
- args 2.4.0
- asn1lib 1.4.0
- async 2.10.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.2.1
- clock 1.1.1
- cloud_firestore_platform_interface 5.11.5 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.3.5 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]  
- cloud_functions_platform_interface 5.2.1 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.4.1 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.17.0
- convert 3.1.1 [typed_data]
- crypto 3.0.2 [typed_data]
- fake_async 1.3.1 [clock collection]
- ffi 2.0.1
- file 6.1.4 [meta path]
- firebase_analytics_platform_interface 3.3.21 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.1+12 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]    
- firebase_app_check_platform_interface 0.0.7 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_app_check_web 0.0.9 [_flutterfire_internals firebase_app_check_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]       
- firebase_auth_platform_interface 6.14.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.4.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.7.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.4.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 4.4.0 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.4.0 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]  
- firebase_remote_config_platform_interface 1.1.33 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.1.22 [firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins js]
- flutter_plugin_android_lifecycle 2.0.9 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- geolocator_android 4.1.7 [flutter geolocator_platform_interface]
- geolocator_apple 2.2.5 [flutter geolocator_platform_interface]
- geolocator_platform_interface 4.0.7 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 2.1.6 [flutter flutter_web_plugins geolocator_platform_interface]
- geolocator_windows 0.1.1 [flutter geolocator_platform_interface]
- google_maps_flutter_android 2.4.7 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface stream_transform]
- google_maps_flutter_ios 2.2.0 [flutter google_maps_flutter_platform_interface stream_transform]
- google_maps_flutter_platform_interface 2.2.6 [collection flutter plugin_platform_interface stream_transform]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- js 0.6.5 [meta]
- lints 2.0.1
- logging 1.1.1
- matcher 0.12.13 [meta stack_trace]
- material_color_utilities 0.2.0
- meta 1.8.0
- nested 1.0.0 [flutter]
- package_info_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- path 1.8.2
- path_provider_android 2.0.24 [flutter path_provider_platform_interface]
- path_provider_foundation 2.2.0 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.9 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.0.6 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.4 [ffi flutter path path_provider_platform_interface win32]
- permission_handler_android 10.2.0 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.0.7 [flutter permission_handler_platform_interface]
- permission_handler_platform_interface 3.9.0 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.1.2 [flutter permission_handler_platform_interface]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.4.16 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.1 [collection]
- url_launcher_android 6.0.24 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.1.1 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.3 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.3 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.2 [flutter plugin_platform_interface]
- url_launcher_web 2.0.15 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.4 [flutter url_launcher_platform_interface]
- vector_math 2.1.4
- win32 3.1.3 [ffi]
- xdg_directories 1.0.0 [meta path process]

###Dependencies Android
dependencies {
    implementation platform('com.google.firebase:firebase-bom:32.0.0')
    implementation 'com.google.firebase:firebase-messaging:23.1.2'
    implementation 'com.google.firebase:firebase-crashlytics:18.3.7'
    implementation  'androidx.browser:browser:1.5.0'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.google.firebase:firebase-auth:22.0.0'
    //implementation 'com.google.android.gms:play-services-safetynet:18.0.1'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'com.google.code.gson:gson:2.9.1'
    implementation 'androidx.core:core:1.6.0'
    // (Java only)
    implementation "androidx.work:work-runtime:2.8.1"
    implementation ('io.socket:socket.io-client:2.1.0') {
        exclude group: 'org.json', module: 'json'
    }
    implementation 'com.google.guava:guava:27.0.1-android'
    implementation 'com.google.firebase:firebase-common-ktx:20.3.2'

}

**Comment by darshankawar** [comment]
@GrandeSamarone 
Can you provide the complete error log along with a minimal code sample that is causing the reported behavior ?

**Comment by GrandeSamarone** [comment]
https://github.com/firebase/flutterfire/assets/30990831/9be88194-de4f-4bac-a8e1-bcb5188fffee

**Comment by darshankawar** [comment]
Thanks for the update. Are you using any third party package implementations in your app ? Does the same behavior occur only using `firebase_auth` and other related firebase plugins only ?

**Comment by GrandeSamarone** [comment]
> Obrigado pela atualização. Você está usando alguma implementação de pacote de terceiros em seu aplicativo? O mesmo comportamento ocorre apenas usando `firebase_auth`e outros plug-ins do firebase relacionados apenas?

I'm not using third-party plugins, only with firebase auth, I can't find the error and why the code doesn't reach the app

**Comment by GrandeSamarone** [comment]
do you have a demo code that works?
based on it, or does the code only arrive in the app if it's in the store?

**Comment by darshankawar** [comment]
@GrandeSamarone 
Check below comments and see if they help in your case.

https://github.com/firebase/flutterfire/issues/4916#issuecomment-914239993

https://github.com/firebase/flutterfire/issues/4916#issuecomment-922274592

Also, `[SmsRetrieverHelper] Timed out waiting for SMS.` seems to be coming from native SDK and not from client side, so you'll probably need to reach out to native Android sdk for further resolution. See this related issue for your reference: 
https://github.com/firebase/firebase-android-sdk/issues/2688

Closing from here, as this doesn't seem to be actionable from flutterfire side. If you disagree, write in comments and I'll reopen it.

**Comment by GrandeSamarone** [comment]
just answer my doubt, is it possible to test the automatic verification before sending it to the store?
