### ISSUE TITLE
🐛 [cloud_firestore] WEB: useFirestoreEmualtor throws Exception: NoSuchMethodError: 'code' ... Receiver: Instance of 'NativeError'

### ISSUE THREAD

**Issue by just7mile** [firebase/flutterfire#10947]
## Bug report

Flutter version: 3.10.0
cloud_firestore version: 4.6.0

**Describe the bug**
After upgrading to Flutter 3.10.0, `FirebaseFirestore.instance.useFirestoreEmulator(...)` started to throw `Exception: NoSuchMethodError: 'code'` on hot-reload/restart.

```sh
Exception: NoSuchMethodError: 'code'
method not found
Receiver: Instance of 'NativeError'
Arguments: []
When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 288:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 813:3   defaultNoSuchMethod
dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 64:17                 noSuchMethod
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 808:31  noSuchMethod
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 135:10  dload
packages/cloud_firestore/src/firestore.dart 114:44                                useFirestoreEmulator
....

```

**Comment by darshankawar** [comment]
Thanks for the report. Seeing the same behavior upon trying to hot reloading using the firestore emulator.

/cc @Lyokone

**Comment by matt-hall-zory** [comment]
I'm seeing similar errors on useAuthEmulator (only on hot reload/restart)
`Error: Expected a value of type 'firebase_auth.Error', but got one of type 'NativeError'
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 288:49  throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 121:3   castError
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/types.dart 245:34   as
packages/firebase_auth_web/firebase_auth_web.dart 487:57                      useAuthEmulator`
