### ISSUE TITLE
🐛 [firebase_messaging] example project throw duplicateApp after following instructions in example/lib/main.dart

### ISSUE THREAD

**Issue by triplehman3563** [firebase/flutterfire#10943]
## Bug report

**Describe the bug**
Error message described as below.

````
2023-05-11 14:54:40.425176+0800 Firebase Cloud Messaging Example[26668:2610460] [VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: [core/duplicate-app] A Firebase App named "[DEFAULT]" already exists
#0      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:134:11)
<asynchronous suspension>
#1      Firebase.initializeApp (package:firebase_core/src/firebase.dart:43:31)
<asynchronous suspension>
#2      main (package:firebase_messaging_example/main.dart:121:3)
<asynchronous suspension>
````
### Steps to reproduce
1. following the instructions in ./packages/firebase_messaging/firebase_messaging/example/lib/main.dart

2. exception throw in step. 5

### Expected behavior

example to run on actual ios device successfully.

### Sample project

the example project in ./packages/firebase_messaging/firebase_messaging/example

---

## Additional context
The example project build and run fine when skipping step.4.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel master, 3.11.0-1.0.pre.20, on macOS 13.2 22D49 darwin-arm64, locale zh-Hant-TW)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.78.0)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 3.1.0-66.0.dev
Flutter SDK 3.11.0-1.0.pre.20
flutterfire_workspace 0.0.0

dev dependencies:
- melos 3.0.1 [ansi_styles args cli_launcher cli_util collection conventional_commit file glob graphs http meta mustache_template path platform pool prompts pub_semver pub_updater pubspec string_scanner yaml yaml_edit]

transitive dependencies:
- ansi_styles 0.3.2+1
- args 2.4.1
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- charcode 1.3.1
- cli_launcher 0.3.1 [path yaml]
- cli_util 0.3.5 [meta path]
- collection 1.17.1
- conventional_commit 0.6.0+1
- file 6.1.4 [meta path]
- glob 2.1.1 [async collection file path string_scanner]
- graphs 2.3.0 [collection]
- http 0.13.6 [async http_parser meta]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- io 1.0.4 [meta path string_scanner]
- json_annotation 4.8.1 [meta]
- matcher 0.12.15 [async meta stack_trace term_glyph test_api]
- meta 1.9.1
- mustache_template 2.0.0
- path 1.8.3
- platform 3.1.0
- pool 1.5.1 [async stack_trace]
- process 4.2.4 [file path platform]
- prompts 2.0.0 [charcode io]
- pub_semver 2.1.4 [collection meta]
- pub_updater 0.2.4 [http json_annotation process]
- pubspec 2.3.0 [path pub_semver yaml uri]
- quiver 3.2.1 [matcher]
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.5.2 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.2 [collection]
- uri 1.0.0 [matcher quiver]
- yaml 3.1.2 [collection source_span string_scanner]
- yaml_edit 2.1.1 [collection meta source_span yaml]
```

</details>

---

**Comment by triplehman3563** [comment]
found the solution.
the information in  `./packages/firebase_messaging/firebase_messaging/example/ios/runner/GoogleService-Info.plist ` will not be modified after the command `flutterfire configure`.
to fastest way to use the example is to just update the information in `GoogleService-Info.plist ` with those in `./packages/firebase_messaging/firebase_messaging/example/lib/firebase_options.dart`

and make sure you have the match bundle information in `runner.xcworkspace`, `firebase_options.dart` and `GoogleService-Info.plist`.

the instructions in main.dart should have add these on.

**Comment by danagbemava-nc** [comment]
Reproducible using the steps outlined above. 
The solution in https://github.com/firebase/flutterfire/issues/10943#issuecomment-1543563595 also worked. 

It seems like the GoogleService-Info.plist file is not being updated when `flutterfire configure` is run. 

The google-services.json file is properly updated so this doesn't happen on android. 

We can add that users will need to use an updated `GoogleService-Info.plist` file to the documentation after they make their modifications, but a better solution might be to have the cli tool update it just as it does for android. 

cc @russellwheatley

**Comment by russellwheatley** [comment]
This has been addressed already on FFCLI, a dev release hasn't been cut yet because it's awaiting approval. Will circle back once it has been released.
