### ISSUE TITLE
🐛 [firebase_messaging] sendMessage method is not working and its useless 

### ISSUE THREAD

**Issue by jijojacob556** [firebase/flutterfire#10951]
Future<void> sendMessage(
{String? to,
Map<String, String>? data,
String? collapseKey,
String? messageId,
String? messageType,
int? ttl}
)

I tired to use this method to send msg to a specific topic, but I'm getting null exceptions for something is missing which is not clear from exception, the method does not nessserly point out the required parameter, also its only for Android, then how do I  send msg to a topic in ios, it look like no one use this method, can't find any data in internet about how to use it, if it's deprecated, pls tell me an alternative way to send msg using the plugin

**Comment by darshankawar** [comment]
@jijojacob556 
Its not very clear what your issue is and what are you trying to implement / run. Please provide `flutter doctor -v`, a minimal complete code sample along with complete payload you are sending along with current / actual behavior with any error log that can be helpful to analyze further.

**Comment by jijojacob556** [comment]
i want to know how to use it for Android and ios, I can't find any info about how to use it , and I'm just getting a null exception only 

 Future sendMessage(
{String? to,
Map<String, String>? data,
String? collapseKey,
String? messageId,
String? messageType,
int? ttl}
)

**Comment by jijojacob556** [comment]
firebase_messageing is useless without 

Future sendMessage(
{String? to,
Map<String, String>? data,
String? collapseKey,
String? messageId,
String? messageType,
int? ttl}
)
