### ISSUE TITLE
[firebase_core-2.12.0]Can't compile on MacOS [flutter 3.10.0]

### ISSUE THREAD

**Issue by Fraa-124** [firebase/flutterfire#10964]
## Bug report

**Describe the bug**
[+5969 ms] [+5966 ms] ../../../.pub-cache/hosted/pub.dev/firebase_core-2.12.0/lib/src/firebase_app.dart:18:25: Error: Member not found: 'FirebaseAppPlatform.verify'.
firebase_app.dart:18
[        ] [   +1 ms]     FirebaseAppPlatform.verify(_delegate);

Platform: Macos

Still trying to upgrade my  app, but jesus christ, no luck... I don't understand how this error could have been overlooked.

**Comment by vickyGeo** [comment]
I have the same issue

**Comment by Lyokone** [comment]
Hey, can you try to run `flutterfire update` and paste the command result?

**Comment by Fraa-124** [comment]
I'm still encountering an error with my Firebase dependencies.

my firebase dependencies.

```dart
  firebase_core: 2.13.0
  firebase_auth: 4.6.1
  firebase_crashlytics: 3.3.1
  firebase_dynamic_links: 5.3.1
```

I have cleared the cache multiple times on macOS using the following commands, which usually resolve the issue.

```dart
rm macos/Podfile.lock
flutter clean && flutter pub get
sudo arch -x86_64 gem install ffi
arch -x86_64 pod repo update
arch -x86_64 pod install
```

**Comment by danagbemava-nc** [comment]
Hi @Fraa-124, please share the full output of `flutter run -v` or `flutter build macos -v` depending on what command you face the issue with. 

The output is likely to be huge so kindly put it into a .log file and paste it here. 

Please also provide your `Podfile` & `Podfile.lock` files. 

Thank you
