### ISSUE TITLE
[📚firebase_firestore]  Firestore caching of missing documents

### ISSUE THREAD

**Issue by pyciko** [firebase/flutterfire#10962]
When user registers in my app, there's a Cloud Function which triggers on account creation and creates a corresponding Firestore document in users collection for them. I'm using link auth, so there's no way to check if account was just created or it already existed on client. Because of that, in my auth listener, I just try to fetch the user document in Firestore once they logged in, and in case if this operation fails (and it fails upon registration because it takes a few seconds to create the document), it just repeats the operation until it manages to fetch it. But the problem is, it looks like there's some kind of caching of non-existing documents, and so if for once the app fails to fetch the document, it will then fail each next time. It's quite hard to exit this state, sometimes I need to restart the app, sometimes I even need to reinstall it. I also noticed similar behaviour in some other cases as well: the document was missing on first fetch, I created it, but the app still continued thinking that it does not exist in Firestore. So am I correct that there's some kind of non-existent document caching in place, and how do I fix my issue? It is not documented anywhere, but as I said, I encountered this behaviour in multiple other places.

**Comment by darshankawar** [comment]
@pyciko 

Can you try by passing "source" to GetOptions in the get() calls to make it retrieve the cache-only updates ?

**Comment by pyciko** [comment]
I'm not using get(), I'm using snapshots().listen() to get further updates. The base system for that is used in many other app components, and in those components, the logic is made so that if document does not exist in the first snapshot, it just cancels the listener and returns an error. In most places in my app this is a correct logic, this is why I don't continue listening to snapshots if first one was missing.

Here's the code snippet:

  Future<T?> getFromServer(String id) async {
    final dbRef = colRef.doc(id);

    final completer = Completer<T>();
    late StreamSubscription<DocumentSnapshot<Object?>> sub;
    sub = dbRef.snapshots().listen((snap) async {
      if (!snap.exists) {
        if (!completer.isCompleted) completer.completeError('DOCUMENT $id IS MISSING');
        await sub.cancel();
        return;
      }
      if (!_items.containsKey(id)) {
        //FIRST SNAPSHOT
        try {
          _items[id] = parseJson(snap.data()! as Map<String, dynamic>);
          _items[id]!.setRefs(dbRef, quicksRef, sub, this);
          _items[id]!.onInit();
          if (!completer.isCompleted) completer.complete(_items[id]);
        } catch (e) {
          if (!completer.isCompleted) completer.completeError('Err during loading: $e');
          await sub.cancel();
        }
      } else {
        await _items[id]?.onServerUpdate(snap.data()! as Map<String, dynamic>);
        _items[id]?.notify();
      }
    });

    return completer.future;
  }

**Comment by russellwheatley** [comment]
What error are you receiving?

**Comment by darshankawar** [comment]
This issue got closed probably because the bot didn't remove the waiting label.
I'll reopen based on OP's response.

**Comment by Lyokone** [comment]
Hello, after reading through the issue, it looks like something that has to do with backend and cloud functions more than Flutterfire implementation of Firestore. I would advise you to open an issue in https://github.com/firebase/firebase-admin-node for clarification.
