### ISSUE TITLE
📚 [firebase_performance] Proper documentation for Flutter Web missing?

### ISSUE THREAD

**Issue by iamshaunwu** [firebase/flutterfire#10960]
I am unable to get Perf Mon to work on Flutter Web. There doesn't seem to be proper documentation about it except for the installing the dependency on the official Firebase Documentation and on the old Flutterfire documentation, it shows a simple one liner FirebasePerformance performance = FirebasePerformance.instance; which does not work.

My current pubspec version is firebase_performance: ^0.9.2.

I have tried manual installation indicated here https://firebase.flutter.dev/docs/manual-installation/web (though the content is considered archived) but to no avail.

I have also tried the troubleshooting methods indicated here https://firebase.google.com/docs/perf-mon/troubleshooting?platform=web but nothing is working. I don't see any network logs on Chrome Dev Tool that the web app is sending data to Firebase Performance.

Can someone shed some light on this? Thanks!

**Comment by udit6023** [comment]
Actually the thing is Firebase, does not currently support Firebase Performance Monitoring on Flutter Web. As of my knowledge cutoff in September 2021, Firebase Performance Monitoring is only available for Flutter on iOS and Android platforms.

**Comment by arensonjr** [comment]
I ran across the same thing today.

If that's the case udit6023, should the `firebase_performance` package drop the `platform:web` tag?

**Comment by TarekkMA** [comment]
Hi @iamshaunwu  ,

Thank you for your report! Since this issue was opened, the implementation details have changed significantly. If you feel that this issue is still relevant, please feel free to open a new issue with updated context. We appreciate your understanding and support.
