### ISSUE TITLE
🐛 [firebase_core] Upgrade path plugin to 1.8.3

### ISSUE THREAD

**Issue by Saifallak** [firebase/flutterfire#10979]
## Bug report

**Describe the bug**
Upgrade path plugin to 1.8.3

### Expected behavior

Upgraded path plugin to 1.8.3

**Comment by danagbemava-nc** [comment]
Hi @Saifallak, firebase_core does not depend on the path plugin. See https://github.com/firebase/flutterfire/blob/master/packages/firebase_core/firebase_core/pubspec.yaml

Did you perhaps mean another package? Also, is there a specific error that you're facing from one of the packages that may be depending on the `path` plugin?
