### ISSUE TITLE
🐛 [Github] Link in the "About" section on Github does not work anymore

### ISSUE THREAD

**Issue by jaredsburrows** [firebase/flutterfire#10985]
The link https://firebase.google.com/docs/flutter/setup does not work anymore. 

<img width="355" alt="Screenshot 2023-05-17 at 11 57 31 AM" src="https://github.com/firebase/flutterfire/assets/1739848/e576f2a6-8d1c-4d4b-91e3-90e1f6f03024">

**Comment by darshankawar** [comment]
@jaredsburrows 
I tried the link and it is working as expected.


https://github.com/firebase/flutterfire/assets/67046386/817a8540-da98-46cb-9362-1ddccdf53741

The link opens the screen / page properly:

https://firebase.google.com/docs/flutter/setup?platform=android

Will close as WAI. If you disagree, write in comments and I'll reopen it.

**Comment by jaredsburrows** [comment]
Thanks. Must have been bad cache.
