### ISSUE TITLE
🐛 [firebase_dynamic_links] getDynamicLink return null on iOS with short link from another firebase project

### ISSUE THREAD

**Issue by thanhhuan1990** [firebase/flutterfire#10986]
## Bug report

**Describe the bug**
I have 2 Flutter application
- Application 1: show a shortlink which created by Google APIs as a QR code
- Application 2: Scan the QR code from Application 1: to get the shortlink, and then call the function getDynamicLink to get PendingDynamicData

### Expected behavior

Application 2 can get the PendingDynamicData as expected in iOS (It's working normally on Android)

## Additional context
- It's working normally on Android
- The getDynamicLink return data in case I use the example shortLink created in the Firebase console of Application 2
---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.2.1 22D68 darwin-arm64, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.4)
[✓] VS Code (version 1.78.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
- firebase_analytics 10.4.1 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 2.13.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 3.3.1 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_dynamic_links 5.3.1 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]

```

</details>

---

**Comment by danagbemava-nc** [comment]
Hi @thanhhuan1990, please provide a complete minimal reproducible code sample in a repo we can clone so that we can investigate this.

PS: It does not have to be your actual project, just the smallest sample required to reproduce the issue is fine. 

Thank you

**Comment by thanhhuan1990** [comment]
Hi, @danagbemava-nc , please help to check my demo source in this public project:
https://github.com/thanhhuan1990/demo_dynamiclinks_issue.git

---
iOS return null data
![Simulator Screenshot - iPhone 13 - 2023-05-20 at 14 55 27](https://github.com/firebase/flutterfire/assets/11939679/2659400b-b664-493f-b12f-5dfd9dfaa245)

But is's OK on Android
![Screenshot_20230520-144012](https://github.com/firebase/flutterfire/assets/11939679/48155681-a6d7-4cbe-a9c5-c19ce8297dbf)

**Comment by danagbemava-nc** [comment]
Hi, @thanhhuan1990, thanks for the code sample. 

I can reproduce the issue using the repo provided above. 

I don't see any errors but I just see these lines in my console. Not sure what it means. 

```
[connection] nw_connection_copy_connected_local_endpoint_block_invoke [C3] Client called nw_connection_copy_connected_local_endpoint on unconnected nw_connection
[connection] nw_connection_copy_connected_remote_endpoint_block_invoke [C3] Client called nw_connection_copy_connected_remote_endpoint on unconnected nw_connection
[connection] nw_connection_copy_protocol_metadata_internal_block_invoke [C3] Client called nw_connection_copy_protocol_metadata_internal on unconnected nw_connection
[connection] nw_connection_copy_connected_local_endpoint_block_invoke [C4] Client called nw_connection_copy_connected_local_endpoint on unconnected nw_connection
[connection] nw_connection_copy_connected_remote_endpoint_block_invoke [C4] Client called nw_connection_copy_connected_remote_endpoint on unconnected nw_connection
[connection] nw_connection_copy_protocol_metadata_internal_block_invoke [C4] Client called nw_connection_copy_protocol_metadata_internal on unconnected nw_connection
[connection] nw_connection_copy_connected_local_endpoint_block_invoke [C7] Client called nw_connection_copy_connected_local_endpoint on unconnected nw_connection
[connection] nw_connection_copy_connected_remote_endpoint_block_invoke [C7] Client called nw_connection_copy_connected_remote_endpoint on unconnected nw_connection
[connection] nw_connection_copy_protocol_metadata_internal_block_invoke [C7] Client called nw_connection_copy_protocol_metadata_internal on unconnected nw_connection
[connection] nw_connection_copy_connected_local_endpoint_block_invoke [C10] Client called nw_connection_copy_connected_local_endpoint on unconnected nw_connection
[connection] nw_connection_copy_connected_remote_endpoint_block_invoke [C10] Client called nw_connection_copy_connected_remote_endpoint on unconnected nw_connection
[connection] nw_connection_copy_protocol_metadata_internal_block_invoke [C10] Client called nw_connection_copy_protocol_metadata_internal on unconnected nw_connection
```

Labeling for further investigation

**Comment by jerrypaulsam** [comment]
Hello @thanhhuan1990  I have the same issue. Did you find a solution?

**Comment by russellwheatley** [comment]
Hi folks, we'd like to inform you that the Firebase Dynamic Links service will be shutdown on August 25, 2025. In the meantime, only critical or security issues will be fixed in the SDK.

More at [firebase.google.com/support/dynamic-links-faq](https://firebase.google.com/support/dynamic-links-faq)
