### ISSUE TITLE
🐛 [APP_CHECK] App Check keeps returning a invalid token on android

### ISSUE THREAD

**Issue by Andrushka1012** [firebase/flutterfire#10983]
I created this issue cause [the previous one](https://github.com/firebase/flutterfire/discussions/7998) was not properly solved. Using debug variant on production is not a solution and is restricted on [official docs page](https://firebase.flutter.dev/docs/app-check/debug-provider/).

After setup playintegrity in Firebase, the appcheck plugin for flutter android always app returns token eyJlcnJvciI6IlVOS05PV05fRVJST1IifQ==.
In that string encoded -> {"error":"UNKNOWN_ERROR"} in base64.

**Comment by darshankawar** [comment]
Thanks for the report @Andrushka1012 
Can you provide `flutter doctor -v`, complete error log and a reproducible code sample that we can use that shows the reported behavior ?

**Comment by Andrushka1012** [comment]
Hi, @darshankawar . Here is my flutter doctor:
[✓] Flutter (Channel stable, 3.7.11, on macOS 13.3.1 22E772610a darwin-x64, locale en-GB)
    • Flutter version 3.7.11 on channel stable at /Users/andriimakarenko/Desktop/euvic/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f72efea43c (5 weeks ago), 2023-04-11 11:57:21 -0700
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/andriimakarenko/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (4 available)
    • Pixel 6 (mobile)       • 19061FDF6006MD                       • android-arm64  • Android 13 (API 33)
    • iPhone 14 Pro (mobile) • C0747B85-B9E6-42CC-9442-825BEC23ABD4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 13.3.1 22E772610a darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 113.0.5672.92

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!


Steps to reproduce is actually same as in https://github.com/firebase/flutterfire/discussions/7998.
After I setup app check play integrity for my firebase project
```
Firebase.initializeApp().then((value) async {
      await FirebaseAppCheck.instance.activate(
        appleProvider: AppleProvider.appAttestWithDeviceCheckFallback,
        androidProvider: AndroidProvider.playIntegrity,
      );
    }
```
    
   
 and then 
    
`FirebaseAppCheck.instance.getToken()`.


This returns me as a result  eyJlcnJvciI6IlVOS05PV05fRVJST1IifQ==

**Comment by darshankawar** [comment]
@Andrushka1012 
This has probably been fixed https://github.com/firebase/flutterfire/issues/10167. Please check the same and see if it helps in your case.
