### ISSUE TITLE
🐛 [PLUGIN_NAME_HERE] Your issue title here

### ISSUE THREAD

**Issue by Rafael33Taveira** [firebase/flutterfire#10989]
## Bug report

Couldn't resolve the package 'firebase_storage' in 'package:firebase_storage/firebase_storage.dart'.

### Steps to reproduce

2. '...'
4. See error or incorrect behavior

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by darshankawar** [comment]
@Rafael33Taveira 
Can you provide `flutter doctor -v`, a complete error log that is shown along with `pubspec.yaml` and steps to replicate that shows the reported error ?

**Comment by Rafael33Taveira** [comment]
hey guys, the project is running right now!!! thanks for everyone !!!

**Comment by darshankawar** [comment]
Closing as resolved based on above comment.
