### ISSUE TITLE
🐛 [firebase_auth] WEB: Bad state: Cannot fire new event. Controller is already firing an event

### ISSUE THREAD

**Issue by just7mile** [firebase/flutterfire#10993]
## Bug report

Dart: **3.0.0**
Flutter: **3.10.0**
Firebase Core: **2.13.0**
Firebase Auth: **4.6.1**

**Describe the bug**
After upgrading to Flutter 3.10 the Firebase Auth on web is giving `Bad state: Cannot fire new event. Controller is already firing an event` error during hot reload/restart. I tried the fix mentioned in this [comment](https://github.com/firebase/flutterfire/issues/3756#issuecomment-757500560), but it did not work.

<img width="703" alt="image" src="https://github.com/firebase/flutterfire/assets/29413456/13f2433f-21ff-47a8-9d49-a8bd265af1b2">

And the VSCode points to the file `firebase_auth_web-5.5.1/lib/src/interop/auth.dart`:

<img width="1059" alt="image" src="https://github.com/firebase/flutterfire/assets/29413456/e1051564-086c-49f8-a340-e3a11dfdb6e8">

**Comment by darshankawar** [comment]
Thanks for the report @just7mile 
I tried to replicate it using [plugin example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_auth/firebase_auth/example) running on latest stable with dart 3 environment and latest plugin versions, but I was able to login properly with a test user without throwing the reported error.

<img width="1193" alt="Screenshot 2023-05-18 at 5 32 48 PM" src="https://github.com/firebase/flutterfire/assets/67046386/7cf40e88-ebcc-4ac8-81dd-2627db0c02d1">

You can try the same and see if it still gives you same error or not. If not, a repo or minimal code sample would be helpful to debug this further.

**Comment by just7mile** [comment]
Thank you for you response! I couldn't reproduce it with plugin's example app, but I was able to find the source of the problem. **It turns out the problem was related to Cloud Firestore, with the catching `FirebaseException` specifically**. 

When using Firestore emulators and enabling persistence it gives `Firestore has already been started and persistence can no longer be enabled. You can only enable persistence before calling any other methods on a Firestore object.` error on hot restart/reload, so I was catching this error and ignoring it if it's a `failed-precondition` error:
```dart
try {
    if (kIsWeb && persistenceEnabled) {
      await FirebaseFirestore.instance
          .enablePersistence(const PersistenceSettings(synchronizeTabs: true));
    }
  } on FirebaseException catch (e) {
    // On hot reload/restart [FirebaseFirestore.instance.enablePersistence] throws failed-precondition error on WEB.
    if (e.code != 'failed-precondition') rethrow;
  }
```
After upgrading to Flutter 3.10.0 we no longer getting `FirebaseException` on the WEB, but only `NativeError`, so the catch was not working and it was causing the problem.

I think issue is related to the [#10947](https://github.com/firebase/flutterfire/issues/10947), and `NativeError`s should be handled somehow globally and converted to `FirebaseException`s, because  developers might use the `FirebaseException` in many places in their projects.

**Comment by just7mile** [comment]
> Thanks for the report @just7mile I tried to replicate it using [plugin example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_auth/firebase_auth/example) running on latest stable with dart 3 environment and latest plugin versions, but I was able to login properly with a test user without throwing the reported error.
> <img alt="Screenshot 2023-05-18 at 5 32 48 PM" width="1193" src="https://user-images.githubusercontent.com/67046386/239228475-7cf40e88-ebcc-4ac8-81dd-2627db0c02d1.png">
> 
> You can try the same and see if it still gives you same error or not. If not, a repo or minimal code sample would be helpful to debug this further.

Thank you for your fast response! I couldn't reproduce it with plugin's example app, but I was able to find the source of the problem. **It turns out the problem was related to Cloud Firestore, with the catching `FirebaseException` specifically**. 

When using Firestore emulators and enabling persistence it gives `Firestore has already been started and persistence can no longer be enabled. You can only enable persistence before calling any other methods on a Firestore object.` error on hot restart/reload, so I was catching this error and ignoring it if it's a `failed-precondition` error:
```dart
try {
    if (kIsWeb && persistenceEnabled) {
      await FirebaseFirestore.instance
          .enablePersistence(const PersistenceSettings(synchronizeTabs: true));
    }
  } on FirebaseException catch (e) {
    // On hot reload/restart [FirebaseFirestore.instance.enablePersistence] throws failed-precondition error on WEB.
    if (e.code != 'failed-precondition') rethrow;
  }
```
After upgrading to Flutter 3.10.0 we no longer getting `FirebaseException` on the WEB, but only `NativeError`, so the catch was not working and it was causing the problem.

I think issue is related to the [#10947](https://github.com/firebase/flutterfire/issues/10947), and `NativeError`s should be handled somehow globally and converted to `FirebaseException`s, because  developers might use the `FirebaseException` in many places in their projects.

**Comment by darshankawar** [comment]
Thanks for the detailed analysis and update. Since the linked issue has been fixed recently, does upgrading `cloud_firestore` to latest version and trying out the scenario again gives you the same behavior ?

**Comment by just7mile** [comment]
> Thanks for the detailed analysis and update. Since the linked issue has been fixed recently, does upgrading `cloud_firestore` to latest version and trying out the scenario again gives you the same behavior ?

Yes, here are the packages versions:
```yml
cloud_firestore: ^4.7.1
firebase_auth: ^4.6.1
firebase_core: ^2.13.0
```

And printing the exception shows this `FirebaseError: [code=failed-precondition]: Firestore has already been started and persistence can no longer be enabled. You can only enable persistence before calling any other methods on a Firestore object.`, as you can see it is printed as a `FirebaseError: ...`, but the runtime type is still `NativeError`:
```dart
try {
    if (kIsWeb && persistenceEnabled) {
      await FirebaseFirestore.instance
          .enablePersistence(const PersistenceSettings(synchronizeTabs: true));
    }
  } on FirebaseException catch (e) {
    // On hot reload/restart [FirebaseFirestore.instance.enablePersistence] throws failed-precondition error on WEB.
    if (e.code != 'failed-precondition') rethrow;
  } catch(e) {
    print(e); // FirebaseError: ...
    print(e.runtimeType); // NativeError
  }
```

**Comment by russellwheatley** [comment]
Hey there, the native error issue is being tracked here:https://github.com/firebase/flutterfire/issues/10966. I will update that channel once it has been resolved.

We've raised with the Dart team which you can view here: https://github.com/dart-lang/sdk/issues/52572.
