### ISSUE TITLE
🐛 [firebase_messaging] Foreground notifications doesn't fire onMessage event listener without fetching token prior to receiving

### ISSUE THREAD

**Issue by NilsIrl** [firebase/flutterfire#11008]
## Bug report

**Describe the bug**

Identical issue to #6011

Unlike what is claimed in that issue the problem has not been fixed (or at least there's been a regression).

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.1, on macOS 13.3.1 22E772610a darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
[✓] VS Code (version 1.78.1)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 3.0.1
Flutter SDK 3.10.1
pingable 1.0.0+1

dependencies:
- cupertino_icons 1.0.5
- firebase_core 2.13.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 14.6.1 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection js material_color_utilities meta vector_math sky_engine]
- flutter_local_notifications 14.0.1 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- http 0.13.6 [async http_parser meta]

dev dependencies:
- flutter_lints 2.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection js matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- _flutterfire_internals 1.3.1 [collection firebase_core firebase_core_platform_interface flutter meta]
- args 2.4.1
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- collection 1.17.1
- dbus 0.7.8 [args ffi meta xml]
- fake_async 1.3.1 [clock collection]
- ffi 2.0.2
- file 6.1.4 [meta path]
- firebase_core_platform_interface 4.8.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.5.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 4.5.1 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.5.1 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flutter_local_notifications_linux 4.0.0+1 [dbus ffi flutter flutter_local_notifications_platform_interface path xdg_directories]
- flutter_local_notifications_platform_interface 7.0.0+1 [flutter plugin_platform_interface]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- js 0.6.7 [meta]
- lints 2.1.0
- matcher 0.12.15 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.2.0
- meta 1.9.1
- path 1.8.3
- petitparser 5.4.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.4 [meta]
- process 4.2.4 [file path platform]
- sky_engine 0.0.99
- source_span 1.9.1 [collection path term_glyph]
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.5.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.9.2 [path]
- typed_data 1.3.2 [collection]
- vector_math 2.1.4
- xdg_directories 1.0.0 [meta path process]
- xml 6.3.0 [collection meta petitparser]
```

</details>

---

**Comment by darshankawar** [comment]
@NilsIrl Thanks for the report. The issue you linked is quite an old one and the most recent comment is from last year. In order to properly address this, can you provide on what platform are you seeing this behavior ?

Is there a way for you to check out [plugin example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example) and see if using it, you get the reported behavior or not ?

**Comment by NilsIrl** [comment]
I tried the plugin and was able to reproduce. Other things than calling `FirebaseMessaging.instance.getToken()` "fix" the issue. These include getting `FirebaseMessaging.instance.onTokenRefresh`, as well as calling `FirebaseMessaging.instance.getInitialMessage()` and `FirebaseMessaging.instance.setForegroundNotificationPresentationOptions()`.

The following patch file modifies the example such that `onMessage` doesn't get triggered: [onMessage.patch](https://github.com/firebase/flutterfire/files/11534571/onMessage.patch)


Note that even when onMessage doesn't get fired, the following is printed to the console when the notification/message is sent which means that it does reach a part of the front-end, just not `onMessage`:

```
D/FLTFireMsgReceiver( 5059): broadcast received for message
W/FirebaseMessaging( 5059): Unable to log event: analytics library is missing
W/FirebaseMessaging( 5059): Unable to log event: analytics library is missing
```

**Comment by darshankawar** [comment]
@NilsIrl 
Check if this could be related or not: https://github.com/firebase/flutterfire/issues/10291

**Comment by NilsIrl** [comment]
Sorry, I forgot to respond to your question but all this has been done on Android. I have not tried with iOS.

**Comment by darshankawar** [comment]
Thanks for the report. Using plugin example, seeing the same behavior as reported https://github.com/firebase/flutterfire/issues/11008#issuecomment-1557642713, so will keep this issue open for team's input.

**Comment by victor-kotov** [comment]
I could confirm it for iOS too, so I followed the guide https://firebase.google.com/docs/cloud-messaging/flutter/receive and was able to receive pushes on a device, but foreground and background related code/listeners weren't called until I added "FirebaseMessaging.instance.getToken()" - also I suppose it should be wrapped with notification permission status check 🤔

@darshankawar could you please provide some estimation for a fix?

**Comment by russellwheatley** [comment]
Hey @NilsIrl, do you have to call `getToken()` every single time to receive a message via `onMessage()`? Or is it periodically? Again I've tested, and I received a message without calling `getToken()`. 

My sense is that your token is stale and you need to get a fresh token for it to be received

**Comment by 0xManjeet** [comment]
> Hey @NilsIrl, do you have to call `getToken()` every single time to receive a message via `onMessage()`? Or is it periodically? Again I've tested, and I received a message without calling `getToken()`.

I'm facing the same issue.
I have to call the `getToken()` at least once on every launch of the app to get the foreground messages working.

**Comment by NilsIrl** [comment]
> Hey @NilsIrl, do you have to call `getToken()` every single time to receive a message via `onMessage()`? Or is it periodically?

I'm not sure how I'd go about checking this. However my impression is that I have to call getToken every single time I run the app. I have never had it work without calling getToken.

> My sense is that your token is stale and you need to get a fresh token for it to be received

The stale token hypothesis seems unlikely considering when I don't call `getToken()` there are things printed on the console whenever a notification is sent, it's just that it doesn't reach my listener.

My impression is that there's something that is lazily initiated by calling `getToken()` (and other functions) which makes `onMessage` work.

>  Again I've tested, and I received a message without calling `getToken()`.

Do you maybe call another function that fixes the issue: https://github.com/firebase/flutterfire/issues/11008#issuecomment-1557642713

**Comment by russellwheatley** [comment]
I've circled back to this, and completely stripped out the example app with just the `onMessage` handler set for FirebaseMessaging. I was able to reproduce on both android and iOS. I think you are correct @NilsIrl, it seems you need to call `getToken()` before setting `onMessage()`. I consider this a documentation update as it is a form of initialisation required at the level of the native SDKs.

**Comment by NilsIrl** [comment]
Is it really necessary to initialize it in this way though? As I mentioned things are printed to the console even when "it is not initialized", so it means this could work without it being initialized.

**Comment by russellwheatley** [comment]
Thanks for that insight, @NilsIrl. I went back and debugged what is happening, I've got a PR fix here: https://github.com/firebase/flutterfire/pull/11447
