### ISSUE TITLE
🐛 [firebase_dynamic_links] Define custom suffix and ofl-parameter at the same time

### ISSUE THREAD

**Issue by LoadJulz** [firebase/flutterfire#11000]
## Bug report

**Describe the bug**
We use dynamic links that allow our users to refer other users using a unique link. Initially, I used the Flutter package to create dynamic links, but I realized I needed the 'ofl-parameter.' To include this parameter, I had to call the REST API. This addition ensures that when users accessing the link on desktop are redirected to our landing page instead of receiving the Firebase error message. This method has been working well so far. However, we have a new requirement where some users would like to have a custom dynamic link suffix. This customization would make the link appear more trustworthy when shared within their community. I am aware that Firebase web app supports this feature, but I haven't found any options for it in the REST API or the Flutter package.

Can someone please advise me on how to achieve the 'ofl-parameter' along with a custom suffix using Flutter?

**Comment by darshankawar** [comment]
@LoadJulz 
ofl parameter seemed to have been added as part of https://github.com/firebase/flutterfire/issues/7643 so please check the same and see if it helps.
If not, provide more details so that we can properly address this issue.

**Comment by LoadJulz** [comment]
But can I adjust the suffix of the short link with this package as well?

**Comment by russellwheatley** [comment]
If you're trying to build a dynamic link with the `ofl` parameter, you can just add it to the `longDynamicLink` as demonstrated in the example app here: https://github.com/firebase/flutterfire/blob/e1f5a5ea798c54f19d1d2f7b8f2250f8819f44b7/packages/firebase_dynamic_links/firebase_dynamic_links/example/lib/main.dart#L75 Also include the `uriPrefix` you wish to use from the Firebase console.

**Comment by LoadJulz** [comment]
This didn't answer my question. I have already implemented the ofl-tag in my dynamic link, but I have no option to use a custom suffix instead of the short url (the code that is generated randomly). Is there any option I can use to define the suffix of the url?
