### ISSUE TITLE
The "@pragma('vm:entry-point')" the code added to andriod correctly working on but not in ios🐛 

### ISSUE THREAD

**Issue by paramesh0** [firebase/flutterfire#11022]
## Bug report

**Describe the bug**
 andriod working properly. but ios I have problem
`  @pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
    await Firebase.initializeApp();
    print("ON TERMINATED");
  if (message.messageId?.isNotEmpty ?? false) {
    NotificationService.instance.categorizeNotification(message.data);
  }
}`

### Steps to reproduce

1. the same code build not working on ios
2. the "@pragma('vm:entry-point')" the code added ios correctly working on andriod but not in ios

### Expected behavior

the ios working properly

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by darshankawar** [comment]
@paramesh0 
Can you provide `flutter doctor -v`, `pubspec.yaml` ? When you say it is not correctly working, what behavior is it showing on iOS ? Are you getting any error ? What's the expected result are you looking for against the actual result ?

**Comment by paramesh0** [comment]
@darshankawar  

flutter doctor:
/Users/parameshwaran/developement/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 3.7.10, on macOS 13.2.1 22D68 darwin-x64, locale en-IN)
    • Flutter version 3.7.10 on channel stable at /Users/parameshwaran/developement/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b12645012 (8 weeks ago), 2023-04-03 17:46:48 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/parameshwaran/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Users/parameshwaran/Downloads/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • Subbiah’s iPhone (mobile) • 00008030-000C091A346B402E • ios            • iOS 15.6.1 19G82
    • macOS (desktop)           • macos                     • darwin-x64     • macOS 13.2.1 22D68 darwin-x64
    • Chrome (web)              • chrome                    • web-javascript • Google Chrome 113.0.5672.126

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
Process finished with exit code 0


Pubspec yaml:
firebase_crashlytics: ^3.3.0
firebase_core: ^2.12.0
firebase_messaging: ^14.6.0
