### ISSUE TITLE
🐛 [firebase_crashlytics] Grouping of exceptions for iOS is broken in version 3.0.17

### ISSUE THREAD

**Issue by lsuhov** [firebase/flutterfire#11029]
## Bug report

The version 3.0.17 is incorporating this CR https://github.com/firebase/flutterfire/pull/10566/files for iOS.
With it, the abs address is changed from 0 to the real one, and the comment states the following: **abs addresses are different across sessions, Crashlytics is smart enough to group exceptions in the same issue**.
At least in my case Crashlytics was not capable of performing the grouping, and now just a single exception is scatered across tens of events. 
You can figure now that Crashlytics became unusable with this regression.

Please ignore the part of having the code obfuscated, still researching on that problem.
Here's a screenshot:
![2023-05-23 at 16 42](https://github.com/firebase/flutterfire/assets/20156338/51caf93b-d1e9-4c7f-8b3b-df63dbb33eb7)

### Steps to reproduce
1. Utilise the 3.0.17 version
2. Send same exception on iOS accross several app sessions
3. Exceptions are not grouped in a single event , instead they are grouped per abs address

### Expected behavior

Exceptions should be grouped as before the release of 3.0.17

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
 Flutter (Channel unknown, 3.3.10, on macOS 13.4 ....)
    Flutter version 3.3.10 on ....
  
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[!] Android Studio (version 2022.2)
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.78.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
dependencies:
.....
- firebase_analytics 10.4.1 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 2.13.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 3.3.1 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_dynamic_links 5.3.1 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_messaging 14.6.1 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_performance 0.9.2+1 [firebase_core firebase_core_platform_interface firebase_performance_platform_interface firebase_performance_web flutter]

transitive dependencies:
...
- firebase_analytics_platform_interface 3.6.1 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.4+1 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_core_platform_interface 4.8.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.5.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.6.1 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_dynamic_links_platform_interface 0.2.6+1 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.5.1 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.5.1 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_performance_platform_interface 0.1.4+1 [_flutterfire_internals firebase_core flutter plugin_platform_interface]
- firebase_performance_web 0.1.4+1 [_flutterfire_internals firebase_core firebase_core_web firebase_performance_platform_interface flutter flutter_web_plugins js]
......
```

</details>

---

**Comment by danagbemava-nc** [comment]
Hi @lsuhov, 3.0.17 is an older version of crashlytics. Can you upgrade to the latest version of crashlytics to see if you still have this issue?

You may need to update your flutter version as well.

**Comment by lsuhov** [comment]
Hello @danagbemava-nc ,
We have tested with 3.2.0 and the issue is still reproducible.

**Comment by darshankawar** [comment]
Keeping this issue for team's input and attention based on the report and number of upvotes.

/cc @Lyokone

**Comment by lsuhov** [comment]
Hello,
The workaround found for this issue was to downgrade the firebase crashlytics version to 3.0.16.
The side effect was that now we have the Android reporting broken. Almost all exceptions are comming in same group, irrespective of their type!

So please take ios grouping issue on priority because we have to chose now which platform is less important for us.

**Comment by KoheiKanagu** [comment]
I'm also facing the same issue.
As a workaround, I've avoided the problem by replacing it with `abs 0`.
`firebase_crashlytics: ^3.4.1`

```dart
final newStackTrace = StackTrace.fromString(
  StackTrace.current
      .toString()
      .split('\n')
      .map(
        (e) => e.replaceFirst(RegExp(r'abs [\da-f]+'), 'abs 0'),
      )
      .join('\n'),
);
FirebaseCrashlytics.instance.recordError(
  Exception('exception'),
  newStackTrace,
);
```

**Comment by russellwheatley** [comment]
@Isuhov -  Does this still occur when the dart stack traces are symbolicated (de-obfuscated)? If you follow the documentation here: https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?&platform=flutter#run-script-does-not-exist

It will de-obfuscate the Dart stack trace which might allow the Firebase console to group them appropriately.

**Comment by lsuhov** [comment]
Hello @russellwheatley ,
How is that going to help if we upload DSYMs? Aren't those supposed to contain only symbols related to native ios code? Or is Flutter generating DSYM files also for the Dart code?

And yes, we do upload DSYM files from a long period but the only deobfuscation that we see is on native stacktraces, not Dart ones.
Thank you,
Lucian

**Comment by russellwheatley** [comment]
If you're only seeing de-obfuscated stack traces for native, then I don't think you have the correct configuration. It should de-obfuscate Dart code which might help with the grouping. I've recently made a fix on FlutterFire CLI for this specific issue: https://github.com/invertase/flutterfire_cli/pull/247

If you want to try out the dev version and get de-obfuscated Dart code, check this out: https://github.com/invertase/flutterfire_cli/issues/14#issuecomment-1862546146

**Comment by lsuhov** [comment]
Hello @russellwheatley ,
Thank you for the info. We will try out again in next weeks and will let you know.
