### ISSUE TITLE
[📚] setCurrentScreen method should be annotated as Deprecated

### ISSUE THREAD

**Issue by tsinis** [firebase/flutterfire#11035]
Hey Team!

Thanks for the great package! As per https://firebase.google.com/docs/analytics/screenviews and since https://github.com/firebase/flutterfire/pull/9397:
* `setCurrentScreen` method in the `FirebaseAnalytics` class should be annotated as `@Deprecated` to not confuse the developers.
* existing examples in `firebase_analytics/example/lib` should be updated with `logEvent()` method instead.
* FirebaseAnalyticsObserver should use `logEvent()` under the hood of the private _sendScreenView method.
* `FirebaseAnalytics`'s unit tests should be updated accordingly.

**Comment by tsinis** [comment]
@abhishek09827 you can always create a PR if you want, it's open-source :)

@darshankawar Actually [documentation](https://firebase.google.com/docs/analytics/screenviews#dart) is also wrong:
```dart
await FirebaseAnalytics.instance.logEvent(
  name: 'screen_view',
  parameters: {
    'firebase_screen': screenName, // <- Error 14
    'firebase_screen_class': screenClass, // <- Error 14
  },
);
```
Because it's forbidden to use parameter names with [_firebase](https://support.google.com/analytics/answer/13316687?hl=en#zippy=%2Cmobile-android-and-ios:~:text=Reserved%20parameter%20names,firebase_) prefix, events logged this way will show firebase_error with [value 14](https://firebase.google.com/docs/analytics/errors#:~:text=invalid%20event%20name.-,14,-Event%20parameter%20name) and reference to `firebase_screen`/`firebase_screen_class`. Proper parameter keys (at least for GA4) are `screen_name` and `screen_class` for use directly in the `logEvent` method. But in that case, it makes sense to use the [logScreenView](https://pub.dev/documentation/firebase_analytics/latest/firebase_analytics/FirebaseAnalytics/logScreenView.html) method instead...

**Comment by Alok1251** [comment]
await FirebaseAnalytics.instance.logEvent(
  name: 'screen_view',
  parameters: {
    'screen_name': screenName,
    'screen_class': screenClass,
  },
);

**Comment by tsinis** [comment]
> await FirebaseAnalytics.instance.logEvent( name: 'screen_view', parameters: { 'screen_name': screenName, 'screen_class': screenClass, }, );

[logScreenView](https://pub.dev/documentation/firebase_analytics/latest/firebase_analytics/FirebaseAnalytics/logScreenView.html) should be more relevant in this case.

**Comment by Alok1251** [comment]
yes ,
Using logScreenView simplifies the process by automatically setting the appropriate parameter keys for screen view events, saving you from manually specifying the parameters.
