### ISSUE TITLE
🐛 [firebase_app_check] Add support for getLimitedUseAppCheckToken

### ISSUE THREAD

**Issue by nohe427** [firebase/flutterfire#11031]
## Bug report

**Describe the bug**
There is currently no support for getLimitedUseAppCheckToken for replay protection in the firebase_app_check package

### Steps to reproduce

n/a

### Expected behavior

getLimitedUseAppCheckToken API is available

### SDK Locations

* [Android](https://firebase.google.com/docs/reference/kotlin/com/google/firebase/appcheck/FirebaseAppCheck#getLimitedUseAppCheckToken())
* [iOS](https://firebase.google.com/docs/reference/swift/firebaseappcheck/api/reference/Classes/AppCheck#limitedusetoken)
* [web](https://firebase.google.com/docs/reference/js/app-check.md#getlimitedusetoken)

**Comment by Ruisi-Lu** [comment]
firebase_app_check_platform_interface HttpsCallableOptions currently has no limitedUseAppCheckTokens 
[Cloud Functions for firebase Replay protection](https://firebase.google.com/docs/app-check/cloud-functions#replay-protection)
