### ISSUE TITLE
🐛 firebase_app_check:  Reason: Invalid appcheck token

### ISSUE THREAD

**Issue by Zaveri21** [firebase/flutterfire#11032]
## Bug report

**Describe the bug**
`[FirebaseDatabase][I-RDB034005] Firebase Database connection was forcefully killed by the server.  Will not attempt reconnect. Reason: Invalid appcheck token`

### Steps to reproduce
As per documentation all apple & Android platform required configuration done for app check integration and its working fine few days ago suddenly getting error in iOS platform Invalid appcheck token.**(force status mode)**
my TTL (token expire limit) 7 days.
also getting App check debug provider and also added in firebase console under respective platforms.

 release mode app its working fine but if tried with debug mode in simulator its not working but on physical device its working well on device (debug provider token added in console). 

if i change app check status **enforced** to **unforced** . I can able to read data from realtime database.  

<img width="972" alt="Screenshot 2023-05-23 at 11 11 27 PM" src="https://github.com/firebase/flutterfire/assets/69706520/283823bf-35b5-4dfe-9b18-d971c70fbbd7">

Tried solutions:
1. Solution 
  flutter  clean
  flutter cache clean 
  re-add app check package 
  flutter pub get 
  run app 
  
  2. carefully check all integration steps & documentation  (as mentioned above its working fine few days days ago)
  3. re-install app and generate new app check debug provider. 
  

</details>

---

**Comment by darshankawar** [comment]
Thanks for the report @Zaveri21 
Can you try [this](https://github.com/firebase/flutterfire/issues/6872#issuecomment-1270039805) and see if it helps in your case ?

**Comment by vishal-zaveri-us** [comment]
@darshankawar thanks for the help but yes its added in my `AppDelegate.swift` file still not validating simulator token which already added in firebase console and also one thing i notice that in physical device's request verified with (enforced) status without register that physical device's debug provider token its working fine .

**Comment by darshankawar** [comment]
Thanks for the update. Since the error is occuring only on simulator but not on physical device, I am not sure if this is a plugin issue or out of scope of the plugin. Keeping this open for team's input on reported behavior.

**Comment by russellwheatley** [comment]
If it works on a physical device but not on a simulator, this would be a limitation outside the scope of FlutterFire. With that said, I've just tested this on a simulator in debug mode using Xcode 15 + iPhone 15 simulator and it worked. Closing out.
