### ISSUE TITLE
🐛 [firebase_auth] Calling Apple Revoke Token endpoint

### ISSUE THREAD

**Issue by huangbolaw** [firebase/flutterfire#11065]
## Bug report

**Describe the bug**
Calling revoke token endpoint has been resolved in the firebase-ios-sdk:
https://github.com/firebase/firebase-ios-sdk/issues/9906#issuecomment-1538477802

A "feature" request was submitted:
https://github.com/firebase/flutterfire/discussions/10827

Respectfully, and apologies to be blunt, this should be a *top priority bug* rather than a *feature* request for flutter firebase_auth, because without this, making an iOS app using flutter is infeasible. Not supporting iOS for almost a year is unacceptable. I find no rationale to view this as something that is "nice to have".
https://developer.apple.com/news/?id=12m75xbj

### Steps to reproduce

1. Use firebase_auth to support signing in through AppleID
2. No way to call the revoke token end point within firebase_auth

### Expected behavior

FirebaseAuth.instance.currentUser!.revokeAppleToken() returns true and disconnect the Apple ID from the firebase app.

**Comment by huangbolaw** [comment]
For people out there, while waiting for this feature, consider using the sign_in_with_apple package (at https://pub.dev/packages/sign_in_with_apple), which works.

### Firebase Function
See the following re implementation of a firebase function which, if provided with the authorizationCode, would (1) obtain a refresh token using the authorization code and (2) then revoke the refresh token:
https://github.com/jooyoungho/apple-token-revoke-in-firebase
Ref: https://github.com/firebase/firebase-ios-sdk/issues/9906#issuecomment-1420143667

### Client Side
Once you have the firebase function up and running, you can do the following on the app (client side) to obtain authorization code using sign_in_with_apple and then call the function:

```
final AuthorizationCredentialAppleID credential =
   await SignInWithApple.getAppleIDCredential(
      scopes: [
         AppleIDAuthorizationScopes.email,
         AppleIDAuthorizationScopes.fullName,
     ],
   );

Map<String, String> payload = {'token': credential.authorizationCode};
HttpsCallable revokeToken = FirebaseFunctions.instance.httpsCallable("revokeToken");

try {
   revokeToken.call(payload);
} catch (exception, stack) {
   // Deal with errors
}
```

**Comment by ChiaraMC** [comment]
Hey @danagbemava-nc is it possible to know if this issue is actively being worked on (and if so, if there's an estimate of when it might be fixed) or if it's been put in a backlog?

**Comment by darshankawar** [comment]
Added android label based on https://github.com/firebase/flutterfire/issues/11396#issuecomment-1658337983

**Comment by ChiaraMC** [comment]
Thanks for this @russellwheatley ! Really appreciated
