### ISSUE TITLE
[firebase_messaging]: onMessage/onMessageOpenedApp functions not triggered with third party APNS notifications

### ISSUE THREAD

**Issue by Monojit12** [firebase/flutterfire#11064]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you aware of the differences between iOS and Android background message handling?

- [X] I understand that iOS and Android background messages behave differently, and I've designed my application with that in mind.

### Do you have an active Apple Developer account?

- [X] I have an active Apple Developer account.

### Are you using a physical iOS device to test background messages?

- [X] I am using a physical iOS device to test background messages.

### Have you enabled "Remote Notifications" & "Background Mode" (Checking options for "Background Processing" & "Remote Notifications") in your app's Xcode project?

<img width="652" alt="Screenshot 2023-05-31 at 14 37 21" src="https://github.com/firebase/flutterfire/assets/81352778/0264cf39-4dec-4c15-9140-6cf7b9b0d9d3">

### Have you created an APNs key in your Apple Developer account & uploaded this APNs key to your Firebase console?

Yes, we have uploaded the APNS certificate to the firebase console.

### Have you disabled method swizzling for Firebase in your app?

No we haven't disabled method swizzling

### Are you sending messages to your app from the Firebase Admin SDK?

yes

### Have you requested permission from the user to receive notifications?

- [X] I have the relevant permission to receive notifications.

### Have you used the 'Console' application on your macOS device to check if the iOS device's system is throttling your background messages?

yes

**Comment by danagbemava-nc** [comment]
Hi @Monojit12, please provide a complete minimal reproducible code sample so that we can investigate this. 

Please also provide the version of `firebase_messaging` & the iOS versions you're experiencing this issue on. Please also provide the output of `flutter doctor -v`. 

Thank you

**Comment by russellwheatley** [comment]
`firebase_messaging` isn't setup for receiving notifications from third party libraries. It is setup to receive notifications from any [one of these methods](https://firebase.google.com/docs/cloud-messaging/server). The recommended method is to use one of the admin SDKs.

> You'll need to decide on a way to interact with FCM servers: either using the [Firebase Admin SDK](https://firebase.google.com/docs/cloud-messaging/server#firebase-admin-sdk-for-fcm) or the raw protocols. Because of its support across popular programming languages and its convenience methods for handling authentication and authorization, the Firebase Admin SDK is the recommended method.
