### ISSUE TITLE
🐛 [Crashlytics] Build error links to internal Google login page for Google employees rather than Firebase console

### ISSUE THREAD

**Issue by wesleym** [firebase/flutterfire#11076]
## Bug report

When building an app for iOS that uses Crashlytics, build output says to visit `https://firebase.corp.google.com/`, a website that requires _____@google.com credentials.

### Steps to reproduce

Prerequisites: A Flutter project with Firebase imported and Crashlytics added.

1. `flutter build ipa --obfuscate --split-debug-info ./debug-info`

### Expected behavior

A message appears telling me to upload dSYMs and provides a link to do so.

### Actual behaviour

Such a message appears, but the link is broken.

```
    Running upload-symbols in Build Phase mode
    error: Flutter build with --obfuscate enabled. Crashlytics does not support
    uploading obfuscated dSYMs via the command line. Please upload dSYMs through
    the Firebase console web uploader at 
    https://firebase.corp.google.com/project/_/crashlytics
    Command PhaseScriptExecution failed with a nonzero exit code
```

The link https://firebase.corp.google.com/project/_/crashlytics redirects to https://login.corp.google.com/request?..., which asks me for an email address ending in "@google.com"

### Sample project

https://github.com/wesleym/corptest - basically an empty project with Firebase, Crashlytics

---

## Additional context

* A closely related issue was previously reported as https://github.com/firebase/flutterfire/issues/3795, but the response didn't specifically address that links to firebase.corp.google.com do not work for public users.
* https://github.com/firebase/flutterfire/issues/10994 has the same repro steps, and that bug also quotes the same build output with the same broken link.
* This document also refers to https://firebase.corp.google.com/: https://github.com/firebase/flutterfire/blob/81f1b80c445cfaab3e7752b8c58f35c92d234d8d/packages/firebase_performance/firebase_performance/example/README.md

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
➜  src flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.2, on macOS 13.2.1 22D68 darwin-arm64, locale
    en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.78.2)
[✓] Connected device (3 available)
    ! Error: (null) needs to connect to determine its availability. Check the
      connection between the device and its companion iPhone, and the connection
      between the iPhone and Xcode. Both devices may also need to be restarted
      and unlocked. (code 1)
[✓] Network resources

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
➜  corptest git:(main) flutter pub deps -- --style=compact
Dart SDK 3.0.2
Flutter SDK 3.10.2
corptest 1.0.0+1

dependencies:
- cupertino_icons 1.0.5
- firebase_crashlytics 3.3.2 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- flutter 0.0.0 [characters collection js material_color_utilities meta vector_math sky_engine]

dev dependencies:
- flutter_lints 2.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection js matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- _flutterfire_internals 1.3.2 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- collection 1.17.1
- fake_async 1.3.1 [clock collection]
- firebase_core 2.13.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_core_platform_interface 4.8.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.5.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.6.2 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- js 0.6.7 [meta]
- lints 2.1.0
- matcher 0.12.15 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.2.0
- meta 1.9.1
- path 1.8.3
- plugin_platform_interface 2.1.4 [meta]
- sky_engine 0.0.99
- source_span 1.9.1 [collection path term_glyph]
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.5.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- vector_math 2.1.4
```

</details>

---

**Comment by russellwheatley** [comment]
That log is not produced by FlutterFire, but by the firebase iOS SDK. More specifically, it is created by the `FirebaseCrashlytics/upload-symbols` script. Please file an issue on that repository here if you wish to get it fixed: https://github.com/firebase/firebase-ios-sdk

If you want to manually upload symbols, you just have to open Crashlytics in the Firebase console and upload them here:
<img width="1341" alt="Screenshot 2023-12-15 at 10 44 29" src="https://github.com/firebase/flutterfire/assets/16018629/d7fe7273-ec4c-4588-b189-f6e3937117f3">
