### ISSUE TITLE
🐛 [cloud_firestore] Documents not removed from query snapshot after update (always hasPendingWrites to true)

### ISSUE THREAD

**Issue by serbixote** [firebase/flutterfire#11078]
### Case 1
I'm listening real time changes on a query that gets documents with type field set to A, when I update one of the documents from this query by setting the type to B, the document should disappear from the snapshot documents, however, the document stays in the snapshot docs "hanging" with only the field that has been updated, and nothing more.

I can see in the console that the update has been performed properly, however:
- the document does not get removed from the snapshot documents
- the document that stays hanging locally it only contains the modified fields
- the listener is triggered only once after the update, with hasPendingWrites set to true, and that's that

### Case 2

I can experience a similar issue by listening changes of a single document if I perform a similar update:

- the firs time the listener is triggered the snapshot has hasPendingWrites set to true
- it also contains only the modified data, so the document has missing data
- the main difference with this case is that after the first snapshot, the next one gets updated, but of course, there there's a fraction of time that the document has missing data

It is also worth mention that I only have those problem when I modify and delete fields in the same update, but I cant find any restriction about this on the documentation.

### Expected behavior in Case 1

The document should be removed from the snapshot documents, and don't stay hanging. 

---

### Expected behavior in Case 1

I expect the snapshot document to not have missing fields when I update it.

---

## Additional context

My guess is that performs the change locally, then to firestore, but since the document does not belong anymore to the query results, the write in firestore does not get acknowledged by the client, so it does not get removed locally.

I'm experiencing this in an iOS device and emulator.

**Comment by marco2704** [comment]
I can workaround this by deleting a single field by update:

```dart
final firstUpdate = <String, dynamic>{
  "firstField": FieldValue.delete(),
};

firestore
  .collection(usersCollection)
  .doc("myDocument")
  .update(firstUpdate);

// then
final secondUpdate = <String, dynamic>{
  "secondField": FieldValue.delete(),
};

firestore
  .collection(usersCollection)
  .doc("myDocument")
  .update(secondUpdate);
```

However the delete field actions also does not work offline, is this expected??

**Comment by danagbemava-nc** [comment]
Hi @marco2704, please provide a complete minimal reproducible sample project so that we can investigate this. Please also provide the version of `cloud_firestore` that you're using. 

Please also provide the output of flutter doctor -v. 

Thank you
