### ISSUE TITLE
🐛 [cloud_firestore] IN and array_contains_any should allow 30 values

### ISSUE THREAD

**Issue by puf** [firebase/flutterfire#11085]
## Bug report

With the introduction of OR clauses, Firestore queries can now contain up to 30 disjunctions in the query normal form. This also means that the maximum number of values in an IN clause or array-contains-any clause is now 30. The Flutter SDK still seems to limit this to 10 here: https://github.com/firebase/flutterfire/blob/81f1b80c445cfaab3e7752b8c58f35c92d234d8d/packages/cloud_firestore/cloud_firestore/lib/src/query.dart#L734

**Comment by russellwheatley** [comment]
Hey @puf, I had a play with this. I found that you could have [30 disjunctive queries](https://github.com/firebase/flutterfire/pull/11140/files#diff-24d88bfbf516869914dafeb46b907a3384e1dd9e4622ab0e23b8aaeac105108cR2096-R2147) when using `Filter` API, but it isn't possible using the `array-contains-any` or `where-in` or `where-not-in` which [still only allow 10](https://github.com/firebase/flutterfire/pull/11140/files#diff-24d88bfbf516869914dafeb46b907a3384e1dd9e4622ab0e23b8aaeac105108cR2149-R2344) (I removed the 10 limit locally but received an error from the Firebase server when testing on android and iOS).

**Comment by puf** [comment]
Thanks for testing, Russel!
Hmm... I really thought this should work now based on the documentation.
I'm gonna ask around...

**Comment by russellwheatley** [comment]
I've created a PR to reinsert the commented out e2e tests and to increase the filters allowed for "in" & "array-contains-any" as they now appear to successfully complete. Not sure if it was something in my testing or response from the Firebase server but at least it works now ⚡
