### ISSUE TITLE
Refactor FlutterFire web implementation by removing `is` checks on web instances.

### ISSUE THREAD

**Issue by russellwheatley** [firebase/flutterfire#11099]
As per the recommendation by the Flutter SDK team, we need to remove all `is` checks on web instances and use `@staticInterop` in the interop layer.

## Example 

update this:
```dart
  if (exception is core_interop.FirebaseError) {
    return _firebaseExceptionFromCoreFirebaseError(
      exception,
      plugin: plugin,
      codeParser: codeParser,
      messageParser: messageParser,
    );
  }
```

To this:
```dart
  if (js_util.instanceof(exception, core_interop.FirebaseError)) {
    return _firebaseExceptionFromCoreFirebaseError(
      exception,
      plugin: plugin,
      codeParser: codeParser,
      messageParser: messageParser,
    );
  }
```
This would also require changing `core_interop.FirebaseError` to a `@staticInterop`.

### To Update
- [ ] Await this issue to be resolved first: https://github.com/dart-lang/sdk/issues/52572
- [ ] Refactor the above noted.
- [ ] Remove the test skips on web for Firestore here: https://github.com/firebase/flutterfire/pull/11092/files

**Comment by sigmundch** [comment]
Note that the `instanceof` call takes as an argument a constructor, but Dart doesn't give you that when you refer to the dart class. So likely it is not:
```
 if (js_util.instanceof(exception, core_interop.FirebaseError)) {
    return _firebaseExceptionFromCoreFirebaseError(
      exception,
      plugin: plugin,
      codeParser: codeParser,
      messageParser: messageParser,
    );
  }
```

but more something like:
```
 if (js_util.instanceof(exception, core_interop.firebaseErrorJSConstructor)) {
    return _firebaseExceptionFromCoreFirebaseError(
      exception,
      plugin: plugin,
      codeParser: codeParser,
      messageParser: messageParser,
    );
  }
```

where `firebaseErrorJSConstructor` is a getter that returns the JavaScript `FirebaseError` type.

**Comment by russellwheatley** [comment]
Closing out as we have now implemented the latest `js_interop`
