### ISSUE TITLE
🐛 [firebase-auth] Unhandled Exception: [core/no-app] No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()

### ISSUE THREAD

**Issue by kimcumjee** [firebase/flutterfire#11097]
## Bug report

I am developing a mobile app using flutter. However, when I run the app, I get an error saying "Unhandled Exception: [core/no-app] No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()" The condition of this error occurs only when the app is deployed as aab or when the app is deployed as testflight. If you build with Android Studio, it doesn't happen at all. And it only happens when I distribute it on my PC, but it doesn't happen when I distribute it on my colleague's PC. Of course, I'm doing Firebase.initializeApp().

**Comment by kimcumjee** [comment]
I've already checked everything you said. I thought my local repository setting might be a problem, so I received the project file from a PC from a colleague who was working normally and distributed it, but the same error occurred.

**Comment by darshankawar** [comment]
@kimcumjee 
Can you provide how are you configuring / initializing firebase app ? A minimal code sample would be helpful.
Also try by `flutterfire update` and then`flutterfire configure` to reconfigure with your existing firebase app to see if it helps or not.

**Comment by kimcumjee** [comment]
`WidgetsBinding widgetsBinding = WidgetsFlutterBinding.ensureInitialized();

      FlutterNativeSplash.preserve(widgetsBinding: widgetsBinding);

      if (PlatformInfo.isAndroid) {
        await AndroidInAppWebViewController.setWebContentsDebuggingEnabled(true);
      }

      const String env = String.fromEnvironment('ENV');

      // 빌드 옵션으로 추가한 env 파일을 로드한다.
      await dotenv.load(fileName: 'assets/env/$env.env');

      FlutterError.onError = (errorDetails) {
        FirebaseCrashlytics.instance.recordFlutterError(errorDetails);
      };

      PlatformDispatcher.instance.onError = (error, stack) {
        // If you wish to record a "non-fatal" exception, please remove the "fatal" parameter
        FirebaseCrashlytics.instance.recordError(error, stack, fatal: true);
        return true;
      };

      // 유저 agent를 가져오는 library init
      await FkUserAgent.init();

      // Firebase Core Init
      await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);`

      After all of this, runApp is called. And I tried flutterfire update and flutterfire configure beforehand, but still get errors.

**Comment by kimcumjee** [comment]
After all of this, runApp is called. And I tried flutterfire update and flutterfire configure beforehand, but still get errors.

**Comment by darshankawar** [comment]
@kimcumjee 
Check the firebase_auth plugin example and how it is using the initializeApp() method and check if it helps in your case.

https://github.com/firebase/flutterfire/blob/67b051fda24d4e7f50023a24001bdc6b0cc7f7bf/packages/firebase_auth/firebase_auth/example/lib/main.dart#L22

**Comment by kimcumjee** [comment]
[GoogleAccountDataServiceImpl] GetToken() -> BAD_AUTHENTICATION. Is it related?

**Comment by atleugim** [comment]
This happened to me using the flutterfire plugin, the solution was to delete the `google-services.json` and the `GoogleService-Info.plist` and re-run the `flutterfire configure` command, so that it would update the files to the corresponding project.

**Comment by kimcumjee** [comment]
This method didn't help me 😢

**Comment by albinrk10** [comment]
![image](https://github.com/firebase/flutterfire/assets/79820950/b17f40b2-1684-4633-a706-dff33b69a4e4)
error : E/flutter (  730): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(null-error, Host platform returned null value for non-null return value., null, null)

**Comment by followthemoney1** [comment]
same happened for me with different flavors implementation

**Comment by iptodays** [comment]
Try this
android>build.gradle
```
dependencies {
         classpath 'com.android.tools.build:gradle:7.3.1'
         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
         classpath 'com.google.gms:google-services:4.3.15'
         classpath 'io.fabric.tools:gradle:1.28.0'
     }
```

**Comment by russellwheatley** [comment]
Move this line:

```
// Firebase Core Init
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
```

to just after:
```
WidgetsFlutterBinding.ensureInitialized();
```

Ensure your `google-services.json` is located here: `android/app/google-services.json`. It is picked up by the firebase android sdk.

**Comment by kroyoda** [comment]
Hello there, I managed to fix this issue by moving down references to the FirebaseAuth object to my custom FirebaseService and also by removing the `name` parameter in the `initializeApp()` options. If it helps:

```dart
const String name = 'Blinst!';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  late final FirebaseApp app;
  late final FirebaseAuth auth;
  late final FirebaseFirestore store;

  app = await Firebase.initializeApp(
    name: name, // <- Get rid of this
    options: DefaultFirebaseOptions.currentPlatform,
  );
}
```
