### ISSUE TITLE
🐛 [cloud_firestore_odm] FirestoreBuilder ref parameter type

### ISSUE THREAD

**Issue by esperaking81** [firebase/flutterfire#11126]
Hello everyone.

I have FirestoreBuilder used in a widget and suddenly after updating dependencies, I get this error with the ref parameter.

`The argument type 'DocumentRefence<User>' can't be assigned to the parameter type FirestoreListenable<UserDocumentSnapshot> `

I am following what's exactly on the documentation.

**Comment by esperaking81** [comment]
[✓] Flutter (Channel stable, 3.10.3, on macOS 13.0 22A380 darwin-arm64, locale en-BJ)
    • Flutter version 3.10.3 on channel stable at /Users/espera/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f92f44110e (12 days ago), 2023-06-01 18:17:33 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/espera/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/espera/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/espera/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/espera/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 8ECC3D78-F462-4CDA-AACE-2056DC43EBB8 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.0
      22A380 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome
      114.0.5735.106

[✓] Network resources
    • All expected network resources are available.

• No issues found!

---- Code sample ----
```
import 'package:stacked/stacked.dart';
import 'package:flutter/material.dart';
import 'package:korys_shared/shelf.dart';

FirestoreBuilder<UserDocumentSnapshot>(
      ref: usersRef.doc(id),
      builder: (
        BuildContext context,
        AsyncSnapshot<UserDocumentSnapshot> snapshot,
        Widget? child,
      ) { ... }
```

**Comment by darshankawar** [comment]
@esperaking81 
Please provide us [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without any third party package implementation that we can directly copy paste and run to verify the reported behavior.

Also, as the error indicates a mismatch while trying to parse:

`The argument type 'DocumentRefence<User>' can't be assigned to the parameter type FirestoreListenable<UserDocumentSnapshot>`

Check if you are correctly using the argument type and expected parameter type.
