### ISSUE TITLE
🐛 [firebase_dynamic_link] Dynamic link broke Safari on IOS when link contains unicode 

### ISSUE THREAD

**Issue by nerder** [firebase/flutterfire#11122]
## Bug report

**Describe the bug**
As in the title, when the `link` contains a unicode character such as `ó` the link will break Safari and not open correctly.

### Steps to reproduce

1. Open this link in the IOS Simulator https://arya.page.link/qV5g
2. See the error message in Safari: `Safari cannot open the page because the address is invalid`

### Expected behavior

To open the app correctly and fire the flutter integration as usual.

### Sample project

_This is not needed as I'm pretty confident that you will be able to reproduce this in the example app._

---

## Additional context

You can try with a valid link such as this one: https://arya.page.link/6XZ5 and you can confirm that is indeed working as expected.

Also, this is the  code used for generating the link in our backend:

```ts
const getParameters = (gymId: string) => {
  return {
    dynamicLinkInfo: {
      domainUriPrefix: `https://${process.env.DYNAMIC_LINK_DOMAIN}`,
      link: `https://www.getstriveapp.com/register/${gymId}`, //gmyId can contain unicode
      androidInfo: {
        androidPackageName: process.env.APP_UNIQUE_IDENTIFIER,
      },
      iosInfo: {
        iosBundleId: process.env.APP_UNIQUE_IDENTIFIER,
        iosAppStoreId: process.env.APPLE_STORE_ID,
      },
      navigationInfo: {
        enableForcedRedirect: true,
      },
    },
    suffix: {
      option: 'SHORT',
    },
  };
};

const generateReferralUrl = async (gymId: string) => {
  const response = await fetch(
    `https://firebasedynamiclinks.googleapis.com/v1/shortLinks?key=${process.env.WEB_FIREBASE_API_KEY}`,
    {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
      },
      body: JSON.stringify(getParameters(gymId)),
    },
  );

  const jsonResponse = await response.json();

  const referralUrl = jsonResponse.shortLink;
  console.info(`generated referral link [${referralUrl}] for gym [${gymId}]`);

  return referralUrl;
};
````

## Notes

I'm not sure if this is actually the right place to report this as it might as well be an issue with Safari since on Android the dynamic link works fine for the most part.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.10.4, on macOS 13.3.1 22E772610a darwin-arm64, locale en-IT)
    • Flutter version 3.10.4 on channel stable at /Users/nerder/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 682aa387cf (7 days ago), 2023-06-05 18:04:56 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nerder/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nerder/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.10121639/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/nerder/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.10121639/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/nerder/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
    • IntelliJ at /Users/nerder/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 74.0.4
    • Dart plugin version 231.9065

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
    • IntelliJ at /Users/nerder/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9011.34/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.1)
    • IntelliJ at /Users/nerder/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.8770.65/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • SM G975F (mobile)          • R58M67B0S3Y                          • android-arm64 • Android 12 (API 31)
    • iPhone 14 Pro Max (mobile) • FB142510-43C2-45EC-BFF4-150B6E17F611 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64  • macOS 13.3.1 22E772610a darwin-arm64

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the report @nerder 
I accessed the link on iOS simulator in which I get the said behavior, but accessing it on physical device took me properly to app store, so that probably indicates it is not a plugin issue but could be specific to simulators as they don't have AppStore app and the link must be trying to find one and hence the error as address is invalid.

See if it helps to answer / resolve your issue.

**Comment by nerder** [comment]
Hey @darshankawar thank you for your fast reply, the problem is that when I have the app installed it should open it, not try to open the App Store. 

 can send you a quick video when the first link correctly opens the app in the simulator and the other return that error.
 
 The expected behavior should be to open both links in the app to be handled properly.

**Comment by nerder** [comment]
Actually, after some extensive testing, it seems like the link doesn't even trigger the flutter code to be executed as it fails directly in the native code and spawns this error in the console:

`FLTFirebaseDynamicLinks: The URL has not been supplied with the dynamic link. Please try opening your app with the long dynamic link to see if that works`

https://github.com/firebase/flutterfire/blob/52d920a5ed7e06cbbf9105a20eefc56824475f27/packages/firebase_dynamic_links/firebase_dynamic_links/ios/Classes/FLTFirebaseDynamicLinksPlugin.m#L311

I'm not sure how to debug this further in the native implementation.

Here are the 2 links when expanded:

1. https://arya.page.link/?link=https://www.getstriveapp.com/register/new_test&apn=com.arya.checkin.dev&isi=1471462737&ibi=com.arya.checkin.dev&efr=1
2. https://arya.page.link/?link=https://www.getstriveapp.com/register/matar%C3%B3_jiujitsu&apn=com.arya.checkin.dev&isi=1471462737&ibi=com.arya.checkin.dev&efr=1

They are configured exactly in the same way the only differences are those special characters encoded in browser code that I suspect are breaking something.

**Comment by darshankawar** [comment]
Thanks for the update and digging deep. Can you take a look at [this](https://github.com/firebase/flutterfire/issues/9110#issuecomment-1201156205) and see if using it in your scenario, still gives you same behavior or not ?

**Comment by darshankawar** [comment]
Sorry if it wasn't clear earlier, but I wanted to see if you follow the steps mentioned in that link with respect to your app, run in release mode, generate the dynamic link to see if the same issue persists or not.

**Comment by nerder** [comment]
Up. I'll be providing more information between today and tomorrow. I was quite busy with a big release for my app.

**Comment by nerder** [comment]
hey @darshankawar, I don't have a real IOS device handy to do that test. But I'm pretty positive this is happening because it's happening with our app in production.

**Comment by darshankawar** [comment]
Thanks for the update. Can you take a look at [this](https://stackoverflow.com/questions/68767276/when-the-dynamic-link-is-opened-from-browserespecially-in-safari-it-is-always) and see if it helps in your case ?

**Comment by darshankawar** [comment]
Thanks for the update. I do see the same behavior as reported using the links provided. I think there was already an issue or I read something about having unicode in dynamic links but can't seem to find any reference of it.

/cc @russellwheatley

**Comment by nerder** [comment]
There is an ETA for this?

**Comment by russellwheatley** [comment]
Hi folks, we'd like to inform you that the Firebase Dynamic Links service will be shutdown on August 25, 2025. In the meantime, only critical or security issues will be fixed in the SDK.

More at [firebase.google.com/support/dynamic-links-faq](https://firebase.google.com/support/dynamic-links-faq)
