### ISSUE TITLE
🐛 firebase-analytics-ktx - Adding Firebase Analytics dependency to fresh project causes immediate crash.

### ISSUE THREAD

**Issue by protonforest** [firebase/flutterfire#11134]
## Bug report

**Describe the bug**
The app loads up on an android emulator for a second and immediately crashes.

### Steps to reproduce

1. Create a new flutter app. Create a new firebase project and follow the prompts and add the necessary build.gradle changes.
``` 
implementation platform('com.google.firebase:firebase-bom:32.1.0')
implementation 'com.google.firebase:firebase-analytics-ktx'
```
I also changed the minSdkVersion `minSdkVersion 19`. 

2. Run the app on an android emulator. 
3. App self terminates.

### Expected behavior

I expect it to not crash. 

---

## Additional context

Tried on Pixel 6 API 34, as well as Pixel 3a API 34/ 

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.4, on macOS 13.4 22F66 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.79.1)
[✓] Connected device (4 available)
[✓] Network resources
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 3.0.3
Flutter SDK 3.10.4
testapp 1.0.0+1

dependencies:
- cupertino_icons 1.0.5
- flutter 0.0.0 [characters collection js material_color_utilities meta vector_math sky_engine]

dev dependencies:
- flutter_lints 2.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection js matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- collection 1.17.1
- fake_async 1.3.1 [clock collection]
- js 0.6.7 [meta]
- lints 2.1.1
- matcher 0.12.15 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.2.0
- meta 1.9.1
- path 1.8.3
- sky_engine 0.0.99
- source_span 1.9.1 [collection path term_glyph]
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.5.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- vector_math 2.1.4
```

</details>

---

**Comment by darshankawar** [comment]
@protonforest Thanks for the report.



> implementation platform('com.google.firebase:firebase-bom:32.1.0')
> implementation 'com.google.firebase:firebase-analytics-ktx'

These don't seem to be required / mandatory for Flutter, as I don't see in the [documentation](https://firebase.google.com/docs/analytics/get-started?platform=flutter). For Android, it seems to be required. You can check the documentation for flutter and also the [plugin example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_analytics/firebase_analytics/example) wherein, these are not used.

Curious to know the reason behind you are adding those in your project ?

**Comment by protonforest** [comment]
@darshankawar It seems that you are suggesting the instructions are sharing via that link are explicit to Flutter, and that I should not use the android setup sdk instructions. I will try following those instructions instead. 

What is confusing is that I was following another tutorial and they added these dependencies exactly this way when they added the firebase dependencies to their flutter project, albeit it is an older tutorial.

**Comment by darshankawar** [comment]
Thanks for the update and feedback @protonforest 
If you want to create a Firebase app and integrate with Flutter, you can do so using `flutterfire configure` CLI tool which writes the native config files to respective platform folders so you don't need to go through Firebase console and UI to create one.
That way once you create and integrate the project, you can take a look if the parameters in question are being used or not.

You can read more about the CLI tool here if you haven't done so already: https://firebase.google.com/docs/flutter/setup?platform=ios

**Comment by protonforest** [comment]
@darshankawar I followed the tutorial you suggested and got it working. Since I'm adding those dependencies to the Flutter `pubspec.yaml` file, and checking both the `build.gradle` files, I see the above-mentioned dependencies are not necessary. I think having the Firebase console recommend adding those dependencies to get it working with an android app only for it to break is problematic. How and maybe where should I recommend making a change ?

**Comment by protonforest** [comment]
So I tried using the tool, and it did not update my build.gradle files. I expected to see a gradle plugin or something firebase related and I didnt. It seems my issue is the same as [this one.](https://github.com/invertase/flutterfire_cli/issues/126) . 

I get this error when I run the flutter app on an android emulator. I'm assuming its because the necessary dependencies werent added by flutterfire. 

```E/FA      ( 5429): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI```

**Comment by darshankawar** [comment]
> E/FA ( 5429): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI

See [this](https://github.com/firebase/flutterfire/issues/10399) and underlying comments and check if they help in your case.

**Comment by Fernandomr88** [comment]
i had to completely remove analytics from my app to stop it from crashing on android startup.

```
Fatal Exception: java.lang.ExceptionInInitializerError:
       at com.google.android.gms.measurement.internal.zzik.<init>(zzik.java:34)
       at com.google.android.gms.measurement.internal.zzgd.<init>(zzgd.java:183)
       at com.google.android.gms.measurement.internal.zzgd.zzp(zzgd.java:58)
       at com.google.android.gms.measurement.internal.AppMeasurementDynamiteService.initialize(AppMeasurementDynamiteService.java:17)
       at com.google.android.gms.internal.measurement.zzcx.zza(zzcx.java:108)
       at com.google.android.gms.internal.measurement.zzdu.run(zzdu.java:12)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

**Comment by Fernandomr88** [comment]
any updates?

**Comment by amasry** [comment]
This same issue is happening to me as well on different devices and only on release version

**Comment by protonforest** [comment]
> Hey @protonforest. We need more information to resolve this issue but there hasn't been an update in 7 weekdays. I'm marking the issue as stale and if there are no new updates in the next 7 days I will close it automatically.
> 
> If you have more information that will help us get to the bottom of this, just add a comment!

Can you be more specific ? What are you looking for? Theres 2 issues here. The Google Firebase portal setup crashes a new Flutter app.  Also, the suggested tool to fix the `build.gradle` files is broken, as suggested in the referenced link.

**Comment by darshankawar** [comment]
@protonforest 
Does removing `-ktx` help ?

**Comment by Fernandomr88** [comment]
> @protonforest Does removing `-ktx` help ?

No

**Comment by Fernandomr88** [comment]
a temporary solution in my case was adding `-keep class com.google.** { *; }` to the end of my proguard rules file.
