### ISSUE TITLE
cloud_firestore: ^4.8.1 (domain=NSPOSIXErrorDomain, code=3)

### ISSUE THREAD

**Issue by yarmel** [firebase/flutterfire#11138]
After updating the cloud_firestore package to the latest version (^4.8.1), my app crashed every time after the build. Occurred on real devices and iOS simulators.

It seems that this problem belongs to firestore persistent settings. 
I can only build and run my App if the persistent settings are completely commented out.

```
// db.settings = const Settings(persistenceEnabled: true);
```

**Comment by russellwheatley** [comment]
Thanks for the update, I was able to recreate this and will get a fix out 👍

**Comment by akulubala** [comment]
same issue here, any solution now?:

`An error occurred while parsing query arguments, this is most likely an error with this SDK. (
	0   CoreFoundation                      0x00007ff8004288ab __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff80004dba3 objc_exception_throw + 48
	2   CoreFoundation                      0x00007ff800437ab8 +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0
	3   CoreFoundation                      0x00007ff80042cd71 ___forwarding___ + 1431
	4   CoreFoundation                      0x00007ff80042f068 _CF_forwarding_prep_0 + 120
	5   Runner                              0x000000010f5eadfe -[FLTFirebaseFirestoreReader FIRFirestoreSettings] + 334
	6   Runner                              0x000000010f5eaabd -[FLTFirebaseFirestoreReader readValueOfType:] + 1517
	7   Runner                              0x000000010f5ed5e4 -[FLTFirebaseFirestoreReader FIRFirestore] + 116
	8   Runner                              0x000000010f5eaa79 -[FLTFirebaseFirestoreReader readValueOfType:] + 1449
	9   Flutter                             0x000000011d3b8460 -[FlutterStandardReader readVal
Lost connection to device.`
