### ISSUE TITLE
flutter run firebase_message has problem

### ISSUE THREAD

**Issue by zetaoliu** [firebase/flutterfire#11147]
## Bug report
flutter run 

**Describe the bug**
```
C:\Users\ccb\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\device_info-2.0.3\android\src\main\java\io\flutter\plugins\deviceinfo\DeviceInfoPlugin.java:49: ����: [unchecked] ����Ϊԭʼ����Class�ĳ�Ա��getConstructor(Class<?>...)�ĵ���δ�������
          methodChannelClass.getConstructor(
                                           ^
  ����, T�����ͱ���:
    T��չ������ Class��������Object
C:\Users\ccb\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\device_info-2.0.3\android\src\main\java\io\flutter\plugins\deviceinfo\DeviceInfoPlugin.java:49: ����: [unchecked] δ������ת��
          methodChannelClass.getConstructor(
                                           ^
  ��Ҫ: Constructor<MethodChannel>
  �ҵ�:    Constructor
2 ������
C:\Users\ccb\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\firebase_messaging-14.6.3\android\src\main\java\io\flutter\plugins\firebase\messaging\JobIntentService.java:18: ����: [deprecation] android.os�е�AsyncTask�ѹ�ʱ
import android.os.AsyncTask;
                 ^
C:\Users\ccb\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\firebase_messaging-14.6.3\android\src\main\java\io\flutter\plugins\firebase\messaging\FlutterFirebaseMessagingPlugin.java:21: ����: [deprecation] androidx.localbroadcastmanager.content�е�LocalBroadcastManager�ѹ�ʱ
import androidx.localbroadcastmanager.content.LocalBroadcastManager;
                                             ^
C:\Users\ccb\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\firebase_messaging-14.6.3\android\src\main\java\io\flutter\plugins\firebase\messaging\FlutterFirebaseMessagingReceiver.java:11: ����: [deprecation] androidx.localbroadcastmanager.content�е�LocalBroadcastManager�ѹ�ʱ
import androidx.localbroadcastmanager.content.LocalBroadcastManager;
                                             ^
C:\Users\ccb\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\firebase_messaging-14.6.3\android\src\main\java\io\flutter\plugins\firebase\messaging\FlutterFirebaseMessagingService.java:9: ����: [deprecation] androidx.localbroadcastmanager.content�е�LocalBroadcastManager�ѹ�ʱ
import androidx.localbroadcastmanager.content.LocalBroadcastManager;
                                             ^
C:\Users\ccb\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\firebase_messaging-14.6.3\android\src\main\java\io\flutter\plugins\firebase\messaging\FlutterFirebaseMessagingBackgroundExecutor.java:238: ����: [deprecation] Intent�е�<T>getParcelableExtra(String)�ѹ�ʱ
```

### Steps to reproduce

 1. flutter pub get
  firebase_core: ^2.14.0
  firebase_analytics: ^10.4.1
  firebase_messaging: ^14.6.3
  firebase_crashlytics: ^3.3.1
 2. flutter run

## Additional context

firebase_message is not receive info

---

### Flutter doctor

Run `flutter doctor` and paste the output below:
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[√] Flutter (Channel master, 3.12.0-4.0.pre.110, on Active code page: 65001

Microsoft Windows [版本 10.0.22621.1848], locale zh-CN)
    • Flutter version 3.12.0-4.0.pre.110 on channel master at D:\flutter_src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c29b570678 (3 hours ago), 2023-06-16 20:07:25 -0400
    • Engine revision 7ffa1355f7
    • Dart version 3.1.0 (build 3.1.0-213.0.dev)
    • DevTools version 2.24.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\ccb\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = C:\Users\ccb\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.5.2)
    • Visual Studio at d:\Program Files\Microsoft Visual Studio\2022\Professional
    • Visual Studio Professional 2022 version 17.5.33502.453
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] Connected device (4 available)
    • RMX2025 (mobile)  • 6776fa1c • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows  • windows-x64    • Active code page: 65001

      Microsoft Windows [版本 10.0.22621.1848]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 114.0.5735.134
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 113.0.1774.57

[!] Network resources
    X A network error occurred while checking "https://github.com/": 信号灯超时时间已到

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

Dart SDK 3.1.0-213.0.dev
Flutter SDK 3.12.0-4.0.pre.110
ben.app 1.0.0

dependencies:
- adjust_sdk 4.33.1 [flutter meta]
- device_info 2.0.3 [flutter device_info_platform_interface]
- firebase_analytics 10.4.3 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 2.14.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 3.3.3 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_messaging 14.6.3 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math web sky_engine]
- http 1.0.0 [async http_parser meta]
- package_info 2.0.2 [flutter]
- sprintf 7.0.0
- webview_flutter 4.2.2 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]
- webview_jsbridge 1.0.3 [flutter]

dev dependencies:
- flutter_lints 2.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math async boolean_selector characters collection material_color_utilities meta source_span stream_channel string_scanner term_glyph web]

transitive dependencies:
- _flutterfire_internals 1.3.3 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- collection 1.17.2
- device_info_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- fake_async 1.3.1 [clock collection]
- firebase_analytics_platform_interface 3.6.3 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.4+3 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_core_platform_interface 4.8.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.6.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.6.3 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.5.3 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.5.3 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math web]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- js 0.6.7 [meta]
- lints 2.1.1
- matcher 0.12.16 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.5.0 [collection]
- meta 1.9.1
- path 1.8.3
- plugin_platform_interface 2.1.4 [meta]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.6.0 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- typed_data 1.3.2 [collection]
- vector_math 2.1.4
- web 0.1.4-beta
- webview_flutter_android 3.8.0 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 2.3.1 [flutter meta plugin_platform_interface]
- webview_flutter_wkwebview 3.5.0 [flutter path webview_flutter_platform_interface]
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by darshankawar** [comment]
@zetaoliu 
Some of the logs seems to be pointing to `device_info` which is third party package. If you create a new Flutter project, add only flutterfire plugins as you listed and try to run, do you get same log ?
