### ISSUE TITLE
🐛 [firebase_remote_config] Firebase Remote Config Fails on WiFi network in Flutter

### ISSUE THREAD

**Issue by tirth-multipl** [firebase/flutterfire#11154]
## Bug report

Firebase Remote Config keeps throwing this error when mobile device is connected to my home WiFi network. Because of that data of Firebase Remote Config is not loaded in the app.

```
[log] [firebase_remote_config/internal] internal remote config fetch error
       #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
       #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
       <asynchronous suspension>
       #2      MethodChannelFirebaseRemoteConfig.fetchAndActivate (package:firebase_remote_config_platform_interface/src/method_channel/method_channel_firebase_remote_config.dart:150:29)
       <asynchronous suspension>
       #3      FirebaseRemoteConfig.fetchAndActivate (package:firebase_remote_config/src/firebase_remote_config.dart:90:26)
       <asynchronous suspension>
       #4      setupRemoteConfigSettings (package:multiplapp/main.dart:77:5)
       <asynchronous suspension>
       #5      main (package:app_name/main.dart:28:3)
       <asynchronous suspension>
```

It works fine when mobile is connected to mobile data. I don't seem to understand what could be the issue.

Any help would be appreciated! Tried looking for similar issues on GitHub and stackoverflow but couldn't find one.

I filed one SO question too - https://stackoverflow.com/questions/76507037/firebase-remote-config-fails-on-wifi-network-in-flutter

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4 22F66 darwin-arm64, locale
    en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[!] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.79.2)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @tirth-multipl 
Is that the only error log you get ? Do you get more logs with `Error Domain=NSURLErrorDomain Code` ? 
A relatively similar issue was fixed recently that you can take a look https://github.com/firebase/flutterfire/issues/6196



> It works fine when mobile is connected to mobile data. I don't seem to understand what could be the issue.

You can also reach out to Firebase support in this case. The plugin code doesn't differentiate between mobile data and wifi data, so if it works with mobile data, then it probably may not be causing due to plugin code.
