### ISSUE TITLE
🐛 [firebase_ui_auth] Enabling Google provider from profile doesn't work on web

### ISSUE THREAD

**Issue by graemep-nz** [firebase/flutterfire#11156]
I posted a bug report here
https://github.com/firebase/flutterfire/issues/11148
which Andrei Lesnitsky has unreasonably closed and locked the conversation on.
Lesnitsky initially claimed that the bug report was invalid and when I questioned it he said that he couldn't reproduce it.  You have no business closing a bug report as invalid without saying you couldn't reproduce it.  The main bugs are in the second post of that thread
https://github.com/firebase/flutterfire/issues/11148#issuecomment-1595677492
and all of these are 100% reproducible and valid.
@lesnitsky 
@Ehesp 
@darshankawar

**Comment by darshankawar** [comment]
Based on the replication details mentioned in https://github.com/firebase/flutterfire/issues/11148#issuecomment-1595677492, I tried the same using plugin example, but have been getting `an unknown error occured` while trying to enable google sign-in from `Enable more sign-in method` section:

<img width="191" alt="Screenshot 2023-06-20 at 4 12 23 PM" src="https://github.com/firebase/flutterfire/assets/67046386/8ed3d3f9-ee4f-418b-807e-8536b6176e79">
<img width="204" alt="Screenshot 2023-06-20 at 4 15 46 PM" src="https://github.com/firebase/flutterfire/assets/67046386/9b372160-1c2a-4b43-bdf5-aa586c192eeb">

After the error occured, I logged out and logged in again and repeated the steps few times but have been getting same error.

@graemep-nz Can you possibly provide us a short video or screenshots that helps to properly understand the behavior you are reporting ?

That way, it'll help @lesnitsky to get clear picture of the issue reported.

**Comment by graemep-nz** [comment]
Also I got the error

Error: setState() or markNeedsBuild() called when widget tree was locked.

in the process of testing this with the example app as described here
https://github.com/firebase/flutterfire/issues/11070

**Comment by graemep-nz** [comment]
Perhaps Mr Lesnitsky could post a video showing the profile dialog NOT going wrong - since he claimed he couldn't reproduce it.

**Comment by darshankawar** [comment]
Thanks for the video. It showed it could be replicable on web, so I tried the same and was able to replicate the reported behavior.

<img width="909" alt="Screenshot 2023-06-21 at 5 06 30 PM" src="https://github.com/firebase/flutterfire/assets/67046386/01ec8e2c-8b9c-405e-a341-91a536d0500a">
<img width="604" alt="Screenshot 2023-06-21 at 5 06 43 PM" src="https://github.com/firebase/flutterfire/assets/67046386/bb212e87-f41a-41e7-8a97-4c9c959d35cc">

After above error, I signed out, logged in again which showed the google sign-in method was added:

<img width="764" alt="Screenshot 2023-06-21 at 5 07 10 PM" src="https://github.com/firebase/flutterfire/assets/67046386/1ce79678-2b37-45b3-accb-60e25d225437">

**Comment by graemep-nz** [comment]
Ah, the platform.  Yeah the web.  But it goes wrong on my Samsung tablet as well, but differently.

Perhaps your bug reporting template should ask for the platform to be identified.  Also if the bug author doesn't state the platform you should ask what it is.

**Comment by lesnitsky** [comment]
The fact that this issue is only reproducible on web is very important and was not mentioned in the #11148 and this issue as well. I was trying to reproduce the issue on android emulator and it works as expected.

The reason why I asked to file a new issue – it's easier to keep track for us when every issue is only about a single thing. 
Ideally I'd want to understand what's the issue about based on the title. For example "Enabling Google provider from profile doesn't work on web" is much more descriptive. "reposting bug 11148" says nothing, until you go to that issue and find a relevant comment there.

> Perhaps your bug reporting template should ask for the platform to be identified.

That's correct, I'm going to add a new issue template specifically for the UI.

**Comment by graemep-nz** [comment]
@Ehesp 
@darshankawar 
@lesnitsky 
You're full of BS My Lesnitsky. You've got no business changing my title.  The title was correct.  Your title is incorrect, which you would know if you had actually tested this as you have now twice claimed.  I already said in my previous post that it goes wrong on my Android tablet as well.  I have now just wasted a bunch more time and find that it also fails on an Android emulator.  One of the first things any good developer does is ask for not just the platform but also the device type.  Please post a video that shows this working correctly on your Android emulator Mr Lesnitsky.  Off by one errors are not platform dependent Mr Lesnitsky.  As I already said, you had no business closing and locking my original bug report.

Also when are you going to post a roadmap that allows people to know when this package will be useable in a real application.  You shouldn't be working on a brand new package when this package isn't useable.

**Comment by darshankawar** [comment]
@graemep-nz 
There's nothing wrong in changing the issue title if it helps to give a quick summary of what the issue is.
Also, I suggest you to go through [Github code of conduct](https://docs.github.com/en/site-policy/github-terms/github-community-code-of-conduct).

**Comment by graemep-nz** [comment]
There's everything wrong with changing someone else's title and making it wrong which it now is.

So are you going to file a bug report for your "unknown error occurred" Mr Darshankawar, or is that going to be forgotten about because Mr Lesnitsky says this is a web only bug?

**Comment by graemep-nz** [comment]
It doesn't work correctly on my Android tablet. It doesn't work correctly on my Android emulator.  It doesn't work correctly on Mr darshankawar's devices.  Why would it work correctly on your device?
