### ISSUE TITLE
🐛 [Firebase_messaging] onMessageOpenedApp.listen() doesn't work when app killed

### ISSUE THREAD

**Issue by Gobmichet** [firebase/flutterfire#11167]
Hi,
I have to open specific screens when user clicks on a notification following the payload it has (classic...).  
here is the code :
```
// Listener 2 :: When notif clicked and open the app :
FirebaseMessaging.onMessageOpenedApp.listen((message) async {
      switch (message.data["type"]) {
        case "case1" :
          navigatorKey.currentState!.push(MaterialPageRoute(builder: (_) => Case1Page());
          break;
        case "case2" :
          navigatorKey.currentState!.push(MaterialPageRoute(builder: (_) => Case2Page());
          break;
        default :
          // nothing
      }
    });
```
The problem is that it ONLY works when app is in background when user clicks the notification !
It doesn't work when app was killed, it just opens the app on homepage

I spent some time searching for a fix but i only find the :
```
  FirebaseMessaging.configure(
    onLaunch: (Map<String, dynamic> message) async {
      navigateToSpecificScreen(message['data']['screen']);
    },
    onResume: (Map<String, dynamic> message) async {
      navigateToSpecificScreen(message['data']['screen']);
    },
  );
```
but it dosen't exist anymore !
like told here :
https://firebase.flutter.dev/docs/migration/#messaging

it is said that this is replaced by the onMessageOpenedApp.listen() method but i also read that this last method ONLY works when app is in background and not when the app is killed.

So How to achieve that ?
What is the replacement of .configure() > .onLaunch() method in newest versions of the package ?
I just couldn't find it anywhere :(

Thanks in advance for your help !

**Comment by darshankawar** [comment]
Thanks for the report @Gobmichet 
Is this occuring on Android or iOS ?
Also, can you try out the [plugin example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example) and see if it helps in your case ?

**Comment by Gobmichet** [comment]
Hi,
Until now we do develop testing on Android devices/emulators for convenience purpose... 
So, sure it happens on Android.
for our implementation we do :
```
// Firebase configuration ::
  await Firebase.initializeApp();
  await FirebaseMessaging.instance.requestPermission(alert:true, badge:true, sound:true,);
  // Allows ONLY on iOS to receive foreground notifs when app is open.
  FirebaseMessaging.instance.setForegroundNotificationPresentationOptions(alert:true, badge:true, sound:true,);
  final firebaseMessaging = FCM();
```
Where FCM is a service class like :
```
class FCM {
  // See https://firebase.flutter.dev/docs/messaging/notifications/ for below code
  final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();
  final AndroidNotificationChannel channel = AndroidNotificationChannel(
    'high_importance_channel', // id
    'High Importance Notifications', // title
    importance: Importance.max,
  );

  /**
   * 4 listeners needed for all Notif receiving and firing cases ::
   */
  setNotifications() async {
    doInitAndroidSpecificNotifChannel();
    // Listener 1 :: When notif arrives & app is in background or even killed ::
    FirebaseMessaging.onBackgroundMessage(onBackgroundMessage);
    // Listener 2 :: When application is in foreground (Heads up notifs) ::
    FirebaseMessaging.onMessage.listen((message) async {
      print("onMessage.listen((message)");
      // For Android specific local notification when app is in foreground, blocked otherwise ::
      RemoteNotification? notification = message.notification;
      AndroidNotification? android = message.notification?.android;
      if (notification != null && android != null) {
        flutterLocalNotificationsPlugin.show(
          notification.hashCode,
          notification.title,
          notification.body,
          NotificationDetails(
            android: AndroidNotificationDetails(
              channel.id,
              channel.name,
              icon: "@mipmap/ic_launcher",
              importance: Importance.max,
              // other properties...
            ),
          ));
      }
      doForegroundPersistNotificationInDB(message);
    },);
    // Listener 3 :: When notif clicked and open the app ::
    // ONLY when app is Launched / in background | Equivalent to "old" onResume()
    FirebaseMessaging.onMessageOpenedApp.listen((message) async {
      doOnNotifOpenedRedirection(message);
    });
    // Listener 4 :: When notif clicked and open the app ::
    // ONLY when app was Killed | Equivalent to "old" onLaunch()
    FirebaseMessaging.instance.getInitialMessage().then((message) => {
      if (message != null) { doOnNotifOpenedRedirection(message), }
    });
  } // setNotifications

} // FCM
```

We did many tests and the onMessageOpenedApp.listen() only fires when app is in background not killed...

We did find the FirebaseMessaging.instance.getInitialMessage().then((message)) method searching on StackOverflow...

But in the firebase documentation it is said that onMessageOpenedApp.listen() should replace BOTH onLaunch() and onResume() deprecated methods and that's not what we have.

What am i missing ?
Thx in advance.

PS : Another wierd thing (maybe linked ? maybe not). when we use the Notification test page, we manage to send notifications to devices when we do give the different tokens.
But none is sent when we target an OS app...
> The app isn't on google play store yet.
Is there a problem with those OS based campains ?

**Comment by darshankawar** [comment]
Thanks for the update @Gobmichet 

> We did many tests and the onMessageOpenedApp.listen() only fires when app is in background not killed...

This is WAI, as `onMessageOpenedApp` doesn't trigger when the app is killed. If you check the [documentation](https://pub.dev/documentation/firebase_messaging/latest/firebase_messaging/FirebaseMessaging/onMessageOpenedApp.html), it states:

`A Stream event will be sent if the app has opened from a background state (not terminated).`
