### ISSUE TITLE
🐛 [FIREBASE_MESSAGING] deleteToken() in offline mode throw exception SERVICE_NOT_AVAILABLE

### ISSUE THREAD

**Issue by gemunet** [firebase/flutterfire#11177]
## Bug report

I try to unsubscribe from topics when the user logs out by removing the FCM token. This works fine if I'm online, but when offline I get an error and does not remove the token:

`[firebase_messaging/unknown] java.io.IOException: SERVICE_NOT_AVAILABLE`

* I have tried this only on android

### Steps to reproduce

1. initialize firebase and subscribe to topic
2. put the mobile device in airplane mode
3. invoke the `FirebaseMessaging.instance.deleteToken();`

### Expected behavior

remove the token and no longer receive FCM notifications

### Flutter doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.12, on Microsoft Windows [Versi¢n 10.0.19044.3086], locale es-CL)
[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.8.5)
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.79.2)
[√] Connected device (4 available)
[√] HTTP Host Availability

! Doctor found issues in 2 categories.
```
---

### Flutter dependencies

```
firebase_messaging: ^14.6.3
```

**Comment by danagbemava-nc** [comment]
Hi @gemunet, the flutterfire plugins are just wrappers around the native sdks. You will need to report this on the `firebase-android-sdk` repo so that they can implement it on their end. The native method seems to execute a network call and so it will require network access for the request to complete. 

Closing from here as this is out of scope for the plugin.
