### ISSUE TITLE
No error message regarding requiring Keychain Sharing capability enabled 

### ISSUE THREAD

**Issue by dotjon0** [firebase/flutterfire#11186]
There was an update via https://github.com/firebase/firebase-ios-sdk/issues/10582 which:

"Prevent keychain pop-up when accessing Firebase Auth keychain in a Mac app. Note that using Auth in a Mac app requires that the app is signed with a provisioning profile that has the Keychain Sharing capability enabled (see Firebase 9.6.0 release notes) (https://github.com/firebase/firebase-ios-sdk/issues/10582)." (see https://firebase.google.com/support/release-notes/ios#version_1050_-_february_7_2023).

This is a breaking change if (i) an Apple Developer team has not been applied to the flutter macOS app, and (ii) Keychain Sharing capability has not been enabled (as a result of i above) - as it stops Firebase Auth from being able to login. In our case, we did not make any changes to the Firebase Auth Flutter package version, carried out flutter run and Firebase Auth can no longer log users in. This is a breaking change, so it may have been a good idea to push this out in a major release, and at a bare minimum throw an error if i and ii are not met above - so the developer experience is great and days of time are not spent debugging and then stumbling on the above release article, as in our case.

**Comment by dotjon0** [comment]
For anyone temporarily wanting to use the version of Firebase Auth/Core/etc prior to the update forcing the Keychain Sharing capability enabled config, simply set your pubspec.yaml to:

```
  firebase_auth: 4.2.1
  firebase_auth_web: 5.2.1
  firebase_core_platform_interface: 4.5.2
  firebase_core_web: 2.0.2
  firebase_core: 2.4.0
```

**Comment by darshankawar** [comment]
Thanks for the report @dotjon0 
Can you take a look at https://github.com/firebase/flutterfire/issues/9538, https://github.com/firebase/flutterfire/issues/8811#issuecomment-1245953448, https://github.com/firebase/flutterfire/issues/8811 and https://github.com/firebase/flutterfire/issues/9538#issuecomment-1459894150 to see if it helps in your case or not.

**Comment by dotjon0** [comment]
Hi @darshankawar thanks for the reply. we have put in the below as a temporary fix:

`firebase_auth: 4.2.1
  firebase_auth_web: 5.2.1
  firebase_core_platform_interface: 4.5.2
  firebase_core_web: 2.0.2
  firebase_core: 2.4.0`

What would be good is if we could update the Firebase Auth docs (general docs and on dart.pub) to state that you have to have Keychain Sharing capability enabled - is this possible? Ive bumped into other dev's with the same issue, and they were unaware of the release notes as they did not change the firebase_auth flutter package version (obviously impacting via having a range of version nos) - not an impact that you would expect though with no major version change...

**Comment by darshankawar** [comment]
Thanks for the feedback @dotjon0 
It seems this PR has added a note in the documentation for same: https://github.com/firebase/flutterfire/pull/11110/files although it seem to be related to `firebase_remote_config` , but check if this addition helps to answer your question or not.

**Comment by dotjon0** [comment]
@darshankawar brilliant, thank you. However you need macOS Keychain to be enabled regardless to use Firebase Auth in Flutter within a macOS app - the use case is not limited to Remote Config on macOS.

**Comment by darshankawar** [comment]
Thanks for the update. Keeping it open as a documentation issue.

**Comment by dotjon0** [comment]
Thank you so much
