### ISSUE TITLE
🐛 [firebase_core_web] Error: Expected a value of type 'Object', but got one of type 'Null'

### ISSUE THREAD

**Issue by nrobi144** [firebase/flutterfire#11180]
## Bug report
Having the same issue as https://github.com/firebase/flutterfire/issues/9934

**Comment by darshankawar** [comment]
@nrobi144 
Can you provide us `flutter doctor -v`, `pubspec.yaml`, exact steps to replicate that throws the error along with complete error log ?
The issue you linked is not recent and each issue could have different config / settings or cause throwing same error.
