### ISSUE TITLE
[FIREBASE_MESSAGING] TOO_MANY_REGISTRATIONS

### ISSUE THREAD

**Issue by moneypluses** [firebase/flutterfire#11194]
## Bug report

Its saying :
```
"FirebaseException [firebase_messaging/unknown] java.io.IOException: TOO_MANY_REGISTRATIONS" on getToken()

E/FirebaseInstanceId(29577): Topic sync or token retrieval failed on hard failure exceptions: TOO_MANY_REGISTRATIONS. Won't retry the operation.
I/PlatformViewsController(29577): Hosting view in view hierarchy for platform view: 0
D/BufferQueueConsumer(29577): [](id:738900000002,api:0,p:-1,c:29577) connect: controlledByApp=true
E/flutter (29577): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [firebase_messaging/unknown] java.io.IOException: TOO_MANY_REGISTRATIONS
E/flutter (29577): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
E/flutter (29577): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
E/flutter (29577): <asynchronous suspension>
E/flutter (29577): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:510:43)
E/flutter (29577): <asynchronous suspension>
E/flutter (29577): #3      MethodChannelFirebaseMessaging.getToken (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:224:11)
E/flutter (29577): <asynchronous suspension>
```

Half of the applications is getting the token and other half are not getting the token. This devices are not testing applications but actual release builds used by customers that are downloaded from play store.

**Comment by darshankawar** [comment]
@moneypluses 
[firebase_messaging/unknown] java.io.IOException: TOO_MANY_REGISTRATIONS" probably indicates your device is already registered or being reused many times.

Check [this](https://stackoverflow.com/a/48439819) link and see if it helps in your case.

Also, check if `messagingSenderId` for your firebase project is empty or not. 

If above doesn't help, please provide a bare minimum but complete reproducible code sample without any third party package code implementation that triggers this exception, so that we can analyze it properly further.

**Comment by iresolveservices** [comment]
facing same issue with some real time devices

E/FirebaseInstanceId( 9566): Topic sync or token retrieval failed on hard failure exceptions: TOO_MANY_REGISTRATIONS. Won't retry the operation.
E/flutter ( 9566): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [firebase_messaging/unknown] java.io.IOException: TOO_MANY_REGISTRATIONS
E/flutter ( 9566): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
E/flutter ( 9566): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
E/flutter ( 9566): <asynchronous suspension>
E/flutter ( 9566): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:510:43)
E/flutter ( 9566): <asynchronous suspension>
E/flutter ( 9566): #3      MethodChannelFirebaseMessaging.getToken (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:224:11)
E/flutter ( 9566): <asynchronous suspension>
E/flutter ( 9566):

**Comment by iresolveservices** [comment]
In my case, the issue occurred because the client had 135 apps installed, including system apps, totaling 350 apps. However, after removing some apps, the notification working fine.
