### ISSUE TITLE
Google sign in is crashing in Android 12 and up.

### ISSUE THREAD

**Issue by desaivishal11** [firebase/flutterfire#11204]
## Bug report

**Describe the bug**
WE started getting below when trying to sign up with google sign in.

CALL_ACTIVITY_RESULT_BEFORE_RESUME
Change ID: 78294732
Default State: Enabled for apps that target Android 12 (API level 32) or higher.
For apps targeting Android 12 (API level 32) and higher, corrects the lifecycle of activity result to guarantee that an activity gets the activity result just before resume.

### Steps to reproduce

You can reproduce this on android 12 and up.

**Comment by danagbemava-nc** [comment]
Hi @desaivishal11, are you using the google_sign_in package directly or are you using in through firebase_auth? 
What versions of the packages are you using? 
Please provide the output of `flutter pub deps -- --style=compact`

Please also provide the output of flutter doctor -v. 

A minimal reproducible code sample would also help us get to the root of the issue quickly

Thank you
