### ISSUE TITLE
Flutter Project in Android Studio Flamingo

### ISSUE THREAD

**Issue by AllyTechEngineering** [firebase/flutterfire#11208]
## Bug report

**Describe the bug**
On macOS Venture 13.4.1, Android Studio Flamingo, Flutter 3.10.5, Dart 3.0.5, flutterfire 0.2.7: Unhandled exception when running the flutterfire CLI configure for Android, ios, macos and web. Does not even let me answer Y or N and jumps to error.

### Steps to reproduce

On macOS Venture 13.4.1, Android Studio Flamingo, Flutter 3.10.5, Dart 3.0.5, flutterfire 0.2.7: Go through the initial setup steps for a Firebase Flutter project. Run flutterfire configure (for your project) and get the list for android, ios, macos and web and run the command you will get the issue and sometimes it will skip past the Y or N and give the long error that start with, Unhandled exception: followed by a long explanation.

### Expected behavior

Normally you answer Yes and get the full registration information in the terminal and can proceed with the next steps of setting up Firebase. 

### Sample project

This is a complex Flutter project so I am showing the terminal window results.
`Bobbys-MBP:firebasenotworkingproject bobbytaylor$ flutterfire configure --project=fir-notworkingwithflutter
i Found 4 Firebase projects. Selecting project fir-notworkingwithflutter.                                                                                  
✔ Which platforms should your configuration support (use arrow keys & space to select)? · android, ios, macos, web                                         
i Firebase android app com.example.firebasenotworkingproject registered.                                                                                   
i Firebase ios app com.example.firebasenotworkingproject registered.                                                                                       
i Firebase macos app com.example.firebasenotworkingproject.RunnerTests registered.                                                                         
i Firebase web app firebasenotworkingproject (web) registered.                                                                                             
Unhandled exception:
Exception: /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:88:in `require': cannot load such file -- xcodeproj (LoadError)
        from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:88:in `require'
        from -e:1:in `<main>'

#0      ConfigCommand.run (package:flutterfire_cli/src/commands/config.dart:540:11)
<asynchronous suspension>
#1      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#2      main (file:///Users/bobbytaylor/.pub-cache/hosted/pub.dev/flutterfire_cli-0.2.7/bin/flutterfire.dart:57:5)
<asynchronous suspension>
Bobbys-MBP:firebasenotworkingproject bobbytaylor$ 
`

[Please link to the public repository URL.](https://github.com/AllyTechEngineering/firebasenotworkingproject)

---

## Additional context

If you do flutterfire config (your project) and just select android and register and then answer yes - no issue. Same for web. However, macOS and iOS both have the error.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4.1 22F82 darwin-x64, locale en)
    • Flutter version 3.10.5 on channel stable at /Users/bobbytaylor/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (2 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/bobbytaylor/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] VS Code (version 1.78.2)
    • VS Code at /Volumes/TOSHIBA EXT/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 8.1.0 (API 27) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     • macOS 13.4.1 22F82 darwin-x64
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 3.0.5
Flutter SDK 3.10.5
firebasenotworkingproject 1.0.0+1

dependencies:
- cupertino_icons 1.0.5
- firebase_core 2.14.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection js material_color_utilities meta vector_math sky_engine]

dev dependencies:
- flutter_lints 2.0.2 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection js matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- collection 1.17.1
- fake_async 1.3.1 [clock collection]
- firebase_core_platform_interface 4.8.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.6.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- js 0.6.7 [meta]
- lints 2.1.1
- matcher 0.12.15 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.2.0
- meta 1.9.1
- path 1.8.3
- plugin_platform_interface 2.1.4 [meta]
- sky_engine 0.0.99
- source_span 1.9.1 [collection path term_glyph]
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.5.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- vector_math 2.1.4

```

</details>

---

**Comment by darshankawar** [comment]
@AllyTechEngineering 
`flutterfire configure` related issues need to be reported in dedicated repo: https://github.com/invertase/flutterfire_cli/issues
Closing from here.
