### ISSUE TITLE
🐛 [firebase_messaging] Display images in notifications on iOS 

### ISSUE THREAD

**Issue by gjrjf** [firebase/flutterfire#11205]
## Bug report

**Describe the bug**
I'm having trouble displaying push images on iOS.

[https://firebase.google.com/docs/cloud-messaging/flutter/receive?hl=en#display_images_in_notifications_on_ios](url)

As above, when I install the extension in xcode and run 'flutter build ios' I get an error.

--- Error ---
Semantic Issue (Xcode): 'openURL:options:completionHandler:' is unavailable: not available on iOS (App Extension)
/Users/keolheo/.pub-cache/hosted/pub.dev/geolocator_apple-2.2.7/ios/Classes/GeolocatorPlugin.m:179:5

Semantic Issue (Xcode): 'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.
/Users/keolheo/.pub-cache/hosted/pub.dev/social_share-2.3.1/ios/Classes/SocialSharePlugin.m:83:28

Semantic Issue (Xcode): 'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.
/Users/keolheo/.pub-cache/hosted/pub.dev/social_share-2.3.1/ios/Classes/SocialSharePlugin.m:90:28

Semantic Issue (Xcode): 'openURL:options:completionHandler:' is unavailable: not available on iOS (App Extension)
/Users/keolheo/.pub-cache/hosted/pub.dev/social_share-2.3.1/ios/Classes/SocialSharePlugin.m:90:47

... More same error ...
--- // Error ---

in xCode
I tried changing options like 'Enable Bitcode [no/yes]', 'Require Only App-Extension-Safe API[no/yes]', 'Other Linker Flags', etc. but to no avail.

I had no errors when using only the Share-Extension in xCode, but I installed the ImageNotification (Notification Service Extension) extension and got an error.

Is there anyone who can help?

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.3.1 22E261 darwin-x64, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
[✓] VS Code (version 1.73.0)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by HassanBalousha** [comment]
check the configuration of your ImageNotification (Notification Service Extension) extension

**Comment by gjrjf** [comment]
> check the configuration of your ImageNotification (Notification Service Extension) extension

It is related to the following link, or seems to be a similar issue.
But it doesn't work...

https://forums.swift.org/t/set-application-extension-api-only-on-a-spm-package/39333/57
https://danielsaidi.com/blog/2022/05/18/how-to-suppress-linking-warning

**Comment by gjrjf** [comment]
> 

I solved it.

target 'ImageNotification' do
   use_frameworks!
   pod 'Firebase/Auth' # Add this line if you are using FirebaseAuth phone authentication
   pod 'Firebase/Messaging'
end

Changed the location of the code above.

It should be set externally, not as a child of Runner .

Thanks @HassanBalousha !
