### ISSUE TITLE
🐛 [cloud_firestore] "You cannot use 'in' filters with 'array-contains-any' filters."

### ISSUE THREAD

**Issue by dvoloshyn** [firebase/flutterfire#11203]
## Bug report

**Describe the bug**
Here is the code from the query.dart file that prevents using 'in' with 'array-contains-any' in debug mode
```
if (operator == 'array-contains-any' || operator == 'in') {
        assert(
          !(hasIn && hasArrayContainsAny),
          "You cannot use 'in' filters with 'array-contains-any' filters.",
        );
      }
```
I couldn't find this limitation here: https://firebase.google.com/docs/firestore/query-data/queries#query_limitations
You can execute such a query from Firebase Console.
Also, in profile mode (with assertions disabled) query works as expected both with emulator and real firestore

### Expected behavior

In debug mode (with assertions enabled) the validations should match those of the server side

### Flutter dependencies

cloud_firestore 4.8.2

**Comment by jcalven** [comment]
_Piggybacking on this issue – please let me know if it should be filed as a separate issue._ 

**Describe the bug**
The following code in query.dart prevents using any 'in' filters with more than 10 elements in debug mode:

```
assert(
          (value as Iterable).length <= 10,
          "'$operator' filters support a maximum of 10 elements in the value [Iterable].",
        );
```

The maximum number of elements is currently 30 as per the documentation: [https://firebase.google.com/docs/firestore/query-data/queries#limits_on_or_queries](url)

### Flutter dependencies
cloud_firestore 4.8.2

**Comment by darshankawar** [comment]
@dvoloshyn @jcalven 
See if [this](https://github.com/firebase/flutterfire/issues/11085) is related to your cases or not.

**Comment by dvoloshyn** [comment]
@darshankawar 

Yes, it's related but this one has more cases.
"With the introduction of OR clauses, Firestore queries can now contain up to 30 disjunctions in the query normal form."
And I tested the following with the firestore server:
- "in":  up to 30 values are allowed, else server returns error
- "array-contains-any": up to 30 values are allowed, else server returns error
- "in + array-contains-any": up to 30 disjunctions are allowed, for example in (5) + array-contains-any (6), else server returns error

So, besides increasing limits for 'in' and 'array-contains-any', combination 'in + array-contains-any' needs to be allowed as well.

**Comment by darshankawar** [comment]
Thanks for the update. 

/cc @russellwheatley
