### ISSUE TITLE
🐛 [Firebase auth] Proof of ownership of a second factor is required to complete sign-in.

### ISSUE THREAD

**Issue by mighttymike** [firebase/flutterfire#11218]
## Proof of ownership of a second factor is required to complete sign-in.

**Describe the bug**
In our app the Firebase auth Multi factor authentication seems to be broken. Before we catched a ```FirebaseAuthMultiFactorException``` on the ```signInWithEmailAndPassword``` method. Now this catch doesn't get triggered but only the ```FirebaseAuthException```.  This is problematic because we don't have a resolver at this place.

The documentation for the javascript sdk, seems to have updated. Here you can retrieve a resolver at top level. While this doesn't seem possible in the Flutter sdk. 

This seems to happen with the latest version but also older versions.

**Comment by darshankawar** [comment]
Thanks for the report @mighttymike 
I think you are hitting https://github.com/firebase/flutterfire/issues/10966, so please follow-up in it for further updates.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.
