### ISSUE TITLE
🐛 [firebase_ui_firestore match >1.5.4 ] getting version mismatch issue with firebase_Ui_localisation while i am not using firebase_ui_localization. 

### ISSUE THREAD

**Issue by vikasdduc** [firebase/flutterfire#11215]
## Bug report

Because no versions of firebase_ui_firestore match >1.5.4 <2.0.0 and firebase_ui_firestore 1.5.4 depends on firebase_ui_localizations ^1.5.0, firebase_ui_firestore ^1.5.4 requires
  firebase_ui_localizations ^1.5.0.
And because no versions of firebase_ui_localizations match >1.5.0 <2.0.0, firebase_ui_firestore ^1.5.4 requires firebase_ui_localizations 1.5.0.
And because firebase_ui_localizations 1.5.0 depends on flutter_localizations from sdk which depends on intl 0.17.0, firebase_ui_firestore ^1.5.4 requires intl 0.17.0.
So, because pix_cam depends on both firebase_ui_firestore ^1.5.4 and intl ^0.18.0, version solving failed.

### Steps to reproduce

2. '...'
3. See error or incorrect behavior

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by danagbemava-nc** [comment]
Hi @vikasdduc, please provide the output of flutter doctor -v as well as the packages you have in your pubspec.yaml. Please make sure you're using the latest version of flutter and the firebase dependencies. 

Thank you
