### ISSUE TITLE
🐛 [Firebase_performance] App Crashing with the exception - MissingPluginException(No implementation found for method HttpMetric#stop on channel plugins.flutter.io/firebase_performance)

### ISSUE THREAD

**Issue by rishabhsharma3617** [firebase/flutterfire#11214]
## Bug report

**App Crashes**
So i have enabled network tracking with firebase_performance and it works fine but randomly crashes the app with this exception - 
 MissingPluginException(No implementation found for method HttpMetric#stop on channel plugins.flutter.io/firebase_performance)
**I am using firebase_performance 0.8.3+3**
### Steps to reproduce
- Integrate firebase_performance 
- Run your app randomly 

### Expected behavior

It shouldnt break

---

## Additional context

I am able to see the network traced data on dashboard which suggests that it works fine and only crashing randomly 

---

### Flutter doctor

```
Flutter (Channel stable, 3.10.4, on macOS 13.1 22C65 darwin-arm64 (Rosetta), locale en-IN)
    ! Warning: `flutter` on your path resolves to /Users/rishabhsharma/Desktop/My_Computer/Installations/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/rishabhsharma/fvm/versions/3.10.4. Consider adding /Users/rishabhsharma/fvm/versions/3.10.4/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/rishabhsharma/Desktop/My_Computer/Installations/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/rishabhsharma/fvm/versions/3.10.4. Consider adding /Users/rishabhsharma/fvm/versions/3.10.4/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.69.1)
```

**Comment by danagbemava-nc** [comment]
Hi, @rishabhsharma3617

please provide a complete minimal reproducible code sample in a repo that we can clone so that we can investigate this issue. 

Kindly also upgrade to the latest version of firebase_performance (0.9.2+3) to see if you still face this issue. 

Thank you.
