### ISSUE TITLE
🐛 [firebase_storage] Using getData throws a PlatformException instead of a FirebaseException

### ISSUE THREAD

**Issue by jellynoone** [firebase/flutterfire#11211]
## Bug report

**Describe the bug**
When calling `getData()` on a storage reference and the call fails, a PlatformException is issued instead of it being converted into a FirebaseException like it is done for other methods.

### Steps to reproduce

1. Call .getData() on a non existing reference
2. See the platform exception being thrown

### Expected behavior
The call should convert the PlatformException into a FirebaseException like it does for other methods.

## Additional context
This is probably related to #8113, if not the same issue.

Additionally, I'm not providing a sample project because I think I found the issue.
If we look at the `firebase_storage_platform_interface-4.4.3/lib/src/method_channel/method_channel_reference.dart` implementation, and look at the definition of `getData` we quickly notice the result of the methodCall is directly returned from the function, meaning the encompassing try / catch block is more or less doing nothing.

If we look at other method implementations in this class, we see the futures produced by other method calls are always awaited, thus their PlatformExceptions are correctly converted to a FirebaseException.

https://github.com/firebase/flutterfire/blob/dcf1b22aefa6b3846cff9604ab15fae36d847cd1/packages/firebase_storage/firebase_storage_platform_interface/lib/src/method_channel/method_channel_reference.dart#L142-L160

**Comment by darshankawar** [comment]
Thanks for the report. Using the plugin example and using `getData()` on a reference that doesn't exist throws a `PlatformException` as reported.

**Comment by russellwheatley** [comment]
I've just tested this with:

```dart
    final ref = FirebaseStorage.instance
              .ref()
              .child('flutter-tests')
              .child('some-image.jpg');
          try {
            final result = await ref.getData();
          } catch (e) {
            print('${e.runtimeType}');
          }
```

It produced a `FirebaseException`, this might have something to do with the Storage rework a few months back but it is no longer an issue.
