### ISSUE TITLE
🐛 [cloud_firestore_odm] Have an error if the `@Collection` is in a different file from the model

### ISSUE THREAD

**Issue by rrousselGit** [firebase/flutterfire#11236]
Related to https://github.com/firebase/flutterfire/issues/11228

Currently, if the model & collection reference are in different files, we'll get a compilation error.
This is a known limitation, but we are lacking a nice error message to catch this early on. At the moment, folks would have to find it the hard way, by having a compilation error in the generated code and googling why that is the case.

**Comment by diegog-sf** [comment]
could this be converted into a feature? or maybe think of a workaround? I think its very anti pattern to have to have all classes on the same file,

Specially if we have multiple sub collections for a parent collection.

**Comment by diegog-sf** [comment]
This seemed to work like a charm.

<img width="1244" alt="image" src="https://github.com/firebase/flutterfire/assets/87551320/c57c718b-eb62-4005-ae86-4f28c674b50d">

**Comment by laeo** [comment]
So if we want define a sub reference, we should write all models in single file? to avoid private variable access across files?

**Comment by rrousselGit** [comment]
Pretty much.

Finding a solution to this limitation is difficult at the moment

**Comment by danielmahon** [comment]
I have been able to use "different" files by using the `part` and `part of` directives.
My freezed classes are generated from a protobuf file and in my root `models.dart`:
```
import 'package:freezed_annotation/freezed_annotation.dart';

part 'generated/proto/api/v1/api.firebuf.dart';
part 'generated/proto/common/v1/common.firebuf.dart';
part 'models.freezed.dart';
part 'models.g.dart';

// ...

@Collection<User>('users')
final userCollectionReference = UserCollectionReference();
```

This works fine but since migrating to freezed I also need to generate a global to fix the field maps:
```
// generated from protobuf message

@freezed
class User with _$User {
  const User._();

  @JsonSerializable(
    converters: [
      FirestoreTimestampConverter(),
    ],
  )
  const factory User({
    @Id() required String id,
    Timestamp? createdAt,
    Timestamp? updatedAt,
    @Default('') String email,
    @Default('') String displayName,
    @Default('') String brandIdentity,
  }) = _User;

  factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);

  bool get hasCreatedAt => createdAt != null;
  bool get hasUpdatedAt => updatedAt != null;
}

// NEED TO MAP THESE VARIABLES
const _$$_UserFieldMap = _$$UserImplFieldMap;

```
The field map names seem to be off. Is related to the separate files?

**Comment by rrousselGit** [comment]
Sounds like a bug in the ODM due to a recent Freezed change

**Comment by diegogarciar** [comment]
> This seemed to work like a charm.
> 
> <img alt="image" width="1244" src="https://user-images.githubusercontent.com/87551320/252017270-c57c718b-eb62-4005-ae86-4f28c674b50d.png">

I was using this for workaround with no issues, but with latest version I'm no longer allowed.

```
When using json_serializable, the `@Collection` annotation and the class that
represents the content of the collection must be in the same file.

- @Collection is from /liberty_energy/lib/invoices/core/models/invoice.dart
- `class CompanySettings with _$CompanySettings` is from /liberty_energy/lib/settings/models/settings.dart

package:liberty_energy/invoices/core/models/invoice.dart:17:7
   ╷
17 │ class Invoice with _$Invoice {
```


why is it ok that we manually have to expose the `fromJson()` and `toJson()` when using json_serializable, but its not ok to expose the `fieldMap` to expose it for different files? its literally the same use case.
```dart
@JsonSerializable()
class Person {
  /// The generated code assumes these values exist in JSON.
  final String firstName, lastName;

  /// The generated code below handles if the corresponding JSON value doesn't
  /// exist or is empty.
  final DateTime? dateOfBirth;

  Person({required this.firstName, required this.lastName, this.dateOfBirth});

  /// Connect the generated [_$PersonFromJson] function to the `fromJson`
  /// factory.
  factory Person.fromJson(Map<String, dynamic> json) => _$PersonFromJson(json);

  /// Connect the generated [_$PersonToJson] function to the `toJson` method.
  Map<String, dynamic> toJson() => _$PersonToJson(this);

  /// Connect the generated [_$PersonFieldMap] function to the `fieldMap` variable.
  static Map<String, String> get fieldMap => _$PersonFieldMap;
}

```

**Comment by TarekkMA** [comment]
Moved to: https://github.com/FirebaseExtended/firestoreodm-flutter/issues/26
