### ISSUE TITLE
🐛 [firebase_auth] web app signIn NOT throwing FirebaseAuthMultiFactorException for MFA enrolled users

### ISSUE THREAD

**Issue by tatlacas** [firebase/flutterfire#11240]
## Bug report

**Describe the bug**
Flutter web is NOT throwing `FirebaseAuthMultiFactorException` when I sign in with google account that has enrolled MFA. Instead `FirebaseAuthException` is thrown.

### Steps to reproduce

1. Run the following on flutter web app:

```
GoogleAuthProvider googleProvider = GoogleAuthProvider();
await FirebaseAuth.instance.signInWithPopup(googleProvider);
```

3. Sign in with account that already enrolled MFA
4.  `FirebaseAuthException` is thrown with code: `unkown` and message:
 ```
"An unknown error occurred: FirebaseError: Firebase: Proof of ownership of a second factor is required to complete sign-in. (auth/multi-factor-auth-required)."
```

### Expected behavior

`FirebaseAuthMultiFactorException`  must be thrown with resolver so that I complete the MFA. 

---

## Additional context

I looked at `getFirebaseAuthException` in firebase_auth_web/lib/src/utils/web_utils.dart and I see that in `FirebaseAuthException getFirebaseAuthException(Object exception, [auth_interop.Auth? auth,])` the Object exception is of type `NativeError ` that's why `FirebaseAuthException` is returned (line 25).

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.22621.1928], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    X Android SDK file not found: C:\devtools\android-sdk\platforms\android-34\android.jar.
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2022 17.1.5)
[√] Android Studio (version 2021.2)
[√] Android Studio (version 2022.2)
[√] VS Code (version 1.79.2)
[√] Connected device (4 available)
[√] Network resources
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Got dependencies.
Dart SDK 3.0.5
Flutter SDK 3.10.5

dependencies:
- firebase_auth 4.6.3 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.14.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 3.3.3 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_dynamic_links 5.3.3 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
```

</details>

---

**Comment by danagbemava-nc** [comment]
Hi @tatlacas, this is a known issue and it is being tracked in https://github.com/firebase/flutterfire/issues/10966. 

Kindly subscribe to the original issue for updates. 

Closing from here as duplicate. 

Thank you
