### ISSUE TITLE
Duplicate notification when app is in background or app kill state

### ISSUE THREAD

**Issue by iresolveservices** [firebase/flutterfire#11249]
## Bug report

**Describe the bug**
Duplicate notification when app is in background or app kill state

### Steps to reproduce

push token base test notification from firebase console

https://console.firebase.google.com/project/{project}/notification/compose
![Screenshot 2023-07-10 193743](https://github.com/firebase/flutterfire/assets/42065876/f393640f-bf38-48aa-9cd0-082ffe57d6c8)

![WhatsApp Image 2023-07-10 at 7 31 53 PM](https://github.com/firebase/flutterfire/assets/42065876/53bca6ca-72e3-4902-af64-362e14339052)

this firebase default example project . give any valid way to fix this

**Comment by darshankawar** [comment]
@iresolveservices 
Check [this](https://github.com/firebase/flutterfire/issues/10137#issuecomment-1359065385) comment from team member as why it shows duplicate notifications which should be able to answer your query.
Based on it, I'll close as duplicate. If you disagree, write in comments and I'll reopen it.
