### ISSUE TITLE
🐛 [firebase_auth][WEB] always fires firebase_auth/unknown instead of actual error code

### ISSUE THREAD

**Issue by pogorv12** [firebase/flutterfire#11250]
## Bug report

Hi! 

The problem is that web implementation of the firebase auth has broken error reporting that always fires firebase_auth/unknown error code with the right code attached in the error text description.

`[firebase_auth/unknown] An unknown error occurred: FirebaseError: Firebase: There is no user record corresponding to this identifier. The user may have been deleted. (auth/user-not-found).
`

Error reporting in android works as expected. 

### Steps to reproduce

1. Attempt to authorize with inexistent user credentials through firebase_auth for WEB. 
2. See the error

### Expected behavior

error.code should contain actual error code.

### Sample project

```
Future<void> _loginUser(BuildContext context) async {
    if (_formKey.currentState!.validate()) {
      _formKey.currentState!.save();
      try {
        await FirebaseAuth.instance.signInWithEmailAndPassword(
          email: _emailController.text,
          password: _passwordController.text,
        );
      } catch (e) {
        print(e);
      }
    }
  }
```

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.19042.1706], locale be-BY)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.3)
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.80.0)
[√] Connected device (3 available)
[√] Network resources

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
firebase_auth 4.6.3
|   |-- firebase_auth_platform_interface 6.15.3
|   |   |-- _flutterfire_internals 1.3.3
|   |   |   |-- collection...
|   |   |   |-- firebase_core...
|   |   |   |-- firebase_core_platform_interface...
|   |   |   |-- flutter...
|   |   |   '-- meta...
|   |   |-- collection...
|   |   |-- firebase_core...
|   |   |-- flutter...
|   |   |-- meta...
|   |   '-- plugin_platform_interface...
|   |-- firebase_auth_web 5.5.3
|   |   |-- firebase_auth_platform_interface...
|   |   |-- firebase_core...
|   |   |-- firebase_core_web...
|   |   |-- flutter...
|   |   |-- flutter_web_plugins...
|   |   |-- http_parser...
|   |   |-- js...
|   |   '-- meta...
|   |-- firebase_core...
|   |-- firebase_core_platform_interface...
|   |-- flutter...
|   '-- meta...
```

</details>

---

**Comment by danagbemava-nc** [comment]
Hi @pogorv12, this is a known issue that is being tracked in https://github.com/firebase/flutterfire/issues/10966. 

Kindly subscribe to the original issue for updates. 

Closing from here as duplicate.

Thank you
