### ISSUE TITLE
🐛 [firebase_analytics] Doesn't log entire route with GoRouter

### ISSUE THREAD

**Issue by lukepighetti** [firebase/flutterfire#11277]
If you add `FirebaseAnalytisObserver` to GoRouter, it doesn't log the entire route path. This makes it hard to understand what screen you are viewing

```dart
final navigationRouter = GoRouter(
  observers: [
    FirebaseAnalyticsObserver(analytics: FirebaseAnalytics.instance),
  ],
);
```

| pushed (expected) | logged | working |
| ----------------- | ------ | ------- |
| /                 | /      | ✅      |
| /foo              | foo    | ❌      |
| /settings/user    | user   | ❌      |
| /user             | user   | ❌      |

**Comment by darshankawar** [comment]
Thanks for the report @lukepighetti 
Can you take a look at go_router's `location` property to get to the current location in your app for logging and see if it helps in your case ?
