### ISSUE TITLE
🐛 [firebase_auth] Phone Authentication not working. Error:- Invalid request fields in play_integrity_token

### ISSUE THREAD

**Issue by webstar-code** [firebase/flutterfire#11272]
## Bug report

When triggering an otp with a valid phone number, it throws an error saying, `this app is not authorized to use Firebase Authentication. Please verify that the correct package name, SHA-1, and SHA-256 are configured in the Firebase Console. 
[Invalid request fields in play_integrity_token]`

I have added the SHA-1 and SHA-256 keys as well in the firebase console.

### Steps to reproduce

1. Create a new flutter project
2. Run `flutterfire configure`, to add firebase to the app
3. trigger an otp with a valid number.

Source code: https://github.com/webstar-code/test-firebase-otp

Screenshots:
![image](https://github.com/firebase/flutterfire/assets/60955315/7ecf1f10-b854-4799-8ed4-f8fa745e4d22)

Output
![image](https://github.com/firebase/flutterfire/assets/60955315/9a0b853f-9a91-4995-ad23-11d1e109aa00)

Package Versions
![image](https://github.com/firebase/flutterfire/assets/60955315/a454cae1-241d-4b01-bd24-8ab8f6228b25)

**Comment by danagbemava-nc** [comment]
Hi @webstar-code, what device are you testing on? Physical or Emulator? 
Can you also check this SO post to see if it helps? https://stackoverflow.com/a/53513327

**Comment by atleugim** [comment]
See this: #11133

**Comment by webstar-code** [comment]
I have tested it on a physical device again and it is working now, it seems it got auto-resolved

**Comment by danagbemava-nc** [comment]
Closing this since the issue has been resolved.
