### ISSUE TITLE
🐛 [firebase_auth] The given sign-in provider is disabled for this Firebase project. Enable it in the Firebase console, under the sign-in method tab of the Auth section.

### ISSUE THREAD

**Issue by openclues** [firebase/flutterfire#11288]
## Bug report

**Describe the bug**
I have integrated Firebase into my Flutter Android app and have been using Firebase Authentication successfully for more than a month. However, today when trying to verify a user's phone number using the phone authentication method, I started receiving the following error:

E/FirebaseAuth(31189): [SmsRetrieverHelper] SMS verification code request failed: unknown status code: 17006 null
D/FirebaseAuth(31189): Invoking original failure callbacks after phone verification failure for +xxxxxx, error - The given sign-in provider is disabled for this Firebase project. Enable it in the Firebase console, under the sign-in method tab of the Auth section.

### Steps to reproduce

1. Initializing firebase and FirebaseAppCheck
2. Putting the phone number for testing ( which is added in the console and have been using it for a month )
3. Getting the error i mentioned above.
4. On firebase App check metrics, the requests for authentication are considered Verified requests.

 ### Expected behavior
I expect the phone verification process to work smoothly 

### Sample project
https://github.com/openclues/firebaseProblem/blob/main/SendOtp
---

## Additional context

- I have verified that the provided API key and SHA-1/SHA-256 fingerprints in my Firebase project settings match those from my Flutter app.
- The provider is enabled on Firebase console 
- Usign real device.
- The same projectId so, the application not trying to interact with another firebase project.
### Flutter doctor

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.7.8, on Microsoft Windows [Version 10.0.25905.1000], locale en-US)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.11)
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.80.1)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
Dart SDK 2.19.5
Flutter SDK 3.7.8
Taafaa 1.1.0+15

dependencies:
- animate_do 3.0.2 [flutter]
- autoscale_tabbarview 1.0.2 [flutter]
- cached_network_image 3.2.3 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- card_swiper 2.0.4 [flutter]
- change_app_package_name 1.1.0
- connectivity_plus 4.0.1 [flutter flutter_web_plugins connectivity_plus_platform_interface js meta nm]
- cupertino_icons 1.0.5
- dart_code_metrics 5.7.5 [analyzer analyzer_plugin ansicolor args collection crypto dart_code_metrics_presets file glob html http meta path platform pub_updater source_span uuid xml yaml]
- device_info_plus 9.0.2 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta win32 win32_registry]
- easy_localization 3.0.1 [flutter shared_preferences intl args path easy_logger flutter_localizations]
- equatable 2.0.5 [collection meta]
- firebase_app_check 0.1.5+1 [firebase_app_check_platform_interface firebase_app_check_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 4.7.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.15.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 14.4.0 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flag 6.0.0 [flutter flutter_svg enum_to_string]
- flutter 0.0.0 [characters collection js material_color_utilities meta vector_math sky_engine]
- flutter_bloc 8.1.2 [flutter bloc provider]
- flutter_cache_manager 3.3.0 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_iconly 1.0.2 [flutter]
- flutter_local_notifications 14.1.1 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_native_splash 2.2.19 [args flutter flutter_web_plugins js html image meta path universal_io xml yaml]
- font_awesome_flutter 10.4.0 [flutter]
- google_fonts 4.0.3 [flutter http path_provider crypto]
- http 0.13.5 [async http_parser meta path]
- image_picker 1.0.0 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- in_app_purchase 3.1.7 [flutter in_app_purchase_android in_app_purchase_platform_interface in_app_purchase_storekit]
- intl 0.17.0 [clock path]
- page_transition 2.0.9 [flutter]
- permission_handler 10.4.1 [flutter meta permission_handler_android permission_handler_apple permission_handler_windows permission_handler_platform_interface]
- pin_code_fields 7.4.0 [flutter]
- pretty_qr_code 2.0.3 [flutter qr]
- print_remover 1.0.1
- provider 6.0.5 [collection flutter nested]
- purchases_flutter 5.3.0 [flutter freezed_annotation json_annotation]
- share_plus 7.0.2 [cross_file meta mime flutter flutter_web_plugins share_plus_platform_interface file url_launcher_web url_launcher_windows url_launcher_linux url_launcher_platform_interface ffi win32]
- shared_preferences 2.1.0 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- sliver_header_delegate 0.0.5 [flutter]
- spring 2.0.2 [simple_animations supercharged universal_platform vector_math flutter]
- thawani_payment 0.0.6 [http webview_flutter webview_flutter_android webview_flutter_wkwebview flutter]     
- url_launcher 6.1.11 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- whatsapp_unilink 2.1.0

dev dependencies:
- flutter_launcher_icons 0.13.1 [args checked_yaml cli_util image json_annotation path yaml]

transitive dependencies:
- _fe_analyzer_shared 61.0.0 [meta]
- _flutterfire_internals 1.3.4 [collection firebase_core firebase_core_platform_interface flutter meta]      
- analyzer 5.13.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- analyzer_plugin 0.11.2 [analyzer collection dart_style pub_semver yaml]
- ansicolor 2.0.1
- archive 3.3.7 [crypto path pointycastle]
- args 2.4.0
- async 2.10.0 [collection meta]
- bloc 8.1.1 [meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- cached_network_image_platform_interface 2.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.0.2 [flutter flutter_cache_manager cached_network_image_platform_interface]     
- characters 1.2.1
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- cli_util 0.4.0 [meta path]
- clock 1.1.1
- collection 1.17.0
- connectivity_plus_platform_interface 1.2.4 [flutter meta plugin_platform_interface]
- convert 3.1.1 [typed_data]
- cross_file 0.3.3+4 [js meta]
- crypto 3.0.2 [typed_data]
- csslib 1.0.0 [source_span]
- dart_code_metrics_presets 1.8.0
- dart_style 2.3.2 [analyzer args path pub_semver source_span]
- dbus 0.7.8 [args ffi meta xml]
- device_info_plus_platform_interface 7.0.0 [flutter meta plugin_platform_interface]
- easy_logger 0.0.2 [flutter]
- enum_to_string 2.0.1
- fake_async 1.3.1 [clock collection]
- ffi 2.0.1
- file 6.1.4 [meta path]
- file_selector_linux 0.9.2 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.3 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.0 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.3 [cross_file file_selector_platform_interface flutter]
- firebase_app_check_platform_interface 0.0.9+1 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_app_check_web 0.0.11+1 [_flutterfire_internals firebase_app_check_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 6.16.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.6.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser js meta]
- firebase_core_platform_interface 4.8.0 [collection flutter flutter_test meta plugin_platform_interface]    
- firebase_core_web 2.6.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 4.3.0 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.3.0 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flutter_blurhash 0.7.0 [flutter]
- flutter_local_notifications_linux 4.0.0+1 [dbus ffi flutter flutter_local_notifications_platform_interface path xdg_directories]
- flutter_local_notifications_platform_interface 7.0.0+1 [flutter plugin_platform_interface]
- flutter_localizations 0.0.0 [flutter intl characters clock collection js material_color_utilities meta path vector_math]
- flutter_plugin_android_lifecycle 2.0.15 [flutter]
- flutter_svg 1.1.6 [flutter meta path_drawing vector_math xml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection js matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]     
- freezed_annotation 2.4.1 [collection json_annotation meta]
- glob 2.1.2 [async collection file path string_scanner]
- html 0.15.4 [csslib source_span]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image 4.0.17 [archive meta xml]
- image_picker_android 0.8.7+3 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]    
- image_picker_for_web 2.2.0 [flutter flutter_web_plugins image_picker_platform_interface mime]
- image_picker_ios 0.8.8 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.8.0 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- in_app_purchase_android 0.3.0+10 [collection flutter in_app_purchase_platform_interface json_annotation]   
- in_app_purchase_platform_interface 1.3.4 [flutter plugin_platform_interface]
- in_app_purchase_storekit 0.3.6+4 [collection flutter in_app_purchase_platform_interface json_annotation]
- js 0.6.5 [meta]
- json_annotation 4.8.1 [meta]
- matcher 0.12.13 [meta stack_trace]
- material_color_utilities 0.2.0
- meta 1.8.0
- mime 1.0.4
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- octo_image 1.0.2 [flutter flutter_blurhash]
- package_config 2.1.0 [path]
- path 1.8.2
- path_drawing 1.0.1 [vector_math meta path_parsing flutter]
- path_parsing 1.0.1 [vector_math meta]
- path_provider 2.0.15 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- path_provider_android 2.0.24 [flutter path_provider_platform_interface]
- path_provider_foundation 2.2.1 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.10 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.0.6 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.7 [ffi flutter path path_provider_platform_interface win32]
- pedantic 1.11.1
- permission_handler_android 10.3.0 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.1.3 [flutter permission_handler_platform_interface]
- permission_handler_platform_interface 3.11.0+1 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.1.3 [flutter permission_handler_platform_interface]
- petitparser 5.1.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.4 [meta]
- pointycastle 3.7.3 [collection convert js]
- process 4.2.4 [file path platform]
- pub_semver 2.1.4 [collection meta]
- pub_updater 0.3.0 [http json_annotation process pub_semver]
- qr 3.0.1 [meta]
- rxdart 0.27.7
- share_plus_platform_interface 3.2.1 [cross_file flutter meta mime plugin_platform_interface path_provider uuid]
- shared_preferences_android 2.1.2 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.2.1 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.2.0 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.2.0 [flutter plugin_platform_interface]
- shared_preferences_web 2.1.0 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.2.0 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- simple_animations 3.1.1 [flutter supercharged pedantic]
- sky_engine 0.0.99
- source_span 1.9.1 [collection path term_glyph]
- sqflite 2.2.8+4 [flutter sqflite_common path]
- sqflite_common 2.4.5 [synchronized path meta]
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]
- string_scanner 1.2.0 [source_span]
- supercharged 2.1.1 [supercharged_dart flutter]
- supercharged_dart 2.1.1
- synchronized 3.1.0
- term_glyph 1.2.1
- test_api 0.4.16 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.9.2 [path]
- typed_data 1.3.1 [collection]
- universal_io 2.2.0 [collection meta typed_data]
- universal_platform 1.0.0+1
- url_launcher_android 6.0.26 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.1.3 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.5 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.4 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.2 [flutter plugin_platform_interface]
- url_launcher_web 2.0.16 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.6 [flutter url_launcher_platform_interface]
- uuid 3.0.7 [crypto]
- vector_math 2.1.4
- watcher 1.0.2 [async path]
- webview_flutter 4.0.7 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]
- webview_flutter_android 3.5.2 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 2.2.0 [flutter meta plugin_platform_interface]
- webview_flutter_wkwebview 3.3.0 [flutter path webview_flutter_platform_interface]
- win32 4.1.4 [ffi]
- win32_registry 1.1.0 [ffi win32]
- xdg_directories 1.0.0 [meta path process]
- xml 6.2.2 [collection meta petitparser]
- yaml 3.1.1 [collection source_span string_scanner]```

</details>

---

**Comment by krishna700** [comment]
Please help. Same issue

**Comment by openclues** [comment]
> Please help. Same issue

What is the exact error you got?

**Comment by krishna700** [comment]
@openclues Initially it was working correctly, but it gives the below error. Even the earlier production build is giving same error.

I thought something is wrong in the project, so deleted that project, created a new one, but it's still same. 

Also tried downgrading flutter to 3.3.3 & 3.7.12, doesn't work. Neither downgrading the plugins work.

```
E/FirebaseAuth(24002): [SmsRetrieverHelper] SMS verification code request failed: unknown status code: 17006 null
D/FirebaseAuth(24002): Invoking original failure callbacks after phone verification failure for +96512345678, 
error - The given sign-in provider is disabled for this Firebase project. Enable it in the Firebase console, under the sign-in method tab of the Auth section.
```


```
  firebase_core: 2.14.0
  firebase_auth: 4.6.3
  firebase_ui_auth: 1.4.3
```
  
 `Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.3.1 22E772610a darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices  Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.80.1)
[✓] Connected device (3 available)
[✓] Network resources`

Also I get **IntegrityService : linkToDeath** , but this is something I used to get earlier also, that's why I created a new project and never enabled integrity services but still no luck. 

Please help, we were supposed to go live and at end moment this is happening. Also production is not working anymore. 

CC - @nilevars

**Comment by openclues** [comment]
> @openclues Initially it was working correctly, but it gives the below error. Even the earlier production build is giving same error.
> 
> I thought something is wrong in the project, so deleted that project, created a new one, but it's still same.
> 
> Also tried downgrading flutter to 3.3.3 & 3.7.12, doesn't work. Neither downgrading the plugins work.
> 
> ```
> E/FirebaseAuth(24002): [SmsRetrieverHelper] SMS verification code request failed: unknown status code: 17006 null
> D/FirebaseAuth(24002): Invoking original failure callbacks after phone verification failure for +96512345678, 
> error - The given sign-in provider is disabled for this Firebase project. Enable it in the Firebase console, under the sign-in method tab of the Auth section.
> ```
> 
> ```
>   firebase_core: 2.14.0
>   firebase_auth: 4.6.3
>   firebase_ui_auth: 1.4.3
> ```
> 
> `Doctor summary (to see all details, run flutter doctor -v): [✓] Flutter (Channel stable, 3.10.6, on macOS 13.3.1 22E772610a darwin-arm64, locale en-IN) [✓] Android toolchain - develop for Android devices Android SDK version 32.1.0-rc1) [✓] Xcode - develop for iOS and macOS (Xcode 14.3) [✓] Chrome - develop for the web [✓] Android Studio (version 2021.3) [✓] VS Code (version 1.80.1) [✓] Connected device (3 available) [✓] Network resources`
> 
> Also I get **IntegrityService : linkToDeath** , but this is something I used to get earlier also, that's why I created a new project and never enabled integrity services but still no luck.
> 
> Please help, we were supposed to go live and at end moment this is happening. Also production is not working anymore.
> 
> CC - @nilevars

Yes, That is exactly the same problem.

**Comment by openclues** [comment]
> @openclues Initially it was working correctly, but it gives the below error. Even the earlier production build is giving same error.
> 
> I thought something is wrong in the project, so deleted that project, created a new one, but it's still same.
> 
> Also tried downgrading flutter to 3.3.3 & 3.7.12, doesn't work. Neither downgrading the plugins work.
> 
> ```
> E/FirebaseAuth(24002): [SmsRetrieverHelper] SMS verification code request failed: unknown status code: 17006 null
> D/FirebaseAuth(24002): Invoking original failure callbacks after phone verification failure for +96512345678, 
> error - The given sign-in provider is disabled for this Firebase project. Enable it in the Firebase console, under the sign-in method tab of the Auth section.
> ```
> 
> ```
>   firebase_core: 2.14.0
>   firebase_auth: 4.6.3
>   firebase_ui_auth: 1.4.3
> ```
> 
> `Doctor summary (to see all details, run flutter doctor -v): [✓] Flutter (Channel stable, 3.10.6, on macOS 13.3.1 22E772610a darwin-arm64, locale en-IN) [✓] Android toolchain - develop for Android devices Android SDK version 32.1.0-rc1) [✓] Xcode - develop for iOS and macOS (Xcode 14.3) [✓] Chrome - develop for the web [✓] Android Studio (version 2021.3) [✓] VS Code (version 1.80.1) [✓] Connected device (3 available) [✓] Network resources`
> 
> Also I get **IntegrityService : linkToDeath** , but this is something I used to get earlier also, that's why I created a new project and never enabled integrity services but still no luck.
> 
> Please help, we were supposed to go live and at end moment this is happening. Also production is not working anymore.
> 
> CC - @nilevars

I am sorry, can i ask when this problem started ?

**Comment by darshankawar** [comment]
@openclues 
It looks like it could be a server glitch as based on above reports, the same error is thrown in production environment as well, so I suggest you all to wait for some time and see if it starts working again or not.
As you mentioned you have already been using the plugin and it suddenly started to throw the error, that too, 17006 as null, it may not be specific to any plugin changes unless you upgraded your flutterfire plugins and then started to see the issue.

Also, see [this](https://stackoverflow.com/questions/66015192/sms-verification-code-request-failed-with-unknown-status-code-17006-while-authe) and check if it helps in your case or not.

**Comment by krishna700** [comment]
Well to specify everything in details. 

Login/SignUp with OTP was working fine for all the selected countries, but suddenly I saw in OTP verification screen, I am getting an error like "**The given Sign in provider for this Firebase project. Enable it in Firebase console, under sign in ......** ". I was pretty sure everything was turned on and set up was correctly done as it was working previously. 

Then I read somewhere it's related to OAUTH client, I created a new firebase project, created a new app id & new signing key and it started working again. 

Then I realised I have used same key to sign two different applications in playstore, which conflicted the keys and as soon as both the apps were live firebase started blocking the project logins for both Android & iOS. 

Finally I unpublished both the apps with same key, created new firebase project, and published fresh apps, with new bundle ID & new UNIQUE signing keys for both the apps. 
Strangely after this it started working again. 

@openclues Maybe this way you can make your project work

But now it only works for Indian number, other countries still show the above error. So If it's working for one country it must work for other countries. 

Also SMS region policy is set correctly to Allow the countries I am trying to. Also If I add whitelisted numbers for that country still it doesn't work. So something must be blocking from Firebase side. This is very crucial and we're stuck in this. 

@darshankawar Please look into this once. And Thank you for your time.

CC - @nilevars

**Comment by wellRoundedAppDev** [comment]
I have an issue when tested my app on Kuwaiti numbers, I get "The given sign-in provider is disabled for this Firebase project. Enable it in the Firebase console, ..", even though it works perfectly on Egyptian phone numbers.
I tried setting Kuwait in settings under firebase authentication tab, and same error occurs.
Please help.

**Comment by openclues** [comment]
- Removed the project.
- Created a new project.
- The problem is still the same Invoking original failure callbacks after phone verification failure for +96812341234, error - The given sign-in provider is disabled for this Firebase project. Enable it in the Firebase console, under the sign-in method tab of the Auth section.

**Comment by darshankawar** [comment]
Looking at the error being received `Invoking original failure callbacks after phone verification failure for +96812341234, error - The given sign-in provider is disabled for this Firebase project. Enable it in the Firebase console, under the sign-in method tab of the Auth section".`, the first step is obviously to check if the given sign-in provider is really enabled and committed in the firebase console, because the error indicates that could be the reason.

I also suggest to reach out to firebase support because reading one of the comments, it says that the phone sign-in works for one number but not for other, so it may be an issue from server side, so I request everyone facing this issue to reach out to firebase support and see what they say.

https://firebase.google.com/support

**Comment by krishna700** [comment]
Added ticket to Firebase Support team. let's see.

**Comment by isyedaliraza** [comment]
Hi there, I am facing the exact same issue. The sign-in provider is properly enabled in my Firebase project. I can confirm that it is not happening with all phone numbers. Phone numbers of some countries are working.

I hope this issue will be solved as soon as possible. We're losing new customers due to this issue.

@krishna700 Did you get any update from Firebase Support Team?

**Comment by krishna700** [comment]
@isyedaliraza 

Yes after writing couple of emails and describing the issue correctly they have fixed it. 

> 
> Thank you for your quick response. 
> 
> The project ID is ************ & Project Number is ************
> Country code facing this issue (+965), KW
> 
> I believe the issue is not with OTP delivery, cause it's not even going to the delivery stage and rejecting beforehand.
> 
> Supporting point why I say this:- 
> Even if I add a whitelist number as ************, it shows the same error which I have attached the screenshot of the error from device & from my firebase
> for your reference.
> Please forward this github link to the concerned engineer. https://github.com/firebase/flutterfire/issues/11288 I have described everything in this link. 
> Even if I add a whitelist number of USA code, it doesn't work. 
> Only Indian numbers are working for both whitelisted and normal numbers
> Also added the screenshot that the countries are allowed. 
> Initially I have done everything possible, starting with a new firebase project, removing published apps from stores, creating a new signing key, and a new app ID. 
> And if it was an issue from my development side, it won't work for Indian numbers also, so definitely we're good from the config side & code part. 
> I think something is blocking the requests to firebase. Also User Activity logging is enabled. App Check is disabled.
> 
> Hope you understand our concern. And provide a quick resolution for the issue. 
>

**Comment by openclues** [comment]
> @darshankawar Please close the issue

why ? You wrote this issue ? 

maybe it is fixed for you. but it still not fixed with me.
Next time ask to close just issues you wrote bro.

**Comment by krishna700** [comment]
@openclues My bad. I thought it's fixed from the firebase team for everyone. It's better to to contact Firebase. As definitely this is from their backend. 

Also did you tried adding a whitelisted number, are you getting the same issue?

**Comment by openclues** [comment]
> @openclues My bad. I thought it's fixed from the firebase team for everyone. It's better to to contact Firebase. As definitely this is from their backend.
> 
> Also did you tried adding a whitelisted number, are you getting the same issue?

I have sent them and still waiting. 
Yes i am testing with whitelisted number and getting the same error.

**Comment by wellRoundedAppDev** [comment]
Issue isn't solved for me, yet.

**Comment by openclues** [comment]
Firebse answered me.

According to the details that you kindly shared, the phone number that you reported is from Omen country, I must confirm that your case is not isolated, as we've received similar reports from other clients. This suggests an outage in our SMS service. Our expert Authentication team has been diligently working on investigating the matter. 

Our priority at this moment is to identify the root cause of this issue and implement a suitable resolution as swiftly and effectively as possible. I assure you that our team is putting forth its best efforts to restore the service to its full functionality. 

While the investigation is ongoing, I will ensure that you are promptly updated with any new information or progress we make in resolving this issue.

Should you have any further queries or require additional support during this time, please do not hesitate to reach out. It's my commitment to you to provide assistance to the best of my ability. 

I thank you once again for your understanding and patience. Rest assured, we're doing everything in our power to address this concern promptly

**Comment by danagbemava-nc** [comment]
@wellRoundedAppDev what region are you operating from? Have you tried reaching out to firebase support? 

@openclues, it seems that the issue is indeed from firebase and not the plugin, I'm not sure if there's anything we can do from here
