### ISSUE TITLE
🐛 [firebase_auth] fetchSignInMethodsForEmail faulty

### ISSUE THREAD

**Issue by sydneyagcaoili** [firebase/flutterfire#11293]
## Bug report

**Describe the bug**
Getting platform error from Firebase Auth when calling 'fetchSignInMethodsForEmail'

### Steps to reproduce

1. Simply call fetchSignInMethodsForEmail using any email
2. See error or incorrect behavior

```
FirebaseAuthHostApi.fetchSignInMethodsForEmail (package:firebase_auth_platform_interface/src/pigeon/messages.pigeon.dart:1180:7)
<asynchronous suspension>
#1      MethodChannelFirebaseAuth.fetchSignInMethodsForEmail (package:firebase_auth_platform_interface/src/method_channel/method_channel_firebase_auth.dart:428:20)
<asynchronous suspension>
```

### Expected behavior
Returns an empty array for emails that does not have sign up in the past

---

## Additional context
It happens to any email whether they signed up using the email before or not. It's happening on firebase_auth: 4.7.1 and is not happening on 4.6.2 below.

[firebase_auth/null-error] Host platform returned null value for non-null return value.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F770820d darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] Connected device (3 available)
[✓] Network resources

```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the report @sydneyagcaoili 
Can you provide us complete error log ?
Also, what plugin version are you on ? If on 4.7.0, if you downgrade to previous version, does it throw same error ?

**Comment by sydneyagcaoili** [comment]
Hello yes I did use 4.7.1, and when I downgraded the dependency the issue was not there.

> Thanks for the report @sydneyagcaoili Can you provide us complete error log ? Also, what plugin version are you on ? If on 4.7.0, if you downgrade to previous version, does it throw same error ?

**Comment by felixgabler** [comment]
I get this error too. However, it only happens on iOS for me, works on Android. Perhaps this helps with finding the issue. No iOS user can currently sign into my app.

**Comment by kareldb** [comment]
Same issue, it says: "host platform returned null value for non-null return value". Only ios. Version: 4.6.3

**Comment by sydneyagcaoili** [comment]
> I get this error too. However, it only happens on iOS for me, works on Android. Perhaps this helps with finding the issue. No iOS user can currently sign into my app.
> 
> Here is the entire log it throws for me:
> 
> ```
> flutter: The following exception was thrown Authentication failed with code null-error:
> flutter: [firebase_auth/null-error] Host platform returned null value for non-null return value.
> flutter: 
> #0      FirebaseAuthHostApi.fetchSignInMethodsForEmail (package:firebase_auth_platform_interface/src/pigeon/messages.pigeon.dart:1180:7)
> <asynchronous suspension>
> #1      MethodChannelFirebaseAuth.fetchSignInMethodsForEmail (package:firebase_auth_platform_interface/src/method_channel/method_channel_firebase_auth.dart:428:20)
> <asynchronous suspension>
> #2      AuthService.userExistsForEmail (package:example_app/services/auth_service.dart:39:8)
> <asynchronous suspension>
> #3      _ContinueWithEmailWidgetState._submitEmailOnly (package:example_app/ui/auth/widgets/continue_with_email_widget.dart:191:31)
> <asynchronous suspension>
> ```

Thanks, this is what I'm getting as well. As a temporary measure, as we had to release, I downgraded my firebase_auth to 4.6.3 and firebase_core to 2.13.1 (firebase_auth 4.6.3 supported core version). While this doesn't really affect actual sign up, it's hassle for those who upgraded to 4.7.1 and uses the method to check if email exists or not before signing up because it will always return wrong values and causes wrong behaviours in the app.

**Comment by darshankawar** [comment]
Thanks for the update. I was able to replicate the crash using the said method's code snippet from documentation using  4.7.1 version.

https://firebase.google.com/docs/auth/flutter/email-link-auth

**Comment by raulmabe-labhouse** [comment]
Same issue, thanks for notifying as I was very confused. 😃

**Comment by nsalleron-omedo** [comment]
Hey there,

We've made the decision to rollback our version as well. The issue is likely the same as @sydneyagcaoili

Here's the stacktrace we encountered:

```
Fatal Exception: FlutterError
0  ???                            0x0 FirebaseAuthHostApi.fetchSignInMethodsForEmail + 1180 (messages.pigeon.dart:1180)
1  ???                            0x0 MethodChannelFirebaseAuth.fetchSignInMethodsForEmail + 428 (method_channel_firebase_auth.dart:428)
2  ???                            0x0 UserRepository._isEmailAlreadyUse + 1088 (user_repository.dart:1088)
```

[firebase_auth/null-error : Host platform returned null value for non-null return value.

It's happen only on the iOS platform. iOS 16+

Thanks

**Comment by nsalleron** [comment]
Hey there,

We've made the decision to rollback our version as well. The issue is likely the same as @sydneyagcaoili

Here's the stacktrace we encountered:

```
Fatal Exception: FlutterError
0  ???                            0x0 FirebaseAuthHostApi.fetchSignInMethodsForEmail + 1180 (messages.pigeon.dart:1180)
1  ???                            0x0 MethodChannelFirebaseAuth.fetchSignInMethodsForEmail + 428 (method_channel_firebase_auth.dart:428)
2  ???                            0x0 UserRepository._isEmailAlreadyUse + 1088 (user_repository.dart:1088)
```

firebase_auth/null-error : Host platform returned null value for non-null return value.

The problem appears to be specific to the iOS platform, specifically iOS 16 and above.

Thanks

**Comment by dan-omedo** [comment]
Same issue here

**Comment by shareefhadid** [comment]
Same issue for us

**Comment by karimSalahx** [comment]
Can anyone tell us what version should we downgrade to that is working?

**Comment by nsalleron** [comment]
We are currently utilizing the following set of versions:

```
  firebase_core: 2.13.1
  cloud_firestore: 4.8.0
  firebase_auth: 4.6.2
  firebase_messaging: 14.6.2
  firebase_crashlytics: 3.3.2
  firebase_remote_config: 4.2.2
  firebase_storage: 11.2.2
  firebase_analytics: 10.4.2
```

**Comment by rpungin** [comment]
I have the same issue! Users can't signup with email! Please fix!

**Comment by ZeyadShawki** [comment]
i have this issue on ios it gives platform exception when checking email with firebase fetchSignInMethodsForEmail i had to downgrade to avoid this issue please fix it

**Comment by temaand1** [comment]
Also have this issue! Any updates ?

**Comment by ultraon** [comment]
Looks like firebase_auth 4.8 and 4.9 have the same issue!

**Comment by rexolion** [comment]
For me firebase_auth 4.9.0 returns 
`[firebase_auth/null-error] Host platform returned null value for non-null return value`
when I using this method :(

**Comment by rpungin** [comment]
I can't believe this is still not fixed!

**Comment by sarthakydv** [comment]
On downgrading firebase_core, we have to downgrade crashlytics as well where debug symbols for ios are not being uploaded correctly on the older version.

**Comment by sarthakydv** [comment]
Any timeline for the fix?

**Comment by saurabhkumar8112** [comment]
hmmm its been 3 months

**Comment by orestesgaolin** [comment]
Unfortunately issue is stil present with 4.9.0... Glad we have regression testing before the release...

**Comment by Wackymax** [comment]
Also running into this problem

**Comment by russellwheatley** [comment]
I've created a PR that fixes the issue in the short term. Effectively, `providers` can be `nil`. If it is, we pass back an empty array: https://github.com/firebase/flutterfire/pull/11596

The main cause, perhaps, is `nil` returning when there are providers associated with the email address. I've opened an issue on the firebase-ios-sdk here: https://github.com/firebase/firebase-ios-sdk/issues/11810

**Comment by varunvasista** [comment]
It returns empty array for google sign in the android 

May be the issue is fixed in iOS but android still get empty array

**Comment by russellwheatley** [comment]
I believe this is an issue with the Firebase server, I mentioned here that an empty array is returned across all platforms: https://github.com/firebase/firebase-ios-sdk/issues/11810#issuecomment-1725327252

There has been an issue filed on the Firebase backend to resolve this issue. Thank you for your patience 🙏
