### ISSUE TITLE
🐛 [cloud_firestore] No implementation found for method Query#get on channel plugins.flutter.io/firebase_firestore

### ISSUE THREAD

**Issue by abeticlairon** [firebase/flutterfire#11290]
I am getting this error only when running the web app from its release build; it works fine in the simulator though. Here is the call that triggers that:

```
FirebaseFirestore db = FirebaseFirestore.instance;
await db.collection('orders').where('publicOrderId', isEqualTo: orderNumber).get().then((querySnapshot) async {
  if(querySnapshot.docs != null){
    // Logic
    }
});
```

**Comment by darshankawar** [comment]
@abeticlairon 
In order to properly address the issue, please provide complete minimal reproducible code sample that we can copy paste and run.
Also I suggest you to check [plugin example](https://github.com/firebase/flutterfire/tree/master/packages/cloud_firestore/cloud_firestore/example) and see if using it you get same error or not.

**Comment by abeticlairon** [comment]
Hello @darshankawar, thank you for your response. The code that I pasted is the minimal reproducible code sample that you can copy paste and run, the error is happening at the `.get()` part of the asynchronous function. I didn't post the logic that follows because running this code doesn't even reach that part.

> @abeticlairon In order to properly address the issue, please provide complete minimal reproducible code sample that we can copy paste and run. Also I suggest you to check [plugin example](https://github.com/firebase/flutterfire/tree/master/packages/cloud_firestore/cloud_firestore/example) and see if using it you get same error or not.

**Comment by abeticlairon** [comment]
I closed this issue by accident

**Comment by abeticlairon** [comment]
> @abeticlairon In order to properly address the issue, please provide complete minimal reproducible code sample that we can copy paste and run. Also I suggest you to check [plugin example](https://github.com/firebase/flutterfire/tree/master/packages/cloud_firestore/cloud_firestore/example) and see if using it you get same error or not.

Hello @darshankawar, thank you for your response. The code that I pasted is the minimal reproducible code sample that you can copy paste and run, the error is happening at the .get() part of the asynchronous function. I didn't post the logic that follows because running this code doesn't even reach that part.

**Comment by darshankawar** [comment]
Thanks for the update @abeticlairon 
I tried the code snippet in plugin example wherein I get an analyzer error in the `null` check condition:

<img width="719" alt="Screenshot 2023-07-18 at 4 03 01 PM" src="https://github.com/firebase/flutterfire/assets/67046386/3c1762bd-c08b-41f8-bb10-c9490ff1ca1a">

Do you get the same because the null check will return true as suggested.

**Comment by abeticlairon** [comment]
> Thanks for the update @abeticlairon I tried the code snippet in plugin example wherein I get an analyzer error in the `null` check condition:
> 
> <img alt="Screenshot 2023-07-18 at 4 03 01 PM" width="719" src="https://user-images.githubusercontent.com/67046386/254236529-3c1762bd-c08b-41f8-bb10-c9490ff1ca1a.png">
> Do you get the same because the null check will return true as suggested.

The code doesn't even run up to the null check; but I've changed the null check to `if (querySnapshot.docs.isNotEmpty)`. The exact error I'm getting is:

`Uncaught MissingPluginException(No implementation found for method Query#get on channel plugins.flutter.io/firebase_firestore)` which is referring to the `.get()` part  of the function

**Comment by darshankawar** [comment]
Thanks for the feedback @abeticlairon 
I tried below code sample using the plugin example which printed the text I passed, but not the error you reported.

```
return Padding(
      padding: const EdgeInsets.only(bottom: 4, top: 4),
      child: Center(
        child: ElevatedButton(
          onPressed: () {
            FirebaseFirestore.instance.collection('firestore-example-app').get().then((querySnapshot) {
              if (querySnapshot.docs.isNotEmpty) {
                print('error');
              }
            });
          },
          child: Text('Test')
        )
      )
    );
```

`I/flutter (26074): error`

Can you try the same as I mentioned the plugin example link [here](https://github.com/firebase/flutterfire/issues/11290#issuecomment-1637968899) and with above snippet to see if you still get the reported error or not ? Or is there any missing step from my end to properly replicate the error.

**Comment by abeticlairon** [comment]
> Thanks for the feedback @abeticlairon I tried below code sample using the plugin example which printed the text I passed, but not the error you reported.
> 
> ```
> return Padding(
>       padding: const EdgeInsets.only(bottom: 4, top: 4),
>       child: Center(
>         child: ElevatedButton(
>           onPressed: () {
>             FirebaseFirestore.instance.collection('firestore-example-app').get().then((querySnapshot) {
>               if (querySnapshot.docs.isNotEmpty) {
>                 print('error');
>               }
>             });
>           },
>           child: Text('Test')
>         )
>       )
>     );
> ```
> 
> `I/flutter (26074): error`
> 
> Can you try the same as I mentioned the plugin example link [here](https://github.com/firebase/flutterfire/issues/11290#issuecomment-1637968899) and with above snippet to see if you still get the reported error or not ? Or is there any missing step from my end to properly replicate the error.

This works in the Chrome emulator when running in debug mode, but it doesn't work when I actually deploy the web app online. I still get the following error:

<img width="720" alt="Screenshot 2023-07-19 at 5 56 28 PM" src="https://github.com/firebase/flutterfire/assets/65367455/7b23c2d2-c46c-4b74-b91a-d4b93877eb51">

**Comment by danagbemava-nc** [comment]
Hi @abeticlairon, what version of `cloud_firestore` & `firebase_core` as well as flutter are you using?

Where is your app deployed?

**Comment by abeticlairon** [comment]
Hi @danagbemava-nc I'm using the latest versions of both cloud_firestore and firebase_core (4.8.4 and 2.15.0 respectively). The app is deployed to shared hosting via cPanel

**Comment by darshankawar** [comment]
@abeticlairon 
Can you provide `index.html` ? 
I tried again using the code snippet and deployed on web in release mode, but don't see the reported error.  Maybe there's a cache issue.
Is your firebase project integrated using flutterfire configure CLi tool or manually ? If through tool, can you update your flutterfire configure and run to see if you still get same error or not ?

**Comment by systematique** [comment]
Greetings.  I have a minimal Flutter project and I'm seeing the same issue.  I can query my firestore collection when debugging, but after deploying to firebase hosting I'm seeing 

"Uncaught MissingPluginException(No implementation found for method Query#get on channel plugins.flutter.io/firebase_firestore)"

I'd like to help debug this.  What steps should I follow?

**Comment by systematique** [comment]
When I re-checked this morning, the problem seems to have gone away.  I re-deployed and now there is no error as there was before.  If I run into it again I will post.
