### ISSUE TITLE
🐛 [firebase_auth_platform_interface] UserInfo failing to parse from json when isAnonymous or isEmailVerified are unset

### ISSUE THREAD

**Issue by dmosdallas** [firebase/flutterfire#11307]
## Bug report

After upgrading to firebase_auth_platform_interface 6.16.0, I'm receiving this error when reading `User.providerData`:

```
Error: Expected a value of type 'bool', but got one of type 'Null'
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 288:49                         throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 121:3                          castError
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 529:12                     cast
dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 715:17                                   as
packages/firebase_auth_platform_interface/src/user_info.dart 23:44                                   fromJson
packages/firebase_auth_platform_interface/src/platform_interface/platform_interface_user.dart 91:33  get providerData
packages/firebase_auth/src/user.dart 71:22                                                           get providerData
```

This appears to be caused by the deserialization changes in this commit: https://github.com/firebase/flutterfire/commit/43e5b20b14799102a6544a4763476eaba44b9cfb#diff-3576558e0a439bec69acd5c4ff2a40929571d9e98981a182b47c9df60091e2ed

### Steps to reproduce

1. Attempt to access the `providerInfo` from a valid User object
2. Get exception :/

^ Not sure if these users needed to be created with an older version of this library or similar, but all user accuonts I test with on my project are experiencing this issue.

### Expected behavior

A user's provider info is deserialized successfully

### Additional Context

Explicitly pinning to the previous version of this library eliminates the exception:

```
firebase_auth_platform_interface: 6.15.3
```

**Comment by danagbemava-nc** [comment]
Hi @dmosdallas, this was reported in https://github.com/firebase/flutterfire/issues/11289 and has since been fixed in the firebase_auth_web plugin. See https://pub.dev/packages/firebase_auth_web/changelog#561

Can you upgrade your dependencies to use the latest version of firebase_auth_web to see if you still experience this issue?

**Comment by dmosdallas** [comment]
Hey @danagbemava-nc, thanks for the quick response! Updating the version of firebase_auth_web seems to have done the trick. Looks like I got caught in a weird half-broken state when I last did a `flutter pub upgrade` -- It left firebase_auth at an old version which kept firebase_auth_web pinned back too. Manually updating the versions in my pubspec.yaml unwedged things.

Appreciate the pointer to https://github.com/firebase/flutterfire/issues/11289, I was only looking at open issues before opening this one (since the breakage looked so recent, but looks like you were just very on top of it :)

I'll close this out.
