### ISSUE TITLE
[CI] GitHub Actions removing Node 12 soon

### ISSUE THREAD

**Issue by thatfiredev** [firebase/flutterfire#11303]
## Bug report

**Describe the bug**
GitHub Actions plans to remove Node12 from the Actions runner on the 14th of August 2023.

I see that the `publish_old_docs` workflow still uses Node12:

https://github.com/firebase/flutterfire/blob/91ccc57d4b40b1b7a77dc0d871f9ff7d3f24ba13/.github/workflows/publish_old_docs.yaml#L18

It would be nice to upgrade if that workflow is still useful, or completely remove it if not (I see it was last run [a year ago](https://github.com/firebase/flutterfire/actions/runs/2294353415))

**Comment by Lyokone** [comment]
Thanks for the heads up @thatfiredev, we'll remove it since we are not using it anymore :)
