### ISSUE TITLE
🐛 [firebase_messaging] willPresentNotification crash

### ISSUE THREAD

**Issue by NSLogZfRee** [firebase/flutterfire#11320]
firebase_messaging: 14.5.0

flutter:3.7.5.   device:iOS platform(iPhone 13).

when use flutter_local_notifications to display notification.  app crash.

last break point at 

```
@implementation FLTFirebaseMessagingPlugin line 324:
[_originalNotificationCenterDelegate userNotificationCenter:center
                                        willPresentNotification:notification
                                          withCompletionHandler:completionHandler];
```

crash log:

```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=2, address=0x16af3fff0)
    frame #0: 0x00000001beedc9a4 libsystem_malloc.dylib`nanov2_allocate_from_block$VARIANT$armv81 + 4
libsystem_malloc.dylib`nanov2_allocate_from_block$VARIANT$armv81:
->  0x1beedc9a4 <+4>:  stp    x28, x27, [sp, #0x20]
    0x1beedc9a8 <+8>:  stp    x26, x25, [sp, #0x30]
    0x1beedc9ac <+12>: stp    x24, x23, [sp, #0x40]
    0x1beedc9b0 <+16>: stp    x22, x21, [sp, #0x50]
```

**Comment by darshankawar** [comment]
@NSLogZfRee 
Do you have reproducible code sample along with steps to replicate that triggers the reported crash ?
Also, see if [this](https://github.com/firebase/flutterfire/issues/7462) is relatable to your case or not.

**Comment by NSLogZfRee** [comment]
[screenshot](https://img.ilingomate.com/file/0e61c1b6ec9872d452860aeb3c8d6a00.png)

**Comment by NSLogZfRee** [comment]
In the iOS version of our project, whenever it involves system push functionality, displaying local notifications or handling remote notifications, it crashes within FLTFirebaseMessagingPlugin.m. When I comment out all the code related to firebase_messaging, everything runs fine.

**Comment by NSLogZfRee** [comment]
> [screenshot](https://img.ilingomate.com/file/0e61c1b6ec9872d452860aeb3c8d6a00.png)

if (_originalNotificationCenterDelegate != nil &&
      _originalNotificationCenterDelegateRespondsTo.willPresentNotification) {
    [_originalNotificationCenterDelegate userNotificationCenter:center
                                        willPresentNotification:notification
                                          withCompletionHandler:completionHandler];
  }


The code first enters line 320: "if" statement, then executes the "forward" code. After that, it enters line 320: "if" statement and runs the "forward" code again. This creates a loop where the code keeps entering the "if" statement and executing the "forward" code repeatedly.

so, the main thread is stuck

**Comment by NSLogZfRee** [comment]
The issue occurs when we both import the mobpush_plugin and firebase_messaging. Our logic is to use mobpush in China and firebase in non-China regions. we cannot see the .m file for mobpush, I suspect that both plugins have implemented method swizzling for the - (void)userNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification method. The problem is resolved as long as we don't use both plugins simultaneously.
