### ISSUE TITLE
Flutter Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)

### ISSUE THREAD

**Issue by guns28** [firebase/flutterfire#11335]
Hi  community,

I recently upgraded my Flutter version, and after the upgrade, I encountered an issue that shows up when I start the app. I've tried various solutions I found online, but unfortunately, nothing seems to be working.

Here are some details about my setup:

- Flutter version: 3.10.6 (Channel: stable)
- Firebase packages:
    - firebase_core: 2.15.0
    - firebase_messaging: ^14.6.5
    - firebase_core_platform_interface: 4.8.0

Error Message:
```
2023-07-20 18:12:24.090413+0100 Runner[17167:85712] [VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
#0 FirebaseCoreHostApi.initializeCore (package:firebase_core_platform_interface/src/pigeon/messages.pigeon.dart:210:7)
<asynchronous suspension>
#1 MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:29:44)
<asynchronous suspension>
#2 MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:73:7)
<asynchronous suspension>
#3 Firebase.initializeApp (package:firebase_core/src/firebase.dart:43:31)
<asynchronous suspension>
#4 PushNotificationService.setUpFirebase (package:obiplus/services/push_nofitication_service.dart:40:5)
```

Here is the output of the `flutter doctor --verbose` command:

```
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.1 22C65 darwin-x64, locale fr)
    • Flutter version 3.10.6 on channel stable at /Users/macbook/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (8 days ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /Users/macbook/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc1
    • ANDROID_HOME = /Users/macbook/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

The error occurs in the following code block:

```dart
await Firebase.initializeApp(
  options: DefaultFirebaseOptions.currentPlatform,
);
```

Any assistance or insights into resolving this issue would be greatly appreciated. Thank you!

**Comment by danagbemava-nc** [comment]
Hi @guns28, thanks for filing the issue. 

Please provide a complete minimal reproducible code sample in a repo that we can clone so that we can investigate this issue. 

Thank you

**Comment by guns28** [comment]
Hi, it's a big project and I updated flutter  to the latest version and the
error popped up.
So I updated firebase to the latest version also but the error persisted.

**Comment by battlecook** [comment]
same issue here

**Comment by jnelle** [comment]
This error happens to me when I try to get the idToken from firebase auth

```dart
 @override
  Future<String> getIdToken({bool forceRefresh = false}) async {
    String? token = await _firebaseAuth.currentUser!.getIdToken(forceRefresh);
    return token!;
  }
  ```

**Comment by danagbemava-nc** [comment]
Hi @guns28, do you call the method in https://github.com/firebase/flutterfire/issues/11335#issuecomment-1646629847 in your project?

**Comment by guns28** [comment]
@danagbemava-nc no i'm calling this method : 
`      final _token = await FirebaseMessaging.instance.getToken();
`
but the error occur when i call : 
`await Firebase.initializeApp(
  options: DefaultFirebaseOptions.currentPlatform,
);`

thx.

**Comment by danagbemava-nc** [comment]
Hi @guns28, can you share a minimal reproducible code sample in a repo that we can clone to see if we can repro?

**Comment by HieuNghiemViet** [comment]
I had the same issue

**Comment by ams770** [comment]
is there any solution? I'm facing the same bug on ios devices but android is working well

**Comment by guns28** [comment]
> is there any solution? I'm facing the same bug on ios devices but android is working well

i downgraded the flutter version for now.

**Comment by ams770** [comment]
Thank you for your attention,
I removed the iOS folder from my project, followed by creating a new one with the same Bundle ID, then I re-registered the iOS project on Firebase.
now it's working with no issues.

**Comment by ams770** [comment]
> > is there any solution? I'm facing the same bug on ios devices but android is working well
> 
> 
> 
> i downgraded the flutter version for now.

Thank you for your attention,
I removed the iOS folder from my project, followed by creating a new one with the same Bundle ID, then I re-registered the iOS project on Firebase.
now it's working with no issues.
