### ISSUE TITLE
[firebase_messaging]: onBackgroundMessage must be woken up with 1 Notification first, then it works. On Terminated.

### ISSUE THREAD

**Issue by blakewood84** [firebase/flutterfire#11336]
This is for when the app is terminated. The onBackgroundMessage listener doesn't seem to be executing my function on the first notification. It's like it has to be woken up first. The 2nd + notifications seem to work fine.

### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you aware of the differences between iOS and Android background message handling?

- [X] I understand that iOS and Android background messages behave differently, and I've designed my application with that in mind.

### Do you have an active Apple Developer account?

- [X] I have an active Apple Developer account.

### Are you using a physical iOS device to test background messages?

- [X] I am using a physical iOS device to test background messages.

### Have you enabled "Remote Notifications" & "Background Mode" (Checking options for "Background Processing" & "Remote Notifications") in your app's Xcode project?

![Screen Shot 2023-07-20 at 12 30 57 PM](https://github.com/firebase/flutterfire/assets/60270366/87d30106-bae6-4d4d-9f35-0ba712affe02)

### Have you created an APNs key in your Apple Developer account & uploaded this APNs key to your Firebase console?

![Screen Shot 2023-07-20 at 12 32 12 PM](https://github.com/firebase/flutterfire/assets/60270366/644eaa50-9fe7-4f66-9818-a8585d184787)

### Have you disabled method swizzling for Firebase in your app?

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CADisableMinimumFrameDurationOnPhone</key>
	<true/>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleDisplayName</key>
	<string>Timesheet Mobile</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>timesheet_mobile</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>com.googleusercontent.apps.398976455450-s8eica22a9lo8ilvnffg4gir5husu6b4</string>
			</array>
		</dict>
	</array>
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
	<key>FirebaseAppDelegateProxyEnabled</key>
	<true/>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>UIApplicationSupportsIndirectInputEvents</key>
	<true/>
	<key>UIBackgroundModes</key>
	<array>
		<string>fetch</string>
		<string>remote-notification</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
</dict>
</plist>
```

### Are you sending messages to your app from the Firebase Admin SDK?

```javascript
await admin.messaging().send({
  token: token,
  notification: {
    title,
    body,
  },
  // Data
  data: {
    ...dataObj,
  },
  // Android Settings
  android: {
    priority: "high",
  },
  // APNS (Apple) config
  apns: {
    payload: {
      aps: {
        contentAvailable: true,
      },
    },
    headers: {
      "apns-priority": "10",
    },
  },
});
```

### Have you requested permission from the user to receive notifications?

- [X] I have the relevant permission to receive notifications.

### Have you used the 'Console' application on your macOS device to check if the iOS device's system is throttling your background messages?

When I build my app in release mode and test, the first notification always doesn't go through, the second goes through fine.

```
default	13:05:04.123642-0700	dasd	Submitted Activity: com.apple.pushLaunch.rewired.timesheet.example:6152FD at priority 10 (Thu Jul 20 13:05:04 2023 - Fri Jul 21 13:05:04 2023)
default	13:05:04.130362-0700	dasd	com.apple.pushLaunch.rewired.timesheet.example:6152FD:[
	{name: ApplicationPolicy, policyWeight: 50.000, response: {Decision: Absolutely Must Proceed, Score: 1.00, Rationale: [{[appIsForeground]: Required:1.00, Observed:1.00},]}}
 ], FinalDecision: Absolutely Must Proceed}
default	13:05:04.131396-0700	dasd	[FBSSystemService][0x10bd] Sending request to open "rewired.timesheet.example"
default	13:05:04.215517-0700	dasd	Hit the server for a process handle 210b32a000016c6 that resolved to: [application<rewired.timesheet.example>:5830]
default	13:05:04.450002-0700	dasd	COMPLETED com.apple.pushLaunch.rewired.timesheet.example:6152FD at priority 10 <private>!
default	13:05:04.450074-0700	dasd	NO LONGER RUNNING com.apple.pushLaunch.rewired.timesheet.example:6152FD ...Tasks running in group [com.apple.dasd.defaultNetwork] are 2!
default	13:05:27.472704-0700	dasd	Submitted Activity: com.apple.pushLaunch.rewired.timesheet.example:35FE0B at priority 10 (Thu Jul 20 13:05:27 2023 - Fri Jul 21 13:05:27 2023)
default	13:05:27.479065-0700	dasd	com.apple.pushLaunch.rewired.timesheet.example:35FE0B:[
	{name: ApplicationPolicy, policyWeight: 50.000, response: {Decision: Absolutely Must Proceed, Score: 1.00, Rationale: [{[appIsForeground]: Required:1.00, Observed:1.00},]}}
 ], FinalDecision: Absolutely Must Proceed}
default	13:05:27.480249-0700	dasd	[FBSSystemService][0x72c] Sending request to open "rewired.timesheet.example"
default	13:05:27.613002-0700	dasd	COMPLETED com.apple.pushLaunch.rewired.timesheet.example:35FE0B at priority 10 <private>!
default	13:05:27.613040-0700	dasd	NO LONGER RUNNING com.apple.pushLaunch.rewired.timesheet.example:35FE0B ...Tasks running in group [com.apple.dasd.defaultNetwork] are 1!
```

### Additional context and comments

This is for when the app is terminated. The onBackgroundMessage listener doesn't seem to be executing my function on the first notification. It's like it has to be woken up first. The 2nd + notifications seem to work fine.

--

I get the Notification just fine always, but the code inside my **onBackgroundMessage** handler doesn't execute until the second time. I am using hive to store some data, but most importanly I am just wanting FlutterAppBadget to update the badge properly.

Here's how I am testing.

1. Build the app in release mode.
2. Open the app. Close the app, and kill it so it is terminated.
3. Send first notification. This doesn't work and does not show app badge count.
4. Send second notification. This does work and shows an app badge count.

Here is my code:

```dart
@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp();
  await Hive.initFlutter();
  final data = message.data;
  final docId = data['docId'];
  // Reviewer, Admin, Attention
  final type = data['type'];

  final boxName = switch (type) {
    'REVIEWER' => 'reviewer-notifications',
    'ADMIN' => 'admin-notifications',
    'ATTENTION' => 'attention-notifications',
    // "APPROVED" => 'approved-notifications',
    _ => ''
  };

  if (boxName.isNotEmpty) {
    final box = Hive.isBoxOpen(boxName) ? Hive.box<String>(boxName) : await Hive.openBox<String>(boxName);
    await box.put(docId, docId);
    final count = await _checkAppBadgeCount();
    await FlutterAppBadger.updateBadgeCount(count);
  }
}

```

I've also tried removing my code and just doing the following:

```dart
@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await FlutterAppBadget.updateBadgeCount(1);
}

```

Nothing shows for the badge count until the second notification. 

It seems whenever I open the app and close it, it only works after the second notification goes through.

Any help to solve this so my code is ran on the first notification?

**Comment by danagbemava-nc** [comment]
Hi @blakewood84, what plugin are you using to display the badges? Could this perhaps be an issue with the plugin? In the initial code with the hive, is there a way for you to check if it executes all the time?

**Comment by blakewood84** [comment]
hey @danagbemava-nc , I'm using FlutterAppBadger: https://pub.dev/packages/flutter_app_badger

Is there a decent way to test this onBackgroundMessage handler is being ran if I remove my code in there and just see if it's running properly?

So far it never runs the first notification, it like it has to be "woken up" first.

**Comment by blakewood84** [comment]
Update, I took all of my code out and added a print statement to the  onBackgroundMessage handler:


```dart
@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  print('Running background message handler!');
}
```

I used the Console.app to monitor any logs being sent out. On first notification nothing, on second notification I saw the print statement. This was when the app was terminated.

**Comment by danagbemava-nc** [comment]
Hi @blakewood84, I think you might be hitting https://github.com/firebase/flutterfire/issues/7407 can you take a look at it to see if your case is similar to it?

**Comment by blakewood84** [comment]
hey @danagbemava-nc , seems like this is a similar issue 😏 Main is indeed ran once to start up the app, but then the `onBackgroundMessage` listener is used as long as I don't open the app.

**Comment by danagbemava-nc** [comment]
Hi @blakewood84, according to the documentation, it seems like if the app is terminated, you will need to start the app before the onBackgroundMessage starts working again. See https://firebase.google.com/docs/cloud-messaging/flutter/receive. It is stated in the second bullet point

Do you terminate the app by removing it from the app switcher?

**Comment by blakewood84** [comment]
@danagbemava-nc Yep, I terminate the app by removing it from the app switcher. I guess this still doesn't make sense to me in the documentation. We need a way to make it a bit more clear how to perform logic like app badges when the app terminated. The user will most likely close their apps in the App Switcher to preserve battery life. It's apparent now that the app must be started first. Maybe we should add some more documentation to make things a little clearer? I'd be happy to help.

**Comment by danagbemava-nc** [comment]
I think more documentation might be better. Please feel free

**Comment by russellwheatley** [comment]
I was not able to reproduce this. I used the [sending message logic](https://github.com/firebase/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/example/scripts/send-message.js) for the example app, and your own sending message logic in the issue. I always received the notification after terminating the app. 

To be clear, you are not seeing the notification appear at the top of your phone screen after sending?

**Comment by blakewood84** [comment]
@russellwheatley Hey, thanks for the response. I am seeing the notifications at the top pop up as well each time, this was never an issue for me.

Hey guys I am going to go ahead and close this issue because I am implementing sending a blank notification first to wake up the app so my `onBackgroundMessage` handler can perform some logic like using `FlutterAppBadger` and saving to local storage.
