### ISSUE TITLE
 [firebase_auth] [firebase_messaging] Conflict ? getting notification-not-forwarded error

### ISSUE THREAD

**Issue by galvin59** [firebase/flutterfire#11330]
Hi

I have been using firebase_auth with phone authentication / OTP without any problem
I receive the SMS, without Recaptcha, meaning the silent notification sending seems to work

But as soon as 
- I add firebase_messaging in pubspec.yaml, 
- I do "pod update Firebase/CoreOnly" (which is asked by xcode during next build)

The OTP SMS is not sent anymore :(
I get a "notification-not-forwarded" error in the verificationFailed handler, with the following message : " if app delegate swizzling is disabled, remote notifications received by uiapplicationdelegate need to be forwarded to firauth's canhandlenotificaton: method."

Swizzling however is enabled afaik, I did not set the FirebaseAppDelegateProxyEnabled flag

Any idea ?
That problem has driven me mad for the last few hours 😭

Thanks a lot

Julien

firebase_auth: ^4.1.0
firebase_messaging: ^14.6.5

**Comment by danagbemava-nc** [comment]
Hi @galvin59, can you upgrade to the latest version of firebase_auth to see if you still face this issue? 

Would it also be possible for you to provide a complete minimal reproducible code sample in a repo that we can clone to see if we can reproduce the issue?

Thank you

**Comment by galvin59** [comment]
Hi again
I made a sample test, with only those two libraries, and indeed it is working
My project is much more complex and I can't see how to find the origin of the problem ... 
If you have some ideas about where to look, I would be happy to hear about them before closing that ticket 🙄
Thanks again

**Comment by danagbemava-nc** [comment]
Can you cross-check the configuration of the sample app with that of your main project?

**Comment by galvin59** [comment]
you mean the firebase configuration ? the google-services.json file ?

**Comment by danagbemava-nc** [comment]
Both and try to see if any steps might have been missed in the initial setup of the app
