### ISSUE TITLE
🐛 [cloud_firestore_odm] Support Sets as well as Lists for query method generation

### ISSUE THREAD

**Issue by Rexios80** [firebase/flutterfire#11344]
## Bug report

**Describe the bug**
I want to enforce item uniqueness, but the query methods don't generate for Sets

### Steps to reproduce

1. Create an ODM model with a Set in it
2. Run the generator
3. See that there is no query method for the Set

### Expected behavior
Should there be a generated query method?

### Sample project

```dart
@firestoreSerializable
class ClassWithSet {
  /// Query method `whereItems` will not generate
  final Set<String> items;
}

@firestoreSerializable
class ClassWithList {
  /// Query method `whereItems` will generate
  final List<String> items;
}
```

---

## Additional context

Maybe we should generate the query method for all iterables? They should serialize to a JSON list anyways.

**Comment by rrousselGit** [comment]
I can see some value in that.

**Comment by rrousselGit** [comment]
I disagree with the title change.

I do not think we should support `Iterable` itself. List/Set are fine because they have a finite length. But an Iterable could literally never end
