### ISSUE TITLE
🐛 [firebase_crashlytics] Getting build errors

### ISSUE THREAD

**Issue by vatsa1101** [firebase/flutterfire#11359]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkProductionReleaseAarMetadata'.
> Could not resolve all files for configuration ':app:productionReleaseRuntimeClasspath'.
   > Could not find any version that matches com.google.firebase:firebase-sessions:[15.0.0, 16.0.0).
     Versions that do not match: 1.0.0
     Required by:
         project :app > project :firebase_crashlytics > com.google.firebase:firebase-crashlytics:18.4.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by danagbemava-nc** [comment]
Hi @vatsa1101, please provide a complete minimal reproducible code sample in a repo that we can clone so that we can investigate this issue.

What version of flutter, firebase_core & firebase_crashlytics are you using? 

Do you also have this issue with the plugin example app?

**Comment by jay-7span** [comment]
I am having the same issue.
Below are version details:

flutter: 3.13.1
firebase_crashlytics: ^3.3.5
firebase_messaging: ^14.6.7
firebase_core: ^2.15.1

**Comment by danagbemava-nc** [comment]
Hi @jay-7span, kindly file a new issue and provide all the relevant information required to reproduce
