### ISSUE TITLE
🐛 [firebase] Xcode build fails

### ISSUE THREAD

**Issue by gbijwe** [firebase/flutterfire#11367]
## Bug report

I made a simple Flutter app using Firebase to handle Google Authorization. The app builds and works well on Android, without any glitches. However, the app crashes on iOS simulator after I click on the log in button and throws this error. And it fails to build on a physical iPad at all.

When I try to launch the app using Android Studio, it gives me error as follows: 

<details> <summary>Android Studio build fail report</summary>

```
Launching lib/main.dart on iPad (2) in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: LZ7386N87A
Running Xcode build...
Xcode build done.                                           34.8s
Failed to build iOS app
Could not build the precompiled application for the device.
Error (Xcode): No profiles for 'com.example.day4' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.example.day4'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.
/Users/gauravbijwe/StudioProjects/day4/ios/Runner.xcodeproj


It appears that there was a problem signing your application prior to installation on the device.

Verify that the Bundle Identifier in your project is your signing id in Xcode
  open ios/Runner.xcworkspace

Also try selecting 'Product > Build' to fix the problem.

Error launching application on iPad (2).
```
</details>

------

### Expected behavior

After I click the log in button, it should ask me for my Google account details, and after successful sign in, it should display my google id profile picture and email address.

### Sample project

Here is the link to my repository. 
https://github.com/gbijwe/day4
---

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.3, on macOS 13.4.1 22F770820d darwin-arm64,
    locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.80.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 3.0.3
Flutter SDK 3.10.3
day4 0.1.0

dependencies:
- firebase_auth 4.7.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.15.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection js material_color_utilities meta vector_math sky_engine]
- google_sign_in 6.1.4 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]

dev dependencies:
- flutter_lints 2.0.2 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection js matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- _flutterfire_internals 1.3.4 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- collection 1.17.1
- fake_async 1.3.1 [clock collection]
- firebase_auth_platform_interface 6.16.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.6.1 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser js meta]
- firebase_core_platform_interface 4.8.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.6.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- google_identity_services_web 0.2.1 [js meta]
- google_sign_in_android 6.1.18 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.6.2 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.4.1 [flutter plugin_platform_interface quiver]
- google_sign_in_web 0.12.0+2 [flutter flutter_web_plugins google_identity_services_web google_sign_in_platform_interface http js]
- http 1.1.0 [async http_parser meta]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- js 0.6.7 [meta]
- lints 2.1.1
- matcher 0.12.15 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.2.0
- meta 1.9.1
- path 1.8.3
- plugin_platform_interface 2.1.5 [meta]
- quiver 3.2.1 [matcher]
- sky_engine 0.0.99
- source_span 1.9.1 [collection path term_glyph]
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.5.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.2 [collection]
- vector_math 2.1.4
```

</details>

---

**Comment by danagbemava-nc** [comment]
Hi @gbijwe, have you completed the setup for the google_sign_in package? See the readme here https://pub.dev/packages/google_sign_in

Please also note that to run the app on a physical device you need to have an apple developer account linked to the project.

**Comment by gbijwe** [comment]
> Hi @gbijwe, have you completed the setup for the google_sign_in package? See the readme here https://pub.dev/packages/google_sign_in
> 
> Please also note that to run the app on a physical device you need to have an apple developer account linked to the project.

I completed the setup using the readme. I had used `flutterfire configure`. However, using the above steps still does not solve the issue. When I build using Xcode it is giving me 55 errors and over 300 warnings. In android studio, when I run the app on a virtual iPhone, the app builds and launches, only to crash when I click log in. 

So, what should I do? Is this an issue with xcode, or I am just doing something very wrong here. I am very new to this world of flutter and have very little knowledge.

**Comment by danagbemava-nc** [comment]
Hi @gbijwe, kindly share the full output of `flutter run -v`. The output may be large so kindly put it into a .log/.txt file or put it in pastebin and share the link here. 

Thank you

**Comment by gbijwe** [comment]
> Hi @gbijwe, kindly share the full output of `flutter run -v`. The output may be large so kindly put it into a .log/.txt file or put it in pastebin and share the link here.
> 
> Thank you

https://pastebin.com/KfSi1R42

**Comment by danagbemava-nc** [comment]
Hi @gbijwe, please run `flutter run -v` in your project directory and share those logs

**Comment by gbijwe** [comment]
> Hi @gbijwe, please run `flutter run -v` in your project directory and share those logs

https://pastebin.com/R3Est7uz

Apologies for the error. 
Also, is it okay for me to share the data of my directories on here?

**Comment by danagbemava-nc** [comment]
Hi @gbijwe, the logs you provided show that you tried to run on macOS whereas you reported that you're having the issue on iOS. Please provide the logs with you targeting an iOS device. 

> Also, is it okay for me to share the data of my directories on here?
Yes, but you may want to redact any sensitive information you have in there.

**Comment by danagbemava-nc** [comment]
> The error message from simulator after app crashes at google auth: [pastebin.com/W30xDZWH](https://pastebin.com/W30xDZWH)

Regarding this, please make sure you have completed the setup process for iOS from the google_sign_in. The point at which it is crashing usually indicates that you may not have done step 8 in the setup. 

> the logs targeting an iOS device (simulator) are: [jpst.it/3jZYs](https://jpst.it/3jZYs)
Regarding this, kindly check https://stackoverflow.com/questions/70760326/flutter-on-ios-redefinition-of-module-firebase to see if any of the comments help. If it does not help, please provide a complete minimal reproducible code sample in a repo we can clone so that we can investigate this issue. The repo you linked above is not accessible

**Comment by gbijwe** [comment]
> > The error message from simulator after app crashes at google auth: [pastebin.com/W30xDZWH](https://pastebin.com/W30xDZWH)
> 
> Regarding this, please make sure you have completed the setup process for iOS from the google_sign_in. The point at which it is crashing usually indicates that you may not have done step 8 in the setup.
> 
> > the logs targeting an iOS device (simulator) are: [jpst.it/3jZYs](https://jpst.it/3jZYs)
> > Regarding this, kindly check https://stackoverflow.com/questions/70760326/flutter-on-ios-redefinition-of-module-firebase to see if any of the comments help. If it does not help, please provide a complete minimal reproducible code sample in a repo we can clone so that we can investigate this issue. The repo you linked above is not accessible

https://github.com/gbijwe/day4
This should be good to replicate after you run flutterfire configure in the terminal.

**Comment by danagbemava-nc** [comment]
Hi @gbijwe, did you add firebase dependencies to the firebase project in Xcode?

**Comment by gbijwe** [comment]
> Hi @gbijwe, did you add manually firebase dependencies to the firebase project in Xcode?

No, I did not. Am I supposed to? I thought flutterfire configure took care of everything

**Comment by danagbemava-nc** [comment]
No, you're not supposed to but I see Firebase dependencies in your project when I open it in XCode and the error that you're getting happens when you have manually added the native iOS dependencies. See https://stackoverflow.com/questions/70760326/flutter-on-ios-redefinition-of-module-firebase

**Comment by gbijwe** [comment]
> No, you're not supposed to but I see Firebase dependencies in your project when I open it in XCode and the error that you're getting happens when you have manually added the native iOS dependencies. See https://stackoverflow.com/questions/70760326/flutter-on-ios-redefinition-of-module-firebase

I tried out the solution and now the build is successful, however, it again crashes as it did previously.

**Comment by danagbemava-nc** [comment]
Have you added the `CFBundleURLTypes` to your `Info.plist`? You can see how to set that up in the ReadMe for the google_sign_in package. https://pub.dev/packages/google_sign_in
