### ISSUE TITLE
🐛 [remote_config]: many [firebase_remote_config/internal] exceptions

### ISSUE THREAD

**Issue by r-i-c-o** [firebase/flutterfire#11371]
## Bug report
Remote config is throwing exceptions.
On Android message is simple: ```[firebase_remote_config/internal] internal remote config fetch error```, so we don't know what causes the problem.
On iOS exceptions are more verbose, most of them have this structure:
```
[firebase_remote_config/internal] Failed to get installations token. 
Error : Error Domain=com.firebase.installations 
Code=0 "Underlying error: Вероятно, соединение с интернетом прервано." 
UserInfo={
    NSLocalizedFailureReason=Underlying error: Вероятно, соединение с интернетом прервано., 
    NSUnderlyingError=0x282d6d1d0 {
        Error Domain=NSURLErrorDomain 
        Code=-1009 "Вероятно, соединение с интернетом прервано." 
        UserInfo={
            _kCFStreamErrorCodeKey=50, 
            NSUnderlyingError=0x282d08e10 {
                Error Domain=kCFErrorDomainCFNetwork 
                Code=-1009 "(null)" 
                UserInfo={
                    _kCFStreamErrorDomainKey=1, 
                    _kCFStreamErrorCodeKey=50, 
                    _NSURLErrorNWResolutionReportKey=Resolved 0 endpoints in 1ms using unknown from cache, 
                    _NSURLErrorNWPathKey=unsatisfied (Denied over cellular interface), 
                    interface: pdp_ip0[lte], ipv4, dns, expensive
                }
            }, 
        }
    }
}
```
We understand that users may have connectivity problems, but not that much (>2600 exceptions in the past month).
Is this behavior expected? Or our setup is incorrect? A sample is attached below.

### Expected behavior
Not this much exceptions.

### Sample project
This is the simplified setup we have.
```
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  try {
    await _remoteConfig.setDefaults(defaults);
    await _remoteConfig.setConfigSettings(
      RemoteConfigSettings(
        fetchTimeout: const Duration(seconds: 5),
        minimumFetchInterval: const Duration(minutes: 5),
      ),
    );
    await _remoteConfig.fetchAndActivate().timeout(const Duration(seconds: 5));
  } catch (exception) {
    logException(exception);
  }
  runApp(App());
}
```

---

## Additional context

In addition, app is making requests from Russia. If this can cause problem, please leave a comment with possible fix.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel stable, 3.10.4, on Microsoft Windows [Version 10.0.19045.3208], locale ru-RU)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.4)
[√] Android Studio (version 2022.1)
[√] IntelliJ IDEA Community Edition (version 2022.3)
[√] Connected device (3 available)
[√] Network resources

```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the report @r-i-c-o 
As the error says (translated to English for readability):

`The internet connection is probably interrupted.`

The error code thrown is `Code=-1009` which indicates an issue with the internet connection that appears to be offline, so that means it is not an issue / bug in the plugin code, but could be occuring due to network connection at your end.

Also, you may take a look at https://firebase.google.com/docs/remote-config/loading and specially:

`Don't rely on network connectivity to obtain Remote Config values. Do set in-app default parameter values so that your app always behaves as expected. You can periodically keep app and Remote Config backend default values in sync using [downloaded template defaults](https://firebase.google.com/docs/remote-config/templates#download_template_defaults).`

And see if it helps in your case or not. Also, as mentioned above, this doesn't seem to be an issue with the plugin.

**Comment by r-i-c-o** [comment]
Thank you for answer, @darshankawar. I've sent a report to the Firebase support.
If it's OK with you, I would keep this ticket opened for now. I will close it if and when it's resolved or I get any information from the Firebase team via the support ticket.

**Comment by r-i-c-o** [comment]
It seems like there is nothing wrong with our setup or with Remote config plugin. Thus I close the issue.

**Comment by pascalfriedrich** [comment]
We have the same issue. @r-i-c-o any information about this topic from firebase?
