### ISSUE TITLE
[📚][firebase_auth] When is the result of `User.getIdToken` null?

### ISSUE THREAD

**Issue by blaugold** [firebase/flutterfire#11386]
The result of `User.getIdToken` was recently made nullable, but I cannot find any information under which circumstances `null` is returned. The SDKs for the other platforms all seem to use a non-nullable return type.

Looking into this a bit further, most of the fields of [`IdTokenResult`](https://pub.dev/documentation/firebase_auth_platform_interface/latest/firebase_auth_platform_interface/IdTokenResult-class.html) are not nullable on the other platforms (for example [Web](https://firebase.google.com/docs/reference/node/firebase.auth.IDTokenResult)) as well.

**Comment by Lyokone** [comment]
The token can be null for instance on the Android platform: https://firebase.google.com/docs/reference/android/com/google/firebase/auth/GetTokenResult
