### ISSUE TITLE
Implement Auth.revokeToken method to support Sign in with Apple token revocation

### ISSUE THREAD

**Issue by peterfriese** [firebase/flutterfire#11396]
As of [version 10.8.0](https://firebase.google.com/support/release-notes/ios#version_1080_-_april_11_2023), Firebase for Apple platforms support token revocation for Sign in with Apple (see the [documentation](https://firebase.google.com/docs/auth/ios/apple#token_revocation)).

Apps that offer account creation, must also provide users with a way to delete their account (and revoke the associated tokens) from within the app. 

To allow Flutter developers to use this API, it should be exposed (looks like [FLTFirebaseAuthPlugin.m](https://github.com/firebase/flutterfire/blob/master/packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m) might be a good place to put it).

See [this comment](https://github.com/firebase/firebase-ios-sdk/issues/9906#issuecomment-1518134941) on the Apple SDK repo for a person requesting this

_Originally posted by @peterfriese in https://github.com/firebase/flutterfire/discussions/10827_

**Comment by ChiaraMC** [comment]
Hey @darshankawar I noticed that this was tagged as `platform: ios` is there no plan to support this for android? Firebase supports apple sign in on Android (and the sign in part currently does work on Flutter) so would be nice to be able to use that option

**Comment by darshankawar** [comment]
Thanks for pointing that out @ChiaraMC . Updated the label.

**Comment by ChiaraMC** [comment]
Thank @darshankawar! By the way, I think this is a duplicate of https://github.com/firebase/flutterfire/issues/11065

**Comment by darshankawar** [comment]
Yes. Closing this in favor of the linked issue. Will add android label to it for correct status.
