### ISSUE TITLE
[📚][firebase_auth] sendEmailVerification needs DynamicLinks config to work in ios

### ISSUE THREAD

**Issue by luisgurmendez** [firebase/flutterfire#11390]
I was getting `internal-error` when calling `sendEmailVerification` on ios, after a lot of debugging and network inspection I found that the actual error was:
```
"message": "DYNAMIC_LINK_NOT_ACTIVATED : FDL domain is not configured"
```
What confused me at first was that in android it worked fine. I'm still trying to understand why is this required for ios but nor for android, and more so, why is this needed for email verification? Also, the firebase console says that DynamicLinks is not recommended anymore so it's even more confusing.

**Comment by erdzan12** [comment]
The same happens for us, where we explicitly did not enable FDL as they are deprecated, and we get the issue on iOS

**Comment by yukihiro-numata** [comment]
We have encountered an issue that seems to be a bug. The versions we are using are as follows:
```
firebase_core: 2.13.1  
firebase_auth: 4.6.2  
```
 
We created a Firebase Dynamic Link in the Firebase Console and can now receive emails. However, the link contained in the email is incorrect. It includes the Firebase Dynamic Link we created as a parameter in the continue URL, as shown below:
```
https://example.com?mode=verifyEmail&oobCode=XXX&apiKey=XXX&continueUrl=https%3A%2F%2Fexample.page.link%3Flink%3Dhttps%3A%2F%2Fexample.com%2Fverify_email%3FuserUuid%2XXX%3Dcom.example%26ifl%3Dhttps%3A%2F%2Fexample.com%2Fverify_email%3FuserUuid%2&lang=ja   
 ```

Additionally, the link changes when we toggle the 'handleCodeInApp' option in 'ActionCodeSettings'. In the link provided above, 'handleCodeInApp' is set to 'false'. When it is toggled to 'true', the link changes to the format shown below:
```
https://example.page.link?link=https://example.com?apiKey%3%26mode%3DverifyEmail%26oobCode%3%26continueUrl%3Dhttps://example.com?userUuid%2XXX%26lang%3Dja&ibi=com.example&ifl=https://example.com?apiKey%3XXX%26mode%3DverifyEmail%26oobCode%3XXX%26continueUrl%3Dhttps://example.com?userUuid%2XXX%26lang%3Dja  
```

**Comment by TarekkMA** [comment]
Closing this in favor of this #12666.
