### ISSUE TITLE
🐛 [cloud_firestore] Support accessing non-default databases

### ISSUE THREAD

**Issue by puf** [firebase/flutterfire#11414]
## Bug report

**Describe the bug**

In iOS, Android, and Web code it is now possible to access non-default Firestore database instances by passing the database ID to the call that gets the Firestore instance. This feature should be available in Flutter code too.

---

## Additional context

For web, see: https://firebase.google.com/docs/reference/js/firestore_.md#getfirestore  
```
export declare function getFirestore(app: FirebaseApp, databaseId: string): Firestore;
```
For Android, see https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/FirebaseFirestore#getInstance(com.google.firebase.FirebaseApp,java.lang.String)
```
public static @[NonNull](https://developer.android.com/reference/kotlin/androidx/annotation/NonNull.html) [FirebaseFirestore](https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/FirebaseFirestore) [getInstance](https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/FirebaseFirestore#getInstance(com.google.firebase.FirebaseApp,java.lang.String))(@[NonNull](https://developer.android.com/reference/kotlin/androidx/annotation/NonNull.html) [FirebaseApp](https://firebase.google.com/docs/reference/android/com/google/firebase/FirebaseApp) app, @[NonNull](https://developer.android.com/reference/kotlin/androidx/annotation/NonNull.html) [String](https://developer.android.com/reference/kotlin/java/lang/String.html) database)
```

For iOS, see: https://firebase.google.com/docs/reference/swift/firebasefirestore/api/reference/Classes/Firestore#firestoredatabase:
```
class func firestore(database: String) -> Self
```

**Comment by russellwheatley** [comment]
We have already released support for 2nd Firestore database. This should've been closed when we merged this PR: https://github.com/firebase/flutterfire/pull/11310
