### ISSUE TITLE
🐛 [firebase_messaging] Foreground notifications doesn't fire onMessage event listener without fetching token prior to receiving

### ISSUE THREAD

**Issue by maks** [firebase/flutterfire#11410]
This is to reopen #6011 (hence the same issue title) which was prematurely closed because the exact behaviour is still completely reproducible for me sending messages using the "Send test message" button in the Friebase console which requires you to supply the FCM token of the device you are sending to and latest versions of:
```
firebase_core: ^2.15.0
firebase_messaging: ^14.6.5
```
running on an Android Emulator with Android 13 image with Google Play services.

It can be easily reproduced in a freshly created, slightly [modified version of the counter app as in this repo](https://github.com/maks/ff_fcm_bug).

The observed behaviour is as per the original bug report: if you send a test message to the specific device token, **nothing** is delivered from the ` FirebaseMessaging.onMessage` stream, **as soon** as you call `FirebaseMessaging.instance.getToken()`, in my demo app via pressing the FAB, the stream immediately emits the sent notification (I just debug print it in the repro app).

Would be great if you could have a look at this @russellwheatley as you said you weren't able to repo this on the previous issue comments.

**Comment by danagbemava-nc** [comment]
I can reproduce the issue using the steps below

- Setup a project for firebase messaging
- Use the code sample from https://github.com/maks/ff_fcm_bug
- Run the app on android
- Use the firebase console to push a message and specify the app that you created as the target
- Observe the logs 

After waiting for a couple of minutes, the notification never came but after tapping the FAB to get the token, the message I had sent earlier came within a few minutes
