### ISSUE TITLE
🐛 [ firebase_dynamic_links] Your issue title here

### ISSUE THREAD

**Issue by Ramghosh16RG** [firebase/flutterfire#11419]
## Bug report

**Describe the bug**
A clear and concise description of what the bug is. to fix this error, you need to configure the Dynamic Links domain for your project. You can do this in the Firebase Console. Once you have configured the domain, you should be able to send email verification links without any errors.

### Steps to reproduce

Here are the steps on how to configure the Dynamic Links domain for your project:

1)  Go to the Firebase Console.
2)  Click on the "Dynamic Links" tab.
3)  Click on the "Domain settings" tab.
4)  Enter the domain name for your project.
5)  Click on the "Save" button.

### Expected behavior

The expected behavior for the problem is that the email verification link should be able to open the user's app on iOS without any errors.

When you send an email verification link to a user, Firebase will use Dynamic Links to open the link in the user's app, regardless of the platform. If the Dynamic Links domain for your project is configured, then Firebase will be able to create the link and open it in the user's app.

However, if the Dynamic Links domain for your project is not configured, then Firebase will not be able to create the link. This will cause the error message "DYNAMIC_LINK_NOT_ACTIVATED : FDL domain is not configured".

The expected behavior is that the error message should not be displayed. The email verification link should be able to open the user's app on iOS without any errors.

Here are some possible reasons why the error message is being displayed:

The Dynamic Links domain for your project is not configured.
The Dynamic Links domain for your project is configured incorrectly.
There is a problem with the Firebase SDK.
To fix the error, you need to configure the Dynamic Links domain for your project. You can do this in the Firebase Console. Once you have configured the domain, you should be able to send email verification links without any errors.

If you are still getting the error message after configuring the domain, then you can try the following:

Check the Dynamic Links domain for your project to make sure that it is configured correctly.
Update the Firebase SDK to the latest version.
File a bug report with the Firebase team.

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Sure, here is a sample project that demonstrates the issue:

import UIKit
import Firebase

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()

        // Create a Dynamic Link with the email verification URL.
        let link = DynamicLink(url: URL(string: "https://www.example.com/email-verification")!,
                                options: DynamicLinkOptions(domain: "your-domain.firebaseapp.com"))

        // Send the Dynamic Link to the user.
        let email = "user@example.com"
        link.sendEmailVerification(to: email) { (error) in
            if let error = error {
                // Handle the error.
                print(error)
            } else {
                // The email verification link was sent successfully.
                print("Email verification link sent successfully.")
            }
        }
    }
}

Please link to the public repository URL.
https://github.com/Ramghosh16RG/Empty-Firebase-Project
---

## Additional context

The problem is specific to iOS. On Android, the Dynamic Links domain is not required for email verification.
The problem is caused by the fact that the Dynamic Links domain for the project is not configured.
The error message "DYNAMIC_LINK_NOT_ACTIVATED : FDL domain is not configured" is displayed when the Dynamic Links domain is not configured.
The problem can be fixed by configuring the Dynamic Links domain for the project.
The Dynamic Links domain can be configured in the Firebase Console.
Once the Dynamic Links domain is configured, the error message should no longer be displayed.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.4.1 21F79 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Ultimate (version 2021.3.2)
[✓] VS Code (version 1.66.2)
[✓] Connected device (1 available)

• No issues found!
<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```
✓] Flutter (Channel stable, 2.10.4, on macOS 12.4.1 21F79 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Ultimate (version 2021.3.2)
[✓] VS Code (version 1.66.2)
[✓] Connected device (1 available)

• No issues found!

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:
# This file lists all of the direct and indirect dependencies of your project.
# It can be used to rebuild your project's package dependencies and
# to generate documentation for your project.

# To learn more about this file, see:
# https://dart.dev/tools/pub/dependencies

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  firebase_auth: ^3.3.7
  firebase_core: ^1.12.0

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```
# This file lists all of the direct and indirect dependencies of your project.
# It can be used to rebuild your project's package dependencies and
# to generate documentation for your project.

# To learn more about this file, see:
# https://dart.dev/tools/pub/dependencies

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  firebase_auth: ^3.3.7
  firebase_core: ^1.12.0
</details>

---

**Comment by danagbemava-nc** [comment]
Hi @Ramghosh16RG, are you responding to a particular issue or reporting an issue? If the former, please comment on that issue instead. If the latter, kindly update your issue description with the required information so that it may be properly addressed.

Thank you
