### ISSUE TITLE
[📚] Your documentation feedback title (Firebase Dynamic Links Domain Not Configured Error on iOS)

### ISSUE THREAD

**Issue by Ramghosh16RG** [firebase/flutterfire#11418]
Please describe your documentation issue or suggested improvement in detail here and provide links to any pre-existing/relevant documentation and screenshots if necessary:

The error message "DYNAMIC_LINK_NOT_ACTIVATED : FDL domain is not configured" means that the Dynamic Links domain for your project is not configured. This is required for iOS, but not for Android.

Dynamic Links are a feature of Firebase that allow you to create links that can open your app on any platform. When you send an email verification link to a user, Firebase will use Dynamic Links to open the link in the user's app, regardless of the platform.

If the Dynamic Links domain for your project is not configured, then Firebase will not be able to create the link. This will cause the error message that you are seeing.

To fix this error, you need to configure the Dynamic Links domain for your project. You can do this in the Firebase Console. Once you have configured the domain, you should be able to send email verification links without any errors.

As for why Dynamic Links are not recommended anymore, it is because Firebase has a new feature called App Links. App Links are a more modern and secure way to open your app on any platform. If you are not using Dynamic Links for anything else, then you can safely disable them.

Here are the steps on how to configure the Dynamic Links domain for your project:

Go to the Firebase Console.
Click on the "Dynamic Links" tab.
Click on the "Domain settings" tab.
Enter the domain name for your project.
Click on the "Save" button.
Once you have configured the domain, you should be able to send email verification links without any errors.

I hope this helps!

**Comment by danagbemava-nc** [comment]
Hi @Ramghosh16RG, are you responding to a particular issue or reporting an issue with the documentation? If the former, please comment on that issue instead. If the latter, kindly share which part of the documentation you are reporting the issue with. Your issue as it stands now is not clear on what it is trying to achieve.

Thank you
