### ISSUE TITLE
🐛 [firebase_core] Web-App crashes with "NoSuchMethodError: method not found: 'gB5' on null"

### ISSUE THREAD

**Issue by chrisDK1977** [firebase/flutterfire#11426]
calling await Firebase.initializeApp(); in my WebApp crashes 

### Steps to reproduce

Call initFirebaseAndGetToken in the following class

```
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';

class MyFirebaseMessaging {

  Future<String?> initFirebaseAndGetToken() async {

    print('initializeApp');

    await Firebase.initializeApp();

    print('after initializeApp');

    FirebaseMessaging messaging = FirebaseMessaging.instance;

    print('before messaging.requestPermission');

    NotificationSettings? settings;

    try {
      settings = await messaging.requestPermission(
            alert: true,
            announcement: false,
            badge: true,
            carPlay: false,
            criticalAlert: false,
            provisional: false,
            sound: true,
          );
    } catch (e) {
      print(e);
    }

    if(settings == null){
      return null;
    }

    if (settings.authorizationStatus == AuthorizationStatus.authorized) {
      print('User granted permission');
    } else if (settings.authorizationStatus == AuthorizationStatus.provisional) {
      print('User granted provisional permission');
    } else {
      print('User declined or has not accepted permission');
    }

    return messaging.getToken();
  }

}
```
when calling 
```
  try {
    String? token = await MyFirebaseMessaging().initFirebaseAndGetToken();
    if(token != null) {
        ...
      }
  } catch (e) {
    print("error in loggedInCallback");
    print(e);
  }
```

I get

```
...
main.dart.js:42101 initializeApp
main.dart.js:42101 error in loggedInCallback
main.dart.js:42101 NoSuchMethodError: method not found: 'gB5' on null
```

### Expected behavior

The same as when build for android or ios

[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.19044.3086], locale de-DE)
    • Flutter version 3.10.5 on channel stable at C:\SDKs\[more...]
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (8 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\[more...]
    • Platform android-33-ext5, build-tools 33.0.2
    • Java binary at: C:\Program Files\[more...]
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\[more...]

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.5)
    • Visual Studio at C:\Program Files (x86)\[more...]
    • Visual Studio Community 2019 version 16.9.31229.75
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\[more...]
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at C:\Program Files\[more...]
    • Flutter plugin version 73.1.1
    • Dart plugin version 231.9065

[√] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19044.3086]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 115.0.5790.171
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 115.0.1901.188

[√] Network resources
    • All expected network resources are available.

**Comment by darshankawar** [comment]
Thanks for the report @chrisDK1977 
Can you provide what version of `firebase_core` and `firebase_messaging` are you using ? 
Also,  can you try using the [plugin example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example) and check if using it, you get same error as you reported ?
