### ISSUE TITLE
🐛 [firebase_auth] I am trying to setup MFA for my webapp but my exception is catching FirebaseAuthMultiFactorExceptionPlatform instead of FirebaseAuthMultiFactorException

### ISSUE THREAD

**Issue by HabaN3r0** [firebase/flutterfire#11449]
## Bug report

**Describe the bug**
I am trying to setup MFA for my webapp but my exception is catching FirebaseAuthMultiFactorExceptionPlatform instead of FirebaseAuthMultiFactorException. Issue here is FirebaseAuthMultiFactorExceptionPlatform does not have a MultiFactorResolver which means I cannot use the MultiFactor methods.

### Steps to reproduce

1. Enable SMS MFA on firebase console and setup MFA for a test account
2. use firebaseauth's signInWithEmailAndPassword and try catch FirebaseAuthMultiFactorException
3. FirebaseAuthMultiFactorExceptionPlatform is caught instead without the resolver component

### Expected behavior

Expected caught FirebaseAuthMultiFactorException

### Sample project

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 3.4.0-17.2.pre, on Microsoft Windows [Version 10.0.19045.3208], locale en-SG)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.21) 
[!] Android Studio (version 2020.3)
    X Unable to determine bundled Java version.
[!] Android Studio (version 2022.1)
    X Unable to find bundled Java version.
[√] VS Code (version 1.81.0)
[√] Connected device (3 available)
[√] HTTP Host Availability

! Doctor found issues in 2 categories.```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.19.0-146.2.beta
Flutter SDK 3.4.0-17.2.pre
owl_component_tests 1.0.0+1

dependencies:
- after_layout 1.2.0 [flutter]
- awesome_dialog 3.1.0 [flutter rive]
- beamer 1.5.6 [flutter flutter_web_plugins]
- build_runner 2.3.3 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- cupertino_icons 1.0.5
- data_table_2 2.3.7 [flutter async]
- dotted_border 2.0.0+3 [flutter path_drawing]
- dropdown_button2 2.1.4 [flutter meta]
- editable 2.0.0 [flutter]
- firebase_auth 4.7.2 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_auth_web 5.6.2 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser js meta]
- firebase_core 2.15.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_mobx 2.0.6+5 [flutter mobx]
- flutter_quill 6.1.6 [flutter collection flutter_colorpicker flutter_keyboard_visibility quiver tuple url_launcher pedantic characters diff_match_patch i18n_extension device_info_plus platform pasteboard]
- fluttertoast 8.2.2 [flutter flutter_web_plugins]
- google_fonts 4.0.4 [flutter http path_provider crypto]
- mobx 2.2.0 [meta]
- mobx_codegen 2.3.0 [analyzer build build_resolvers meta mobx path source_gen]
- provider 6.0.5 [collection flutter nested]
- responsive_sizer 3.1.1 [flutter]
- syncfusion_flutter_datagrid 20.3.52 [flutter syncfusion_flutter_core collection]
- syncfusion_flutter_signaturepad 20.3.52 [flutter syncfusion_flutter_core]

dev dependencies:
- flutter_lints 2.0.2 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- _fe_analyzer_shared 50.0.0 [meta]
- _flutterfire_internals 1.3.4 [collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer 5.2.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- args 2.4.1
- async 2.9.0 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.3.1 [analyzer async convert crypto glob logging meta path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.1.1 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.1.0 [analyzer async build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.2.7 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.6.1 [built_collection collection fixnum meta]
- characters 1.2.1
- checked_yaml 2.0.2 [json_annotation source_span yaml]
- clock 1.1.1
- code_builder 4.4.0 [built_collection built_value collection matcher meta]
- collection 1.16.0
- convert 3.1.1 [typed_data]
- crypto 3.0.2 [typed_data]
- dart_style 2.2.5 [analyzer args path pub_semver source_span]
- device_info_plus 7.0.1 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta win32]
- device_info_plus_platform_interface 6.0.1 [flutter meta plugin_platform_interface]
- diff_match_patch 0.4.1
- equatable 2.0.5 [collection meta]
- fake_async 1.3.1 [clock collection]
- ffi 2.0.2
- file 6.1.4 [meta path]
- firebase_auth_platform_interface 6.16.1 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_core_platform_interface 4.8.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.6.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- fixnum 1.0.1
- flutter_colorpicker 1.0.3 [flutter]
- flutter_keyboard_visibility 5.4.1 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_linux flutter_keyboard_visibility_macos flutter_keyboard_visibility_web flutter_keyboard_visibility_windows flutter]
- flutter_keyboard_visibility_linux 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_macos 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_keyboard_visibility_windows 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- frontend_server_client 3.2.0 [async path]
- gettext_parser 0.2.0
- glob 2.1.1 [async collection file path string_scanner]
- graphs 2.3.1 [collection]
- http 0.13.5 [async http_parser meta path]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- i18n_extension 6.0.0 [sprintf args analyzer gettext_parser equatable intl flutter]
- intl 0.17.0 [clock path]
- io 1.0.4 [meta path string_scanner]
- js 0.6.4
- json_annotation 4.8.0 [meta]
- lints 2.0.1
- logging 1.1.1
- matcher 0.12.12 [stack_trace]
- material_color_utilities 0.2.0
- meta 1.8.0
- mime 1.0.4
- nested 1.0.0 [flutter]
- package_config 2.1.0 [path]
- pasteboard 0.2.0 [flutter flutter_web_plugins js]
- path 1.8.2
- path_drawing 1.0.1 [vector_math meta path_parsing flutter]
- path_parsing 1.0.1 [vector_math meta]
- path_provider 2.0.15 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- path_provider_android 2.0.27 [flutter path_provider_platform_interface]
- path_provider_foundation 2.2.3 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.11 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.0.6 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.7 [ffi flutter path path_provider_platform_interface win32]
- pedantic 1.11.1
- platform 3.1.0
- plugin_platform_interface 2.1.4 [meta]
- pool 1.5.1 [async stack_trace]
- process 4.2.4 [file path platform]
- pub_semver 2.1.4 [collection meta]
- pubspec_parse 1.2.3 [checked_yaml collection json_annotation pub_semver yaml]
- quiver 3.2.1 [matcher]
- rive 0.11.4 [collection flutter flutter_web_plugins http meta plugin_platform_interface rive_common]
- rive_common 0.1.0 [collection ffi flutter flutter_web_plugins graphs http meta plugin_platform_interface]
- shelf 1.4.1 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.4 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.3.2 [analyzer async build dart_style glob path source_span yaml]
- source_span 1.9.1 [collection path term_glyph]
- sprintf 7.0.0
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.1.0
- string_scanner 1.1.1 [source_span]
- syncfusion_flutter_core 20.3.52 [vector_math flutter]
- term_glyph 1.2.1
- test_api 0.4.13 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timing 1.0.1 [json_annotation]
- tuple 2.0.2
- typed_data 1.3.2 [collection]
- url_launcher 6.1.11 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- url_launcher_android 6.0.36 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.1.4 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.5 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.5 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.3 [flutter plugin_platform_interface]
- url_launcher_web 2.0.17 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.6 [flutter url_launcher_platform_interface]
- vector_math 2.1.3
- watcher 1.0.2 [async path]
- web_socket_channel 2.4.0 [async crypto stream_channel]
- win32 3.1.4 [ffi]
- xdg_directories 1.0.0 [meta path process]
- yaml 3.1.1 [collection source_span string_scanner]```

</details>

---

**Comment by danagbemava-nc** [comment]
Hi @HabaN3r0, what version of firebase_auth are you using? A similar issue was reported in https://github.com/firebase/flutterfire/issues/10966 which has since been fixed. If you are not using the latest version of firebase_auth(4.7.2) kindly upgrade to that version to see if you still face this issue. If you are using the latest version or are still facing this issue while using the latest version, please provide the output of `flutter pub dep -- --style=compact` and a complete minimal reproducible code sample in a repo that we can clone so that we can investigate this issue.

Thank you

**Comment by HabaN3r0** [comment]
@danagbemava-nc thanks for replying. I have tried using both 
`firebase_auth 4.7.2 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]`
and
`firebase_auth_web 5.6.2 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser js meta]`
to no avail. I have provided the output of `flutter pub dep -- --style=compact` in my post above. 

While creating a demo [repository](https://github.com/HabaN3r0/firebase_auth_mfa_demo), I managed to figure out that the issue lies within firebase_auth_web 5.6.2. Using firebase_auth 4.7.2 catches the right error but now the sms isn't sending to my number.

**Comment by danagbemava-nc** [comment]
Hi @HabaN3r0, were you manually importing firebase_auth_web? 

Have you completed the setup for the MFA described in https://firebase.google.com/docs/auth/flutter/multi-factor#enabling_multi-factor_authentication? 

Also, what region are youtesting from?

**Comment by HabaN3r0** [comment]
Yes, I was manually importing firebase_auth_web. 

I completed the MFA setup and assigned my phone number to a demo account. 

I am testing from asia-southeast1 region.

**Comment by danagbemava-nc** [comment]
Which country, in particular, are you testing from? 

Do you get any errors when you make the request to send the SMS?

**Comment by HabaN3r0** [comment]
I am testing from Singapore and received no issues.

As you mention which country, I realize it could be an issue with my phone number (registered under a provider called Simba) as this number has had issues with being recognized as an eligible phone number. I tried with another number and it's working. Thanks for the support!
