### ISSUE TITLE
🐛 [firebase_core: ^2.15.0]  Target of URI doesn't exist package:firebase_core/firebase_core.dart'

### ISSUE THREAD

**Issue by mrbinitie** [firebase/flutterfire#11442]
## Bug report

I have successfully built a flutter app with Firebase. Today I opened VSCode and there were these errors in the firebase_options. dart
Target of URI doesn't exist - package:firebase_core/firebase_core.dart' and the code will no longer recompile. FlutterFire works and I have added the firebase_core plugin, nothing works. 
To check if it was something I did I created a new project connected to my Firebase project, the moment firebase_options.dart was generated by flutterfire configure the errors appeared in the new dart file
### Steps to reproduce

1. create a new Flutter project
2. run flutterfire configure
3. run fflutter pub add firebase_core
4.  rerun flutterfire configure

### Expected behavior

firebase_options.dart generated without errors referencing a missing firebase_core.dart file

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and
![Screenshot 2023-08-10 034654](https://github.com/firebase/flutterfire/assets/92861/3629c6a4-643b-4ed2-8b1b-8fcfd7661f15)
 paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---
![Screenshot 2023-08-10 034654](https://github.com/firebase/flutterfire/assets/92861/6789eb71-fb5f-4957-9953-9fdc607a14db)

**Comment by mrbinitie** [comment]
I also noticed something else, if you look in the dependences panel, firebase core is the only empty folder. the screenshot will show what I mean. How has this happened?
 I just did a release to the Play store a week ago and all was perfect
![Screenshot 2023-08-10 043228](https://github.com/firebase/flutterfire/assets/92861/b72a163f-fa9d-4f0d-9d0f-6e97c647ebd9)

**Comment by danagbemava-nc** [comment]
Hi @mrbinitie, this is likely an issue with your local setup. Have you made any recent changes to your flutter tooling or your project? I followed the steps you have outlined and it all worked just fine for me. The firebase_core package is also not empty in my dependencies. What version of the flutterfire_cli are you also using? Please also provide the output of `flutter doctor -v`. Thank you

<img width="254" alt="Screenshot 2023-08-10 at 10 16 40" src="https://github.com/firebase/flutterfire/assets/88313112/877df63d-d6c5-4784-86c2-12f2ba176149">

**Comment by mrbinitie** [comment]
[danagbemava-nc] thanks so much for the speedy response. The only thing I have done is to update flutter and dart, nothing else. I've totally rebuilt the project from scratch and still same result. It bugged me so much I couldn't sleep. 
flutterfire_cli 0.2.7.
Here's my flutter doctor _v

PS D:\ayobi\Projects\flutterProjects\my_inec2023> flutter doctor -v
[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.25300.1000], locale en-GB)
    • Flutter version 3.10.6 on channel stable at D:\ayobi\DroidTools\flutterSDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (4 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at D:\ayobi\DroidTools\SDK
    • Platform android-UpsideDownCake, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.81.0)
    • VS Code at C:\Users\ayobi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.70.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.25300.1000]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 116.0.1938.43

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
PS D:\ayobi\Projects\flutterProjects\my_inec2023>

**Comment by mrbinitie** [comment]
I'd really appreciate your help here. I'm totally befuddled and out of ideas

**Comment by danagbemava-nc** [comment]
Hi @mrbinitie, kindly walk me through the steps you use to setup your project. If you could share a screen recording, that would help.

Can you also try clearing your pub cache and try running the commands again to see if you still face this issue? You can clear your pub cache by running `flutter pub cache clean`. 

PS: You will need to re-run `flutter pub get` for all your flutter projects.

**Comment by mrbinitie** [comment]
Hi Daniel, I finally cracked it, it was a bit of a sledge hammer solution,
I went to the C:\Users\purple\AppData\Local\Pub\Cache and deleted the cache
folder. After that it was oo-jah-com-spif. Everythings is fine now after a
flutter pub get

**Comment by danagbemava-nc** [comment]
Thanks for the update, I will be closing this as solved.
