### ISSUE TITLE
🐛 [firebase_app_check] AppCheck fails on app update for Android

### ISSUE THREAD

**Issue by mzkai** [firebase/flutterfire#11453]
## AppCheck fails on app update for Android

I have several users that experience that AppCheck fails when they upgrade to a new version of my app. This seems only to affect Android users, but might just be because it is less common on iOS devices.

Only after the user logs out and in again will AppCheck again pass.

### Steps to reproduce

The following is my setup for FirebaseAppCheck for Android. iOS uses the default setup. The same problem seems to occur for SafetyNet too though:
```
await FirebaseAppCheck.instance.activate(
    androidProvider: AndroidProvider.playIntegrity,
);
await FirebaseAppCheck.instance.setTokenAutoRefreshEnabled(true);
```

### Expected behavior

I would expect AppCheck to continue working despite the app being updated.

### Flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 darwin-arm64)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.81.1)

• No issues found!

### Flutter dependencies

firebase_app_check: ^0.1.5+1

**Comment by darshankawar** [comment]
@mzkai 
Per your comment saying that it occured using SafetyNet too, then I am inclined towards saying that it may not be firebase_app_check plugin issue, as the plugin is a thin wrapper around native Firebase SDKs.
I suggest you to reach out to [firebase support](https://firebase.google.com/support) to see what they say in the case you are facing.

**Comment by nialljawad96** [comment]
Also getting this error. So sad. Just destroys experience for Android users.

**Comment by nialljawad96** [comment]
@mzkai Was this solved on your end?

**Comment by EngMoAmri** [comment]
same here

**Comment by alshowaiterElias** [comment]
This need to be fixed **immediately**

**Comment by EngMoAmri** [comment]
Hi @mzkai
For me the solution was to set the device integrity to ```MEETS_BASIC_INTEGRITY``` in Play Console

```NOTE *``` THIS ACTION MAY TAKE SOME TIME 
For me it was about 30 minutes

![image](https://github.com/firebase/flutterfire/assets/88964080/c778f0d2-ab41-4d20-ad22-cc2b20479deb)
