### ISSUE TITLE
🐛 [flutter_messaging] getInitialMessage() returns null

### ISSUE THREAD

**Issue by fullflash** [firebase/flutterfire#11465]
is:issue is:open 🐛 [flutter_messaging] getInitialMessage() returns null bug still happens in latest version

issue has been closed but this still happens on latest iOS , latest flutter and firebase_messaging plugin
https://github.com/firebase/flutterfire/issues/9906

firebase_messaging: ^14.6.5
```

flutter doctor -v
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.5 22G74 darwin-arm64, locale
    en-AZ)
    • Flutter version 3.10.6 on channel stable at
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (5 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/***************android
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/------------
        • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • B54E8D4C-0D83-4369-9EFB-CA58A26BAD4D • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-arm64   • macOS 13.5 22G74 darwin-arm64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 115.0.5790.170

[✓] Network resources
    • All expected network resources are available.
```

**Comment by darshankawar** [comment]
Thanks for the report @fullflash 
Can you try to use nodejs admin SDK script to send notifications as shown in the [plugin example](https://github.com/firebase/flutterfire/blob/91d8aa72f627620245fe15df48f2d68f204e3d10/packages/firebase_messaging/firebase_messaging/example/scripts/send-message.js) script and check if using it, you still get the method as null ?

**Comment by sinxwal** [comment]
It is not stale. Just try to reproduce #9906 issue.

**Comment by shubhamkislay** [comment]
Can I please an update on this as I've been experiencing the same issue

**Comment by Woutwo** [comment]
Same problem here, always null on iOS when opened from terminated state. Tried delaying and tried some other things like rearranging code, but still happens.

**Comment by ntaworking** [comment]
Same problem here. Both Android & iOS.

**Comment by fullflash** [comment]
we cannot provide additional details as there are no details your plugin just response null also you can see that this issue happens for many users. you

**Comment by darshankawar** [comment]
I tried the [plugin example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example) on iOS with which the reported behavior doesn't occur. Anyone facing this issue, please try the plugin example and check at your end.

**Comment by fullflash** [comment]
we are initializing firebase inside runZoneGuarded block but it should not cause the case that sdk failed to get initial message payload when app openened from notification

```
runZonedGuarded<Future<void>>(() async {
    try {
      WidgetsFlutterBinding.ensureInitialized();
      initializeDateFormatting();
      SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(statusBarColor: Colors.transparent));
      await Firebase.initializeApp();
     
```

**Comment by ItayBarFaye** [comment]
This issue also happen in android..

**Comment by ItayBarFaye** [comment]
Hey, do you have any solution for this case?

**Comment by darshankawar** [comment]
The plugin also makes use of flutter_local_notifications so I think that helps to get the initial message. Please check the implementation:

https://github.com/firebase/flutterfire/blob/f78838ae480e28f0f83f1b7cf10bf424ac0593d6/packages/firebase_messaging/firebase_messaging/example/lib/main.dart#L328
