### ISSUE TITLE
🐛 [firebase_dynamic_links] Not receiving anything in "PendingDynamicLinkData" callback

### ISSUE THREAD

**Issue by Faiza-Farooqui** [firebase/flutterfire#11467]
## Bug report

**Describe the bug**
Not receiving anything in "PendingDynamicLinkData" callback. I have generated links from firebase, it is opening my app but i am not receiving anything in the callback

### Steps to reproduce

1. write the below code
2. Future<void> initDynamicLinks() async {
     FirebaseDynamicLinks.instance.onLink.listen((dynamicLinkData) {
     print("deeplink ${ dynamicLinkData.link.path}");
    }).onError((error) {
      print('onLink error');
      print(error.message);
    });
  }
3. and receive nothing in print

### Expected behavior

should print the link

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the report @Faiza-Farooqui 
Using the plugin example, I do see that `Future<void> initDynamicLinks() async {` method does get called, but it doesn't print the `dynamicLinkData` inside the method.

The below code snippet also prints null indicating deep link is null:

```
ElevatedButton(
                        onPressed: () async {
                          final PendingDynamicLinkData? data =
                              await dynamicLinks.getInitialLink();
                          final Uri? deepLink = data?.link;
                          print(deepLink);

                          if (deepLink != null) {
                            // ignore: unawaited_futures
                            Navigator.pushNamed(context, deepLink.path);
                          } else {
                            print('deepLink is null');
                          }
                        },
                        child: const Text('getInitialLink'),
                      )
```

```
I/flutter (26453): I am called
D/EGL_emulation(26453): app_time_stats: avg=898.31ms min=2.04ms max=33476.76ms count=38
I/flutter (26453): null
I/flutter (26453): deepLink is null
```

Although it points me to a similar issue https://github.com/firebase/flutterfire/issues/8926#issuecomment-1196653932 for which can you try [this](https://github.com/firebase/flutterfire/issues/8926#issuecomment-1196653932) and check if it helps in your case or not ?

**Comment by Faiza-Farooqui** [comment]
I am getting this error in my android app, please let me know here where Am
I doing wrong. need to deliver the app by tomorrow

**Comment by Faiza-Farooqui** [comment]
[image: image.png]

this is my whole code but it only print the first print statement
"==================
initDynamicLinks called" , after this nothing is happening or print

**Comment by darshankawar** [comment]
> I am getting this error in my android app,

Can you provide the actual error ?
