### ISSUE TITLE
🐛 [Firebase_auth] signInWithPopup auth fails with crossOriginIsolated=true

### ISSUE THREAD

**Issue by Nimo11** [firebase/flutterfire#11466]
## Bug report
I am using firebase hosting for a pwa application requiring firebase_auth and sharedarraybuffer
To enable sharedArrayBuffer i use cross-origin isolation:

```
"headers": [
          {
            "key": "Cross-Origin-Opener-Policy",
            "value": "same-origin"
          },
          {
            "key": "Cross-Origin-Embedder-Policy",
            "value": "require-corp"
          }
        ]
```

but it s incompatible with signInWithPopup because iframe content is blocked by browser due to missing headers Cross-Origin-Resource-Policy.

Could you help me solving this issue?

=
![Capture](https://github.com/firebase/flutterfire/assets/60822263/ef856073-cbcf-4833-bc5a-9c9c3820de10)

**Comment by darshankawar** [comment]
@Nimo11 
This doesn't seem to be an issue with firebase_auth, but could be related to underlying firebase js sdk. Flutterfire plugins are  thin wrappers around native Firebase SDKs, so I suggest you to reach out to firebase support or native Firebase sdk repo.
I already see a similar issue open in firebase js repo https://github.com/firebase/firebase-js-sdk/issues/6467 in which you seem to have commented as well. I suggest you to follow-up in that issue for updates. Once the feature is implemented natively, then flutterfire can leverage the implementation to work in firebase_auth plugin.

Closing from here, as this doesn't seem to be actionable from plugin side. If you disagree, write in comments and I'll reopen it.
