### ISSUE TITLE
🐛 [cloud_firestore] Argument exception when request multiple not null columns

### ISSUE THREAD

**Issue by Paroca72** [firebase/flutterfire#11476]
## Bug report

When using remote request with composite filter (OR) in particular when try to filter on more than one column as not null (isNull: false) an argument exception is raised.
`PlatformException(error, An error occurred while parsing query arguments, see native logs for more information. Please report this issue., null, null)`

### Steps to reproduce

EXCEPTION:
Filter.or(
        Filter("first_column_name", isNull: false),
        Filter("second_column_name", isNull: false),
        Filter("third_column_name", isEqualTo: STRING),
);

ALLOWED:
Filter.or(
        Filter("first_column_name", isNull: false),
        Filter("third_column_name", isEqualTo: STRING),
);

ALLOWED:
Filter.or(
        Filter("second_column_name", isNull: false),
        Filter("third_column_name", isEqualTo: STRING),
);

**Comment by danagbemava-nc** [comment]
Hi @Paroca72, what platform(s) are you experiencing this issue on? 

What version of `cloud_firestore` are you using and what version of flutter are you using?

**Comment by Paroca72** [comment]
cloud_firestore: 4.8.4
Flutter: 3.10.0

Thanks

**Comment by danagbemava-nc** [comment]
Hi @Paroca72, please provide a complete minimal reproducible code sample in a repo that we can clone so that we can investigate this issue. 

Thank you
