### ISSUE TITLE
🐛 [Firebase_storage] I am not able to use its functionality , the plugin is not getting imported

### ISSUE THREAD

**Issue by Iamgroot000** [firebase/flutterfire#11477]
## Bug report

**Describe the bug**

### Steps to reproduce

2. '...'
3. See error or incorrect behavior

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by danagbemava-nc** [comment]
Closing this since no information has been provided. 

In the future when you file an issue, please provide some/all of the information requested in the issue template. 

Thank you
