### ISSUE TITLE
🐛 [firebase_auth] TypeError: Cannot read properties of undefined (reading 'appVerificationDisabledForTesting')

### ISSUE THREAD

**Issue by NefariousNiru** [firebase/flutterfire#11488]
## Bug report

**Describe the bug**
Phone auth on flutter doesn't seem to be working.

Error in this line in the console. 
I have already deployed the app using Firebase Hosting and it still doesn't work since I figured it might be an error due to localhost or the app being in debug. But even in release, it doesn't work. You can find the release version here. 
[ https://batchcon-25c99.web.app/#/](url)

Problem at this line.
`    this._recaptchaLoader = this.auth.settings.appVerificationDisabledForTesting
      ? new MockReCaptchaLoaderImpl()
      : new ReCaptchaLoaderImpl();
`

### Steps to reproduce

1. Go to the repo
2. Run the project
3. See error or incorrect behavior

### Expected behavior

Should receive otp and resume authentication flow.

### Sample project
[https://github.com/NefariousNiru/phoneauthtest](url)
---

## Additional context

TypeError: Cannot read properties of undefined (reading 'appVerificationDisabledForTesting')
Tried with and without this line also. 

`auth.setSettings(appVerificationDisabledForTesting: true);`

I added these two lines as well from other past issues but of no help (Tried with different versions as well).

` <script src="https://www.gstatic.com/firebasejs/8.6.1/firebase-app.js"></script>`
 `<script src="https://www.gstatic.com/firebasejs/8.6.1/firebase-auth.js"></script>`

Attached log from chrome
[localhost-1692296952136.log](https://github.com/firebase/flutterfire/files/12372599/localhost-1692296952136.log)
---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.5, on Microsoft Windows [Version 10.0.19045.3324], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.micros
[localhost-1692296952136.log](https://github.com/firebase/flutterfire/files/12372565/localhost-1692296952136.log)
oft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.3)
[√] VS Code, 64-bit edition (version 1.78.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

Dart SDK 2.19.2
Flutter SDK 3.7.5
wizork 1.0.0+1

dependencies:
- carousel_slider 4.2.1 [flutter]
- countup 0.1.4 [flutter]
- cupertino_icons 1.0.5
- firebase_auth 4.7.3 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.15.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection js material_color_utilities meta vector_math sky_engine]
- font_awesome_flutter 10.4.0 [flutter]
- html 0.15.4 [csslib source_span]
- intl_phone_field 3.2.0 [flutter]
- pin_code_fields 8.0.1 [flutter]
- shared_preferences 2.2.0 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- url_launcher 6.1.11 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- video_player 2.7.0 [flutter html video_player_android video_player_avfoundation video_player_platform_interface video_player_web]

dev dependencies:
- flutter_lints 2.0.2 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection js matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- _flutterfire_internals 1.3.5 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.10.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.2.1
- clock 1.1.1
- collection 1.17.0
- csslib 1.0.0 [source_span]
- fake_async 1.3.1 [clock collection]
- ffi 2.0.2
- file 6.1.4 [meta path]
- firebase_auth_platform_interface 6.16.2 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.6.3 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser js meta]
- firebase_core_platform_interface 4.8.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.7.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- js 0.6.5 [meta]
- lints 2.0.1
- matcher 0.12.13 [meta stack_trace]
- material_color_utilities 0.2.0
- meta 1.8.0
- path 1.8.2
- path_provider_linux 2.2.0 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.0 [flutter platform plugin_platform_interface]
- path_provider_windows 2.2.0 [ffi flutter path path_provider_platform_interface win32]
- platform 3.1.1
- plugin_platform_interface 2.1.4 [meta]
- shared_preferences_android 2.2.0 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.3.3 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.3.0 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.3.0 [flutter plugin_platform_interface]
- shared_preferences_web 2.2.0 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.3.0 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sky_engine 0.0.99
- source_span 1.9.1 [collection path term_glyph]
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.4.16 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.2 [collection]
- url_launcher_android 6.0.36 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.1.4 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.5 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.5 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.3 [flutter plugin_platform_interface]
- url_launcher_web 2.0.18 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.7 [flutter url_launcher_platform_interface]
- vector_math 2.1.4
- video_player_android 2.4.9 [flutter video_player_platform_interface]
- video_player_avfoundation 2.4.6 [flutter video_player_platform_interface]
- video_player_platform_interface 6.1.0 [flutter plugin_platform_interface]
- video_player_web 2.0.16 [flutter flutter_web_plugins video_player_platform_interface]
- win32 4.1.4 [ffi]
- xdg_directories 1.0.2 [meta path]

</details>

---

**Comment by kirillnepomiluev** [comment]
I have the same issue with phoneAuth FLutter Web.  I tried to uprade flutter auth package and flutter_core.  I tried to upgrade flutter.  I tried ways from the same issues like that https://github.com/firebase/flutterfire/issues/9432 /  But nothing work/ 

The result is "TypeError: Cannot read properties of undefined (reading 'appVerificationDisabledForTesting')" 
on Flutter web  release and debag.  Everything works okey on Android build but that use different metod. 
at pubspec.yaml -
  firebase_auth: 4.7.3  (i tried different versions with dependency_overrides but it does not work)
  firebase_core: ^2.15.1
   
at index.html -    
  <script src="https://www.gstatic.com/firebasejs/9.0.1/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/9.0.1/firebase-auth.js"></script>

**Comment by davidmigloz** [comment]
Same issue here.

- In my case, affecting SMS 2FA
- It started happening after upgrading from: (I haven't checked all the intermediate version, so not sure in which one it broke)
```
firebase_core: 2.12.0 -> 2.15.1
firebase_auth: 4.6.0 -> 4.7.3
firebase_messaging: 114.6.0 -> 4.6.6
(flutter 3.0.6 -> 3.1.0)
```
- It is only affecting web (Android and iOS work fine)
- Exception:
```
[firebase_auth/unknown] An unknown error occurred: TypeError: Cannot read properties of undefined (reading 'appVerificationDisabledForTesting')
```

**Comment by davidmigloz** [comment]
Duplicated of https://github.com/firebase/flutterfire/issues/11485

**Comment by NefariousNiru** [comment]
Works by adding this line in index.html
`<script>window.flutterfire_web_sdk_version` = '9.22.1';</script>`

Closing this issue.
