### ISSUE TITLE
[📚] linkWithCredential possible wrong error message

### ISSUE THREAD

**Issue by karkakol** [firebase/flutterfire#11492]
Package: firebase_auth
Class: User
Method: linkWithCredential

According the documentation FirebaseAuthException is thrown with message "invalid-email" when there is problem with password.

[Link](https://pub.dev/documentation/firebase_auth/latest/firebase_auth/User/linkWithCredential.html)

![image](https://github.com/firebase/flutterfire/assets/70136588/5a1a1616-a2ee-4cff-97d9-01de1181eb9e)

**Comment by darshankawar** [comment]
@karkakol 
Can you please elaborate which possible wrong error message case is mentioned in the doc ? and for which `invalid-email` case should it be corrected ?

**Comment by karkakol** [comment]
This one:
![image](https://github.com/firebase/flutterfire/assets/70136588/8216f7da-f909-4404-845a-f7b2c55a60c3)

Error code should be wrong password or user does not have a password.

**Comment by darshankawar** [comment]
Thanks for the update.

/cc @Lyokone

**Comment by karkakol** [comment]
Any progress in case?

**Comment by ahsanahmad4654** [comment]
This issue is solved. it should be closed.

**Comment by russellwheatley** [comment]
Thanks for the update @ahsanahmad4654, closing out 👍
