### ISSUE TITLE
how can fix it  ? ( about firebase whitelisted problem ) 

### ISSUE THREAD

**Issue by axroromonov** [firebase/flutterfire#11496]
```
FLTFirebaseDynamicLinks: An error occurred while calling method FirebaseDynamicLinks#buildShortLink, errorOrNil => {
    NSLocalizedFailureReason = "We could not match param 'https://hansa-lab.ru/site/article?id=341' with whitelisted URL patterns in this Google project. [https://support.google.com/firebase/answer/9021429] [https://support.google.com/firebase/answer/9021429]";
   remoteErrorCode = 400;
    remoteStatus = "INVALID_ARGUMENT";
}
```
<img width="692" alt="Screenshot 2023-08-19 at 03 01 07" src="https://github.com/firebase/flutterfire/assets/76530966/32e3ccdd-5739-4872-a3b5-1410ffd7621a">

**Comment by nox1134** [comment]
Hii ! I'm new to open source and would like to work on this issue. How do I get started?

**Comment by axroromonov** [comment]
> Hii @axroromonov ! I'm new to open source and would like to work on this issue. How do I get started?

via youtube

**Comment by darshankawar** [comment]
@axroromonov 
You'll probably need to reach out to firebase support as it looks like related to backend rather than an issue with the plugin itself. See another similar issue raised in native repo for your reference: https://github.com/firebase/firebase-ios-sdk/issues/10392

Closing from here.
