### ISSUE TITLE
🐛 [cloud_firestore] Firestore freezes when opened after a long time on android

### ISSUE THREAD

**Issue by cnkygmr** [firebase/flutterfire#11498]
## Bug report

When the application is opened after a long time on android, it freezes, this problem never happens on ios.
I did it so that it says "Updating" above in the appbar like in Telegram, after a long time it stays that way on android, on ios it comes right away. Also, because there is no update, no other firestore process is working. It is fixed by closing and reopening the app.

### Steps to reproduce

```
pageQuery.snapshots(includeMetadataChanges: true).map((convert) {
    _snapshot = convert;
    setState(() {
          _isFromCache = _snapshot?.metadata.isFromCache;
     });
});
```

### Expected behavior

I expect it to run every time it boots up like in ios

**Comment by darshankawar** [comment]
Thanks for the report @cnkygmr 
Can you provide a time frame after which it starts to freeze ? 
Can you also try running the [plugin example](https://github.com/firebase/flutterfire/tree/master/packages/cloud_firestore/cloud_firestore/example) on affected Android device, keep it for said time and check if it still freezes or not ?

Also please check [this](https://github.com/firebase/flutterfire/issues/11146) issue and underlying comments to check if it helps further in your case or not.

**Comment by cnkygmr** [comment]
@darshankawar Yes, my problem is just like this, it only happens on android. The same code is written on ios but it never does this problem on it
