### ISSUE TITLE
🐛 [firebase_app_check] App Check is Failing in Production for Android Users at Random Times

### ISSUE THREAD

**Issue by nialljawad96** [firebase/flutterfire#11491]
## Bug report

**Describe the bug**
App Check is failing in production for android users at random times. If a user restarts the app, then it does not fail and works as normal. No problems on iOS, just Android. 

### Steps to reproduce

```
await FirebaseAppCheck.instance.activate(

    );
```

### Expected behavior

Should not fail. It was working fine before. Now it is failing repeatedly. 

### Sample project

Just a standard project using the following:
```
await FirebaseAppCheck.instance.activate(

    );
```
---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[!] Flutter (Channel stable, 3.10.6, on macOS 12.6 21G115 darwin-x64, locale en-GB)
    ! Warning: `dart` on your path resolves to /usr/local/Cellar/dart/2.17.3/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nialljawad/fvm/versions/2.5.3. Consider adding
      /Users/nialljawad/fvm/versions/2.5.3/bin to the front of your path.
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Community Edition (version 2023.1.2)
[✓] VS Code (version 1.81.0)
[✓] Connected device (2 available)
[✓] Network resources

```

</details>

---

### Flutter dependencies

```
  firebase_app_check: ^0.1.5
```

</details>

---

**Comment by darshankawar** [comment]
@nialljawad96 
If the call is failing randomly and that too for Android, then mostly likely it is not related to plugin code, but could be a server glitch which is out of control from the plugin, as the plugin code doesn't differentiate between android and iOS and if the calls are failing only in production without making any code changes specific to the plugin, then it is most likely a server issue for which you can reach out to [firebase support](https://firebase.google.com/support) for further resolution. 

Closing from here.

**Comment by nialljawad96** [comment]
@darshankawar Thanks a lot for your reply. 

As a consumer whether it's a server issue or not is surely not my concern? The plugin only works if there isn't server issues. I'm a little confused by the point of this github if I have to reach out to firebase separately for a plugin not working correctly. Isn't the plugin made by Firebase? 

Generally, i'm unable to test App Check on Android in a debug environment, and have not been able to for months, because it is literally impossible to get it working as the debug token never registers. iOS, no problems. As a result, I wouldn't look into the fact they are only failing in production. 

There was also another issue opened last week with the same problem.

Or are you saying it's most likely is server issue on the Play Integrity side? Or the Firebase side?

**Comment by darshankawar** [comment]
> Or are you saying it's most likely is server issue on the Play Integrity side? Or the Firebase side?

Yes, I was referring to Firebase side issue.



> i'm unable to test App Check on Android in a debug environment, and have not been able to for months, because it is literally impossible to get it working as the debug token never registers.

If you could provide more details like a code sample, error logs if any then I could revisit this issue.

**Comment by nialljawad96** [comment]
The only thing that I'm using App Check wise in my code is this, calling in my main():
```
await FirebaseAppCheck.instance.activate(

    );
```

I haven't installed any other packages on the android specific side, or modified the build.gradle or anything like that.

Crashlytics error log:
`[cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.`

I know that it's unrelated to security rules because after I shut down the app and restart it, it suddenly starts carrying out the requests perfectly. This is the only way to get it working again when it randomly fails. Working perfectly on iOS.
