### ISSUE TITLE
FirebaseCrashlytics.recordError crash - flutter 

### ISSUE THREAD

**Issue by amiravisar89** [firebase/flutterfire#11510]
we are running on   `firebase_crashlytics: ^3.0.17`
we have followed [crashlytics getting started](https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=flutter).
- release mode
- flutter 3.10.5

pubspec.yaml dependencies:

>  firebase_remote_config: ^3.0.15
  firebase_analytics: ^10.1.6
  firebase_core: ^2.8.0
  firebase_crashlytics: ^3.0.17

we are crashing on this line:

> PlatformDispatcher.instance.onError = (error, stack) {
    crashlytics.recordError(error, stack, fatal: true);
    return true;
  };

and we are getting a-lot of crashes with Production.
any ideas?
<img width="1185" alt="Screenshot 2023-08-23 at 13 47 53" src="https://github.com/firebase/flutterfire/assets/18641468/f46a3837-12d0-44ba-ab84-22bf78eb41a8">

**Comment by darshankawar** [comment]
@amiravisar89 
Can you provide the complete crash log in properly formatted text instead of in screenshot ?

**Comment by amiravisar89** [comment]
@darshankawar this is the logs:

`# Crashlytics - Stack trace
# Application: ag.prospera.x
# Platform: apple
# Version: 1.2.0 (39)
# Issue: 4a4c22a5c842d54fa1e0fb99579e3216
# Session: 6f06dcf92be44e0cb2478cfb24a87729_DNE_0_v2
# Date: Fri Aug 25 2023 06:28:51 GMT+0300 (Israel Daylight Time)

Fatal Exception: FlutterError
0  ???                            0x0 FirebaseCrashlytics.recordError + 119 (firebase_crashlytics.dart:119)
1  ???                            0x0 _crashlyticsConfig.<fn> + 34 (configs.dart:34)

Crashed: com.apple.main-thread
0  FirebaseCrashlytics            0x1e2cc FIRCLSProcessRecordAllThreads + 184
1  FirebaseCrashlytics            0x1e6ac FIRCLSProcessRecordAllThreads + 1176
2  FirebaseCrashlytics            0x1573c FIRCLSHandler + 48
3  FirebaseCrashlytics            0xfb9c FIRCLSExceptionRecordOnDemand + 1328
4  FirebaseCrashlytics            0xf5dc FIRCLSExceptionRecordOnDemandModel + 228
5  FirebaseCrashlytics            0x1da98 -[FIRCLSOnDemandModel recordOnDemandExceptionWithModel:] + 68
6  FirebaseCrashlytics            0x1d4f4 -[FIRCLSOnDemandModel recordOnDemandExceptionIfQuota:withDataCollectionEnabled:usingExistingReportManager:] + 164
7  FirebaseCrashlytics            0x2b9a8 -[FIRCrashlytics recordOnDemandExceptionModel:] + 140
8  Runner                         0xb0524 -[FLTFirebaseCrashlyticsPlugin recordError:withMethodCallResult:] + 177 (FLTFirebaseCrashlyticsPlugin.m:177)
9  Runner                         0xafde0 -[FLTFirebaseCrashlyticsPlugin handleMethodCall:result:] + 101 (FLTFirebaseCrashlyticsPlugin.m:101)
10 Flutter                        0x5d5fd8 (Missing UUID 4c4c444555553144a19d3dfde98674e8)
11 Flutter                        0x3736c (Missing UUID 4c4c444555553144a19d3dfde98674e8)
12 libdispatch.dylib              0x24b4 _dispatch_call_block_and_release + 32
13 libdispatch.dylib              0x3fdc _dispatch_client_callout + 20
14 libdispatch.dylib              0x127f4 _dispatch_main_queue_drain + 928
15 libdispatch.dylib              0x12444 _dispatch_main_queue_callback_4CF + 44
16 CoreFoundation                 0x9a6f8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
17 CoreFoundation                 0x7c058 __CFRunLoopRun + 2036
18 CoreFoundation                 0x80ed4 CFRunLoopRunSpecific + 612
19 GraphicsServices               0x1368 GSEventRunModal + 164
20 UIKitCore                      0x3a23d0 -[UIApplication _run] + 888
21 UIKitCore                      0x3a2034 UIApplicationMain + 340
22 Runner                         0x5c20 main + 5 (AppDelegate.swift:5)
23 ???                            0x1c5c64960 (Missing)

com.google.firebase.firestore.rpc
0  libsystem_kernel.dylib         0x422c poll + 8
1  grpc                           0xa294c pollset_work(grpc_pollset*, grpc_pollset_worker**, grpc_core::Timestamp) + 1592
2  grpc                           0xa4f4c pollset_work(grpc_pollset*, grpc_pollset_worker**, grpc_core::Timestamp) + 84
3  grpc                           0x83cac cq_next(grpc_completion_queue*, gpr_timespec, void*) + 392
4  grpcpp                         0x1c9e8 grpc::CompletionQueue::AsyncNextInternal(void**, bool*, gpr_timespec) + 60
5  FirebaseFirestore              0x2c59c firebase::firestore::remote::Datastore::PollGrpcQueue() + 104
6  FirebaseFirestore              0x153974 firebase::firestore::util::Task::ExecuteAndRelease() + 184
7  libdispatch.dylib              0x3fdc _dispatch_client_callout + 20
8  libdispatch.dylib              0xb694 _dispatch_lane_serial_drain + 672
9  libdispatch.dylib              0xc1e0 _dispatch_lane_invoke + 384
10 libdispatch.dylib              0x16e10 _dispatch_workloop_worker_thread + 652
11 libsystem_pthread.dylib        0xdf8 _pthread_wqthread + 288
12 libsystem_pthread.dylib        0xb98 start_wqthread + 8

com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0xb48 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13008 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13248 mach_msg_overwrite + 388
3  libsystem_kernel.dylib         0x108c mach_msg + 24
4  CoreFoundation                 0x7aaf0 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7bd34 __CFRunLoopRun + 1232
6  CoreFoundation                 0x80ed4 CFRunLoopRunSpecific + 612
7  Foundation                     0x42334 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8  Foundation                     0x4221c -[NSRunLoop(NSRunLoop) runUntilDate:] + 64
9  UIKitCore                      0x4d733c -[UIEventFetcher threadMain] + 436
10 Foundation                     0x5b808 __NSThread__start__ + 716
11 libsystem_pthread.dylib        0x16cc _pthread_start + 148
12 libsystem_pthread.dylib        0xba4 thread_start + 8

io.flutter.1.ui
0  libsystem_kernel.dylib         0xb48 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13008 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13248 mach_msg_overwrite + 388
3  libsystem_kernel.dylib         0x108c mach_msg + 24
4  CoreFoundation                 0x7aaf0 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7bd34 __CFRunLoopRun + 1232
6  CoreFoundation                 0x80ed4 CFRunLoopRunSpecific + 612
7  Flutter                        0x2e654c (Missing UUID 4c4c444555553144a19d3dfde98674e8)
8  Flutter                        0x2e603c (Missing UUID 4c4c444555553144a19d3dfde98674e8)
9  libsystem_pthread.dylib        0x16cc _pthread_start + 148
10 libsystem_pthread.dylib        0xba4 thread_start + 8

io.flutter.1.raster
0  libsystem_kernel.dylib         0xb48 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13008 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13248 mach_msg_overwrite + 388
3  libsystem_kernel.dylib         0x108c mach_msg + 24
4  CoreFoundation                 0x7aaf0 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7bd34 __CFRunLoopRun + 1232
6  CoreFoundation                 0x80ed4 CFRunLoopRunSpecific + 612
7  Flutter                        0x2e654c (Missing UUID 4c4c444555553144a19d3dfde98674e8)
8  Flutter                        0x2e603c (Missing UUID 4c4c444555553144a19d3dfde98674e8)
9  libsystem_pthread.dylib        0x16cc _pthread_start + 148
10 libsystem_pthread.dylib        0xba4 thread_start + 8

io.flutter.1.io
0  libsystem_kernel.dylib         0xb48 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13008 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13248 mach_msg_overwrite + 388
3  libsystem_kernel.dylib         0x108c mach_msg + 24
4  CoreFoundation                 0x7aaf0 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7bd34 __CFRunLoopRun + 1232
6  CoreFoundation                 0x80ed4 CFRunLoopRunSpecific + 612
7  Flutter                        0x2e654c (Missing UUID 4c4c444555553144a19d3dfde98674e8)
8  Flutter                        0x2e603c (Missing UUID 4c4c444555553144a19d3dfde98674e8)
9  libsystem_pthread.dylib        0x16cc _pthread_start + 148
10 libsystem_pthread.dylib        0xba4 thread_start + 8

io.worker.1
0  libsystem_kernel.dylib         0x141c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x806c _pthread_cond_wait + 1232
2  Flutter                        0x48a60 (Missing UUID 4c4c444555553144a19d3dfde98674e8)
3  Flutter                        0x2e00cc (Missing UUID 4c4c444555553144a19d3dfde98674e8)
4  libsystem_pthread.dylib        0x16cc _pthread_start + 148
5  libsystem_pthread.dylib        0xba4 thread_start + 8

io.worker.2
0  libsystem_kernel.dylib         0x141c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x806c _pthread_cond_wait + 1232
2  Flutter                        0x48a60 (Missing UUID 4c4c444555553144a19d3dfde98674e8)
3  Flutter                        0x2e00cc (Missing UUID 4c4c444555553144a19d3dfde98674e8)
4  libsystem_pthread.dylib        0x16cc _pthread_start + 148
5  libsystem_pthread.dylib        0xba4 thread_start + 8

io.worker.3
0  libsystem_kernel.dylib         0x141c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x806c _pthread_cond_wait + 1232
2  Flutter                        0x48a60 (Missing UUID 4c4c444555553144a19d3dfde98674e8)
3  Flutter                        0x2e00cc (Missing UUID 4c4c444555553144a19d3dfde98674e8)
4  libsystem_pthread.dylib        0x16cc _pthread_start + 148
5  libsystem_pthread.dylib        0xba4 thread_start + 8

io.worker.4
0  libsystem_kernel.dylib         0x141c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x806c _pthread_cond_wait + 1232
2  Flutter                        0x48a60 (Missing UUID 4c4c444555553144a19d3dfde98674e8)
3  Flutter                        0x2e00cc (Missing UUID 4c4c444555553144a19d3dfde98674e8)
4  libsystem_pthread.dylib        0x16cc _pthread_start + 148
5  libsystem_pthread.dylib        0xba4 thread_start + 8

io.worker.5
0  libsystem_kernel.dylib         0x141c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x806c _pthread_cond_wait + 1232
2  Flutter                        0x48a60 (Missing UUID 4c4c444555553144a19d3dfde98674e8)
3  Flutter                        0x2e00cc (Missing UUID 4c4c444555553144a19d3dfde98674e8)
4  libsystem_pthread.dylib        0x16cc _pthread_start + 148
5  libsystem_pthread.dylib        0xba4 thread_start + 8

io.worker.6
0  libsystem_kernel.dylib         0x141c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x806c _pthread_cond_wait + 1232
2  Flutter                        0x48a60 (Missing UUID 4c4c444555553144a19d3dfde98674e8)
3  Flutter                        0x2e00cc (Missing UUID 4c4c444555553144a19d3dfde98674e8)
4  libsystem_pthread.dylib        0x16cc _pthread_start + 148
5  libsystem_pthread.dylib        0xba4 thread_start + 8

dart:io EventHandler
0  libsystem_kernel.dylib         0x2480 kevent + 8
1  Flutter                        0x4d77e0 (Missing UUID 4c4c444555553144a19d3dfde98674e8)
2  Flutter                        0x506780 (Missing UUID 4c4c444555553144a19d3dfde98674e8)
3  libsystem_pthread.dylib        0x16cc _pthread_start + 148
4  libsystem_pthread.dylib        0xba4 thread_start + 8

com.google.firebase.crashlytics.MachExceptionServer
0  libsystem_kernel.dylib         0xb48 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13008 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13248 mach_msg_overwrite + 388
3  libsystem_kernel.dylib         0x108c mach_msg + 24
4  FirebaseCrashlytics            0x17d54 FIRCLSMachExceptionServer + 108
5  libsystem_pthread.dylib        0x16cc _pthread_start + 148
6  libsystem_pthread.dylib        0xba4 thread_start + 8

com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0xb48 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13008 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13248 mach_msg_overwrite + 388
3  libsystem_kernel.dylib         0x108c mach_msg + 24
4  CoreFoundation                 0x7aaf0 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7bd34 __CFRunLoopRun + 1232
6  CoreFoundation                 0x80ed4 CFRunLoopRunSpecific + 612
7  CFNetwork                      0x2565a8 _CFURLStorageSessionDisableCache + 61088
8  Foundation                     0x5b808 __NSThread__start__ + 716
9  libsystem_pthread.dylib        0x16cc _pthread_start + 148
10 libsystem_pthread.dylib        0xba4 thread_start + 8

Thread
0  libsystem_kernel.dylib         0x141c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x806c _pthread_cond_wait + 1232
2  libc++.1.dylib                 0xcacc std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  leveldb                        0x18094 leveldb::(anonymous namespace)::PosixEnv::BackgroundThreadMain() + 80
4  leveldb                        0x18044 leveldb::(anonymous namespace)::PosixEnv::BackgroundThreadEntryPoint(leveldb::(anonymous namespace)::PosixEnv*) + 10
5  leveldb                        0x18128 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(leveldb::(anonymous namespace)::PosixEnv*), leveldb::(anonymous namespace)::PosixEnv*> >(void*) + 44
6  libsystem_pthread.dylib        0x16cc _pthread_start + 148
7  libsystem_pthread.dylib        0xba4 thread_start + 8

Thread
0  libsystem_kernel.dylib         0x141c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x806c _pthread_cond_wait + 1232
2  grpc                           0x1c5654 gpr_cv_wait + 160
3  grpc                           0xa717c grpc_core::Executor::ThreadMain(void*) + 180
4  grpc                           0x1d40d4 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::__invoke(void*) + 140
5  libsystem_pthread.dylib        0x16cc _pthread_start + 148
6  libsystem_pthread.dylib        0xba4 thread_start + 8

Thread
0  libsystem_kernel.dylib         0x141c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x806c _pthread_cond_wait + 1232
2  grpc                           0x1c5654 gpr_cv_wait + 160
3  grpc                           0xa717c grpc_core::Executor::ThreadMain(void*) + 180
4  grpc                           0x1d40d4 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::__invoke(void*) + 140
5  libsystem_pthread.dylib        0x16cc _pthread_start + 148
6  libsystem_pthread.dylib        0xba4 thread_start + 8

Thread
0  libsystem_kernel.dylib         0x141c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x806c _pthread_cond_wait + 1232
2  grpc                           0x1c5644 gpr_cv_wait + 144
3  grpc                           0x1dbd94 timer_thread(void*) + 580
4  grpc                           0x1d40d4 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::__invoke(void*) + 140
5  libsystem_pthread.dylib        0x16cc _pthread_start + 148
6  libsystem_pthread.dylib        0xba4 thread_start + 8

Thread
0  libsystem_kernel.dylib         0x141c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x806c _pthread_cond_wait + 1232
2  grpc                           0x1c5654 gpr_cv_wait + 160
3  grpc                           0x1dbd94 timer_thread(void*) + 580
4  grpc                           0x1d40d4 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::__invoke(void*) + 140
5  libsystem_pthread.dylib        0x16cc _pthread_start + 148
6  libsystem_pthread.dylib        0xba4 thread_start + 8

Thread
0  libsystem_pthread.dylib        0xb90 start_wqthread + 254

Thread
0  libsystem_kernel.dylib         0x1050 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe44 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb98 start_wqthread + 8

com.google.firebase.crashlytics.on.demand
0  libsystem_kernel.dylib         0x1008 __semwait_signal + 8
1  libsystem_c.dylib              0x57d8 nanosleep + 220
2  libsystem_c.dylib              0x19ad8 sleep + 52
3  FirebaseCrashlytics            0x1d790 __107-[FIRCLSOnDemandModel recordOnDemandExceptionIfQuota:withDataCollectionEnabled:usingExistingReportManager:]_block_invoke + 340
4  Foundation                     0xa72f0 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 24
5  Foundation                     0x7b4a0 -[NSBlockOperation main] + 104
6  Foundation                     0x7b430 __NSOPERATION_IS_INVOKING_MAIN__ + 16
7  Foundation                     0x3c7d8 -[NSOperation start] + 708
8  Foundation                     0x3c50c __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 16
9  Foundation                     0x41c20 __NSOQSchedule_f + 172
10 libdispatch.dylib              0x13114 _dispatch_block_async_invoke2 + 148
11 libdispatch.dylib              0x3fdc _dispatch_client_callout + 20
12 libdispatch.dylib              0xb694 _dispatch_lane_serial_drain + 672
13 libdispatch.dylib              0xc1e0 _dispatch_lane_invoke + 384
14 libdispatch.dylib              0x16e10 _dispatch_workloop_worker_thread + 652
15 libsystem_pthread.dylib        0xdf8 _pthread_wqthread + 288
16 libsystem_pthread.dylib        0xb98 start_wqthread + 8

com.smartlook.sdk.SnapshottingQueue (QOS: DEFAULT)
0  libsystem_kernel.dylib         0x1680 __ulock_wait + 8
1  libdispatch.dylib              0x49cc _dlock_wait + 56
2  libdispatch.dylib              0x4780 _dispatch_thread_event_wait_slow + 56
3  libdispatch.dylib              0x13860 __DISPATCH_WAIT_FOR_QUEUE__ + 368
4  libdispatch.dylib              0x1340c _dispatch_sync_f_slow + 144
5  SmartlookAnalytics             0x1a790 __swift_memcpy40_8 + 10644
6  SmartlookAnalytics             0xcc6d8 block_destroy_helper.20 + 312
7  Foundation                     0xa72f0 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 24
8  Foundation                     0x7b4a0 -[NSBlockOperation main] + 104
9  Foundation                     0x7b430 __NSOPERATION_IS_INVOKING_MAIN__ + 16
10 Foundation                     0x3c7d8 -[NSOperation start] + 708
11 Foundation                     0x3c50c __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 16
12 Foundation                     0x41c20 __NSOQSchedule_f + 172
13 libdispatch.dylib              0x24b4 _dispatch_call_block_and_release + 32
14 libdispatch.dylib              0x3fdc _dispatch_client_callout + 20
15 libdispatch.dylib              0x746c _dispatch_continuation_pop + 504
16 libdispatch.dylib              0x6ad4 _dispatch_async_redirect_invoke + 584
17 libdispatch.dylib              0x15a6c _dispatch_root_queue_drain + 396
18 libdispatch.dylib              0x16284 _dispatch_worker_thread2 + 164
19 libsystem_pthread.dylib        0xdbc _pthread_wqthread + 228
20 libsystem_pthread.dylib        0xb98 start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1050 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe44 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb98 start_wqthread + 8

com.smartlook.sdk.ScreenshotQueue
0  libsystem_kernel.dylib         0x1680 __ulock_wait + 8
1  libdispatch.dylib              0x49cc _dlock_wait + 56
2  libdispatch.dylib              0x4780 _dispatch_thread_event_wait_slow + 56
3  libdispatch.dylib              0x13860 __DISPATCH_WAIT_FOR_QUEUE__ + 368
4  libdispatch.dylib              0x1340c _dispatch_sync_f_slow + 144
5  SmartlookAnalytics             0x59728 block_destroy_helper.5 + 18780
6  SmartlookAnalytics             0xcc6d8 block_destroy_helper.20 + 312
7  libdispatch.dylib              0x13114 _dispatch_block_async_invoke2 + 148
8  libdispatch.dylib              0x3fdc _dispatch_client_callout + 20
9  libdispatch.dylib              0x746c _dispatch_continuation_pop + 504
10 libdispatch.dylib              0x1aa58 _dispatch_source_invoke + 1588
11 libdispatch.dylib              0xb56c _dispatch_lane_serial_drain + 376
12 libdispatch.dylib              0xc1e0 _dispatch_lane_invoke + 384
13 libdispatch.dylib              0x16e10 _dispatch_workloop_worker_thread + 652
14 libsystem_pthread.dylib        0xdf8 _pthread_wqthread + 288
15 libsystem_pthread.dylib        0xb98 start_wqthread + 8

DartWorker
0  libsystem_kernel.dylib         0x141c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8098 _pthread_cond_wait + 1276
2  Flutter                        0x68c1c0 (Missing UUID 4c4c444555553144a19d3dfde98674e8)
3  Flutter                        0x6c620c (Missing UUID 4c4c444555553144a19d3dfde98674e8)
4  Flutter                        0x68bb8c (Missing UUID 4c4c444555553144a19d3dfde98674e8)
5  libsystem_pthread.dylib        0x16cc _pthread_start + 148
6  libsystem_pthread.dylib        0xba4 thread_start + 8

DartWorker
0  libsystem_kernel.dylib         0x141c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8098 _pthread_cond_wait + 1276
2  Flutter                        0x68c1c0 (Missing UUID 4c4c444555553144a19d3dfde98674e8)
3  Flutter                        0x6c620c (Missing UUID 4c4c444555553144a19d3dfde98674e8)
4  Flutter                        0x68bb8c (Missing UUID 4c4c444555553144a19d3dfde98674e8)
5  libsystem_pthread.dylib        0x16cc _pthread_start + 148
6  libsystem_pthread.dylib        0xba4 thread_start + 8

io.ably.socketrocket.NetworkThread
0  libsystem_kernel.dylib         0xb48 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13008 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13248 mach_msg_overwrite + 388
3  libsystem_kernel.dylib         0x108c mach_msg + 24
4  CoreFoundation                 0x7aaf0 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7bd34 __CFRunLoopRun + 1232
6  CoreFoundation                 0x80ed4 CFRunLoopRunSpecific + 612
7  Foundation                     0x42334 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8  Ably                           0x53af8 -[ARTSRRunLoopThread main] + 216
9  Foundation                     0x5b808 __NSThread__start__ + 716
10 libsystem_pthread.dylib        0x16cc _pthread_start + 148
11 libsystem_pthread.dylib        0xba4 thread_start + 8

com.apple.CFSocket.private
0  libsystem_kernel.dylib         0x16ac __select + 8
1  libsystem_kernel.dylib         0x16ac select$DARWIN_EXTSN + 8
2  CoreFoundation                 0xcb6c4 __CFSocketManager + 636
3  libsystem_pthread.dylib        0x16cc _pthread_start + 148
4  libsystem_pthread.dylib        0xba4 thread_start + 8

com.google.firebase.crashlytics.startup
0  ???                            0x1c5c536c0 (Missing)
1  ???                            0x1c5c53634 (Missing)
2  ???                            0x1c5c552b0 (Missing)
3  FirebaseCrashlytics            0x26154 -[FIRCLSSymbolResolver updateStackFrame:] + 220
4  FirebaseCrashlytics            0x25a60 __36-[FIRCLSSymbolicationOperation main]_block_invoke + 56
5  FirebaseCrashlytics            0x2637c -[FIRCLSThreadArrayOperation enumerateFramesWithBlock:] + 264
6  FirebaseCrashlytics            0x25a1c -[FIRCLSSymbolicationOperation main] + 68
7  Foundation                     0x7b430 __NSOPERATION_IS_INVOKING_MAIN__ + 16
8  Foundation                     0x3c7d8 -[NSOperation start] + 708
9  FirebaseCrashlytics            0x1f5d4 -[FIRCLSProcessReportOperation symbolicateFile:withResolver:] + 236
10 FirebaseCrashlytics            0x1f744 __36-[FIRCLSProcessReportOperation main]_block_invoke + 68
11 FirebaseCrashlytics            0x16d88 -[FIRCLSInternalReport enumerateSymbolicatableFilesInContent:] + 200
12 FirebaseCrashlytics            0x1f6e4 -[FIRCLSProcessReportOperation main] + 172
13 Foundation                     0x7b430 __NSOPERATION_IS_INVOKING_MAIN__ + 16
14 Foundation                     0x3c7d8 -[NSOperation start] + 708
15 FirebaseCrashlytics            0x22a38 __91-[FIRCLSReportUploader prepareAndSubmitReport:dataCollectionToken:asUrgent:withProcessing:]_block_invoke + 460
16 FirebaseCrashlytics            0x61b4 FIRCLSApplicationActivity + 72
17 FirebaseCrashlytics            0x22824 -[FIRCLSReportUploader prepareAndSubmitReport:dataCollectionToken:asUrgent:withProcessing:] + 172
18 FirebaseCrashlytics            0x11618 -[FIRCLSExistingReportManager processExistingActiveReportPath:dataCollectionToken:asUrgent:] + 152
19 libdispatch.dylib              0x24b4 _dispatch_call_block_and_release + 32
20 libdispatch.dylib              0x3fdc _dispatch_client_callout + 20
21 libdispatch.dylib              0xb694 _dispatch_lane_serial_drain + 672
22 libdispatch.dylib              0xc1e0 _dispatch_lane_invoke + 384
23 libdispatch.dylib              0x16e10 _dispatch_workloop_worker_thread + 652
24 libsystem_pthread.dylib        0xdf8 _pthread_wqthread + 288
25 libsystem_pthread.dylib        0xb98 start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1050 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe44 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb98 start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1050 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe44 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb98 start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1050 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe44 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb98 start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1050 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe44 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb98 start_wqthread + 8`

**Comment by darshankawar** [comment]
@amiravisar89 
Have you tried implementing a runZonedGuard like below and check if using it, you still get the same crash or not ?

```
await runZonedGuarded(() async {
    WidgetsFlutterBinding.ensureInitialized();
    await Firebase.initializeApp();
    FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterError;
    runApp(MyApp());
  }, (error, stackTrace) {
    FirebaseCrashlytics.instance.recordError(error, stackTrace);
  });
```

**Comment by amiravisar89** [comment]
I will try that and let you know :)
