### ISSUE TITLE
🐛 [firebase_core_web] is throwing an exception when running in debug mode and asking the IDE to catch all exceptions

### ISSUE THREAD

**Issue by wer-mathurin** [firebase/flutterfire#11525]
## Bug report
In production is not a problem, the exception is not preventing the application to crash...but when debuging code (in VS code) is very common to is very common to activate:
![image](https://github.com/firebase/flutterfire/assets/39314023/9fac9df3-386b-4668-929d-915370f21d64)
 
and you will get this error:
![image](https://github.com/firebase/flutterfire/assets/39314023/4c9995b3-d2fd-4a61-b092-5be9be4f2050)

**Describe the bug**

### Steps to reproduce
Run the app with device Chrome.

```
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const App());
}

class App extends StatelessWidget {
  const App({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
```

### Expected behavior
Current code that interpreted as Uncaught Exceptions in VS Code and this look strange since this is catched!

 ```
 List<String> get _ignoredServiceScripts {
    try {
      JsObject ignored =
          JsObject.fromBrowserObject(context['flutterfire_ignore_scripts']);

      if (ignored is Iterable) {
        return (ignored as Iterable)
            .map((e) => e.toString())
            .toList(growable: false);
      }
    } catch (e) {
      // Noop
    }

    return [];
  }
```

But if we want to resolve this we can always do this:

 ```
 List<String> get _ignoredServiceScripts {
    try {
      final ignoreScripts = context['flutterfire_ignore_scripts'];
      if (ignoreScripts == null) return [];

      JsObject ignored = JsObject.fromBrowserObject(ignoreScripts);

      if (ignored is Iterable) {
        return (ignored as Iterable)
            .map((e) => e.toString())
            .toList(growable: false);
      }
    } catch (e) {
      // Noop
    }

    return [];
  }
```

**Comment by darshankawar** [comment]
Thanks for the report @wer-mathurin 
Can you take a look at https://github.com/firebase/flutterfire/issues/10468 and underlying comments and see if they help in your case or not ?

**Comment by wer-mathurin** [comment]
@darshankawar that's my point, the latest solution identified  in the ticket you referenced is not working as expected.  Uncaught exception still bring us to the failing code !

But we can argue that relying on exception to detect undefined value in the configuration is not self explanatory.

This is an easy PR to do and will make the code more.clear to me and solve this issue that is raised multiple time.

Any thoughts?

**Comment by darshankawar** [comment]
Thanks for the feedback @wer-mathurin 
I am wondering if this is related to dart specifically and it's effect rippled to flutterfire plugins. See https://github.com/dart-lang/sdk/issues/53334 and check if it helps further or not.

**Comment by wer-mathurin** [comment]
@darshankawar maybe this is related.  Can we let the ticket open until the hotfix land and see if this resolve the issue

**Comment by darshankawar** [comment]
Ok, will keep it open for now.

**Comment by russellwheatley** [comment]
The hot fix mentioned by @darshankawar has landed in Flutter, @wer-mathurin (in Flutter version >= v3.13.4). Could you try it out and see if it addresses your issue?
