### ISSUE TITLE
🐛 [FIREBASE_AUTH] Emulator in development doesn't work after logged in

### ISSUE THREAD

**Issue by matanshukry** [firebase/flutterfire#11534]
## Bug report

**Describe the bug**
My current app will set up the emulator on startup, and allow user to login.

If I'm using the emulator, then login, then close the app, then open it again - the emulator won't set up.
I've managed to put breakpoint on FlutterFire code and see the error - otherwise it won't surface, it just try to connect to the real firebase.

### Steps to reproduce

1. Launch the app
2. Login - emulator login popup shows
3. Close the app
4. Launch the app again
5. Click login - firebase real login popup shows.

### Expected behavior

on the 2nd login - emulator login popup shpuld show.

### Sample project

I can't do it at the moment, but I'm hoping to get some guidance on how to debug it on my own 🙏 

## Additional context

When I put breakpoint in `firebaes_auth_web.dart`:490, I can see this exception when it happens:

```
FirebaseError: Firebase: Auth instance has already been used to make a network call. Auth can no longer be configured to use the emulator. Try calling "connectAuthEmulator()" sooner. (auth/emulator-config-failed).
```

I'm calling useAuthEmulator as soon as possible.
Any chance I can put a breakpoint when it's used before? I tried to put in various places, but the same places seems to run when it's working + when it's not.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel stable, 3.13.1, on Microsoft Windows [Version 10.0.19045.3324], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.5.2)
[√] Android Studio (version 2022.3)
[√] IntelliJ IDEA Community Edition (version 2023.2)
[√] VS Code, 64-bit edition (version 1.79.2)
[√] Connected device (3 available)
[√] Network resources

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by HandsonOmbiro** [comment]
Firebase_auth 4.7.0 and above seems to have broken the way authentication works for web and how the useAuthEmulator is called. I have had the same experience immediately I updated to Flutter 3.13.0 and above (.1 and .2) with Firebase_auth 4.7.0 and above and as is your case, either you get what you are experiencing or the firebase emulator NEVER connects with authentication (thus, for my case, I will get local database (records and images (storage) but on authentication, it connect with live firebase. 

I have seen PR on changes in auth and some committed to Master, I did change the same based on the PR locally and the issue persisted. Finally I downgraded to Firebase_auth: ^4.6.3 even with 3.13.2 and everything went back to normal. 

For now, my advise is: use `firebase_auth: ^4.6.3`

**Comment by darshankawar** [comment]
Thanks for the report @matanshukry 
Can you take a look at [this](https://github.com/firebase/flutterfire/issues/11233) issue and check if it helps in your case or not ?

@HandsonOmbiro Can you file a new issue using template and provide relevant details on the issue you are facing, so that we can take a look at it properly and also be tracked separately ?

**Comment by matanshukry** [comment]
Sorry for the late reply - @darshankawar I missed your message.
Yes it was exactly that issue - and I ended up just removing the port and it worked. Thanks!
