### ISSUE TITLE
🐛 [FIREBASE_CORE, CLOUD_FIRESTORE, etc] FirebaseException sealed class

### ISSUE THREAD

**Issue by carloshpb** [firebase/flutterfire#11538]
Hello there!

Firsthand, I would like to thank the team for your hard work. Firebase is indeed an incredible platform at the moment, as it takes me pleasure to use it.
I don't know if this was asked before, but now since Dart 3 was released we've got sealed class ... which is great!

The only painful part (for me, at least) when dealing with any Firebase lib in Flutter is dealing with the exceptions.
As it has a lot of error codes (that are kinda of hard to find on the web ... Stackoverflow questions usually have some, but they are changing sometimes), it would be nice to make a sealed class of FirebaseException, with each error code having its own exception. This way, developers that use the libs will have to waste less time looking for the error codes to create a switch statement over. 

I like to build apps with clean architecture, which makes me isolate the APIs exceptions from the other layers and create new local ones from them. And thx to this idea of architecture, I usually end up creating a class to deal with FirebaseException with 2-3 switch cases (even more when dealing with internationalization).

So, that's it. Asking this so just we won't have to deal with old and new error codes all the time.

Thank you for your attention! :)

**Comment by darshankawar** [comment]
Thanks for the report @carloshpb 
Can you take a look at [this](https://stackoverflow.com/a/59668270) comment / answer and see if it helps further ?
