### ISSUE TITLE
🐛 [Firebase_auth]not working properly for Android  9 and lesser version.

### ISSUE THREAD

**Issue by vajesh-kumar-healy** [firebase/flutterfire#11531]
## Bug report

I am  using firebase_auth: ^4.6.3 for SSO using function signInWithProvider with OIDC. The sign in process works fine for Android version more than 9 (> SDK 28). But when it come to android version 9 or less than it. There is prompt  triggering on signInWithProvider function  which shows two option one is the actual app(App trying to authentication) and another is browser app. If I choose actual app it end's up infinite loop with in the sign in screen. But I click on browser app.It opens browser and then after authentication  the redirect Url is the same host name of the  app . So a new prompt  is triggered show the actual app and browser again.
If I choose the actual app.Its end up starting the app newly and If I hit on browser then it get#s stuck inside the browser app.
 
*SideNote: I have added host name inside the AndroidManifest.xml 

I hope the description is pretty clear. Thanks in advance

**Comment by kovacs-tamas** [comment]
I faced the same issue, do you have an idea how to fix it? The problem occurs on android 9 or older, my client is impatient

**Comment by darshankawar** [comment]
Thanks for the report @vajesh-kumar-healy 
Since you are using OIDC, can you check [this](https://stackoverflow.com/a/76629310) and see if it helps in your case or not ?
Also, since the reported behavior occurs on Android 9 or lesser, I am not sure if this would belong to plugin issue or a native Android. Is there a way for you to check the same on native Android app using Android 9 or lesser and confirm if it works there or not ?

**Comment by vajesh-kumar-healy** [comment]
@darshankawar The [this](https://stackoverflow.com/a/76629310) is not solving the issue.Since the implementation is same like the reference. I think the problem is  plugin from the beginning.I downgrade to 4.0.0. It happens there still.  And sorry don't have any reference for native android app with same feature to test.

**Comment by darshankawar** [comment]
@vajesh-kumar-healy 
I tried the plugin example by running it on Android api level 28 (Pie) and logged in using gmail account (ie, used Sign in with gmail) option with which I was able to login properly without any issues.

Although I didn't try with OIDC provider, which I am not much aware about, but if it works with google sign in provider, then it should probably work for other providers as well.

Can you try with any other sign in provider on api 28 version to confirm if it persists or not ?
