### ISSUE TITLE
Consider removing the author requirement on the no-response bot

### ISSUE THREAD

**Issue by Fernandomr88** [firebase/flutterfire#11544]
"Currently the no-response bot only removes the label if the original author comments. This isn't always desirable."

Since many times the author goes MIA and other users have the same problem and keep on commenting and helping out, the issue will be closed unless the author and only him comments.

I have already suffered with this in this repo and would like to suggest the same as it has been suggested at the flutter repo 
here: https://github.com/flutter/flutter/issues/133254

**Comment by darshankawar** [comment]
@Fernandomr88 Hello again :)

The https://github.com/google-oss-bot is maintained by firebase-tools and is leveraged by flutterfire repo and others. So I suggest you to file this issue in dedicated repo: https://github.com/firebase/firebase-tools/issues

Closing from here, as this doesn't seem to be actionable from flutterfire side.
