### ISSUE TITLE
 Build fails with: Execution failed for task ':app:mapDebugSourceSetPaths'

### ISSUE THREAD

**Issue by dumabg** [firebase/flutterfire#11543]
## Bug  
The same described in  #8238 

## Resolution
flutterfire configure adds this lines in build.gradle:

// START: FlutterFire Configuration
        classpath 'com.google.gms:google-services:4.3.10'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.8.1'
// END: FlutterFire Configuration

'com.google.gms:google-services:4.3.10' is the cause of this bug.

Change to 'com.google.gms:google-services:4.3.15' and it works.

**Comment by darshankawar** [comment]
@dumabg 
If this is related to `flutterfire configure` command that adds a specific version of google-service which causes a bug, then it need to be reported in CLI's dedicated repo : https://github.com/invertase/flutterfire_cli/issues

Closing from here.
