### ISSUE TITLE
🐛 [Firebase Crashlytics] Your issue title here

### ISSUE THREAD

**Issue by onkarmonks** [firebase/flutterfire#11556]
## Bug report

We are triggering some errors to firebase with the below code  - 
PlatformDispatcher.instance.onError = (final error, final stack) {
      FirebaseCrashlytics.instance.recordError(error, stack, fatal: true);
      return true;
    };

As these are rightly logged in the crashlytics dashboard as shown below but the proximity on the dashboard shows as 0% background but while using the app we are not experiencing any crash. But it looks like a background error not impacting the user / crash. Can we get more clarity on this.

Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Bad state: No element. Error thrown during a scheduler callback.
       at List.single(dart:core)
       at ScrollController.position(scroll_controller.dart:107)
       at ScrollTracker.startTracking(scroll_tracker.dart:24)
       at _CarouselState.initState.<fn>(carousel.dart:49)
       at SchedulerBinding._invokeFrameCallback(binding.dart:1284)
       at SchedulerBinding.handleDrawFrame(binding.dart:1223)
       at SchedulerBinding._handleDrawFrame(binding.dart:1072)

<img width="552" alt="Screenshot 2023-09-05 at 7 18 15 PM" src="https://github.com/firebase/flutterfire/assets/59840952/8e5652e3-c831-4558-b612-c2df1640e732">

### Steps to reproduce

Call FirebaseCrashlytics.instance.recordError() and check for proximity on crashlytics dashboard

### Flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.5.1 22G90 darwin-arm64, locale
    en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS
      and macOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] Android Studio (version 2022.3)
[✓] Connected device (2 available)
[✓] Network resources

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

firebase_analytics 10.4.5 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_analytics_platform_interface 3.6.5 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.4+5 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_core_platform_interface 4.8.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.7.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics 3.3.5 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_crashlytics_platform_interface 3.6.5 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging 14.5.0 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_messaging_platform_interface 4.5.6 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.5.6 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_performance 0.9.2+5 [firebase_core firebase_core_platform_interface firebase_performance_platform_interface firebase_performance_web flutter]
- firebase_performance_platform_interface 0.1.4+5 [_flutterfire_internals firebase_core flutter plugin_platform_interface]
- firebase_performance_web 0.1.4+5 [_flutterfire_internals firebase_core firebase_core_web firebase_performance_platform_interface flutter flutter_web_plugins js]

---

**Comment by danagbemava-nc** [comment]
Hi @onkarmonks, I'm not sure I follow. Do you get this exception in your app? And are surmising that this is a background error?

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Bad state: No element. Error thrown during a scheduler callback.
at List.single(dart:core)
at ScrollController.position(scroll_controller.dart:107)
at ScrollTracker.startTracking(scroll_tracker.dart:24)
at _CarouselState.initState.(carousel.dart:49)
at SchedulerBinding._invokeFrameCallback(binding.dart:1284)
at SchedulerBinding.handleDrawFrame(binding.dart:1223)
at SchedulerBinding._handleDrawFrame(binding.dart:1072)
```

**Comment by onkarmonks** [comment]
Hi @danagbemava-nc - what i meant is, these issues are actually not causing a crash on the device and they must be tagged as a background crashes but if you see the screen shot it says 0% background

**Comment by danagbemava-nc** [comment]
These are error messages from the flutter framework which is likely why they are not being reported as crashes. There are some errors that you get but do not stop your app from functioning. The background is for when the application is not active (or in the foreground). 
Does this clear it up for you?

**Comment by onkarmonks** [comment]
@danagbemava-nc  - that explains my query. Thanks, a lot.
