### ISSUE TITLE
🐛 [PLUGIN_NAME_HERE] Your issue title here

### ISSUE THREAD

**Issue by asseries** [firebase/flutterfire#11558]
Note: /Users/adxamsoataliyev/.pub-cache/hosted/pub.dev/vibration-1.8.1/android/src/main/java/com/benjaminabel/vibration/VibrationPlugin.java uses or overrides a deprecated API.

**Comment by danagbemava-nc** [comment]
Vibration is a third-party package. Any issues you face using it should be reported on their repo. It seems this has already been filed on their repo https://github.com/benjamindean/flutter_vibration/issues/87. 

Closing from here
