### ISSUE TITLE
Unable to check for empty/undefined fields in firestore is a big issue

### ISSUE THREAD

**Issue by jmw11x** [firebase/flutterfire#11563]
## Bug report

**Describe the bug**
Unable to check for empty field value in docs.forEach((value) value

[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: field does not exist within the DocumentSnapshotPlatform

### Steps to reproduce

try to access a field that is not there in firebase
2. '...'
3. See error or incorrect behavior

### Expected behavior

value['thing'] == null SHOULD NOT break the application. Null checks should be required and if it is not included the package is not robust and this is a huge problem
value['thing'] also should not return the same error. 

AKA some way of checking if this is there or not should be inside this package or it is incomplete.

the only way currently to do this is check like this
value.data().toString().contains('thing:')) which can be inconsistent if any key or value contains the string 'thing:'

value['thing']==null// return true not break the application and cause 
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: field does not exist within the DocumentSnapshotPlatform

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

No issues with this........

</details>

---

**Comment by danagbemava-nc** [comment]
Hi @jmw11x, please provide the version of cloud_firestore you're using. 
Please also provide a complete minimal reproducible code sample in a repo that we can clone so that we can investigate this. 

Please also format your issue description so that it is clear what the issue is. 

Thank you

**Comment by jmw11x** [comment]
To be clear this issue is that I would like to access a record without raising an exception. For ex. in Javascript firebase sdk I can check the ...forEach((**value**) => .... like this

value['<field key name>'] == undefined // returns true or false. Where in flutter it raises an error and crashes the app.

**Comment by danagbemava-nc** [comment]
Hi @jmw11x, can you check if https://stackoverflow.com/a/68607904 works for you?
