### ISSUE TITLE
🐛 [PLUGIN_NAME_HERE] Your issue title here

### ISSUE THREAD

**Issue by ALISOHEELHAYAJNEH** [firebase/flutterfire#11569]
## Bug report

**Describe the bug*
getdownloadurl in firestorage print in debug console stars

Future uploadFile() async {
    if (_photo == null) return;
    final fileName = basename(_photo!.path+"jjjjjjjjj");
    const destination = 'images/';

    try {
      final ref = _storage.ref(destination+fileName);
      await ref.putFile(_photo!);
      String url = (await ref.getDownloadURL());
      print(url);
    } catch (e) {
      print('error occured');
    }
  }

### Steps to reproduce

2. '...'
3. See error or incorrect behavior

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```
I/flutter ( 5861): *******************************************************************************************************************************************************************************
sometime future<String>instance i tried all ways in all websites but no way 
</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by darshankawar** [comment]
@ALISOHEELHAYAJNEH 
Your issue isn't clear as what exactly are you trying to report. Please elaborate your description with actual and expected results with clear logs if any that shows the reported behavior.
