### ISSUE TITLE
 🐛 [firebase_dynamic_links] Define custom short suffix of dynamic link #11000 

### ISSUE THREAD

**Issue by baptistesx** [firebase/flutterfire#11566]
I saw related issues: [1182](https://github.com/firebase/quickstart-unity/issues/1182) and [11000](https://github.com/firebase/flutterfire/issues/11000) but does really give me a solution...

I'd simply need to custom the suffix of short link, as we can do on the web console:

![image](https://github.com/firebase/flutterfire/assets/9638281/c7ab53b7-52ce-4ed2-8477-bc0353168361)

I've also found this: https://pypi.org/project/firebase-dynamic-links-generator/#description
which uses customPrefix but it doesn't seem to work.

Any suggestion?

Thanks in advance

**Comment by russellwheatley** [comment]
This is not possible from Dynamic Link API, and Firebase has stated it will only fix critical or security issues for this service as it will be shutdown on August 25, 2025: [firebase.google.com/support/dynamic-links-faq](https://firebase.google.com/support/dynamic-links-faq)
