### ISSUE TITLE
🐛 [flutterfire-cli] FlutterFire CLI should also generate firebase-messaging-sw.js, or at least ensure we do not have to hardcode one ourselves

### ISSUE THREAD

**Issue by jakusb** [firebase/flutterfire#11580]
## Bug report

**Describe the bug**
Running "flutterfire configure" works like a charm for normal Firebase operations, but is missing out on Cloud Messaging assistance. We now need to still manually and hardcoded introduce our own firebase-messaging-sw.js for web.

### Steps to reproduce

1) Run "flutterfire configure"
2) Notice web/firebase-messaging-sw.js is not created

### Expected behavior
web/firebase-messaging-sw.js or any working equivalent should be created, optionally through flag or always

### Sample project
---

## Additional context
---

### Flutter doctor
---

### Flutter dependencies
---

**Comment by danagbemava-nc** [comment]
Hi @jakusb, the flutterfire_cli lives in a different repo. Kindly file this issue over there. https://github.com/invertase/flutterfire_cli/issues?q=is:issue+is:open+sort:updated-desc

Closing from here. 

Thank you
