### ISSUE TITLE
🐛 [firebase_auth] [firebase_core] [firebase_storage] [cloud_firestore] Log Spam "No App Check token for request" on Android Emulator

### ISSUE THREAD

**Issue by Lootwig** [firebase/flutterfire#11582]
Running an app that relies on all of the mentioned packages I get the warning `W/NetworkRequest( 4488): No App Check token for request.` spammed over and over.

Googling "disable app check" yields nothing but results with instructions on how to ENABLE app check.

**I do not want to enable app check.**

I also don't want whatever package is trying to use an app check token to warn me about failing to do so, because I never specified that it's supposed to attempt using one in the first place.

I also would like to know which of the mentioned packages is generating that warning in the first place because I cannot file a better bug report this way.

---

Please include in your documentation how to disable app check usage attempts.

Please provide a way to disable the warning.

Please change the warning to one that is useful, i.e. one that includes a stack trace, details on the specific resource requested, package name, a link with further docs.

**Comment by danagbemava-nc** [comment]
Hi @Lootwig, what firebase auth services have you activated for your project? This may likely be coming from firebase auth. 

Some services from firebase require appcheck and unfortunately, this is not something the flutterfire plugins control as these plugins are just wrappers around the native sdks.

**Comment by Lootwig** [comment]
@danagbemava-nc Email/PW, Google, Facebook and Apple are enabled

Which ones of these are requiring app check?

I've tried searching the repo for the error message, but it seems to be coming from another codebase :-/

**Comment by danagbemava-nc** [comment]
It doesn't seem like these ones require app check.

Do you get this on a physical device? Also, does the emulator have playstore support?
