### ISSUE TITLE
🐛 [Firebase Messaging] Firebase Messaging Initialization Issue in Release Package

### ISSUE THREAD

**Issue by puri-new** [firebase/flutterfire#11583]
# Bug report

When we run the app with Firebase Messaging in a release package on IOS device, the app randomly hangs on getting the Firebase token (which we do on the app home page). In non release mode, it always works fine, and in release mode on IOS, sometimes works fine (which probably means that the configuration is correct), sometimes hangs. The application works fine in all cases on Android.

This issue does not produce any error logs or messages in the release package and we haven’t been able to understand when the issue happens. We confirmed though that if we comment the part that gets the Firebase token the application always runs fine in release mode.

## Steps to reproduce

1. Initialize Firebase Messaging in the project 
2. Config project align the Flutter integration document
3. Do packaging for iOS release

### Flutter doctor

```
[✓] Flutter (Channel stable, 3.7.10, on macOS 13.2.1 22D68 darwin-arm64, locale en-TH)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
```

---

### Flutter dependencies

```
firebase_messaging: ^14.6.7
firebase_core: ^2.15.1
permission_handler: ^10.2.0
```

---

### Debugging steps that already try, but it still didn’t solve the problem :
1. re-check the setup process align with : https://firebase.flutter.dev/docs/messaging/apple-integration/
2. Change the config align with : https://github.com/firebase/flutterfire/issues/2672

**Comment by danagbemava-nc** [comment]
Hi @puri-new, I noticed you're using an older version of flutter, can you try upgrading to the latest version of flutter to see if this issue still persists?

**Comment by puri-new** [comment]
Thank you for your answer @danagbemava-nc, I alraedy try to upgrade my flutter to `Flutter (Channel stable, 3.13.4, on macOS 13.2.1 22D68 darwin-arm64, locale en-TH)` and rebuild the release package. It still have the issue.

**Comment by danagbemava-nc** [comment]
Hi @puri-new, when you run in release mode locally, do you still get this issue? What iOS device(s) are you seeing this issue on?

**Comment by puri-new** [comment]
Hi @danagbemava-nc I'm sorry for the late response. When I run in release mode locally, this issue does not happen. The issue happened to all of the iOS devices that I tested on `iPhone 12 Pro with iOS 16.5, iPhone 12 Pro with iOS17 [public beta], iPhone 13 Pro max with iOS 16.6`

**Comment by danagbemava-nc** [comment]
Hi @puri-new, can you share the code that you use to initialize firebase messaging & other firebase services (if applicable)?

**Comment by puri-new** [comment]
@danagbemava-nc  I'm truly sorry, but we're still working on fixing the code and cannot provide it at this time.

**Comment by danagbemava-nc** [comment]
Anytime you can share the minimal sample is fine.

PS: it does not have to be your project, in fact, if it is a standalone app that reproduces the issue, that is much better as it makes it easier for us trace the source/cause of the issue

**Comment by puri-new** [comment]
For now, my team is in the process of initiating a new standalone project to reproduce this issue. If there are any updates, I will share them with you.

**Comment by danagbemava-nc** [comment]
Please keep us updated
