### ISSUE TITLE
🐛 [firebase_auth] signInWithCredentials with custom OIDC OAuthProvider

### ISSUE THREAD

**Issue by YoamFarges** [firebase/flutterfire#11591]
## Bug report

Users can login with Azure ADB2C within my application by using a pretty standard OAuth2 authentication. My goal is for these logged-in users to be able to access their resources on one or multiple firebase projects, without having them being asked to re-enter their credentials. For that, it looks like the _signinWithCredentials_ method would be exactly what I need so that I can pass the `accessToken` from the initial authentication to Firebase.

However, on flutter _signinWithCredentials_ with a custom OpenID Connect (OIDC) `OAuthProvider` behaves incorrectly and gives me several errors depending on the provided credentials.

### Steps to reproduce

_NB: Mainly tested on flutter iOS 16+._

##### 1. Setup the OIDC provider on firebase
<details>
<summary>Screenshot of the OIDC configuration</summary>

![image](https://github.com/firebase/flutterfire/assets/2854976/73be3e13-60af-45c9-babe-c44fd7997db6)

</details>

##### 2. Verify quickly that the OIDC provider configuration works properly with `signInForProvider` (it does).
<details open>
<summary>Code details</summary>

```
// This works as expected. The app will open the AzureADB2C login page, 
// and after login, will create a firebaseAuth user.
Future<void> _loginWithFirebase() async {
    final provider = OAuthProvider('oidc.azure-ad-b2c-test');
    try {
      var firebaseAuth =
          await FirebaseAuth.instance.signInWithProvider(provider);
      debugPrint("success! ${firebaseAuth.user}");
    } catch (error) {
      debugPrint('_loginWithFirebase: $error');
    }
  }
```

</details>

##### 3. Implement the OAuth2 login, and retrieve the token after successful authentication.
<details open>
<summary>Code details</summary>

```
   final AuthorizationTokenResponse? result =
    await appAuth.authorizeAndExchangeCode(
          AuthorizationTokenRequest(
            azureContext.azureClientId, 
            'msauth.com.example.app.dev://auth/',
            issuer: azureContext.issuerUrl,
            scopes: ['openid']
            )
        );
    debugPrint("SUCCESS ${result!.accessToken} ${result!.idToken}");
```

</details>

  - NB: we use `flutter_appauth` in this example but could use any other auth library.
  - We retrieve successfully both an `accessToken` and an `idToken`. 
  - NB: the idToken contains a nonce.

##### 4. Attempt to login with `signInWithCredentials` to Firebase. First with simply the `accessToken`.
<details open>
<summary>Code details</summary>

```
final provider = OAuthProvider('oidc.azure-ad-b2c-test');
    final credentials = provider.credential(
        accessToken: result.accessToken);
    try {
      var firebaseAuth =
          await FirebaseAuth.instance.signInWithCredential(credentials);
      debugPrint("success! ${firebaseAuth.user}");
    } catch (error) {
      debugPrint('_loginWithFirebaseWithCredentials error: $error');
    }
```
</details>

  - ⚠️ We receive an error :  `flutter: _loginWithFirebaseWithCredentials error: type 'int' is not a subtype of type 'String' in type cast` which comes from `~/.pub-cache/hosted/pub.dev/firebase_auth_platform_interface-6.18.0/lib/src/pigeon/messages.pigeon.dart` line 1069 in the `signInWithCredential` method.
  - With the problematic code being :
```
 throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
```

where replyList[0] is actually an Int.
<img width="351" alt="image" src="https://github.com/firebase/flutterfire/assets/2854976/26454456-39f9-482c-a95c-f6245415b609">
- ⚠️ **What's interesting is that the underlying error makes no sense either**, especially the localhost part (especially as I do NOT use firebase emulator): `INVALID_CREDENTIAL_OR_PROVIDER_ID : Invalid IdP response/credential: http://localhost?providerId=oidc.azure-ad-b2c-test&access_token=eyJhbGciOiJ[...REDACtED...]Exhs6COA`

##### 5. Apparently, the accessToken does not work. Fine we can try with `idToken` + `rawNonce`. 
<details open>
<summary>Code details</summary>

```
 Map<String, dynamic> decodedToken = JwtDecoder.decode(result!.idToken!);
    final nonce = decodedToken?['nonce']!;
    final bytes = utf8.encode(nonce);
    final hashedNonce = sha256.convert(bytes).toString();

    final provider = OAuthProvider(azureContext.firebaseAuthProviderName);
    final credentials = provider.credential(
        idToken: _azureResult?.idToken,
        rawNonce: hashedNonce.toString());
    try {
      var firebaseAuth =
          await FirebaseAuth.instance.signInWithCredential(credentials);
      debugPrint("success! ${firebaseAuth.user}");
    } catch (error) {
      debugPrint('_loginWithFirebaseWithCredentials error: $error');
    }
```

</details>

  - ⚠️ However it looks like the nonce is always considered as invalid.
    - Without hashing : `[firebase_auth/missing-or-invalid-nonce] The nonce in ID Token "R8BTkEwFY_-1KjZELGrgTSZ4Anf49gsOAhVOePJMS7s" does not match the SHA256 hash of the raw nonce "R8BTkEwFY_-1KjZELGrgTSZ4Anf49gsOAhVOePJMS7s" in the request.`
    - With hashing : `[firebase_auth/missing-or-invalid-nonce] The nonce in ID Token "R8BTkEwFY_-1KjZELGrgTSZ4Anf49gsOAhVOePJMS7s" does not match the SHA256 hash of the raw nonce "536dc330a89d0556fad0f6f4c7d28763f9de0bb1145c54723307fd6c1f148229" in the request.`

### Expected behavior

Expected would be a successful retrieval of a FirebaseAuth object when using `signInWithCredential` with a custom OIDC`OAuthProvider`, in both cases (accessToken / idToken + nonce)

### Sample project

Unfortunately I cannot share a sample project due to sensible information around the Azure policy access.

---

## Additional context

Looks related to : https://github.com/firebase/flutterfire/issues/10865#issuecomment-1600930917.
It is unclear that custom OIDC is supported by Flutterfire : if that is not, a clarification would be welcome.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.5.2 22G91 darwin-arm64, locale fr-CH)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.82.1)
[✓] Connected device (4 available)
    ! Device 28201FDH300APX is not authorized.
      You might need to check your device for an authorization dialog.
[✓] Network resources

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 3.0.6
Flutter SDK 3.10.6
login_firebase_azure 1.0.0+1

dependencies:
- cloud_firestore 4.9.1 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- crypto 3.0.3 [typed_data]
- cupertino_icons 1.0.6
- firebase_auth 4.9.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.15.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection js material_color_utilities meta vector_math sky_engine]
- flutter_appauth 6.0.2 [flutter flutter_appauth_platform_interface]
- jwt_decoder 2.0.1

dev dependencies:
- flutter_lints 2.0.3 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection js matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- _flutterfire_internals 1.3.5 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- cloud_firestore_platform_interface 5.16.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.7.0 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.17.1
- fake_async 1.3.1 [clock collection]
- firebase_auth_platform_interface 6.18.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.8.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser js meta]
- firebase_core_platform_interface 4.8.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.7.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_appauth_platform_interface 6.0.0 [flutter plugin_platform_interface]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- js 0.6.7 [meta]
- lints 2.1.1
- matcher 0.12.15 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.2.0
- meta 1.9.1
- path 1.8.3
- plugin_platform_interface 2.1.6 [meta]
- sky_engine 0.0.99
- source_span 1.9.1 [collection path term_glyph]
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.5.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.2 [collection]
- vector_math 2.1.4
```

</details>

---

**Comment by danagbemava-nc** [comment]
Hi @YoamFarges, can you try the comment in this SO post to see if it helps? https://stackoverflow.com/a/76629310

**Comment by YoamFarges** [comment]
Thanks @danagbemava-nc . I looked at it already. It's actually working fine with _signInWithProvider_, but not with _signInWithCredentials_.
