### ISSUE TITLE
APNS token not found...

### ISSUE THREAD

**Issue by computerfriendlog2** [firebase/flutterfire#11590]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you aware of the differences between iOS and Android background message handling?

- [X] I understand that iOS and Android background messages behave differently, and I've designed my application with that in mind.

### Do you have an active Apple Developer account?

- [X] I have an active Apple Developer account.

### Are you using a physical iOS device to test background messages?

- [X] I am using a physical iOS device to test background messages.

### Have you enabled "Remote Notifications" & "Background Mode" (Checking options for "Background Processing" & "Remote Notifications") in your app's Xcode project?

```
flutter: exception while permission of messaging    [firebase_messaging/apns-token-not-set] APNS token has not been set yet. Please ensure the APNS token is available by calling `getAPNSToken()`.
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: [firebase_messaging/apns-token-not-set] APNS token has not been set yet. Please ensure the APNS token is available by calling `getAPNSToken()`.
#0      MethodChannelFirebaseMessaging._APNSTokenCheck (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:138:9)
<asynchronous suspension>
#1      MethodChannelFirebaseMessaging.getToken (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:244:5)
<asynchronous suspension>
#2      PushNotificationService.initializeFCMToken (package:firebase_notifications_handler/src/service.dart:132:19)
<asynchronous suspension>
#3      PushNotificationService.initialize (package:firebase_notifications_handler/src/service.dart:110:17)
<asynchronous suspension>
#4      _FirebaseNotificationsHandlerState.initState.<anonymous closure> (package:firebase_notifications_handler/src/widget.dart:267:21)
<asynchronous suspension>
flutter: initialized---
```

### Have you created an APNs key in your Apple Developer account & uploaded this APNs key to your Firebase console?

yes

### Have you disabled method swizzling for Firebase in your app?

yes

### Are you sending messages to your app from the Firebase Admin SDK?

yed

### Have you requested permission from the user to receive notifications?

- [X] I have the relevant permission to receive notifications.

### Have you used the 'Console' application on your macOS device to check if the iOS device's system is throttling your background messages?

```
flutter: exception while permission of messaging    [firebase_messaging/apns-token-not-set] APNS token has not been set yet. Please ensure the APNS token is available by calling `getAPNSToken()`.
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: [firebase_messaging/apns-token-not-set] APNS token has not been set yet. Please ensure the APNS token is available by calling `getAPNSToken()`.
#0      MethodChannelFirebaseMessaging._APNSTokenCheck (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:138:9)
<asynchronous suspension>
#1      MethodChannelFirebaseMessaging.getToken (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:244:5)
<asynchronous suspension>
#2      PushNotificationService.initializeFCMToken (package:firebase_notifications_handler/src/service.dart:132:19)
<asynchronous suspension>
#3      PushNotificationService.initialize (package:firebase_notifications_handler/src/service.dart:110:17)
<asynchronous suspension>
#4      _FirebaseNotificationsHandlerState.initState.<anonymous closure> (package:firebase_notifications_handler/src/widget.dart:267:21)
<asynchronous suspension>
flutter: initialized---
```

**Comment by computerfriendlog2** [comment]
please let me know how can I solve it... I have implemented more than 10 apps before this firebase notification each time this issue come and unexpectedly resolved but today its not resolving by me....

**Comment by danagbemava-nc** [comment]
Hi @computerfriendlog2, in the newer version of messaging, the APNS token is required. When you call `getAPNSToken()`, what response do you get?

**Comment by computerfriendlog2** [comment]
Thank you for your response.

I'm using firebase_messaging: ^14.6.7

initNotification()async {
  try{
    //FirebaseMessaging.instance.requestPermission();
    FirebaseMessaging _messaging = FirebaseMessaging.instance;
    FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
    NotificationSettings settings = await _messaging.requestPermission (
      alert: true,
      announcement: false,
      badge: true,
      carPlay: false,
      criticalAlert: false,
      provisional: false,
      sound: true,
    );

    print('User granted permission: ${settings.authorizationStatus}');
    print('User granted permission:
${settings.authorizationStatus.toString()
=='AuthorizationStatus.authorized'}');
    if(settings.authorizationStatus.toString()
=='AuthorizationStatus.authorized') {
      print('1 token is   ');
      String? apns_token1= await _messaging.getToken() ?? '';
      print('d token 1 is   $apns_token1');
      // String apns_token= await _messaging.getAPNSToken() ?? '';
      // print('apns token is   $apns_token');
      // String fcm_token = Platform.isIOS? await
_messaging.getToken(vapidKey: apns_token) ?? '': await
_messaging.getToken() ?? '';
  print('fcm token is   $apns_token1');
  await LocalDatabase.saveString(LocalDatabase.FIREBASE_MSG_TOKEN,
apns_token1??'');
  FirebaseMessaging.onMessage.listen((RemoteMessage message) {
  print('Received message: ${message.notification?.title}');
  final LocalNotificationService localNotification = LocalNotificationService();
  localNotification.initializNotifications();
  localNotification.sendNotification(message.notification?.title??'',
message.notification?.body??'');
  // Handle the notification here
  });
  FirebaseMessaging.onMessageOpenedApp.listen((RemoteMessage message) {
  print('Message opened when app is in foreground:
${message.notification?.body}');
  // Handle the notification here
  });


  }
  } catch(e) {
  print('exception while permission of messaging    ${e.toString()}');
  }

}

in main function just after firebase initialization.


Changes which I made in swift

import UIKit
import Flutter
import Firebase
import FirebaseMessaging

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions:
[UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
          FirebaseApp.configure()

             if #available(iOS 10.0, *) {
                 UNUserNotificationCenter.current().delegate = self
as? UNUserNotificationCenterDelegate
             }

    GeneratedPluginRegistrant.register(with: self)
    return super.application(application,
didFinishLaunchingWithOptions: launchOptions)
  }

      override func application(_ application: UIApplication,
didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
       Messaging.messaging().apnsToken = deviceToken
       print("Token: \(deviceToken)")

       super.application(application,
        didRegisterForRemoteNotificationsWithDeviceToken: deviceToken)
     }
}





Also I have setup APNs key on firebase. Its valid and membership is also
valid.


<key>FirebaseAppDelegateProxyEnabled</key>
<true/>

<key>UIBackgroundModes</key>
<array>
   <string>fetch</string>
   <string>remote-notification</string>
</array>

I put through xcode in plist which for all tabs "'all", debug, release and
profile also.


After all unable to get token... Please help me I'm stucked here from 3
days.

Thanks in advance

**Comment by danagbemava-nc** [comment]
Hi @computerfriendlog2, can you check https://github.com/firebase/flutterfire/issues/11548#issuecomment-1705218284 to see if it helps?

**Comment by msarkrish** [comment]
@danagbemava-nc I'm not calling getAPNSToken() method. because I'm not using that token for sending notification. 
Is it mandatory to call that method?
If I'm missing something kindly guide me @danagbemava-nc

**Comment by danagbemava-nc** [comment]
@msarkrish, that method is called by the plugin to check if the APNS has been properly setup. You should call it before calling getToken. The APNS being setup properly is not a requirement. See https://github.com/firebase/firebase-ios-sdk/issues/10742

**Comment by msarkrish** [comment]
@danagbemava-nc  I'm not calling getToken method. Because I don't need that token. I'm just trying to subscribe to topic alone. 

Still I have to call getAPNSToken method before subscribing to topic?

**Comment by linsendidi** [comment]
I try with the latest flutter sdk(3.13.6) and latest firebase sdk. Currently the getAPNSToken method will return null when first time user given the push notification permission and I try to get the token directly. After 3 seconds I call getAPNSToken again, I will get the token. Also when I closed the app and reopen again, I can get the token as well. So the only problem is the first time I try to call getAPNSToken and return null.
