### ISSUE TITLE
🐛 [firebase_analytics] The firebase_analytics is not working on android, works fine on ios

### ISSUE THREAD

**Issue by LuisOtavioOliveira** [firebase/flutterfire#11592]
## Bug report

I used the dart-only initialization, with flutterfire cli, and everything works fine, firebase_messaging works on ios and android, and the firebase_analytics works on ios, but not on android

**Comment by danagbemava-nc** [comment]
Hi @LuisOtavioOliveira, when you say it doesn't work on android, can you please provide full details as to how it does not work? 

Please also provide the version of the flutterfire plugins you're using along with the output of `flutter doctor -v` and a complete minimal reproducible code sample in a repo that we can clone so that we can investigate this. 

Thank you

**Comment by LuisOtavioOliveira** [comment]
I'm using these versions of firebase plugins:
firebase_analytics: ^10.4.3
firebase_core: ^2.15.1

flutter doctor shows no issues, and firebase_messaging and cloud_firestore are both working, firebase_analytics works on ios, but when i open the app on android, nothing happens in the real time analytics, i've already re-installed the firebase_core and changed version, but just doesn't work, i´ve already tried the manual installation too but no sucess.

**Comment by danagbemava-nc** [comment]
Hi @LuisOtavioOliveira, do you have this same issue when you use the code sample from the firebase_anayltics example? 

It would help if you could provide a minimal sample in a repo that we can clone so that we can investigate this. 

Thank you

**Comment by LuisOtavioOliveira** [comment]
I solved the problem using the manual installation, and adding the permissions to AndroidManifest.xml.
in AndroidManifest.xml:
 <uses-permission android:name="android.permission.INTERNET" />
 <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
in android/build.gradle:
classpath 'com.google.gms:google-services:4.3.15'
in android/app/build.gradle:
apply plugin: 'com.google.gms.google-services'
in main.dart:
  Platform.isAndroid
      ? await Firebase.initializeApp()
      : await Firebase.initializeApp(
          options: DefaultFirebaseOptions.currentPlatform);
