### ISSUE TITLE
🐛 [firebase_messaging] RemoteMessage.RemoteNotification.AppleNotification doesn't receive all values in onMessage

### ISSUE THREAD

**Issue by darkang3lz92** [firebase/flutterfire#11608]
## Bug report

**Describe the bug**
Trying to get notification value from `RemoteMessage` and generate a local notification alert with same setup from fcm. So, would like to retrieve `sound` value from `AppleNotification` in `onMessage` but it's always returning null even though `sound` value is specified in FCM aps payload.

### Steps to reproduce

1. Push a notification with aps payload
```json
{
    "message": {
        "token": "my.fcm.token.here",
        "notification": {
            "body": "Test body",
            "title": "Test Title"
        },
        "apns": {
            "payload": {
                "aps": {
                    "badge" : 1,
                    "sound" : "a_custom_sound.wav"
                }
            }
        }
    }
}
```
2. This should trigger `FirebaseMessaging.onMessage.listen`.
3. Retrieve value from `RemoteMessage message`, `message.notification?.apple`.
4. Only receive badge value in the result while sound is null
```dart
"badge": "1",
"sound": null
```

### Expected behavior

Receive both `badge` and `sound` value from `AppleNotification`.

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.10.1, on macOS 13.3.1 22E772610a darwin-x64, locale en-MY)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.82.0)
[✓] Connected device (3 available)
[✓] Network resources
```

</details>

---

Is this a bug or it's intended to not receive `sound` value?

**Comment by darshankawar** [comment]
Thanks for the report @darkang3lz92 
Can you check if `sound` property comes back properly on Android if possible ?
That way we can check further if it is an issue in ios side of the plugin or a native SDK issue.

You can also use plugin [example's](https://github.com/firebase/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/example/scripts/send-message.js) script, add `sound` property to the payload and check if using it, do you get the property value back or not.

**Comment by darkang3lz92** [comment]
Hi @darshankawar,

Tested for `Android` with this payload.

```
{
    "message": {
        "token": "my.fcm.token.here",
        "notification": {
            "body": "Test body",
            "title": "Test Title"
        },
        "android": {
            "priority": "high",
            "notification": {
                "sound": "a_custom_sound",
                "channel_id": "my_channel"
            }
        },
        "apns": {
            "payload": {
                "aps": {
                    "badge" : 1,
                    "sound" : "a_custom_sound.wav"
                }
            }
        }
    }
}

```

`message.notification?.android` is working correctly
```dart
"channelId": "my_channel",
"sound": "a_custom_sound"
```

**Comment by darshankawar** [comment]
Thanks for the update. Can you check if you have properly setup the configuration for iOS as mentioned in the documentation:

https://firebase.google.com/docs/cloud-messaging/flutter/client#ios

Also, the documentation says to request for permission that has `sound` property as `true` that you can try and check if it works in your case or not:

https://firebase.google.com/docs/cloud-messaging/flutter/receive

**Comment by darkang3lz92** [comment]
Hi yes, I believe I have properly setup and already added `sound` property as `true` with

```dart
await FirebaseMessaging.instance.requestPermission(
  sound: true,
  badge: true,
  alert: true,
  provisional: true,
);
```

If I push notification in `background` mode, it does play the custom notification sound in the device, but in `foreground` mode I unable to retrieve the `sound` value, which is through `FirebaseMessaging.onMessage.listen`.

**Comment by darshankawar** [comment]
Thanks for the update. Check https://github.com/firebase/flutterfire/issues/10804#issuecomment-1662174305 and see if it helps in your case or not.

**Comment by darkang3lz92** [comment]
I can use `setForegroundNotificationPresentationOptions` as workaround, but if possible, would like to handle the notification alert myself.

**Comment by darshankawar** [comment]
> but if possible, would like to handle the notification alert myself.

This sounds like an enhancement for which you may file a new issue with relevant details.



> I can use `setForegroundNotificationPresentationOptions` as workaround

If this has resolved your issue, you may close this.
