### ISSUE TITLE
firebase_core (from `.symlinks/plugins/firebase_core/ios`) was resolved to 2.16.0, which depends on       Firebase/CoreOnly (= 10.15.0)🐛 [PLUGIN_NAME_HERE] Your issue title here

### ISSUE THREAD

**Issue by vinodlee** [firebase/flutterfire#11605]
## Bug report

**Describe the bug**

### Steps to reproduce

2. '...'
3. See error or incorrect behavior

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by elkasvirElka** [comment]
@vinodlee  did you resolve the issue?
I am facing similar error but with another library of firebase:
firebase_dynamic_links (from `.symlinks/plugins/firebase_dynamic_links/ios`) was resolved to 5.3.6, which depends on
      Firebase/DynamicLinks (= 10.15.0)
I've tried flutter doctor(no errors)

**Comment by darshankawar** [comment]
@vinodlee 
Can you provide the entire error log ? Just providing the one liner error message isn't enough to properly address the issue.
You may try below and see if they work in your case or not:

`pod repo update && pod install --repo-update`

Check which `$FirebaseSDKVersion` are you using. It should be compatible with flutterfire plugin version you are using.

**Comment by elkasvirElka** [comment]
$ pod repo update 
gives no error
$ pod install 
gives this:
<img width="1052" alt="image" src="https://github.com/firebase/flutterfire/assets/37272004/c3a7d059-fff2-48ab-a62c-90b573dedb13">
I removed firebase libs from pubspec.yaml and run pod install(it was successful)
Returned firebase libs back and run  pod install
And it worked.
I've tried clean cache and flutter doctor, it did not work for me.

P.S: this is flutter project, error when I've tried to launch app on IOS

**Comment by darshankawar** [comment]
@elkasvirElka 
You'll need to delete `pubspec.lock`, run `pod install` which should resolve the error, because the error you are getting is due to the conflict between plugin versions you are using with the one in pubspec.lock.

Based on https://github.com/firebase/flutterfire/issues/11605#issuecomment-1727656920, closing this as resolved.
