### ISSUE TITLE
Firebase Auth -  BUILD FAILED 

### ISSUE THREAD

**Issue by fisforfaheem** [firebase/flutterfire#11612]
Could not resolve all files for configuration ':app:devDebugRuntimeClasspath'.
   > Failed to transform firebase-auth-ktx-22.1.1.aar (com.google.firebase:firebase-auth-ktx:22.1.1) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing

**Comment by fisforfaheem** [comment]
Note: /Users/4edoc/.pub-cache/hosted/pub.dev/cloud_firestore-4.9.2/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestoreMessageCodec.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/4edoc/.pub-cache/hosted/pub.dev/firebase_messaging-14.6.8/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/4edoc/.pub-cache/hosted/pub.dev/mic_stream-0.6.5/android/src/main/java/com/code/aaron/micstream/MicStreamPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/4edoc/.pub-cache/hosted/pub.dev/mic_stream-0.6.5/android/src/main/java/com/code/aaron/micstream/MicStreamPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
ERROR:D8: com.android.tools.r8.kotlin.H

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeExtDexDevDebug'.
> Could not resolve all files for configuration ':app:devDebugRuntimeClasspath'.
   > Failed to transform firebase-auth-ktx-22.1.1.aar (com.google.firebase:firebase-auth-ktx:22.1.1) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=23, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: /Users/4edoc/.gradle/caches/transforms-3/defef7f807d15929c2a6237fae7286cc/transformed/jetified-firebase-auth-ktx-22.1.1-runtime.jar.
         > Error while dexing.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 14s
Running Gradle task 'assembleDevDebug'...                         196.5s

┌─ Flutter Fix ──────────────────────────────────────────────────────────────┐
│ [!] The shrinker may have failed to optimize the Java bytecode.            │
│ To disable the shrinker, pass the `--no-shrink` flag to this command.      │
│ To learn more, see: https://developer.android.com/studio/build/shrink-code │

**Comment by darshankawar** [comment]
@fisforfaheem 
This doesn't seem to be specific to firebase_auth plugin, but with the gradle version and conflict.
Try upgrading your gradle plugin which should hopefully resolve the reported error.

See this similar issue for your reference: https://github.com/firebase/firebase-android-sdk/issues/5322
Closing from here.
