### ISSUE TITLE
🐛 [firebase_analytics] DT_TOOLCHAIN_DIR blocking issue in Xcode 15.0

### ISSUE THREAD

**Issue by lukepighetti** [firebase/flutterfire#11614]
When trying to run a Flutter app using flutter fire with Xcode 15.0, I get this error

<img width="337" alt="F6eYL-rWcAAmNN5" src="https://github.com/firebase/flutterfire/assets/666539/de4d702d-6e83-4270-ad47-e2d8e884bf89">

```
  cloud_firestore: ^4.9.2
  firebase_analytics: ^10.5.0
  firebase_auth: ^4.10.0
  firebase_app_check: ^0.2.0
  firebase_core: ^2.16.0
  firebase_crashlytics: ^3.3.6
  firebase_database: ^10.2.6
  firebase_storage: ^11.2.7
```

```
Failed to build iOS app
Could not build the precompiled application for the device.
Error (Xcode): DT_TOOLCHAIN_DIR cannot be used to evaluate LIBRARY_SEARCH_PATHS, use TOOLCHAIN_DIR instead


Error launching application on Luke's iPhone.
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.2, on macOS 13.5.2 22G91 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.82.2)
[✓] Connected device (3 available)
    ! Error: Luke’s Apple Watch needs to connect to determine its availability. Check the connection between the device and its companion iPhone, and the connection between the iPhone and Xcode. Both devices may also need to be restarted and unlocked. (code 1)
[✓] Network resources

• No issues found!
```

**Comment by RicharC293** [comment]
Check this FIX related to XCODE 15 
https://github.com/CocoaPods/CocoaPods/issues/12012#issuecomment-1659803356

**Comment by lukepighetti** [comment]
While that did work for me, it is a shim, not a fix. Would be ideal to remove it after the fix is applied. Looks like that fix can come from Cocoapods `1.13.0` when it's released, but I'm not certain about that. Anyway, here's what I did:

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    # shim for CocoaPods issue, should remove when 1.13.0 is released
    # more info: https://github.com/CocoaPods/CocoaPods/issues/12012#issuecomment-1659803356
    target.build_configurations.each do |config|
      xcconfig_path = config.base_configuration_reference.real_path
      xcconfig = File.read(xcconfig_path)
      xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
      File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
    end
  end
end
```

I should note that this only worked on Simulator for me. Is anyone seeing this work on physical iOS devices? It may be an unrelated issue.

```
Launching lib/main.dart on Luke's iPhone in debug mode...
main.dart:1
Automatically signing iOS for device deployment using specified development team in Xcode project: TA8U33SGB8
Xcode build done.                                           16.3s
(lldb) warning: libobjc.A.dylib is being read from process memory. This indicates that LLDB could not find the on-disk shared cache for this device. This will likely reduce debugging performance.
The Dart VM Service was not discovered after 30 seconds. This is taking much longer than expected...
process interrupt
```

**Comment by heeyunlee** [comment]
> I should note that this only worked on Simulator for me. Is anyone seeing this work on physical iOS devices? It may be an unrelated issue.

Ran into the same issue this morning, but using the same workaround you mentioned above worked for me on both simulators and physical iOS devices. I am using `Xcode 15 beta 8 (15A5229m)`, but I don't think it makes much difference (or does it?).

**Comment by maxlapides** [comment]
We ran into the same issue, but the Podfile fix above helped. Then, we also observed an additional similar issue related specifically related to connectivity_plus. In case it's helpful for anyone else: https://github.com/fluttercommunity/plus_plugins/issues/1955#issuecomment-1725339762

**Comment by danagbemava-nc** [comment]
Hi all, unfortunately, this is an issue related to XCode 15 and cocoapods. It seems like it has been fixed in cocoapods but it has not been released yet. Until it is released, the workaround in https://github.com/firebase/flutterfire/issues/11614#issuecomment-1727897971 should work. 

For now, I'll be closing this since this needs to be fixed by cocoapods. We can revisit this if this issue still occurs after cocoapods 1.13.0 is released. 

Thank you
