### ISSUE TITLE
i got the solution for this i changed the timeout seconds to 0 sec,i changed it to 5 sec it working fine now

### ISSUE THREAD

**Issue by Quickgram** [firebase/flutterfire#11616]
i got the solution for this i changed the timeout seconds to 0 sec,i changed it to 5 sec it working fine now
              
              how you do that please help me i am getting same error
              
_Originally posted by @Shubham-Phatale in https://github.com/firebase/flutterfire/issues/7374#issuecomment-978881113_

**Comment by danagbemava-nc** [comment]
Closing this since no information has been provided. 

Please file an issue using the issue template the next time you want to file an issue. 

Thank you
