### ISSUE TITLE
FCM_TOKEN Not Getting - IOS app crashing. 

### ISSUE THREAD

**Issue by Irfadg** [firebase/flutterfire#11623]
## Bug report

**Describe the bug**
I'm using   firebase_messaging: ^14.6.4 , for android it's  working fine . IOS also working till I update iOS version to 16.6.

ERROR MESSAGE:

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value

Code :     

String FCMToken = sharedPref!.getString(SharedPrefKeys.FCM_TOKEN)!;
 above  line of code is crashing. any idea????

**Comment by darshankawar** [comment]
@Irfadg 
Can you provide complete reproducible code sample that shows the reported error ?

As per the [documentation](https://firebase.google.com/docs/cloud-messaging/flutter/receive#apple_platforms_and_android), you need to put the onBackgroundMessage function outside of a class, at the top of your file as a top-level function. See [Firebase messaging example](https://github.com/firebase/flutterfire/blob/dfafdf276b56fabe5c21025f54c1469d5215344e/packages/firebase_messaging/firebase_messaging/example/lib/main.dart#L25-L30) for implementation. Check if you are following this in your implementation properly or not.

**Comment by darshankawar** [comment]
maybe related / similar https://github.com/firebase/flutterfire/issues/11597

**Comment by Irfadg** [comment]
Sorry for the late reply. Let me check,

Thankyou
