### ISSUE TITLE
🐛 [firebase_storage] Firestore stale local cache issue

### ISSUE THREAD

**Issue by nileshmsd12345** [firebase/flutterfire#11632]
Problem.
Sometimes, when fetching a Firestore collection, it appears that the Firestore client only retrieves the old documents and does not fetch newly added documents. This issue is affecting the consistency of data retrieval from Firestore.

Expected Behavior:

When querying a Firestore collection, the Firestore client should retrieve all relevant documents, including both old and newly added documents. The data should be consistent with what is stored in the Firestore database.

Steps to Reproduce:

Attempt to fetch a Firestore collection.
Observe that the fetched data may not include newly added documents.

**Comment by darshankawar** [comment]
@nileshmsd12345 
Can you provide `flutter doctor -v`, plugin versions, platform on which you are seeing the reported behavior and most importantly, a runnable reproducible code sample that shows it returns old documents and not new, so that we can properly address the issue.
