### ISSUE TITLE
Crashed: com.google.firebase.crashlytics.ios.exception

### ISSUE THREAD

**Issue by mazhengshui** [firebase/flutterfire#11634]
## Bug report

**Describe the bug**
Sudden crash during program operation, sporadic and non reproducible

### Steps to reproduce

Sudden crash during program operation, sporadic and non reproducible

### Expected behavior

During use, the page is not fixed

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

---

### Flutter doctor

 flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.2.1 22D68 darwin-arm64
    (Rosetta), locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

firebase_crashlytics: 2.8.6

```
Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x948c __exceptionPreprocess
1  libobjc.A.dylib                0x15050 objc_exception_throw
2  CoreFoundation                 0x198420 -[__NSCFString characterAtIndex:].cold.1
3  CoreFoundation                 0x194e1c -[__NSArrayM insertObject:atIndex:].cold.2
4  CoreFoundation                 0x13764 -[__NSArrayM insertObject:atIndex:]
5  Flutter                        0x3543c (Missing UUID 4c4c446255553144a19e32e7ebdbdb73)
6  Flutter                        0x3dd824 (Missing UUID 4c4c446255553144a19e32e7ebdbdb73)
7  Flutter                        0x3dda7c (Missing UUID 4c4c446255553144a19e32e7ebdbdb73)
8  Flutter                        0x2e4b0c (Missing UUID 4c4c446255553144a19e32e7ebdbdb73)
9  Flutter                        0x3dd198 (Missing UUID 4c4c446255553144a19e32e7ebdbdb73)
10 Flutter                        0x3de9c4 (Missing UUID 4c4c446255553144a19e32e7ebdbdb73)
11 Flutter                        0x3ddcbc (Missing UUID 4c4c446255553144a19e32e7ebdbdb73)
12 Flutter                        0x3f3de0 (Missing UUID 4c4c446255553144a19e32e7ebdbdb73)
13 Flutter                        0x2e3144 (Missing UUID 4c4c446255553144a19e32e7ebdbdb73)
14 Flutter                        0x2e6470 (Missing UUID 4c4c446255553144a19e32e7ebdbdb73)
15 CoreFoundation                 0xc1c1c __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
16 CoreFoundation                 0x82e64 __CFRunLoopDoTimer
17 CoreFoundation                 0x2c17c __CFRunLoopDoTimers
18 CoreFoundation                 0x7563c __CFRunLoopRun
19 CoreFoundation                 0x79da0 CFRunLoopRunSpecific
20 GraphicsServices               0x1998 GSEventRunModal
21 UIKitCore                      0x37180c -[UIApplication _run]
22 UIKitCore                      0x371484 UIApplicationMain
23 Runner                         0x64c8 main + 10 (AppDelegate.swift:10)
24 ???                            0x1db5dc344 (Missing)

Crashed: com.google.firebase.crashlytics.ios.exception
0  FirebaseCrashlytics            0x1eea8 FIRCLSProcessRecordAllThreads + 393 (FIRCLSProcess.c:393)
1  FirebaseCrashlytics            0x1f288 FIRCLSProcessRecordAllThreads + 424 (FIRCLSProcess.c:424)
2  FirebaseCrashlytics            0x164d4 FIRCLSHandler + 34 (FIRCLSHandler.m:34)
3  FirebaseCrashlytics            0x111a8 __FIRCLSExceptionRecord_block_invoke + 232 (FIRCLSException.mm:232)
4  libdispatch.dylib              0x64780 _dispatch_client_callout + 16
5  libdispatch.dylib              0x46a50 _dispatch_lane_barrier_sync_invoke_and_complete + 52
6  FirebaseCrashlytics            0x101b4 FIRCLSExceptionRecord + 234 (FIRCLSException.mm:234)
7  FirebaseCrashlytics            0x10cc8 FIRCLSExceptionRecordNSException + 126 (FIRCLSException.mm:126)
8  FirebaseCrashlytics            0xfe0c FIRCLSTerminateHandler() + 398 (FIRCLSException.mm:398)
9  libc++abi.dylib                0x13424 std::__terminate(void (*)()) + 12
10 libc++abi.dylib                0x15f90 __cxa_rethrow + 144
11 libobjc.A.dylib                0x16674 objc_exception_rethrow + 40
12 CoreFoundation                 0x79e64 CFRunLoopRunSpecific + 780
13 GraphicsServices               0x1998 GSEventRunModal + 160
14 UIKitCore                      0x37180c -[UIApplication _run] + 868
15 UIKitCore                      0x371484 UIApplicationMain + 312
16 Runner                         0x64c8 main + 10 (AppDelegate.swift:10)
17 ???                            0x1db5dc344 (Missing)

```

</details>
(feature) flutter pub deps -- --style=compact
Dart SDK 3.0.0
Flutter SDK 3.10.0
flutter_app 1.0.68+69

dependencies:
- animate_do 2.1.0 [flutter]
- azlistview 2.0.0 [flutter scrollable_positioned_list]
- bot_toast 4.0.3 [flutter]
- build_runner 2.3.3 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- card_swiper 2.0.4 [flutter]
- connectivity_plus 2.3.9 [flutter connectivity_plus_platform_interface connectivity_plus_linux connectivity_plus_macos connectivity_plus_web connectivity_plus_windows]
- convert 3.0.2 [typed_data]
- crypto 3.0.2 [typed_data]
- cupertino_icons 1.0.5
- date_format 2.0.7
- dio 4.0.6 [http_parser path]
- encrypt 5.0.1 [args asn1lib clock collection crypto pointycastle]
- english_words 4.0.0 [string_scanner]
- firebase_analytics 9.3.8 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 1.24.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 2.8.6 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_messaging 11.4.4 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection js material_color_utilities meta vector_math sky_engine]
- flutter_google_places_sdk 0.3.2+6 [flutter flutter_google_places_sdk_platform_interface flutter_google_places_sdk_ios flutter_google_places_sdk_web flutter_google_places_sdk_android flutter_google_places_sdk_windows]
- flutter_local_notifications 9.4.0 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_localizations 0.0.0 [flutter intl characters clock collection js material_color_utilities meta path vector_math]
- flutter_picker 2.0.5 [flutter]
- geolocator 9.0.0 [flutter geolocator_platform_interface geolocator_android geolocator_apple geolocator_web geolocator_windows]
- get_ip_address 0.0.5 [http]
- google_geocoding_api 1.0.1+2 [dio]
- google_maps_flutter 2.4.0 [flutter google_maps_flutter_android google_maps_flutter_ios google_maps_flutter_platform_interface google_maps_flutter_web]
- http_certificate_pinning 2.0.4 [dio flutter http]
- image_picker 0.8.7 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_platform_interface]
- install_plugin_v2 1.0.0 [flutter]
- intl 0.18.0 [clock meta path]
- json_serializable 6.6.1 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- map_launcher 2.4.0 [flutter]
- oktoast 3.1.5 [flutter flutter_test]
- open_file 3.3.1 [flutter ffi]
- package_info_plus 4.0.2 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface win32]
- path_provider 2.0.4 [flutter path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- percent_indicator 3.4.0 [flutter]
- permission_handler 10.2.0 [flutter meta permission_handler_android permission_handler_apple permission_handler_windows permission_handler_platform_interface]
- photo_view 0.14.0 [flutter]
- provider 6.0.3 [collection flutter nested]
- pull_to_refresh 2.0.0 [flutter]
- qr_code_scanner 1.0.1 [js flutter flutter_web_plugins]
- safe_device 1.1.2 [flutter trust_location]
- shared_preferences 2.0.15 [flutter shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- skeletons 0.0.3 [flutter]
- sqflite 2.0.2+1 [flutter sqflite_common path]
- url_launcher 6.1.6 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- video_player 2.5.0 [flutter html video_player_android video_player_avfoundation video_player_platform_interface video_player_web]
- webview_flutter 4.2.1 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]

dev dependencies:
- flutter_lints 1.0.4 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection js matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

dependency overrides:
- firebase_core_platform_interface 4.5.0 [collection flutter flutter_test meta plugin_platform_interface]
- geolocator_android 3.0.2 [flutter geolocator_platform_interface]

transitive dependencies:
- _fe_analyzer_shared 50.0.0 [meta]
- _flutterfire_internals 1.0.2 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer 5.2.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- args 2.4.1
- asn1lib 1.4.1
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.3.1 [analyzer async convert crypto glob logging meta path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.1.1 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.1.0 [analyzer async build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.2.7 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.6.1 [built_collection collection fixnum meta]
- characters 1.3.0
- checked_yaml 2.0.2 [json_annotation source_span yaml]
- clock 1.1.1
- cloud_firestore_platform_interface 5.7.7 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.8.10 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 4.4.0 [built_collection built_value collection matcher meta]
- collection 1.17.1
- connectivity_plus_linux 1.3.1 [flutter connectivity_plus_platform_interface meta nm]
- connectivity_plus_macos 1.2.6 [connectivity_plus_platform_interface flutter]
- connectivity_plus_platform_interface 1.2.4 [flutter meta plugin_platform_interface]
- connectivity_plus_web 1.2.5 [connectivity_plus_platform_interface flutter_web_plugins flutter js]
- connectivity_plus_windows 1.2.2 [connectivity_plus_platform_interface flutter]
- cross_file 0.3.3+4 [js meta]
- csslib 0.17.2 [source_span]
- dart_style 2.2.5 [analyzer args path pub_semver source_span]
- dbus 0.7.8 [args ffi meta xml]
- fake_async 1.3.1 [clock collection]
- ffi 2.0.2
- file 6.1.4 [meta path]
- firebase_analytics_platform_interface 3.3.7 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.4.2+7 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_core_web 1.7.3 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.3.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 3.5.4 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.4.4 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- fixnum 1.0.1
- flutter_google_places_sdk_android 0.1.2+6 [flutter flutter_google_places_sdk_platform_interface]
- flutter_google_places_sdk_ios 0.1.2+4 [flutter flutter_google_places_sdk_platform_interface]
- flutter_google_places_sdk_platform_interface 0.2.4+3 [flutter plugin_platform_interface]
- flutter_google_places_sdk_web 0.1.3+4 [flutter flutter_web_plugins flutter_google_places_sdk_platform_interface js google_maps collection]
- flutter_google_places_sdk_windows 0.1.0+1 [flutter http latlong2 flutter_google_places_sdk_platform_interface freezed_annotation json_annotation]
- flutter_local_notifications_linux 0.4.2 [flutter flutter_local_notifications_platform_interface dbus path xdg_directories]
- flutter_local_notifications_platform_interface 5.0.0 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 2.0.15 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- freezed_annotation 2.4.1 [collection json_annotation meta]
- frontend_server_client 3.2.0 [async path]
- geolocator_apple 2.2.7 [flutter geolocator_platform_interface]
- geolocator_platform_interface 4.0.7 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 2.1.6 [flutter flutter_web_plugins geolocator_platform_interface]
- geolocator_windows 0.1.1 [flutter geolocator_platform_interface]
- glob 2.1.1 [async collection file path string_scanner]
- google_maps 6.3.0 [js js_wrapping meta]
- google_maps_flutter_android 2.4.15 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface stream_transform]
- google_maps_flutter_ios 2.2.3 [flutter google_maps_flutter_platform_interface stream_transform]
- google_maps_flutter_platform_interface 2.4.0 [collection flutter plugin_platform_interface stream_transform]
- google_maps_flutter_web 0.5.4+1 [collection flutter flutter_web_plugins google_maps google_maps_flutter_platform_interface sanitize_html stream_transform]
- graphs 2.3.1 [collection]
- html 0.15.3 [csslib source_span]
- http 0.13.5 [async http_parser meta path]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image_picker_android 0.8.7+4 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 2.2.0 [flutter flutter_web_plugins image_picker_platform_interface mime]
- image_picker_ios 0.8.8 [flutter image_picker_platform_interface]
- image_picker_platform_interface 2.8.0 [cross_file flutter http plugin_platform_interface]
- io 1.0.4 [meta path string_scanner]
- js 0.6.7 [meta]
- js_wrapping 0.7.4 [js]
- json_annotation 4.8.0 [meta]
- latlong2 0.8.2 [intl]
- lints 1.0.1
- logging 1.1.1
- matcher 0.12.15 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.2.0
- meta 1.9.1
- mime 1.0.4
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- package_config 2.1.0 [path]
- package_info_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- path 1.8.3
- path_provider_linux 2.1.11 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.7 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.6 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.7 [ffi flutter path path_provider_platform_interface win32]
- permission_handler_android 10.3.2 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.1.4 [flutter permission_handler_platform_interface]
- permission_handler_platform_interface 3.11.3 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.1.3 [flutter permission_handler_platform_interface]
- petitparser 5.1.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.4 [meta]
- pointycastle 3.7.3 [collection convert js]
- pool 1.5.1 [async stack_trace]
- process 4.2.4 [file path platform]
- pub_semver 2.1.4 [collection meta]
- pubspec_parse 1.2.3 [checked_yaml collection json_annotation pub_semver yaml]
- sanitize_html 2.0.0 [html meta]
- scrollable_positioned_list 0.2.3 [flutter collection]
- shared_preferences_android 2.2.0 [flutter shared_preferences_platform_interface]
- shared_preferences_ios 2.1.1 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.3.0 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_macos 2.0.5 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.3.0 [flutter plugin_platform_interface]
- shared_preferences_web 2.2.0 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.3.0 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.4.1 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.4 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.3.2 [analyzer async build dart_style glob path source_span yaml]
- source_helper 1.3.3 [analyzer collection source_gen]
- source_span 1.9.1 [collection path term_glyph]
- sqflite_common 2.4.5+1 [synchronized path meta]
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- synchronized 3.1.0
- term_glyph 1.2.1
- test_api 0.5.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.8.0 [path]
- timing 1.0.1 [json_annotation]
- trust_location 2.0.13 [flutter]
- typed_data 1.3.2 [collection]
- url_launcher_android 6.0.36 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.1.4 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.5 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.6 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.3 [flutter plugin_platform_interface]
- url_launcher_web 2.0.18 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.7 [flutter url_launcher_platform_interface]
- vector_math 2.1.4
- video_player_android 2.4.9 [flutter video_player_platform_interface]
- video_player_avfoundation 2.4.9 [flutter video_player_platform_interface]
- video_player_platform_interface 6.2.0 [flutter plugin_platform_interface]
- video_player_web 2.0.16 [flutter flutter_web_plugins video_player_platform_interface]
- watcher 1.0.2 [async path]
- web_socket_channel 2.4.0 [async crypto stream_channel]
- webview_flutter_android 3.9.1 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 2.4.0 [flutter meta plugin_platform_interface]
- webview_flutter_wkwebview 3.7.0 [flutter path webview_flutter_platform_interface]
- win32 4.1.4 [ffi]
- xdg_directories 0.2.0+3 [meta path process]
- xml 6.1.0 [collection meta petitparser]
- yaml 3.1.1 [collection source_span string_scanner]

---

**Comment by darshankawar** [comment]
@mazhengshui 
We would need more details so as to properly address the issue. If you could try to get more meaningful logs, it'll help to debug the issue further.

**Comment by mazhengshui** [comment]
Here we also provide project dependencies. Because this is a production issue and customer feedback, we can only get so many logs from the Firebase backend. What else do you need from us regarding the local environment? Please point it out.

**Comment by darshankawar** [comment]
`Fatal Exception: NSInvalidArgumentException` seems incomplete. Usually, it comes back with a reason for the exception such as below:

`Fatal Exception: NSInvalidArgumentException
-[NSNull getDocumentsWithSource:completion:]:`

But since there are no replicable steps, pattern and the exception seems to be intermittent, I'll label it for team's input / attention.

**Comment by russellwheatley** [comment]
If you look at the stack trace, you will note that it isn't coming from any FlutterFire API. It is an internal issue with FirebaseCrashlytics from the Firebase iOS SDK.

**Comment by TarekkMA** [comment]
Hello @mazhengshui, Can you confirm if this issue still persists?
