### ISSUE TITLE
🐛 [firebase_messaging] java.io.IOException: TOO_MANY_REGISTRATIONS

### ISSUE THREAD

**Issue by shashankjat7** [firebase/flutterfire#11636]
## Bug report

I have read this issue all over stackoverflow and github but in my case its unique and only happens on Samsung A32 and Samsung A52 devices running Android 11. The same devices with android 12 or 13 do not have the issue. And other devices with android 11 do not have the issue as well. Just those 2 devices running Android 11. The issue not only occurs on real devices, but emulators as well.

The error reads : 

```
FirebaseInstanceId: Topic sync or token retrieval failed on hard failure exceptions: TOO_MANY_REGISTRATIONS. Won't retry the operation.
flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [firebase_messaging/unknown] java.io.IOException: TOO_MANY_REGISTRATIONS
 flutter : #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652)
flutter : #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310)
flutter : <asynchronous suspension>
flutter : #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:510)
flutter : <asynchronous suspension>
flutter : #3      MethodChannelFirebaseMessaging.getToken (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:248)
```

I have tested the issue on multiple projects with flutter version 2.2.3 and 3.10.6, and it persists in all. It can be reproduced on the devices specified above with just simple 3 lines of code in main.dart file.
```
WidgetsFlutterBinding.ensureInitialized();
await Firebase.initializeApp();
final fcmToken = await FirebaseMessaging.instance.getToken();
```

**Comment by darshankawar** [comment]
> only happens on Samsung A32 and Samsung A52 devices running Android 11. The same devices with android 12 or 13 do not have the issue. And other devices with android 11 do not have the issue as well. Just those 2 devices running Android 11. The issue not only occurs on real devices, but emulators as well.

@shashankjat7 
The plugin is a thin wrapper around native Firebase sdks and it is unlikely that this is a bug in the plugin itself since it seems to be device + OS specific. The plugin code doesn't differentiate between emulators and devices.

I suggest you to reach out to [firebase support](https://firebase.google.com/support) for resolution.
