### ISSUE TITLE
🐛 [firebase_dynamic_links] Empty utmParameters only after SDK migration

### ISSUE THREAD

**Issue by FeelHippo** [firebase/flutterfire#11638]
## Bug report

**FirebaseDynamicLinks has stopped reading utm parameters after dependencies update**

Back in April, Firebase Dynamic Links was implemented in one of our apps, and it's been working fine up until recently.
At the time, the app was running on Flutter 2x. [This issue](https://github.com/firebase/flutterfire/issues/8954) helped me properly setting it up and the app was reading the parameters as expected.

Here is the dependencies used for that early version:

```
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

  # https://pub.dev/packages/firebase_dynamic_links
  # license: BSD-3-Clause
  firebase_dynamic_links: ^4.1.0

dependency_overrides:
  firebase_dynamic_links_platform_interface: ^0.2.3
```

In August 2023 the app was migrated to Flutter 3x, and the dependency update accordingly:

```
environment:
  sdk: '>=2.12.0 <=3.10.2'

dependencies:

  # https://pub.dev/packages/firebase_dynamic_links
  # license: BSD-3-Clause
  firebase_dynamic_links: ^5.3.4

dependency_overrides:
  firebase_dynamic_links_platform_interface: ^0.2.3
```

And here is when it stopped working. Please bear in mind, the configuration has remained the same, the Manifest is properly set up with its intents and host etc etc., as a matter of fact it's been working so far. 

### Steps to reproduce

Steps to reproduce the behavior, let's take .onLink.listen() for instance:

1. App is running on the background
2. User taps on the dynamic link from the same device: `https://valid_host.page.link/?link=https://www.zurich.ch&apn=valid_apn&isi=1234567890&ibi=valid_ibi&utm_source=test_source&utm_medium=test_medium&utm_campaign=test_campaign`
4. The following is what the app reads: `PendingDynamicLinkData({ios: null, android: {clickTimestamp: 1695798144348, minimumVersion: 0}, link: https://www.zurich.ch, utmParameters: {}})`

I suspect this might be related to [this other issue](https://github.com/firebase/flutterfire/issues/10627), which has recently been closed.

Can anyone please look into this?

**Comment by darshankawar** [comment]
Thanks for the report @FeelHippo 
Are you creating the dynamic link from universal link, or through custom url or directly from firebase console ?
Also, can you check the [plugin example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_dynamic_links/firebase_dynamic_links/example) and check if using it, you get same behavior as reported or not ?

**Comment by FeelHippo** [comment]
Thank you for your answer, @darshankawar 
I have been creating links programmatically, or "manually": https://firebase.google.com/docs/dynamic-links/create-manually

I will investigate further and let you know, thank you

**Comment by FeelHippo** [comment]
@darshankawar I have set up the plugin example mentioned above to run with my firebase options, but I am experiencing the same issue

**Comment by FeelHippo** [comment]
@darshankawar 

Someone at my organization deleted the Firebase Project associated with the malfunctioning app. 
This issue can be closed, thank you for your time and help

**Comment by rohansohonee1** [comment]
Facing this same issue.

Tested using versions 
- **5.0.1** (lowest supported by firebase_core 2.12.0) 
- **5.3.6**.

**Comment by FeelHippo** [comment]
Reopening this to allow @rohansohonee1 to have his case looked into.

**Comment by FeelHippo** [comment]
UPDATE: after restoring the project, and making sure the config is exactly the same as the working version, the problem persists. 

This looks like a genuine bug, previous versions of the same SDK were returning the utm params values, where as the latest does not

**Comment by darshankawar** [comment]
Thanks for the update @FeelHippo 
Check [this](https://github.com/firebase/flutterfire/issues/8954) issue and underlying comments to see if they help in your case or not.

**Comment by FeelHippo** [comment]
@darshankawar as mentioned in my big report above, that issue and related comments, helped me make it work previously.

Everything was working till I updated the dependencies involved.

**Comment by darshankawar** [comment]
Thanks for the update. Using the plugin example, I do see the same behavior as reported, but based on Russell's [this](https://github.com/firebase/flutterfire/issues/10627#issuecomment-1557271918) comment, not sure if this is a plugin issue or a native one.

Will keep this issue open for team's input. 

/cc @russellwheatley

**Comment by FeelHippo** [comment]
@darshankawar hope everything is fine.
I was wondering if you've heard back regarding this.

**Comment by FeelHippo** [comment]
@darshankawar this is a huge blocker on my side, can you please give me a quick update?

**Comment by FeelHippo** [comment]
hi @russellwheatley , as stated by @darshankawar earlier on, this can be reproduced from the [example publicly available](https://github.com/firebase/flutterfire/tree/master/packages/firebase_dynamic_links/firebase_dynamic_links/example).

Here is a tiny reproduction, though of course firebase options and host cannot be shared here

- example link
```
https://test.page.link/?link=https://www.zurich.ch&apn=ch.zurich.test&isi=xxxx46xxxx&ibi=ch.zurich.a-test&utm_source=android&utm_medium=test_medium&utm_campaign=test_campaign
```

- pubspec.yaml
```
environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  firebase_core: ^2.16.0
  firebase_dynamic_links: ^5.3.6
  flutter:
    sdk: flutter

```
- main.dart
```
import 'dart:async';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_dynamic_links/firebase_dynamic_links.dart';
import 'package:flutter/material.dart';

import 'firebase_options.dart';

void main() {
  initApp();
}

Future<void> initApp() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const App());
}

class App extends StatefulWidget {
  const App();

  @override
  State<StatefulWidget> createState() => _AppState();
}

class _AppState extends State<App> {
  FirebaseDynamicLinks dynamicLinks = FirebaseDynamicLinks.instance;

  @override
  void initState() {
    super.initState();
    initDynamicLinks(dynamicLinks);
  }

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Test Dynamic Links',
      home: Text('Hello There'),
    );
  }
}

Future<void> initDynamicLinks(FirebaseDynamicLinks dynamicLinks) async {

  debugPrint('initDynamicLinks');

  final PendingDynamicLinkData? pendingDynamicLinkData =
  await FirebaseDynamicLinks.instance.getInitialLink();

  final Map<String, String?>? utmParameters =
      pendingDynamicLinkData?.utmParameters;

  debugPrint('Expect utmParamters: $utmParameters');

  if (utmParameters != null) {

    debugPrint('Found utmParamters: $utmParameters');

    utmParameters.forEach((String key, String? value) {

      debugPrint('Each utmParamter: $key | $value');

      if (value != null) {

        debugPrint('Each value utmParamter: $value');

      }

    });

  }

  dynamicLinks.onLink.listen((PendingDynamicLinkData dynamicLinkData) {

    debugPrint('Expect PendingDynamicLinkData: $dynamicLinkData');

    dynamicLinkData.utmParameters.forEach((String key, String? value) {

      debugPrint('Each PendingDynamicLinkData utmParamter: $key | $value');

      if (value != null) {

        debugPrint('Each value PendingDynamicLinkData utmParamter: $value');

      }

    });

  }).onError((dynamic error, StackTrace stacktrace) {
    debugPrint('Error: $error');
  });
}

```

- AndroidManifest.xml
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          package="ch.zurich.test">
  <application
    android:label="firebase_dynamic_links_example"
    android:icon="@mipmap/ic_launcher">
    <activity
      android:name="io.flutter.embedding.android.FlutterActivity"
      android:launchMode="singleTop"
      android:theme="@style/LaunchTheme"
      android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
      android:hardwareAccelerated="true"
      android:windowSoftInputMode="adjustResize"
      android:exported="true" >
      <!-- Specifies an Android theme to apply to this Activity as soon as
           the Android process has started. This theme is visible to the user
           while the Flutter UI initializes. After that, this theme continues
           to determine the Window background behind the Flutter UI. -->
      <meta-data
        android:name="io.flutter.embedding.android.NormalTheme"
        android:resource="@style/NormalTheme"
      />
      <!-- Displays an Android View that continues showing the launch screen
           Drawable until Flutter paints its first frame, then this splash
           screen fades out. A splash screen is useful to avoid any visual
           gap between the end of Android's launch screen and the painting of
           Flutter's first frame. -->
      <meta-data
        android:name="io.flutter.embedding.android.SplashScreenDrawable"
        android:resource="@drawable/launch_background"
      />
      <intent-filter>
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/>
      </intent-filter>
      <intent-filter>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:host="test.page.link" android:scheme="http"/>
        <data android:host="test.page.link" android:scheme="https"/>
      </intent-filter>
      <intent-filter>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:host="www.zurich.ch" android:scheme="http"/>
        <data android:host="www.zurich.ch" android:scheme="https"/>
      </intent-filter>
    </activity>
    <!-- Don't delete the meta-data below.
         This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
    <meta-data
      android:name="flutterEmbedding"
      android:value="2" />
  </application>
</manifest>

```

- build.gradle
```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
  localPropertiesFile.withReader('UTF-8') { reader ->
    localProperties.load(reader)
  }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
  throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
  flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
  flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
  namespace 'ch.zurich.test'
  compileSdkVersion 33

  lintOptions {
    disable 'InvalidPackage'
  }

  defaultConfig {
    applicationId "ch.zurich.test"
    minSdkVersion 19
    targetSdkVersion 33
    versionCode flutterVersionCode.toInteger()
    versionName flutterVersionName
  }

  buildTypes {
    release {
      signingConfig signingConfigs.debug
    }
  }
}

flutter {
  source '../..'
}

```

- expected result: SDK should be able to read utmParameters
- status quo: 
```
PendingDynamicLinkData({ios: null, android: {clickTimestamp: 1697803343417, minimumVersion: 0}, link: https://www.zurich.ch/ utmParameters: {}})
```

Your help is much appreciated, please let me know if you need any further details

**Comment by FeelHippo** [comment]
@darshankawar sorry to be a pest, do you have any news on this? It's ok if there is no fix, but from a business perspective I need to make this feature work, and will have to migrate to branch.io if I cannot rely on firebase_dynamic_links

**Comment by russellwheatley** [comment]
Hi folks, we'd like to inform you that the Firebase Dynamic Links service will be shutdown on August 25, 2025. In the meantime, only critical or security issues will be fixed in the SDK.

More at [firebase.google.com/support/dynamic-links-faq](https://firebase.google.com/support/dynamic-links-faq)
