### ISSUE TITLE
[firebase_app_check] minor rework for token api

### ISSUE THREAD

**Issue by lukepighetti** [firebase/flutterfire#11652]
Hey all,

I noticed a few things about the FirebaseAppCheck API that I wanted to bring to your attention.

`FirebaseAppCheck.instance.getToken()` returns `String?` but is throwing. So it's not clear when to expect a `FirebaseException` or `null` value.

`FirebaseAppCheck.instance.onTokenChange` emits `String?` but it doesn't emit the last known value. 

### Where this matters

Given a use case where you want to show a widget containing the latest AppCheck token (for debug purposes), the implementation is actually quite convoluted (pseudo-code)

```
stream token:
  let token
  try
    token = getToken()
  catch
    token = null

  yield token

  for event in onTokenChange
    yield event

subscribe stream
```

Ideally we could instead do

```
subscribe onTokenChange
```

**Comment by lukepighetti** [comment]
Here's a working version of this

```dart
extension FirebaseAppCheckExtensions on FirebaseAppCheck {
  /// The last known token and any updates to it
  // More info: https://github.com/firebase/flutterfire/issues/11652
  Stream<String?> get tokenStream async* {
    String? token;

    try {
      token = await getToken(false);
    } catch (_) {
      token = null;
    }

    yield token;

    await for (final event in onTokenChange) {
      yield event;
    }
  }
}
```

**Comment by russellwheatley** [comment]
Hey @lukepighetti - is `getToken()` throwing across all platforms? That shouldn't happen.

The `onTokenChange` stream will only call upon the token changing so it isn't going to call for the current token.
