### ISSUE TITLE
[📚] `firebase_app_check` Readme -> Getting Started

### ISSUE THREAD

**Issue by FMorschel** [firebase/flutterfire#11690]
pub: [firebase_app_check](https://pub.dev/packages/firebase_app_check)

The readme on `firebase_app_check` should point to somewhere like https://firebase.google.com/docs/app-check/flutter/default-providers

**Comment by AbhishekMaurya2002** [comment]
Can you please assign to me?

**Comment by FMorschel** [comment]
I'm not able to do this, but I believe you could create a PR and mention this issue in its description.

**Comment by russellwheatley** [comment]
@AbhishekMaurya2002 - feel free to open a PR and change this URL: https://github.com/firebase/flutterfire/blob/master/packages/firebase_app_check/firebase_app_check/README.md?plain=1#L10 😄. PRs welcome from contributors.
