### ISSUE TITLE
🐛 [firebase_auth] fetchSignInMethodsForEmail returning an empty list

### ISSUE THREAD

**Issue by nohe427** [firebase/flutterfire#11702]
On September 15, 2023 [email enumeration protection](https://cloud.google.com/identity-platform/docs/admin/email-enumeration-protection) was enabled by default for **all new Firebase projects created after that date** to boost security. When this setting is enabled, it limits the ability to check for what existing sign in methods exist for an email address through the `fetchSignInMethodsForEmail` JavaScript API. 

If you do need access to `fetchSignInMethodsForEmail`, the only workaround is to [disable email enumeration protection](https://cloud.google.com/identity-platform/docs/admin/email-enumeration-protection#disable) on your Firebase project's underlying Cloud project. Disabling email enumeration protection will lower the security of your project.

**Comment by darshankawar** [comment]
Hello @nohe427 
A similar [issue](https://github.com/firebase/flutterfire/issues/11508) was raised and fixed from flutterfire end.
Leaving it here for your reference.

**Comment by Lyokone** [comment]
Hello @nohe427, I'm closing this issue since https://github.com/firebase/flutterfire/pull/11676 added this information in the documentation. Feel free to reopen if you feel it's needed.

**Comment by Amyx000** [comment]
Turning off Email enumeration protection gives provider and if enable it I get an empty array.
