### ISSUE TITLE
🐛 [firebase_auth] Test for `requires-recent-login` throw programmatically

### ISSUE THREAD

**Issue by FMorschel** [firebase/flutterfire#11730]
## What feature would you like to see?

On `firebase_auth` there is a `FirebaseAuthException` with code "`requires-recent-login`". I believe it would be useful to have a method to test if this would be thrown on trying to work with security-sensitive actions. 

For example, with `firebase_ui_auth`, when I call `EmailSignUpDialog` it throws the warning there but I have no intelligible way of showing a new page for my user to actually reauthenticate and it doesn't do it by itself. I even created #11729 to solve my problem in another way, but I do believe this should be testable by the programmer anyway.

**Comment by Lyokone** [comment]
Hi @FMorschel, since this issue is related with https://github.com/firebase/FirebaseUI-Flutter could you reopen it on this repository? Thanks

**Comment by FMorschel** [comment]
Done at https://github.com/firebase/FirebaseUI-Flutter/discussions/158
