### ISSUE TITLE
🐛 [FirebaseAuth] "sendPasswordResetEmail" method doesn't catch exceptions

### ISSUE THREAD

**Issue by TheStrongest** [firebase/flutterfire#11739]
## Bug report

**Describe the bug**
When testing my authentication flow I found out that the "sendPasswordResetEmail" method does not catch/throw exceptions. I tried using different fake emails that are not registered on my database to test it, but no error was thrown in the end. Instead, the try/catch block was passed successfully.

---

**Comment by darshankawar** [comment]
@TheStrongest 
The case for `sendPasswordResetEmail` is mentioned in this open issue: https://github.com/firebase/flutterfire/issues/3273
Please follow-up in it for further updates. Closing as duplicate.
