### ISSUE TITLE
[📚] pub.dev claims Windows support

### ISSUE THREAD

**Issue by adil192** [firebase/flutterfire#11733]
The [pub.dev page](https://pub.dev/packages/firebase_core) says that the package supports Windows. 
![pub.dev screenshot](https://github.com/firebase/flutterfire/assets/21128619/7ab50943-ebce-4659-b746-f820e57b635e)

However, running `flutterfire configure` generates this code:
```dart
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // ...
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
```

https://firebase.google.com/docs/flutter/setup doesn't contain any instructions to configure firebase for Windows.

If the package doesn't support Windows, then the [pub.dev page](https://pub.dev/packages/firebase_core) should be updated.
Otherwise, it would be helpful if the documentation was updated to explain how to setup Windows support.

**Comment by darshankawar** [comment]
> The [pub.dev page](https://pub.dev/packages/firebase_core) says that the package supports Windows.

The package does now support Windows, as part of [this](https://github.com/firebase/flutterfire/pull/11516) PR 



> However, running `flutterfire configure` generates this code:

You might need to raise this in dedicated [repo](https://github.com/invertase/flutterfire_cli/issues) to get the tool update the windows specific implementation. 



> https://firebase.google.com/docs/flutter/setup doesn't contain any instructions to configure firebase for Windows.

The Windows support has been added just a week ago, so the instructions should get updated soon.



> If the package doesn't support Windows, then the [pub.dev page](https://pub.dev/packages/firebase_core) should be updated.

It does support now per the fixed PR.

I'll close this for now, as flutterfire configure related issue should be addressed in other repo. If the documentation is not yet updated soon, will reopen it. If you disagree, write in comments and I'll reopen anyway.

**Comment by black-coda** [comment]
Please, any luck with the configuration

**Comment by adil192** [comment]
Not yet, we need https://github.com/invertase/flutterfire_cli/issues/219.
There's probably a way to get all the information for `FirebaseOptions` to do it yourself, but that's beyond me
