### ISSUE TITLE
🐛[auth] : Windows desktop crashes when google signin is attempted.  

### ISSUE THREAD

**Issue by floyd-lewis** [firebase/flutterfire#11752]
## Bug report
Was using firedart before.  Since the new release now supports Windows desktop I had installed the below plugins. App compiles and runs but crashes the moment I click the google signin button.
Nothing is logged to the console.

**Describe the bug**
Use the following packages:
###################################################
  firebase_core: ^2.19.0
  cloud_firestore: ^4.11.0
  firebase_auth: ^4.11.1
  firebase_storage: ^11.3.1
  #####################################################
  google_sign_in: ^6.1.5
  google_sign_in_platform_interface: ^2.4.2
  extension_google_sign_in_as_googleapis_auth: ^2.0.11
  google_sign_in_dartio: 
    path: packages/google_sign_in_dartio

**Comment by darshankawar** [comment]
Thanks for the report @floyd-lewis 
google_sign_in doesn't seem to support windows yet. https://github.com/flutter/flutter/issues/103682
I currently don't have windows machine to verify, but can you run `flutter run -v` and check if it shows any error entries in it ? If so, can you provide the entire log here ?

Also, if you create a new Flutter project on windows, just add `firebase_core` and google_sign_in

**Comment by TheAkash2002** [comment]
I have the same issue, however my library versions are newer. There are no error entries in `flutter run -v`.

  firebase_core: ^2.20.0
  firebase_auth: ^4.12.0
  cloud_firestore: ^4.12.0
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  permission_handler: ^11.0.1
  google_fonts:
  get_storage: ^2.1.1
  logging: ^1.2.0
  fluttertoast: ^8.2.2
  loading_animation_widget: ^1.2.0+4
  just_audio: ^0.9.35
  bot_toast: ^4.1.3
  google_sign_in: ^6.1.5
  google_sign_in_dartio:
  
I took a closer look and found that `signInWithCredential()` of `messages.pigeon.dart`is the culprit. App crashes immediately after the `channel.send()` call.

**Comment by floyd-lewis** [comment]
Its a simple fix. Just open the VC++ project  after doing a windows build. firebase_auth is asserting for secret parameter which were  not required. I moved it to within the methods requiring it.

 std::string secret = std::get<std::string>(arguments[kArgumentSecret]);

**Comment by darshankawar** [comment]
Thanks for the update. Since I don't have windows to verify it, based on the report and potential fix as above, keeping it open and labeling for team's tracking.

**Comment by TheAkash2002** [comment]
> Its a simple fix. Just open the VC++ project after doing a windows build. firebase_auth is asserting for secret parameter which were not required. I moved it to within the methods requiring it.
> 
> std::string secret = std::getstd::string(arguments[kArgumentSecret]);

This works! `secret` and `rawNonce` were the unnecessary variables in my case (GoogleSignIn).

**Comment by floyd-lewis** [comment]
yeah i had to do that for rawNonce too

**Comment by black-coda** [comment]
@floyd-lewis 
Hi, Please i still havent been able to run firebase with my windows app.
it keeps on showing build error
How did you do yours?

Thanks

**Comment by laurencetroyv** [comment]
same problem with @black-coda, it only shows 

```
Launching lib\main.dart on Windows in debug mode...
Exception: Build process failed.

Exited (1).
```

**Comment by black-coda** [comment]
@darshankawar Please any updates

**Comment by Lyokone** [comment]
Thanks for opening the issue, I wasn't aware of `google_sign_in_dartio`, I've created #11861 which should show how to use this package.
