### ISSUE TITLE
🐛 [firebase_analytics] iOS missing initiateOnDeviceConversionMeasurementWithEmailAddress

### ISSUE THREAD

**Issue by liugaocomeon** [firebase/flutterfire#11775]
[https://firebase.google.com/docs/tutorials/ads-ios-on-device-measurement/step-3?hl=en](https://firebase.google.com/docs/tutorials/ads-ios-on-device-measurement/step-3?hl=en ) used initiateOnDeviceConversionMeasurementWithEmailAddress, but flutter sdk doesn't exist.

**Comment by asaarnak** [comment]
@Lyokone 
Thanks for the feature! Have been waiting for it.

Could you update the docs to include Flutter?
> https://firebase.google.com/docs/tutorials/ads-ios-on-device-measurement/step-3

**Comment by Lyokone** [comment]
@asaarnak I'll ping someone for it, thanks for the reminder
