### ISSUE TITLE
🐛 [firebase_messaging] FlutterFirebaseMessagingStore will only store a max of 20 notifications to SharedPreferences even though there could be more in the Android notification drawer

### ISSUE THREAD

**Issue by scott1055** [firebase/flutterfire#11771]
## Bug report

FirebaseMessaging.onMessageOpenedApp() and FirebaseMessaging.getInitialMessage() both do not work when a bunch of notifications are stacked in the notification drawer and notification 21 or higher is tapped.

### Steps to reproduce

1. Terminate the app so incoming background notifications are persisted only to SharedPreferences and not to the HashMap.
2. Have the app receive 24 notifications while the app is still terminated so that they stack in the notification drawer.
3. Clear the newest 20 out of the 24 notifications.
4. Now tap on the oldest notification.
5. The app now launches but FirebaseMessaging.onMessageOpenedApp() does not fire (if the app was in the background) and FirebaseMessaging.getInitialMessage() returns null (if the app was launched while terminated).

### Expected behavior

FirebaseMessaging.onMessageOpenedApp() and FirebaseMessaging.getInitialMessage() both work as expected for all notifications pending in the notification drawer.

## Additional context

Here is the exact line of code which is causing the issue:
https://github.com/firebase/flutterfire/blob/f54ff7ce78aacbf5ae5ec2e8e7f584a3f349b38b/packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingStore.java#L66

We have not seen this issue on iOS. It is Android only.

**Comment by darshankawar** [comment]
Thanks for the report.
Using the steps to replicate, I was able to verify the reported behavior on Android.
