### ISSUE TITLE
🐛 [cloud_firestore] The count value that can be obtained from AggregateQuery is 0.

### ISSUE THREAD

**Issue by hukusuke1007** [firebase/flutterfire#11786]
## Bug report

The count value that can be obtained from AggregateQuery is 0.

```dart
Future<int> func() async {
  final query = FirebaseFirestore.instance.collectionGroup(...).count();
  final snap = await query.get();
  return snap.count; // 0 
}
```

cloud_firestore: 4.12.1 => NG
cloud_firestore: 4.9.3 => OK Correct

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.9, on macOS 13.5.2 22G91 darwin-arm64, locale
    ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.83.1)
[✓] Connected device (3 available)
    ! Error: Browsing on the local area network for 中川祥平のiPhone. Ensure the
      device is unlocked and attached with a cable or associated with the same
      local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)
    ! Error: Browsing on the local area network for Apple Vision. Ensure the
      device is unlocked and attached with a cable or associated with the same
      local area network as this Mac. (code -27)
    ! Error: Browsing on the local area network for 中川祥平のiPad. Ensure the device
      is unlocked and attached with a cable or associated with the same local
      area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)
[✓] Network resources

• No issues found!
```

</details>

---

**Comment by darshankawar** [comment]
@hukusuke1007 
I tried with below firestore setup with which it returned the correct count:

<img width="825" alt="Screenshot 2023-10-27 at 3 23 30 PM" src="https://github.com/firebase/flutterfire/assets/67046386/cba105b0-8ec7-4df8-b5aa-7fb7ab9f491b">










`I/flutter ( 6549): 4`

I used latest plugin version and master version of the framework.

**Comment by hukusuke1007** [comment]
@darshankawar I get the number of documents in `posts` using `CollectionGroup`. Your example is not `CollectionGroup`.
![スクリーンショット 2023-10-28 7 23 15](https://github.com/firebase/flutterfire/assets/29278033/49500feb-b32a-40bc-b431-7572cc9fd5fd)

**Comment by darshankawar** [comment]
@hukusuke1007 
I tried set-up sub-collections under `test` Collection which now looks like below:

<img width="899" alt="Screenshot 2023-10-30 at 5 01 21 PM" src="https://github.com/firebase/flutterfire/assets/67046386/a89955e8-ff11-45b8-a91c-0d0cbf2608b8">

for which I do get a count of collection group as 4.

If above doesn't represent your case, can you provide a db structure ?

**Comment by zariweyo** [comment]
Same issue for me. Version cloud_firestore 4.12.2 always return count as 0.

I have tested this structure:
users/{userId}/races/{raceId}

2 users
user1 in races collection has got: MockRace_1 and MockRace_2
user2 in races collection has got: MockRace_2 and MockRace_3

I have 2 indexes enabled to list races, that work as expected.

My query:
FirebaseFirestore.instance
        .collectionGroup("races")
        .count().get();

**Comment by hukusuke1007** [comment]
@darshankawar The collection to be set in CollectionGroup is set to index.
 
![スクリーンショット 2023-11-03 18 34 14](https://github.com/firebase/flutterfire/assets/29278033/fb088b84-634e-4e11-9575-cdd7fadd0134)

**Comment by darshankawar** [comment]
Thanks for the report. Using the details provided and after recreating db structure as mentioned [in](https://github.com/firebase/flutterfire/issues/11786#issuecomment-1791689450), I was able to replicate the reported behavior.
