### ISSUE TITLE
🐛 [flutterfire configure] lack of Windows support?

### ISSUE THREAD

**Issue by csells** [firebase/flutterfire#11797]
From [Hallelujah — Firebase For Flutter Is Now On Windows!](https://andrewzuo.com/hallelujah-firebase-for-flutter-is-on-windows-9ed62c514dcf):

"Oh, yeah, one more thing. Firebase has deprecated the old way of initializing Firebase in favour of the much more streamlined flutterfire configure command. This command works really well but there’s a slight problem. flutterfire configure creates a file called lib/firebase_options.dart. This file is used to get the configuration object to init Firebase. It works pretty well but there is one problem… no Windows support. By default it will throw an error if you try to init Windows. So just stop it from doing that. I made it return the web configuration object when the platform is Windows. Seems to work."

**Comment by danagbemava-nc** [comment]
Hi @csells, the flutterfire_cli lives in a different repo. There's a feature request tracking adding windows support to the cli in https://github.com/invertase/flutterfire_cli/issues/219. 

Closing this in favor of the linked issue. 

Thank you

**Comment by csells** [comment]
Excellent. Thank you.
