### ISSUE TITLE
[cloud_firestore] Native Dart for Server Implementation

### ISSUE THREAD

**Issue by faizabdillah** [firebase/flutterfire#11793]
Is there any plan or consideration to develop a native Dart implementation or support for Dart servers in the cloud_firestore package? This would be beneficial for developers working on projects beyond Flutter and for server-side Dart applications. I'd like to know if there are any discussions or roadmaps regarding this feature

**Comment by danagbemava-nc** [comment]
Hi @faizabdillah, are you talking about a dart implementation of the firebase admin sdk?

If that is not the case, can you provide more detail as to what you're requesting?

Thank you

**Comment by jemutorres** [comment]
Hi @danagbemava-nc ,

I guess the request is about being able to use the **cloud_firestore** package on **backend** developed in Dart.

Has this need been considered? When trying to use the package, an error is generated because dart:ui (required by cloud_firestore) does not exist.

Thank you

**Comment by danagbemava-nc** [comment]
Hi @jemutorres, on the backend you'll need to use an admin sdk. Does https://github.com/invertase/dart_firebase_admin(it is being developed by the flutterfire team) suit your needs?

**Comment by jemutorres** [comment]
Hi @danagbemava-nc,

Thank you for your reply. I see what you are saying, although it would be preferable to be able to use cloud_firestore in the same way we do it from Flutter but in backend with Dart.

Alternatively to the package you propose, it could be this https://pub.dev/packages/googleapis/example, couldn't it? Preferably for the support you can give to this library.

What do you think?

**Comment by danagbemava-nc** [comment]
> although it would be preferable to be able to use cloud_firestore in the same way we do it from Flutter but in backend with Dart.

Unfortunately, this would not be possible. At present, the flutterfire plugins are wrappers around the native android/ios/web sdks and as such require items that would not be available on dart on the backend. 

Also, if you're going to use firebase on your server, the recommended way is to use one of the native admin sdks. 

> Alternatively to the package you propose, it could be this https://pub.dev/packages/googleapis/example, couldn't it? Preferably for the support you can give to this library.

It could be possible, I haven't looked much into how the package works so I can't say. That package is being maintained by the dart team, so I think it is in good hands.

**Comment by russellwheatley** [comment]
We are working on a Dart Firebase admin SDK which you can use here: https://github.com/invertase/dart_firebase_admin
