### ISSUE TITLE
🐛 firebase_messaging:  abortError: Registration failed push service error  on chrome mobile

### ISSUE THREAD

**Issue by thunderbug1** [firebase/flutterfire#11818]
## Bug report

getToken() throws error [abortError: Registration failed push service error] when run as a web app on a mobile browser.

It works on Chrome desktop:
![image](https://github.com/firebase/flutterfire/assets/1395321/58dd0bb6-8819-483f-9b54-37804ebb9853)

But on the phone I get:
![Screenshot_20231102-095307](https://github.com/firebase/flutterfire/assets/1395321/1090fe5c-d68d-479e-9bb9-eb24bc1d5f4e)

### Steps to reproduce

Open the example deploment on a mobile browser and click the button, the result will be shown below the button.

### Expected behavior

getToken should return the token. In the example project it should be displayed like in the screenshot from chrome desktop.

### Sample project

[example project source](https://github.com/thunderbug1/fcm_test)

[deployment of example project](https://fcm-test-8607b.web.app)

---

## Additional context

Output of chrome version on the phone:

<details><summary>Click To Expand</summary>

```
Google Chrome | 118.0.5993.111 (Official Build) (64-bit)
-- | --
Revision | 47c097e133ae535cd69c530a3c9a48e8fff3c825-refs/branch-heads/5993@{#1392}
OS | Android 14; Pixel 6 Build/UP1A.231005.007; 34; REL
APK versionCode | 599311133
APK targetSdkVersion | 34
isAtLeastU/targetsAtLeastU | true/true
Google Play services | SDK=233700000; Installed=234212044; Access=1p
JavaScript | V8 11.8.172.16
User Agent | Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Mobile Safari/537.36
```

</details>

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.13.9, on Ubuntu 22.04.3 LTS 5.15.90.1-microsoft-standard-WSL2, locale
    en_US.UTF-8)
    • Flutter version 3.13.9 on channel stable at /home/developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (8 days ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/developer/android-sdk-linux
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /home/developer/android-sdk-linux
    • ANDROID_SDK_ROOT = /home/developer/android-sdk-linux
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.8.1+1-Ubuntu-0ubuntu122.04)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed
      instructions).

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Ubuntu 22.04.3 LTS 5.15.90.1-microsoft-standard-WSL2

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 3.1.5
Flutter SDK 3.13.9
fcm_test 1.0.0+1

dependencies:
- cupertino_icons 1.0.6
- firebase_core 2.21.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 14.7.3 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math web sky_engine]
- flutter_riverpod 2.4.5 [collection flutter meta riverpod state_notifier]

dev dependencies:
- flutter_lints 2.0.3 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math async boolean_selector characters collection material_color_utilities meta source_span stream_channel string_scanner term_glyph web]

transitive dependencies:
- _flutterfire_internals 1.3.11 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- collection 1.17.2
- fake_async 1.3.1 [clock collection]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.8.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 4.5.12 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.5.12 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math web]
- js 0.6.7 [meta]
- lints 2.1.1
- matcher 0.12.16 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.5.0 [collection]
- meta 1.9.1
- path 1.8.3
- plugin_platform_interface 2.1.6 [meta]
- riverpod 2.4.5 [meta stack_trace state_notifier]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.0 [path]
- state_notifier 1.0.0 [meta]
- stream_channel 2.1.1 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.6.0 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- vector_math 2.1.4
- web 0.1.4-beta
```

</details>

---

**Comment by danagbemava-nc** [comment]
Hi @thunderbug1, what device(s) are you experiencing this issue on? I ran the deployed version of your app and I was able to get the token just fine.

Did you accept the notification permission when it appeared?

I tested on a Pixel 7. Can you use the chrome inspector tool to see if you get any more details regarding the error you're getting?

<img src="https://github.com/firebase/flutterfire/assets/88313112/1800f365-6d93-45ea-951f-6cf8fc1b4232" width="300"/>

**Comment by thunderbug1** [comment]
I am using a pixel 6 and I did run it with the chrome inspector as well but I don't get more information than this error code shown in the screenshot. This makes it really hard to determine where the error is coming from since I don't know what's happening on the server.
As far as I can see all notifications in chrome are enabled.

**Comment by thunderbug1** [comment]
Is this related maybe? https://github.com/firebase/firebase-js-sdk/issues/3195

**Comment by danagbemava-nc** [comment]
Hi @thunderbug1, that seems related. What version of chrome are you using on android btw? 

I think it might be worth filing an issue on the firebase-js sdk since the flutterfire packages are wrappers around the existing native/web packages

**Comment by thunderbug1** [comment]
> Hi @thunderbug1, that seems related. What version of chrome are you using on android btw?
> 
> I think it might be worth filing an issue on the firebase-js sdk since the flutterfire packages are wrappers around the existing native/web packages

here the output of chrome://version:
Google Chrome | 118.0.5993.111 (Official Build) (64-bit)
-- | --
Revision | 47c097e133ae535cd69c530a3c9a48e8fff3c825-refs/branch-heads/5993@{#1392}
OS | Android 14; Pixel 6 Build/UP1A.231005.007; 34; REL
APK versionCode | 599311133
APK targetSdkVersion | 34
isAtLeastU/targetsAtLeastU | true/true
Google Play services | SDK=233700000; Installed=234212044; Access=1p
JavaScript | V8 11.8.172.16
User Agent | Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Mobile Safari/537.36

**Comment by danagbemava-nc** [comment]
Hi @thunderbug1, I see that you've filed an issue on the firebase js repo. 

Kindly keep us updated with what comes of it. 

Thank you
