### ISSUE TITLE
🐛 [cloud_firestore][web] Error When Using Document Snapshot As Cursor

### ISSUE THREAD

**Issue by azwalzaman** [firebase/flutterfire#11817]
## Bug report

**Describe the bug**
When I use a document snapshot as a cursor to paginate a query [as shown in the docs](https://firebase.google.com/docs/firestore/query-data/query-cursors#dart_3) I get the error 

> Invalid argument (dartObject): Could not convert: Instance of '_JsonQueryDocumentSnapshot'

### Steps to reproduce

1. Install cloud_firestore
2. Create a query with pagination that uses a document snapshot as the cursor

### Expected behavior

I expected the query to work and give me documents after the document I used as the cursor

### Sample project

```

 try {
            Query query = FirebaseFirestore.instance
                .collection('collection')
                .orderBy("field").limit(50);
            var result = await query.get();

            var cursor = result.docs[result.docs.length - 1];

            Query query2 = FirebaseFirestore.instance
                .collection('collection')
                .orderBy("field").limit(50);
            query2 = query2.startAfter([cursor]);
            var result2 = await query2.get();
} catch (e) {
            print(e);
}


```

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.0, on Microsoft Windows [Version 10.0.22621.2428], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Enterprise 2022 17.6.5)
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.83.1)
[√] Connected device (3 available)
[√] Network resources

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 3.1.0
Flutter SDK 3.13.0
cloud_firestore_example 1.0.0+1

dependencies:
- cloud_firestore 4.12.2 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.6
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math web sky_engine]

dev dependencies:
- flutter_lints 2.0.3 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math async boolean_selector characters collection material_color_utilities meta source_span stream_channel string_scanner term_glyph web]

transitive dependencies:
- _flutterfire_internals 1.3.11 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- cloud_firestore_platform_interface 6.0.3 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.8.3 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]    
- collection 1.17.2
- fake_async 1.3.1 [clock collection]
- firebase_core 2.21.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.8.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math web]
- js 0.6.7 [meta]
- lints 2.1.1
- matcher 0.12.16 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.5.0 [collection]
- meta 1.9.1
- path 1.8.3
- plugin_platform_interface 2.1.6 [meta]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.6.0 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- vector_math 2.1.4
- web 0.1.4-beta
```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the report @azwalzaman 
Can you provide us the firestore db structure so that we can try to recreate it and check about the error you are getting ?

**Comment by azwalzaman** [comment]
> Thanks for the report @azwalzaman Can you provide us the firestore db structure so that we can try to recreate it and check about the error you are getting ?

So I can't really reveal our schema but I managed to make another one where this bug is reproduced for me. I made two documents with these values and set the limit to 1. I got the same error as before

```
{
 name: "Jack",
 age: 25
}
```

```
{
 name: "Smith",
 age: null
}
```

**Comment by darshankawar** [comment]
@azwalzaman 
I came up with below db structure and then used the code sample you shared with which I didn't get the reported error:

1. db:

<img width="859" alt="Screenshot 2023-11-03 at 5 59 12 PM" src="https://github.com/firebase/flutterfire/assets/67046386/c7039b75-27b8-4d5e-bc4a-d6a897eaa83b">


2. Code:

```
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MaterialApp(
    home: MyApp(),
  ));
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Title"),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            query();
          },
          child: Text('Test'),
        ),
      ),
    );
  }

  void query() async {
    try {
      Query query =
      FirebaseFirestore.instance.collection('test_bug').orderBy("age").limit(1);
      var result = await query.get();
      print(result.toString());

      var cursor = result.docs[result.docs.length - 1];
      print(cursor.toString());

      Query query2 = FirebaseFirestore.instance
          .collection('test_bug')
          .orderBy("age").limit(1);
      query2 = query2.startAfter([cursor]);
      var result2 = await query2.get();
      print(result2);
    } catch (e) {
      print(e);
      // } catch (e) {
      //   print(e.toString());
      // }
    }
  }

}

```

3. Log:

```
I/flutter (17875): Instance of '_JsonQuerySnapshot'
I/flutter (17875): Instance of '_JsonQueryDocumentSnapshot'
I/flutter (17875): Invalid argument: Instance of '_JsonQueryDocumentSnapshot'

```

  firebase_core: ^2.20.0
  cloud_firestore: ^4.12.0


Ran on Android.

**Comment by azwalzaman** [comment]
> @azwalzaman I came up with below db structure and then used the code sample you shared with which I didn't get the reported error:
> 
> 1. db:
> 
> <img alt="Screenshot 2023-11-03 at 5 59 12 PM" width="859" src="https://user-images.githubusercontent.com/67046386/280277489-c7039b75-27b8-4d5e-bc4a-d6a897eaa83b.png">
> 2. Code:
> 
> ```
> import 'package:flutter/material.dart';
> import 'package:firebase_core/firebase_core.dart';
> import 'firebase_options.dart';
> import 'package:cloud_firestore/cloud_firestore.dart';
> 
> void main() async {
>   WidgetsFlutterBinding.ensureInitialized();
>   await Firebase.initializeApp(
>     options: DefaultFirebaseOptions.currentPlatform,
>   );
>   runApp(const MaterialApp(
>     home: MyApp(),
>   ));
> }
> 
> class MyApp extends StatelessWidget {
>   const MyApp({super.key});
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: const Text("Title"),
>       ),
>       body: Center(
>         child: ElevatedButton(
>           onPressed: () {
>             query();
>           },
>           child: Text('Test'),
>         ),
>       ),
>     );
>   }
> 
>   void query() async {
>     try {
>       Query query =
>       FirebaseFirestore.instance.collection('test_bug').orderBy("age").limit(1);
>       var result = await query.get();
>       print(result.toString());
> 
>       var cursor = result.docs[result.docs.length - 1];
>       print(cursor.toString());
> 
>       Query query2 = FirebaseFirestore.instance
>           .collection('test_bug')
>           .orderBy("age").limit(1);
>       query2 = query2.startAfter([cursor]);
>       var result2 = await query2.get();
>       print(result2);
>     } catch (e) {
>       print(e);
>       // } catch (e) {
>       //   print(e.toString());
>       // }
>     }
>   }
> 
> }
> ```
> 
> 3. Log:
> 
> ```
> I/flutter (17875): Instance of '_JsonQuerySnapshot'
> I/flutter (17875): Instance of '_JsonQueryDocumentSnapshot'
> I/flutter (17875): Invalid argument: Instance of '_JsonQueryDocumentSnapshot'
> ```
> 
> firebase_core: ^2.20.0 cloud_firestore: ^4.12.0
> 
> Ran on Android.

Okay I copied your code and tried it and got the same error
Output
```
Instance of '_JsonQuerySnapshot'
Instance of '_JsonQueryDocumentSnapshot'
Invalid argument (dartObject): Could not convert: Instance of '_JsonQueryDocumentSnapshot'
```

Ran on Web(Chrome) with ` cloud_firestore: ^4.12.2`. Can you please try on web? I also tried it on Android and it worked perfectly there

**Comment by darshankawar** [comment]
Thanks for the update. Running the scenario on web does seem to throw the reported error.

**Comment by Lyokone** [comment]
Hi @azwalzaman, you can use `startAfterDocument` method. There is an issue with the documentation, I'll ping the team responsible to change it.

**Comment by Lyokone** [comment]
This has been changed.
