### ISSUE TITLE
 🐛[Firebase Crashlytics] Crash not reported at Firebase Console 

### ISSUE THREAD

**Issue by xntop** [firebase/flutterfire#11837]
## Bug report

**Describe the bug**
Follow the official documentation to connect to the Crashlytics plug-in.

After testing, the following issues were discovered:
1. For flutter framework exceptions, simulate exceptions regularly, report exception information, check the reported information in the background, and lose some exception events. For example: 5 abnormal events were reported, but only 2 were viewed in the background.
2. Check abnormal event delay in the background

How to deal with the above problems. thanks

**Comment by darshankawar** [comment]
@xntop 
Can you provide a runnable reproducible code sample along with `flutter doctor -v`, plugin versions and platform on which you are seeing the reported behavior ?

**Comment by xntop** [comment]
> @xntop Can you provide a runnable reproducible code sample along with `flutter doctor -v`, plugin versions and platform on which you are seeing the reported behavior ? There's a similar issue reported which we weren't able to replicate, hence asking for reproducible details. #11640

flutter doctor -v
[!] Flutter (Channel unknown, 3.7.0, on macOS 14.0 23A344 darwin-x64, locale
    zh-Hans-CN)
    ! Flutter version 3.7.0 on channel unknown at /Users/anker/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an
      official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions
      at https://flutter.dev/docs/get-started/install.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at
      https://flutter.dev/docs/get-started/install.
    • Framework revision b06b8b2710 (10 months ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/anker/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

**Comment by darshankawar** [comment]
@xntop 
You are on older version of the framework and also may plugin as well. I suggest you to upgrade your config to latest including latest flutterfire plugins and run your scenario again to check if the issue still persists or not.

**Comment by xntop** [comment]
> @xntop You are on older version of the framework and also may plugin as well. I suggest you to upgrade your config to latest including latest flutterfire plugins and run your scenario again to check if the issue still persists or not.

Maybe I didn't describe the problem clearly.

Report crash information through the following methods

`
  FlutterError.onError = (errorDetails) {
    bool isIntercept = isInterceptCrash(errorDetails.exception, errorDetails.stack);
    if (!isIntercept) {
      // If you wish to record a "non-fatal" exception, please use `FirebaseCrashlytics.instance.recordFlutterError` instead
      FirebaseCrashlytics.instance.recordFlutterFatalError(errorDetails);
    }
  };
  PlatformDispatcher.instance.onError = (error, stack) {
    bool isIntercept = isInterceptCrash(error, stack);
    if (!isIntercept) {
      // If you wish to record a "non-fatal" exception, please remove the "fatal" parameter
      FirebaseCrashlytics.instance.recordError(error, stack, fatal: true);
    }
    return true;
  };
`
10 crash messages were triggered and reported, but after logging into the backend of the firebase website to check, it was found that there were only 8 crash records. Is this a problem with the background statistics processing of the Firebase website?

**Comment by darshankawar** [comment]
> 10 crash messages were triggered and reported, but after logging into the backend of the firebase website to check, it was found that there were only 8 crash records. Is this a problem with the background statistics processing of the Firebase website?

Could be. The plugin is a thin wrapper around native Firebase sdk and sends, receives data through Dart, so I suggest you to reach out to firebase support to know why only 8 crash records were found and not all.

**Comment by xntop** [comment]
> > 10 crash messages were triggered and reported, but after logging into the backend of the firebase website to check, it was found that there were only 8 crash records. Is this a problem with the background statistics processing of the Firebase website?
> 
> Could be. The plugin is a thin wrapper around native Firebase sdk and sends, receives data through Dart, so I suggest you to reach out to firebase support to know why only 8 crash records were found and not all.

yes，Judging from the native layer code, there is indeed an event reporting strategy

**Comment by xntop** [comment]
How to modify the Firebase configuration file ，the setting json 

```
{
	"settings_version": 3,
	"cache_duration": 86400,
	"features": {
		"collect_logged_exceptions": true,
		"collect_reports": true,
		"collect_analytics": false,
		"prompt_enabled": false,
		"push_enabled": false,
		"firebase_crashlytics_enabled": false,
		"collect_anrs": false,
		"collect_metric_kit": false,
		"collect_build_ids": false
	},
	"app": {
		"status": "activated",
		"update_required": false,
		"report_upload_variant": 2
	},
	"on_demand_upload_rate_per_minute": 10,
	"on_demand_backoff_base": 1.2,
	"on_demand_backoff_step_duration_seconds": 60,
	"app_quality": {
		"sessions_enabled": true,
		"sampling_rate": 1,
		"session_timeout_seconds": 1800
	}
}
```

**Comment by danagbemava-nc** [comment]
Hi @xntop, were you able to reach out to firebase support as requested in https://github.com/firebase/flutterfire/issues/11837#issuecomment-1801651754?

**Comment by xntop** [comment]
Replace sentry, and the test found that sentry can be captured normally, but Firebase sometimes misses the report.
