### ISSUE TITLE
🐛 [firebase_storage] Hot Restart leads to fatal crash when open reference (iOS)

### ISSUE THREAD

**Issue by jtdLab** [firebase/flutterfire#11833]
## Bug report

Cannot connect to emulator after Storage SDK initialization. Call useEmulator(host:port:) before creating a Storage reference or trying to load data.: file FirebaseStorage/Storage.swift, line 247
Lost connection to device.

### Steps to reproduce

1. Run Flutter App with `firebase_storage` on iOS.

```dart
await FirebaseStorage.instance.useStorageEmulator(<host>, <port>);

final ref = FirebaseStorage.instance.ref(<path>);
await ref.putData(<data>);
```
2. Hot Restart

Hint:

Without `putData` call it works.

**Comment by darshankawar** [comment]
@jtdLab 
Can you provide plugin version you are using ? Also, can you provide the complete error log ?

**Comment by jtdLab** [comment]
pub: `firebase_storage: ^11.4.1`

pod: `  - Firebase/Storage (10.16.0):`

**Comment by darshankawar** [comment]
Thanks for the update @jtdLab 
I am unable to replicate it using the [plugin example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_storage/firebase_storage/example) and using the code snippet you shared earlier, running on iOS. Can you take a look at it and check if using the plugin example at your end, gives same error or not ?

**Comment by khamutov** [comment]
@darshankawar I reproduced it on [plugin example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_storage/firebase_storage/example) from master.

The steps are:
- click on "+" -> "Upload string"
- perform hot restart (capital R in the terminal)

Log:

```
Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on iPhone 14 Pro Max is available at: http://127.0.0.1:54561/C7niK84c0DE=/
The Flutter DevTools debugger and profiler on iPhone 14 Pro Max is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:54561/C7niK84c0DE=/

Performing hot restart...
Restarted application in 588ms.
FirebaseStorage/Storage.swift:247: Fatal error: Cannot connect to emulator after Storage SDK initialization. Call useEmulator(host:port:) before creating a Storage reference or trying to load data.
Lost connection to device.
```

flutter --version
```
Flutter 3.13.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d211f42860 (2 weeks ago) • 2023-10-25 13:42:25 -0700
Engine • revision 0545f8705d
Tools • Dart 3.1.5 • DevTools 2.25.0
```

**Comment by darshankawar** [comment]
Thanks for the update @khamutov 
Using the details provided, I was able to replicate the reported error.

/cc @russellwheatley

**Comment by russellwheatley** [comment]
Thanks for reporting, I have reproduced. I will take a look 👌

**Comment by russellwheatley** [comment]
I have a fix, will be out in the next release. Thank you for your patience 🙏

**Comment by khamutov** [comment]
@russellwheatley It works, thanks for prompt solving the issue 🎉! firebase_storage 11.5.1 has no issues with hot restart. 🙏
