### ISSUE TITLE
[firebase_storage]: why it needs to specify metadata 

### ISSUE THREAD

**Issue by akshay-khapare** [firebase/flutterfire#11836]
## Bug report
why it needs to specify metadata while uploading files to storage . It is ok if i want to upload single type of file but what if i want to upload different types of files ,

**Comment by darshankawar** [comment]
@akshay-khapare 
Can you elaborate what exactly is the issue you are facing by providing relevant details so that we can properly address it ?

**Comment by akshay-khapare** [comment]
[image: metadata.png]
here i  given metadata to specify content type ,everything fine for this
code





[image: 1.png]
if i remove metadata  then while uploading file (image) to cloud storage
,firebase not detecting automatically file type
it saved file without type as shown in below picture




[image: Screenshot 2023-11-06 163555.png]
the file type is missing  and its downloadable file not a image ,
and the first file(image) has been uploaded using metadata.

**Comment by Lyokone** [comment]
[According to documentation](https://firebase.google.com/docs/storage/web/upload-files#add_file_metadata), the metadata will be inferred according to the extension of your file.
