### ISSUE TITLE
[cloud_firestore] Support sum() and avg() aggregation queries

### ISSUE THREAD

**Issue by larssn** [firebase/flutterfire#11848]
## What feature would you like to see?

Seeing as `count()` is already supported, it would be beneficial if `sum()` and `avg()` were also supported.
Explanations here: https://firebase.google.com/docs/firestore/query-data/aggregation-queries

**Comment by Lyokone** [comment]
PR already opened here: https://github.com/firebase/flutterfire/pull/11757 
We are waiting for a full API Review, but if you need this feature ASAP you can checkout this branch
