### ISSUE TITLE
🐛 [Firebase_remote_config] RCN Fetch failure.

### ISSUE THREAD

**Issue by duki97** [firebase/flutterfire#11842]
## Bug report

When install the app for first time cannon get data from remote config (data is empty), after I close app, launch app for second time, I can get data only in IOS device (Iphone XR ios version 17.1) on Android works fine.

I get this log 

```
10.16.0 - [FirebaseRemoteConfig][I-RCN000026] RCN Fetch failure: Error Domain=NSURLErrorDomain Code=-999 "cancelado" UserInfo={NSErrorFailingURLStringKey=xxxxxxxx, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <BE1C2A13-06D7-4EF8-B5BD-9D971AED605F>.<1>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <BE1C2A13-06D7-4EF8-B5BD-9D971AED605F>.<1>, NSLocalizedDescription=cancelado}. No cached config result.
10.16.0 - [FirebaseRemoteConfig][I-RCN000026] RCN Fetch failure. Response http error code: 0

```
I checked the GoogleService-Info file and is correct.

### Steps to reproduce

In App delegate I  call method  FirebaseApp.configure()

In flutter:

```
`WidgetsFlutterBinding.ensureInitialized();

await Firebase.initializeApp();

final remoteConfig = FirebaseRemoteConfig.instance;
await remoteConfig.ensureInitialized();

remoteConfig.setConfigSettings(
    RemoteConfigSettings(
        fetchTimeout: const Duration(seconds: 30),
        minimumFetchInterval: const Duration(seconds: 0),
    ),
);

await remoteConfig
     .fetchAndActivate()
     .timeout(const Duration(seconds: 15));

print(remoteConfig.getString('data_name'));`
```

**Comment by darshankawar** [comment]
@duki97 
Can you provide plugin and framework version you are seeing this behavior on ?
Looking at the logs, it is throwing `NSURLErrorDomain Code=-999 "cancelado"` for which a fix was made: https://github.com/firebase/flutterfire/pull/10376

The same `cancelled` log is also mentioned in this open issue: https://github.com/firebase/flutterfire/issues/10981 can you take a look at it and see if you are also hitting the same ?

**Comment by duki97** [comment]
I can resolve this problem using the latest version (4.3.3) and flutter version 3.13.9 with same code.
Note: when i can't get data,I was in version 3.0.4.
 
      WidgetsFlutterBinding.ensureInitialized();
      
      await Firebase.initializeApp();
            final remoteConfig = FirebaseRemoteConfig.instance;
            await remoteConfig.ensureInitialized();

      // only I added await in config setting
      await remoteConfig.setConfigSettings(
        RemoteConfigSettings(
          fetchTimeout: const Duration(seconds: 30),
          minimumFetchInterval: const Duration(seconds: 0),
        ),
      );

      await remoteConfig.fetchAndActivate();
