### ISSUE TITLE
🐛 [Firebase Auth] Cant transform for shrinking

### ISSUE THREAD

**Issue by cyberpwnn** [firebase/flutterfire#11853]
```
ERROR:D8: com.android.tools.r8.kotlin.H
ERROR:D8: com.android.tools.r8.kotlin.H
ERROR:D8: com.android.tools.r8.kotlin.H
ERROR:D8: com.android.tools.r8.kotlin.H
ERROR:D8: com.android.tools.r8.kotlin.H
ERROR:D8: com.android.tools.r8.kotlin.H
ERROR:D8: com.android.tools.r8.kotlin.H
ERROR:D8: com.android.tools.r8.kotlin.H
ERROR:D8: com.android.tools.r8.kotlin.H

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeExtDexDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform firebase-auth-22.2.0.aar (com.google.firebase:firebase-auth:22.2.0) to match attributes {artifactType=android-dex, asm-transformed-variant=debug, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: C:\Users\cyberpwn\.gradle\caches\transforms-3\a80f42a1c5af921992142198ec1fa8e1\transformed\jetified-firebase-auth-22.2.0-runtime.jar.
         > Error while dexing.
   > Failed to transform play-services-measurement-api-21.5.0.aar (com.google.android.gms:play-services-measurement-api:21.5.0) to match attributes {artifactType=android-dex, asm-transformed-variant=debug, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: C:\Users\cyberpwn\.gradle\caches\transforms-3\bfce6a0444c280e0de298fa18b8f1094\transformed\jetified-play-services-measurement-api-21.5.0-runtime.jar.
         > Error while dexing.
   > Failed to transform kotlin-stdlib-1.9.0.jar (org.jetbrains.kotlin:kotlin-stdlib:1.9.0) to match attributes {artifactType=android-dex, asm-transformed-variant=debug, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: C:\Users\cyberpwn\.gradle\caches\transforms-3\7f4509efff026f2a5c812842831e039c\transformed\jetified-kotlin-stdlib-1.9.0.jar.
         > Error while dexing.
```

**Comment by danagbemava-nc** [comment]
Hi @cyberpwnn, please provide a complete minimal reproducible code sample in a repo that we can clone so that we can investigate this issue. 

Please also provide the output of `flutter doctor -v` and `flutter pub get -- --deps style=compact`. 

Thank you

**Comment by milindgoel15** [comment]
Oh so an issue is already created. Been experiencing this issue on my app as well after doing pub upgrade in the project and found out, the issue comes from adding `built_value: ^8.7.0` in the dependencies with the firebase_analytics plugin. And It will only occur if the compileSdk version is 34. Since by default the compileSdkversion is `compileSdkVersion flutter.compileSdkVersion` in the android/app/build.gradle, the transform wont appear in the default flutter.compileSdkversion which is probably 33.

So to reproduce the error:
We need to make the compileSdkversion as 34 with built_value's version 8.7.0.

Reproducible repo: https://github.com/milindgoel15/builtvaluetest

**Comment by danagbemava-nc** [comment]
Hi @milindgoel15, can you upgrade your AGP version and the Gradle version to version 8 to see if you still face this issue? 

In your `android/build.gradle` you can do

```
dependencies {
        classpath 'com.android.tools.build:gradle:8.1.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
```

And in your `android/gradle/wrapper` you can do `distributionUrl=https\://services.gradle.org/distributions/gradle-8.0-all.zip`

**Comment by milindgoel15** [comment]
> can you upgrade your AGP version and the Gradle version to version 8 to see if you still face this issue?

It works after increasing the Gradle plugin version to 8.0+. So what changed with built_value that causes the firebase_analytics to throw a transform issue?

This can be considered one of the solutions for this problem, with alternative approaches to fixing the problem since many users probably won't be able to do AGP 8+ upgrades for their projects as many plugins/dependencies do not support AGP 8+ yet.

**Comment by boolavin** [comment]
Downgrading the gradle plugin worked for me, now it looks like:
`
...
    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.15'
    }
...`

**Comment by Chaseshaw** [comment]
Also having this issue. working on a new app and the google required API is 34 so can't do the downgrade suggestion.

**Comment by milindgoel15** [comment]
> Can someone tell me where the
> 
> `built_value: ^8.7.0`
> 
> is located so I can try tweaking that?

You could add built_value: 8.6.3 to `dependency_overrides:` section. Before doing this, you could check if your pubspec.lock file has this dependency. If it exists there with ^8.7.0, then proceed.

**Comment by milindgoel15** [comment]
An update on this issue:

As of flutter v3.16 update, the lower version of `built_value` won't work anymore and will result in transform error. The only solution that works now are:

- Use AGP 8.0+
- Downgrade flutter to 3.13 and then use lower version of `built_value`

**Comment by tomasatisocco** [comment]
I solved it without downgrading the version flutter by doing the following:
 * Overriding the version of build_version package.
```
dependency_overrides:
  built_value: 8.6.0
```
* Using version 7.3.0 of gradle in build.gradle file
```
dependencies {
        classpath 'com.android.tools.build:gradle:7.3.0'
        classpath 'com.google.gms:google-services:4.3.14'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
```
* Changing the following linne in the android/gradle/wrapper/gradle-wrapper.properties file 
`distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-all.zip`

**Comment by resultanyildizi** [comment]
> I solved it without downgrading the version flutter by doing the following:
> 
> * Overriding the version of build_version package.
> 
> ```
> dependency_overrides:
>   built_value: 8.6.0
> ```
> 
> * Using version 7.3.0 of gradle in build.gradle file
> 
> ```
> dependencies {
>         classpath 'com.android.tools.build:gradle:7.3.0'
>         classpath 'com.google.gms:google-services:4.3.14'
>         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
>     }
> ```
> 
> * Changing the following linne in the android/gradle/wrapper/gradle-wrapper.properties file
>   `distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-all.zip`

This is working for debug run but not working release run. When I try to release with that configuration, it gives the error below for some of my dependencies:

```Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.20, expected version is 1.6.0```

Do you have any suggestion to solve that?

**Comment by resultanyildizi** [comment]
> > Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.20, expected version is 1.6.0
> 
> What kotlin version is set on your `android/build.gradle` file?

```
buildscript {
    ext.kotlin_version = '1.8.20'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.15'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.5'
        classpath 'com.google.firebase:perf-plugin:1.4.2'
    }
  
}
```

**Comment by milindgoel15** [comment]
Some plugin seems to be using old version of kotlin. Try finding which one breaks it.

**Comment by resultanyildizi** [comment]
> Some plugin seems to be using old version of kotlin. Try finding which one breaks it.

Probably but they are just working fine on debug mode. Also, I was using the same kotlin version before and they were no problem again. Is there any settings for ext.kotlin_version for spesifically release mode?

**Comment by tomasatisocco** [comment]
> > > Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.20, expected version is 1.6.0
> > 
> > 
> > What kotlin version is set on your `android/build.gradle` file?
> 
> ```
> buildscript {
>     ext.kotlin_version = '1.8.20'
>     repositories {
>         google()
>         jcenter()
>     }
> 
>     dependencies {
>         classpath 'com.android.tools.build:gradle:7.3.0'
>         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
>         classpath 'com.google.gms:google-services:4.3.15'
>         classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.5'
>         classpath 'com.google.firebase:perf-plugin:1.4.2'
>     }
>   
> }
> ```

This is how I have it: 
```
buildscript {
    ext.kotlin_version = '1.8.21'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.0'
        classpath 'com.google.gms:google-services:4.3.14'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
```

**Comment by dpedrinha** [comment]
Same problem here. 

I get this problem when I use `coreLibraryDesugaringEnabled true` in `android -> compileOptions`

If I remove it, everything works fine. But I kinda need it for a plugin.

None of the above solutions worked for me.

**Comment by laeo** [comment]
Same problem when i configure flutter_local_notifications.

**Comment by dpedrinha** [comment]
> Same problem when i configure flutter_local_notifications.

That's because this plugin requires coreLibraryDesugaringEnabled true. Same as me.

To be honest, I gave up on this plugin. I removed a 10 years old feature from my app. I hope my users will understand, but this plugin is impossible. Too many breaking changes in every update. And now, as far as I understood, it's using libraries not yet supported by most. It was working fine with version 9 of the plugin, but recently Apple forced me to upgrade this plugin and now I can't make it work.

But, if you make it work, please do let me know.

**Comment by resultanyildizi** [comment]
I somehow achieved to make it working again. I hope it helps you too. Here is my working configuration:

- I am using the latest version of Android Studio, `Android Studio Giraffe | 2022.3.1 Patch 4`.
- I am using `coretto-11` as my Android Studio JDK.

- Here is the app level build.gradle file:

```
android {
    compileSdkVersion 33

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    repositories {
        google()
        mavenCentral()
        jcenter()
    }

    defaultConfig {
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        applicationId "application-id"
        minSdkVersion 21
        targetSdkVersion 33
        multiDexEnabled true
    }

    compileOptions {
        // FlutterLocalNotificationsPlugin 13.0.0 
        // https://pub.dev/documentation/flutter_local_notifications/latest/
        // Flag to enable support for the new language APIs
        coreLibraryDesugaringEnabled true

        // Sets Java compatibility to Java 8
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.multidex:multidex:2.0.1'
    
    // FlutterLocalNotificationsPlugin 13.0.0 
    // https://pub.dev/documentation/flutter_local_notifications/latest/
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.2.2'
    implementation 'androidx.window:window:1.0.0'
    implementation 'androidx.window:window-java:1.0.0'

}
```

- Here is the project level build.gradle file:

```
buildscript {
    ext.kotlin_version = '1.8.20'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.15'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.5'
        classpath 'com.google.firebase:perf-plugin:1.4.2'
    }
  
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}
```
- Here is the gradle version

```
distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-all.zip
```

**Comment by marcellocamara** [comment]
Same error here 

```
* What went wrong:
Execution failed for task ':app:mergeExtDexMasculinoDebug'.
> Could not resolve all files for configuration ':app:masculinoDebugRuntimeClasspath'.
   > Failed to transform firebase-auth-22.3.0.aar (com.google.firebase:firebase-auth:22.3.0) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: /Users/cello/.gradle/caches/transforms-3/4b08968830af3da9ea79a835f54e4392/transformed/jetified-firebase-auth-22.3.0-runtime.jar.
         > Error while dexing.
   > Failed to transform play-services-measurement-api-21.5.0.aar (com.google.android.gms:play-services-measurement-api:21.5.0) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: /Users/cello/.gradle/caches/transforms-3/079e6b2ddf406d689e6927fea9a3cc61/transformed/jetified-play-services-measurement-api-21.5.0-runtime.jar.
         > Error while dexing.
```

I'm using Flutter Local Notifications with Firebase Auth

`flutter_local_notifications: ^16.2.0` + `firebase_auth: ^4.14.1`
`Flutter 3.16.0` with `Dart 3.2.0`

With this configs:
```
defaultConfig {
        multiDexEnabled true
    }

compileOptions {
        // Flag to enable support for the new language APIs
        coreLibraryDesugaringEnabled true
        // Sets Java compatibility to Java 8
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.2.2'
    implementation 'androidx.window:window:1.1.0'
    implementation 'androidx.window:window-java:1.1.0'
}

...

dependencies {
    classpath 'com.android.tools.build:gradle:7.4.2'
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    classpath 'com.google.gms:google-services:4.4.0'
    classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.9'
}
```

**Comment by danagbemava-nc** [comment]
Hi @marcellocamara, can you try upgrading your gradle versions to see if you still have this issue?

**Comment by kjxbyz** [comment]
```
Launching lib/main.dart on sdk gphone64 x86 64 in debug mode...
Running Gradle task 'assembleDebug'...
ERROR:D8: com.android.tools.r8.kotlin.H

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeExtDexDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform play-services-measurement-api-21.5.0.aar (com.google.android.gms:play-services-measurement-api:21.5.0) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: /Users/ying/.gradle/caches/transforms-3/172725e3c511207560e4c4a7674f107f/transformed/jetified-play-services-measurement-api-21.5.0-runtime.jar.
         > Error while dexing.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 36s

┌─ Flutter Fix ──────────────────────────────────────────────────────────────┐
│ [!] The shrinker may have failed to optimize the Java bytecode.            │
│ To disable the shrinker, pass the `--no-shrink` flag to this command.      │
│ To learn more, see: https://developer.android.com/studio/build/shrink-code │
└────────────────────────────────────────────────────────────────────────────┘
Exception: Gradle task assembleDebug failed with exit code 1

```


```
android {
    compileSdk 34

    compileOptions {
        // flutter_local_notifications
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.xxx"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-build-configuration.
        minSdkVersion 21
        targetSdkVersion 33
        versionCode 1
        versionName flutterVersionName
        versionNameSuffix appVersionNameSuffix
        multiDexEnabled true
    }

    signingConfigs {
        if (System.getenv("ANDROID_KEYSTORE_PATH")) {
            release {
                storeFile file(System.getenv("ANDROID_KEYSTORE_PATH"))
                keyAlias System.getenv("ANDROID_KEYSTORE_ALIAS")
                keyPassword System.getenv("ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD")
                storePassword System.getenv("ANDROID_KEYSTORE_PASSWORD")
            }
        } else {
            release {
                keyAlias keystoreProperties['keyAlias']
                keyPassword keystoreProperties['keyPassword']
                storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
                storePassword keystoreProperties['storePassword']
            }
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

    // flutter_local_notifications
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.0.4'
    implementation 'androidx.window:window:1.2.0'
    implementation 'androidx.window:window-java:1.2.0'
}
```

```
buildscript {
    ext.kotlin_version = '1.8.22'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.4.0'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-7.6.3-all.zip
```

```

**Comment by milindgoel15** [comment]
It seems more and more developers have started to hit this issue. So it would be better that instead of posting the same console messages, gradle code and since the error only happens if the gradle version is below 8, please try if you could upgrade your project to AGP 8.0+.

If there are any technical limitations such as plugins not supported by AGP 8.0, kindly ask their respective developers to update to AGP 8 asap.

Moreover, alternative solutions can also be used in the meantime.

**Comment by kjxbyz** [comment]
It works for me

```
buildscript {
    ext.kotlin_version = '1.8.22'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.15'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

```

```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-7.6.3-all.zip
```

```
android {
    compileSdk 34

    compileOptions {
        // flutter_local_notifications
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    defaultConfig {
        applicationId "com.xxx"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-build-configuration.
        minSdkVersion 21
        targetSdkVersion 33
        versionCode 1
        versionName flutterVersionName
        versionNameSuffix appVersionNameSuffix
        multiDexEnabled true
//        versionCode flutterVersionCode.toInteger()
    }

    signingConfigs {
        if (System.getenv("ANDROID_KEYSTORE_PATH")) {
            release {
                storeFile file(System.getenv("ANDROID_KEYSTORE_PATH"))
                keyAlias System.getenv("ANDROID_KEYSTORE_ALIAS")
                keyPassword System.getenv("ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD")
                storePassword System.getenv("ANDROID_KEYSTORE_PASSWORD")
            }
        } else {
            release {
                keyAlias keystoreProperties['keyAlias']
                keyPassword keystoreProperties['keyPassword']
                storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
                storePassword keystoreProperties['storePassword']
            }
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    // flutter_local_notifications
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.9'
    implementation 'androidx.window:window:1.1.0'
    implementation 'androidx.window:window-java:1.1.0'
}
```

**Comment by Alwin-Lazar** [comment]
@kjxbyz  Your compileSdk is 34 and targetSdkVersion is  33. 

classpath 'com.android.tools.build:gradle:7.3.1' 

gradle-wrapper.properties

distributionUrl=https\://services.gradle.org/distributions/gradle-7.6.3-bin.zip

Does it really work? 

API level 34's minimum AGP version is 8.1.1

![gradle](https://github.com/firebase/flutterfire/assets/24988480/0f4c71f6-2f2f-43be-b5fb-c69ed674794a)

**Comment by kjxbyz** [comment]
The android studio version also does not meet the requirements, but it still works

**Comment by Alwin-Lazar** [comment]
@kjxbyz It worked thanks. 

Can we set compileSdk: 34 and targetSdkVersion: 33 to submit in play store 

I used 
coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.2.3' version and it also works

![sugar](https://github.com/firebase/flutterfire/assets/24988480/94cc8cf6-103a-443a-8f79-43eed877a6af)

**Comment by g-apparence** [comment]
Any solution to not downgrade gradle?

**Comment by milindgoel15** [comment]
The issue has numerous comments that already provide detailed information and workarounds to the problem.

**Comment by AlfaizCeras** [comment]
> It works for me
> 
> ```
> buildscript {
>     ext.kotlin_version = '1.8.22'
>     repositories {
>         google()
>         mavenCentral()
>     }
> 
>     dependencies {
>         classpath 'com.android.tools.build:gradle:7.3.1'
>         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
>         classpath 'com.google.gms:google-services:4.3.15'
>     }
> }
> 
> allprojects {
>     repositories {
>         google()
>         mavenCentral()
>     }
> }
> 
> rootProject.buildDir = '../build'
> subprojects {
>     project.buildDir = "${rootProject.buildDir}/${project.name}"
> }
> subprojects {
>     project.evaluationDependsOn(':app')
> }
> 
> tasks.register("clean", Delete) {
>     delete rootProject.buildDir
> }
> ```
> 
> ```
> distributionBase=GRADLE_USER_HOME
> distributionPath=wrapper/dists
> zipStoreBase=GRADLE_USER_HOME
> zipStorePath=wrapper/dists
> distributionUrl=https\://services.gradle.org/distributions/gradle-7.6.3-all.zip
> ```
> 
> ```
> android {
>     compileSdk 34
> 
>     compileOptions {
>         // flutter_local_notifications
>         coreLibraryDesugaringEnabled true
>         sourceCompatibility JavaVersion.VERSION_1_8
>         targetCompatibility JavaVersion.VERSION_1_8
>     }
> 
>     kotlinOptions {
>         jvmTarget = '1.8'
>     }
> 
>     defaultConfig {
>         applicationId "com.xxx"
>         // You can update the following values to match your application needs.
>         // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-build-configuration.
>         minSdkVersion 21
>         targetSdkVersion 33
>         versionCode 1
>         versionName flutterVersionName
>         versionNameSuffix appVersionNameSuffix
>         multiDexEnabled true
> //        versionCode flutterVersionCode.toInteger()
>     }
> 
>     signingConfigs {
>         if (System.getenv("ANDROID_KEYSTORE_PATH")) {
>             release {
>                 storeFile file(System.getenv("ANDROID_KEYSTORE_PATH"))
>                 keyAlias System.getenv("ANDROID_KEYSTORE_ALIAS")
>                 keyPassword System.getenv("ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD")
>                 storePassword System.getenv("ANDROID_KEYSTORE_PASSWORD")
>             }
>         } else {
>             release {
>                 keyAlias keystoreProperties['keyAlias']
>                 keyPassword keystoreProperties['keyPassword']
>                 storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
>                 storePassword keystoreProperties['storePassword']
>             }
>         }
>     }
> 
>     buildTypes {
>         release {
>             signingConfig signingConfigs.release
>             minifyEnabled true
>             proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
>         }
>         debug {
>             signingConfig signingConfigs.debug
>         }
>     }
> }
> 
> flutter {
>     source '../..'
> }
> 
> dependencies {
>     // flutter_local_notifications
>     coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.9'
>     implementation 'androidx.window:window:1.1.0'
>     implementation 'androidx.window:window-java:1.1.0'
> }
> ```

Worked for me in both debug and release mode.
Thanks👍🏻

**Comment by adrianvintu** [comment]
The following configuration worked for me when migrating to AGP8:

`build.gradle`

```
buildscript {
    ext.kotlin_version = '1.9.0'
    repositories {
        google()
        jcenter()
        maven { url 'https://developer.huawei.com/repo/' }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.1'
        classpath 'com.google.gms:google-services:4.3.15'
        classpath 'com.google.firebase:perf-plugin:1.4.2'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.6'
        classpath 'com.huawei.agconnect:agcp:1.5.2.300'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
...
```

`app\build.gradle`

```
...
apply plugin: 'com.android.application'
apply plugin: 'com.google.firebase.firebase-perf'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
//apply plugin: 'com.huawei.agconnect'

android {
    // Conditional for compatibility with AGP <4.2.
    if (project.android.hasProperty("namespace")) {
      namespace 'my_namespace'
    }

    compileSdkVersion 34
...		  
```

`gradle-wrapper.properties`

```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
#https://developer.android.com/studio/releases/gradle-plugin
distributionUrl=https\://services.gradle.org/distributions/gradle-8.0-all.zip
```

Forks (if required):
https://github.com/adrianvintu/file_saver
https://github.com/adrianvintu/flutter_statusbarcolor
https://github.com/adrianvintu/hms-flutter-plugin

**Comment by aykutuludag** [comment]
I found a working solution for flutter and possibly other kind of multi-plaform/native projects: https://stackoverflow.com/a/77738936/4606368

**Comment by JoshStrobl** [comment]
Bad bot, fuck off.

**Comment by danagbemava-nc** [comment]
Hi all, my apologies for getting back to this issue late and my apologies for letting this get out of hand. 

As it stands now, the core issues appears to be a gradle configuration issue which can be resolved by upgrading your gradle version. There are seemingly conflicting reports about the source of the issue (either built_value or corelibrarydesugaring, and possibly other sources that may or may not be related to either issue) 

To anyone else who may be facing this issue, please try any the solutions provided in this thread. If you still get the issue after trying the solutions, please file a new issue and provide detailed steps to reproduce so that we can investigate this issue. 

Closing this for now as there are several solutions in the thread. 

Thank you
