### ISSUE TITLE
🐛 [firebase_storage] - User does not have permission to access this object.

### ISSUE THREAD

**Issue by codewitharvind** [firebase/flutterfire#11863]
## Bug report

**Describe the bug**
When I am trying to upload any image to Firebase then I get an error from Firebase
![image](https://github.com/firebase/flutterfire/assets/51447920/484a1aae-3480-40a2-b25f-b35a5e483b86)
![image](https://github.com/firebase/flutterfire/assets/51447920/c0d65392-60b0-412f-8b0c-3ff4c3c5fc92)

Earlier it was working properly but now it is throwing the above error

### Steps to reproduce

2. '...'
3. See error or incorrect behavior

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by danagbemava-nc** [comment]
Hi @codewitharvind, this is an issue with your permissions on firebase storage. You should review it. See the stackoverflow thread below for some options. 

Closing from here as this is not an issue with the plugin. 
https://stackoverflow.com/questions/38671444/user-does-not-have-permission-to-access-this-object-firebase-storage-android
