### ISSUE TITLE
🐛 [Firebase/Analytics] Firebase Analytics report that Mac users use iOS....

### ISSUE THREAD

**Issue by stephane-archer** [firebase/flutterfire#11868]
Firebase Analytics reports that all my Mac OS users used iOS... I think you mean Mac OS...
<img width="593" alt="Screenshot 2023-11-10 at 14 17 11" src="https://github.com/firebase/flutterfire/assets/2981437/d9feeb2c-b7a9-444a-a83c-07a11a7f01db">

**Comment by danagbemava-nc** [comment]
Hi @stephane-archer, I think this might be an issue with the underlying firebase-ios-sdk rather than the flutter fire plugins.

Can you try reaching out to firebase support to see if they can offer any assistance?

**Comment by stephane-archer** [comment]
I tried but they have been not so cooperative saying that Firebase is built for mobile and the web, not Mac OS and desktop experience. so "it's not a bug but a feature"...

**Comment by danagbemava-nc** [comment]
Hi @stephane-archer, the macOS implementation is more or less based on the iOS implementation.

Since the flutterfire_plugins are thin wrappers around the native implementations, this would have to be implemented on the native side before we can (if required), implement it on our end. 

Please feel free to raise a feature request on the firebase-ios-sdk repo. If you are redirected here, kindly leave a comment below and I will reopen this. 

Thank you

**Comment by stephane-archer** [comment]
"Hi Stephane,

Thanks for the quick update and for providing those details.

Upon further investigation of the issue-at hand and also discussing your case with the team, it appears that the OS should be reported as "Macintosh" rather than "iOS" as stated in the [documentation](https://support.google.com/analytics/answer/9143382?hl=en#zippy=%2Cplatform-device:~:text=Android%27%2C%20%27Chrome%20OS%27%2C%20%27-,Macintosh,-%27%2C%20and%20%27Windows%27.).

As an action on your behalf, I have filed your case along with the details you have shared as a bug report for our engineering team to further investigate the issue at-hand. While our team continues to investigate this behavior, please note that we have yet to provide any details or timelines for the fix. For now, you may keep an eye out on our [release notes](https://firebase.google.com/support/releases) and[ official blog](https://firebase.googleblog.com/) to get the latest updates regarding Firebase features and its services, including the bug fixes and enhancements we've rolled out.

Our sincere apologies for the inconvenience this has caused you. Just let me know if you have additional questions or clarifications, I'll be more than happy to help.

Best,
Troy"
