### ISSUE TITLE
[firebase] Only mobile: type '_Map<Object?, Object?>' is not a subtype of type 'Map<String, dynamic>' in type cast

### ISSUE THREAD

**Issue by Patrick386** [firebase/flutterfire#11872]
Make the data types consistent between the mobile and web platforms. The issue only arises on the mobile platform.

In my app, I use a Cloud Function to fetch data. On the web, the data type is Map<String, dynamic>, but on mobile, it is Map<Object?, Object?>. I've attempted various methods for type conversion, but I can't resolve the error. It's also inconsistent. There have been no issues when fetching other collection data, and data retrieval from the web is working correctly. Currently, I haven't been able to identify the cause.

**< desktop, mobile >**
Data type: _Map<Object?, Object?>

**Data Convert**
```
 Map<String, dynamic> categoryData = Map<String, dynamic>.from(data['categoryData']! as Map<Object?, Object?>);
        ProntoCategoryData category = ProntoCategoryData.fromJson(categoryData); // <<< convert error
```

<img width="1385" alt="Screenshot 2023-11-12 at 11 03 49 AM" src="https://github.com/firebase/flutterfire/assets/49754877/1c66b754-f5ac-4efd-b64b-cac694083591">

**< Web >**
Data type: Map<String, dynamic>
No error
<img width="1766" alt="Screenshot 2023-11-12 at 10 58 15 AM" src="https://github.com/firebase/flutterfire/assets/49754877/807be949-c2ed-4e57-a2c8-0cb4cee7b4bd">

```
[✓] Flutter (Channel stable, 3.13.9, on macOS 13.0 22A380 darwin-arm64 (Rosetta), locale en-KR)
    • Flutter version 3.13.9 on channel stable at /Users/patrick386/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (2 weeks ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/patrick386/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 76.3.1
    • Dart plugin version 222.4582

[✓] VS Code (version 1.71.1)
    • VS Code at /Users/patrick386/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] VS Code (version 1.75.1)
    • VS Code at /Users/patrick386/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.0 22A380 darwin-arm64 (Rosetta)
    • Chrome (web)    • chrome • web-javascript • Google Chrome 119.0.6045.123

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

https://github.com/firebase/flutterfire/issues/7945
https://github.com/firebase/flutterfire/issues/10909

**Comment by danagbemava-nc** [comment]
Hi @Patrick386, can you provide the output of `flutter pub deps -- --style=compact`? 

Also, would it be possible to provide a minimal complete reproducible code sample in a repo that we can clone so that we can verify this issue?

Thank you

**Comment by Patrick386** [comment]
> Hi @Patrick386, can you provide the output of `flutter pub deps -- --style=compact`?
> 
> Also, would it be possible to provide a minimal complete reproducible code sample in a repo that we can clone so that we can verify this issue?
> 
> Thank you

I'm using cloud functions to fetch data. Unable to resolve the issue, I modified the cloud_firestore code on the client side, and it works without any problems. Presumably, **'dynamic'** is more flexible because it allows null, unlike **'Object.'** There might be values in the data that are not Objects, causing exceptions during data processing. In this case, there is a SubModel. There's no issue with the Model, but it seems that mobile doesn't tolerate it. If I use the same type (Map<String, dynamic>) on mobile, it seems that there won't be any issues. Thank you.

**Comment by danagbemava-nc** [comment]
Hi @Patrick386, which portion of the cloud_firestore codebase did you have to modify?

**Comment by Patrick386** [comment]
> Hi @Patrick386, which portion of the cloud_firestore codebase did you have to modify?

I removed the previously used cloud function and replaced it with the following code.
It works correctly on both the web and mobile app.

**Remove Cloud functions:**
```
Future<HttpsCallableResult<Map<String, dynamic>?>> getStartAccountAip() async {
 return functions
     .httpsCallable('getStartAccount')
     .call({'token': await getDeviceToken()});
}
```

**Changed code:**
```
final CollectionReference<CategoryData> categoryCollectionRef =
   firebaseFirestore
       .collection(CATEGORY_COLLECTION)
       .withConverter<CategoryData>(
           fromFirestore:
               (DocumentSnapshot<Map<String, dynamic>> snapshot, _) =>
                   CategoryData.fromJson(snapshot.data()!),
           toFirestore: (CategoryData model, _) => model.toJson());

```

```

Future<void> fetchData() async {
 ...

DocumentReference<CategoryData> categoryRef =
categoryCollectionRef.doc(‘category');


await FirebaseFirestore.instance.runTransaction((Transaction transaction)async{
 final DocumentSnapshot<Account> accountSnapshot = await transaction.get(accountRef);
 Account? account = accountSnapshot.data();

 final DocumentSnapshot<CategoryData> categorySnapshot = await transaction.get(categoryRef);
 CategoryData? category = categorySnapshot.data();

 return (account, category);
}).then(((Account?, CategoryData?) value){
 account = value.$1;
 categories = value.$2;
});

}
```

**Comment by danagbemava-nc** [comment]
Hi @Patrick386, was this within your project code?

**Comment by Patrick386** [comment]
> Hi @Patrick386, was this within your project code?

Yes, that's correct. I'm also using cloud functions along with it.

**Comment by danagbemava-nc** [comment]
What version of `cloud_functions` were you using?

**Comment by biancoblu79** [comment]
@Patrick386 were you able to solve this? If so, how? I have the same issue. That's happening only when I call the function from Android/iOS. If I call it from the web app everything just works fine

**Comment by biancoblu79** [comment]
Hello @danagbemava-nc, If that could help identify the issue... this is my code:

```
class SearchRepository {
  SearchRepository(this._functions);
  final FirebaseFunctions _functions;

  Future<SearchResults?> searchResults(String searchQuery) async {
    if (searchQuery != '') {
      final HttpsCallableResult<dynamic> callable =
          await _functions.httpsCallable('enterprise_search_docs').call(
        <String, dynamic>{'search_query': searchQuery},
      );
      final SearchResults results = SearchResults.fromJson(callable.data);
      return results;
    } else {
      return null;
    }
  }
}
```

```
  # Firebase
  firebase_core: ^2.22.0
  firebase_auth: ^4.13.0
  firebase_ui_auth: ^1.10.0
  firebase_storage: ^11.5.0
  cloud_firestore: ^4.13.0
  cloud_functions: ^4.5.4
  firebase_ui_firestore: ^1.5.14
```

I am calling the method with the same input string both from the Web App and from the iOS/Android emulators. I checked the logs on Google Cloud and from the local Firebase functions emulator and the Cloud Function is returning the same data with the same types in all the cases. 
![web_response](https://github.com/firebase/flutterfire/assets/14143174/614ee160-f170-486f-a7b2-6fd9e8c3a4bb)
![iOS_response](https://github.com/firebase/flutterfire/assets/14143174/13159264-01ba-46b8-8839-79bee6f7559f)
![iOS Issue](https://github.com/firebase/flutterfire/assets/14143174/19f0fc03-5593-4ff8-be84-4b12cd37ceb8)

**Comment by biancoblu79** [comment]
I fixed the iOS/Android issue by replacing: data with Map<String, dynamic>.from(data)

```
List<DocData> docData = docDataList
        .map((data) => DocData.fromJson(Map<String, dynamic>.from(data)))
        .toList();
```

I just wonder why the difference in the behavior among the platforms...

**Comment by danagbemava-nc** [comment]
Hi @Patrick386,  @biancoblu79, would it be possible to provide a complete minimal sample in a repo that we can clone so that we can verify this? I tried with the plugin example app but it throws an error on mobile, so I can't verify this.

**Comment by TravisSperry** [comment]
I seem to be seeing the same thing here. I wonder if this is an actual issue.

**Comment by ramanraja** [comment]
My workaround was this cast:
`myJson = Map<String, dynamic>.from (snapshot.value as Map);`
Doesn't look nice, but I will use this until anything more elegant comes up.
