### ISSUE TITLE
🐛 [firebase_auth] Apple Sign-In: missing-email An email address must be provided error triggered even on the first login attempt using AppleAuthProvider.

### ISSUE THREAD

**Issue by mtalha101** [firebase/flutterfire#11878]
## Bug report

**Describe the bug**
Even with the new users, signing in using Apple Auth Providers returns an error with 'null' email and display name. When tapping on the SIgn in with Apple button, no bottomsheet showing an option to hide or share email is displayed, rather it directly displays Continue with Password sheet. I've previously done it using the sign_in_with_apple plugin, but unfortunately, the problem is the same.

### Steps to reproduce

Below is the sample code I'm trying to test.

`try {
      final userCreds = await _firebaseAuth.signInWithProvider(AppleAuthProvider());
      return userCreds;
    } catch (e, s) {
      FirebaseCrashlytics.instance.recordError(e, s);
      return null;
    }`

### Expected behavior

The Sign in with Apple should show a bottomsheet to allow users to choose to hide or share their email, and then proceed to next step of authenticating with password, touch ID or face ID.

### Sample project

![Simulator Screenshot - iPhone Xs - 2023-11-13 at 16 52 18](https://github.com/firebase/flutterfire/assets/61347696/4dfbbf53-7fb9-4649-8004-f301f1109af8)

### Flutter dependencies

firebase_core: ^2.11.0
firebase_auth: ^4.12.1

**Comment by danagbemava-nc** [comment]
Hi @mtalha101, have you set the required scopes for apple sign in? 

With apple sign in, you need to explicitly declare the scopes that you need, otherwise you will not get anything from apple. Also, with apple_sign_in, the data is sent by apple only on the first sign in, unless you remove the app from the sign in list.

**Comment by flutterocks** [comment]
I'm also experiencing this and have tried adding scopes like:

```dart
  Future<void> signInWithApple() async {
    final appleProvider = AppleAuthProvider();
    appleProvider.addScope('fullName');
    appleProvider.addScope("email");
    if (kIsWeb) {
      await FirebaseAuth.instance.signInWithPopup(appleProvider);
    } else {
      final credential =
          await FirebaseAuth.instance.signInWithProvider(appleProvider);
      print("sign in done");
    }
  }
```

Is there a different way to add scopes?
