### ISSUE TITLE
🐛 [cloud_firestore] Permission Denied error started to happen today without me changing the Firestore rules or anything in the app

### ISSUE THREAD

**Issue by rpungin** [firebase/flutterfire#11898]
## Bug report

All of a sudden today, my Flutter application is getting this exception:
```
Unhandled Exception: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.
E/flutter (16121): #0      StandardMethodCodec.decodeEnvelope
message_codecs.dart:652
E/flutter (16121): #1      MethodChannel._invokeMethod
platform_channel.dart:310
E/flutter (16121): <asynchronous suspension>
E/flutter (16121): #2      MethodChannel.invokeMapMethod
platform_channel.dart:510
E/flutter (16121): <asynchronous suspension>
E/flutter (16121): #3      MethodChannelQuery.get
method_channel_query.dart:99
E/flutter (16121): <asynchronous suspension>
```
The thing is, the app has been running for almost a year with no problems and I have not touched the Firestore security rules since then, which are

```
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if request.auth.uid != null;
    }
  }
}
```

So yesterday, everything worked, but today I am getting the permission denied error. Nothing changed from the apps perspective! I am 100% positive that I am successfully logged in the app.

My production users can't use the app now!

**Comment by netoreboucas** [comment]
I'm experiencing the same problem in several apps that use Firestore and apparently the error is in Google Cloud, you can follow their solution here: https://status.cloud.google.com/incidents/iRvJVnsbz8T47ySiy5Hg

**Comment by rpungin** [comment]
Thank you for the link @netoreboucas ! I could not find any solution on that page though. Is there one, or do we just have to wait till they fix it?

**Comment by rpungin** [comment]
Aaaand drumroll, they fixed it! 👍

**Comment by netoreboucas** [comment]
All we can do is wait. But apparently they have already corrected it, based on their latest report.
