### ISSUE TITLE
🐛 [firebase_analytics] Device model is not populating for Galaxy / Amazon device

### ISSUE THREAD

**Issue by Chadpagesuite** [firebase/flutterfire#11906]
I'm using firebase_analytics: ^10.1.0 and there is an issue that the "device mode" dimension is not populating for Galaxy / Amazon device. And another dimension "Device" is not populating apple device.

Is it a bug or something i have to do such that i can combine them as one dimension?

![image](https://github.com/firebase/flutterfire/assets/151061269/947affe5-7947-4683-8285-6638846a3599)

**Comment by danagbemava-nc** [comment]
Hi @Chadpagesuite, how are you getting this data? 

This may be due to differences between the native sdks as the flutterfire_plugins are thin wrappers around the existing native sdks.
