### ISSUE TITLE
🐛 [Firebase Crashlytics] Crash not reported at Firebase Console 

### ISSUE THREAD

**Issue by ynlvko** [firebase/flutterfire#11908]
## Bug report

**Describe the bug**
I have an app for iOS and Android, and each has 3 flavors: [dev], [stage], [prod]. I've set up Firebase Crashlytics for each 6 apps, but it doesn't work for iOS [prod].

Before release, we already had a React Native app in the App Store, and we had a Firebase App for it. Then we deleted it, and created it again with the same settings (basically, bundle ID). And now we have an issue that Crashlytics works for 5 out of 6 apps.

**Comment by danagbemava-nc** [comment]
Hi @ynlvko, if it is working for 5/6 apps, you should probably be checking your configuration. 

Which platform is the last app running on and what version of the FF packages are you using?

**Comment by russellwheatley** [comment]
@ynlvko I tested iOS fatal and non-fatal crashes and they both appeared in the Crashlytics console. I'm going to need steps to reproduce this. Thanks.
