### ISSUE TITLE
[Flutter FCM Firebase Messaging] Don't receive notification at all or receive it with huge time gap between sending and receiving

### ISSUE THREAD

**Issue by VolodiaHunkalo** [firebase/flutterfire#11918]
## Bug report

**Describe the bug**
Don't receive notification at all or receive it with huge time gap between sending and receiving

### Expected behavior

3 days ago everything worked correctly

**Comment by danagbemava-nc** [comment]
Hi @VolodiaHunkalo, did you make any changes to your project? 

Please provide the output of `flutter pub deps -- --style=compact` and the output of `flutter doctor -v`. 

Also, what platform(s) are you experiencing this issue on?
