### ISSUE TITLE
🐛 [firebase_analytics] Missing google_app_id. Firebase Analytics disabled. [ANDROID]

### ISSUE THREAD

**Issue by alidev0** [firebase/flutterfire#11912]
## Bug report

**Describe the bug**
After installing firebase on a new app it gives the error "Missing google_app_id. Firebase Analytics disabled.

### Steps to reproduce

1. create new app with the flutter sdk [3.16.0].
2. create new app in firebase, enable analytics.
3. install Firebase Analytics with flutter fire.
4. copy paste example code in: https://github.com/firebase/flutterfire/blob/master/packages/firebase_analytics/firebase_analytics/example/lib/main.dart
5. run app

I also tried to do the installment manually and again through android studio but same result.

### Expected behavior

Firebase Analytics should be be able to work.

### Flutter dependencies

  firebase_core: ^2.22.0
  firebase_analytics: ^10.7.0

IOS works fine. Android issue only.

**Comment by danagbemava-nc** [comment]
Hi @alidev0, kindly check if this comment helps https://github.com/firebase/flutterfire/issues/9785#issuecomment-1291924142

**Comment by nickJLm** [comment]
I am seeing the same issue. We tried to revert back to other versions, but cannot seem to figure out a solution.

**Comment by jibbers42** [comment]
I have the same problem and https://github.com/firebase/flutterfire/issues/9785#issuecomment-1291924142 isn't working. I'm using a newly built, java based `android` project from Flutter 3.16.0 and I think those comments may not directly map. I'm don't know much about grade, but I'll look at current Firebase documentation for configuring Flutter-android and see if I can get the error to go away.

Considering issue https://github.com/firebase/flutterfire/issues/9785#issuecomment-1291924142 was closed, could someone please verify this is a bug. My understanding is the cli should be making the needed changes to the android project... or does the Firebase Flutter documentation need updating?

**Comment by ashutosh-mulik** [comment]
I'm experiencing the same issue. Here are the details of my setup:
- **Flutter:** (Channel stable, 3.13.9, on macOS 12.6.6 21G646 darwin-x64, locale en-IN)
- **Platform:** Android
- **Firebase Core:** ^2.22.0
- **Firebase Analytics:** ^10.7.0

<details open>
<summary>Doctor summary</summary>
[✓] Flutter (Channel stable, 3.13.9, on macOS 12.6.6 21G646 darwin-x64, locale
    en-IN)<br>
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)<br>
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)<br>
[✓] Chrome - develop for the web<br>
[✓] Android Studio (version 2022.3)<br>
[✓] VS Code (version 1.84.2)<br>
[✓] Connected device (3 available)<br>
[✓] Network resources<br>
</details>

**Comment by danagbemava-nc** [comment]
Hi all, I just followed the steps in https://github.com/firebase/flutterfire/issues/9785#issuecomment-1291924142 and I do not get the `missing google_app_id` message. 

Can you try to make your config match these files to see if you still face the issue? 

This is my android/build.gradle


```
buildscript {
    ext.kotlin_version = '1.7.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.14'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

```

`android/app/build.gradle`

```groovy
plugins {
    id "com.android.application"
    id "kotlin-android"
    id "dev.flutter.flutter-gradle-plugin"
    // id "com.google.gms.google-services"
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

android {
    namespace "com.example.lyticstest"
    compileSdkVersion flutter.compileSdkVersion
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.lyticstest"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
        minSdkVersion flutter.minSdkVersion
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {}

apply plugin: 'com.google.gms.google-services'
```

> My understanding is the cli should be making the needed changes to the android project..

This appears to have been fixed in the latest version of the cli, can you check https://github.com/invertase/flutterfire_cli/issues/210#issuecomment-1770505141 to see if that helps?

**Comment by alidev0** [comment]
> Hi @alidev0, kindly check if this comment helps [#9785 (comment)](https://github.com/firebase/flutterfire/issues/9785#issuecomment-1291924142)

This seems to work for me. Thank you.

P.S in my case I had to revert to "classpath 'com.google.gms:google-services:4.3.14'"

**Comment by ashutosh-mulik** [comment]
Thanks @danagbemava-nc 

I followed the steps below, and it appears to be working:
1. Updated the Google services version from `'com.google.gms:google-services:4.3.10'` to `4.3.14`. I also tried `4.4.0`, but it didn't work; only `4.3.14` is effective.
2. Added the line `apply plugin: 'com.google.gms.google-services'` above the android block in `android/app/build.gradle`:
```
def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

// START: This here
apply plugin: 'com.google.gms.google-services'
// END:

android {
    namespace "com.example.test"
    compileSdkVersion flutter.compileSdkVersion
    ndkVersion flutter.ndkVersion
```

**Comment by jibbers42** [comment]
> This appears to have been fixed in the latest version of the cli, can you check https://github.com/invertase/flutterfire_cli/issues/210#issuecomment-1770505141 to see if that helps?

I verified I was on the latest version and assume the `-v` output is just out of date (I actually did do the `deactivate` step mentioned below and installed again just be sure)...
```pwsh
> dart pub global activate flutterfire_cli 0.3.0-dev.18 --overwrite
Package flutterfire_cli is currently active at version 0.3.0-dev.18.
The package flutterfire_cli is already activated at newest available version.
To recompile executables, first run `dart pub global deactivate flutterfire_cli`.
Installed executable flutterfire.
Activated flutterfire_cli 0.3.0-dev.18.
```
```pwsh
> flutterfire -v
0.3.0-dev.16
✔ There is a new version of flutterfire_cli available (0.2.7). Would you like to update? · no
```

I then ran `configure` and also `reconfigure`...
```pwsh
> flutterfire configure
? You have an existing `firebase.json` file and possibly already configured your project for Firebase. Would you prefer to reuse the? You have an existing `firebase.json` file and possibly already configured your project for Firebase. Would you prefer to reuse the✔ You have an existing `firebase.json` file and possibly already configured your project for Firebase. Would you prefer to reuse the values in your existing `firebase.json` file to configure your project? · yes

> flutterfire reconfigure

```

The `flutter` section of my `firebase.json` is:
```json
  "flutter": {
    "platforms": {
      "android": {
        "buildConfigurations": {
          "src\\dev": {
            "projectId": "[redacted]",
            "appId": "[redacted]",
            "fileOutput": "android\\app\\src\\dev\\google-services.json"
          },
          "src\\prod": {
            "projectId": "[redacted]",
            "appId": "[redacted]",
            "fileOutput": "android\\app\\src\\prod\\google-services.json"
          }
        }
      },
      "dart": {
        "lib\\firebase_options_dev.dart": {
          "projectId": "[redacted]",
          "configurations": {
            "android": "[redacted]"
          }
        },
        "lib\\firebase_options_prod.dart": {
          "projectId": "[redacted]",
          "configurations": {
            "android": "[redacted]"
          }
        }
      }
    }
  }
```

The tool did not add any lines to either `build.gradle` file. However, I was able to get it working manually after reading tips everyone left (thank you all).

At least on my machine, there still seems to be a bug where it doesn't write the needed config.

**Comment by danagbemava-nc** [comment]
Hi @jibbers42, for the flutterfire_cli issue, please file an issue on its dedicated repo. 

Since the issue in this thread has been resolved, I will be closing this issue. 

Thank you

**Comment by jibbers42** [comment]
So after searching the repos owned by `firebase` on github, I ended up locating the pub.dev flutterfire_cli and using the Repository link on that page to get to the Invertase repo (https://github.com/invertase/flutterfire_cli).

What is the relationship between Invertase and Firebase? Curious why this tool seems to be outsourced and isn't within Firebase?

**Comment by andypradhana** [comment]
> This seems to work for me. Thank you.
> 
> P.S in my case I had to revert to "classpath 'com.google.gms:google-services:4.3.14'"

This seems to work for me too. Thank you.

P.S in my case I had to revert to "classpath 'com.google.gms:google-services:4.3.14'" from 4.4.0

Thank you now is working..
