### ISSUE TITLE
🐛 [firebase_crashlytics 3.4.5] mach-o/utils.h file not found

### ISSUE THREAD

**Issue by khushAdmin** [firebase/flutterfire#11936]
## Bug report

**Describe the bug**
I have implemented firebase_crashlytics plugin in one of my flutter project  that support android/iOS/macOS. But when I try to run my flutter project in macOS with the Plugin its unable to compile with 'mach-o/utils.h' file not found issue.

Please check:-
macos/Pods/FirebaseCrashlytics/Crashlytics/Shared/FIRCLSMachO/FIRCLSMachO.m:24:10: fatal error: 'mach-o/utils.h' file not found
#include <mach-o/utils.h>
^~~~~~~~~~~~~~~~

**Comment by danagbemava-nc** [comment]
Hi @khushAdmin, I just tested the crashlytics example app on macOS and it built just fine. 

Can you check if you face this issue with the sample app? If you do not, please provide a complete minimal reproducible code sample so that we can investigate this. 

Please also provide the output of `flutter doctor -v`. 

Thank you

**Comment by khushAdmin** [comment]
Hii,
Thank you for your reply
[✓] Flutter (Channel stable, 3.13.6, on macOS 12.7.1 21G920 darwin-x64, locale en-GB)
    • Flutter version 3.13.6 on channel stable at /Users/TEST/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (8 weeks ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/<>/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_SDK_ROOT = /Users/<>/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.12.1


> Hi @khushAdmin, I just tested the crashlytics example app on macOS and it built just fine.
> 
> Can you check if you face this issue with the sample app? If you do not, please provide a complete minimal reproducible code sample so that we can investigate this.
> 
> Please also provide the output of `flutter doctor -v`.
> 
> Thank you

**Comment by danagbemava-nc** [comment]
Hi @khushAdmin, did you try this? And what were the results if you did?

> Can you check if you face this issue with the sample app? If you do not, please provide a complete minimal reproducible code sample so that we can investigate this.

**Comment by razvan-g-nutu** [comment]
While this has been somehow thrown to the bin of the "hope-to-be-solved-by-itself" problems, I have encountered it too. As I'm only a modest react-native programmer, having the project setup being done by somebody else, I've run into the same problem when trying to build the project with xcode. And by inspecting the source code coming with the pods, there indeed we can see an unresolved import "#import mach-o/utils.h" in the file mentioned above: Pods/FirebaseCrashlytics/Crashlytics/Shared/FIRCLSMachO/FIRCLSMachO.m:24:10.

So my question is: how can we have that file resolved? Should it be provided with the firebase pod? Should it be by default on the macOS? 

The problematic import was not there in older versions of the library.

Many thanks in advance for any help

**Comment by paulb777** [comment]
@themiswang Should the import be wrapped in `#if CLS_TARGET_OS_VISION`?
