### ISSUE TITLE
[firebase_messaging]: <[I-FCM002022] APNS device token not set before retrieving FCM Token for Sender ID '808662265677'.Be sure to re-retrieve the FCM token once the APNS device token is set. 2023-11-24 23:46:40.037190-0500 Tailored[9893:4209932] 10.17.0 - [FirebaseMessaging][I-FCM002022] Declining request for FCM Token since no APNS Token specified>

### ISSUE THREAD

**Issue by yunsanch** [firebase/flutterfire#11946]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you aware of the differences between iOS and Android background message handling?

- [X] I understand that iOS and Android background messages behave differently, and I've designed my application with that in mind.

### Do you have an active Apple Developer account?

- [X] I have an active Apple Developer account.

### Are you using a physical iOS device to test background messages?

- [X] I am using a physical iOS device to test background messages.

### Have you enabled "Remote Notifications" & "Background Mode" (Checking options for "Background Processing" & "Remote Notifications") in your app's Xcode project?

![image](https://github.com/firebase/flutterfire/assets/60577975/40ed7f7a-f1ce-4441-be53-1789cd7cb2f6)

### Have you created an APNs key in your Apple Developer account & uploaded this APNs key to your Firebase console?

![image](https://github.com/firebase/flutterfire/assets/60577975/76fe4b6c-7de7-4825-837d-1e19d360598d)

### Have you disabled method swizzling for Firebase in your app?

![image](https://github.com/firebase/flutterfire/assets/60577975/83d8975f-3f76-49b4-8247-92eba6403e3d)

### Are you sending messages to your app from the Firebase Admin SDK?

![image](https://github.com/firebase/flutterfire/assets/60577975/34010e3b-44e2-4956-a5bf-56dfee304305)

### Have you requested permission from the user to receive notifications?

- [X] I have the relevant permission to receive notifications.

### Have you used the 'Console' application on your macOS device to check if the iOS device's system is throttling your background messages?

Message ID: 1700887822751310
whats this [AnyHashable("gcm.message_id"): 1700887822751310, AnyHashable("google.c.sender.id"): 808662265677, AnyHashable("google.c.fid"): csX_0W0UKUP6mVDFVqHtvd, AnyHashable("google.c.a.e"): 1, AnyHashable("body"): get the alert boys, AnyHashable("aps"): {
    alert =     {
        body = "get the alert boys";
        title = "testing fucntions on update";
    };
}]

### Additional context and comments

i keep getting this errror on console 

`FirebaseMessaging][I-FCM002022] APNS device token not set before retrieving FCM Token for Sender ID '808662265677'.Be sure to re-retrieve the FCM token once the APNS device token is set.
2023-11-24 23:46:40.037190-0500 Tailored[9893:4209932] 10.17.0 - [FirebaseMessaging][I-FCM002022] Declining request for FCM Token since no APNS Token specified`
then i do get a token and then still getting the error afterwords
`error to subcribed to topic : Error Domain=com.google.fcm Code=505 "No APNS token specified before fetching FCM Token" UserInfo={NSLocalizedFailureReason=No APNS token specified before fetching FCM Token}
Firebase registration token: Optional("csX_0W0UKUP6mVDFVqHtvd:APA91bGnxPIT6PL5MMF7diwQFFEmnmq26smIk75bjBKg9XFLR3b_jaDYoAAkMWRa5GFOhMHGjGzfDtHIXOPjcqixB-a-y6lXgnZ94Tf7KEmBijTKVcbxtWvL5ZEx59OoSBmtmDAm8jZ9")
["token": "csX_0W0UKUP6mVDFVqHtvd:APA91bGnxPIT6PL5MMF7diwQFFEmnmq26smIk75bjBKg9XFLR3b_jaDYoAAkMWRa5GFOhMHGjGzfDtHIXOPjcqixB-a-y6lXgnZ94Tf7KEmBijTKVcbxtWvL5ZEx59OoSBmtmDAm8jZ9"]
2023-11-24 23:46:40.382326-0500 Tailored[9893:4209933] 10.17.0 - [FirebaseMessaging][I-FCM002010] The subscription operation failed due to an error getting the FCM token: Error Domain=com.google.fcm Code=505 "No APNS token specified before fetching FCM Token" UserInfo={NSLocalizedFailureReason=No APNS token specified before fetching FCM Token}.
`

i even get the meesaahe when using the node.js function or scheudleing thru firebase when hardcoding the fcm token observed here 
Message ID: 1700887822751310
whats this [AnyHashable("gcm.message_id"): 1700887822751310, AnyHashable("google.c.sender.id"): 808662265677, AnyHashable("google.c.fid"): csX_0W0UKUP6mVDFVqHtvd, AnyHashable("google.c.a.e"): 1, AnyHashable("body"): get the alert boys, AnyHashable("aps"): {
    alert =     {
        body = "get the alert boys";
        title = "testing fucntions on update";
    };
}]

**Comment by TalhaTZA** [comment]
I have been facing the same issue recently. The notifications were working a few days ago. Upon investigation, I found the getAPNSToken() method is returning null.

`FirebaseMessaging.instance.getAPNSToken()`

**Comment by dbspark7** [comment]
I too have the same problem.
This mainly occurs in the iPhone 12 series.

**Comment by TalhaTZA** [comment]
@dbspark7 were you able to find any solution? for me its happening in the iPhone SE 2nd Generation

**Comment by yunsanch** [comment]
The reason I believe this is a bug in firebase(for SwiftUI), is because currently I have a function triggering on update of specific documents, and it is working however the console on iPhone 11 and 13 shows this aps token not set error.https://github.com/firebase/flutterfire/assets/60577975/d32e0b25-1522-4c6b-94bb-3e1cec27330c

**Comment by darshankawar** [comment]
@yunsanch  @TalhaTZA thanks for the updates. I tried the plugin example running on device which gave me the apns token properly as below:

```
Example: Getting APNs token...
2023-11-28 16:30:30.373764+0530 Firebase Cloud Messaging Example[13489:179054] flutter: FlutterFire Messaging Example: Got APNs token: 66616B652D61706E732D746F6B656E2D666F722D73696D756C61746F72

```

In case on device issue, do you have the aps-environment entitlement along with push notifications capability, because these are required in order for firebase messaging to run on devices.

**Comment by TalhaTZA** [comment]
@darshankawar Upon investigation, I was able to find the issue. There are two things required to make sure APNS is retrieved, apart from steps in the documentation.

1. Make sure the aps-environment entitlement is set to development when testing locally and set to production before sending it to the test flight.
2. Add a delay before retrieving the APNS token; otherwise, it is null.

@yunsanch leaving the comment for you and others who are facing this issue.

**Comment by dbspark7** [comment]
I requested technical support from Apple stating that I could not receive the deviceToken.
But, they said they determined it should be resolved through the Firebase Messaging support channel.

**Comment by darshankawar** [comment]
Thanks for the update. I am unable to replicate the apnstoken null behavior as reported earlier, but based on the report, keeping it open for team's input.

**Comment by russellwheatley** [comment]
Messaging on apple requires the APNS token to be set. We receive the APNS token from this handler here: https://github.com/firebase/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/ios/Classes/FLTFirebaseMessagingPlugin.m#L398-L403

Until this is received, API such as `getToken()` (Firebase messaging token) will not work. We throw an exception if you try to call `getToken()` before the APNS token is set. 

@TalhaTZA - This advice is pretty much spot on for what is required to get it working:

> @darshankawar Upon investigation, I was able to find the issue. There are two things required to make sure APNS is retrieved, apart from steps in the documentation.
> 
> 1. Make sure the aps-environment entitlement is set to development when testing locally and set to production before sending it to the test flight.
> 2. Add a delay before retrieving the APNS token; otherwise, it is null.
> 
> @yunsanch leaving the comment for you and others who are facing this issue.
