### ISSUE TITLE
🐛 [firebase_messaging] Firebase notification received twice in android in background mode

### ISSUE THREAD

**Issue by GnuaAruht** [firebase/flutterfire#11945]
Notification receive twice in background mode.
I tried the code from firebase messaging sample code.

When `showFlutterNotifcation` is removed, notification is received one time but don't show headup notification.
What should I do?

```
@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  await setupFlutterNotifications();
  showFlutterNotification(message);
}
```

**Comment by Avijaygovinda** [comment]
for me also same issue, please respond if anyone have any solution

**Comment by darshankawar** [comment]
@GnuaAruht 
Along with above comment / solution, check [this](https://stackoverflow.com/a/69027270) and see if it helps to resolve the issue in your case.

**Comment by Avijaygovinda** [comment]
Along with above comment / solution, check [this](https://stackoverflow.com/a/69027270) and see if it helps to resolve the issue in your case.
