### ISSUE TITLE
🐛 [firebae_auth] custom claims is null on windows desktop

### ISSUE THREAD

**Issue by floyd-lewis** [firebase/flutterfire#11949]
## Bug report

**Describe the bug**
Custom claims was set for a user with a role using admin sdk in javascript. 

When logging into the app On Web and Android, when the user logs in the app gets the custom claim. On windows the claims is null.

 pubspec.yaml
  firebase_core: ^2.23.0
  cloud_firestore: ^4.13.2
  firebase_auth: ^4.14.1
  cloud_functions: ^4.5.5
  firebase_storage: ^11.3.1

Using google_sign_in_dartio for windows

**Comment by darshankawar** [comment]
@floyd-lewis Thanks for the report.
Can you elaborate on how are you setting the custom claims and then trying to retrieve it ? A code sample will also be helpful so that we can address it properly.

**Comment by floyd-lewis** [comment]
For retreival i modifies the code as below for it to work in flutter, Earlier I was using getIdTokenResult, which was returning a nulllfor claims. Please note that it only does not work for windows desktop

  String? tokenStr =
          await firebase_auth.FirebaseAuth.instance.currentUser!.getIdToken();

      Map<String, dynamic> decodedToken = JwtDecoder.decode(tokenStr!);
      var roleName = decodedToken['role'] ?? Role.LEARNER.name;

**Comment by floyd-lewis** [comment]
Old code  which did not work on windows desktop
firebase_auth.IdTokenResult? idTokenResult = await firebase_auth
          .FirebaseAuth.instance.currentUser
          ?.getIdTokenResult();

      var roleName = idTokenResult?.claims?['role'] ?? Role.LEARNER.name;

**Comment by darshankawar** [comment]
Thanks for the update. Upon verifying on windows machine, getting the same result as reported.

/cc @Lyokone

**Comment by Lyokone** [comment]
Opened an issue on the C++ repository for support: https://github.com/firebase/firebase-cpp-sdk/issues/1494

**Comment by TarekkMA** [comment]
Will close this in favor of #12684.
