### ISSUE TITLE
🐛 [  cloud_firestore: 4.13.2 and firebase_core: ^2.23.0] Incompatibilities, fixed using previous versions

### ISSUE THREAD

**Issue by gcoolen** [firebase/flutterfire#11947]
## Bug report

Probably incompatibility in Flutter between **cloud_firestore: ^4.13.2** and **firebase_core: ^2.23.0**
When doing a read from Firestore:
   
```
final data = (await collection_ref.get());
data.docs.forEach((element) {print(element.data());});
```

got error "`No interface method getBuffer()`" that led to other errors.
Response of the request showed `data` coming back as empty (while it's not).
Specifying the following in pubspec.yaml dependencies fixed this and response data is correct:
```
cloud_firestore: ^4.13.1
firebase_core: ^2.22.0
```

**Comment by darshankawar** [comment]
@gcoolen 
Please check by upgrading both plugin versions to the latest and greatest and confirm if you still get the same behavior or not.
