### ISSUE TITLE
🐛 [firebase_messaging] Customizing onBackgroundMessage default notification

### ISSUE THREAD

**Issue by abhinavsinghring** [firebase/flutterfire#11940]
## What feature would you like to see?

I'm creating an app which have different courses users can choose from and chosen course is stored in shared preference. 
When app is in foreground I'm using this code to check if data has this course or not then push notification. 
```
  FirebaseMessaging.onMessage.listen((message) async {
    debugPrint("Handling a foreground message: ${message.data}");
    SharedPreferences prefs = await SharedPreferences.getInstance();
    String? userCourseValue = prefs.getString('userCourse');
    if (userCourseValue!=null) {
      if(message.data['userCourse']==userCourseValue){
        AwesomeNotifications().createNotification(
          content: NotificationContent(
            id: 1, 
            channelKey: message.notification!.android!.channelId ?? 'basic',
            title: message.notification!.title,
            body: message.notification!.body,
            bigPicture: message.notification!.android!.imageUrl,
            notificationLayout: NotificationLayout.BigPicture
          )
        );   
      }
    }
  });
```
I want to do the same in background but it is showing the default as well as the one I have created (if conditions meet).

**Comment by huycozy** [comment]
Hi @abhinavsinghring 

>I want to do the same in background but it is showing the default as well as the one I have created (if conditions meet).

Could you be more specific? Do you mean the notification in background case is not changed after you updated the prefs data?

Please share a minimal and complete sample code along with a recorded video/screenshot will help to make this more clear. Thank you!

**Comment by abhinavsinghring** [comment]
@huycozy I think you don't understand. Let me explain it more simpler way.

So I have this app for students of different courses and students can select their course from listed courses. So when user selects any course it get updated to both users database in firestore as well as in shared preference.

Now I'm trying to setup notifications in my app to notify users about updates of their respective courses.
The behaviour I want that the notifications I send from FCM don't pushed to every user but only to those users with specific course which I'm specifying in data section of FCM with key as "userCourse" and value as whatever course I want to send notification to. 
For example, let's say I have two courses named "Class 10" and "Class 11" and User's of "Group A" have selected Class 10 and "Group B" have selected Class 11. Now I'm sending a notification from Firebase with with key as "userCourse" and value as "Class 10" and want that only Group A user's receive that notification. So to check that "userCourse" from FCM and "userSelectedCourse" from shared preference matches or not then popup a notification. 

Now like I told before that this behaviour is working as expected when app is in foreground. When broadcast message is received, it first checks the condition and then if user course match it shows notification and if doesn't match it won't show. 
Here is the code for the foreground one with condition:
```
FirebaseMessaging.onMessage.listen((message) async {
    debugPrint("Handling a foreground message: ${message.data}");
    SharedPreferences prefs = await SharedPreferences.getInstance();
    String? userCourseValue = prefs.getString('userCourse');
    if (userCourseValue!=null) {
      if(message.data['userCourse']==userCourseValue){
        AwesomeNotifications().createNotification(
          content: NotificationContent(
            id: 1, 
            channelKey: message.notification!.android!.channelId ?? 'basic',
            title: message.notification!.title,
            body: message.notification!.body,
            bigPicture: message.notification!.android!.imageUrl,
            notificationLayout: NotificationLayout.BigPicture
          )
        );   
      }
    }
  });
```

But when I'm setting this thing for the background or terminated state it doesn't working as expected and shows notification anyway. During background there are three conditions:
1. When I don't have any code to setup push notification like the one for foreground it still shows notification by default. (And I don't want this default behaviour and this will solve my problem)
```
FirebaseMessaging.onBackgroundMessage(_firebasePushHandler);
```
```
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message)async{
 
}
```

2. When I setup this code with condition for background it is showing the default one everytime and if condition is true it is showing two notification 

```
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message)async{
  debugPrint("Handling a background message: ${message.data}");
  SharedPreferences prefs = await SharedPreferences.getInstance();
  String? userCourseValue = prefs.getString('userCourse');
  print(message.data['userCourse']);
  print(userCourseValue);
  if(userCourseValue==message.data['userCourse']){
    AwesomeNotifications().createNotification(
          content: NotificationContent(
            id: 1, 
            channelKey: message.notification!.android!.channelId ?? 'basic',
            title: message.notification!.title,
            body: message.notification!.body,
            bigPicture: message.notification!.android!.imageUrl,
            notificationLayout: NotificationLayout.BigPicture
          )
        );   
  } 
}
```
This is data I'm sending from FCM
![image](https://github.com/firebase/flutterfire/assets/83336285/5cc808b4-7f1a-4029-9212-f7185c1159b8)

This is the screenshot when condition is true
![Screenshot_1700831526](https://github.com/firebase/flutterfire/assets/83336285/7404ebed-5147-4579-ba5f-00868249836a)
and this when condition is not true 
![Screenshot_1700831852](https://github.com/firebase/flutterfire/assets/83336285/a4004180-1e1f-474d-a548-4acafa3e8612)

3. When I use this code which is provided by `awesome_notification` plugin to create notification by `messages.data`, I get only one notifcation but everytime, no matter if condition is met or not. Here is the code: 
```
@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message)async{
  debugPrint("Handling a background message: ${message.data}");
  SharedPreferences prefs = await SharedPreferences.getInstance();
  String? userCourseValue = prefs.getString('userCourse');
  debugPrint(message.data['userCourse']);
  debugPrint(userCourseValue);
  if (userCourseValue!=null) {
    if(message.data['userCourse']==userCourseValue){
      AwesomeNotifications().createNotificationFromJsonData(message.data); 
    }
  }
}
```
I've used `awesome_notification` for demo purpose to show in more simpler way but I'll be not using this for my app as it is increasing app size by almost 1.5 to 2mb when I build apk splits with this in my `pubspec.yaml`. So If you can provide solution to this background behaviour guide me with `flutter_local_notification` plugin. 
I'm sharing whole `main.dart` code here:
<details>
  <summary>main.dart</summary>

```

// ignore_for_file: unused_field

import 'dart:async';
import 'package:awesome_notifications/awesome_notifications.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:get/get.dart';
import 'package:paperbook/Constants/color_constant.dart';
import 'package:paperbook/Services/Authentication/auth_repository.dart';
import 'package:paperbook/Theme/theme_share_prefs.dart';
import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'Services/Authentication/auth_page.dart';
import 'Theme/theme_file.dart';

@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message)async{
  debugPrint("Handling a background message: ${message.data}");
  SharedPreferences prefs = await SharedPreferences.getInstance();
  String? userCourseValue = prefs.getString('userCourse');
  debugPrint(message.data['userCourse']);
  debugPrint(userCourseValue);
  if (userCourseValue!=null) {
    if(message.data['userCourse']==userCourseValue){
      AwesomeNotifications().createNotification(
        content: NotificationContent(
          id: 2, 
          channelKey: message.notification!.android!.channelId ?? 'basic',
          title: message.notification!.title,
          body: message.notification!.body,
          bigPicture: message.notification!.android!.imageUrl,
          notificationLayout: NotificationLayout.BigPicture
        )
      ); 
    }
  }
}

Future<void> main() async {

  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp().then((value) => Get.put(AuthenticationRepository()));

  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

  FirebaseMessaging.onMessage.listen((message) async {
    debugPrint("Handling a foreground message: ${message.data}");
    SharedPreferences prefs = await SharedPreferences.getInstance();
    String? userCourseValue = prefs.getString('userCourse');
    if (userCourseValue!=null) {
      if(message.data['userCourse']==userCourseValue){
        AwesomeNotifications().createNotification(
          content: NotificationContent(
            id: 1, 
            channelKey: message.notification!.android!.channelId ?? 'basic',
            title: message.notification!.title,
            body: message.notification!.body,
            bigPicture: message.notification!.android!.imageUrl,
            notificationLayout: NotificationLayout.BigPicture
          )
        );   
      }
    }
  });

  AwesomeNotifications().initialize(
    null,
    [
      NotificationChannel(
        channelKey: 'updates',
        channelName: 'Course Updates',
        channelDescription: 'Receive Course updates notifications',
        defaultColor: primary,
        channelShowBadge: true,
        importance: NotificationImportance.Max,
        playSound: true,
        enableVibration: true
      ),
      NotificationChannel(
        channelKey: 'basic',
        channelName: 'Basic',
        channelDescription: 'Basic notifications',
        defaultColor: primary,
        channelShowBadge: true,
        importance: NotificationImportance.High,
        playSound: true,
        enableVibration: true
      )
    ]
  );

  AwesomeNotifications().isNotificationAllowed().then((isAllowed) {
    if (!isAllowed) {
      AwesomeNotifications().requestPermissionToSendNotifications();
    }
  });

  // Initialize ThemeNotifier and load the theme preference
  ThemeNotifier themeNotifier = ThemeNotifier();
  await themeNotifier.loadThemePreference();

  SystemChrome.setPreferredOrientations(
    [DeviceOrientation.portraitUp, DeviceOrientation.portraitDown]
  );

  runApp(
    ChangeNotifierProvider(
      create: (_)=> themeNotifier,
      child: const MyApp()
    )
  );

    // Register a callback to handle incoming intents
  // ReceiveSharingIntent.receiveStream().listen((intent) {
  //   if (intent.hasData) {
  //     final sharedText = intent.text;
  //     if (sharedText != null && sharedText.endsWith('.pdf')) {
  //       // Handle the PDF file here, e.g., open it in your PDF viewer activity.
  //     }
  //   }
  // });
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context){
      return GetMaterialApp(
        debugShowCheckedModeBanner: false,
        title: "Paperbook",
        darkTheme: AppTheme.darkTheme,
        theme: AppTheme.lightTheme,
        themeMode: Provider.of<ThemeNotifier>(context).currentThemeMode,
        home: const MainAuthPage(),
      );
  }
}

```

</details>

**Comment by Avijaygovinda** [comment]
i can just solve one thing, if the app in background mode and if you got mutliple notifications then you need to collect the data from RemoteMessage, and then show the notification. also restrict to send the notifcation object from backend

**Comment by abhinavsinghring** [comment]
@Avijaygovinda 

> i can just solve one thing,

I have only one problem to solve, i.e. Disable default notification which shows after receiving broadcast message in background and terminated state. 

> i can just solve one thing, if the app in background mode and if you got mutliple notifications then you need to collect the data from RemoteMessage, and then show the notification. also restrict to send the notifcation object from backend

Please share here so I can check if that solves my problem or not.

**Comment by Avijaygovinda** [comment]
check [this](https://stackoverflow.com/a/69027270) and see if it helps to resolve the issue in your case.

**Comment by abhinavsinghring** [comment]
sending data notification works but requires device tokens to send to. you can't send to everyone at once. Correct me if I'm wrong.

**Comment by huycozy** [comment]
@abhinavsinghring 
>When I use this code which is provided by awesome_notification plugin to create notification by messages.data, I get only one notifcation but everytime, no matter if condition is met or not.

Is there a mechanism to check duplicate data inside `awesome_notification` plugin? You can read it source to check this but I think we shouldn't go too far from the main issue.

Can you set a debug point at the check condition `message.data['userCourse']==userCourseValue` to see how many notifications are fired if it's true?

Please also check the output console to see if there are these logs (related issue https://github.com/firebase/flutterfire/issues/9964):

```console
FlutterJNI.loadLibrary called more than once
FlutterJNI.prefetchDefaultFontManager called more than once
```

**Comment by abhinavsinghring** [comment]
@huycozy 

> Can you set a debug point at the check condition message.data['userCourse']==userCourseValue to see how many notifications are fired if it's true?

If `message.data['userCourse']==userCourseValue` is `true`, two notifications are fired.

> Please also check the output console to see if there are these logs (related issue https://github.com/firebase/flutterfire/issues/9964):

```
FlutterJNI.loadLibrary called more than once
FlutterJNI.prefetchDefaultFontManager called more than once
````

I'm getting this in my console. I've been to #9964 before but didn't find anything.

When I remove `FirebaseMessaging.onBackgroundMessage(_firebasePushHandler);` from main.dart it won't show in logs and 
![image](https://github.com/firebase/flutterfire/assets/83336285/4cbf77df-0b62-40f0-b298-5b1d17bd7fa8)
this also removed but with `FirebaseMessaging.onBackgroundMessage(_firebasePushHandler);` it is showing.

**Comment by huycozy** [comment]
>I think notifications send via firebase console sends notification message and in background it is handled automatically

I think it is intentional behavior, please check https://github.com/firebase/flutterfire/issues/10137#issuecomment-1359065385. And looks like `FlutterJNI.loadLibrary called more than once` (https://github.com/firebase/flutterfire/issues/9964) is the issue under the hood. So I would suggest you follow that issue and leave there your comment about this case.
