### ISSUE TITLE
🐛 [Firebase_Messageing] onMessageOpenedApp not working on android

### ISSUE THREAD

**Issue by engrpatel21** [firebase/flutterfire#11959]
## Bug report
i have loaded up the exampled FCM example app that integrates flutter_local_notifications. When i send a notification to the android device in the foreground, i recieve the message. When i click on the notification nothing happens. the onMessageOpenedApp call back does not trigger. this behavior works on ios. i am using the very exact flutter fire project with one simple modifications which is this 

```dart 
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  // Set the background messaging handler early on, as a named top-level function
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
  FirebaseMessaging.onMessageOpenedApp.listen((RemoteMessage message) {
    print('A new onMessageOpenedApp event was published!');
    showFlutterNotification(message);
  });
  final message = await FirebaseMessaging.instance.getInitialMessage();
  if (message != null) {
    print('A new getInitialMessage event was published!');
    showFlutterNotification(message);
  }

  if (!kIsWeb) {
    await setupFlutterNotifications();
  }

  runApp(const MessagingExampleApp());
}
```

im printing the the call backs. in the example app when in ios physical device and i click on the notification, it navigates me to the message detail. on andaroid this call back does not fire. 

again i am using the exact flutter fire example app with the following andraoid manifest and gradle configs. 

the following is from android/build.gradle

```
buildscript {
    ext.kotlin_version = '1.8.22'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

plugins {
  // ...

  // Add the dependency for the Google services Gradle plugin
  id 'com.google.gms.google-services' version '4.4.0' apply false

}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
```

this will be from android/app/src/build.gradle 
```
plugins {
    id "com.android.application"
    id "kotlin-android"
    id "dev.flutter.flutter-gradle-plugin"
    id 'com.google.gms.google-services'
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

android {
    namespace "io.zyka.chef"
    compileSdkVersion flutter.compileSdkVersion
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "io.zyka.chef"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
        minSdkVersion 21
        targetSdkVersion 34
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation platform('com.google.firebase:firebase-bom:32.6.0')
    implementation 'com.google.firebase:firebase-analytics'
}
```
this next part is my android manifest

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <application
        android:label="chef"
        android:name="${applicationName}"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />

        <meta-data
            android:name="com.google.firebase.messaging.default_notification_channel_id"
            android:value="high_importance_channel" />
    </application>
</manifest>
```

### Steps to reproduce

load the example flutterfire firebase messaging app for android
register your app with fire base
run flutterfire configure to load firebase configs into the app
adjust the native code to enable firebase and flutter_local_notifications
use the send-message.js script in the example project to a notification to the android device
click on the android notification

### Expected behavior
when tapping on a notifiacation, the onMessageOpenedApp callback should fire to print in the console.

---

## Additional context
i am using a samsung galaxy s20 FE to test
my build configurations are given

**Comment by darshankawar** [comment]
Thanks for the detailed report @engrpatel21 
Can you check [this](https://github.com/firebase/flutterfire/issues/9211#issuecomment-1537651843) and see if it helps in your case or not ?

**Comment by engrpatel21** [comment]
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <application
        android:label="chef"
        android:name="${applicationName}"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
             <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK"/>
                <category android:name="android.intent.category.DEFAULT"/>
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />

        <meta-data
            android:name="com.google.firebase.messaging.default_notification_channel_id"
            android:value="high_importance_channel" />
    </application>
</manifest>
```

that is the new manifest

```js

admin.
  messaging().send({
    token,

    data: {
      chefId: '1',
      userId: '1',
      orderId: '1',
      userName: 'Paul',
      clickAction: 'OPEN_ORDER_DETAILS_FOR_USER',
      click_action: 'OPEN_ORDER_DETAILS_FOR_USER',
    },
    notification: {
      title: 'title',
      body: 'body',
    },
    android: {
      priority: 'high',
      notification: {
        sound: 'default',
        clickAction: 'FLUTTER_NOTIFICATION_CLICK',
      },

    },
    apns: {
      headers: {
        'apns-priority': '10',
      },

      payload: {
        aps: {
          category: 'ORDER_DETAILS',
          sound: 'zyka-alert.aiff',
        },
      },
    },

  ```
  
  that is how im sending the notification, however the callback is still not being triggered

**Comment by engrpatel21** [comment]
I get what you are saying. What im trying do is navigate to a specific page once the notification is tapped while the app is in any state. The onMessageOpen listener does get fired the way i want to in ios. While app is in foreground and i tap the notification, i do get navigated to the right page. How do i get this working. I had an implementation of this using awesome notifications on android, but that library wasnt build for ios so i had to switch to local notifications. But in this case i dont think its the third party lib. 

Would i have to implement actions for this behavior, it it works absolutely fine on ios.

**Comment by darshankawar** [comment]
Thanks for the update @engrpatel21 
I looked at the code again in the plugin example and use it to replicate by sending a push notification from admin sdk itself and like the way you have provided, with which, I do seem to get same behavior as reported, ie, the listener isn't getting triggered.
I am wondering the way local notifications are being created when we get a push notification from the plugin could have something to do with the behavior.
I guess since the `onMessageOpenedApp` method isn't being called because the notifications aren't created by the plugin itself but coming from `flutter_local_notifications` .
Maybe we can you try to pass a callback function while initializing `flutter_local_notifications` like below, check the payload and then redirect ?

https://github.com/MaikuB/flutter_local_notifications/blob/ca71c96ba2a245175b44471e2e41e4958d480876/flutter_local_notifications/example/lib/main.dart#L172

Based on the report, I'll keep this issue open for team's input on correct behavior for the method to be called in foreground specially for Android.

**Comment by alexbejann** [comment]
> Thanks for the update @engrpatel21 I looked at the code again in the plugin example and use it to replicate by sending a push notification from admin sdk itself and like the way you have provided, with which, I do seem to get same behavior as reported, ie, the listener isn't getting triggered. I am wondering the way local notifications are being created when we get a push notification from the plugin could have something to do with the behavior. I guess since the `onMessageOpenedApp` method isn't being called because the notifications aren't created by the plugin itself but coming from `flutter_local_notifications` . Maybe we can you try to pass a callback function while initializing `flutter_local_notifications` like below, check the payload and then redirect ?
> 
> https://github.com/MaikuB/flutter_local_notifications/blob/ca71c96ba2a245175b44471e2e41e4958d480876/flutter_local_notifications/example/lib/main.dart#L172
> 
> Based on the report, I'll keep this issue open for team's input on correct behavior for the method to be called in foreground specially for Android.

Hi @darshankawar, we have a similar implementation as you specified in your message. Everything works fine for iOS and Android 13, but below that, we get the notification but we are not redirected to the desired page (but the app is still opened) as the "onDidReceiveBackgroundNotificationResponse" callback is not triggered when the application is killed (in the background is working perfectly. Do you might have any idea what we could miss from this setup?

**Comment by engrpatel21** [comment]
> Hi @darshankawar, we have a similar implementation as you specified in your message. Everything works fine for iOS and Android 13, but below that, we get the notification but we are not redirected to the desired page (but the app is still opened) as the "onDidReceiveBackgroundNotificationResponse" callback is not triggered when the application is killed (in the background is working perfectly. Do you might have any idea what we could miss from this setup?

i am on a samsung s20 FE edition running on android 13 physical device, and it is not working on there

**Comment by russellwheatley** [comment]
I just tested, using the notification generated by Firebase Messaging SDK (i.e. `notification` in payload when you send via admin SDK), it opened the app. If you're using another package to generate the notification (i.e. `flutter_local_notifications `), it won't work.
