### ISSUE TITLE
🐛 [firebase_messaging_web] getToken throws Subscription failed - no active Service Worker

### ISSUE THREAD

**Issue by adar2378** [firebase/flutterfire#11954]
## Bug report

**Describe the bug**
I have noticed that when calling getToken for the first time on web in chrome browser it always returns `Subscription failed - no active Service Worker`. After that, calling `getToken` works expectedly.

### Steps to reproduce

1. `flutter create fcm_test --platforms web`
2. `flutterfire configure` to configure firebase
3. Copy paste `index.html` and `firebase-messaging-sw.js` from https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example/web
4. Update credentials in `firebase-messaging-sw.js`
5. Add a button that will request permission and getToken in main.dart
6. Run the project using `flutter run -d chrome`
7. After pressing button it shows permission request pop up, accept it then getToken throws `AbortError: Failed to execute 'subscribe' on 'PushManager': Subscription failed - no active Service Worker`
### Expected behavior

It should not show `AbortError: Failed to execute 'subscribe' on 'PushManager': Subscription failed - no active Service Worker` error when `getToken` is called.

### Sample project

`main.dart`
```dart
import 'package:fcm_test/firebase_options.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: ElevatedButton(
            onPressed: () {
              getToken();
            },
            child: const Text('Request Token'),
          ),
        ),
      ),
    );
  }

  Future getToken({int retry = 2}) async {
    print('retry: $retry');
    if (retry == 0) {
      return;
    }
    final supprted = await FirebaseMessaging.instance.isSupported();
    print('supported: $supprted');
    if (supprted) {
      bool permissionGiven = false;
      final settings =
          await FirebaseMessaging.instance.getNotificationSettings();
      if (settings.authorizationStatus == AuthorizationStatus.authorized) {
        permissionGiven = true;
      }
      if (!permissionGiven) {
        final permissionStatus =
            await FirebaseMessaging.instance.requestPermission();
        if (permissionStatus.authorizationStatus ==
            AuthorizationStatus.authorized) {
          permissionGiven = true;
        }
      }

      if (permissionGiven) {
        try {
          final token = await FirebaseMessaging.instance.getToken(
              vapidKey:
                  vapidKey);
          print('Token: $token');
        } catch (e) {
          print(e);
          await Future.delayed(const Duration(milliseconds: 500));
          await getToken(retry: retry - 1);
        }
      }
    }
  }
}

```
---

## Additional context

![bug_fcm](https://github.com/firebase/flutterfire/assets/8059258/5d5a72c9-9557-418e-bc8d-fb48c0a6c30b)

Related issue: https://github.com/firebase/firebase-js-sdk/issues/6013

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.0, on macOS 13.5.2 22G91 darwin-arm64, locale
    en-BD)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.84.2)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 3.2.0
Flutter SDK 3.16.0
fcm_test 0.1.0

dependencies:
- firebase_core 2.23.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 14.7.5 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math web sky_engine]

dev dependencies:
- flutter_lints 2.0.3 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math async boolean_selector characters collection material_color_utilities meta source_span stream_channel string_scanner term_glyph web]

transitive dependencies:
- _flutterfire_internals 1.3.13 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- collection 1.18.0
- fake_async 1.3.1 [clock collection]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.8.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 4.5.14 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.5.14 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math web]
- js 0.6.7 [meta]
- lints 2.1.1
- matcher 0.12.16 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.5.0 [collection]
- meta 1.10.0
- path 1.8.3
- plugin_platform_interface 2.1.7 [meta]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- vector_math 2.1.4
- web 0.3.0```

</details>

---

**Comment by adar2378** [comment]
similar issue https://github.com/firebase/flutterfire/issues/11798

**Comment by adar2378** [comment]
Seems like some race condition when accessing service worker for the first time and requesting a token

**Comment by darshankawar** [comment]
Thanks for the report @adar2378 
I think it may be more related to underlying sdk rather than a plugin issue considering the fact that it gives error upon first try but runs properly in subsequent tries. Can you try to segregate this issue just using firebase-js sdk and check if it replicates using it ? That way we'll know that the error could be at js side itself or with thin wrapper of flutterfire that is used to send and receive data through dart.

**Comment by RomanIvn** [comment]
Even after deleting (With try\catch because deletion of non-existing token can cause an error),  the 'firebase-messaging-sw' worker is not installed on the first launch of an app, only after a refresh.  

I used the documentation's way to add it:

`
<!DOCTYPE html>
<html>

<head>
  
  <base href="$FLUTTER_BASE_HREF">

  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="A new Flutter project.">

  
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="frontend">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  
  <link rel="icon" type="image/png" href="favicon.png" />

  <title>frontend</title>
  <link rel="manifest" href="manifest.json">

  <script>
    // The value below is injected by flutter build, do not touch.
    const serviceWorkerVersion = null;
  </script>
  
  <script src="flutter.js" defer></script>

  <script src="https://www.gstatic.com/firebasejs/10.7.0/firebase-analytics.js"></script>
  <script src="https://www.gstatic.com/firebasejs/10.7.0/firebase-firestore.js"></script>
</head>

<body>
  <script>
    window.addEventListener('load', function (ev) {

      navigator.serviceWorker.register('/firebase-messaging-sw.js');

      navigator.serviceWorker.ready.then(function (serviceWorkerRegistration) {
        _flutter.loader.loadEntrypoint({
          serviceWorker: {
            serviceWorkerVersion: serviceWorkerVersion,
          },
          onEntrypointLoaded: function (engineInitializer) {
            engineInitializer.initializeEngine().then(function (appRunner) {
              appRunner.runApp();
            });
          }
        });

      });
      // Download main.dart.js

    });
  </script>
</body>

</html>
`

Replacing the entire HTML with the one firebase have in their example is an ugly overkill that I'm not going to do.

**Comment by darshankawar** [comment]
@adar2378 
Does [this](https://github.com/firebase/flutterfire/issues/11798#issuecomment-1793849624) help to resolve ?

**Comment by adar2378** [comment]
@darshankawar No, I have always used await. But does not resolve it.

**Comment by adar2378** [comment]
@darshankawar I have tried using only firebase sdk with a basic html+javascript setup, and there were no issues.

index.html
```html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8" />
    <title>example</title>

</head>

<body>
    <script type="module">
        import getFcmToken from './main.js';

        function requestPermission() {
            console.log('Requesting permission...');
            // It says Notification is not defined
            console.log(Notification);
            Notification.requestPermission().then((permission) => {
                if (permission === 'granted') {
                    console.log('Notification permission granted.');
                    getFcmToken();
                } else {
                    console.log('Unable to get permission to notify.');
                }
            });
        }
        var serviceWorkerVersion = null;
        var scriptLoaded = false;
        function loadApp() {
            if (scriptLoaded) {
                return;
            }
            scriptLoaded = true;
            // apend a paragram to the body to display the version number
            var versionEl = document.createElement('p');
            versionEl.innerText = 'Loaded App';
            document.body.appendChild(versionEl);
        }

        if ('serviceWorker' in navigator) {
            // Service workers are supported. Use them.
            window.addEventListener('load', function () {
                // Register Firebase Messaging service worker.
                navigator.serviceWorker.register('firebase-messaging-sw.js').then(
                    function (registration) {

                        console.log('ServiceWorker registration successful with scope: ', registration.scope);

                        requestPermission();

                    },
                    function (err) {
                        console.log('ServiceWorker registration failed: ', err);
                    }

                );
                loadApp();
                setTimeout(() => {
                    if (!scriptLoaded) {
                        console.warn(
                            'Failed to load app from service worker. Falling back to plain <script> tag.'
                        );
                        loadApp();
                    }
                }, 4000);
            });
        } else {
            // Service workers not supported. Just drop the <script> tag.
            loadApp();
        }
    </script>
</body>

</html>
```

main.js
```js
import { initializeApp } from 'https://www.gstatic.com/firebasejs/9.22.0/firebase-app.js'
import { getMessaging, getToken } from 'https://www.gstatic.com/firebasejs/9.22.0/firebase-messaging.js'

export default function getFcmToken() {
    var firebaseConfig = {
        apiKey: 'your apiKey',
       // rest of the config
    };

    const app = initializeApp(firebaseConfig);

    // Initialize Firebase Messaging
    const messaging = getMessaging();
    getToken(messaging, {
        vapidKey: '<Your vapid key>'
    }).then((currentToken) => {
        if (currentToken) {
            console.log(currentToken);
        } else {
            // Show permission request UI
            console.log('No registration token available. Request permission to generate one.');
        }
    }
    ).catch((err) => {
        console.log('An error occurred while retrieving token. ', err);
    }
    );
}

```

firebase-messaging-sw.js
```js
importScripts('https://www.gstatic.com/firebasejs/9.22.0/firebase-app-compat.js')
importScripts('https://www.gstatic.com/firebasejs/9.22.0/firebase-messaging-compat.js')

firebase.initializeApp({
    // firebase config
});

var messaging = firebase.messaging();

messaging.onBackgroundMessage(function (payload) {
    console.log('[firebase-messaging-sw.js] Received background message ', payload);
    // Customize notification here
    const notificationTitle = payload.notification.title;
    const notificationOptions = {
        body: payload.notification.body,
        icon: payload.notification.icon,
        image: payload.notification.image,
        click_action: payload.notification.click_action
    };

    self.registration.showNotification(notificationTitle,
        notificationOptions);
}
);

```

Received token without any error like we get in flutter
![image](https://github.com/firebase/flutterfire/assets/8059258/b4290062-962b-4b02-95b9-9d1c39865a01)

**Comment by darshankawar** [comment]
Thanks for the update. I was able to replicate the originally reported behavior https://github.com/firebase/flutterfire/issues/11954#issue-2014198524.

A similar [issue](https://github.com/firebase/flutterfire/issues/11798) was raised and closed based on https://github.com/firebase/flutterfire/issues/11798#issuecomment-1793849624 but it seems there are new reports claiming the solution doesn't resolve the issue.

**Comment by adar2378** [comment]
@darshankawar Thanks, looking forward to the fix.

**Comment by Lyokone** [comment]
Thanks for the detailed reproduction example, I was able to reproduce this. I'll see how it can be fixed.
