### ISSUE TITLE
🐛 [PLUGIN_NAME_HERE] firebase_core

### ISSUE THREAD

**Issue by floyd-lewis** [firebase/flutterfire#11956]
## Bug report
This problem appears to be after the windows desktop integration.
I can only get the build for windows desktop  to work in debug mode
When I run 
flutter  build windows --release
i get a tonne of errors as...
[releaseBuild.txt](https://github.com/firebase/flutterfire/files/13489712/releaseBuild.txt)
When I run 
flutter  build windows --debug
i get errors but the build results in an exe as ...
[debugBuild.txt](https://github.com/firebase/flutterfire/files/13490064/debugBuild.txt)

pubspec.yaml contains

###################################################
  firebase_core: ^2.23.0
  cloud_firestore: ^4.13.2
  firebase_auth: ^4.14.1
  cloud_functions: ^4.5.5
  firebase_storage: ^11.3.1
#####################################################
  google_sign_in: ^6.1.5
  google_sign_in_dartio: ^0.2.2+1
  google_sign_in_platform_interface: ^2.4.2
  extension_google_sign_in_as_googleapis_auth: ^2.0.11
  flutter_signin_button: ^2.0.0

**Comment by floyd-lewis** [comment]
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.19045.3693], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.8.1)   
[√] Android Studio (version 2022.3)
[√] Connected device (3 available)
[√] Network resources

**Comment by darshankawar** [comment]
@floyd-lewis 
It seems you are hitting https://github.com/firebase/flutterfire/issues/11919 in which you can follow-up for further updates.
Closing this as a duplicate.
Mean time, you can also check below similar issues and see if they help to resolve the errors you are getting in release mode:

https://github.com/firebase/flutterfire/issues/11626
https://github.com/firebase/flutterfire/issues/10931
