### ISSUE TITLE
🐛 [firebase_database] Add localhost remap for Android

### ISSUE THREAD

**Issue by jonbhanson** [firebase/flutterfire#11963]
## Request:
Please add the ability to pass `localhost` or `127.0.0.1` to the [`useDatabaseEmulator`](https://github.com/firebase/flutterfire/blob/1670377e3a17aecff6a93a8db8a17c8095a85c88/packages/firebase_database/firebase_database/lib/src/firebase_database.dart#L78C18-L78C18) method and have it automatically remap while using an Android emulator to `10.0.2.2`.  

## Background:
In both Firebase Function's [`useFunctionsEmulator`](https://github.com/firebase/flutterfire/blob/1670377e3a17aecff6a93a8db8a17c8095a85c88/packages/cloud_functions/cloud_functions/lib/src/firebase_functions.dart#L103) and Firebase Firestore's [`useFirestoreEmulator`](https://github.com/firebase/flutterfire/blob/1670377e3a17aecff6a93a8db8a17c8095a85c88/packages/cloud_firestore/cloud_firestore/lib/src/firestore.dart#L124) it is possible to pass `localhost` or `127.0.0.1` while using an Android emulator as those methods map the host to `10.0.2.2`.  However, Firebase Database's [`useDatabaseEmulator`](https://github.com/firebase/flutterfire/blob/1670377e3a17aecff6a93a8db8a17c8095a85c88/packages/firebase_database/firebase_database/lib/src/firebase_database.dart#L78C18-L78C18) does not remap `localhost`, which can cause confusion when a user such as myself expects the package to remap.

**Comment by Lyokone** [comment]
Closing this since it was done in #11976
