### ISSUE TITLE
🐛 [firebase_messaging] Push notifications on Mac Sonoma are delayed until a network change 

### ISSUE THREAD

**Issue by daniel-kane-everbridge-com** [firebase/flutterfire#11965]
## Bug report

Messages sent through Firebase cloud messaging are not received until there is a network change (Connect/Disconnect with VPN, change wifi network etc). After the change the messages come through. 

This is only reproducible on Sonoma, other OS versions are coming through immediately. 

### Steps to reproduce

Run the example firebase_messaging on a Mac with Sonoma. 
Send new message from the firebase console.
Nothing is received.
Connect to VPN.
Message is received. 
Send another message.
Nothing is received.
Disconnect from VPN.
Message is received. 

### Expected behavior

Message is received < 1min. 

### Sample project

Use the example project in firebase_messaging

**Comment by danagbemava-nc** [comment]
Hi @daniel-kane-everbridge-com, how are you sending the messages? 

I just sent a few messages from the admin console and using the plugin example app, I get the messages instantly. 

Is this is release mode or debug mode? 

I tested on macOS Sonoma (14.1.1)

**Comment by daniel-kane-everbridge-com** [comment]
I'm running the example app in debug mode. We have the same issue in our App in debug or release. 

After your comment, I tried the example App and it started working, went to our App and that was suddenly working too. However after restarting my Mac both the example App and our App have stopped working. So a bit confusing. 

I have other engineers in my team and customers using our App with the same issue.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.1, on macOS 14.1.2 23B92 darwin-arm64, locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.84.0)
[✓] Connected device (2 available)
[✓] Network resources

**Comment by danagbemava-nc** [comment]
Hi @daniel-kane-everbridge-com, can you check if your messages are bring throttled? 


```
To check the status of your push notification, please follow the steps below.

Open the Console app on your Mac
Select your Mac on the left hand side
Filter messages by typing in your Bundle ID (e.g. The Firebase Messaging example app bundle ID is 'io.flutter.plugins.firebase.messaging') into the search box and pressing enter.
Press the clear button to clean the history.
Now send the message to your device
Select all the rows on the logs & copy them, Cmd + C (not available on right-click menu)
```

**Comment by mukhtharcm** [comment]
Nothing is shown as log when I do that

**Comment by daniel-kane-everbridge-com** [comment]
Same situation this morning, notification we're coming fine, then I restarted the Mac and they stopped again unless I toggled the network connection.

Logs are empty until I toggle the VPN connection. Then this comes through 

> default 09:55:15.599013+1300    usernoted   Received push from topic com.everbridge.enterprise
> default 09:55:15.599042+1300    usernoted   Received push for com.everbridge.enterprise
> default 09:55:15.711827+1300    NotificationCenter  [com.apple.private.nc.dnd:94315971-416F-4BA1-9EE1-6D33ABE073A6] Resolving behavior for event, details=<DNDMutableClientEventDetails: 0x6000029d9860; identifier: '8969E27A-8277-47D3-8837-37052E9BD591'; bundleIdentifier:: com.everbridge.enterprise; type: Default; urgency: Default; sender: (null); threadIdentifier: (null); filterCritera: (null); notifyAnyway: 0; behavior: Default>
> default 09:55:15.712786+1300    donotdisturbd   Event was resolved: resolution=<DNDSEventBehaviorResolution: 0x146f32aa0; UUID: EEA56886-XXXX; date: 2023-12-04 20:55:15 +0000; eventBehavior: <DNDClientEventBehavior: 0x146f24a10; eventDetails: <DNDClientEventDetails: 0x146f29cc0; identifier: '8969E27A-8277-47D3-8837-37052E9BD591'; bundleIdentifier:: com.everbridge.enterprise; type: Default; urgency: Default; sender: (null); threadIdentifier: (null); filterCritera: (null); notifyAnyway: 0; behavior: Default>; interruptionSuppression: none; resolutionReason: disabled; activeModeUUID: (null)>; clientIdentifier: '[com.apple.nc](http://com.apple.nc/).donotdisturb.user-toggles.preload'; outcome: allowed; reason: disabled>
> default 09:55:15.713125+1300    NotificationCenter  [com.apple.private.nc.dnd:94315971-416F-4BA1-9EE1-6D33ABE073A6] Resolved event, details=<DNDMutableClientEventDetails: 0x6000029d9860; identifier: '8969E27A-8277-47D3-8837-37052E9BD591'; bundleIdentifier:: com.everbridge.enterprise; type: Default; urgency: Default; sender: (null); threadIdentifier: (null); filterCritera: (null); notifyAnyway: 0; behavior: Default> behavior=<DNDClientEventBehavior: 0x600000410cc0; eventDetails: <DNDClientEventDetails: 0x6000029d9590; identifier: '8969E27A-8277-47D3-8837-37052E9BD591'; bundleIdentifier:: com.everbridge.enterprise; type: Default; urgency: Default; sender: (null); threadIdentifier: (null); filterCritera: (null); notifyAnyway: 0; behavior: Default>; interruptionSuppression: none; resolutionReason: disabled; activeModeUUID: (null)>
> default 09:55:15.713164+1300    NotificationCenter  Resolved interruption suppression for com.everbridge.enterprise as none
> default 09:55:15.713468+1300    NotificationCenter  [com.everbridge.enterprise:98BF651E] displaying as banner
> default 09:55:15.713556+1300    NotificationCenter  Playing notification sound {  } for com.everbridge.enterprise
> default 09:55:15.729552+1300    NotificationCenter  [com.everbridge.enterprise:98BF651E] updating existing notification with content from 98BF651E

We also just got a report of the same issue on Mac OS Monterey 12.7.1 but haven't looked into it yet.

**Comment by danagbemava-nc** [comment]
Hi @daniel-kane-everbridge-com, what VPN are you using? Could the VPN be blocking the traffic?

**Comment by mukhtharcm** [comment]
it it's helpful, this issue exists with and without vpn.
I mean, not receiving

**Comment by daniel-kane-everbridge-com** [comment]
It isn't related to the VPN. If i change my wifi network the same thing happens.

**Comment by mukhtharcm** [comment]
btw, is there any way to receive push notifications while we're debugging?

**Comment by danagbemava-nc** [comment]
You should be able to receive the notifications in debug mode. The plugin should work regardless of the mode you're in

**Comment by daniel-kane-everbridge-com** [comment]
We've raised an issue with firebase directly, I will update this as when I get more information from them.
