### ISSUE TITLE
🐛 [firebase_messaging] In Flutter web adding a custom background notification show two notifications

### ISSUE THREAD

**Issue by amrgetment** [firebase/flutterfire#11985]
## Bug report

**Describe the bug**
I want to show a custom background notification on web but if I added in my `firebase-messaging-sw.js` an override to `messaging.onBackgroundMessage` I get two notifications, the custom notification and the default notification

### Steps to reproduce

1. Follow flutter messaging tutorial to make integrate Flutter and Firebase messaging
2. Go to the background
3. Send notification from Firebase
4. Add a custom icon image to the notification and send again
5. Override onBackgroundMessage in firebase-messaging-sw.js and send a notification again

### Expected behavior

1- Sending a notification with image will show the notification with the custom image
2- Override onBackgroundMessage in javascript shows the custom image as expected but not showing the default notification with chrome icon

---

## Additional context
![image](https://github.com/firebase/flutterfire/assets/149420647/6ce81c89-1e38-4dc9-9816-0d27a25d445c)

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.16.3, on macOS 14.1 23B74 darwin-x64, locale en-EG)
    • Flutter version 3.16.3 on channel stable at /Users/apple/.pvotal/flutter
    • Upstream repository ssh://git@github.com/flutter/flutter.git
    • Framework revision b0366e0a3f (30 hours ago), 2023-12-05 19:46:39 -0800
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Community Edition (version 2023.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.10248

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 119.0.6045.199

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

</details>

---

**Comment by amrgetment** [comment]
if I override the messaging on my firebase service js (firebase-messaging-sw.js) file it show the default notification and the custom notification


firebase-messaging-sw.js
```
// Necessary to receive background messages:
const messaging = firebase.messaging();

// Optional:
messaging.onBackgroundMessage((payload) => {
    console.log("onBackgroundMessage", payload);

    const { title, body, image } = payload.notification ?? {};
    console.log("onBackgroundMessage title", title);
    console.log("onBackgroundMessage body", body);
    console.log("onBackgroundMessage image", image);

    if (!title) {
        return;
    }
    console.log("onBackgroundMessage Make sure macOS allow chrome to show notification from macOS settings/notifications/chrome");

    self.registration.showNotification(title, {
        body,
        icon: image || '/icons/Icon-192.png',
    });
});
```

**Comment by amrgetment** [comment]
@darshankawar I don't use javascript or postman
I only use the firebase console
![image](https://github.com/firebase/flutterfire/assets/149420647/aae3259b-6be8-401f-90aa-702f509451e8)

**Comment by darshankawar** [comment]
> // Optional:
> messaging.onBackgroun

@amrgetment I think the optional part you are implementing in the worker is triggering the duplicate notif. Sending a notification with title/body displays the notification automatically and flutter_location_notification to display the notification and hence it could be the reason as why you are seeing two notifications.

**Comment by amrgetment** [comment]
@darshankawar I use flutter_local_notifications for Android, iOS and in my testing, I disabled it
Notifications for web work by default If I added the Firebase messaging

```
  await Firebase.initializeApp(options: flavor.firebaseOptions);
  final FirebaseMessaging firebaseMessaging = FirebaseMessaging.instance;
```
I tried to override the default behaviour but it didn’t work for me
`  FirebaseMessaging.onBackgroundMessage((RemoteMessage message) async => print);
`

I want either disable default onBackgroundMessage and use javascript by
`FirebaseMessaging.setDefaultBackgroundMessage(javascriptOnly or none);`

or customizing the default behaviour notification
`FirebaseMessaging.setBackgroundMessageOptions(image: image url or image asset);`

**Comment by darshankawar** [comment]
> are you able to change the background notification icon in Flutter web by adding an image url?

No, I remember trying the same for android which works, but haven't tried on web yet.

I'll keep the issue open for team's input on expected behavior whether the app should show two notifications after adding custom background notification on web.

/cc @Lyokone

**Comment by russellwheatley** [comment]
Firebase messaging will present a notification at the level of the Firebase web JS SDK if you send a notification. You might think about using the nodejs Firebase admin SDK to send data-only messages (silent messages with no notification) which will allow you to use your custom handler `firebase-messaging-sw.js` to present notifications. Here is an example script you could use:

```js
const admin = require('firebase-admin');
// Get service account key from firebase console
const serviceAccount = require('../ff-e2e-service.json');
admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
});
const token = 'TOKEN';
admin
.messaging()
.send(
  {
    token: token,
    data: {
      something:'test',
    },
    android: {
      // Required for background/terminated app state messages on Android
      priority: 'high',
    },
    apns: {
      payload: {
        aps: {
          // Required for background/terminated app state messages on iOS
          contentAvailable: true,
        }
      },
    },
  },
  
)
.then((res) => {
  if (res.failureCount) {
    console.log('Failed', res.results[0].error);
  } else {
    console.log('Success');
  }
})
```

Other than that, there isn't much we can do to block the default notification if you're sending one via the Firebase console.

**Comment by amrgetment** [comment]
@russellwheatley Thanks, I got it, I have to use Nodejs Firebase admin SDK to send data-only messages
I think there should be a comment regarding this behaviour in the following file
https://github.com/firebase/flutterfire/blob/52c53f5c470aeca32e652cb0d477c5fc2bba7812/packages/firebase_messaging/firebase_messaging/example/web/firebase-messaging-sw.js#L19
