### ISSUE TITLE
[firebase_core] Link for "Getting Started" section on README should be updated

### ISSUE THREAD

**Issue by FMorschel** [firebase/flutterfire#11995]
Link for "Getting Started" section on README should be updated. 

When we open the link, it tells us to go [here](https://firebase.google.com/docs/flutter/setup?platform=ios)

**Comment by danagbemava-nc** [comment]
Hi @FMorschel, which plugin(s) are you referring to?

And what should the link be updated to?

**Comment by FMorschel** [comment]
Sorry! I meant firebase_core, the getting started link should be updated to the one I posted here on the issue description. 

But I did see this happen on more than one occasion some days ago in another project. 

Maybe eventually review all the readmes links?

**Comment by ashwinair** [comment]
Hi @danagbemava-nc, can I work on this issue?

> Maybe eventually review all the readmes links?

So far, I've identified this issue in the READMEs of these packages:

- firebase_core
- [firebase_dynamic_links](https://github.com/firebase/flutterfire/tree/master/packages/firebase_dynamic_links/firebase_dynamic_links)
-  [cloud_firestore](https://github.com/firebase/flutterfire/tree/master/packages/cloud_firestore/cloud_firestore)
- [cloud_functions](https://github.com/firebase/flutterfire/tree/master/packages/cloud_functions/cloud_functions)


will inspect more...

**Comment by danagbemava-nc** [comment]
@ashwinair, feel free. PRs are always welcome. Make sure to read the contributing guide first
