### ISSUE TITLE
🐛 [firebase_messaging] Firefox Mobile stops the app on Notification permission

### ISSUE THREAD

**Issue by amorenew** [firebase/flutterfire#11996]
## Bug report

**Describe the bug**
I got the following error on **Firefox Android Mobile** version 120
`The Notification permission may only be requested from inside a short running user-generated event handler.`
after searching I found that requesting permission to show notification should be by a handler which is a button click otherwise it will be blocked as the default behavior for Firefox Mobile, and Safari Mobile.

### Steps to reproduce

1. Add Firebase messaging to Flutter web
2. Open your Flutter website on Firefox Android Mobile
3. You will get the following error `The Notification permission may only be requested from inside a short running user-generated event handler` and the website will not work

### Expected behavior

It looks like auto request notification should be done manually on Firefox and Safari mobile.

---

## Additional context

https://stackoverflow.com/questions/61475486/notification-requestpermission-throwing-error-on-mozilla

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.16.3, on macOS 14.1 23B74 darwin-x64, locale
    en-EG)
    • Flutter version 3.16.3 on channel stable at /Users/apple/.pvotal/flutter
    • Upstream repository ssh://git@github.com/flutter/flutter.git
    • Framework revision b0366e0a3f (2 days ago), 2023-12-05 19:46:39 -0800
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Community Edition (version 2023.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.10248

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 119.0.6045.199

[✓] Network resources
    • All expected network resources are available.

• No issues found!```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by amorenew** [comment]
And I think other browsers will do the same restricting of auto-request notification permission 
https://blog.mozilla.org/futurereleases/2019/11/04/restricting-notification-permission-prompts-in-firefox/

**Comment by amrgetment** [comment]
@darshankawar Firefox is latest on Desktop v120, and Android Firefox is latest v120

it works fine on Firefox Desktop but when I went to Private mode it disabled  the service worker loading and the it blocked the permission too

Firebase seems to be blocked too even without Flutter web but at least we could make a workaround
https://bugzilla.mozilla.org/show_bug.cgi?id=1771783

```
12:52:50.918 No Service worker in navigator example.web.app:292:17
12:52:50.919 Exception while loading service worker: Error: Service Worker API unavailable.
    loadServiceWorker https://example.web.app/flutter.js:130
    loadEntrypoint https://example.web.app/flutter.js:360
    <anonymous> https://example.web.app/:270
flutter.js:362:17
12:52:50.919 Injecting <script> tag. Using callback. flutter.js:298:19
12:52:52.554 unreachable code after return statement
main.dart.js:12525:1
12:52:52.554 unreachable code after return statement
main.dart.js:91745:1
12:52:52.742 Flutter Web Bootstrap: Programmatic. main.dart.js:10012:28
12:52:55.931 Got object store box in database app_box. main.dart.js:35367:78
12:52:55.941 Initializing Firebase firebase_core line 61071 > injectedScript:2:17
12:52:55.945 Initializing Firebase firebase_firestore line 61071 > injectedScript:2:17
12:52:55.946 Initializing Firebase firebase_auth line 61071 > injectedScript:2:17
12:52:55.949 Initializing Firebase firebase_messaging line 61071 > injectedScript:2:17
12:52:56.040 Firebase is being shimmed by Firefox. See https://bugzilla.mozilla.org/show_bug.cgi?id=1771783 for details. sandbox eval code:1:9
12:52:56.481
Uncaught : [firebase_messaging/permission-blocked] Messaging: The notification permission was not granted and blocked instead. . main.dart.js:5547:19
12:53:08.959
Unknown property ‘-moz-border-radius’.  Declaration dropped. example.web.app:1:468
12:53:08.960 Expected media feature name but found ‘-ms-high-contrast’. example.web.app:1:1403
12:53:08.961
Unknown property ‘-moz-border-radius’.  Declaration dropped. example.web.app:1:6929```

**Comment by amrgetment** [comment]
I think if someone used a notification blocker it would make the same issue 🤔🤓

**Comment by amorenew** [comment]
Firefox is the latest on Desktop v120, and Android Firefox is the latest v120

**Comment by amorenew** [comment]
@darshankawar should I open a new issue why do js error exceptions stop the Flutter web app and in which repo Dart or Flutter?

**Comment by darshankawar** [comment]
@amorenew 


> why do js error exceptions stop the Flutter web app

Is there a way for you to check if the same behavior / error occurs just using firebase-js sdk ? ie native web ?

**Comment by amorenew** [comment]
@darshankawar I tried js errors and try catch works as expected looks like it is an issue with Firebase messaging flutter only
sample of flutter js error, works fine
https://github.com/amrgetment/flutter_web_error

I don't know js very well to test firebase-js sdk

**Comment by amorenew** [comment]
@danagbemava-nc I reviewed the package example code
it used permission from a button
```
      return ElevatedButton(
          onPressed: requestPermissions,
          child: const Text('Request Permissions'));

```

But my case happened when you auto-request permission with a button (handler)

` await _firebaseMessaging.requestPermission();`

that's why I get this error

`The Notification permission may only be requested from inside a short running user-generated event handler.
`
so I want to request without a button (handler) and not crashing as some browsers support auto request and others require a button

**Comment by darshankawar** [comment]
@amorenew 
This doesn't seem to be actionable from plugin side. Also check https://pushpad.xyz/blog/the-notification-prompt-can-only-be-triggered-by-a-user-gesture-on-some-browsers for your reference which also says to use a button to make a permission request.

**Comment by amorenew** [comment]
@danagbemava-nc I will close it for now and I will check if my app is crashing due to a different reason or not
