### ISSUE TITLE
🐛 [cloud_firestore] Consider helpful extension methods

### ISSUE THREAD

**Issue by Levi-Lesches** [firebase/flutterfire#12002]
I always define the following in my code: 
```dart
/// Helpful functions to call on a [CollectionReference].
extension CollectionUtils<E> on CollectionReference<E> {
  /// Checks whether a document ID exists in this collection.
  Future<bool> contains(String id) async => (await doc(id).get()).exists;
}

/// Helpful functions to call on a [DocumentReference].
extension DocumentUtils<E> on DocumentReference<E> {
  /// Gets the data out of this document.
  Future<E?> getData() async => (await get()).data();
}

/// Helpful functions to call on a [Query].
extension QueryUtils<E> on Query<E> {
  /// Gets all the data from a query.
  Future<List<E>> getAll() async => [
    for (final document in (await get()).docs) 
      document.data(),
  ];
}
```

Maybe these, and other useful extensions, can be a part of `package:cloud_firestore`? They are a useful way of getting straight to the data without worrying about documents along the way, and since `.withConverter` came out, these are fully type-safe too.

**Comment by russellwheatley** [comment]
Thanks for your suggestion. It isn't something we are planning on implementing within the library itself. We try to stay as close to the native SDKs as possible. You're more than welcome to start a thread in the discussions for other developers to post their extensions 🙏
