### ISSUE TITLE
🐛[flutter_dynamic_links] link/?request_ip_version=IP_V6&match_message=No+pre-install+link+matched+for+this+devic

### ISSUE THREAD

**Issue by narasimha1419** [firebase/flutterfire#12005]
## Bug 
Match error found during build phase link/?request_ip_version=IP_V6&match_message=No+pre-install+link+matched+for+this+devic

### Steps to reproduce

1. App not installed
2. First time app install

Getting after configuring dynamic links

**Comment by darshankawar** [comment]
@narasimha1419 
It is not clear what exactly is the issue you are reporting. Please try to elaborate by providing the requested details from the issue template so that we'll have enough info to work with.
