### ISSUE TITLE
🐛 [cloud_firestore] saving make windows app loose connection and crash

### ISSUE THREAD

**Issue by richard457** [firebase/flutterfire#12009]
## Bug report

**Describe the bug**
Window loose connection on save

### Steps to reproduce

run this code
```dart
 @override
  Future<void> onSave<T extends IJsonSerializable>({required T item}) async {
    final String collectionName = getCollectionName<T>();
    final collectionRef = FirebaseFirestore.instance.collection(collectionName);
    try {
      await collectionRef.doc(getItemId<T>(item)).set(item.toJson());
    } catch (e) {
      print('Error: $e');
      // Handle the error appropriately.
    }
  }
```
3. See error or incorrect behavior

### Expected behavior

it should save normally, again it is important to note that it happens on some window machine

**Comment by patricknicolosi** [comment]
Same issue

**Comment by danagbemava-nc** [comment]
Hi @richard457, @patricknicolosi could either of you provide a complete minimal reproducible code sample in a repo that we can clone so that we can investigate this? 

I ran the plugin example app and played with it a little and it seems to work for me

**Comment by patricknicolosi** [comment]
The same app, crash in some pcs and in others no

**Comment by danagbemava-nc** [comment]
Hi @patricknicolosi, are you experiencing the same issue with the plugin example app?

If so, could you share the steps to reproduce and what devices it reproduces on?

**Comment by patricknicolosi** [comment]
The example app works correctly. My app always works in debug mode, it works in release in some devices and in others it does not

**Flutter doctor**
<img width="1147" alt="Screenshot 2023-12-17 alle 23 36 27" src="https://github.com/firebase/flutterfire/assets/23001470/e14a86fb-40a7-49d3-95b9-d511b9f317ab">

**System informations**
- Intel(R) Celeron(R) CPU N2840 @ 2.16Ghz
- RAM 2gb
- Windows 10 Pro 64bit

**pubsbec.yaml sdk version**
`environment:
  sdk: '>=3.2.3 <4.0.0'`

**Other informations**
All Firebase-related dependencies are from the latest version.

**Comment by danagbemava-nc** [comment]
Hi @patricknicolosi, can you share the crash message that you get? You might be able to get it if you debug with visual studio
