### ISSUE TITLE
Migrate `_web` packages to `package:web`, etc to support Wasm

### ISSUE THREAD

**Issue by kevmoo** [firebase/flutterfire#12027]
We are working on public documentation for this process, but creating this issue as a placeholder.

The short version:
- Migrate usage of `dart:html` to `package:web`
- Migrate usage of `dart:js`, `dart:js_util`, and `package:js` to `dart:js_interop`

**Comment by IchordeDionysos** [comment]
@Lyokone could we add a checklist of things that need to be done aka. packages that still need to be migrated to a TODO list in this issue?

e.g., Remote Config and Performance Monitoring, ... are also still open but have no PR yet.
And at the end, as I understand it, we'd have to remove `js` from all packages?!

**Comment by The-RootCause** [comment]
@Lyokone  Thank you.
Is there a any projection when the plugin can be compatible with Wasm ?
The current plugin is not compatible yet with wasm, which is blocking all firebase related plugins from being compatible with wasm,

**Comment by IchordeDionysos** [comment]
Related issue: https://github.com/firebase/flutterfire/issues/12466

**Comment by MominRaza** [comment]
web_plugin_registrant.dart => package:firebase_app_check_web => dart:html
App check is still using dart:html

**Comment by kevmoo** [comment]
> web_plugin_registrant.dart => package:firebase_app_check_web => dart:html
> App check is still using dart:html

Thanks @MominRaza  ! See https://github.com/firebase/flutterfire/issues/12597

**Comment by MominRaza** [comment]
Now I'm able to build with --wasm, yes now you can close this issue.
Thanks

**Comment by kevmoo** [comment]
Well done, folks!
