### ISSUE TITLE
🐛 [firebase_storage] refFromURL doesn't work on android when using firebase emulator

### ISSUE THREAD

**Issue by ellet0** [firebase/flutterfire#12046]
## Bug report

**Describe the bug**

The `refFromURL` by download URL doesn't work on Android when using Firebase emulator

![image](https://github.com/firebase/flutterfire/assets/73608287/fcc89fdf-8010-4a44-9d13-8b4bcb79e5d3)

### Steps to reproduce

the problem is on the dart side in `firebase_storage`

1. Create a new Flutter project, add Firebase to it, and use the plugin `firebase_storage`
2. Use the Firebase emulator and use `localhost` on android
3. Upload an image and try to get the reference by downloading the URL and you will get an exception, an asset failure in the file `firebase_storage.dart` on line 121:

```dart
assert(parts != null,
          "url could not be parsed, ensure it's a valid storage URL");
```

### Expected behavior

It would be nice if we could use it on all cases

I will fix it in PR

**Comment by darshankawar** [comment]
@ellet0 
Can you check [this](https://github.com/firebase/flutterfire/pull/7003) similar fix made previously ?

**Comment by ellet0** [comment]
> @ellet0 Can you check [this](https://github.com/firebase/flutterfire/pull/7003) similar fix made previously ?

That's fixing another bug, this bug only happens on Android because it uses `127.0.0.1` and it's not being checked in the current code, so I suggest fixing it or merging the simple non-breaking PR I sent to close this issue, thank you for your understanding.

**Comment by darshankawar** [comment]
Thanks for the update and explaination. With given replicable steps, I see the same behavior as reported.

**Comment by ellet0** [comment]
> Thanks for the update and explaination. With given replicable steps, I see the same behavior as reported.

I send a [PR](https://github.com/firebase/flutterfire/pull/12047) that fix this bug
it doesn't change much, only one line of code

It should fix the bug

**Comment by russellwheatley** [comment]
hey @ellet0 - could you flesh out your steps with code? You mention downloading the URL but you're reporting the bug with refFromUrl(). Please provide a code sample for me to reproduce the bug. Thanks.

**Comment by ellet0** [comment]
> hey @ellet0 - could you flesh out your steps with code? You mention downloading the URL but you're reporting the bug with refFromUrl(). Please provide a code sample for me to reproduce the bug. Thanks.

The file reference by url, that's what I meant

Url is the same as download url

Can you take a look at the PR? It has everything clear in there
