### ISSUE TITLE
macOS Foreground FCM notification not working

### ISSUE THREAD

**Issue by Allamprabhu1058** [firebase/flutterfire#12042]
macOS Foreground FCM notification not working

I am using firebase_messaging: ^14.6.7

Till today i was getting push notifcation in foreground for macos, it is stopped getting nofication in foreground.
Other platform like andoird, ios i am getting notification.

**Comment by darshankawar** [comment]
@Allamprabhu1058 
Are you getting any error logs or any entries you see in the console that will help to properly analyze the behavior ?


> Till today i was getting push notifcation in foreground for macos, it is stopped getting nofication in foreground.

This seems to be intermittent and may not be related to the plugin code, but could be a server side glitch. 
Also, in order for use to properly address the issue, please provide us all requested details in the issue template so that we'll have enough info to work with.

**Comment by Allamprabhu1058** [comment]
@darshankawar 
no errors, once after push notification received  FirebaseMessaging.onMessage.listen() this is getting triggered for all the platform macOS, iOS, Android.
For other platforms when the app is in foreground push notification are displayed except macOS.

 notification: {
        title: "Message Title",
        body:"Conent of the message",
        click_action: "FLUTTER_NOTIFICATION_CLICK",
        priority: "high",
        sound: "default",
        icon: "ic_launcher.png",
      },
      data: {
        "Action": "New Message",
        "isGroup": "true",
        "titleMultilang": message.name,
        "bodyMultilang": "Message content",
        "title": "New message in Group",
        "body": "New message(s) recieved.",
        "groupid": message.iDfltrd,
        "workspaceId": message.workspaceId.toString(),
        "workspacename": message.workspacename,
        "click_action": "FLUTTER_NOTIFICATION_CLICK",
        "messageType": message.type.toString(),
        "content": message.type == 6 ? message.contentnew : "",
      },

This message body working fine when the app is in killed or background, but only on macOS when the app is in foreground not receiving . let me know anything else is required to debug.
