### ISSUE TITLE
🐛 [firebase_app_check] Doesn't work on ios App Attest / Device Check

### ISSUE THREAD

**Issue by Epikur86** [firebase/flutterfire#12049]
## Bug report

**Describe the bug**
AppleProvider.deviceCheck and AppleProvider.appAttestWithDeviceCheckFallback doesn't not work on IOS 17.2. I tried both methods and both aren't working, all request are being blocked. On android App Check works without a problem.
Current package version of app check is 0.2.1+8.

I uploaded my app to Test Flight and from there I downloaded it to test the app.

Does someone has an idea what the issue could be?

**Comment by darshankawar** [comment]
@Epikur86 
Is it only occuring while in release mode or occurs in debug mode as well ?
Can you provide the exact log you get while trying to call AppleProvider.deviceCheck and AppleProvider.appAttestWithDeviceCheckFallback ?

**Comment by Epikur86** [comment]
In debug mode it is working when providing a debug app check token. The app is currently in review for the app store and I disabled app check for this period to not interrupt the review process. But I get the a permission-denied error from firebase, is there another way to get a more detailed log?

**Comment by darshankawar** [comment]
> I get the a permission-denied error from firebase

Can you provide the entire error log you get ? Along with `permission-denied`, it should also show a one liner description something like `The caller does not have permission to execute the specified operation.`

**Comment by Epikur86** [comment]
Hello,
I tried it on now with AppleProvider.debug on simulator and physical device with providing a debug token but both doesn't work on ios.
PlatformException (PlatformException(permission-denied, The caller does not have permission to execute the specified operation., {message: The caller does not have permission to execute the specified operation., code: permission-denied}, null)). 

On Android it works perfectly fine in debug mode.

firebase_app_check:'^0.2.1+8'

`[✓] Flutter (Channel stable, 3.16.3, on macOS 14.2 23C64
    darwin-arm64, locale de-DE)
    • Flutter version 3.16.3 on channel stable at
      /Users/artjomgyulnazarov/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0366e0a3f (4 weeks ago), 2023-12-05
      19:46:39 -0800
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK
    version 34.0.0)
    • Android SDK at
      /Users/artjomgyulnazarov/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google
      Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.85.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554
      • android-arm64  • Android 12 (API 32) (emulator)
    • iPhone von Artjom (mobile)  • 00008120-000A1D042EB8201E
      • ios            • iOS 17.2.1 21C66
    • iPhone 15 Pro Max (mobile)  •
      8D678EEF-1DB6-4C22-AA67-381BA71B5AEE • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)             • macos
      • darwin-arm64   • macOS 14.2 23C64 darwin-arm64
    • Chrome (web)                • chrome
      • web-javascript • Google Chrome 120.0.6099.129

[✓] Network resources
    • All expected network resources are available.`

**Comment by Epikur86** [comment]
I found the solution:

In the file GoogleService-Info.plist, a wrong GOOGLE_APP_ID was defined.
