### ISSUE TITLE
firebase_messaging (14.7.9) : Notification message handler not working for iOS

### ISSUE THREAD

**Issue by komalkhatri08** [firebase/flutterfire#12058]
## Bug report

**Describe the bug**
I receive notification on iOS flutter app, but my message handlers - onMessageOpenedApp, onMessage, getInitialMessage() are not triggered. 

### Expected behavior

on tap of message in background the message should be opened in the application  (iOS). Works fine in android.

### Sample project
below is the payload that i use to send notification to iOS.
```
  {
        aps: {
          alert: {
            title: 'Notification Title',
            body: notificationData
          },
          badge: 1,
          sound: 'default'
        },
        data: {
          tag: tag,
          messageType: messageType
        }
      };

```

I am sending notification via notification hub service of azure. notificationhubservice.apns.send(message).... 
---
I receive notification but on tap it does not trigger respective methods in flutter.

Let me know if any more information is required from my end.  I referred #9292 issue raised for same but versions are different.
## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by danagbemava-nc** [comment]
Hi @komalkhatri08, can you try using the firebase admin sdk to see if you experience the same issue? What version of flutter are you using and what version of iOS are you using?

**Comment by komalkhatri08** [comment]
Flutter version : >=2.19.6 <3.0.0'.    and iOS version : 17

**Comment by komalkhatri08** [comment]
@danagbemava-nc   -> I forgot to mention - I am sending notification to iOS and android using Azure notification hub. The payload accepted by Azure notification hub as per documentation is   
```
message  = {
        aps: {
          alert: {
            title: 'Notification Title',
            body: notificationData
          },
          badge: 1,
          sound: 'default'
        },
        data: {
          tag: tag,
          messageType: messageType
        }
      };
```
I do receive notification on my iOS device. but on tab of  notification the handlers are not triggered. 
But when i send test message from FCM to my iOS then the handlers are working fine. 

I guess its payload issue but I am not sure which exact payload is supported. 

Thanks in advance :)

**Comment by russellwheatley** [comment]
I've been testing this all day using this nodejs script:

```js
const admin = require('firebase-admin');
// Get service account key from firebase console
const serviceAccount = require('../ff-e2e-service.json');
admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
});
const token = 'TOKEN';
admin
.messaging()
.send(
  {
    token: token,
    data: {
      something:'test',
    },
    android: {
      // Required for background/terminated app state messages on Android
      priority: 'high',
    },
    apns: {
      payload: {
        aps: {
          // Required for background/terminated app state messages on iOS
          contentAvailable: true,
        }
      },
    },
  },
  
)
.then((res) => {
  if (res.failureCount) {
    console.log('Failed', res.results[0].error);
  } else {
    console.log('Success');
  }
})
```

and it has been working fine. I highly recommend you use Firebase admin SDK to send Firebase Messages. Closing as this isn't an issue with FlutterFire.

**Comment by komalkhatri08** [comment]
ok here I see firebase admin is used to send the notification using FCM. what i am doing is sending notification through azure notification hub and payload for iOS sent via Notification hub is different. 

below is my code in node js .

```
const { HUB_NAME, CONNECTION_STRING_FULL_ACCESS, DEVICE_TOKEN} = require("../config/config.js");
var azure = require("azure-sb");
var notificationHubService = azure.createNotificationHubService(
  HUB_NAME,
  CONNECTION_STRING_FULL_ACCESS
);

async function sendNotification(params) {
    let tag = params.tag;
    let notificationData = params.notificationData;
    let messageType = params.messageType;
    let platform = params.platform;
    let message = '';
   
    if(platform =='ios'){
   
      message  = {
        **aps: {
          alert: {
            title: 'Notification Title',
            body: notificationData
          },
          badge: 1,
          sound: 'default'
        },
        data: {
          tag: tag,
          messageType: messageType
        }
      };**

    }
    else if(platform == 'android'){
   message = {
        notification: {
          title: "Notification",
          body: "Notification Message"
        },
        data:{
          messageType: messageType,
          body:      
           notificationData,       
      },
       // tag: req.body.tag,
        tag: tag,
       
      };
    }
    console.log('inside send notification to '+ platform);

    if(platform == 'ios'){
      return new Promise((resolve, reject) => {
        notificationHubService.apns.send(tag, message, (error, response) => {
         if (error) {
          reject(error);
         } else {
          resolve(response);
         }
       });
     });
    } 
    else if(platform == android){
    return new Promise((resolve, reject) => {
       notificationHubService.gcm.send(tag, message, (error, response) => {
        if (error) {
         reject(error);
        } else {
         resolve(response);
        }
      });
    });
  }
  }
  module.exports = {
    sendNotification,   
  };
```

I get the notifciation using this code, but on tap no handlers are triggered.
