### ISSUE TITLE
🐛 [firebase_messaging] Disable default notification

### ISSUE THREAD

**Issue by menezes85** [firebase/flutterfire#12068]
Hello, 

First thanks for this fantastic plugin! You do an awesome work!

I come here to ask if its possible to disable default firebase notification, i was unable to achieve that, i have my own notification service on my app and want to use it instead of default firebase notification. backgroundHandler automatically fires a default notification, is this possible ?  Thanks.

**Comment by danagbemava-nc** [comment]
Hi @menezes85, how are you sending the notifications and what is the payload that you send?

**Comment by russellwheatley** [comment]
The background handler does not by default post a notification. If you wish to have a silent message (i.e. no notification), do not send a notification in the message payload: https://github.com/firebase/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/example/scripts/send-message.js#L25C1-L28
