### ISSUE TITLE
🐛 [firebase_messaging ]  Unhandled Exception: [firebase_messaging/apns-token-not-set] APNS token has not been set yet.

### ISSUE THREAD

**Issue by wepashka** [firebase/flutterfire#12070]
## Bug report

** Unhandled Exception: [firebase_messaging/apns-token-not-set] APNS token has not been set yet. Please ensure the APNS token is available by calling `getAPNSToken()`.**

I have configured all configurations for iOS notification but still gat that issue; my flutter version is 3.7.7 firebase_messaging version is ^14.6.5

**Comment by wepashka** [comment]
my issue is exactly like this issue: "APNS token not found... #11590"

**Comment by wepashka** [comment]
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: [firebase_messaging/apns-token-not-set] APNS token has not been set yet. Please ensure the APNS token is available by calling `getAPNSToken()`.
#0      MethodChannelFirebaseMessaging._APNSTokenCheck (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:138:9)
<asynchronous suspension>
#1      MethodChannelFirebaseMessaging.unsubscribeFromTopic (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:404:5)
<asynchronous suspension>
#2      main (package:timar_mobile_app/main.dart:171:3)
<asynchronous suspension>

**Comment by tashfeenzaidi** [comment]
i also having the same prob.
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [firebase_messaging/apns-token-not-set] APNS token has not been set yet. Please ensure the APNS token is available by calling `getAPNSToken()`.

**Comment by wepashka** [comment]
I have solved that issue by changing my plugins version which I used in my app: 

 firebase_core: 2.15.1
  firebase_messaging: 14.6.7
  firebase_analytics: 10.4.5
  firebase_core_platform_interface: 4.8.0
  
  After setting them I run `pod install` on my iOS directory then run

 `pod install --repo-update `
 then 
` pod update Firebase/CoreOnly`

**Comment by wepashka** [comment]
my flutter version is 3.13.2
