### ISSUE TITLE
🐛 [cloud_firestore] Add sum and average operators

### ISSUE THREAD

**Issue by puf** [firebase/flutterfire#12074]
## What feature would you like to see?

The native SDKs for Firestore on iOS, Android, and Web support the new `sum` and `average` aggregation operations. Can you make these operations available in Flutter too?

**Comment by sanghvi-develop** [comment]
It would really beneficial and helpful as counters are a tedious process to achieve this. Apparently sum and average are 2 main queries by which analytics could be maintained.

**Comment by puf** [comment]
Thanks @russellwheatley! No idea why I couldn't find that one when I searched for it. 👍
