### ISSUE TITLE
[📚] [Analytics] Documentation for setCurrentScreen is wrong and confusing

### ISSUE THREAD

**Issue by wujek-srujek** [firebase/flutterfire#12091]
The documentation found here https://github.com/firebase/flutterfire/blob/firebase_analytics-v10.7.4/packages/firebase_analytics/firebase_analytics/lib/src/firebase_analytics.dart#L173-L191 is incorrect and confusing:

1. It says that it sets the screen as a context, whereas in reality (at least the method channel implementation) it just logs the 'screen_view' event: https://github.com/firebase/flutterfire/blob/firebase_analytics-v10.7.4/packages/firebase_analytics/firebase_analytics_platform_interface/lib/src/method_channel/method_channel_firebase_analytics.dart#L142. This is because it presumably used to call https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.html#setCurrentScreen(android.app.Activity,%20java.lang.String,%20java.lang.String) (which it links to), but it doesn't do it any more.
2. The name 'setCurrentScreen' is confusing, at least to me. I initially thought that it would set the screen as 'context' (i.e. a piece of data that is attached to all events logged afterwards, until removed or changed) - it might have done it in the past, but now it doesn't, it just logs a screen view.
3. It links to the Android https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.html#setCurrentScreen(android.app.Activity,%20java.lang.String,%20java.lang.String) method, which has the same name but is now deprecated. But it doesn't even call that function (probably because it has been deprecated), but it adds to the confusion.
4. It links to the iOS method https://firebase.google.com/docs/reference/ios/firebaseanalytics/api/reference/Classes/FIRAnalytics#setscreennamescreenclass, which doesn't even exist as it seems.

**Comment by russellwheatley** [comment]
Hey @wujek-srujek, we already have an issue open for this: https://github.com/firebase/flutterfire/issues/11035

and a PR that deprecates `setScreenView()`: https://github.com/firebase/flutterfire/pull/12085

Essentially, stop using `setScreenView()`, and use `logScreenView()` instead.

**Comment by wujek-srujek** [comment]
@russellwheatley That's perfect, thank you.
