### ISSUE TITLE
🐛 [firebase_messaging] Web notification redirection not working 

### ISSUE THREAD

**Issue by mahammad-webelight** [firebase/flutterfire#12105]
## Bug report

**Describe the bug**
Flutter Web notification redirection not working

### Steps to reproduce

1. click on notification
2. it will open same page it will not redirect to other sceeen
3. See video

https://www.veed.io/embed/7ecfe6da-0108-4b9d-80b7-20e99c040b4c

### Expected behavior

it should redirect to specific screen which mention in route

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.5, on macOS 14.0 23A344 darwin-arm64 (Rosetta), locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.85.1)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

</details>

---

**Comment by zeeshan-webelight** [comment]
facing same issue in PWA as well

**Comment by Zeeshan0201** [comment]
facing same issue in PWA as well

**Comment by darshankawar** [comment]
Closing this out in favour of this issue: https://github.com/firebase/flutterfire/issues/10268. They're effectively the same.
