### ISSUE TITLE
[FirebaseAuth] cannot find symbol import com.google.firebase.auth.TotpSecret;

### ISSUE THREAD

**Issue by Srba90** [firebase/flutterfire#12108]
After upgrade to latest versions of firebase packages for flutter I get this error when building apk for android: 

``` 
.pub-cache/hosted/[pub.dev/firebase_auth-4.15.3/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseTotpSecret.java:11](http://pub.dev/firebase_auth-4.15.3/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseTotpSecret.java:11): error: cannot find symbol import com.google.firebase.auth.TotpSecret; 
symbol: class TotpSecret
 location: package com.google.firebase.auth 
.pub-cache/hosted/[pub.dev/firebase_auth-4.15.3/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseTotpMultiFactor.java:11](http://pub.dev/firebase_auth-4.15.3/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseTotpMultiFactor.java:11): error: cannot find symbol import com.google.firebase.auth.TotpMultiFactorAssertion; 
symbol: class TotpMultiFactorAssertion 
location: package com.google.firebase.auth 
.pub-cache/hosted/[pub.dev/firebase_auth-4.15.3/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseTotpMultiFactor.java:12](http://pub.dev/firebase_auth-4.15.3/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseTotpMultiFactor.java:12): error: cannot find symbol import com.google.firebase.auth.TotpMultiFactorGenerator; 
symbol: class TotpMultiFactorGenerator 
location: package com.google.firebase.auth 
.pub-cache/hosted/[pub.dev/firebase_auth-4.15.3/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseTotpMultiFactor.java:13](http://pub.dev/firebase_auth-4.15.3/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseTotpMultiFactor.java:13): error: cannot find symbol import com.google.firebase.auth.TotpSecret; 
symbol: class TotpSecret location: package com.google.firebase.auth 
.pub-cache/hosted/[pub.dev/firebase_auth-4.15.3/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseTotpMultiFactor.java:22](http://pub.dev/firebase_auth-4.15.3/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseTotpMultiFactor.java:22): error: cannot find symbol static final Map<String, TotpSecret> multiFactorSecret = new HashMap<>(); 
symbol: class TotpSecret 
location: class FlutterFirebaseTotpMultiFactor 
```

 **Pubspec.yaml:** 
dependencies: 
firebase_messaging: ^14.7.9
firebase_auth: ^4.15.3 
firebase_core: ^2.24.2

 **Gradle wrapper:** gradle-8.5-all.zip **

Gradle.build:** dependencies { 
classpath 'com.android.tools.build:gradle:8.2.0' 
classpath 'com.google.gms:google-services:4.4.0' } 

**Java:** openjdk-17.jdk

 Build for iOS works fine. Latest version for android that could build without issue was with dependencies: 
firebase_messaging: 14.6.0 
firebase_auth: 4.7.3 
firebase_core: 2.15.1

 I found this reported issue https://github.com/firebase/flutterfire/issues/11648 but they don't say how to fix it, only that issue is resolved. 

Any suggestions?

**Comment by danagbemava-nc** [comment]
Hi @Srba90, do you have this issue with the plugin example app as well? 

Does clearing your pub cache make it work? Did you happen to upgrade your gradle version at the time you updated your flutterfire dependencies?

**Comment by Srba90** [comment]
Hi @danagbemava-nc , I had version of FirebaseSDK in build.gradle file set to

rootProject.ext {
  set('FlutterFire', [
    FirebaseSDKVersion: '29.0.4'
  ])
}

and when I removed it, it got solved. I guess it wasn't compatible with latest firebase packages that I use. 
Thank you anyway.

**Comment by danagbemava-nc** [comment]
Closing this based on https://github.com/firebase/flutterfire/issues/12108#issuecomment-1876802631
