### ISSUE TITLE
🐛 [cloud_Firestore] Update 4.14.0 CHANGELOG to clearly describe its BREAKING change

### ISSUE THREAD

**Issue by kosukesaigusa** [firebase/flutterfire#12119]
## Update 4.14.0 CHANGELOG to clearly describe its BREAKING change

According to the [diff](https://github.com/firebase/flutterfire/commit/82af6c2f40160a9e2f74e2d48652003fa48bb161#diff-a7d6f2f7fa9f6ad84f9faf884d4a507f5e85a06d88e64b99578de885a0b637d5R19), since cloud_firestore version `4.14.0`, aggregation `count` query returns `int?` instead of `int`, which is not compatible with previous versions.

So would it be better to clearly describe the BREAKING change for 4.14.0 CHANGELOG? (Otherwise, I would like to know the standard to judge what BREAKING changes are and others are not.)

And additionally, having doc comments to explain when the `count` property to return `null` is desired.

**Comment by ViniciusSossela** [comment]
It looks like a bug to return null...

**Comment by Lyokone** [comment]
Hello @kosukesaigusa, sorry for the late response. The change from int to int? is indeed a breaking change but was considered a fix since it could happen in some edge cases in the previous versions.
