### ISSUE TITLE
🐛 [cloud_firestore 4.14.0] error: can't find firestore plugin in Flutter

### ISSUE THREAD

**Issue by Siyaho** [firebase/flutterfire#12127]
All works great, until Firestore plugin is being installed on Flutter. Getting 🐛 [cloud_firestore 4.14.0] error: can't find firestore plugin in Flutter, error. 

Any chance how to solve this? Already tried cleaning, running it again and updating all other plugins.

`Firestore does not exist flutterEngine.getPlugins().add(new io.flutter.plugins.firebase.firestore.FlutterFirebaseFirestorePlugin());`

**Comment by darshankawar** [comment]
@Siyaho 
After adding firestore plugin, are you running `flutter pub get` ?
Also, can you provide the complete error log that is triggered ? Can you also provide replicable steps that leads to the error shown ?

**Comment by Siyaho** [comment]
Yes, I did the usual things. Flutter clean, pub get and run. Nothing worked. For now I just removed Firestore. Will try later again, but it was not working, sadly.

**Comment by darshankawar** [comment]
I ran into this while updating the plugin example. I did `flutter clean` and also [this](https://github.com/fluttercommunity/flutter_workmanager/issues/287#issuecomment-893476072) in combination.

**Comment by darshankawar** [comment]
@Siyaho Maybe you are hitting same as https://github.com/flutter/flutter/issues/141940

**Comment by darshankawar** [comment]
Closing this in favor of the flutter issue I linked above. Please follow-up in it for further updates. Once it is fixed, you can retry your scenario to check if you still get the same error or not and comment here if the issue still persists after the fix.

**Comment by Siyaho** [comment]
I ended up not using it, sadly. It was just not working. What info do you require, that I need to share?
