### ISSUE TITLE
🐛 [Firebase_messaging] iOS Terminated push Notifications issue

### ISSUE THREAD

**Issue by Gobmichet** [firebase/flutterfire#12138]
Hi,

I recently discovered (but too late :( we have 35k users that use our app that handles push notifs via onBackgroundMessage() in order to save them in DB to have an history in the app... ) from your documentation at :
https://firebase.google.com/docs/cloud-messaging/flutter/receive)](https://firebase.google.com/docs/cloud-messaging/flutter/receive
that :
![Capture](https://github.com/firebase/flutterfire/assets/3100468/bf777a8c-343f-41de-a3ab-3aab78a47b68)

I'm aware that it is an iOS restriction even if i don't understand why it is not "fixed"/changed by Apple.

So our app does work in 5 scenarios out of 6.
The only one that doesn't work is for TERMINATED iOS app, but it must be the case for 80% of the time for iOS users :( 

I would like to know if there is something to do about it !?

Because I've read this thread on stackoverflow :
https://stackoverflow.com/questions/76238055/flutter-fcm-not-handling-messages-when-app-terminated-on-ios
where people have the same issue and in the 1st post the author says :
`The one scenario in which the onBackgroundMessage() handler is not called (even though the push notification comes through and is displayed), is on IOS when the app is terminated. **_The handler does however work when you send a second push notification right after the first one, because the first one wakes up the app_**.`

Is it correct that a 1st notif would wake up the app ?
And that a 2nd one would then correctly be handled ?

If true, there must be a solution right ? "refiring" the event that woke up the app in the 1st place for exemple or something...

How to achieve this please ?

Any help would be MUCH appreciated 'cause we can't stay like that and the only solution would be to refactor the whole thing by a webservice call that would "pull" notifs history from a server (an i'd (really) rather not do that...)

Thanks in advance.

**Comment by darshankawar** [comment]
maybe [this](https://github.com/firebase/flutterfire/issues/11500) then.

**Comment by Rohan-raftlabs** [comment]
Did anyone identify a fix. Recently faced this issue on our app.

notificaitons works absolutely fine on android and on ios as well in background and foreground state.

in terminated state the notification shows up but the callback handler is not invoked.
