### ISSUE TITLE
🐛 [cloud_firestore] sentinel value breaks wrappers

### ISSUE THREAD

**Issue by cedvdb** [firebase/flutterfire#12130]
## Bug report

Following [this issue](https://github.com/firebase/flutterfire/issues/11874) a "sentinel value" was [added](https://github.com/firebase/flutterfire/pull/11896/files#diff-c388154c29616d9c4eff4b583681b56e75ae1f0291f6c31db037d3d1e85fdd65R602) to query parameters. 

From:

```dart
  Query<Map<String, dynamic>> where(
    Object fieldOrFilter, {
    Object? isEqualTo,
    Object? isNotEqualTo,
    Object? isLessThan,
    Object? isLessThanOrEqualTo,
    Object? isGreaterThan,
    Object? isGreaterThanOrEqualTo,
    Object? arrayContains,
```

To:

```dart
    Object? isEqualTo = notSetQueryParam,
    Object? isNotEqualTo = notSetQueryParam,
    Object? isLessThan = notSetQueryParam,
    Object? isLessThanOrEqualTo = notSetQueryParam,
    Object? isGreaterThan = notSetQueryParam,
    Object? isGreaterThanOrEqualTo = notSetQueryParam,
    Object? arrayContains = notSetQueryParam,
```

However this is a breaking change for any kind of wrapper as null will be passed: 

```dart
  AppQuery<T> where(
    AppFieldPath fieldPath, {
    Object? isEqualTo,
    Object? isNotEqualTo,
    Object? isLessThan,
    Object? isLessThanOrEqualTo,
    Object? isGreaterThan,
    Object? isGreaterThanOrEqualTo,
    Object? arrayContains,
    Iterable<Object?>? arrayContainsAny,
    Iterable<Object?>? whereIn,
    Iterable<Object?>? whereNotIn,
    bool? isNull,
  }) {
    final queryRef = _ref.where(
      fieldPath.toFirestore(),
      isEqualTo: isEqualTo,
      isNotEqualTo: isNotEqualTo,
      isLessThan: isLessThan,
      isLessThanOrEqualTo: isLessThanOrEqualTo,
      isGreaterThan: isGreaterThan,
      isGreaterThanOrEqualTo: isGreaterThanOrEqualTo,
      arrayContains: arrayContains,
      arrayContainsAny: arrayContainsAny,
      whereIn: whereIn,
      whereNotIn: whereNotIn,
      isNull: isNull,
    );
    // ...
```

I believe this (breaking) change was not required since there is already a `isNull` parameter. Exposing `notSetQueryParam` to the public api doesn't sound too good, so if that previous change wasn't necessary I suggest reverting those changes as this will be a breaking change for libraries wrapping firebase. For instance `fake_cloud_firestore` has diverged in behavior from cloud firestore. 

Note: The [dart default parameter proposal](https://github.com/dart-lang/language/issues/2269) would have been helpful here

**Comment by russellwheatley** [comment]
Hey @cedvdb, thanks for the update. Upon review, we have decided that this does constitute a breaking change and will roll this back in the next release 🙏
