### ISSUE TITLE
🐛 [firebase_analytics] Implement consent mode v2

### ISSUE THREAD

**Issue by szepeshazi** [firebase/flutterfire#12148]
As per https://developers.google.com/tag-platform/security/guides/app-consent?platform=ios the recommended way to set user consent is consent mode v2, which enables toggling the following four individual properties.
```
AD_PERSONALIZATION | Sets consent for personalized advertising.
AD_STORAGE | Enables storage (such as device identifiers) related to advertising.
AD_USER_DATA | Sets consent for sending user data to Google for advertising purposes.
ANALYTICS_STORAGE | Enables storage (such as app identifiers) related to analytics, e.g. visit duration.
```

In the `firebase_analytics` plugin, the `setConsent` method signature is 
```
/// Sets the applicable end user consent state. 'default' value for 'adStorageConsentGranted' & 'analyticsStorageConsentGranted' is 'true'
  Future<void> setConsent({
    bool? adStorageConsentGranted,
    bool? analyticsStorageConsentGranted,
  }) 
```
exposing only two of the four above mentioned properties.

Please update `firebase_analytics` in `flutterfire` to support Google consent mode v2.

**Comment by olenirwing** [comment]
There ar major marketing implications for tons of of apps out there if we cannot implement the consent mode v2. I hope you guys can make it a priority. Thanks for your work!

**Comment by leo-mms** [comment]
To raise attention, I'd also like to leave a comment here. For us it's also crucial to use V2 soon.
Maybe you can roughly estimate when this will be implemented, so that we know that we might need to use workarounds before we go live.

**Comment by shanelic** [comment]
I'm facing the same problem, please make this a priority to implement the consent mode v2. 

Btw, do you guys have any awareness of the reason why after I executed
`FirebaseAnalytics.instance.setConsent(adStorageConsentGranted: value);`
the verbose logs keep showing the same value as the default one I set in the Info.plist / AndroidManifest.xml? The value doesn't even change once at all.

**Comment by kaptnkoala** [comment]
I can also only emphasize, that it is crucial for us that we have support for setting these additional consent flags prior to the rollout of Google Consent Mode V2 in March 2024.

**Comment by russellwheatley** [comment]
As an update, we are planning on updating the API for the above mentioned, we're just going through an API review before implementing. I will let you know when it is released 🙏

**Comment by matinzd** [comment]
@russellwheatley 
I started working on adding it yesterday and I opened a PR today. Should I continue working on it or you have open PR internally?

**Comment by matinzd** [comment]
@russellwheatley 
I began implementing this yesterday and have already submitted a pull request today. Would you prefer that I proceed with further enhancements, or do you currently have an open pull request in progress internally?

**Comment by russellwheatley** [comment]
@matinzd - I have the bones of a PR which is on hold until we decide on API. Happy to proceed with your PR once decided if you care to update when the time to implement arrives 😄

**Comment by matinzd** [comment]
@russellwheatley I am available as soon as you have the internal discussions resolved. Just ping me in the PR.

**Comment by JgomesAT** [comment]
this setConsent is not valid for FLutter web, how can I set consent in flutter web?

**Comment by russellwheatley** [comment]
@JgomesAT - It will be allowed in upcoming PR. [See docs](https://firebase.google.com/docs/reference/js/analytics?_gl=1*1yx3yyi*_up*MQ..*_ga*MTkyNzk2MTAyMS4xNzA4NDQ2MDQy*_ga_CW55HF8NVT*MTcwODQ0NjA0MS4xLjAuMTcwODQ0NjA0MS4wLjAuMA..#setconsent_1697027)

**Comment by JgomesAT** [comment]
Great news

**Comment by JgomesAT** [comment]
any schedule, for when that will be ready

**Comment by ibrahimdevs** [comment]
@russellwheatley what is the final status about this? 
There is a deadline to implement Consent Mode V2 for 6. March, and there is no official solution for Flutter Apps.

**Comment by nitinrgadhiya** [comment]
@ibrahimdevs I've done customization in the local and the package works fine for me.

you need to make some specific changes in packages and follow the V1 consent methods.

**Comment by russellwheatley** [comment]
Hey everyone, sorry for the delay. We have the green light for this API update.

@matinzd - let me know if you wish to proceed with your PR. I've provided some feedback 😄

**Comment by szepeshazi** [comment]
@russellwheatley thanks for addressing this! Great help. Could you give us some hints on the release ETA?

**Comment by russellwheatley** [comment]
@szepeshazi - Hopefully today, definitely tomorrow 👍
