### ISSUE TITLE
Addition to Delete files with Cloud Storage on Flutter page

### ISSUE THREAD

**Issue by RobKabob1** [firebase/flutterfire#12149]
On https://firebase.flutter.dev/docs/storage/delete-files, there is a section about deleting a file. The reference creation uses a string "images/desert.jpg" as the ID to get a reference.

![Screenshot from 2024-01-11 10-25-52](https://github.com/firebase/flutterfire/assets/17152722/fe7c5128-e1bf-4014-895d-da14fa4007af)

I was not able to use it to figure out how to get a reference from a URL. Here is the code that will do it:

`
Reference desertRef = FirebaseStorage.instance.refFromURL("https://something.jpg");
await ref.delete();
`

Is that something that you can add to the documentation?

**Comment by darshankawar** [comment]
@RobKabob1 
The link you referred is not updated one and should not be referred anymore. The correct usage link for the plugin is https://firebase.google.com/docs/storage/flutter/delete-files#delete_a_file so check the same and see if it answers your question or not.

**Comment by RobKabob1** [comment]
Even that new link (https://firebase.google.com/docs/storage/flutter/delete-files#delete_a_file) doesn't have information on getting a reference from a URL. Could it be updated to include that?

**Comment by darshankawar** [comment]
@RobKabob1 
The link says `To delete a file, first [create a reference](https://firebase.google.com/docs/storage/flutter/create-reference) to that file.`, which shows the way the reference has been created to delete the said file: 

https://firebase.google.com/docs/storage/flutter/create-reference

Mainly:

```
// Create a child reference
// imagesRef now points to "images"
final imagesRef = storageRef.child("images");

// Child references can also take paths
// spaceRef now points to "images/space.jpg
// imagesRef still points to "images"
final spaceRef = storageRef.child("images/space.jpg");
```

See if above is applicable in your case and whether creating the shown reference helps to answer your question or not.

**Comment by RobKabob1** [comment]
I still couldn't figure out how to do what I originally requested from the documentation. I found the solution on a stackoverflow page. Im closing this one.
