### ISSUE TITLE
🐛 [Cloud_Firestore] App crashes when running add or set offline

### ISSUE THREAD

**Issue by rafaelterada** [firebase/flutterfire#12142]
### Description
I'm developing an app that needs to work online and offline. Online is working perfectly. However, when it's offline and I go to execute a add or set, it generates an error. The strange thing is that after the error it doesn't catch. It just stops the app on the screen

### Sample project
``
    final ref = FirebaseFirestore.instance.collection('devices');
    final map = deviceDto.toMap();
    if (deviceDto.id.isEmpty) {
      await ref.add(map);
    } else {
      await ref.doc(deviceDto.id).set(map);
    }
``

### Generated error
`Stream closed with status: Status{code=UNAVAILABLE, description=Unable to resolve host firestore.googleapis.com, cause=java.lang.RuntimeException: java.net.UnknownHostException: Unable to resolve host "firestore.googleapis.com": No address associated with hostname`

### Flutter doctor
[!] Flutter (Channel stable, 3.16.5, on Microsoft Windows [versÆo 10.0.22621.2861], locale pt-BR)
    • Flutter version 3.16.5 on channel stable at C:\Users\Usuario\.puro\envs\vgcj\flutter
    ! Warning: `flutter` on your path resolves to C:\Users\Usuario\.puro\envs\stable\flutter\bin\flutter, which is not inside your current Flutter SDK checkout at
      C:\Users\Usuario\.puro\envs\vgcj\flutter. Consider adding C:\Users\Usuario\.puro\envs\vgcj\flutter\bin to the front of your path.
    ! Warning: `dart` on your path resolves to C:\Users\Usuario\.puro\envs\stable\flutter\bin\dart, which is not inside your current Flutter SDK checkout at
      C:\Users\Usuario\.puro\envs\vgcj\flutter. Consider adding C:\Users\Usuario\.puro\envs\vgcj\flutter\bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (3 weeks ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Usuario\AppData\Local\Android\sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34330.188
    ✗ Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[✓] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[✓] VS Code (version 1.85.0)
    • VS Code at C:\Users\Usuario\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.74.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [versÆo 10.0.22621.2861]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 120.0.6099.200
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 120.0.2210.121

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.

### Flutter dependencies
cloud_firestore: ^4.14.0

**Comment by darshankawar** [comment]
@rafaelterada 
Based on [this](https://github.com/firebase/flutterfire/issues/7636#issuecomment-1190114304) answer, I'll go ahead and close this as not an issue with plugin.
