### ISSUE TITLE
🐛 [firebase_messaging] Insecure hashing algorithm SHA-1 used

### ISSUE THREAD

**Issue by jamesonfajardo** [firebase/flutterfire#12163]
Hi Team,

a security audit flagged this issue on our app. May I request for more info on this.

firebase_messaging: ^14.6.3

<img width="823" alt="image" src="https://github.com/firebase/flutterfire/assets/54289743/54ed00d5-9834-45b2-b796-c036e9829ef5">

<img width="819" alt="image" src="https://github.com/firebase/flutterfire/assets/54289743/f72c9372-1242-4030-99d1-1ca8341337b7">

**Comment by darshankawar** [comment]
I think this probably need to be raised in native sdk, but will this issue open for team's input.

**Comment by russellwheatley** [comment]
You need to raise this in the firebase-android-sdk which contains the code you're referencing: https://github.com/firebase/firebase-android-sdk
