### ISSUE TITLE
🐛 [firebase_auth] need to validate non-existing numbers

### ISSUE THREAD

**Issue by guvanch07** [firebase/flutterfire#12165]
## What feature would you like to see?

Need to validate non-existing numbers for example: +375 29 111 11 11 is valid number because with 29 - phone code exists if user write  +375 87 111 11 11 also is valid for firebase otp but isn't, because  87 - phone code does't exist for the current country

Is there a missing a feature that is supported on an underlying SDK? Or is there a feature that you think would be useful to have in FlutterFire?

**Comment by russellwheatley** [comment]
On FlutterFire, we essentially mirror the Firebase SDK APIs. There isn't an API for validating numbers on the SDK, but there are specific dart packages for this use case that might help you: https://pub.dev/packages/phone_number
