### ISSUE TITLE
"Error building Flutter project on Windows: 'FirebaseAppPlatform.verifyExtends' not found" here

### ISSUE THREAD

**Issue by salah804** [firebase/flutterfire#12166]
## Bug report

**Describe the bug**
A clear and concise description of the issue: 

When attempting to build my Flutter project on Windows, I encounter the following error related to the 'firebase_core' package:

```plaintext
../../AppData/Local/Pub/Cache/hosted/pub.dev/firebase_core-1.24.0/lib/src/firebase_app.dart(18,25): error G75B77105: Member not found: 'FirebaseAppPlatform.verifyExtends'. [C:\Users\salah\Downloads\flutter_web_app\build\windows\x64\flutter\flutter_assemble.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(242,5): error MSB8066: Custom build for 'C:\Users\salah\Downloads\flutter_web_app\build\windows\x64\CMakeFiles\ab250fb67725dffd1d08fe0e0ff975ae\flutter_windows.dll.rule;C:\Users\salah\Downloads\flutter_web_app\build\windows\x64\CMakeFiles\6e4c404df4a1dd3ce87044a35db02a3e\flutter_assemble.rule;C:\Users\salah\Downloads\flutter_web_app\windows\flutter\CMakeLists.txt' exited with code 1. [C:\Users\salah\Downloads\flutter_web_app\build\windows\x64\flutter\flutter_assemble.vcxproj]
```

### Steps to reproduce

Run flutter build windows in the project directory.
See the error mentioned above.
### Expected behavior

I expected the build process to complete successfully without any errors.

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
/../AppData/Local/Pub/Cache/hosted/pub.dev/firebase_core-1.24.0/lib/src/fir
ebase_app.dart(18,25): error G75B77105: Member not found: 'FirebaseAppPlatfor
m.verifyExtends'. [C:\Users\salah\Downloads\flutter_web_app\build\windows\x64\flutter\flutter_assemble.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\
v170\Microsoft.CppCommon.targets(242,5): error MSB8066: Custom build for 'C:\
Users\salah\Downloads\flutter_web_app\build\windows\x64\CMakeFiles\ab250fb677
25dffd1d08fe0e0ff975ae\flutter_windows.dll.rule;C:\Users\salah\Downloads\flut
ter_web_app\build\windows\x64\CMakeFiles\6e4c404df4a1dd3ce87044a35db02a3e\flu
tter_assemble.rule;C:\Users\salah\Downloads\flutter_web_app\windows\flutter\C
MakeLists.txt' exited with code 1. [C:\Users\salah\Downloads\flutter_web_app\build\windows\x64\flutter\flutter_assemble.vcxproj]
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by danagbemava-nc** [comment]
Hi @salah804, it doesn't seem like you're using the latest version of `firebase_core`. Please upgrade to the latest version of `firebase_core` to see if you still experience this issue. If you do, please provide the output of `flutter pub deps -- --style=compact` and the output of `flutter doctor -v` and a complete minimal reproducible code sample in a repo that we can clone so that we can investigate this issue. 

Thank you
