### ISSUE TITLE
🐛 [firebase_analytics] Events are not showing up on  google analytics (ANDROID ONLY) FLUTTER APP

### ISSUE THREAD

**Issue by Alex-web0** [firebase/flutterfire#12178]
## Bug report

**Describe the bug**
Firebase google analytics package not logging any events on the dashboard. The app will not change anything in the realtime panel and only when I uninstall the app entirely does the logs show up

### Steps to reproduce

1. create a new flutter project
2. install packages ```firebase_core, firebase_analytics``` of the latest versions
3. create a firebase project with google analytics enabled and run flutterfire to link the project to the flutter app
4. run the code below in your main (this is literally just the default counter app with the increment button dispatching a screen event to google analytics)
```dart
import 'package:dio/dio.dart';
import 'package:firebase_analytics/firebase_analytics.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

import 'firebase_options.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  FirebaseAnalytics.instance;

  runApp(MyApp(firebaseAnalytics: FirebaseAnalytics.instance));
}

class MyApp extends StatelessWidget {
  const MyApp({super.key, required this.firebaseAnalytics});

  final FirebaseAnalytics firebaseAnalytics;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      navigatorObservers: [
        FirebaseAnalyticsObserver(analytics: FirebaseAnalytics.instance),
      ],
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home:
          MyHomePage(title: 'Flutter Demo Home Page', firebaseAnalytics: firebaseAnalytics),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title, required this.firebaseAnalytics});

  final FirebaseAnalytics firebaseAnalytics;


  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;



  void _incrementCounter() async {
    try {
      FirebaseAnalytics.instance.setCurrentScreen(screenName: "ssss20832us8028$_counter");
      await FirebaseAnalytics.instance.logEvent(
        name: 'first_open_2',
        callOptions: AnalyticsCallOptions(global: true),
        parameters: {
          'ss': "SCREEN_${DateTime.timestamp().millisecondsSinceEpoch}",
          'ss2': "FLUTTER_${DateTime.timestamp().millisecondsSinceEpoch}",
        },
      );
    } catch (e) {
      print(e);
    }
    setState(() {

      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(

        backgroundColor: Theme.of(context).colorScheme.inversePrimary,

        title: Text(widget.title),
      ),
      body: Center(

        child: Column(

          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```
5. (OPTIONAL) Change gradle as needed and add google services if gotten the error 
` google_app_id not found. Firebase Analytics Disabled`

- in build.gradle (project level):
```gradle
buildscript {
    // ! changed this version
    ext.kotlin_version = '1.9.20'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {

  // ! Changed this version
        classpath 'com.android.tools.build:gradle:7.4.1'
  // ! Added this dependency

        classpath 'com.google.gms:google-services:4.3.14'

        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
```

In app/build.gradle:
```gradle
dependencies {
     // added thsi line
    implementation 'com.google.firebase:firebase-analytics:21.5.0'

    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}
```
in android object changed sdk versions to:
```gradle
    defaultConfig {

        applicationId "com.example.shit_2"

        minSdkVersion 23 // ! added this
        targetSdkVersion 34 // ! added this
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

Add this to initial apply plugin statements:
apply plugin: 'com.google.gms.google-services' // added this

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
```

After applying this solution and then running
```shell
cd android

./gradlew clean

./gradlew build
```
6. Run the app, and make sure no errors are logged in the console by flutter

### Expected behavior

It is expected for logs to show up in this tab after I click the increment button which will dispatch an event of type `screen_view`
just like in this screen, it only shows the user and no matter how many times I dispatch an event id doesn't work
![image](https://github.com/firebase/flutterfire/assets/89301122/12123545-1da2-4fa2-bafd-0fd6259d28c6)

### Sample project
[sample_project_google_analytics_bug.zip](https://github.com/firebase/flutterfire/files/13998685/sample_project_google_analytics_bug.zip)

---

## Additional context

I tried to :
• change the `firebase_core` and `firebase_analytics` versions to the lowest I could
• I tried flutter clean
•  I tried to refresh, wait and debug the actual web console of google analytics
•  connected and disconnected to the internet

I believe it has to do with the android implementation of the firebase_analytics plugin

---

### Flutter doctor

<details><summary>
</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.4, on Microsoft Windows [Version 10.0.19045.3930], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.3)
[√] Android Studio (version 2021.1)
[√] Android Studio (version 2021.3)
[√] Android Studio (version 2022.1)
[√] IntelliJ IDEA Community Edition (version 2022.2)
[√] VS Code (version 1.85.1)
[√] Connected device (3 available)
[√] Network resources

• No issues found!
```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
Dart SDK 3.0.3
Flutter SDK 3.10.4
shit_2 1.0.0+1

dependencies:
- cupertino_icons 1.0.6
- dio 5.4.0 [async http_parser meta path]
- firebase_analytics 9.3.8 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 1.24.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection js material_color_utilities meta vector_math sky_engine]

dev dependencies:
- flutter_lints 2.0.3 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection js matcher material_color_utilities me
ta source_span stream_channel string_scanner term_glyph]

dependency overrides:
- firebase_core_platform_interface 4.5.1 [collection flutter flutter_test meta plugin_platform_interface]

transitive dependencies:
- _flutterfire_internals 1.0.2 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- cloud_firestore_platform_interface 5.7.7 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.8.10 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]      
- collection 1.17.1
- fake_async 1.3.1 [clock collection]
- firebase_analytics_platform_interface 3.3.7 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.4.2+7 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_core_web 1.7.3 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- js 0.6.7 [meta]
- lints 2.1.1
- matcher 0.12.15 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.2.0
- meta 1.9.1
- path 1.8.3
- plugin_platform_interface 2.1.8 [meta]
- sky_engine 0.0.99
- source_span 1.9.1 [collection path term_glyph]
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.5.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.2 [collection]
- vector_math 2.1.4
```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the report. I ran the plugin example and will wait until tomorrow to see if the events were captured are not.
Meantime, can you confirm if the events are being printed locally in the console ? ie, events are indeed being fired from plugin side ? This is just to confirm that the issue is with plugin or with firebase console that it is not able to receive the events.

**Comment by Alex-web0** [comment]
> Thanks for the report. I ran the plugin example and will wait until tomorrow to see if the events were captured are not. Meantime, can you confirm if the events are being printed locally in the console ? ie, events are indeed being fired from plugin side ? This is just to confirm that the issue is with plugin or with firebase console that it is not able to receive the events.

I have confirmed that actually, the events are not sent to the server, if you fire them they will not be sent until the app uninstalls

**Comment by Alex-web0** [comment]
@darshankawar Thank you so much, can you provide me with some more details

1) Did you run the example project only without changing any params other than firebase options
2) How much did the event take to appear on the dashboard, you mentioned in another reply that you would "wait for tomorrow" Is that related?
3) Can you please use the real-time tab on Google Analytics, I used it to produce the error in my example and the use case needs the realtime feature to work. Also if it doesn't log the events in real-time, try after logging some events to uninstall the app, they will all appear in one go.

**Comment by darshankawar** [comment]
> 1. Did you run the example project only without changing any params other than firebase options

Yes.



> 2\. How much did the event take to appear on the dashboard, you mentioned in another reply that you would "wait for tomorrow" Is that related?

Somewhat. It usually updates throughout the day periodically. You can read about it [here](https://firebase.google.com/docs/analytics/events?platform=flutter).



> 3\. Can you please use the real-time tab on Google Analytics,

This probably will be beyond the plugin's control, as the data is passed via firebase console to GA.

If you want to confirm really whether the events are indeed being triggered locally or not, you can try to use the adb command like [this](https://stackoverflow.com/a/60915019) and see if it helps in your case or not.
