### ISSUE TITLE
🐛 [firebase_storage/channel_error] Unable to establish connection on channel.

### ISSUE THREAD

**Issue by sickleox2** [firebase/flutterfire#12215]
## Bug report

Trying to access an image from Firebase Storage gives an error everytime I try to access, with any path.

In the rules:

```
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read: if true;
      allow write: if false;
    }
  }
}
```

Using Flutter's future builder when calling this function gives the error in the title which i can't find anything about online except for a closed issue here.

### Sample project

```
FirebaseStorage storage = FirebaseStorage.instance;
Future<Widget> displayImage(String documentId) async {
  print(storage.app.name);
  Reference imageLink =
      storage.ref("ao.jpg"); // this image exists! doesn't work with any path
  print(imageLink);
  final imageUrl = await imageLink.getDownloadURL(); // errors here i think becasue imageUrl doesn't get printed
  print(imageUrl);
  return Image.network(
    imageUrl.toString(),
    errorBuilder: (context, error, stackTrace) => const SizedBox(
      width: 0,
      height: 0,
    ),
  );
}
```

Function gets called here

```
  widgets.add(FutureBuilder<Widget>(
    future: displayImage(documentId),
    builder: (context, snapshot) {
      if (snapshot.hasData) {
        return (snapshot.data!);
      } else if (snapshot.hasError) {
        return Text('${snapshot.error}'); // this line prints the error
      }

      // By default, show a loading spinner.
      return const CircularProgressIndicator();
    },
  ));

```

**Comment by darshankawar** [comment]
@sickleox2 
What platform are you seeing this behavior on ?
I tried with firebase_storage plugin [example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_storage/firebase_storage/example) on Android and it seems to be working fine upon uploading a file.
Can you try the same and check if using it, you still get the same error or not ?

**Comment by sickleox2** [comment]
I’m using the iOS simulator.


Leonardo Mignini

**Comment by darshankawar** [comment]
> I tried with firebase_storage plugin [example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_storage/firebase_storage/example) on Android and it seems to be working fine upon uploading a file.
> Can you try the same and check if using it, you still get the same error or not ?

Did you get a chance to check this ?
