### ISSUE TITLE
firebase_core_web - Null/String error even on 2.11.1

### ISSUE THREAD

**Issue by NeilFawcett1** [firebase/flutterfire#12248]
Am on latest flutter, latest firebase_core and firebase_auth, including the newest update from an hour ago (2.11.1) for firebase_core_web. Flutter doctor is fine.

When calling  idtoken = await FirebaseAuth.instance.currentUser?.getIdToken(false) ?? ''; I still get an exception "expected String but got Null" error, despite the newest update fixing interop migration problems.

Firebase initializes at app start correctly, or without exception anyway. Calling .getIdToken after instance.signInWithCredential causes that String/Null error. I checked that the credential being passed from google sign in is correct-- there is an access and id token received from it. This all worked fine until I updated to the newer versions of firebase and flutter yesterday.

Still all works fine on Android, but web is now broken.

Thanks,
Neil

**Comment by NeilFawcett1** [comment]
I also get the same error with the following code, signing in with emailandpassword, so I know it is nothing to do with google_sign_in:

                                                    try {
                                                      LoadingIndicatorDialog().show(context,"Logging in...");
                                                      await FirebaseAuth.instance
                                                          .signInWithEmailAndPassword(
                                                          email: fieldValues['username'].toString(),
                                                          password: fieldValues['password']
                                                              .toString());
                                                      idtoken =
                                                          await FirebaseAuth.instance.currentUser
                                                              ?.getIdToken(false) ?? '';
                                                    } catch (e) {
                                                      LoadingIndicatorDialog().dismiss();
                                                      NfForms().nfshowDialog(context, "186 - login.dart Error", e.toString());

**Comment by darshankawar** [comment]
@NeilFawcett1 
I tried using auth plugin example running on latest stable and with latest plugin versions on web. I added below line under 
`Future<void> _emailAndPassword() async {` method:

```
final idToken = await FirebaseAuth.instance.currentUser?.getIdToken(false) ?? '';
  print(idToken);
```

And upon trying to login as a test user, it gives me below error:

<img width="582" alt="Screenshot 2024-02-01 at 6 12 22 PM" src="https://github.com/firebase/flutterfire/assets/67046386/8f68e18b-a030-4c70-9848-31fd7fc7c85c">



Is this a correct interpretation of the bug you are reporting ?

**Comment by NeilFawcett1** [comment]
Thanks Lyokone. I updated again to latest firebase_auth_web and firebase_core_web, and applied the above fixes, flutter clean, flutter build web, but still same issue on calling getIdToken. Might take some time to sort out the migration, but appreciate the quick response.

**Comment by NeilFawcett1** [comment]
Actually, now I have applied the fixes, I note that it is working fine for signin with email and password:

await FirebaseAuth.instance
                                                          .signInWithEmailAndPassword(
                                                          email: fieldValues['username'].toString(),
                                                          password: fieldValues['password']
                                                              .toString());
                                                      idtoken =
                                                          await FirebaseAuth.instance.currentUser
                                                              ?.getIdToken(false) ?? '';

But still the same string/null error when I try login with google credentials. (That still works on android but broken on web).
