### ISSUE TITLE
🐛 [cloud_firestore_web] DocumentSnapshot and Timestamp data types no longer consistent in 3.10.3

### ISSUE THREAD

**Issue by dmosdallas** [firebase/flutterfire#12279]
## Bug report

I just upgraded from cloud_firestore_web 3.9.0 --> 3.10.3 (I've not bisected to find the specific version where this issue begins).

In the old version DocumentReferences and Timestamps in the returned `DocumentSnapshot.data()` were always of a type that inherited from [this DocumentReference](https://github.com/firebase/flutterfire/blob/e864acebf72ec94a91a7abb995736a3bbb7b9699/packages/cloud_firestore/cloud_firestore/lib/src/document_reference.dart#L15) and [this Timestamp](https://github.com/firebase/flutterfire/blob/e864acebf72ec94a91a7abb995736a3bbb7b9699/packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/timestamp.dart#L28).

In the latest version, this is no longer true. 

#### DocumentReference
For DocumentReference, it sometimes comes back as the type mentioned above and sometimes as the type defined in [cloud_firestore_web's interop](https://github.com/firebase/flutterfire/blob/e864acebf72ec94a91a7abb995736a3bbb7b9699/packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore.dart#L297)

#### Timestamp
For Timestamp, it sometimes returns as the timestamp type mentioned above and sometimes as a LegacyJavaScriptObject.

I had been type checking the sub-messages in each DocumentSnapshot before casting to the correct type and reading the field, but I no longer can. I now have to blindly read from the dynamic value.

### Steps to reproduce

Fetch a document from firebase that contains either a DocumentReference type field or a Timestamp type field.

I've not figured out the specific scenarios where it chooses which type to return as, but it seems to return either type about half the time for me.

### Expected behavior

A DocumentSnapshot returns DocumentReference and Timestamp fields of a consistent type every time.

### Sample project

Sadly, I do not have a simple project to recap.

**Comment by yarmel** [comment]
> Hi @dmosdallas, I'm not sure exactly what you are experiencing, there was a bug before cloud_firestore_web 3.10.3, where nested fields typed would not be properly restored, but it has been fixed. Checking with this code I get the proper types.
> 
> ```
>   // Add a dcoument to the collection flutter-tests
>   // containing a timestamp and a document reference
>   await FirebaseFirestore.instance
>       .collection('flutter-tests')
>       .doc('conserve-typing')
>       .set({
>     'timestamp': Timestamp.fromDate(DateTime.now()),
>     'reference': FirebaseFirestore.instance.collection('flutter-tests').doc(),
>   });
> 
>   // Get it and check the typing of each field
>   final doc = await FirebaseFirestore.instance
>       .collection('flutter-tests')
>       .doc('conserve-typing')
>       .get();
> 
>   print('Timestamp: ${doc.get('timestamp')}');
>   print('Timestamp: ${doc.get('timestamp').runtimeType}');
> 
>   print('Reference: ${doc.get('reference')}');
>   print('Reference: ${doc.get('reference').runtimeType}');
> ```
> 
> ```
> Timestamp: Timestamp(seconds=1707120167, nanoseconds=514000000)
> Timestamp: Timestamp
> Reference: DocumentReference<Map<String, dynamic>>(flutter-tests/85iCJB6rnGdbTqxO1zRs)
> Reference: _JsonDocumentReference
> ```

Please try to replace your data from 

```
{
    'timestamp': Timestamp.fromDate(DateTime.now()),
    'reference': FirebaseFirestore.instance.collection('flutter-tests').doc(),
  }
```

to

```
{
        'timestamp': Timestamp.fromDate(DateTime.now()),
        'logs': [
          {
            'createdAt': Timestamp.fromDate(DateTime.now()),
          },
        ],
}
``` 
and get the value and type of nested field 'createdAt'. And you will get "Expected a value of type 'Timestamp', but got one of type 'LegacyJavaScriptObject'"

**Comment by Lyokone** [comment]
Thanks I've been able to reproduce with your example
