### ISSUE TITLE
🐛 [Crashlytics] Crashlytics skipped rotating the Install ID during urgent mode because it is run on the main thread, which can't succeed. This can happen if the app crashed the last run and Crashlytics is uploading urgently

### ISSUE THREAD

**Issue by hanxiaofeng** [firebase/flutterfire#12281]
## Bug report

**Describe the bug**
Crashlytics skipped rotating the Install ID during urgent mode because it is run on the main thread, which can't succeed. This can happen if the app crashed the last run and Crashlytics is uploading urgently

flutter android is normal, but ios reports an error

code:

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Non-async exceptions
  FlutterError.onError = (errorDetails) {
    // If you want to record a "non-fatal" exception
    FirebaseCrashlytics.instance.recordFlutterError(errorDetails);
  };
  // Async exceptions
  PlatformDispatcher.instance.onError = (error, stack) {
    // If you want to record a "non-fatal" exception
    FirebaseCrashlytics.instance.recordError(error, stack, fatal: false);
    return true;
  };

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
  firebase_core: ^2.23.0
  firebase_analytics: ^10.7.1
  firebase_crashlytics: ^3.4.5
```

</details>

---

**Comment by darshankawar** [comment]
@hanxiaofeng 
Is this log coming from production app ? Does it throw same log in debug mode locally ?
What flutter version are you on ?

**Comment by darshankawar** [comment]
Can you upgrade your plugin versions and try again to check if the issue persists or not ?
