### ISSUE TITLE
🐛 [firebase_auth_platform_interface, firebase_auth_web?] Still getting the same error when calling GoogleAuthProvider, saying expected String got Null. 

### ISSUE THREAD

**Issue by NeilFawcett1** [firebase/flutterfire#12282]
Latest flutter, dart, and firebase_core 2.25.3, firebase_core_web 2.11.3, firebase_auth_web 5.9.3.

Still getting the "expected string got null" error when calling:

                                                      final credential = GoogleAuthProvider
                                                          .credential(
                                                        accessToken: googleAuth?.accessToken,
                                                        idToken: googleAuth?.idToken,
                                                      );

This was closed as fixed, but it hasn't been fixed on Web.

**Comment by NeilFawcett1** [comment]
Just did a completely fresh install of flutter, dart, firebase all latest versions as of 10 mins ago on my laptop, and recompiled. Same error on Web, but works for Android. It definitely hasn't been fixed.

**Comment by Lyokone** [comment]
Let me have a look.

**Comment by Lyokone** [comment]
@NeilFawcett1, I'm not able to reproduce, if you try the example project in `packages/firebase_auth/firebase_auth/example` do you also have this issue? I'll need a complete example from you to be able to reproduce this.

**Comment by NeilFawcett1** [comment]
Hi Lyokone, thanks for the reply, I'll do an empty flutter app to try and reproduce.
