### ISSUE TITLE
🐛 [firebase_analytics] [Android Only] screen_view event is not fired when transitioning to the same screen using pushAndRemoveUntil.

### ISSUE THREAD

**Issue by ShuheiSuzuki-07** [firebase/flutterfire#12302]
## Bug report

**Describe the bug**
 screen_view event is not fired when transitioning to the same screen using pushAndRemoveUntil.

- First, prepare PageA, which calls setCurrentScreen when it detects a didPush and then calls the screen_view event.
- Next, with PageA displayed (i.e., screen_view event has been fired), Navigator's pushAndRemoveUntil is used to transition to the same PageA.
- Finally, the new PageA is pushed and setCurrentScreen is called, but the screen_view event is not fired.

This bug only occurs on Android.

### Steps to reproduce

- First, prepare PageA, which calls setCurrentScreen when it detects a didPush and then calls the screen_view event.
- Next, with PageA displayed (i.e., screen_view event has been fired), Navigator's pushAndRemoveUntil is used to transition to the same PageA.
- Finally, the new PageA is pushed and setCurrentScreen is called, but the screen_view event is not fired.

At this point, Firebase logs the following to the console
"Ignoring call to log screen view event with duplicate parameters."

Note: This event does not occur simply by firing two or more consecutive screen_view events with the same screen name. A transition using pushAndRemoveUntil is required.

### Expected behavior

As with iOS, screen_view events are fired even when the transition to the same screen is doubled.

### Sample project

We do not have a minimum project available.

---

## Additional context

The first thing I want to know is if this is a specification.
---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.3.10, on macOS 14.0 23A344 darwin-x64, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.86.0)
[✓] Connected device (3 available)
    ! Error: Browsing on the local area network for iPhone13. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] HTTP Host Availability
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by darshankawar** [comment]
@ShuheiSuzuki-07 
Can you check [this](https://github.com/firebase/firebase-android-sdk/issues/3788) and see if it helps in your case or not ?

**Comment by ShuheiSuzuki-07** [comment]
@darshankawar 
Thanks for the reply.

It seems that the event in the link you provided is also due to duplicate parameters. However, I am Flutter app. Only MainActivity exists in my Flutter app. So it seems to be a little different.

**Comment by darshankawar** [comment]
Thanks for the update @ShuheiSuzuki-07 
It seems you are on older version of the framework. Please upgrade to latest stable and also use latest versions of the flutterfire plugins and re-run your scenario to check if issue still persists or not.

**Comment by ShuheiSuzuki-07** [comment]
@darshankawar 
Thank you.
I updated to the latest plugin and tried it. However, the event occurs.
Was this an issue that should have been fixed?

**Comment by darshankawar** [comment]
Thanks for the update and sorry for delay to comeback to this.
Can you provide us a runnable reproducible code sample that we can use to verify this further ?

**Comment by ShuheiSuzuki-07** [comment]
We are still getting ready, sorry.

**Comment by ShuheiSuzuki-07** [comment]
Sorry, we are still getting ready.
