### ISSUE TITLE
🐛 [firebase_auth_web] signInWithEmailAndPassword returns unknown error code instead of invalid-credential

### ISSUE THREAD

**Issue by rohansohonee1** [firebase/flutterfire#12309]
## Bug report

**Describe the bug**
NOTE: The firebase project has email enumeration protection enabled.

The signInWithEmailAndPassword is returning unknown as the error code when entering wrong email or password.
```
[firebase_auth/unknown] An unknown error occurred: FirebaseError: Firebase: The supplied auth credential is incorrect, malformed or has expired. (auth/invalid-credential).
```

### Steps to reproduce

1. provide a wrong email or password to the signInWithEmailAndPassword function
2. print the error code from the error object

```dart
try {    
      await FirebaseAuth.instance.signInWithEmailAndPassword(email: emailId, password: password);
    } catch (error) {
      print(error);
    }
```

### Expected behavior

The error code returned should be invalid-credential.
On android platform it is working.

## Additional context

This function is checking if there is an error.
https://github.com/firebase/flutterfire/blob/7cae803a3f5e146cd53b2a313b61417a12de52dc/packages/firebase_auth/firebase_auth_web/lib/src/utils/web_utils.dart#L19

---

### Flutter doctor

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.6, on macOS 12.7.3 21H1015 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.86.0)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
Dart SDK 3.2.3
Flutter SDK 3.16.6

dependencies:
- firebase_auth 4.17.4 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.25.4 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_auth_web 5.9.4 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser js meta web]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.11.4 [firebase_core_platform_interface flutter flutter_web_plugins js meta web]

```

</details>

---

**Comment by JishnuM** [comment]
Not an expert, but the check [here](https://github.com/firebase/flutterfire/pull/12145/files#r1483731502) seems incorrect to me
