### ISSUE TITLE
🐛 [Firebase Analytics] - Third-party cookie will be blocked

### ISSUE THREAD

**Issue by wer-mathurin** [firebase/flutterfire#12308]
## Bug report

Just wondering if this warning will cause problem in the future. 

### Steps to reproduce
Just deploy the firebase_analytics example in Firebase hosting
Go to the website and you will get this in the console:

<img width="1455" alt="image" src="https://github.com/firebase/flutterfire/assets/39314023/54041888-3f60-4fc2-bd2f-fa671a5e904d">

### Expected behavior

I'm not sure if this expected or not

</details>

---

**Comment by darshankawar** [comment]
@wer-mathurin 
Check if [this](https://developers.google.com/privacy-sandbox/3pcd/prepare/audit-cookies) helps.
Also, this doesn't seem to be specific to firbase_analytics plugin. I suggest you to reach out to firebase support for this.
