### ISSUE TITLE
🐛 [fireabase_auth] On the latest versions the login error code is always "unknown"

### ISSUE THREAD

**Issue by Macacoazul01** [firebase/flutterfire#12313]
## Bug report

**Describe the bug**
On older versions, if an error occured during the login proccess, an error code was returned explaining what happened (like 'weak-password','email-already-in-use'....)

With `firebase_auth: 4.17.4` all we have is `code: "unknown"` independent of the error.

It is possible to get the error from the message: `"An unknown error occurred: FirebaseError: Firebase: The password is invalid or the user does not have a password. (auth/wrong-password)."`

But why should we do this if the code already exists and is an easier option?

### Steps to reproduce

1. Force a login error in a project with `firebase_auth: 4.17.4` 

### Expected behavior

The error code explaining what happened as it was on older versions.

Error message:
![image](https://github.com/firebase/flutterfire/assets/57464965/dfb5bc4b-794f-4564-b20f-fd957636e66f)

using flutter web `Flutter 3.16.9 • channel stable`

**Comment by darshankawar** [comment]
@Macacoazul01 
What platform are you seeing this behavior on ? 
There was a recent [issue](https://github.com/firebase/flutterfire/issues/12309) and fix made that you can check and see if helps in your case or not.

**Comment by Macacoazul01** [comment]
On web

**Comment by darshankawar** [comment]
> There was a recent [issue](https://github.com/firebase/flutterfire/issues/12309) and fix made that you can check and see if helps in your case or not.

Did you get a chance to look at this ?

**Comment by ReversedHourglass** [comment]
Faced the same issue on web build, downgraded to a lower version for now.



> > There was a recent [issue](https://github.com/firebase/flutterfire/issues/12309) and fix made that you can check and see if helps in your case or not.
> 
> Did you get a chance to look at this ?

This has not been published to pub.dev so did not tried it as a fix but I would say that it looks like it, may be the fix we are looking for

**Comment by Macacoazul01** [comment]
> > There was a recent [issue](https://github.com/firebase/flutterfire/issues/12309) and fix made that you can check and see if helps in your case or not.
> 
> Did you get a chance to look at this ?

Waiting for it to be published. Any expected date?

**Comment by bekturovv13** [comment]
Sorry, I just wanted to ask. The Internet does not help and even in closed problems I did not find the answer. How to process:
PlatformException (PlatformException(ERROR_INVALID_VERIFICATION_CODE, The verification code from SMS/TOTP is invalid. Please check and enter the correct verification code again., {}, null))

Nothing helps, I tried using

(PlatformException, FirebaseAuthException,
Exception)

try/catch doesn't handle the error (doesn't catch at all)

**Comment by russellwheatley** [comment]
Check out the latest [version of firebase_auth](https://pub.dev/packages/firebase_auth), this has been fixed 👍
