### ISSUE TITLE
🐛 [firebase_messaging] remote message intent action keys

### ISSUE THREAD

**Issue by flbaue** [firebase/flutterfire#12317]
On Android
When my app is in the background
And I (the user) dismiss a just received push notification via the system menu

Actual:
In my onBackgroundMessageReceived callback I get a RemoteMessage object that contains no meaningful data.

Expected:
I would like to get the intent action key (com.google.firebase.messaging.NOTIFICATION_DISMISS) so that I understand the reason of the event. https://developers.google.com/android/reference/com/google/android/gms/cloudmessaging/CloudMessagingReceiver.IntentActionKeys

I made a quick debug session and noticed that the FlutterFirebaseMessagingUtils remoteMessageToMap method ignores the action intent and tries to create the typical message map.

**Comment by Lyokone** [comment]
After discussing it internally, we decided not to support this feature since it would be hard to align the behavior without breaking current usage. You can check other plugins in the Flutter/Dart ecosystem to support this usecase.
