### ISSUE TITLE
[firebase_messaging]: onBackgroundMessage() won't work after Reboot on iOS

### ISSUE THREAD

**Issue by Gobmichet** [firebase/flutterfire#12324]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you aware of the differences between iOS and Android background message handling?

- [X] I understand that iOS and Android background messages behave differently, and I've designed my application with that in mind.

### Do you have an active Apple Developer account?

- [X] I have an active Apple Developer account.

### Are you using a physical iOS device to test background messages?

- [X] I am using a physical iOS device to test background messages.

### Have you enabled "Remote Notifications" & "Background Mode" (Checking options for "Background Processing" & "Remote Notifications") in your app's Xcode project?

<img width="688" alt="BG modes" src="https://github.com/firebase/flutterfire/assets/3100468/ed00009b-798f-424d-96f4-12d099477cf3">

### Have you created an APNs key in your Apple Developer account & uploaded this APNs key to your Firebase console?

![APNKeys](https://github.com/firebase/flutterfire/assets/3100468/4c95b4ff-ea81-4a0c-9651-dbc34813fc00)

### Have you disabled method swizzling for Firebase in your app?

no such thing in our info.plist

### Are you sending messages to your app from the Firebase Admin SDK?

Also tested with the project you recommend (flutterfire's nodeJS Firebase admin SDK script in previous section) :
![ObjetNotif](https://github.com/firebase/flutterfire/assets/3100468/bce9915a-dd5c-4470-816c-c868a1d2c12a)

Otherwise, we use the Java firebase library :
```
<dependency>
<groupId>com.google.firebase</groupId>
<artifactId>firebase-admin</artifactId>
<version>9.2.0</version>
</dependency>
```
like :
![Springboot_SendMsg](https://github.com/firebase/flutterfire/assets/3100468/3f0f38ae-4f6e-4cbc-ab06-eaae58988584)

### Have you requested permission from the user to receive notifications?

- [X] I have the relevant permission to receive notifications.

### Have you used the 'Console' application on your macOS device to check if the iOS device's system is throttling your background messages?

![MacConsole](https://github.com/firebase/flutterfire/assets/3100468/fcfd82a7-444a-43b9-ac56-5d2b0148ba3b)

### Additional context and comments

Briefly :
- Our app is in Flutter

- we make BG code to persist the notification in databse so that we can show it in an "history" screen (works 100% fine on Android and sometimes on iOS)

- Android part works 100% of the time :
-- Notifs received 100% of the time
-- Notifs are 100% (BG) handled whether the app is in foreground, background, killed/terminated state, and even after device reboot.

- iOS part "partly" works :
-- Notifs received 100% of the time !
-- Notifs are (BG) Handled when app is in foreground, background and even if we kill/terminate the app after this by switching up the app in the recent apps list, notifications are still received and BG handled.

BUT AFTER THE IPHONE's REBOOT :
=======================
- The BG handling part is "broken..." and just won't work anymore.
- We correctly receive the notification (sometimes with seconds of latency...)
- BUT the BG code is ignored ! 

and as we can see in the MacOs console stackTrace screenshot :
> response : { Decision : Must Not Proceed , Score : 0.00  [...]  }

What are we missing so that the BG part still works after the device's reboot on iOS !? 
Did i miss a configuration part or something ? a parameter maybe ? (We do use content-available : true and priority ones)

How to transform this "must not proceed" decision from iOS when receiving the notification (that, again, we do receive on the phone,) in  "can proceed" or "must proceed" so that the background callback code works normally !?

Any help would be MUCH appreciated ! (^_^)

Thanks in advance.

**Comment by darshankawar** [comment]
@Gobmichet 
Can you try [this](https://github.com/firebase/flutterfire/issues/10082#issuecomment-1434029834) and see if it helps in your case ?
Also, can you provide the iOS device details you are using ?

**Comment by darshankawar** [comment]
Thanks for the update. I am not sure what should be the expected behavior after rebooting the device, ideally, it should resume the actions as before, but wondering if in this case, the native ios comes into picture or not.

I'll keep the issue open and label for team's input.

**Comment by Gobmichet** [comment]
Thanks in advance, we're really stuck in here and think we do have already tried everything possible :(

**Comment by Gobmichet** [comment]
yes i do ;)

indeed the only way to have the background code to work is to first receive a notification in foreground (app opened)
then it works UNTIL you reboot the iPhone.

After reboot nothing works anymore until a first notif is again received when app is opened.
