### ISSUE TITLE
🐛 [cloud_firestore] Bring back Dart 2 support.

### ISSUE THREAD

**Issue by larssn** [firebase/flutterfire#12323]
## What feature would you like to see?

I'd like to request Dart 2 support back.

When resolving versions higher than 4.14.0, we apparently need Dart 3:
`Because cloud_firestore >=4.15.4 depends on cloud_firestore_web >=3.10.0 which requires SDK version >=3.2.0 <4.0.0, cloud_firestore >=4.15.4 is forbidden.`

We're still on Dart 2.10 and have a bunch of non-null safe code which isn't going anywhere atm.

I realize there might be very valid reasons for ditching Dart 2 support, but I figured I'd at least ask.

EDIT:
On further inspection, it seems that "web" is the main culprit. FYI: we're not using web.

**Comment by darshankawar** [comment]
Not sure if support back for Dart 2 would be feasible, but I'll keep the issue open and label for team's attention.

**Comment by larssn** [comment]
@darshankawar It's not that long ago that Dart 3 was release, so it seems premature to ditch Dart 2 so soon.

I'd like to know why that decision was made, if you don't mind.

**Comment by andrewalexanderbalogh** [comment]
I'd also like to second continued support for Dart 2.

But besides that, I'd like to request that the _Minimum Versions_ as published for Firebase packages 
actually reflect those being enforced.

~ e.g. the pub.dev listing for `cloud_firestore` implies at least Dart SDK 2.18 should be supported
![image](https://github.com/firebase/flutterfire/assets/17296403/d9e77cfa-f33a-4a69-bf0b-8dc179eb2185)


As does the `pubspec.yaml` file for the latest publish version on the `master` branch 
https://github.com/firebase/flutterfire/blob/f24d0a76ff384cf40605ae59af705b2854e53ba7/packages/cloud_firestore/cloud_firestore/pubspec.yaml#L14

It should not be the case that we only find out the dependancies do not match upon attempting to get/update versions.
