### ISSUE TITLE
🐛 [firebase_messaging] Custom notification sound.

### ISSUE THREAD

**Issue by tonujewel** [firebase/flutterfire#12333]
## Can you please add custom notification sound feature.

We have to use location notification for custom sound.

**Comment by danagbemava-nc** [comment]
You should be able to use this on iOS, for macOS there seems to be an issue with it. See https://github.com/firebase/flutterfire/issues/8772. On android, this isn't something that the plugin can control. See https://github.com/firebase/flutterfire/issues/4521#issuecomment-1040362540

If you are facing a particular issue on platforms other than android, please file a new issue and provide all the relevant details. 

Closing from here. 

Thank you
