### ISSUE TITLE
Class constructor IndexedDBLocalPersistence cannot be invoked without 'new'

### ISSUE THREAD

**Issue by jiharal** [firebase/flutterfire#12345]
TypeError: Class constructor IndexedDBLocalPersistence cannot be invoked without 'new'
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 462:37   _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 555:39   dcall
https://www.gstatic.com/firebasejs/10.7.0/firebase-auth.js 1:48595                 _getInstance
https://www.gstatic.com/firebasejs/10.7.0/firebase-auth.js 1:144495                _initializeAuthInstance
https://www.gstatic.com/firebasejs/10.7.0/firebase-auth.js 1:144643                instanceFactory
https://www.gstatic.com/firebasejs/10.7.0/firebase-app.js 977:39                   getOrInitializeService
https://www.gstatic.com/firebasejs/10.7.0/firebase-app.js 921:31                   initialize
https://www.gstatic.com/firebasejs/10.7.0/firebase-auth.js 1:68877                 initializeAuth
dart-sdk/lib/_internal/js_shared/lib/js_util_patch.dart 110:66                     callMethod$
packages/firebase_auth_web/src/interop/auth.dart 24:40                             getAuthInstance
packages/firebase_auth_web/firebase_auth_web.dart 92:43                            <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                 runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5                 _async
packages/firebase_auth_web/firebase_auth_web.dart 91:33                            <fn>
packages/firebase_core_web/src/firebase_core_web.dart 323:41                       <fn>
dart-sdk/lib/internal/iterable.dart 403:20                                         moveNext
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 1140:20  next
dart-sdk/lib/async/future.dart 516:16                                              wait
packages/firebase_core_web/src/firebase_core_web.dart 315:18                       initializeApp
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                 <fn>
dart-sdk/lib/async/zone.dart 1661:54                                               runUnary
dart-sdk/lib/async/future_impl.dart 162:18                                         handleValue
dart-sdk/lib/async/future_impl.dart 838:44                                         handleValueCallback
dart-sdk/lib/async/future_impl.dart 867:13                                         _propagateToListeners
dart-sdk/lib/async/future_impl.dart 643:5                                          [_completeWithValue]
dart-sdk/lib/async/future.dart 524:22                                              <fn>
dart-sdk/lib/async/zone.dart 1661:54                                               runUnary
dart-sdk/lib/async/future_impl.dart 162:18                                         handleValue
dart-sdk/lib/async/future_impl.dart 838:44                                         handleValueCallback
dart-sdk/lib/async/future_impl.dart 867:13                                         _propagateToListeners
dart-sdk/lib/async/future_impl.dart 643:5                                          [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 713:7                                          callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                                   _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                                    _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7                 <fn>

**Comment by Macacoazul01** [comment]
related to #12344

**Comment by ghecreagheorghe** [comment]
I encounter the same issue after upgrading to 3.19. Please fix asap.

**Comment by tyler-jewell** [comment]
Same issue after 3.19 upgrade.

**Comment by VIP-Dev-Invisible** [comment]
I am facing the same issue after the 3.19 upgrade. Any solutions ?

**Comment by ZoftPranav** [comment]
encountered issue after 3.19 upgrade , please fix asap

**Comment by simeonangelov94** [comment]
flutter run -d chrome --release 
flutter run -d chrome --profile

You can run if you don't want to downgrade.

**Comment by ZoftPranav** [comment]
> flutter run -d chrome --release flutter run -d chrome --profile
> 
> You can run if you don't want to downgrade.

what is the root cause of this issue?

**Comment by simeonangelov94** [comment]
Looks like the new Flutter version is not working properly with the Firebase package. Waiting for update.
https://github.com/firebase/flutterfire/issues/12291

**Comment by omegaui** [comment]
It's been 3 days waiting ... our projects have pending bugs and features to be implemented, please fix this asap.

**Comment by ZoftPranav** [comment]
> It's been 3 days waiting ... our projects have pending bugs and features to be implemented, please fix this asap.

same here...

**Comment by VIP-Dev-Invisible** [comment]
i think.  they need more time than expected.

**Comment by vijayvaghela72** [comment]
waiting for the new release !

**Comment by silexcorp** [comment]
> flutter run -d chrome --release flutter run -d chrome --profile
> 
> You can run if you don't want to downgrade.



> flutter run -d chrome --release flutter run -d chrome --profile
> 
> You can run if you don't want to downgrade.

Thanks, It's a good solution while I wait for an update :D

**Comment by simeonangelov94** [comment]
> > flutter run -d chrome --release flutter run -d chrome --profile
> > You can run if you don't want to downgrade.
> 
> > flutter run -d chrome --release flutter run -d chrome --profile
> > You can run if you don't want to downgrade.
> 
> Thanks, It's a good solution while I wait for an update :D

Update your fibrease_auth to the latest version - 4.17.5

**Comment by Johnnvula** [comment]
Same isso

**Comment by shehroz2260** [comment]
same here

**Comment by PRASHANTKUMAR2004** [comment]
please help i am also in this condition

**Comment by Johnnvula** [comment]
To solve this error, we need to downgrade
