### ISSUE TITLE
🐛 [firebase_messaging] Mute notification sound in background and terminated state 

### ISSUE THREAD

**Issue by anmolgupta321** [firebase/flutterfire#12341]
Muting Notification Sound in Background and Terminated State with Firebase Messaging

Issue Description: Implement functionality to mute notification sounds when the app is in the background or terminated using Firebase Messaging. This enhancement will improve user experience by reducing interruptions from notifications. Follow the provided tutorial for step-by-step instructions.

**Comment by darshankawar** [comment]
@anmolgupta321 
Are you looking for this implementation on Android or iOS ?
For Android, check if [this](https://developer.android.com/develop/ui/views/notifications#ManageChannels) helps in your case or not.

Also, check using this method, if it is achievable already or not.

https://github.com/firebase/flutterfire/blob/376310f3437476b249e1461ac7a64cbcc1abe943/packages/firebase_messaging/firebase_messaging/example/lib/permissions.dart#L28
