### ISSUE TITLE
firebase_core_web

### ISSUE THREAD

**Issue by guvenacar** [firebase/flutterfire#12344]
## Bug report

I am getting this error when i was run flutter/firebase application on vscode.

DEBUG CONSOLE:

    `/C:/Users/gacwi/AppData/Local/Pub/Cache/hosted/pub.dev/firebase_core_web-2.11.4/lib/src/firebase_core_web.dart:152:43:` 
    Error: The getter 'winydowVar' isn't defined for the class 'FirebaseCoreWeb'.
     - 'FirebaseCoreWeb' is from 'package:firebase_core_web/firebase_core_web.dart' 
     ('/C:/Users/gacwi/AppData/Local/Pub/Cache/hosted/pub.dev/firebase_core_web-2.11.4/lib/firebase_core_web.dart').
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'winydowVar'.
            globalContext.delete('ff_trigger_$winydowVar'.toJS);
                                              ^^^^^^^^^^
    Failed to compile `application.`

I asked a more detailed question on stackoverflow. Since I couldn't find an answer there, I wanted to ask here too.

https://stackoverflow.com/questions/78009138/i-cant-run-my-flutter-firebase-projects-in-vscode

**Comment by Macacoazul01** [comment]
Here i'm having similar problems since updating to flutter 3.19

**Comment by kaumudpa** [comment]
+1

**Comment by tahsin-emre** [comment]
+1

**Comment by ZoftPranav** [comment]
+1

**Comment by russellwheatley** [comment]
@guvenacar - that is odd, if you look at the line: https://github.com/firebase/flutterfire/blob/master/packages/firebase_core/firebase_core_web/lib/src/firebase_core_web.dart#L152

you will note the variable name is `windowVar` not `winydowVar`. I would `flutter clean` and `flutter pub get` and it should change.

**Comment by guvenacar** [comment]
[russellwheatley](https://github.com/russellwheatley) Could such a thing be possible? It's really weird. 

I've already done what you said many times. flutter clean and flutter pub get. But i am formating my pc now. I can not check this steps again.

**Comment by kaumudpa** [comment]
@guvenacar Maybe buying a new machine might help! ;)
