### ISSUE TITLE
🐛 [firebase_auth_web] Minimum dart SDK constraint

### ISSUE THREAD

**Issue by deepak-agendaboa** [firebase/flutterfire#12354]
The minimum constraint defined in the firebase_auth_web is 3.3.0 which is forcing to use Flutter 3.19.
https://github.com/firebase/flutterfire/blob/376310f3437476b249e1461ac7a64cbcc1abe943/packages/firebase_auth/firebase_auth_web/pubspec.yaml#L8

However in the other packages such as firebase_core, firebase_storage, etc, it is 3.2.0
https://github.com/firebase/flutterfire/blob/376310f3437476b249e1461ac7a64cbcc1abe943/packages/firebase_core/firebase_core_web/pubspec.yaml#L8

**Comment by deepak-agendaboa** [comment]
> This will be incompatible with #12353
> 
> As web v0.5.0 requires minimum Dart v3.3: https://github.com/dart-lang/web/blob/a54a1f0447979f9a3ea220199eca849ffb214e91/pubspec.yaml#L1-L7

But firebase_auth_web depends on web as `web: '>=0.3.0 <0.5.0'`
It is not supporting version 0.5.0. Also it has a minimum constraint as 0.3.0. So depending on the Flutter version specific web package version will be used.

**Comment by davidmigloz** [comment]
You are right. There isn't a need to require Dart 3.3 until a future Flutter stable version is released requiring web v0.5.0.
