### ISSUE TITLE
upgrade js dependency to js 0.7.1

### ISSUE THREAD

**Issue by Yoda-Man** [firebase/flutterfire#12355]
The package currently runs on  js ^0.6.3 which is really old

**Comment by deepak-agendaboa** [comment]
The recommendation is to use `dart:js_interop` as mentioned here 
- https://dart.dev/interop/js-interop/package-web
- https://dart.dev/interop/js-interop/past-js-interop

**Comment by timmolter** [comment]
yes, please update s it clashes with `flutter_native_splash`.
```
Because no versions of flutter_native_splash match >2.3.13 <3.0.0 and flutter_native_splash 2.3.13 depends on js ^0.7.1, flutter_native_splash ^2.3.13 requires js ^0.7.1.
And because firebase_core >=2.25.4 depends on firebase_core_web ^2.11.4 which depends on js ^0.6.3, flutter_native_splash ^2.3.13 is incompatible with firebase_core >=2.25.4.
So, because readable_english_app depends on both firebase_core ^2.25.4 and flutter_native_splash ^2.3.13, version solving failed.
```

**Comment by Lyokone** [comment]
We are in the process of moving to dart:js_interop. Once all packages are migrated we will remove the js dependency.

**Comment by Lyokone** [comment]
Closing in favor of https://github.com/firebase/flutterfire/issues/12466
