### ISSUE TITLE
🐛 [FirebaseMessaging] disableNetwork and enableNetwork

### ISSUE THREAD

**Issue by haidarmehsen** [firebase/flutterfire#12368]
### Use case

For my app, which completely relies on firebase fcm service to function, when the internet connection is intermittent, firebase messaging has a delay of couple of minutes to get to receive messages again, which makes my app completely useless.

I already asked a [question](https://stackoverflow.com/questions/77964208/flutter-app-not-receiving-notification-from-firebase-in-specific-cases) about this with no answers, and opened a [discussion](https://github.com/firebase/flutterfire/discussions/12360) about it in flutterfire repo, and searched alot for a way to force firebase to reconnect, but with no luck.

Currently the only solution I am facing is to change firebase fcm service and use another notifications provider, which is so bad because I will need to make alot of changes to my code on FE and BE.

It would be very nice if firebase had an option to force it to reconnect in this case.

- Note: my app is listening to firebase messages in the foreground, and the app is always on charger and screen is on and the app is always opened, so this is NOT A BACKGROUND MESSAGES ISSUE.

- Note : this request is similar to[ #21300](https://github.com/flutter/flutter/issues/21300) if I understand correctly

Thank you. 

### Proposal

- Enable a way to prompt firebase library to reconnect if the connection was gone then restored.

**Comment by darshankawar** [comment]
@haidarmehsen 
As I understand, any action related to connection reset or restore / delay is out of control from plugin side, because the plugins are thin wrappers around native firebase sdks and share data between dart. If there's any connection reset occurs while sharing data, then it would probably fall under native / server side to restore which dart can handle from plugin side.
You may either need to raise this in respective sdks or reach out to firebase support.

**Comment by darshankawar** [comment]
I'll label this for team's input whether this is feasible from plugin's point of view or not.

**Comment by Lyokone** [comment]
FCM is a service running at OS level, that can be impacted by Network (especially if intermittent). When running `FirebaseMessaging.onMessage` you are receiving all the messages sent by the OS to the app. 
To ensure that you are debugging messaging efficiently, try running the app in release mode. Depending on your phone OS Version / Maker it can impact messages delivery.
