### ISSUE TITLE
🐛 [auth] New exception `invalid-credential` for `signInWithEmailAndPassword` not mapped in the docs 

### ISSUE THREAD

**Issue by feinstein** [firebase/flutterfire#12365]
There's a new exception `invalid-credential` since email enumeration protection was activated, but the `signInWithEmailAndPassword` docs doesn't include it in the exceptions list.

**Comment by darshankawar** [comment]
Thanks for raising this @feinstein 
Let's track this in the original issue https://github.com/firebase/flutterfire/issues/3273, I'll close this in favor of it.

**Comment by feinstein** [comment]
Ah wow, that's from 4 years ago lol, good digging.
