### ISSUE TITLE
[firebase_auth] Because firebase_auth depends on firebase_auth, version solving failed.

### ISSUE THREAD

**Issue by DilshanMadhushanka2003** [firebase/flutterfire#12372]
![Screenshot (7)](https://github.com/firebase/flutterfire/assets/160840783/f5c690f7-52db-487d-b382-18dabd69a689)

**Comment by danagbemava-nc** [comment]
You can't have your project name be the same as a plugin you want to use. Change the name of your project or create a new project with a different name. 

Closing as this is not a firebase issue
