### ISSUE TITLE
🐛 [firestore] `set` with merge true should not send data that has not changed in local cache.

### ISSUE THREAD

**Issue by cedvdb** [firebase/flutterfire#12397]
## Bug report

**Describe the bug**

When using `_ref.set(data, SetOptions(merge: true))`, all properties will be sent over the network even if the locally persisted version contained some of those properties. 

For example:

  - locally persisted object `{ windows: 1, bathrooms: 1, toilets 1 }`
  - `ref.set({ windows: 1, bathrooms: 1, toilets 2 }, , SetOptions(merge: true)` => sends `{ windows: 1, bathrooms: 1, toilets 2 }` over the network.
  - In the above there was no need to send `{ windows: 1, bathrooms: 1}` 

The issue with this is that this might introduce unintended overwrites in the event that two users try to update the same record at the same time. (EG: with a `copyWith`).

I believe that concerns all underlying sdks, but I tested web.
 
### Steps to reproduce

Here is an example where an user overrides an update from another user

https://github.com/cedvdb/firebase-repro/tree/firestore_merge

```dart
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';

import 'firebase_options.dart';

void main() async {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  FirebaseFirestore.instance.settings =
      const Settings(persistenceEnabled: true);

  final house = House(windows: 1, bathrooms: 1, toilets: 1);

  final housesRef =
      FirebaseFirestore.instance.collection('houses').withConverter(
    fromFirestore: (snapshot, options) {
      final data = snapshot.data();
      if (data == null) return null;
      return House.fromMap(data);
    },
    toFirestore: (value, options) {
      return value?.toMap() ?? {};
    },
  );

  //  initial save
  await housesRef.doc('house-id').set(house);

  await Future.wait([
    // user 1 update
    housesRef.doc('house-id').set(house.copyWith(toilets: 2)),
    // user 2 update
    housesRef.doc('house-id').set(house.copyWith(windows: 2)),
  ]);

  print('done');

  // expected result: { bathrooms: 1, toilets: 2, windows: 2 }
  // actual result: variable
}

class House {
  final int windows;
  final int bathrooms;
  final int toilets;

  House({
    required this.windows,
    required this.bathrooms,
    required this.toilets,
  });

  House copyWith({
    int? windows,
    int? bathrooms,
    int? toilets,
  }) {
    return House(
      windows: windows ?? this.windows,
      bathrooms: bathrooms ?? this.bathrooms,
      toilets: toilets ?? this.toilets,
    );
  }

  Map<String, dynamic> toMap() => {
        'windows': windows,
        'toilets': toilets,
        'bathrooms': bathrooms,
      };

  factory House.fromMap(Map<String, dynamic> map) {
    return House(
      windows: map['windows'],
      bathrooms: map['bathrooms'],
      toilets: map['toilets'],
    );
  }
}
```

### Expected behavior

The local cache should be checked against and properties that are the same as in the local cache should not be sent over the network to avoid unintended overrides between users.

### Sample project

[Here is a sample project, add your own firebase config before running it](https://github.com/cedvdb/firebase-repro/tree/firestore_merge)

**Comment by darshankawar** [comment]
@cedvdb 
Can you check if something like https://github.com/firebase/flutterfire/issues/11149 would help to avoid the behavior you are reporting ?

**Comment by cedvdb** [comment]
@darshankawar I don't see how that issue is related.

**Comment by russellwheatley** [comment]
Hey @cedvdb - This isn't something that should be handled by FlutterFire. It is for the firebase-sdks to implement if at all. FlutterFire is a thin wrapper around the SDKs. I would recommend filing an issue with [Firebase support](https://firebase.google.com/support/troubleshooter/contact) if you wish to see these changes across all Firebase SDKs.
