### ISSUE TITLE
🐛 [firebase_analytics] Firebase analytics doesn't init on web release, only in debug

### ISSUE THREAD

**Issue by bypass112** [firebase/flutterfire#12395]
## Bug report

**Describe the bug**
Having a Flutter Web app in Release mode will fail Firebase.initializeApp with: **PlatformException(channel-error, Unable to establish connection on channel., null, null)**

### Steps to reproduce

1. Create any Flutter web app
2. Initialize Firebase Analytics with **flutterfire config**
3. Run project in Debug mode -> see that Firebase Analytics connects and sends data to Firebase Console
4. Run project in Realese mode -> see that in Chrome Console the initialise will fail with  **PlatformException(channel-error, Unable to establish connection on channel., null, null)** 

In my tests i wrapped  Firebase.initializeApp in a try catch as follows:
```
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  try{
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch(e){
    print("Firebase init failed");
    print(e);
  }
```
### Expected behavior

Firebase Analytics should init in Web Release Mode

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.8, on Microsoft Windows [Version 10.0.19045.4046], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.3.0)
[√] Android Studio (version 2021.2)
[√] Connected device (3 available)
[√] Network resources

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

Thank you for the help!

**Comment by danagbemava-nc** [comment]
Hi @bypass112, do you get this issue when you host on a hosting site or when you run in release mode locally? 

Can you try upgrading to the latest version of flutter to see if you still experience this issue?

Please also make sure you're using the latest version of firebase_analytics to see if you still experience the issue. 

Thank you

**Comment by bypass112** [comment]
Ok, upgrading Flutter to 3.19.1 from 3.16.8 fixed this from me.
Thank you for the help!
