### ISSUE TITLE
🐛 [firebase_storage] PlatformException after firebase deployment Web

### ISSUE THREAD

**Issue by canavci312** [firebase/flutterfire#12409]
I use Flutter 3.19.1 and `firebase_storage: ^11.6.7`

```
[firebase_storage/channel-error] Unable to establish connection on channel.
main.dart.js:21972 PlatformException(channel-error, Unable to establish connection on channel., null, null)
```
I only use FirebaseStorage with `getDownloadUrl()`, this exception happens when this method is called. 

I cannot reproduce this issue in localhost it works fine.

I use `firebase deploy` to deploy my app to the hosting service and thats when this issue happens.

Note that I didn't configure CORS as in documents it says its only needed for `getData()`

The domain I use is default firebase domain, they are added to whitelist in settings already. 

### Steps to reproduce

1. Use getDownloadUrl() in flutter web app
2. Deploy the app using `firebase deploy`
3. Open the webpage

### Expected behavior

Expected it to show display my image data just like localhost

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.1, on macOS 14.2.1 23C71 darwin-arm64, locale en-MY)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.86.2)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for Can Apple Watch’u. Ensure the device is unlocked and discoverable via Bluetooth. (code -27)
[✓] Network resources

• No issues found!

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
dependencies:
- animated_text_kit 4.2.2 [flutter characters]
- auto_size_text 3.0.0 [flutter]
- cupertino_icons 1.0.6
- equatable 2.0.5 [collection meta]
- firebase_core 2.25.5 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_storage 11.6.7 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_animate 4.5.0 [flutter flutter_shaders]
- flutter_bloc 8.1.4 [bloc flutter provider]
- flutter_color 2.1.0 [flutter]
- video_player 2.8.2 [flutter html video_player_android video_player_avfoundation video_player_platform_interface video_player_web]

dev dependencies:
- flutter_lints 2.0.3 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]

transitive dependencies:
- _flutterfire_internals 1.3.23 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.11.0 [collection meta]
- bloc 8.1.3 [meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- collection 1.18.0
- csslib 1.0.0 [source_span]
- fake_async 1.3.1 [clock collection]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.11.5 [firebase_core_platform_interface flutter flutter_web_plugins js meta web]
- firebase_storage_platform_interface 5.1.10 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.7.1 [_flutterfire_internals async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta web]
- flutter_shaders 0.1.2 [flutter vector_math]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- html 0.15.4 [csslib source_span]
- http 1.2.0 [async http_parser meta web]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- js 0.6.7 [meta]
- leak_tracker 10.0.0 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 2.0.1 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 2.0.1 [leak_tracker matcher meta]
- lints 2.1.1
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.8.0 [collection]
- meta 1.11.0
- nested 1.0.0 [flutter]
- path 1.9.0
- plugin_platform_interface 2.1.8 [meta]
- provider 6.1.1 [collection flutter nested]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- typed_data 1.3.2 [collection]
- vector_math 2.1.4
- video_player_android 2.4.12 [flutter video_player_platform_interface]
- video_player_avfoundation 2.5.6 [flutter video_player_platform_interface]
- video_player_platform_interface 6.2.2 [flutter plugin_platform_interface]
- video_player_web 2.2.0 [flutter flutter_web_plugins video_player_platform_interface]
- vm_service 13.0.0
- web 0.4.2
```

</details>

---

**Comment by darshankawar** [comment]
@canavci312 
Can you try by using the [plugin example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_storage/firebase_storage/example) and see if using it, you still get same error as reported ?

**Comment by canavci312** [comment]
> @canavci312 Can you try by using the [plugin example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_storage/firebase_storage/example) and see if using it, you still get same error as reported ?

I connected the example to a cloud storage and deployed exactly same way. It worked. Its weird that I get that error in my app while doing pretty much the same thing. 
Any idea why this may happen? I still dont understand how it can fetch from cloud storage in my localdev but gives error above when I deploy it

**Comment by darshankawar** [comment]
You may want to reach out in https://github.com/firebase/firebase-tools/issues

**Comment by canavci312** [comment]
I'm not sure what was the issue but I fixed it by copy-pasting my lib to a new flutter project. However, I didn't understand how the example project upload/getdata functions worked without setting server-side cors.  Thank you for responses 🙏
