### ISSUE TITLE
Getting error errors.dart:327 Uncaught (in promise) Error: AbortError: Failed to execute 'subscribe' on 'PushManager': Subscription failed - no active Service Worker  on web browser first time.

### ISSUE THREAD

**Issue by AbhayJadoun** [firebase/flutterfire#12415]
I am getting error errors.dart:327 Uncaught (in promise) Error: AbortError: Failed to execute 'subscribe' on 'PushManager': Subscription failed - no active Service Worker 

fcmToken = kIsWeb
                    ? await _messaging.getToken(
                            vapidKey:
                                'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx') ??
                        ''
                    : await _messaging.getToken() ?? '';
                    
  when kIsWeb is true and code is in main.dart file.  Any help would be appreciated.

**Comment by Lyokone** [comment]
Hello, can you check [this issue](https://github.com/firebase/flutterfire/issues/11954) to see if it helps?
Otherwise, I'm going to need a full example app reproducing the issue.

**Comment by AbhayJadoun** [comment]
@Lyokone I don't have any button on my main.dart and also not required on that page as per my requirement. Then any other workaround for this scenario??

**Comment by Lyokone** [comment]
As said previously, I'll need a full example app for reproducing the issue to understand what is happening.

**Comment by DDSrivatsan** [comment]
here is the service worker file - firebase-messaging-sw.js

importScripts("https://www.gstatic.com/firebasejs/10.8.1/firebase-app-compat.js");
importScripts("https://www.gstatic.com/firebasejs/10.8.1/firebase-messaging-compat.js");

firebase.initializeApp({
     apiKey: "",
     authDomain: "",
     projectId: "",
     storageBucket: "",
     messagingSenderId: "",
     appId: "1",
     measurementId: ""
});

const messaging = firebase.messaging();

below the index.html file - where firebase-messaging-sw.js is registered, and also no firebase sdk/js is included here as they are automatically injected by the flutterfire/cli code


<script>
  window.addEventListener('load', function(ev) {
    // Download main.dart.js
    _flutter.loader.loadEntrypoint({
      serviceWorker: {
        serviceWorkerVersion: serviceWorkerVersion,
      },
      onEntrypointLoaded: function(engineInitializer) {
        engineInitializer.initializeEngine().then(function(appRunner) {
          appRunner.runApp();
          if ('serviceWorker' in navigator) {
            // Specify scope for service worker registration
            const scope = '/'; // Specify your desired scope here
              navigator.serviceWorker.register('firebase-messaging-sw.js', { scope: scope })
                .then(function(registration) {
                  console.log('Service worker registration successful. Scope:', scope);
                  console.log('Registration:', registration);
                })
                .catch(function(error) {
                  console.error('Service worker registration failed:', error);
                });
          }
        });
      }
    });
  });
</script>


login.dart file 

String? fcmToken;

          try {
            fcmToken = await FirebaseMessaging.instance.getToken(
              vapidKey: kIsWeb ? "zzzz" : null
            );

            if (fcmToken != null) {
              print("FCM Token: $fcmToken");
              // You can use the FCM token as needed (e.g., send it to your server, save it locally, etc.)
            } else {
              // Handle the case where the FCM token is null
              print("Error: FCM Token is null");
            }
          } catch (e) {
            // Handle any exceptions that may occur during token generation
            print("Error while generating FCM Token: $e");
          }

here is how i trying to get tokem, works perfetly on android, but in web it takes too long to generated the token, when tried on main.dart file itself it throws the mentioned error by @AbhayJadoun
