### ISSUE TITLE
[firebase_messaging] Support multiple FirebaseApp instances

### ISSUE THREAD

**Issue by SupposedlySam** [firebase/flutterfire#12428]
## What feature would you like to see?

Add support for non-default databases in Firebase Messaging.

Currently the `instanceFor` factory constructor [is private](https://github.com/firebase/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/lib/src/messaging.dart#L38-L42) for firebase_messaging, but is exposed for Auth, Firestore, Functions, and Storage.

Is there a missing a feature that is supported on an underlying SDK? Or is there a feature that you think would be useful to have in FlutterFire?

I'm not sure if it's supported in the underlying SDK yet or not, but it would be great to have!

**Comment by russellwheatley** [comment]
Not supported in either the Firebase iOS or android SDKs, but it appears to be supported on web: https://firebase.google.com/docs/reference/js/messaging_.md?_gl=1*tja5fc*_up*MQ..*_ga*MTIxNDE1NzQ3MS4xNzEwMzIzMTQ2*_ga_CW55HF8NVT*MTcxMDMyMzE0Ni4xLjAuMTcxMDMyMzE0Ni4wLjAuMA..#getmessaging_cf608e1

**Comment by ray007** [comment]
So the JS platform is the only one to actually support multiple messaging instances?

**Comment by russellwheatley** [comment]
Closing this out for now as mentioned previously, multi-app support is only available for web. If the upstream SDKs (apple and android) change, FlutterFire will also support multi-apps for messaging.
