### ISSUE TITLE
🐛 [firebase_app_check] Remove discontinued safetynet app attestation api

### ISSUE THREAD

**Issue by canewsin** [firebase/flutterfire#12423]
### Context: Play Store displaying warning regarding use of safetynet app attestation api

com.google.android.gms:play-services-safetynet:18.0.0
This SDK version has a note from the SDK developer. Here's what the SDK developer told us:

The SafetyNet Attestation API is being discontinued and replaced by the new Play Integrity API. Begin migration as soon as possible to avoid user disruption. The Play Integrity API includes all the integrity signals that SafetyNet Attestation offers and more, like Google Play licensing and better error messaging. Learn more and start migrating at https://developer.android.com/training/safetynet/deprecation-timeline

**Comment by Lyokone** [comment]
Hello @canewsin, Play Integrity is already [implemented in the AppCheck plugin](https://firebase.google.com/docs/app-check/flutter/default-providers#initialize). SafetyNet will not be removed until the end of support in January 2025.
