### ISSUE TITLE
🐛 [firebase_analytics] About the error of upgrading flutter-plugin-loader with 3.19.0

### ISSUE THREAD

**Issue by LiJinJinJIn** [firebase/flutterfire#12438]
After upgrading according to the latest version of flutter 3.19.0
settings.gradle:
pluginManagement {
     def flutterSdkPath = {
         def properties = new Properties()
         file("local.properties").withInputStream { properties.load(it) }
         def flutterSdkPath = properties.getProperty("flutter.sdk")
         assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
         return flutterSdkPath
     }
     settings.ext.flutterSdkPath = flutterSdkPath()

     includeBuild("${settings.ext.flutterSdkPath}/packages/flutter_tools/gradle")

     repositories {
         google()
         mavenCentral()
         gradlePluginPortal()
     }
}

plugins {
     id "dev.flutter.flutter-plugin-loader" version "1.0.0"
     id "com.android.application" version "7.3.0" apply false
     id "org.jetbrains.kotlin.android" version "1.7.10" apply false
     id "com.google.gms.google-services" version "4.4.0" apply false
     id "com.google.firebase.crashlytics" version "2.9.9" apply false
}

include ":app"

app.gradle:

plugins {
     id "com.android.application"
     id "com.google.gms.google-services"
     id "com.google.firebase.crashlytics"
     id "kotlin-android"
     id "dev.flutter.flutter-gradle-plugin"
}

Using firebase_analytics will prompt an error message
E/FA (22376): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI

Of course, when I roll back the code, such an error does not exist.

**Comment by Lyokone** [comment]
Duplicated: https://github.com/firebase/flutterfire/issues/12388
