### ISSUE TITLE
[📚] Hyperlink error in Get Started

### ISSUE THREAD

**Issue by cosminpm** [firebase/flutterfire#12435]
When I visit the [Firebase Analytics documentation](https://firebase.flutter.dev/docs/analytics/overview/) and navigate to the _Next Steps_ section, clicking the hyperlink for [Get started](https://firebase.flutter.dev/docs/analytics/overview/get-started) leads to a `404` error, as shown in the following screenshot:

![404 Error Screenshot](https://github.com/firebase/flutterfire/assets/51784809/9d1bef33-8576-4626-8ecf-6d614a0229f0)

**Comment by Lyokone** [comment]
As mentioned in the top section of your link, this documentation is archived. Please find the correct documentation here: https://firebase.google.com/docs/analytics/get-started?platform=flutter

**Comment by cosminpm** [comment]
Thanks for the answer. Is there any plan to remove this documentation?
