### ISSUE TITLE
🐛 [FLTFirebaseCorePlugin] __39+[FLTFirebaseCorePlugin sharedInstance]_block_invoke, iOS App Getting Crash

### ISSUE THREAD

**Issue by siddew201** [firebase/flutterfire#12437]
## Bug report

**Describe the bug**

We are getting crashes in our iOS app. The stacktrace from Firebase crashlytics indicates crash in FLTFirebaseCorePlugin. These Crashes are occurring on end users in our production build and we are not able to replicate it at our end.
We are providing details below. 

 We look forward to your feedback.

### Steps to reproduce

Crash is occurring on end-user devices and we don't have steps to reproduce it.

### Expected behavior

App should not crashed.

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

**CrashStack**

com.apple.main-thread
0  ???                            0x1eced9bf8 (Missing)
1  ???                            0x1ad742cf0 (Missing)
2  ???                            0x1ad7429ec (Missing)
3  ???                            0x1ad74309c (Missing)
4  ???                            0x107e4590c (Missing)
5  ???                            0x107e465cc (Missing)
6  ???                            0x107e5d06c (Missing)
7  ???                            0x107e5c5d8 (Missing)
8  ???                            0x107e65cfc (Missing)
9  ???                            0x107e661b4 (Missing)
10 ???                            0x107b9f4f8 (Missing)
11 ???                            0x107b9f674 (Missing)
12 ???                            0x107b9f404 (Missing)
13 ???                            0x107b9c65c (Missing)
14 ???                            0x107b9c30c (Missing)
15 Runner                         0x1b927ac __39+[FLTFirebaseCorePlugin sharedInstance]_block_invoke + 49 (FLTFirebaseCorePlugin.m:49)
16 ???                            0x1ad742300 (Missing)
17 ???                            0x1ad743b3c (Missing)
18 Runner                         0x1b926e8 +[FLTFirebaseCorePlugin sharedInstance] + 85 (once.h:85)
19 Runner                         0x1b9262c +[FLTFirebaseCorePlugin registerWithRegistrar:] + 16 (FLTFirebaseCorePlugin.m:16)
20 Runner                         0xc390 +[GeneratedPluginRegistrant registerWithRegistry:] + 453 (GeneratedPluginRegistrant.m:453)
21 Runner                         0xdd1c AppDelegate.application(_:didFinishLaunchingWithOptions:) + 79 (AppDelegate+NotificationHandler.swift:79)
22 Runner                         0xe150 @objc AppDelegate.application(_:didFinishLaunchingWithOptions:) + 4339491152 (<compiler-generated>:4339491152)
23 ???                            0x1a7b80620 (Missing)
24 ???                            0x1a7b7f788 (Missing)
25 ???                            0x1a7b7e76c (Missing)
26 ???                            0x1a7b7e3b8 (Missing)
27 ???                            0x1a7afaee0 (Missing)
28 ???                            0x1a7b823b4 (Missing)
29 ???                            0x1a7aa9eb8 (Missing)
30 ???                            0x1a7aa88c0 (Missing)
31 ???                            0x1a7aa8228 (Missing)
32 ???                            0x1a7aa80f8 (Missing)
33 ???                            0x1a7aa8000 (Missing)
34 ???                            0x1a7aa7888 (Missing)
35 ???                            0x1a7aa7538 (Missing)
36 ???                            0x1a7e2b270 (Missing)
37 ???                            0x1a7aa66bc (Missing)
38 ???                            0x1a7aa652c (Missing)
39 ???                            0x1a7bbec98 (Missing)
40 ???                            0x1a7bbea30 (Missing)
41 ???                            0x1bdc056d4 (Missing)
42 ???                            0x1bdc05570 (Missing)
43 ???                            0x1bdc0419c (Missing)
44 ???                            0x1bdc0ff8c (Missing)
45 ???                            0x1ad742300 (Missing)
46 ???                            0x1ad745d48 (Missing)
47 ???                            0x1bdc00520 (Missing)
48 ???                            0x1bdc004a0 (Missing)
49 ???                            0x1bdc00378 (Missing)
50 ???                            0x1a57790ac (Missing)
51 ???                            0x1a5778328 (Missing)
52 ???                            0x1a5776b3c (Missing)
53 ???                            0x1a5775818 (Missing)
54 ???                            0x1a57753f8 (Missing)
55 ???                            0x1e8d2b4f8 (Missing)
56 ???                            0x1a7b9b8a0 (Missing)
57 ???                            0x1a7b9aedc (Missing)
58 Runner                         0xea84 main + 8 (AppDelegate.swift:8)
59 ???                            0x1c84dedcc (Missing)

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
hrishikeshrajwade@LP-GKL4PGKWQV tata-neu-app % flutter doctor -v
[✓] Flutter (Channel stable, 3.10.6, on macOS 14.0 23A344 darwin-arm64, locale en-IN)
    • Flutter version 3.10.6 on channel stable at /Users/hrishikeshrajwade/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (8 months ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1
 
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/hrishikeshrajwade/Library/Android/sdk
    • Platform android-34, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.
 
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2
 
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
 
[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
 
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 73.0.4
    • Dart plugin version 231.8109.91
 
[✓] VS Code (version 1.71.2)
    • VS Code at /Users/hrishikeshrajwade/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0
 
[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 121.0.6167.85
    ! Error: Browsing on the local area network for Hrishikesh’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
 
[✓] Network resources
    • All expected network resources are available.
 
• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
firebase_core: ^2.15.0
firebase_analytics: ^10.4.4
firebase_crashlytics: ^3.3.4
firebase_performance: ^0.9.2+4
```

</details>

---

**Comment by Lyokone** [comment]
Hello, without any code to reproduce it, it's going to be hard to fix on our end. Can you try to run `flutterfire configure` with the latest version? https://pub.dev/packages/flutterfire_cli/versions/0.3.0-dev.19

**Comment by siddew201** [comment]
Hi @Lyokone we had run flutterfire configure with latest version 0.2.7 when we configured Firebase. We are not facing the same issue in our Android app.

In crash stack It seems FLTFirebaseCorePlugin have some issues. Can you please suggest some solution for this issue. This is a top crash in our project.
