### ISSUE TITLE
🐛 [Debug] I cannot run Flutterfire projects in Windows mode.

### ISSUE THREAD

**Issue by guvenacar** [firebase/flutterfire#12447]
## Bug report
 I cannot run Flutterfire projects in Windows mode.

**Describe the bug**
Whenever I try to run my Flutterfire projects in windows mode, I first get a cmake version error. After fixing the Cmake version (3.1 > 3.5) error, I get the Nuget not installed error.
And my screen freezes on the "firebase_options.dart" file in debug mode, producing the following error:
"Exception has occurred.
UnsupportedError (Unsupported operation: DefaultFirebaseOptions have not been configured for windows - you can reconfigure this by running the FlutterFire CLI again.)"

![image](https://github.com/firebase/flutterfire/assets/78052322/fca45a2c-b83f-4ad8-bd54-a7b07d4b7a1b)

### Sample project

 This is an empty project I created for this example. Project codes are below.
 
Attachments I added before running my project:
flutter pub add firebase_core
flutter pub add firebase_auth
flutter pub add cloud_firestore
flutter pub add provider
flutter pub add firebase_ui_auth
dart pub global activate flutterfire_cli
flutterfire configure

 main.dart
 
 `   
        import 'package:cloud_firestore/cloud_firestore.dart';
        import 'package:firebase/firebase_options.dart';
        import 'package:firebase_core/firebase_core.dart';
        import 'package:flutter/material.dart';
      
      String str = "";
      
      void main()  async {
         WidgetsFlutterBinding.ensureInitialized();
         await Firebase.initializeApp(
          options: DefaultFirebaseOptions.currentPlatform, 
        );
      
        var db = FirebaseFirestore.instance;
        
          await db.collection("testdb").doc("sehir").get().then(
            (value) {
              str = value.get("ad").toString();
            },
          ).catchError((error) => error);

        runApp(const MyApp());
      }
      
      class MyApp extends StatelessWidget {
        const MyApp({super.key}); 
        @override
        Widget build(BuildContext context) {
          return MaterialApp(
            title: 'Flutter Demo',
            theme: ThemeData( 
              colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
              useMaterial3: true,
            ),
            home: const MyHomePage(title: 'Flutter Demo Home Page'),
          );
        }
      }
      
      class MyHomePage extends StatefulWidget {
        const MyHomePage({super.key, required this.title}); 
      
        final String title;
     
        @override
        State<MyHomePage> createState() => _MyHomePageState();
      }
      
      class _MyHomePageState extends State<MyHomePage> {
        int _counter = 0;
      
        void _incrementCounter() {
          setState(() { 
            _counter++;
          });
        }
      
        @override
        Widget build(BuildContext context) { 
          return Scaffold(
            appBar: AppBar( 
              backgroundColor: Theme.of(context).colorScheme.inversePrimary, 
              title: Text(widget.title),
            ),
            body: Center( 
              child: Column( 
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                  const Text(
                    'You have pushed the button this many times:',
                  ),
                  Text(
                    str,
                    style: Theme.of(context).textTheme.headlineMedium,
                  ),
                ],
              ),
            ),
            floatingActionButton: FloatingActionButton(
              onPressed: _incrementCounter,
              tooltip: 'Increment',
              child: const Icon(Icons.add),
            ), // This trailing comma makes auto-formatting nicer for build methods.
          );
        }
      }` 

 
### Flutter doctor

<details><summary>Click To Expand</summary>

```
PS D:\flutter\hazir_sablonlar\firebase> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.19.2, on Microsoft Windows [Version 10.0.22631.3155], locale tr-TR)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.1)
[√] Android Studio (version 2023.1)
[√] VS Code (version 1.87.0)
[√] Connected device (3 available)
[√] Network resources

• No issues found!
```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
PS D:\flutter\hazir_sablonlar\firebase> flutter pub deps -- --style=compact
Dart SDK 3.3.0
Flutter SDK 3.19.2
firebase 1.0.0+1

dependencies:
- cloud_firestore 4.15.7 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.6
- firebase_auth 4.17.7 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.26.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_ui_auth 1.13.1 [email_validator firebase_auth firebase_core firebase_dynamic_links firebase_ui_localizations firebase_ui_oauth firebase_ui_shared flutter flutter_localizations meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- provider 6.1.2 [collection flutter nested]

dev dependencies:
- flutter_lints 3.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]       

transitive dependencies:
- _flutterfire_internals 1.3.24 [collection firebase_core firebase_core_platform_interface flutter meta]
- args 2.4.2
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- cloud_firestore_platform_interface 6.1.8 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.10.7 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.18.0
- crypto 3.0.3 [typed_data]
- desktop_webview_auth 0.0.15 [crypto flutter http flutter_web_plugins plugin_platform_interface]
- email_validator 2.1.17
- fake_async 1.3.1 [clock collection]
- firebase_auth_platform_interface 7.1.7 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.9.7 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser js meta web]       
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.11.5 [firebase_core_platform_interface flutter flutter_web_plugins js meta web]
- firebase_dynamic_links 5.4.16 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_dynamic_links_platform_interface 0.2.6+24 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_ui_localizations 1.10.2 [flutter flutter_localizations path]
- firebase_ui_oauth 1.5.1 [desktop_webview_auth firebase_auth firebase_ui_auth firebase_ui_shared flutter_svg flutter]
- firebase_ui_shared 1.4.1 [flutter]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_svg 2.0.10+1 [flutter http vector_graphics vector_graphics_codec vector_graphics_compiler]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- http 1.2.0 [async http_parser meta web]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- intl 0.18.1 [clock meta path]
- js 0.6.7 [meta]
- leak_tracker 10.0.0 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 2.0.1 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 2.0.1 [leak_tracker matcher meta]
- lints 3.0.0
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.8.0 [collection]
- meta 1.11.0
- nested 1.0.0 [flutter]
- path 1.9.0
- path_parsing 1.0.1 [vector_math meta]
- petitparser 6.0.2 [meta]
- plugin_platform_interface 2.1.8 [meta]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- typed_data 1.3.2 [collection]
- vector_graphics 1.1.11+1 [flutter http vector_graphics_codec]
- vector_graphics_codec 1.1.11+1
- vector_graphics_compiler 1.1.11+1 [args meta path_parsing xml vector_graphics_codec path]
- vector_math 2.1.4
- vm_service 13.0.0
- web 0.4.2
- xml 6.5.0 [collection meta petitparser]
```

</details>

---

**Comment by Lyokone** [comment]
You can find instructions in this video: https://youtu.be/v7UxcMV30rA?si=TtpEVq0Zsz8KFveY&t=810

Please note that Windows support is still in beta, thus some documentation might not be up to date.
