### ISSUE TITLE
🐛 [firebase_crashlytics] Unable to get readable crash reports in ANR and crashes

### ISSUE THREAD

**Issue by sumittiware** [firebase/flutterfire#12459]
## Bug report

**Describe the bug**
Hey folks,
We are using Flutter for developing our mobile app. We are getting a lot of ANR's or Crashes but in all the cases there is not dart associated stackTrace in the crashlytics dashboard. Due to which we are not able to debug or get more insights on the issue as we are not able to find the trigger point in our code(dart code) which lead to crash or an ANR.
Is this how it is supposed to be or can we get the dart associated stackTrace and we might be doing something wrong. Could someone provide some insights about it?

**Comment by russellwheatley** [comment]
Hi @sumittiware, do you have an obfuscated Dart stack trace? Or no Dart stack trace at all? 

It would be helpful if you could provide a sample stack trace so we can take a look. Thanks.
