### ISSUE TITLE
[📚] [google_sign_in_ios] Whether to put GoogleService-Info.plist into project or not?

### ISSUE THREAD

**Issue by dheeraj-p** [firebase/flutterfire#12458]
I am implementing Google Signin in my flutter application and came across following documentation for the package.
https://pub.dev/packages/google_sign_in_ios#ios-integration
<img width="795" alt="Screenshot 2024-03-08 at 5 19 36 PM" src="https://github.com/firebase/flutterfire/assets/44019618/294bb12c-0b99-413d-ad75-8fae15c99873">

The step 3 of iOS integration, it says:
`Make sure to download a new copy of your project's GoogleService-Info.plist from step 2. Do not put this file in your project.`

But everywhere else in firebase documentation (https://firebase.google.com/docs/auth/ios/google-signin#enable_google_sign-in_for_your_firebase_project) it is mentioned to place this file in the root of `ios` directory. It confuses me and I wasted a lot of time debugging my application just because I had not copied the GoogleService-Info.plist  into my project. Please provide clarity for the above. I am sure that the step mentioned in the package documentation is not by mistake.

Apologies in advance if I have missed reading any obvious point/step in the documentation.

**Comment by Lyokone** [comment]
You are linking the documentation for iOS, the correct documentation is under Flutter on the left menu. https://firebase.google.com/docs/auth/flutter/federated-auth#google

You'll need to follow `google_sign_in` instructions (so you'll need to add GoogleService-Info.plist). Check the example app for guidance: https://github.com/firebase/flutterfire/blob/master/packages/firebase_auth/firebase_auth/example/ios/Runner/GoogleService-Info.plist

**Comment by dheeraj-p** [comment]
Thank you @Lyokone for quick response. I understand now that GoogleService-Info.plist needs to be added. However, I feel that the step mentioned in the package documentation is misleading, not sure if that is for some different purpose or scenario.
