### ISSUE TITLE
🐛 [CLOUD_FIRESTORE] Can't use startAfterDocument

### ISSUE THREAD

**Issue by GuiQueirozRibeiro** [firebase/flutterfire#12461]
## Bug report

**Describe the bug**
I'm trying to pagination and show my cards, but everytime that i try to use startAfterDocument in flutter i got the same error:
´´´
I/flutter ( 9224): [cloud_firestore/invalid-argument] Client specified an invalid argument. Note that this differs from failed-precondition. invalid-argument indicates arguments that are problematic regardless of the state of the system (e.g., an invalid field name).
´´´

### Steps to reproduce
´´´
Future<void> loadCards({isNotFromSplash = false}) async {
    const maxCardsLoaded = 3;

    if (!isNotFromSplash) {
      _items.clear();
      _items.addAll(await loadUserCards(_currentUser?.id));
    } else if (!_hasNext) {
      return;
    }
    Query<Map<String, dynamic>> baseQuery = firestore
        .collection('cards')
        .where('uid', isNotEqualTo: _currentUser!.id);

    if (isNotFromSplash) {
      print(_latestDoc);
      final query = await baseQuery.startAfterDocument(_latestDoc!).get();
    }
    try {
      final query = await baseQuery.limit(maxCardsLoaded).get();
      final newCards =
          query.docs.map((doc) => CardModel.fromSnapshot(doc)).toList();
      _items.addAll(newCards);

      if (query.docs.isNotEmpty) _latestDoc = query.docs.last;
      if (query.docs.length < maxCardsLoaded) _hasNext = false;
      notifyListeners();
    } catch (error) {
      print(error);
      rethrow;
    }
  }
´´´
---

### Version

```
cloud_firestore: ^4.15.6
firebase_auth: ^4.17.6
firebase_core: ^2.25.5
firebase_messaging: ^14.7.17
firebase_storage: ^11.6.7
```

</details>
print for my _latestDoc variable
```
I/flutter ( 9224): Instance of '_JsonQueryDocumentSnapshot'
```

**Comment by Lyokone** [comment]
Hello @GuiQueirozRibeiro, please provide a complete sample project so we can investigate this issue. This seem related to your data model.

**Comment by larssn** [comment]
@GuiQueirozRibeiro You must have an `orderBy` clause on your query for `startAfter` or `startAfterDocument` to work.
