### ISSUE TITLE
☂️ Migration to `js_interop` for WASM Compatibility

### ISSUE THREAD

**Issue by Lyokone** [firebase/flutterfire#12466]
## Objective
The goal of this umbrella issue is to track the progress of migrating our web package plugins from the `js` package to `js_interop`. This migration aims to enhance compatibility with WebAssembly (WASM), ensuring Flutter applications using Firebase can leverage the full capabilities of WASM for improved performance and functionality.

## Migration List
Below is a list of plugins included in this migration effort. Each plugin requires updates to be fully compatible with `js_interop` and thereby, WASM.

- [x] Core (#12031)
- [x] Auth (#12145)
- [x] App Check (#12209)
- [x] Firestore (#12169)
- [x] Functions (#12205)
- [x] Messaging (#12223)
- [x] Storage (#12202)
- [x] App Installation (#12220)
- [x] Analytics (#12206)
- [x] Remote config (#12489)
- [x] Database (#12530)
- [x] Performance (#12515)
- [x] Removing `package:js` dependency (#12534) 

## Feedback and Discussion
For any questions, feedback, or discussions related to this migration effort, please comment on this issue or reach out to the project maintainers directly.

**Comment by JgomesAT** [comment]
add support to web 0.5.1?

**Comment by Lyokone** [comment]
@JgomesAT It's has been merged and will be released tomorrow: https://github.com/firebase/flutterfire/pull/12469

**Comment by Lyokone** [comment]
The new interop has been released across all packages 🎉
