### ISSUE TITLE
Firebase initialization crash in Web / Flutter, works fine in android and ios.

### ISSUE THREAD

**Issue by luiznpi** [firebase/flutterfire#12470]
## Bug report

Just like the previous closed thread:  "[flutterfire] "Firebase.initializeApp" exception "Expected a value of type 'Object', but got one of type 'Null'" #8128" I am getting problems initializing the firebase when running the Web target in flutter. Same code works fine in android.

 

**Describe the bug**

On flutter web target the project throws this exception in the core.dart during the execution of the firebase initialization on the main dart:

await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

Exception has occurred.
FirebaseError: Firebase: No Firebase App '[DEFAULT]' has been created - call initializeApp() first (app/no-app).
https://www.gstatic.com/firebasejs/10.7.0/firebase-app.js 2045:29   getApp
dart-sdk/lib/_internal/js_shared/lib/js_util_patch.dart 110:66      callMethod$
packages/firebase_core_web/src/interop/core.dart 59:28              app$
packages/firebase_core_web/src/firebase_core_web.dart 350:48        <fn>
packages/firebase_core_web/src/firebase_core_web.dart 374:21        guardNotInitialized
packages/firebase_core_web/src/firebase_core_web.dart 350:13        app
packages/firebase_core/src/firebase.dart 56:41                      app
packages/firebase_app_check/src/firebase_app_check.dart 39:52       get instance
packages/hydra/main.dart 33:35                                      main
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50  <fn>
dart-sdk/lib/async/zone.dart 1661:54                                runUnary
dart-sdk/lib/async/future_impl.dart 162:18                          handleValue
dart-sdk/lib/async/future_impl.dart 838:44                          handleValueCallback
dart-sdk/lib/async/future_impl.dart 867:13                          _propagateToListeners

Would like to know what dependencies of firebase / flutter versions are compatible to avoid this bug.

### Flutter doctor
[√] Flutter (Channel stable, 3.19.3, on Microsoft Windows [Version 10.0.19045.4046], locale en-GB)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.5)
[√] Android Studio (version 2023.2)
[√] VS Code (version 1.87.1)
[√] Connected device (3 available)
[√] Network resources

• No issues found!

### Flutter dependencies

dependencies:
- amplify_api 1.7.0 [amplify_api_dart amplify_core amplify_flutter connectivity_plus flutter meta plugin_platform_interface]
- amplify_auth_cognito 1.7.0 [amplify_analytics_pinpoint amplify_analytics_pinpoint_dart amplify_auth_cognito_dart amplify_core amplify_flutter amplify_secure_storage async flutter meta path plugin_platform_interface]
- amplify_flutter 1.7.0 [amplify_core amplify_secure_storage aws_common collection flutter meta]
- cloud_firestore 4.15.8 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.6
- firebase_app_check 0.2.1+17 [firebase_app_check_platform_interface firebase_app_check_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 4.17.8 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.27.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_login 5.0.0 [another_flushbar another_transformer_page_view flutter font_awesome_flutter intl_phone_number_input phone_numbers_parser provider quiver sign_in_button url_launcher]
- google_sign_in 6.2.1 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- intl 0.19.0 [clock meta path]
- provider 6.1.2 [collection flutter nested]
- shared_preferences 2.2.2 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]

dev dependencies:
- flutter_launcher_icons 0.13.1 [args checked_yaml cli_util image json_annotation path yaml]

transitive dependencies:
- _flutterfire_internals 1.3.25 [collection firebase_core firebase_core_platform_interface flutter meta]
- amplify_analytics_pinpoint 1.7.0 [amplify_analytics_pinpoint_dart amplify_core amplify_db_common amplify_secure_storage aws_common device_info_plus flutter meta package_info_plus path_provider]
- amplify_analytics_pinpoint_dart 0.3.7 [amplify_core amplify_db_common_dart amplify_secure_storage_dart aws_common aws_signature_v4 built_collection built_value collection drift intl meta path smithy smithy_aws uuid]
- amplify_api_dart 0.4.0 [amplify_core async aws_common collection json_annotation meta plugin_platform_interface stream_transform web_socket_channel]
- amplify_auth_cognito_dart 0.10.10 [amplify_analytics_pinpoint_dart amplify_core amplify_secure_storage_dart async aws_common aws_signature_v4 built_collection built_value clock collection convert crypto ffi fixnum http intl js json_annotation meta oauth2 path smithy smithy_aws stream_transform uuid win32 win32_registry worker_bee]
- amplify_core 1.7.0 [async aws_common aws_signature_v4 collection graphs intl json_annotation logging meta retry stack_trace uuid]
- amplify_db_common 0.3.5 [amplify_db_common_dart drift flutter path path_provider]
- amplify_db_common_dart 0.3.6 [amplify_core async aws_common drift meta path sqlite3]
- amplify_secure_storage 0.4.2 [amplify_secure_storage_dart async file flutter meta path path_provider path_provider_windows]
- amplify_secure_storage_dart 0.4.3 [async aws_common built_collection built_value ffi file js meta path win32 worker_bee]
- another_flushbar 1.12.30 [flutter]
- another_transformer_page_view 2.0.1 [flutter]
- archive 3.4.10 [crypto path pointycastle]
- args 2.4.2
- async 2.11.0 [collection meta]
- aws_common 0.6.3 [async built_collection built_value collection http2 js json_annotation logging meta mime os_detect path stream_transform uuid]
- aws_signature_v4 0.5.1 [async aws_common collection convert crypto json_annotation meta path]
- boolean_selector 2.1.1 [source_span string_scanner]
- built_collection 5.1.1
- built_value 8.8.1 [built_collection collection fixnum meta]
- characters 1.3.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- cli_util 0.4.1 [meta path]
- clock 1.1.1
- cloud_firestore_platform_interface 6.1.9 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.10.8 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.18.0
- connectivity_plus 5.0.2 [flutter flutter_web_plugins connectivity_plus_platform_interface js meta nm]
- connectivity_plus_platform_interface 1.2.4 [flutter meta plugin_platform_interface]
- convert 3.1.1 [typed_data]
- crclib 3.0.0 [meta tuple]
- crypto 3.0.3 [typed_data]
- dbus 0.7.10 [args ffi meta xml]
- device_info_plus 9.1.2 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta win32 win32_registry]
- device_info_plus_platform_interface 7.0.0 [flutter meta plugin_platform_interface]
- drift 2.14.1 [async convert collection js meta stream_channel sqlite3 path]
- equatable 2.0.5 [collection meta]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.2
- file 7.0.0 [meta path]
- firebase_app_check_platform_interface 0.1.0+19 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_app_check_web 0.1.0+19 [_flutterfire_internals firebase_app_check_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 7.1.8 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.9.8 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins 
http_parser js meta web]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.11.5 [firebase_core_platform_interface flutter flutter_web_plugins js meta web]
- fixnum 1.1.0
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- font_awesome_flutter 10.7.0 [flutter]
- google_identity_services_web 0.3.0+2 [meta web]
- google_sign_in_android 6.1.21 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.7.4 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.4.5 [flutter plugin_platform_interface]
- google_sign_in_web 0.12.3+3 [flutter flutter_web_plugins google_identity_services_web google_sign_in_platform_interface http web]
- graphs 2.3.1 [collection]
- http 1.2.0 [async http_parser meta web]
- http2 2.3.0
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image 4.1.7 [archive meta xml]
- intl_phone_number_input 0.7.4 [flutter libphonenumber_plugin equatable collection]
- js 0.6.7 [meta]
- json_annotation 4.8.1 [meta]
- leak_tracker 10.0.0 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 2.0.1 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 2.0.1 [leak_tracker matcher meta]
- libphonenumber_platform_interface 0.4.2 [flutter plugin_platform_interface]
- libphonenumber_plugin 0.3.3 [flutter flutter_web_plugins libphonenumber_platform_interface libphonenumber_web]        
- libphonenumber_web 0.3.2 [flutter flutter_web_plugins js libphonenumber_platform_interface]
- logging 1.2.0
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.8.0 [collection]
- meta 1.11.0
- mime 1.0.5
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- oauth2 2.0.2 [collection crypto http http_parser]
- os_detect 2.0.1
- package_info_plus 5.0.1 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface web win32]
- package_info_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- path 1.9.0
- path_provider 2.1.2 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- path_provider_android 2.2.2 [flutter path_provider_platform_interface]
- path_provider_foundation 2.3.2 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.2.1 [ffi flutter path path_provider_platform_interface win32]
- petitparser 6.0.2 [meta]
- phone_numbers_parser 8.2.1 [meta]
- platform 3.1.4
- plugin_platform_interface 2.1.8 [meta]
- pointycastle 3.7.4 [collection convert js]
- quiver 3.2.1 [matcher]
- retry 3.1.2
- shared_preferences_android 2.2.1 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.3.5 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.3.2 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.3.2 [flutter plugin_platform_interface]
- shared_preferences_web 2.2.2 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.3.2 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.4.1 [async collection http_parser path stack_trace stream_channel]
- sign_in_button 3.2.0 [flutter font_awesome_flutter]
- sky_engine 0.0.99
- smithy 0.6.3 [async aws_common built_collection built_value collection convert crypto fixnum http_parser intl json_annotation meta path retry shelf typed_data xml]
- smithy_aws 0.6.2 [aws_common aws_signature_v4 built_collection built_value collection convert crclib crypto intl json_annotation meta path smithy xml]
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- sqlite3 2.4.0 [collection ffi js meta path]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- tuple 2.0.2
- typed_data 1.3.2 [collection]
- url_launcher 6.2.5 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- url_launcher_android 6.3.0 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.2.5 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.1.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.1.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.2.3 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.1 [flutter url_launcher_platform_interface]
- uuid 4.3.3 [crypto sprintf meta fixnum]
- vector_math 2.1.4
- vm_service 13.0.0
- web 0.4.2
- web_socket_channel 2.4.3 [async crypto stream_channel web]
- win32 5.3.0 [ffi]
- win32_registry 1.1.2 [ffi win32]
- worker_bee 0.2.3 [async aws_common built_collection built_value collection js meta path stack_trace stream_channel stream_transform]
- xdg_directories 1.0.4 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]
``
</details>

---

**Comment by Lyokone** [comment]
Hello @luiznpi, can you run `fluttefire configure` again to be sure that there is no issues with your setup? Thanks

**Comment by Lyokone** [comment]
Not sure what is happening then, I would need a reproduction sample to be able to reproduce on my end.

**Comment by luiznpi** [comment]
HI, 

On Index.html the body contains this:

<body> 
  <script src="https://www.gstatic.com/firebasejs/10.7.0/firebase-app.js" ></script> 

<script>
    const firebaseConfig = {
    apiKey: "xxxxxxxxxxx",
    authDomain: "xxxxxx.firebaseapp.com",
    projectId: "xxxxxxxxx",
    storageBucket: "xxxxxxxxxx.appspot.com",
    messagingSenderId: "xxxxxxxxxxxx",
    appId: "1:xxxxxxxxxxxxx",
    measurementId: "G-1QYJE24EJ2"
    };
    firebase.initializeApp(firebaseConfig);
    firebase.analytics();
  </script>
  <script src="main.dart.js" type="application/javascript"></script> 
  <script>
    window.addEventListener('load', function(ev) {
      // Download main.dart.js
      _flutter.loader.loadEntrypoint({
        serviceWorker: {
          serviceWorkerVersion: serviceWorkerVersion,
        },
        onEntrypointLoaded: function(engineInitializer) {
          engineInitializer.initializeEngine().then(function(appRunner) {
            appRunner.runApp();
          });
        }
      });
    });
  </script>
</body>



And on main.dart:




void main() async {
  // navigation bar color
  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      systemNavigationBarColor: Color.fromARGB(255, 127, 43, 43),
    ),
  );
  //Firebase initialization
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  await FirebaseAppCheck.instance.activate();
  // Run the app wrapped with Provider for CreditsService
  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider<CreditsService>(
            create: (context) => CreditsServiceRouter
                .getCreditsService()), //This could use a router
        ChangeNotifierProvider<LoginService>(
            create: (context) => LoginServiceRouter.getLoginService())
      ],
      child: const HydraApp(),
    ),
  );
}

 DefaultFirebaseOptions.currentPlatform contains the same config as on index.html, we tried already to skip initialization on index.html, the result is the same, a crash when calling  await Firebase.initializeApp in the main dart with the following error on the core.dart:

![image](https://github.com/firebase/flutterfire/assets/142594868/3d2e30cd-daf3-4711-8c24-ddfcbc04e31c)


There are so many other cases not solved with the same problem, was a solution ever found for this problem ?

**Comment by Lyokone** [comment]
Please follow documentation: https://firebase.google.com/docs/flutter/setup?platform=ios#initialize-firebase You are not supposed to modify the index.html

**Comment by luiznpi** [comment]
The exact same error happens with the index.html without any reference added to the firebase initialization, like this:

<body> 
  <script src="main.dart.js" type="application/javascript"></script> 
  <script>
    window.addEventListener('load', function(ev) {
      // Download main.dart.js
      _flutter.loader.loadEntrypoint({
        serviceWorker: {
          serviceWorkerVersion: serviceWorkerVersion,
        },
        onEntrypointLoaded: function(engineInitializer) {
          engineInitializer.initializeEngine().then(function(appRunner) {
            appRunner.runApp();
          });
        }
      });
    });
  </script>
</body>

**Comment by luiznpi** [comment]
Redoing the steps from the suggested documentation, result is the same, crash with the following error:

A Dart VM Service on Chrome is available at: http://127.0.0.1:50706/u2NjSjdlTi8=
The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:50706/u2NjSjdlTi8=
Error: [core/no-app] No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 297:3  throw_
packages/firebase_core_web/src/firebase_core_web.dart 354:9                  app
packages/firebase_core/src/firebase.dart 56:41                               app
packages/firebase_app_check/src/firebase_app_check.dart 39:52                get instance
packages/hydra/main.dart 33:35                                               main
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50           <fn>
dart-sdk/lib/async/zone.dart 1661:54                                         runUnary
dart-sdk/lib/async/future_impl.dart 162:18                                   handleValue
dart-sdk/lib/async/future_impl.dart 838:44                                   handleValueCallback
dart-sdk/lib/async/future_impl.dart 867:13                                   _propagateToListeners
dart-sdk/lib/async/future_impl.dart 643:5                                    [_completeWithValue]
dart-sdk/lib/async/future.dart 524:22                                        <fn>
dart-sdk/lib/async/zone.dart 1661:54                                         runUnary
dart-sdk/lib/async/future_impl.dart 162:18                                   handleValue
dart-sdk/lib/async/future_impl.dart 838:44                                   handleValueCallback
dart-sdk/lib/async/future_impl.dart 867:13                                   _propagateToListeners
dart-sdk/lib/async/future_impl.dart 464:9                                    callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                             _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                              _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7           <fn>
