### ISSUE TITLE
🐛 [core] Add isGooglePlayServicesAvailable() wrapper

### ISSUE THREAD

**Issue by emersion** [firebase/flutterfire#12481]
The `com.google.android.gms.common.GoogleApiAvailability` package provides a `isGooglePlayServicesAvailable()` method. It would be nice to expose it in flutterfire.

**Comment by Lyokone** [comment]
It is [not part of Firebase](https://firebase.google.com/s/results?q=isGooglePlayServicesAvailable) so it will not be added.
