### ISSUE TITLE
🐛 [firebase_core] upgrade BoM version 32.7.4 (Remote Config version 21.6.3)

### ISSUE THREAD

**Issue by phamconganh** [firebase/flutterfire#12495]
## Bug report

**Describe the bug**
Need upgrade  BoM version 32.7.4 (Remote Config version 21.6.3) to fix this issue https://github.com/firebase/firebase-android-sdk/issues/5751#issuecomment-1986104125

**Comment by xiaolongwuhpu** [comment]
https://github.com/firebase/firebase-android-sdk/issues/5751

**Comment by Lyokone** [comment]
It has been merged to master and will be released by tomorrow, thanks for the report.

**Comment by rwrz** [comment]
how can I grab this release?

**Comment by rwrz** [comment]
@Lyokone 
do you mind to release it? please!

**Comment by edu-magno** [comment]
@Lyokone 
Do you have an estimate of when this version will be released?

**Comment by rwrz** [comment]
Thank you. It was released 27hrs ago.
