### ISSUE TITLE
🐛 [firebase_core] Add a method a `FirebaseException.toString` method but without the stack trace

### ISSUE THREAD

**Issue by nilsreichardt** [firebase/flutterfire#12497]
## What feature would you like to see?

I'm looking for a `FirebaseException.toString` without the stack trace:

```dart
/// Returns [toString] without the stack trace.
String toStringWithoutStackTrace() {
  return '[$plugin/$code] $message';
}
```

Background: Sometimes I want to display the error and the stack trace is too much information and breaks the UI.

I could easily create a PR for this but I'm not sure if this will be accepted?

cc: @Lyokone

**Comment by Lyokone** [comment]
Hello @nilsreichardt, we don't think we'll add this feature directly to FlutterFire since it could be confusing for new users. But you can create an extension to have it directly :) Thanks for the suggestion.
