### ISSUE TITLE
🐛 [firebase_auth_web] Request to Upgrade JS Version in firebase_auth_web Dependency to Resolve Compatibility Issue with flutter_native_splash

### ISSUE THREAD

**Issue by narekv7** [firebase/flutterfire#12492]
When attempting to integrate the `flutter_native_splash` package into the project alongside `firebase_auth`, 
 a version conflict arises due to incompatible dependencies on the `js` package. 
 
 Logs
 ``` 
 Because firebase_auth >=4.17.9 depends on firebase_auth_web ^5.10.0 which depends on js ^0.6.3, firebase_auth >=4.17.9 requires js ^0.6.3.
And because flutter_native_splash 2.3.13 depends on js ^0.7.1 and no versions of flutter_native_splash match >2.3.13 <3.0.0, firebase_auth >=4.17.9 is incompatible with
  flutter_native_splash ^2.3.13.
So, because flutter_app depends on both flutter_native_splash ^2.3.13 and firebase_auth ^4.17.9, version solving failed.
 ```

**Comment by Lyokone** [comment]
Hello @narekv7, we are [currently migrating](https://github.com/firebase/flutterfire/issues/12466) to `js_interop` and will stop using the `js` package. You can force a dependency override in the meantime.
