### ISSUE TITLE
🐛 [FIREBASE_APP_CHECK] error on get token in FLutter web

### ISSUE THREAD

**Issue by JgomesAT** [firebase/flutterfire#12500]
In this function

Future<app_check_interop.AppCheckTokenResult> getToken(bool? forceRefresh) =>
      app_check_interop.getToken(jsObject, forceRefresh?.toJS).toDart
          as Future<app_check_interop.AppCheckTokenResult>;

`Error: TypeError: Instance of _Future<Object?>': type _Future<Object?> 
is not a subtype of type Future\<JavaScriptObject> 

dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 297:3  throw_
dart-sdk/lib/_internal/js_shared/lib/rti.dart 1385:3                         _failedAsCheck
dart-sdk/lib/_internal/js_shared/lib/rti.dart 1363:3                         _generalAsCheckImplementation
dart-sdk/lib/_internal/js_shared/lib/rti.dart 1258:30                        _installSpecializedAsCheck
packages/firebase_app_check_web/src/interop/app_check.dart 62:11             getToken
packages/firebase_app_check_web/firebase_app_check_web.dart 138:17           <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54           runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5           _async
packages/firebase_app_check_web/firebase_app_check_web.dart 136:50           <fn>`

**Comment by Lyokone** [comment]
Thanks for the report, will be looking into that, you can probably use `firebase_app_check_web: 0.1.0+19` in the mean time.
