### ISSUE TITLE
[firebase_auth]: authDomain not working on mobile despite announced support

### ISSUE THREAD

**Issue by benlc** [firebase/flutterfire#12517]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Auth

### Which platforms are affected?

Android, iOS

### Description

It was announced that custom `authDomain` was now supported on mobile/flutter in November 2023. However, while setting authDomain works on web, it still doesn't seem to get picked up on mobile and we're still seeing firebase's url instead of our own during the login flow

Relevant tickets and code changes:
https://github.com/firebase/flutterfire/issues/9668
https://github.com/firebase/flutterfire/pull/12157
https://github.com/firebase/flutterfire/pull/11925

![Screenshot from 2024-03-20 17-57-06](https://github.com/firebase/flutterfire/assets/1082345/20c7e0f5-e787-4b42-a82d-2283719fca66)

### Reproducing the issue

We've tried different firebase and flutter versions and are experiencing this on the latest version of Core, Auth and Flutter as of March 20th 2024.

The same configuration works as expected on web but it seems like `authDomain` is still ignored on mobile

```  
static const FirebaseOptions android = FirebaseOptions(
    apiKey: '...',
    appId: '...',
    projectId: '...',
    authDomain: 'custom.domain.com',
  );
```  

```
final provider = OAuthProvider(providerId);
firebaseAuth.signInWithProvider(provider)
```  

From decompiling the app, we can see that the underlying SDK on Android is the following:
```firebase-auth_client=22.3.1```

And the interop version is the following:
```firebase-auth-interop_client=20.0.0```

### Firebase Core version

2.27.1

### Flutter Version

3.19.3

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```
  firebase_analytics: ^10.8.0
  firebase_app_check: ^0.2.1+14
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  firebase_messaging: ^14.7.16
  firebase_performance: ^0.9.0+6
  firebase_remote_config: ^4.3.8

```

</details>

**Comment by russellwheatley** [comment]
We have a PR for this already: https://github.com/firebase/flutterfire/pull/12218

Should be out in the next release 👍

**Comment by benlc** [comment]
Ok thanks @russellwheatley !
