### ISSUE TITLE
[firebase_ml_model_downloader]: does model re-downloads on app upgrade

### ISSUE THREAD

**Issue by saurabhkumar8112** [firebase/flutterfire#12512]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Other

### Which platforms are affected?

Android, iOS

### Description

We are using a tflite model along with `firebase_ml_model_downloader` for managing our local model which runs on device.

We are observing that whenever users upgrade the app, the model downloads once again(even if it hasn't been updated on remote).

We are aware that ML model downloader compares the presence of a new model by comparing the hash(meta-data) of local model with remote model.

But there's no mention of the behaviour on app upgrade. And to our observation app-upgrade lead to re-downloading of the model, but in a separate location.

Can we get some clarification on this? 

### Reproducing the issue

This is how we download the model currently which is just using example code

```
Future<File> getModelFile() async {

    FirebaseCustomModel newModel =
        await FirebaseModelDownloader.instance.getModel(
      modelName,
      FirebaseModelDownloadType.localModelUpdateInBackground,
      FirebaseModelDownloadConditions(
        iosAllowsCellularAccess: true,
        iosAllowsBackgroundDownloading: true,
        androidChargingRequired: false,
        androidWifiRequired: false,
        androidDeviceIdleRequired: false,
      ),
    );
   return newModel
  }
```

Step1: Build the example app in release mode
Step2: Upgrade the app

### Firebase Core version

2.27.0

### Flutter Version

3.19.3

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by Lyokone** [comment]
Hello @saurabhkumar8112, going through the native code, we are not setting a custom redownload or path compared to the native libraries. I cannot find any specific documentation about models being redownloaded manually. When you mention app upgrade, does it mean that you are only updating dart code, or native libraries as well? My guess is that changing the `firebase_core` could impact how the hash is calculated.

**Comment by saurabhkumar8112** [comment]
Thanks for your reply @saurabhkumar8112 
By app upgrade I meant, upgrading to a new version available on play-store/app-store. 
We use [upgrader](https://pub.dev/packages/upgrader) to ask users to upgrade the app when a new version is available. 

>My guess is that changing the firebase_core could impact how the hash is calculated

I think hash is not a problem here. As long as the model file is same, MD5 should return the same hash. My speculation is the `local file path` which is used to check whether there's already an available model might be different or the logic could be flawed.

This is how the path to model looks like on a device
`/data/user/0/app_id/no_backup/com.google.firebase.ml.custom.models/some_hash/model_name/**id**`
This can be retrieved by printing `model.path`

The `id` parameter is an integer. 

What made me believe that model is getting downloaded _multiple times_ after each app upgrade is, after app upgrade the` id `parameter increases by 1 even though its the same model on remote.

Which is not the expected behaviour. The mode should only be re-download when  model updates on remote.

Even looking at the native code, I couldn't see a condition where the plugin checks for already installed models, compares hash and then only proceeds.

Am I missing something?
<img width="1095" alt="image" src="https://github.com/firebase/flutterfire/assets/20687565/57e30aa5-af60-448c-89fe-03b59514b2b0">

**Comment by saurabhkumar8112** [comment]
Thanks for your reply @Lyokone 
By app upgrade I meant, upgrading to a new version available on play-store/app-store. 
We use [upgrader](https://pub.dev/packages/upgrader) to ask users to upgrade the app when a new version is available. 

>My guess is that changing the firebase_core could impact how the hash is calculated

I think hash is not a problem here. As long as the model file is same, MD5 should return the same hash. My speculation is the `local file path` which is used to check whether there's already an available model might be different or the logic could be flawed.

This is how the path to model looks like on a device
`/data/user/0/app_id/no_backup/com.google.firebase.ml.custom.models/some_hash/model_name/**id**`
This can be retrieved by printing `model.path`

The `id` parameter is an integer. 

What made me believe that model is getting downloaded _multiple times_ after each app upgrade is, after app upgrade the` id `parameter increases by 1 even though its the same model on remote.

Which is not the expected behaviour. The mode should only be re-download when  model updates on remote.

Even looking at the native code, I couldn't see a condition where the plugin checks for already installed models, compares hash and then only proceeds.

Am I missing something?
<img width="1095" alt="image" src="https://github.com/firebase/flutterfire/assets/20687565/57e30aa5-af60-448c-89fe-03b59514b2b0">

**Comment by Lyokone** [comment]
When referring to the native code, we are only bridging using the native android and iOS SDK. 
I had a look at the native code for Android and couldn't find any condition that would force to redownload the model: https://github.com/firebase/firebase-android-sdk/blob/master/firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloader.java

You can probably open an issue on this repository to see if the native team has an idea about what could be happening: https://github.com/firebase/firebase-android-sdk
