### ISSUE TITLE
🐛 [firebase_analytics] Request for Release Including Recent Consent Changes

### ISSUE THREAD

**Issue by krishnamshah** [firebase/flutterfire#12528]
I've noticed that recent changes related to [user consent features](https://github.com/firebase/flutterfire/pull/12298) have been merged into the main branch. These updates are crucial for ensuring compliance with privacy regulations in my project. Could you please consider releasing a new version of the package that includes these changes? This would greatly assist in safely deploying our product to production with the necessary consent management features in place.

**Comment by russellwheatley** [comment]
It'll be getting released at some point today/tomorrow. Just need to check the CHANGELOG in the root of the repository for updates.
