### ISSUE TITLE
[firebase_storage]: <TypeError: Cannot read properties of undefined (reading 'getStorage')>

### ISSUE THREAD

**Issue by Sarathlal13** [firebase/flutterfire#12523]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Storage

### Which platforms are affected?

Web

### Description

Tryning upload image. Getting exception TypeError: Cannot read properties of undefined (reading 'getStorage') when call FirebaseStorage.instance.ref();

TypeError: Cannot read properties of undefined (reading 'getStorage')

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_shared/lib/js_util_patch.dart 110:58                    callMethod$
packages/firebase_storage_web/src/interop/storage.dart 31:25                      getStorageInstance
packages/firebase_storage_web/src/firebase_storage_web.dart 51:25                 get delegate
packages/firebase_storage_web/src/reference_web.dart 34:21                        new
packages/firebase_storage_web/src/firebase_storage_web.dart 111:12                [_createReference]
packages/firebase_storage_web/src/firebase_storage_web.dart 103:49                <fn>
packages/_flutterfire_internals/_flutterfire_internals.dart 120:21                guardWebExceptions
packages/firebase_storage_web/src/utils/errors.dart 20:20                         guard
packages/firebase_storage_web/src/firebase_storage_web.dart 101:12                ref
packages/firebase_storage/src/firebase_storage.dart 102:40                        ref
packages/mfq_admin_panel/controllers/video_controller.dart 31:36                  onInit
packages/get/get_instance/src/lifecycle.dart 66:5                                 [_onStart]
packages/get/get_instance/src/lifecycle.dart 12:15                                call
packages/get/get_instance/src/get_instance.dart 254:8                             [_startController]
packages/get/get_instance/src/get_instance.dart 205:11                            [_initDependencies]
packages/get/get_instance/src/get_instance.dart 302:17                            find
packages/get/get_instance/src/extension_instance.dart 69:45                       Inst.find
packages/mfq_admin_panel/ui/home/home_screen.dart 324:15                          onItemTapped
packages/mfq_admin_panel/ui/home/home_screen.dart 133:35                          <fn>
packages/flutter/src/material/ink_well.dart 1183:21                               handleTap
packages/flutter/src/gestures/recognizer.dart 315:24                              invokeCallback
packages/flutter/src/gestures/tap.dart 652:11                                     handleTapUp
packages/flutter/src/gestures/tap.dart 309:5                                      [_checkUp]
packages/flutter/src/gestures/tap.dart 242:7                                      handlePrimaryPointer
packages/flutter/src/gestures/recognizer.dart 670:9                               handleEvent
packages/flutter/src/gestures/pointer_router.dart 98:7                            [_dispatch]
packages/flutter/src/gestures/pointer_router.dart 143:9                           <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/linked_hash_map.dart 21:7           forEach
packages/flutter/src/gestures/pointer_router.dart 141:17                          [_dispatchEventToRoutes]
packages/flutter/src/gestures/pointer_router.dart 127:7                           route
packages/flutter/src/gestures/binding.dart 495:5                                  handleEvent
packages/flutter/src/gestures/binding.dart 475:14                                 dispatchEvent
packages/flutter/src/rendering/binding.dart 430:11                                dispatchEvent
packages/flutter/src/gestures/binding.dart 420:7                                  [_handlePointerEventImmediately]
packages/flutter/src/gestures/binding.dart 383:5                                  handlePointerEvent
packages/flutter/src/gestures/binding.dart 330:7                                  [_flushPointerEventQueue]
packages/flutter/src/gestures/binding.dart 299:9                                  [_handlePointerDataPacket]
lib/_engine/engine/platform_dispatcher.dart 1361:5                                invoke1
lib/_engine/engine/platform_dispatcher.dart 286:5                                 invokeOnPointerDataPacket
lib/_engine/engine/pointer_binding.dart 398:30                                    [_sendToFramework]
lib/_engine/engine/pointer_binding.dart 224:7                                     onPointerData
lib/_engine/engine/pointer_binding.dart 1001:20                                   <fn>
lib/_engine/engine/pointer_binding.dart 930:7                                     <fn>
lib/_engine/engine/pointer_binding.dart 531:9                                     loggedHandler
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 550:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 555:39  dcall

### Reproducing the issue

Done firebase configuration for Web platform

      Reference ref = FirebaseStorage.instance.ref();
      Reference dirRef = ref.child('shows');
      Reference nameRef = dirRef.child('image-$dateTime');
      final metadata = SettableMetadata(contentType: 'image/jpeg');
      uploadTask = nameRef.putData(imageAsBytes!, metadata);
      uploadTask.whenComplete(() => print('completed'));

### Firebase Core version

2.27.1

### Flutter Version

3.19.2

### Relevant Log Output

```shell
TypeError: Cannot read properties of undefined (reading 'getStorage')

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_shared/lib/js_util_patch.dart 110:58                    callMethod$
packages/firebase_storage_web/src/interop/storage.dart 31:25                      getStorageInstance
packages/firebase_storage_web/src/firebase_storage_web.dart 51:25                 get delegate
packages/firebase_storage_web/src/reference_web.dart 34:21                        new
packages/firebase_storage_web/src/firebase_storage_web.dart 111:12                [_createReference]
packages/firebase_storage_web/src/firebase_storage_web.dart 103:49                <fn>
packages/_flutterfire_internals/_flutterfire_internals.dart 120:21                guardWebExceptions
packages/firebase_storage_web/src/utils/errors.dart 20:20                         guard
packages/firebase_storage_web/src/firebase_storage_web.dart 101:12                ref
packages/firebase_storage/src/firebase_storage.dart 102:40                        ref
packages/mfq_admin_panel/controllers/video_controller.dart 31:36                  onInit
packages/get/get_instance/src/lifecycle.dart 66:5                                 [_onStart]
packages/get/get_instance/src/lifecycle.dart 12:15                                call
packages/get/get_instance/src/get_instance.dart 254:8                             [_startController]
packages/get/get_instance/src/get_instance.dart 205:11                            [_initDependencies]
packages/get/get_instance/src/get_instance.dart 302:17                            find
packages/get/get_instance/src/extension_instance.dart 69:45                       Inst.find
packages/mfq_admin_panel/ui/home/home_screen.dart 324:15                          onItemTapped
packages/mfq_admin_panel/ui/home/home_screen.dart 133:35                          <fn>
packages/flutter/src/material/ink_well.dart 1183:21                               handleTap
packages/flutter/src/gestures/recognizer.dart 315:24                              invokeCallback
packages/flutter/src/gestures/tap.dart 652:11                                     handleTapUp
packages/flutter/src/gestures/tap.dart 309:5                                      [_checkUp]
packages/flutter/src/gestures/tap.dart 242:7                                      handlePrimaryPointer
packages/flutter/src/gestures/recognizer.dart 670:9                               handleEvent
packages/flutter/src/gestures/pointer_router.dart 98:7                            [_dispatch]
packages/flutter/src/gestures/pointer_router.dart 143:9                           <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/linked_hash_map.dart 21:7           forEach
packages/flutter/src/gestures/pointer_router.dart 141:17                          [_dispatchEventToRoutes]
packages/flutter/src/gestures/pointer_router.dart 127:7                           route
packages/flutter/src/gestures/binding.dart 495:5                                  handleEvent
packages/flutter/src/gestures/binding.dart 475:14                                 dispatchEvent
packages/flutter/src/rendering/binding.dart 430:11                                dispatchEvent
packages/flutter/src/gestures/binding.dart 420:7                                  [_handlePointerEventImmediately]
packages/flutter/src/gestures/binding.dart 383:5                                  handlePointerEvent
packages/flutter/src/gestures/binding.dart 330:7                                  [_flushPointerEventQueue]
packages/flutter/src/gestures/binding.dart 299:9                                  [_handlePointerDataPacket]
lib/_engine/engine/platform_dispatcher.dart 1361:5                                invoke1
lib/_engine/engine/platform_dispatcher.dart 286:5                                 invokeOnPointerDataPacket
lib/_engine/engine/pointer_binding.dart 398:30                                    [_sendToFramework]
lib/_engine/engine/pointer_binding.dart 224:7                                     onPointerData
lib/_engine/engine/pointer_binding.dart 1001:20                                   <fn>
lib/_engine/engine/pointer_binding.dart 930:7                                     <fn>
lib/_engine/engine/pointer_binding.dart 531:9                                     loggedHandler
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 550:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 555:39  dcall
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_spinkit: ^5.2.0
  google_fonts: ^6.1.0
  video_player: ^2.7.2
  chewie: ^1.7.1
  dio: ^5.4.0
  oktoast: ^3.4.0
  cached_network_image: ^3.3.0
  firebase_core: ^2.27.1
  firebase_storage: ^11.6.10
  file_picker: ^8.0.0+1

```

</details>

**Comment by russellwheatley** [comment]
I tested your code (with slight updates so it would run) and I did not get the exception you are experiencing:

```dart
	Reference ref = FirebaseStorage.instance.ref();
	Reference dirRef = ref.child('flutter-tests');
	Reference nameRef = dirRef.child('image-something');
	final metadata = SettableMetadata(contentType: 'image/jpeg');
	final usint = Uint8List(10);
	final uploadTask = nameRef.putData(usint, metadata);
	await uploadTask.whenComplete(() => print('completed'));
```

We're going to need an updated code reproduction to verify the bug. Thanks.

**Comment by Sarathlal13** [comment]
Thanks, I am encountering an exception from this first line: Reference ref = FirebaseStorage.instance.ref();. The remaining lines are not executing.

In my Firebase project, I added a Web app and in my main function, I included:
WidgetsFlutterBinding.ensureInitialized();
await Firebase.initializeApp(options: DefaultFirebaseOptions.web);

Additionally, in the web folder's index.html file, I included:

<script src="https://www.gstatic.com/firebasejs/9.9.1/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/9.15.0/firebase-storage.js"></script>

I have also provided the firebaseConfig as follows inside index.html
  <script>
var firebaseConfig = {
     // Your Firebase configuration goes here
};
    // Initialize Firebase
    firebase.initializeApp(firebaseConfig);
  </script>

Am I missing something in configuration ?

**Comment by russellwheatley** [comment]
@Sarathlal13 - the scripts are auto-injected by the firebase_core plugin. Remove this code:

```js
<script src="https://www.gstatic.com/firebasejs/9.9.1/firebase-app.js"></script> <script src="https://www.gstatic.com/firebasejs/9.15.0/firebase-storage.js"></script>
I have also provided the firebaseConfig as follows inside index.html

<script> var firebaseConfig = { // Your Firebase configuration goes here }; // Initialize Firebase firebase.initializeApp(firebaseConfig); </script>
```

See Storage example `web/index.html`: https://github.com/firebase/flutterfire/blob/master/packages/firebase_storage/firebase_storage/example/web/index.html

**Comment by Sarathlal13** [comment]
"I removed the unwanted codes from index.html and also set up CORS as I saw in the example. Unfortunately, the error still persists. In the Chrome console, I'm getting..."

js_helper.dart:1196 Uncaught TypeError: Instance of 'NullError': type 'NullError' is not a subtype of type 'JavaScriptObject'
    at Object.wrapException (js_helper.dart:1196:37)
    at Object._failedAsCheck (rti.dart:1385:3)
    at Rti._generalAsCheckImplementation [as _as] (rti.dart:1363:3)
    at Object._testException (_flutterfire_internals.dart:82:38)
    at Object.guardWebExceptions (_flutterfire_internals.dart:152:10)
    at Object.guard (errors.dart:20:3)
    at FirebaseStorageWeb.ref$1 (firebase_storage_web.dart:101:12)
    at firebase_storage.dart:102:30
    at _wrapJsFunctionForAsync_closure.$protected (async_patch.dart:303:19)
    at _wrapJsFunctionForAsync_closure.call$2 (async_patch.dart:328:23)

**Comment by russellwheatley** [comment]
Have you ran `flutter clean`? This is almost certainly a problem with your setup. Follow the storage example to help you.

**Comment by Sarathlal13** [comment]
Thanks, issue has resolved
