### ISSUE TITLE
[firebase_messaging]: IOS Notification Images setup problem

### ISSUE THREAD

**Issue by lshong98** [firebase/flutterfire#12524]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you aware of the differences between iOS and Android background message handling?

- [X] I understand that iOS and Android background messages behave differently, and I've designed my application with that in mind.

### Do you have an active Apple Developer account?

- [X] I have an active Apple Developer account.

### Are you using a physical iOS device to test background messages?

- [X] I am using a physical iOS device to test background messages.

### Have you enabled "Remote Notifications" & "Background Mode" (Checking options for "Background Processing" & "Remote Notifications") in your app's Xcode project?

![Screenshot 2024-03-23 at 13 11 35](https://github.com/firebase/flutterfire/assets/31333309/8ea7c9ff-a480-4af6-a728-4f44a4e5511e)

### Have you created an APNs key in your Apple Developer account & uploaded this APNs key to your Firebase console?

![Screenshot 2024-03-23 at 13 17 05](https://github.com/firebase/flutterfire/assets/31333309/632f4396-1b97-4f7e-95d8-1456242e9a79)

### Have you disabled method swizzling for Firebase in your app?

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CADisableMinimumFrameDurationOnPhone</key>
	<true/>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleDisplayName</key>
	<string>$(BUNDLE_DISPLAY_NAME)</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$(BUNDLE_NAME)</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>trienekens</string>
			</array>
		</dict>
	</array>
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>sarawakpay</string>
	</array>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
		<key>NSAllowsArbitraryLoadsInWebContent</key>
		<true/>
	</dict>
	<key>NSCameraUsageDescription</key>
	<string>This app requires access to your gallery for evidence upload.</string>
	<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
	<string>This app requires access to location for request RoRo container.</string>
	<key>NSLocationAlwaysUsageDescription</key>
	<string>This app requires access to location for request RoRo container.</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>This app requires access to location for request RoRo container.</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>This app requires access to your gallery for evidence upload.</string>
	<key>UIApplicationSupportsIndirectInputEvents</key>
	<true/>
	<key>UIBackgroundModes</key>
	<array>
		<string>fetch</string>
		<string>remote-notification</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
</dict>
</plist>

### Are you sending messages to your app from the Firebase Admin SDK?

        var topic = req.body.target;

        var payloadWithTopic = {
            notification: {
                'title': req.body.title,
                'body': req.body.message
            },
            android: {
                notification: {
                    imageUrl: imgPublicUrl
                }
            },
            apns: {
                payload: {
                    aps: {
                        'mutable-content': 1
                    }
                },
                fcm_options: {
                    image: imgPublicUrl
                }
            },
            topic: topic
        };

        FCMAdmin.messaging().send(payloadWithTopic);

### Have you requested permission from the user to receive notifications?

- [X] I have the relevant permission to receive notifications.

### Have you used the 'Console' application on your macOS device to check if the iOS device's system is throttling your background messages?

i can't even build my app yet, so nothing to do with my ios device

### Additional context and comments

I am not able to build my app after adding in the ImageNotification

![Screenshot 2024-03-23 at 18 47 07](https://github.com/firebase/flutterfire/assets/31333309/56a7d409-fb14-4dfa-a9b2-a3b83271d6b8)

Below is the detail error message

![Screenshot 2024-03-23 at 18 48 53](https://github.com/firebase/flutterfire/assets/31333309/cae2eb84-97a6-458c-8d49-c52f81f91579)

Undefined symbols for architecture arm64:
  "_FlutterMethodNotImplemented", referenced from:
      -[FLTFirebaseMessagingPlugin handleMethodCall:result:] in firebase_messaging[4](FLTFirebaseMessagingPlugin.o)
      ___61-[FLTTileProviderController requestTileForX:y:zoom:receiver:]_block_invoke in google_maps_flutter_ios[5](FLTGoogleMapTileOverlayController.o)
      -[FLTGoogleMapController onMethodCall:result:] in google_maps_flutter_ios[8](GoogleMapController.o)
  "_OBJC_CLASS_$_FlutterBasicMessageChannel", referenced from:
       in firebase_core[7](messages.g.o)
  "_OBJC_CLASS_$_FlutterError", referenced from:
       in firebase_core[4](FLTFirebaseCorePlugin.o)
  "_OBJC_CLASS_$_FlutterMethodChannel", referenced from:
       in firebase_messaging[4](FLTFirebaseMessagingPlugin.o)
  "_OBJC_CLASS_$_FlutterStandardMessageCodec", referenced from:
       in firebase_core[7](messages.g.o)
  "_OBJC_CLASS_$_FlutterStandardReader", referenced from:
      _OBJC_CLASS_$_FirebaseCoreHostApiCodecReader in firebase_core[7](messages.g.o)
  "_OBJC_CLASS_$_FlutterStandardReaderWriter", referenced from:
      _OBJC_CLASS_$_FirebaseCoreHostApiCodecReaderWriter in firebase_core[7](messages.g.o)
  "_OBJC_CLASS_$_FlutterStandardTypedData", referenced from:
       in google_maps_flutter_ios[8](GoogleMapController.o)
  "_OBJC_CLASS_$_FlutterStandardWriter", referenced from:
      _OBJC_CLASS_$_FirebaseCoreHostApiCodecWriter in firebase_core[7](messages.g.o)
  "_OBJC_METACLASS_$_FlutterStandardReader", referenced from:
      _OBJC_METACLASS_$_FirebaseCoreHostApiCodecReader in firebase_core[7](messages.g.o)
  "_OBJC_METACLASS_$_FlutterStandardReaderWriter", referenced from:
      _OBJC_METACLASS_$_FirebaseCoreHostApiCodecReaderWriter in firebase_core[7](messages.g.o)
  "_OBJC_METACLASS_$_FlutterStandardWriter", referenced from:
      _OBJC_METACLASS_$_FirebaseCoreHostApiCodecWriter in firebase_core[7](messages.g.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Ignoring duplicate libraries: '-lsqlite3', '-lz'

Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found

Could not find or use auto-linked framework 'Flutter': framework 'Flutter' not found

Undefined symbol: _FlutterMethodNotImplemented

Undefined symbol: _OBJC_CLASS_$_FlutterBasicMessageChannel

Undefined symbol: _OBJC_CLASS_$_FlutterError

Undefined symbol: _OBJC_CLASS_$_FlutterMethodChannel

Undefined symbol: _OBJC_CLASS_$_FlutterStandardMessageCodec

Undefined symbol: _OBJC_CLASS_$_FlutterStandardReader

Undefined symbol: _OBJC_CLASS_$_FlutterStandardReaderWriter

Undefined symbol: _OBJC_CLASS_$_FlutterStandardTypedData

Undefined symbol: _OBJC_CLASS_$_FlutterStandardWriter

Undefined symbol: _OBJC_METACLASS_$_FlutterStandardReader

Undefined symbol: _OBJC_METACLASS_$_FlutterStandardReaderWriter

Undefined symbol: _OBJC_METACLASS_$_FlutterStandardWriter

Linker command failed with exit code 1 (use -v to see invocation)

**Comment by russellwheatley** [comment]
This isn't an issue with firebase_messaging, it looks like flutter iOS code itself is missing from source. Double check you have it in you pubspec.yaml, like in the [cloud_firestore example](https://github.com/firebase/flutterfire/blob/master/packages/cloud_firestore/cloud_firestore/example/pubspec.yaml#L10).

Then run:
```bash
flutter clean
flutter pub get
flutter run
```
