### ISSUE TITLE
[FirebaseMessaging]: PrivacyInfo.xcprivacy' of type 'text.xml' for architecture 'arm64'

### ISSUE THREAD

**Issue by jeremygraph** [firebase/flutterfire#12548]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Core, Messaging

### Which platforms are affected?

iOS

### Description

When i run the task xcode build for an adhoc version of my app i got an error 
 no rule to process file no rule to process file '/Users/runner/work/1/s/ios/Pods/FirebaseMessaging/FirebaseMessaging/Sources/Resources/PrivacyInfo.xcprivacy' of type 'text.xml' for architecture 'arm64' (in target 'FirebaseMessaging' from project 'Pods')

i found the same issue here: https://github.com/firebase/firebase-ios-sdk/issues/12511
and seems to be already fixe one the version 10.23.0 
https://github.com/firebase/firebase-ios-sdk/pull/12513

### Reproducing the issue

Install and build FirebaseMessaging 10.22.0 with CocoaPod

### Firebase Core version

2.27.2

### Flutter Version

3.19.5

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by TarekkMA** [comment]
Thank you, @jeremygraph, for reporting it. I will look into it.

**Comment by jeremygraph** [comment]
the issue has been closed. Do we have any news about it ? i'm still having issue de build on iOS.  @TarekkMA

**Comment by russellwheatley** [comment]
@jeremygraph  I think this should be resolved when we upgrade to firebase-ios-sdk  =>`10.23.0`. I will let you know when we have upgraded the underlying firebase-ios-sdk. Thank you for your patience 🙏

**Comment by jeremygraph** [comment]
@russellwheatley thanks for your anwser. Do you know when is it planned to upgrade firebase-ios-sdk ?

**Comment by russellwheatley** [comment]
When we have updated the firestore-ios-frameworks to handle the latest firebase-ios-sdk: https://github.com/invertase/firestore-ios-sdk-frameworks/pull/95

Once this is released and confirmed as working, we will update the firebase-ios-sdk version 👌

**Comment by jeremygraph** [comment]
sorry to reopen it but we probably have an issue on
[this podsec](https://github.com/firebase/flutterfire/blob/213608cf7d889aeb60084ef5fb74a1e74178d7ba/packages/firebase_messaging/firebase_messaging/ios/firebase_messaging.podspec#L28) compare to this fix https://github.com/firebase/firebase-ios-sdk/commit/01c7d950dbea30720dfb560f45d28d8611c654e2 
I keep having the same error on the lastest update of the lib

**Comment by russellwheatley** [comment]
Hey @jeremygraph - have you tried the latest FlutterFire firebase_messaging release? It contains the firebase-ios-sdk update which might solve your problem. Let me know if it doesn't. Thanks 🙏

**Comment by jeremygraph** [comment]
hello @russellwheatley, I tried 14.8.1 and it doesn't solve the problem. Did you check the podspec, it sounds fine for you ?

**Comment by russellwheatley** [comment]
@jeremygraph - could you reproduce this exception locally? i.e. build/archive the project which has this build error? It would make debugging this issue easy. 

I would like to see you podfile.lock as well, please.

I am not convinced that changing the source property in firebase_messaging will have an effect. The reason why this is a fix: https://github.com/firebase/firebase-ios-sdk/commit/01c7d950dbea30720dfb560f45d28d8611c654e2

is because it no longer makes the privacy manifest xml file part of the source files. firebase_messaging does not include the privacy manifest in the source files: https://github.com/firebase/flutterfire/blob/213608cf7d889aeb60084ef5fb74a1e74178d7ba/packages/firebase_messaging/firebase_messaging/ios/firebase_messaging.podspec#L28

But the original exception is coming from the FirebaseMessaging privacy manifest, not the firebase_messaging plugin.

**Comment by jeremygraph** [comment]
Alright thanks for the explanation @russellwheatley , well i don't have any issues locally. That's why it's a bit complicated to handle it. 
<details>
<summary>podfile.lock</summary>

PODS:
  - connectivity_plus (0.0.1):
    - Flutter
    - FlutterMacOS
  - Firebase/Analytics (10.22.0):
    - Firebase/Core
  - Firebase/Auth (10.22.0):
    - Firebase/CoreOnly
    - FirebaseAuth (~> 10.22.0)
  - Firebase/Core (10.22.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (~> 10.22.0)
  - Firebase/CoreOnly (10.22.0):
    - FirebaseCore (= 10.22.0)
  - Firebase/Crashlytics (10.22.0):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 10.22.0)
  - Firebase/Messaging (10.22.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 10.22.0)
  - firebase_analytics (10.10.1):
    - Firebase/Analytics (= 10.22.0)
    - firebase_core
    - Flutter
  - firebase_auth (4.19.1):
    - Firebase/Auth (= 10.22.0)
    - firebase_core
    - Flutter
  - firebase_core (2.29.0):
    - Firebase/CoreOnly (= 10.22.0)
    - Flutter
  - firebase_crashlytics (3.5.1):
    - Firebase/Crashlytics (= 10.22.0)
    - firebase_core
    - Flutter
  - firebase_messaging (14.8.1):
    - Firebase/Messaging (= 10.22.0)
    - firebase_core
    - Flutter
  - FirebaseAnalytics (10.22.0):
    - FirebaseAnalytics/AdIdSupport (= 10.22.0)
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - FirebaseAnalytics/AdIdSupport (10.22.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleAppMeasurement (= 10.22.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - FirebaseAppCheckInterop (10.24.0)
  - FirebaseAuth (10.22.0):
    - FirebaseAppCheckInterop (~> 10.17)
    - FirebaseCore (~> 10.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/Environment (~> 7.8)
    - GTMSessionFetcher/Core (< 4.0, >= 2.1)
    - RecaptchaInterop (~> 100.0)
  - FirebaseCore (10.22.0):
    - FirebaseCoreInternal (~> 10.0)
    - GoogleUtilities/Environment (~> 7.12)
    - GoogleUtilities/Logger (~> 7.12)
  - FirebaseCoreExtension (10.24.0):
    - FirebaseCore (~> 10.0)
  - FirebaseCoreInternal (10.24.0):
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
  - FirebaseCrashlytics (10.22.0):
    - FirebaseCore (~> 10.5)
    - FirebaseInstallations (~> 10.0)
    - FirebaseSessions (~> 10.5)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.8)
    - nanopb (< 2.30911.0, >= 2.30908.0)
    - PromisesObjC (~> 2.1)
  - FirebaseInstallations (10.24.0):
    - FirebaseCore (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - PromisesObjC (~> 2.1)
  - FirebaseMessaging (10.22.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleDataTransport (~> 9.3)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/Reachability (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - FirebaseSessions (10.24.0):
    - FirebaseCore (~> 10.5)
    - FirebaseCoreExtension (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.10)
    - nanopb (< 2.30911.0, >= 2.30908.0)
    - PromisesSwift (~> 2.1)
  - Flutter (1.0.0)
  - flutter_native_splash (0.0.1):
    - Flutter
  - fluttertoast (0.0.2):
    - Flutter
    - Toast
  - Google-Mobile-Ads-SDK (11.2.0):
    - GoogleUserMessagingPlatform (>= 1.1)
  - google_mobile_ads (1.0.0):
    - Flutter
    - Google-Mobile-Ads-SDK (~> 11.2.0)
    - webview_flutter_wkwebview
  - GoogleAppMeasurement (10.22.0):
    - GoogleAppMeasurement/AdIdSupport (= 10.22.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - GoogleAppMeasurement/AdIdSupport (10.22.0):
    - GoogleAppMeasurement/WithoutAdIdSupport (= 10.22.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - GoogleAppMeasurement/WithoutAdIdSupport (10.22.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - GoogleDataTransport (9.4.1):
    - GoogleUtilities/Environment (~> 7.7)
    - nanopb (< 2.30911.0, >= 2.30908.0)
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUserMessagingPlatform (2.3.0)
  - GoogleUtilities/AppDelegateSwizzler (7.13.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
    - GoogleUtilities/Privacy
  - GoogleUtilities/Environment (7.13.0):
    - GoogleUtilities/Privacy
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/Logger (7.13.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Privacy
  - GoogleUtilities/MethodSwizzler (7.13.0):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - GoogleUtilities/Network (7.13.0):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Privacy
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (7.13.0)":
    - GoogleUtilities/Privacy
  - GoogleUtilities/Privacy (7.13.0)
  - GoogleUtilities/Reachability (7.13.0):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - GoogleUtilities/UserDefaults (7.13.0):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - GTMSessionFetcher/Core (3.3.2)
  - nanopb (2.30910.0):
    - nanopb/decode (= 2.30910.0)
    - nanopb/encode (= 2.30910.0)
  - nanopb/decode (2.30910.0)
  - nanopb/encode (2.30910.0)
  - package_info_plus (0.4.5):
    - Flutter
  - permission_handler_apple (9.3.0):
    - Flutter
  - PromisesObjC (2.4.0)
  - PromisesSwift (2.4.0):
    - PromisesObjC (= 2.4.0)
  - RecaptchaInterop (100.0.0)
  - shared_preferences_foundation (0.0.1):
    - Flutter
    - FlutterMacOS
  - Toast (4.1.1)
  - url_launcher_ios (0.0.1):
    - Flutter
  - webview_flutter_wkwebview (0.0.1):
    - Flutter

DEPENDENCIES:
  - connectivity_plus (from `.symlinks/plugins/connectivity_plus/darwin`)
  - firebase_analytics (from `.symlinks/plugins/firebase_analytics/ios`)
  - firebase_auth (from `.symlinks/plugins/firebase_auth/ios`)
  - firebase_core (from `.symlinks/plugins/firebase_core/ios`)
  - firebase_crashlytics (from `.symlinks/plugins/firebase_crashlytics/ios`)
  - firebase_messaging (from `.symlinks/plugins/firebase_messaging/ios`)
  - Flutter (from `Flutter`)
  - flutter_native_splash (from `.symlinks/plugins/flutter_native_splash/ios`)
  - fluttertoast (from `.symlinks/plugins/fluttertoast/ios`)
  - google_mobile_ads (from `.symlinks/plugins/google_mobile_ads/ios`)
  - package_info_plus (from `.symlinks/plugins/package_info_plus/ios`)
  - permission_handler_apple (from `.symlinks/plugins/permission_handler_apple/ios`)
  - shared_preferences_foundation (from `.symlinks/plugins/shared_preferences_foundation/darwin`)
  - url_launcher_ios (from `.symlinks/plugins/url_launcher_ios/ios`)
  - webview_flutter_wkwebview (from `.symlinks/plugins/webview_flutter_wkwebview/ios`)

SPEC REPOS:
  trunk:
    - Firebase
    - FirebaseAnalytics
    - FirebaseAppCheckInterop
    - FirebaseAuth
    - FirebaseCore
    - FirebaseCoreExtension
    - FirebaseCoreInternal
    - FirebaseCrashlytics
    - FirebaseInstallations
    - FirebaseMessaging
    - FirebaseSessions
    - Google-Mobile-Ads-SDK
    - GoogleAppMeasurement
    - GoogleDataTransport
    - GoogleUserMessagingPlatform
    - GoogleUtilities
    - GTMSessionFetcher
    - nanopb
    - PromisesObjC
    - PromisesSwift
    - RecaptchaInterop
    - Toast

EXTERNAL SOURCES:
  connectivity_plus:
    :path: ".symlinks/plugins/connectivity_plus/darwin"
  firebase_analytics:
    :path: ".symlinks/plugins/firebase_analytics/ios"
  firebase_auth:
    :path: ".symlinks/plugins/firebase_auth/ios"
  firebase_core:
    :path: ".symlinks/plugins/firebase_core/ios"
  firebase_crashlytics:
    :path: ".symlinks/plugins/firebase_crashlytics/ios"
  firebase_messaging:
    :path: ".symlinks/plugins/firebase_messaging/ios"
  Flutter:
    :path: Flutter
  flutter_native_splash:
    :path: ".symlinks/plugins/flutter_native_splash/ios"
  fluttertoast:
    :path: ".symlinks/plugins/fluttertoast/ios"
  google_mobile_ads:
    :path: ".symlinks/plugins/google_mobile_ads/ios"
  package_info_plus:
    :path: ".symlinks/plugins/package_info_plus/ios"
  permission_handler_apple:
    :path: ".symlinks/plugins/permission_handler_apple/ios"
  shared_preferences_foundation:
    :path: ".symlinks/plugins/shared_preferences_foundation/darwin"
  url_launcher_ios:
    :path: ".symlinks/plugins/url_launcher_ios/ios"
  webview_flutter_wkwebview:
    :path: ".symlinks/plugins/webview_flutter_wkwebview/ios"

SPEC CHECKSUMS:
  connectivity_plus: ddd7f30999e1faaef5967c23d5b6d503d10434db
  Firebase: 797fd7297b7e1be954432743a0b3f90038e45a71
  firebase_analytics: 8e6cecb9b9541db49ac40a46eec7c0f519de7252
  firebase_auth: 35e39b82fa6703db53401e2d8708341597edc7be
  firebase_core: aaadbddb3cb2ee3792b9804f9dbb63e5f6f7b55c
  firebase_crashlytics: 4271b5bb77f6169ac7c2a9d62ad0e6aa5f84c2fe
  firebase_messaging: 860e28c6ad8b3281276eba922024644b9909c903
  FirebaseAnalytics: 8d0ff929c63b7f72260f332b86ccf569776b75d3
  FirebaseAppCheckInterop: fecc08c89936c8acb1428d8088313aabedb348e4
  FirebaseAuth: bbe4c68f958504ba9e54aee181adbdf5b664fbc6
  FirebaseCore: 0326ec9b05fbed8f8716cddbf0e36894a13837f7
  FirebaseCoreExtension: af5fd85e817ea9d19f9a2659a376cf9cf99f03c0
  FirebaseCoreInternal: bcb5acffd4ea05e12a783ecf835f2210ce3dc6af
  FirebaseCrashlytics: e568d68ce89117c80cddb04073ab9018725fbb8c
  FirebaseInstallations: 8f581fca6478a50705d2bd2abd66d306e0f5736e
  FirebaseMessaging: 9f71037fd9db3376a4caa54e5a3949d1027b4b6e
  FirebaseSessions: 2651b464e241c93fd44112f995d5ab663c970487
  Flutter: e0871f40cf51350855a761d2e70bf5af5b9b5de7
  flutter_native_splash: edf599c81f74d093a4daf8e17bd7a018854bc778
  fluttertoast: 9f2f8e81bb5ce18facb9748d7855bf5a756fe3db
  Google-Mobile-Ads-SDK: 5a6d005a6cb5b5e8f4c7b69ca05cdea79c181139
  google_mobile_ads: 5698dd1cd5a3cfc6688abec7db5428f237d6b1ac
  GoogleAppMeasurement: ccefe3eac9b0aa27f96066809fb1a7fe4b462626
  GoogleDataTransport: 6c09b596d841063d76d4288cc2d2f42cc36e1e2a
  GoogleUserMessagingPlatform: b1ad7bb1ee3ce64749d4fec24f667b36e45c396c
  GoogleUtilities: d053d902a8edaa9904e1bd00c37535385b8ed152
  GTMSessionFetcher: 0e876eea9782ec6462e91ab872711c357322c94f
  nanopb: 438bc412db1928dac798aa6fd75726007be04262
  package_info_plus: 58f0028419748fad15bf008b270aaa8e54380b1c
  permission_handler_apple: 9878588469a2b0d0fc1e048d9f43605f92e6cec2
  PromisesObjC: f5707f49cb48b9636751c5b2e7d227e43fba9f47
  PromisesSwift: 9d77319bbe72ebf6d872900551f7eeba9bce2851
  RecaptchaInterop: 7d1a4a01a6b2cb1610a47ef3f85f0c411434cb21
  shared_preferences_foundation: b4c3b4cddf1c21f02770737f147a3f5da9d39695
  Toast: 1f5ea13423a1e6674c4abdac5be53587ae481c4e
  url_launcher_ios: 6116280ddcfe98ab8820085d8d76ae7449447586
  webview_flutter_wkwebview: be0f0d33777f1bfd0c9fdcb594786704dbf65f36

PODFILE CHECKSUM: 496e113e85a60ea951648234ba22359eda20ad21

COCOAPODS: 1.15.2


</details>

**Comment by jeremygraph** [comment]
Oh you're right i forgot to update versions from the podfile. I don't have anymore the issue thanks for your help.
