### ISSUE TITLE
[firebase_analytics_web]: Firebase analytics for Flutter web is not working

### ISSUE THREAD

**Issue by rajubhusani** [firebase/flutterfire#12546]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Analytics

### Which platforms are affected?

Web

### Description

Uncaught MissingPluginException(No implementation found for method Analytics#setAnalyticsCollectionEnabled on channel plugins.flutter.io/firebase_analytics)
And the logging is not working.

### Reproducing the issue

Integrate the Flutter firebase analytics web plugin and tried to firebase_analytics plugin also.. For both the plugins it is not working.. Do we need to go JAVAscript route for flutter web?

### Firebase Core version

2.7.1

### Flutter Version

3.7.10

### Relevant Log Output

```shell
Uncaught MissingPluginException(No implementation found for method Analytics#setAnalyticsCollectionEnabled on channel plugins.flutter.io/firebase_analytics)
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by Lyokone** [comment]
Hi 👋 I see that you are using a much older version of firebase_core than the current one, can you update to `firebase_core: ^2.27.2`

**Comment by rajubhusani** [comment]
But what is the way of integrating the analytics to Flutter web application. Is it similar to Flutter mobile ?

**Comment by rajubhusani** [comment]
We are using 3.7.11 flutter version.. Any one can update on this

**Comment by tuotau-lessonapp** [comment]
I think we have a related issue, the Firebase Analytics works fine on the debug build, but on the production build we get the following error when trying to log an event:

Uncaught : MissingPluginException(No implementation found for method Analytics#logEvent on channel plugins.flutter.io/firebase_analytics)

We have following versions in use:
firebase_core 2.30.1
firebase_analytics 10.10.4

@Lyokone

**Comment by tuotau-lessonapp** [comment]
Browsing the other bug reports it seems that it could be related to using canvaskit instead of html for the rendering.

We're building our app with: flutter build web --web-renderer canvaskit --release

**Comment by tuotau-lessonapp** [comment]
It seems to have been some sort of caching error most likely, because today it's working without any additional changes...

**Comment by TarekkMA** [comment]
@rajubhusani Can you confirm if you still having issues using the latest version of firebase?
