### ISSUE TITLE
Note: plugin use deprecated API

### ISSUE THREAD

**Issue by malak4822** [firebase/flutterfire#12552]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

App Check

### Which platforms are affected?

Android

### Description

After updating plugin to this version wihtin the build process I started to see this warning:

'''Note: /Users/malak/.pub-cache/hosted/pub.dev/firebase_app_check-0.2.1+19/android/src/main/java/io/flutter/plugins/firebase/appcheck/FlutterFirebaseAppCheckPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.'''

### Reproducing the issue

I just updated plugin version in pubspec.yaml file and note started to show every time I build app.

### Firebase Core version

2.27.2

### Flutter Version

3.19.5

### Relevant Log Output

```shell
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
Note: /Users/malak/.pub-cache/hosted/pub.dev/cloud_firestore-4.15.10/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/malak/.pub-cache/hosted/pub.dev/firebase_app_check-0.2.1+19/android/src/main/java/io/flutter/plugins/firebase/appcheck/FlutterFirebaseAppCheckPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by Lyokone** [comment]
Hello @malak4822, those warnings are caused because we are still supporting SafetyNet even though it has been deprecated: https://developer.android.com/privacy-and-security/safetynet/deprecation-timeline
We will not be removing those warnings before end of January 2025.
