### ISSUE TITLE
🐛 [cloud_firestore] Query with range and inequality filters on multiple fields

### ISSUE THREAD

**Issue by perret123** [firebase/flutterfire#12550]
## What feature would you like to see?

Since a few days, Firestore is supporting range queries on multiple fields 👍 I have been waiting for this for a long time - now I would like to see support for this in Flutter Fire. 

See the documentation here:
https://firebase.google.com/docs/firestore/query-data/multiple-range-fields

Currently, even if the latest Version of the Native SDKs would already support this, it is not possible because of the following assertion in `query.dart`:

```dart 
      if (_isInequality(operator)) {
        if (hasInequality == null) {
          hasInequality = field;
        } else {
          assert(
            hasInequality == field,
            'All where filters with an inequality (<, <=, >, or >=) must be '
            "on the same field. But you have inequality filters on '$hasInequality' and '$field'.",
          );
        }
      }
```

The feature is still in "public preview", but I feel like this is a great addition that should be included as soon as possible - or whenever it makes sense for the maintainers of this package :)

Thank you very much for your work on this, it is greatly appreciated. Thank you.🙇‍♂️

**Comment by Lyokone** [comment]
Hello @perret123, we were waiting on the official release to remove this assert. It will be part of today's release 😁✌️
