### ISSUE TITLE
[📚] [cloud_firestore]: enablePersistence is deprecated

### ISSUE THREAD

**Issue by Macacoazul01** [firebase/flutterfire#12553]
On my project we have both a mobile and web implementation and we tried to implement firestore local persistence but when trying to enable it there is this warning on the parameter:

`Attempts to enable persistent storage, if possible. This setting has no effect on Web, for Web use [FirebaseFirestore.enablePersistence] instead.`

```
firestoreInstance.settings = const Settings(
  persistenceEnabled: true,
);
```

but if i try to use the above code, there is another one:

```
firestoreInstance.enablePersistence();

'enablePersistence' is deprecated and shouldn't be used. Use Settings.persistenceEnabled instead.
```

So the final code we are using is this one:

```
if (kIsWeb) {
    await Firebase.initializeApp(
      options: prodOptions,
    );

    firestoreInstance.enablePersistence();
  } else {
    await Firebase.initializeApp();
    firestoreInstance.settings = const Settings(
      persistenceEnabled: true,
    );
  }
```

Is this still true (This setting has no effect on Web, for Web use [FirebaseFirestore.enablePersistence]) and the team forgot to fix the docs?

**Comment by Lyokone** [comment]
Thanks for the report @Macacoazul01, I've created a PR to fix the documentation, you can use `persistenceEnabled` it has been enabled for web.
