### ISSUE TITLE
Bump `compileSdk` version of Android plugins to latest stable (34)

### ISSUE THREAD

**Issue by bartekpacia** [firebase/flutterfire#12555]
Hi maintainers of FlutterFire!

I'd like to request all Android plugins in FlutterFire to be bumped to `compileSdk 34`.

Currently [almost all plugins](https://github.com/search?q=repo%3Afirebase%2Fflutterfire+compileSdk&type=code) are compiled against Android SDK 33, which results in this SDK always downloaded ([Learn more about this issue here](https://github.com/flutter/flutter/issues/63533#issuecomment-2027851231)).

**Comment by Lyokone** [comment]
Hey @bartekpacia, thanks for the suggestions, I've created https://github.com/firebase/flutterfire/pull/12566 to fix this since I don't see any downside to updating to `compileSdk` 34
