### ISSUE TITLE
Captcha doesn't appear when verifying phone number

### ISSUE THREAD

**Issue by rsegecin** [firebase/flutterfire#12587]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Auth

### Which platforms are affected?

Web

### Description

`FirebaseAuth.instance.signInWithPhoneNumber` won't show recaptcha and consequently it doesn't follow through with the signin. 

<img width="1694" alt="captcha error" src="https://github.com/firebase/flutterfire/assets/4460859/bc656f98-fe07-48a0-98ef-3e56802d9639">

### Reproducing the issue

create firebase account 
add phone as authentication method
add "localhost" on Athentication > settings > authorized Domains

create flutter project
add firebase libs
run flutterfire configure
add on main:
```
await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
```

run code 
```
FirebaseAuth auth = FirebaseAuth.instance;

ConfirmationResult confirmationResult = await auth.signInWithPhoneNumber('+[your phone number]');
```

### Firebase Core version

2.28.0

### Flutter Version

3.19.1

### Flutter dependencies

name: phonetest
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.28.0
  firebase_auth: ^4.19.0
  firebase_auth_web: ^5.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

### Additional context and comments

In the same project even though I can't validate a phone I'm able to use firebase's Google Login, so it's not something to do with Firebase authentication.

**Comment by TarekkMA** [comment]
Hi @rsegecin, please add a title to your issue.

**Comment by rsegecin** [comment]
> Hi @rsegecin, please add a title to your issue.

I'm sorry, thanks.

**Comment by TarekkMA** [comment]
Thank you @rsegecin, I've reproduced this issue.


cc @Lyokone

**Comment by Lyokone** [comment]
Thanks for the report, I'm having a look @rsegecin

**Comment by Lyokone** [comment]
I'm reproducing the issue, but the recaptcha, even if not showing is actually properly created in the DOM 🤔 
![Screenshot 2024-04-04 at 15 02 22](https://github.com/firebase/flutterfire/assets/3680002/10f0364e-952d-4ade-b037-e21339c6bf3e)

**Comment by rsegecin** [comment]
Yeah, everything appears to be loading correctly, but the captcha dialog isn't showing up.

**Comment by Lyokone** [comment]
@rsegecin This is normal we try to use an invisible catpcha by default
```
      parameters['size'] = 'invisible';
```

**Comment by Lyokone** [comment]
Found the issue, some types weren't properly transformed using the new `dart:js_interop`

**Comment by rsegecin** [comment]
When I grow up I wanna be like you. Actually I'm really curious on how you found this issue, do you work with this are you on a google team? DM me if you have the time. thanks. Ohh and how long do you think its going to take a release with a fix to come out?

**Comment by rsegecin** [comment]
I think I'll wait, lots of dependency issues, Thank you @Lyokone you're the best.

**Comment by Lyokone** [comment]
```
firebase_auth_web:
  git:
    url: https://github.com/firebase/flutterfire.git
    ref: master
    path: packages/firebase_auth/firebase_auth_web
```
It should work with that
