### ISSUE TITLE
[firebase_messaging]: _firebaseMessagingBackgroundHandler isn't triggered on ios

### ISSUE THREAD

**Issue by hihan-danbi** [firebase/flutterfire#12582]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you aware of the differences between iOS and Android background message handling?

- [X] I understand that iOS and Android background messages behave differently, and I've designed my application with that in mind.

### Do you have an active Apple Developer account?

- [X] I have an active Apple Developer account.

### Are you using a physical iOS device to test background messages?

- [X] I am using a physical iOS device to test background messages.

### Have you enabled "Remote Notifications" & "Background Mode" (Checking options for "Background Processing" & "Remote Notifications") in your app's Xcode project?

![image](https://github.com/firebase/flutterfire/assets/110805570/871c2e79-80b9-4937-b17b-e26348c57b07)

### Have you created an APNs key in your Apple Developer account & uploaded this APNs key to your Firebase console?

<img width="985" alt="image" src="https://github.com/firebase/flutterfire/assets/110805570/fd576343-702b-4cac-86b7-ea16502f43aa">

### Have you disabled method swizzling for Firebase in your app?

![image](https://github.com/firebase/flutterfire/assets/110805570/5e44cdd3-52b0-4f60-831c-b383ab67cfab)

### Are you sending messages to your app from the Firebase Admin SDK?

![image](https://github.com/firebase/flutterfire/assets/110805570/5f9a57b2-bb52-4e83-bc9e-0f69b70cc0f1)

### Have you requested permission from the user to receive notifications?

- [X] I have the relevant permission to receive notifications.

### Have you used the 'Console' application on your macOS device to check if the iOS device's system is throttling your background messages?

![image](https://github.com/firebase/flutterfire/assets/110805570/cab95a46-010c-4faf-9577-cd78acbb7560)

### Additional context and comments

![image](https://github.com/firebase/flutterfire/assets/110805570/95e61292-91a8-4d48-bf00-92d52dec9e83)
![image](https://github.com/firebase/flutterfire/assets/110805570/08179867-b693-447d-9199-de8cb4656687)

I added the log to the Appdelegate File. When the push received, the log was clearly visible.
But the log of the flutter's '_firebaseMessagingBackgroundHandler' is not visible.

![image](https://github.com/firebase/flutterfire/assets/110805570/eba02ad7-c5cf-445a-8a9a-669bf8eb3bbd)

**Comment by russellwheatley** [comment]
@hihan-danbi - why is there a swift implementation of `didReceiveRemoteNotification`?

It is already implemented on the messaging plugin:
https://github.com/firebase/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/ios/Classes/FLTFirebaseMessagingPlugin.m#L424

That might be a problem for the plugin receiving messages from APNS.

**Comment by hihan-danbi** [comment]
I added it to take a log for error verification. But it doesn't work when I delete it.
If I add notification to the FCM body, I also get push well in the background. 
But I'm going to use silent push, so if I remove notification, I don't get it both in the foreground and background

**Comment by russellwheatley** [comment]
@hihan-danbi - thanks for letting us know you have found a solution for your issue. I'm unsure if there is anything to fix on FlutterFire as I know that background messages do work. Can we close this issue out now?
