### ISSUE TITLE
Still 3 references to dart:html

### ISSUE THREAD

**Issue by kevmoo** [firebase/flutterfire#12597]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Other

### Which platforms are affected?

Web

### Description

```console
> github/flutterfire git:(master) git gp 'dart:html'
packages/firebase_app_check/firebase_app_check_web/lib/firebase_app_check_web.dart:6:import 'dart:html';
packages/firebase_core/firebase_core_web/test/tools.dart:5:import 'dart:html';
packages/firebase_storage/firebase_storage/example/lib/save_as/save_as_html.dart:6:import 'dart:html';
```

```console
> github/flutterfire git:(master) git gp 'dart.library'
packages/_flutterfire_internals/lib/_flutterfire_internals.dart:17:    if (dart.library.js) 'package:firebase_core_web/firebase_core_web_interop.dart'
packages/firebase_storage/firebase_storage/example/lib/save_as/save_as.dart:5:export 'save_as_interface.dart' if (dart.library.html) 'save_as_html.dart';
```

See https://github.com/firebase/flutterfire/issues/12027#issuecomment-2040207666

as of 1b6ef73935062a4fa2c43bb4ef9b6d080a3ca5b4

### Reproducing the issue

Grep the source

### Firebase Core version

???

### Flutter Version

n/a

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by Lyokone** [comment]
Thanks for raising this, it will be part of next release scheduled for tomorrow
