### ISSUE TITLE
[firebase_app_check]: doesn't pass in Play Store Pre-Launch Report

### ISSUE THREAD

**Issue by xVemu** [firebase/flutterfire#12628]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

App Check

### Which platforms are affected?

Android

### Description

I'm using Firebase App Check to protect my backend. When I upload my app to Google Play, it produces Pre-launch report. It contains screenshots with error about unavailable app check token. I can also see in Firebase Crashalytics, that test device reported errors indicating the same issue. Is it possible to use some kind of debug provider in Pre-launch report?

### Reproducing the issue

Upload app to play store.

### Firebase Core version

2.29.0

### Flutter Version

3.19.5

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

firebase_app_check: ^0.2.2+1

```

</details>

**Comment by russellwheatley** [comment]
@xVemu - Difficult to figure out what the issue is without any context or access to the project. Out of curiosity, have you test the app on internal, open or closed testing via Google play console to check that the app works with app check enforcement? i.e. you're able to use plugins were you have enforced app check?

**Comment by xVemu** [comment]
> @xVemu - Difficult to figure out what the issue is without any context or access to the project. Out of curiosity, have you test the app on internal, open or closed testing via Google play console to check that the app works with app check enforcement? i.e. you're able to use plugins where you have enforced app check?

I'm using closed testing. The issue occurs only when Google performs their automated test on the app. Later, when I download it on my device, everything works fine.

**Comment by russellwheatley** [comment]
@xVemu - Could you ask [Firebase support](https://firebase.google.com/support/troubleshooter/contact) why it is failing and provide details from the pre-launch report? It appears to be a configuration issue that isn't solved by a fix on FlutterFire.

**Comment by xVemu** [comment]
I've contacted Firebase support, and they told me to add signing key to SHA-256 certificate fingerprint, but it didn't work out. The same issue appears when running with Test Lab inside Firebase Console.
