### ISSUE TITLE
[firebase auth]: Flutter, ReactNative apps hit Error code 39 (QuotaExceeded) message is too vague, shows on blaze plan

### ISSUE THREAD

**Issue by nyenloop** [firebase/flutterfire#12637]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Auth

### Which platforms are affected?

Android, iOS, Web

### Description

Hi!
I got an internal error, code 39 when using calling the verifyphone method of phone sign in. Can you give me any specifics, what causes this error? Is there a list?
Thanks a lot in advance!

### Reproducing the issue

I faced this error when I tried to logged in by using phoneNumber.
This functions have worked normally for 2 years.
I tested with many phoneNumbers that I have.

Error: {"error":{"code":503,"message":"Error code: 39","errors":[{"message":"Error code: 39","domain":"global","reason":"backendError"}]}}

### Firebase Core version

2.27.0

### Flutter Version

3.19.0

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by russellwheatley** [comment]
The exception is QuotaExceeded, this means you have hit the limit for the IP address. You might be able to whitelist your phone number which you can do in the Firebase console. Although, you will still have to wait until the temporary restriction is lifted by the Firebase server. (i.e. whitelist your phone number and wait a day for the ban to be lifted). This isn't something to be fixed on FlutterFire so I am closing it out.
