### ISSUE TITLE
[DatabaseReference]: <Firebase realtime database onvalue event don't work>

### ISSUE THREAD

**Issue by guvenacar** [firebase/flutterfire#12642]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Database

### Which platforms are affected?

Android, Web, Windows

### Description

I have firebase realtime database. When I manually change data on the Firebase console, vscode stops responding and throws the following error.

`Error: TypeError: Instance of '_Exception': type '_Exception' is not a subtype of type 'JavaScriptObject'`

### Reproducing the issue

```dart
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_database/firebase_database.dart';
import 'package:flutter/material.dart';
import 'package:realtimedbtest/firebase_options.dart';


String result = "";

void main()  async { 
WidgetsFlutterBinding.ensureInitialized(); 
await Firebase.initializeApp(
options: DefaultFirebaseOptions.currentPlatform,   
 );

DatabaseReference ref = FirebaseDatabase.instance.ref('widget/image/name'); 
ref.onValue.listen((DatabaseEvent event)     { 
result =   event.snapshot.value.toString();
});

runApp(const MainApp());
}

class MainApp extends StatelessWidget {
 const MainApp({super.key});

@override
  Widget build(BuildContext context) {
   return  MaterialApp(
    home: Scaffold(
      body: Center(
       child: Text("result: $result"),
      ),
     ),
   );
  }
}
```

### Firebase Core version

2.29.0

### Flutter Version

3.19.5

### Relevant Log Output

```shell
`Error: TypeError: Instance of '_Exception': type '_Exception' is not a subtype of type 'JavaScriptObject'`
```

### Flutter dependencies

 firebase_core.dart
 firebase_database.dart
 firebase_options.dart

**Comment by russellwheatley** [comment]
Hi @guvenacar, I was able to reproduce and there is a PR to fix.
