### ISSUE TITLE
[Analytics]: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.11, but the range of supported deployment target versions is 10.13 to 13.3.99

### ISSUE THREAD

**Issue by stephane-archer** [firebase/flutterfire#12641]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Analytics

### Which platforms are affected?

macOS

### Description

When building my app using firebase
```
/Users/fractale/lut_viewer/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.11, but the range of supported deployment target versions is 10.13 to 13.3.99. (in target 'nanopb-nanopb_Privacy' from project 'Pods')
/Users/fractale/lut_viewer/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.11, but the range of supported deployment target versions is 10.13 to 13.3.99. (in target 'nanopb' from project 'Pods')
/Users/fractale/lut_viewer/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.11, but the range of supported deployment target versions is 10.13 to 13.3.99. (in target 'PromisesObjC-FBLPromises_Privacy' from project 'Pods')
/Users/fractale/lut_viewer/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.11, but the range of supported deployment target versions is 10.13 to 13.3.99. (in target 'PromisesObjC' from project 'Pods')
/Users/fractale/lut_viewer/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.12, but the range of supported deployment target versions is 10.13 to 13.3.99. (in target 'GoogleUtilities-GoogleUtilities_Privacy' from project 'Pods')
/Users/fractale/lut_viewer/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.12, but the range of supported deployment target versions is 10.13 to 13.3.99. (in target 'GoogleUtilities' from project 'Pods')
``` 
``` 
firebase_core: ^2.29.0
firebase_analytics: ^10.10.1
``` 

### Firebase Core version

2.29.0

### Flutter Version

3.19.5

**Comment by russellwheatley** [comment]
This is just  a warning, you can set the project wide build target in your macos/Podfile like this:
```
platform :osx, '10.14'
```

If you really want to remove the warnings, you can also open the project in Xcode, and manually update the build target for each Pod that has the warning:
<img width="982" alt="Screenshot 2024-04-15 at 08 50 13" src="https://github.com/firebase/flutterfire/assets/16018629/3562f22c-73f9-4d8d-a6a7-9eecff257723">

This will remove all the warnings.

**Comment by stephane-archer** [comment]
`platform :osx, '10.14'` is set on top of the `macos/Podfile` as you mentioned.

opening with XCode `macos/Pods/Pods.xcodeproj` and updating the version manually delete the warning but as soon as you do a `flutter clean; flutter build macos` the warning reappears. 
`macos/Pods/Pods.xcodeproj` seem to be generated. Do you have any "permanent" solution you can think of?
