### ISSUE TITLE
io.flutter.plugins.firebase.crashlytics.FlutterError - [firebase_messaging/unknown] java.io.IOException: TOO_MANY_REGISTRATIONS

### ISSUE THREAD

**Issue by cctmobiledev** [firebase/flutterfire#12649]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Description

I have a deployed app on Play Store, and for some users i am getting error **"FirebaseException [firebase_messaging/unknown] java.io.IOException: TOO_MANY_REGISTRATIONS"**

For the first time when i got this error at the time of development, One of my testing device was already registered or being reused many times. And resetting the device worked in that case.

And even i read various reason to generate this error out there that 
          1. (which is impossible I guess) is the same token is linked with multiple senderIds
          2. The device must have many apps (100+ apps) installed and removing some of the applications and restarting the 
              app, has worked for some peoples.

But, In my case user neither have 40+ apps installed by max, nor he installed the app many times (this error generated on the first register of the app) and i don't think same token is linked with multiple senderIds because Firebase takes care of the token to be generated.

            
![Screenshot 2024-04-15 at 7 44 44 PM](https://github.com/firebase/flutterfire/assets/166811659/52f228b0-6c27-45e0-b4f3-120b5272fa28)

How to solve this?? 
Is it anything to do with the code side or version of the dependencies ??
Or It's from the Firebase configuration thing or they are gonna look into this because i dont find any solution of this all over ?

I am giving down my code and flutter doctor.

**Flutter Doctor** 
[✓] Flutter (Channel stable, 3.16.4, on macOS 14.4.1 23E224 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.88.0)
[✓] Connected device (3 available)
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network
      as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!

**Code of Implementation** 

` Future<String> getDeviceToken() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    String? token = prefs.getString('fcmtoken');

    if (token == null || token == '') {
      //firebase shares token based on token not on its userID
      log('token generated');

      String? fcmtoken;
      try {
        fcmtoken = await messaging.getToken();
      } on Exception catch (e) {
        log(e.toString());
      }
      //gives token based on device id
      await prefs.setString('fcmtoken', fcmtoken!);
      fcmToken = fcmtoken;
      return fcmToken;
    } else {
      log('token used from storage');
      log(token);
      fcmToken = token;
      return fcmToken;
    }
  }`
  

  

### Reproducing the issue

I don't know how the error is generated but i guess one of the reason can be
Using just a device with 100+ apps will generate you the issue as per the given solutions by some people. 

For me this is not how it produced i know, because i have 40+ apps only by max, and this error generated on the first install and register. (And it is only happening to very less device out of all the users out there).

### Firebase Core version

2.27.0

### Flutter Version

3.16.4

### Flutter dependencies

  **Firebase Versions :**
  firebase_core: ^2.27.0
  firebase_messaging: ^14.6.6

**Comment by russellwheatley** [comment]
Hi @cctmobiledev - This isn't something we have control over at FlutterFire. [Here is a response](https://github.com/firebase/firebase-android-sdk/issues/5253#issuecomment-1685872180) taken from the firebase-android-sdk for you.

Quote:

> 1. When a client has a multitude of apps registered with FCM, this would trigger the TOO_MANY_REGISTRATIONS error. The problem here is, the only mitigation is for the user to delete some of the other client apps from the device to make room for the new one.
> 2. Otherwise, the device is likely "cloned" from another one, so that multiple device have the same identifiers. In this case, the best thing is factory-reset.
>
> Unfortunately, there's nothing we can do on the SDK side since we don't have any visibility on the backend. It'll be best for you to reach out to our [Firebase support](https://firebase.google.com/support/troubleshooter/contact) for better assistance. You'll be able to share your project details and configuration which will allow them to support you better. Thanks!

It is best for you to reach out to Firebase support if the above isn't possible. Thanks.

**Comment by cctmobiledev** [comment]
@russellwheatley but as i mentioned above, i have a real device with rarely 40 apps installed, and its not cloned i know.
Still its giving error on the first install and register. Also its happening to only some devices rarely.
