### ISSUE TITLE
🐛 [firebase-database] Apply sort/compare onChildChanged.

### ISSUE THREAD

**Issue by aymaalo** [firebase/flutterfire#12657]
##  Apply sort/compare onChildChanged.

When I update my item in firebase real-time database, I would like my FirebaseAnimatedList() widget to apply the sort.
_Example: I add a child to my query `something.child($id)`_ 

This can be fixed manually in firebase-database/ui/firebase_sorted_list.dart by adding `_snapshots.sort(comparator);` before `onChildChanged!(index, event.snapshot);` line 114.

**Comment by russellwheatley** [comment]
@aymaalo - do you mind opening a PR with this change, please? I am interested because it does seem like the list should be sorted particularly when the whole point of `FirebaseSortedList` is to sort it.

**Comment by aymaalo** [comment]
PR created: https://github.com/firebase/flutterfire/pull/12664

This is my first PR contribution on a open-source project, so let me know if there is something I forgot/missed.
