### ISSUE TITLE
Installing BoringSSL-GRPC (0.0.32)

### ISSUE THREAD

**Issue by joshua750** [firebase/flutterfire#12660]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Cloud Functions

### Which platforms are affected?

iOS

### Description

After installing latest version  cloud_firestore: ^4.16.1 we are getting this issue below on ios

### Reproducing the issue

joshua@joshuas-MacBook-Pro ios % pod install
Analyzing dependencies
cloud_firestore: Using Firebase SDK version '10.24.0' defined in 'firebase_core'
firebase_auth: Using Firebase SDK version '10.24.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '10.24.0' defined in 'firebase_core'
Downloading dependencies
Installing BoringSSL-GRPC (0.0.32)

[!] Error installing BoringSSL-GRPC
[!] /usr/bin/git clone https://github.com/google/boringssl.git /var/folders/91/hm2yhm515qqg8wm5zzsz4dnm0000gn/T/d20240417-6098-2yenxh --template=

Cloning into '/var/folders/91/hm2yhm515qqg8wm5zzsz4dnm0000gn/T/d20240417-6098-2yenxh'...
error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
error: 3939 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

### Firebase Core version

2.29.0

### Flutter Version

3.19.2

### Relevant Log Output

```shell
joshua@joshuas-MacBook-Pro untitled4 % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.2, on macOS 12.6.3 21G419 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.80.0)
[✓] VS Code (version 1.80.0)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
joshua@joshuas-MacBook-Pro untitled4 %
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

### Additional context and comments

<img width="1440" alt="Screenshot 2024-04-17 at 11 06 25 AM" src="https://github.com/firebase/flutterfire/assets/9497422/42cd8158-f2c1-47da-bacb-8a0b75a53f59">

**Comment by russellwheatley** [comment]
@joshua750 - Try cleaning out your project:

```
flutter clean
cd ios &&  rm -rf Pods && rm Podfile.lock
flutter run
```

If this fails, could you paste your Podfile? BoringSSL is now OpenSSL so this seems odd. Maybe you have it as a dependency in your Podfile

**Comment by joshua750** [comment]
i tried everything nothing happen.the issue in ios  it was working fine few day ago now suddenly i am getting this issue i don't what  change comes in cloud firestore here is my pod file

# Uncomment this line to define a global platform for your project
# platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end

**Comment by russellwheatley** [comment]
@joshua750 - could you create a small reproducible reproduction in a github repository for me to check? Thanks

**Comment by joshua750** [comment]
please tell me how   reproducible reproduction in a github repository i am beginner

**Comment by russellwheatley** [comment]
Read this: https://stackoverflow.com/help/minimal-reproducible-example

Following the above, create a repository on github to share the code reproduction of the issue with me.
