### ISSUE TITLE
[firebase_storage]: the latest version of plugin does not work with the latest firebase_remote_config plugin on IOS

### ISSUE THREAD

**Issue by as-stefit** [firebase/flutterfire#12677]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Description

firebase_storage cannot be used if min ios version is greater than 10.0, while the latest firebase_remote_config requires min ios version 11.0. I know that workaround is to downgrade firebase_remote_config (and some other plugins as well...), but it would be nice to be able to use latest versions, benefit from security fixes and all features. What's more, creating new flutter project, min ios version is set to 12.0 by default. It's one company, please communicate guys :)

### Reproducing the issue

Create new flutter project with firebase configured, add 2 plugins to pubspec.yaml : firebase_storage, firebase_remote_config. 

### Firebase Core version

^2.4.0

### Flutter Version

3.19.3

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by russellwheatley** [comment]
Hi @as-stefit - I'm not sure I follow. We have both remote config and storage in our test app and the app has a deployment target of 12. See here: https://github.com/firebase/flutterfire/blob/master/tests/ios/Podfile#L2

[Storage already has a deployment target of 11](https://github.com/firebase/flutterfire/blob/master/packages/firebase_storage/firebase_storage/ios/firebase_storage.podspec#L31) in its podspec so I'm not sure what you mean when you say storage cannot be used on iOS > 10.
