### ISSUE TITLE
Redirection to Captcha Verification on iOS while doing phone auth

### ISSUE THREAD

**Issue by Rohit-RA-2020** [firebase/flutterfire#12695]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Auth

### Which platforms are affected?

Android, iOS

### Description

I'm using Firebase Phone Auth in my Flutter app but every time a user enters his phone number for OTP verification it takes to Captcha verification even on release mode. I have set up all the SHA keys and APNs (Because I'm getting notifications), but that does not remove and this behavior impacts the user experience. 

Kindly guide me through the steps to remove this behavior.

## Added a screen recording to understand the issue.

https://github.com/firebase/flutterfire/assets/53489549/d6db5b9c-5dfb-4634-85d7-dd5f3b3dffc1

### Firebase Core version

2.24.2

### Flutter Version

3.10.6

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by russellwheatley** [comment]
Hey @Rohit-RA-2020 - See documentation here: https://firebase.google.com/docs/auth/ios/phone-auth?_gl=1*18z1wu6*_up*MQ..*_ga*MTU5MTcwNDU5Ny4xNzE0MDMzOTgz*_ga_CW55HF8NVT*MTcxNDAzMzk4Mi4xLjAuMTcxNDAzMzk4Mi4wLjAuMA..#enable-app-verification

Quote:

> reCAPTCHA verification: In the event that sending or receiving a silent push notification is not possible, such as when the user has disabled background refresh for your app, or when testing your app on an iOS simulator, Firebase Authentication uses reCAPTCHA verification to complete the phone sign-in flow. The reCAPTCHA challenge can often be completed without the user having to solve anything.

recaptcha fails in the above scenarios.

To enable silent notifications to minimise recaptcha verification, [follow this documentation](https://firebase.google.com/docs/auth/ios/phone-auth?_gl=1*18z1wu6*_up*MQ..*_ga*MTU5MTcwNDU5Ny4xNzE0MDMzOTgz*_ga_CW55HF8NVT*MTcxNDAzMzk4Mi4xLjAuMTcxNDAzMzk4Mi4wLjAuMA..#start-receiving-silent-notifications).
