### ISSUE TITLE
[firebase_core]: Error Encountered After Upgrading Firebase Core to v2.30.1: Invalid Conditional Import in _flutterfire_internals Package

### ISSUE THREAD

**Issue by isaacadariku** [firebase/flutterfire#12708]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Core

### Description

After upgrading Firebase Core from version `2.27.0` to version `2.30.1`, running the build runner resulted in the following error in the log output.

The error originates from the `_flutterfire_internals` package `v1.3.32`. Downgrading the package to `v1.3.31` by overriding it, resolved the error. It's noted that the error was addressed in a merged pull request: PR #12698, which was released in version `1.3.32`.

## Expected Behavior
The build runner should execute without errors.

## Current Behavior
The build runner fails with the reported error.

### Reproducing the issue

Upgrade Firebase Core to version `2.30.1`.
Using the latest `build_runner: ^2.4.9` 
Run the build runner `dart run build_runner build --delete-conflicting-outputs`

### Firebase Core version

2.30.1

### Flutter Version

3.19.6

### Relevant Log Output

```shell
[SEVERE] build_modules:module_library on package:_flutterfire_internals/_flutterfire_internals.dart (cached):

Invalid argument(s): Unsupported conditional import of `dart:js_interop` found in _flutterfire_internals|lib/_flutterfire_internals.dart:

import 'src/interop_shimmer.dart' if (dart.library.js_interop) 'dart:js_interop' as js_interop;

This environment does not support direct conditional imports of `dart:` libraries. Instead you must create a separate library which unconditionally imports (or exports) the `dart:` library that you want to use, and conditionally import (or export) that library.
[SEVERE] Failed after 1m 28s
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by Lyokone** [comment]
Thanks for the report I'm looking into it, have you tried to exclude this particular file in your build.yaml file?

**Comment by Lyokone** [comment]
![Screenshot 2024-04-26 at 10 18 12](https://github.com/firebase/flutterfire/assets/3680002/75d142fe-f845-4d6c-8d31-6fd741377967)

I cannot reproduce the issue, could you give a complete sample?

**Comment by alex-dokienko** [comment]
hello @Lyokone , 

my comment not related to mentioned issue, but if I can please ask to do another version release to include 10.11.1 firebase js library https://firebase.google.com/support/release-notes/js
to resolve following issue
https://github.com/firebase/firebase-js-sdk/pull/8145
which is long running annoying problem, please help 🙏

**Comment by rokk4** [comment]
Same error here:
`Deprecated. Use `dart run` instead.
[INFO] Generating build script completed, took 188ms
[INFO] Setting up file watchers completed, took 4ms
[INFO] Waiting for all file watchers to be ready completed, took 676ms
[INFO] Reading cached asset graph completed, took 876ms
[INFO] Checking for updates since last build completed, took 1.1s
[INFO] Running build completed, took 247ms
[INFO] Caching finalized dependency graph completed, took 898ms
[SEVERE] build_modules:module_library on package:_flutterfire_internals/_flutterfire_internals.dart (cached):

Invalid argument(s): Unsupported conditional import of `dart:js_interop` found in _flutterfire_internals|lib/_flutterfire_internals.dart:

import 'src/interop_shimmer.dart' if (dart.library.js_interop) 'dart:js_interop' as js_interop;

This environment does not support direct conditional imports of `dart:` libraries. Instead you must create a separate library which unconditionally imports (or exports) the `dart:` library that you want to use, and conditionally import (or export) that library.
[SEVERE] Failed after 1.2s`

**Comment by elitree** [comment]
I ran into this too. Updating to the latest versions of all the Flutter Firebase packages solved the error for me.

**Comment by ciprig** [comment]
The issue still happen with firebase_core: 2.31.0

**Comment by isaacadariku** [comment]
@Lyokone Thanks for the response. I have not tried excluding the file in the `build.yaml` file. Can you provide an example of excluding the file in the build.yaml file? As this file is part of the _flutterfire_internals package, I am not sure how to exclude it.

**Comment by elitree** [comment]
Hi @isaacadariku, I was running into this issue as well, and have [a small workaround](https://github.com/firebase/flutterfire/compare/master...elitree:flutterfire:fix-web-build-error) which I might submit as a PR if it works for you too. Can you see if that's the case?

```
dependency_overrides:
  _flutterfire_internals:
    git:
      url: https://github.com/elitree/flutterfire.git
      path: packages/_flutterfire_internals
      ref: fix-web-build-error
```

Hi @Lyokone, I'm still not 100% sure how this is happening in my build.yaml, but I believe it has to do with [some reference `build_web_compilers` code from the `drift` project for using web workers](https://github.com/simolus3/drift/blob/develop/examples/web_worker_example/build.yaml). It seems that the dart2js compilation from that reference code doesn't play nicely with the direct `dart:js_interop` import added in [#12698](https://github.com/firebase/flutterfire/pull/12698/files#diff-21c0cc53e676cc44f50879020b0739a93598eeace6972230c3cc7fb0f2a12b9dR19). Based on [this other similar issue](https://github.com/dint-dev/universal_html/issues/48), I tried using an indirect import, and that fixed my build error. 

I apologize that I'm still not sure how to reproduce the original example, but my guess based on the above is it would involve adding a builder using the `build_web_compilers` package and dart2js. Thanks

**Comment by elitree** [comment]
Quick note that https://github.com/firebase/flutterfire/pull/12925 is submitted to fix this issue. Thanks…

**Comment by elitree** [comment]
Can we leave this open until 
[#12925] is merged to fix the issue?

**Comment by isaacadariku** [comment]
A fix from @elitree is almost ready to be merged to fix this. Hey, @google-oss-bot, please re-open the issue 😄

**Comment by TarekkMA** [comment]
The PR is now merged
