### ISSUE TITLE
storage: file storage with dynamic directory  not visible in gcsfuse

### ISSUE THREAD

**Issue by appliedrd** [firebase/flutterfire#12718]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Storage

### Which platforms are affected?

macOS, Windows

### Description

This code saves a file to firebase storage.
- the file  can be seen and downloaded from google cloud storage bucket
- the file  can be seen and downloaded from Firebase storage
- the file is not visible in a gcsfuse mounted bucket in a  debian 12 compute engine

### Reproducing the issue

this successfully uploaded file is not visible in a  gcsfuse mounted bucket on windows nor macOS.

 var uid = auth.currentUser?.uid;
Reference ref = FirebaseStorage.instance
        .ref()
        .child('base')
        .child(uid)
       .child('/$fileName');

    try {
      await ref.putFile(file);
    } on FirebaseException catch (e) {
      print(e);
      return false;
    }
--------------------------------------------------

my workaround is to use a static directory and  name the file with the uid
String fName = "$uid-$filename.csv";

    Reference ref = FirebaseStorage.instance
        .ref()
        .child('base')
        .child('/$fName');

### Firebase Core version

2.29.0

### Flutter Version

3.19.5

### Relevant Log Output

```shell
flutter: F:\/sessions\2023-11-1V002\analytics-2023-11-01T000014.csv
flutter: analytics-2023-11-01T000014.csv
[ERROR:flutter/shell/common/shell.cc(1038)] The 'plugins.flutter.io/firebase_storage/taskEvent/9739f162-2314-4ecb-bac0-64b9d8fe5426' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.
flutter: upload success!
```

### Flutter dependencies

Dart SDK 3.3.3
Flutter SDK 3.19.5
docking_station_pc_app 1.0.0+1

dependencies:
- cloud_firestore 4.16.1 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- csv 6.0.0
- cupertino_icons 1.0.6
- device_info_plus 10.1.0 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta web win32 win32_registry]
- fast_csv 0.2.11
- file_picker 8.0.0+1 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path win32 cross_file]
- firebase_auth 4.19.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.29.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_storage 11.7.1 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- fl_chart 0.67.0 [equatable flutter]
- flex_color_scheme 7.3.1 [flex_seed_scheme flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_form_builder 9.2.1 [flutter intl]
- flutter_launcher_icons 0.13.1 [args checked_yaml cli_util image json_annotation path yaml]
- flutter_local_notifications 17.0.0 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutterfire_cli 0.3.0-dev.21 [ansi_styles args ci cli_util deep_pick file http interact meta path platform pub_updater pubspec xml yaml]
- fluttertoast 8.2.4 [flutter flutter_web_plugins]
- form_builder_validators 9.1.0 [flutter flutter_localizations intl]
- image_picker 1.0.8 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- intl 0.18.1 [clock meta path]
- path_provider 2.1.3 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- provider 6.1.2 [collection flutter nested]
- settings_ui 2.0.2 [flutter]
- shared_preferences 2.2.2 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- url_launcher 6.2.5 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- youtube_player_flutter 8.1.2 [flutter flutter_inappwebview]

dev dependencies:
- flutter_launcher_icons 0.13.1 [args checked_yaml cli_util image json_annotation path yaml]
- flutter_lints 3.0.2 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel strin
g_scanner term_glyph vm_service]

transitive dependencies:
- _flutterfire_internals 1.3.29 [collection firebase_core firebase_core_platform_interface flutter meta]
- ansi_styles 0.3.2+1
- archive 3.4.10 [crypto path pointycastle]
- args 2.4.2
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- ci 0.1.0
- cli_util 0.4.1 [meta path]
- clock 1.1.1
- cloud_firestore_platform_interface 6.1.13 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.11.1 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins]
- collection 1.18.0
- convert 3.1.1 [typed_data]
- cross_file 0.3.4+1 [meta web]
- crypto 3.0.3 [typed_data]
- dart_console 1.2.0 [ffi win32 intl characters]
- dbus 0.7.10 [args ffi meta xml]
- deep_pick 1.0.0
- device_info_plus_platform_interface 7.0.0 [flutter meta plugin_platform_interface]
- equatable 2.0.5 [collection meta]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.2
- file 6.1.4 [meta path]
- file_selector_linux 0.9.2+1 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.3+3 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.2 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.3+1 [cross_file file_selector_platform_interface flutter]
- firebase_auth_platform_interface 7.2.2 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.11.1 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser meta web]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.15.0 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_storage_platform_interface 5.1.16 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.9.1 [_flutterfire_internals async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http meta web]
- flex_seed_scheme 1.5.0 [collection flutter meta]
- flutter_inappwebview 5.8.0 [flutter]
- flutter_local_notifications_linux 4.0.0+1 [dbus ffi flutter flutter_local_notifications_platform_interface path xdg_directories]
- flutter_local_notifications_platform_interface 7.0.0+1 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 2.0.17 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- http 0.13.6 [async http_parser meta]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image 4.1.7 [archive meta xml]
- image_picker_android 0.8.9+5 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 3.0.3 [flutter flutter_web_plugins image_picker_platform_interface mime web]
- image_picker_ios 0.8.9+2 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1+1 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1+1 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.10.0 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1+1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- interact 2.2.0 [dart_console meta tint]
- js 0.7.1
- json_annotation 4.8.1 [meta]
- leak_tracker 10.0.0 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 2.0.1 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 2.0.1 [leak_tracker matcher meta]
- lints 3.0.0
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.8.0 [collection]
- meta 1.11.0
- mime 1.0.5
- nested 1.0.0 [flutter]
- path 1.9.0
- path_provider_android 2.2.3 [flutter path_provider_platform_interface]
- path_provider_foundation 2.3.2 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.2.1 [ffi flutter path path_provider_platform_interface win32]
- petitparser 6.0.2 [meta]
- typed_data 1.3.2 [collection]
- uri 1.0.0 [matcher quiver]
- url_launcher_android 6.3.0 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.2.5 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.1.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.1.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.3.0 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.1 [flutter url_launcher_platform_interface]
- vector_math 2.1.4
- vm_service 13.0.0
- web 0.5.1
- win32 5.4.0 [ffi]
- win32_registry 1.1.2 [ffi win32]
- xdg_directories 1.0.4 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]

### Additional context and comments

Debian GNU/Linux 12 (bookworm) on a Google Compute Engine
gcsfuse version 2.0.1

The app uploads selected files to firebase storage.
currently compiled and tested on Windows 10 & mac OS (latest).
will eventually also run on iOS & Android.

on windows, I am using flutterfire beta for windows
https://github.com/invertase/flutterfire_cli

on macOS, I am using the stadnard flutterfire

**Comment by TarekkMA** [comment]
Hello @appliedrd,

Thank you for reporting this bug. I believe the issue might not be directly related to FlutterFire, as FlutterFire primarily serves as a wrapper around the Firebase SDKs for iOS/MacOS ([firebase-ios-sdk](https://github.com/firebase/firebase-ios-sdk)) and Windows ([firebase-cpp-sdk](https://github.com/firebase/firebase-cpp-sdk)). You might want to report this bug directly to those repositories. Alternatively, if it's relevant, you can also file the bug with [gcsfuse](https://github.com/GoogleCloudPlatform/gcsfuse).

Additionally, could you please provide more details about what you were trying to achieve and the steps you followed to reproduce the issue? This information will help us better understand the context and it can help us resolve the issue
