### ISSUE TITLE
[BUG]: Error: Unable to get Xcode project information ... Unable to read project 'Runner.xcodeproj'. After Running Flutterfire Configure on MACOS

### ISSUE THREAD

**Issue by biondiBagasta** [firebase/flutterfire#12740]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Core, Other

### Which platforms are affected?

iOS

### Description

When i running flutterfire configure, my IOS project suddenly can't running

### Reproducing the issue

[https://drive.google.com/file/d/1eNTSsuH3hLvRXAigZFhePUfj2rf7Hugr/view?usp=sharing](url)

### Firebase Core version

^2.19.0

### Flutter Version

3.19.5

### Relevant Log Output

```shell
Launching lib/main.dart on iPhone 15 in debug mode...
Error: Unable to get Xcode project information:
 2024-05-03 10:05:10.061 xcodebuild[36844:232542] Writing error result bundle to /var/folders/7_/cp_zpfgn6xs2th9fnss_s9w00000gn/T/ResultBundle_2024-03-05_10-05-0010.xcresult
xcodebuild: error: Unable to read project 'Runner.xcodeproj'.
	Reason: Project /Users/adamulti/Documents/Kerja/ADAMULTI CLONE PROJECT/MPN IOS/mpn_clone_ios/ios/Runner.xcodeproj cannot be opened because it is missing its project.pbxproj file.
```

**Comment by TarekkMA** [comment]
Hello @biondiBagasta, thank you for reporting this issue. Can you please open this issue [here](https://github.com/invertase/flutterfire_cli), since it might be related to the CLI?
