### ISSUE TITLE
[firebase_analytics]: Crashlytics doesn't track screen view breadcrumbs

### ISSUE THREAD

**Issue by TatsuUkraine** [firebase/flutterfire#12760]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Analytics, Crashlytics

### Which platforms are affected?

Android, iOS (not sure about iOS since some reports containing breadcrumbs)

### Description

It seems `logScreenView` method doesn't track navigation changes. In the crashlytics reports breadcrumbs tab is empty

### Reproducing the issue

```dart
FirebaseAnalytics.instance.logScreenView(screenName: 'some_screen_name');
FirebaseCrashlytics.instance.recordError('Some message', null);
```

### Firebase Core version

2.29.0

### Flutter Version

3.19.6

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

### Additional context and comments

It seems Dart plugin uses following code to log screen views
```dart
_delegate.logEvent(
      name: 'screen_view',
      parameters: filterOutNulls(<String, Object?>{
        _SCREEN_CLASS: screenClass,
        _SCREEN_NAME: screenName,
        if (parameters != null) ...parameters,
      }),
      callOptions: callOptions,
    );
```
Where _SCREEN_CLASS is `screen_class` and _SCREEN_NAME is `screen_name`

While according to the documentation it should be
```dart
await FirebaseAnalytics.instance.logEvent(
  name: 'screen_view',
  parameters: {
    'firebase_screen': screenName,
    'firebase_screen_class': screenClass,
  },
);
```
Firebase doc - https://firebase.google.com/docs/analytics/screenviews?authuser=0&hl=en#manually_track_screens
GA4 doc - https://support.google.com/analytics/answer/9234069#screen_view

Which kind of strange, since native SDK docs say that the current code in `logScreenView` is accurate 🤔

**Comment by TatsuUkraine** [comment]
@TarekkMA it seems it's not, I'm getting following message
`E/FA      (31087): Name starts with reserved prefix. Type, name: event param, firebase_screen`

**Comment by TarekkMA** [comment]
I guess `firebase_screen` and `firebase_screen_class` is for web only. Since the value of the `AnalyticsParameterScreenName` in swift and  `FirebaseAnalytics.Param.SCREEN_NAME` for java/kotlin doesn't have the firebase prefix.

**Comment by TatsuUkraine** [comment]
maybe, but it's quite confusing, since GA4 says it's for `app`, and Firebase docs having exact this codesnipet for Flutter

**Comment by TatsuUkraine** [comment]
![Снимок экрана 2024-05-10 в 11 50 29](https://github.com/firebase/flutterfire/assets/621542/7b19c0b3-8722-4eb0-8e2f-299ac175e94a)

**Comment by TatsuUkraine** [comment]
ok, so I think it seems the issue is with `com.google.gms.google-services`. 
GA doesn't work when app uses google-services v4.4.x, I'm see message like `Missing google_app_id.` in console.

Downgrading it to 4.3.x seems fixes GA reports as well as breadcrumbs in Crashlytics

P.S still trying to confirm that breadcrumbs working on iOS though

**Comment by TatsuUkraine** [comment]
so on iOS this code send screen view events, but doesn't record screen name
```dart
await FirebaseAnalytics.instance.logEvent(
  name: 'screen_view',
  parameters: {
    'firebase_screen': screenName,
    'firebase_screen_class': screenClass,
  },
);
```

but `logScreenView` seems works fine in my debug code 🤔 need more time to track our prod logs to understand if works stable enough, since for now I see that not all of our error events having breadcrumbs from some reason

**Comment by TarekkMA** [comment]
Thank you for the update

**Comment by TatsuUkraine** [comment]
small update. After downgrading google-services version android breadcrumbs it seems reported. Strange thing though that for iOS not every report contains breadcrumbs. The majority of them do, but not all of them. And for now I don't know the reason why

**Comment by TarekkMA** [comment]
@TatsuUkraine Hello, can you try to update Flutter and FlutterFire, then try again to see if the issue still happens?

**Comment by TatsuUkraine** [comment]
@TarekkMA hello, we did the release 2 weeks ago with most up to date versions at that time, and I still see that some reports from iOS devices don't have Breadscrumbs, not a lot, and I still haven't figure the reason

**Comment by TarekkMA** [comment]
@TatsuUkraine 
I don't think this issue is related to the Flutter side of FlutterFire. It might be related to the native iOS SDK (https://github.com/firebase/firebase-ios-sdk) or the server side. Could you try contacting Firebase support regarding this issue?
