### ISSUE TITLE
[ALL] Consider adding `topics` to `pubspec.yaml` for better discoverability

### ISSUE THREAD

**Issue by jonasfj** [firebase/flutterfire#12777]
Topics helps users on pub.dev discover packages, and related packages.

You can see a list of [topics here](https://pub.dev/topics).
You can also make your own topics.

Topics are added to `pubspec.yaml` as follows:

```yaml
topics:
 - my-topic
 - some-other-topic
```

See also: https://dart.dev/tools/pub/pubspec#topics

**Comment by russellwheatley** [comment]
Hi @jonasfj - thank you for bringing this to our awareness, I'll report back to the team and see what topics we'd like to add to each package 👍
