### ISSUE TITLE
[flutterfire_cli]: v1.0.0 update command fails on Windows

### ISSUE THREAD

**Issue by rayliverified** [firebase/flutterfire#12776]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Other

### Which platforms are affected?

Windows

### Description

The following command crashes on Windows.

```
flutterfire update
```

<details><summary>Crash</summary>
<p>
flutterfire update
Cleaning up current workspace ...
Unhandled exception:
ProcessException: The system cannot find the file specified.

  Command: flutter clean
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:402:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      _runNonInteractiveProcess (dart:io-patch/process_patch.dart:579:18)
#3      Process.run (dart:io-patch/process_patch.dart:49:12)
#4      UpdateCommand.run (package:flutterfire_cli/src/commands/update.dart:79:19)
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:27)
#6      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:122:25)
#7      new Future.sync (dart:async/future.dart:306:31)
#8      CommandRunner.run (package:args/command_runner.dart:122:14)
#9      main (file:///C:/Users/searc/AppData/Local/Pub/Cache/hosted/pub.dev/flutterfire_cli-1.0.0/bin/flutterfire.dart:63:48)
<asynchronous suspension>
Cleaning up current workspace ...
Unhandled exception:
ProcessException: The system cannot find the file specified.

  Command: flutter clean
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:402:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      _runNonInteractiveProcess (dart:io-patch/process_patch.dart:579:18)
#3      Process.run (dart:io-patch/process_patch.dart:49:12)
#4      UpdateCommand.run (package:flutterfire_cli/src/commands/update.dart:79:19)
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:27)
#6      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:122:25)
#7      new Future.sync (dart:async/future.dart:306:31)
#8      CommandRunner.run (package:args/command_runner.dart:122:14)
#9      main (file:///C:/Users/searc/AppData/Local/Pub/Cache/hosted/pub.dev/flutterfire_cli-1.0.0/bin/flutterfire.dart:63:48)
<asynchronous suspension>
</p>
</details> 

### Reproducing the issue

1. Update to flutterfire v1.0.0
2. Run `flutterfire update` on Windows
3. See the crash

### Firebase Core version

N/A

### Flutter Version

3.19.0

### Flutter dependencies

N/A

**Comment by russellwheatley** [comment]
Please file an issue on the FlutterFire CLI repository: https://github.com/invertase/flutterfire_cli
