### ISSUE TITLE
[FIRESTORE]: includeMetadataChanges does not make the stream emit second non cache event

### ISSUE THREAD

**Issue by jtdLab** [firebase/flutterfire#12781]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Database

### Description

When listening for data like this (with internet connection):

```dart
doc.snapshots(includeMetadataChanges: true)
```

There is only a snapshot with `metadata.isFromCache` = `true` fired but no second
with `metadata.isFromCache` = `false` as stated in https://firebase.google.com/docs/reference/js/v8/firebase.firestore.SnapshotMetadata

### Reproducing the issue

Listen to a document as described.

### Firebase Core version

2.31.0

### Flutter Version

3.22.0

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by TarekkMA** [comment]
@jtdLab, thank you for reporting this issue. Could you please provide additional details about which platform you have tested on and where you found this bug? This information will help us better understand and address the issue.
