### ISSUE TITLE
[firebase_crashlytics] 此应用有 1 个崩溃问题未处理。请上传 1 个 dSYM 文件以处理崩溃问题。

### ISSUE THREAD

**Issue by giantss** [firebase/flutterfire#12782]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Crashlytics

### Which platforms are affected?

iOS

### Description

expected： ios error reports can now be transmitted to Crashlytics.

actually：
<img width="921" alt="image" src="https://github.com/firebase/flutterfire/assets/13778798/976a3aff-40df-4533-a2f3-c816e024c625">

### Reproducing the issue

[Official document steps](https://firebase.google.com/docs/crashlytics/get-started?platform=flutter)

### Firebase Core version

2.31.0

### Flutter Version

3.19.5

### Relevant Log Output

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.4.1 23E224 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] Connected device (4 available)  
[✓] Network resources
• No issues found!

```

### Additional context and comments

I tried to find [this clue](https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?authuser=1&_gl=1*1kzbdvz*_ga*OTg1NzUwMDY0LjE3MTU1NzY2MjQ.*_ga_CW55HF8NVT*MTcxNTczOTU5NC44LjEuMTcxNTc0MjU0NS41OC4wLjA.&platform=flutter) and found the location of the FlutterFire: "flutterfire upload-crashlytics-symbols" script in xcode. The content inside is as follows:

```

#!/bin/bash
PATH=${PATH}:$FLUTTER_ROOT/bin:$HOME/.pub-cache/bin
flutterfire upload-crashlytics-symbols --upload-symbols-script-path=$PODS_ROOT/FirebaseCrashlytics/upload-symbols --platform=ios --apple-project-path=${SRCROOT} --env-platform-name=${PLATFORM_NAME} --env-configuration=${CONFIGURATION} --env-project-dir=${PROJECT_DIR} --env-built-products-dir=${BUILT_PRODUCTS_DIR} --env-dwarf-dsym-folder-path=${DWARF_DSYM_FOLDER_PATH} --env-dwarf-dsym-file-name=${DWARF_DSYM_FILE_NAME} --env-infoplist-path=${INFOPLIST_PATH} --default-config=default

```

I don't know if there is a problem with the content in this script, because the plug-in is automatically added when I add it.

I also uploaded the dSYM file in the Crashlytics backend.
Using [this method,](https://stackoverflow.com/questions/35159244/xcode-there-are-no-dsyms-available-for-download/39361649#39361649) I obtained the dsym file and uploaded it. After a while, it still had no effect.

I don't know how to solve this problem now. Has anyone else encountered the same problem?

**Comment by russellwheatley** [comment]
Hey @giantss - The uploading symbols script is generated by FlutterFire CLI. You might want to update to the latest FlutterFire CLI version by running first:

```bash
dart pub global activate flutterfire_cli
```

and configuring app again, debug symbols should be uploaded. If the problem persists, please file an issue on that repository: https://github.com/invertase/flutterfire_cli 🙏
