### ISSUE TITLE
[firebase_analytics]: logPurchase crashes when any of the values inside parameters is null

### ISSUE THREAD

**Issue by jorgecoca** [firebase/flutterfire#12790]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Analytics

### Which platforms are affected?

Android, iOS, macOS, Web, Windows

### Description

Firebase Analytics version: 10.10.4

`logPurchase` accepts a `parameters` input with the signature `Map<String, Object?>?`, so a call like this should work:

```dart
firebaseAnalytics.logPurchase(value: 123, parameters: { 'hello': null });
```

However, this code crashes due to an internal call to a method named `_assertParameterTypesAreCorrect`:

```dart
void _assertParameterTypesAreCorrect(Map<String, Object?>? parameters) =>
    parameters?.forEach((key, value) {
      assert(
        value is String || value is num,
        "'string' OR 'number' must be set as the value of the parameter: $key. $value found instead",
      );
    });
```

where the `assert` does not allow `value` to be `null`, creating the crash.

### Reproducing the issue

Call `logPurchase` with `parameters` having a null value.

```
firebaseAnalytics.logPurchase(value: 123, parameters: { 'hello': null });
```

### Firebase Core version

2.31.0

### Flutter Version

3.19.6

### Relevant Log Output

```shell
[log] #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
      #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
      #2      _assertParameterTypesAreCorrect.<anonymous closure> (package:firebase_analytics/src/firebase_analytics.dart:1501:9)
      #3      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
      #4      _assertParameterTypesAreCorrect (package:firebase_analytics/src/firebase_analytics.dart:1499:17)
      #5      FirebaseAnalytics.logPurchase (package:firebase_analytics/src/firebase_analytics.dart:885:5)
      #6      FirebaseAnalyticsRepository.purchase (package:firebase_analytics_repository/src/firebase_analytics_repository.dart:100:28)
```
```


### Flutter dependencies

<!--- Look below for instructions on how to share your Flutter Dependencies. --->

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by russellwheatley** [comment]
@jorgecoca - `null` values are not allowed which is why we have that assertion. We do have a PR for fixing incorrect types (that allow `null` values) but it is a breaking change, and we are waiting until the time when we cut a breaking change release: https://github.com/firebase/flutterfire/pull/12427

**Comment by jorgecoca** [comment]
Understood! I think in this case it makes sense to close the issue and the associated PR, since the compiler will catch those issues in the next release.

Thank you!
