### ISSUE TITLE
[📚] [firebase_messaging_web] How to load on Flutter 3.22?

### ISSUE THREAD

**Issue by stx** [firebase/flutterfire#12798]
https://firebase.google.com/docs/cloud-messaging/flutter/receive#web has this:

```
<html>
<body>
  ...
  <script src="main.dart.js" type="application/javascript"></script>
  <script>
       if ('serviceWorker' in navigator) {
          // Service workers are supported. Use them.
          window.addEventListener('load', function () {
            // ADD THIS LINE
            navigator.serviceWorker.register('/firebase-messaging-sw.js');

            // Wait for registration to finish before dropping the <script> tag.
            // Otherwise, the browser will load the script multiple times,
            // potentially different versions.
            var serviceWorkerUrl = 'flutter_service_worker.js?v=' + serviceWorkerVersion;

            //  ...
          });
      }
  </script>
```

But the Flutter 3.22 index.html format is completely different:

```
<script src="flutter_bootstrap.js" async></script>
```

When using existing code in the example and other repos, these deprecations are thrown:

```
Warning: In index.html:30: Local variable for "serviceWorkerVersion" is deprecated. Use "{{flutter_service_worker_version}}" template token instead.
Warning: In index.html:243: "FlutterLoader.loadEntrypoint" is deprecated. Use "FlutterLoader.load" instead.
```

Can we get a complete example of loading this with Flutter 3.22?

**Comment by TarekkMA** [comment]
@stx Thank you for reporting this issue and pointing that out. We will work on updating the current documentation to match the new Flutter version.

**Comment by electriko3** [comment]
Hello.
Can someone share the code of how the `navigator.serviceWorker.register('firebase-messaging-sw.js'` should now be registered in `<script src="flutter_bootstrap.js" async></script>` ?

**Comment by electriko3** [comment]
@stx  hello. maybe u can share an example if u found a solution?

**Comment by Lyokone** [comment]
This pull request should guide you https://github.com/firebase/flutterfire/pull/12836
