### ISSUE TITLE
[firebase_analytics]: Firebase make bundle format ambiguous for MacOS Gatekeeper

### ISSUE THREAD

**Issue by stephane-archer** [firebase/flutterfire#12826]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Analytics

### Which platforms are affected?

macOS

### Description

When I build my app with Firebase, MacOS Gatekeeper doesn't accept my app.
```
spctl --assess --type execute —verbose MyApp.app
MyApp.app/: rejected (bundle format is ambiguous (could be app or framework))
source=matched cdhash
```
My App is signed and notarized.

If I remove Firebase from my app, my app run perfectly and MacOS Gatekeeper has no issue.

There is something that is included by Firebase in the .app that makes the bundle format ambiguous.

Here is what I use:
```
firebase_core: ^2.19.0
firebase_analytics: ^10.6.1
```

### Reproducing the issue

up

### Firebase Core version

2.19.0

### Flutter Version

3.19.5

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by TarekkMA** [comment]
Hi @stephane-archer,

Thank you for reporting this issue.

Could you please specify which plugin is causing the problem? Try removing the analytics plugin and see if the issue still reproduces. If we can identify what specifically is causing the issue.

**Comment by stephane-archer** [comment]
the problem was caused by `zip` that wasn't preserving symlink. Sorry, this wasn't linked to Firabase
