### ISSUE TITLE
[firebase_messaging]: Embedded binary is not signed with the same certificate as the parent app

### ISSUE THREAD

**Issue by febryardiansyah** [firebase/flutterfire#12827]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which platforms are affected?

iOS

### Description

I just updated my macOS and Flutter to the latest version. When i tried to build the app to IPA, i suddenly got this error
`Embedded binary is not signed with the same certificate as the parent app. Verify the embedded binary target's code sign settings match the parent app's.`

my app uses `ImageNotification` extension to display an image in notification. when i deleted it and rebuild it works as expected. but i want to use that extension. here are my bundle identifier each target
![Screenshot 2024-05-24 at 15 53 14](https://github.com/firebase/flutterfire/assets/33514300/7718ceb3-1a24-4703-a5ed-1954c0f3859b)
![Screenshot 2024-05-24 at 15 53 25](https://github.com/firebase/flutterfire/assets/33514300/a1ce9a37-08b6-4a34-a213-945a135b148a)

### Reproducing the issue

[✓] Flutter (Channel stable, 3.19.6, on macOS 14.5 23F79 darwin-arm64, locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Community Edition (version 2022.1.4)
[✓] VS Code (version 1.89.1)
[✓] Connected device (2 available)
[✓] Network resources

### Firebase Core version

2.1.0

### Flutter Version

3.19.6

### Relevant Log Output

```shell
Failed to build iOS app
Error (Xcode): Embedded binary is not signed with the same certificate as the parent app. Verify the embedded binary target's code sign settings match the parent app's.


Encountered error while archiving for device.
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by TarekkMA** [comment]
@febryardiansyah Thank you for reporting this issue.

Could you please downgrade your Flutter version and test again? Additionally, I recommend running `flutter clean` and `rm -rf Pods && rm Podfile.lock` before testing it again.

**Comment by febryardiansyah** [comment]
@TarekkMA any idea what specific flutter version should i downgrade to?

**Comment by TarekkMA** [comment]
Maybe [3.19.6]

**Comment by febryardiansyah** [comment]
> Maybe [3.19.6]



> Maybe [3.19.6]

currently i use that version

**Comment by TarekkMA** [comment]
So could you please find out which version it was working on before it stopped?

**Comment by febryardiansyah** [comment]
> So could you please find out which version it was working on before it stopped?

Hi, sorry for the late response. it used to work on 3.7.3 version of flutter

**Comment by febryardiansyah** [comment]
@TarekkMA can we open this issue again?

**Comment by TarekkMA** [comment]
@febryardiansyah Hello, if this issue is still happening, please open a new issue with the updated details.
