### ISSUE TITLE
[firebase_messaging]: AuthorizationStatus.notDetermined is never returned on Android

### ISSUE THREAD

**Issue by Wes1324** [firebase/flutterfire#12839]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Messaging

### Which platforms are affected?

Android

### Description

The [permissions section of the FCM docs](https://firebase.google.com/docs/cloud-messaging/flutter/receive#permissions) state that 

> The authorizationStatus property of the NotificationSettings object returned from the request can be used to determine the user's overall decision

and that an `AuthorizationStatus` of `notDetermined` means

> The user has not yet chosen whether to grant permission

The DartDoc above the `notDetermined` enum value also states:

> The app user has not yet chosen whether to allow the application to create notifications. Usually this status is returned prior to the first call of [requestPermission]

However, when I start an Android emulator with Android API 34 and run my app, the call to `getNotificationSettings` instantly returns `AuthorizationStatus.denied`, before notification permissions are ever requested from the user.

I've taken a look at the source code and I cannot see how a `notDetermined` value would ever be returned on Android. The only value I can see being returned is a `0` or `1` [here](https://github.com/firebase/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java#L408), however a `-1` value relates to `notDetermined` as can be seen [here](https://github.com/firebase/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/utils.dart#L83).

### Reproducing the issue

- Run any Flutter app with an FCM integration on an Android emulator
- Invoke `final notificationSettings = await FirebaseMessaging.instance.getNotificationSettings();` before ever requesting notification permissions

`notificationSettings.authorizationStatus` will be `AuthorizationStatus.denied`, not `AuthorizationStatus.notDetermined` as expected.

### Firebase Core version

2.9.0

### Flutter Version

3.19.5

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by TarekkMA** [comment]
Hello @Wes1324,

Thank you for bringing this issue to our attention. We will work on a resolution to fix it.

**Comment by russellwheatley** [comment]
Hey @Wes1324 - there is no way to determine if permission has been requested from the user like with iOS. This is a limitation of android and I have created a PR to update the documentation to reflect that. 

Having a look at the pub plugin [permission handler](https://pub.dev/packages/permission_handler) which is a more comprehensive permission handler, it appears to have the same limitation on android (example is for camera but presumably works the same for notifications). From the docs:

```dart
var status = await Permission.camera.status;
if (status.isDenied) {
  // We haven't asked for permission yet or the permission has been denied before, but not permanently.
}
```
