### ISSUE TITLE
[firebase_analytics]: iOS 13 required?

### ISSUE THREAD

**Issue by JCKodel** [firebase/flutterfire#12917]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Analytics

### Which platforms are affected?

iOS

### Description

After last update, firebase_analytics required iOS 13:

The pod "Firebase/Analytics" required by the plugin "firebase_analytics" requires a higher minimum iOS deployment version than the plugin's reported minimum version.

Flutter is compatible with iOS 12. It makes no sense whatsoever to require a higher iOS version than Flutter itself.

We would lose more than 15 thousand users by forcing an iOS 13 update right now!

### Reproducing the issue

Just update the project

### Firebase Core version

3.0.0

### Flutter Version

3.22.1

**Comment by romatallinn** [comment]
Yea, there are cases when packages may have different target versions from what Flutter can handle by default. Sure, for a simple wrapper packages that don't even have platform-specific implementations, it doesn't make sense to max out these versions. However, things like analytics must evolve at some point together with very deep-native API of OSs.

I would say it's about time. From what I know, Stripe, Mixpanel are also already on 13+.

Yeah, the team is [not very elaborate about the reasoning](https://github.com/firebase/firebase-ios-sdk/issues/11517) behind the bump, but whatever. It's understandable.

I mean, you still have a totally viable option just not to upgrade. Your apps stop working any time soon. And I doubt you have any amazing features in mind that you need right now from the latest releases. So, yeah, a decision for you to make.

**Comment by TarekkMA** [comment]
For Firebase iOS SDK 11 it would require a bump to iOS 13, that's why flutterfire have bumped the iOS version.
