### ISSUE TITLE
[firebase_analytics]: `AnalyticsEventItem.asMap()` to `Map<String, Object>` instead of `Map<String, dynamic>`

### ISSUE THREAD

**Issue by romatallinn** [firebase/flutterfire#12918]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Analytics

### Description

The package provides an interface that defines the required attributes of an analytics item: [`AnalyticsEventItem`](https://github.com/firebase/flutterfire/blob/master/packages/firebase_analytics/firebase_analytics_platform_interface/lib/src/analytics_event_item.dart).

This class contains `asMap()` that converts the object to `Map<String, dynamic>`.

However, the recent Firebase Analytics v11.0.0 release fixes typing of event parameters to `Map<String, Object>?` (#12427).

This works fine in general use-cases, since this object is used as nested parameter in the standard events, like [`logViewItem`](https://github.com/firebase/flutterfire/blob/e946eb9b429da16bea617b68dda32f23d0deb5bc/packages/firebase_analytics/firebase_analytics/lib/src/firebase_analytics.dart#L1120-L1140). However, I see great value in having this `asMap()` casting to `Map<String, Object>` as well. This provides more flexibility on how the interface is used. For example, in my own use-cases, I regularly use it as top-level parameter object. And now it doesn't work unless casted explicitly.

### Reproducing the issue

```
FirebaseAnalytics.instance.logEvent(
  name: "test",
  parameters: AnalyticsEventItem(
    itemName: "...",
    itemId: "...",
    affiliation: "...",
    price: "...",
    currency: "...",
  ).asMap(),
);
```

### Firebase Core version

3.0.0

### Flutter Version

3.22.1

**Comment by TarekkMA** [comment]
Thank you, @romatallinn, for bringing this to our attention. We will review and discuss this enhancement internally.

**Comment by TarekkMA** [comment]
This change is a breaking one and wasn't planned. You can create an extension with a custom `.toMap()` to cast to `Map<String, Object>` for more flexibility.
