### ISSUE TITLE
[firebase_messaging]: Remove references to deprecated v1 Android embedding 

### ISSUE THREAD

**Issue by reidbaker** [firebase/flutterfire#12936]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Messaging

### Which platforms are affected?

Android

### Description

To ensure this plugin will work with users running the next stable version of Flutter remove references to the v1 embedding.

The v1 embedding was deprecated around 6 and a half years ago. In Flutter 3.22, the Flutter tool dropped support for building v1 apps entirely. Flutter plans to delete version one of it's Android embedding in the next stable release, per https://medium.com/flutter/whats-new-in-flutter-3-22-fbde6c164fe3 (in the "Removal of v1 Android embedding" section). 

When that deletion happens, any apps using plugins that still have references to the removed classes will fail to build when updating to the next stable version (probably Flutter `3.26`). 

As a part of this deprecation, the Flutter Android team is doing community outreach by filing bugs and submitting some pull requests to update plugins to minimize the impact this removal has on the community. 

#### Some example PRs:
- Flutter team maintained plugins: https://github.com/flutter/packages/pull/6494
- `android_alarm_manager_plus` https://github.com/fluttercommunity/plus_plugins/pull/2864 

#### Consequences:
- This change should have no impact on users of this plugin that are building apps using the v2 embedding (we don't have a percentage to share, but this is the vast majority of users). 
- It will remove support for users that are still using the v1 embedding on version of Flutter older than `3.22`.

If this change doesn't land, this plugin will instead be broken for all apps building on the next stable version of Flutter and beyond.

#### Is there a way to support both v1 and v2 embedding apps in the next stable version of Flutter?
No.

This is the PR where we are removing the deprecated engine classes: https://github.com/flutter/engine/pull/52022

### Reproducing the issue

Build Messaging with a custom engine version targeting https://github.com/flutter/engine/pull/52022 

### Firebase Core version

tip of tree 

### Flutter Version

3.26

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

N/A

```

</details>

**Comment by reidbaker** [comment]
https://github.com/search?q=repo%3Afirebase%2Fflutterfire%20(%22io.flutter.view.FlutterMain%22%20OR%20%22io.flutter.view.FlutterNativeView%22%20OR%20%22io.flutter.view.FlutterView%22%20OR%20%22io.flutter.embedding.engine.plugins.shim%22%20OR%20%22io.flutter.app%22%20OR%20%22PluginRegistry.Registrar%22)&type=code

The only instances in this plugin are dart docs.

**Comment by reidbaker** [comment]
Confirmed compilation against the version of the engine with the classes removed.

**Comment by Lyokone** [comment]
Thanks for checking @reidbaker, if I understand properly, the only thing that we still have to do is remove the references in documentation?

**Comment by reidbaker** [comment]
Correct. I debated not filing an issue at all since it wont cause issues for your customers but figured you might want to know you are referencing classes that will not exist in the future :).

**Comment by Lyokone** [comment]
Thanks for taking the time to check :)
