### ISSUE TITLE
👉FCM V1 👈_firebaseMessagingBackgroundHandler flutter_incoming_call  sound not working and  awesome_notifications  incoming call sound not working ⚠⚠⚠⚠⚠

### ISSUE THREAD

**Issue by Amshaf123** [firebase/flutterfire#12949]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

In-App Messaging, Messaging

### Which platforms are affected?

Android

### Description

_firebaseMessagingBackgroundHandler flutter_incoming_call  sound not working and  awesome_notifications  incoming call sound not working ⚠⚠⚠⚠⚠

### Reproducing the issue

_firebaseMessagingBackgroundHandler flutter_incoming_call  sound not working and  awesome_notifications  incoming call sound not working ⚠⚠⚠⚠⚠

### Firebase Core version

3.1.0

### Flutter Version

3.1.0

### Relevant Log Output

```shell
_firebaseMessagingBackgroundHandler flutter_incoming_call  sound not working and  awesome_notifications  incoming call sound not working ⚠⚠⚠⚠⚠
```

### Flutter dependencies

_firebaseMessagingBackgroundHandler flutter_incoming_call  sound not working and  awesome_notifications  incoming call sound not working ⚠⚠⚠⚠⚠

### Additional context and comments

_firebaseMessagingBackgroundHandler flutter_incoming_call  sound not working and  awesome_notifications  incoming call sound not working ⚠⚠⚠⚠⚠

**Comment by MukhtarAbbas** [comment]
Yes, I am also facing this type of issue with my app.
But in addition to this, I have another issue.
when I click the silent notification or any event button, the app starts launching and there appears again another notification with a ringing tone. then it behaves as I implement it.

**Comment by russellwheatley** [comment]
Sorry this issue is incorrectly filled out, I'm closing out for now. If you do have something relevant to report, please ensure you fill out the issue appropriately and we can take a look. Thanks 🙏
