### ISSUE TITLE
[cloud_firestore]: snapshot.connectionState = ConnectionState.active when macos connect cloud_firestore

### ISSUE THREAD

**Issue by maiducgiang** [firebase/flutterfire#12943]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Database

### Which platforms are affected?

macOS

### Description

I try connect macos to cloud_firestore but " connectionState = ConnectionState.active" allway.
I can't get data in cloud_firestore from macos

### Reproducing the issue

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:puzzle/features/list_product/presentation/screen/home_screen/controller/home_controller.dart';

class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  final HomeController homeController = Get.put(HomeController());
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    homeController.getData();
  }

  final Stream<QuerySnapshot> _usersStream = FirebaseFirestore.instance.collection('set_of_questions').snapshots();

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<QuerySnapshot>(
      stream: _usersStream,
      builder: (BuildContext context, AsyncSnapshot<QuerySnapshot> snapshot) {
        if (snapshot.hasError) {
          return Text('Something went wrong');
        }

        if (snapshot.connectionState == ConnectionState.waiting) {
          return Text("Loading");
        }
        if (snapshot.connectionState == ConnectionState.done) {
          return Text("Done");
        }
        if (snapshot.connectionState == ConnectionState.active) {
          return Text("active");
        }
        return ListView(
          children: snapshot.data!.docs.map((DocumentSnapshot document) {
            Map<String, dynamic> data = document.data()! as Map<String, dynamic>;
            return ListTile(
              title: Text(data.toString()),
              subtitle: Text("data['company']"),
            );
          }).toList(),
        );
      },
    );
  }
}

<img width="554" alt="Ảnh màn hình 2024-06-11 lúc 23 05 09" src="https://github.com/firebase/flutterfire/assets/43919583/e3cb344c-367d-4d8f-bae5-65d7936717c6">

<img width="849" alt="Ảnh màn hình 2024-06-11 lúc 23 04 02" src="https://github.com/firebase/flutterfire/assets/43919583/495bb227-a2a6-4099-b42a-fce9f647d1b1">

### Firebase Core version

3.0.0

### Flutter Version

3.19.4

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by Lyokone** [comment]
Hey @maiducgiang, I'm not sure to fully understand your issue. Does it work for other platforms and just not for macos? Are you able to provide a complete sample? Thanks
