### ISSUE TITLE
🐛 [VectorStore] Dart SDK for Vector Store and vector search

### ISSUE THREAD

**Issue by bimission** [firebase/flutterfire#12955]
Only the Python and Node.js client libraries support vector search
https://firebase.google.com/docs/firestore/vector-search#limitations

Please add support to Dart SDK

**Comment by russellwheatley** [comment]
Hi @bimission - those features are available on the Firebase Admin SDKs. FlutterFire is a thin wrapper around Firebase client SDKs (i.e. android, web, iOS, etc). Whatever the client SDKs support, we aim to support. At the moment, this isn't available on the client SDKs.
