### ISSUE TITLE
[📚] Missing Windows information in "Add Firebase to your Flutter app"

### ISSUE THREAD

**Issue by alestiago** [firebase/flutterfire#12956]
**Description**

[Add Firebase to your Flutter app](https://firebase.google.com/docs/flutter/setup?_gl=1*14fmh0f*_up*MQ..*_ga*MTIyMzIwODMzMy4xNzE4MjcxNjE0*_ga_CW55HF8NVT*MTcxODI3MTYxMy4xLjAuMTcxODI3MTYxMy4wLjAuMA..&platform=web) does not have information about Windows, but Windows seems to be supported by [`firebase_auth` in pub.dev](https://pub.dev/packages/firebase_auth).

**Steps**

1. Go to the `firebase_auth` pub.dev website, see that Windows is an available platform. Navigate to the documentation website that is specified in its README.
2. [Go to Get Started with Firebase Authentication on Flutter](https://firebase.google.com/docs/auth/flutter/start?_gl=1*14fmh0f*_up*MQ..*_ga*MTIyMzIwODMzMy4xNzE4MjcxNjE0*_ga_CW55HF8NVT*MTcxODI3MTYxMy4xLjAuMTcxODI3MTYxMy4wLjAuMA..), see that the first steps refers you to [Add Firebase to your Flutter app](https://firebase.google.com/docs/flutter/setup?_gl=1*14fmh0f*_up*MQ..*_ga*MTIyMzIwODMzMy4xNzE4MjcxNjE0*_ga_CW55HF8NVT*MTcxODI3MTYxMy4xLjAuMTcxODI3MTYxMy4wLjAuMA..&platform=web).
3. [Add Firebase to your Flutter app](https://firebase.google.com/docs/flutter/setup?_gl=1*14fmh0f*_up*MQ..*_ga*MTIyMzIwODMzMy4xNzE4MjcxNjE0*_ga_CW55HF8NVT*MTcxODI3MTYxMy4xLjAuMTcxODI3MTYxMy4wLjAuMA..&platform=web) does not show a Windows platform and does not provide instructions for Windows.

**Screenshots**

![CleanShot 2024-06-13 at 11 15 19](https://github.com/firebase/flutterfire/assets/44524995/ce462c9a-693a-4490-9bd6-746b32a0fc5c)
Alt: A screenshot of the `package:firebase_auth` from pub.dev, showing that Windows is a supported platform.

![CleanShot 2024-06-13 at 11 15 45](https://github.com/firebase/flutterfire/assets/44524995/3fb6068a-b8e5-4c71-b8da-30892dc1c72f)
Alt: A screenshot of [Add Firebase to your Flutter app](https://firebase.google.com/docs/flutter/setup?_gl=1*14fmh0f*_up*MQ..*_ga*MTIyMzIwODMzMy4xNzE4MjcxNjE0*_ga_CW55HF8NVT*MTcxODI3MTYxMy4xLjAuMTcxODI3MTYxMy4wLjAuMA..&platform=web) showing that there is no Windows option.

**Comment by russellwheatley** [comment]
Hey @alestiago - Windows support is for development environment only at the moment. [See the README](https://github.com/firebase/flutterfire). Once it becomes stable, presumably the documentation will also update to reflect setup required.

**Comment by alestiago** [comment]
Awesome, thanks @russellwheatley for the quick reply! 💙 

Would be nice to get the development information in [Add Firebase to your Flutter app](https://firebase.google.com/docs/flutter/setup?_gl=1*14fmh0f*_up*MQ..*_ga*MTIyMzIwODMzMy4xNzE4MjcxNjE0*_ga_CW55HF8NVT*MTcxODI3MTYxMy4xLjAuMTcxODI3MTYxMy4wLjAuMA..&platform=web) too! Note that users landing on pub.dev [`firebase_auth`](https://pub.dev/packages/firebase_auth) or [`firebase_core`](https://pub.dev/packages/firebase_core) might not land on the documentation you shared since there is no direct link to it.

For MacOS, iOS and Android there are some versions constraints the project needs to comply with before adding Firebase to a Flutter application (as stated in the documentation), are there any version constraints for Windows (even when used for development and not production)? If there are version constraints, where are those documented?

**Comment by alestiago** [comment]
Awesome, thanks @russellwheatley for the quick reply! 💙 

Would be nice to get the development information in [Add Firebase to your Flutter app](https://firebase.google.com/docs/flutter/setup?_gl=1*14fmh0f*_up*MQ..*_ga*MTIyMzIwODMzMy4xNzE4MjcxNjE0*_ga_CW55HF8NVT*MTcxODI3MTYxMy4xLjAuMTcxODI3MTYxMy4wLjAuMA..&platform=web) too!

For MacOS, iOS and Android there are some versions constraints the project needs to comply with before adding Firebase to a Flutter application (as stated in the documentation), are there any version constraints for Windows (even when used in a development environment)? If there are version constraints, where are those documented?
