### ISSUE TITLE
How to disable the recaptcha flow in firebase phone authentication (Flutter)

### ISSUE THREAD

**Issue by sai-chandra22** [firebase/flutterfire#12967]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

App Check

### Which platforms are affected?

Android, iOS

### Description

I have enabled Player Integrity in firebase app check, and also added App attest for Ios (Uploaded the auth key and enabled everything for silent notifications), still Recaptcha is coming

### Reproducing the issue

Please list out what else are required for making the auth flow with out recaptcha

### Firebase Core version

2.16.0

### Flutter Version

3.19.6

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by Lyokone** [comment]
Hello @sai-chandra22, Recaptacha is automatically disabled if App attest or any other method can be used. Are you using a prod environment to test that (or at least something deployed to Testflight?)

**Comment by sai-chandra22** [comment]
Hello,

I am testing it in test flight, it is still showing the captcha, how it is
possible even if app attest is made properly.

**Comment by Lyokone** [comment]
I'm not sure without any logs or reproduction sample. You can try to update to the latest versions of the plugins.

**Comment by sai-chandra22** [comment]
Hi,

What logs are you referring to? can you tell me what inputs I need to
present you such that you will explain more about this

Thanks,
Sai chandra

**Comment by Lyokone** [comment]
Any log produced by logcat or the Android device you are testing on.

**Comment by sai-chandra22** [comment]
I m getting this error in IOS device. Previously there is a custom URL in place by which the RECAPTCHA issue is coming according to the doccumentation i found this
<img width="913" alt="Screenshot 2024-06-21 at 3 42 30 PM" src="https://github.com/firebase/flutterfire/assets/169041163/69784e73-0517-44cf-9da3-654c274c818d">

After removing it, I was not even getting logged in
![Simulator Screenshot - iPhone 15 Pro - 2024-06-21 at 15 15 45](https://github.com/firebase/flutterfire/assets/169041163/59b92824-90c1-431b-a952-59559ddd4079)

**Comment by sai-chandra22** [comment]
Any update @Lyokone

**Comment by Lyokone** [comment]
The error is expected if you are removing the URL Scheme. You didn't produce any log we could use to help you debug the issue as requested.

**Comment by sai-chandra22** [comment]
My issue is with ios only, debug console currently showing no errors, can you tell me is there any way to take logs for ios emulator during debug mode ( may be i m not aware of it, kindly help)

**Comment by Lyokone** [comment]
Here is the documentation: https://developer.apple.com/documentation/xcode/acquiring-crash-reports-and-diagnostic-logs#Access-device-console-logs
