### ISSUE TITLE
[📚] Custom sound FCM ios device

### ISSUE THREAD

**Issue by Poloten** [firebase/flutterfire#12977]
There is no documentation how to use FCM 'sound' parameter in ios devices. 
https://firebase.google.com/docs/cloud-messaging/flutter/client

```
android: {
      notification: {
          channelId: "app_alerts",
          sound: 'custom_sound'
      },
  },
  apns: {
      payload: {
          aps: {
              sound: 'custom_sound.wav'
          },
      },
  },
```

When I look for information in other sources, everyone refers to 'flutter_local_notification', but I would like to receive information on how to use without this library, because I receive a ready 'notification' object from the server.

In Android the same situation...

**Comment by Lyokone** [comment]
Hello @Poloten, with FlutterFire we are only bridging the options available on iOS and provided by the Firebase iOS SDK. If this is not documented in the [iOS documentation](https://firebase.google.com/docs/cloud-messaging/ios/receive) (and I couldn't find a reference to this key) you should ask for a documentation update directly on the Firebase iOS SDK repository:  https://github.com/firebase/firebase-ios-sdk

Thanks for raising this :)
