### ISSUE TITLE
[core]: Fail to initialize

### ISSUE THREAD

**Issue by DavidAriza** [firebase/flutterfire#12980]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Core

### Which platforms are affected?

Web

### Description

I'm unable to initialize Firebase in web 

```
FirebaseError: Firebase: No Firebase App '[DEFAULT]' has been created - call initializeApp() first (app/no-app).
https://www.gstatic.com/firebasejs/10.7.0/firebase-app.js 2045:29   getApp
packages/firebase_core_web/src/interop/core.dart 60:28              app$
packages/firebase_core_web/src/firebase_core_web.dart 252:24        initializeApp
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50  <fn>
dart-sdk/lib/async/zone.dart 1661:54                                runUnary
dart-sdk/lib/async/future_impl.dart 162:18                          handleValue
dart-sdk/lib/async/future_impl.dart 846:44                          handleValueCallback
dart-sdk/lib/async/future_impl.dart 875:13                          _propagateToListeners
dart-sdk/lib/async/future_impl.dart 647:5                           [_completeWithValue]
dart-sdk/lib/async/future.dart 529:22                               <fn>
dart-sdk/lib/async/zone.dart 1661:54                                runUnary
dart-sdk/lib/async/future_impl.dart 162:18                          handleValue
dart-sdk/lib/async/future_impl.dart 846:44                          handleValueCallback
dart-sdk/lib/async/future_impl.dart 875:13                          _propagateToListeners
dart-sdk/lib/async/future_impl.dart 647:5                           [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 721:7                           callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                    _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                     _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7  <fn>
```
This is my flutter doctor 

[√] Flutter (Channel stable, 3.16.5, on Microsoft Windows [Versi¢n 10.0.19045.4529], locale es-CO)
    • Flutter version 3.16.5 on channel stable at C:\FlutterSDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (6 months ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\57305\AppData\Local\Android\Sdk
    • Platform android-34, build-tools 33.0.2
    • ANDROID_HOME = C:\Users\57305\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\android-studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.19)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.32901.82
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\android-studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\android-studio
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code (version 1.90.1)
    • VS Code at C:\Users\57305\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.90.0

[√] Connected device (4 available)
    • moto g 60 (mobile) • ZY22FVPZCB • android-arm64  • Android 12 (API 31)
    • Windows (desktop)  • windows    • windows-x64    • Microsoft Windows [Versi¢n 10.0.19045.4529]
    • Chrome (web)       • chrome     • web-javascript • Google Chrome 126.0.6478.114
    • Edge (web)         • edge       • web-javascript • Microsoft Edge 126.0.2592.56

[√] Network resources
    • All expected network resources are available.

• No issues found!

### Reproducing the issue

1. Create a new flutter application 
2. Run flutterfire configure
3. Select web 
4. Run flutter pub add firebase_core
5. Initialize Firebase inside the main
```
WidgetsFlutterBinding.ensureInitialized();
await Firebase.initializeApp(options: DefaultFirebaseOptions.web);
```
6. Run proyect on Chrome

### Firebase Core version

2.27.0

### Flutter Version

3.16.5

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by Lyokone** [comment]
Hello, are you reproducing this issue using the latest versions?

**Comment by DavidAriza** [comment]
Hello, I havent tried the latest versions, I can not upgrade Flutter due to some packages, so I can not upgrade Firebase

**Comment by DavidAriza** [comment]
Hi @Lyokone, now I have tried with flutter 3.22.0, and firebase_core 3.1.0 (latest version), and its still the same result. 

I did flutter clean, flutter pub get,  flutter create --platforms web .,  flutterfire configure, even changed Firebase project and registered a new web app, but nothing works. Am I missing something? 

This is the dart file

```
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:test_web/firebase_options.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.web);
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() async {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```
This is the output where changed the version of firebase js as expected

FirebaseError: Firebase: No Firebase App '[DEFAULT]' has been created - call initializeApp() first (app/no-app).
https://www.gstatic.com/firebasejs/10.11.1/firebase-app.js 2220:29  getApp

[√] Flutter (Channel stable, 3.22.0, on Microsoft Windows [Versi¢n 10.0.19045.4529], locale es-CO)
    • Flutter version 3.22.0 on channel stable at C:\Users\57305\fvm\versions\3.22.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (6 weeks ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3

**Comment by Lyokone** [comment]
@DavidAriza No issue on my side using your example. At this point I'm just assuming a bad development environment. Not sure if it's updating Chrome or corrupted Flutter installation. But initializing Web on Windows or any other platform is working fine;
