### ISSUE TITLE
🐛 [Firebase Remote Config] Add ability to manually set app's locale

### ISSUE THREAD

**Issue by adonisRodxander** [firebase/flutterfire#12982]
## This feature request proposes a new method, `setAppLocale(locale)`

Currently, Firebase Remote Config automatically uses the device's locale to determine the values of variables based on language conditions. However, there is no way to manually set the app's locale.

Firebase Remote Config provides a powerful way to manage and dynamically update app behavior and appearance without requiring users to download an app update. One of its features is the ability to deliver different variable values based on the device's locale. However, this feature has a limitation: it automatically uses the device's locale, and there is no method to manually set the app's locale.

## Current Limitation:

- Firebase Remote Config automatically sends the device's locale, which is used to apply conditions and determine variable values based on language settings.
- Developers do not have the ability to override this behavior and set the app's locale manually.
- Using user properties as a workaround is not ideal because it can take several [hours](https://firebase.google.com/docs/analytics/user-properties?platform=flutter) for data collected with the property to be included in reports. This delay affects the immediacy of configuration changes.

## Use Case:
A multi-language app allows users to switch between languages from within the app. With the current setup, Firebase Remote Config conditions based on locale will not reflect the user's language choice immediately. By using the proposed setAppLocale(locale) method, developers can ensure that Remote Config uses the correct language settings as soon as the user changes the language within the app.

**Comment by Lyokone** [comment]
Thanks for suggesting this feature. Unfortunately, as far as I can tell, it's not supported by the native SDKs. You should post this feature request on https://firebase.uservoice.com/. If it gets added to the native SDKs, we will be able to implement this feature.
