### ISSUE TITLE
firebase_auth_web: No Firebase app '[DEFAULT]' has been created.

### ISSUE THREAD

**Issue by kris-cc3** [firebase/flutterfire#12989]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Auth

### Which platforms are affected?

Web

### Description

I've got as far as working out that this web only both render types, I've also pulled a few other codebases and built for web who have the same issue. Clone this and run and you can see the error https://github.com/coder-Aayush/firebase_auth_riverpod (not my code base) Issue not present on iOS or Android. Yes the app is being initalized in main   await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

### Reproducing the issue

Run firebase Auth on web, set breakpoints to all and uncaught.
![Screenshot 2024-06-23 082733](https://github.com/firebase/flutterfire/assets/164484851/70366fe2-bf7f-4b8c-9bac-165620da014d)
![Screenshot 2024-06-23 082558](https://github.com/firebase/flutterfire/assets/164484851/ed140ab7-d710-4508-b727-1c71ce386624)
![Screenshot 2024-06-23 082540](https://github.com/firebase/flutterfire/assets/164484851/a4864742-2f8f-403f-b97b-9e07c2201fee)

### Firebase Core version

3.1.0

### Flutter Version

3.23

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by TarekkMA** [comment]
Hello @kris-cc3 Did you try the flutterfire auth example app found here: https://github.com/firebase/flutterfire/tree/master/packages/firebase_auth/firebase_auth/example

**Comment by shamith-Adya** [comment]
Any progress on this? I'm facing the exact same issue

**Comment by kris-cc3** [comment]
Yes I tried setting up main as in this example and saw the same issue. I’d need to go back and reconfirm though and have a closer look at what’s in auth.dart. I won’t be at the computer for maybe a week though.

**Comment by shamith-Adya** [comment]
Hi @TarekkMA I'm also able to reproduce this issue in [firebaseauth](https://github.com/firebase/flutterfire/tree/master/packages/firebase_auth/firebase_auth/example) as well 

### Relevant Logs

> Exception has occurred.
> FirebaseError: Firebase: No Firebase App '[DEFAULT]' has been created - call initializeApp() first (app/no-app).
> https://www.gstatic.com/firebasejs/10.11.1/firebase-app.js 2220:29  getApp
> packages/firebase_core_web/src/interop/core.dart 60:28              app$
> packages/firebase_core_web/src/firebase_core_web.dart 255:24        initializeApp
> dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50  <fn>
> dart-sdk/lib/async/zone.dart 1661:54                                runUnary
> dart-sdk/lib/async/future_impl.dart 163:18                          handleValue
> dart-sdk/lib/async/future_impl.dart 847:44                          handleValueCallback
> dart-sdk/lib/async/future_impl.dart 876:13                          _propagateToListeners
> dart-sdk/lib/async/future_impl.dart 652:5                           [_completeWithValue]
> dart-sdk/lib/async/future.dart 532:22                               <fn>
> dart-sdk/lib/async/zone.dart 1661:54                                runUnary
> dart-sdk/lib/async/future_impl.dart 163:18                          handleValue
> dart-sdk/lib/async/future_impl.dart 847:44                          handleValueCallback
> dart-sdk/lib/async/future_impl.dart 876:13                          _propagateToListeners
> dart-sdk/lib/async/future_impl.dart 652:5                           [_completeWithValue]
> dart-sdk/lib/async/future_impl.dart 722:7                           callback
> dart-sdk/lib/async/schedule_microtask.dart 40:11                    _microtaskLoop
> dart-sdk/lib/async/schedule_microtask.dart 49:5                     _startMicrotaskLoop
> dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7  <fn>

**Platform** : Web

### SDK

> ➜  example git:(master) ✗ flutter doctor   
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale en-IN)
> [✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
> [✓] Xcode - develop for iOS and macOS (Xcode 15.4)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 2023.3)
> [✓] VS Code (version 1.90.2)
> [✓] Connected device (4 available)
> [✓] Network resources

**Comment by TarekkMA** [comment]
I couldn't get this issue to happen to the flutter auth example. How are you running the application? I'm using `flutter run -d chrome`

Here's my flutter version:
```
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale en-EG)
    • Flutter version 3.22.2 on channel stable at /Users/tarekkma/Developer/Libs/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (3 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3
```

**Comment by TarekkMA** [comment]
I got this error while running on VSCode set to catch all exceptions, but the app seems to run normally without any issues.
