### ISSUE TITLE
[Data Connect] Data Connect feature request

### ISSUE THREAD

**Issue by miguelfs** [firebase/flutterfire#13001]
## What feature would you like to see?
Hi, Firebase announced Data Connect as relational SQL database alternative for Firestore.

When consuming Data Connect data at the client, the documentation offers solutions for web and Android, [here](https://firebase.google.com/docs/data-connect/quickstart?authuser=0&hl=pt#generate-client).

Since this feature is in experimental support at these environments, I wonder if the implementation for Flutter should kickstart soon.

**Comment by Lyokone** [comment]
You can discuss your needs for Data Connect here: https://firebase.uservoice.com/forums/948424-general/suggestions/48437954-dart-sdk-for-data-connect
We don't have timeline but it's being discussed internally how to best achieve this with Dart, especially seeing the new macros.
