### ISSUE TITLE
[firebase_auth 4.20.0]: Use Anonymously, currentUser is null

### ISSUE THREAD

**Issue by Chau14022000** [firebase/flutterfire#13008]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Auth

### Which platforms are affected?

iOS

### Description

Even though I was logged in before and my code only performed logout before logging in, some time later that user used the app again without knowing the word minimized or starting from scratch and I don't know what that user did. but FirebaseAuth.instance.currentUser was null, surely the user did not clear the cache because this is an iOS device that does not have this feature.
I still don't know if this error is due to the user's device or the library, can anyone explain to me?
What is the _delegate value, is it lost?

### Reproducing the issue

I can't reproduce it, but my users are mainly on high versions of IOS, there is an API (called when starting the app) that rarely happens. so I guess that happens when the app is minimized

### Firebase Core version

2.32.0

### Flutter Version

3.19.5

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by Lyokone** [comment]
Hello @Chau14022000, anonymous tokens don't expire so if you have not logged out your user, it should still be the same. it's persisted on disk, but maybe your user ran out of storage on its iOS device.

**Comment by Chau14022000** [comment]
Hi @Lyokone 
Do you mean that when my device runs out of storage, the token previously saved on disk will be automatically deleted? Isn't that a bit unreasonable? 🙇‍♀️
