### ISSUE TITLE
🐛 [firebase_auth] Update MFA Phone Number

### ISSUE THREAD

**Issue by AbhishekDoshi26** [firebase/flutterfire#13004]
As of now, there's no way we can update MFA phone number. With admin sdk, it's only possible using NodeJS admin sdk.

Basically, we want to have a update phone number feature for our app and admin dashboard and we are completely blocked right now.

Any workarounds as of now? We are using JAVA Admin SDK.

**Comment by AbhishekDoshi26** [comment]
@Lyokone can you help in this?

**Comment by Lyokone** [comment]
Hello @AbhishekDoshi26, if you need help with the Java ADMIN SDK, you can ask here: https://github.com/firebase/firebase-admin-java
