### ISSUE TITLE
[Crashlytics]: Missing UUID in crash reports

### ISSUE THREAD

**Issue by pamafe1976** [firebase/flutterfire#13030]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Crashlytics

### Which platforms are affected?

Android, iOS

### Description

I often receive crash reports with stack traces that indicate that there are missing UUIDs. Some other reports are fine.

```
2  Flutter                        0x58df4 (Missing UUID 4c4c44ce55553144a1c1c6eff75c53e3)
3  Flutter                        0x3ef7b4 (Missing UUID 4c4c44ce55553144a1c1c6eff75c53e3)
4  Flutter                        0x2e66c (Missing UUID 4c4c44ce55553144a1c1c6eff75c53e3)
5  Flutter                        0x2e53c (Missing UUID 4c4c44ce55553144a1c1c6eff75c53e3)
```
I'm uploading symbols during build, with this commands:

```
flutter build appbundle --release  --split-debug-info="build/app/outputs/symbols"
firebase crashlytics:symbols:upload --app APPID build/app/outputs/symbols 
```
what can be causing this issue?

### Reproducing the issue

Not applicable

### Firebase Core version

3.1.1

### Flutter Version

3.22.1

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by russellwheatley** [comment]
@pamafe1976 - Is this from a android or iOS crash report?

```bash
2  Flutter                        0x58df4 (Missing UUID 4c4c44ce55553144a1c1c6eff75c53e3)
3  Flutter                        0x3ef7b4 (Missing UUID 4c4c44ce55553144a1c1c6eff75c53e3)
4  Flutter                        0x2e66c (Missing UUID 4c4c44ce55553144a1c1c6eff75c53e3)
5  Flutter                        0x2e53c (Missing UUID 4c4c44ce55553144a1c1c6eff75c53e3)
```

**Comment by pamafe1976** [comment]
That one is from IOS

**Comment by russellwheatley** [comment]
This is for android:
```
flutter build appbundle --release  --split-debug-info="build/app/outputs/symbols"
firebase crashlytics:symbols:upload --app APPID build/app/outputs/symbols 
```

iOS app debug symbols are uploaded when you build your app. This script is injected into build phase run scripts when you run `flutterfire configure`. Install the latest version:

```bash
dart pub global activate flutterfire_cli 1.0.1-dev.2
```

and configure your app. Here is a [recent issue](https://github.com/invertase/flutterfire_cli/issues/314) about this specific issue on FlutterFire CLI. If you still cannot fix the problem, you might want to open an issue on the [FlutterFire CLI repo](https://github.com/invertase/flutterfire_cli)
