### ISSUE TITLE
Firebase Performance: Custom traces are not captured in the real devices

### ISSUE THREAD

**Issue by Rasul8215** [firebase/flutterfire#13043]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Performance

### Which platforms are affected?

Android

### Description

I created the some custom traces in the app. That traces are captured in the emulator but same custom traces are not captured in the real devices.

### Reproducing the issue

Performance dashboard contains the traces only in the emulator device.

### Firebase Core version

3.1.1

### Flutter Version

0.10.0+2

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by TarekkMA** [comment]
@Rasul8215 Thank you for reporting this issue, can you please provide a reproduction repo where I can reproduce this issue?
