### ISSUE TITLE
[AUTH]: Inconsistent behavior when switching from emulators to server

### ISSUE THREAD

**Issue by pamafe1976** [firebase/flutterfire#13051]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Description

If an app is initialized using local emulators (useAuthEmulator and useFirestoreEmulator), and there is an anonymous sign in (signInAnonymously); and afterwards the app is restarted without using the emulators, the Firestore get return cached emulator data, also marking it as not from cache. The cached data is returned even after stopping the emulators.
In this situation, also the old user auth credential is returned instead of null.
I have not found a way of recovering from that situation without deleting all app data. An auth signout wont help, because the new call to signInAnonimously will return a credential (I dont know from where, because the emulator is off and the uid is not being registered on the server). If at this point I call FirebaseFirestore.instance.clearPersistence, the next gets will start failing as unauthorized, because the user is not authenticated.

Im worried mostly about this behavior in which the cached credential seems to be invalid or corrupt and there is no exception thrown and no way to recover. I don't know if this could happen under any circunstance when not using the emulator, but it would be good to have a way of detecting and recovering from this kind of invalid auth situation.

### Reproducing the issue

1) Start app with emulators on
2) Sign in to FirebaseAuth anonimously
3) Get some doc from Firestore
4) Restart without enabling emulators
5) Get the same doc. It will retrieve doc from cache with emulator content, with metadata isFromCache=false
6) Auth signOut, and anonymous sign in again (no error or exception)
7) No way that I could find to recover from this (being able to sign in again to the server) without clearing app cache and data

### Firebase Core version

3.1.1

### Flutter Version

3.22.1

### Flutter dependencies

  cloud_firestore: ^5.0.2
  cloud_functions: ^5.0.2
  firebase_analytics: ^11.1.0
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_crashlytics: ^4.0.2
  firebase_dynamic_links: ^6.0.2
  firebase_messaging: ^15.0.2
  firebase_performance: ^0.10.0+1
  firebase_remote_config: ^5.0.2
  firebase_storage: ^12.1.0

**Comment by Lyokone** [comment]
Hello @pamafe1976, thanks for reaching out. I see what is your issue, unfortunately, there is nothing that FlutterFire can do directly. You should not mix your dev (emulator) environment with your prod (server) environment. 

You can try to have different bundle for different environments so you don't get inconsistent data. 

If you feel this is something that needs to be addressed directly, you can open an issue on the [Android](https://github.com/firebase/firebase-android-sdk) or [iOS](https://github.com/firebase/firebase-ios-sdk) repository.

**Comment by pamafe1976** [comment]
Hi @Lyokone, I understand your point. During developement I can clear the data every time I switch from emulator to prod, no problem with that... 
But what worries me most is the fact that the Auth does not throw any error or even notice that the cached data is invalid. My fear is that for some reason the cached credential might become corrupt or out of sync at some point, and since there is no exception the app wont be able to access firebase services anymore, and it will be dead until the user decides to clear data or reinstall.
