### ISSUE TITLE
Firebase.initializeApp(     options: DefaultFirebaseOptions.currentPlatform,   ) intialize issue

### ISSUE THREAD

**Issue by developeramit3** [firebase/flutterfire#13055]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Core

### Which platforms are affected?

Android

### Description

PlatformException(java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.firebase.auth.FirebaseUser com.google.firebase.auth.FirebaseAuth.getCurrentUser()' on a null object reference, ExecutionException, Cause: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.firebase.auth.FirebaseUser com.google.firebase.auth.FirebaseAuth.getCurrentUser()' on a null object reference, Stacktrace: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.firebase.auth.FirebaseUser com.google.firebase.auth.FirebaseAuth.getCurrentUser()' on a null object reference

### Reproducing the issue

Issue in Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  ),

### Firebase Core version

4.19.4

### Flutter Version

3.19.0

### Relevant Log Output

```shell
PlatformException(java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.firebase.auth.FirebaseUser com.google.firebase.auth.FirebaseAuth.getCurrentUser()' on a null object reference, ExecutionException, Cause: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.firebase.auth.FirebaseUser com.google.firebase.auth.FirebaseAuth.getCurrentUser()' on a null object reference, Stacktrace: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.firebase.auth.FirebaseUser com.google.firebase.auth.FirebaseAuth.getCurrentUser()' on a null object reference
```

### Flutter dependencies

  firebase_core: ^2.28.0
  cloud_firestore: ^4.17.2
  firebase_auth: ^4.19.4

**Comment by TarekkMA** [comment]
@developeramit3 Thank you for reporting this issue.

You need to use the latest FlutterFire packages. If you still face the same issue, please open a new issue with more details and a reproduction example.
