### ISSUE TITLE
[flutterfire]: CDN: trunk URL couldn't be downloaded:

### ISSUE THREAD

**Issue by nzackoya** [firebase/flutterfire#13050]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Storage

### Which platforms are affected?

iOS

### Description

Any ios update via `pod update` stucks on firebase_storage and couldn't be downloaded in Russia, it works only with VPN
CDN: trunk URL couldn't be downloaded: .... Response: Timeout was reached

### Reproducing the issue

Update the firebase libs in `pubsec` and run `pod update` in Russia

### Firebase Core version

3.1.1

### Flutter Version

3.22.2

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by Lyokone** [comment]
Hello, the pods are not hosted directly by this project, you should open an issue in https://github.com/CocoaPods/CocoaPods
