### ISSUE TITLE
Found some security issues

### ISSUE THREAD

**Issue by devsideal** [firebase/flutterfire#13053]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Auth, Cloud Functions, Messaging

### Which platforms are affected?

Android, iOS

### Description

I did a security test on `appsweep` with below packages:
`firebase_auth: ^5.1.0`
`firebase_messaging: ^15.0.1`
`cloud_firestore: ^5.0.1`

And found the below security issues in the report:
![image](https://github.com/firebase/flutterfire/assets/91250232/4b984ec8-aee5-4ed8-bd5e-d48267f9060c)

Is there any way to resolve these issues?

### Reproducing the issue

1. Add all the given three packages and sync
2. Build apk file
3. Test the apk with any security testing tool `appsweep`
4. You will see that security issues.

### Firebase Core version

3.1.0

### Flutter Version

3.22.2

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by TarekkMA** [comment]
Can you please post more details about what exact issues did you find?

**Comment by devsideal** [comment]
@TarekkMA  Please find the more details:

`cloud_firestore: ^5.0.1`  showing **Insecure hashing algorithm MD5 used** with below findings:
![Screenshot from 2024-07-09 11-47-55](https://github.com/firebase/flutterfire/assets/91250232/66a26367-6d12-4313-b50b-460dd8eca1bb)

`firebase_auth: ^5.1.0` showing **Insecure hashing algorithm SHA1 used** with below findings:

![image](https://github.com/firebase/flutterfire/assets/91250232/f371b67a-03af-4979-81c3-d48df5e0cdd0)
![image](https://github.com/firebase/flutterfire/assets/91250232/cfb4d701-9c2d-4853-9c07-16fe0f93b902)

`firebase_messaging: ^15.0.1` showing **Insecure hashing algorithm SHA-1 used** with below findings:
![image](https://github.com/firebase/flutterfire/assets/91250232/e026013e-946d-405d-8a52-9158ab9879a0)

**Comment by TarekkMA** [comment]
@devsideal Thank you for the details. Since the issue you are referring to seems to be originating from the underlying native Android SDK, I would suggest you open a new issue here: https://github.com/firebase/firebase-android-sdk.
