### ISSUE TITLE
Firebase Phone MFA not working with some numbers

### ISSUE THREAD

**Issue by radikris** [firebase/flutterfire#13061]
I found this similar issue.

> @ibragimazizli if you're still experiencing this problem and want to continue the discussion just leave a comment here and we are happy to re-open this.
> 
> _Originally posted by @google-oss-bot in https://github.com/firebase/flutterfire/issues/12594#issuecomment-2095037520_

            

I've been using Firebase Authentication with Multi-Factor Authentication (MFA) in my Flutter app (web) without issues for the past 6 months. Recently, I started encountering a `500 Internal Server Error` when trying to initiate MFA. No code changes were made to the authentication logic. It was working before, some days ago I startet getting this 500 error on the mfa:start endpoint.

#### Packages:
```yaml
dependencies:
  firebase_auth: ^4.14.1
  firebase_storage: ^11.0.10
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
```

#### Error Message:
```json
{error: {code: 500, message: "Internal error encountered.", status: "INTERNAL"}}
```

#### Checked the Endpoint calls, this throws 500:
https://identitytoolkit.googleapis.com/v2/accounts/mfaSignIn:start?key=MY_API_KEY
In the body request it also contains all the neccessary info:

    {
        "mfaPendingCredential": "AMzJoSk ... MFA PENDING CREDENTIAL",
        "mfaEnrollmentId": "db86e89e-b3c6-47cb ... ENROLLMENT ID ",
        "phoneSignInInfo": {
            "recaptchaToken": "03AFcWe... RECAPTCHA"
        }
    }

The signInWithEmailAndPassword and recaptcha endpoint runs to 200, and returns back the mfa-id and all the other info related and needed.

#### What I've Tried:
- **Retrying the request:** Multiple times with no success.
- **Checking Firebase Status:** No reported outages or issues.
- **Reviewing API Documentation:** No updates or deprecations found related to my issue.
- **Updating Dependencies:** Cant really update it easily, because this is an old project, and have dependency conflict with the latest Flutter, but as I said, this project has been running since 6 month without issues.

#### Additional Info:
I found a note about cross-origin redirect sign-in on Google Chrome M115+ stopping on June 24, 2024. However, I don't think this is related as my issue is with the signInWithEmailAndPassword and it should not affects phone auth MFA process itself?!

#### Questions:
1. What could be causing this sudden `500 Internal Server Error`?
2. Has there been any recent changes to Firebase Auth that could affect MFA?
3. How can I debug or resolve this issue?

Any help or insights would be greatly appreciated!

FIREBASE PROJECT ID: marketprog-bf7d3
________________

 **UPDATE:**
 I talked to the support, I experience this issue with Hungarian phone numbers (we are operating here in Hungary...), but I tried with the added test phone number it worked, also tried some free USA and Finnland based phonenumber and the sms were received, but the hungarian "carriers affected with consistently low SMS success rates are temporarily unavailable" - the support told me.
             
 This auth feature is crucial for our production application, where we need a second layer after the sign in email+password also type the SMS code they receive.

I found a similar stackoverflow reference, but the author deleted the post, but it looks like we have the same issue (production app, eastern european country, phone auth/mfa, sms OTP):
<img width="697" alt="image" src="https://github.com/firebase/flutterfire/assets/55052220/d7250050-a7ac-44a0-b3e6-5938c1f6b511">

[![firebase api call 500 and 200][2]][2]

  [2]: https://i.sstatic.net/3Grxk4rl.png
            
            
    Stackoverflow link: https://stackoverflow.com/questions/78718291/firebase-multi-factor-authentication-suddenly-failing-with-500-internal-server-e

**Comment by TarekkMA** [comment]
Hello @radikris,

Thank you for pointing this out. Since only some numbers (Hungarian) are affected but not others, I'm afraid that this issue cannot be solved/handled by the FlutterFire team. You can continue contacting Firebase support to reach a solution.
