### ISSUE TITLE
[firebase_messaging]: After turning off the device and turn back on, onBackgroundMessage is not fired on iOS.

### ISSUE THREAD

**Issue by ViniciusSossela** [firebase/flutterfire#13072]
Steps:
1 - Turn off the iPhone real device
2 - Turn on the iPhone device (DO NOT OPEN YOUR APP)
3 - Send a push notification
The DEVICE will receive the notification, but the APP will not.
`onBackgroundMessage` is not fired on iOS in this situation

(After turning back on the device and opening it at least once, it starts to fire the onBackgroundMessage handler).
In other words, -->**_EVERY TIME_**<-- the device is turned off and on, the APP must be opened at least once, to start to fire onBackgroundMessage.

**Is this a normal situation?**

@russellwheatley can you help me with this?

Code:
```
@pragma('vm:entry-point')
Future<void> backgroundHandler(remoteMessage) async {
//my stuffs never called after turn on
}

Future<Null> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  FirebaseMessaging.onBackgroundMessage(backgroundHandler);

.....

  runApp(MyApp());
}

```

_Originally posted by @ViniciusSossela in https://github.com/firebase/flutterfire/discussions/13071_

**Comment by Lyokone** [comment]
Hello, please use the correct template for this kind of issues: "iOS background message handling bug report for Firebase Messaging"
