### ISSUE TITLE
[firebase_analytics_web]: Error (Xcode): ../../../.pub-cache/hosted/pub.dev/firebase_core_web-2.17.3/lib/src/interop/utils/es6_interop.dart:18:12: Error: Type 'JSString' not found.

### ISSUE THREAD

**Issue by geronimol** [firebase/flutterfire#13087]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Analytics

### Which platforms are affected?

iOS, macOS

### Description

 I can't run the app on iOS after adding the web implementation. But works fine for Web.
 Am I doing something wrong?
 
 `Error (Xcode): ../../../.pub-cache/hosted/pub.dev/firebase_core_web-2.17.3/lib/src/interop/utils/es6_interop.dart:18:12: Error: Type 'JSString' not found.`

### Reproducing the issue

1. Add dependencies

```dart
 firebase_analytics: ^11.2.0
 firebase_analytics_web: ^0.5.9
```
2. Add `import 'package:firebase_analytics_web/firebase_analytics_web.dart';`

3. Inside the `main()`:

```dart
WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  /// Analytics
  try {
    await FirebaseAnalyticsWeb().logEvent(
      name: 'screen_view',
      parameters: {
        'firebase_screen': 'home',
        'firebase_screen_class': 'home_page',
      },
    );
  } catch (e) {
    log(e.toString());
  }
```

### Firebase Core version

3.2.0

### Flutter Version

3.22.3

### Relevant Log Output

```shell
Error (Xcode): ../../../.pub-cache/hosted/pub.dev/firebase_core_web-2.17.3/lib/src/interop/utils/es6_interop.dart:18:12: Error: Type 'JSString' not found.
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by Lyokone** [comment]
Hello @geronimol, you are not supposed to add _web packages directly or use them directly. you can use `FirebaseAnalytics` and it will log on web normally.
