### ISSUE TITLE
[firebase_auth]: Google login fails with local emulator

### ISSUE THREAD

**Issue by inteist** [firebase/flutterfire#13095]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Auth

### Which platforms are affected?

Android, iOS

### Description

Exception has occurred.
FirebaseAuthException ([firebase_auth/unknown] An internal error has occurred. [ The Auth Emulator only support sign-in with google.com using id_token, not access_token. Please update your code to use id_token.)

```dart
class GoogleSignInProvider extends SignInProviders {
  ///
  @override
  Future<UserCredential?> signIn() async {
    // Trigger the authentication flow
    final GoogleSignInAccount? googleUser = await GoogleSignIn().signIn();

    // Obtain the auth details from the request
    final GoogleSignInAuthentication? googleAuth = await googleUser?.authentication;

    // Create a new credential
    final credential = GoogleAuthProvider.credential(
      idToken: googleAuth?.idToken,
      accessToken: googleAuth?.accessToken,
    );

    // Once signed in, return the UserCredential
    return await FirebaseAuth.instance.signInWithCredential(credential);
  }
}
```

-----------------------

❯ firebase --version
13.13.2

  firebase_auth:
    dependency: "direct main"
    description:
      name: firebase_auth
      sha256: a41b56878fa6aef3ea52962329b47eee333672d4b0ecc406e071b9fc729f242c
      url: "https://pub.dev"
    source: hosted
    version: "5.1.2"
  firebase_auth_platform_interface:
    dependency: transitive
    description:
      name: firebase_auth_platform_interface
      sha256: d1c68097588f3b75ef79a22102ff96c311735c254353bccf6824d19f1a7e86b9
      url: "https://pub.dev"
    source: hosted
    version: "7.4.2"
  firebase_auth_web:
    dependency: transitive
    description:
      name: firebase_auth_web
      sha256: e66ec0ae5697ee39ccd4865d6887cb0df220dd4ea0b21404910c68ca4c1a731a
      url: "https://pub.dev"
    source: hosted
    version: "5.12.4"

### Reproducing the issue

using following code:

```dart
class GoogleSignInProvider extends SignInProviders {
  ///
  @override
  Future<UserCredential?> signIn() async {
    // Trigger the authentication flow
    final GoogleSignInAccount? googleUser = await GoogleSignIn().signIn();

    // Obtain the auth details from the request
    final GoogleSignInAuthentication? googleAuth = await googleUser?.authentication;

    // Create a new credential
    final credential = GoogleAuthProvider.credential(
      idToken: googleAuth?.idToken,
      accessToken: googleAuth?.accessToken,
    );

    // Once signed in, return the UserCredential
    return await FirebaseAuth.instance.signInWithCredential(credential);
  }
}
```

### Firebase Core version

3.2.0

### Flutter Version

3.22.3

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by Lyokone** [comment]
Hello @inteist, it seems that you are using both 
```
    final credential = GoogleAuthProvider.credential(
      idToken: googleAuth?.idToken,
      accessToken: googleAuth?.accessToken,
    );
```

You might you to try to use only `idToken` according to your error message. It looks like it's an expected behavior.

**Comment by inteist** [comment]
Yes, I tried and it comes back as `NULL` with auth simulated.

**Comment by inteist** [comment]
@Lyokone Yes, I tried and it comes back as NULL with auth simulated.
