### ISSUE TITLE
cloud_firestore: There is a bug when we have an empty document in the Windows version

### ISSUE THREAD

**Issue by HeroRickyGAMES** [firebase/flutterfire#13099]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Database

### Which platforms are affected?

Windows

### Description

Hello, how are you, yesterday I had a meeting with my boss and my program simply closed abruptly, after a search I detected that the .doc(idCondominio) o idCondominio was empty because it had not yet been collected and set.
In the debug version you don't hear any errors.
When I got home I tested the production version to see if everything was ok and it could be something on the guy's PC there, so I opened it and came across this, no logs, no error stack, nothing.
It was basically blindly that I found this possible flaw.
The right thing to do was to display something in the console... The document cannot be empty, as is normally the case in Android and Web versions.

### Reproducing the issue

After a search I detected that the .doc(idCondominio) o idCondominio was empty because it had not yet been collected and set.
In the debug version you don't hear any errors.
When I got home I tested the production version to see if everything was ok and it could be something on the guy's PC there, so I opened it and came across this, no logs, no error stack, nothing.
It was basically blindly that I found this possible flaw.
The right thing to do was to display something in the console... The document cannot be empty, as is normally the case in Android and Web versions.

### Firebase Core version

3.2.0

### Flutter Version

3.22.1

### Relevant Log Output

```shell
The app was closed after clicking Ctrl+C, without any logs.
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> cloud_firestore</summary>
<br>
</details>

**Comment by exaby73** [comment]
Hello @HeroRickyGAMES. Can you provide a code sample that reproduces this issue so that I may test it?

**Comment by HeroRickyGAMES** [comment]
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';

//Desenvolvido por HeroRickyGames

//Change the testclass("") to another value to solve the problem.
main(){
  runApp(
    MaterialApp(
      home: testclass(""),
    )
  );
}

class testclass extends StatefulWidget {

  String checkedDoc = "";
  testclass(this.checkedDoc, {super.key});

  @override
  State<testclass> createState() => _testclassState();
}

class _testclassState extends State<testclass> {

  initCode() async {
    //The line issue
    var getUserPermissions = await FirebaseFirestore.instance
        .collection("QualquerColecao")
        .doc(widget.checkedDoc).get();

    print(getUserPermissions["sameValue"]);
  }

  @override
  Widget build(BuildContext context) {
    return const Placeholder();
  }
}

**Comment by Lyokone** [comment]
Hello @HeroRickyGAMES, it looks like your code is at fault since you're not calling `data()` on your `getUserPermissions` to get the actual data. Not sure how this is supposed to work. Check for null safety issues before force getting the document.

**Comment by HeroRickyGAMES** [comment]
@Lyokone So does this mean that a serious problem in the dependency is an error in my code?
I don't think you read what I said, so I'll say it again!

The app is closing in the RELEASE VERSION! In the DEBUG version it works normally and in ANDROID this problem does not happen!

In fact, the expected behavior was to have a document, BUT IN THE RELEASE VERSION it does not put an alert, much less in DEBUG.
There should be an alert saying that document x is empty.
