### ISSUE TITLE
[AUTH]: Flutter web "signInWithPhoneNumber" error : invalid-app-credential

### ISSUE THREAD

**Issue by saharvx9** [firebase/flutterfire#13098]
### Which plugins are affected?

`firebase_auth
`
### Which platforms are affected?

Web

### Description

When i am using test numbers and calling `signInWithPhoneNumber` working great, but when i am using real numbers, i am getting all the time error of :` invalid-app-credential`

I checked in the github of firebase js and saw this issue :
https://github.com/firebase/firebase-js-sdk/issues/8387

Same as error i receive, 
For veryfication, i working at the porject with firebase long time, so configuration are correct and using 
on my main widget : 

```
 await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
```

Snipt code : 

```
  void submitPhoneNumber() async {
    state.add(Loading());
    if (!_validPhone(_phoneNumber)) {
      state.add(Error("Not valid"));
      return;
    }

    final phone = "+972${_phoneNumber!.substring(1, _phoneNumber!.length)}";

    try {
      _confirmationResult = await _auth.signInWithPhoneNumber(phone);
      logI("verificationSent ${_confirmationResult?.verificationId}");
      state.add(DisplayPinCode());
    } on FirebaseAuthException catch (e){
      logE("verificationFailed : ${e.message}, code ${e.code}", stackTrace: e.stackTrace);
    } catch (e, s) {
      logE("verificationFailed : $e", stackTrace: s);
    }
  }
```

Flutter doctor : 

```
[!] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale en-IL)
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.0.5/libexec/bin/dart, which is not inside your current Flutter SDK
      checkout at /Users/saharvanunu/flutter. Consider adding /Users/saharvanunu/flutter/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] IntelliJ IDEA Community Edition (version 2024.1.1)
[✓] VS Code (version 1.85.1)
[✓] Connected device (3 available)
    ! Error: Browsing on the local area network for גילה iphone. Ensure the device is unlocked and attached with a cable or associated with the
      same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources
```

### Reproducing the issue

1. Call `signInWithPhoneNumber`
2. receive immediately error 

Expect : 
Get sms with no errors.

### Firebase Core version

3.2.0

### Flutter Version

3.22.2

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

  firebase_core: 3.2.0
  firebase_auth: 5.1.2
  cloud_firestore: 5.1.0
  firebase_storage: 12.1.1
  cloud_functions: 5.0.3
```

</details>

**Comment by Lyokone** [comment]
Thanks for linking the JS issue, it seems to be related to the native SDK, so it will need to be resolved by the backend teams.

**Comment by lisovyk** [comment]
Same is happening for us in production at web! Any quick ways to fix it from out side?

**Comment by Lyokone** [comment]
@lisovyk Not yet, you can follow https://github.com/firebase/firebase-js-sdk/issues/8387 for more information

**Comment by lisovyk** [comment]
@Lyokone we tracked it down to one of the carriers in Ukraine not getting OTP's while others work fine, and firebase giving us the same error. If only there was a dashboard with all carrier statuses updated at least daily, huh. It's an issue we encounter couple times a year, every time with new surprising and exciting error messages not telling you a thing.

**Comment by Lyokone** [comment]
It seems related to this comment: https://github.com/firebase/flutterfire/pull/13100

**Comment by PROGrand** [comment]
Error appears when web app run on localhost (from IDE).
And not appears when run on deployment server with ssl.

**Comment by SheharyarAmin** [comment]
Any updates on this?
