### ISSUE TITLE
[firebase_analytics]: Update Google Analytics for Firebase (GA4F) iOS SDK to Version 10.24.0 or Later

### ISSUE THREAD

**Issue by BunnyBuddy** [firebase/flutterfire#13090]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Core, Analytics

### Which platforms are affected?

iOS

### Description

Action Recommended:
Update the Google Analytics for Firebase (GA4F) iOS SDK to version 10.24.0 or later to comply with upcoming privacy manifest policies effective after May 1, 2024.

Issue Details:
The current version of the GA4F iOS SDK in our project needs to be updated to version 10.24.0 or later. Failure to update may result in potential impacts due to new privacy manifest policies that come into effect after May 1, 2024.

Can you suggest which Firebase Analytics version I should migrate to resolve this privacy policy issue?

Also, my firebase_analytics version in the project is 9.1.1 and firebase_core version is 1.24.0

(We're using an old version of flutter because this is a huge but old app and it would take months to bring it to null safety)

### Reproducing the issue

not applicable

### Firebase Core version

1.24.0

### Flutter Version

2.10.4

### Flutter dependencies

  firebase_core: ^1.24.0
  firebase_analytics: 9.1.1
  firebase_performance: ^0.6.0+2
  firebase_core_platform_interface: 4.2.0

**Comment by BunnyBuddy** [comment]
I know this has been resolved on April 12 in a PR but is there a way to resolve this without moving to null safe version of Flutter?

**Comment by Lyokone** [comment]
Hello 👋 You can manually override in your Podfile using 
```
$FirebaseSDKVersion = '10.24.0'
```
You might encounter some unexpected issues since you are using a very old version.

**Comment by BunnyBuddy** [comment]
This is my podfile,
```
# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

$FirebaseSDKVersion = '10.24.0'

# source 'https://github.com/CocoaPods/Specs.git'
# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

(and so on...)
```
but google is still showing **Update Google Analytics for Firebase (GA4F) iOS SDK to Version 10.24.0 or Later...**, is the notification just gonna stay there or am I doing something wrong?
