### ISSUE TITLE
[firebase_messaging]: getInitialMessage() intermittently returns null

### ISSUE THREAD

**Issue by orourkedd** [firebase/flutterfire#13108]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Messaging

### Which platforms are affected?

iOS

### Description

This appears to be similar [9906](https://github.com/firebase/flutterfire/issues/9906).

`getInitialMessage` intermittently returns null and can be worked-around by polling the method. It looks like some kind of race condition.

I have been using code similar to the following in production to work around it and to report the number of attempts it required to get the message:

```
Future<RemoteMessage?> getInitialMessage() async {
  for (var i = 0; i < 10; i++) {
    var initialMessage = await FirebaseMessaging.instance.getInitialMessage();

    if (initialMessage != null) {
      Sentry.captureMessage("initial message retrieved after ${i + 1} attempts.");
      return initialMessage;
    }

    await Future.delayed(const Duration(seconds: 1));
  }

  return null;
}
```

I have seen in our Sentry logs that the initial message appears after several attempts, sometimes even 8 or 9 attempts.

I don't know if there is something I should be waiting on before using `getInitialMessage`. If there is nothing to wait on, it looks like there is a race condition that needs to be fixed or perhaps polling like this can be added to the `getInitialMessage` itself.

### Reproducing the issue

It is very difficult to reproduce and I see it only in production intermittently. For this reason, it appears to be some kind of race condition.

### Firebase Core version

2.32.0

### Flutter Version

3.22.3

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by Poloten** [comment]
getInitialMessage() not working on ios, because when you get the push message application start in invisible mode in background... You should wait until application is in AppLifecycleState.resumed state and than call getInitialMessage().
Unfortunately, the developers ignore this point.

**Comment by Lyokone** [comment]
Hello @orourkedd, thanks for raising this. 
@Poloten do you have a complete sample on how you are avoiding this issue? We don't encounter it during our tests with our sample app. Maybe some other libraries are interacting with firebase_messaging?

**Comment by Poloten** [comment]
> Hello @orourkedd, thanks for raising this. @Poloten do you have a complete sample on how you are avoiding this issue? We don't encounter it during our tests with our sample app. Maybe some other libraries are interacting with firebase_messaging?

[Lyokone](https://github.com/Lyokone) the error is related to the fact that the context when processing onBackgroundMessage(firebaseMessagingBackgroundHandler) and the context when clicking on a push message are the same. But in original documentation: "the handler runs in its own isolate outside your applications context, it is not possible to update application state or execute any UI impacting logic. " https://firebase.google.com/docs/cloud-messaging/flutter/receive

[Lyokone](https://github.com/Lyokone) Can I see your current sample on Swift with the latest version of Flutter and fcm libraryes, because the current sample in Git is very old.
