### ISSUE TITLE
[firebase_database, firebase_core, firebase_analytics]: Issue in the latest version(3.2.0) of firebase core: "requires a higher minimum iOS deployment version than the plugin's reported minimum version" issue while running the application.

### ISSUE THREAD

**Issue by cshanjib** [firebase/flutterfire#13114]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Core, Analytics, Database

### Which platforms are affected?

iOS

### Description

Getting the "requires a higher minimum iOS deployment version than the plugin's reported minimum version" issue while running the application.
In the 3.2.0 version of Firebase core, Firebase iOS SDK bumps to 10.28.0.
In firabase_database, the minimum target is 13.0. However, it seems that Firebase/Database version 10.28.0 requires the minimum target to be set at a version greater than 13.0.

It seems the minimum target needs to be bumped to 14 to use the Firebase iOS SDK 10.28.0 and all the dependent plugins need to update this as well.

I am getting the same issues in other plugins(firebase_analytics) as well.

Error: The pod "Firebase/Database," required by the plugin "firebase_database" requires a higher minimum iOS deployment version than the plugin's reported minimum version.
To build, remove the plugin "firebase_analytics", or contact the plugin's developers for assistance.
Error running pod install

Error: The pod "Firebase/Analytics," required by the plugin "firebase_analytics" requires a higher minimum iOS deployment version than the plugin's reported minimum version.
To build, remove the plugin "firebase_analytics", or contact the plugin's developers for assistance.
Error running pod install

### Reproducing the issue

Set Firebase core to the current latest version: 3.2.0 
Set the Firebase database, and analytics to the current latest version: 11.0.3 or below.

Run the app, and it throws **Error**: The pod "Firebase/Analytics," required by the plugin "firebase_analytics" requires a higher minimum iOS deployment version than the plugin's reported minimum version.

### Firebase Core version

3.2.0

### Flutter Version

3.22.1

### Relevant Log Output

```shell
[!] CocoaPods could not find compatible versions for pod "Firebase/Analytics":
      In snapshot (Podfile.lock):
        Firebase/Analytics (= 10.27.0)

      In Podfile:
        Firebase/Analytics

        firebase_analytics (from `.symlinks/plugins/firebase_analytics/ios`) was resolved to 11.0.0, which depends on
          Firebase/Analytics (= 10.28.0)

    Specs satisfying the `Firebase/Analytics, Firebase/Analytics (= 10.27.0), Firebase/Analytics (= 10.28.0)` dependency were found, but they required a higher minimum deployment target.



Error: The pod "Firebase/Analytics," required by the plugin "firebase_analytics" requires a higher minimum iOS deployment version than the plugin's reported minimum version.
To build, remove the plugin "firebase_analytics", or contact the plugin's developers for assistance.
Error running pod install
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by Lyokone** [comment]
Hello @cshanjib, I think you need to remove your Podfile.lock and Pods folder. Then run pod install again.

**Comment by cshanjib** [comment]
@Lyokone I did that already. Cleaned the flutter project, remove the Podfile.lock and regenerated it. Still not working in my case. For now I downgraded the firebase_core version to make it work.
