### ISSUE TITLE
🐛 [firebase_crashylitics] Pure Dart crashylitics API

### ISSUE THREAD

**Issue by lukehutch** [firebase/flutterfire#13126]
## What feature would you like to see?

I want to be able to log server exceptions in Crashylitics. I am running Serverpod (a Dart server). Currently `firebase_crashylitics` depends upon Android/iOS. Can we please get a pure Dart Crashylitics API implementation too?

**Comment by Lyokone** [comment]
Hello, since there is no REST Api for Crashlytics, we wouldn't be able to add a pure dart version. You can add your request to UserVoice here: https://firebase.uservoice.com/forums/948424-general
