### ISSUE TITLE
firebase_auth: error while running `flutterfire configure` to add android support

### ISSUE THREAD

**Issue by andrewgwoodruff** [firebase/flutterfire#13124]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Auth

### Description

Hey all! I'm running `flutterfire configure` to try and add support for Android in my Flutter app. I have created my Flutter app based on the instructions [here](https://docs.flutter.dev/get-started/test-drive?tab=vscode), and then I started following the instructions [here](https://firebase.google.com/docs/flutter/setup?platform=android) to add firebase to my Flutter app. When I get to the step of running `flutterfire configure`, I get an error any time it reaches the `Registering new Firebase android app on Firebase project` step. As a sanity check, I tried running `flutterfire configure` and only selecting `ios` and `web` as the supported platforms, and it successfully ran. But anytime I try to add support for Android, I get this error:

```
FirebaseCommandException: An error occured on the Firebase CLI when attempting to run a command.
COMMAND: firebase apps:create android threepio (android) --package-name=com.deck-star.this-is-the-swuiz --json --project=this-is-the-swuiz 
ERROR: Failed to create Android app for project this-is-the-swuiz. See firebase-debug.log for more info.
```

When I check the `firebase-debug.log` file for further details, this is what I see:

```
[debug] [2024-07-30T17:48:08.672Z] ----------------------------------------------------------------------
[debug] [2024-07-30T17:48:08.676Z] Command:       /usr/local/Cellar/node/21.7.1/bin/node /usr/local/bin/firebase apps:create android threepio (android) --package-name=com.deck-star.this-is-the-swuiz --json --project=this-is-the-swuiz
[debug] [2024-07-30T17:48:08.676Z] CLI Version:   13.14.2
[debug] [2024-07-30T17:48:08.676Z] Platform:      darwin
[debug] [2024-07-30T17:48:08.676Z] Node Version:  v21.7.1
[debug] [2024-07-30T17:48:08.677Z] Time:          Tue Jul 30 2024 11:48:08 GMT-0600 (Mountain Daylight Time)
[debug] [2024-07-30T17:48:08.677Z] ----------------------------------------------------------------------
[debug] 
[debug] [2024-07-30T17:48:08.731Z] Object "" in "firebase.json" has unknown property: {"additionalProperty":"flutter"}
[debug] [2024-07-30T17:48:08.736Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2024-07-30T17:48:08.736Z] > authorizing via signed-in user (andrewgwoodruff@gmail.com)
[info] Create your ANDROID app in project this-is-the-swuiz:
[debug] [2024-07-30T17:48:08.740Z] >>> [apiv2][query] POST https://firebase.googleapis.com/v1beta1/projects/this-is-the-swuiz/androidApps [none]
[debug] [2024-07-30T17:48:08.740Z] >>> [apiv2][body] POST https://firebase.googleapis.com/v1beta1/projects/this-is-the-swuiz/androidApps {"displayName":"threepio (android)","packageName":"com.deck-star.this-is-the-swuiz"}
[debug] [2024-07-30T17:48:09.942Z] <<< [apiv2][status] POST https://firebase.googleapis.com/v1beta1/projects/this-is-the-swuiz/androidApps 400
[debug] [2024-07-30T17:48:09.942Z] <<< [apiv2][body] POST https://firebase.googleapis.com/v1beta1/projects/this-is-the-swuiz/androidApps {"error":{"code":400,"message":"Request contains an invalid argument.","status":"INVALID_ARGUMENT"}}
[debug] [2024-07-30T17:48:09.943Z] HTTP Error: 400, Request contains an invalid argument.
[debug] [2024-07-30T17:48:10.517Z] FirebaseError: HTTP Error: 400, Request contains an invalid argument.
    at responseToError (/usr/local/lib/node_modules/firebase-tools/lib/responseToError.js:49:12)
    at RetryOperation._fn (/usr/local/lib/node_modules/firebase-tools/lib/apiv2.js:305:77)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[error] 
[error] Error: Failed to create Android app for project this-is-the-swuiz. See firebase-debug.log for more info.
```

I've tried nuking everything and recreating the Flutter app and running `flutterfire configure` again, but get the same `INVALID_ARGUMENT` error every time.

Any ideas what might be up?

### Reproducing the issue

Follow the instructions [here](https://docs.flutter.dev/get-started/test-drive?tab=vscode) to create an empty app, and then follow the instructions [here](https://firebase.google.com/docs/flutter/setup?platform=android). On the step where you run `flutterfire configure`, you should only select `android`, `ios`, and `web` as the platforms you want to support. Curious if other people are seeing the same error as me (you'll need to go and check your firebase-debug.log file to confirm.

### Firebase Core version

uncertain

### Flutter Version

3.22.3

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by SelaseKay** [comment]
Hi @andrewgwoodruff. This issue is most likely related to the format of your package name(`com.deck-star.this-is-the-swuiz`) for Android. Kindly replace the hyphens(`-`) with an underscore(`_`) and try again.

**Comment by andrewgwoodruff** [comment]
@SelaseKay Thank you so much!! That was the problem, and I've confirmed that it's working now, so I'm closing this issue. Thank you again!

**Comment by nmeri17** [comment]
> Hi @andrewgwoodruff. This issue is most likely related to the format of your package name(`com.deck-star.this-is-the-swuiz`) for Android. Kindly replace the hyphens(`-`) with underscores(`_`) and try again.
> 
> `com.deck-star.this-is-the-swuiz` should be `com.deck_star.this_is_the_swuiz` instead.

How do I replace them when I didn't even type any bundle name? Typing there doesn't take or indicate that it's taking my input. I suppose it's being detected from gradle or AndroidManifest. Besides, my bundle name includes no special characters
