### ISSUE TITLE
Firebase Auth 5.1.2 - Anon to Normal User

### ISSUE THREAD

**Issue by Tr736** [firebase/flutterfire#13123]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Auth

### Description

Im currently crashing when trying to link an anon user to a normal user after they add their email address.

STR
User must be Anon
get email string
createLoginLinkFromOobCode
final _credential = EmailAuthProvider.credentialWithLink(email: email.trim(), emailLink: link.toString());
await _auth.currentUser?.linkWithCredential(_credential);

What happening
Simulator closes the app without error
Device closes the app with the following error

`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]'
*** First throw call stack:
(0x19ba76678 0x193d27c80 0x19b9e01bc 0x19b9dfae0 0x10695b398 0x106944df4 0x1069432d4 0x106940928 0x10697fe18 0x10697dda4 0x106970a24 0x106954598 0x109448f50 0x10944ab34 0x10945298c 0x10945375c 0x1094527c4 0x109453728 0x1094605f8 0x10945fc2c 0x205a83964 0x205a83a04)
libc++abi: terminating due to uncaught exception of type NSException`

If it helps for some reason the _credential type is set to `password` rather then expected `OOB`

### Reproducing the issue

see above

### Firebase Core version

^3.2.0

### Flutter Version

3.22.x

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by Tr736** [comment]
This also happens with signInwithLink

**Comment by Lyokone** [comment]
Hello, can you provide a full sample so I can reproduce? I'm not sure what `createLoginLinkFromOobCode` refers to?
