### ISSUE TITLE
[cloud_firestore]: 5.2.0 wont compile on windows

### ISSUE THREAD

**Issue by cyberpwnn** [firebase/flutterfire#13134]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which platforms are affected?

Windows

### Description

```
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.0
  firebase_storage: ^12.1.2
  firebase_auth: ^5.1.3
  firebase_analytics: ^11.2.1
  firebase_crashlytics: ^4.0.4
  cloud_functions: ^5.0.4
```

```
Launching lib\main.dart on Windows in debug mode...
Building Windows application...
Nuget is not installed.
Attempting to download nuget.
CMake Deprecation Warning at C:/Users/cyberpwn/Documents/development/workspace/Crucible/applications/crucible/build/windows/x64/extracted/firebase_cpp_sdk_windows/CMakeLists.txt:17 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


C:\Users\cyberpwn\Documents\development\workspace\Crucible\applications\crucible\windows\flutter\ephemeral\.plugin_symlinks\cloud_firestore\windows\cloud_firestore_plugin.cpp(1576,40): error C2248: 'cloud_firestore_windows::PigeonDocumentSnapshot::ToEncodableList': cannot access private member declared in class 'cloud_firestore_windows::PigeonDocumentSnapshot' [C:\Users\cyberpwn\Documents\development\workspace\Crucible\applications\crucible\build\windows\x64\plugins\cloud_firestore\cloud_firestore_plugin.vcxproj]
C:\Users\cyberpwn\Documents\development\workspace\Crucible\applications\crucible\windows\flutter\ephemeral\.plugin_symlinks\cloud_firestore\windows\cloud_firestore_plugin.cpp(1585,24): error C2248: 'cloud_firestore_windows::PigeonDocumentChange::ToEncodableList': cannot access private member declared in class 'cloud_firestore_windows::PigeonDocumentChange' [C:\Users\cyberpwn\Documents\development\workspace\Crucible\applications\crucible\build\windows\x64\plugins\cloud_firestore\cloud_firestore_plugin.vcxproj]
C:\Users\cyberpwn\Documents\development\workspace\Crucible\applications\crucible\windows\flutter\ephemeral\.plugin_symlinks\cloud_firestore\windows\cloud_firestore_plugin.cpp(1591,60): error C2248: 'cloud_firestore_windows::PigeonSnapshotMetadata::ToEncodableList': cannot access private member declared in class 'cloud_firestore_windows::PigeonSnapshotMetadata' [C:\Users\cyberpwn\Documents\development\workspace\Crucible\applications\crucible\build\windows\x64\plugins\cloud_firestore\cloud_firestore_plugin.vcxproj]
C:\Users\cyberpwn\Documents\development\workspace\Crucible\applications\crucible\windows\flutter\ephemeral\.plugin_symlinks\cloud_firestore\windows\cloud_firestore_plugin.cpp(1683,22): error C2248: 'cloud_firestore_windows::PigeonDocumentSnapshot::ToEncodableList': cannot access private member declared in class 'cloud_firestore_windows::PigeonDocumentSnapshot' [C:\Users\cyberpwn\Documents\development\workspace\Crucible\applications\crucible\build\windows\x64\plugins\cloud_firestore\cloud_firestore_plugin.vcxproj]
C:\Users\cyberpwn\Documents\development\workspace\Crucible\applications\crucible\windows\flutter\ephemeral\.plugin_symlinks\cloud_firestore\windows\messages.g.cpp(2293,1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [C:\Users\cyberpwn\Documents\development\workspace\Crucible\applications\crucible\build\windows\x64\plugins\cloud_firestore\cloud_firestore_plugin.vcxproj]
C:\Users\cyberpwn\Documents\development\workspace\Crucible\applications\crucible\windows\flutter\ephemeral\.plugin_symlinks\cloud_firestore\windows\messages.g.cpp(2293,56): error C2143: syntax error: missing ';' before '&' [C:\Users\cyberpwn\Documents\development\workspace\Crucible\applications\crucible\build\windows\x64\plugins\cloud_firestore\cloud_firestore_plugin.vcxproj]
C:\Users\cyberpwn\Documents\development\workspace\Crucible\applications\crucible\windows\flutter\ephemeral\.plugin_symlinks\cloud_firestore\windows\messages.g.cpp(2293,58): error C2065: 'request_arg': undeclared identifier [C:\Users\cyberpwn\Documents\development\workspace\Crucible\applications\crucible\build\windows\x64\plugins\cloud_firestore\cloud_firestore_plugin.vcxproj]
C:\Users\cyberpwn\Documents\development\workspace\Crucible\applications\crucible\windows\flutter\ephemeral\.plugin_symlinks\cloud_firestore\windows\messages.g.cpp(2295,23): error C2146: syntax error: missing ';' before identifier 'encodable_request_arg' [C:\Users\cyberpwn\Documents\development\workspace\Crucible\applications\crucible\build\windows\x64\plugins\cloud_firestore\cloud_firestore_plugin.vcxproj]
C:\Users\cyberpwn\Documents\development\workspace\Crucible\applications\crucible\windows\flutter\ephemeral\.plugin_symlinks\cloud_firestore\windows\messages.g.cpp(2297,28): error C2065: 'request_arg': undeclared identifier [C:\Users\cyberpwn\Documents\development\workspace\Crucible\applications\crucible\build\windows\x64\plugins\cloud_firestore\cloud_firestore_plugin.vcxproj]
Error: Build process failed.
```

### Reproducing the issue

Remember google io years ago? Yeah do what they did. Try to actually use firestore on windows.

### Firebase Core version

3.3.0

### Flutter Version

3.22.3

### Relevant Log Output

```shell
Launching lib\main.dart on Windows in debug mode...
Building Windows application...
Nuget is not installed.
Attempting to download nuget.
CMake Deprecation Warning at C:/Users/cyberpwn/Documents/development/workspace/Crucible/applications/crucible/build/windows/x64/extracted/firebase_cpp_sdk_windows/CMakeLists.txt:17 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


C:\Users\cyberpwn\Documents\development\workspace\Crucible\applications\crucible\windows\flutter\ephemeral\.plugin_symlinks\cloud_firestore\windows\cloud_firestore_plugin.cpp(1576,40): error C2248: 'cloud_firestore_windows::PigeonDocumentSnapshot::ToEncodableList': cannot access private member declared in class 'cloud_firestore_windows::PigeonDocumentSnapshot' [C:\Users\cyberpwn\Documents\development\workspace\Crucible\applications\crucible\build\windows\x64\plugins\cloud_firestore\cloud_firestore_plugin.vcxproj]
C:\Users\cyberpwn\Documents\development\workspace\Crucible\applications\crucible\windows\flutter\ephemeral\.plugin_symlinks\cloud_firestore\windows\cloud_firestore_plugin.cpp(1585,24): error C2248: 'cloud_firestore_windows::PigeonDocumentChange::ToEncodableList': cannot access private member declared in class 'cloud_firestore_windows::PigeonDocumentChange' [C:\Users\cyberpwn\Documents\development\workspace\Crucible\applications\crucible\build\windows\x64\plugins\cloud_firestore\cloud_firestore_plugin.vcxproj]
C:\Users\cyberpwn\Documents\development\workspace\Crucible\applications\crucible\windows\flutter\ephemeral\.plugin_symlinks\cloud_firestore\windows\cloud_firestore_plugin.cpp(1591,60): error C2248: 'cloud_firestore_windows::PigeonSnapshotMetadata::ToEncodableList': cannot access private member declared in class 'cloud_firestore_windows::PigeonSnapshotMetadata' [C:\Users\cyberpwn\Documents\development\workspace\Crucible\applications\crucible\build\windows\x64\plugins\cloud_firestore\cloud_firestore_plugin.vcxproj]
C:\Users\cyberpwn\Documents\development\workspace\Crucible\applications\crucible\windows\flutter\ephemeral\.plugin_symlinks\cloud_firestore\windows\cloud_firestore_plugin.cpp(1683,22): error C2248: 'cloud_firestore_windows::PigeonDocumentSnapshot::ToEncodableList': cannot access private member declared in class 'cloud_firestore_windows::PigeonDocumentSnapshot' [C:\Users\cyberpwn\Documents\development\workspace\Crucible\applications\crucible\build\windows\x64\plugins\cloud_firestore\cloud_firestore_plugin.vcxproj]
C:\Users\cyberpwn\Documents\development\workspace\Crucible\applications\crucible\windows\flutter\ephemeral\.plugin_symlinks\cloud_firestore\windows\messages.g.cpp(2293,1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [C:\Users\cyberpwn\Documents\development\workspace\Crucible\applications\crucible\build\windows\x64\plugins\cloud_firestore\cloud_firestore_plugin.vcxproj]
C:\Users\cyberpwn\Documents\development\workspace\Crucible\applications\crucible\windows\flutter\ephemeral\.plugin_symlinks\cloud_firestore\windows\messages.g.cpp(2293,56): error C2143: syntax error: missing ';' before '&' [C:\Users\cyberpwn\Documents\development\workspace\Crucible\applications\crucible\build\windows\x64\plugins\cloud_firestore\cloud_firestore_plugin.vcxproj]
C:\Users\cyberpwn\Documents\development\workspace\Crucible\applications\crucible\windows\flutter\ephemeral\.plugin_symlinks\cloud_firestore\windows\messages.g.cpp(2293,58): error C2065: 'request_arg': undeclared identifier [C:\Users\cyberpwn\Documents\development\workspace\Crucible\applications\crucible\build\windows\x64\plugins\cloud_firestore\cloud_firestore_plugin.vcxproj]
C:\Users\cyberpwn\Documents\development\workspace\Crucible\applications\crucible\windows\flutter\ephemeral\.plugin_symlinks\cloud_firestore\windows\messages.g.cpp(2295,23): error C2146: syntax error: missing ';' before identifier 'encodable_request_arg' [C:\Users\cyberpwn\Documents\development\workspace\Crucible\applications\crucible\build\windows\x64\plugins\cloud_firestore\cloud_firestore_plugin.vcxproj]
C:\Users\cyberpwn\Documents\development\workspace\Crucible\applications\crucible\windows\flutter\ephemeral\.plugin_symlinks\cloud_firestore\windows\messages.g.cpp(2297,28): error C2065: 'request_arg': undeclared identifier [C:\Users\cyberpwn\Documents\development\workspace\Crucible\applications\crucible\build\windows\x64\plugins\cloud_firestore\cloud_firestore_plugin.vcxproj]
Error: Build process failed.
```

### Flutter dependencies

This is a build error specifically about cloud firestore messages & the firestore plugin

### Additional context and comments

It's been years. Do you guys support firestore or firebase at all on windows or not? It seems like every version either fails to build or is extremely crashy on windows. It's a painful developer experience, and I feel like every time something like this is submitted its just kicked down the road until the automated bot closes the issue.

**Comment by isra-khan** [comment]
I am also facing this issue

**Comment by rayliverified** [comment]
Can reproduce.
Existing projects that have not run `pub upgrade` still work. A new project or running `pub upgrade` fails.

**Comment by Lyokone** [comment]
Hello, I'll have a look, you can lock `cloud_firestore: 5.1.0` in the mean time.

**Comment by venky9885** [comment]
Same issue solve it please

**Comment by PythonFlutterUser** [comment]
Same issue here

**Comment by ciceromsjr** [comment]
Unfortunately, even in cloud_store 5.1.0 it can't compile anymore =( 
I've clean the build folder, ran flutter clean, etc.
Nothing worked.

**Comment by Donzo24** [comment]
Same error with 5.1.0, unable to compile

**Comment by venky9885** [comment]
yes 5.1.0 is also having same issue

**Comment by cyberpwnn** [comment]
While I was able to get 5.1.0 working, as mentioned previously, I'd like the builds going forward to be less unusable seemingly randomly. I see that the PRs have automated testing & checks, what are you checking? What's the point of testing & checking if builds like 5.2.0 can still get through?

**Comment by NextdoorPsycho** [comment]
> While I was able to get 5.1.0 working, as mentioned previously, I'd like the builds going forward to be less unusable seemingly randomly. I see that the PRs have automated testing & checks, what are you checking? What's the point of testing & checking if builds like 5.2.0 can still get through?

im crying... lmao

**Comment by mortezaom** [comment]
@cyberpwnn 5.1.0 is not working for me, is there any other configuration that you have done?

**Comment by shtse8** [comment]
I have the same issue after upgrading.

**Comment by cyberpwnn** [comment]
> @cyberpwnn 5.1.0 is not working for me, is there any other configuration that you have done?
> 
> Edit: add firestore like this `cloud_firestore: 5.1.0` then remove pubspec.lock and run `flutter pub get`

Yeah, and for anyone else use

```yaml
cloud_firestore: 5.1.0 # Dont use the carat ^ symbol
```

then run `flutter pub get` and it will downgrade the pubspec lock to 5.1.0

**Comment by jameshayek** [comment]
**Description:**

I'm encountering a build error when attempting to integrate the cloud_firestore plugin in my Flutter project on the Windows platform. The error occurs during the build process and appears to be related to the generated C++ code for the plugin.

**Environment:**

- Flutter Version: 3.4.3
- Dart SDK Version: 2.19.2
- cloud_firestore Version: 5.2.0 (also tried 5.1.0)
- firebase_core Version: 3.2.0
- Operating System: Windows 10 (Version 10.0.22631.3880)
- CMake Version: 3.30.2

**Error Message:**

```
C:\Users\James\Programming\Flutter\FirstFlutterApp\frequency_details_app\frequency_details_app\windows\flutter\ephemeral\.plugin_symlinks\cloud_firestore\windows\messages.g.cpp(2295,23): error C2146: syntax error: missing ';' before identifier 'encodable_request_arg' [C:\Users\James\Programming\Flutter\FirstFlutterApp\frequency_details_app\frequency_details_app\build\windows\x64\plugins\cloud_firestore\cloud_firestore_plugin.vcxproj]
C:\Users\James\Programming\Flutter\FirstFlutterApp\frequency_details_app\frequency_details_app\windows\flutter\ephemeral\.plugin_symlinks\cloud_firestore\windows\messages.g.cpp(2297,28): error C2065: 'request_arg': undeclared identifier [C:\Users\James\Programming\Flutter\FirstFlutterApp\frequency_details_app\frequency_details_app\build\windows\x64\plugins\cloud_firestore\cloud_firestore_plugin.vcxproj]
Error: Build process failed.
```

I also receive numerous warnings like:

`firebase_firestore.lib(7ba01613985f32fe50e0c125a0414f54_firebase_firestore.dir_Debug_aggregate_query_main.obj) : warning LNK4099: PDB '' was not found with 'firebase_firestore.lib(7ba01613985f32fe50e0c125a0414f54_firebase_firestore.dir_Debug_aggregate_query_main.obj)' or at ''; linking object as if no debug info [C:\Users\James\Programming\Flutter\FirstFlutterApp\frequency_details_app\frequency_details_app\build\windows\x64\runner\frequency_details_app.vcxproj]`

**Steps Taken:**

- Verified that cmake is correctly installed and updated to version 3.30.2.
- Updated Visual Studio 2022 with all necessary components, including Desktop development with C++ and Universal Windows Platform (UWP) development.
- Cleaned and rebuilt the project using flutter clean and flutter pub get.
- Attempted to use various versions of cloud_firestore, including 3.1.10 and 5.2.0, to resolve dependency conflicts with firebase_core.
- Removed the caret symbol (^) from the cloud_firestore version to ensure exact versioning.

**pubspec.yaml:**

```
name: frequency_details_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 3.2.0
  firebase_auth: ^5.1.2
  in_app_purchase: ^3.2.0
  collection: ^1.18.0
  http_parser: ^4.0.2
  material_color_utilities: ^0.8.0
  meta: ^1.12.0
  provider: ^6.1.2
  cloud_firestore: 5.2.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  leak_tracker: ^10.0.4
  leak_tracker_flutter_testing: ^3.0.3
  test_api: ^0.7.0
  vm_service: ^14.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/FrequencyDB.json
```
**Questions:**

- Why am I encountering this syntax error and missing identifier issue with the cloud_firestore plugin on Windows?
- How can I resolve these issues to successfully build my Flutter project on the Windows platform?
- Are there specific configurations or workarounds that I need to apply for compatibility with cloud_firestore on Windows?

Any help or guidance would be greatly appreciated.

**Comment by Lyokone** [comment]
We are going to release https://github.com/firebase/flutterfire/pull/13135 today that will fix this issue

**Comment by appliedrd** [comment]
thank you

**Comment by Lyokone** [comment]
The fix has been released as part of 
```
cloud_firestore: ^5.2.1
```

**Comment by ronhanic** [comment]
Windows 11
firebase_core: ^3.3.0
cloud_firestore: ^5.2.1

I have import statements and only this code

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:firebase_windows/firebase_windows.dart';

import 'package:get/get.dart';


import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void login(String email, password)  async{
    try {

      FirebaseAuth? auth;

    } catch (firebaseAuthException) {}
  }


When i build the flutter app you can see the error compiling below with the 5.2.1 library.

Any idea? Thanks for your help

I opened the windows solution and it shows that the User user should be a User *user
is there something that i should do with 5.2.1 to make this work.


C:\Users\ronha\Documents\Data\flutter\600watts\34\protrainr\windows\flutter\ephemeral\.plugin_symlinks\firebase_auth\windows\firebase_auth_plugin.cpp(1266,12): error C2039: 'SendEmailVerificationBeforeUpdatingEmail': is not a member of 'firebase::auth::User' [C:\Users\ronha\Documents\Data\flutter\600watts\34\protrainr\build\windows\x64\plugins\firebase_auth\firebase_auth_plugin.vcxproj]
C:\Users\ronha\Documents\Data\flutter\600watts\34\protrainr\windows\flutter\ephemeral\.plugin_symlinks\firebase_windows\windows\firebase_auth_plugin.cpp(150,16): error C2440: 'initializing': cannot convert from 'firebase::auth::User' to 'firebase::auth::User *' [C:\Users\ronha\Documents\Data\flutter\600watts\34\protrainr\build\windows\x64\plugins\firebase_windows\firebase_windows_plugin.vcxproj]
C:\Users\ronha\Documents\Data\flutter\600watts\34\protrainr\windows\flutter\ephemeral\.plugin_symlinks\firebase_windows\windows\firebase_auth_plugin.cpp(188,16): error C2440: 'initializing': cannot convert from 'firebase::auth::User' to 'firebase::auth::User *' [C:\Users\ronha\Documents\Data\flutter\600watts\34\protrainr\build\windows\x64\plugins\firebase_windows\firebase_windows_plugin.vcxproj]
C:\Users\ronha\Documents\Data\flutter\600watts\34\protrainr\windows\flutter\ephemeral\.plugin_symlinks\firebase_windows\windows\firebase_auth_plugin.cpp(302,14): error C2440: 'initializing': cannot convert from 'firebase::auth::User' to 'firebase::auth::User *' [C:\Users\ronha\Documents\Data\flutter\600watts\34\protrainr\build\windows\x64\plugins\firebase_windows\firebase_windows_plugin.vcxproj]
C:\Users\ronha\Documents\Data\flutter\600watts\34\protrainr\windows\flutter\ephemeral\.plugin_symlinks\firebase_windows\windows\firebase_auth_plugin.cpp(467,24): error C2440: 'initializing': cannot convert from 'firebase::Future<firebase::auth::User>' to 'firebase::Future<firebase::auth::User *>' [C:\Users\ronha\Documents\Data\flutter\600watts\34\protrainr\build\windows\x64\plugins\firebase_windows\firebase_windows_plugin.vcxproj]
C:\Users\ronha\Documents\Data\flutter\600watts\34\protrainr\windows\flutter\ephemeral\.plugin_symlinks\firebase_windows\windows\firebase_auth_plugin.cpp(506,24): error C2440: 'initializing': cannot convert from 'firebase::Future<firebase::auth::AuthResult>' to 'firebase::Future<firebase::auth::User *>' [C:\Users\ronha\Documents\Data\flutter\600watts\34\protrainr\build\windows\x64\plugins\firebase_windows\firebase_windows_plugin.vcxproj]
C:\Users\ronha\Documents\Data\flutter\600watts\34\protrainr\windows\flutter\ephemeral\.plugin_symlinks\firebase_windows\windows\firebase_auth_plugin.cpp(547,24): error C2440: 'initializing': cannot convert from 'firebase::Future<firebase::auth::AuthResult>' to 'firebase::Future<firebase::auth::User *>' [C:\Users\ronha\Documents\Data\flutter\600watts\34\protrainr\build\windows\x64\plugins\firebase_windows\firebase_windows_plugin.vcxproj]
C:\Users\ronha\Documents\Data\flutter\600watts\34\protrainr\windows\flutter\ephemeral\.plugin_symlinks\firebase_windows\windows\firebase_auth_plugin.cpp(601,50): error C2819: type 'firebase::auth::User' does not have an overloaded member 'operator ->' [C:\Users\ronha\Documents\Data\flutter\600watts\34\protrainr\build\windows\x64\plugins\firebase_windows\firebase_windows_plugin.vcxproj]
C:\Users\ronha\Documents\Data\flutter\600watts\34\protrainr\windows\flutter\ephemeral\.plugin_symlinks\firebase_windows\windows\firebase_auth_plugin.cpp(601,52): error C2232: '->firebase::auth::User::GetToken': left operand has 'class' type, use '.' [C:\Users\ronha\Documents\Data\flutter\600watts\34\protrainr\build\windows\x64\plugins\firebase_windows\firebase_windows_plugin.vcxproj]
Error: Build process failed.

**Comment by cyberpwnn** [comment]
Thats great it compiles again, but the reason I wanted it to compile was so I could use it on flutter windows. It kind of just crashes whenever I try to use it. `Lost connection to device.`
