### ISSUE TITLE
[app_check] Fails with 403 during "In Review" stage of Google Play Console.

### ISSUE THREAD

**Issue by codyfilatov** [firebase/flutterfire#13137]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

App Check

### Which platforms are affected?

Android

### Description

AppCheck enforced with Firebase Authentication when release build submitted to an Internal track that does not require Play Console review... Then downloaded from the Play Store on a genuine device WORKS. Everything is good. Furthermore on debug build using debug tokens everything WORKS. Great.

However, when submitted to a Closed track on GooglePlay Console for "In Review" the automated bot is clearly receiving an error that it can not pass AppCheck Authentication enforcement. It's failing to be logged in anonymously. Meaning it is not downloaded from the Play Store, and therefore receives the 403 and fails.

Am I suppose to just disable AppCheck enforcement while I have a build In-Review?

### Reproducing the issue

- Implement App Check as described by documentation
- Upload aab for any track that requires a review in Google Play Console.
- AppCheck completely fails every interaction in release build.
- Works fine when downloaded from the Play Store as release build on an Internal track (that does not require review).

### Firebase Core version

3.3.1

### Flutter Version

3.19.0

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by Lyokone** [comment]
Hello @codyfilatov, I'm assuming that AppCheck being triggered by an automated bot is the expected behavior. Since it doesn't seem to be an implementation detail from FlutterFire, I would suggest asking on the Android SDK repository which may have more information about the specifics of Play Store: https://github.com/firebase/firebase-android-sdk
