### ISSUE TITLE
[firebase_auth]: Recaptcha unimplemented error in windows platform

### ISSUE THREAD

**Issue by venky9885** [firebase/flutterfire#13143]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Auth

### Which platforms are affected?

Windows

### Description

For recaptcha unimplemented error is thrown

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: UnimplementedError: RecaptchaVerifier is not implemented
#0      RecaptchaVerifierFactoryPlatform.instance (package:firebase_auth_platform_interface/src/platform_interface/platform_interface_recaptcha_verifier_factory.dart:55:7)
#1      RecaptchaVerifier._factory (package:firebase_auth/src/recaptcha_verifier.dart:12:40)
#2      RecaptchaVerifier._factory (package:firebase_auth/src/recaptcha_verifier.dart)
#3      new RecaptchaVerifier (package:firebase_auth/src/recaptcha_verifier.dart:58:7)
#4      FirebaseAuth.signInWithPhoneNumber (package:firebase_auth/src/firebase_auth.dart:676:18)
#5      Auth.login (package:soft_desk/Auth/phoneAuth.dart:15:23)
#6      _AuthPhoneState.build.<anonymous closure> (package:soft_desk/Auth/authscreen.dart:141:36)
#7      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1170:21)
#8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:344:24)
#9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:652:11)
#10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:309:5)
#11     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:242:7)
#12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:696:9)
#13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#14     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#16     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:495:19)
#19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:475:22)
#20     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:450:11)
#21     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:420:7)
#22     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:383:5)
#23     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:330:7)
#24     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:299:9)
#25     _invoke1 (dart:ui/hooks.dart:328:13)
#26     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:442:7)
#27     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)

### Reproducing the issue

Create flutter project and add firebase auth for phone otp authentication

Then try to sign in

### Firebase Core version

3.3.0

### Flutter Version

3.23.0-0.1.pre

### Relevant Log Output

```shell
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: UnimplementedError: RecaptchaVerifier is not implemented
#0      RecaptchaVerifierFactoryPlatform.instance (package:firebase_auth_platform_interface/src/platform_interface/platform_interface_recaptcha_verifier_factory.dart:55:7)
#1      RecaptchaVerifier._factory (package:firebase_auth/src/recaptcha_verifier.dart:12:40)
#2      RecaptchaVerifier._factory (package:firebase_auth/src/recaptcha_verifier.dart)
#3      new RecaptchaVerifier (package:firebase_auth/src/recaptcha_verifier.dart:58:7)
#4      FirebaseAuth.signInWithPhoneNumber (package:firebase_auth/src/firebase_auth.dart:676:18)
#5      Auth.login (package:soft_desk/Auth/phoneAuth.dart:15:23)
#6      _AuthPhoneState.build.<anonymous closure> (package:soft_desk/Auth/authscreen.dart:141:36)
#7      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1170:21)
#8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:344:24)
#9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:652:11)
#10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:309:5)
#11     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:242:7)
#12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:696:9)
#13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#14     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#16     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:495:19)
#19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:475:22)
#20     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:450:11)
#21     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:420:7)
#22     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:383:5)
#23     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:330:7)
#24     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:299:9)
#25     _invoke1 (dart:ui/hooks.dart:328:13)
#26     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:442:7)
#27     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by Lyokone** [comment]
Hello @venky9885, as described in the documentation
```
  /// This method is only available on web based platforms.
```
