### ISSUE TITLE
 FirebaseMessaging.onBackgroundMessage stoped after some time in ios release build,it is working properly in debug build

### ISSUE THREAD

**Issue by nafih07** [firebase/flutterfire#13146]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you aware of the differences between iOS and Android background message handling?

- [X] I understand that iOS and Android background messages behave differently, and I've designed my application with that in mind.

### Do you have an active Apple Developer account?

- [X] I have an active Apple Developer account.

### Are you using a physical iOS device to test background messages?

- [X] I am using a physical iOS device to test background messages.

### Have you enabled "Remote Notifications" & "Background Mode" (Checking options for "Background Processing" & "Remote Notifications") in your app's Xcode project?

![Screenshot 2024-08-05 at 12 58 48 AM](https://github.com/user-attachments/assets/8a0e542a-f1ac-49b5-8aaf-cc90fe7303a9)

### Have you created an APNs key in your Apple Developer account & uploaded this APNs key to your Firebase console?

<img width="932" alt="Screenshot 2024-08-05 at 1 00 17 AM" src="https://github.com/user-attachments/assets/2c831fae-9a7b-4d5d-9c54-e33edaf0657b">

### Have you disabled method swizzling for Firebase in your app?

<key>FirebaseAppDelegateProxyEnabled</key>
	<false/>
    <key>FirebaseMessagingAutoInitEnabled</key>
    <false/>
<key>UIBackgroundModes</key>
	<array>
		<string>audio</string>
		<string>fetch</string>
		<string>remote-notification</string>
		<string>voip</string>
</array>

### Are you sending messages to your app from the Firebase Admin SDK?

{
    "to":"eZmJ2Gxbc0K2uMveUIeDMN:APA91bFngvh8zXa1-Vrl3jyHIRGKKfcNnkMub5tlbjcfyhPQXdOt5Gj7WWaLLGu-pzEzC8dDMS3KXNq4kc0dphqb3V20KuyT4DW9pBh-FiM5gPtOP3XxmV_GT3kQ1Pi7QfKFfGaCMNGR",

    "priority": "high",
  "content_available": true,
  "mutable-content":1,
  "notification":{
    "title":"title ",
    "message":"Message",
  },
    "data": {
        "action":"callStarted",
        "id":"epyxEDWbSL6cHpT7v2D7ke",
        "body": "Cek Pesan Klik Notif",
        "title": "Ada Pesan Baru",
        
        "priority": "high"
    }
}

### Have you requested permission from the user to receive notifications?

- [X] I have the relevant permission to receive notifications.

### Have you used the 'Console' application on your macOS device to check if the iOS device's system is throttling your background messages?

default	01:51:42.675005+0530	locationd	{"msg":"#CLIUA Marking change", "clientKey":"icom.ministryofhelpers.app.moh:", "reason":"Decaying in-use status from process state", "assertionLevel":3, "coming":0}
default	01:51:42.675450+0530	locationd	{"msg":"#CLIUA updating AssertionRecord", "ClientKey":"icom.ministryofhelpers.app.moh:", "AssertionLevel":{"type":"decode failure","raw value":3,"expected type":"Generic"}}
default	01:51:42.675913+0530	locationd	{"msg":"#CLIUA AssertionRecord updated", "ClientKey":"icom.ministryofhelpers.app.moh:", "AssertionLevel":{"type":"decode failure","raw value":0,"expected type":"Generic"}}
default	01:51:42.676326+0530	locationd	{"msg":"#CLIUA in-use level changed for client", "ClientKey":"icom.ministryofhelpers.app.moh:"}
default	01:51:42.676778+0530	locationd	{"msg":"computing freshAuthorizationContext", "Client":"icom.ministryofhelpers.app.moh:", "ClientDictionary":"{\n    BundleId = \"com.ministryofhelpers.app.moh\";\n    BundlePath = \"\/private\/var\/containers\/Bundle\/Application\/9843594A-C307-4BD7-8AD8-25E60B83A7E8\/Runner.app\";\n    Executable = \"\/private\/var\/containers\/Bundle\/Application\/9843594A-C307-4BD7-8AD8-25E60B83A7E8\/Runner.app\/Runner\";\n    ExistsInLSDatabase = 1;\n    InUseLevel = 0;\n    PluginBundleIds =     (\n    );\n    SuppressShowingInSettings = 1;\n}", "BigSwitch":1, "InUseLevel":{"type":"decode failure","raw value":0,"expected type":"Generic"}}
default	01:51:42.675174+0530	locationd	{"msg":"#CLIUA Marking change", "clientKey":"icom.ministryofhelpers.app.moh:", "reason":"Decaying in-use status from process state", "assertionLevel":3, "coming":0}
default	01:51:42.675652+0530	locationd	{"msg":"#CLIUA updating AssertionRecord", "ClientKey":"icom.ministryofhelpers.app.moh:", "AssertionLevel":{"type":"decode failure","raw value":3,"expected type":"Generic"}}
default	01:51:42.676119+0530	locationd	{"msg":"#CLIUA AssertionRecord updated", "ClientKey":"icom.ministryofhelpers.app.moh:", "AssertionLevel":{"type":"decode failure","raw value":0,"expected type":"Generic"}}
default	01:51:42.676491+0530	locationd	{"msg":"#CLIUA in-use level changed for client", "ClientKey":"icom.ministryofhelpers.app.moh:"}
default	01:51:42.677001+0530	locationd	{"msg":"computing freshAuthorizationContext", "Client":"icom.ministryofhelpers.app.moh:", "ClientDictionary":"{\n    BundleId = \"com.ministryofhelpers.app.moh\";\n    BundlePath = \"\/private\/var\/containers\/Bundle\/Application\/9843594A-C307-4BD7-8AD8-25E60B83A7E8\/Runner.app\";\n    Executable = \"\/private\/var\/containers\/Bundle\/Application\/9843594A-C307-4BD7-8AD8-25E60B83A7E8\/Runner.app\/Runner\";\n    ExistsInLSDatabase = 1;\n    InUseLevel = 0;\n    PluginBundleIds =     (\n    );\n    SuppressShowingInSettings = 1;\n}", "BigSwitch":1, "InUseLevel":{"type":"decode failure","raw value":0,"expected type":"Generic"}}
default	01:51:42.675097+0530	locationd	{"msg":"#CLIUA Marking change", "clientKey":"icom.ministryofhelpers.app.moh:", "reason":"Decaying in-use status from process state", "assertionLevel":3, "coming":0}
default	01:51:42.675534+0530	locationd	{"msg":"#CLIUA updating AssertionRecord", "ClientKey":"icom.ministryofhelpers.app.moh:", "AssertionLevel":{"type":"decode failure","raw value":3,"expected type":"Generic"}}
default	01:51:42.675997+0530	locationd	{"msg":"#CLIUA AssertionRecord updated", "ClientKey":"icom.ministryofhelpers.app.moh:", "AssertionLevel":{"type":"decode failure","raw value":0,"expected type":"Generic"}}
default	01:51:42.676424+0530	locationd	{"msg":"#CLIUA in-use level changed for client", "ClientKey":"icom.ministryofhelpers.app.moh:"}
default	01:51:42.676897+0530	locationd	{"msg":"computing freshAuthorizationContext", "Client":"icom.ministryofhelpers.app.moh:", "ClientDictionary":"{\n    BundleId = \"com.ministryofhelpers.app.moh\";\n    BundlePath = \"\/private\/var\/containers\/Bundle\/Application\/9843594A-C307-4BD7-8AD8-25E60B83A7E8\/Runner.app\";\n    Executable = \"\/private\/var\/containers\/Bundle\/Application\/9843594A-C307-4BD7-8AD8-25E60B83A7E8\/Runner.app\/Runner\";\n    ExistsInLSDatabase = 1;\n    InUseLevel = 0;\n    PluginBundleIds =     (\n    );\n    SuppressShowingInSettings = 1;\n}", "BigSwitch":1, "InUseLevel":{"type":"decode failure","raw value":0,"expected type":"Generic"}}
default	01:51:50.608165+0530	SpringBoard	Received incoming message on topic com.ministryofhelpers.app.moh at priority 10
default	01:51:50.608114+0530	SpringBoard	Received incoming message on topic com.ministryofhelpers.app.moh at priority 10
default	01:51:50.608058+0530	SpringBoard	Received incoming message on topic com.ministryofhelpers.app.moh at priority 10
default	01:51:50.643655+0530	SpringBoard	[com.ministryofhelpers.app.moh] Received remote notification request 9762-0FC8 [ waking: 0, hasAlertContent: 1, hasSound: 0 hasBadge: 0 hasContentAvailable: 1 hasMutableContent: 0 pushType: Alert]
default	01:51:50.643704+0530	SpringBoard	[com.ministryofhelpers.app.moh] Received remote notification request 9762-0FC8 [ waking: 0, hasAlertContent: 1, hasSound: 0 hasBadge: 0 hasContentAvailable: 1 hasMutableContent: 0 pushType: Alert]
default	01:51:50.644045+0530	SpringBoard	[com.ministryofhelpers.app.moh] Process delivery of push notification 9762-0FC8
default	01:51:50.644093+0530	SpringBoard	[com.ministryofhelpers.app.moh] Process delivery of push notification 9762-0FC8
default	01:51:50.644311+0530	SpringBoard	[com.ministryofhelpers.app.moh] Request DUET delivers content-available push notification to application
default	01:51:50.644366+0530	SpringBoard	[com.ministryofhelpers.app.moh] Request DUET delivers content-available push notification to application
default	01:51:50.644551+0530	SpringBoard	SUBMITTING: com.apple.pushLaunch.com.ministryofhelpers.app.moh:DA4ED2
default	01:51:50.644596+0530	SpringBoard	SUBMITTING: com.apple.pushLaunch.com.ministryofhelpers.app.moh:DA4ED2
default	01:51:50.645061+0530	dasd	Submitted Activity: com.apple.pushLaunch.com.ministryofhelpers.app.moh:DA4ED2 at priority 10 (Mon Aug  5 01:51:50 2024 - Tue Aug  6 01:51:50 2024)
default	01:51:50.645123+0530	dasd	Submitted Activity: com.apple.pushLaunch.com.ministryofhelpers.app.moh:DA4ED2 at priority 10 (Mon Aug  5 01:51:50 2024 - Tue Aug  6 01:51:50 2024)
default	01:51:50.646013+0530	SpringBoard	[com.ministryofhelpers.app.moh] Badge can be set for notification 9762-0FC8: 0 [ canBadge: 1 badgeNumber: (null) ]
default	01:51:50.646059+0530	SpringBoard	[com.ministryofhelpers.app.moh] Badge can be set for notification 9762-0FC8: 0 [ canBadge: 1 badgeNumber: (null) ]
default	01:51:50.646272+0530	SpringBoard	Getting effectiveSectionInfo for section identifier: com.ministryofhelpers.app.moh
default	01:51:50.646317+0530	SpringBoard	Getting effectiveSectionInfo for section identifier: com.ministryofhelpers.app.moh
default	01:51:50.646845+0530	SpringBoard	[com.ministryofhelpers.app.moh] Getting effective section info
default	01:51:50.646891+0530	SpringBoard	[com.ministryofhelpers.app.moh] Getting effective section info
default	01:51:50.649687+0530	SpringBoard	[com.ministryofhelpers.app.moh] Got effective section info [ hasResult: 1 ]
default	01:51:50.649907+0530	SpringBoard	Getting effectiveSectionInfo for section identifier: com.ministryofhelpers.app.moh
default	01:51:50.650134+0530	SpringBoard	[com.ministryofhelpers.app.moh] Getting effective section info
default	01:51:50.651851+0530	SpringBoard	[com.ministryofhelpers.app.moh] Got effective section info [ hasResult: 1 ]
default	01:51:50.652360+0530	SpringBoard	[com.ministryofhelpers.app.moh] Saving notification 9762-0FC8: YES [ hasAlertContent: YES, shouldPresentAlert: YES settingsShouldSave: YES]
default	01:51:50.654144+0530	SpringBoard	[com.ministryofhelpers.app.moh] Delivered user visible push notification 9762-0FC8
default	01:51:50.655796+0530	SpringBoard	[com.ministryofhelpers.app.moh] Load 0 pending notification dictionaries
default	01:51:50.649733+0530	SpringBoard	[com.ministryofhelpers.app.moh] Got effective section info [ hasResult: 1 ]
default	01:51:50.649950+0530	SpringBoard	Getting effectiveSectionInfo for section identifier: com.ministryofhelpers.app.moh
default	01:51:50.650177+0530	SpringBoard	[com.ministryofhelpers.app.moh] Getting effective section info
default	01:51:50.657283+0530	SpringBoard	[com.ministryofhelpers.app.moh] Adding notification 9762-0FC8 [ hasAlertContent: 1, shouldPresentAlert: 1 hasSound: 0 shouldPlaySound: 1 ]; interruption-level: 1; destinations 398: (
    NotificationCenter,
    LockScreen,
    Alert,
    Spoken,
    Forwarding
)
default	01:51:50.658377+0530	SpringBoard	BBDataProviderProxy com.ministryofhelpers.app.moh has enqueued a bulletin request
default	01:51:50.658631+0530	SpringBoard	BBDataProviderProxy com.ministryofhelpers.app.moh is now sending enqueued bulletin request to BBServer
default	01:51:50.651897+0530	SpringBoard	[com.ministryofhelpers.app.moh] Got effective section info [ hasResult: 1 ]
default	01:51:50.652409+0530	SpringBoard	[com.ministryofhelpers.app.moh] Saving notification 9762-0FC8: YES [ hasAlertContent: YES, shouldPresentAlert: YES settingsShouldSave: YES]
default	01:51:50.654187+0530	SpringBoard	[com.ministryofhelpers.app.moh] Delivered user visible push notification 9762-0FC8
default	01:51:50.655843+0530	SpringBoard	[com.ministryofhelpers.app.moh] Load 0 pending notification dictionaries
default	01:51:50.657342+0530	SpringBoard	[com.ministryofhelpers.app.moh] Adding notification 9762-0FC8 [ hasAlertContent: 1, shouldPresentAlert: 1 hasSound: 0 shouldPlaySound: 1 ]; interruption-level: 1; destinations 398: (
    NotificationCenter,
    LockScreen,
    Alert,
    Spoken,
    Forwarding
)
default	01:51:50.658427+0530	SpringBoard	BBDataProviderProxy com.ministryofhelpers.app.moh has enqueued a bulletin request
default	01:51:50.658674+0530	SpringBoard	BBDataProviderProxy com.ministryofhelpers.app.moh is now sending enqueued bulletin request to BBServer
default	01:51:50.661495+0530	SpringBoard	Publishing bulletin for section <com.ministryofhelpers.app.moh>: subsectionIDs: (null), bulletinID = <9D68262C-FC6B-454E-BF64-8FDF6A660F40>, expiration date = <Mon Aug 12 01:51:50 2024>, expiration events <0>
default	01:51:50.661545+0530	SpringBoard	Publishing bulletin for section <com.ministryofhelpers.app.moh>: subsectionIDs: (null), bulletinID = <9D68262C-FC6B-454E-BF64-8FDF6A660F40>, expiration date = <Mon Aug 12 01:51:50 2024>, expiration events <0>
default	01:51:50.643594+0530	SpringBoard	[com.ministryofhelpers.app.moh] Received remote notification request 9762-0FC8 [ waking: 0, hasAlertContent: 1, hasSound: 0 hasBadge: 0 hasContentAvailable: 1 hasMutableContent: 0 pushType: Alert]
default	01:51:50.643994+0530	SpringBoard	[com.ministryofhelpers.app.moh] Process delivery of push notification 9762-0FC8
default	01:51:50.644238+0530	SpringBoard	[com.ministryofhelpers.app.moh] Request DUET delivers content-available push notification to application
default	01:51:50.644505+0530	SpringBoard	SUBMITTING: com.apple.pushLaunch.com.ministryofhelpers.app.moh:DA4ED2
default	01:51:50.645014+0530	dasd	Submitted Activity: com.apple.pushLaunch.com.ministryofhelpers.app.moh:DA4ED2 at priority 10 (Mon Aug  5 01:51:50 2024 - Tue Aug  6 01:51:50 2024)
default	01:51:50.645967+0530	SpringBoard	[com.ministryofhelpers.app.moh] Badge can be set for notification 9762-0FC8: 0 [ canBadge: 1 badgeNumber: (null) ]
default	01:51:50.646225+0530	SpringBoard	Getting effectiveSectionInfo for section identifier: com.ministryofhelpers.app.moh
default	01:51:50.646797+0530	SpringBoard	[com.ministryofhelpers.app.moh] Getting effective section info
default	01:51:50.649632+0530	SpringBoard	[com.ministryofhelpers.app.moh] Got effective section info [ hasResult: 1 ]
default	01:51:50.649863+0530	SpringBoard	Getting effectiveSectionInfo for section identifier: com.ministryofhelpers.app.moh
default	01:51:50.650084+0530	SpringBoard	[com.ministryofhelpers.app.moh] Getting effective section info
default	01:51:50.651797+0530	SpringBoard	[com.ministryofhelpers.app.moh] Got effective section info [ hasResult: 1 ]
default	01:51:50.652293+0530	SpringBoard	[com.ministryofhelpers.app.moh] Saving notification 9762-0FC8: YES [ hasAlertContent: YES, shouldPresentAlert: YES settingsShouldSave: YES]
default	01:51:50.654098+0530	SpringBoard	[com.ministryofhelpers.app.moh] Delivered user visible push notification 9762-0FC8
default	01:51:50.655730+0530	SpringBoard	[com.ministryofhelpers.app.moh] Load 0 pending notification dictionaries
default	01:51:50.657222+0530	SpringBoard	[com.ministryofhelpers.app.moh] Adding notification 9762-0FC8 [ hasAlertContent: 1, shouldPresentAlert: 1 hasSound: 0 shouldPlaySound: 1 ]; interruption-level: 1; destinations 398: (
    NotificationCenter,
    LockScreen,
    Alert,
    Spoken,
    Forwarding
)
default	01:51:50.658255+0530	SpringBoard	BBDataProviderProxy com.ministryofhelpers.app.moh has enqueued a bulletin request
default	01:51:50.658587+0530	SpringBoard	BBDataProviderProxy com.ministryofhelpers.app.moh is now sending enqueued bulletin request to BBServer
default	01:51:50.661427+0530	SpringBoard	Publishing bulletin for section <com.ministryofhelpers.app.moh>: subsectionIDs: (null), bulletinID = <9D68262C-FC6B-454E-BF64-8FDF6A660F40>, expiration date = <Mon Aug 12 01:51:50 2024>, expiration events <0>
default	01:51:50.690151+0530	SpringBoard	NCBulletinNotificationSource adding bulletin 9762-0FC8 for feed 3115 in section com.ministryofhelpers.app.moh
default	01:51:50.690197+0530	SpringBoard	NCBulletinNotificationSource adding bulletin 9762-0FC8 for feed 3115 in section com.ministryofhelpers.app.moh
default	01:51:50.690105+0530	SpringBoard	NCBulletinNotificationSource adding bulletin 9762-0FC8 for feed 3115 in section com.ministryofhelpers.app.moh
default	01:51:51.160649+0530	SpringBoard	[com.apple.springboard.NCBulletinNotificationSource:BCE9105E-A7B8-4E40-8837-9E50FDA214F0] Resolving behavior for event, details=<DNDMutableClientEventDetails: 0x301671630; identifier: 'B85F0B59-339D-46C2-B833-E3C3D595282F'; bundleIdentifier:: com.ministryofhelpers.app.moh; type: Default; urgency: Default; sender: (null); threadIdentifier: FEE40AAEB2771881; filterCritera: (null); notifyAnyway: 0; behavior: Default>
default	01:51:51.161554+0530	donotdisturbd	Event was resolved: resolution=<DNDSEventBehaviorResolution: 0xdbe6ea800; UUID: CAD70CB1-36FE-41A8-BFDB-9729D70ED94E; date: 2024-08-04 8:21:50 PM +0000; eventBehavior: <DNDClientEventBehavior: 0xdbe76c930; eventDetails: <DNDClientEventDetails: 0xdbe5fb840; identifier: 'B85F0B59-339D-46C2-B833-E3C3D595282F'; bundleIdentifier:: com.ministryofhelpers.app.moh; type: Default; urgency: Default; sender: (null); threadIdentifier: FEE40AAEB2771881; filterCritera: (null); notifyAnyway: 0; behavior: Default>; interruptionSuppression: none; resolutionReason: disabled; activeModeUUID: (null)>; clientIdentifier: 'com.apple.springboard.NCBulletinNotificationSource'; outcome: allowed; reason: disabled>
default	01:51:51.162158+0530	SpringBoard	[com.apple.springboard.NCBulletinNotificationSource:BCE9105E-A7B8-4E40-8837-9E50FDA214F0] Resolved event, details=<DNDMutableClientEventDetails: 0x301671630; identifier: 'B85F0B59-339D-46C2-B833-E3C3D595282F'; bundleIdentifier:: com.ministryofhelpers.app.moh; type: Default; urgency: Default; sender: (null); threadIdentifier: FEE40AAEB2771881; filterCritera: (null); notifyAnyway: 0; behavior: Default> behavior=<DNDClientEventBehavior: 0x3038dd0e0; eventDetails: <DNDClientEventDetails: 0x301597390; identifier: 'B85F0B59-339D-46C2-B833-E3C3D595282F'; bundleIdentifier:: com.ministryofhelpers.app.moh; type: Default; urgency: Default; sender: (null); threadIdentifier: FEE40AAEB2771881; filterCritera: (null); notifyAnyway: 0; behavior: Default>; interruptionSuppression: none; resolutionReason: disabled; activeModeUUID: (null)>
default	01:51:51.162610+0530	SpringBoard	Posting notification id: 9762-0FC8; section: com.ministryofhelpers.app.moh; thread: 76E5-43BD; category: ; timestamp: 2024-08-04 8:21:50 PM +0000; interruption-level: active; relevance-score: 0.00; filter-criteria: (null); actions: [ minimal: 0 (0 text), default: 0 (0 text) ]; destinations: [ {(
    BulletinDestinationCoverSheet,
    BulletinDestinationBanner,
    BulletinDestinationNotificationCenter,
    BulletinDestinationLockScreen
)} ]
default	01:51:51.168461+0530	SpringBoard	Incoming Section [NCNotificationStructuredSectionList] inserting notification request 9762-0FC8 in new group Group List [com.ministryofhelpers.app.moh:76E5-43BD]
default	01:51:51.168741+0530	SpringBoard	Group List [com.ministryofhelpers.app.moh:76E5-43BD] inserting notification request 9762-0FC8 at index 0
default	01:51:51.160603+0530	SpringBoard	[com.apple.springboard.NCBulletinNotificationSource:BCE9105E-A7B8-4E40-8837-9E50FDA214F0] Resolving behavior for event, details=<DNDMutableClientEventDetails: 0x301671630; identifier: 'B85F0B59-339D-46C2-B833-E3C3D595282F'; bundleIdentifier:: com.ministryofhelpers.app.moh; type: Default; urgency: Default; sender: (null); threadIdentifier: FEE40AAEB2771881; filterCritera: (null); notifyAnyway: 0; behavior: Default>
default	01:51:51.161505+0530	donotdisturbd	Event was resolved: resolution=<DNDSEventBehaviorResolution: 0xdbe6ea800; UUID: CAD70CB1-36FE-41A8-BFDB-9729D70ED94E; date: 2024-08-04 8:21:50 PM +0000; eventBehavior: <DNDClientEventBehavior: 0xdbe76c930; eventDetails: <DNDClientEventDetails: 0xdbe5fb840; identifier: 'B85F0B59-339D-46C2-B833-E3C3D595282F'; bundleIdentifier:: com.ministryofhelpers.app.moh; type: Default; urgency: Default; sender: (null); threadIdentifier: FEE40AAEB2771881; filterCritera: (null); notifyAnyway: 0; behavior: Default>; interruptionSuppression: none; resolutionReason: disabled; activeModeUUID: (null)>; clientIdentifier: 'com.apple.springboard.NCBulletinNotificationSource'; outcome: allowed; reason: disabled>
default	01:51:51.162112+0530	SpringBoard	[com.apple.springboard.NCBulletinNotificationSource:BCE9105E-A7B8-4E40-8837-9E50FDA214F0] Resolved event, details=<DNDMutableClientEventDetails: 0x301671630; identifier: 'B85F0B59-339D-46C2-B833-E3C3D595282F'; bundleIdentifier:: com.ministryofhelpers.app.moh; type: Default; urgency: Default; sender: (null); threadIdentifier: FEE40AAEB2771881; filterCritera: (null); notifyAnyway: 0; behavior: Default> behavior=<DNDClientEventBehavior: 0x3038dd0e0; eventDetails: <DNDClientEventDetails: 0x301597390; identifier: 'B85F0B59-339D-46C2-B833-E3C3D595282F'; bundleIdentifier:: com.ministryofhelpers.app.moh; type: Default; urgency: Default; sender: (null); threadIdentifier: FEE40AAEB2771881; filterCritera: (null); notifyAnyway: 0; behavior: Default>; interruptionSuppression: none; resolutionReason: disabled; activeModeUUID: (null)>
default	01:51:51.162559+0530	SpringBoard	Posting notification id: 9762-0FC8; section: com.ministryofhelpers.app.moh; thread: 76E5-43BD; category: ; timestamp: 2024-08-04 8:21:50 PM +0000; interruption-level: active; relevance-score: 0.00; filter-criteria: (null); actions: [ minimal: 0 (0 text), default: 0 (0 text) ]; destinations: [ {(
    BulletinDestinationCoverSheet,
    BulletinDestinationBanner,
    BulletinDestinationNotificationCenter,
    BulletinDestinationLockScreen
)} ]
default	01:51:51.168411+0530	SpringBoard	Incoming Section [NCNotificationStructuredSectionList] inserting notification request 9762-0FC8 in new group Group List [com.ministryofhelpers.app.moh:76E5-43BD]
default	01:51:51.168677+0530	SpringBoard	Group List [com.ministryofhelpers.app.moh:76E5-43BD] inserting notification request 9762-0FC8 at index 0
default	01:51:51.160553+0530	SpringBoard	[com.apple.springboard.NCBulletinNotificationSource:BCE9105E-A7B8-4E40-8837-9E50FDA214F0] Resolving behavior for event, details=<DNDMutableClientEventDetails: 0x301671630; identifier: 'B85F0B59-339D-46C2-B833-E3C3D595282F'; bundleIdentifier:: com.ministryofhelpers.app.moh; type: Default; urgency: Default; sender: (null); threadIdentifier: FEE40AAEB2771881; filterCritera: (null); notifyAnyway: 0; behavior: Default>
default	01:51:51.161442+0530	donotdisturbd	Event was resolved: resolution=<DNDSEventBehaviorResolution: 0xdbe6ea800; UUID: CAD70CB1-36FE-41A8-BFDB-9729D70ED94E; date: 2024-08-04 8:21:50 PM +0000; eventBehavior: <DNDClientEventBehavior: 0xdbe76c930; eventDetails: <DNDClientEventDetails: 0xdbe5fb840; identifier: 'B85F0B59-339D-46C2-B833-E3C3D595282F'; bundleIdentifier:: com.ministryofhelpers.app.moh; type: Default; urgency: Default; sender: (null); threadIdentifier: FEE40AAEB2771881; filterCritera: (null); notifyAnyway: 0; behavior: Default>; interruptionSuppression: none; resolutionReason: disabled; activeModeUUID: (null)>; clientIdentifier: 'com.apple.springboard.NCBulletinNotificationSource'; outcome: allowed; reason: disabled>
default	01:51:51.162060+0530	SpringBoard	[com.apple.springboard.NCBulletinNotificationSource:BCE9105E-A7B8-4E40-8837-9E50FDA214F0] Resolved event, details=<DNDMutableClientEventDetails: 0x301671630; identifier: 'B85F0B59-339D-46C2-B833-E3C3D595282F'; bundleIdentifier:: com.ministryofhelpers.app.moh; type: Default; urgency: Default; sender: (null); threadIdentifier: FEE40AAEB2771881; filterCritera: (null); notifyAnyway: 0; behavior: Default> behavior=<DNDClientEventBehavior: 0x3038dd0e0; eventDetails: <DNDClientEventDetails: 0x301597390; identifier: 'B85F0B59-339D-46C2-B833-E3C3D595282F'; bundleIdentifier:: com.ministryofhelpers.app.moh; type: Default; urgency: Default; sender: (null); threadIdentifier: FEE40AAEB2771881; filterCritera: (null); notifyAnyway: 0; behavior: Default>; interruptionSuppression: none; resolutionReason: disabled; activeModeUUID: (null)>
default	01:51:51.162503+0530	SpringBoard	Posting notification id: 9762-0FC8; section: com.ministryofhelpers.app.moh; thread: 76E5-43BD; category: ; timestamp: 2024-08-04 8:21:50 PM +0000; interruption-level: active; relevance-score: 0.00; filter-criteria: (null); actions: [ minimal: 0 (0 text), default: 0 (0 text) ]; destinations: [ {(
    BulletinDestinationCoverSheet,
    BulletinDestinationBanner,
    BulletinDestinationNotificationCenter,
    BulletinDestinationLockScreen
)} ]
default	01:51:51.168354+0530	SpringBoard	Incoming Section [NCNotificationStructuredSectionList] inserting notification request 9762-0FC8 in new group Group List [com.ministryofhelpers.app.moh:76E5-43BD]
default	01:51:51.168627+0530	SpringBoard	Group List [com.ministryofhelpers.app.moh:76E5-43BD] inserting notification request 9762-0FC8 at index 0

### Additional context and comments

in ios release build firebase background notifications successfully delivered, but FirebaseMessaging.onBackgroundMessage stoped after some time , both are working properly in debug build.

**Comment by Lyokone** [comment]
![Screenshot 2024-08-05 at 10 18 22](https://github.com/user-attachments/assets/95925fc2-3618-41ed-9a29-053ed04791b5)

Looking at this screenshot, your dev APNS certificate is expired and you don't have any production certificate.
