### ISSUE TITLE
firebase_core: Twitter Login Fails on Mobile When Firefox is the Default Browser

### ISSUE THREAD

**Issue by rsegecin** [firebase/flutterfire#13141]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Auth

### Which platforms are affected?

Android

### Description

There are two problems with Twitter login:

1. Initial Login Issue: If you are not logged into Twitter on the web browser of your mobile phone (or the web browser if you are on the web platform), the Twitter authentication pop-up does not close after logging in. Instead, it opens the Twitter web page in the pop up window. On the second attempt, since the Twitter session is already active, the pop-up closes correctly, and Firebase Auth login succeeds.

2. Browser-Specific Issue on Android: On Android (and likely on iOS as well), if Firefox is set as the default web browser, after logging in through the pop-up, it remains open and throws an error (see attached screenshot). In contrast, using Chrome as the default browser allows the pop-up to close after login, and authentication succeeds.

![firecore](https://github.com/user-attachments/assets/09583e09-051c-4ab9-a127-c5d0dcb7b2f6)

### Reproducing the issue

Setup a normal twitter login setup through firebase.

### Firebase Core version

3.2.0

### Flutter Version

3.22.2

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by Lyokone** [comment]
Hello @rsegecin, both of those issues are unrelated to FlutterFire directly. You can open an issue on the Android repository: https://github.com/firebase/firebase-android-sdk

Is see people have opened similar issues here: https://github.com/firebase/firebase-android-sdk/issues/6144

**Comment by rsegecin** [comment]
Hello @Lyokone, I hope you're well, thank you.
