### ISSUE TITLE
[FIREBASE MESSAGING]: java.lang.NullPointerException: Firebase Messaging component is not present, Stacktrace: 

### ISSUE THREAD

**Issue by Lukaalishi** [firebase/flutterfire#13149]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Core, Messaging

### Which platforms are affected?

Android

### Description

E/flutter (14077): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Firebase Messaging component is not present, ExecutionException, Cause: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Firebase Messaging component is not present, Stacktrace: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Firebase Messaging component is not present

### Reproducing the issue

when you try : flutter pub run

### Firebase Core version

3.3.0

### Flutter Version

3.22.x

### Relevant Log Output

```shell
E/flutter (14077): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Firebase Messaging component is not present, ExecutionException, Cause: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Firebase Messaging component is not present, Stacktrace: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Firebase Messaging component is not present
E/flutter (14077):      at com.google.android.gms.tasks.Tasks.zza(com.google.android.gms:play-services-tasks@@18.1.0:5)
```

### Flutter dependencies

  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  firebase_in_app_messaging: ^0.8.0+4
  firebase_auth: ^5.1.3
  flutter_local_notifications: ^17.1.2

### Additional context and comments

please i need help to solve this

**Comment by Lyokone** [comment]
Hello @Lukaalishi, cannot reproduce on my can you provide a complete sample?

**Comment by Lukaalishi** [comment]
E/flutter ( 6915): #0      FirebaseCoreHostApi.initializeCore (package:firebase_core_platform_interface/src/pigeon/messages.pigeon.dart:215:7)
E/flutter ( 6915): <asynchronous suspension>
E/flutter ( 6915): #1      MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:29:44)
E/flutter ( 6915): <asynchronous suspension>
E/flutter ( 6915): #2      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:73:7)
E/flutter ( 6915): <asynchronous suspension>
E/flutter ( 6915): #3      Firebase.initializeApp (package:firebase_core/src/firebase.dart:66:31)
E/flutter ( 6915): <asynchronous suspension>
E/flutter ( 6915): #4      main (package:myproject/main.dart:26:3)
E/flutter ( 6915): <asynchronous suspension>

**Comment by Lukaalishi** [comment]
i got this when am try to run:
W/ComponentDiscovery( 6915): Application info not found.
W/ComponentDiscovery( 6915): Could not retrieve metadata, returning empty list of registrars.
I/FirebaseApp( 6915): Device unlocked: initializing all Firebase APIs for app [DEFAULT]

**Comment by Lyokone** [comment]
Hello @Lukaalishi, this is not a complete sample. A complete sample should be a Github repository that I can clone with minimal code reproducing the issue.
