### ISSUE TITLE
[flutterfire_cli]: CLI creates plugin references wrongly in Android

### ISSUE THREAD

**Issue by feinstein** [firebase/flutterfire#13157]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Other

### Which platforms are affected?

Android

### Description

I have executed:

```console
flutterfire configure \
--project="my-project" \
--platforms="ios,android,web" \
--ios-build-config=Debug-production \
--ios-out=/ios/Runner/GoogleService-Info.plist \
--android-out=/android/app/google-services.json \
--ios-bundle-id="id.myproject" \
--android-package-name="id.myproject" \
--out=/lib/firebase/firebase_options_production.dart \
--overwrite-firebase-options \
--yes
```

And my `android/app/build.gradle` file was modified as:

```groovy
plugins {
    id "com.android.application"
// START: FlutterFire Configuration
apply plugin: 'com.google.gms.google-services'
// END: FlutterFire Configuration
    // TODO: Check if this problem still applied to release builds:
    // There is an issue with sentry plugin version >=4.3.0 when making a release build.
    // Check issue at https://github.com/getsentry/sentry-react-native/issues/3644
    id "io.sentry.android.gradle" version "4.10.0"
}
```

Which generates this compiler error:

>Only method calls to 'id' and 'alias' are available in 'plugins' block

I got this error because I tried to run an android build and it generated this error:

>class org.codehaus.groovy.ast.expr.TupleExpression cannot be cast to class org.codehaus.groovy.ast.expr.ArgumentListExpression (org.codehaus.groovy.ast.expr.TupleExpression and org.codehaus.groovy.ast.expr.ArgumentListExpression are in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @29774679)
> class org.codehaus.groovy.ast.expr.TupleExpression cannot be cast to class org.codehaus.groovy.ast.expr.ArgumentListExpression (org.codehaus.groovy.ast.expr.TupleExpression and org.codehaus.groovy.ast.expr.ArgumentListExpression are in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @29774679)
> 
> Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
> 
> Re-download dependencies and sync project (requires network)
> The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
> 
> Stop Gradle build processes (requires restart)
> Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.
> 
> In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

### Reproducing the issue

1. Install the flutterfire_cli
2. Execute this:
```console
flutterfire configure \
--project="my-project" \
--platforms="ios,android,web" \
--ios-build-config=Debug-production \
--ios-out=/ios/Runner/GoogleService-Info.plist \
--android-out=/android/app/google-services.json \
--ios-bundle-id="id.myproject" \
--android-package-name="id.myproject" \
--out=/lib/firebase/firebase_options_production.dart \
--overwrite-firebase-options \
--yes
```

3. Try to run an android build

### Firebase Core version

3.2.0

### Flutter Version

3.23.3

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by Lyokone** [comment]
Hello @feinstein, please report this issue in this repository: https://github.com/invertase/flutterfire_cli

**Comment by feinstein** [comment]
Can you transfer?
