### ISSUE TITLE
[firebase_analytics]: in_app_purchase event is not being auto reported for iOS

### ISSUE THREAD

**Issue by juanmasilf** [firebase/flutterfire#13155]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Analytics

### Which platforms are affected?

iOS

### Description

I've noticed that `in_app_purchases` event stopped being auto reported by Firebase from July 18th. 

We are using firebase_analytics ^11.0.0.

<img width="1166" alt="Screenshot 2024-08-06 at 5 07 22 PM" src="https://github.com/user-attachments/assets/e52f25c7-99fb-427f-8999-48e5a9bd5fa5">

### Reproducing the issue

This is an auto reported event, so no reproducible code to add here

### Firebase Core version

3.0.0

### Flutter Version

3.22.2

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by Lyokone** [comment]
Hello, thanks for reporting, can you open this issue in https://github.com/firebase/firebase-ios-sdk please? This looks like an issue with the native SDK.

**Comment by juanmasilf** [comment]
Got it! Thanks @Lyokone 😄

**Comment by davidnunes19** [comment]
@juanmasilf Could you share the link to the issue in firebase-ios-sdk? Or Have you found any solution to this?
Thanks in advance 😄
