### ISSUE TITLE
signInWithRedirect is of void type, but is stated as returning UserCredentials in the docs

### ISSUE THREAD

**Issue by tanmay1100** [firebase/flutterfire#13164]
https://firebase.google.com/docs/auth/flutter/federated-auth

The web section discusses 2 ways of getting users authenticated with their google account:

```
// Once signed in, return the UserCredential
  return await FirebaseAuth.instance.signInWithPopup(googleProvider);

  // Or use signInWithRedirect
  // return await FirebaseAuth.instance.signInWithRedirect(googleProvider);
  ```
  The function that encapsulates them has a return type of `UserCredential` but the signInWithRedirect method is of return type void

**Comment by Lyokone** [comment]
Hello @tanmay1100, thanks for reporting this. I do think that we do that to avoid duplicating the documentation too much. Linter should help you if you decide to uncomment this code block.
