### ISSUE TITLE
[AppCheck]: Pub get fails after share_plus releases new versions

### ISSUE THREAD

**Issue by marcellocamara** [firebase/flutterfire#13188]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

App Check

### Which platforms are affected?

Android, iOS, macOS, Web, Windows

### Description

After the new releases of `share_plus`, 10.0.1 and 10.0.2, app_check don't allow pub get, forcing us to override the dependency version.

```
Because no versions of firebase_app_check match >0.3.0+4 <0.4.0 and firebase_app_check 0.3.0+4 depends on firebase_app_check_web ^0.1.2+12, firebase_app_check ^0.3.0+4 requires firebase_app_check_web ^0.1.2+12.
And because no versions of firebase_app_check_web match >0.1.2+12 <0.2.0, firebase_app_check ^0.3.0+4 requires firebase_app_check_web 0.1.2+12.
And because firebase_app_check_web 0.1.2+12 depends on web ^0.5.1 and share_plus >=10.0.1 depends on web ^1.0.0, firebase_app_check ^0.3.0+4 is incompatible with share_plus >=10.0.1.
So, because loterias depends on both share_plus ^10.0.2 and firebase_app_check ^0.3.0+4, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on share_plus: flutter pub add share_plus:^10.0.0
```

Note that it says: `firebase_app_check ^0.3.0+4 is incompatible with share_plus >=10.0.1`

The last workable version is 10.0.0
10.0.1 and 10.0.2 results in the same problem, forcing override dependencies to fix pub get.

### Reproducing the issue

Uses `share_plus` at new versions, under 10.0.0

### Firebase Core version

3.3.0

### Flutter Version

3.24.0

### Relevant Log Output

```shell
Because no versions of firebase_app_check match >0.3.0+4 <0.4.0 and firebase_app_check 0.3.0+4 depends on firebase_app_check_web ^0.1.2+12, firebase_app_check ^0.3.0+4 requires firebase_app_check_web ^0.1.2+12.
And because no versions of firebase_app_check_web match >0.1.2+12 <0.2.0, firebase_app_check ^0.3.0+4 requires firebase_app_check_web 0.1.2+12.
And because firebase_app_check_web 0.1.2+12 depends on web ^0.5.1 and share_plus >=10.0.1 depends on web ^1.0.0, firebase_app_check ^0.3.0+4 is incompatible with share_plus >=10.0.1.
So, because loterias depends on both share_plus ^10.0.2 and firebase_app_check ^0.3.0+4, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on share_plus: flutter pub add share_plus:^10.0.0
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml
  share_plus: ^10.0.2
  firebase_core: ^3.3.0
  firebase_app_check: ^0.3.0+4
```

</details>

**Comment by irhmaan** [comment]
Does it work without mentioning a certain version of share plus.
I faced similar issue, and left the version blank.

**Comment by Lyokone** [comment]
Duplicates of https://github.com/firebase/flutterfire/issues/13190, check solution at https://github.com/firebase/flutterfire/issues/13190#issuecomment-2295927416
