### ISSUE TITLE
[Database/unavailable] Service unavailable on Android after update - Possible impact of multiple database support?

### ISSUE THREAD

**Issue by Alecia1997** [firebase/flutterfire#13186]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Database

### Description

Description:

We are encountering an issue with the cloud_firestore package where Android users are receiving the following error:

[cloud_firestore/unavailable] The service is currently unavailable. This is most likely a transient condition and may be corrected by retrying with a backoff.

### Reproducing the issue

Steps to Reproduce:
Update the cloud_firestore package to the latest version.
Attempt to connect to a Firestore database from an Android device.
The above error is received intermittently.

Expected Behavior:
Android devices should be able to connect to the Firestore database without encountering the [cloud_firestore/unavailable] error.

### Firebase Core version

^3.3.0

### Flutter Version

3.24.0

**Comment by SelaseKay** [comment]
Hi @Alecia1997 . Kindly provide a full sample code reproducing this issue.

**Comment by Alecia1997** [comment]
`import 'dart:io';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:device_info_plus/device_info_plus.dart';
import 'package:package_info_plus/package_info_plus.dart';
import 'package:flutter/foundation.dart';

class MainFirebaseRepository {
  final FirebaseFirestore _firebaseFirestore = FirebaseFirestore.instance;

  Future<int> latestAppVersion() async {
    try {
      DocumentSnapshot<Map<String, dynamic>> snapshot = 
          await _firebaseFirestore.collection('settings').doc('latestAppVersion').get();
      
      if (Platform.isIOS) {
        return snapshot.data()?['iosBuild'] ?? 0;
      } else if (Platform.isAndroid) {
        return snapshot.data()?['androidBuild'] ?? 0;
      }
      return 0;
    } catch (e) {
      print('Error fetching latest app version: $e');
      rethrow;
    }
  }
}

class AppVersionChecker {
  final MainFirebaseRepository _repository = MainFirebaseRepository();

  Future<void> checkIfLatestAppVersion() async {
    try {
      PackageInfo packageInfo = await PackageInfo.fromPlatform();
      
      int buildNumberStoredInFirebase = await _repository.latestAppVersion();
      int myBuildNumber = int.tryParse(packageInfo.buildNumber) ?? 0;
      
      print('Firebase build number: $buildNumberStoredInFirebase');
      print('Current app build number: $myBuildNumber');
      
      if (buildNumberStoredInFirebase > myBuildNumber) {
        print('App not using latest version');
      } else {
        print('App is using latest version');
      }
    } catch (e) {
      print('Error checking app version: $e');
    }
  }
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  
  AppVersionChecker checker = AppVersionChecker();
  await checker.checkIfLatestAppVersion();
}`

**Comment by Alecia1997** [comment]
Please find sample code to run: 

`import 'dart:io';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:package_info_plus/package_info_plus.dart';

class MainFirebaseRepository {
  final FirebaseFirestore _firebaseFirestore = FirebaseFirestore.instance;

  Future<int> latestAppVersion() async {
    try {
      DocumentSnapshot<Map<String, dynamic>> snapshot =
      await _firebaseFirestore.collection('settings').doc('latestAppVersion').get();

      if (Platform.isIOS) {
        return snapshot.data()?['iosBuild'] ?? 0;
      } else if (Platform.isAndroid) {
        return snapshot.data()?['androidBuild'] ?? 0;
      }
      return 0;
    } catch (e) {
      print('Error fetching latest app version: $e');
      rethrow;
    }
  }
}

class AppVersionChecker {
  final MainFirebaseRepository _repository = MainFirebaseRepository();

  Future<void> checkIfLatestAppVersion() async {
    try {
      PackageInfo packageInfo = await PackageInfo.fromPlatform();

      int buildNumberStoredInFirebase = await _repository.latestAppVersion();
      int myBuildNumber = int.tryParse(packageInfo.buildNumber) ?? 0;

      print('Firebase build number: $buildNumberStoredInFirebase');
      print('Current app build number: $myBuildNumber');

      if (buildNumberStoredInFirebase > myBuildNumber) {
        print('App not using latest version');
      } else {
        print('App is using latest version');
      }
    } catch (e) {
      print('Error checking app version: $e');
    }
  }
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();

  AppVersionChecker checker = AppVersionChecker();
  await checker.checkIfLatestAppVersion();
}`

The issue primarily impacts android users.

**Comment by SelaseKay** [comment]
I am unable to reproduce this issue locally on my end. This issue is similar to [12019](https://github.com/firebase/flutterfire/issues/12019). From previous reports, it seems to be related to network issue/firestore downtime, etc.
