### ISSUE TITLE
[flutter_core_web]: Version solving failed

### ISSUE THREAD

**Issue by Sardorbee** [firebase/flutterfire#13197]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Core, Crashlytics, Messaging

### Which platforms are affected?

Android, iOS

### Description

When i run pub get, i got this error:   
Because firebase_core_web 2.17.4 depends on web ^0.5.1 and no versions of firebase_core_web match >2.17.4 <3.0.0, firebase_core_web ^2.17.4 requires web ^0.5.1.
And because emoji_picker_flutter >=3.0.0 depends on web ^1.0.0 and firebase_core >=3.3.0 depends on firebase_core_web ^2.17.4, emoji_picker_flutter >=3.0.0 is incompatible with firebase_core >=3.3.0.

### Reproducing the issue

Because firebase_core_web 2.17.4 depends on web ^0.5.1 and no versions of firebase_core_web match >2.17.4 <3.0.0, firebase_core_web ^2.17.4 requires web ^0.5.1.
And because emoji_picker_flutter >=3.0.0 depends on web ^1.0.0 and firebase_core >=3.3.0 depends on firebase_core_web ^2.17.4, emoji_picker_flutter >=3.0.0 is incompatible with firebase_core >=3.3.0.

### Firebase Core version

3.3.0

### Flutter Version

3.24.0

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml
Because firebase_core_web 2.17.4 depends on web ^0.5.1 and no versions of firebase_core_web match >2.17.4 <3.0.0, firebase_core_web ^2.17.4
  requires web ^0.5.1.
And because emoji_picker_flutter >=3.0.0 depends on web ^1.0.0 and firebase_core >=3.3.0 depends on firebase_core_web ^2.17.4,
  emoji_picker_flutter >=3.0.0 is incompatible with firebase_core >=3.3.0.
So, because topish depends on both firebase_core ^3.3.0 and emoji_picker_flutter ^3.0.0, version solving failed.

```

</details>

**Comment by SelaseKay** [comment]
Hi @Sardorbee . This issue has been reported several times. Kindly search for duplicates before posting a new issue. 
Please refer to this: [issue](https://github.com/firebase/flutterfire/issues/13190)
