### ISSUE TITLE
firebase_auth: ^5.1.4 and firebase_core: ^3.3.0

### ISSUE THREAD

**Issue by Mustakim-final** [firebase/flutterfire#13206]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Other

### Which platforms are affected?

Windows

### Description

when i bulid windows application its not bulid

### Reproducing the issue

_CRT_SECURE_NO_WARNINGS issue

### Firebase Core version

3.3.0

### Flutter Version

3.22.3

### Relevant Log Output

```shell
F:\android\meal\build\windows\x64\extracted\firebase_cpp_sdk_windows\include\firebase/variant.h(801,7): error C2220: the following warning is treated as an error [F:\android\meal\build\windows\x64\plugins\firebase_auth\firebase_auth_plugin.vcxproj]
F:\android\meal\build\windows\x64\extracted\firebase_cpp_sdk_windows\include\firebase/variant.h(801,7): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [F:\android\meal\build\windows\x64\plugins\firebase_auth\firebase_auth_plugin.vcxproj]
F:\android\meal\build\windows\x64\extracted\firebase_cpp_sdk_windows\include\firebase/variant.h(827,7): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [F:\android\meal\build\windows\x64\plugins\firebase_auth\firebase_auth_plugin.vcxproj]
F:\android\meal\build\windows\x64\extracted\firebase_cpp_sdk_windows\include\firebase/variant.h(801,7): error C2220: the following warning is treated as an error [F:\android\meal\build\windows\x64\plugins\firebase_auth\firebase_auth_plugin.vcxproj]
F:\android\meal\build\windows\x64\extracted\firebase_cpp_sdk_windows\include\firebase/variant.h(801,7): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [F:\android\meal\build\windows\x64\plugins\firebase_auth\firebase_auth_plugin.vcxproj]
F:\android\meal\build\windows\x64\extracted\firebase_cpp_sdk_windows\include\firebase/variant.h(827,7): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [F:\android\meal\build\windows\x64\plugins\firebase_auth\firebase_auth_plugin.vcxproj]
Error: Build process failed.
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by SelaseKay** [comment]
Hi @Mustakim-final . Have you tried `flutter clean` and `flutter pub get`? On the other hand, there's a similar issue that has been closed. Kindly refer to this [issue](https://github.com/firebase/flutterfire/issues/12088) to see if any of the comments help?

**Comment by Mustakim-final** [comment]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_app_desktop.obj) : warning LNK4099: PDB 'firebase_app.pdb' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_app_desktop.obj)' or at 'F:\android\meal\build\windows\x64\runner\Debug\firebase_app.pdb'; linking object as if no debug info [F:\android\meal\build\windows\x64\runner\meal.vcxproj] given this errror when i use firebase auth and firebase core

**Comment by SelaseKay** [comment]
Hi @Mustakim-final . Did you try out the above comment?

**Comment by Mustakim-final** [comment]
i try this same error

**Comment by Mustakim-final** [comment]
no help this comments

**Comment by Mustakim-final** [comment]
i using android studio

**Comment by SelaseKay** [comment]
What version of Visual Studio do you have installed?

**Comment by Mustakim-final** [comment]
i using android studio

**Comment by SelaseKay** [comment]
Yes. I'm aware you're using android studio. However, you need to have Visual Studio installed when you want to run flutter apps on windows platform. Please refer to this [link](https://docs.flutter.dev/platform-integration/windows/install-windows/install-windows-from-android)
