### ISSUE TITLE
[firebase_app_check]: App Attest does not work on macOS and fails to fallback to DeviceCheck

### ISSUE THREAD

**Issue by OutdatedGuy** [firebase/flutterfire#13202]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

App Check

### Which platforms are affected?

iOS, macOS

### Description

The firebase app check initialization for apple using:

```dart
await FirebaseAppCheck.instance.activate(
  androidProvider: AndroidProvider.playIntegrity,
  appleProvider: AppleProvider.appAttestWithDeviceCheckFallback,
);
```

does not work when running an iOS/iPad app (not a macOS app) on macOS (apple silicon).

It used to work with `AppleProvider.deviceCheck` perfectly well, but since I changed it to `AppleProvider.appAttestWithDeviceCheckFallback` it completely stopped working as I have enforced App Check on all my services (meaning I'm getting `Unauthenticated` errors).

App Attest states that it works on iOS and macOS 14+ and I'm using macOS 17.6.1 but even then this shouldn't be the case as when App Attest fails it should fallback to DeviceCheck which works on macOS.

I already have setup App Attest according to the Firebase docs and the proof of it working is the iOS devices are getting the app check token and works well.

### Reproducing the issue

You can use the example app for firebase_app_check with App Attest configured on macOS.

### Firebase Core version

3.3.0

### Flutter Version

3.24.0

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by Lyokone** [comment]
Hello @OutdatedGuy, you mention that the proof that you have configured everything fine is the iOS app working, but you still need to add different keys and properly sign and notarize your Flutter app to have it work. Were you able to complete those steps.

**Comment by OutdatedGuy** [comment]
@Lyokone can you specify what do you means by _still need to add different keys and properly sign and notarize your Flutter app to have it work_

If it means,
1. Enabling **App Attest** in [Identifiers](https://developer.apple.com/account/resources/identifiers/list), [Profiles](https://developer.apple.com/account/resources/profiles/list) & [Keys](https://developer.apple.com/account/resources/authkeys/list) on Apple developer Account then yes I have had it done already.

2. Uploading `.p8` file for DeviceCheck and App Attest then yes I have done it.
   <img width="485" alt="Screenshot 2024-08-29 at 10 15 57 PM" src="https://github.com/user-attachments/assets/c3c79d75-e2d9-4b7d-a22a-94557d73161b">

3. Enabling App Attest under **Capabilities** section in XCode, then that is done too.

**Comment by OutdatedGuy** [comment]
Btw if it wasn't clear in the main post, I'm running iOS app on macOS. Idk what apple calls it, but I'm not running native macOS apps on my mac, but rather iOS apps on my apple silicon mac downloaded through app store.
