### ISSUE TITLE
cloud_firestore: W/Firestore(22438): (25.0.0) [WriteStream]: (6d13a49) Stream closed with status: Status{code=UNAVAILABLE, description=Unable to resolve host firestore.googleapis.com, cause=java.lang.RuntimeException: java.net.UnknownHostException: Unable to resolve host "firestore.googleapis.com": No address associated with hostname

### ISSUE THREAD

**Issue by DaniyalDolare** [firebase/flutterfire#13218]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Database

### Which platforms are affected?

Android

### Description

Environment: Using windows for development and build and physical android device running on android 12 and 13.
I am using cloud firestore in my flutter project. When I am online, everythings work good. I can create,read,update and delete data in my cloud firestore. But when I turn off my wifi and I am still in the app and tries to do any create,update,delete action, it gives this error:
W/Firestore( 3295): 	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:219)
W/Firestore( 3295): 	... 5 more
W/Firestore( 3295): Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
W/Firestore( 3295): 	at libcore.io.Linux.android_getaddrinfo(Native Method)
W/Firestore( 3295): 	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
W/Firestore( 3295): 	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:222)
W/Firestore( 3295): 	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
W/Firestore( 3295): 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
W/Firestore( 3295): 	... 9 more
W/Firestore( 3295): }.

When I close my app, turn off wifi, and open the app, it reads the data but I still cant do any write operation on the data. 

### Reproducing the issue

Setup a flutter project which uses cloud firestore.
Turn on Wifi and perform crud operation
Turn off Wifi and perform crud operation.

### Firebase Core version

3.3.0

### Flutter Version

3.22.2

### Relevant Log Output

```shell
W/Firestore( 3295): 	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:219)
W/Firestore( 3295): 	... 5 more
W/Firestore( 3295): Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
W/Firestore( 3295): 	at libcore.io.Linux.android_getaddrinfo(Native Method)
W/Firestore( 3295): 	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
W/Firestore( 3295): 	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:222)
W/Firestore( 3295): 	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
W/Firestore( 3295): 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
W/Firestore( 3295): 	... 9 more
W/Firestore( 3295): }.
W/ManagedChannelImpl( 3295): [{0}] Failed to resolve name. status={1}
```

### Flutter dependencies

Dart SDK 3.4.3
Flutter SDK 3.22.2
productivity_app 1.0.0+4

dependencies:
- cloud_firestore 5.2.1 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.8
- firebase_auth 5.1.4 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 3.3.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_local_notifications 17.2.2 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_staggered_grid_view 0.7.0 [flutter]
- flutter_timezone 3.0.0 [flutter flutter_web_plugins]
- google_sign_in 6.2.1 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- intl 0.19.0 [clock meta path]
- provider 6.1.2 [collection flutter nested]
- shared_preferences 2.3.2 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- timezone 0.9.4 [path]

dev dependencies:
- flutter_launcher_icons 0.13.1 [args checked_yaml cli_util image json_annotation path yaml]
- flutter_lints 4.0.0 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]

transitive dependencies:
- _flutterfire_internals 1.3.40 [collection firebase_core firebase_core_platform_interface flutter meta]       
- archive 3.6.1 [crypto path]
- args 2.5.0
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- cli_util 0.4.1 [meta path]
- clock 1.1.1
- cloud_firestore_platform_interface 6.3.1 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 4.1.1 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins]
- collection 1.18.0
- crypto 3.0.5 [typed_data]
- dbus 0.7.10 [args ffi meta xml]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.3
- file 7.0.0 [meta path]
- firebase_auth_platform_interface 7.4.3 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.12.5 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser meta web]
- firebase_core_platform_interface 5.2.0 [collection flutter flutter_test meta plugin_platform_interface]      
- firebase_core_web 2.17.4 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- flutter_local_notifications_linux 4.0.1 [dbus ffi flutter flutter_local_notifications_platform_interface path xdg_directories]
- flutter_local_notifications_platform_interface 7.2.0 [flutter plugin_platform_interface]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- google_identity_services_web 0.3.1+4 [meta web]
- google_sign_in_android 6.1.28 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.7.6 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.4.5 [flutter plugin_platform_interface]
- google_sign_in_web 0.12.4+2 [flutter flutter_web_plugins google_identity_services_web google_sign_in_platform_interface http web]
- http 1.2.2 [async http_parser meta web]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image 4.2.0 [archive meta xml]
- json_annotation 4.9.0 [meta]
- leak_tracker 10.0.4 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.3 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 4.0.0
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.8.0 [collection]
- meta 1.12.0
- nested 1.0.0 [flutter]
- path 1.9.0
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.3.0 [ffi flutter path path_provider_platform_interface]
- petitparser 6.0.2 [meta]
- platform 3.1.5
- plugin_platform_interface 2.1.8 [meta]
- shared_preferences_android 2.3.2 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.5.2 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.4.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.4.1 [flutter plugin_platform_interface]
- shared_preferences_web 2.4.2 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.4.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.7.0 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner 
term_glyph]
- typed_data 1.3.2 [collection]
- vector_math 2.1.4
- vm_service 14.2.1
- web 0.5.1
- xdg_directories 1.0.4 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]

### Additional context and comments

It was working previously for me, but when I upgraded my projects dependencies like flutter sdk version, using latest version of all packages, I am getting issue,

**Comment by SelaseKay** [comment]
Hi @DaniyalDolare . Thanks for reporting. I am able to reproduce this issue. Can you recall the version it was working for previously?

**Comment by DaniyalDolare** [comment]
Hi @SelaseKay , The app is working now, there was some logic issue from my side. Now all crud operation is working in offline mode. But the error is still coming in the console log
`
W/Firestore( 6937): (25.0.0) [WatchStream]: (159d369) Stream closed with status: Status{code=UNAVAILABLE, description=null, cause=java.net.ConnectException: failed to connect to firestore.googleapis.com/142.250.183.74 (port 443) from /:: (port 0): connect failed: ENETUNREACH (Network is unreachable)
W/Firestore( 6937): 	at libcore.io.IoBridge.connect(IoBridge.java:187)
W/Firestore( 6937): 	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
W/Firestore( 6937): 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
W/Firestore( 6937): 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
W/Firestore( 6937): 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
W/Firestore( 6937): 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
W/Firestore( 6937): 	at java.net.Socket.connect(Socket.java:646)
W/Firestore( 6937): 	at java.net.Socket.connect(Socket.java:595)
W/Firestore( 6937): 	at java.net.Socket.<init>(Socket.java:475)
W/Firestore( 6937): 	at java.net.Socket.<init>(Socket.java:275)
W/Firestore( 6937): 	at javax.net.DefaultSocketFactory.createSocket(SocketFactory.java:285)
W/Firestore( 6937): 	at io.grpc.okhttp.OkHttpClientTransport$3.run(OkHttpClientTransport.java:535)
W/Firestore( 6937): 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
W/Firestore( 6937): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
W/Firestore( 6937): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
W/Firestore( 6937): 	at java.lang.Thread.run(Thread.java:1012)
W/Firestore( 6937): Caused by: android.system.ErrnoException: connect failed: ENETUNREACH (Network is unreachable)
W/Firestore( 6937): 	at libcore.io.Linux.connect(Native Method)
W/Firestore( 6937): 	at libcore.io.ForwardingOs.connect(ForwardingOs.java:201)
W/Firestore( 6937): 	at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:158)
W/Firestore( 6937): 	at libcore.io.ForwardingOs.connect(ForwardingOs.java:201)
W/Firestore( 6937): 	at libcore.io.IoBridge.connectErrno(IoBridge.java:201)
W/Firestore( 6937): 	at libcore.io.IoBridge.connect(IoBridge.java:179)
W/Firestore( 6937): 	... 15 more
W/Firestore( 6937): }.
W/ManagedChannelImpl( 6937): [{0}] Failed to resolve name. status={1}
`

**Comment by SelaseKay** [comment]
@DaniyalDolare , This issue is coming from the native Android sdk. It should be worth raising a report [here](https://github.com/firebase/firebase-android-sdk).
