### ISSUE TITLE
const { onRequest } = require("firebase-functions/v1/https");

### ISSUE THREAD

**Issue by milyes** [firebase/flutterfire#13222]
const { onRequest } = require("firebase-functions/v1/https");

exports.helloWorld = onRequest((request, response) => {
   response.send(`The env VARIABLE value is: ${process.env.VARIABLE}`);
}));

_Originally posted by @milyes in https://github.com/firebase/firebase-tools/issues/7596#issuecomment-2312421203_

**Comment by SelaseKay** [comment]
Hi @milyes . Kindly use the provided template to file an issue.

**Comment by milyes** [comment]
thank you
