### ISSUE TITLE
[firebase_messaging: '10.0.8']: <[firebase_messaging/unknown]java.io.IOEXCEPTION:PHONE_REGISTRATION_ERROR>

### ISSUE THREAD

**Issue by roja321** [firebase/flutterfire#13234]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which platforms are affected?

Android

### Description

I am using the firebase_messaging:10.0.8 package to get the token, but on Realme 6 (Android 11) and Redmi Note 8 (Android 11) devices, it returns null with the exception [firebase_messaging/unknown] java.io.IOException: PHONE_REGISTRATION_ERROR.

### Reproducing the issue

 var messaging = FirebaseMessaging.instance;
 String regId =await messaging.getToken();

### Firebase Core version

1.16.0

### Flutter Version

2.10.2

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by SelaseKay** [comment]
Hi @roja321 . Kindly provide a minimal sample code reproducing this issue. Also, add the steps followed to reproduce the issue.

**Comment by roja321** [comment]
@SelaseKay Thank you for your attension.

import 'package:firebase_messaging/firebase_messaging.dart';
String  regId =await FirebaseMessaging.instance.getToken();

here in regId i got null. for above mention devices.
![image](https://github.com/user-attachments/assets/ad10f32a-ce07-4c69-b2a9-025e35a7cb72)

**Comment by SelaseKay** [comment]
Hi @roja321 , I'm unable to reproduce this issue. Upgrade your `firebase_messaging` plugin and try again.

**Comment by Lyokone** [comment]
Hello @roja321, it looks like your devices doesn't have the Google Play Services to use Firebase Messaging. Nothing the FlutterFire repository can fix.
