### ISSUE TITLE
[firebase_auth]: Sign in with Apple invalid OAuth response

### ISSUE THREAD

**Issue by rikou75** [firebase/flutterfire#13235]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Auth

### Which platforms are affected?

iOS

### Description

Sign in with apple no longer works when upgrading firebase_auth (5.2.0) and firebase_core (3.4.0) to the latest version via the `signInWithCredential` function, but works using `signInWithProvider` and `AppleAuthProvider()`. 
The following error appears: **[firebase_auth/invalid-credential] Invalid OAuth response from apple.com**. 

I'm also using the latest version of the "**sign_in_with_apple**" package.

It works perfectly with the previous version, 5.1.3 for firebase_auth and 3.3.0 for firebase_core. 

### Reproducing the issue

```
import 'dart:convert';
import 'dart:math';
import 'package:crypto/crypto.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:sign_in_with_apple/sign_in_with_apple.dart';

String generateNonce([int length = 32]) {
  const charset =
      '0123456789ABCDEFGHIJKLMNOPQRSTUVXYZabcdefghijklmnopqrstuvwxyz-._';
  final random = Random.secure();
  return List.generate(length, (_) => charset[random.nextInt(charset.length)])
      .join();
}

String sha256ofString(String input) {
  final bytes = utf8.encode(input);
  final digest = sha256.convert(bytes);
  return digest.toString();
}

Future<UserCredential> signInWithApple() async {
    final rawNonce = generateNonce();
    final nonce = sha256ofString(rawNonce);

    final appleCredential = await SignInWithApple.getAppleIDCredential(
      scopes: [
        AppleIDAuthorizationScopes.email,
      ],
      nonce: nonce,
    );

    final oauthCredential = OAuthProvider("apple.com").credential(
      idToken: appleCredential.identityToken,
      rawNonce: rawNonce,
    );

    return await FirebaseAuth.instance.signInWithCredential(oauthCredential);
  }
```

### Firebase Core version

3.4.0

### Flutter Version

3.24.1

### Relevant Log Output

```shell
[firebase_auth/invalid-credential] Invalid OAuth response from apple.com
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml
dependencies:
- firebase_analytics 11.3.0 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 5.2.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 3.4.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 4.1.0 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_messaging 15.1.0 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_performance 0.10.0+5 [firebase_core firebase_core_platform_interface firebase_performance_platform_interface firebase_performance_web flutter]
- firebase_remote_config 5.1.0 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]
```

</details>

**Comment by rikou75** [comment]
Issue solved. Simply pass `accessToken: appleCredential.authorizationCode` to the `OAuthProvider(“apple.com”).credential()` method.

**Comment by coolswood** [comment]
> Issue solved. Simply pass `accessToken: appleCredential.authorizationCode` to the `OAuthProvider(“apple.com”).credential()` method.

Thanks, it worked for me!

**Comment by Linaks** [comment]
> Issue solved. Simply pass `accessToken: appleCredential.authorizationCode` to the `OAuthProvider(“apple.com”).credential()` method.

Thank you!
