### ISSUE TITLE
firebase_core_web: Dependency on old version of web (0.5.1)

### ISSUE THREAD

**Issue by tbz43353** [firebase/flutterfire#13241]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Core

### Which platforms are affected?

Web

### Description

firebase_core_web seems to have a dependency on an old version of the web library (0.5.1, current is 1.0.0).  This causing several issues including upgrading other libraries which have dependencies on 1.0.0.  I think its also preventing me from being able to compile the app for WASM.

### Reproducing the issue

Try setting up a flutter project with the latest version of youtube_player_iframe and firebase_analytics_web.  

### Firebase Core version

2.17.1

### Flutter Version

3.24.1

### Relevant Log Output

```shell
Resolving dependencies...
Because firebase_analytics_web >=0.5.7+9 <0.5.9 depends on firebase_core_web ^2.17.2 and firebase_analytics_web >=0.5.9 <0.5.9+1 depends on firebase_core_web ^2.17.3, firebase_analytics_web >=0.5.7+9 <0.5.9+1 requires firebase_core_web ^2.17.2.
And because firebase_analytics_web >=0.5.9+1 <0.5.9+2 depends on firebase_core_web ^2.17.4, firebase_analytics_web >=0.5.7+9 <0.5.9+2 requires firebase_core_web ^2.17.2.
And because firebase_analytics_web >=0.5.9+2 depends on firebase_core_web ^2.17.5 which depends on web ^0.5.1, firebase_analytics_web >=0.5.7+9 requires web ^0.5.1.
And because youtube_player_iframe >=5.1.4 depends on youtube_player_iframe_web ^3.0.3 which depends on web ^1.0.0, firebase_analytics_web >=0.5.7+9 is incompatible with youtube_player_iframe >=5.1.4.
So, because decision_app_common depends on both firebase_analytics_web ^0.5.7+9 and youtube_player_iframe ^5.1.5, version solving failed.
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  uuid: ^4.4.0
  get_it: ^7.6.7
  intl: ^0.19.0

  firebase_core: ^3.0.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  cloud_functions: ^5.0.1
  firebase_analytics_web: ^0.5.7+9
  logger: ^2.3.0
  flutter_linkify: ^6.0.0
  memory_cache: ^1.2.0
  youtube_player_iframe: ^5.1.5
  device_info_plus: ^10.1.0
  hooks_riverpod: ^2.5.1
  form_validator: ^2.1.1
  hexcolor: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.5
  freezed: ^2.5.2
  json_serializable: ^6.8.0 
  fake_cloud_firestore: ^3.0.0
  mockito: ^5.4.4

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>


### Additional context and comments

_No response_

**Comment by ngockhanhbl** [comment]
yes. they need to be upgrade :(

**Comment by SelaseKay** [comment]
Hi @tbz43353 , Thanks for the report. However, this issue appears to be a duplicate. You can get more insights [here](https://github.com/firebase/flutterfire/issues/13190#issuecomment-2295927416). Also, this [PR](https://github.com/firebase/flutterfire/pull/13200) has all the information you need.
