### ISSUE TITLE
firebase_analytics: version solving failed.

### ISSUE THREAD

**Issue by tyagnesh-mufin** [firebase/flutterfire#13249]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Analytics

### Which platforms are affected?

Android, iOS

### [Problem]
Resolving dependencies...
Because firebase_analytics >=11.3.0 depends on firebase_core ^3.4.0 and msquare_market depends on firebase_core ^2.26.0, firebase_analytics >=11.3.0 is forbidden.
So, because ****_project depends on firebase_analytics ^11.3.0, version solving failed.

### [My expected]
- **Is it possible to update Firebase Analytics without updating Firebase Core and any other dependencies?** i've try to update firebase core but when I update Firebase Core, it causes errors with Firebase Auth. There are many Flutter packages in my project, and updating Firebase Core seems to cause errors with these packages one by one based on their versions. My project is in production with over 1 million users, and if I update all the packages, I need to thoroughly test every feature to avoid generating issues for users. Currently, I am encountering numerous errors with other packages as well, which complicates the update process.

### Reproducing the issue

**I've included a few examples of these errors here.**

`Because no versions of firebase_auth match >4.20.0 <5.0.0 and firebase_auth >=4.19.6 <4.20.0 depends on firebase_core ^2.31.1, firebase_auth >=4.19.6 <4.20.0-∞ or >4.20.0 <5.0.0 requires firebase_core ^2.31.1.`

`Because no versions of firebase_remote_config match >4.3.17 <4.3.18 and firebase_remote_config >=4.3.16 <4.3.17 depends on firebase_core ^2.26.0, firebase_remote_config >=4.3.16 <4.3.17-∞ or >4.3.17 <4.3.18-∞ requires firebase_core ^2.26.0.`

`Because no versions of firebase_messaging match >14.7.19 <14.7.20 and firebase_messaging >=14.7.18 <14.7.19 depends on firebase_core ^2.26.0, firebase_messaging >=14.7.18 <14.7.19-∞ or >14.7.19 <14.7.20-∞ requires firebase_core ^2.26.0.`

### Firebase Core version

3.4.0

### Flutter Version

3.22.3

### Flutter dependencies

  firebase_auth: ^4.19.6
  firebase_core: ^2.26.0
  firebase_dynamic_links: ^5.4.16
  firebase_crashlytics: ^3.4.17
  firebase_analytics: ^10.8.8
  firebase_messaging: ^14.7.18
  firebase_remote_config: ^5.1.0

**Comment by SelaseKay** [comment]
Hi @tyagnesh-mufin , there's a way around it but it will be ideal to update your dependencies since the workaround might cause some breaking changes. The firebase plugins often depend on each other.

**Comment by tyagnesh-mufin** [comment]
@SelaseKay I understand your point, but right now I need to update only Firebase Analytics due to a fast update release. In the next version of the app, I plan to update all Firebase components to the latest release. Can you provide detailed instructions on how to update only Firebase Analytics in the meantime?


i have also one another issue if i update all firebase dependancy in flutter i receive new error is like

`Execution failed for task ':app:checkDevDebugDuplicateClasses'.
 A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
    Duplicate class com.google.firebase.iid.FirebaseInstanceIdReceiver found in modules jetified-firebase-iid-20.1.5-runtime (com.google.firebase:firebase-iid:20.1.5) and jetified-firebase-messaging-24.0.1-runtime (com.google.firebase:firebase-messaging:24.0.1)`

**Comment by SelaseKay** [comment]
I think what you can do is use the latest version of `firebase_core` under dependencies:
```
dependencies:
  firebase_core: 3.4.0
```
and override it to your current version like so:
```
dependency_overrides:
  firebase_core: ^2.26.0
```

**Comment by SelaseKay** [comment]
I think what you can do is use the latest version of `firebase_core` under dependencies:
```
dependencies:
  firebase_core: 3.4.0
```
and override it to your current version like so:
```
dependency_overrides:
  firebase_core: ^2.26.0
```
