### ISSUE TITLE
firebase_auth: Can not Sign in with Apple when upgrading from firebase_auth 5.1.4 to 5.2.0

### ISSUE THREAD

**Issue by beastoin** [firebase/flutterfire#13242]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Auth

### Which platforms are affected?

iOS

### Description

When upgrade from version 5.1.4 to 5.2.0, our user can not sign-in with Apple anymore, happen with new account.

log:

```
flutter: ID Token: eyJraWQi...m8ag
flutter: Attempting to sign in with Firebase...
flutter: FirebaseAuthException: invalid-credential - Invalid OAuth response from apple.com
flutter: Please check Firebase console configuration for Apple Sign In.
flutter: Token: null
```

there have also a breaks changes warning in pod, in-case any help for your guys on resolving the issue.

<img width="927" alt="Screenshot 2024-09-01 at 06 20 43" src="https://github.com/user-attachments/assets/7b082f76-9e4a-42c2-a542-ad9f650024fa">

### Reproducing the issue

1. create an flutter app, with Sign-in with Apple, use firebase auth 5.1.4, e.g. https://github.com/BasedHardware/Omi
   ```
   firebase_auth: 5.1.4
   ```
2. update static ver in pubspec.yaml
   ```
   firebase_auth: 5.2.0
   ```
   or just let it up-to-date
    ```
   firebase_auth: ^5.1.4
   ```
3. run app from 1, again

### Firebase Core version

3.3.0

### Flutter Version

3.24.1

### Relevant Log Output

```shell
flutter: ID Token: eyJraWQi...m8ag
flutter: Attempting to sign in with Firebase...
flutter: FirebaseAuthException: invalid-credential - Invalid OAuth response from apple.com
flutter: Please check Firebase console configuration for Apple Sign In.
flutter: Token: null
```
```


### Flutter dependencies

<!--- Look below for instructions on how to share your Flutter Dependencies. --->

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by SelaseKay** [comment]
Hi @beastoin , this issue appears to be related to [this](https://github.com/firebase/flutterfire/issues/13235). Kindly refer to see if it helps.

**Comment by beastoin** [comment]
> Hi @beastoin , this issue appears to be related to [this](https://github.com/firebase/flutterfire/issues/13235). Kindly refer to see if it helps.

yes man, we can fix it by updating our code or just stick with the previous version. however, i think there should be the better way to prevent these kinds of break changes in a minor upgrade. you know that a minor upgrade should not introduce any break changes, or the system might down.

**Comment by iktakahiro** [comment]
Hi, thank you for creating and discussing this issue. I experienced the same problem in our application, and it has been resolved. However, is setting the authorizationCode the correct solution? This approach is not reflected in the official Firebase documentation, and I also believe that such changes should not be introduced silently.
