### ISSUE TITLE
[firebase_messaging]: the package sometimes listen to notifications ( data message ) ,and sometimes not 

### ISSUE THREAD

**Issue by Joseph-Nathan** [firebase/flutterfire#13248]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Messaging

### Which platforms are affected?

Android

### Description

This happened after I updated flutter and released the package to the highest version,
Not all incoming notifications ( data message ) are listened to, randomly some may appear and some may not appear,
that happen in Foreground and Background 

### Reproducing the issue

Use the package to receive 10 notifications within a time period of 5 minutes for example .
 Expected to receive 6 out of 10 notifications at most.

### Firebase Core version

2.16.0

### Flutter Version

3.24.1

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

this appear when my data message display on device .

[+23749 ms] V/ActivityThread(15131): scheduleReceiver info = ActivityInfo{1984e15 io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingReceiver} intent = Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x11080010 pkg=MY_PACKAGE_NAME cmp=cMY_PACKAGE_NAME/io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingReceiver (has extras) } sync = true hasCode = 254605833
[   +1 ms] D/FLTFireMsgReceiver(15131): broadcast received for message
[  +24 ms] V/ActivityThread(15131): scheduleReceiver info = ActivityInfo{ad831f7 com.google.firebase.iid.FirebaseInstanceIdReceiver} intent = Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x11080010 pkg=com.eteaching.da7ee7 cmp=MY_PACKAGE_NAME/com.google.firebase.iid.FirebaseInstanceIdReceiver (has extras) } sync = true hasCode = 265587772

**Comment by SelaseKay** [comment]
Hi @Joseph-Nathan , I'm unable to reproduce this. Kindly provide a sample code reproducing this issue.

**Comment by Joseph-Nathan** [comment]
Hi @SelaseKay  ,
thanks for you time ,
could you please try with 
```
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
```
and 
```
    ext.kotlin_version = '1.9.0'
```
and
```
classpath 'com.android.tools.build:gradle:7.3.0'
```
and
```
distributionUrl=https\://services.gradle.org/distributions/gradle-8.4-rc-2-all.zip
```

**Comment by SelaseKay** [comment]
This is not a sample code. I'd need a full sample code reproducing this issue.

**Comment by Joseph-Nathan** [comment]
the problem was in my backend , sorry for you time .
