### ISSUE TITLE
[firebase_app_check]: PERMISSION_DENIED

### ISSUE THREAD

**Issue by heshesh2010** [firebase/flutterfire#13258]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

App Check

### Which platforms are affected?

iOS

### Description

App attestation failed.

### Reproducing the issue

Hello , I teseting firebase phone auth on flutter , but it's needs app check to got token , so I have got the debug token and saved it to firebase console  , but I got error :
`11.0.0 - [FirebaseAuth][I-AUT000018] Error getting App Check token; using placeholder token instead. Error: Error Domain=com.google.app_check_core Code=0 "Too many attempts. Underlying error: The operation couldn’t be completed. The server responded with an error: 
 - URL: https://firebaseappcheck.googleapis.com/v1/projects/loklok-jiftun/apps/1:839324697722:ios:5a0194b81def8064f6e7c3:exchangeDeviceCheckToken 
 - HTTP status code: 403 
 - Response body: {
  "error": {
    "code": 403,
    "message": "App attestation failed.",
    "status": "PERMISSION_DENIED"
  }
}
" UserInfo={NSLocalizedFailureReason=Too many attempts. Underlying error: The operation couldn’t be completed. The server responded with an error: 
 - URL: https://firebaseappcheck.googleapis.com/v1/projects/loklok-jiftun/apps/1:839324697722:ios:5a0194b81def8064f6e7c3:exchangeDeviceCheckToken 
 - HTTP status code: 403 
 - Response body: {
  "error": {
    "code": 403,
    "message": "App attestation failed.",
    "status": "PERMISSION_DENIED"
  }
}
}`

### Firebase Core version

^3.4.0

### Flutter Version

3.24

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by SelaseKay** [comment]
Kindly provide a sample code reproducing this issue

**Comment by heshesh2010** [comment]
> Kindly provide a sample code reproducing this issue

kindly share your email so I can add you to my private repo in gitlap

**Comment by SelaseKay** [comment]
Kindly create a mini project on github which reproduces the issue and share link here.
[How to create a Minimal, Reproducible Example - Help Center](https://stackoverflow.com/help/minimal-reproducible-example)
