### ISSUE TITLE
[firebase_auth]: User is not loaded on secondary app launch

### ISSUE THREAD

**Issue by KestasVenslauskas** [firebase/flutterfire#13251]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Auth

### Which platforms are affected?

iOS

### Description

We just updated to `firebase_auth: 5.2.0` and started seeing this error on app launch for iOS. Because of this every fresh app start does not load user session and loads as if there was never logged in user.

`[[FirebaseAuth]] 11.0.0 - [FirebaseAuth][I-AUT000001] Error loading saved user when starting up: Error Domain=FIRAuthErrorDomain Code=17072 "The provided user's tenant ID does not match the Auth instance's tenant ID." UserInfo={FIRAuthErrorUserInfoNameKey=ERROR_TENANT_ID_MISMATCH, NSLocalizedDescription=The provided user's tenant ID does not match the Auth instance's tenant ID.}`

As I understand we could set the tennatID somewhere in the swift code for iOS but the problem is that we do not want it hardcoded.
We do have a backend that return as the tenantID after we get custom JWT from a custom auth provider.

### Reproducing the issue

- Run the app using firebase_auth iOS SDK 11.0.0
- Login into the app.
- Kill the app.
- Launch app again.
- Observe user is logged out

### Firebase Core version

3.4.0

### Flutter Version

3.24.1

### Relevant Log Output

```shell
[[FirebaseAuth]] 11.0.0 - [FirebaseAuth][I-AUT000001] Error loading saved user when starting up: Error Domain=FIRAuthErrorDomain Code=17072 "The provided user's tenant ID does not match the Auth instance's tenant ID." UserInfo={FIRAuthErrorUserInfoNameKey=ERROR_TENANT_ID_MISMATCH, NSLocalizedDescription=The provided user's tenant ID does not match the Auth instance's tenant ID.}
```

**Comment by SelaseKay** [comment]
Hi @KestasVenslauskas , Kindly provide a sample code reproducing this issue.

**Comment by KestasVenslauskas** [comment]
@SelaseKay I'm sorry but we do have basic integration. There is nothing in native code apart `FirebaseApp.configure()`.
Only thing is that our project uses multi-tenant approach but that's not code setup it's GCP config.

**Comment by SelaseKay** [comment]
I'd need a sample code to be able to reproduce this issue. This on the other hand seems to be an IOS native SDK issue which is out of scope for this repo. Is the project a flutter project?

**Comment by KestasVenslauskas** [comment]
@SelaseKay yes this is a flutter project, but issues seems to be on IOS native SDK version 11.0.0. I will forward this issue.
