### ISSUE TITLE
[FirebaseCore][I-COR000008] The project's Bundle ID is inconsistent

### ISSUE THREAD

**Issue by stefandric** [firebase/flutterfire#13264]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Core

### Which platforms are affected?

iOS

### Description

I’ve encountered an issue where Firebase initialization in my Flutter app on iOS ignores custom-named plist files. I have everything configured correctly in my project, including multiple .plist files for different environments (e.g., GoogleService-Info-dev.plist for development).

Also I have a setup for using different .plist files for **GOOGLE_SERVICE_INFO** key.

When I run an env using different .plist file than GoogleService-Info.plist I am getting an error:

`10.29.0 - [FirebaseCore][I-COR000008] The project's Bundle ID is inconsistent with either the Bundle ID in 'GoogleService-Info.plist', or the Bundle ID in the options if you are using a customized options. To ensure that everything can be configured correctly, you may need to make the Bundle IDs consistent. To continue with this plist file, you may change your app's bundle identifier to 'xx.xxxxxxxx.xxx'. Or you can download a new configuration file that matches your bundle identifier from https://console.firebase.google.com/ and replace the current one.`

Everything worked fine and what I did is that I renamed my custom plist file to GoogleService-Info.plist file and the error is gone. 

It looks like a setting in xcode for different file names is ignored.

Here is my setup:

![Screenshot 2024-09-03 at 12 00 42](https://github.com/user-attachments/assets/91d9fa28-8e66-4b4f-a708-45364bc38129)
![Screenshot 2024-09-03 at 12 01 02](https://github.com/user-attachments/assets/3ce5ea4d-b03c-4ca2-9f3b-f6c76aec1f15)

### Reproducing the issue

- set different environments using flutterfire
- set plist names depending on config
- initialize flutter firebase app with different config files

### Firebase Core version

3.3.0

### Flutter Version

3.24.0

### Relevant Log Output

```shell
flutter doctor -v
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.6.1 23G93 darwin-arm64, locale en-AT)
    • Flutter version 3.24.0 on channel stable at /Users/stefandric/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (5 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/stefandric/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.92.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (7 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554                        • android-arm64  • Android 13 (API 33) (emulator)
    • Stefan’s iPhone (mobile)        • 00008101-0008342A2638001E            • ios            • iOS 17.6.1 21G93
    • iPhone 15 Plus (mobile)         • 2D7F7936-E943-40EE-8D92-61D44D5E6EFA • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • iPhone 15 Pro Max (mobile)      • A148EBCE-A00B-4717-936A-5D30E9E643AC • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.6.1 23G93 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 128.0.6613.114

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

 firebase_core: ^3.3.0
  firebase_analytics: ^11.2.1
  firebase_crashlytics: ^4.0.4
  firebase_messaging: ^15.0.4
```

</details>

**Comment by SelaseKay** [comment]
Kindly provide a sample minimal code or github repo reproducing this issue

**Comment by stefandric** [comment]
@SelaseKay Thank you for your response.

Here is the code I have, everything is generated through flutterfire cli.

`import 'package:xxxx/firebase_options.dart';
import 'package:xxxx/firebase_options_dev.dart' as dev;


extension EnvExt on Environment {
  Future<void> firebaseInit() async {
    if (this == Environment.production) {
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );
    } else {
      await Firebase.initializeApp(
          options: dev.DefaultFirebaseOptions.currentPlatform);
    }
  }
`

Both firebase options are correct and having different ids. Even though I have added dynamic GOOGLE_SERVICE_INFO flag that returns different GoogleService-Info.plist files, it seems it is ignored and it always finds the default one. I've tested it with setting even a hardcoded value GoogleServiceInfo-dev for GOOGLE_SERVICE_INFO to my custom plist name and it is ignored. If I rename my GoogleService-Info-dev.plist to GoogleService-Info.plist it works like a charm. This gives me an impression that GOOGLE_SERVICE_FLAG is ignored when looking for .plist file.

**Comment by SelaseKay** [comment]
This appears to be a misconfiguration from your end and out of scope for FF repo. Kindly refer [here](https://stackoverflow.com/questions/37615405/use-different-googleservice-info-plist-for-different-build-schemes) to see if it helps. I will go ahead and close this issue for now.
