### ISSUE TITLE
[firebase_messaging] APNS token has not been set yet. Please ensure the APNS token is available by calling getAPNSToken()

### ISSUE THREAD

**Issue by phamquoctrongnta** [firebase/flutterfire#13273]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Description

**SORRY FOR MY BAD ENGLISH**
I have the same issue: #12244
Because this topic is closed, I re-open this issue.
When I add delayed code before `.getToken()` method, it's work:
```
await Future.delayed(const Duration(seconds: 1));
final fcmToken = await FirebaseMessaging.instance.getToken(); // Has token
```
but no  delayed code is not work:
```
final fcmToken = await FirebaseMessaging.instance.getToken(); // Return null
```
What exactly solution?

### Reproducing the issue

1. Open app first time.
2. Call `getToken()` method -> Return null
3. Close app -> Reopen app -> Return token.

### Firebase Core version

2.10.0

### Flutter Version

3.22.2

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by SelaseKay** [comment]
Hi @phamquoctrongnta , you'll have to await the token like so
```
final fcmToken = await FirebaseMessaging.instance.getToken();
```

**Comment by phamquoctrongnta** [comment]
When I update to latest version:
```
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
```
this issue still occurs.

**Comment by SelaseKay** [comment]
I'm unable to reproduce this issue. Please share a full sample code reproducing this issue. Are you experiencing this on iOS or Android?

**Comment by phamquoctrongnta** [comment]
@SelaseKay 
Only iOS.
Try build in release mode please, not error in debug mode.

**Comment by wangjian115** [comment]
Is there any good way to deal with it?
And when running on iOS 18.1, it cannot be obtained, no matter how much delay is added.

**Comment by OutdatedGuy** [comment]
@phamquoctrongnta it is due to changes in iOS SDK after v10.4.0. [See documentation](https://firebase.google.com/docs/cloud-messaging/flutter/client#access_the_registration_token).

You will have to first wait for APNs token on iOS and then try to get FCM token

e.g.

```dart
Future<String?> getFCMToken() async {
  if (Platform.isIOS) {
    final apnsToken = await FirebaseMessaging.instance.getAPNSToken();
    if (apnsToken == null) return null;
  }

  final deviceFCMToken = await FirebaseMessaging.instance.getToken();
  return deviceFCMToken;
}
```

**Comment by phamquoctrongnta** [comment]
@OutdatedGuy 
Thanks for your support.
Look like it's good answer.
I will check it.

**Comment by EliseiNicolae** [comment]
Still getting the error...
I tried the solution from @OutdatedGuy , but didn't work for me.

I'm using xcode v16

firebase_core: ^3.3.0
firebase_messaging: ^15.0.4

**Comment by phamquoctrongnta** [comment]
@EliseiNicolae 
I do not test @OutdatedGuy  's solution yet.
If you have tested within an error, I will be reopen this issue.

**Comment by EliseiNicolae** [comment]
I fixed my issue by adding:
```
    FirebaseMessaging messaging = FirebaseMessaging.instance;
    await messaging.requestPermission(
      alert: true,
      announcement: true,
      badge: true,
      carPlay: false,
      criticalAlert: true,
      provisional: true,
      sound: true,
    );
```

**Comment by russellwheatley** [comment]
As mentioned in this thread, you will need to wait for the APNS token to become available and it is necessary to request permission of the user.

**Comment by WieFel** [comment]
> As mentioned in this thread, you will need to wait for the APNS token to become available and it is necessary to request permission of the user.

@russellwheatley could you please provide a clear way of how to do that?
I encounter the problem in 165 cases in the last 90 days (crashlytics), but I am not able to reproduce it on my physical iOS device. So I can't just start guessing solutions and throwing them out to production to see if they might work...

Is this a valid approach? According to people's feedback, this also doesn't solve it.
> ```dart
> Future<String?> getFCMToken() async {
>   if (Platform.isIOS) {
>     final apnsToken = await FirebaseMessaging.instance.getAPNSToken();
>     if (apnsToken == null) return null;
>   }
> 
>   final deviceFCMToken = await FirebaseMessaging.instance.getToken();
>   return deviceFCMToken;
> }
> ```

Seems that all issues regarding this topic just get closed, without providing any clear way of solving it.
