### ISSUE TITLE
[fiarebase_auth: Lexical or Preprocessor Issue :  non-modular header inside framework module

### ISSUE THREAD

**Issue by nissaba** [firebase/flutterfire#13280]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Auth

### Which platforms are affected?

iOS

### Description

Firebase auth is preventing the building of my project.
If I remove firebase auth from vergin flutter project ti will build, if it is present it will fail. 

### Reproducing the issue

1) create a new flutter project. 
2) add firebase_core, firebase_auth and cloud_firestore, update pubspec
3) run the project

### Firebase Core version

3.4.0

### Flutter Version

3.24.1 

### Relevant Log Output

```shell
Could not build the precompiled application for the device.
Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.FLTAuthStateChannelStreamHandler': '/Users/user/StudioProjects/for_fuck_sake/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/user/.pub-cache/hosted/pub.dev/firebase_auth-5.2.0/ios/Classes/Private/FLTAuthStateChannelStreamHandler.h:12:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.PigeonParser': '/Users/user/StudioProjects/for_fuck_sake/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/user/.pub-cache/hosted/pub.dev/firebase_auth-5.2.0/ios/Classes/Private/PigeonParser.h:6:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.FLTIdTokenChannelStreamHandler': '/Users/user/StudioProjects/for_fuck_sake/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/user/.pub-cache/hosted/pub.dev/firebase_auth-5.2.0/ios/Classes/Private/FLTIdTokenChannelStreamHandler.h:12:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.FLTPhoneNumberVerificationStreamHandler': '/Users/user/StudioProjects/for_fuck_sake/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/user/.pub-cache/hosted/pub.dev/firebase_auth-5.2.0/ios/Classes/Private/FLTPhoneNumberVerificationStreamHandler.h:12:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.FLTFirebaseAuthPlugin': '/Users/user/StudioProjects/for_fuck_sake/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/user/.pub-cache/hosted/pub.dev/firebase_auth-5.2.0/ios/Classes/Public/FLTFirebaseAuthPlugin.h:6:8
```

### Flutter dependencies

<details>
<summary>Expand <code>
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.4.0
  cloud_firestore: ^5.4.0
  firebase_auth: ^5.2.0
</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by SelaseKay** [comment]
Hi @nissaba , I'm unable to reproduce this issue. I suspect it could have something to do with your Xcode configurations. Kindly refer [here](https://stackoverflow.com/questions/66148505/flutter-include-of-non-modular-header-inside-framework-module-firebase-core-fl).

**Comment by pilgrim1385** [comment]
When I upgraded Xcode to version 16.1.0-Beta, my flutter project couldn’t run on iOS Simulator. Almost same issue, except mine was caused by Crashlytics. After making the following changes, my project ran successfully:

1. Modified the PROJECT - Runner - Build Settings:
`CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = YES`

2. Modified the TARGETS - Runner - Build Settings:
`CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = YES`

![5fe0be54-8158-4b43-bd48-02d42a56f308](https://github.com/user-attachments/assets/64fc90a7-cb86-44da-b776-8c40d78c625c)

3. Added the following to the Podfile:
```
target.build_configurations.each do |config|
  config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
end
```

![30de4c42-a885-465d-9a39-6db68c2d9c68](https://github.com/user-attachments/assets/2065843f-3843-431b-9bf4-858b58f65162)

4. run `pod install`

Then try run your project on iOS.

**Comment by nissaba** [comment]
> When I upgraded Xcode to version 16.1.0-Beta, my flutter project couldn’t run on iOS Simulator. Almost same issue, except mine was caused by Crashlytics. After making the following changes, my project ran successfully:
> 
> 1. Modified the PROJECT - Runner - Build Settings:
>    `CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = YES`
> 2. Modified the TARGETS - Runner - Build Settings:
>    `CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = YES`
> 
> ![5fe0be54-8158-4b43-bd48-02d42a56f308](https://private-user-images.githubusercontent.com/8338907/365356337-64fc90a7-cb86-44da-b776-8c40d78c625c.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4OTc3MDksIm5iZiI6MTcyNTg5NzQwOSwicGF0aCI6Ii84MzM4OTA3LzM2NTM1NjMzNy02NGZjOTBhNy1jYjg2LTQ0ZGEtYjc3Ni04YzQwZDc4YzYyNWMuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDE1NTY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwZGZkMWRkZjk5Y2NhYjFkNDFmNTMxMGE0MGJhNGY5MDg4OTJmNWNkZjNjYTZlZjI1ZjNhMGRkYTU1MmFkNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.woVycgwXhEQ4SmK_sDj-JeGBXy3PHT8g1M8e3lSJiIk)
> 
> 3. Added the following to the Podfile:
> 
> ```
> target.build_configurations.each do |config|
>   config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
> end
> ```
> 
> ![30de4c42-a885-465d-9a39-6db68c2d9c68](https://private-user-images.githubusercontent.com/8338907/365356592-2065843f-3843-431b-9bf4-858b58f65162.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4OTc3MDksIm5iZiI6MTcyNTg5NzQwOSwicGF0aCI6Ii84MzM4OTA3LzM2NTM1NjU5Mi0yMDY1ODQzZi0zODQzLTQzMWItOWJmNC04NThiNThmNjUxNjIuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDE1NTY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkOGRiOGQwZjc2ZjEyYTE1Y2UxNTZmOGM2M2JjNDI3ZDUzYTE5MGVjZGYzOGJmZDFkYmRjYTg5NTA5ZmFjYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VXevGBkpKzGVS1C-9OXMfqM8ADmVU-TvZiS5qmK95mE)
> 
> 4. run `pod install`
> 
> Then try run your project on iOS.

This does work. I had found a stackOverflow with the update for the podfile, but they had not included to update the clan module rules. 

Thanks!

**Comment by mikemilla** [comment]
Worked for me too
