### ISSUE TITLE
firebase_messaging_web 3.8.13  which depends on web ^0.5.1, other package depends on web ^1.0.0

### ISSUE THREAD

**Issue by ankitparmar007** [firebase/flutterfire#13282]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Messaging

### Which platforms are affected?

Web

### Description

Unable to use Firebase messaging for web as it depends on lower version of the web package

### Reproducing the issue

Try to use any package that depends upon web ^1.0.0 [https://pub.dev/packages/web] (Web Package)

### Firebase Core version

^3.4.0

### Flutter Version

3.24.1

### Relevant Log Output

```shell
Because cached_network_image >=3.4.1 depends on cached_network_image_web ^1.3.1 which depends on web ^1.0.0, cached_network_image >=3.4.1 requires web ^1.0.0.
And because firebase_messaging >=15.1.0 depends on firebase_messaging_web ^3.8.13 which depends on web ^0.5.1, cached_network_image >=3.4.1 is incompatible with firebase_messaging >=15.1.0.
So, because trending_homes depends on both firebase_messaging 15.1.0 and cached_network_image 3.4.1, version solving failed.
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by ankitparmar007** [comment]
Also same for firebase_core

Because cached_network_image >=3.4.1 depends on cached_network_image_web ^1.3.1 which depends on web ^1.0.0, cached_network_image >=3.4.1 requires web ^1.0.0.
And because firebase_core >=3.4.0 depends on firebase_core_web ^2.17.5 which depends on web ^0.5.1, cached_network_image >=3.4.1 is incompatible with firebase_core >=3.4.0.
So, because trending_homes depends on both firebase_core 3.4.0 and cached_network_image 3.4.1, version solving failed.

**Comment by SelaseKay** [comment]
Hi @ankitparmar007 , this is a duplicate. [13190](https://github.com/firebase/flutterfire/issues/13190)
