### ISSUE TITLE
[flutterfire]: 100% usage building for iOS

### ISSUE THREAD

**Issue by YarosMallorca** [firebase/flutterfire#13288]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Core, Other

### Which platforms are affected?

iOS

### Description

When building for iOS (debug and release builds) the CPU goes to 100% and in Activity monitor I can see lots of "Clang" processes taking all the CPU resources.

<img width="400px" alt="Screenshot 2024-09-07 at 23 34 47" src="https://github.com/user-attachments/assets/a4bf6569-b6e6-48af-8383-ff630483890a">

### Reproducing the issue

1. Create a Flutter project with the latest stable version
2. Using Flutterfire CLI add iOS Firebase support, and add plugins like Firebase Core, Analytics, etc...
3. Try to build for iOS

I only tested this on a Macbook Air M3 as I don't have access to another Mac.

### Firebase Core version

2.24.2

### Flutter Version

3.24.1

**Comment by SelaseKay** [comment]
Hi @YarosMallorca , thanks for the report. The high CPU usage from Clang during iOS builds is expected as it's responsible for compiling the project. This behavior is not related to FlutterFire. Closing this issue as it's unrelated to FlutterFire.

**Comment by YarosMallorca** [comment]
@SelaseKay This does not happen when the project does not include Flutter fire tho.

When it does, the temperature of the CPU often reaches 98°C.

**Comment by SelaseKay** [comment]
That's strange. I tested on M1 and it seemed quite normal.
