### ISSUE TITLE
firebase_crashlytics: flutter iOS dart code symbol files not uploading to crashlytics

### ISSUE THREAD

**Issue by maheshjadhav8378** [firebase/flutterfire#13283]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Crashlytics

### Which platforms are affected?

iOS

### Description

Crashes for iOS stack trace are obfuscated on Crashlytics when creating release build for iOS using the following command 

flutter build ipa  --obfuscate --split-debug-info=obfuscate/xxx --extra-gen-snapshot-options=--save-obfuscation-map=obfuscate/xxx/ios.mapping.json

This process creates the files:
 app.ios-arm64.symbols and 
ios.mapping.json

The resulting crash log stacks trace is obfuscated and not readable

As per     [Flutter Fire Documentation](https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=flutter) , my application satisfies the min requirement for the min SDK versions (Flutter 3.12.0+ and Crashlytics Flutter plugin 3.3.4+ )

Following are the details of the version
Flutter (Channel stable, 3.16.9,
firebase_core: ^2.17.0
firebase_crashlytics: ^3.3.5

### Reproducing the issue

1. Create flutter app and configure firebase crashlytics
2. 
3. Create release build using the command 
flutter build ipa  --obfuscate --split-debug-info=obfuscate/xxx --extra-gen-snapshot-options=--save-obfuscation-map=obfuscate/xxx/ios.mapping.json

4. Upload build to Testflight
5. Force crash and observe that crash stack trace is obfuscated
6. Manually upload the symbol files to crashlytics
7.  Force crash and observe that crash stack trace is still obfuscated

### Firebase Core version

2.17.0

### Flutter Version

3.16.9

### Relevant Log Output

```shell
Fatal Exception: FlutterError
0  ???                            0x0 (null).    #00 abs 000000010c4ac4db _kDartIsolateSnapshotInstructions+0x4ce19b
1  ???                            0x0 (null).    #01 abs 000000010c1739e7 _kDartIsolateSnapshotInstructions+0x1956a7
2  ???                            0x0 (null).    #02 abs 000000010c1737b7 _kDartIsolateSnapshotInstructions+0x195477
3  ???                            0x0 (null).    #03 abs 000000010c4b8ab7 _kDartIsolateSnapshotInstructions+0x4da777
4  ???                            0x0 (null).    #04 abs 000000010c3d8c8b _kDartIsolateSnapshotInstructions+0x3fa94b
5  ???                            0x0 (null).    #05 abs 000000010c36b87b _kDartIsolateSnapshotInstructions+0x38d53b
6  ???                            0x0 (null).    #06 abs 000000010c37a667 _kDartIsolateSnapshotInstructions+0x39c327
7  ???                            0x0 (null).    #07 abs 000000010c36764f _kDartIsolateSnapshotInstructions+0x38930f
8  ???                            0x0 (null).    #08 abs 000000010c3673e3 _kDartIsolateSnapshotInstructions+0x3890a3
9  ???                            0x0 (null).    #09 abs 000000010c46ce4b _kDartIsolateSnapshotInstructions+0x48eb0b
10 ???                            0x0 (null).    #10 abs 000000010c0d573f _kDartIsolateSnapshotInstructions+0xf73ff
11 ???                            0x0 (null).    #11 abs 000000010c3aaf8b _kDartIsolateSnapshotInstructions+0x3ccc4b
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by SelaseKay** [comment]
Hi @maheshjadhav8378 , thanks for the report. Can you confirm if your dSYM files were uploaded?

**Comment by maheshjadhav8378** [comment]
Hi @SelaseKay, thanks for responding. Yes, I tried uploading dSYM files manually as well but, still stack traces for  new exceptions were obfuscated on Firebase Crashlytics for iOS.

**Comment by SelaseKay** [comment]
Can you confirm it has been uploaded? Kindly check your Crashlytics dashboard. If you see `Missing dSYM`, it means it wasn't uploaded.

**Comment by maheshjadhav8378** [comment]
I can see missing Optional dSYM file on Crashlytics.

**Comment by SelaseKay** [comment]
Kindly share a screenshot

**Comment by maheshjadhav8378** [comment]
For build **0.0.1 (2024090302)**, 

![Screenshot 2024-09-09 at 2 21 02 PM](https://github.com/user-attachments/assets/62b4a18b-f4cc-4137-b1d2-8687d6863388)
![Screenshot 2024-09-09 at 2 21 21 PM](https://github.com/user-attachments/assets/4f7a673e-1044-401f-8e74-b438779c980a)

**Comment by SelaseKay** [comment]
Have you tried the iOS specific steps as stated [here](https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=ios)?

**Comment by maheshjadhav8378** [comment]
Yes, I have followed these steps, 


![Screenshot 2024-09-09 at 2 39 37 PM](https://github.com/user-attachments/assets/92ca852d-664b-4b6a-bfd9-ee44bfb55cac)
![Screenshot 2024-09-09 at 2 40 59 PM](https://github.com/user-attachments/assets/77431b18-f338-43df-92d4-163aa23fbf5a)


Also I uploaded dSYM files manually on Crashlytics dashboard by finding those manually [as per steps for manually locating dSYMs](https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=ios#locate)

**Comment by russellwheatley** [comment]
@maheshjadhav8378 - FlutterFire CLI takes care of uploading debug symbols. Please configure your app using the latest FlutterFire CLI:
```
dart pub global activate flutterfire_cli 1.0.1-dev.4
```
Rebuild your app:
```
flutter build ipa --obfuscate --split-debug-info=obfuscate/xxx
```
and let me know if this fixes your issue.

**Comment by maheshjadhav8378** [comment]
Thanks @russellwheatley. I will try doing this.

**Comment by Tom3652** [comment]
Hi @russellwheatley hope you are doing great, i confirm that the `flutterfire_cli` is taking care of this without issue !

However from my previous releases the past few months i have seen that [Flutter DSYM](https://github.com/flutter/flutter/issues/116493) was missing from the iOS archive when obfuscating the build until the fix 2 weeks ago. 

Will `flutterfire_cli` also upload it once it's in the archive folder ? 
Or is it already uploading the Flutter DSYM from another location ? 

I have (fortunately !) not enough crashlytics traces from my apps to check if the Flutter DSYM is still missing as it was few months ago

Thanks !

**Comment by russellwheatley** [comment]
Hey @Tom3652 - I'm not sure what you're asking I'm afraid. The DYSM file path is set for the upload symbols tool here: https://github.com/invertase/flutterfire_cli/blob/main/packages/flutterfire_cli/lib/src/commands/upload_symbols.dart#L376

It gets the DSYM path using the Xcode environment variable here:https://github.com/invertase/flutterfire_cli/blob/main/packages/flutterfire_cli/lib/src/firebase/firebase_apple_writes.dart#L377

This is a script that runs when you build your app.

If you want to see what that path looks like, run `xcodebuild -showBuildSettings` in your ios/ directory which will show you the debug symbol path variable which is `DWARF_DSYM_FOLDER_PATH`. Hope this helps.

Thanks for confirming it works 👍 . If you do think there is a bug, please open an issue on: https://github.com/invertase/flutterfire_cli 🙏

**Comment by Tom3652** [comment]
Well unfortunately @russellwheatley i have spoken a bit too fast 😅 here is what my crashlytics dashboard looks like today (the release 1.1.0 was made using the current version of all the firebase products including crashlytics and `flutterfire_cli`) : 

<img width="934" alt="Capture d’écran 2024-10-08 à 09 29 09" src="https://github.com/user-attachments/assets/f6b96c9c-cf86-4faf-a5f5-0fae94a489ba">

I have raised an issue in Firebase Support to help understand why i have missing dSYM

I have run the commands : `mdfind -name .dSYM | while read -r line; do dwarfdump -u "$line"; done`  and `dwarfdump -u <path-to-dsym>` to check all my dSYM UUIDs and i could not find the ones Crashlytics is requiring... 

I will raise and link an issue to https://github.com/invertase/flutterfire_cli 🙏
