### ISSUE TITLE
[firebase_auth]: Upgrade dependency 'web' to ^1.0.0 in firebase_auth_web

### ISSUE THREAD

**Issue by olof-dev** [firebase/flutterfire#13286]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Auth

### Which platforms are affected?

Android, iOS, Web

### Description

Many packages now depend on the 'web' package ^1.0.0, which is incompatible with firebase_auth's dependency on firebase_auth_web, which has `web: ^0.5.1` specified. This means any app that depends on firebase_auth is prevented from updating dependency versions for many other packages.

Since 1.0.0 represents an update to a stable version of the web package, it'd be good to update the dependency ASAP. 

### Reproducing the issue

Create a new Flutter project and add dependencies:

```yaml
dependencies:
  firebase_auth: ^5.2.0
  share_plus: ^10.0.2
```

### Firebase Core version

3.4.0

### Flutter Version

3.24.1

### Relevant Log Output

```shell
Because firebase_auth >=5.2.0 depends on firebase_auth_web ^5.12.6 which depends on web ^0.5.1, firebase_auth >=5.2.0 requires web ^0.5.1.
And because share_plus >=10.0.1 depends on web ^1.0.0, firebase_auth >=5.2.0 is incompatible with share_plus >=10.0.1.
So, because firebase_dep depends on both share_plus ^10.0.2 and firebase_auth ^5.2.0, version solving failed.
```

**Comment by Muslimdeveloper1444** [comment]
i have this problem to

**Comment by Parthib** [comment]
+1

**Comment by SelaseKay** [comment]
Hi @Parthib , this issue already exists. [13190](https://github.com/firebase/flutterfire/issues/13190)

**Comment by olof-dev** [comment]
Ah, I didn't find it because it didn't mention firebase_auth, which is what had the conflict for me. Sorry for the extra issue!

**Comment by SelaseKay** [comment]
Add 
```
dependency_overrides:
  web: 1.0.0

```
to your pubspec file
