### ISSUE TITLE
[firebase_analytics]: <Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)>

### ISSUE THREAD

**Issue by hasen6** [firebase/flutterfire#13291]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Analytics

### Which platforms are affected?

iOS

### Description

Added firebase to my new flutter project using firebase CLI and it all runs fine with remote config and core:

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.0
  firebase_remote_config: ^5.1.0
  
  as soon as I add firebase_analytics it fails to build

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.0
  firebase_remote_config: ^5.1.0
  firebase_analytics: ^11.3.0

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MainApp());
}

Error:

Failed to build iOS app
Error (Xcode): Undefined symbols:

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

Could not build the application for the simulator.

I've tried so many things, been through it all with different AI, recommendations on stackoverflow, nothing works. If I build with xcodebuild -verbose  it says:

fatal error: module
      'firebase_analytics' not found
@import firebase_analytics;

I've tried this: https://stackoverflow.com/questions/66685348/flutter-fatal-error-module-firebase-analytics-not-found and also this:

Remove ios/Pods folder.
Copy podfile and keep it outside of your directory.
Remove podfile and podfile.lock
Remove pubspec.lock .
Run pod cache clean —all in terminal
Run flutter clean in terminal
Run flutter pub get in terminal
Copy the back up podfile, to newly regenerated podfile.
Run pod install in terminal
Build your project. Once successful, then archive.

### Reproducing the issue

1. Install a new flutter project for iOS
2. Create ios project at firebase console
3. add dependencies   firebase_core: ^3.4.0  firebase_remote_config: ^5.1.0  firebase_analytics: ^11.3.0
4. Add the google info plist into the xcode project.
5. Run flutterfire in project's terminal to create the files required by firebase for flutter.
6. add pod 'Firebase/Analytics' into target 'Runner' in podfile, run pod install etc
7. Try to run or build app.

### Firebase Core version

3.4.0

### Flutter Version

3.24.2

### Relevant Log Output

```shell
fatal error: module 'firebase_analytics' not found
@import firebase_analytics;
 ~~~~~~~^~~~~~~~~~~~~~~~~~
1 error generated.
```

### Flutter dependencies

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.0
  firebase_remote_config: ^5.1.0
  firebase_analytics: ^11.3.0

**Comment by SelaseKay** [comment]
What version of Xcode are you using?

**Comment by SelaseKay** [comment]
Hi @hasen6 , I've reopened an older issue that is similar to this. I'll go ahead and close this one. [13277](https://github.com/firebase/flutterfire/issues/13277)

**Comment by hasen6** [comment]
> What version of Xcode are you using?

15.0.1
