### ISSUE TITLE
[firebase_auth]: auth is not persisted in flutter web when using local firebase emulator

### ISSUE THREAD

**Issue by Hassico** [firebase/flutterfire#13296]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Auth

### Which platforms are affected?

Web

### Description

While testing my web app locally on my machine using firebase emulator, authenticated users get logged out upon page refresh. I tried all persistence options but the behavior remains the same. I tried on regular production environment and persistence and auth state works fine, but all the bulk of testing and work is done locally which is annoying to login every single time. I am using email login, not tested for other login methods, but I expect that the same will happen.

In the code I provided, just refresh the page after logging in, it will directly return a null user indicating no authenticated users.

### Reproducing the issue

```
class TestAuth extends StatelessWidget {
  const TestAuth({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: StreamBuilder<User?>(
        stream: FirebaseAuth.instance.userChanges(),
        builder: (context, snapshot) {
          return Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                TextButton(
                  onPressed: () async {
                    await FirebaseAuth.instance.signInWithEmailAndPassword(
                      email: 'test@gmail.com',
                      password: '123456',
                    );
                  },
                  child: snapshot.data != null ? Text('Logged in already') : Text('Login'),
                ),
              ],
            ),
          );
        },
      ),
    );
  }
}
```
### Firebase Core version

3.0.0

### Flutter Version

3.24.0

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by SelaseKay** [comment]
Hi @Hassico , I'm unable to reproduce this issue. What version of `firebase_auth` are you using?

**Comment by Hassico** [comment]
@SelaseKay, I am using version 5.0.0

**Comment by SelaseKay** [comment]
Kindly update your version and try again.

**Comment by Hassico** [comment]
I have bumped all flutterfire packages to the latest version, but the behavior remains the same. Please make sure you are testing locally using firebase emulator

**Comment by SelaseKay** [comment]
I tested locally but was unable to reproduce.

**Comment by Hassico** [comment]
Can you please give possible reasons fir such a behavior on my end, noting that when in production environment, authentication works properly and sessions are not lost. Does `firebase_auth` approach session caching or authentication differently when connecting to firebase emulator.

**Comment by SelaseKay** [comment]
Have you tested in other browsers? Also, try clearing your pub cache(`flutter pub cache clean`).

**Comment by Hassico** [comment]
@SelaseKay, I cleared the pub cache and tried safari but still upon refresh the user returned is null after a successful email authentication.

**Comment by SelaseKay** [comment]
I'm still unable to reproduce this issue. Can you create a minimal github repo reproducing this issue?
