### ISSUE TITLE
[📚] Disabling Flutter Web SDK injection

### ISSUE THREAD

**Issue by pepealonso95** [firebase/flutterfire#13305]
Im trying to run a chrome extension using flutterfire but downloading external scripts is not possible due to chrome's manifest security policies. Your documentation shows on how to download js sdk's locally but firebase_core is not included in the process so I am unable to run the build:

 https://firebase.google.com/docs/flutter/setup?platform=web#disable-auto.

**Comment by pepealonso95** [comment]
I would probably add a web label to this issue as it is 100% web related.

**Comment by Lyokone** [comment]
Hello @pepealonso95, I'm not sure what you mean, you can do
```
window.flutterfire_ignore_scripts = ['core', 'analytics', 'firestore'];
```
