### ISSUE TITLE
🐛 [cloud_firestore] I am surprised why firestore query does not support substring matching yet!

### ISSUE THREAD

**Issue by delwar36** [firebase/flutterfire#13308]
## Please add substring matching in Firestore Query?

It is important to search document using substring in the collection. Currently there is no support for that. So I request to add something like:
`query.where('fieldName', contains: 'substring')`

**Comment by SelaseKay** [comment]
Hi @delwar36 , Cloud Firestore does not support that. You can raise your concerns [here](https://firebase.uservoice.com/forums/948424-general).
Reference: [https://firebase.google.com/docs/firestore/solutions/search](https://firebase.google.com/docs/firestore/solutions/search)
