### ISSUE TITLE
🐛 [Firebase Crashlytics ] Support for windows platform 

### ISSUE THREAD

**Issue by DevAloshe** [firebase/flutterfire#13307]
### Request for Windows Platform Support in Firebase Crashlytics

Are there any plans to support the Windows platform in Firebase Crashlytics? Since Windows is a prominent platform, particularly when using Flutter for building desktop applications, it would be highly beneficial to have support for monitoring errors and bugs on Windows. This feature would help in improving the quality and stability of Flutter applications built for the Windows platform.

**Comment by SelaseKay** [comment]
Hi @DevAloshe , Firebase Crashlytics is not supported by C++ SDK. You can raise your concerns [here](https://firebase.uservoice.com/forums/948424-general).
