### ISSUE TITLE
[firebase_messaging]: java.io.IOException: TOO_MANY_REGISTRATIONS

### ISSUE THREAD

**Issue by ricardobegar** [firebase/flutterfire#13318]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Messaging

### Which platforms are affected?

Android, iOS

### Description

When I am trying to obtain the fcm token on some devices it is giving me the following error 

java.io.IOException: TOO_MANY_REGISTRATIONS
![Screenshot 2024-09-11 at 12 24 44 PM](https://github.com/user-attachments/assets/a2334ae2-a467-4845-b605-32c54000c2ec)
![Screenshot 2024-09-11 at 12 25 27 PM](https://github.com/user-attachments/assets/f7d42906-6f0c-440f-8087-0841df76060b)

### Reproducing the issue

I'm not sure how to reproduce it, but it's happening to me on these devices.
![Screenshot 2024-09-11 at 12 26 24 PM](https://github.com/user-attachments/assets/0dcfb92b-b50d-4c8c-8c57-a673b6b617f3)

### Firebase Core version

2.30.1

### Flutter Version

3.19.6

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by SelaseKay** [comment]
Hi @ricardobegar , unfortunately, this isn't something we have control over. [Here is a similar issue](https://github.com/firebase/flutterfire/issues/12649) with more insight.
