### ISSUE TITLE
[AUTH]: AuthAPNSTokenManager.getToken() fatal error unwrapping nil 

### ISSUE THREAD

**Issue by y2kpaulh** [firebase/flutterfire#13326]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Auth

### Which platforms are affected?

iOS

### Description

https://github.com/firebase/firebase-ios-sdk/issues/13470
https://github.com/firebase/firebase-ios-sdk/pull/13472

![err2](https://github.com/user-attachments/assets/9118fcb2-6cef-4d15-bb25-711ed0296ac9)

Hello! I am a flutter beginner. I am reporting an issue because I am having a similar issue with the feature that was fixed in the latest version of iOS.
I am not sure if I applied it wrong or if the latest iOS feature has not been applied yet, so I am asking a question. Please answer.

### Reproducing the issue

When performing PhoneAuthProvider.provider().verifyPhoneNumber and getting a timeout, the app crashes since AuthAPNSTokenManager runs into a nil unwrapping fatal error.

### Firebase Core version

3.4.1

### Flutter Version

3.24.2

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by SelaseKay** [comment]
This issue already exists: [13255](https://github.com/firebase/flutterfire/issues/13255)

**Comment by CntrlX** [comment]
This issue only exists when i test on a real device
