### ISSUE TITLE
error: [auth/billing-not] an internal error has occured. [billing_not_enabled] in firebase authentication in react native

### ISSUE THREAD

**Issue by Avik-Bera-scorpion23** [firebase/flutterfire#13320]
![Selected photo](https://github.com/user-attachments/assets/2b90078d-cadd-442f-ad96-9c4500616c45)

A warning shown
Error: [auth/billing-not] an internal error has occured. [billing_not_enabled] in firebase authentication in react native

**Comment by SelaseKay** [comment]
Kindly raise your report [here](https://github.com/invertase/react-native-firebase).

**Comment by Avik-Bera-scorpion23** [comment]
@SelaseKay thanks
