### ISSUE TITLE
firebase_database: Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module

### ISSUE THREAD

**Issue by HeitorCand** [firebase/flutterfire#13342]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Database

### Description

Flutter 3.24.3 

Xcode 16

IOS 18

  firebase_core: ^3.4.0
  firebase_database: ^11.1.1
  firebase_storage: ^12.2.0
  

Launching lib/main_dev.dart on Iphone Heitor in debug mode...
Running Xcode build...                                                  
 └─Compiling, linking and signing...                      1.761ms
Xcode build done.                                           38,1s
Failed to build iOS app
Could not build the precompiled application for the device.
Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module
'firebase_database.FLTFirebaseDatabaseObserveStreamHandler':
'/Users/heitor.candido/Documents/inteliApp/inteli/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/heitor.candido/.pub-cache/hosted/pub.dev/firebase_database-11.1.1/ios/Classes/FLTFirebaseDatabaseObserveStreamHandler.h:3:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module
'firebase_database.FLTFirebaseDatabasePlugin':
'/Users/heitor.candido/Documents/inteliApp/inteli/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/heitor.candido/.pub-cache/hosted/pub.dev/firebase_database-11.1.1/ios/Classes/FLTFirebaseDatabasePlugin.h:3:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module
'firebase_database.FLTFirebaseDatabaseUtils':
'/Users/heitor.candido/Documents/inteliApp/inteli/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/heitor.candido/.pub-cache/hosted/pub.dev/firebase_database-11.1.1/ios/Classes/FLTFirebaseDatabaseUtils.h:3:8

### Reproducing the issue

Just add the package and build
  firebase_core: ^3.4.0
  firebase_database: ^11.1.1
  firebase_storage: ^12.2.0
  

### Firebase Core version

3.4.0

### Flutter Version

3.24.3

### Relevant Log Output

```shell
Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module
'firebase_database.FLTFirebaseDatabaseObserveStreamHandler':
'/Users/heitor.candido/Documents/inteliApp/inteli/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/heitor.candido/.pub-cache/hosted/pub.dev/firebase_database-11.1.1/ios/Classes/FLTFirebaseDatabaseObserveStreamHandler.h:3:8


Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module
'firebase_database.FLTFirebaseDatabasePlugin':
'/Users/heitor.candido/Documents/inteliApp/inteli/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/heitor.candido/.pub-cache/hosted/pub.dev/firebase_database-11.1.1/ios/Classes/FLTFirebaseDatabasePlugin.h:3:8


Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module
'firebase_database.FLTFirebaseDatabaseUtils':
'/Users/heitor.candido/Documents/inteliApp/inteli/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/heitor.candido/.pub-cache/hosted/pub.dev/firebase_database-11.1.1/ios/Classes/FLTFirebaseDatabaseUtils.h:3:8
```

### Flutter dependencies

  cupertino_icons: ^1.0.8
  firebase_core: ^3.4.0
  firebase_database: ^11.1.1
  firebase_storage: ^12.2.0
  flutter_dotenv: ^5.1.0

  amplify_flutter: ^2.4.0
  amplify_auth_cognito: ^2.4.0
  amplify_authenticator: ^2.1.2
  amplify_core: ^2.4.0
  amplify_secure_storage: ^0.5.5
  flutter_bloc: ^8.1.6
  lottie: ^3.1.2
  flutter_svg: ^2.0.10+1
  http: ^1.2.2
  hive_flutter: ^1.1.0
  hive: ^2.2.3

**Comment by gigamike** [comment]
I also encountered this when I updated Xcode due to the new ios18 simulator and installed package:firebase_messaging

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_messaging.FLTFirebaseMessagingPlugin':
'/ios/Pods/Headers/Public/Firebase/Firebase.h'
/.pub-cache/hosted/pub.dev/firebase_messaging-15.1.0/ios/Classes/FLTFirebaseMessagingPlugin.h:11:8

**Comment by ShaunAtSense** [comment]
I just updated to Xcode 16 and started receiving this error when using iOS 18.

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_messaging.FLTFirebaseMessagingPlugin': '/ios/Pods/Headers/Public/Firebase/Firebase.h'
/.pub-cache/hosted/pub.dev/firebase_messaging-15.1.1/ios/Classes/FLTFirebaseMessagingPlugin.h:11:8

**Comment by SelaseKay** [comment]
Hi @HeitorCand , this issue appears to be a duplicate. [13323](https://github.com/firebase/flutterfire/issues/13323)

**Comment by DevClement** [comment]
I found a solution.

You have to go to Xcode => Runner => Build Settings and put "Allow Non-modular Includes In Framework Modules" to "yes"

**Comment by dantodsky** [comment]
> I found a solution.
> 
> You have to go to Xcode => Runner => Build Settings and put "Allow Non-modular Includes In Framework Modules" to "yes"

you are very very very great. . thank you so much. .

**Comment by toykam** [comment]
> I found a solution.
> 
> You have to go to Xcode => Runner => Build Settings and put "Allow Non-modular Includes In Framework Modules" to "yes"

i cant find this option in my xcode 16.

**Comment by DevClement** [comment]
> > I found a solution.
> > You have to go to Xcode => Runner => Build Settings and put "Allow Non-modular Includes In Framework Modules" to "yes"
> 
> i cant find this option in my xcode 16.

You have to open your project on Xcode, you click on the runner and then on the left then on the top, you have build settings. And for the option check all and you have a magnifying glass to do the search

**Comment by malakmahersoliman** [comment]
> > > I found a solution.
> > > You have to go to Xcode => Runner => Build Settings and put "Allow Non-modular Includes In Framework Modules" to "yes"
> > 
> > 
> > i cant find this option in my xcode 16.
> 
> You have to open your project on Xcode, you click on the runner and then on the left then on the top, you have build settings. And for the option check all and you have a magnifying glass to do the search

still unable to find it and when I use the search get noting

**Comment by malakmahersoliman** [comment]
> > > I found a solution.
> > > You have to go to Xcode => Runner => Build Settings and put "Allow Non-modular Includes In Framework Modules" to "yes"
> > 
> > 
> > i cant find this option in my xcode 16.
> 
> You have to open your project on Xcode, you click on the runner and then on the left then on the top, you have build settings. And for the option check all and you have a magnifying glass to do the search

<img width="1512" alt="Screenshot 2024-09-21 at 2 02 53 AM" src="https://github.com/user-attachments/assets/fb7e01ff-683f-4db6-8399-0c49fc209028">
can you help me to do it , I can't find it

**Comment by adrianorios** [comment]
> > I found a solution.
> > You have to go to Xcode => Runner => Build Settings and put "Allow Non-modular Includes In Framework Modules" to "yes"
> 
> i cant find this option in my xcode 16.

You have to go to Xcode => Runner => Build Settings => All and put "Allow Non-modular Includes In Framework Modules" to yes.

For me its ok!!

**Comment by krszozda** [comment]
It's working but I have next step in this issue: 
note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, 

somebody something? :)

**Comment by iamnabink** [comment]
> I found a solution.
> 
> You have to go to Xcode => Runner => Build Settings and put "Allow Non-modular Includes In Framework Modules" to "yes"

**Anyone why we have to do this?**

**Comment by emirgangs** [comment]
> I found a solution.
> 
> You have to go to Xcode => Runner => Build Settings and put "Allow Non-modular Includes In Framework Modules" to "yes"

thank you so much brother <3 you saved us

**Comment by NguyenHuuPhuc** [comment]
<img width="1396" alt="Screenshot 2024-09-23 at 09 30 24" src="https://github.com/user-attachments/assets/4a0de462-297f-4291-a518-fb9c52b93a8c">
Change to 'Yes'
But in my case, Xcode build extremely slow.

**Comment by therngbtg** [comment]
> I found a solution.
> 
> You have to go to Xcode => Runner => Build Settings and put "Allow Non-modular Includes In Framework Modules" to "yes"

Thank you :)

**Comment by ibrhm117-togo** [comment]
I don't seem to have this option in my XCode version 16 

<img width="1333" alt="Screenshot 2024-09-23 at 12 37 22 PM" src="https://github.com/user-attachments/assets/e9ebce1b-e76d-40e3-aa51-7a214969ea27">

**Comment by bonaparta13** [comment]
> I don't seem to have this option in my XCode version 16
> 
> <img alt="Screenshot 2024-09-23 at 12 37 22 PM" width="1333" src="https://private-user-images.githubusercontent.com/176575827/369778069-e9ebce1b-e76d-40e3-aa51-7a214969ea27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwODA5MzAsIm5iZiI6MTcyNzA4MDYzMCwicGF0aCI6Ii8xNzY1NzU4MjcvMzY5Nzc4MDY5LWU5ZWJjZTFiLWU3NmQtNDBlMy1hYTUxLTdhMjE0OTY5ZWEyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QwODM3MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNGUzYWZjZWU2YThjZjIwZjgzYzJlODMyZTg1MTViNzc5YTgxZTYyZjM0ZTgzMmQ0Nzg2M2RlZWU0NzZlOTlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.D1XHiTVEuMk4TO2wcvnv_bJkSnP8JeUT0xCnbK3GtCQ">

make sure to select ALL 
![Screenshot 2024-09-23 at 11 52 42 AM](https://github.com/user-attachments/assets/aedcbd4e-3dd3-46a3-8b12-cbe00f665a96)

**Comment by auliaridhov** [comment]
> > I found a solution.
> > You have to go to Xcode => Runner => Build Settings and put "Allow Non-modular Includes In Framework Modules" to "yes"
> 
> **Anyone why we have to do this?**

Does anyone know why?

**Comment by krszozda** [comment]
Somebody can run some flutter project on iOS? I have each all some errors..

**Comment by adrianorodesousa** [comment]
> Allow Non-modular Includes In Framework Modules

You're my hero! Thanks <3

**Comment by tfyilmaz** [comment]
I am having the same issue on my flutter project and dont know what to do. Any help would be much appreciated.

**Comment by bunthoeun-develop** [comment]
Anyone know why need to do it?

**Comment by anshidp** [comment]
> I found a solution.
> 
> You have to go to Xcode => Runner => Build Settings and put "Allow Non-modular Includes In Framework Modules" to "yes"

great this is working 👍

**Comment by wasilni2022** [comment]
Allowing "Non-modular Includes in Framework Modules" will cause massive runtime issues later on. This is not a solution, you are slowly destroying your project. Do not do it! Wait until a new version of the package is ready!

**Comment by borisbokan** [comment]
> I found a solution.
> 
> You have to go to Xcode => Runner => Build Settings and put "Allow Non-modular Includes In Framework Modules" to "yes"

Thanks :)

**Comment by fikretsengul** [comment]
I get the same error why this is closed?

ILexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_messaging.FLTFirebaseMessagingPlugin': '/Users/fikretsengul/Workspace/Quattro.Mobile.Refactor/app/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/fikretsengul/.pub-cache/hosted/pub.dev/firebase_messaging-15.1.2/ios/Classes/FLTFirebaseMessagingPlugin.h:11:8

**Comment by goj1** [comment]
> I found a solution.
> 
> You have to go to Xcode => Runner => Build Settings and put "Allow Non-modular Includes In Framework Modules" to "yes"

Great job! Thank you!

**Comment by BeshoyMelika** [comment]
> I found a solution.
> 
> You have to go to Xcode => Runner => Build Settings and put "Allow Non-modular Includes In Framework Modules" to "yes"

Great job! Thank you!

**Comment by aekkachan** [comment]
> I found a solution.
> 
> You have to go to Xcode => Runner => Build Settings and put "Allow Non-modular Includes In Framework Modules" to "yes"

bro you saved my life, big thank

**Comment by danielkiing3** [comment]
> I found a solution.
> 
> You have to go to Xcode => Runner => Build Settings and put "Allow Non-modular Includes In Framework Modules" to "yes"

Thank you very much, God bless you
I've been battling with this for over 2 weeks now😭

This is just solved my phone

**Comment by lisbonc1987** [comment]
I was getting the exact error and I changed the build settings like what @DevClement suggested. But I was reading through and saw @wasilni2022 so I didn't want to take the risk. I noticed this started happening when I used Clean My Mac (I have since deleted) and it deleted my simulator settings so I added a new one with IOS 18. What I ended up doing that worked for me without changing the build settings is to run the following commands in the root of your project:

`flutter clean
flutter pub get
cd ios
pod deintegrate
pod install --repo-update
cd ..`

I had a pod error at this point. I went to ios/Pods/Local Podspecs directory and looked at every single json file to see what's the highest IOS version on every single one. The highest on mine was "iOS": "13.0"

I went to project/iOS/Podfile and changed the  platform :iOS, "xx.x" to the highest iOS values in my json files from above, which is 13.

I then ran the below command on the iOS folder of your project:

`pod update Firebase/Auth`

Then I navigate to the iOS folder of my project and ran:

`pod install
flutter build iOS`

It worked! I am basing all of these on memory so I may have missed something but hopefully this helps someone out.

**Comment by bawantha** [comment]
just happened to me

**Comment by theoheneba** [comment]
> I found a solution.
> 
> You have to go to Xcode => Runner => Build Settings and put "Allow Non-modular Includes In Framework Modules" to "yes"

Thank you very much, it work

**Comment by Jonas-Sander** [comment]
> Allowing "Non-modular Includes in Framework Modules" will cause massive runtime issues later on. This is not a solution, you are slowly destroying your project. Do not do it! Wait until a new version of the package is ready!

Why and what runtime issues exactly?
