### ISSUE TITLE
[firebase_core]:  Cannot run on Apple Vision Pro simulator

### ISSUE THREAD

**Issue by Saad29** [firebase/flutterfire#13359]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Core, Analytics, Messaging, Remote Config

### Which platforms are affected?

iOS

### Description

I have managed to compile the counter flutter app on Apple Vision Pro simulator. However, I get build failed due to  
`No such module 'Flutter'` or `firebase.h not found` sometimes when I try to compile my flutter app, which is using firebase core, messaging, analytics, dynamic links and remote config. 

I have also asked it as a question here but no answers so far.
https://github.com/firebase/flutterfire/discussions/13204

### Reproducing the issue

Include any of the following dependencies :
```
  firebase_analytics: ^11.2.1
  firebase_core: ^3.3.0
  firebase_dynamic_links: ^6.0.4
  firebase_messaging: ^15.0.4
  firebase_remote_config: ^5.0.4
```

Try to run the app on Apple Vision pro simulator. You should get Build failed with the message `Module 'one_of_the_firebase_plugins' not found`.

For running a flutter app on Apple vision pro simulator, you can follow the steps at https://simonauer.medium.com/how-to-get-started-with-flutter-and-visionos-apple-vision-pro-4335c3243248

### Firebase Core version

3.3.0

### Flutter Version

3.24.0

### Relevant Log Output

```shell
No such module 'Flutter'
Module 'firebase_core' not found
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by SelaseKay** [comment]
Hi @Saad29 , thanks for submitting this issue. Unfortunately, FF does not support visionOS at the moment.
