### ISSUE TITLE
firebase_crashlytics: ios 18 version get error

### ISSUE THREAD

**Issue by rajeshbdabhi** [firebase/flutterfire#13357]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Crashlytics

### Which platforms are affected?

iOS

### Description

when i try to run my app into latest ios 18 version simulator. it is giving bellow issue

### Reproducing the issue

try to run app in latest ios 18 version simulator or phone

### Firebase Core version

3.5.0

### Flutter Version

3.24.3

### Relevant Log Output

```shell
Running Xcode build...
Xcode build done.                                           73.5s
Failed to build iOS app
Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_crashlytics.Crashlytics_Platform': '/Users/rajeshdabhi/Desktop/Work/AndroidStudioProjects/ridex-wb-user/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/rajeshdabhi/.pub-cache/hosted/pub.dev/firebase_crashlytics-4.1.2/ios/Classes/Crashlytics_Platform.h:20:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_crashlytics.ExceptionModel_Platform': '/Users/rajeshdabhi/Desktop/Work/AndroidStudioProjects/ridex-wb-user/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/rajeshdabhi/.pub-cache/hosted/pub.dev/firebase_crashlytics-4.1.2/ios/Classes/ExceptionModel_Platform.h:20:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_messaging.FLTFirebaseMessagingPlugin': '/Users/rajeshdabhi/Desktop/Work/AndroidStudioProjects/ridex-wb-user/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/rajeshdabhi/.pub-cache/hosted/pub.dev/firebase_messaging-15.1.2/ios/Classes/FLTFirebaseMessagingPlugin.h:11:8

Could not build the application for the simulator.
Error launching application on iPhone 16 Pro Max.
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by Jbz797** [comment]
Same here

**Comment by OliverNarramore** [comment]
Same here

**Comment by rajeshbdabhi** [comment]
https://github.com/firebase/flutterfire/issues/13323#issuecomment-2355013360

i have fix with above changes from xcode

So far, I found a fix by setting "Allow Non-modular includes in Frame Modules" (CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES) to YES. Build is successful now.

**Comment by SelaseKay** [comment]
Duplicate: [13323](https://github.com/firebase/flutterfire/issues/13323)
