### ISSUE TITLE
[cloud_firestore]: Differing behavior between isNull and isEqualTo null.

### ISSUE THREAD

**Issue by danReynolds** [firebase/flutterfire#13351]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Database

### Which platforms are affected?

iOS

### Description

There is differing behavior when filtering on a field that does not exist on a document depending on whether you use `isNull: true` versus `isEqualTo: null`.

I would expect that these two queries have the same behavior. Let me know if that is correct. Thanks!

### Reproducing the issue

1. Create any document without the field `createdAt`.
2. Try querying that field using `isNull: true`. It **does not** return the document.
3. Try querying that field using `isEqualTo: null`. It **does** return the document.

### Firebase Core version

2.27.0

### Flutter Version

3.19.0

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by SelaseKay** [comment]
Hi @danReynolds , thanks for submitting this issue. I am able to reproduce this issue.
