### ISSUE TITLE
[FIREBASE STORAGE]: iOS build fails after upgrading to iOS 18, MacOS Sequoia - Include of non-modular header inside framework module 'firebase_storage.FLTTaskStateChannelStreamHandler': /ios/Pods/Headers/Public/Firebase/Firebase.h'

### ISSUE THREAD

**Issue by dgurudot** [firebase/flutterfire#13365]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Storage

### Which platforms are affected?

iOS

### Description

Build was working great and Xcode got updated based on auto-update, then upgraded Mac OS as well.

Now, build fails with the error given below:

Include of non-modular header inside framework module 'firebase_storage.FLTTaskStateChannelStreamHandler': '/Users/vk/StudioProjects/<name>/ios/Pods/Headers/Public/Firebase/Firebase.h'

### Reproducing the issue

This is a big project so diffiucult for me to create yet another similar minimal one to reproduce. Please see the error if you find the issue and suggest a solution.

### Firebase Core version

^3.5.0

### Flutter Version

3.24.3

### Relevant Log Output

```shell
/Users/vk/.pub-cache/hosted/pub.dev/firebase_storage-12.3.1/ios/Classes/FLTTaskStateChannelStreamHandler.h:13:9 Include of non-modular header inside framework module 'firebase_storage.FLTTaskStateChannelStreamHandler': '/Users/vk/StudioProjects/<name>/ios/Pods/Headers/Public/Firebase/Firebase.h'
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by dgurudot** [comment]
I found a solution. 

<img width="862" alt="image" src="https://github.com/user-attachments/assets/031684dc-f956-444a-b0b8-a922e9a3904f">

**Comment by dgurudot** [comment]
Okay to close it but others can comment.

**Comment by samariotorres** [comment]
What version of xcode? im not seeing it in Xcode 16.. can you copy and paste your yaml file (firebase packages) as well? and also your Podfile? Thank you!

@dgurudot

**Comment by samariotorres** [comment]
Nevermind, restarted Xcode and saw it after. I updated the value in both the target and project Runners

**Comment by victorcode1** [comment]
> ¿Qué versión de Xcode? No la veo en Xcode 16. ¿Puedes copiar y pegar también tu archivo yaml (paquetes de Firebase)? ¿Y también tu Podfile? ¡Gracias!
> 
> @dgurudot
> 
> ACTUALIZACIÓN No importa, reinicié Xcode y lo vi después. Actualicé el valor tanto en el ejecutor de destino como en el de proyecto. Funcionó bien.

Would you help me?

**Comment by victorcode1** [comment]
I have the same problem, I would appreciate your help

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside
framework module 'firebase_dynamic_links.FLTFirebaseDynamicLinksPlugin':
'/Users/victorflores/invuKDS/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/victorflores/.pub-cache/hosted/pub.dev/firebase_dynamic_links-6.0.7/ios/C
lasses/FLTFirebaseDynamicLinksPlugin.h:3:8


Could not build the application for the simulator.
Error launching application on Ipad .

**Comment by SelaseKay** [comment]
Duplicate: [13323](https://github.com/firebase/flutterfire/issues/13323)

**Comment by victorcode1** [comment]
![Screenshot 2024-09-19 at 9 47 52 AM](https://github.com/user-attachments/assets/d2d194e7-cd35-4560-a2da-e114fea0a7b0)


my solution
