### ISSUE TITLE
Firebase: Can't run app only in iOS devices in latest update (iOS 18) and Xcode 16

### ISSUE THREAD

**Issue by emanuelzallikodelabs** [firebase/flutterfire#13368]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Crashlytics

### Which platforms are affected?

iOS

### Description

I have upgraded Flutter to the latest version (3.24.3), Xcode has the newest version (16), and my device has iOS 18.
When I want to install pods I get this Warning:
Warning: firebase_app_id_file.json file does not exist. This may cause issues in upload-symbols. If this error is unexpected, try running flutterfire configure again.

I have it configured firebase for both devices (iOS, Android), and when I want to run app in iOS device I get this issue:
Could not build the precompiled application for the device.
Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_crashlytics.Crashlytics_Platform': '/Users/emanuelzalli/Projects/bms-mobile/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/emanuelzalli/.pub-cache/hosted/pub.dev/firebase_crashlytics-4.1.2/ios/Classes/Crashlytics_Platform.h:20:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_crashlytics.ExceptionModel_Platform': '/Users/emanuelzalli/Projects/bms-mobile/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/emanuelzalli/.pub-cache/hosted/pub.dev/firebase_crashlytics-4.1.2/ios/Classes/ExceptionModel_Platform.h:20:8

Error launching application on Kode OS.

In Android devices I can run the app without problems

### Reproducing the issue

Based on the description fields, this issue happened when I upgraded Firebase libraries in the latest version, and Xcode in the 16 version.

### Firebase Core version

3.5.0

### Flutter Version

3.24.3

### Relevant Log Output

```shell
Could not build the precompiled application for the device.
Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_crashlytics.Crashlytics_Platform': '/Users/emanuelzalli/Projects/bms-mobile/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/emanuelzalli/.pub-cache/hosted/pub.dev/firebase_crashlytics-4.1.2/ios/Classes/Crashlytics_Platform.h:20:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_crashlytics.ExceptionModel_Platform': '/Users/emanuelzalli/Projects/bms-mobile/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/emanuelzalli/.pub-cache/hosted/pub.dev/firebase_crashlytics-4.1.2/ios/Classes/ExceptionModel_Platform.h:20:8

Error launching application on Kode OS.
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by alfie-trbc** [comment]
I fixed the issue by setting the allow non modular  includes in framework modules to yes. 

![image](https://github.com/user-attachments/assets/4bc3dc1c-c5b3-4fac-87e4-979115146a3c)

I think, Xcode is now transitioning to not support the non modular header in Xcode 16. and Hopefully there will be a migration with this changes with the flutter fire team.

**Comment by SelaseKay** [comment]
Duplicate: [13323](https://github.com/firebase/flutterfire/issues/13323)

**Comment by emanuelzallikodelabs** [comment]
Alfie C. Tribaco, thank you for your response, this option also solved the issue for me.

**Comment by kerem-h** [comment]
Right-click on the İOS folder in Flutter and select Open in Xcode to change the setting. It worked for me.

**Comment by ming-chu** [comment]
duplicate: https://github.com/firebase/flutterfire/issues/12962
this [comment](https://github.com/firebase/flutterfire/issues/12962#issuecomment-2183898535) solved it.

**Comment by komaxx** [comment]
Please note that the "solution" is no such thing but a workaround.
While this might work in your project there is also a chance that you'll run into unexplainable errors later on with your iOS build! Allowing Non-Modular includes is basically an invitation for duplicated headers later on.

I hope that the Firebase team comes up with a proper fix soon :)
