### ISSUE TITLE
Version 5.3.0 don't work on iOS.

### ISSUE THREAD

**Issue by eliikiisser** [firebase/flutterfire#13363]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Description

Version 5.3.0 don't work on iOS.
if I would install another version it's still install 5.3.0

### Reproducing the issue

Could not build the precompiled application for the device.
Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.FLTAuthStateChannelStreamHandler': '/Users/elii/Desktop/FlutterApp/wellmarc/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/elii/.pub-cache/hosted/pub.dev/firebase_auth-5.3.0/ios/Classes/Private/FLTAuthStateChannelStreamHandler.h:12:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.PigeonParser': '/Users/elii/Desktop/FlutterApp/wellmarc/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/elii/.pub-cache/hosted/pub.dev/firebase_auth-5.3.0/ios/Classes/Private/PigeonParser.h:6:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.FLTIdTokenChannelStreamHandler': '/Users/elii/Desktop/FlutterApp/wellmarc/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/elii/.pub-cache/hosted/pub.dev/firebase_auth-5.3.0/ios/Classes/Private/FLTIdTokenChannelStreamHandler.h:12:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.FLTPhoneNumberVerificationStreamHandler': '/Users/elii/Desktop/FlutterApp/wellmarc/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/elii/.pub-cache/hosted/pub.dev/firebase_auth-5.3.0/ios/Classes/Private/FLTPhoneNumberVerificationStreamHandler.h:12:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.FLTFirebaseAuthPlugin': '/Users/elii/Desktop/FlutterApp/wellmarc/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/elii/.pub-cache/hosted/pub.dev/firebase_auth-5.3.0/ios/Classes/Public/FLTFirebaseAuthPlugin.h:6:8
2

Error launching application on iPhone Elii.

### Firebase Core version

3.5.0

### Flutter Version

3.24.3

### Relevant Log Output

```shell
Could not build the precompiled application for the device.
Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.FLTAuthStateChannelStreamHandler': '/Users/elii/Desktop/FlutterApp/wellmarc/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/elii/.pub-cache/hosted/pub.dev/firebase_auth-5.3.0/ios/Classes/Private/FLTAuthStateChannelStreamHandler.h:12:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.PigeonParser': '/Users/elii/Desktop/FlutterApp/wellmarc/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/elii/.pub-cache/hosted/pub.dev/firebase_auth-5.3.0/ios/Classes/Private/PigeonParser.h:6:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.FLTIdTokenChannelStreamHandler': '/Users/elii/Desktop/FlutterApp/wellmarc/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/elii/.pub-cache/hosted/pub.dev/firebase_auth-5.3.0/ios/Classes/Private/FLTIdTokenChannelStreamHandler.h:12:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.FLTPhoneNumberVerificationStreamHandler': '/Users/elii/Desktop/FlutterApp/wellmarc/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/elii/.pub-cache/hosted/pub.dev/firebase_auth-5.3.0/ios/Classes/Private/FLTPhoneNumberVerificationStreamHandler.h:12:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.FLTFirebaseAuthPlugin': '/Users/elii/Desktop/FlutterApp/wellmarc/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/elii/.pub-cache/hosted/pub.dev/firebase_auth-5.3.0/ios/Classes/Public/FLTFirebaseAuthPlugin.h:6:8
2

Error launching application on iPhone Elii.
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by SelaseKay** [comment]
Duplicate: [13323](https://github.com/firebase/flutterfire/issues/13323)
