### ISSUE TITLE
Firebase Crashlytics/Messaging: Security Finding - Prevent firebase from logging session event

### ISSUE THREAD

**Issue by LisaLamparterXX** [firebase/flutterfire#13397]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Crashlytics, Messaging

### Which platforms are affected?

Android

### Description

Hi,

pen testing had a security finding in our app because the firebase libraries (GTDLogger) are logging session events (including firebaseAuthenticationToken, firebaseInstallationId etc.) on debug level.

We are using the following libraries:

  firebase_core: ^2.32.0
  firebase_crashlytics: ^3.5.7
  firebase_messaging: ^14.9.4
Is there a way to prevent firebase from logging at all or set another log level?

Thanks in advance!

### Reproducing the issue

Observe standard output when using firebase libraries.

### Firebase Core version

2.32.0

### Flutter Version

3.22.1

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by SelaseKay** [comment]
Hi @LisaLamparterXX , thank you for submitting this issue. Could you please try running your test with the latest versions of FlutterFire?

**Comment by russellwheatley** [comment]
@LisaLamparterXX - I'd also check if the logs only occur in debug build, they probably don't occur in release mode which is ultimately what matters.

**Comment by LisaLamparterXX** [comment]
Thanks for that hint. Pen tester seemed to perform their scans by using debug mode - at least I checked that those loggings are only visible in logcat if the app runs in debug mode.
