### ISSUE TITLE
[firebase_messaging/apns-token-not-set] APNS token has not been set yet. Please ensure the APNS token is available by calling `getAPNSToken()`

### ISSUE THREAD

**Issue by EliseiNicolae** [firebase/flutterfire#13426]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

In-App Messaging, Messaging

### Which platforms are affected?

iOS

### Description

Getting this error:
[firebase_messaging/apns-token-not-set] APNS token has not been set yet. Please ensure the APNS token is available by calling `getAPNSToken()`

### Reproducing the issue

I'm using xcode v16

firebase_core: ^3.3.0
firebase_messaging: ^15.0.4

On Simulator it is working well, but when running the app with a real Apple device it throws the error.

### Firebase Core version

3.3.0

### Flutter Version

3.24.1

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by WieFel** [comment]
@EliseiNicolae I have the same problem. None of the already closed issues about this topic provides a clear solution.
How did you resolve it?

**Comment by EliseiNicolae** [comment]
Hi @WieFel, I have fixed this by creating this function:

<img width="756" alt="image" src="https://github.com/user-attachments/assets/ddd41f88-bfdb-423d-a1e2-5abb4d25865b">


I think the issue was that I haven't called requestPermission on ios
