### ISSUE TITLE
Set badge

### ISSUE THREAD

**Issue by StanleyCocos** [firebase/flutterfire#13425]
I don't seem to see how to set the desktop icon. Would you consider adding this feature?

**Comment by SelaseKay** [comment]
Hi @StanleyCocos , could you please provide more details about your feature request? I'm not entirely clear on what you mean. Thank you!

**Comment by StanleyCocos** [comment]
Hi @SelaseKay, For example, when iOS pushes 
```
{
 "aps" : {
    "alert" : {
       "body" : "message book",            
     },
    "badge" : 5, 
  },
}
```
At this time, the picture on the desktop will display the corner mark 5. When I click into my application, I need to set the corresponding read data and modified 5 corner mark data. For example: 
```
UIApplication.shared.applicationIconBadgeNumber = 2
```
Hope it can be added
```
FirebaseMessaging.setBadgeNumber(2);
```

**Comment by StanleyCocos** [comment]
OK thank you. 
However, I still think that setting the corner mark is a very small function, and it is part of the push function. No need to reintroduce a framework. And there is currently no mature and well-maintained framework on the market.
