### ISSUE TITLE
[Cloud Firestore]: type 'Null' is not a subtype of type 'Map<String, dynamic>'

### ISSUE THREAD

**Issue by Tr736** [firebase/flutterfire#13441]
closed

**Comment by SelaseKay** [comment]
I'm unable to reproduce this issue. Kindly elaborate on what you mean by the data coming through is incomplete?

**Comment by Tr736** [comment]
> I'm unable to reproduce this issue. Kindly elaborate on what you mean by the data coming through is incomplete?

So this is the json im getting in the logs

` json:{tags: [security, DOWNLOADED], settings: {added: 2024-09-25T03:30:12.000Z, updated: 2024-09-29T14:45:44.168807Z, synced: 2008-10-31T14:10:00.000Z, position: 0, queueindex: 0}}
`

Where in fact it should contain

_id (Missing)
_origin (Missing)
_type (Missing)
Content (Missing)
Settings (included)
Tags  (included)
