### ISSUE TITLE
[flutterfire_cli]: Package name length limited

### ISSUE THREAD

**Issue by rayliverified** [firebase/flutterfire#13457]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Other

### Which platforms are affected?

macOS, Windows

### Description

flutterfire_cli package name input is limited. Cannot enter full package name.

https://github.com/user-attachments/assets/ebcd85c8-00c3-440e-9ec9-a82eb2515087

https://github.com/user-attachments/assets/e6f01ba6-f6f2-4952-8578-8a4cfc3ddf0e

### Reproducing the issue

1. Run `flutterfire configure`
2. Type a package name that reached the length of the terminal window.

### Firebase Core version

3.7.0

### Flutter Version

3.24.0

### Flutter dependencies

flutterfire_cli v1.0.0

**Comment by SelaseKay** [comment]
Hi @rayliverified , kindly submit this issue on [flutterfire_cli repo](https://github.com/invertase/flutterfire_cli)

**Comment by rayliverified** [comment]
https://github.com/invertase/flutterfire_cli/issues/341
