### ISSUE TITLE
web + storage + reference_web.dart `putString` needs testing and fixes

### ISSUE THREAD

**Issue by kevmoo** [firebase/flutterfire#13464]
https://github.com/firebase/flutterfire/blob/7fcdbeebf79060354b1853bf3e1b8716dfd3f96e/packages/firebase_storage/firebase_storage_web/lib/src/reference_web.dart#L173-L207

* The casting to `dynamic` is scary
* In only *one* case is the value converted to `Uint8List` – but all calls to `put` should be a binary type

**Comment by kevmoo** [comment]
Related to https://github.com/firebase/flutterfire/issues/13458

**Comment by Lyokone** [comment]
Thanks for the report, the fix will be published as part of tomorrow's release.
