### ISSUE TITLE
[cloud_firestore]: When Fetching(write, read, create) data from firebaseFireStore, I'm getting this error

### ISSUE THREAD

**Issue by vedatsalmis** [firebase/flutterfire#13485]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Cloud Functions

### Which platforms are affected?

Android

### Description

While the application is opening, I am pulling some data from firestore in the background. After pulling that data, this error occurs. However, when I try to pull other data from firestore for the second time while the app is open, this error does not occur. I started to encounter this problem after upgrading Flutter. This error message does not harm the application's operation, but I cannot understand why it occurs.

### Reproducing the issue

While the application is opening, I am pulling some data from firestore in the background. After pulling that data, this error occurs. This error only occurs the first time when retrieving data from the firestore while the application is open. When the app later pull data from Firestore while the application is running, I do not get this error again in that session.

### Firebase Core version

3.6.0

### Flutter Version

3.24.3

### Relevant Log Output

```shell
E/GoogleApiManager( 9077): Failed to get service from broker.
E/GoogleApiManager( 9077): java.lang.SecurityException: Unknown calling package name 'com.google.android.gms'.
E/GoogleApiManager( 9077): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
E/GoogleApiManager( 9077): 	at android.os.Parcel.createException(Parcel.java:3041)
E/GoogleApiManager( 9077): 	at android.os.Parcel.readException(Parcel.java:3024)
E/GoogleApiManager( 9077): 	at android.os.Parcel.readException(Parcel.java:2966)
E/GoogleApiManager( 9077): 	at amrz.a(:com.google.android.gms@243834032@24.38.34 (190800-681941525):36)
E/GoogleApiManager( 9077): 	at amqg.z(:com.google.android.gms@243834032@24.38.34 (190800-681941525):143)
E/GoogleApiManager( 9077): 	at alxh.run(:com.google.android.gms@243834032@24.38.34 (190800-681941525):54)
E/GoogleApiManager( 9077): 	at android.os.Handler.handleCallback(Handler.java:958)
E/GoogleApiManager( 9077): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/GoogleApiManager( 9077): 	at bqww.mv(:com.google.android.gms@243834032@24.38.34 (190800-681941525):1)
E/GoogleApiManager( 9077): 	at bqww.dispatchMessage(:com.google.android.gms@243834032@24.38.34 (190800-681941525):5)
E/GoogleApiManager( 9077): 	at android.os.Looper.loopOnce(Looper.java:205)
E/GoogleApiManager( 9077): 	at android.os.Looper.loop(Looper.java:294)
E/GoogleApiManager( 9077): 	at android.os.HandlerThread.run(HandlerThread.java:67)

Error message is above.

Also, before this error, before I updated Flutter and now I am getting these warning logs related to Firestore. This is below.

W/DynamiteModule( 9077): Local module descriptor class for com.google.android.gms.providerinstaller.dynamite not found.
I/DynamiteModule( 9077): Considering local module com.google.android.gms.providerinstaller.dynamite:0 and remote module com.google.android.gms.providerinstaller.dynamite:0
W/ProviderInstaller( 9077): Failed to load providerinstaller module: No acceptable module com.google.android.gms.providerinstaller.dynamite found. Local version is 0 and remote version is 0.
D/nativeloader( 9077): Configuring clns-7 for other apk /system/framework/org.apache.http.legacy.jar. target_sdk_version=34, uses_libraries=ALL, library_path=/data/app/~~D0otSPDQ6ze3M8w6brTTrA==/com.google.android.gms-xN_U7Ba9Fcm8BTSBEE9ncA==/lib/x86_64:/data/app/~~D0otSPDQ6ze3M8w6brTTrA==/com.google.android.gms-xN_U7Ba9Fcm8BTSBEE9ncA==/base.apk!/lib/x86_64, permitted_path=/data:/mnt/expand:/data/user/0/com.google.android.gms
D/nativeloader( 9077): Configuring clns-8 for other apk /system/framework/com.android.media.remotedisplay.jar. target_sdk_version=34, uses_libraries=ALL, library_path=/data/app/~~D0otSPDQ6ze3M8w6brTTrA==/com.google.android.gms-xN_U7Ba9Fcm8BTSBEE9ncA==/lib/x86_64:/data/app/~~D0otSPDQ6ze3M8w6brTTrA==/com.google.android.gms-xN_U7Ba9Fcm8BTSBEE9ncA==/base.apk!/lib/x86_64, permitted_path=/data:/mnt/expand:/data/user/0/com.google.android.gms
I/r_application_1( 9077): Compiler allocated 4478KB to compile void android.view.ViewRootImpl.performTraversals()
W/r_application_1( 9077): Loading /data/misc/apexdata/com.android.art/dalvik-cache/x86_64/system@framework@com.android.location.provider.jar@classes.odex non-executable as it requires an image which we failed to load
D/nativeloader( 9077): Configuring clns-9 for other apk /system/framework/com.android.location.provider.jar. target_sdk_version=34, uses_libraries=ALL, library_path=/data/app/~~D0otSPDQ6ze3M8w6brTTrA==/com.google.android.gms-xN_U7Ba9Fcm8BTSBEE9ncA==/lib/x86_64:/data/app/~~D0otSPDQ6ze3M8w6brTTrA==/com.google.android.gms-xN_U7Ba9Fcm8BTSBEE9ncA==/base.apk!/lib/x86_64, permitted_path=/data:/mnt/expand:/data/user/0/com.google.android.gms
D/ApplicationLoaders( 9077): Returning zygote-cached class loader: /system_ext/framework/androidx.window.extensions.jar
D/ApplicationLoaders( 9077): Returning zygote-cached class loader: /system_ext/framework/androidx.window.sidecar.jar
W/r_application_1( 9077): Loading /data/app/~~D0otSPDQ6ze3M8w6brTTrA==/com.google.android.gms-xN_U7Ba9Fcm8BTSBEE9ncA==/oat/x86_64/base.odex non-executable as it requires an image which we failed to load
D/nativeloader( 9077): Configuring clns-10 for other apk /data/app/~~D0otSPDQ6ze3M8w6brTTrA==/com.google.android.gms-xN_U7Ba9Fcm8BTSBEE9ncA==/base.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~D0otSPDQ6ze3M8w6brTTrA==/com.google.android.gms-xN_U7Ba9Fcm8BTSBEE9ncA==/lib/x86_64:/data/app/~~D0otSPDQ6ze3M8w6brTTrA==/com.google.android.gms-xN_U7Ba9Fcm8BTSBEE9ncA==/base.apk!/lib/x86_64, permitted_path=/data:/mnt/expand:/data/user/0/com.google.android.gms
W/ProviderInstaller( 9077): Failed to report request stats: com.google.android.gms.common.security.ProviderInstallerImpl.reportRequestStats [class android.content.Context, long, long]
D/nativeloader( 9077): Load /data/app/~~D0otSPDQ6ze3M8w6brTTrA==/com.google.android.gms-xN_U7Ba9Fcm8BTSBEE9ncA==/base.apk!/lib/x86_64/libconscrypt_gmscore_jni.so using ns clns-10 from class loader (caller=/data/app/~~D0otSPDQ6ze3M8w6brTTrA==/com.google.android.gms-xN_U7Ba9Fcm8BTSBEE9ncA==/base.apk!classes3.dex): ok
V/NativeCrypto( 9077): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 305 native methods...
W/r_application_1( 9077): Accessing hidden method Ldalvik/system/VMStack;->getStackClass2()Ljava/lang/Class; (unsupported, reflection, allowed)
I/egsw.a  ( 9077): Unable to retrieve flag snapshot for com.google.android.gms.providerinstaller#com.google.android.gms, using defaults.
W/r_application_1( 9077): Accessing hidden method Ljava/security/spec/ECParameterSpec;->getCurveName()Ljava/lang/String; (unsupported, reflection, allowed)
I/ProviderInstaller( 9077): Installed default security provider GmsCore_OpenSSL
D/TrafficStats( 9077): tagSocket(137) with statsTag=0xffffffff, statsUid=-1
W/r_application_1( 9077): Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (unsupported, reflection, allowed)
W/r_application_1( 9077): Accessing hidden method Ljava/security/spec/ECParameterSpec;->setCurveName(Ljava/lang/String;)V (unsupported, reflection, allowed)
```

### Flutter dependencies

pubspec.yaml : 

name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

 

### Additional context and comments

main.dart : 

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  await sendFeedback();
  runApp(const MyApp());
}

Future<void> sendFeedback() async {
  Map<String, dynamic> feedback = {
    'subject': 'test',
    'description': 'test',
    'e-mail': 'test',
    'platform': 'test',
    'date': FieldValue.serverTimestamp(),
  };
  try {
    await FirebaseFirestore.instance.collection("feedbackTest").add(feedback);

    print('success');
  } catch (e) {
    print(e.toString());
  }
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    _counter++;

    sendFeedback();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

AndroidManifest.xml : 

<manifest xmlns:android="http://schemas.android.com/apk/res/android">
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<uses-permission android:name="com.google.android.gms.permission.ACTIVITY_RECOGNITION" />
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <application
        android:label="flutter_application_1"
        android:name="${applicationName}"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:taskAffinity=""
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
    
    <queries>
        <intent>
            <action android:name="android.intent.action.PROCESS_TEXT"/>
            <data android:mimeType="text/plain"/>
        </intent>
    </queries>
</manifest>

settings.gradle : 
pluginManagement {
    def flutterSdkPath = {
        def properties = new Properties()
        file("local.properties").withInputStream { properties.load(it) }
        def flutterSdkPath = properties.getProperty("flutter.sdk")
        assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
        return flutterSdkPath
    }()

    includeBuild("$flutterSdkPath/packages/flutter_tools/gradle")

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "8.7.0" apply false
    id "org.jetbrains.kotlin.android" version "2.0.20" apply false
    id 'com.google.gms.google-services' version '4.4.2' apply false
}

include ":app"

android/app/build.gradle : 

plugins {
    id "com.android.application"
    id "kotlin-android"
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id "dev.flutter.flutter-gradle-plugin"
    id 'com.google.gms.google-services'
}

android {
    namespace = "com.example.flutter_application_1"
    compileSdk = 34

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_1_8
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId = "com.example.flutter_application_1"
        // You can update the following values to match your application needs.
        // For more information, see: https://flutter.dev/to/review-gradle-config.
        minSdk = 24
        targetSdk = 34
        versionCode = flutter.versionCode
        versionName = flutter.versionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig = signingConfigs.debug
        }
    }
}

flutter {
    source = "../.."
}

dependencies {
  // Import the Firebase BoM
  implementation platform('com.google.firebase:firebase-bom:33.4.0')

  // TODO: Add the dependencies for Firebase products you want to use
  // When using the BoM, don't specify versions in Firebase dependencies
  implementation 'com.google.firebase:firebase-analytics'
  implementation("com.google.firebase:firebase-firestore")
  implementation("com.squareup.okhttp3:okhttp:4.9.3")

  // Add the dependencies for any other desired Firebase products
  // https://firebase.google.com/docs/android/setup#available-libraries
}

android/build.gradle : 

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

cloud firestore rules on console : 

rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if true;
    }
    match /feedback/{document=**} {
        allow create, write: if true;
    }
    match /feedbackTest/{document=**} {
        allow create, write: if true;
    }
    match /appContents/{document=**} {
      allow read: if true;
  	}
  }
}
flutter doctor - v : 

[√] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.19045.4894], locale tr-TR)
    • Flutter version 3.24.3 on channel stable at D:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (4 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\asus\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java       
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.2.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32526.322
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.94.1)
    • VS Code at C:\Users\asus\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.76.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19045.4894]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 129.0.6668.90
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 129.0.2792.79

[√] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by petersephrin** [comment]
Getting the same issue, did you find a fix?

**Comment by DimasSalah** [comment]
get same issue

**Comment by vedatsalmis** [comment]
Since I entered the documents here incompletely, I closed this and opened a new issue. The link is here:
https://github.com/firebase/flutterfire/issues/13486#issuecomment-2405002857
