### ISSUE TITLE
🐛 [Messaging] Support Android Expandable notification

### ISSUE THREAD

**Issue by petrnymsa** [firebase/flutterfire#13483]
## What feature would you like to see?

Add support for expandable notifications https://developer.android.com/develop/ui/views/notifications/expanded

Currently, text is truncated even when users expand the notification in the notification centre. However, Android supports expandable notifications. 

![image](https://github.com/user-attachments/assets/87e52ca2-63b4-43dc-a098-a98975e11aca)

**Comment by SelaseKay** [comment]
Hi @petrnymsa , This isn't within the scope of FlutterFire, as it doesn't control notification appearance on Android. For expandable notifications, you can use packages like `flutter_local_notifications`, which provide support for notification styles like `BigTextStyle` on Android.

**Comment by petrnymsa** [comment]
How is it not in scope of FlutterFire? 

We can through firebase edit text, body, image and a lot of other properties.

Besides Firebase automatically displays notifications if notification part in JSOn is present.

To use package such as local_notifications we would need to use only data notifications, register for various handlers and display manual notificaitons...

So why wouldnt Firebase  support some flag which will be handled?

Do we really need to handle notificaitions manually in this case?

**Comment by SelaseKay** [comment]
Hi @petrnymsa , kindly visit https://firebase.flutter.dev/docs/messaging/notifications/#notification-channels for more clarification.
