### ISSUE TITLE
Could not build the precompiled application for the device. Swift Compiler Error (Xcode): 'headerValue()' is unavailable in Swift: Use `asyncHeaderValue() async -> String?` instead. /Users/chunce/Desktop/%E6%98%A5%E7%AD%96/ccshort_better/ios/Pods/FirebaseAuth/FirebaseAuth/Sources/Swift/Backend/AuthBackend.swift:111:39

### ISSUE THREAD

**Issue by dackArrogant** [firebase/flutterfire#13537]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Description

Could not build the precompiled application for the device.
Swift Compiler Error (Xcode): 'headerValue()' is unavailable in Swift: Use `asyncHeaderValue() async -> String?` instead.
/Users/chunce/Desktop/%E6%98%A5%E7%AD%96/ccshort_better/ios/Pods/FirebaseAuth/FirebaseAuth/Sources/Swift/Backend/AuthBackend.swift:111:39

### Reproducing the issue

Could not build the precompiled application for the device.
Swift Compiler Error (Xcode): 'headerValue()' is unavailable in Swift: Use `asyncHeaderValue() async -> String?` instead.
/Users/chunce/Desktop/%E6%98%A5%E7%AD%96/ccshort_better/ios/Pods/FirebaseAuth/FirebaseAuth/Sources/Swift/Backend/AuthBackend.swift:111:39

### Firebase Core version

5.3.1

### Flutter Version

3.24.0

### Relevant Log Output

```shell
Could not build the precompiled application for the device.
Swift Compiler Error (Xcode): 'headerValue()' is unavailable in Swift: Use `asyncHeaderValue() async -> String?` instead.
/Users/chunce/Desktop/%E6%98%A5%E7%AD%96/ccshort_better/ios/Pods/FirebaseAuth/FirebaseAuth/Sources/Swift/Backend/AuthBackend.swift:111:39
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

### Additional context and comments

Could not build the precompiled application for the device.
Swift Compiler Error (Xcode): 'headerValue()' is unavailable in Swift: Use `asyncHeaderValue() async -> String?` instead.
/Users/chunce/Desktop/%E6%98%A5%E7%AD%96/ccshort_better/ios/Pods/FirebaseAuth/FirebaseAuth/Sources/Swift/Backend/AuthBackend.swift:111:39

**Comment by NarekManukyan** [comment]
@dackArrogant 

This is a duplicate, you can see the temporary solution here https://github.com/firebase/flutterfire/issues/13527#issuecomment-2427646788
