### ISSUE TITLE
[firebase_auth]: AuthBackendRPCImplementation crash

### ISSUE THREAD

**Issue by eli1stark** [firebase/flutterfire#13553]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Auth

### Which platforms are affected?

iOS

### Description

Since we released the version of our app on Oct 10th, these crashes started happening. We had v5.3.0 of firebase_auth, and we weren't updating anything, so it might be something related to the recent updates of FirebaseExtension which is fetched automatically by Podfile while the app is built. Since we updated to v5.3.1 of firebase_auth and released a new app version on Oct 22nd, these crashes have increased in frequency and are now impacting around 50 of our users, with this number growing. It's hard to make sense of the error itself, but it seems related to sign-up. Also, it's interesting that this crash happens in the first second of user sessions, as per Crashlytics, which makes it even more puzzling.
<img width="1265" alt="Screenshot 2024-10-24 at 10 01 55 PM" src="https://github.com/user-attachments/assets/e8705a91-4931-4deb-8869-dbcc81dd5182">

Couple of crashes:

```
          Crashed: com.apple.root.user-initiated-qos.cooperative
0  libswiftCore.dylib             0x3fde58 swift_unknownObjectRetain + 8
1  FirebaseAuth                   0xa0738 $s12FirebaseAuth0B24BackendRPCImplementation33_CDD8170B2D2F91DA2FEF3E7A88D6BF38LLC12callInternal4with8ResponseQzx_tYaKAA0B10RPCRequestRzlFAA18SecureTokenRequestC_Tg5TY0_ + 604
2  libswift_Concurrency.dylib     0x41ac4 <redacted> + 436
3  libswift_Concurrency.dylib     0x43dc4 <redacted> + 1164
4  libswift_Concurrency.dylib     0x41ab0 <redacted> + 416
5  libswift_Concurrency.dylib     0x42d54 <redacted> + 72
6  libdispatch.dylib              0x15be4 <redacted> + 392
7  libdispatch.dylib              0x163ec <redacted> + 156
8  libsystem_pthread.dylib        0x1928 _pthread_wqthread + 228
9  libsystem_pthread.dylib        0x1a04 start_wqthread + 8
```

```
          Crashed: com.apple.root.user-initiated-qos.cooperative
0  libswiftCore.dylib             0x4388c8 swift_unknownObjectRetain + 8
1  FirebaseAuth                   0xa0738 $s12FirebaseAuth0B24BackendRPCImplementation33_CDD8170B2D2F91DA2FEF3E7A88D6BF38LLC12callInternal4with8ResponseQzx_tYaKAA0B10RPCRequestRzlFAA18SecureTokenRequestC_Tg5TY0_ + 604
2  libswift_Concurrency.dylib     0x610e4 swift::runJobInEstablishedExecutorContext(swift::Job*) + 252
3  libswift_Concurrency.dylib     0x624f4 swift_job_runImpl(swift::Job*, swift::SerialExecutorRef) + 144
4  libdispatch.dylib              0x15d8c _dispatch_root_queue_drain + 392
5  libdispatch.dylib              0x16590 _dispatch_worker_thread2 + 156
6  libsystem_pthread.dylib        0x4c40 _pthread_wqthread + 228
7  libsystem_pthread.dylib        0x1488 start_wqthread + 8
```

```
      Crashed: com.apple.root.user-initiated-qos.cooperative
0  libswiftCore.dylib             0x4388c8 swift_unknownObjectRetain + 8
1  FirebaseAuth                   0xa0738 $s12FirebaseAuth0B24BackendRPCImplementation33_CDD8170B2D2F91DA2FEF3E7A88D6BF38LLC12callInternal4with8ResponseQzx_tYaKAA0B10RPCRequestRzlFAA18SecureTokenRequestC_Tg5TY0_ + 604
2  libswift_Concurrency.dylib     0x610e4 swift::runJobInEstablishedExecutorContext(swift::Job*) + 252
3  libswift_Concurrency.dylib     0x63a08 (anonymous namespace)::ProcessOutOfLineJob::process(swift::Job*) + 480
4  libswift_Concurrency.dylib     0x611a4 swift::runJobInEstablishedExecutorContext(swift::Job*) + 444
5  libswift_Concurrency.dylib     0x624f4 swift_job_runImpl(swift::Job*, swift::SerialExecutorRef) + 144
6  libdispatch.dylib              0x15d8c _dispatch_root_queue_drain + 392
7  libdispatch.dylib              0x16590 _dispatch_worker_thread2 + 156
8  libsystem_pthread.dylib        0x4c40 _pthread_wqthread + 228
9  libsystem_pthread.dylib        0x1488 start_wqthread + 8
```

### Reproducing the issue

This crash only impacts iOS devices. We went through all possible auth scenarios in our app, and we couldn't reproduce it locally in debug mode. However, we were able to reproduce it with our production build, the app indeed crashes in the first second of the session. We recorded crashes on iOS 17 and iOS 18.

### Firebase Core version

3.6.0

### Flutter Version

3.24.3

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

  firebase_core: 3.6.0
  firebase_crashlytics: 4.1.3
  firebase_analytics: 11.3.3
  firebase_dynamic_links: 6.0.8
  firebase_app_check: 0.3.1+2
  firebase_auth: 5.3.1
  firebase_database: 11.1.4
  firebase_performance: 0.10.0+7
  firebase_remote_config: 5.1.3
  cloud_firestore: 5.4.4
  cloud_functions: 5.1.2
  firebase_app_installations: 0.3.1+3


```

</details>

### Additional context and comments

Similar issues: 
1. https://github.com/firebase/firebase-ios-sdk/issues/13650
2. https://github.com/firebase/firebase-ios-sdk/issues/13761

It doesn't seem that Firebase Apple 11.4.0 fixed the issue or flutter package is using older version of iOS plugin.

**Comment by eli1stark** [comment]
Is there a way for us to quickly patch it to production based on [Firebase Apple v11.4.0](https://github.com/firebase/firebase-ios-sdk/releases/tag/11.4.0)?

**Comment by eli1stark** [comment]
Impact: It's currently affecting all iOS devices that are using versions of the apps built post-Oct. 10th (maybe even earlier) and using `v3.5.0`, `v3.6.0` of `firebase_core` and `v3.5.0` and `v3.5.1` of `firebase_auth`. All iOS devices are crashing randomly (sometimes they do and sometimes they don't) within the first seconds of a user session in production.

**Comment by eli1stark** [comment]
Related: https://github.com/firebase/flutterfire/issues/13451

**Comment by Lyokone** [comment]
Hello @eli1stark, thanks for reporting, unfortunately 11.4.0 had a crash in it, and 11.4.1 was a Swift Package Manager only release. We hope to be able to use 11.4.2.

**Comment by russellwheatley** [comment]
Hey @eli1stark - try overriding firebase-ios-sdk to 11.4.0 by doing the following in your ios/Podfile:

```
FirebaseSDKVersion = '11.4.0'
```

please delete old Pods and install latest whilst updating local specs:

```
cd ios && rm -rf Pods && rm Podfile.lock
pod install --repo-update
```

run your app now and let us know if this resolves your issue.

**Comment by eli1stark** [comment]
Thank you so much, team, for a quick response!

The only way we can test whether the fix is working is by publishing the fix to production, because it's very difficult to reproduce locally at a small user scale.

We added version override as the very first line of our ios/Podfile like this:
```
$FirebaseSDKVersion = '11.4.0'
```

@Lyokone You mentioned that `11.4.0` contains a crash. Is it safe to override with this version in this case and publish the build to production? The currently supported version by flutter packages is `11.2.0`. I also checked release notes for ios sdk and it seems that `11.4.2` was published on [Oct 23, 2023](https://firebase.google.com/support/release-notes/ios#version_1142_-_october_23_2023). We tried to override with `11.4.1` and `11.4.2` but some firebase packages don't support this version yet and pod install fails.

We are currently testing and preparing a new build for production release but before releasing, we just want you to confirm version discrepancies between `11.4.0` and `11.4.2`. We will do a staged roll-out and in case some other problems arise, we will revert back to the older version that doesn't have an override.
 
@russellwheatley Is there any ETA when flutter packages will support `11.4.0` and an official fix will be put in place via release through pub.dev?

**Comment by russellwheatley** [comment]
@eli1stark - From what I understand, the problem in v11.4.0 was an issue with a couple of transitive dependencies that have had hot fix releases. Meaning that; if you install new Pods using instructions here: https://github.com/firebase/flutterfire/issues/13553#issuecomment-2441274478

It should install the latest transitive dependencies (with hot fixes) and you shouldn't experience the crashes mentioned. But worth double checking first.

Our release schedule is a little slimmer the closer we get to Christmas, I'd like to get one out this week, but if it isn't possible, it'll be next week. Let me know how it goes with 11.4.0, our CI is green but if you can confirm it fixes your issue, we can look to get this merged 👍

**Comment by eli1stark** [comment]
@russellwheatley We've been monitoring our new release in production for 2 days and haven't seen any crashes so far, so it seems like overriding the Firebase version to v11.4.0 did fix the issue. We'll continue monitoring, and if something comes up, I'll post it here, but so far it seems stable. Thank you for your help!

**Comment by russellwheatley** [comment]
@eli1stark - thank you for the confirmation, please let me know if anything further comes up 🙏
