### ISSUE TITLE
[firebase_messaging]: `priority: "high"` sends a notification that cannot be interacted with.

### ISSUE THREAD

**Issue by RepliedSage11** [firebase/flutterfire#13569]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Messaging

### Which platforms are affected?

Android

### Description

I have discovered a strange bug/interaction when using FCM in my Flutter app on a particular Samsung device.

When sending the notification with priority set to high, the notification is received by the device and tapping the notification opens the app, but none of the FirebaseMessaging callbacks are called and getInitialMessage returns null. This happens for terminated, backgrounded and foregrounded states.

When using the FCM API to send a push notification to an android device we use this body:
```json
{
  "token": "device_token",
  "notification": {
     "title": "some",
     "body": "thing"
   },
   "data": {...},
   "android": {
     "priority": "high",
     "ttl": 123123123123,
     "notification": {
       "sound": "default"
     }
   }
}
```

The priority is set to high and everything works as expect on all devices, expect a Samsung S24+. 

When sending this payload to this particular Samsung, it receives the notification and it can be seen in the notification tray, but when tapping the notification the app opens, but nothing else happens. FirebaseMessaging doesn't call any of the callbacks (onMessage, onBackgroundMessage) and the getInitialMessage method returns null. 

Changing the priority to normal fixes this and tapping the notification works as expected. 

It looks like it has something to do with the [Notification delegation with Google Play services](https://firebase.google.com/docs/cloud-messaging/android/message-priority#proxy), since if we add a `"proxy": "DENY"` property to the `android.notification` object in the above payload, the notification behaves as expected even with priority set to high.

We are using the latest firebase_messaging (15.1.3)

### Reproducing the issue

We can reproduce the issue reliably with the steps above, but we are not sure if this is a problem with a particular device/OS version or a broader issue. 

The device in question is a Samsung S24+.
Android 14
OneUI 6.1

### Firebase Core version

3.6.0

### Flutter Version

3.24.4

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by SelaseKay** [comment]
Hi @RepliedSage11, thanks for the report. I'm currently looking into this.

**Comment by RBen123** [comment]
> @RBen123 does the workaround I described fix it for you too? (proxy: DENY)

@RepliedSage11 yes, proxy: DENY also resolves the issue on our end.

**Comment by SelaseKay** [comment]
Hi @RepliedSage11 , thanks for the report. I couldn’t reproduce this issue on a Samsung Galaxy A12 (Android 11) or a Pixel 3a emulator (Android 14). This may be a device-specific issue. As I understand it, `onMessage` and `onBackgroundMessage` aren’t expected to trigger on a notification tap. However, `getInitialMessage` should return a value if the app is opened from a terminated state by tapping a notification, provided there’s a data payload.

**Comment by RepliedSage11** [comment]
Hi @SelaseKay, we are experiencing issues with foregrounded app state too. When sending the notification with normal priority, the OS does not show a notification, but the `onMessage` callback is called (as expected). When sending the notification with a high priority, the OS shows a notification, but the `onMessage` callback is not called. When tapping on the notification in the notification tray, the app is opened, but none of the callbacks are called and `getInitialMessage` returns null. 

Surely this is device specific, since we have so far identified only one device where this happens.

**Comment by russellwheatley** [comment]
@RepliedSage11 - have you tried setting this in you app manifest:

```xml
 <meta-data android:name= "delivery_metrics_exported_to_big_query_enabled" android:value="false"/>
```

[as per the documentation](https://firebase.google.com/docs/cloud-messaging/android/message-priority#proxy). It seems likely it is related to proxying notifications. This feature is in beta so I wonder if there is some kinks that need ironing out.

**Comment by RepliedSage11** [comment]
As far as I understand `proxy: DENY` does the same thing as this settings, just on a per-message basis.

**Comment by russellwheatley** [comment]
@RepliedSage11 - yes, that is correct. I was suggesting it as a workaround until there is a resolution. Nothing has changed in the FlutterFire android src code for messaging in 5 months. It makes me think there is either additional setup that has been missed for proxying to work, or there is a bug upstream. 

At the moment, you're the only one able to reproduce as it requires a specific device. If you find the root cause of this issue, we would be grateful if you could post your findings here 🙏
