### ISSUE TITLE
[firebase_messaging] App crashes when tap notification in iOS

### ISSUE THREAD

**Issue by amrgetment** [firebase/flutterfire#13573]
The app crashes when I tap on a notification that I received while the app terminated 
It works fine but on release mode only not debug mode 
and on Crashlytics I got useless logs
```
Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x00000000000000a0

```
So I am suggesting adding to the readme that taps on notification that was received while the app terminated would be tested on release mode only

I have Image notification extension service by the way

**Comment by SelaseKay** [comment]
I'm unable to reproduce this. Kindly use the template for bug reports and file another issue. You are using documentation template at the moment.

**Comment by amrgetment** [comment]
@SelaseKay Did you use the notification extension?

**Comment by amrgetment** [comment]
I didn’t use the template as I was thinking it was a known issue with no solution, so I opened the issue for documentation
