### ISSUE TITLE
Xcode upgrading issue fo firebase plugin

### ISSUE THREAD

**Issue by hozefamakhariya** [firebase/flutterfire#13649]
Launching lib/main.dart on iPhone 16 Plus in debug mode...
Running pod install...                                             15.0s
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         3.3s
Xcode build done.                                           22.1s
Failed to build iOS app
Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_messaging.FLTFirebaseMessagingPlugin':
'/Users/hozefamakhariya/projects/superer_bus-master/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/hozefamakhariya/.pub-cache/hosted/pub.dev/firebase_messaging-15.1.0/ios/Classes/FLTFirebaseMessagingPlugin.h:11:8

Could not build the application for the simulator.
Error launching application on iPhone 16 Plus.

Please check this is the issue i always if i run my flutter app in ios simulator i have already all this latest version of xcode and macos and cocoapods but dont understand this issue always occur

**Comment by SelaseKay** [comment]
This issue has been resolved: https://github.com/firebase/flutterfire/issues/13323
