### ISSUE TITLE
🐛 [firebase_messaging] Background messages in IOS

### ISSUE THREAD

**Issue by MotiBartovIntentHQ** [firebase/flutterfire#13652]
## What feature would you like to see?

Hi, 
I would like to ask about firebase_messaging background messages support in IOS

Looking in your repo, i've followed the background isolate activation both Android and IOS and notices that there is no implementation for `startBackgroundIsolate` api in IOS?

On Android, I do see that you registering the rawHandles when this API called, later you use rawHandles values to process messages in background, but on IOS there is no logic for `startBackgroundIsolate` api?

This is the code snippet for IOS, its just empty and returns success nil. 
`else if ([@"Messaging#startBackgroundIsolate" isEqualToString:call.method]) {
    methodCallResult.success(nil);
  }`

In Android on the other-hand, it has rich logic for this.

Does it means that there is no support for background messages in IOS?

Thanks for your support

**Comment by russellwheatley** [comment]
background messages are supported in iOS, but due to the differences in iOS and android, iOS doesn't need the startBackgroundIsolate to process messages.

**Comment by MotiBartovIntentHQ** [comment]
Thank you for your response.

It was little bit confused but I now understand better IOS app states (foreground, background, terminated) and it helps me to understand library design.
