### ISSUE TITLE
[flutterfire]: Android package name limited to 15 characters

### ISSUE THREAD

**Issue by arrrrny** [firebase/flutterfire#13651]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Other

### Which platforms are affected?

Android

### Description

my android package name is wtf.zikzak.zikzak.
Using the CLI as  

flutterfire configure --project=zikzakzikzakwtf

✔ Which Android application id (or package name) do you want to use for this configuration, e.g. 'com.example.app'? · wtf.zikzak.zikz

### Reproducing the issue

flutterfire configure --project='your_project'
on Android try to type a package name 16 characters or longer

### Firebase Core version

3.5.0

### Flutter Version

3.24.4

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by SelaseKay** [comment]
Hi @arrrrny, thanks for the report. Your issue seems to be related to https://github.com/invertase/flutterfire_cli/issues/341. You can follow that thread for updates.

**Comment by arrrrny** [comment]
@SelaseKay hope this gets fixed soon.
