### ISSUE TITLE
firebase_auth_emulators : Error when using google sign in on remote android physical device 

### ISSUE THREAD

**Issue by NelCit** [firebase/flutterfire#13681]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Core, Auth

### Which platforms are affected?

Android

### Description

When trying to sign in with google with firebase_auth_ui while using a remote android device and auth emulators , i have the error message "An error occurred"

### Reproducing the issue

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

    await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform);

    if (kDebugMode) {

      if (Platform.isAndroid) {
        FirebaseAuth.instance.useAuthEmulator('localhost', 9099, automaticHostMapping: false);
        FirebaseFirestore.instance.useFirestoreEmulator('localhost', 8080, automaticHostMapping: false);
      } else if (Platform.isIOS || Platform.isMacOS || Platform.isLinux || Platform.isWindows) {
        FirebaseAuth.instance.useAuthEmulator('localhost', 9099);
        FirebaseFirestore.instance.useFirestoreEmulator('localhost', 8080);
      }
    }
  runApp(MyApp());

}

i have enable tcp reverse to be able to run localhost on my device. : 
adb reverse tcp:8080 tcp:8080
adb reverse tcp:9099 tcp:9099

i have tested with automaticHostMapping = true, and automaticHostMapping = false.

Note : it works with email/mdp , but not with google sign in

### Firebase Core version

3.6.0

### Flutter Version

3.24.4

### Relevant Log Output

```shell
there is no output..
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

### Additional context and comments

n/a

**Comment by SelaseKay** [comment]
Hi @NelCit, could you provide a complete minimal code reproducing this issue?

**Comment by NelCit** [comment]
Was an issue with SHA-1, the information was hard to find, it does not exists on the codelabs tutorial. Please do a "implement google auth with android" in the tutorial.
