### ISSUE TITLE
Getting No such module 'GoogleUtilities_AppDelegateSwizzler' when build iOS with firebase_auth: ^5.3.2 

### ISSUE THREAD

**Issue by Kora3** [firebase/flutterfire#13819]
### Description

When I use firebase_auth: ^5.3.2 package, I get an error: 

Swift Compiler Error (Xcode): No such module 'GoogleUtilities_AppDelegateSwizzler'
..../Pods/FirebaseAuth/FirebaseAuth/Sources/Swift/Auth/Auth.swift:23:30
Encountered error while archiving for device.

Getting this error when i run flutter build ipa, but its work on android (flutter build appbundle).

When i remove firebase_auth: ^5.3.2 package, flutter build ipa work fine

### Reproducing the issue

Add firebase_auth: ^5.3.2 package and run flutter build ipa.

### Firebase SDK Version

11.4.0

### Xcode Version

16.0

### Installation Method

CocoaPods

### Firebase Product(s)

Authentication

### Targeted Platforms

iOS

### Relevant Log Output

```shell
Running pod install...                                              3,9s
Running Xcode build...                                                  
Xcode archive done.                                         72,4s
Failed to build iOS app
Swift Compiler Error (Xcode): No such module 'GoogleUtilities_AppDelegateSwizzler'
.../ios/Pods/FirebaseAuth/FirebaseAuth/Sources/Swift/Auth/Auth.swift:23:30


Encountered error while archiving for device.
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

PODS:
  - app_links (0.0.2):
    - Flutter
  - app_tracking_transparency (0.0.1):
    - Flutter
  - AppAuth (1.7.5):
    - AppAuth/Core (= 1.7.5)
    - AppAuth/ExternalUserAgent (= 1.7.5)
  - AppAuth/Core (1.7.5)
  - AppAuth/ExternalUserAgent (1.7.5):
    - AppAuth/Core
  - audioplayers_darwin (0.0.1):
    - Flutter
  - connectivity_plus (0.0.1):
    - Flutter
    - FlutterMacOS
  - device_info_plus (0.0.1):
    - Flutter
  - DKImagePickerController/Core (4.3.9):
    - DKImagePickerController/ImageDataManager
    - DKImagePickerController/Resource
  - DKImagePickerController/ImageDataManager (4.3.9)
  - DKImagePickerController/PhotoGallery (4.3.9):
    - DKImagePickerController/Core
    - DKPhotoGallery
  - DKImagePickerController/Resource (4.3.9)
  - DKPhotoGallery (0.0.19):
    - DKPhotoGallery/Core (= 0.0.19)
    - DKPhotoGallery/Model (= 0.0.19)
    - DKPhotoGallery/Preview (= 0.0.19)
    - DKPhotoGallery/Resource (= 0.0.19)
    - SDWebImage
    - SwiftyGif
  - DKPhotoGallery/Core (0.0.19):
    - DKPhotoGallery/Model
    - DKPhotoGallery/Preview
    - SDWebImage
    - SwiftyGif
  - DKPhotoGallery/Model (0.0.19):
    - SDWebImage
    - SwiftyGif
  - DKPhotoGallery/Preview (0.0.19):
    - DKPhotoGallery/Model
    - DKPhotoGallery/Resource
    - SDWebImage
    - SwiftyGif
  - DKPhotoGallery/Resource (0.0.19):
    - SDWebImage
    - SwiftyGif
  - emoji_picker_flutter (0.0.1):
    - Flutter
  - ffmpeg-kit-ios-min (6.0)
  - ffmpeg_kit_flutter_min (6.0.3):
    - ffmpeg_kit_flutter_min/min (= 6.0.3)
    - Flutter
  - ffmpeg_kit_flutter_min/min (6.0.3):
    - ffmpeg-kit-ios-min (= 6.0)
    - Flutter
  - file_picker (0.0.1):
    - DKImagePickerController/PhotoGallery
    - Flutter
  - Firebase/Auth (11.4.0):
    - Firebase/CoreOnly
    - FirebaseAuth (~> 11.4.0)
  - Firebase/CoreOnly (11.4.0):
    - FirebaseCore (= 11.4.0)
  - Firebase/Messaging (11.4.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 11.4.0)
  - firebase_auth (5.3.2):
    - Firebase/Auth (= 11.4.0)
    - firebase_core
    - Flutter
  - firebase_core (3.7.0):
    - Firebase/CoreOnly (= 11.4.0)
    - Flutter
  - firebase_messaging (15.1.4):
    - Firebase/Messaging (= 11.4.0)
    - firebase_core
    - Flutter
  - FirebaseAppCheckInterop (11.4.0)
  - FirebaseAuth (11.4.0):
    - FirebaseAppCheckInterop (~> 11.0)
    - FirebaseAuthInterop (~> 11.0)
    - FirebaseCore (~> 11.4)
    - FirebaseCoreExtension (~> 11.4)
    - GoogleUtilities/AppDelegateSwizzler (~> 8.0)
    - GoogleUtilities/Environment (~> 8.0)
    - GTMSessionFetcher/Core (< 5.0, >= 3.4)
    - RecaptchaInterop (~> 100.0)
  - FirebaseAuthInterop (11.4.0)
  - FirebaseCore (11.4.0):
    - FirebaseCoreInternal (~> 11.0)
    - GoogleUtilities/Environment (~> 8.0)
    - GoogleUtilities/Logger (~> 8.0)
  - FirebaseCoreExtension (11.4.1):
    - FirebaseCore (~> 11.0)
  - FirebaseCoreInternal (11.4.2):
    - "GoogleUtilities/NSData+zlib (~> 8.0)"
  - FirebaseInstallations (11.4.0):
    - FirebaseCore (~> 11.0)
    - GoogleUtilities/Environment (~> 8.0)
    - GoogleUtilities/UserDefaults (~> 8.0)
    - PromisesObjC (~> 2.4)
  - FirebaseMessaging (11.4.0):
    - FirebaseCore (~> 11.0)
    - FirebaseInstallations (~> 11.0)
    - GoogleDataTransport (~> 10.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 8.0)
    - GoogleUtilities/Environment (~> 8.0)
    - GoogleUtilities/Reachability (~> 8.0)
    - GoogleUtilities/UserDefaults (~> 8.0)
    - nanopb (~> 3.30910.0)
  - Flutter (1.0.0)
  - flutter_contacts (0.0.1):
    - Flutter
  - flutter_image_compress_common (1.0.0):
    - Flutter
    - Mantle
    - SDWebImage
    - SDWebImageWebPCoder
  - flutter_keyboard_visibility (0.0.1):
    - Flutter
  - flutter_local_notifications (0.0.1):
    - Flutter
  - flutter_native_splash (0.0.1):
    - Flutter
  - gallery_saver_plus (0.0.1):
    - Flutter
  - geolocator_apple (1.2.0):
    - Flutter
  - google_mlkit_commons (0.9.0):
    - Flutter
    - MLKitVision
  - google_mlkit_image_labeling (0.13.0):
    - Flutter
    - google_mlkit_commons
    - GoogleMLKit/ImageLabeling (~> 7.0.0)
    - GoogleMLKit/ImageLabelingCustom (~> 7.0.0)
  - google_mlkit_language_id (0.12.0):
    - Flutter
    - google_mlkit_commons
    - GoogleMLKit/LanguageID (~> 7.0.0)
  - google_sign_in_ios (0.0.1):
    - Flutter
    - FlutterMacOS
    - GoogleSignIn (~> 7.0.0)
  - GoogleDataTransport (10.1.0):
    - nanopb (~> 3.30910.0)
    - PromisesObjC (~> 2.4)
  - GoogleMLKit/ImageLabeling (7.0.0):
    - GoogleMLKit/MLKitCore
    - MLKitImageLabeling (~> 6.0.0)
  - GoogleMLKit/ImageLabelingCustom (7.0.0):
    - GoogleMLKit/MLKitCore
    - MLKitImageLabelingCustom (~> 6.0.0)
  - GoogleMLKit/LanguageID (7.0.0):
    - GoogleMLKit/MLKitCore
    - MLKitLanguageID (~> 7.0.0)
  - GoogleMLKit/MLKitCore (7.0.0):
    - MLKitCommon (~> 12.0.0)
  - GoogleSignIn (7.0.0):
    - AppAuth (~> 1.5)
    - GTMAppAuth (< 3.0, >= 1.3)
    - GTMSessionFetcher/Core (< 4.0, >= 1.1)
  - GoogleToolboxForMac/Defines (4.2.1)
  - GoogleToolboxForMac/Logger (4.2.1):
    - GoogleToolboxForMac/Defines (= 4.2.1)
  - "GoogleToolboxForMac/NSData+zlib (4.2.1)":
    - GoogleToolboxForMac/Defines (= 4.2.1)
  - GoogleToolboxForMac/StringEncoding (4.2.1):
    - GoogleToolboxForMac/Defines (= 4.2.1)
  - GoogleUtilities/AppDelegateSwizzler (8.0.2):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
    - GoogleUtilities/Privacy
  - GoogleUtilities/Environment (8.0.2):
    - GoogleUtilities/Privacy
  - GoogleUtilities/Logger (8.0.2):
    - GoogleUtilities/Environment
    - GoogleUtilities/Privacy
  - GoogleUtilities/Network (8.0.2):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Privacy
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (8.0.2)":
    - GoogleUtilities/Privacy
  - GoogleUtilities/Privacy (8.0.2)
  - GoogleUtilities/Reachability (8.0.2):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - GoogleUtilities/UserDefaults (8.0.2):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - GTMAppAuth (2.0.0):
    - AppAuth/Core (~> 1.6)
    - GTMSessionFetcher/Core (< 4.0, >= 1.5)
  - GTMSessionFetcher/Core (3.5.0)
  - image_cropper (0.0.4):
    - Flutter
    - TOCropViewController (~> 2.7.4)
  - image_picker_ios (0.0.1):
    - Flutter
  - libwebp (1.3.2):
    - libwebp/demux (= 1.3.2)
    - libwebp/mux (= 1.3.2)
    - libwebp/sharpyuv (= 1.3.2)
    - libwebp/webp (= 1.3.2)
  - libwebp/demux (1.3.2):
    - libwebp/webp
  - libwebp/mux (1.3.2):
    - libwebp/demux
  - libwebp/sharpyuv (1.3.2)
  - libwebp/webp (1.3.2):
    - libwebp/sharpyuv
  - light_compressor (1.0.0):
    - Flutter
  - Mantle (2.2.0):
    - Mantle/extobjc (= 2.2.0)
  - Mantle/extobjc (2.2.0)
  - maps_launcher (0.0.1):
    - Flutter
  - MLImage (1.0.0-beta6)
  - MLKitCommon (12.0.0):
    - GoogleDataTransport (~> 10.0)
    - GoogleToolboxForMac/Logger (< 5.0, >= 4.2.1)
    - "GoogleToolboxForMac/NSData+zlib (< 5.0, >= 4.2.1)"
    - GoogleUtilities/Logger (~> 8.0)
    - GoogleUtilities/UserDefaults (~> 8.0)
    - GTMSessionFetcher/Core (< 4.0, >= 3.3.2)
  - MLKitImageLabeling (6.0.0):
    - MLKitCommon (~> 12.0)
    - MLKitImageLabelingCommon (~> 8.0)
    - MLKitVision (~> 8.0)
    - MLKitVisionKit (~> 9.0)
  - MLKitImageLabelingCommon (8.0.0):
    - MLKitCommon (~> 12.0)
    - MLKitVision (~> 8.0)
  - MLKitImageLabelingCustom (6.0.0):
    - MLKitCommon (~> 12.0)
    - MLKitImageLabelingCommon (~> 8.0)
    - MLKitVision (~> 8.0)
    - MLKitVisionKit (~> 9.0)
  - MLKitLanguageID (7.0.0):
    - MLKitNaturalLanguage (~> 8.0)
  - MLKitNaturalLanguage (8.0.0):
    - GoogleToolboxForMac/Logger (< 5.0, >= 4.2.1)
    - "GoogleToolboxForMac/NSData+zlib (< 5.0, >= 4.2.1)"
    - GoogleToolboxForMac/StringEncoding (< 5.0, >= 4.2.1)
    - GTMSessionFetcher/Core (< 4.0, >= 3.3.2)
    - MLKitCommon (~> 12.0)
  - MLKitObjectDetectionCommon (8.0.0):
    - MLKitCommon (~> 12.0)
    - MLKitVision (~> 8.0)
  - MLKitVision (8.0.0):
    - GoogleToolboxForMac/Logger (< 5.0, >= 4.2.1)
    - "GoogleToolboxForMac/NSData+zlib (< 5.0, >= 4.2.1)"
    - GTMSessionFetcher/Core (< 4.0, >= 3.3.2)
    - MLImage (= 1.0.0-beta6)
    - MLKitCommon (~> 12.0)
  - MLKitVisionKit (9.0.0):
    - MLKitCommon (~> 12.0)
    - MLKitImageLabelingCommon (~> 8.0)
    - MLKitObjectDetectionCommon (~> 8.0)
    - MLKitVision (~> 8.0)
  - nanopb (3.30910.0):
    - nanopb/decode (= 3.30910.0)
    - nanopb/encode (= 3.30910.0)
  - nanopb/decode (3.30910.0)
  - nanopb/encode (3.30910.0)
  - open_filex (0.0.2):
    - Flutter
  - package_info_plus (0.4.5):
    - Flutter
  - path_provider_foundation (0.0.1):
    - Flutter
    - FlutterMacOS
  - permission_handler_apple (9.3.0):
    - Flutter
  - PromisesObjC (2.4.0)
  - RecaptchaInterop (100.0.0)
  - receive_sharing_intent (1.6.8):
    - Flutter
  - record_darwin (1.0.0):
    - Flutter
    - FlutterMacOS
  - SDWebImage (5.20.0):
    - SDWebImage/Core (= 5.20.0)
  - SDWebImage/Core (5.20.0)
  - SDWebImageWebPCoder (0.14.6):
    - libwebp (~> 1.0)
    - SDWebImage/Core (~> 5.17)
  - share_plus (0.0.1):
    - Flutter
  - shared_preferences_foundation (0.0.1):
    - Flutter
    - FlutterMacOS
  - simple_barcode_scanner (0.1.7):
    - Flutter
  - sqflite (0.0.3):
    - Flutter
    - FlutterMacOS
  - SwiftyGif (5.4.5)
  - TOCropViewController (2.7.4)
  - url_launcher_ios (0.0.1):
    - Flutter
  - vibration (1.7.5):
    - Flutter
  - video_player_avfoundation (0.0.1):
    - Flutter
    - FlutterMacOS
  - video_thumbnail (0.0.1):
    - Flutter
    - libwebp
  - wakelock_plus (0.0.1):
    - Flutter

DEPENDENCIES:
  - app_links (from `.symlinks/plugins/app_links/ios`)
  - app_tracking_transparency (from `.symlinks/plugins/app_tracking_transparency/ios`)
  - audioplayers_darwin (from `.symlinks/plugins/audioplayers_darwin/ios`)
  - connectivity_plus (from `.symlinks/plugins/connectivity_plus/darwin`)
  - device_info_plus (from `.symlinks/plugins/device_info_plus/ios`)
  - emoji_picker_flutter (from `.symlinks/plugins/emoji_picker_flutter/ios`)
  - ffmpeg_kit_flutter_min (from `.symlinks/plugins/ffmpeg_kit_flutter_min/ios`)
  - file_picker (from `.symlinks/plugins/file_picker/ios`)
  - firebase_auth (from `.symlinks/plugins/firebase_auth/ios`)
  - firebase_core (from `.symlinks/plugins/firebase_core/ios`)
  - firebase_messaging (from `.symlinks/plugins/firebase_messaging/ios`)
  - Flutter (from `Flutter`)
  - flutter_contacts (from `.symlinks/plugins/flutter_contacts/ios`)
  - flutter_image_compress_common (from `.symlinks/plugins/flutter_image_compress_common/ios`)
  - flutter_keyboard_visibility (from `.symlinks/plugins/flutter_keyboard_visibility/ios`)
  - flutter_local_notifications (from `.symlinks/plugins/flutter_local_notifications/ios`)
  - flutter_native_splash (from `.symlinks/plugins/flutter_native_splash/ios`)
  - gallery_saver_plus (from `.symlinks/plugins/gallery_saver_plus/ios`)
  - geolocator_apple (from `.symlinks/plugins/geolocator_apple/ios`)
  - google_mlkit_commons (from `.symlinks/plugins/google_mlkit_commons/ios`)
  - google_mlkit_image_labeling (from `.symlinks/plugins/google_mlkit_image_labeling/ios`)
  - google_mlkit_language_id (from `.symlinks/plugins/google_mlkit_language_id/ios`)
  - google_sign_in_ios (from `.symlinks/plugins/google_sign_in_ios/darwin`)
  - image_cropper (from `.symlinks/plugins/image_cropper/ios`)
  - image_picker_ios (from `.symlinks/plugins/image_picker_ios/ios`)
  - light_compressor (from `.symlinks/plugins/light_compressor/ios`)
  - maps_launcher (from `.symlinks/plugins/maps_launcher/ios`)
  - open_filex (from `.symlinks/plugins/open_filex/ios`)
  - package_info_plus (from `.symlinks/plugins/package_info_plus/ios`)
  - path_provider_foundation (from `.symlinks/plugins/path_provider_foundation/darwin`)
  - permission_handler_apple (from `.symlinks/plugins/permission_handler_apple/ios`)
  - receive_sharing_intent (from `.symlinks/plugins/receive_sharing_intent/ios`)
  - record_darwin (from `.symlinks/plugins/record_darwin/ios`)
  - share_plus (from `.symlinks/plugins/share_plus/ios`)
  - shared_preferences_foundation (from `.symlinks/plugins/shared_preferences_foundation/darwin`)
  - simple_barcode_scanner (from `.symlinks/plugins/simple_barcode_scanner/ios`)
  - sqflite (from `.symlinks/plugins/sqflite/darwin`)
  - url_launcher_ios (from `.symlinks/plugins/url_launcher_ios/ios`)
  - vibration (from `.symlinks/plugins/vibration/ios`)
  - video_player_avfoundation (from `.symlinks/plugins/video_player_avfoundation/darwin`)
  - video_thumbnail (from `.symlinks/plugins/video_thumbnail/ios`)
  - wakelock_plus (from `.symlinks/plugins/wakelock_plus/ios`)

SPEC REPOS:
  https://github.com/CocoaPods/Specs.git:
    - AppAuth
    - DKImagePickerController
    - DKPhotoGallery
    - ffmpeg-kit-ios-min
    - Firebase
    - FirebaseAppCheckInterop
    - FirebaseAuth
    - FirebaseAuthInterop
    - FirebaseCore
    - FirebaseCoreExtension
    - FirebaseCoreInternal
    - FirebaseInstallations
    - FirebaseMessaging
    - GoogleDataTransport
    - GoogleMLKit
    - GoogleSignIn
    - GoogleToolboxForMac
    - GoogleUtilities
    - GTMAppAuth
    - GTMSessionFetcher
    - libwebp
    - Mantle
    - MLImage
    - MLKitCommon
    - MLKitImageLabeling
    - MLKitImageLabelingCommon
    - MLKitImageLabelingCustom
    - MLKitLanguageID
    - MLKitNaturalLanguage
    - MLKitObjectDetectionCommon
    - MLKitVision
    - MLKitVisionKit
    - nanopb
    - PromisesObjC
    - RecaptchaInterop
    - SDWebImage
    - SDWebImageWebPCoder
    - SwiftyGif
    - TOCropViewController

EXTERNAL SOURCES:
  app_links:
    :path: ".symlinks/plugins/app_links/ios"
  app_tracking_transparency:
    :path: ".symlinks/plugins/app_tracking_transparency/ios"
  audioplayers_darwin:
    :path: ".symlinks/plugins/audioplayers_darwin/ios"
  connectivity_plus:
    :path: ".symlinks/plugins/connectivity_plus/darwin"
  device_info_plus:
    :path: ".symlinks/plugins/device_info_plus/ios"
  emoji_picker_flutter:
    :path: ".symlinks/plugins/emoji_picker_flutter/ios"
  ffmpeg_kit_flutter_min:
    :path: ".symlinks/plugins/ffmpeg_kit_flutter_min/ios"
  file_picker:
    :path: ".symlinks/plugins/file_picker/ios"
  firebase_auth:
    :path: ".symlinks/plugins/firebase_auth/ios"
  firebase_core:
    :path: ".symlinks/plugins/firebase_core/ios"
  firebase_messaging:
    :path: ".symlinks/plugins/firebase_messaging/ios"
  Flutter:
    :path: Flutter
  flutter_contacts:
    :path: ".symlinks/plugins/flutter_contacts/ios"
  flutter_image_compress_common:
    :path: ".symlinks/plugins/flutter_image_compress_common/ios"
  flutter_keyboard_visibility:
    :path: ".symlinks/plugins/flutter_keyboard_visibility/ios"
  flutter_local_notifications:
    :path: ".symlinks/plugins/flutter_local_notifications/ios"
  flutter_native_splash:
    :path: ".symlinks/plugins/flutter_native_splash/ios"
  gallery_saver_plus:
    :path: ".symlinks/plugins/gallery_saver_plus/ios"
  geolocator_apple:
    :path: ".symlinks/plugins/geolocator_apple/ios"
  google_mlkit_commons:
    :path: ".symlinks/plugins/google_mlkit_commons/ios"
  google_mlkit_image_labeling:
    :path: ".symlinks/plugins/google_mlkit_image_labeling/ios"
  google_mlkit_language_id:
    :path: ".symlinks/plugins/google_mlkit_language_id/ios"
  google_sign_in_ios:
    :path: ".symlinks/plugins/google_sign_in_ios/darwin"
  image_cropper:
    :path: ".symlinks/plugins/image_cropper/ios"
  image_picker_ios:
    :path: ".symlinks/plugins/image_picker_ios/ios"
  light_compressor:
    :path: ".symlinks/plugins/light_compressor/ios"
  maps_launcher:
    :path: ".symlinks/plugins/maps_launcher/ios"
  open_filex:
    :path: ".symlinks/plugins/open_filex/ios"
  package_info_plus:
    :path: ".symlinks/plugins/package_info_plus/ios"
  path_provider_foundation:
    :path: ".symlinks/plugins/path_provider_foundation/darwin"
  permission_handler_apple:
    :path: ".symlinks/plugins/permission_handler_apple/ios"
  receive_sharing_intent:
    :path: ".symlinks/plugins/receive_sharing_intent/ios"
  record_darwin:
    :path: ".symlinks/plugins/record_darwin/ios"
  share_plus:
    :path: ".symlinks/plugins/share_plus/ios"
  shared_preferences_foundation:
    :path: ".symlinks/plugins/shared_preferences_foundation/darwin"
  simple_barcode_scanner:
    :path: ".symlinks/plugins/simple_barcode_scanner/ios"
  sqflite:
    :path: ".symlinks/plugins/sqflite/darwin"
  url_launcher_ios:
    :path: ".symlinks/plugins/url_launcher_ios/ios"
  vibration:
    :path: ".symlinks/plugins/vibration/ios"
  video_player_avfoundation:
    :path: ".symlinks/plugins/video_player_avfoundation/darwin"
  video_thumbnail:
    :path: ".symlinks/plugins/video_thumbnail/ios"
  wakelock_plus:
    :path: ".symlinks/plugins/wakelock_plus/ios"

SPEC CHECKSUMS:
  app_links: e7a6750a915a9e161c58d91bc610e8cd1d4d0ad0
  app_tracking_transparency: 5b1745ef9ade815f7455cb6a0848349589afb7c5
  AppAuth: 501c04eda8a8d11f179dbe8637b7a91bb7e5d2fa
  audioplayers_darwin: 877d9a4d06331c5c374595e46e16453ac7eafa40
  connectivity_plus: 4c41c08fc6d7c91f63bc7aec70ffe3730b04f563
  device_info_plus: 97af1d7e84681a90d0693e63169a5d50e0839a0d
  DKImagePickerController: 946cec48c7873164274ecc4624d19e3da4c1ef3c
  DKPhotoGallery: b3834fecb755ee09a593d7c9e389d8b5d6deed60
  emoji_picker_flutter: fe2e6151c5b548e975d546e6eeb567daf0962a58
  ffmpeg-kit-ios-min: 4e9a088f4ee9629435960b9d68e54848975f1931
  ffmpeg_kit_flutter_min: 5eff47f4965bf9d1150e98961eb6129f5ae3f28c
  file_picker: 09aa5ec1ab24135ccd7a1621c46c84134bfd6655
  Firebase: cf1b19f21410b029b6786a54e9764a0cacad3c99
  firebase_auth: 5defc54c120ef8d00a359ba787f1f3f521db59ce
  firebase_core: f8c5b220a8f9c436fdbd075ae321cef3d96ef181
  firebase_messaging: a7f18d98006bbd8fd0918f4db64b9a70df29aaa8
  FirebaseAppCheckInterop: 1b9643ae2f1ee214488caa2f8e32b7bc2f0f3735
  FirebaseAuth: c359af98bd703cbf4293eec107a40de08ede6ce6
  FirebaseAuthInterop: 9ac948965ac13ec9d8a080f39490ddb2bda30520
  FirebaseCore: e0510f1523bc0eb21653cac00792e1e2bd6f1771
  FirebaseCoreExtension: f1bc67a4702931a7caa097d8e4ac0a1b0d16720e
  FirebaseCoreInternal: 35731192cab10797b88411be84940d2beb33a238
  FirebaseInstallations: 6ef4a1c7eb2a61ee1f74727d7f6ce2e72acf1414
  FirebaseMessaging: f8a160d99c2c2e5babbbcc90c4a3e15db036aee2
  Flutter: e0871f40cf51350855a761d2e70bf5af5b9b5de7
  flutter_contacts: edb1c5ce76aa433e20e6cb14c615f4c0b66e0983
  flutter_image_compress_common: ec1d45c362c9d30a3f6a0426c297f47c52007e3e
  flutter_keyboard_visibility: 0339d06371254c3eb25eeb90ba8d17dca8f9c069
  flutter_local_notifications: 4cde75091f6327eb8517fa068a0a5950212d2086
  flutter_native_splash: edf599c81f74d093a4daf8e17bd7a018854bc778
  gallery_saver_plus: c4b59c605df1049a02d036ef81d82972b6dfd606
  geolocator_apple: 6cbaf322953988e009e5ecb481f07efece75c450
  google_mlkit_commons: 384e4e206e122b6dad430d3158205e0b2fac6789
  google_mlkit_image_labeling: d5b60af262f4920caa9e860c5a1b674c17d2ada4
  google_mlkit_language_id: 52df284ee6ac2eadad3429a036599e9b12e9969c
  google_sign_in_ios: 7c205d44fdc266640375c6ac33d96ba3983dbe02
  GoogleDataTransport: aae35b7ea0c09004c3797d53c8c41f66f219d6a7
  GoogleMLKit: eff9e23ec1d90ea4157a1ee2e32a4f610c5b3318
  GoogleSignIn: b232380cf495a429b8095d3178a8d5855b42e842
  GoogleToolboxForMac: d1a2cbf009c453f4d6ded37c105e2f67a32206d8
  GoogleUtilities: 26a3abef001b6533cf678d3eb38fd3f614b7872d
  GTMAppAuth: 99fb010047ba3973b7026e45393f51f27ab965ae
  GTMSessionFetcher: 5aea5ba6bd522a239e236100971f10cb71b96ab6
  image_cropper: 37d40f62177c101ff4c164906d259ea2c3aa70cf
  image_picker_ios: b545a5f16c0fa88e3ecbbce3ed4de45567a8ec18
  libwebp: 1786c9f4ff8a279e4dac1e8f385004d5fc253009
  light_compressor: 3f6f2c961a84fdf4b46b0c58488985469ee3317c
  Mantle: c5aa8794a29a022dfbbfc9799af95f477a69b62d
  maps_launcher: 2e5b6a2d664ec6c27f82ffa81b74228d770ab203
  MLImage: 0ad1c5f50edd027672d8b26b0fee78a8b4a0fc56
  MLKitCommon: 07c2c33ae5640e5380beaaa6e4b9c249a205542d
  MLKitImageLabeling: 7f052589de9ffde213bc2c26854d212ea4dde17a
  MLKitImageLabelingCommon: 23f0c9037c2c6433784db594bd1bb87173172fe9
  MLKitImageLabelingCustom: 594c49fa1bb809ec05215bb4ac1c15729c7a601a
  MLKitLanguageID: f52e378d875f1a5e67ac0f259ebddaab95faa1c7
  MLKitNaturalLanguage: 1faece38017b0cf8eb49ac69cff10cb419f68c01
  MLKitObjectDetectionCommon: 0198709a728984e3b6fac98a5fa53a8042880336
  MLKitVision: 45e79d68845a2de77e2dd4d7f07947f0ed157b0e
  MLKitVisionKit: 8a7abd5f11aeb1add2942a694c2685eca422a849
  nanopb: fad817b59e0457d11a5dfbde799381cd727c1275
  open_filex: 6e26e659846ec990262224a12ef1c528bb4edbe4
  package_info_plus: c0502532a26c7662a62a356cebe2692ec5fe4ec4
  path_provider_foundation: 3784922295ac71e43754bd15e0653ccfd36a147c
  permission_handler_apple: 9878588469a2b0d0fc1e048d9f43605f92e6cec2
  PromisesObjC: f5707f49cb48b9636751c5b2e7d227e43fba9f47
  RecaptchaInterop: 7d1a4a01a6b2cb1610a47ef3f85f0c411434cb21
  receive_sharing_intent: 6837b01768e567fe8562182397bf43d63d8c6437
  record_darwin: 1f6619f2abac4d1ca91d3eeab038c980d76f1517
  SDWebImage: 73c6079366fea25fa4bb9640d5fb58f0893facd8
  SDWebImageWebPCoder: e38c0a70396191361d60c092933e22c20d5b1380
  share_plus: 8b6f8b3447e494cca5317c8c3073de39b3600d1f
  shared_preferences_foundation: fcdcbc04712aee1108ac7fda236f363274528f78
  simple_barcode_scanner: bb2603ae5228a007bd066e9f955911858ae55755
  sqflite: 673a0e54cc04b7d6dba8d24fb8095b31c3a99eec
  SwiftyGif: 706c60cf65fa2bc5ee0313beece843c8eb8194d4
  TOCropViewController: 80b8985ad794298fb69d3341de183f33d1853654
  url_launcher_ios: 5334b05cef931de560670eeae103fd3e431ac3fe
  vibration: 7d883d141656a1c1a6d8d238616b2042a51a1241
  video_player_avfoundation: 2b4384f3b157206b5e150a0083cdc0c905d260d3
  video_thumbnail: c4e2a3c539e247d4de13cd545344fd2d26ffafd1
  wakelock_plus: 78ec7c5b202cab7761af8e2b2b3d0671be6c4ae1

PODFILE CHECKSUM: 0a5f56871a909cbcf5ee7b67e407f0d5e422e2db

COCOAPODS: 1.16.2

**Comment by SelaseKay** [comment]
Hi @Kora3, thanks for the report. I'm unable to reproduce this issue. Kindly outline clear reproducible steps.

**Comment by imyzherytskyi** [comment]
Update: I've managed to fix problem in my project with next `ios/Podfile` update:
```diff
flutter_additional_ios_build_settings(target)
      target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
-       config.build_settings['OTHER_SWIFT_FLAGS'] = '-no-verify-emitted-module-interface'
      end
```

It seems build was failing because of `-no-verify-emitted-module-interface` flag.

After removing it and updating all Firebase dependencies – I can build iOS app and run on device without any errors.
