### ISSUE TITLE
[core]: <macOS installation> The pod "Firebase/CoreOnly" required by the plugin "firebase_core" requires a higher minimum macOS deployment version than the plugin's reported minimum version.

### ISSUE THREAD

**Issue by zeeolek** [firebase/flutterfire#14505]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Core, Analytics, Crashlytics

### Which platforms are affected?

macOS

### Description

Hi, I have totally fresh project, with first "external dependencies" with firebase crashlytics and analytics and I have problem with build for MacOS while pod install:
> Error: The pod "Firebase/CoreOnly" required by the plugin "firebase_core" requires a higher minimum macOS deployment version than the plugin's reported minimum version.
> To build, remove the plugin "firebase_core", or contact the plugin's developers for assistance.
> Error: Error running pod install
It's for the newest versions:
  firebase_core: ^3.7.0
  firebase_crashlytics: ^4.1.4
With the newest MacOS 15.0.1
 

### Reproducing the issue

Just call pod install for MacOs as target, on just build apk for this platform.

### Firebase Core version

3.7.0

### Flutter Version

3.24.3

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

- _flutterfire_internals 1.3.45 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- collection 1.18.0
- fake_async 1.3.1 [clock collection]
- firebase_core_platform_interface 5.3.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.18.1 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_crashlytics_platform_interface 3.6.45 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- leak_tracker 10.0.5 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.5 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 4.0.0
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- meta 1.15.0
- path 1.9.0
- plugin_platform_interface 2.1.8 [meta]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.7.2 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- vector_math 2.1.4
- vm_service 14.2.5
- web 1.1.0

```

</details>

**Comment by SelaseKay** [comment]
Hi @zeeolek, kindly set your minimum macOS deployment version to 10.15.
