### ISSUE TITLE
🐛 [firebase_remote_config] Provide `onConfigUpdated` Web support

### ISSUE THREAD

**Issue by alestiago** [firebase/flutterfire#15684]
## What feature would you like to see?

Provide Web support for `onConfigUpdated`:

https://github.com/firebase/flutterfire/blob/da597c687e614e95e0096f3c1b2cfa6916f7365b/packages/firebase_remote_config/firebase_remote_config_web/lib/firebase_remote_config_web.dart#L186

**Comment by SelaseKay** [comment]
Hi @alestiago, thanks for raising this concern. Currently, Firebase does not support real-time Remote Config for web, so we’re unable to proceed with this feature at the moment. For more details, you can refer to this [documentation](https://firebase.google.com/docs/remote-config/get-started?platform=flutter#add-real-time-listener).

**Comment by alestiago** [comment]
@SelaseKay I'm aware that Firebase does not support real-time Remote config for web. 

For any future readers that are interested in this feature, go **VOTE** for this feature at: [**Firebase User Voice - Add real time support to the Firebase Javascipt SDK for Remote Config**
](https://firebase.uservoice.com/forums/948424-general/suggestions/46938547-add-real-time-support-to-the-firebase-javascipt-sd)
