### ISSUE TITLE
[storage]: Storage ref with query params causes app crash

### ISSUE THREAD

**Issue by davestimpert** [firebase/flutterfire#15799]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Storage

### Which platforms are affected?

macOS, Web

### Description

I'm trying to get a storage ref from a pre-signed storage URL (where therefore has query params on it for the authentication). If I pass this into FirebaseStorage `refFromUrl` the app hangs and eventually crashes. Confirmed on both web and MacOS. I'm assuming all platforms are affected.

Here's the code where it is happening. The app hangs on the `firstMatch`
```
    // google cloud storage url
  } else {
    RegExp cloudStorageRegExp = RegExp(
      '^https?://$_cloudStorageHost$_optionalPort/$_bucketDomain/$_cloudStoragePath',
      caseSensitive: false,
    );

    RegExpMatch? match = cloudStorageRegExp.firstMatch(decodedUrl);
```

I tested the regex used in regex101

`^https?:\/\/(?:storage.googleapis.com|storage.cloud.google.com)(?::\d+)?\/([A-Za-z0-9.\-_]+)\/([^?#]*)*$`

And confirmed that if I put querystring params on the url, e.g. 
`https://storage.googleapis.com/myapp.appspot.com/users/john/chat/image.jpg?foo=bar`
Then there's an error:
Catastrophic backtracking has been detected and the execution of your expression has been halted. To find out more and what this is, please read the following article: [Runaway Regular Expressions](http://www.regular-expressions.info/catastrophic.html)

### Reproducing the issue

Call FirebaseStorage.instance.refFromUrl('https://storage.googleapis.com/myapp.appspot.com/users/john/chat/image.jpg?foo=bar')

### Firebase Core version

3.3.0

### Flutter Version

3.24.4

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by davestimpert** [comment]
@paulb777 is this fixed and just not released yet? Not sure why it was closed.

**Comment by paulb777** [comment]
Sorry, my mistake. It looks like this issue was in the middle of several spam issues that I bulk closed.

**Comment by SelaseKay** [comment]
Hi @davestimpert , thanks for the report. I'm able to reproduce this issue. 

## Reproducible Steps
<details>
<summary>Reproducible code</summary>

```dart
  UploadTask uploadString() {
    const String putStringText =
        'This upload has been generated using the putString method! Check the metadata too!';
   FirebaseStorage.instance.refFromURL('https://storage.cloud.google.com/test-lab-n0yzpjc8fd2wa-ymsv2wu157its/2024-10-31_11-30-37.513184_MMGp/matrix_0/Nexus6P-26-en-portrait-shard_0-rerun_1/test_cases/0000_logcat?foo=bar');


    // Create a Reference to the file
    Reference ref = FirebaseStorage.instance
        .ref()
        .child('flutter-tests')
        .child('/put-string-example.txt');

    // Start upload of putString
    return ref.putString(
      putStringText,
      metadata: SettableMetadata(
        contentLanguage: 'en',
        customMetadata: <String, String>{'example': 'putString'},
      ),
    );
  }
```
</details>

1. Run the `firebase_storage` example app with the updated `uploadString` function above. 
2. Observe that the app freezes.
