### ISSUE TITLE
🐛 [firebase_auth] Use readable date format for email sign-in

### ISSUE THREAD

**Issue by cs-marcoblagoiev** [firebase/flutterfire#16073]
## Use readable date format for email sign-in

According to 
https://firebase.google.com/docs/auth/web/email-link-auth#default-email
and 
https://github.com/firebase/firebase-js-sdk/issues/2574
The email sign in template contains a timestamp in the email title and body, so email are not collapsed into a sigle thread.

I believe the current date time format, such as `2024 November 11 13:33 UTC` is not user friendly, and should be replaced with a more readable format, such as `Nov. 11, 2024, 11:33`.

The mail language is already based on the language set in the Firebase Authentication -> Template language section, so the formatting can be done based on the same setting, or a new option can be added in the Firebase Console to select a format.

**Comment by cs-marcoblagoiev** [comment]
@SelaseKay can you let me know why this was closed and flagged as invalid?

**Comment by SelaseKay** [comment]
Sorry about that. Was closing out spam issues and this got caught into it.

**Comment by SelaseKay** [comment]
Hi @cs-marcoblagoiev, thank you for raising this concern. However, the date formatting in email sign-in templates falls outside the scope of FlutterFire, as it is managed directly by Firebase. Therefore, adjustments to the date format would need to be made on Firebase's end.

I recommend sharing your feedback on this matter through Firebase's official feedback channel, which you can access [here](https://firebase.uservoice.com/forums/948424-general).

**Comment by cs-marcoblagoiev** [comment]
Thanks @SelaseKay , I will create a suggestion on the uservoice link
