### ISSUE TITLE
Cloud_Firestore cocoapods install error

### ISSUE THREAD

**Issue by MRtootisabz** [firebase/flutterfire#16686]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Database

### Which platforms are affected?

iOS

### Description

I update cloud firestore version in my flutter project and  cocoa pods in my system. then i got this error when call pod install.

JSON::ParserError - Failed to parse JSON at file: '/Users/macbookair/.cocoapods/repos/trunk/Specs/9/1/0/gRPC-Core/1.68.0/gRPC-Core.podspec.json'.  

### Reproducing the issue

cloud_firestore 5.5.0
cocoapods version : 1.16.2
flutter version : 3.24.5

### Firebase Core version

3.8.0

### Flutter Version

3.24.5

### Relevant Log Output

```shell
cloud_firestore: Using Firebase SDK version '11.4.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '11.4.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '11.4.0' defined in 'firebase_core'

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command


/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.16.2
        Ruby : ruby 3.3.6 (2024-11-05 revision 75015d4c1f) [arm64-darwin23]
    RubyGems : 3.5.23
        Host : macOS 14.6.1 (23G93)
       Xcode : 15.3 (15E204a)
         Git : git version 2.47.0
Ruby lib dir : /opt/homebrew/Cellar/ruby/3.3.6/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

# Uncomment this line to define a global platform for your project
platform :ios, '14.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```

### Error

```
JSON::ParserError - Failed to parse JSON at file: '/Users/macbookair/.cocoapods/repos/trunk/Specs/9/1/0/gRPC-Core/1.68.0/gRPC-Core.podspec.json'.

unexpected token at '"src/core/lib/iomgr/call_combiner.'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-core-1.16.2/lib/cocoapods-core/specification/json.rb:66:in `rescue in from_json'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-core-1.16.2/lib/cocoapods-core/specification/json.rb:61:in `from_json'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-core-1.16.2/lib/cocoapods-core/specification.rb:759:in `from_string'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-core-1.16.2/lib/cocoapods-core/specification.rb:733:in `from_file'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-core-1.16.2/lib/cocoapods-core/source.rb:188:in `specification'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-core-1.16.2/lib/cocoapods-core/specification/set.rb:58:in `block in specification_name'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-core-1.16.2/lib/cocoapods-core/specification/set.rb:56:in `each'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-core-1.16.2/lib/cocoapods-core/specification/set.rb:56:in `specification_name'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-core-1.16.2/lib/cocoapods-core/cdn_source.rb:217:in `search'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-core-1.16.2/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-core-1.16.2/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-core-1.16.2/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/resolver.rb:385:in `find_cached_set'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/resolver.rb:165:in `search_for'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/resolver.rb:267:in `each'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/resolver.rb:267:in `sort_by'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/resolver.rb:267:in `sort_by!'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:60:in `block in sort_dependencies'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:77:in `with_no_such_dependency_error_handling'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:59:in `sort_dependencies'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:744:in `require_nested_dependencies_for'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:727:in `activate_new_spec'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/resolver.rb:94:in `resolve'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer/analyzer.rb:1082:in `block in resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer/analyzer.rb:1080:in `resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer/analyzer.rb:125:in `analyze'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:422:in `analyze'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:162:in `install!'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/command/install.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/bin/pod:55:in `<top (required)>'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/bin/pod:25:in `load'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/bin/pod:25:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Failed+to+parse+JSON+at+file%3A+%27%2FUsers%2Fmacbookair%2F.cocoapods%2Frepos%2Ftrunk%2FSpecs%2F9%2F1%2F0%2FgRPC-Core%2F1.68.0%2FgRPC-Core.podspec.json%27.%0A%0Aunexpected+token+at+%27%22src%2Fcore%2Flib%2Fiomgr%2Fcall_combiner.%27&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md
```

### Flutter dependencies

  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5

  cloud_firestore: ^5.5.0
![Screenshot 2024-11-17 at 2 41 19 PM](https://github.com/user-attachments/assets/6c9b6394-6f39-4556-aaba-aa2b14f05066)

### Additional context and comments

I have reported to cocoapods github page also

**Comment by SelaseKay** [comment]
Hi @MRtootisabz, I'm unable to reproduce this issue. Could you share a complete minimal repo reproducing this issue?

**Comment by MRtootisabz** [comment]
@SelaseKay  Just create  a flutter empty project and add cloud_firestore.

**Comment by SelaseKay** [comment]
Hi @MRtootisabz, I'm still unable to reproduce this issue with an new Flutter Project. Kindly upgrade your Xcode and try again.

**Comment by JherysVargas** [comment]
I had the same error and I solved it by changing the following value in the Podfile `platform: ios, '13.0'`

**Comment by leipenggit** [comment]
pod install
Analyzing dependencies
cloud_firestore: Using Firebase SDK version '11.4.0' defined in 'firebase_core'
firebase_analytics: Using Firebase SDK version '11.4.0' defined in 'firebase_core'
firebase_auth: Using Firebase SDK version '11.4.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '11.4.0' defined in 'firebase_core'
Project at /Users/shanshan/Desktop/项目New/Runner.xcodeproj does not exist. Please check paths or incorporate Crashlytics upload symbols manually.
firebase_crashlytics: Using Firebase SDK version '11.4.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '11.4.0' defined in 'firebase_core'
firebase_storage: Using Firebase SDK version '11.4.0' defined in 'firebase_core'

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/shanshan/.rvm/rubies/ruby-3.0.0/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.16.2
        Ruby : ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [arm64-darwin22]
    RubyGems : 3.2.3
        Host : macOS 15.0.1 (24A348)
       Xcode : 16.0 (16A242d)
         Git : git version 2.39.5 (Apple Git-154)
Ruby lib dir : /Users/shanshan/.rvm/rubies/ruby-3.0.0/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ f752aeaa9a4ec028480cb0342f5f3a7dc1646ab1

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Pods for Runner
  #pod 'AmazonChimeSDK-Bitcode', '~> 0.22.7'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

 post_install do |installer|


  installer.aggregate_targets.each do |target|

    target.xcconfigs.each do |variant, xcconfig|

      xcconfig_path = target.client_root + target.xcconfig_relative_path(variant)

      IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))

    end

  end


  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      if config.name == 'Dev'
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
        break
      end
      
      if config.base_configuration_reference.is_a? Xcodeproj::Project::Object::PBXFileReference

        xcconfig_path = config.base_configuration_reference.real_path

        IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))

      end

    #from permission_handler config
    # target.build_configurations.each do |config|
      # You can remove unused permissions here
      # for more information: https://github.com/BaseflowIT/flutter-permission-handler/blob/master/permission_handler/ios/Classes/PermissionHandlerEnums.h
      # e.g. when you don't need camera permission, just add 'PERMISSION_CAMERA=0'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        ## dart: PermissionGroup.camera
        'PERMISSION_CAMERA=1',
        ## dart: PermissionGroup.photos
        'PERMISSION_PHOTOS=1',
        ## The 'PERMISSION_LOCATION' macro enables the `locationWhenInUse` and `locationAlways` permission. If
        ## the application only requires `locationWhenInUse`, only specify the `PERMISSION_LOCATION_WHENINUSE`
        ## macro.
        ##
        ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
        'PERMISSION_LOCATION=1',
        'PERMISSION_LOCATION_WHENINUSE=0',
      ]
    end
  end
 end

#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    flutter_additional_ios_build_settings(target)
#    if target.name == 'AmazonChimeSDK-Bitcode' # 替换为你想要修改的 Pod 名称
#      target.build_configurations.each do |config|
#        config.build_settings['ENABLE_BITCODE'] = 'NO'
#      end
#    end
#    if target.name == 'AmazonChimeSDKMedia-Bitcode' # 替换为你想要修改的 Pod 名称
#      target.build_configurations.each do |config|
#        config.build_settings['ENABLE_BITCODE'] = 'NO'
#      end
#    end
#  end
#end

# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     # # 设置 Bitcode 为 NO
#     # if target.name == 'AmazonChimeSDK-Bitcode'
#     #   target.build_configurations.each do |config|
#     #     config.build_settings['ENABLE_BITCODE'] = 'NO'
#     #   end
#     # end
    
#     # if target.name == 'AmazonChimeSDKMedia-Bitcode' # 替换为你想要修改的 Pod 名称
#     #   target.build_configurations.each do |config|
#     #     config.build_settings['ENABLE_BITCODE'] = 'NO'
#     #   end
#     # end

#     # target.build_configurations.each do |config|
#     #   config.build_settings['ENABLE_BITCODE'] = 'NO'
#     # end
    
#     # 如果需要，可以在这里调用 flutter_additional_ios_build_settings
#     # 但通常情况下，不需要这样做
#     flutter_additional_ios_build_settings(target)
#   end
# end





# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     target.build_configurations.each do |config|
#       config.build_settings['ENABLE_BITCODE'] = 'NO'
#     end
#   end

#   # 如果需要，可以在这里调用 flutter_additional_ios_build_settings
#   # 但通常情况下，不需要这样做
#   installer.pods_project.targets.each do |target|
#     flutter_additional_ios_build_settings(target)
#   end
# end
```

### Error

```
JSON::ParserError - Failed to parse JSON at file: '/Users/shanshan/.cocoapods/repos/trunk/Specs/9/1/0/gRPC-Core/1.65.5/gRPC-Core.podspec.json'.

439: unexpected token at '"src/core/ext/transport/chttp2/transport/frame_s'
/Users/shanshan/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.16.2/lib/cocoapods-core/specification/json.rb:66:in `rescue in from_json'
/Users/shanshan/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.16.2/lib/cocoapods-core/specification/json.rb:61:in `from_json'
/Users/shanshan/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.16.2/lib/cocoapods-core/specification.rb:759:in `from_string'
/Users/shanshan/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.16.2/lib/cocoapods-core/specification.rb:733:in `from_file'
/Users/shanshan/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.16.2/lib/cocoapods-core/source.rb:188:in `specification'
/Users/shanshan/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.16.2/lib/cocoapods/resolver/lazy_specification.rb:37:in `specification'
/Users/shanshan/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/delegate.rb:348:in `block in delegating_block'
/Users/shanshan/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/delegate.rb:349:in `block in delegating_block'
/Users/shanshan/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.16.2/lib/cocoapods/resolver.rb:178:in `dependencies_for'
/Users/shanshan/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:18:in `block in dependencies_for'
/Users/shanshan/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:77:in `with_no_such_dependency_error_handling'
/Users/shanshan/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:17:in `dependencies_for'
/Users/shanshan/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:809:in `block in group_possibilities'
/Users/shanshan/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:808:in `reverse_each'
/Users/shanshan/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:808:in `group_possibilities'
/Users/shanshan/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:779:in `possibilities_for_requirement'
/Users/shanshan/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:761:in `push_state_for_requirements'
/Users/shanshan/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:744:in `require_nested_dependencies_for'
/Users/shanshan/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:727:in `activate_new_spec'
/Users/shanshan/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
/Users/shanshan/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/Users/shanshan/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
/Users/shanshan/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
/Users/shanshan/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.16.2/lib/cocoapods/resolver.rb:94:in `resolve'
/Users/shanshan/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.16.2/lib/cocoapods/installer/analyzer.rb:1082:in `block in resolve_dependencies'
/Users/shanshan/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.16.2/lib/cocoapods/user_interface.rb:64:in `section'
/Users/shanshan/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.16.2/lib/cocoapods/installer/analyzer.rb:1080:in `resolve_dependencies'
/Users/shanshan/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.16.2/lib/cocoapods/installer/analyzer.rb:125:in `analyze'
/Users/shanshan/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:422:in `analyze'
/Users/shanshan/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
/Users/shanshan/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.16.2/lib/cocoapods/user_interface.rb:64:in `section'
/Users/shanshan/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
/Users/shanshan/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:162:in `install!'
/Users/shanshan/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.16.2/lib/cocoapods/command/install.rb:52:in `run'
/Users/shanshan/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/shanshan/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.16.2/lib/cocoapods/command.rb:52:in `run'
/Users/shanshan/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.16.2/bin/pod:55:in `<top (required)>'
/Users/shanshan/.rvm/rubies/ruby-3.0.0/bin/pod:23:in `load'
/Users/shanshan/.rvm/rubies/ruby-3.0.0/bin/pod:23:in `<main>'
/Users/shanshan/.rvm/rubies/ruby-3.0.0/bin/ruby_executable_hooks:22:in `eval'
/Users/shanshan/.rvm/rubies/ruby-3.0.0/bin/ruby_executable_hooks:22:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Failed+to+parse+JSON+at+file%3A+%27%2FUsers%2Fshanshan%2F.cocoapods%2Frepos%2Ftrunk%2FSpecs%2F9%2F1%2F0%2FgRPC-Core%2F1.65.5%2FgRPC-Core.podspec.json%27.%0A%0A439%3A+unexpected+token+at+%27%22src%2Fcore%2Fext%2Ftransport%2Fchttp2%2Ftransport%2Fframe_s%27&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Found no similar issues. To create a new issue, please visit:
https://github.com/cocoapods/cocoapods/issues/new
