### ISSUE TITLE
[📚][firebase_analytics_web]: Firebase Analytics for Flutter Web not working if Google Tag is not included in index.html

### ISSUE THREAD

**Issue by pcba-dev** [firebase/flutterfire#16746]
It appears that Firebase Analytics for Flutter Web requires the Google Tag script to be manually included in the index.html file for proper functionality. Without this, the Google Analytics panel reports that "Data collection isn’t active for your website," even after correctly initialising Firebase Analytics as per the Firebase Analytics documentation.

If it is actually required, the documentation should explicitly instruct developers to include the tag.

**Comment by SelaseKay** [comment]
Hi @pcba-dev, thanks for raising this. However, I don't think you have to manually add Google Tag script to get analytics working. I just tested with the current `firebase_analytics` example app and it works fine without the script. Which `firebase_analytics` version are you using?

**Comment by pcba-dev** [comment]
We are using firebase_analytics v11.3.5. We have removed the Google Tag script and are waiting in case it takes 48h as it indicates the Analytics pannel.
