### ISSUE TITLE
[firebase_auth]: Anonymous sign-in failure on deployed web app

### ISSUE THREAD

**Issue by lore-co** [firebase/flutterfire#16788]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Auth

### Which platforms are affected?

Web

### Description

Firebase auth version: 5.3.1

As the title suggests, while calling the FirebaseAuth.instance.signInAnonymously method, the deployed web app (it is currently deployed with Firebase Hosting) throws a 

> Uncaught Error: PlatformException(channel-error, Unable to establish connection on channel: "dev.flutter.pigeon.firebase_auth_platform_interface.FirebaseAuthHostApi.registerIdTokenListener"., null, null)

The error does not shows up while running the app from IDE, working correctly and letting me fetch my firestore collection.

### Reproducing the issue

Create a simple flutter project with flutter_auth in the pubspec.yaml and the corresponding firebase project, using the CLI to setup everything.

in your main add 

`void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  await FirebaseAuth.instance.signInAnonymously();

  runApp(const MyApp());
}`

### Firebase Core version

3.6.0

### Flutter Version

3.24.4

### Relevant Log Output

```shell
Uncaught Error: PlatformException(channel-error, Unable to establish connection on channel: "dev.flutter.pigeon.firebase_auth_platform_interface.FirebaseAuthHostApi.registerIdTokenListener"., null, null)
    at Object.c (main.dart.js:3503:19)
    at main.dart.js:50747:20
    at aN4.a (main.dart.js:4865:63)
    at aN4.$2 (main.dart.js:41135:14)
    at aLP.$1 (main.dart.js:41129:21)
    at a8d.Mp (main.dart.js:42139:33)
    at aFf.$0 (main.dart.js:41560:11)
    at Object.z_ (main.dart.js:5023:40)
    at ae.ot (main.dart.js:41494:3)
    at IV.dY (main.dart.js:41121:8)
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.4

```

</details>

**Comment by SelaseKay** [comment]
Hi @lore-co, thanks for the report. I'm unable to reproduce this issue. Could you provide a complete minimal code reproducing this issue?

**Comment by petersephrin** [comment]
Getting the same issue after deploying. Running in dev on localhost it works without errors but on deployment the issue pops up

**Comment by SelaseKay** [comment]
Hi @petersephrin, what version of `firebase_auth` do you experience this on?

**Comment by petersephrin** [comment]
Firebase version 13.28.0 
But the error was on my part. I was not waiting for firebase to initialize.

**Comment by lore-co** [comment]
> Hi @lore-co, thanks for the report. I'm unable to reproduce this issue. Could you provide a complete minimal code reproducing this issue?

Hello, it seems like Flutter Web sometime will inexplicably cache builds and not upload correct configuration files/libs versions. As such, deleting my local project and redownloading it from the remote repo worked and I resolved the issue!
