### ISSUE TITLE
[FIREBASE ANALYTICS]: FAILING TO LAUNCH ON IOS

### ISSUE THREAD

**Issue by SenadBajram** [firebase/flutterfire#16794]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Analytics

### Which platforms are affected?

iOS

### Description

Adding firebase_analytics: ^11.3.5 and just launching on iOS will produce this:

Failed to build iOS app
Error (Xcode): Error: Couldn't resolve the package 'google_mobile_ads' in 'package:google_mobile_ads/google_mobile_ads.dart'.

Encountered error while building for device.

### Reproducing the issue

Adding firebase_analytics: ^11.3.5 and just launching on iOS 

### Firebase Core version

3.8.0

### Flutter Version

3.24.5 

### Relevant Log Output

```shell
Running pod install...                                              3.1s
Running Xcode build...                                                  
 └─Compiling, linking and signing...                      2,971ms
Xcode build done.                                           93.3s
Failed to build iOS app
Error (Xcode): Undefined symbols:


Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)


Encountered error while building for device.
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by SelaseKay** [comment]
Hi @SenadBajram, based on the error logs, this issue appears to be related to the `google_mobile_ads` package rather than the FlutterFire plugins.

**Comment by Muhammad-Ullah** [comment]
Issue is not related to google_mobile_ads packages. I am getting the same error even though I am not using google_mobile_ads package.

**Error**:
Running pod install...                                              3.1s
Running Xcode build...                                                  
 └─Compiling, linking and signing...                      2,971ms
Xcode build done.                                           93.3s
Failed to build iOS app
Error (Xcode): Undefined symbols:


Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)


Encountered error while building for device.

Any permanent solution for this?

**Comment by SelaseKay** [comment]
@Muhammad-Ullah, can you share a list of the dependencies in your `pubspec.yaml`?

**Comment by Muhammad-Ullah** [comment]
This is my pubspec.yaml file,
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  get_it: ^7.6.7
  intl: ^0.19.0
  shimmer: ^3.0.0
  sqflite: ^2.3.3+1
  geolocator: ^12.0.0
  image_picker: ^1.1.2
  geocoding: ^3.0.0
  flutter_bloc: ^8.1.5
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  flutter_slidable: ^3.1.1
  path_provider: ^2.1.3
  google_sign_in: ^6.2.1
  connectivity_plus: ^6.0.3
  cloud_firestore: ^5.1.0
  device_info_plus: ^10.1.0
  firebase_storage: ^12.1.0
  country_code_picker: ^3.0.0
  firebase_messaging: ^15.0.1
  shared_preferences: ^2.2.3
  pinput: ^5.0.0
  sign_in_with_apple: ^6.1.1
  permission_handler: ^11.3.1
  cached_network_image: ^3.3.1
  flutter_card_swiper: ^7.0.1
  flutter_svg: ^2.0.10+1
  firebase_crashlytics: ^4.0.2
  firebase_analytics: ^11.0.0
  rive: ^0.13.9
  screenshot: ^3.0.0
  url_launcher: ^6.3.0
  flutter_colorpicker: ^1.1.0
  package_info_plus: ^8.0.2
  matrix_gesture_detector:
    git:
      url: https://github.com/besttechguru/matrix_gesture_detector.git
  hexcolor: ^3.0.1
  flutter_image_compress: ^2.3.0
  # Helpers
  freezed: ^2.5.7
  build_runner: ^2.4.12
  # Generators
  json_serializable: ^6.8.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  
  
  PS:
  I also tried with updated version of firebase_analytics: 11.3.6
