### ISSUE TITLE
[firebase_analytics]: FirebaseAnalytics.instance.logPurchase

### ISSUE THREAD

**Issue by JonBenson** [firebase/flutterfire#16793]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Analytics

### Which platforms are affected?

Android, iOS

### Description

I don't know if anybody else is experiencing this issue but Im trying to use `FirebaseAnalytics.instance.logPurchase` to log a purchase with items. 

```
FirebaseAnalytics.instance.logPurchase(
      transactionId: 'order ID',
      value: 9.99,
      shipping: 0.00,
      currency: 'GBP',
      items: order.products
          .map(
            (item) => AnalyticsEventItem(
              itemId: item.someID,
              itemBrand: item.brand,
              currency: item.currency,
              itemListName: item.name,
              price: item.price,
            ),
          )
          .toList(),
    );
```

All seems fine app side, I don't get any errors however in the Firebase Console Debug view the event comes through like this.
<img width="780" alt="Screenshot 2024-11-29 at 15 06 03" src="https://github.com/user-attachments/assets/a62c1de9-0e52-4fe1-9e1b-85ce2bc18a6a">

The error code 21 seems to relate to it not accepting an array and if I remove the array of items from the call it works fine. 

### Reproducing the issue

Attempt to call the function to log a purchase with items.

FirebaseAnalytics.instance.logPurchase(
      transactionId: 'order ID',
      value: 9.99,
      shipping: 0.00,
      currency: 'GBP',
      items: order.products
          .map(
            (item) => AnalyticsEventItem(
              itemId: item.someID,
              itemBrand: item.brand,
              currency: item.currency,
              itemListName: item.name,
              price: item.price,
            ),
          )
          .toList(),
    );

### Firebase Core version

2.12.0

### Flutter Version

3.22.1

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by SelaseKay** [comment]
Hi @JonBenson, I'm unable to reproduce this issue. Could you try upgrading `firebase_analytics` to see if it resolves your issue? Seems to work fine on the latest version.

**Comment by JonBenson** [comment]
The SDK update did the trick thanks SelaseKay
