### ISSUE TITLE
Firebase Core: Include of non-modular header inside framework module 'FirebaseCoreExtension.FIRAppInternal'

### ISSUE THREAD

**Issue by habyaad** [firebase/flutterfire#16796]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Core

### Which platforms are affected?

iOS

### Description

This is my result from codemagic, i get the same when I try to run in xcode too
I have:
set CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES to YES;

My packages versions:
  firebase_analytics: ^11.3.5
  firebase_crashlytics: ^4.1.5
  firebase_messaging: ^15.1.5
  firebase_core: ^3.8.0

### Reproducing the issue

Use the latest version of these packages
firebase_analytics: ^11.3.5
  firebase_crashlytics: ^4.1.5
  firebase_messaging: ^15.1.5
  firebase_core: ^3.8.0
  
  and try to run ios build using a CI/CD pipeline like codemagic

### Firebase Core version

3.8.0

### Flutter Version

3.24

### Relevant Log Output

```shell
Archiving <com.projectname>
Updating project for Xcode compatibility.
Upgrading project.pbxproj
Upgrading Runner.xcscheme
Automatically signing iOS for device deployment using specified development team in Xcode project: U6Y38UNLA6
Running pod install...                                           2,051ms
Running Xcode build...                                          
Xcode archive done.                                         37.4s
Failed to build iOS app
Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'FirebaseCoreExtension.FIRAppInternal': '/Users/builder/clone/ios/Pods/Headers/Public/FirebaseCore/FIRApp.h'
/Users/builder/clone/ios/Pods/FirebaseCoreExtension/FirebaseCore/Extension/FIRAppInternal.h:16:8

Encountered error while archiving for device.


Build failed :|
Step 9 script `Flutter build ipa` exited with status code 1
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

  firebase_analytics: ^11.3.5
  firebase_crashlytics: ^4.1.5
  firebase_messaging: ^15.1.5
  firebase_core: ^3.8.0
```

</details>

**Comment by SelaseKay** [comment]
Hi @habyaad, what version of Xcode are you using in CI?

**Comment by habyaad** [comment]
> Hi @habyaad, what version of Xcode are you using in CI and locally?

I am using 16.0 on CI and 16.1 locally
