### ISSUE TITLE
[firebase-messaging ] [web] - getToken() prompts notification permission in web

### ISSUE THREAD

**Issue by bf-vs** [firebase/flutterfire#16817]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

In-App Messaging

### Which platforms are affected?

Web

### Description

The current behavior of `getToken()` on web prompts the user with a permission dialog if notification permissions have not already been granted.

In comparison, the behavior on mobile platforms is already ideal, as `getToken()` operates silently regardless of the user's notification permission status. It returns null if the permission is not given.

### Reproducing the issue

- On a web app, ensure that notification permissions are not granted.
- Call `getToken()`.
- Observe that a permission dialog appears.

### Firebase Core version

3.8.0

### Flutter Version

3.24.5

**Comment by SelaseKay** [comment]
Hi @bf-vs, thanks for the report. However, I'm not entirely sure about your concern. Could you please clarify what you believe the expected behavior should be on the web?
