### ISSUE TITLE
🐛 [firebase_crashlytics] add Windows support

### ISSUE THREAD

**Issue by allessandrojs** [firebase/flutterfire#16825]
🐛 [firebase_crashlytics] add Windows support

**Comment by SelaseKay** [comment]
Hi @allessandrojs, `firebase_crashlytics` is not currently supported on the Windows platform, as noted in the [Firebase documentation](https://firebase.google.com/docs/flutter/setup?platform=ios#available-plugins). If you'd like to share your feedback or request support, you can do so on the [Firebase UserVoice forum](https://firebase.uservoice.com/forums/948424-general).
