### ISSUE TITLE
firebase_message: default_notification_color can not override  in AndroidManifest.xml

### ISSUE THREAD

**Issue by hsc42lol** [firebase/flutterfire#16855]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

firebase_message

### Which platforms are affected?

android

### Description

lutter firebase messaging, set the default_notification_color in AndroidManifest.xml but didn't work,
it show transparent, 
the device is honor android 14, 
the default_notification_color work on pixel and samsung but honor, 
O-(///￣皿￣)☞ ─═≡☆゜★█▇▆▅▄▃▂＿

### Firebase Core version

2.32.0

### Flutter Version

3.24.1

**Comment by russellwheatley** [comment]
Hi @hsc42lol - this is device specific, as you mentioned, it works on Pixel and Samsung. It's not something we can fix on FlutterFire I'm afraid. The only advice I can think of is to update the android OS, maybe it has been fixed upstream.
