### ISSUE TITLE
firebase_analytics: firebase_core

### ISSUE THREAD

**Issue by helloalbin** [firebase/flutterfire#16873]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Core, Analytics

### Which platforms are affected?

Android, iOS

### Description

After upgrading to latest flutter version 3.27.0 build is giving an error " Unable to find a specification for `firebase_core` depended upon by `firebase_analytics`"

### Reproducing the issue

Upgrade to latest version of flutter 3.27.0. List of plugins

  firebase_core : ^3.8.1
  firebase_analytics : ^11.3.6
  cloud_firestore : ^5.5.1
  firebase_messaging : ^15.1.6
  firebase_crashlytics : ^4.2.0
  firebase_in_app_messaging : ^0.8.0+11
  #firebase_remote_config: ^3.0.9
  firebase_performance : ^0.10.0+11

### Firebase Core version

3.8.1

### Flutter Version

3.27.0

### Relevant Log Output

```shell
firebase_crashlytics: Using Firebase SDK version '11.4.0' defined in 'firebase_core'
firebase_in_app_messaging: Using Firebase SDK version '11.4.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '11.4.0' defined in 'firebase_core'
firebase_performance: Using Firebase SDK version '11.4.0' defined in 'firebase_core'
[!] Unable to find a specification for `firebase_core` depended upon by `firebase_analytics`
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by thni-monta** [comment]
@helloalbin I'm experiencing the same. What was your solution?

If I downgrade to firebase_core 3.4.1 the error disappears, so guess it has something to do with this change in 3.5.0 if running Flutter 3.27.:

FEAT(core): support for using SPM (Swift Package Manager) ([#12786](https://github.com/firebase/flutterfire/issues/12786)). ([4e28103f](https://github.com/firebase/flutterfire/commit/4e28103fafd84c6613df647e7f0dbb6a068ca8ea))

My teammates don't experience the error (yet at least), so it could be a local setting somehow, but I feel like I've tried everything with no luck

**Comment by helloalbin** [comment]
I closed the ticket because a similar issue already reported https://github.com/firebase/flutterfire/issues/16670 . I couldn't find any solution other than downgrading to a lower version.
