### ISSUE TITLE
[firebase_messaging]: Delay In messages and duplicate

### ISSUE THREAD

**Issue by muhammedelsepa3y** [firebase/flutterfire#16881]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Messaging

### Which platforms are affected?

iOS

### Description

When sending notifications via FCM, it takes more than 3 seconds to reach the target, and sometimes notifications are duplicated. How can I prevent notifications from being automatically displayed by Firebase Messaging and reduce the delay?

### Reproducing the issue

when sending notification via iOS

### Firebase Core version

3.8.1

### Flutter Version

3.24.5

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by SelaseKay** [comment]
Hi @muhammedelsepa3y, the delivery time for notifications is managed by Firebase and can depend on various factors outside our control. For further assistance with notification delays, we recommend reaching out directly to [Firebase Support](https://firebase.google.com/support).
