### ISSUE TITLE
🐛 [Firebase] Improve iOS build error

### ISSUE THREAD

**Issue by JCKodel** [firebase/flutterfire#16889]
## What feature would you like to see?

Every time I update Flutter, I usually delete all the package cache (`dart pub cache clean`). This deletes the `flutterfire_cli`. When building the iOS app on VSCode, the error message is pretty unhelpful. The only helpful information is given by XCode when it fails the build and you click on the build logs (then you realize that the upload-crashlytics_symbols step failed because `flutterfire` is not available).

Suggestion:

Change the script to add a `dart pub global activate flutterfire_cli` on `shellScript` below:

```
8B3DA8A8A3A6FFF9F96462E2 /* FlutterFire: "flutterfire upload-crashlytics-symbols" */ = {
  isa = PBXShellScriptBuildPhase;
  buildActionMask = 2147483647;
  files = (
  );
  inputFileListPaths = (
  );
  inputPaths = (
  );
  name = "FlutterFire: \"flutterfire upload-crashlytics-symbols\"";
  outputFileListPaths = (
  );
  outputPaths = (
  );
  runOnlyForDeploymentPostprocessing = 0;
  shellPath = /bin/sh;
  shellScript = "\n#!/bin/bash\ndart pub global activate flutterfire_cli\nPATH=${PATH}:$FLUTTER_ROOT/bin:$HOME/.pub-cache/bin\nflutterfire upload-crashlytics-symbols --upload-symbols-script-path=$PODS_ROOT/FirebaseCrashlytics/upload-symbols --platform=ios --apple-project-path=${SRCROOT} --env-platform-name=${PLATFORM_NAME} --env-configuration=${CONFIGURATION} --env-project-dir=${PROJECT_DIR} --env-built-products-dir=${BUILT_PRODUCTS_DIR} --env-dwarf-dsym-folder-path=${DWARF_DSYM_FOLDER_PATH} --env-dwarf-dsym-file-name=${DWARF_DSYM_FILE_NAME} --env-infoplist-path=${INFOPLIST_PATH} --default-config=default\n";
};
```

If possible, make checks if firebase is authenticated as well (and, somehow, make those mistakes clearer when we issue an `flutter build`).

Also, this script is not compatible with CI/CD, since firebase will not be authenticated in, let's say, XCode Cloud. Maybe add a environment variable or something that ignores this script, so we can build in a cloud environment without having to delete this script?

**Comment by russellwheatley** [comment]
Hi @JCKodel - There is a separate repository for flutterfire CLI, please open this issue there: https://github.com/invertase/flutterfire_cli
