### ISSUE TITLE
[flutterfire]: PathNotFoundException: Cannot open file 'android/build.gradle' when running flutterfire configure

### ISSUE THREAD

**Issue by bennajah** [firebase/flutterfire#16886]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Other

### Which platforms are affected?

Android, iOS, macOS, Web, Windows

### Description

When running the flutterfire configure command to set up Firebase for a Flutter project, the process fails with a PathNotFoundException error. The error indicates that the build.gradle file in the [android] directory cannot be found. This issue occurs even though the Firebase configuration for Android, iOS, macOS, web, and Windows platforms is successfully registered.

### Reproducing the issue

flutter create example
cd example
dart pub global activate flutterfire_cli
flutterfire configure --project=example-1b63e
![Screenshot 2024-12-17 000125](https://github.com/user-attachments/assets/1d533c45-0378-4b2c-9874-4d458753e428)

### Firebase Core version

3.8.1

### Flutter Version

3.27.0

### Relevant Log Output

```shell
PS D:\Projects\untitled> flutterfire configure --project=example-1b63e
i Found 4 Firebase projects. Selecting project example-1b63e.
✔ Which platforms should your configuration support (use arrow keys & space to select)? · android, ios, macos, web, windows
✔ Which Android application id (or package name) do you want to use for this configuration, e.g. 'com.example.app'? · com.example.untitled
i Firebase android app com.example.untitled registered.                                                                                                                                        
i Firebase ios app com.example.untitled registered.
i Firebase macos app com.example.untitled registered.
i Firebase web app untitled (web) registered.
i Firebase windows app untitled (windows) registered.
PathNotFoundException: Cannot open file, path = 'D:\Projects\untitled\android\build.gradle' (OS Error: The system cannot find the file specified.
, errno = 2)
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by SelaseKay** [comment]
Hi @bennajahk, thank you for reporting this. Could you please share your concerns on the [flutterfire_cli repository](https://github.com/invertase/flutterfire_cli/issues)?

**Comment by surajroy-inland** [comment]
how to resolve this

**Comment by bennajah0** [comment]
@SelaseKay this issue when using flutter 3.28
Because this version use build.gradle.kts

**Comment by EthicalAniruddha** [comment]
I am getting this same error since yesterday. I have searched for a solution but still I could not find one.

Here the error from my side

Android Project Structure

**Comment by luckycreationsindia** [comment]
Same issue found just now. I think we need to configure manually until the package get updated to support build.gradle.kts
