### ISSUE TITLE
[Firebase Messaging, Firebase Analytics]: Firebase service issues with SPM.

### ISSUE THREAD

**Issue by muhammadkamel** [firebase/flutterfire#16898]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Analytics, Messaging

### Which platforms are affected?

iOS

### Description

Please, fix the SPM Integration like what have done for the "firebase_core" package in the latest version.

https://github.com/firebase/flutterfire/pull/16834

### Reproducing the issue

[✓] Flutter (Channel stable, 3.27.1, on macOS 15.2 24C101 darwin-arm64, locale
    en-EG)
    • Flutter version 3.27.1 on channel stable at
      /Users/muhammad/.fvm/versions/3.27.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 17025dd882 (3 days ago), 2024-12-17 03:23:09 +0900
    • Engine revision cb4b5fff73
    • Dart version 3.6.0
    • DevTools version 2.40.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/muhammad/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at:
      /Library/Java/JavaVirtualMachines/jdk-19.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 19.0.2+7-44)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] VS Code (version 1.96.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.102.0

[✓] VS Code (version 1.94.2)
    • VS Code at /Volumes/Data/apppps/Visual Studio Code.app/Contents
    • Flutter extension version 3.102.0

[✓] Connected device (4 available)
    • iPhone 16 (mobile)              • ECD81F69-447D-41FD-98D3-486A7D9722F3 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-18-1 (simulator)
    • macOS (desktop)                 • macos                                •
      darwin-arm64   • macOS 15.2 24C101 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                •
      darwin         • macOS 15.2 24C101 darwin-arm64
    • Chrome (web)                    • chrome                               •
      web-javascript • Google Chrome 131.0.6778.205

[✓] Network resources
    • All expected network resources are available.

### Firebase Core version

3.9.0

### Flutter Version

3.27.1

### Relevant Log Output

```shell

```

### Flutter dependencies

dependencies:
  flutter:
    sdk: flutter

  # firebase
  firebase_core: ^3.9.0

  # state management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4

  # local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  path_provider: ^2.1.5
  shared_preferences: ^2.3.4

  #localization
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

  #  apis packages
  http: ^1.2.2
  mime: ^2.0.0
  # http_parser: ^4.1.0
  # collection: ^1.19.0
  dio: ^5.7.0

  # other packages
  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0
  lottie: ^3.3.0
  flutter_easyloading: ^3.0.5
  loading_animation_widget: ^1.3.0
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.8.0
  carousel_slider: ^5.0.0
  email_validator: ^3.0.0
  page_view_indicators: ^2.0.0
  pinput: ^5.0.0
  flutter_svg: ^2.0.16
  cached_network_image: ^3.4.1
  eva_icons_flutter: ^3.1.0
  flutter_typeahead: ^5.2.0
  equatable: ^2.0.7
  getwidget: ^5.0.0
  page_transition: ^2.1.0
  # file_picker: ^8.1.2
  photo_view: ^0.15.0
  package_info_plus: ^8.1.2
  pretty_dio_logger: ^1.4.0
  connectivity_plus: ^6.1.1
  fluttertoast: ^8.2.10
  flutter_local_notifications: ^18.0.1
  device_preview: ^1.2.0
  flutter_multi_formatter: ^2.13.0
  country_code_picker: ^3.1.0
  syncfusion_flutter_sliders: ^28.1.35
  syncfusion_flutter_core: ^28.1.35

  country_picker: ^2.0.27
  image_picker: ^1.1.2
  gap: ^3.0.1
  hugeicons: ^0.0.7
  line_icons: ^2.0.3
  fluentui_system_icons: ^1.1.270
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^14.6.2
  internet_connection_checker: ^3.0.1
  persistent_bottom_nav_bar_v2: ^5.3.1
  collection: ^1.19.0
  get_it: ^8.0.3
  flutter_hooks: ^0.20.5

**Comment by muhammadkamel** [comment]
firebase_analytics: ^11.3.6
  firebase_core: ^3.9.0
  firebase_messaging: ^15.1.6


[!] Unable to find a specification for `firebase_core` depended upon by `firebase_analytics`

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.


When I am using Firebase core package only the app works well.

**Comment by SelaseKay** [comment]
Hi @muhammadkamel, thank you for the report. A similar issue already exists, which you can track for updates [here](https://github.com/firebase/flutterfire/issues/16670).
