### ISSUE TITLE
[firebase_auth ]: <Build process failed>

### ISSUE THREAD

**Issue by IsmailHosenIsmailJames** [firebase/flutterfire#16909]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Auth

### Which platforms are affected?

Windows

### Description

I was unable to compile or build for Windows. The firebase_auth package now has Windows support, so it was expected that the project would be built without any issues. But firebase_auth 5.3.4 is as dependency, the project doesn't compile for Windows. 

I am getting error when I try to build for windows. This is the error looks like :

```
> flutter build windows

Nuget.exe not found, trying to download or use cached version.
C:\Users\mdism\hr_platform\windows\flutter\ephemeral\cpp_client_wrapper\include\flutter\encodable_value.h(199,60): error C2665: 'std::variant<std::monostate,bool,int32_t,int64_t,double,std::string,std::vector<uint8_t,std::allocator<uint8_t>>,std::vector<int32_t,std::allocator<int>>,std::vector<int64_t,std::allocator<int64_t>>,std::vector<double,std::allocator<double>>,flutter::EncodableList,flutter::EncodableMap,flutter::CustomEncodableValue,std::vector<float,std::allocator<float>>>::variant': no overloaded function could convert all the argument types [C:\Users\mdism\hr_platform\build\windows\x64\plugins\firebase_auth\firebase_auth_plugin.vcxproj]
Building Windows application...                                    11.8s
Build process failed.
```

### Reproducing the issue

I did not write any code that will be required to import firebase_auth. I simply added firebase_auth as a dependency. The project was configured using flutterfire_cli. Then I go this error : 

```
> flutter build windows

Nuget.exe not found, trying to download or use cached version.
C:\Users\mdism\hr_platform\windows\flutter\ephemeral\cpp_client_wrapper\include\flutter\encodable_value.h(199,60): error C2665: 'std::variant<std::monostate,bool,int32_t,int64_t,double,std::string,std::vector<uint8_t,std::allocator<uint8_t>>,std::vector<int32_t,std::allocator<int>>,std::vector<int64_t,std::allocator<int64_t>>,std::vector<double,std::allocator<double>>,flutter::EncodableList,flutter::EncodableMap,flutter::CustomEncodableValue,std::vector<float,std::allocator<float>>>::variant': no overloaded function could convert all the argument types [C:\Users\mdism\hr_platform\build\windows\x64\plugins\firebase_auth\firebase_auth_plugin.vcxproj]
Building Windows application...                                    11.8s
Build process failed.
```

### Firebase Core version

3.9.0

### Flutter Version

3.27.1

### Relevant Log Output

```shell
> flutter build windows

Nuget.exe not found, trying to download or use cached version.
C:\Users\mdism\hr_platform\windows\flutter\ephemeral\cpp_client_wrapper\include\flutter\encodable_value.h(199,60): error C2665: 'std::variant<std::monostate,bool,int32_t,int64_t,double,std::string,std::vector<uint8_t,std::allocator<uint8_t>>,std::vector<int32_t,std::allocator<int>>,std::vector<int64_t,std::allocator<int64_t>>,std::vector<double,std::allocator<double>>,flutter::EncodableList,flutter::EncodableMap,flutter::CustomEncodableValue,std::vector<float,std::allocator<float>>>::variant': no overloaded function could convert all the argument types [C:\Users\mdism\hr_platform\build\windows\x64\plugins\firebase_auth\firebase_auth_plugin.vcxproj]
Building Windows application...                                    11.8s
Build process failed.
```

### Flutter dependencies

name: demo
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hive_flutter: ^1.1.0
  url_strategy: ^0.3.0
  gap: ^3.0.1
  email_validator: ^3.0.0
  firebase_core: ^3.8.1
  cloud_firestore: ^5.5.1
  firebase_storage: ^12.3.7
  firebase_auth: ^5.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

**Comment by SelaseKay** [comment]
Hi @IsmailHosenIsmailJames, thanks for the report. This issue appears to have been resolved but yet to be released. If you need an immediate workaround, please refer to the steps outlined in this [comment](https://github.com/firebase/flutterfire/issues/16536#issuecomment-2549773571).

**Comment by IsmailHosenIsmailJames** [comment]
@SelaseKay thank you very much. It's working now.

**I just did this** 

```
dependencies:
  firebase_auth:
    git:
      url: https://github.com/FirebaseExtended/flutterfire.git
      path: packages/firebase_auth/firebase_auth
      ref: main
```
