### ISSUE TITLE
Firebase Auth Error Running windows Platform

### ISSUE THREAD

**Issue by skylastn** [firebase/flutterfire#16922]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Description

D:\Kerja\Perusahaan\PT_Anugrah_Bersama_Teknology\Food_Order\food_order\windows\flutter\ephemeral\cpp_client_wrapper\include\flutter\encodable_value.h(199,60): error C2665: 'std::variant<std::monostate,bool,int32_t,int64_t,double,std::string,std::vector<uint8_t,std::allocator<uint8_t>>,std::vector<int32_t,std::allocator<int>>,std::vector<int64_t,std::allocator<int64_t>>,std::vector<double,std::allocator<double>>,flutter::EncodableList,flutter::EncodableMap,flutter::CustomEncodableValue,std::vector<float,std::allocator<float>>>::variant': no overloaded function could convert all the argument types [D:\Kerja\Perusahaan\PT_Anugrah_Bersama_Teknology\Food_Order\food_order\build\windows\x64\plugins\firebase_auth\firebase_auth_plugin.vcxproj]

### Reproducing the issue

D:\Kerja\Perusahaan\PT_Anugrah_Bersama_Teknology\Food_Order\food_order\windows\flutter\ephemeral\cpp_client_wrapper\include\flutter\encodable_value.h(199,60): error C2665: 'std::variant<std::monostate,bool,int32_t,int64_t,double,std::string,std::vector<uint8_t,std::allocator<uint8_t>>,std::vector<int32_t,std::allocator<int>>,std::vector<int64_t,std::allocator<int64_t>>,std::vector<double,std::allocator<double>>,flutter::EncodableList,flutter::EncodableMap,flutter::CustomEncodableValue,std::vector<float,std::allocator<float>>>::variant': no overloaded function could convert all the argument types [D:\Kerja\Perusahaan\PT_Anugrah_Bersama_Teknology\Food_Order\food_order\build\windows\x64\plugins\firebase_auth\firebase_auth_plugin.vcxproj]

### Firebase Core version

3.9.0

### Flutter Version

3.27.1

### Relevant Log Output

```shell

```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by skylastn** [comment]
Flutter dependencies
firebase_core: ^3.9.0
firebase_auth: ^5.3.4
firebase_messaging: ^15.1.6
google_sign_in: ^6.2.2

**Comment by SelaseKay** [comment]
Hi @skylastn, this issue is resolved but not yet released. For a workaround, please see [this comment](https://github.com/firebase/flutterfire/issues/16536#issuecomment-2549773571).
