### ISSUE TITLE
[firebase_messaging] Need Kotlin documentation and example  

### ISSUE THREAD

**Issue by giorgio79** [firebase/flutterfire#2311]
**Describe the bug**
At https://pub.dev/packages/firebase_messaging step 6 of backgrond messaging talks about MainActivity.java but it does not exist for my Flutter project.
![image](https://user-images.githubusercontent.com/283347/78545594-5503d580-77fc-11ea-8faa-a07f941b65e5.png)

Looks like a lot of others have this issue https://stackoverflow.com/questions/59225943/flutter-project-mainactivity-java-is-missing

**To Reproduce**
2. '...'
4. See error or incorrect behavior

**Expected behavior**

**Additional context**

**Comment by TahaTesser** [comment]
Hi @giorgio79 
Your project has Kotlin instead of Java . You can implement `MainActivity.kt` from this [answer](https://stackoverflow.com/a/60634673)

or you can create Flutter project with java support an follow the steps to implement `firebase_messaging`

Closing, as this isn't an issue with `firebase_messaging` itself,
if you disagree please write in the comments and I will reopen it 
Thank you

**Comment by giorgio79** [comment]
Thanks Taha. Perhaps the documentaiton could be improved at https://pub.dev/packages/firebase_messaging
I assume the kotlin based projects will prevail over pure Java, as Flutter rocks.

**Comment by TahaTesser** [comment]
Hi @giorgio79 
thanks for feedback

**Comment by giorgio79** [comment]
Just found a dupe thread :) https://github.com/FirebaseExtended/flutterfire/issues/1906

**Comment by giorgio79** [comment]
PS, it is also unclear whether we should paste the stuff after what is in MainActivity.kt or overwrite what is in there? For now, I just pasted after what was in there...

`
import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant
//https://stackoverflow.com/questions/59984162/firebase-messaging-handle-background-message-in-kotlin/60634673#60634673
import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService

class MainActivity: FlutterActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}

import io.flutter.app.FlutterApplication
import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService


class Application : FlutterApplication(), PluginRegistrantCallback {
    fun onCreate() {
        super.onCreate()
        FlutterFirebaseMessagingService.setPluginRegistrant(this)
    }

    fun registerWith(registry: PluginRegistry?) {
        GeneratedPluginRegistrant.registerWith(registry)
    }
}`

**Comment by giorgio79** [comment]
Ok, I think the Google team needs to do a better job. I am unsuccessful so far in updating my main Kotlin file, getting errors like this based on the linked stackoverflow kotlin example... The imports are also totally different from the default kotlin file provided out of the box...


```
package me.exampleapp

import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant
//https://stackoverflow.com/questions/59984162/firebase-messaging-handle-background-message-in-kotlin/60634673#60634673
import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService
import io.flutter.app.FlutterApplication
import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService


class Application : FlutterApplication(), PluginRegistrantCallback {
    fun onCreate() {
        super.onCreate()
        FlutterFirebaseMessagingService.setPluginRegistrant(this)
    }

    fun registerWith(registry: PluginRegistry?) {
        GeneratedPluginRegistrant.registerWith(registry)
    }
}

```
```
Launching lib\main.dart on Pixel 2 in debug mode...
Running Gradle task 'assembleDebug'...
e: android\app\src\main\kotlin\me\cashnear\MainActivity.kt: (8, 45): Conflicting import, imported name 'FlutterFirebaseMessagingService' is ambiguous
e: android\app\src\main\kotlin\me\cashnear\MainActivity.kt: (12, 45): Conflicting import, imported name 'FlutterFirebaseMessagingService' is ambiguous
e: android\app\src\main\kotlin\me\cashnear\MainActivity.kt: (16, 9): 'onCreate' hides member of supertype 'FlutterApplication' and needs 'override' modifier
e: android\app\src\main\kotlin\me\cashnear\MainActivity.kt: (21, 9): 'registerWith' hides member of supertype 'PluginRegistrantCallback' and needs 'override' modifier
e: android\app\src\main\kotlin\me\cashnear\MainActivity.kt: (22, 48): Type mismatch: inferred type is PluginRegistry? but FlutterEngine was expected

FAILURE: Build failed with an exception.
```

**Comment by giorgio79** [comment]
Lol I am finding so many issues around this and the plugin page has no up to date documentation ... WTF Simple carelessness...

https://github.com/FirebaseExtended/flutterfire/issues/1684
https://github.com/FirebaseExtended/flutterfire/issues/1613

**Comment by giorgio79** [comment]
Thanks Taha! Looking forward to a working Kotlin / Flutter example. The example linked from firebase_messaging pub dart page is 3 years old and Java based... https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/example

**Comment by hectorAguero** [comment]
I don't have time to test this, but based in another plugin that I'm use, and use isolate services, maybe this will be the Android code for handle background notifications, with flutter v2 embedding.


**Application.kt**
```kotlin
package your.app.package

import io.flutter.app.FlutterApplication
import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
import io.flutter.view.FlutterMain
import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService

class Application : FlutterApplication(), PluginRegistrantCallback {
    override fun onCreate() {
        super.onCreate()
        FlutterFirebaseMessagingService.setPluginRegistrant(this)
        FlutterMain.startInitialization(this)
    }
    
    override fun registerWith(registry: PluginRegistry?) {
         if (!registry!!.hasPlugin("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin")) {
            FlutterFirebaseMessagingService.registerWith(registry!!.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"))
        }
    }
}
```

**MainActivity.kt**
```kotlin
package your.app.package

import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {
}

```

**Comment by joshua1996** [comment]
> Update: based in another plugin that I'm using in another app, I'm ussing this code for handle background message in kotlin... I don't know is better than stackoverflow answer, but works.
> 
> **Application.kt**
> 
> ```kotlin
> package your.app.package
> 
> import io.flutter.app.FlutterApplication
> import io.flutter.plugin.common.PluginRegistry
> import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
> import io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin
> import io.flutter.view.FlutterMain
> import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService
> 
> class Application : FlutterApplication(), PluginRegistrantCallback {
> 
>     override fun onCreate() {
>         super.onCreate()
>         FlutterFirebaseMessagingService.setPluginRegistrant(this);
>         FlutterMain.startInitialization(this)
>     }
> 
>     override fun registerWith(registry: PluginRegistry?) {
>         if (!registry!!.hasPlugin("io.flutter.plugins.firebasemessaging")) {
>             FirebaseMessagingPlugin.registerWith(registry!!.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"));
>         }
>     }
> }
> ```

Yes, It works! Thank You

**Comment by bretie** [comment]
> Update: based in another plugin that I'm using in another app, I'm ussing this code for handle background message in kotlin... I don't know is better than stackoverflow answer, but works.
> 
> **Application.kt**
> 
> ```kotlin
> package your.app.package
> 
> import io.flutter.app.FlutterApplication
> import io.flutter.plugin.common.PluginRegistry
> import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
> import io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin
> import io.flutter.view.FlutterMain
> import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService
> 
> class Application : FlutterApplication(), PluginRegistrantCallback {
> 
>     override fun onCreate() {
>         super.onCreate()
>         FlutterFirebaseMessagingService.setPluginRegistrant(this);
>         FlutterMain.startInitialization(this)
>     }
> 
>     override fun registerWith(registry: PluginRegistry?) {
>         if (!registry!!.hasPlugin("io.flutter.plugins.firebasemessaging")) {
>             FirebaseMessagingPlugin.registerWith(registry!!.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"));
>         }
>     }
> }
> ```

Can you share everything you've done?
Did you remove your MainActivity file? Did you update your AndroidManifest.xml android:name?

**Comment by hpadrao** [comment]
You have to update the `AndroidManifest.xml` as well.
```
-        android:name="io.flutter.app.FlutterApplication"
+        android:name=". Application"
```
and add:
```
            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
```
inside the `<activity` tag.

**Comment by bretie** [comment]
> You have to update the `AndroidManifest.xml` as well.
> 
> ```
> -        android:name="io.flutter.app.FlutterApplication"
> +        android:name=".Application"
> ```
> 
> and add:
> 
> ```
>             <intent-filter>
>                 <action android:name="FLUTTER_NOTIFICATION_CLICK" />
>                 <category android:name="android.intent.category.DEFAULT" />
>             </intent-filter>
> ```
> 
> inside the `<activity` tag.

Is there more of your implementation you can share? Like a spoonfeeding of information?

How did you declare your myBackgroundMessageHandler function?

What are you using for MainActivity.kt?

What are you using for Application.kt?

What does your AndroidManifest have in it?
Does the package name at the top match what's in google-services.json? Does it match what's in the MainActivity.kt?

What version of the actual plugin are yo using in pubspec?

What version of the android/app/build.gradle dependency are you using?
Ex: implementation "com.google.firebase:firebase-messaging:XXXX

My mind is blown by this plugin. None of it makes sense, thanks in advance.

**Comment by hectorAguero** [comment]
@bretie  you need to follow the pub.dev documentation https://pub.dev/packages/firebase_messaging

The only thing that change from that for flutter kotlin projects is the code below the step that says:

**_2. Add an Application.java class to your app in the same directory as your MainActivity.java. This is typically found in <app-name>/android/app/src/main/java/<app-organization-path>/._**

If the proccess is too complicated you can search for a youtube video

**Comment by bretie** [comment]
> @bretie you need to follow the pub.dev documentation https://pub.dev/packages/firebase_messaging
> 
> The only thing that change from that for flutter kotlin projects is the code below the step that says:
> 
> **_2. Add an Application.java class to your app in the same directory as your MainActivity.java. This is typically found in /android/app/src/main/java//._**
> 
> If the proccess is too complicated you can search for a youtube video

I can assure you it's not too complicated. When it comes to background messages using this plug it tends to be inconsistent compatibility. It requires unique steps for every other person that aren't documented. Hence, me asking for your full implementation.

**Comment by lakshanmamalgaha** [comment]
> 
> 
> Update: based in another plugin that I'm using in another app, I'm ussing this code for handle background message in kotlin... I don't know is better than stackoverflow answer, but works.
> 
> **Application.kt**
> 
> ```kotlin
> package your.app.package
> 
> import io.flutter.app.FlutterApplication
> import io.flutter.plugin.common.PluginRegistry
> import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
> import io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin
> import io.flutter.view.FlutterMain
> import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService
> 
> class Application : FlutterApplication(), PluginRegistrantCallback {
> 
>     override fun onCreate() {
>         super.onCreate()
>         FlutterFirebaseMessagingService.setPluginRegistrant(this);
>         FlutterMain.startInitialization(this)
>     }
> 
>     override fun registerWith(registry: PluginRegistry?) {
>         if (!registry!!.hasPlugin("io.flutter.plugins.firebasemessaging")) {
>             FirebaseMessagingPlugin.registerWith(registry!!.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"));
>         }
>     }
> }
> ```

I' ve spend around 2 hours to fix this. Thanks a lot. You saved mine time.

**Comment by randika-srimal** [comment]
@giorgio79 Did you find a solution yet for this ?

**Comment by Purvik** [comment]
> > Update: based in another plugin that I'm using in another app, I'm ussing this code for handle background message in kotlin... I don't know is better than stackoverflow answer, but works.
> > **Application.kt**
> > ```kotlin
> > package your.app.package
> > 
> > import io.flutter.app.FlutterApplication
> > import io.flutter.plugin.common.PluginRegistry
> > import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
> > import io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin
> > import io.flutter.view.FlutterMain
> > import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService
> > 
> > class Application : FlutterApplication(), PluginRegistrantCallback {
> > 
> >     override fun onCreate() {
> >         super.onCreate()
> >         FlutterFirebaseMessagingService.setPluginRegistrant(this);
> >         FlutterMain.startInitialization(this)
> >     }
> > 
> >     override fun registerWith(registry: PluginRegistry?) {
> >         if (!registry!!.hasPlugin("io.flutter.plugins.firebasemessaging")) {
> >             FirebaseMessagingPlugin.registerWith(registry!!.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"));
> >         }
> >     }
> > }
> > ```
> 
> I' ve spend around 2 hours to find fix for this. Thanks a lot. You saved me.

Buddy, you saved my day.

**Comment by randika-srimal** [comment]
@giorgio79 , I struggled with this for many hours. Even the above solutions didn't work for me. Finally found a way solve this. Here is how I managed to fix this.

1. Change `AndroidManifest.xml` name properties as below.

```xml 
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.app">
    <application
        android:name=".Application">
           <activity
            android:name=".MainActivity">
           </activity>
    </application>
</manifest>
```
2. Empty `MainActivity.kt` file as below.

```kt
package com.example.app

import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {}
```

3. Add `FirebaseCloudMessagingPluginRegistrant.kt` file in same directory.

```kt
package com.example.app

import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin

object FirebaseCloudMessagingPluginRegistrant {
    fun registerWith(registry: PluginRegistry?) {
        if (alreadyRegisteredWith(registry)) {
            return
        }
        FirebaseMessagingPlugin.registerWith(registry?.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"))
    }

    private fun alreadyRegisteredWith(registry: PluginRegistry?): Boolean {
        val key: String? = FirebaseCloudMessagingPluginRegistrant::class.java.canonicalName
        if (registry?.hasPlugin(key)!!) {
            return true
        }
        registry.registrarFor(key)
        return false
    }
}
```

4. Add `Application.kt` file in same directory.

```kt
package com.example.app

import io.flutter.app.FlutterApplication
import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService

class Application : FlutterApplication(), PluginRegistrantCallback {
    override fun onCreate() {
        super.onCreate()
        FlutterFirebaseMessagingService.setPluginRegistrant(this)
    }

    override fun registerWith(registry: PluginRegistry?) {
        FirebaseCloudMessagingPluginRegistrant.registerWith(registry)
    }
}
```

**Comment by fahmisatrio** [comment]
> 
> 
> You have to update the `AndroidManifest.xml` as well.
> 
> ```
> -        android:name="io.flutter.app.FlutterApplication"
> +        android:name=".Application"
> ```
> 
> and add:
> 
> ```
>             <intent-filter>
>                 <action android:name="FLUTTER_NOTIFICATION_CLICK" />
>                 <category android:name="android.intent.category.DEFAULT" />
>             </intent-filter>
> ```
> 
> inside the `<activity` tag.

thanks a lot @hectorAguero and @hpadrao ,
i misstype changing android:name --> .Application inside activity instead of android:name inside application tag.

**Comment by deadsoul44** [comment]
Totally lost with Kotlin implementation. This issue has been open for 5 months. We need an immediate solution.

**Comment by EdwinOlivera** [comment]
> @giorgio79 , I struggled with this for many hours. Even the above solutions didn't work for me. Finally found a way solve this. Here is how I managed to fix this.
> 
> 1. Change `AndroidManifest.xml` name properties as below.
> 
> ```
> <manifest xmlns:android="http://schemas.android.com/apk/res/android"
>     package="com.example.app">
>     <application
>         android:name=".Application">
>            <activity
>             android:name=".MainActivity">
>            </activity>
>     </application>
> </manifest>
> ```
> 
> 1. Empty `MainActivity.kt` file as below.
> 
> ```kotlin
> package com.example.app
> 
> import androidx.annotation.NonNull;
> import io.flutter.embedding.android.FlutterActivity
> import io.flutter.embedding.engine.FlutterEngine
> import io.flutter.plugins.GeneratedPluginRegistrant
> 
> class MainActivity: FlutterActivity() {}
> ```
> 
> 1. Add `FirebaseCloudMessagingPluginRegistrant.kt` file in same directory.
> 
> ```kotlin
> package com.example.app
> 
> import io.flutter.plugin.common.PluginRegistry
> import io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin
> 
> object FirebaseCloudMessagingPluginRegistrant {
>     fun registerWith(registry: PluginRegistry?) {
>         if (alreadyRegisteredWith(registry)) {
>             return
>         }
>         FirebaseMessagingPlugin.registerWith(registry?.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"))
>     }
> 
>     private fun alreadyRegisteredWith(registry: PluginRegistry?): Boolean {
>         val key: String? = FirebaseCloudMessagingPluginRegistrant::class.java.canonicalName
>         if (registry?.hasPlugin(key)!!) {
>             return true
>         }
>         registry.registrarFor(key)
>         return false
>     }
> }
> ```
> 
> 1. Add `Application.kt` file in same directory.
> 
> ```kotlin
> package com.example.app
> 
> import io.flutter.app.FlutterApplication
> import io.flutter.plugin.common.PluginRegistry
> import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
> import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService
> 
> class Application : FlutterApplication(), PluginRegistrantCallback {
>     override fun onCreate() {
>         super.onCreate()
>         FlutterFirebaseMessagingService.setPluginRegistrant(this)
>     }
> 
>     override fun registerWith(registry: PluginRegistry?) {
>         FirebaseCloudMessagingPluginRegistrant.registerWith(registry)
>     }
> }
> ```

Esta es la solucion al problema. A mi me funcion perfectamente. No me habia dado cuenta que no tenia los archivos en un mismo directorio. Espero que esto le sirva a otras personas.

**Comment by robgry** [comment]
This took me a while to figure out but here is a working solution:

You'll need two files in the SAME directory as your MainActivity.kt. The two files:



**MainActivity.kt**

This file will stay the same.

```
package com.example.app

import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {
}
```

**Application.kt**

```
package com.example.app

import io.flutter.app.FlutterApplication
import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
import io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin
import io.flutter.view.FlutterMain
import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService

class Application : FlutterApplication(), PluginRegistrantCallback {

    override fun onCreate() {
        super.onCreate()
        FlutterFirebaseMessagingService.setPluginRegistrant(this);
        FlutterMain.startInitialization(this)
    }

    override fun registerWith(registry: PluginRegistry?) {
        if (!registry!!.hasPlugin("io.flutter.plugins.firebasemessaging")) {
            FirebaseMessagingPlugin.registerWith(registry!!.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"));
        }
    }
}

```

You then need to update your AndroidManifest.xml to point at these two files. You do this like this:

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.app">
    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
         <!-- 
           <application
        android:name="io.flutter.app.FlutterApplication"
         -->
    <application
        android:name=".Application"
        android:label="example"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"

```

So, you've essentially replaced the application file and kept the main activity the same. 

**Don't forget**

You need to drop this in the AndroidManifest.xml file as well within the activity tags. 

```
<intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
```

**Comment by ming-chu** [comment]
I follow this doc and it works fine.
https://firebase.flutter.dev/docs/messaging/overview

`firebase_core: ^0.5.1`
`firebase_messaging: ^8.0.0-dev.5`

ps. I am using Flutter Android Embedding V2 

Hope this helps.

**Comment by deadsoul44** [comment]
I also moved my app from Kotlin to Java. Kotlin first development is a lie and we shouldn't rely on fancy announcements.

**Comment by KaungZawHtet** [comment]
Deprecated doc killing many apps including mine. There r many solutions but I don't know which one should be final. Plz consider to update the doc

**Comment by zstima** [comment]
didnt read a lot of these posts, but i managed to get push working on an emulator, running a flutter build.

the main thing u gotta use is PlatformChannel, to call a method written in kt/java files from the flutter widget or flutter file.
u gotta setup the channel on both sides of the code, so flutter calls method using PlatformChannel and kotlin/java recieves the call.

i succesfully got a push message from the console on a flutter app.

the instructions provided online are OK but somewhat confusing with all the classes (somewhat bulky) u gotta use, especially if ure not experienced.

**Comment by mohadel92** [comment]
i have found the solution for this problem 
first you have to create 2 files in the same directory of MainActivity.kt: 
1- Application.kt:
`package <your package path e.g : com.bla bla bla .bla >


import io.flutter.app.FlutterApplication
import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
import io.flutter.plugins.GeneratedPluginRegistrant
import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService

class Application : FlutterApplication(), PluginRegistrantCallback {

    override fun onCreate() {
        super.onCreate()
        FlutterFirebaseMessagingService.setPluginRegistrant(this);
    }

    override fun registerWith(registry: PluginRegistry?) {
        io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin.registerWith(registry?.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"));
    }
}`
2- create FirebaseCloudMessagingPluginRegistrant.kt:
`package <your package path e.g : com.bla bla bla .bla >

import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin

object FirebaseCloudMessagingPluginRegistrant {
    fun registerWith(registry: PluginRegistry?) {
        if (alreadyRegisteredWith(registry)) {
            return
        }
        FirebaseMessagingPlugin.registerWith(registry?.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"))
    }

    private fun alreadyRegisteredWith(registry: PluginRegistry?): Boolean {
        val key: String? = FirebaseCloudMessagingPluginRegistrant::class.java.canonicalName
        if (registry?.hasPlugin(key)!!) {
            return true
        }
        registry.registrarFor(key)
        return false
    }
}`

3- then modify MainActivity.kt to look like:
`package <your package path e.g : com.bla bla bla .bla >

import androidx.annotation.NonNull
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}
`

4- reference MainActivity.kt and Application.kt in Androidmainfest.xml file:
a- `<application
        android:name="com.blablabla.Application"` 
b-`<activity android:name="com.blablabla.MainActivity"`

**Comment by Karlheinzniebuhr** [comment]
Documentation needs urgent updating, still no official Kotlin example despite Flutter overtaking the industry!

**Comment by abdullah432** [comment]
firebase_messaging: "^9.0.0" (Null Safety)

```
com.example.yourpackagename;
import io.flutter.app.FlutterApplication;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback;
import io.flutter.plugins.GeneratedPluginRegistrant;
import io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService;

class Application : FlutterApplication(), PluginRegistrantCallback {

  override fun onCreate() {
    super.onCreate()
    FlutterFirebaseMessagingBackgroundService.setPluginRegistrant(this)
  }


  override fun registerWith(registry: PluginRegistry?) {
        io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingPlugin.registerWith(registry?.registrarFor("io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingPlugin"));
    }

}

```

**Comment by uc-dve** [comment]
> > PluginRegistrantCallback
> 
> Not working again.
> "PluginRegistrantCallback" is deprecated now. Any solution?

I have just updated flutter 2 and write the below code and it works for me

```
package com.flutter.yourPackageName
import io.flutter.app.FlutterApplication
import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
import io.flutter.view.FlutterMain
import io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService;

class Application : FlutterApplication(), PluginRegistrantCallback {

    override fun onCreate() {
        super.onCreate()
        FlutterFirebaseMessagingBackgroundService.setPluginRegistrant(this);
        FlutterMain.startInitialization(this)
    }

    override fun registerWith(registry: PluginRegistry?) {
    }
}
```

**Comment by abdullah432** [comment]
> > > PluginRegistrantCallback
> > 
> > 
> > Not working again.
> > "PluginRegistrantCallback" is deprecated now. Any solution?
> 
> I have just updated flutter 2 and write the below code and it works for me
> 
> ```
> package com.flutter.yourPackageName
> import io.flutter.app.FlutterApplication
> import io.flutter.plugin.common.PluginRegistry
> import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
> import io.flutter.view.FlutterMain
> import io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService;
> 
> class Application : FlutterApplication(), PluginRegistrantCallback {
> 
>     override fun onCreate() {
>         super.onCreate()
>         FlutterFirebaseMessagingBackgroundService.setPluginRegistrant(this);
>         FlutterMain.startInitialization(this)
>     }
> 
>     override fun registerWith(registry: PluginRegistry?) {
>     }
> }
> ```

https://github.com/transistorsoft/flutter_background_fetch/issues/127#issuecomment-643795427
Please check out this answer, here this dude is saying that we no longer need custom .Application class. I follow him and the issue now get resolved.

**Comment by SAMYAK99** [comment]
> Update: based in another plugin that I'm using in another app, I'm ussing this code for handle background message in kotlin... I don't know is better than stackoverflow answer, but works.
> 
> **Application.kt**
> 
> ```kotlin
> package your.app.package
> 
> import io.flutter.app.FlutterApplication
> import io.flutter.plugin.common.PluginRegistry
> import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
> import io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin
> import io.flutter.view.FlutterMain
> import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService
> 
> class Application : FlutterApplication(), PluginRegistrantCallback {
> 
>     override fun onCreate() {
>         super.onCreate()
>         FlutterFirebaseMessagingService.setPluginRegistrant(this);
>         FlutterMain.startInitialization(this)
>     }
> 
>     override fun registerWith(registry: PluginRegistry?) {
>         if (!registry!!.hasPlugin("io.flutter.plugins.firebasemessaging")) {
>             FirebaseMessagingPlugin.registerWith(registry!!.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"));
>         }
>     }
> }
> ```


It works 🤩🤩

**Comment by rs-anhnq2** [comment]
> @giorgio79 , I struggled with this for many hours. Even the above solutions didn't work for me. Finally found a way solve this. Here is how I managed to fix this.
> 
> 1. Change `AndroidManifest.xml` name properties as below.
> 
> ```
> <manifest xmlns:android="http://schemas.android.com/apk/res/android"
>     package="com.example.app">
>     <application
>         android:name=".Application">
>            <activity
>             android:name=".MainActivity">
>            </activity>
>     </application>
> </manifest>
> ```
> 
> 1. Empty `MainActivity.kt` file as below.
> 
> ```kotlin
> package com.example.app
> 
> import androidx.annotation.NonNull;
> import io.flutter.embedding.android.FlutterActivity
> import io.flutter.embedding.engine.FlutterEngine
> import io.flutter.plugins.GeneratedPluginRegistrant
> 
> class MainActivity: FlutterActivity() {}
> ```
> 
> 1. Add `FirebaseCloudMessagingPluginRegistrant.kt` file in same directory.
> 
> ```kotlin
> package com.example.app
> 
> import io.flutter.plugin.common.PluginRegistry
> import io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin
> 
> object FirebaseCloudMessagingPluginRegistrant {
>     fun registerWith(registry: PluginRegistry?) {
>         if (alreadyRegisteredWith(registry)) {
>             return
>         }
>         FirebaseMessagingPlugin.registerWith(registry?.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"))
>     }
> 
>     private fun alreadyRegisteredWith(registry: PluginRegistry?): Boolean {
>         val key: String? = FirebaseCloudMessagingPluginRegistrant::class.java.canonicalName
>         if (registry?.hasPlugin(key)!!) {
>             return true
>         }
>         registry.registrarFor(key)
>         return false
>     }
> }
> ```
> 
> 1. Add `Application.kt` file in same directory.
> 
> ```kotlin
> package com.example.app
> 
> import io.flutter.app.FlutterApplication
> import io.flutter.plugin.common.PluginRegistry
> import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
> import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService
> 
> class Application : FlutterApplication(), PluginRegistrantCallback {
>     override fun onCreate() {
>         super.onCreate()
>         FlutterFirebaseMessagingService.setPluginRegistrant(this)
>     }
> 
>     override fun registerWith(registry: PluginRegistry?) {
>         FirebaseCloudMessagingPluginRegistrant.registerWith(registry)
>     }
> }
> ```
This works for me.
https://github.com/FirebaseExtended/flutterfire/issues/2311#issuecomment-659620636
Document said that: "If you are using Flutter Android Embedding V2 (Flutter Version >= 1.12) then no additional integration steps are required for Android."
But my flutter version 1.22.6,  firebase_messaging: ^7.0.3, cloud_firestore: ^0.14.4 still get this issue.
Thank you. You save my day!

**Comment by JaviCore** [comment]
Hi there, any idea on how to do this with a FlutterFragmentActivity instead?

**Comment by Lyokone** [comment]
[Official documentation](https://firebase.google.com/docs/cloud-messaging/flutter/client) is not specific to Java now so I'm closing this issue :) 

@JaviCore feel free to open a new issue if you have issues.
