### ISSUE TITLE
Adopt flutter_plugin_tools podspecs linter

### ISSUE THREAD

**Issue by jmagman** [firebase/flutterfire#2405]
[lint_darwin_plugins.sh](https://github.com/FirebaseExtended/flutterfire/blob/master/script/lint_darwin_plugins.sh) now lives in flutter_plugin_tools and has more linting features.
Already done in Flutter plugins with https://github.com/flutter/plugins/pull/2346.

**Comment by jmagman** [comment]
`lint_darwin_plugins.sh` no longer exists and the podspec linting has moved from `.cirrus.yml` to  https://github.com/FirebaseExtended/flutterfire/blob/584d0d340bae7ed3f32c09fe68aab7ddf32a4229/melos.yaml#L75

**Comment by darshankawar** [comment]
Hi @Salakar 
Couldn't find a relevant label for this. Should this be kept as-is ?
Thanks.

**Comment by Lyokone** [comment]
I'm closing this for the following reasons:
- We do not publish the podspecs so the warning are not relevant (missing author or license are included in the dart package)
- the underlying command `pod lib lint` does not support importing variables from ruby files which we use for defining a global firebase_sdk_version

Anybody feel free to reopen if you feel it's important
