### ISSUE TITLE
[firebase_crashlytics] Crashlytics not reporting in dev mode regardless of enableInDevMode

### ISSUE THREAD

**Issue by dotdoom** [firebase/flutterfire#283]
## Steps to reproduce

1. Create a new flutter application
1. Set up crashlytics plugin per https://firebase.flutter.dev/docs/crashlytics/overview/
1. Set `FlutterError.onError` per https://firebase.flutter.dev/docs/crashlytics/usage#handling-uncaught-errors
1. Run application in debug mode and trigger a flutter error, e.g. with a layout:

```diff
- child: Text('$_counter'),
+ child: Text(_counter > 0 ? 'ERROR ' * 1000 : 'Press +'),
```

Expected result: error is reported to Crashlytics
Actual result: no error is reported

Suspect that an error handler is overwritten in dev mode (by default) due to https://github.com/flutter/flutter/issues/41540 and does not let Crashlytics code handle the error and report it upstream.

**Comment by Salakar** [comment]
Given the age of this issue and that Crashlytics has had a major rework since; I'm going to close this issue in favour of trying the latest release

**Comment by dotdoom** [comment]
@Salakar mass closing issues without even giving reporter a chance to reproduce with latest release is rather demotivating. Since underlying issue is still open, I don't believe this is resolved.

**Comment by Salakar** [comment]
I understand how you feel; on the other side of the fence maintainers having to make sense of and investigate every one liner issue report is demotivating. So I'll re-open this.

Having said that (in my brief time having to research it) isn't this specifically something that needs to be resolved in Flutter rather than FlutterFire based on flutter/flutter#41540? I don't have as much understanding or context of this as I'd like in relation to FlutterFire.

**Comment by dotdoom** [comment]
The problem manifests in FlutterFire.  I root caused it to FlutterFire actually exercising behavior that Flutter does not provide.  The fix for this issue can be either a workaround here or an FR to Flutter, and it's not up to me to make this call.

If you had a problem with issue report text I would appreciate you telling me explicitly rather than closing it.  Short description doesn't necessarily mean longer to investigate.

**Comment by Salakar** [comment]
> The fix for this issue can be either a workaround here

What would the work around here look like, can you propose a workaround for this?

**Comment by dotdoom** [comment]
Depends on how far away is the fix in Flutter. In short term, a documentation update could be a good start. It's been a while, I don't have much state swapped in to provide options right away.

**Comment by dotdoom** [comment]
Thanks for checking in, but I have moved on since then and don't have a sample at hand to test it.
