### ISSUE TITLE
🐛 [Firebase_Storage] Slow upload speed 

### ISSUE THREAD

**Issue by hyobbb** [firebase/flutterfire#4278]
I am using firebase storage to save images and videos(.mp4) but upload speed is too slow.
Every files I upload is less then 4MB and it takes more than 15secs to upload it to firebase storage.
If I upload same file directly from console it only takes few seconds.
Is there any way to optimize the upload speed? such as setting chunk size?

Here is the log of uploadTask information and flutter doctor -v 

```
UploadTask uploadVideoFile(String fileName, String filePath, String subFolder) {
    final file = File(filePath);
    //final fileName = path.basename(filePath);
    currentTask = _storageRef
        .child('$video/$subFolder/$fileName.mp4')
        .putFile(file);
    return currentTask;
  }

```
```
      print('[RecordingProviderDebug] start upload ${DateTime.now()}');
      _videoUrl = await uploadVideoFile(videoName, _encodingPath, _subfolder)
          .then((upload) => upload.ref.getDownloadURL());

      print('[RecordingProviderDebug] end upload ${DateTime.now()}');
      print('[RecordingProviderDebug] upload bytes size ${_fireVideoService.currentTask.snapshot.totalBytes}');
```

```
I/flutter (11648): [RecordingProviderDebug] start upload 2020-12-01 15:30:11.337365
I/System.out(11648): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(11648): (HTTPLog)-Static: isSBSettingEnabled false
D/BufferPoolAccessor(11648): bufferpool2 0x6f231f5620 : 0(0 size) total buffers - 0(0 size) used buffers - 1/7 (recycle/alloc) - 6/258 (fetch/transfer)
D/BufferPoolAccessor(11648): Destruction - bufferpool2 0x6f231f5620 cached: 0/0M, 0/0% in use; allocs: 7, 14% recycled; transfers: 258, 98% unfetced
I/ViewRootImpl@eaa066[MainActivity](notion://www.notion.so/11648): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(11648): prepareNavigationBarInfo() DecorView@a651d00[MainActivity]
D/InputMethodManager(11648): getNavigationBarColor() 0
I/System.out(11648): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(11648): (HTTPLog)-Static: isSBSettingEnabled false
D/UploadTask(11648): Increasing chunk size to 524288
I/System.out(11648): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(11648): (HTTPLog)-Static: isSBSettingEnabled false
D/UploadTask(11648): Increasing chunk size to 1048576
I/System.out(11648): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(11648): (HTTPLog)-Static: isSBSettingEnabled false
D/UploadTask(11648): Increasing chunk size to 2097152
I/System.out(11648): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(11648): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(11648): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(11648): (HTTPLog)-Static: isSBSettingEnabled false
I/flutter (11648): [RecordingProviderDebug] end upload 2020-12-01 15:30:29.363642
I/flutter (11648): [RecordingProviderDebug] upload bytes size 3104208
```
Took 18secs for 3.1MB file

```
I/flutter ( 8584): [RecordingProviderDebug] start upload 2020-12-01 15:52:26.829094
I/System.out( 8584): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out( 8584): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out( 8584): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out( 8584): (HTTPLog)-Static: isSBSettingEnabled false
W/ract.nowfiprot( 8584): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
D/UploadTask( 8584): Increasing chunk size to 524288
I/System.out( 8584): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out( 8584): (HTTPLog)-Static: isSBSettingEnabled false
D/UploadTask( 8584): Increasing chunk size to 1048576
I/System.out( 8584): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out( 8584): (HTTPLog)-Static: isSBSettingEnabled false
D/UploadTask( 8584): Increasing chunk size to 2097152
I/System.out( 8584): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out( 8584): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out( 8584): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out( 8584): (HTTPLog)-Static: isSBSettingEnabled false
I/flutter ( 8584): [RecordingProviderDebug] end upload 2020-12-01 15:52:44.418709
I/flutter ( 8584): [RecordingProviderDebug] upload bytes size 2632654
```
Also took 18secs for 2.6MB file

```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-KR)
    • Flutter version 1.22.4 at /Users/hyobbb/development/flutter
    • Framework revision 1aafb3a8b9 (3 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/hyobbb/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9245
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

 
[✓] Connected device (1 available)            
    • SM G970N (mobile) • R39M30264QW • android-arm64 • Android 10 (API 29)

• No issues found!

```

**Comment by markusaksli-nc** [comment]
Hi @hyobbb 
I'm not seeing this issue with my SM G950F on the latest master `1.24.0-8.0.pre.375` using the official example with `firebase_storage: ^5.1.0`.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.24.0-8.0.pre.375, on Microsoft Windows [Version 10.0.19041.630], locale et-EE)
    • Flutter version 1.24.0-8.0.pre.375 at C:\Development\flutter_master
    • Framework revision a7f5fd5360 (22 hours ago), 2020-11-30 13:14:13 +0100
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\202.8194.7
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (6 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.630]
    • Web Server (web)            • web-server         • web-javascript • Flutter Tools
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 87.0.4280.66
    • Edge (web)                  • edge               • web-javascript • Microsoft Edge 87.0.664.47

• No issues found!
```
</details>

Could you test the upload speed of both your computer and phone to see if that could be causing the discrepancy (assuming you meant uploading from your computer when you said uploading from console)? 

If your computer is connected via a cable and your phone is connected via wifi that could cause the difference if your router is particularly subpar or the connection isn't great.
Thank you

**Comment by hyobbb** [comment]
@markusaksli-nc 

Thank you for the reply.
I tried the same process with Andorid Emulator(Pixel 3a) and yes it works fine.

on Emulator 

LAN

```
I/flutter ( 8046): [RecordingProviderDebug] start upload 2020-12-02 10:50:12.919593
D/UploadTask( 8046): Increasing chunk size to 524288
D/UploadTask( 8046): Increasing chunk size to 1048576
I/flutter ( 8046): [RecordingProviderDebug] end upload 2020-12-02 10:50:14.826493
I/flutter ( 8046): [RecordingProviderDebug] upload bytes size 984316
```

WiFi

```
I/flutter (16451): [RecordingProviderDebug] start upload 2020-12-02 11:02:12.608428
D/UploadTask(16451): Increasing chunk size to 524288
D/UploadTask(16451): Increasing chunk size to 1048576
I/flutter (16451): [RecordingProviderDebug] end upload 2020-12-02 11:02:15.465289
I/flutter (16451): [RecordingProviderDebug] upload bytes size 913803
```

with emulator both LAN & WiFi it shows more than 300KB/s.
However in real device

WiFi Real device  SM-G970N

```
I/flutter (18526): [RecordingProviderDebug] start upload 2020-12-02 10:32:47.056455
I/System.out(18526): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(18526): (HTTPLog)-Static: isSBSettingEnabled false
W/ract.nowfiprot(18526): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/ract.nowfiprot(18526): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/ract.nowfiprot(18526): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
I/System.out(18526): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(18526): (HTTPLog)-Static: isSBSettingEnabled false
D/UploadTask(18526): Increasing chunk size to 524288
I/System.out(18526): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(18526): (HTTPLog)-Static: isSBSettingEnabled false
D/UploadTask(18526): Increasing chunk size to 1048576
I/System.out(18526): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(18526): (HTTPLog)-Static: isSBSettingEnabled false
D/UploadTask(18526): Increasing chunk size to 2097152
I/System.out(18526): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(18526): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(18526): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(18526): (HTTPLog)-Static: isSBSettingEnabled false
I/flutter (18526): [RecordingProviderDebug] end upload 2020-12-02 10:33:11.468783
I/flutter (18526): [RecordingProviderDebug] upload bytes size 2126767
```

the upload speed is less than 100KB/s. Could you tell me which factor may cause that difference?

**Comment by hyobbb** [comment]
Also, the upload speed is not even linear with upload data size.

```
I/flutter (10841): [RecordingProviderDebug] start upload 2020-12-02 14:53:27.864421
I/System.out(10841): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(10841): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(10841): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(10841): (HTTPLog)-Static: isSBSettingEnabled false
D/UploadTask(10841): Increasing chunk size to 524288
I/System.out(10841): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(10841): (HTTPLog)-Static: isSBSettingEnabled false
D/UploadTask(10841): Increasing chunk size to 1048576
I/System.out(10841): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(10841): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(10841): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(10841): (HTTPLog)-Static: isSBSettingEnabled false
I/flutter (10841): [RecordingProviderDebug] end upload 2020-12-02 14:53:42.570363
I/flutter (10841): [RecordingProviderDebug] upload bytes size 818114
```

according to this log it takes 15secs for uploading just 818KB size data. Is there any way to check the process with more information?

**Comment by markusaksli-nc** [comment]
I meant if you could check the speed on both devices on a third-party service like https://www.speedtest.net/. The previous possibility for a discrepancy remains since emulator will use the host internet connection.

Not familiar with android networking debugging but you could try `flutter run -v` to see if it provides more logs.

**Comment by hyobbb** [comment]
@markusaksli-nc 
I also tried uploading files from SM 970GN device using firebase console web. It didn't take so long time although I did the task with same device, same internet connection. I will try to run the project with verbose command to see whether there's any problem.

**Comment by hyobbb** [comment]
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-KR)
    • Flutter version 1.22.4 at /Users/hyobbb/development/flutter
    • Framework revision 1aafb3a8b9 (3 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/hyobbb/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9245
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • SM T860 (mobile) • R54M900BP0V • android-arm64 • Android 10 (API 29)


- WiFi & SM T860

I/flutter (25333): [RecordingProviderDebug] start video upload 2020-12-03 10:59:08.408808
I/System.out(25333): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(25333): (HTTPLog)-Static: isSBSettingEnabled false
V/NativeCrypto(25333): Write error: ssl=0x7e87745488: I/O error during system call, Broken pipe
V/NativeCrypto(25333): SSL shutdown failed: ssl=0x7e87745488: I/O error during system call, Success
I/System.out(25333): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(25333): (HTTPLog)-Static: isSBSettingEnabled false
D/UploadTask(25333): Increasing chunk size to 524288
I/System.out(25333): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(25333): (HTTPLog)-Static: isSBSettingEnabled false
W/act.nowfi_prot(25333): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
D/UploadTask(25333): Increasing chunk size to 1048576
I/System.out(25333): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(25333): (HTTPLog)-Static: isSBSettingEnabled false
D/UploadTask(25333): Increasing chunk size to 2097152
I/System.out(25333): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(25333): (HTTPLog)-Static: isSBSettingEnabled false
W/System  (25333): A resource failed to call release.
I/System.out(25333): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(25333): (HTTPLog)-Static: isSBSettingEnabled false
I/flutter (25333): [RecordingProviderDebug] end video upload 2020-12-03 10:59:29.369711
I/flutter (25333): [RecordingProviderDebug] upload bytes size 2145751


I tried with other device and got same results. it took 21secs for uploading 2.14MB videos. I think this is not a problem of internet connection. I am developing with my macbook with same WiFi connection that I used with those devices.

**Comment by hyobbb** [comment]
```
2020-12-03 15:42:57.084690+0900 Runner[980:605851] flutter: [RecordingProviderDebug] start video upload 2020-12-03 15:42:57.084614
2020-12-03 15:42:58.667796+0900 Runner[980:605933] BackgroundSession <85CE1F74-A905-4169-8CD7-431B0F35A967> connection to background transfer daemon invalidated
2020-12-03 15:43:00.281808+0900 Runner[980:605851] flutter: [RecordingProviderDebug] end video upload 2020-12-03 15:43:00.281613
2020-12-03 15:43:00.283060+0900 Runner[980:605851] flutter: [RecordingProviderDebug] upload bytes size 1365464
2020-12-03 15:43:00.284149+0900 Runner[980:605851] flutter: [RecordingProviderDebug] start image upload 2020-12-03 15:43:00.284025
```

I tested with Iphone X with same WiFi connection. It is super fast compared to samsung device. I'd like to know why there's so big difference between devices.

**Comment by surveshoeb** [comment]
@markusaksli-nc I'm also facing the same issue. I tried both the Physical device (Oneplus 8/7t) and Android emulator (Samsung) were both upload the files at very slow speed. It takes approximately 38sec to upload 1.4Mb file where my internet speed is off 25Mbps. 

### Speedtest by Ookla
<img width="731" alt="Screenshot 2020-12-03 at 12 30 52 PM" src="https://user-images.githubusercontent.com/26933124/100975049-648e1680-3563-11eb-876a-00edfa892905.png">


### Sample Code
```
try {
      if (file == null) return null;

      UploadTask uploadTask;
      var fileName = DateTime.now().millisecondsSinceEpoch.toString();
      Reference ref = FirebaseStorage.instance.ref().child(fileName);

      if (kIsWeb)
        uploadTask = ref.putData(await file.readAsBytes());
      else
        uploadTask = ref.putFile(File(file.path));

      final stream = uploadTask.snapshotEvents;

      CloudStorageResult result;

      await for (var event in stream) {
        if (event.state == TaskState.success) {
          var downloadUrl = await uploadTask.snapshot.ref.getDownloadURL();

          var url = downloadUrl.toString();
          result = CloudStorageResult(
            fileUrl: url,
            fileName: fileName,
          );
          break;
        }
      }

      return result;
    } on Exception catch (e) {
      print(e);
      return null;
    }
```

I can use `uploadTask.snapshotEvents.listen((event) { })` instead of `await for (var event in stream) { }` because I need to return the object instead of returning value in callback function.

**Comment by hyobbb** [comment]
Any opinion for the symptom??

**Comment by surveshoeb** [comment]
Any update on this issue?

**Comment by hyobbb** [comment]
umm.. so there's no way to figure it out?

**Comment by sebasbose** [comment]
I am having the same issue. My app uploads pictures without any problems when running on the iOS Simulator, but if I deploy it on a physical device it no longer seems to work. It gets stuck in the "running" TaskState and won't return the URL... very weird.

**Comment by EidarousDev** [comment]
`connection to background transfer daemon invalidated`
Any solution for this?

**Comment by MustafaAdam** [comment]
I'm facing the same frustrating issue.
I'm using Future.wait to wait as per @puf advise on this question from SO:
[How can i upload multiple images to firebase in flutter and get all their download urls](https://stackoverflow.com/questions/63513002/how-can-i-upload-multiple-images-to-firebase-in-flutter-and-get-all-their-downlo)

for all the futures to finish, but's extremely extremely slow

Future<List<String>> uploadToStorage2(List<List<int>> imagesData) {
  String uid = CurrentUser.getCurrentUser().uid;

  var futures = imagesData.map((imageData) async {
    String rannum = Uuid().v1();
    Reference reference = FirebaseStorage.instance.ref().child("$uid/$rannum");
    UploadTask uploadTask = reference.putData(imageData);
    TaskSnapshot taskSnapshot = await uploadTask.whenComplete(() => null);
    return taskSnapshot.ref.getDownloadURL();
  });
  return Future.wait(futures);
}

It's truly frustrating

**Comment by nidegen** [comment]
same here. very sad:(

**Comment by giuliano-oliveira** [comment]
My guess it is a dart/flutter issue?, I'm getting the same issue, however i'm not using Firebase, instead I am uploading a file using the http library, however I get extremely slow upload speeds in a real device (1mb file takes around 30secs to finish), in the emulator it works fine, I've tried the following (no success):
* Using streams reading the file and writing to the request body
* Reading the entire file and putting in the request
* Using dio instead of http package.

**Comment by rolba** [comment]
Hello.
Update from my side. I am also facing the same issue, uploading small files (418KB). I made some experiments with a peace of uploading code:
```
      print('StorageReference start');
      Stopwatch stopwatch = new Stopwatch()..start();
      final Reference storageReference = await firebase_storage.FirebaseStorage.instance
          .ref().child('users').child(uploadFileName);
      print('storageReference executed in ${stopwatch.elapsed}');

      print('Upload start');
      stopwatch = new Stopwatch()..start();
      final UploadTask uploadTask = storageReference.putFile(file);
      print('Upload 1 executed in ${stopwatch.elapsed}');
      final TaskSnapshot taskSnapshot = await uploadTask.whenComplete(() {
        print('Upload 2 executed in ${stopwatch.elapsed}');
      });
```

And here is my log file:
```
I/flutter (22605): StorageReference start
I/flutter (22605): storageReference executed in 0:00:00.000535
I/flutter (22605): Upload start
I/flutter (22605): Upload 1 executed in 0:00:00.002367
W/NetworkRequest(22605): No App Check token for request.
W/NetworkRequest(22605): No App Check token for request.
D/UploadTask(22605): Increasing chunk size to 524288
W/NetworkRequest(22605): No App Check token for request.
I/flutter (22605): Upload 2 executed in 0:00:04.092026
```

Firebase Storage negotiates chunk size to 524288. Pretty obvious, because it's 512KB and I have 418KB file. So I have checked it for 158KB file:
```
I/flutter (22605): StorageReference start
I/flutter (22605): storageReference executed in 0:00:00.000650
I/flutter (22605): Upload start
I/flutter (22605): Upload 1 executed in 0:00:00.002980
W/NetworkRequest(22605): No App Check token for request.
W/NetworkRequest(22605): No App Check token for request.
I/flutter (22605): Upload 2 executed in 0:00:02.745000
```

So I I have checked is my Internet provider upload speed. It is low, 2Mbps.

Than I rerun my experiment, and switched to my LTE and again checked the upload speed: 1.5Mbps. And again uploaded 418KB file: "Upload 2 executed in 0:00:06.436079" and the 158KB file: "Upload 2 executed in 0:00:02.330972".

Probably it is the problem of internet provider. I'll check it on faster upload in few days.
