### ISSUE TITLE
🐛 [firebase_analytics] Impossible to use on web when loaded asynchronously

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [firebase/flutterfire#5293]
## Bug report

There are some cases where you are **required** to load the Firebase analytics JS library **asynchronously** (enforced by GDPR).

The way we work with it is adding the 

```
<script src="https://www.gstatic.com/firebasejs/7.24.0/firebase-analytics.js"></script>
```

script **only** when users have consented to tracking (via Google Tag Manager).

However, in most of the cases, this **breaks** `firebase_analytics`. This is because the JS library has to be loaded before `main.dart.js` is executed. 

The error that appears in that case is the following:

```
TypeError: Cannot read property 'analytics' of undefined
    at Object.analytics$ [as analytics] (http://localhost:50937/packages/firebase/src/top_level.dart.lib.js:110:102)
    at new firebase_analytics_web.FirebaseAnalyticsWeb.new (http://localhost:50937/packages/firebase_analytics_web/firebase_analytics_web.dart.lib.js:56:64)
    at Function.registerWith (http://localhost:50937/packages/firebase_analytics_web/firebase_analytics_web.dart.lib.js:19:82)
```

And at that point, it is impossible to use analytics in that session.

**Comment by darshankawar** [comment]
@creativecreatorormaybenot Hi, Can you confirm if this is still a valid issue using latest plugin version and stable version (3.0.3) ?

**Comment by creativecreatorormaybenot** [comment]
Hi @darshankawar - I can unfortunately not confirm this at this moment as I am currently not working with Flutter web.

I worked around this issue using the solution I describe in https://stackoverflow.com/a/66589887/6509751. This should be easy to reproduce by writing some quick JS code that loads in:

```js
<script src="https://www.gstatic.com/firebasejs/7.24.0/firebase-analytics.js"></script>
```

After a delay (and opting out of the default import by the Firebase Analytics plugin). Note that you might not want to use `7.24.0` but the current version.

**Comment by Lyokone** [comment]
Since we have updated the way to load Firebase on Web I'll close this.
