### ISSUE TITLE
🐛 [firebase_messaging] [v.9.1.0] [Android] Background messages not working properly. RemoteMessage.RemoteNotification object is null

### ISSUE THREAD

**Issue by bohdan1krokhmaliuk** [firebase/flutterfire#5488]
## Bug report

**Describe the bug**
Wrong PN behavior. Notifications emitted when app was in the background are not returned on `FirebaseMessaging.instance.getInitialMessage()` or `FirebaseMessaging.onMessageOpenedApp` if app was closed and then clicked on notification. So looks like background messages are not handled when the app was closed. Or closed and opened again.

PN - Push Notification

### Steps to reproduce

[1] Steps to reproduce the behavior:

1. Open an app which is using PN
2. Put it in the background (by clicking on the home button for example)
3. Emit push notification.
4. Clean memory (or close the app so it is no longer in the background)
5. Click on PN
6. App gets opened but neither `FirebaseMessaging.onMessageOpenedApp` nor `FirebaseMessaging.instance.getInitialMessage()` emits a Remote message - so app doesn't know where to navigate.

[1] Other steps to reproduce the behavior:

1. Open an app which is using PN
2. Put it in the background (by clicking on the home button for example)
3. Emit push notification.
4. Clean memory (or close the app so it is no longer in the background)
5. Open the app again
5. Click on PN
6. App gets opened but neither `FirebaseMessaging.onMessageOpenedApp` nor `FirebaseMessaging.instance.getInitialMessage()` emits a Remote message - so app doesn't know where to navigate.

### Expected behavior

After point 5 in steps to reproduce[1], `FirebaseMessaging.instance.getInitialMessage()` should return `RemoteMessage`. And after point 5 in steps to reproduce[2], `FirebaseMessaging.onMessageOpenedApp` should emmit `RemoteMessage`.

**Comment by markusaksli-nc** [comment]
Hi @bohdan1krokhmaliuk 
I was not able to reproduce the issue with the steps you mentioned (both variations) using the official example with `firebase_messaging: ^9.1.0`
<details>
 <summary>flutter doctor -v</summary>

```console
[√] Flutter (Channel master, 2.1.0-13.0.pre.294, on Microsoft Windows [Version 10.0.19041.867], locale et-EE)
    • Flutter version 2.1.0-13.0.pre.294 at C:\Development\flutter_master
    • Framework revision a603714610 (26 hours ago), 2021-03-28 03:54:02 -0700
    • Engine revision b5e15d055d
    • Dart version 2.13.0 (build 2.13.0-162.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7199119\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7199119
    • Flutter plugin version 54.0.1
    • Dart plugin version 201.9335
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\203.7717.56
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (4 available)
    • SM G950F (mobile) • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.867]
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 89.0.774.57

• No issues found!
```
</details>

As mentioned in the documentation https://firebase.flutter.dev/docs/messaging/usage#receiving-messages when the app is killed on Android the notifications to be received or listened to.
Did I read correctly that you are not able to get the initial message or `onMessageOpenedApp` if you just close the app normally and tap the notification?
Thank you

**Comment by bohdan1krokhmaliuk** [comment]
@markusaksli-nc  yes, if the notification was received when app was in the background mode, and then app was closed, exactly that notification will not produce any remote message. If the notification was received when the app was closed it will produce RemoteMessage.

I didn't remove below code from AndroidManifest.xml, can it be the reason of that problems? If I remove that, then all messages which are sent with `click_action: 'FLUTTER_NOTIFICATION_CLICK'` will not redirect to app at all. So I left that in order to keep push notifications working in old versions of the app.

```
<intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
</intent-filter>
```

**Comment by markusaksli-nc** [comment]
That should no longer be necessary. The intent filter would still be there in the old versions of the app even if you remove it for your next update so it shouldn't matter?

I tried adding it in and specifying the click action of the notification but still didn't run into this.

Where are you listening to the `onMessageOpenedApp` stream or calling `getInitialMessage`?

You could also try just running the official example code to see if this is a code issue.

**Comment by bohdan1krokhmaliuk** [comment]
@markusaksli-nc Yes it no longer needed, but if I send push notification with `click_action: 'FLUTTER_NOTIFICATION_CLICK'` to app with firebase_messaging version 9 and remove that intent-filter, click on notification will do nothing at all. The app is not even opened. If I remove `click_action: 'FLUTTER_NOTIFICATION_CLICK'` from push notification itself app will open and emmit RemoteMessage.

Please check these points:

1. App with firebase_messaging v7 + with `click_action: 'FLUTTER_NOTIFICATION_CLICK'` + intent filter: in PN works fine (expected)
2. App with firebase_messaging v7 + with `click_action: 'FLUTTER_NOTIFICATION_CLICK'` + no intent filter: in PN works bad (expected)
3. App with firebase_messaging v9 + without `click_action: 'FLUTTER_NOTIFICATION_CLICK'` + No intent filter:  in PN works fine (expected)
4. App with firebase_messaging v9 + with `click_action: 'FLUTTER_NOTIFICATION_CLICK'` in PN + No intent filter:  doesn't work, app receives PN but doesn't redirect anywhere, even app is not opened (not expected)
5. App with firebase_messaging v9 + with `click_action: 'FLUTTER_NOTIFICATION_CLICK'` in PN + intent filter: PN are redirecting to app and working as expected except this only edge case when PN was received during app in background and opened when app is closed (not expected)

**Comment by bohdan1krokhmaliuk** [comment]
This is the video how it works:
1. app is in background and notification(received during app in background) clicked - it works as expected
2. app is closed and notification(received during app closed) clicked - it works as expected
3. app is closed and notification(received during app in background) clicked - it works not as expected

https://user-images.githubusercontent.com/59435984/112849963-4029ed00-90b2-11eb-83ea-14cc92b0a45b.mov

**Comment by markusaksli-nc** [comment]
Could you try the same with the official example to make sure this isn't just an implementation issue?

**Comment by markusaksli-nc** [comment]
I take it that the official example worked for this edge case then? 

The error you got is because you are using the deprecated FCM HTTP API to send your messages. Officially it is reccommended to use the v1 FCM HTTP API Please take a look at https://github.com/FirebaseExtended/flutterfire/issues/4611#issuecomment-757917877

There should be no special implementation needed here, since it should work out of the box as with the official example unless you are initializing the streams wrong.

**Comment by bohdan1krokhmaliuk** [comment]
If I am initializing streams wrong, why I don't have same issue for IOS? and also why it works for all normal situations for android except when push notific received in background and app killed?

I have a specific service which resolves messaging, when app is opened it initializes streams and RemoteMessages are intercepted. As soon as it is intercepted app navigates to specific screen. 
On firebase messaging v7 it worked fine for all occassions, then I updated to v9 and now it also works pretty fine, except this one edge case. Implementation of my service was not changed, I made only updates on breaking changes of firebase messaging v9.

**Comment by markusaksli-nc** [comment]
I meant if the streams are being listened to in the wrong place but it's hard to say. What would really help diagnose the issue here is a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) since we can't reproduce this with the official example.

**Comment by darshankawar** [comment]
Verified this on latest stable using above project and I see `notification` object being `null` when app is closed.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.4 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision b1395592de (7 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)    

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
	  SM A260G (mobile)            • 5200763ebcfa861f • android-arm    • Android
      8.1.0 (API 27)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 14.4.1
    • macOS (desktop)           • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 1 category.

```

</details>

**Comment by petchgabriel** [comment]
> @markusaksli-nc Yes it no longer needed, but if I send push notification with `click_action: 'FLUTTER_NOTIFICATION_CLICK'` to app with firebase_messaging version 9 and remove that intent-filter, click on notification will do nothing at all. The app is not even opened. If I remove `click_action: 'FLUTTER_NOTIFICATION_CLICK'` from push notification itself app will open and emmit RemoteMessage.
> 
> As the message may be sent to any app version - I keep this `click_action: 'FLUTTER_NOTIFICATION_CLICK'` and intent filter is more like workaround (look point 4)
> 
> Please check these points:
> 
> 1. App with firebase_messaging v7 + with `click_action: 'FLUTTER_NOTIFICATION_CLICK'` + intent filter: in PN works fine (expected)
> 2. App with firebase_messaging v7 + with `click_action: 'FLUTTER_NOTIFICATION_CLICK'` + no intent filter: in PN works bad (expected)
> 3. App with firebase_messaging v9 + without `click_action: 'FLUTTER_NOTIFICATION_CLICK'` + No intent filter:  in PN works fine (expected)
> 4. App with firebase_messaging v9 + with `click_action: 'FLUTTER_NOTIFICATION_CLICK'` in PN + No intent filter:  doesn't work, app receives PN but doesn't redirect anywhere, even app is not opened (not expected)
> 5. App with firebase_messaging v9 + with `click_action: 'FLUTTER_NOTIFICATION_CLICK'` in PN + intent filter: PN are redirecting to app and working as expected except this only edge case when PN was received during app in background and opened when app is closed (not expected)

I am facing the exact same issue like you after I migrated to null safety.

**Comment by congtieniuh** [comment]
Having the same issues in Android.

**Comment by russellwheatley** [comment]
Hey @bohdan1krokhmaliuk, I'm happy to debug, but do you mind updating your code sample? I've just ran your project and I'm not receiving popup notifications with the app in the background _or foreground_ (although I can see the notifications coming through the logs).

**Comment by bohdan1krokhmaliuk** [comment]
@russellwheatley Sorry, I have no time for that now. If you are pushing notifications from the app - there is a delay for 2 seconds, so If you put the app into background just after you requested a new push - you should see a push pops up. 

If this doesn't work for you - feel free to emit pushes from postman or any other tool you can use. Server key is present into the app code.

**Comment by russellwheatley** [comment]
The problem isn't receiving the notification, the PN UI isn't being triggered so I'm unable to verify.

**Comment by bohdan1krokhmaliuk** [comment]
Hi @russellwheatley, just launched  the project again and everything works fine. When you generate a push notification please put app to the background so within 2 seconds push notificaiton will be emmited. Make sure you are using android device or simulator as the issue originally created for android platform, also I didn't provide APNS key for Apple side.

**Comment by alexlovar** [comment]
Hi, i have a similar issue but  when i tap in the notification with app in foreground, plugin version ^9.1.3, 
i need to manage notification click event, but onforeground tap message does not work. 
on arrived msg  i get this in the console:
` "Accessing hidden method Landroid/os/WorkSource;->add(I)Z (greylist,test-api, reflection, allowed)"`
  , and FirebaseMessaging.onMessage.listen is not triggered, my onmessage function only have a print(¨msg¨)
  i try the official example, but the same  thing happens there is not event triggered on notification tap.
any one knows how i can solve?
thank you!
