### ISSUE TITLE
🐛 [firebase_storage] [object Object] as the storage bucket name in Flutter for Web

### ISSUE THREAD

**Issue by julianschmuckli** [firebase/flutterfire#5684]
## Bug report

The bug only occurs for the web version in flutter with the package `firebase_storage: ^8.0.2`. It works well on iOS and Android.

```dart
var response = await (FirebaseStorage.instance
          .ref() // Also tried here with .refFromURL("gs://xxx.appspot.com")
          .child("profile/" + uid + "/images/" + nameId + "_blur_1000.jpg"))
          .getDownloadURL();
```

If I want to generate a download URL from the API, it will not decode somehow the object correctly in Flutter and request it wrongly to the Firebase Storage server.

![Request to the Firebase Storage server](https://user-images.githubusercontent.com/6286544/113776103-d18c0580-9729-11eb-8245-f1488c15e680.png)

As a result, I then get following error message.

```
{
  "error": {
    "code": 404,
    "message": "Not Found.  Could not access bucket [object Object]",
    "status": "ACCESS_BUCKET"
  }
}
```

### Expected behavior

Actually it should load the image with the correct path, as it would already happen for iOS and Android.

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.3 20E5224a darwin-x64, locale en-CH)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.0)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
...
- firebase 9.0.1 [http http_parser js]
- firebase_analytics_platform_interface 1.1.0 [flutter meta]
- firebase_analytics_web 0.2.0+1 [firebase firebase_analytics_platform_interface flutter flutter_web_plugins meta]
- firebase_auth_platform_interface 4.0.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.0.4 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_core_web 1.0.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.0.0 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 2.1.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 1.0.4 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 2.0.1 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 1.0.3 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_plugin_android_lifecycle 2.0.0 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
...
```

</details>

---

**Comment by darshankawar** [comment]
@julianschmuckli 
I tried the official plugin [example](https://pub.dev/packages/firebase_storage/example) on latest master and was able to get the downloadURL properly.

```
Future<void> _downloadLink(firebase_storage.Reference ref) async {
    final link = await FirebaseStorage.instance.ref().child('playground/').child('/some-image.jpg').getDownloadURL();
    print(link.toString());

    await Clipboard.setData(ClipboardData(
      text: link,
    ));
```
ex: https://firebasestorage.googleapis.com/v0/b/triage-79c7c.appspot.com/o/playground%2Fsome-image.jpg?alt=media&token=ff58faab-5a95-4008-b2a6-d27041069a47

<img width="1079" alt="Screenshot 2021-04-07 at 3 57 47 PM" src="https://user-images.githubusercontent.com/67046386/113852428-2f682e00-97ba-11eb-8e87-9285a43a7c40.png">

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.496, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.1.0-13.0.pre.496 at
      /Users/dhs/documents/fluttersdk/flutter
    • Framework revision 026ee9756c (35 minutes ago), 2021-04-06 21:52:35 -0700
    • Engine revision 92f4dfb048
    • Dart version 2.13.0 (build 2.13.0-208.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 14.4.1
    • macOS (desktop)           • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 1 category.

```

</details>

If this doesn't represent your case, can you provide a complete minimal reproducible code sample and steps to replicate the same ?

**Comment by julianschmuckli** [comment]
@darshankawar
So I have used almost the same code like you. You have tested in Chrome, right?
When I execute the code from the issue above I get the 404 error from the server:
![image](https://user-images.githubusercontent.com/6286544/113856884-1e132780-97a2-11eb-865b-b93dddefdcf6.png)

And as you can see, as the bucket it will use [object Object] and not the defined bucket as a string.

**Comment by darshankawar** [comment]
@julianschmuckli 
Yes, I verified on chrome. Can you try the plugin official example and see if you get same issue ? https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_storage/firebase_storage/example,  because I tried again and works as expected.

**Comment by julianschmuckli** [comment]
@darshankawar 
Okay I have tested the example now, and it does it also worked for me, and it chooses the correct bucket. I have tried now to print the reference and both actually show the same:

React Native Bucket
Reference(app: [DEFAULT], fullPath: playground/some-image.jpg)

My bucket:
Reference(app: [DEFAULT], fullPath: profile/xxxx/images/xxxx_blur_1000.jpg)

Although I still tries to fetch the [object Object] bucket.

**Comment by julianschmuckli** [comment]
I also tried the `reference.bucket` attribute and it gives me the correct bucket in the console:
```dart
Reference reference = FirebaseStorage.instance
          .ref()
          .child("profile/" + uid + "/images/" + nameId + "_blur_1000.jpg");

print(reference.bucket);
```

**Comment by darshankawar** [comment]
@julianschmuckli 
Thanks for these details. So If I understand the scenario correctly, from the example, we first upload a file or a string text with which the task / operation is successful. Once that is done, we then tap on `get download url` using which we get the link properly as we saw. 
Coming to your issue, after generating the download url, it is followed with the error you get ?

`[object Object] bucket.` ?

**Comment by julianschmuckli** [comment]
@darshankawar 
Exactly, so if you compare the two urls, which was obviously called with the same method, you see that in my project it just calls the [object Object]

### Example project: 
- expected bucket: react-native-firebase-testing.appspot.com
- requested bucket: react-native-firebase-testing.appspot.com, 

**Requested URL to get the download URL:**
`https://firebasestorage.googleapis.com/v0/b/react-native-firebase-testing.appspot.com/o/playground%2Fsome-image.jpg`

**Image output URL is then correct:**
`https://firebasestorage.googleapis.com/v0/b/react-native-firebase-testing.appspot.com/o/playground%2Fsome-image.jpg?alt=media&token=49de7369-85fe-4e75-8774-4835f3889c88`

### My project
- expected bucket: xxxx.appspot.com
- requested bucket: [object Object], 

**Requested URL to get the download URL:**
`https://firebasestorage.googleapis.com/v0/b/%5Bobject%20Object%5D/o/profile%2Fxxx%2Fimages%2Fxxx_blur_1000.jpg`

Image output URL can then not be received, since it is referencing to the wrong bucket `%5Bobject%20Object%5D` which is equal to `[object Object]`

I hope that you see now what I mean?

**Comment by darshankawar** [comment]
Keeping this issue open for further investigation, since, using the official example, the issue isn't replicable.

**Comment by russellwheatley** [comment]
Hey @julianschmuckli, do you mind pasting a code sample of how to replicate? I've read the thread and I'm still not sure where to expect this error. I've also tested the example code and it works fine. Thanks.

**Comment by julianschmuckli** [comment]
Hi @russellwheatley,

well there isn't actually more than I can present. I have checked my configurations in the index.html file and they look fine:
```javascript
var firebaseConfig = {
      apiKey: "AIzaSyDYaaaa",
      authDomain: "xxx.firebaseapp.com",
      projectId: "xxx",
      storageBucket: "xxx.appspot.com",
      messagingSenderId: "1234567890",
      appId: "1:47874aaaaaaa:web:9baaaaaaaa",
      measurementId: "G-9NSaaaaaa"
    };
    // Initialize Firebase
    firebase.initializeApp(firebaseConfig);
```
Everywhere I have pasted three x (xxx), there is my project name and bucket name since I'm only using one bucket for my project.

And I'm loading there the following CDNs above:
```html
  <!-- The core Firebase JS SDK is always required and must be listed first -->
  <script src="https://www.gstatic.com/firebasejs/8.3.2/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-firestore.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-messaging.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-storage.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-auth.js"></script>
```

I'm not sure if it is a version problem?

**Comment by russellwheatley** [comment]
@julianschmuckli, I don't know I'm afraid. To rule out the possibility of versions, I'd follow the documentation for recommended Firebase web sdk versions as shown [here](https://firebase.flutter.dev/docs/storage/overview#3-web-only-add-the-sdk). 

If that doesn't fix your issue, could you please provide a [minimum reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that I can run, please? Even if I'm not able to reproduce, it's worth understanding what leads to your problem. Someone else may be able to reproduce for example.

**Comment by julianschmuckli** [comment]
Hi @russellwheatley,

I'm afraid that I can't let you show you the complete source code. I mean actually I do nothing with the instance during the runtime at only that point, where it tries to fetch the download URL as you can see in the initial issue comment.

I have tried to debug the code a bit and it looks like that it has some problems when trying to use the reference. During the runtime it calls multiple times the NativeJSObject which contains a [object Object] instance. 
![image](https://user-images.githubusercontent.com/6286544/114581287-def04500-9c7f-11eb-9447-2770adb94f6b.png)

And this reference will be used as well for the download URL here: 
![image](https://user-images.githubusercontent.com/6286544/114581358-edd6f780-9c7f-11eb-8307-42e17bce28e2.png)

At somepoint it comes to the creating instance, where it uses the credentials provided by the index.html file, right? So this means this method then in Dart. But during that it looks like, that it fetched the right bucket:
![image](https://user-images.githubusercontent.com/6286544/114581768-49a18080-9c80-11eb-9350-a72c26f95d89.png)

Can you maybe do something with this or do you need a specific analysis for a certain method or class?

Thank you very much.

**Comment by russellwheatley** [comment]
Hi @julianschmuckli, I don't want your source code, just the [smallest reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) to confirm and thus fix the bug. Thanks.
