### ISSUE TITLE
🐛 [flutter_performance] Requests not collected for gRPC

### ISSUE THREAD

**Issue by steeling** [firebase/flutterfire#6145]
Does the flutter_performance plugin record requests for gRPC? What about grpc-web? 

What if I'm hitting  an ip-based domain over HTTP? 90% of my requests are to a static IP address over gRPC (on device) and grpc-web (on web), however I'm seeing 0 metrics in the firebase console.

Is this a known deficit or is there something I can do to fix this?

**Comment by russellwheatley** [comment]
Hey @steeling, the Firebase performance plugin was reworked at the tail end of 2021. Not sure if the metrics are now appearing in your console?
