### ISSUE TITLE
🐛 [cloud_firestore] Hot reload breaks local emulator on web

### ISSUE THREAD

**Issue by Vluf** [firebase/flutterfire#6216]
## Bug report

When configuring the emulator on web, a hot reload crashes Firestore because its settings cannot be changed after initialization.

I have tried numerous ways to try and detect if Firebase was already initialized, but I cannot seem to find a way to get it properly fixed. It also feels very hacky.

I'm simply using the configuration for the emulator as described in the [docs](https://firebase.flutter.dev/docs/firestore/usage#emulator-usage).

Possibly the docs just need to be a bit more precise on how to implement it? Furthermore, the usage of the emulator for firestore is quite different from the simple `useEmulator()` functions for the other packages.

### Steps to reproduce

1. Create a new flutter project with web support
2. Install cloud_firestore
3. Set up the emulators
4. Configure the flutter app to use the emulator
5. Make some hot reload changes, notice the "Firestore has already been started and its settings can no longer be changed. You can only modify settings before calling any other methods on a Firestore object."

### Expected behavior

A hot reload should simply accept my settings again

### Sample project

https://github.com/Vluf/cloud_firestore_web_emulator_bug

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19042.985], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
[√] VS Code (version 1.56.0)
[√] VS Code, 64-bit edition (version 1.26.1)
[√] Connected device (2 available)

! Doctor found issues in 1 category.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.12.2
Flutter SDK 2.0.4
cloud_firestore_web_emulator_bug 1.0.0+1

dependencies:
- cloud_firestore 2.2.0 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.3
- firebase_core 1.2.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- cloud_firestore_platform_interface 5.1.0 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.1.0 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- fake_async 1.2.0 [clock collection]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- path 1.8.0
- plugin_platform_interface 2.0.0 [meta]
- sky_engine 0.0.99
- source_span 1.8.0 [charcode collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the detailed report and code sample. Replicable using latest stable and [latest](https://pub.dev/packages/cloud_firestore/install) plugin version.

`Firestore has already been started and its settings can no longer be changed. You can only modify settings before calling any other methods on a Firestore object.`


<details>
<summary> flutter doctor -v </summary>

```
dhs@Dhss-MacBook-Pro ncflutter % flutter doctor -v
[✓] Flutter (Channel stable, 2.2.0, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.0 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision b22742018b (9 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • AOSP on IA Emulator (mobile) • emulator-5554
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 90.0.4430.212

• No issues found!



```

</details>

**Comment by darshankawar** [comment]
@Vluf 


> Furthermore, the usage of the emulator for firestore is quite different from the simple `useEmulator()` functions for the other packages.

An issue is opened to track this, https://github.com/FirebaseExtended/flutterfire/issues/5224

**Comment by darshankawar** [comment]
The issue may be related to https://github.com/FirebaseExtended/flutterfire/issues/3935

**Comment by devj3ns** [comment]
I can confirm that this issue still exists using the latest version of `cloud_firestore` (2.3.0) and `firebasejs` (8.6.1 & 8.7.0).

**Comment by KristianBalaj** [comment]
This is still an issue using the `cloud_firestore: 2.5.0` and the `8.6.1` of the `firebase-firestore.js`.

Here is the error with its stacktrace:

<details> 
<summary>console error</summary> 

```console
FirebaseError: Firestore has already been started and its settings can no longer be changed. You can only modify settings before calling any other methods on a Firestore object.
    at new xr (https://www.gstatic.com/firebasejs/8.6.1/firebase-firestore.js:1:48453)
    at yp.rp._setSettings (https://www.gstatic.com/firebasejs/8.6.1/firebase-firestore.js:1:265710)
    at https://www.gstatic.com/firebasejs/8.6.1/firebase-firestore.js:1:308734
    at Sg.useEmulator (https://www.gstatic.com/firebasejs/8.6.1/firebase-firestore.js:1:309580)
    at firestore.Firestore._fromJsObject.useEmulator (http://localhost:55876/packages/cloud_firestore_web/src/interop/utils/utils.dart.lib.js:221:28)
    at cloud_firestore_web.FirebaseFirestoreWeb.new.useEmulator (http://localhost:55876/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:747:34)
    at cloud_firestore.FirebaseFirestore.__.useFirestoreEmulator (http://localhost:55876/packages/cloud_firestore/cloud_firestore.dart.lib.js:1378:26)
    at main (http://localhost:55876/packages/bottleshopdeliveryapp/main_web_dev.dart.lib.js:99:50)
    at main.next (<anonymous>)
    at http://localhost:55876/dart_sdk.js:37403:33
    at _RootZone.runUnary (http://localhost:55876/dart_sdk.js:37274:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:55876/dart_sdk.js:32530:29)
    at handleValueCallback (http://localhost:55876/dart_sdk.js:33057:49)
    at Function._propagateToListeners (http://localhost:55876/dart_sdk.js:33095:17)
    at _Future.new.[_completeWithValue] (http://localhost:55876/dart_sdk.js:32943:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:55876/dart_sdk.js:32964:35)
    at Object._microtaskLoop (http://localhost:55876/dart_sdk.js:37526:13)
    at _startMicrotaskLoop (http://localhost:55876/dart_sdk.js:37532:13)
    at http://localhost:55876/dart_sdk.js:33303:9
```

</details>


Following are the `package.yaml` firebase packages used in the project:

<details>
<summary>firebase packages versions</summary>

```
  firebase_core: ^1.5.0
  firebase_messaging: ^10.0.5
  firebase_auth: ^3.0.2
  cloud_firestore: ^2.5.0
  firebase_crashlytics: ^2.2.0
  firebase_analytics: ^8.3.0
  firebase_storage: ^10.0.2
  cloud_functions: ^3.0.1
```

</details>


Additionally, here is the firebase related code in the main function of the project:

<details>
<summary>code snippet</summary>

```dart
.
.
.
  await Firebase.initializeApp();

  await FirebaseAuth.instance
      .useAuthEmulator('localhost', AppEnvironment.devFirebaseAuthPort);
  final host = defaultTargetPlatform == TargetPlatform.android
      ? '10.0.2.2'
      : 'localhost';
  FirebaseFirestore.instance
      .useFirestoreEmulator(host, AppEnvironment.devFirestorePort);
  FirebaseFunctions.instance.useFunctionsEmulator(
    'localhost',
    AppEnvironment.devFunctionsPort,
  );
.
.
.
```

</details>

**Comment by linxydmhg** [comment]
Same problem, I solved it like this
```
main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  FirebaseFunctions.instance.useFunctionsEmulator('localhost', 5001);
  try {
    FirebaseFirestore.instance.useFirestoreEmulator('localhost', 8080);
  } catch (e) {
    print(e);
  }
  runApp(MyApp());
}
```

**Comment by Invectys** [comment]
I have the same problem

**Comment by jbryanh** [comment]
If this is helpful in any way, in my project, I've been restarting for a couple days with no issues, and then suddenly it started happening out of the blue.  In my case:

Main: 
`void main() {
  WidgetsFlutterBinding.ensureInitialized();
  SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp, DeviceOrientation.portraitDown]).then((_) {
    var configuredApp = AppConfig(
      appTitle: '...',
      photoLocation: '...',
      child: App(),
    );
    setupLocator();
    Stripe.init(...);
    return runApp(configuredApp);
  });
}`

App:
`class App extends StatelessWidget {
  final Future<FirebaseApp> _initialization = Firebase.initializeApp();

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
      future: _initialization,
      builder: (context, snapshot) {
        if (snapshot.hasError) {
          return LoadingStart();
        }
        if (snapshot.connectionState == ConnectionState.done) {
          FirebaseFirestore.instance.settings = const Settings(persistenceEnabled: false);
          return MultiProvider(
              providers: [...],
              builder: (context, snapshot) {
                return MyApp();
              });
        }
        return LoadingStart();
      },
    );
  }
}`

`          FirebaseFirestore.instance.settings = const Settings(persistenceEnabled: false);
`

My log points me to the FutureBuilder in App re-initializing:  Firebase.initializeApp();  

All this is probably obvious to you, but I figure anything that might help or trigger something.

**Comment by muddi900** [comment]
@jbryanh My app initializes Firebase in `main()`. The issue still occurs.

**Comment by jbryanh** [comment]
> @jbryanh My app initializes Firebase in `main()`. The issue still occurs.

I figured I'd share my configuration since I didn't start getting the error on restarts until I got a User.  In my migration from mobile to web, I had to work through authentication issues for a couple days, I was never restarting with a User...so I could restart with no issues.  As soon as I was reloading with a User, I started to get the issues.  Maybe the User isn't relevant.  Just figured I'd share the experience.

Additionally, I get the error on hot reload (cmd-s) and restart (Android Studio Play Button)...which feel like the same behavior in Web anyway, I'm not sure.  I have to stop the chrome emulator and restart entirely every time.

**Comment by muddi900** [comment]
Yeah the web does not have Hot Reload. It's hot restart only.

**Comment by jbryanh** [comment]
I removed my answer here, as my problem isn't the same as this thread, though the error was the same.  In my case, I set 

`FirebaseFirestore.instance.settings = const Settings(persistenceEnabled: false);`

For mobile this is fine, but for web, this creates the error.  Making this conditional only for mobile fixed my issue.

**Comment by Levi-Lesches** [comment]
Can confirm the issue still occurs with the latest versions: `cloud_firestore: ^3.1.6` and `firebasejs/8.10.0`. @darshankawar, any updates? From what I can tell: 
- Emulator initialization works the first time, but after using Firestore to get data, subsequent restarts break.
- But this is happening on a hot _restart_ (not reload), which should start back at `main`, reproducing the circumstances of the first `flutter run`.
- With the new Dart-only initialization, I was able to clear all Firebase-related code from `web/index.html`, but this error still happens. 
- `FirebaseAuth.instance.useAuthEmulator` _does_ work
- Wrapping `FirebaseFirestore.instance.useFirestoreEmulator` in a try/catch seems to be a valid workaround since the first call does succeed, and future calls are not necessary.

**Comment by muddi900** [comment]
@Levi-Lesches How does the try catch work? The error is thrown in the browser. Dart does not register it as an error.

**Comment by Levi-Lesches** [comment]
Does the above code snippet not work? Are you able to print `code`? Assuming you follow the instructions for Dart-only initialization on web over at firebase.flutter.dev, and you're on the latest versions of flutter and all the firebase plugins, the error should be passed through to Dart. As I noted, it's not a `FirebaseException` like it should be, but rather a (Dart) class called `JavaScriptObject` that has the same properties (at least on Chrome). If you try catching it with `on`, it won't work, you have to use a blanket-`catch`. 

Also, flutter isn't the best at catching asynchronous errors, so make sure you're on the latest version of flutter and that your function is being awaited properly if you made it async.

**Comment by muddi900** [comment]
@Levi-Lesches 

It works like a charm. Thank you, it would save me hours.
