### ISSUE TITLE
🐛 [firebase_app_check] Does not work on web

### ISSUE THREAD

**Issue by enri90** [firebase/flutterfire#6310]
## Bug report
Error Plugin App Check Firebase

flutter run -no-sound-null-safety not work

firebase_app_check_web.dart 45:35     nullCheck

[ERROR] C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 236:49      throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 518:63  nullCheck
packages/firebase_app_check_web/firebase_app_check_web.dart 45:35                                                              <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                _async
packages/firebase_app_check_web/firebase_app_check_web.dart 45:9                                                               <fn>
packages/firebase_core/src/internals.dart 86:21                                                                                guard
packages/firebase_app_check_web/src/internals.dart 14:10                                                                       guard
packages/firebase_app_check_web/firebase_app_check_web.dart 44:12                                                              activate
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                _async
packages/firebase_app_check_web/firebase_app_check_web.dart 43:24                                                              activate
packages/firebase_app_check/src/firebase_app_check.dart 46:22                                                                  activate
packages/booking_lessons_pets/main.dart 31:37                                                                                  <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                <fn>

---

### Flutter doctor

<details><summary>Click To Expand</summary>

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Versione 10.0.19042.985], locale it-IT)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.56.2)
[√] Connected device (2 available)
</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

Dart SDK 2.13.1
Flutter SDK 2.2.1
test 1.0.0+1

dependencies:
- async 2.6.1 [meta collection]
- cached_network_image 3.0.0 [flutter flutter_cache_manager octo_image]
- cloud_firestore 2.2.0 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- cloud_functions 1.1.0 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]     
- cupertino_icons 1.0.3
- email_validator 2.0.1
- firebase_analytics 8.1.0 [firebase_analytics_platform_interface firebase_analytics_web firebase_core flutter meta]
- firebase_app_check 0.0.1+1 [firebase_app_check_platform_interface firebase_app_check_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 1.2.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.2.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_performance 0.7.0+3 [firebase_core flutter]
- firebase_storage 8.1.0 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_linkify 5.0.2 [flutter linkify]
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]
- flutter_riverpod 0.14.0+3 [collection flutter meta riverpod state_notifier]
- focused_menu 1.0.5 [flutter]
- freezed_annotation 0.14.2 [collection json_annotation meta]
- image_picker 0.7.5+3 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface image_picker_for_web]
- image_picker_for_web 2.0.0 [image_picker_platform_interface meta flutter flutter_web_plugins]
- intl 0.17.0 [clock path]
- json_annotation 4.0.1
- json_serializable 4.1.2 [analyzer build build_config collection json_annotation meta path source_gen]
- line_icons 2.0.1 [flutter]
- logger 1.0.0
- lottie 1.0.1 [archive characters charcode collection flutter logging meta path vector_math]
- meta 1.3.0
- mime_type 1.0.0
- responsive_builder 0.4.1 [flutter]
- skeleton_text 3.0.0 [flutter]
- syncfusion_flutter_calendar 19.1.64 [flutter timezone syncfusion_flutter_core syncfusion_flutter_datepicker intl]
- syncfusion_flutter_core 19.1.64 [vector_math flutter]
- syncfusion_flutter_datepicker 19.1.64-beta [flutter intl syncfusion_flutter_core]
- syncfusion_localizations 19.1.64 [flutter intl syncfusion_flutter_core]
- timelines 0.1.0 [flutter]
- universal_platform 1.0.0-nullsafety
- url_launcher 6.0.4 [flutter url_launcher_platform_interface url_launcher_linux url_launcher_macos url_launcher_windows url_launcher_web]

dev dependencies:
- build_runner 1.12.2 [args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style glob graphs http_multi_server io js logging meta mime path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- freezed 0.14.1+2 [analyzer build build_config meta source_gen freezed_annotation]

transitive dependencies:
- _fe_analyzer_shared 21.0.0 [meta]
- analyzer 1.5.0 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml pedantic]
- archive 3.1.2 [crypto path]
- args 2.1.0
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.0.1 [analyzer async convert crypto glob logging meta path]
- build_config 0.4.7 [checked_yaml json_annotation meta path pubspec_parse yaml]
- build_daemon 2.1.10 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.2 [analyzer build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 6.1.12 [async build build_config build_resolvers collection convert crypto glob graphs logging meta path package_config pedantic pool timing watcher yaml]
- built_collection 5.0.0
- built_value 8.0.0 [built_collection collection fixnum]
- characters 1.1.0
- charcode 1.2.0
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- cli_util 0.3.0 [meta path]
- clock 1.1.0
- cloud_firestore_platform_interface 5.1.0 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.1.0 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- cloud_functions_platform_interface 5.0.5 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.0.7 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 3.7.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- convert 3.0.0 [typed_data]
- crypto 3.0.0 [collection typed_data]
- dart_style 2.0.0 [analyzer args path pub_semver source_span]
- fake_async 1.2.0 [clock collection]
- ffi 1.0.0
- file 6.1.0 [meta path]
- firebase 9.0.1 [http http_parser js]
- firebase_analytics_platform_interface 2.0.1 [flutter meta]
- firebase_analytics_web 0.3.0+1 [firebase firebase_analytics_platform_interface flutter flutter_web_plugins meta]
- firebase_app_check_platform_interface 0.0.1+1 [firebase_core flutter meta plugin_platform_interface]
- firebase_app_check_web 0.0.1+1 [firebase_app_check_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 4.2.3 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.1.3 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 2.1.0 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 1.1.0 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- fixnum 1.0.0
- flutter_blurhash 0.6.0 [flutter meta pedantic]
- flutter_cache_manager 3.0.1 [clock collection file flutter http image path path_provider pedantic rxdart sqflite uuid]
- flutter_plugin_android_lifecycle 2.0.1 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- glob 2.0.1 [async collection file path pedantic string_scanner]
- graphs 1.0.0
- http 0.13.0 [http_parser meta path pedantic]
- http_multi_server 3.0.1 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 3.0.1 [archive meta xml]
- image_picker_platform_interface 2.0.1 [flutter meta http plugin_platform_interface]
- io 1.0.0 [meta path string_scanner]
- js 0.6.3
- linkify 4.0.0
- logging 1.0.0
- matcher 0.12.10 [stack_trace]
- mime 1.0.0
- octo_image 1.0.0+1 [flutter flutter_blurhash]
- package_config 2.0.0 [path]
- path 1.8.0
- path_provider 2.0.1 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 2.0.0 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.0 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.11.0
- petitparser 4.0.2 [meta]
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- pool 1.5.0 [async stack_trace]
- process 4.1.0 [file path platform]
- pub_semver 2.0.0 [collection]
- pubspec_parse 1.0.0 [checked_yaml collection json_annotation pub_semver yaml]
- riverpod 0.14.0+3 [collection freezed_annotation meta state_notifier]
- rxdart 0.26.0
- shelf 1.0.0 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.0 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.0.0 [analyzer async build dart_style glob meta path pedantic source_span]
- source_span 1.8.1 [collection path term_glyph]
- sqflite 2.0.0+3 [flutter sqflite_common path]
- sqflite_common 2.0.0+1 [synchronized path meta]
- stack_trace 1.10.0 [path]
- state_notifier 0.7.0 [meta]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.3.0 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.7.0 [path]
- timing 1.0.0 [json_annotation]
- typed_data 1.3.0 [collection]
- url_launcher_linux 2.0.0 [flutter]
- url_launcher_macos 2.0.0 [flutter]
- url_launcher_platform_interface 2.0.2 [flutter plugin_platform_interface]
- url_launcher_web 2.0.0 [url_launcher_platform_interface meta flutter flutter_web_plugins]
- url_launcher_windows 2.0.0 [flutter]
- uuid 3.0.1 [crypto]
- vector_math 2.1.0
- watcher 1.0.0 [async path pedantic]
- web_socket_channel 2.1.0 [async crypto stream_channel]
- win32 2.0.0 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.0.2 [collection meta petitparser]
- yaml 3.0.0 [charcode collection source_span string_scanner]

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @enri90 
What build target are you having this issue with?
Could you provide a code sample?
Thank you

**Comment by enri90** [comment]
Dart SDK 2.13.1
Flutter SDK 2.2.1

build for the web

void main() async {
    WidgetsFlutterBinding.ensureInitialized();
    await Firebase.initializeApp();
    await FirebaseAppCheck.instance.activate(webRecaptchaSiteKey: 'key');
    runApp(MyApp());
}

**Comment by markusaksli-nc** [comment]
Well I'm not seeing the exact same error but the point is that the example app does not work on web.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 2.3.0-17.0.pre.279, on Microsoft Windows [Version 10.0.19041.985], locale et-EE)
    • Flutter version 2.3.0-17.0.pre.279 at C:\Development\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9dd8bcd8c8 (2 hours ago), 2021-06-09 05:44:02 -0400
    • Engine revision 0fe99dd6dd
    • Dart version 2.14.0 (build 2.14.0-190.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\202.7351085\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.2.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\202.7351085
    • Flutter plugin version 57.0.2
    • Dart plugin version 202.8488
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\211.7442.40
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19041.985]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 91.0.4472.77
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 91.0.864.41

• No issues found!
```
</details>
<details>
 <summary>Logs</summary>

```
Error: Unexpected null value.
    at Object.throw_ [as throw] (http://localhost:49680/dart_sdk.js:5037:11)
    at Object.nullCheck (http://localhost:49680/dart_sdk.js:5362:30)
    at firebase_app_check_web.FirebaseAppCheckWeb.__.<anonymous> (http://localhost:49680/packages/firebase_app_check_web/firebase_app_check_web.dart.lib.js:35:23)
    at Generator.next (<anonymous>)
    at runBody (http://localhost:49680/dart_sdk.js:37393:34)
    at Object._async [as async] (http://localhost:49680/dart_sdk.js:37424:7)
    at http://localhost:49680/packages/firebase_app_check_web/firebase_app_check_web.dart.lib.js:34:70
    at Object.guard (http://localhost:49680/packages/firebase_core/src/internals.dart.lib.js:79:19)
    at Object.guard (http://localhost:49680/packages/firebase_app_check_web/src/internals.dart.lib.js:17:22)
    at firebase_app_check_web.FirebaseAppCheckWeb.__.activate (http://localhost:49680/packages/firebase_app_check_web/firebase_app_check_web.dart.lib.js:34:26)
    at activate.next (<anonymous>)
    at runBody (http://localhost:49680/dart_sdk.js:37393:34)
    at Object._async [as async] (http://localhost:49680/dart_sdk.js:37424:7)
    at firebase_app_check_web.FirebaseAppCheckWeb.__.activate (http://localhost:49680/packages/firebase_app_check_web/firebase_app_check_web.dart.lib.js:33:20)
    at firebase_app_check.FirebaseAppCheck.__.activate (http://localhost:49680/packages/firebase_app_check/firebase_app_check.dart.lib.js:36:30)
    at main$ (http://localhost:49680/packages/triage/main.dart.lib.js:182:58)
    at main$.next (<anonymous>)
    at http://localhost:49680/dart_sdk.js:37374:33
    at _RootZone.runUnary (http://localhost:49680/dart_sdk.js:37245:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:49680/dart_sdk.js:32501:29)
    at handleValueCallback (http://localhost:49680/dart_sdk.js:33028:49)
    at Function._propagateToListeners (http://localhost:49680/dart_sdk.js:33066:17)
    at _Future.new.[_completeWithValue] (http://localhost:49680/dart_sdk.js:32914:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:49680/dart_sdk.js:32935:35)
    at Object._microtaskLoop (http://localhost:49680/dart_sdk.js:37497:13)
    at _startMicrotaskLoop (http://localhost:49680/dart_sdk.js:37503:13)
    at http://localhost:49680/dart_sdk.js:33274:9
```
</details>

**Comment by enri90** [comment]
> Well I'm not seeing the exact same error but the point is that the example app does not work on web.
> 
> flutter doctor -v
> Logs

firebase_app_check 0.0.1+2

I also tried with the update always the same problem

firebase_app_check_web.dart 45:35 nullCheck

**Comment by enri90** [comment]
how do i deactivate this module?
when I call a function it asks me for the validation of the app
I don't know how to do it anymore

**Comment by andre-paraense** [comment]
> Well I'm not seeing the exact same error but the point is that the example app does not work on web.
> flutter doctor -v
> Logs

I am also facing this same issue

**Comment by enri90** [comment]
after updating the bug remains on the web
I don't understand why it is not fixed 

Flutter 2.2.3

firebase_core: ^1.4.0
firebase_app_check: ^0.0.1+3
firebase_auth: ^3.0.0
firebase_performance: ^0.7.0+7
firebase_analytics: ^8.2.0
firebase_storage: ^10.0.0
cloud_firestore: ^2.4.0
cloud_functions: ^3.0.0

`Error: Unexpected null value.
    at Object.throw_ [as throw] (http://localhost:5000/dart_sdk.js:5041:11)
    at Object.nullCheck (http://localhost:5000/dart_sdk.js:5366:30)
    at firebase_app_check_web.FirebaseAppCheckWeb.__.<anonymous> (http://localhost:5000/packages/firebase_app_check_web/firebase_app_check_web.dart.lib.js:35:23)
    at Generator.next (<anonymous>)
    at runBody (http://localhost:5000/dart_sdk.js:37422:34)
    at Object._async [as async] (http://localhost:5000/dart_sdk.js:37453:7)
    at http://localhost:5000/packages/firebase_app_check_web/firebase_app_check_web.dart.lib.js:34:70
    at Object.guard (http://localhost:5000/packages/firebase_core/src/internals.dart.lib.js:79:19)
    at Object.guard (http://localhost:5000/packages/firebase_app_check_web/src/internals.dart.lib.js:17:22)
    at firebase_app_check_web.FirebaseAppCheckWeb.__.activate (http://localhost:5000/packages/firebase_app_check_web/firebase_app_check_web.dart.lib.js:34:26)
    at activate.next (<anonymous>)
    at runBody (http://localhost:5000/dart_sdk.js:37422:34)
    at Object._async [as async] (http://localhost:5000/dart_sdk.js:37453:7)
    at firebase_app_check_web.FirebaseAppCheckWeb.__.activate (http://localhost:5000/packages/firebase_app_check_web/firebase_app_check_web.dart.lib.js:33:20)
    at firebase_app_check.FirebaseAppCheck.__.activate (http://localhost:5000/packages/firebase_app_check/firebase_app_check.dart.lib.js:36:30)
    at main$ (http://localhost:5000/packages/booking_lessons_pets/main.dart.lib.js:248:12)
    at main$.next (<anonymous>)
    at http://localhost:5000/dart_sdk.js:37403:33
    at _RootZone.runUnary (http://localhost:5000/dart_sdk.js:37274:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:5000/dart_sdk.js:32530:29)
    at handleValueCallback (http://localhost:5000/dart_sdk.js:33057:49)
    at Function._propagateToListeners (http://localhost:5000/dart_sdk.js:33095:17)
    at async._AsyncCallbackEntry.new.callback (http://localhost:5000/dart_sdk.js:32824:27)
    at Object._microtaskLoop (http://localhost:5000/dart_sdk.js:37526:13)
    at _startMicrotaskLoop (http://localhost:5000/dart_sdk.js:37532:13)
    at http://localhost:5000/dart_sdk.js:33303:9
`

**Comment by nwparker** [comment]
Any update here? It seems odd that this issue is still in triage despite it having clear reproduction steps for well over a month

**Comment by nwparker** [comment]
After looking into the issue, it appears that the following variable is left uninitialized:
`  final app_check_interop.AppCheck? _webAppCheck;` ([code link](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_app_check/firebase_app_check_web/lib/firebase_app_check_web.dart#L35))

Here is a temporary workaround:
```dart
import 'package:firebase_app_check/firebase_app_check.dart';
import 'package:firebase_app_check_web/firebase_app_check_web.dart';

  final fbApp = await Firebase.initializeApp();
  if (kIsWeb) {
    final appCheckWeb = new FirebaseAppCheckWeb(app: fbApp);
    await appCheckWeb.activate(webRecaptchaSiteKey: 'yourKey');
  } else {
    await FirebaseAppCheck.instance.activate(webRecaptchaSiteKey: 'yourKey');
  }
```

**Comment by enri90** [comment]
@nwparker 

thanks your solution allows the app not to crash.

I find after is the call to a cloud function it returns me http status 403

`[firebase_functions/appCheck/fetch-status-error] AppCheck: Fetch server returned an HTTP error status. HTTP status: 403. .`

**Comment by gOzaru** [comment]
Have you checked whether the latest Firebase SDK is added correctly to build.gradle???
Since I just updated it a few minutes ago and all Unauthenticated messages are gone now.
Give it a try.
Check it in Project Settings > General > Your Apps > See SDK Instructions

**Comment by nwparker** [comment]
> Have you checked whether the latest Firebase SDK is added correctly to build.gradle???
> Since I just updated it a few minutes ago and all Unauthenticated messages are gone now.
> Give it a try.
> Check it in Project Settings > General > Your Apps > See SDK Instructions

@gOzaru , this issue is for Flutter Web, so changing something in `build.gradle` is unlikely to have any effect (that would only help with Android)

**Comment by JonasKuschel** [comment]
> After looking into the issue, it appears that the following variable is left uninitialized:
> ` final app_check_interop.AppCheck? _webAppCheck;` ([code link](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_app_check/firebase_app_check_web/lib/firebase_app_check_web.dart#L35))
> 
> Here is a temporary workaround:
> 
> ```dart
> import 'package:firebase_app_check/firebase_app_check.dart';
> import 'package:firebase_app_check_web/firebase_app_check_web.dart';
> 
>   final fbApp = await Firebase.initializeApp();
>   if (kIsWeb) {
>     final appCheckWeb = new FirebaseAppCheckWeb(app: fbApp);
>     await appCheckWeb.activate(webRecaptchaSiteKey: 'yourKey');
>   } else {
>     await FirebaseAppCheck.instance.activate(webRecaptchaSiteKey: 'yourKey');
>   }
> ```

This helps fixing the bug in web, but I cannot build my iOS app anymore.

**Comment by YDA93** [comment]
> After looking into the issue, it appears that the following variable is left uninitialized:
> ` final app_check_interop.AppCheck? _webAppCheck;` ([code link](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_app_check/firebase_app_check_web/lib/firebase_app_check_web.dart#L35))
> 
> Here is a temporary workaround:
> 
> ```dart
> import 'package:firebase_app_check/firebase_app_check.dart';
> import 'package:firebase_app_check_web/firebase_app_check_web.dart';
> 
>   final fbApp = await Firebase.initializeApp();
>   if (kIsWeb) {
>     final appCheckWeb = new FirebaseAppCheckWeb(app: fbApp);
>     await appCheckWeb.activate(webRecaptchaSiteKey: 'yourKey');
>   } else {
>     await FirebaseAppCheck.instance.activate(webRecaptchaSiteKey: 'yourKey');
>   }
> ```

This fixes the issue for the Web and ruins IOS & Android build.

**Comment by KoheiKanagu** [comment]
I was fixes the issue by removing the initialization in Dart and initializing it in script in index.html.

```diff
-  await FirebaseAppCheck.instance.activate(
-    webRecaptchaSiteKey: 'yourKey',
-  );
```

```diff
  <script>
    const firebaseConfig = {
	  ...
    };
    firebase.initializeApp(firebaseConfig);
+   firebase.appCheck().activate('yourKey', true);
  </script>
```

**Comment by dishankjj** [comment]
I am getting permission denied 403. Please read my stackoverflow question I need help https://stackoverflow.com/questions/70083227/flutter-web-i-am-getting-403-permission-denied-error-after-implementing-fireba

**Comment by dishankjj** [comment]
Sorry after 2 days i found the fix, I was everything was setup except that, storage bucket rules is requesting to have an auth header attached to it. i removed that and it is fixed for me.

**Comment by russellwheatley** [comment]
Hey @enri90, can you confirm if this is still an issue for you, please?
