### ISSUE TITLE
"Error handling" link in [Auth -> Registration] documentation is broken

### ISSUE THREAD

**Issue by fourman-alex** [firebase/flutterfire#6334]
The "Error handling" link  in the [Registration section](https://firebase.flutter.dev/docs/auth/usage/#registration) leads to https://firebase.flutter.dev/docs/auth/usage/error-handling, which appears to be broken

![image](https://user-images.githubusercontent.com/5362998/121048353-65785d00-c7bf-11eb-8c4f-7db0ac314292.png)

**Comment by markusaksli-nc** [comment]
It seems like this is somewhat the same as https://github.com/FirebaseExtended/flutterfire/issues/6348

It looks like sometimes the link is correct but sometimes `usage` gets added to it so it doesn't work?

**Comment by russellwheatley** [comment]
Closing this issue and making this https://github.com/firebase/flutterfire/issues/6751 the broken links issue to track. Thank you for reporting @fourman-alex
