### ISSUE TITLE
🐛 [firebase_analytics] Building failed when adding to flutter Add2App

### ISSUE THREAD

**Issue by anujsaxenadev** [firebase/flutterfire#6524]
## Bug report

**Describe the bug**
I have implemented flutter code as a module [Add2App] to my native apps.
I am just importing the firebase analytics to my project.
When i am not able to build aar file.

Packages Used - 
```
firebase_core: ^1.3.0
firebase_crashlytics: ^2.0.6
firebase_analytics: ^8.1.2
```

### Error From the Console
```
Note: /Users/home/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.3.0/android/src/main/java/io/flutter/plugins/firebase/core/FlutterFirebaseCorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/home/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-8.1.2/android/src/main/java/io/flutter/plugins/firebaseanalytics/FirebaseAnalyticsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/home/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-8.1.2/android/src/main/java/io/flutter/plugins/firebaseanalytics/FirebaseAnalyticsPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':firebase_analytics:uploadArchives'.
> Could not publish configuration 'archives'
   > Could not write to file '/Users/home/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-8.1.2/android/build/poms/pom-default.xml'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s


Gradle task assembleAarDebug failed with exit code 0.
```
---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.3 20E232 darwin-x64, locale
    en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.57.1)
[✓] Connected device (1 available)

• No issues found!
```

</details>

---

**Comment by ranjeetscience** [comment]
Facing the same the issue . can someone please help me? I am new to flutter.

**Comment by markusaksli-nc** [comment]
Hi @anujsaxenadev 
Could you please provide your `pubspec.yaml`?
Thank you

**Comment by anujsaxenadev** [comment]
`name: flutterTestModule
description: A new flutter module project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  dio: ^4.0.0
  dartz: ^0.10.0-nullsafety.2
  equatable: ^2.0.3
  get_it: ^7.1.3
  provider: ^5.0.0
  url_launcher: ^6.0.6
  intl: ^0.17.0



  #! External Dependencies

  # flutter_html (Imported due to android min sdk 16 problem from webview_flutter v2.0.6)
  html: ^0.15.0
  csslib: ^0.17.0
  css_colors: ^1.1.0
  flutter_layout_grid: ^1.0.0-nullsafety.6
  video_player: ^2.0.0
  chewie: ^1.0.0
  webview_flutter: 2.0.4
  chewie_audio: ^1.2.0
  flutter_svg: ^0.21.0-nullsafety.0
  firebase_core: ^1.3.0
  firebase_crashlytics: ^2.0.6
  firebase_analytics: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.10
  http_mock_adapter: ^0.2.1
  build_runner: ^2.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - lib/core/res/images/
  fonts:
    - family: Groteskbold
      fonts:
        - asset: lib/core/res/fonts/groteskbold.ttf
    - family: Groteskreg
      fonts:
        - asset: lib/core/res/fonts/groteskreg.ttf
    - family: Grotesksemibold
      fonts:
        - asset: lib/core/res/fonts/grotesksemibold.ttf

  # To add Flutter specific assets to your application, add an assets section,
  # like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add Flutter specific custom fonts to your application, add a fonts
  # section here, in this "flutter" section. Each entry in this list should
  # have a "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidX: true
    androidPackage: com.example.flutterTestModule
    iosBundleIdentifier: com.example.flutterTestModule
`

**Comment by anujsaxenadev** [comment]
`name: flutterTestModule
description: A new flutter module project.

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  dio: ^4.0.0
  dartz: ^0.10.0-nullsafety.2
  equatable: ^2.0.3
  get_it: ^7.1.3
  provider: ^5.0.0
  url_launcher: ^6.0.6
  intl: ^0.17.0

  html: ^0.15.0
  csslib: ^0.17.0
  css_colors: ^1.1.0
  flutter_layout_grid: ^1.0.0-nullsafety.6
  video_player: ^2.0.0
  chewie: ^1.0.0
  webview_flutter: 2.0.4
  chewie_audio: ^1.2.0
  flutter_svg: ^0.21.0-nullsafety.0
  firebase_core: ^1.3.0
  firebase_crashlytics: ^2.0.6
  firebase_analytics: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.10
  http_mock_adapter: ^0.2.1
  build_runner: ^2.0.4


flutter:
  uses-material-design: true
  assets:
    - lib/core/res/images/
  fonts:
    - family: Groteskbold
      fonts:
        - asset: lib/core/res/fonts/groteskbold.ttf
    - family: Groteskreg
      fonts:
        - asset: lib/core/res/fonts/groteskreg.ttf
    - family: Grotesksemibold
      fonts:
        - asset: lib/core/res/fonts/grotesksemibold.ttf

        
  module:
    androidX: true
    androidPackage: com.example.flutterTestModule
    iosBundleIdentifier: com.example.flutterTestModule
`

**Comment by markusaksli-nc** [comment]
Does the issue persist if you add
```yaml
publish_to: 'none'
```

**Comment by anujsaxenadev** [comment]
Tried this still the same result.

> Does the issue persist if you add
> 
> ```yaml
> publish_to: 'none'
> ```

**Comment by markusaksli-nc** [comment]
Have you tried running the build command with administrator privileges?

**Comment by anujsaxenadev** [comment]
> Have you tried running the build command with administrator privileges?

Still the same error. Even with administrator privileges.

**Comment by markusaksli-nc** [comment]
Labeling for further investigation.

**Comment by Sauvikk** [comment]
I am facing the same issue. I created a fresh flutter module using Android Studio and just added the following dependencies.

```
  firebase_core: ^1.5.0
  firebase_messaging: ^10.0.5 
```

The issue is present in `firebase_analytics: ^8.3.0` as well but the  crashlytics plugin `firebase_crashlytics: ^2.2.0` seems to be working fine.

**Comment by Sauvikk** [comment]
> I am facing the same issue. I created a fresh flutter module using Android Studio and just added the following dependencies.
> 
> ```
>   firebase_core: ^1.5.0
>   firebase_analytics: ^8.3.0
> ```
> 
> The issue is present in ` firebase_messaging: ^10.0.5` as well but the crashlytics plugin `firebase_crashlytics: ^2.2.0` seems to be working fine.

This hack seems to resolve the issue  https://github.com/FirebaseExtended/flutterfire/issues/3978#issuecomment-825601559

**Comment by stevanusw28** [comment]
Is there any update on this issue? It still happened at `firebase_analytics: ^9.0.0`

**Comment by chandragupt1201** [comment]
Even I am facing the same issue. 
firebase_messaging: ^10.0.9
firebase_analytics: ^8.3.4

Any update on this ?

**Comment by Jan-Stepien** [comment]
Issue is still there.

Anyone successfully generated aar from Flutter module with Firebase (Cloud Firestore especially)?

**Comment by aleksei-pavlenko** [comment]
This happens also with firebase_app_check: 0.0.6+13

**Comment by akshaytaru2007** [comment]
Hello everyone.

Facing the same issue with the following dependencies
`firebase_core: ^1.21.0
  firebase_analytics: ^9.3.2`
  
  Issue: 
  
  ```
* What went wrong:
Execution failed for task ':firebase_analytics:uploadArchives'.
> Could not publish configuration 'archives'
   > Could not write to file '/Users/XXX/Akshay/Personal/Flutter_SDK/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-9.3.2/android/build/poms/pom-default.xml
```

**Comment by rckrdstrgrd** [comment]
This issue occurred for me after adding a second firebase dependency, the first being firebase_core. The aar build without any issues when only having firebase_core, when adding firebase_analytics the aar build failed with the same error as above.

I was able to build an aar after applying a workaround detailed [here](https://github.com/firebase/flutterfire/issues/3978#issuecomment-825601559). My guess it that this [exception is thrown](https://stackoverflow.com/a/48213819/4224497) when two packages have the same dependency and the gradle build script in flutter_tools (`flutter/sdk/packages/flutter_tools/gradle/aar_init_script.gradle`) needs to be updated to handle this.

**Comment by russellwheatley** [comment]
This isn't something fixable from FlutterFire, and appears to be an issue with Flutter tooling itself. I would suggest filing an issue on the Flutter repository which illustrates the problem with the script in question. As mentioned, you can just apply the workaround mentioned in the comment above.
