### ISSUE TITLE
🐛 [firebase_app_check]  CocoaPods could not find compatible versions for pod "firebase_app_check"

### ISSUE THREAD

**Issue by bigbang489** [firebase/flutterfire#6699]
I got the below error when trying to add app_check to my project

I got the error when building my app:
```
[!] CocoaPods could not find compatible versions for pod "firebase_app_check":
  In Podfile:
    firebase_app_check (from `.symlinks/plugins/firebase_app_check/ios`)

Specs satisfying the `firebase_app_check (from `.symlinks/plugins/firebase_app_check/ios`)` dependency were found, but they required a higher minimum deployment target.
```

My pub spec.yaml
```
  firebase_core: ^1.4.0
  firebase_auth: ^3.0.0
  cloud_firestore: ^2.4.0
  firebase_storage: ^10.0.0
  cloud_functions: ^3.0.0
  firebase_crashlytics: ^2.0.4
  firebase_remote_config: ^0.10.0+3
  firebase_performance: ^0.7.0+7
  firebase_analytics: ^8.2.0
  firebase_app_check: ^0.0.1+3
```

What should I do?

**Comment by markusaksli-nc** [comment]
Hi @bigbang489 
Please specify a higher build target as mentioned in the error. You can do this by uncommenting the line in your podfile or setting it in Xcode.
See https://firebase.flutter.dev/docs/installation/ios#ios-supported-versions
Thank you

**Comment by bigbang489** [comment]
> Hi @bigbang489
> Please specify a higher build target as mentioned in the error. You can do this by uncommenting the line in your podfile or setting it in Xcode.
> See https://firebase.flutter.dev/docs/installation/ios#ios-supported-versions
> Thank you

I have already uncommented  platform :ios, '10.0' to Podfiles, but it doesn't work

**Comment by Salakar** [comment]
Should be ios 11 for App Check - @russellwheatley is working on a docs PR for this

**Comment by YazeedAlKhalaf** [comment]
This should be added to the docs, currently it is outdated.

**Comment by russellwheatley** [comment]
Hey @bigbang489, the documentation now correctly  specifies the correct deployment target for [iOS](https://firebase.flutter.dev/docs/manual-installation/ios) & [macOS](https://firebase.flutter.dev/docs/manual-installation/macos) as is specified in the official firebase-ios-sdk app check podspec [here](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseAppCheck.podspec#L20-L21).
