### ISSUE TITLE
🐛 [cloud_firestore web] There is no line number for the original firestore call on a "permission-denied" exception

### ISSUE THREAD

**Issue by bernaferrari** [firebase/flutterfire#6743]
When `permission-denied` exception is triggered, Flutter doesn't show the origin point (the firebase call that triggered it), so I have no idea which method I should fix.

Ideally, it would show:
file/firebase.dart 1234:56 callFirebase

```
The following FirebaseException was thrown:
[cloud_firestore/permission-denied] Missing or insufficient permissions.

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 236:49  throw_
packages/firebase_core/src/internals.dart 90:18                               <fn>
dart-sdk/lib/async/zone.dart 1362:47                                          _rootRunUnary
dart-sdk/lib/async/zone.dart 1265:19                                          runUnary
dart-sdk/lib/async/future_impl.dart 172:20                                    handleError
dart-sdk/lib/async/future_impl.dart 719:46                                    handleError
dart-sdk/lib/async/future_impl.dart 740:13                                    _propagateToListeners
dart-sdk/lib/async/future_impl.dart 550:5                                     [_completeError]
dart-sdk/lib/async/future_impl.dart 606:7                                     <fn>
dart-sdk/lib/async/zone.dart 1354:13                                          _rootRun
dart-sdk/lib/async/zone.dart 1258:19                                          run
dart-sdk/lib/async/zone.dart 1162:7                                           runGuarded
dart-sdk/lib/async/zone.dart 1202:23                                          callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: [cloud_firestore/permission-denied] The caller does not have permission
```

**Comment by markusaksli-nc** [comment]
Hi @bernaferrari 
Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
So is this from crashlytics or are you able to reproduce the error?
Thank you

**Comment by bernaferrari** [comment]
I'm using `cloud_firestore: ^2.4.0`. This is a fairly simple bug: just try to read something you don't have access to. The exception is expected. The issue is that there is no origin in the logs. I don't know which method triggered that exception. So it gets EXTREMELY HARD to debug.

```dart
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale
    en-BR)
    • Flutter version 2.2.3 at /usr/local/flutter
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
```

**Comment by markusaksli-nc** [comment]
Do you mean the original call not being in the stack? This seems like a result of how flutter web handles async errors rather than our plugin code.

Labeling this just in case but I'm not sure there is much we can do to improve the stack trace itself.

**Comment by MrAlek** [comment]
I can also attest to this problem. And @markusaksli-nc it's not just web related.

Maybe this should be a separate issue but `permission-denied` exceptions don't provide any meaningful info on the failing operation nor the callstack where the operation was triggered.

This makes it exceptionally hard to debug why a `permission-denied` error is thrown in the first place, in an application with hundreds of different Firestore operations.

<img width="824" alt="image" src="https://user-images.githubusercontent.com/1496135/130240601-cd822b5f-65a1-4a89-aa30-892afb89d990.png">
