### ISSUE TITLE
🐛 [cloud_firestore] Periodic batch write randomly raise permission-denied error

### ISSUE THREAD

**Issue by tomoyuki28jp** [firebase/flutterfire#6898]
## Bug report

When I run batch write periodically on macOS, it works fine normally. But only sometimes (like once in few days) permission-denied error occurs.

After the error occurs:
- Periodic batch write won't work until restarting or reloading my app.
- `FirebaseAuth.instance.currentUser.getIdToken()` is still valid. (I checked it with `admin.auth().verifyIdToken()` method on firebase shell.)
- I can still successfully save firestore data by using my application UI manually

I've been struggling for the issue for about 9 months so far. It also occurs on cloud_firestore v1.0.1.

When I run multiple apps, sometimes all of them throw a permission-denied error, but sometimes only some of them do.

### Stacktrace of the error
```
E0828 10:35:17.559277000 123145530757120 chttp2_transport.cc:2880]     ipv6:[2404:6800:4004:81f::200a]:443: Keepalive watchdog fired. Closing transport.
flutter: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.
#0      MethodChannelWriteBatch.commit
package:cloud_firestore_platform_interface/…/method_channel/method_channel_write_batch.dart:52
<asynchronous suspension>
#1      _ActivityTrackerState._update
package:sample3/main.dart:147
<asynchronous suspension>
```

### Steps to reproduce

1. Run my sample project on Mac.
2. Wait for a while (might be few days) until the error occurs :(

It seems like it tends to occur when I wake up my mac from sleep.

### Expected behavior
Permission-denied error should not be raised.

### Sample project
https://github.com/tomoyuki28jp/flutterfire_scheduled_batch_write_sample3

---

## Additional context

It occurs on my MacBook Pro 16-inch 2019 / macOS Big Sur 11.0.1.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.0.1 20B50 darwin-x64, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.59.1)
[✓] Connected device (2 available)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.13.4
Flutter SDK 2.2.3
sample3 1.0.0+1

dependencies:
- cloud_firestore 2.5.1 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.3
- firebase_auth 3.1.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.6.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.6.1 [meta collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- cloud_firestore_platform_interface 5.4.1 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.4.1 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- fake_async 1.2.0 [clock collection]
- firebase_auth_platform_interface 6.1.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.1.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- path 1.8.0
- plugin_platform_interface 2.0.1 [meta]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.3.0 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
```

</details>

---

**Comment by tomoyuki28jp** [comment]
@markusaksli-nc Confirmed the issue is present on the latest `cloud_firestore: ^2.5.1`. I've updated my sample project. https://github.com/tomoyuki28jp/flutterfire_scheduled_batch_write_sample2

I've added the stacktrace of the error.

**Comment by markusaksli-nc** [comment]
I haven't been able to reproduce the issue so far. It seems like this is the only batch write you are doing in the sample?
https://github.com/tomoyuki28jp/flutterfire_scheduled_batch_write_sample2/blob/df47c0383d9fcb0f653e391e5a9ff7e1a13d37b4/lib/data/firestore/minutely_desktop_activity_data_source.dart#L17-L27

And this should just be called in `initState`? Can you try making just a single `main.dart` file sample where you run a batch write and see if you run into the issue with that when waking your mac from sleep?

Since this is a flaky issue I'll label it based on the report for now.

**Comment by tomoyuki28jp** [comment]
@markusaksli-nc Thank you for taking your time.

> this is the only batch write you are doing in the sample?

Yes.

> Can you try making just a single main.dart file sample where you run a batch write and see if you run into the issue with that when waking your mac from sleep?

I've created a new sample project and confirmed the issue is still present. https://github.com/tomoyuki28jp/flutterfire_scheduled_batch_write_sample3

**Comment by tomoyuki28jp** [comment]
When I add each firestore document without using batch, the issue is still present :(

```
flutter: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.
flutter:
#0      MethodChannelDocumentReference.set
package:cloud_firestore_platform_interface/…/method_channel/method_channel_document_reference.dart:44
<asynchronous suspension>
#1      ActivityTracker._update.<anonymous closure>
package:app/…/activity_tracker/activity_tracker.dart:65
<asynchronous suspension>
```

**Comment by tomoyuki28jp** [comment]
When I connect to public wifi, sleep my mac for few mins, and resume, the permission-denied error occurs with high probability. But it occurs on fixed line at my house too.

**Comment by tomoyuki28jp** [comment]
Found a workaround to avoid a permission-denied error. https://github.com/tomoyuki28jp/flutterfire_scheduled_batch_write_sample3/commit/029107ebae7ec64efd68b74c68d5d8e3d256995f

**Comment by tomoyuki28jp** [comment]
When I add each document without batch inside `await Future.forEach`, it seems like the issue is not present somehow.

**Comment by Lyokone** [comment]
Closing this issue, please feel free to reopen if it still occurs using the latest version of FlutterFire plugins.
