### ISSUE TITLE
[📚] Confusion on iOS App Check providers

### ISSUE THREAD

**Issue by nwparker** [firebase/flutterfire#6940]
The page https://firebase.flutter.dev/docs/app-check/overview does not mention which iOS App Check provider (`DeviceCheck` or `App Attest`) should be used.

The Firebase documentation page here (https://firebase.google.com/docs/app-check/ios/app-attest-provider) makes it sound like `App Attest` only works with iOS 14. But it's quite unclear and it seems like they added special code to fallback to `DeviceCheck`? (see image below)
![image](https://user-images.githubusercontent.com/4138956/131788731-05ef8481-f299-4fd0-b8d3-b80493eab75c.png)

Is this same backwards compatibility code included within the Flutter library's code? And does it automatically fall back to `DeviceCheck`? And if so, if we are targeting any iOS version before 14, does that mean we have to include `DeviceCheck` as an AppCheck provider for IOS?

**Comment by gbaccetta** [comment]
Hello I do not know about the underlying code, however using 0..2.2, on an iOS 13.6 device, AppCheck did not work prior to activating deviceCheck (and having only AppAttest activated).
As soon as I provided an auth key for the the device check, everything worked fine without any modification of the code. That means that the underlying implementation works properly

**Comment by tsunhousam91** [comment]
Hi, I searched the iOS package I downloaded, and I found that the iOS doesn't support change the provider with Flutter currently, and I guessed that the default provider on Flutter SDK is DeviceCheck.
And I test it, when I register the Attest on firebase console, my app always failed, but when I changed to register to DeviceCheck, it is successful~~~!!!  
So I gusessd the default provider on Flutter is DeviceCheck

**Comment by KoheiKanagu** [comment]
Only DeviceCheck appears to be supported.

https://firebase.google.com/docs/app-check/flutter/default-providers#project-setup:~:text=Device%20Check%20on%20Apple%20platforms

https://github.com/firebase/flutterfire/blob/da36b9861b7d635382705b4893eed85fd672125c/packages/firebase_app_check/firebase_app_check/ios/Classes/FLTFirebaseAppCheckPlugin.m#L111-L125

**Comment by russellwheatley** [comment]
Hey @nwparker, since you opened this issue, we have updated the App Check API to use whatever provider you wish which is detailed in the documentation [here](https://firebase.google.com/docs/app-check/flutter/default-providers)
