### ISSUE TITLE
🐛 firebase_messaging Notification not working android 10 or later

### ISSUE THREAD

**Issue by Luanpedro21** [firebase/flutterfire#6956]
## Bug report

**Describe the bug**
In Android 10 or latter, notifications not working after long period of inactivity of the app

**Comment by markusaksli-nc** [comment]
Hi @Luanpedro21 
Please upgrade to the latest version `firebase_messaging: ^10.0.6` and check your device power saving settings (see https://github.com/FirebaseExtended/flutterfire/issues/6855#issuecomment-908432284).
If the issue still persists please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`.
Thank you

**Comment by Luanpedro21** [comment]
I updated to the latest version, and on the device I took it out of battery saving mode, but the problem remains, I try for months to solve this, but nothing works.

My flutter doctor:
`PS C:\push_meu\push> flutter doctor -v
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [versÃ£o 10.0.19042.1165], locale pt-BR)
    • Flutter version 2.2.2 at C:\flutter
    • Framework revision d79295af24 (3 months ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Luanp\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\ProgramData\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_111-b14)        
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.60.0)
    • VS Code at C:\Users\Luanp\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.159
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 93.0.961.38`

my flutter pub deps -- --style=compact:

`Dart SDK 2.13.3
Flutter SDK 2.2.2
push 1.0.0+1

dependencies:
- carousel_slider 4.0.0 [flutter]
- cupertino_icons 1.0.3
- firebase_core 1.6.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 10.0.6 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_local_notifications 8.1.1+2 [flutter flutter_local_notifications_platform_interface platform timezone]
- flutter_mobx 2.0.2 [flutter mobx]
- get_it 6.1.1 [async collection]
- http 0.13.3 [async http_parser meta path pedantic]
- marquee 2.2.0 [fading_edge_scrollview flutter]
- mobx 2.0.4 [meta]
- qr_code_scanner 0.5.2 [js flutter flutter_web_plugins]
- shared_preferences 2.0.7 [flutter meta shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- url_launcher 6.0.9 [flutter meta url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- webview_flutter 2.0.12 [flutter]

dev dependencies:
- build_runner 1.12.2 [args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style glob graphs http_multi_server io js logging meta mime path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- change_app_package_name 1.0.0
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- mobx_codegen 2.0.2 [analyzer build build_resolvers meta mobx path source_gen]

transitive dependencies:
- _fe_analyzer_shared 22.0.0 [meta]
- analyzer 1.7.1 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher 
yaml pedantic]
- args 2.2.0
- async 2.6.1 [meta collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.0.3 [analyzer async convert crypto glob logging meta path]
- build_config 0.4.7 [checked_yaml json_annotation meta path pubspec_parse yaml]
- build_daemon 2.1.10 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.4 [analyzer async build crypto graphs logging path package_config pool pub_semver stream_transform yaml]        
- build_runner_core 6.1.12 [async build build_config build_resolvers collection convert crypto glob graphs logging meta path package_config pedantic pool timing watcher yaml]
- built_collection 5.1.0
- built_value 8.1.2 [built_collection collection fixnum meta]
- characters 1.1.0
- charcode 1.2.0
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- cli_util 0.3.3 [meta path]
- clock 1.1.0
- code_builder 3.7.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- convert 3.0.1 [typed_data]
- crypto 3.0.1 [collection typed_data]
- dart_style 2.0.3 [analyzer args path pub_semver source_span]
- fading_edge_scrollview 2.0.0 [flutter]
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 3.0.5 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.0.5 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- fixnum 1.0.0
- flutter_local_notifications_platform_interface 4.0.1 [flutter plugin_platform_interface]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- glob 2.0.1 [async collection file path pedantic string_scanner]
- graphs 1.0.0
- http_multi_server 3.0.1 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- io 1.0.3 [meta path string_scanner]
- js 0.6.3
- json_annotation 4.0.1
- logging 1.0.1
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- mime 1.0.0
- package_config 2.0.0 [path]
- path 1.8.0
- path_provider_linux 2.0.2 [flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.3 [ffi flutter meta path path_provider_platform_interface win32]
- pedantic 1.11.1
- platform 3.0.0
- plugin_platform_interface 2.0.1 [meta]
- pool 1.5.0 [async stack_trace]
- process 4.2.3 [file path platform]
- pub_semver 2.0.0 [collection]
- pubspec_parse 1.0.0 [checked_yaml collection json_annotation pub_semver yaml]
- shared_preferences_linux 2.0.2 [file meta flutter path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.2 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.2 [flutter flutter_web_plugins meta shared_preferences_platform_interface]
- shared_preferences_windows 2.0.2 [flutter file meta path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.2.0 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.0.3 [analyzer async build dart_style glob meta path pedantic source_span yaml]
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.3.0 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.8.0 [path]
- timing 1.0.0 [json_annotation]
- typed_data 1.3.0 [collection]
- url_launcher_linux 2.0.1 [flutter]
- url_launcher_macos 2.0.1 [flutter]
- url_launcher_platform_interface 2.0.4 [flutter plugin_platform_interface]
- url_launcher_web 2.0.4 [flutter flutter_web_plugins meta url_launcher_platform_interface]
- url_launcher_windows 2.0.2 [flutter]
- vector_math 2.1.0
- watcher 1.0.0 [async path pedantic]
- web_socket_channel 2.1.0 [async crypto stream_channel]
- win32 2.2.6 [ffi]
- xdg_directories 0.2.0 [meta path process]
- yaml 3.1.0 [collection source_span string_scanner]`

help-me!!! rsrs

**Comment by Luanpedro21** [comment]
in time, the emulator works perfect, even with android 10. The problem is when it runs on the real device. I use the library example model for implementation. my cell phone is a SAMSUNG

**Comment by markusaksli-nc** [comment]
Have you checked the power saving setting on the device?

**Comment by Luanpedro21** [comment]
do i get on battery and take the app out of smart save mode? if that's it, yes ..but nothing works kkk..I've tried everything, even testing the app on another cell phone with android 10, but none of it works.

I mean a period of 2 hours without opening the respective app

**Comment by markusaksli-nc** [comment]
What is the message payload and how are you sending it?

**Comment by Luanpedro21** [comment]
`
        private async Task<bool> EnviarNotificacao(string body, string title)
        {
            var message = new
            {
                notification = new
                {
                    body = $"{title}",
                    title = $"{body}"
                },
                android = new
                {
                    priority = "high",
                },
                priority = "HIGH",

                to = "/topics/TopicToListen"
             };


            HttpClient ClientFireBase = StartFireBase();
            ClientFireBase.DefaultRequestHeaders.Authorization =
                new AuthenticationHeaderValue("key", "=AAAA.......my key.......21NIH");
            var response2 = await ClientFireBase.PostAsync("fcm/send", new StringContent(
                JsonConvert.SerializeObject(message),
                Encoding.UTF8, "application/json"));


            if (response2.IsSuccessStatusCode)
                return true;
            else
                return false;

        }

        private HttpClient StartFireBase()
        {
            var client = new HttpClient();
            client.BaseAddress = new Uri("https://fcm.googleapis.com");
            return client;
        }
`
______________________________________________________________________________
I´am use Asp Net(C#) in Backend.  IsSuccessStatusCode return true, mas not showing

**Comment by Luanpedro21** [comment]
My texts : Title:Teste, body: hahahaha hahaha

**Comment by markusaksli-nc** [comment]
We were able to reproduce this on `firebase_messaging: ^10.0.7`.
<details>
<summary> flutter doctor -v </summary>
```
[✓] Flutter (Channel stable, 2.5.0, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.5.0 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (2 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Win\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.
[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
[√] Connected device (5 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API 27)
    • SM G975F (mobile) • RZ8M802WY0X      • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19042.1165]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 93.0.4577.63
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 92.0.902.84
! Doctor found issues in 1 category.
C:\Users\Win>
```
</details>

**Comment by Luanpedro21** [comment]
executed in SM A013M with Android 10. Not works.

**Comment by Luanpedro21** [comment]
I´am tested with kotlin in native platform .It didn't work either. I believe it's something with some specific devices, things that google needs to resolve with the manufacturers

**Comment by kanekv** [comment]
I am seeing this behavior on multiple Android devices including Google's own pixel 2 and pixel 6. After about 2 hours of app not being touched pushes stop coming. They magically start working again after app is opened/interacted with.

**Comment by kanekv** [comment]
@markusaksli-nc now that we have confirmed the problem, what would be the steps to solve it? Is there any way to escalate, this problem is quite annoying.

Thanks.

**Comment by kanekv** [comment]
@darshankawar this bug is confirmed by multiple people, this is basic functionality and very annoying on android that it doesn't work as expected.

**Comment by Luanpedro21** [comment]
Yes! While for one solution ... 
In native with kotlin or java, no Works too .. 

While ...

**Comment by Luanpedro21** [comment]
Works in android 8 or above. Not  Works in android 9 ou after  versions

**Comment by russellwheatley** [comment]
@Luanpedro21, are you sure this problem wasn't addressed in this PR: https://github.com/firebase/flutterfire/pull/6730? It does sound like the device might be in an idle state given what you've said.
