### ISSUE TITLE
FlutterFire Roadmap - continued

### ISSUE THREAD

**Issue by Salakar** [firebase/flutterfire#6979]
Hey all :wave:,

Continuing on from #2582 I'm happy to announce work has now been started on the remaining FlutterFire plugins with the same goals as mentioned in #2582.

These plugins and their current statuses are as follows;

 1. 🟢  `Realtime Database` 
	**Status**: Shipped!
 2. 🟢  `Remote Config`
	**Status**: Shipped!
 3. 🟢  `Analytics`
	**Status**: Shipped!
 4. 🟢  `Dynamic Links`
	**Status**: Shipped!
 5. 🟢  `In-App Messaging`
	**Status**: Shipped!
 6. 🟢  `ML Model Downloader` 
	**Status**: Shipped!
 7. 🟢  `App Check`
	**Status**: Shipped!
 8. 🟢  `Performance Monitoring`
	**Status**: Shipped!
 9. 🟢  `Installations`
	**Status**: Shipped!
----

📣 &nbsp; Work is also well underway for a new FlutterFire UI library, to learn more and get involved please see the discussion [here](https://github.com/FirebaseExtended/flutterfire/discussions/6978) by @lesnitsky who's leading this project.

----

I will keep this issue updated going forwards. If you have any issues you'd specifically want to bring to our attention in relation to these plugins then please tag in this issue on those issues separately, rather than commenting here - I'd prefer not to lock this issue and would like to keep this issue on topic for updates and relevant non-issue-specific conversation items.

**Comment by alexcode9** [comment]
Any windows ETA?

**Comment by Salakar** [comment]
👋  Web is now supported in the latest release of `firebase_database` - more improvements coming soon.

**Comment by louis030195** [comment]
👋 Thanks for sharing this roadmap!

Is Web support for Firebase Remote Config planned?

**Comment by Salakar** [comment]
👋 hey all, for those interested in Linux & Windows support; a separate effort is underway for this led by @pr-Mais - more info [here](https://invertase.io/blog/announcing-flutterfire-desktop) and thoughts/feedback welcome on the [desktop repository](https://github.com/invertase/flutterfire_desktop) or on [this discussion](https://github.com/FirebaseExtended/flutterfire/discussions/5557).

**Comment by CiriousJoker** [comment]
This issue mentions that Remote Config is shipped. In this case, the [pub.dev package](https://pub.dev/packages/firebase_remote_config) incorrectly lists web as incompatible.
