### ISSUE TITLE
🐛 [cloud_firestore_platform_interface] Timestamp dependency on flutter 

### ISSUE THREAD

**Issue by jdebecka** [firebase/flutterfire#7030]
## Bug report

**Describe the bug**
There is a redundant dependency on flutter in package cloud_firestore_platform_interface. Timestamp requires flutter/material in order to mark class immutable, which makes the code require flutter SDK even when the developer creates a package that could not have this dependency such as a package that holds all the models. 

Creating packages to divide code into smaller, testable and grouped units is a common practice in VGV. This practice can be observed in [VERY GOOD START](https://github.com/VGVentures/very_good_start/tree/main/very_good_templates/very_good_start/__brick__/%7B%7B%23snakeCase%7D%7D%7B%7Bproject_name%7D%7D%7B%7B/snakeCase%7D%7D/packages). 

Timestamp converter does not use flutter/material for any other reason thus in my opinion removing this dependency would bring more benefits than losses. 

In order to mark class immutable package `import 'package:meta/meta.dart';` can be imported and the annotation will be transformed from `@immutable()` to `@immutable`. Sample can be found [here](https://github.com/jdebecka/cloud_firestore_platform_interface_bug/blob/main/lib/src/immutable_without_flutter.dart)

### Steps to reproduce

1. Create dart package 
2. Import cloud_firestore_platform_interface
3. Use Timestamp type 
4. Write test for the class 
5. Run tests 

1. Test will not run due to missing dependency on flutter sdk 

### Expected behavior

Dart package that does not use any widgets should be able to use timestamp and do not import flutter sdk. 

### Sample project

https://github.com/jdebecka/cloud_firestore_platform_interface_bug

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by Lyokone** [comment]
Looking at the source code, all `@immutable()` have properly been migrated. I'll close this, thanks for the report :)
