### ISSUE TITLE
[web] Switch to v9 compat libaries

### ISSUE THREAD

**Issue by Ehesp** [firebase/flutterfire#7041]
Currently we recommend that users install the v8 Firebase SDK:

```
<script src="https://www.gstatic.com/firebasejs/8.6.1/firebase-app.js"></script>
```

With v9 released which no longer supports the window object, we will need to switch to the compat versions across all plugins.

```
<script src="https://www.gstatic.com/firebasejs/9.0.2/firebase-app-compat.js"></script>
```

The API is the same but uses the v9 SDK under the hood.

**Comment by markusaksli-nc** [comment]
FYI https://github.com/FirebaseExtended/flutterfire/issues/6967

**Comment by russellwheatley** [comment]
Hey @ChristianEdwardPadilla, I'm happy to keep this channel updated with a list of packages completed, and the package that is currently being worked on so you guys can track progress.

**Completed**
Core
Analytics
App Check
Firestore
Auth
Database

**In Progress**
Functions (very near completion)

**To Be Completed**
Performance
Messaging
Remote Config
Storage

We're happy for you to help if you wish 😄. You just need to branch off v9/core branch, select a package to be completed, and update this channel/open draft PR 👍

**Comment by m6keller** [comment]
Has V9 support been added to the main FlutterFire branch? I am trying to implement it in a Flutter project and was wondering if there has been any documentation added for using V9 modular imports for a Flutter project. Thanks!

**Comment by russellwheatley** [comment]
@m6keller We have all the PRs in review. Once they're approved, we'll merge into v9/core branch and test them all together. It won't be part of the main release just yet, but it will be available for users to test out.

**Comment by m6keller** [comment]
@russellwheatley Ok, thanks!

**Comment by ChristianEdwardPadilla** [comment]
Seems this is done or obsolete since https://github.com/firebase/flutterfire/pull/8235? Great work!

**Comment by russellwheatley** [comment]
Yes, we've decided to make it part of the normal release cycle considering our CI was passing, and it was the underlying implementation that had changed, not the user facing API. Except for auth and messaging which have breaking changes and will both have a major version change.

**Comment by jschaider** [comment]
@russellwheatley Wanting to followup on this thread. I am wondering how the flutter web plugins can pick up the js defined functions for interop? The ES6 `exports` symbol exports the js to other js files but doesn't define them on `window` for the flutter web plugin to interop with correct?

**Comment by jschaider** [comment]
Answered my own question! the `*-compat.js` Firebase files handle exporting on window :)
