### ISSUE TITLE
Flutter Firebase Auth with Microsoft on Mobile platforms

### ISSUE THREAD

**Issue by rulila52** [firebase/flutterfire#7057]
Hi. I am trying to do auth with firebase microsoft on my android/ios app. I'm trying to call this functions:

```
UserCredential user = await auth.signInWithPopup(provider);


await auth.signInWithRedirect(provider);
UserCredential user = await auth.getRedirectResult();
```

But I get the following exception:
```
nhandled Exception: UnimplementedError: signInWithPopup() is only supported on web based platforms
```

Is any methods to do auth with firebase microsoft on mobile platforms?

**Comment by fastlorenzo** [comment]
Is there any plan to support Microsoft authentication?

**Comment by prggTheProgrammer** [comment]
Are there any updates on this?

**Comment by zubeirtech** [comment]
Talked to someone from the Firebase Team at Google I/O and he said that they'll add it to the upcoming feature set. But for now it is not supported.

**Comment by mahmoudsalah37** [comment]
```
FirebaseAuth.instance
                      .signInWithRedirect(GoogleAuthProvider());
```
 if use this line give the same error

**Comment by ewodev** [comment]
> Talked to someone from the Firebase Team at Google I/O and he said that they'll add it to the upcoming feature set. But for now it is not supported.

Can you ask them for time estimates? I don't see any roadmap about this

**Comment by j05u3** [comment]
Any updates on this please? 🙏
