### ISSUE TITLE
🐛 [all] Upgrade legacy build settings for android

### ISSUE THREAD

**Issue by juliansteenbakker** [firebase/flutterfire#7138]
## Bug report

Several plugins like firebase_in_app_messaging, firebase_database and others still have deprecated jCenter declaration which needs to be replaced with mavenCentral.
Besides that, some plugins also use very old versions of gradle like firebase_auth and firebase_messaging.
As last, most of the plugins are currently targeting compileSdkVersion 29, while 31 is already out for a few months.

### Expected behavior

I think it would be good practice to update these to the latest versions. The compileSdkVersion can bring some code changes.
I'm willing to check every plugin for this [together with removing embedding v1 references like mentioned here. ](https://github.com/FirebaseExtended/flutterfire/pull/7127#issuecomment-934244484).
I think it's good to discuss first which version we want to use for Gradle, since it will impact the CI/CD street.

**Comment by ueman** [comment]
[jCenter will shut down on February 2022.](https://blog.gradle.org/jcenter-shutdown)

**Comment by pr-Mais** [comment]
No plugin is using` jcenter()`, all were updated to use `mavenCentral()`, only some of the example apps.

**Comment by russellwheatley** [comment]
We have an internal ticket to update example apps which will cover updating legacy build settings. Thanks.
