### ISSUE TITLE
🐛 [firebase_database] get() query ignors startAt() and endAt() constrains

### ISSUE THREAD

**Issue by paj-co** [firebase/flutterfire#7221]
## Bug report

**Describe the bug**
Firebase Realtime Database `get()` query with `startAt()` and `endAt()` constrains return all, even not matching values. With `once()` everything works fine.

### Steps to reproduce

1. Start Firebase project with Realtime Database.
2. Make structure like:
~~~
somePath 
    - UUID1
        - childField: 'abbb'
    - UUID2
        - childField: 'accc'
    - UUID3
        - childField: 'brrr'
    - UUID4
        - childField: 'bzzz'
    - UUID5
        - childField: 'nggg'
~~~
3. Make `once()` query with `startAt('b')` and `endAt('b\uF8FF')` constrains, then with `get()`.
4. `once()` query will return only matching values:
~~~
  {childField: brrr}
  {childField: bzzz}
~~~
5. `get()` query will return every single one, even not matching ones:
~~~
{childField: accc}
{childField: abbb}
{childField: bzzz}
{childField: brrr}
{childField: nggg}
~~~

### Expected behavior

`get()` query should return only matching values.

### Sample project

~~~dart
    final snapshot = await _databaseRef
        .child('somePath/')
        .orderByChild('childField')
        .startAt('b')
        .endAt('b\uF8FF')
        .get();

    if (snapshot.value != null) {
      final data = snapshot.value as Map<dynamic, dynamic>;
      final keys = data.keys.toList(growable: false);
      final values = data.values.toList(growable: false);

      for (int i = 0; i < keys.length; i++) {
        print(values[i]);
      }
    }
~~~

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale en-PL)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.61.1)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

</details>

---

**Comment by Kobatsu** [comment]
Sorry if you already checked it out, but `limitToFirst()` and `limitToLast()` seems to not work neither.

Also, it is quite difficult to find documentation / StackOverflow posts about the `get()` operator due to its very generic name, any tips for this?

**Comment by Tom3652** [comment]
I have created an issue #7396 regarding the ```limitToFirst()``` and ```limitToLast()``` that indeed seems to not be working.

Unfortunately ```orderByChild``` either :/

**Comment by russellwheatley** [comment]
Hey @paj-co, is this still an issue after the RTDB rework at the tail end of 2021? Particularly with #7396 (limitToFirst() and limitToLast() queries ) confirmed as working now.
