### ISSUE TITLE
🐛 [firebase_database] [web] Error: Bad state: Cannot fire new event. Controller is already firing an event.

### ISSUE THREAD

**Issue by deepak786** [firebase/flutterfire#7244]
## Bug report

On the firebase_database_web, when the listener is added to the query, a stream is returned. 
If the stream event is not completed and in between you have the new event then you get the error `Error: Bad state: Cannot fire new event. Controller is already firing an event.`

The reason for the error is that the stream returned is synced stream, [sync: true](https://github.com/FirebaseExtended/flutterfire/blob/cb510af6b401e909a883dcd8c17eadecf77016e1/packages/firebase_database/firebase_database_web/lib/src/interop/database.dart#L362).

### Sample project

here is the sample that reproduces the issue
https://github.com/deepak786/issue_rtdb_controller_already_firing_event

**Comment by russellwheatley** [comment]
Hey @deepak786, are you still experiencing the same issue with the latest version?

**Comment by deepak786** [comment]
@russellwheatley yes, the issue is also with the latest version.
I have already updated the sample with the latest version
https://github.com/deepak786/issue_rtdb_controller_already_firing_event
