### ISSUE TITLE
No events in Google Analytics 4

### ISSUE THREAD

**Issue by Kravchenko1996** [firebase/flutterfire#7287]
Hello everybody!
I am using Firebase Analytics library for Flutter in my project to send events to GA4. I can check it sent successfully via Debug View of Firebase console, in terminal using command "adb logcat -v time -s FA FA-SVC' and in the GA4 console in real time events (see screenshots). However, there is no events in GA4 history and in UA in spite of GTM container was added to project for both Android and iOs. What could be causing the problem?
![3](https://user-images.githubusercontent.com/63616961/139804929-2b12d5c5-69c2-46cb-8709-892b47c80da5.jpg)
![1](https://user-images.githubusercontent.com/63616961/139804933-a9fb6ab8-1215-4b44-ae36-53813dcbb6ca.jpg)
![2](https://user-images.githubusercontent.com/63616961/139804934-3a181479-0313-4641-88c5-ccdaa3dd9a24.jpg)

![4](https://user-images.githubusercontent.com/63616961/139804932-1b257c80-e84c-442e-ae5f-453447d89a35.jpg)

**Comment by darshankawar** [comment]
> However, there is no events in GA4 history and in UA in spite of GTM container was added to project for both Android and iOs. What could be causing the problem?

Since the events from debugView are being logged properly, but not showing up in the history, you may want to check with [firebase support](https://firebase.google.com/support/troubleshooter/analytics) as to why it may not being recorded there, because I doubt if it would be a plugin's issue or maybe a setting in the GA4 itself.

**Comment by Kravchenko1996** [comment]
Believe it or not, they sent me her
![photo_2021-11-02_14-38-56](https://user-images.githubusercontent.com/63616961/139839551-db3ffb25-2328-4bb5-bf32-52781ffde42a.jpg)
e

**Comment by darshankawar** [comment]
@Kravchenko1996 
Can you provide `flutter doctor -v`, `pubspec.yaml` and a minimal code sample ?
Also, can you check using the official plugin [example](https://pub.dev/packages/firebase_analytics/example) if you still get same behavior with it ?

**Comment by Kravchenko1996** [comment]
@darshankawar,
providing pubspec.yaml dependencies, flutter doctor -v and code sample.
![Screenshot from 2021-11-09 11-07-05](https://user-images.githubusercontent.com/63616961/140896102-2755faac-8d71-41f4-a7bb-12b0c824b368.png)
![photo_2021-11-09_11-05-35](https://user-images.githubusercontent.com/63616961/140896133-821ecd15-3e64-491b-81fe-1d1cab2f111e.jpg)

import 'package:firebase_analytics/firebase_analytics.dart';
import 'package:firebase_analytics/observer.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:fluttertoast/fluttertoast.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  Firebase.initializeApp();
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  static FirebaseAnalytics analytics = FirebaseAnalytics();
  static FirebaseAnalyticsObserver observer = FirebaseAnalyticsObserver(
    analytics: analytics,
  );
  Map<String, String> utmParameters = {};

  @override
  void initState() {
    super.initState();
    _sendAnalyticsEvent();
  }

  Future<void> _sendAnalyticsEvent() async {
    await analytics.logEvent(
      name: 'm_loan_accept_sms_new',
      parameters: utmParameters,
    );
    Fluttertoast.showToast(msg: 'logEvent succeeded with $utmParameters');
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      navigatorObservers: [observer],
      debugShowCheckedModeBanner: false,
      home: Scaffold(),
    );
  }
}


I am not using null safety libraries, because project is running on Flutter version 1.22.4.
Also, I checked the official plugin example as you recommended and I assume my code is pretty similar.
Thanks in advance!

**Comment by darshankawar** [comment]
@Kravchenko1996 
Thanks for the details. Since the plugin is in beta, the document points to a pre-release [version](https://firebase.flutter.dev/docs/analytics/overview/#1-add-dependency) of it that you may try and see if it helps. Also, since 1.22.4 is an obsolete version, using the latest framework version is recommended to get best features and implementations, so if possible, you may try to upgrade to latest and use the pre-release version and check.

**Comment by Kravchenko1996** [comment]
@darshankawar
I tried to use null safety version of library (not pre-release, because in that case I face a lot of conflicts) and it hadn't helped me. Still no events in GA4 history. 
By the way, do you know is it even possible to track events in Universal Analytics using Firebase Analytics in Flutter project?

**Comment by darshankawar** [comment]
> is it even possible to track events in Universal Analytics using Firebase Analytics in Flutter project?

I believe they are being only tracked in GA4.  Keeping it open for further insights from the team.

**Comment by LOG-TAG** [comment]
In this latest version events params are logged only after running the debug mode, strange

**Comment by russellwheatley** [comment]
Hey @Kravchenko1996, the first port of call would be to check in debug mode that events are being sent which it looks like they are correctly sent for you.

As far as FlutterFire is concerned, we only wrap around the native SDK. How the events are rendered (or not!) in Google Analytics is out of our hands I'm afraid. This really is a question for Firebase Support/Google Analytics support. Please update here if you do get a response! Thanks 🙏
