### ISSUE TITLE
[firebase_auth ] State of MFA

### ISSUE THREAD

**Issue by MSchmack** [firebase/flutterfire#7290]
Firebase_auth MFA is currently the second highest unanswered feature request and open since august 2020 without a reply. Google brands flutter as first class citizen but this core feature seems to be getting ignored. As good as any application aimed at mid to enterprise sized organizations that is hosted outside of intranets utilizes 2-factor / MFA auth.

This isn't a issue in the usual sense but a statement on if this feature will find its way into the packages is important for any future app that otherwise will have to look into a seperate solution or workaround for this as well as other potentially missing features.

![image](https://user-images.githubusercontent.com/37783519/139821559-fd417270-a23e-4ee7-8647-46f1938e2482.png)

Edit: Accidentally added the wrong labels. The labels can be removed.

**Comment by darshankawar** [comment]
Keeping this issue open and will try to forward this to the team for their insights on this.

**Comment by darshankawar** [comment]
related discussion thread: https://github.com/FirebaseExtended/flutterfire/discussions/2386

**Comment by steeling** [comment]
This feature has been around for over a year outside of Flutter.. any updates?

**Comment by steeling** [comment]
FWIW it looks like this feature would take all of 4 API calls to implement:

  START_PHONE_MFA_ENROLLMENT = '/v2/accounts/mfaEnrollment:start',
  FINALIZE_PHONE_MFA_ENROLLMENT = '/v2/accounts/mfaEnrollment:finalize',
  START_PHONE_MFA_SIGN_IN = '/v2/accounts/mfaSignIn:start',
  FINALIZE_PHONE_MFA_SIGN_IN = '/v2/accounts/mfaSignIn:finalize',

**Comment by Ehesp** [comment]
Hi All - this is on the roadmap, but currently we are prioritising releasing the [remaining plugins](https://github.com/FirebaseExtended/flutterfire/issues/6979). Once they're complete, this will be worked on.

**Comment by dominicmh** [comment]
Hi @Ehesp, is the roadmap for this feature clearer now that the remaining plugins have been released?
Thanks!

**Comment by hansanker** [comment]
Hi, I hope this feature comes soon. We need MFA in our application to be compliant. Thanks a lot in advance.
And thanks for the work done so far for flutterfire!

**Comment by Ehesp** [comment]
@Salakar is currently documenting the API surface area for all platforms. Once that is approved we'll start the implementation.

**Comment by cbenhagen** [comment]
@Salakar is that documentation public somewhere? What is the status of the implementation? How can I help?

**Comment by davidmigloz** [comment]
@Ehesp do you have an approx. ETA? 
I'm willing to help if needed.

**Comment by Lyokone** [comment]
Hey, the implementation is in progress.
Was needing the v9 SDK on JS that should be soon ready. Thanks for your patience

**Comment by mufarrah** [comment]
Any updates on this ?

**Comment by mufarrah** [comment]
> Should be release with this week version

Awesome, looking forward

**Comment by cbenhagen** [comment]
@Lyokone great news! Will there also be macOS support? What about Linux / Windows in https://github.com/invertase/flutterfire_desktop?

**Comment by cbenhagen** [comment]
@Lyokone can you be more specific about the missing functions in the macOS SDK? Is there an open issue already you can link to? I have successfully implemented MFA on macOS in our app using the REST API. You can find the documentation here:
https://cloud.google.com/identity-platform/docs/reference/rest/v2/accounts.mfaEnrollment

And some more info in this discussion: https://github.com/firebase/flutterfire/discussions/2386

**Comment by Lyokone** [comment]
As I remember, the verifyPhone function was missing from the macOS SDK, I might need to double-check that.
Thanks for the documentation, we'll probably focus on Android, iOS and Web then add desktop platforms.

**Comment by cbenhagen** [comment]
@Lyokone Are you refering to [-verifyphonenumber:uidelegate:completion:](https://firebase.google.com/docs/reference/ios/firebaseauth/api/reference/Classes/FIRPhoneAuthProvider#-verifyphonenumber:uidelegate:completion:)? Would you mind creating an issue in https://github.com/firebase/firebase-ios-sdk for the missing functions once you tracked them down?

**Comment by Lyokone** [comment]
Hey, 
I doubled checked and even MultiFactorSession is only available for iOS : https://firebase.google.com/docs/reference/ios/firebaseauth/api/reference/Classes#firmultifactorsession

I've added a request here: https://github.com/firebase/firebase-ios-sdk/issues/10034
