### ISSUE TITLE
🐛 [firebase_crashlytics] 'recordError' method results in an error being recorded with no stacktrace.

### ISSUE THREAD

**Issue by safield** [firebase/flutterfire#7292]
I am using the recordError method to force a non-fatal error to be propagated to Crashlytics.

I am getting the current stacktrace and passing to recordError as follows...

```
StackTrace stacktrace = StackTrace.current;
FirebaseCrashlytics.instance.recordError("forced error" , stacktrace);
```
The error is properly being propagated to Crashlytics console, but it ends up without a stacktrace.

The stacktrace for the error in the Crashlytics console is a single frame as follows...
```
 Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError
forced error. Error thrown null.
```
I have inspected the stacktrace with the debugger before sending, and the stacktrace is populated with 20+ frames.

**Comment by darshankawar** [comment]
@safield 
Can you provide `flutter doctor -v`, `pubspec.yaml` and a minimal code sample that shows this behavior ?
Thanks.

**Comment by safield** [comment]
Please give concrete list of what additional information is needed.

**Comment by darshankawar** [comment]
> @safield Can you provide `flutter doctor -v`, `pubspec.yaml` and a minimal code sample that shows this behavior ? Thanks.

**Comment by safield** [comment]
Here is a minimal code sample. It seems that the reportError method is not able to handle the Trace class that implements StackTrace.

My use case for using Trace class is to provide a method that can send a crashlytics error from anywhere, but not include the method itself as frame "#0" in the stacktrack, but rather adjust the stacktrace so the calling method is considered frame 0. This is because crashlytics uses frame 0 to distinguish between crashes.

```
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'package:flutter/material.dart';
import 'package:stack_trace/stack_trace.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Demo',
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  void initState() {
    super.initState();
    Firebase.initializeApp();
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Crashlytics Test"),
      ),
      body: Center(
        child: ElevatedButton(
          child: const Text("Crash"),
          onPressed: _crash,
        ),
      ),
    );
  }

  void _crash() {
    sendCrashReportScoppedToCaller();
  }

  // call this method anywhere in code to propagate a crash report to crashlytics with a stacktrace that is 
  // scoped to the calling method as frame 0. This is required to have it show up as a unique crash report.
  static void sendCrashReportScoppedToCaller()
  {
    StackTrace stacktrace = StackTrace.current;
    Trace trace = Trace.from(stacktrace);
    // TODo: Manipulate stack trace here.
    FirebaseCrashlytics.instance.recordError("TEST ERROR" , trace);
  }
}
```

**Comment by darshankawar** [comment]
Thanks for the details. I see the same behavior on latest stable using latest plugin version (^2.3.0)

<details>
<summary> stable flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.5.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.5.3 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (2 days ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 93.0.4577.82


• No issues found!

```

</details>

**Comment by kmandrika** [comment]
Hi @safield,

We've recently fixed this issue (picking frame 0) on the backend, please let me know if you are still seeing it! On a different note, we are currently EAPing a new Crashlytics Flutter SDK that supports features such as on-demand fatals, do you have any interest in trying it out? If so, please reach out me directly on the firebase Slack community channel (firebase-community.slack.com), or via Twitter (kmandrika@) so that your email isn't shared publicly.

Thanks,
Konstantin

**Comment by safield** [comment]
I am still observing this issue. I am passing a stacktrace with multiple frames to Firebase.instance.recordError and for the stack trace in the crashlytics console it simple reports "Error thrown null.".

This is a really big issue for me, because multiple different crashes happening in different areas of code are being reported and grouped as the same error. Is there any path forward on this?

**Comment by korzonkiee** [comment]
I'm experiencing the same issue. Even though I pass the stack trace with multiple frames to the `Firebase.instance.recordError` I can only see the name of the exception class and the "Error thrown null".

![CleanShot 2022-04-19 at 09 38 44](https://user-images.githubusercontent.com/26259846/163941555-78038cdd-166b-452d-aea8-6f52ed405128.png)

**Comment by korzonkiee** [comment]
I noticed that there is a way to set the [printDetails](https://github.com/firebase/flutterfire/blob/master/packages/firebase_crashlytics/firebase_crashlytics/lib/src/firebase_crashlytics.dart#L82) flag on the `recordError` method. It is set to `true` automatically when the app is built in debug mode.  I'm loosing the error's context in the production builds, so I'll always set it to `true` and will verify if that helps with the errors verbosity.

**Comment by Andreas409** [comment]
Experiencing the same thing 😓   really impeding our team from solving crashes

**Comment by russellwheatley** [comment]
I just took a look at this, and we do pass the StackTrace correctly with correct Frames. I printed out the relevant values [here](https://github.com/firebase/flutterfire/blob/master/packages/firebase_crashlytics/firebase_crashlytics/ios/Classes/FLTFirebaseCrashlyticsPlugin.m#L235-L245), using following:

```objc
- (FIRStackFrame *)generateFrame:(NSDictionary *)errorElement {
  NSString *methodName = [errorElement valueForKey:kCrashlyticsArgumentMethod];
  NSString *className = [errorElement valueForKey:@"class"];
  NSString *symbol = [NSString stringWithFormat:@"%@.%@", className, methodName];

  NSLog(@"Symbol %@", symbol);
  NSLog(@"className %@", className);
  NSLog(@"File %@", [errorElement valueForKey:kCrashlyticsArgumentFile]);
  NSLog(@"Line %i", [[errorElement valueForKey:kCrashlyticsArgumentLine] intValue]);
  FIRStackFrame *frame = [FIRStackFrame
      stackFrameWithSymbol:symbol
                      file:[errorElement valueForKey:kCrashlyticsArgumentFile]
                      line:[[errorElement valueForKey:kCrashlyticsArgumentLine] intValue]];
  return frame;
}
```

Produced this output which is correct:

```bash
Symbol _MyHomePageState.sendCrashReportScoppedToCaller
className _MyHomePageState
File package:firebase_crashlytics_example/main.dart
Line 60
Symbol _MyHomePageState._crash
className _MyHomePageState
File package:firebase_crashlytics_example/main.dart
Line 53
Symbol _InkResponseState._handleTap
className _InkResponseState
File package:flutter/src/material/ink_well.dart
Line 1005
Symbol GestureRecognizer.invokeCallback
className GestureRecognizer
File package:flutter/src/gestures/recognizer.dart
Line 198
Symbol TapGestureRecognizer.handleTapUp
className TapGestureRecognizer
File package:flutter/src/gestures/tap.dart
Line 613
Symbol BaseTapGestureRecognizer._checkUp
className BaseTapGestureRecognizer
File package:flutter/src/gestures/tap.dart
Line 298
Symbol BaseTapGestureRecognizer.handlePrimaryPointer
className BaseTapGestureRecognizer
File package:flutter/src/gestures/tap.dart
Line 232
Symbol PrimaryPointerGestureRecognizer.handleEvent
className PrimaryPointerGestureRecognizer
File package:flutter/src/gestures/recognizer.dart
Line 563
Symbol PointerRouter._dispatch
className PointerRouter
File package:flutter/src/gestures/pointer_router.dart
Line 94
Symbol PointerRouter._dispatchEventToRoutes.<fn>
className PointerRouter
File package:flutter/src/gestures/pointer_router.dart
Line 139
Symbol _LinkedHashMapMixin.forEach
className _LinkedHashMapMixin
File dart:collection
Line 0
Symbol PointerRouter._dispatchEventToRoutes
className PointerRouter
File package:flutter/src/gestures/pointer_router.dart
Line 137
Symbol PointerRouter.route
className PointerRouter
File package:flutter/src/gestures/pointer_router.dart
Line 123
Symbol GestureBinding.handleEvent
className GestureBinding
File package:flutter/src/gestures/binding.dart
Line 445
Symbol GestureBinding.dispatchEvent
className GestureBinding
File package:flutter/src/gestures/binding.dart
Line 425
Symbol RendererBinding.dispatchEvent
className RendererBinding
File package:flutter/src/rendering/binding.dart
Line 329
Symbol GestureBinding._handlePointerEventImmediately
className GestureBinding
File package:flutter/src/gestures/binding.dart
Line 380
Symbol GestureBinding.handlePointerEvent
className GestureBinding
File package:flutter/src/gestures/binding.dart
Line 344
Symbol GestureBinding._flushPointerEventQueue
className GestureBinding
File package:flutter/src/gestures/binding.dart
Line 302
Symbol GestureBinding._handlePointerDataPacket
className GestureBinding
File package:flutter/src/gestures/binding.dart
Line 285
```

Followed relevant iOS documentation: https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=ios#customize-stack-traces

I believe this is a Firebase Server issue not parsing the frames correctly.

**Comment by Sesa1988** [comment]
This happens for me as well and probably most of the time on Windows where the app crashes completely.
This happens even if I don't initialize the lib, its just referenced in pubspec for other platforms.

**Comment by russellwheatley** [comment]
Hey @safield, the first frame of a `Trace` is the same as a `StackTrace` from my testing. 

[This function](https://github.com/firebase/flutterfire/blob/master/packages/firebase_crashlytics/firebase_crashlytics/lib/src/utils.dart#L12-L54) is designed to accept a `StackTrace` which is what `recordError()` uses to parse the `StackTrace` argument. This is why you are not seeing the stack trace in your Firebase console.

**Comment by Turburlar** [comment]
> Hey @safield, the first frame of a `Trace` is the same as a `StackTrace` from my testing. 
> 
> 
> 
> [This function](https://github.com/firebase/flutterfire/blob/master/packages/firebase_crashlytics/firebase_crashlytics/lib/src/utils.dart#L12-L54) is designed to accept a `StackTrace` which is what `recordError()` uses to parse the `StackTrace` argument. This is why you are not seeing the stack trace in your Firebase console. 

Can you elaborate? Is this fixed in an upcoming version or is there something I am doing wrong?
