### ISSUE TITLE
🐛 [firebase_auth] Cannot contact reCAPTCHA. Check your connection and try again

### ISSUE THREAD

**Issue by sarbogast** [firebase/flutterfire#7364]
## Bug report

I'm using phone authentication on my Flutter 2.5.3 app and on Apple reviewer's phone, the recaptcha verification fails in the browser with this message: Cannot contact reCAPTCHA. Check your connection and try again.

### Steps to reproduce

I am not able to reproduce that issue.

### Expected behavior

I would expect the app to use silent notifications given as I've configured my Push Notification key in my Firebase project and I have added push notification capability to my app, [as described here](https://firebase.google.com/docs/auth/ios/phone-auth?authuser=1#set-up-recaptcha-verification). But when I run my app on my own device, I see the following error message on the console:

[Firebase/Auth][I-AUT000014] Failed to receive remote notification to verify app identity within 5 second(s), falling back to reCAPTCHA verification.

So I don't know if the Flutter version of Firebase Auth is supposed to support silent notifications instead of reCAPTCHA but that would be really helpful right now.

---

## Additional context

I can't reproduce this issue, but the Apple reviewer seems to have it systematically.
The fact that his iPhone seems to show Asian characters, I guess he might be located in a country like China, which I read could have issues with reCAPTCHA, but I'm not 100% sure.

<img src="https://user-images.githubusercontent.com/143758/141696551-a2134baf-cdad-45e1-8302-c50046a9252a.png" width ="300">

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Android Studio (version 2020.3)
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.2)
[✓] VS Code (version 1.54.3)
[✓] Connected device (3 available)
    ! Error: Séjour is not connected. Xcode will continue when Séjour is connected. (code -13)
    ! Error: iPhone de Sebastien is busy: Making the device ready for development. Xcode will continue when iPhone de Sebastien is finished. (code -10)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.14.4
Flutter SDK 2.5.3
foodeater 1.1.7+28

dependencies:
- awesome_card 1.1.5 [flutter]
- beamer 0.14.1 [flutter flutter_web_plugins]
- cloud_firestore 3.1.0 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cloud_functions 3.1.1 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- common 0.0.1 [flutter flutter_localizations intl json_annotation cloud_firestore latlong2]
- cross_local_storage 2.0.1 [flutter shared_preferences shared_preferences_web shared_preferences_macos shared_preferences_windows shared_preferences_linux]
- cupertino_icons 1.0.3
- email_validator 2.0.1
- firebase_auth 3.2.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.10.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_bugfender 2.0.1 [flutter flutter_web_plugins js meta]
- flutter_form_builder 6.1.0+1 [flutter flutter_localizations intl collection]
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]
- flutter_login 2.2.1 [flutter font_awesome_flutter provider another_transformer_page_view another_flushbar quiver pedantic]
- flutter_markdown 0.6.8 [flutter markdown meta path]
- form_builder_phone_field 0.2.0 [flutter flutter_form_builder phone_number country_pickers]
- form_field_validator 1.1.0 [flutter intl]
- intl 0.17.0 [clock path]
- json_annotation 4.3.0 [meta]
- linkable 3.0.1 [flutter url_launcher]
- logger 1.1.0
- mask_text_input_formatter 2.0.0 [flutter]
- material_segmented_control 3.1.2 [flutter]
- package_info_plus 1.3.0 [flutter package_info_plus_platform_interface package_info_plus_linux package_info_plus_macos package_info_plus_windows package_info_plus_web]
- pin_code_fields 7.3.0 [flutter]
- provider 5.0.0 [collection flutter nested]
- qr_flutter 4.0.0 [flutter qr]
- responsive_builder 0.4.1 [flutter]
- retry 3.1.0
- soundpool 2.2.0 [flutter soundpool_platform_interface soundpool_web soundpool_macos]
- url_launcher 6.0.12 [flutter meta url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 3.0.5 [crypto]

dev dependencies:
- build_runner 2.1.4 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- json_serializable 6.0.1 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]

transitive dependencies:
- _fe_analyzer_shared 30.0.0 [meta]
- analyzer 2.7.0 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- another_flushbar 1.10.24 [pedantic flutter]
- another_transformer_page_view 1.0.1 [pedantic flutter]
- args 2.1.1
- async 2.8.1 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.1.0 [analyzer async convert crypto glob logging meta path]
- build_config 1.0.0 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.0.0 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.4 [analyzer async build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.2.2 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pool timing watcher yaml]
- built_collection 5.1.0
- built_value 8.1.0 [built_collection collection fixnum meta]
- characters 1.1.0
- charcode 1.3.1
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- cli_util 0.3.0 [meta path]
- clock 1.1.0
- cloud_firestore_platform_interface 5.4.5 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.5.0 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- cloud_functions_platform_interface 5.0.14 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.1.1 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 4.0.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- convert 3.0.0 [typed_data]
- country_pickers 2.0.0 [flutter]
- crypto 3.0.1 [collection typed_data]
- dart_style 2.2.0 [analyzer args path pub_semver source_span]
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase_auth_platform_interface 6.1.4 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.2.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.1.0 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.2.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- fixnum 1.0.0
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- font_awesome_flutter 9.1.0 [flutter]
- frontend_server_client 2.1.0 [async path]
- glob 2.0.1 [async collection file path pedantic string_scanner]
- graphs 2.0.0
- http 0.13.3 [async http_parser meta path pedantic]
- http_multi_server 3.0.1 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- io 1.0.0 [meta path string_scanner]
- js 0.6.3
- latlong2 0.8.1 [intl]
- logging 1.0.1
- markdown 4.0.0 [args charcode meta]
- matcher 0.12.10 [stack_trace]
- meta 1.7.0
- mime 1.0.0
- nested 1.0.0 [flutter]
- package_config 2.0.0 [path]
- package_info_plus_linux 1.0.3 [package_info_plus_platform_interface flutter path]
- package_info_plus_macos 1.3.0 [flutter]
- package_info_plus_platform_interface 1.0.2 [flutter meta plugin_platform_interface]
- package_info_plus_web 1.0.4 [flutter flutter_web_plugins http meta package_info_plus_platform_interface]
- package_info_plus_windows 1.0.4 [package_info_plus_platform_interface ffi flutter win32]
- path 1.8.0
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.11.1
- phone_number 0.12.0 [flutter meta]
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- pool 1.5.0 [async stack_trace]
- process 4.2.1 [file path platform]
- pub_semver 2.0.0 [collection]
- pubspec_parse 1.0.0 [checked_yaml collection json_annotation pub_semver yaml]
- qr 2.1.0 [meta]
- quiver 3.0.1 [matcher]
- shared_preferences 2.0.8 [flutter meta shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- shared_preferences_linux 2.0.0 [flutter file meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.0 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.0 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 2.0.0 [shared_preferences_platform_interface flutter file meta path path_provider_platform_interface path_provider_windows]
- shelf 1.1.4 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- soundpool_macos 2.1.3 [flutter soundpool_platform_interface]
- soundpool_platform_interface 2.1.0 [flutter meta plugin_platform_interface]
- soundpool_web 2.1.0 [flutter flutter_web_plugins soundpool_platform_interface http]
- source_gen 1.1.1 [analyzer async build dart_style glob meta path source_span yaml]
- source_helper 1.3.0 [analyzer collection source_gen]
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.2 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timing 1.0.0 [json_annotation]
- typed_data 1.3.0 [collection]
- url_launcher_linux 2.0.0 [flutter]
- url_launcher_macos 2.0.0 [flutter]
- url_launcher_platform_interface 2.0.4 [flutter plugin_platform_interface]
- url_launcher_web 2.0.1 [flutter flutter_web_plugins meta url_launcher_platform_interface]
- url_launcher_windows 2.0.0 [flutter]
- vector_math 2.1.0
- watcher 1.0.0 [async path pedantic]
- web_socket_channel 2.1.0 [async crypto stream_channel]
- win32 2.2.5 [ffi]
- xdg_directories 0.2.0 [meta path process]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by aalhadhoud** [comment]
Same thing here spent hours on this issue. Everything looks good for APNs yet users get redirected to the recaptcha.
I have tried to create a new provision profile and new APNs key and everything I could but still this issue exists. The only way i don't get the recaptcha is with the trusted device on my developer account.

**Comment by maheshmnj** [comment]
Hi @sarbogast, Thanks for filing the issue. It looks like the domain entered When registering the reCaptcha is not accessible in the region where the app is running. Try setting `localhost` as the domain when registering a ReCaptcha.

**Comment by sarbogast** [comment]
@maheshmnj I don't get it. I don't register any reCAPTCHA. I simply call verifyPhoneNumber and Firebase deals with the reCAPTCHA on its own. Can you clarify where I could do this configuration?

**Comment by maheshmnj** [comment]
@sarbogast  Ah sorry that was for the web https://firebase.google.com/docs/app-check/web/recaptcha-provider, please ignore the last comment.

**Comment by maheshmnj** [comment]
@sarbogast I ran the official firebase_auth sample and I could not reproduce the issue the Captcha loads and completes successfully. Can you please try setting deviceToken to `.unknown` in `AppDelegate.swift`
```
 Auth.auth().setAPNSToken(deviceToken, type: .unknown) 
```
as mentioned in this [stackoverflow answer](https://stackoverflow.com/a/69950649/8253662)

**Comment by aalhadhoud** [comment]
> @sarbogast I ran the official firebase_auth sample and I could not reproduce the issue the Captcha loads and completes successfully. Can you please try setting deviceToken to `.unknown` in `AppDelegate.swift`
> 
> ```
>  Auth.auth().setAPNSToken(deviceToken, type: .unknown) 
> ```
> 
> as mentioned in this [stackoverflow answer](https://stackoverflow.com/a/69950649/8253662)

still the same issue that's what I have tried:
`import FirebaseAuth`
```
override func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
            let firebaseAuth = Auth.auth()   
            firebaseAuth.auth().setAPNSToken(deviceToken, type: .unknown)
     }
```

**Comment by maheshmnj** [comment]
Thanks for the update keeping this issue open for further investigation from the team.

**Comment by aalhadhoud** [comment]
I fixed this by re-creating the ios folder. I don't know what exactly was the problem but with a fresh ios folder everything works perfect

**Comment by SenhorBardell** [comment]
Regarding reCaptcha from the iOS perspective, it needs a `REVERSED_CLIENT_ID` to be set to `CFBundleURLTypes`, its pretty common pitfall. I am looking a sandbox firebase native iOS project of Firebase v8.12.1 and FirebaseAuth of v8.12.0, FirebaseMessaging v.8.12., iOS 15.2 deploy target.
I can see my test push message from FCM console delivers successfully. However no *silent push*, delivered. Starting from he version 8.8.0 they made [fallback on captcha](https://github.com/firebase/firebase-ios-sdk/pull/8653).
Not sure where to dig and who to ask for help.

**Comment by TheFreal** [comment]
Having the same issue, unfortunately I can't reproduce it on a physical device myself. Tried both solutions in the Stackoverflow link mentioned above, to no avail. App Store reviewer's phone is set to English and (looking at their time zone) probably in the US, so we can rule out locale being the problem.

I've appended the setAPNSToken code to the AppDelegate as mentioned on SO, not sure if that makes sense?

`override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GMSServices.provideAPIKey("XXXXXXXXXXXXXXXXXXXXXXX")
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }

  //Auth
  override func application(
    _ application: UIApplication,
    didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data
  ) {
      let firebaseAuth = Auth.auth()
      firebaseAuth.setAPNSToken(deviceToken, type: AuthAPNSTokenType.unknown)
  }

  override func application(
    _ application: UIApplication, 
    didReceiveRemoteNotification userInfo: [AnyHashable : Any],
    fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void
  ) {
    let firebaseAuth = Auth.auth()
    if (firebaseAuth.canHandleNotification(userInfo)){
      print(userInfo)
      return
    }
  }`

**Comment by Pitazzo** [comment]
Same problem here, APN is configured as described in the docs, but reCaptcha challenge is always shown

**Comment by russellwheatley** [comment]
Hey @sarbogast, this issue needs to be resolved at the level of firebase-ios-sdk. Here is a [similar issue](https://github.com/firebase/firebase-ios-sdk/issues/9500#issuecomment-1077915917). FlutterFire currently uses [version 8.15.0](https://github.com/firebase/flutterfire/blob/faaf449624ff4081cbbc0f241fec3134492cbdb3/packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb#L3) which up until 2 days ago was the latest version.

I also checked the firebase iOS repo and it looks like [Firebase is blocked](https://github.com/firebase/firebase-ios-sdk/issues?q=is%3Aissue+sort%3Aupdated-desc+china+is%3Aclosed) in China (The characters in the image look like Mandarin to me). So I wouldn't recaptha to work there. Hope this helps!
