### ISSUE TITLE
🐛 [performance] leak of traces

### ISSUE THREAD

**Issue by statop** [firebase/flutterfire#7447]
## Bug report

performance does not have a way to "cancel" a trace. 

The recommendation on the internet to "cancel" a trace is to simply never call stop.

But if you do that in flutterfire, it will cause a memory leak. The reference to the trace will be kept forever.

### Steps to reproduce

Create a trace in performance module and never stop it.

### Expected behavior

Some way to cancel a trace, or auto cleanup (auto cleanup would probably require a major refactor of how the entire library works, so probably need a cancel call)

### Sample project

n/a

## Additional context

n/a

### Flutter doctor

n/a

### Flutter dependencies
n/a

**Comment by darshankawar** [comment]
> The recommendation on the internet to "cancel" a trace is to simply never call stop.

@statop Can you provide us a link for reference ?

According to the `stop` method documentation, it is called after the data is collected in the console tapping on stop, so that's the reason why stop is needed in my opinion.
If you are looking to have `cancel` instead of `stop`, this would be more of a feature request than an issue.

**Comment by statop** [comment]
https://stackoverflow.com/questions/54191283/firebase-trace-cancellation

The use case is timing an api call that gets canceled. Which is quite common.

**Comment by darshankawar** [comment]
Thanks for the link. Keeping it open for further insights from the team.

**Comment by russellwheatley** [comment]
Closing out as there is no functionality to clean up traces. Not calling `stop()` simply means it won't be reported, not cleaned up. We do have a function that removes traces on reinitialisation of firebase core but that is all that is required.
