### ISSUE TITLE
Add documentation for faster iOS and macOS builds.

### ISSUE THREAD

**Issue by Jonas-Sander** [firebase/flutterfire#7467]
Currently you have to search through issues on GitHub to find a mention of making your flutter builds faster with https://github.com/invertase/firestore-ios-sdk-frameworks. It's hard to find and hard to know what information is up-to-date.  
Additionally I think many people don't know that you can speed up iOS **and** macOS builds.  

Even at the README at https://github.com/invertase/firestore-ios-sdk-frameworks I couldn't find any mention of macOS.

I think this should be documented at firebase.flutter.dev.

**Comment by darshankawar** [comment]
@Jonas-Sander 
Please check [this](https://github.com/FirebaseExtended/flutterfire/issues/2751) open issue discussing about xcode build times and see if it helps to answer your questions.

**Comment by Jonas-Sander** [comment]
I know that ticket. My point is that this information should be on firebase.flutter.dev not a ticket. Many people will never see the ticket when they use Firestore as this is never mentioned on the website.

**Comment by Jonas-Sander** [comment]
Ah I'm really sorry, I didn't see it there - my first instinct was looking at "iOS installation" and "macOS installation".  
What do you think about adding it also to "iOS installation" and "macOS installation"?    

It also only mentions iOS, not macOS altough the latter can also be sped up with this workaround.

**Comment by Salakar** [comment]
No worries, at the time when I built https://github.com/invertase/firestore-ios-sdk-frameworks I only tested iOS so I've not actually tested it on macOS - are you able to confirm it now does actually work on macOS too?

**Comment by Jonas-Sander** [comment]
Well you said it yourself here https://github.com/FirebaseExtended/flutterfire/issues/3185#issuecomment-761558740

We've used it in the past, although I never explicitly measured the build times. Pretty sure it's working though.

**Comment by darshankawar** [comment]
maybe it would be helpful to add `ios` and `macos` sections or just tweak the current section to indicate the platforms.

**Comment by Salakar** [comment]
> Well you said it yourself here https://github.com/FirebaseExtended/flutterfire/issues/3185#issuecomment-761558740
> 
> We've used it in the past, although I never explicitly measured the build times. Pretty sure it's working though.

Oh I did, been a while 😀

We'll get the docs updated

**Comment by Jonas-Sander** [comment]
> maybe it would be helpful to add ios and macos sections or just tweak the current section to indicate the platforms.

 While its duplication I think the best way would be to have the full explanation in a seperate "Firestore" >  "Installation"/"Build Time" topic and just have small info texts in "Getting Started" >"Overview", "iOS installation" and "macOS installation" that refer/forward to that section.  

Right now I think that many people won't see it - I mean I specifically searched for it, but I didn't find it ;)

**Comment by nilsreichardt** [comment]
There was already documentation about this:

<img width="880" alt="image" src="https://user-images.githubusercontent.com/24459435/180987028-c296b184-fac5-40bb-aa27-eedac2441a0a.png">


https://firebase.flutter.dev/docs/firestore/overview#4-optional-improve-ios--macos-build-times

But I couldn't find this section in the new docs (https://firebase.google.com) anymore.

**Comment by nilsreichardt** [comment]
@kevinthecheung The docs for Cloud Firestore are not public, right?

Could we add [this](https://firebase.flutter.dev/docs/firestore/overview/#4-optional-improve-ios--macos-build-times) content to the Cloud Firestore as a 4th step?

![image](https://user-images.githubusercontent.com/24459435/180999301-a1106fc4-a6c7-464c-bcb3-bdcc216301a7.png)

https://firebase.google.com/docs/firestore/quickstart

**Comment by kevinthecheung** [comment]
Done. Thanks, Nils!

https://firebase.google.com/docs/firestore/quickstart#dart

**Comment by nilsreichardt** [comment]
Cool, thanks @kevinthecheung!
