### ISSUE TITLE
[Crashlytics] 'Crashlytics_Platform.h' file not found (macos)

### ISSUE THREAD

**Issue by a-v-ebrahimi** [firebase/flutterfire#7558]
### Discussed in https://github.com/FirebaseExtended/flutterfire/discussions/7484

<div type='discussions-op-text'>

<sup>Originally posted by **kostasoft** December  7, 2021</sup>
The project is normally built for ios, but for macos it gives the following error.
I am laying out a screenshot from Xcode, it is well visible, which error and in which file appears.

The file **pubspec.yaml** contains the following code
```
...
  firebase_core: ^1.10.2
  firebase_messaging: ^11.2.0
  firebase_crashlytics: ^2.4.0
...
```

<img width="1440" alt="Снимок экрана 2021-12-07 в 17 44 35" src="https://user-images.githubusercontent.com/7292854/145051670-07cbd222-0247-4216-932f-2f6061b75c9d.png">

Again, the problem is only with the build of the project for MacOs.

</div>

**Comment by darshankawar** [comment]
I see the same behavior upon running plugin's official example on latest stable:

```
Running pod install...                                              3.9s
/Users/dhs/documents/fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_crashlytics-2.4.3/macos/Classes/FLTFirebaseCrashlyticsPlugin.m:6:9: fatal error: 'Crashlytics_Platform.h' file not found
#import "Crashlytics_Platform.h"
        ^~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description
** BUILD FAILED **
```

```
firebase_core: ^1.10.0
firebase_crashlytics: ^2.3.0
```

Although when I tried for the very first time, it compiled and built macOS app properly and launched, but for every subsequent tries, I started to get above error.

```
[✓] Flutter (Channel stable, 2.8.0, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    ! Flutter recommends a minimum Xcode version of 13.0.0.
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] VS Code (version 1.62.0)
[✓] Connected device (3 available)

! Doctor found issues in 1 category.

```

**Comment by neelansh-creatorstack** [comment]
same

**Comment by a-v-ebrahimi** [comment]
Upgraded to 2.2.4, still can't compile on MacOS

firebase_crashlytics: ^2.4.4

**Comment by iTomkinas** [comment]
I have same issue, any workarounds until issue is solved?

**Comment by a-v-ebrahimi** [comment]
> 

Maybe manual modification of native iOS files, I'll try later today and comment in case of success.

**Comment by a-v-ebrahimi** [comment]
> I have same issue, any workarounds until issue is resolved?

Yes, just copy **Crashlytics_Platform.h** from iOS pod folder to macOS folder!

**Comment by YazeedAlKhalaf** [comment]
> > I have same issue, any workarounds until issue is resolved?
> 
> Yes, just copy **Crashlytics_Platform.h** from iOS pod folder to macOS folder!

Where is it located?

**Comment by SergejSachs** [comment]
This is still not fixed. I just can't build my macOS app.

**Comment by gyuri-fluttech** [comment]
Yes, indeed. Still not fixed. But the solution from https://github.com/FirebaseExtended/flutterfire/issues/7558#issuecomment-997184425 works.

**Comment by SergejSachs** [comment]
> Yes, indeed. Still not fixed. But the solution from https://github.com/FirebaseExtended/flutterfire/issues/7558#issuecomment-997184425 works. 

Yes its working on my local machine but what about CI/CD? 

Im not sure if ios folder is available if you just want to build macos, probably not right?

If it is available you could copy as well even its annoying and can produce other bugs in the future.

**Comment by jonmountjoy** [comment]
While https://github.com/FirebaseExtended/flutterfire/issues/7558#issuecomment-997184425  did solve the import, I just get errors later on in the compilation, of "unknown receiver 'FIRAnalytics'; did you mean 'FIRCrashlytics'""

I'm using firebase_crashlytics: ^2.4.5

Here's a sample of the resulting errors:

```
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:x86_64, id:4C75388B-8D59-5986-BF55-2E2D0495D755 }
{ platform:macOS, name:Any Mac }
/Users/oththejoy/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-9.0.5/macos/Classes/FLTFirebaseAnalyticsPlugin.m:85:6: error: unknown receiver 'FIRAnalytics'; did you mean 'FIRCrashlytics'?
    [FIRAnalytics logEventWithName:eventName parameters:parameterMap];
     ^~~~~~~~~~~~
     FIRCrashlytics
In module 'FirebaseCrashlytics' imported from /Users/oththejoy/Desktop/temp/MyApps/porridge/mobile/macos/Pods/Headers/Public/Firebase/Firebase.h:38:
/Users/oththejoy/Desktop/temp/MyApps/porridge/mobile/macos/Pods/FirebaseCrashlytics/Crashlytics/Crashlytics/Public/FirebaseCrashlytics/FIRCrashlytics.h:38:12: note: 'FIRCrashlytics' declared here
@interface FIRCrashlytics : NSObject

/Users/oththejoy/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-9.0.5/macos/Classes/FLTFirebaseAnalyticsPlugin.m:85:19: error: no known class method for selector 'logEventWithName:parameters:'
    [FIRAnalytics logEventWithName:eventName parameters:parameterMap];
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/oththejoy/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-9.0.5/macos/Classes/FLTFirebaseAnalyticsPlugin.m:87:6: error: unknown receiver 'FIRAnalytics'; did you mean 'FIRCrashlytics'?
    [FIRAnalytics logEventWithName:eventName parameters:nil];
     ^~~~~~~~~~~~
     FIRCrashlytics
```

**Comment by ericbenwa** [comment]
What if I don't have the `Crashlytics_Platform.h` file on my machine?
How do I get it? And what directory should it go in for the Mac build?

**Comment by ptgms** [comment]
> While [#7558 (comment)](https://github.com/FirebaseExtended/flutterfire/issues/7558#issuecomment-997184425) did solve the import, I just get errors later on in the compilation, of "unknown receiver 'FIRAnalytics'; did you mean 'FIRCrashlytics'""
> 
> I'm using firebase_crashlytics: ^2.4.5
> 
> Here's a sample of the resulting errors:
> 
> ```
> --- xcodebuild: WARNING: Using the first of multiple matching destinations:
> { platform:macOS, arch:x86_64, id:4C75388B-8D59-5986-BF55-2E2D0495D755 }
> { platform:macOS, name:Any Mac }
> /Users/oththejoy/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-9.0.5/macos/Classes/FLTFirebaseAnalyticsPlugin.m:85:6: error: unknown receiver 'FIRAnalytics'; did you mean 'FIRCrashlytics'?
>     [FIRAnalytics logEventWithName:eventName parameters:parameterMap];
>      ^~~~~~~~~~~~
>      FIRCrashlytics
> In module 'FirebaseCrashlytics' imported from /Users/oththejoy/Desktop/temp/MyApps/porridge/mobile/macos/Pods/Headers/Public/Firebase/Firebase.h:38:
> /Users/oththejoy/Desktop/temp/MyApps/porridge/mobile/macos/Pods/FirebaseCrashlytics/Crashlytics/Crashlytics/Public/FirebaseCrashlytics/FIRCrashlytics.h:38:12: note: 'FIRCrashlytics' declared here
> @interface FIRCrashlytics : NSObject
> 
> /Users/oththejoy/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-9.0.5/macos/Classes/FLTFirebaseAnalyticsPlugin.m:85:19: error: no known class method for selector 'logEventWithName:parameters:'
>     [FIRAnalytics logEventWithName:eventName parameters:parameterMap];
>                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /Users/oththejoy/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-9.0.5/macos/Classes/FLTFirebaseAnalyticsPlugin.m:87:6: error: unknown receiver 'FIRAnalytics'; did you mean 'FIRCrashlytics'?
>     [FIRAnalytics logEventWithName:eventName parameters:nil];
>      ^~~~~~~~~~~~
>      FIRCrashlytics
> ```

I also get the same error.
Here is my flutter doctor output:
```
[✓] Flutter (Channel master, 2.13.0-0.0.pre.108, on macOS 12.3 21E5227a darwin-arm, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[!] Android Studio
    ✗ Unable to find bundled Java version.
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
[✓] VS Code (version 1.66.0-insider)
[✓] Connected device (2 available)
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)
[✓] HTTP Host Availability
```

**Comment by russellwheatley** [comment]
Hey folks, I've just tested this against the latest `firebase_crashlytics` and did not come across this issue. It does appear this [file](https://github.com/firebase/flutterfire/blob/master/packages/firebase_crashlytics/firebase_crashlytics/macos/Classes/Crashlytics_Platform.h) is symlinking correctly. Thanks.
