### ISSUE TITLE
SignScreen flutterfire ui : Register

### ISSUE THREAD

**Issue by angwandi** [firebase/flutterfire#7609]
After registering through email and password, the normal process flow should be to sign out the user and send a verification email then send the user  to the sign in screen. This will be more helpful.

**Comment by lesnitsky** [comment]
@angwandi I'm not sure if I understand the "the normal process flow should be to sign out the user" bit. Could you please explain what you mean here?

**Comment by mijinitech** [comment]
@lesnitsky : Simply meaning, after the user registers, an email verification should be sent to the user. 
And before the user carries on with the login process, the user must verify their email.

**Comment by LostInDarkMath** [comment]
Yes I think that would be a very nice feature which also could be enabled or disabled or disabled via a flag in the widget constructor of `SignInScreen` for example.

**Comment by JanSob** [comment]
Any news on this? Email-verification is an essential part of the email-registration process. I think it would be really important if this feature was included in the flutterfire package.
