### ISSUE TITLE
firebase_messaging-11.2.4 still uses deprecated API (ANDROID)

### ISSUE THREAD

**Issue by fullflash** [firebase/flutterfire#7702]
`pub-cache/hosted/pub.dartlang.org/firebase_messaging-11.2.4/android/src/main/java/io/flutter/plugins/firebase/messaging/JobIntentService.java uses or overrides a deprecated API.
`

**Comment by darshankawar** [comment]
Do see the same log in the console:

`pub-cache/hosted/pub.dartlang.org/firebase_messaging-11.2.4/android/src/main/java/io/flutter/plugins/firebase/messaging/JobIntentService.java uses or overrides a deprecated API.`

Keeping it open and labeling since the message is coming from plugin itself.

**Comment by russellwheatley** [comment]
Closing this out, as we're tracking deprecated Android API in this issue: https://github.com/firebase/flutterfire/issues/8073
