### ISSUE TITLE
[📚] Cloud Firestore to get List of Collection

### ISSUE THREAD

**Issue by gOzaru** [firebase/flutterfire#7715]
Until now I haven't found any way in Documentation or Stackoverflow about how to get the list of Collections inside Firestore, like the picture below: 
![SS - Firestore](https://user-images.githubusercontent.com/3258483/147480655-26527ff1-7393-4bea-9b17-8281720417a2.jpg)
As you can see, I wanted to get the list of Collection inside Proyek/Publishers/{Collection}.
I have tried using this code below: 
```dart
final Stream<DocumentSnapshot<Map<String, dynamic>>> pubs = FirebaseFirestore.instance.collection("Proyek").doc("Publishers").snapshots(); 
StreamBuilder<DocumentSnapshot<Map<String, dynamic>>>(
stream: pubs,
builder: (context, AsyncSnapshot<DocumentSnapshot<Map<String, dynamic>>> doc) {
  if (doc.hasError) {
   return SizedBox();
  } else if (doc.connectionState == ConnectionState.waiting) {
   return CircularProgressIndicator();
  } else if (doc.hasData) {
    DocumentSnapshot pub = doc.data!;
    if (pub.exists) {
      return buildPub(context, pub);
    } else {
      return Text("Empty");
    }
  }
 return SizedBox();
}, ),

  Widget buildPub(BuildContext context, DocumentSnapshot docs) {
    late String name = (docs.data()! as Map)[""];

    return Card(
      elevation: 4.0,
      child: Padding(
        padding: const EdgeInsets.fromLTRB(0, 10, 10, 10),
        child: Align(
          alignment: Alignment.centerLeft,
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(name, style: TextStyle(fontSize: 20.sp)),
              SizedBox(height: 5.h),
            ],
          ),
        ),
      ),
    );
  }
```

The result is always empty. 
Can we not get the list of Collection?
If we really can't, then what is the purpose of making a Firestore in a structure like that?
It is useless, I think. 
And, there is no any documentation about this!!!

**Comment by maheshmnj** [comment]
Hi @gOzaru, Thanks for filing the issue. As far as I know, firebase doesn't expose any such Api to fetch the list of collections since that is itself the top-level collection. However, I do agree this should be documented.

**Comment by maheshmnj** [comment]
Hi @gOzaru, Thanks for filing the issue. As far as I know, firebase doesn't expose any such Api to fetch the list of collections since that is itself the top-level collection. However, I do agree this should be documented.

**Comment by gOzaru** [comment]
Wew. 
I spent almost a week to figure this out by reading entire Firestore docs, Google and stacksoverflow.
Okay, please add it to the documentation. 
So no one does the same like I did. 
Thank you.
I am gonna close this.

**Comment by maheshmnj** [comment]
@gOzaru  lets keep this open until this gets fixed.

**Comment by russellwheatley** [comment]
It isn't possible to list the collections from any of the platforms used in FlutterFire. You can use the `firebase-admin` of your choice to list them however. [See here](https://stackoverflow.com/a/62466799)
