### ISSUE TITLE
🐛 [Cloud-Firestore] Loading bundle failed with Invalid argument on Flutter Web

### ISSUE THREAD

**Issue by halloway** [firebase/flutterfire#7722]
## Bug report

When trying to load a bundle into Firestore Cache an error occurs.
Looking in the console the below is shown:
```
Uncaught (in promise) unimplemented
@firebase/firestore: Firestore (8.10.0): SyncEngine Loading bundle failed with Invalid argument: 0
Uncaught (in promise) Invalid argument: 0
    at Object.b (https://contracts-plus.web.app/main.dart.js:3873:3)
    at Object.v (https://contracts-plus.web.app/main.dart.js:3880:14)
    at Object.BO (https://contracts-plus.web.app/main.dart.js:3724:25)
    at Object.fm (https://contracts-plus.web.app/main.dart.js:6031:17)
    at abi.$1 (https://contracts-plus.web.app/main.dart.js:44599:57)
    at Object.aZ4 (https://contracts-plus.web.app/main.dart.js:3828:69)
    at Object.aHl (https://contracts-plus.web.app/main.dart.js:6028:19)
    at b1a (https://contracts-plus.web.app/main.dart.js:7412:19)
    at Object.next (https://contracts-plus.web.app/main.dart.js:7408:42)
    at Ap._failWith (https://www.gstatic.com/firebasejs/8.10.0/firebase-firestore.js:1:279244)
```
On the Chrome Simulator via VSCode, it works fine. Only when deployed to Firebase Hosting the error occurs as above.

### Steps to reproduce

I am following the instructions from here:
https://firebase.flutter.dev/docs/firestore/usage/#data-bundles

```
// Use a package like 'http' to retrieve bundle.
import 'package:http/http.dart' as http;
final response = await http.get(url);

// Convert the 'bundle.txt' string in the response to an Uint8List instance.
Uint8List buffer = Uint8List.fromList(response.body.codeUnits);

// Load bundle into cache.
LoadBundleTask task = FirebaseFirestore.instance.loadBundle(buffer);

// Use .stream API to expose a stream which listens for LoadBundleTaskSnapshot events.
task.stream.listen((taskStateProgress) {
  if(taskStateProgress.taskState == LoadBundleTaskState.success){
    //bundle is loaded into app cache!
  }
});

// If you do not wish to .listen() to the stream, but simply want to know when the bundle has been loaded. Use .last API:
await task.stream.last;

// Once bundle is loaded into cache, you may query for data by using the GetOptions() to specify data retrieval from cache.
QuerySnapshot<Map<String, Object?>> snapshot = await FirebaseFirestore.instance
  .collection('cached-data')
  .get(const GetOptions(source: Source.cache));

```
I also have to mention that LoadBundleTaskState is marked by VSCode as an undefined name. So there seems to be anyways something missing in the implementation.

<img width="1000" alt="Bildschirmfoto 2021-12-28 um 13 29 17" src="https://user-images.githubusercontent.com/24854934/147566499-106876d8-913d-48d8-9ee1-5fd1e5d84db3.png">

### Expected behavior

I would expect the bundle to be loaded and served via Firestore Cache which is working fine in the Chrome Emulator.

### Sample project

The failing version is uploaded here where the console output can be checked.
https://contracts-plus.web.app/#/

Here is the sample I use via Flutter in VSCode:

```
  // Loading Bundle
  loadBundle() async {
    // Use a package like 'http' to retrieve bundle.
    Uri url = Uri.parse("https://firebasestorage.googleapis.com/v0/b/contracts-plus.appspot.com/o/exports%2Fbundle.txt?alt=media&token=28c306d9-98c5-44d6-8e3f-0a50b286f398");
    final response = await http.get(url);

    // Convert the 'bundle.txt' string in the response to an Uint8List instance.
    Uint8List buffer = Uint8List.fromList(response.body.codeUnits);

    // Load bundle into cache.
    LoadBundleTask task = FirebaseFirestore.instance.loadBundle(buffer);

    // Use .stream API to expose a stream which listens for LoadBundleTaskSnapshot events.
    task.stream.listen((taskStateProgress) {
      //if (taskStateProgress.taskState == LoadBundleTaskState.success) {
        //bundle is loaded into app cache!
        //LoadBundleTaskState is not implemented!!!!
      //}
    });

    // If you do not wish to .listen() to the stream, but simply want to know when the bundle has been loaded. Use .last API:
    await task.stream.last;

    await FirebaseFirestore.instance
        .collection('languages')
        .doc('en')
        .get(const GetOptions(source: Source.cache))
        .then((snap) {
          Map dic = snap?.data();
          print(dic);
    });
  }
```

---

## Additional context

As already mentioned it works fine in the Emulator but fails when uploaded to a webserver like Firebase Hosting.
Below is another example, that works fine on the Emulator but fails when uploaded to a webserver like Firebase Hosting.
Further, I am using the fact that ️FlutterFire now supports initialization directly from Dart which I have used.
Here I am using Firebase Storage to fetch the data bundle.

```
      var buffer = await _storage.ref('exports/bundle.txt').getData();
      // Load bundle into cache.
      LoadBundleTask task = FirebaseFirestore.instance.loadBundle(buffer);
      // Wait until all info has been loaded into cache!
      await task.stream.last;

    await FirebaseFirestore.instance
        .collection('languages')
        .doc('en')
        .get(const GetOptions(source: Source.cache))
        .then((snap) {
          Map dic = snap?.data();
          print(dic);
    });
```

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-arm, locale
    de)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.63.2)
[✓] Connected device (1 available)
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
firebase_core: ^1.10.6
cloud_firestore: ^3.1.5
firebase_storage: ^10.2.4
```

</details>

---

**Comment by darshankawar** [comment]
> at Ap._failWith (https://www.gstatic.com/firebasejs/8.10.0/firebase-firestore.js:1:279244)

Seems you are using `8.10.0` version of the firebasejs. I looked at the manual installation part of the document and it shows the version as 8.6.0, may be you can try with that version and see if it helps ? https://firebase.flutter.dev/docs/manual-installation/web#add-firebase-sdks

**Comment by halloway** [comment]
> > at Ap._failWith (https://www.gstatic.com/firebasejs/8.10.0/firebase-firestore.js:1:279244)
> 
> Seems you are using `8.10.0` version of the firebasejs. I looked at the manual installation part of the document and it shows the version as 8.6.0, may be you can try with that version and see if it helps ? https://firebase.flutter.dev/docs/manual-installation/web#add-firebase-sdks

I have also tested the manual installation with various versions including 8.6.0 with the same result.

**Comment by darshankawar** [comment]
Since this works on Android but fails while loading on web server, it may have to do with the firebase js version. Keeping it open for further investigation and labeling.

/cc @Salakar

**Comment by halloway** [comment]
> Since this works on Android but fails while loading on web server, it may have to do with the firebase js version. Keeping it open for further investigation and labeling.
> 
> /cc @Salakar

Most weird thing is that running it locally in the emulator it works as expected with 8.10.0 and 8.6.0. I agree that it may something wrong with the firebase js version.

**Comment by russellwheatley** [comment]
Is this still an issue, @halloway? We're now on Firebase web JS SDK version `9.11.0`.

**Comment by halloway** [comment]
> Is this still an issue, @halloway? We're now on Firebase web JS SDK version `9.11.0`.

I need to test it on the latest version.

**Comment by kamami** [comment]
Having the same issue. 
![image](https://user-images.githubusercontent.com/43880037/214051381-78bb7051-0770-4732-95de-a8bb25d12f9e.png)
