### ISSUE TITLE
🐛 [firebase_database] No implementation found for method cancel

### ISSUE THREAD

**Issue by deepak786** [firebase/flutterfire#7795]
Firebase Crashlytics shows non-fatal issue 

```
Non-fatal Exception: FlutterError
MissingPluginException(No implementation found for method cancel on channel clients/123456/-MSgn_H8m8_-IV05zNnC-[DEFAULT]-null-DatabaseEventType.value-[]#1). Error thrown Instance of 'faa'.

Non-fatal Exception: FlutterError
0  ???                            0x0 (null).    #00 abs 0 _kDartIsolateSnapshotInstructions+0x670cb
1  ???                            0x0 (null).    #01 abs 0 _kDartIsolateSnapshotInstructions+0x1f933b
```

```
Non-fatal Exception: FlutterError
MissingPluginException(No implementation found for method cancel on channel appointments/123456-[DEFAULT]-null-DatabaseEventType.value-[{type: orderBy, name: orderByChild, path: type_date}, {type: cursor, name: startAt, value: 0_}, {type: cursor, name: endAt, value: 0_202201042359}, {type: limit, name: limitToLast, limit: 1}]#1). Error thrown while de-activating platform stream on channel appointments/123456-[DEFAULT]-null-DatabaseEventType.value-[{type: orderBy, name: orderByChild, path: type_date}, {type: cursor, name: startAt, value: 0_}, {type: cursor, name: endAt, value: 0_202201042359}, {type: limit, name: limitToLast, limit: 1}]#1.

Non-fatal Exception: FlutterError
0  ???                            0x0 MethodChannel._invokeMethod + 165 (platform_channel.dart:165)
1  ???                            0x0 EventChannel.receiveBroadcastStream.<fn> + 518 (platform_channel.dart:518)
```

I don't know the steps to reproduce this issue.

**Comment by deepak786** [comment]
I think this issue is similar to https://github.com/FirebaseExtended/flutterfire/issues/7618

**Comment by darshankawar** [comment]
@deepak786 
Can you provide the entire crash log ?
Also is there a way for you to [symbolicate](https://github.com/flutter/flutter/wiki/Crashes) the log that'll be helpful to debug further, otherwise it would be a bit tough to verify the issue.

**Comment by deepak786** [comment]
@darshankawar Crashlytics shows only the above crash logs. There are no other logs.

**Comment by darshankawar** [comment]
Labeling it for further input from the team.

**Comment by russellwheatley** [comment]
@deepak786 just to be clear, is this happening on all platforms?

**Comment by deepak786** [comment]
@russellwheatley yes, it's happening on both android and ios. I haven't tested it on the web.

**Comment by deepak786** [comment]
There is also another exception:

```
======== Exception caught by services library ======================================================
The following PlatformException was thrown while de-activating platform stream on channel clients/123456/-Mtbh5BnpmZzAmSr-EgZ-[DEFAULT]-null-DatabaseEventType.value-[]#3:
PlatformException(error, No active stream to cancel, null, null)
When the exception was thrown, this was the stack: 
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
<asynchronous suspension>
#2      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:518:9)
<asynchronous suspension>
====================================================================================================
```

With PR #7859, the above exception is also resolved.

**Comment by dsgriffin** [comment]
Getting the same with `firebase_performance`:

`No implementation found for method Trace#stop on channel plugins.flutter.io/firebase_performance`

Any idea on when the fix will be pushed or which version it was introduced in?

**Comment by AlaaCherbib** [comment]
I am having the same issue, apparently it is not yet fixed, I am using the latest firebase plugins, but still having random crashes. there is no reliable way to reproduce the issue. 

sdk: '>=2.12.0 <3.0.0'

  firebase_core: ^1.12.0
  firebase_auth: ^3.3.6
  firebase_database: ^9.0.6
  firebase_storage: ^10.2.6
  firebase_remote_config: ^2.0.0
  firebase_analytics: ^9.1.0
  firebase_crashlytics: ^2.5.0
  firebase_app_check: ^0.0.6+5

======== Exception caught by services library ======================================================
The following MissingPluginException was thrown while de-activating platform stream on channel elements/German/tables/-MV_kxHs0GdvgoEWXK1--[DEFAULT]-null-DatabaseEventType.value-[]#35:
MissingPluginException(No implementation found for method cancel on channel elements/German/tables/-MV_kxHs0GdvgoEWXK1--[DEFAULT]-null-DatabaseEventType.value-[]#35)

When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:528:9)
<asynchronous suspension>
====================================================================================================

**Comment by dsgriffin** [comment]
Getting the same with `firebase_performance`:

```
No implementation found for method Trace#stop on channel plugins.flutter.io/firebase_performance
MissingPluginException (MissingPluginException(No implementation found for method Trace#stop on channel plugins.flutter.io/firebase_performance))
```

Any idea on when the fix will be pushed or which version it was introduced in?

**Comment by deepak786** [comment]
@russellwheatley Still has the same issue. The Crashlytics shows the exception with firebase_database: 9.0.6

```
Non-fatal Exception: FlutterError
MissingPluginException(No implementation found for method cancel on channel jobs/123456/-MurQCirGd7FZcXCLvSL-[DEFAULT]-null-DatabaseEventType.value-[]#8). Error thrown Instance of 'Waa'.
```

**Comment by russellwheatley** [comment]
Hey @deepak786, thanks for the report. Out of curiosity, does your app use `firebase_database` in any further isolates (i.e. other than the main isolate)?

**Comment by deepak786** [comment]
@russellwheatley no

**Comment by russellwheatley** [comment]
@deepak786  Is the previous [reproducible sample](https://github.com/deepak786/issue_rtdb_7556) still able to reliably produce this bug?

**Comment by deepak786** [comment]
@russellwheatley no. I don't have the reproducible steps now.
This issue just appeared in Crashlytics again.

**Comment by russellwheatley** [comment]
@deepak786 Ok, if you are able to provide a reproducible sample, please post here and I'll be happy to look into it.

**Comment by deepak786** [comment]
sure

**Comment by deepak786** [comment]
@russellwheatley please check the similar issue https://github.com/FirebaseExtended/flutterfire/issues/8015

**Comment by hm122** [comment]
Facing the same issue.

`
MissingPluginException(No implementation found for method cancel on channel state-[DEFAULT]-null-DatabaseEventType.childChanged-[]#4)
`

**Comment by deepak786** [comment]
The issue is not fixed yet.

**Comment by russellwheatley** [comment]
@deepak786 - if you have a repro, that would be great! Thanks.

**Comment by hm122** [comment]
Also still facing the issue. I have around 5% of users facing this issue.

**Comment by anilthapa1939** [comment]
is this issue fixed yet ?

**Comment by BWhiteApps** [comment]
I ran into this issue today on `firebase_database: 9.0.18`

**Comment by robindijkhof** [comment]
also on `9.0.19`

**Comment by robindijkhof** [comment]
@deepak786 did you revert to a version to resolve this? If so, which one?

**Comment by deepak786** [comment]
@robindijkhof no. I still have this random issue.

**Comment by robindijkhof** [comment]
@darshankawar though not reproducible, I think I got a clue. I updated `firebase_auth` and got this issue as a result https://github.com/firebase/flutterfire/issues/9210. TLDR; fatal crash on app close.

Now, somehow the issue in this OP barely occurs now.  So I think the issue is related to closing the app.

**Comment by Pitazzo** [comment]
This issue is still present and happening to a small yet significant amount of our users.

**Comment by tyukesz** [comment]
I am facing the same issue.

sdk: ">=2.15.1 <3.0.0"

  firebase_core: ^2.1.0
  firebase_database: ^10.0.2

**Comment by martinpelli** [comment]
Faced same issue 
![image](https://github.com/firebase/flutterfire/assets/63437171/6805d7f4-2900-4729-9207-d8a97c45d09e)

firebase_auth: ^4.5.0

**Comment by Lyokone** [comment]
We have seen this issue raised in Firestore when using some special unicode characters, would it happen to be the case for you (see https://github.com/flutter/flutter/issues/116652)
