### ISSUE TITLE
[📚] firebase_auth : setLanguageCode unclear explanations

### ISSUE THREAD

**Issue by Tom3652** [firebase/flutterfire#7829]
I can read this : 

>When set to null, the default Firebase Console language setting is applied.

>The language code will propagate to email action templates (password reset, email verification and email change revocation), SMS templates for phone authentication, reCAPTCHA verifier and OAuth popup/redirect operations provided the specified providers support localization with the language code specified.

>On web platforms, if null is provided as the languageCode the Firebase project default language will be used. On native platforms, the device language will be used.

In the [reference API](https://pub.dev/documentation/firebase_auth/latest/firebase_auth/FirebaseAuth/setLanguageCode.html).

The first sentence seems contradictory with the last in my humble understanding. In my case, i was hoping that indeed on ```native``` platforms, "the device language will be used".   
Unfortunately it's the first sentence that is correct. 

It would also be great to know all ```languageCode``` to be able to use them, i only know the "famous" ones but how can i be sure it's the expected value in FirebaseAuth ? 

Thanks !

**Comment by russellwheatley** [comment]
The first sentence is the general rule and web is the exception. The Firebase documentation says that it should follow the IETF BCP 47 language tag standard. Here is a list of those tags: https://en.wikipedia.org/wiki/IETF_language_tag

If you want confirmation of which ones are supported (my sense is that they are all supported), I suggest contacting Firebase support.
