### ISSUE TITLE
[📚] google_sign_in docs ref is heading to 404 page

### ISSUE THREAD

**Issue by yahu1031** [firebase/flutterfire#7863]
When I'm going through the [usage part of CLI](https://firebase.flutter.dev/docs/cli/#usage), There I saw `google_sign_in` manual installation references. When I click on that it goes [here](https://firebase.flutter.dev/docs/cli/auth/social#google)(404 page)

**Comment by darshankawar** [comment]
https://firebase.flutter.dev/docs/cli/auth/social#google shows Page Not Found (404).

/cc @Salakar

**Comment by russellwheatley** [comment]
Closing this issue and making this https://github.com/firebase/flutterfire/issues/6751 the broken links issue to track. Thank you for reporting @yahu1031
