### ISSUE TITLE
[firebase_messaging] Disable interception of notification to allow for local notification generation

### ISSUE THREAD

**Issue by Minituff** [firebase/flutterfire#7874]
### Discussed in https://github.com/FirebaseExtended/flutterfire/discussions/6113

<div type='discussions-op-text'>

<sup>Originally posted by **Minituff** May 11, 2021</sup>
## Background
I am trying to create a chat app which delivers reliable notifications that includes action buttons such as `Mark as Read` and `Reply` which creates an input field.

Unfortunately the `firebase_messaging` plugin does not support advanced options like Action/Input buttons. So, to do this in Flutter, I am using a great package called [AwesomeNotifications](https://pub.dev/packages/awesome_notifications) which allows for all these advanced features. For anyone unfamiliar, it is like a more advanced version of the [Local Notifications](https://pub.dev/packages/flutter_local_notifications) plugin. 
Using this plugin, I am able to handle the `FirebaseMessaging.onBackgroundMessage(_fcmBackgroundHandler);` callback from `firebase_messaging` and generate the notification with all the properties and actions that I like.

## The Problem
If the notification includes the `notification` property then `firebase_messaging` will automatically display the notification and  [AwesomeNotifications](https://pub.dev/packages/awesome_notifications) will then display its notification--resulting in **duplicate notifications**.
However, removing the `notification` property turns it into a `data-only` notification which, [according to the FlutterFire docs](https://firebase.flutter.dev/docs/messaging/usage#low-priority-messages) are low-priority`

> As mentioned above, data only messages are classed as "low priority". Devices can throttle and ignore these messages if your application is in the background, terminated, or a variety of other conditions such as low battery or currently high CPU usage.
> 
> You should not rely on data only messages to be delivered, they should only be used to support your applications non-critical functionality, e.g. pre-fetching data so the next time the user opens your app the data is ready to be displayed and if the message never gets delivered then your app still functions and fetches data on open.
> 
> To help improve delivery, you can bump the priority of messages. Note; this does still not guarantee delivery.

I have also tested this with my own IOS and Android devices and I would not receive data-only messages unless the app was in the foreground or the last used app on IOS. Notifications would not come through if I was using another app, or it was swiped away from recents.

For a chat application, getting reliable messages is a priority and therefore I need to use the `notification` property to ensure delivery of my notifications. The issues:
1. I cannot use a plugin like [AwesomeNotifications](https://pub.dev/packages/awesome_notifications) or [Local Notifications](https://pub.dev/packages/flutter_local_notifications) to create advanced functioning notifications because it will create duplicate notifications as long as the `notification` property is set. However, the `notification` property is required for reliable notifications.
2. The `firebase_messaging` plugin does not support advanced features such as Action/Input buttons.

A greater explanation of (number 1):
`firebase_messaging` automatically intercepts notifications and displays them and I don't think there is a way to disable that.[ Per the docs](https://firebase.flutter.dev/docs/messaging/usage#notifications) below:
> Messages can be handled via the onBackgroundMessage handler. When received, an isolate is spawned (Android only, iOS/macOS does not require a separate isolate) allowing you to handle messages even when your application is not running.
> and further
> If your message is a notification one (includes a notification property), the Firebase SDKs will intercept this and display a visible notification to your users (assuming you have requested permission & the user has notifications enabled). Once displayed, the background handler will be executed (if provided).

## The Feature Request

I would like to be able to disable the `firebase_messaging` automatic notification display while still having the `onBackgroundMessage` callback fire. This way I can send reliable notifications (with the `notification` property) and have them be displayed by the more advanced flutter tools.

If this is not possible, then I would love to see ActionButtons and Input fields come to the `firebase_messaging` plugin.

## Additional Infromation
I created another issue here https://github.com/rafaelsetragni/awesome_notifications/issues/165

**Comment by coccyx-cyst** [comment]
Have you already found any solution? @Minituff

**Comment by Minituff** [comment]
> Have you already found any solution? @Minituff

@coccyx-cyst No I haven't yet. The latest update I've found on a solution is here:
https://github.com/rafaelsetragni/awesome_notifications/issues/165#issuecomment-1013559494
It looks like @rafaelsetragni is getting close to a solution in the `release-0-7-0` branch.

**Comment by baotrankhtn** [comment]
Same issue

**Comment by HemantNegi** [comment]
Facing the same issue. I want to add some customisations to notifications but turns out we can not customise background notifications. And if we try to launch our own custom notification then there are duplicates as there is no way to disable default background notifications.

My ask is, please provide a flag to disable triggering of automatic background notifications and let user create his own.

**Comment by russellwheatley** [comment]
Hi @Minituff, there is no way of changing the system behaviour, it will always display a notification is it is present on the payload. You can increase the "low priority" aspect to data only payloads by doing the following:

On Android, set the priority field to high.
On Apple (iOS & macOS), set the content-available field to true.

**Comment by rulefahd** [comment]
" If this is not possible, then I would love to see ActionButtons and Input fields come to the firebase_messaging plugin."
That would be optimal!

**Comment by iosephmagno** [comment]
@russellwheatley there should be a way. We should include mutable-content in payload and fcm should code this workaround https://developer.apple.com/documentation/usernotifications/modifying_content_in_newly_delivered_notifications

Was thinking this might be related to our #9300. It seems silent notifications wont be triggered if

**Comment by iosephmagno** [comment]
To recap issue is:

**Silent notifications** lets developers manipulate the content before showing head ups. Unfortunately they are not reliable on iOS which deliver then with low priority 
apns-priority:5
contentAvailable: true

The result is that they dont work well when app is terminated and they might not be triggered under many conditions even in foreground/background mode.

**Remote notifications** are always delivered with highest priority and triggered in all app states: foreground / background / terminated.

However, as of now, firebase_messaging displays them instantly and prevents developers from editing its content. This feature is key for chat apps which need to decrypt notifications’ payload before displaying it.

Solution is to support content-mutable:1 inside payload and let developers edit payload fields even for “notification”, not just “data”. 
https://developer.apple.com/documentation/usernotifications/modifying_content_in_newly_delivered_notifications
