### ISSUE TITLE
🐛 [ui] improve errors on macOS with missing network client entitlements

### ISSUE THREAD

**Issue by Ehesp** [firebase/flutterfire#7908]
Reported on macOS, Sign In is causing problems:

## Checklist

- [ ] Google Sign In produces a blank screen when signing in:

![image](https://user-images.githubusercontent.com/842078/150306307-3e6f2474-cbbc-44f5-846a-fad1994c9587.png)

- [ ] Signing in with email produces a network error - this was fixed by enabling entitlements - this should be documented or a better error thown.

![image](https://user-images.githubusercontent.com/842078/150306423-9b3e378e-6dfa-4c91-9a10-b93d1c97a562.png)

**Comment by bazookon** [comment]
You must enable "Outgoing connections" in xcode 
<img width="859" alt="Captura de Pantalla 2022-01-20 a la(s) 17 01 01" src="https://user-images.githubusercontent.com/15639967/150413149-7a345023-df28-4055-8d13-b1b0dbb9ee23.png">

**Comment by Ehesp** [comment]
Thanks, will get it added to the docs.

**Comment by lesnitsky** [comment]
@bazookon's suggestion would work, however [it is recommended to edit entitlements manually](https://docs.flutter.dev/desktop#setting-up-entitlements).

To enable outgoing requests, add the following lines to the `DebugProfile.entitlements` and `Release.entitlements`:

```
<key>com.apple.security.network.client</key>
<true/>
```

**Comment by orangeandclementine** [comment]
Thank you @darshankawar for referencing me to this issue. May I recommend in the meantime that we add a line to the documentation referencing that the flag may need to be changed? (as mentioned in #8863). Otherwise I do not think the documentation is complete.

I'll just re-affirm that I struggled for like a week on this issue and almost gave up. Would hate for a less experienced dev to just abandon ship.

**Comment by lesnitsky** [comment]
This is now reflected in documentation in [this section](https://github.com/firebase/flutterfire/blob/master/packages/firebase_ui_auth/doc/README.md#macos-entitlements).

The error message is now also displayed and hints about network failure, however the error coming from the underlying firebase sdk is too generic to be able to recognize that this is related to entitlements.
