### ISSUE TITLE
🐛 [ui] ProfileScreen changes

### ISSUE THREAD

**Issue by Ehesp** [firebase/flutterfire#7909]
## Checklist

- [x] Remove or allow overriding of `AppBar` on `ProfileScreen`

The `ProfileScreen` widget renders an `AppBar` which is inconsistent with other screens, making it hard to integrate with custom applications:

![image](https://user-images.githubusercontent.com/842078/150307065-658b53d4-e8b1-4bfe-bedd-b76d1de18d72.png)

- [x] And mechanism to show email address validation (and maybe a way to trigger an email be sent for validation).

- [x] Allow removal of an auth provider.

- [ ] Add confirmation before triggering account deletion.

**Comment by lesnitsky** [comment]
#8358
