### ISSUE TITLE
[📚] When adding GoogleService-Info.plist please follow this

### ISSUE THREAD

**Issue by EA-YOUHOU** [firebase/flutterfire#7917]
When using Crashlytics, the documentation tell us that to allow native reporting we must follow the old method to init firebase. 

<img width="841" alt="Capture d’écran 2022-01-21 à 11 21 24" src="https://user-images.githubusercontent.com/92172436/150510483-6f1cba22-67d7-413b-94e7-c27135d1b247.png">

So, we must add for instance GoogleService-Info.plist inside IOS folder.  The documentation didn't ask us to pay attention about the Target Membership of the file but if this option is empty Firebase Messaging will not work and app will have APNS token issue (null).

**Note for dev working on multi flavors :**  
You maybe have a folder with several sub folder and several GoogleService-Info.plist and on your project root an other GoogleService-Info.plist.
```
Runner/
  GoogleService-Info.plist
  Firebase/
    Flavor1/
      GoogleService-Info.plist
    Flavor2/
      GoogleService-Info.plist
    Flavor3/
      GoogleService-Info.plist
```
At build time you will copy the correct GoogleService-Info.plist from flavor folder and replace the root one. 
To avoid this issue, check all Target Membership of the root GoogleService-Info.plist file. Let empty others.

**Comment by russellwheatley** [comment]
We do have a pretty comprehensive coverage of how to setup your iOS device [here](https://firebase.flutter.dev/docs/manual-installation/ios) along with apple integration for firebase messaging [here](https://firebase.flutter.dev/docs/messaging/apple-integration) which will work as intended.
