### ISSUE TITLE
[📚] firebase_analytics logAdImpression has the documentation of logAddToWishlist

### ISSUE THREAD

**Issue by Tom3652** [firebase/flutterfire#7925]
Please see that the [documentation](https://pub.dev/documentation/firebase_analytics/latest/firebase_analytics/FirebaseAnalytics/logAdImpression.html) of the method ```FirebaseAnalytics.instance.logAdImpression()``` has the same as `FirebaseAnalytics.instance.logAddToWishlist()`. 

This should be referring to this [documentation](https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.Event.html#public-static-final-string-ad_impression).

**Comment by darshankawar** [comment]
https://pub.dev/documentation/firebase_analytics/latest/firebase_analytics/FirebaseAnalytics/logAdImpression.html is same as 
https://pub.dev/documentation/firebase_analytics/latest/firebase_analytics/FirebaseAnalytics/logAddToWishlist.html

**Comment by russellwheatley** [comment]
The documentation has now been updated. Thanks.
