### ISSUE TITLE
[Firebase_database]: `event.snapshot.value.runtimeType` triggers '_InternalLinkedHashMap<Object?, Object?>' is not a subtype of type 'Map<String, dynamic>'` error 

### ISSUE THREAD

**Issue by cntoss** [firebase/flutterfire#7945]
### Got error of DataSnapshot on firebase database

    Map<String, dynamic> data =  snapshot.value as Map<String, dynamic>;

### Work if i do

    Map<String, dynamic> data = jsonDecode(jsonEncode(snapshot.value))  as Map<String, dynamic>;

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.5.1, on macOS 12.0 21A5522h darwin-arm, locale en-NP)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.63.2)
[✓] Connected device (1 available)
```

</details>

**Comment by darshankawar** [comment]
@cntoss 
What plugin version are you using ? This was fixed as part of this issue already: https://github.com/FirebaseExtended/flutterfire/issues/4059, so I suggest you to upgrade plugin version and framework version and see if it helps to fix the issue.

**Comment by cntoss** [comment]
@darshankawar  i updated everything but got same error

  firebase_database: ^9.0.5
  flutterfire_ui: ^0.3.1
  firebase_core: ^1.11.0

**Comment by darshankawar** [comment]
@cntoss 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this error ?
Thanks.

**Comment by cntoss** [comment]
@darshankawar  this is output of 
<details><summary>flutter doctor -v</summary>

 ```
 [✓] Flutter (Channel stable, 2.5.1, on macOS 12.0 21A5522h darwin-arm, locale en-NP)
    • Flutter version 2.5.1 at /Users/ug/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (4 months ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/ug/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Users/ug/Downloads/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/ug/Downloads/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (1 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64 • Android 12 (API 31) (emulator)
```
</details>

 ### Sample Code
     Future<FirebaseUser?> checkUser() async {
       try {
        DataSnapshot data = await FirebaseDatabase.instance.ref('$firebaseUser/$username').get();
        if (data.value != null) {
          //FirebaseUser.fromJson(data.value) returns error as type cast error
          // '_InternalLinkedHashMap<Object?, Object?>' 
          //is not a subtype of type 'Map<String, dynamic>
          return FirebaseUser.fromJson(jsonDecode(jsonEncode(data.value)));
        } else {
          return null;
        }
      } on FirebaseException catch (e) {
        throw Exception(e);
      } catch (e) {
        rethrow;
      }
    }

### Json Parser 
     factory FirebaseUser.fromJson(Map<String, dynamic> json) => FirebaseUser(
        id: json["id"],
        userDisplayName: json["userDisplayName"],
        userEmail: json["userEmail"],
        profileUrl: json["profileUrl"],
    );

**Comment by darshankawar** [comment]
@cntoss 
Check [this](https://stackoverflow.com/questions/68412968/get-mapstring-dynamic-from-mapdynamic-dynamic-flutter) link and see if it helps to resolve.

**Comment by cntoss** [comment]
Thank you for your response sir but problem was not solved. I have to do this jsonDecode(jsonEncode(data.value)) which is costly

**Comment by darshankawar** [comment]
@cntoss 
I am unable to replicate this using `firebase_database` plugin [example](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_database/firebase_database/example) and including code snippet you provided. I am on latest master. Can you try the same and see if it still persists at your end ?

**Comment by cntoss** [comment]
@darshankawar thank you for your response 
 while running [example](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_database/firebase_database/example/lib/main.dart) code :

    final messagesQuery = FirebaseDatabase.instance.ref('messages').limitToLast(10);
      _messagesSubscription = messagesQuery.onChildAdded.listen(
        (DatabaseEvent event) {
          print('Child added: ${event.snapshot.value.runtimeType}');
        },
        onError: (Object o) {
          final error = o as FirebaseException;
          print('Error: ${error.code} ${error.message}');
        },
    );

i got data type as

    Child added: _InternalLinkedHashMap<Object?, Object?>

**Comment by darshankawar** [comment]
Thanks for the update. With above code, I do see the same behavior / error:

`Child added: _InternalLinkedHashMap<Object?, Object?>`

`firebase_database: ^9.0.6`
`Channel master, 2.10.0-1.0.pre.350`

**Comment by codingcafe1** [comment]
### **Solution:**

if you have data in the FIREBASE DATABASE,
**for example**: [check this, Please Click here to Check Screenshot](https://scontent.fisb17-1.fna.fbcdn.net/v/t39.30808-6/275624214_2102432426590018_7130118197254224223_n.png?_nc_cat=106&ccb=1-5&_nc_sid=730e14&_nc_ohc=uzDcghGYpdYAX9CXqXg&_nc_ht=scontent.fisb17-1.fna&oh=00_AT-pIDvo3iJzE_TFXqrohGBTyhSLtMKFhy8U0QXmZFb4Uw&oe=62325BA1)

**Then as of now, 12th March, 2022:** 
To Retrieve Data from Firebase Database, you must use following sample code.
`String name = (snap.snapshot.value as Map)["name"];`
`print("name :: $name");`
For example:
For retrieving name and email from database.
[Please click here to Check the Code Sample Screenshot](https://scontent.fisb17-1.fna.fbcdn.net/v/t39.30808-6/275616988_2102439169922677_3994024596316528808_n.png?_nc_cat=102&ccb=1-5&_nc_sid=730e14&_nc_ohc=6CMSSxpUyTkAX9l8I7C&_nc_ht=scontent.fisb17-1.fna&oh=00_AT8fY8mq74pYRZYlc56vW_Mgp225itF_LXHfz9tak5hDvg&oe=62317672)

**Comment by russellwheatley** [comment]
Hey @cntoss, we leave it up to the user to cast the value correctly. The value comes through as type `_InternalLinkedHashMap <Object?, Object?>` (effectively `Map <Object?, Object?>`). If you wish to cast it to the Map of your choice, you can do this:

```dart
final value = Map<String, dynamic>.from(event.snapshot.value! as Map<Object?, Object?>);

// or if you know the value of the Map properties are `String`:
final value = Map<String, String>.from(event.snapshot.value! as Map<Object?, Object?>);

```
