### ISSUE TITLE
[Analytics] setDefaultEventParameters behavior is inconsistent between iOS and Android

### ISSUE THREAD

**Issue by lchwe** [firebase/flutterfire#8008]
When setting default event parameters, we pass in a map of the parameters we want to add. This works correctly on Android but not on iOS. I did some digging and I noticed that on iOS the code is looking for the "parameters" key in the original argument to pull the default event parameters. I would think this is the wrong logic because it's pretty clear that the parameters are being passed as the argument, not a map that has a "parameters" key with the parameter values. So I think the lines below should be fixed:

https://github.com/FirebaseExtended/flutterfire/blob/232e5f8972df8ef22bfb76ce8cf1e631d823a1b5/packages/firebase_analytics/firebase_analytics/ios/Classes/FLTFirebaseAnalyticsPlugin.m#L141-L142

They should be replaced with:
` [FIRAnalytics setDefaultEventParameters:arguments];`

**Comment by darshankawar** [comment]
For Android:

https://github.com/FirebaseExtended/flutterfire/blob/751104b6ec282592e209ee57f130aae68a752ba5/packages/firebase_analytics/firebase_analytics/android/src/main/java/io/flutter/plugins/firebase/analytics/FlutterFirebaseAnalyticsPlugin.java#L249

For iOS:

https://github.com/FirebaseExtended/flutterfire/blob/751104b6ec282592e209ee57f130aae68a752ba5/packages/firebase_analytics/firebase_analytics/ios/Classes/FLTFirebaseAnalyticsPlugin.m#L142
