### ISSUE TITLE
[📚 Firebase Dynamic LInks] write how to test on iOS TestFlight 

### ISSUE THREAD

**Issue by yasu47b** [firebase/flutterfire#8009]
thanks to this package we save our time to develop app.

Recently I developed applying Firebase dynamic links to our app.

I had a lot of time that how to test receiving Firebase Dynamic Links path and parameters on iOS TestFlight.
especially how can I test receiving dynamic links parameters after installing app.

But I couldn't understand how to test on it.

finally I thought there is a test that go app store via dynamic link then install the app from TestFlight app.

So I think it is helpful how to test dynamic links on iOS TestFlight.
I also  searched document on Flutter Fire, but I couldn't find that about that.
May be it is difficult for developers to test on their first release of dynamic links.

thanks in advance.

**Comment by darshankawar** [comment]
@yasu47b 
Can you check [this](https://stackoverflow.com/questions/58767826/how-to-test-firebase-dynamic-link-with-testflight-unpublished-ios-app) link and see if it helps ?

**Comment by yasu47b** [comment]
@darshankawar 
thanks for your quick reply. I'll check your suggested link.

I Just thought it is helpful that there is a FlutterFire's document that describing test on iOS Test

the contents is like stackoverflow.
- [How to test Firebase Dynamic Link with TestFlight (Unpublished ios app)]

So I create this issue. 

unless it no need and test process is changed by short span, I think adding it to FlutterFire is very helpful.

**Comment by BesartLaci** [comment]
@yasu47b you need to add "ifl" param to your link to delegate to beta.itunes
this should install the app from testlfight instead of app store

https://link.xxx.app/?apn=com.xxxxx.xxx&isi=xxxxxxxxx&ibi=com.xxxxx.xxx&ifl=https://beta.itunes.apple.com/v1/app/{appId}&link=https://xxx.xxx.xxx?id=123

**Comment by russellwheatley** [comment]
Hey @yasu47b, do you mind creating a pull request with the exact steps to follow at the bottom of this [page here](https://github.com/firebase/flutterfire/blob/master/docs/dynamic-links/receive.md)? 😄
