### ISSUE TITLE
[Web][app_check]: hot restarting / hot reloading throws `Error: [app-check/already-activated] AppCheck: You are trying to activate AppCheck for FirebaseApp [DEFAULT], while it is already activated. AppCheck can only be activated once.`

### ISSUE THREAD

**Issue by misteroak** [firebase/flutterfire#8019]
### Discussed in https://github.com/FirebaseExtended/flutterfire/discussions/8017

<div type='discussions-op-text'>

<sup>Originally posted by **misteroak** February  4, 2022</sup>
Hi,

I am likely missing something here, but couldn't find an answer online. I've been following the instructions to add AppCheck to my Flutter Web app. It's working fine on first load, but the moment I hit hot reload or hot restart (using Vs Code) I get the following error:

`Error: [app-check/already-activated] AppCheck: You are trying to activate AppCheck for FirebaseApp [DEFAULT], while it is already activated. AppCheck can only be activated once. .
`

Here's my initialization code:

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  await FirebaseAppCheck.instance.activate(
    webRecaptchaSiteKey: READCTED-TOKEN,
  );

  BlocOverrides.runZoned(
    () {
      runApp(MyApp());
    },
    blocObserver: AppBlocObserver(),
  );
}
```

What am I doing wrong?</div>

**Comment by darshankawar** [comment]
@misteroak 
Can you try the plugin [example](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_app_check/firebase_app_check/example) and see if you still get same error using it ?

**Comment by misteroak** [comment]
Hey, thanks for you response!

Yes, sadly, I'm getting the exact same error using the example. Cloned it as is and ran it in debug mode. I see the main app screen, but once I hit Restart, I get the following error in the console (all in VS Code):

```
Restarted application in 174ms.
Error: [app-check/already-activated] AppCheck: You are trying to activate AppCheck for FirebaseApp [DEFAULT], while it is already activated. AppCheck can only be activated once. .
    at Object.throw_ [as throw] (http://localhost:52695/dart_sdk.js:5063:11)
at http://localhost:52695/packages/firebase_core/src/internals.dart.lib.js:81:63
    at _RootZone.runUnary (http://localhost:52695/dart_sdk.js:40062:59)
    at _FutureListener.catchError.handleError (http://localhost:52695/dart_sdk.js:34996:33)
    at handleError (http://localhost:52695/dart_sdk.js:35567:51)
    at Function._propagateToListeners (http://localhost:52695/dart_sdk.js:35593:17)
    at _Future.new.[_completeError] (http://localhost:52695/dart_sdk.js:35443:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:52695/dart_sdk.js:35479:31)
    at Object._microtaskLoop (http://localhost:52695/dart_sdk.js:40330:13)
    at _startMicrotaskLoop (http://localhost:52695/dart_sdk.js:40336:13)
    at http://localhost:52695/dart_sdk.js:35811:9

```

**Comment by darshankawar** [comment]
@misteroak 
Thanks for the update. I tried to replicate it locally, but am hitting https://github.com/FirebaseExtended/flutterfire/issues/6310, so can't really verify the behavior you are seeing.
Also, looking at the linked issue, it may be happening due to the fact that, the app_check plugin is early access preview plugin and may have open issues that the team may be working on to fix. As a side note, you can also follow-up in the linked issue to know the current status of plugin working on web.

Labeling this for now based on the error log.

**Comment by gavinerasmus** [comment]
Any update on this? Really makes web dev painful when you can't hot reload?

**Comment by gavinerasmus** [comment]
Any update as you can't seem to turn off App Check on Firebase once you enable it so we are stuck unable to hot restart?

**Comment by kekko7072** [comment]
+1

**Comment by binlebin** [comment]
+1 Fixing this would help my dev experience a lot. Thanks!

**Comment by jvlt** [comment]
I just put the initialization of App Check in a try catch block, which makes it work for dev, but that can't be the official solution, especially since the firebase initializeApp has no such problems.

**Comment by cuong0993** [comment]
+1

**Comment by phadin2009** [comment]
Please help to resolve, I have the problem also when hot reload.

**Comment by deonjo** [comment]
+1

**Comment by darshankawar** [comment]
Instead of commenting `+1` or `same issue` or `me too`, please upvote original issue, that helps team to prioritize issue.

**Comment by russellwheatley** [comment]
I've just tested this against latest on master branch which now uses web v9 JS SDK and it is no longer an issue.
