### ISSUE TITLE
[firebase_auth] refresh token needed to authenticate with Firebase Auth web 

### ISSUE THREAD

**Issue by danielhakimi** [firebase/flutterfire#8058]
Hi, 

I've run into an issue when trying to authenticate with a firebase auth web page. This is the solution I'm using for authenticating with the page:

```
map = jsonEncode({
            'apiKey': apiKey,
            'appName': "[DEFAULT]",
            'displayName': user?.displayName,
            'email': user?.email,
            'emailVerified': user?.emailVerified,
            'isAnonymous': user?.isAnonymous,
            'stsTokenManager': {
              'refreshToken': user?.refreshToken,
              'accessToken': await user?.getIdToken(),
              'expirationTime': null
            },
            'tenantId': user?.tenantId,
            'uid': user?.uid,
          });

          await _webViewController?.evaluateJavascript(
            source: """
            let indexdb = window.indexedDB.open('firebaseLocalStorageDb', 1);

            indexdb.onsuccess = async function()  {
              let db = indexdb.result;
              let transaction = db.transaction('firebaseLocalStorage', 'readwrite');
              let storage = transaction.objectStore('firebaseLocalStorage');

              const request = await storage.put({
                fbase_key: 'firebase:authUser:$apiKey:[DEFAULT]',
                value: $map
              });              
            };
            0;
            """,
          );
```

However, this will not work because there is no refresh token provided with the refreshToken property on the user object. I know this works for sure with the refresh token because I used the refresh token from the login call with the firebase auth mobile SDK, reload the page, and then it's authenticated. I was able to get the refresh token using a proxy. 

Is it possible to fill the refreshToken with a value instead of it being null always?

Or can you think of any other solutions to accomplish this?

Thanks in advance.

**Comment by darshankawar** [comment]
@danielhakimi 
Can you check if [this](https://pub.dev/documentation/firebase_auth/latest/firebase_auth/FirebaseAuth/idTokenChanges.html) method helps ?

**Comment by danielhakimi** [comment]
@darshankawar I just checked it. The refresh token is still empty :(

**Comment by darshankawar** [comment]
@danielhakimi 
Can you try the plugin [example](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_auth/firebase_auth/example) and see if it helps, because looking at the code snippet you provided, you seem to be using custom code. Maybe the plugin example will give you more idea.

**Comment by danielhakimi** [comment]
Thanks for the example, but unfortunately not what I'm looking for. 

Here is a StackOverflow question asking for the same implementation. One of the answers is in react native, but isn't clear how they receive a refresh token or not. Checking the native code of the package the refresh token is not returned with the sign-in with email and password method. Probably it isn't deemed necessary if the expectation is to have authenticated webiews in an app, but doesn't really make sign-in very flexible.

**Comment by darshankawar** [comment]
@danielhakimi 
Using your original example, at first it is empty, but if you refresh the browser or hot restart, does it still return empty ?

**Comment by darshankawar** [comment]
Treating this as an enhancement.

**Comment by jacobaraujo7** [comment]
Any update?

**Comment by russellwheatley** [comment]
Hi @danielhakimi, I'd encourage you to read the documentation regarding "User Sessions" which explains the behaviour of refresh tokens and when they're revoked, etc. [See here](https://firebase.google.com/docs/auth/admin/manage-sessions)
