### ISSUE TITLE
🐛 [Firebase_Auth] Exception with different message (Android and iOS)

### ISSUE THREAD

**Issue by yamauchieduardo** [firebase/flutterfire#8066]
When a user try to authenticate the phone number with a wrong SMS code, an exceptions is throw.

But the exception message is different by platform (Android and iOS).

Using Firebase Auth in Android:

```dart
FirebaseAuthException(
    code: "invalid-verification-code",
    message:
    "The sms verification code used to create the phone auth credential is invalid. "
    "Please resend the verification code sms and be sure use the verification code "
    "provided by the user."
);
```

Using Firebase Auth in iOS:

```dart
FirebaseAuthException(
    code: "invalid-verification-code",
    message: 
    "The SMS verification code used to create the phone auth credential is invalid. "
    "Please resend the verification code SMS and be sure to use the verification code "
    "provided by the user."
);
```

I'm aways use the exception code to do something with the exception, but could be nice normalize these exceptions to record or analyze better using tools like analytics, etc.

`firebase_auth: ^3.3.6`

**Comment by darshankawar** [comment]
@yamauchieduardo 
I see below difference in the exception from what you shared:

- `sms` and `SMS`
- `be sure use the verification code` and `be sure to use the verification code`

Are these the differences you ought to point out and make them same across both ?

**Comment by yamauchieduardo** [comment]
I'm aways use the exception code, but could be useful normalize all exception message across the platforms.

**Comment by yamauchieduardo** [comment]
I just notice these 2 differences @darshankawar

**Comment by Lyokone** [comment]
Unifying Auth error code is discussed in this thread: https://github.com/firebase/flutterfire/issues/3273 

We don't have control over error message since it depends on the underlying SDKs
