### ISSUE TITLE
[Firebase_auth] "QUOTA_EXCEEDED : Exceeded quota for sending verification codes" Using phone number for testing on iOS emulator

### ISSUE THREAD

**Issue by yamauchieduardo** [firebase/flutterfire#8074]
I'm using Firebase Auth for 3 years and now a strange behavior started to appears. When I use some registered phone number for test (Phone and sms code Registered in the whitelist), after sometime I'm not able to use a phone number with sms to authenticate in my tests, because the backend returns "QUOTA_EXCEEDED : Exceeded quota for sending verification codes." 

But I'm just use Phone number registered for test.

This behavior is strange because I'm don't notice that on Android Emulator, just in iOS Emulator.

Notice in ` firebase_auth: ^3.3.6 `version

Thanks for the attention.

**Comment by darshankawar** [comment]
@yamauchieduardo 
Can you provide the entire stacktrace that has the error message you mentioned ?

**Comment by yamauchieduardo** [comment]
After running some tests this start to happen when I start to use Phone number registered for testing

```
flutter: ═══ PhoneNumber: +5521111111111, sms: 111111 ═══
flutter: ═══ verificationFailed +5521111111111 ═══
flutter: 00:37 +0: (setUpAll) [E]
flutter:   Error:
  >>> VerificationFailed<<<
flutter:   package:project_name/utilitiesfirebase_main.dart 88:11                                    UtilFirebase.<fn>
  package:firebase_auth_platform_interface/src/method_channel/method_channel_firebase_auth.dart 602:29  MethodChannelFirebaseAuth.verifyPhoneNumber.<fn>
  dart:async/zone.dart 1436:47                                                                          _rootRunUnary
  dart:async/zone.dart 1335:19                                                                          _CustomZone.runUnary
  dart:async/zone.dart 1244:7                                                                           _CustomZone.runUnaryGuarded
  dart:async/stream_impl.dart 341:11                                                                    _BufferingStreamSubscription._sendData
  dart:async/stream_impl.dart 591:14                                                                    _DelayedData.perform
  dart:async/stream_impl.dart 706:11       <…>
flutter: Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'dart test --chain-stack-traces'.
flutter: 00:37 +0 -1: (tearDownAll)
```

The object throwed by Firebase Auth:

![Screen Shot 2022-02-14 at 3 10 34 PM](https://user-images.githubusercontent.com/44825178/153921896-33d24ccc-f9e0-4e61-97fc-65c1acaa227b.png)

The quota usage in project:

![image](https://user-images.githubusercontent.com/44825178/153913117-9db6e949-c137-4a09-8112-0b42a97128b6.png)

The Phone numbers registered for testing in project

![image (1)](https://user-images.githubusercontent.com/44825178/153913258-e64825f2-61be-48e1-bfed-302a894ba00e.png)

**Comment by darshankawar** [comment]
@yamauchieduardo 
Does it only occur when using iOS simulator ? Can you try it on a physical device to see if you still get same error ?
Since you testing on iOS simulator, the SMS code must be getting verified somehow, something like auto-verify. It would be good to verify this on a physical device to confirm.

**Comment by yamauchieduardo** [comment]
@darshankawar I used a real device and sadly happen too.
A plus information: before start the authentication I setup "appVerificationDisabledForTesting" and forceRecaptchaFlow.

```
  await FirebaseAuth.instance.setSettings(
        appVerificationDisabledForTesting: true,
        forceRecaptchaFlow: false,
      );
```

This behavior is really strange, I just start to notice in the latest versions, a sometime ago (6 months ago) this issue didn't occurs.

**Comment by darshankawar** [comment]
Thanks for the update and further details. Keeping it open and labeling for further insights from the team.

/cc @russellwheatley

**Comment by yamauchieduardo** [comment]
Adicional information: I ran the same amount of tests using an Android Emulator and an Android Physical device and the issue doesn't happen. This issue **just occurs** using **iOS Emulator** or **iOS physical device**.

**Comment by russellwheatley** [comment]
Hey @yamauchieduardo, I believe that error is coming from the Firebase server, it isn't something the plugin would arbitrarily respond with. Please create a ticket with iOS Firebase support to resolve the issue and update here if you can.

**Comment by Neiso** [comment]
Running into same issue, everything is correctly set up in firebase settings with quota (3000sms/day) but after 5 logins, got the same error. @yamauchieduardo , did you get a respond from the Firebase Team ?
