### ISSUE TITLE
🐛 [cloud_firestore] CollectionReference<R> withConverter<R extends Object?> can't return null values

### ISSUE THREAD

**Issue by apan1000** [firebase/flutterfire#8082]
## Bug report

**Describe the bug**
`CollectionReference<R> withConverter<R extends Object?>` can't return null values. Instead, we get a "Null check operator used on a null value" error.

### Steps to reproduce

1. Create a CollectionReference using 
```dart
final yourRef = FirebaseFirestore.instance.collection(your_collection_name)
.withConverter<your_model_name?>(
  fromFirestore: (snapshot, _) => null, toFirestore: (message, _) => "Not important"
);
```
2. Notice we are returning a `null` value in the `fromFirestore` function.
3. Get document data with
```dart
yourRef.snapshots().map((snapshot) => snapshot.docs
        .map((doc) {
            return doc.data();
          }
        })
```
or similar.

3. Receive a "Null check operator used on a null value" error

### Expected behavior

I expect `doc.data()` to be able to return a null value, since all types used by CollectionReference extends the nullable `Object?`, e.g. `CollectionReference<R> withConverter<R extends Object?>`.

---

## Additional context

[In `query_document_snapshot.dart`](https://github.com/FirebaseExtended/flutterfire/blob/b1f8ca0f3cab30deab92d0c4ad901ff9ad2eb6f7/packages/cloud_firestore/cloud_firestore/lib/src/query_document_snapshot.dart#L55) we can see the null check operator being used.

**Comment by darshankawar** [comment]
@apan1000 
Can you provide your `flutter doctor -v` and a minimal but complete reproducible code sample ?
I tried the code snippet in plugin's [example](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/cloud_firestore/cloud_firestore/example) but seems I am missing something to properly implement and replicate the issue you reported.

**Comment by apan1000** [comment]
Thank you for looking into it, @darshankawar 

Sure! Here is my `flutter doctor -v` output:
<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.10.1, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.10.1 at /Users/apan1000/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (6 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/apan1000/Library/Android/sdk
    • Platform android-31, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.64.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • SM G960F (mobile) • 1c8b1004a40d7ece • android-arm64  • Android 10 (API 29)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

You can try my fork where I reproduce the issue [here](https://github.com/apan1000/flutterfire/tree/master/packages/cloud_firestore/cloud_firestore/example)

**Comment by darshankawar** [comment]
Thanks for the update and replicable code sample. I do see the same error `Null check operator used on a null value`.

`cloud_firestore: ^3.1.8`
`Channel master, 2.11.0-0.0.pre.581`

**Comment by exaby73** [comment]
Deduping with https://github.com/firebase/flutterfire/issues/7264
