### ISSUE TITLE
🐛 [FIREBASE_STORAGE] Different exceptions across platforms (Android and iOS).

### ISSUE THREAD

**Issue by yamauchieduardo** [firebase/flutterfire#8113]
I notice different errors/exceptions across the Platform when a Firebase Storage deny access, like the issue #8066 but using Firebase Storage.

The exceptions are different by the platform Android and iOS.

This occurs in two cases:

The first case happen when a User **WITH AUTORIZATION** (by Firebase Storage Rules)  try to read a file that **DOESN'T EXIST** a PlatormException is throw.

Using Android emulator/physical device:

```dart
PlatformException(
  code: "object-not-found",
  message: "com.google.firebase.storage.StorageException: Object does not exist at location.",
  details: {"message": "No object exists at the desired reference."},
);
```

<details>
  <summary>Debug image</summary>
 
![arquivo não existe e usuário tem autorização de leitura Android](https://user-images.githubusercontent.com/44825178/154582777-73cb6ea2-df01-415b-853a-6487f1b659f2.png)
</details>

Using iOS emulator/physical device:

```dart
PlatformException(
  code: "firebase_storage",
  message: "No object exists at the desired reference.",
  details: {"message": "No object exists at the desired reference."},
);
```

<details>
  <summary>Debug image</summary>
 
![arquivo não existe e usuário tem autorização de leitura iOS](https://user-images.githubusercontent.com/44825178/154582796-7c35715b-4d24-430f-8c15-edf5d1cc7b7e.png)
</details>

The second case happen when a User **WITHOUT AUTORIZATION** (by Firebase Storage Rules) try to read a file that **EXIST** a PlatormException is throw.

Using Android emulator/physical device:

```dart
PlatformException(
  code: "firebase_storage",
  message: "com.google.firebase.storage.StorageException: User does not have permission to access this object.",
  details: {
    "code": "unauthorized",
    "message": "User is not authorized to perform the desired action."
  },
);
```

<details>
  <summary>Debug image</summary>
 
![arquivo existe, mas usuario não tem autorização de leitura Android](https://user-images.githubusercontent.com/44825178/154582815-0592defd-2f6a-4a6a-b0f3-4e6f1e9c8a26.png)
</details>

Using iOS emulator/physical device:

```dart
PlatformException(
  code: "unauthorized",
  message: "User is not authorized to perform the desired action.",
  details: {"message": "User is not authorized to perform the desired action."},
);
```

<details>
  <summary>Debug image</summary>
 
![arquivo existe, mas usuario não tem autorização de leitura iOS](https://user-images.githubusercontent.com/44825178/154582831-bb0c6eac-3173-485f-a0f9-64a22d93d093.png)
</details>

I'm aways use the exception code to know the type of exception. Could be nice normalize these exceptions to record or analyze better using tools like analytics, etc.

Adicional information: I test a lot of cases to validade if the Firebase Rules are working in a real scenario using the emulators and devices, and these are the **unique case**s that throw `PlatformException` instead `FirebaseException`.

`firebase_storage: ^10.2.7`
`flutter version: 2.10.`

Regards.

**Comment by darshankawar** [comment]
Thanks for the report. I'll treat this more of a documentation and enhancement issue to make the `platformexception` messages similar across android and iOS. Similar to https://github.com/FirebaseExtended/flutterfire/issues/8066.

/cc @russellwheatley

**Comment by russellwheatley** [comment]
Closing this out for an issue that already tracks Storage exception message handling: https://github.com/firebase/flutterfire/issues/7474
