### ISSUE TITLE
🐛 [firebase_analytics]   Google analytics items array a not showing in the console

### ISSUE THREAD

**Issue by rashmisridar** [firebase/flutterfire#8138]
Hi,

The event name "add_to_cart" parameter items array does not show in the Google analytics console -> Event -> Parameters  . But it shows in the debug view.
![analytics](https://user-images.githubusercontent.com/8536749/154964955-f61b4a86-c123-4b2e-8fb6-8f0db5f5635a.jpeg)

Using "logEvent" 

```
await FirebaseAnalytics.instance
        .logEvent(name: 'add_to_cart', parameters: params)
```

Flutter Plugin,

firebase_analytics: ^9.1.0

Flutter Doctor :

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 6.1.7601], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Chrome - develop for the web
[√] Android Studio (version 4.1)
[√] Connected device (3 available)

! Doctor found issues in 1 category.

**Comment by darshankawar** [comment]
@rashmisridar 
What's the parameter type are you passing with `parameters: params` ?
Does `params` represent `<String, dynamic>` ?

If yes, can you please provide a demo data of `params` you are passing ?

**Comment by rashmisridar** [comment]
Map<String, dynamic> launchScreen = Map();
    Map<String, dynamic> itemDetail = Map();

    launchScreen.putIfAbsent("currency", () => "");
    launchScreen.putIfAbsent(
        "value", () => );

    itemDetail.putIfAbsent(
        "item_name", () => "name");
    itemDetail.putIfAbsent(
        "item_category", () => "");
    itemDetail.putIfAbsent(
        "location_id", () => "");
    itemDetail.putIfAbsent(
        "price", () => "price");
    launchScreen.putIfAbsent("items", () => itemDetail);
    FirebaseAnalytics().logEventData(
        'add_to_cart', launchScreen);

**Comment by darshankawar** [comment]
@rashmisridar 
Thanks for further details. Can you upgrade to latest stable (2.10.2) and try again ?
Also, please provide a complete code sample that we can directly run, because using the above code snippet, I wasn't able to replicate the behavior.

**Comment by rashmisridar** [comment]
@darshankawar 
Ok Sure

**Comment by rashmisridar** [comment]
@darshankawar 
Now use the latest flutter SDK as you suggested. 

A code sample is shared below.
https://gist.github.com/rashmisridar/cda238c2496c61f20918899a96d335fd


  Map<String, dynamic> params = Map<String,dynamic>();
                Map<String, dynamic> itemsData = Map<String,dynamic>();
                itemsData.putIfAbsent("itemName", () => "Socks");
                itemsData.putIfAbsent("itemId", () => "xjw73ndnw");
                itemsData.putIfAbsent("price", () => 10.0);
                params.putIfAbsent("value", () => 10.0);
                params.putIfAbsent("currency", () => "INR");
                params.putIfAbsent("items", () => itemsData);
                await FirebaseAnalytics.instance.logEvent(name:"add_to_cart",
                  parameters: params,
                );
                
                item data not showing an issue. 
                Issues :- 
               
                1.  "value" key-value showing in the debug view but in the Total revenue column in the google analytics not showing. 
               Issue screenshot  https://i.stack.imgur.com/fsTam.png
               2.  In the "item" array price value passing as 10.0 but in debug view showing as 
                
            
![data1](https://user-images.githubusercontent.com/8536749/155332526-45e5c624-12e5-4a25-89e0-1a96c285754c.jpeg)

**Comment by darshankawar** [comment]
Thanks for the details. Keeping it open for further insights from the team.

Below issues reported:

1.  "value" key-value showing in the debug view but in the Total revenue column in the google analytics not showing. 
           Issue screenshot  https://i.stack.imgur.com/fsTam.png
2.  In the "item" array price value passing as 10.0 but in debug view showing as 1000000 as shared in the screen shot

/cc @russellwheatley

**Comment by russellwheatley** [comment]
Hey @rashmisridar,  if it shows in the debug view, but it doesn't show in the GA console, then I'd raise this issue with Firebase Support to find out why. 

In terms of values being incorrect, could you be specific about which platform (i.e. android, iOS, web), please?

**Comment by rashmisridar** [comment]
Hey @russellwheatley android platform built in flutter framework.

**Comment by darshankawar** [comment]
> then I'd raise this issue with Firebase Support to find out why.

@rashmisridar please raise the GA console issue here: https://firebase.google.com/support and let us know what they say about it.
