### ISSUE TITLE
🐛 [firebase_messaging] Isolates are registering all plugins when launching

### ISSUE THREAD

**Issue by atrope** [firebase/flutterfire#8175]
Hey Guys,

I Am opening the issue here because we pinpointed the error on isolates to be generated by this plugin.

This issue should be a continuation from https://github.com/flutter/flutter/issues/97840 

We should be able to allow/disallow certain plugins from initializing in firebase isolate. I Don't want all 90 plugins that i use to be initialized twice only the 1 or 2 that I need in my background handler.

This can easily lead to hard to debug bugs when an isolate is registered first or second and then we are not able to access that isolate anymore because there was another initialization and the variable where we keep reference was updated and i have no way to find out which isolate reference i should keep.

@darshankawar if you could pinpoint to someone from the team this issue would be great!

Thanks

**Comment by atrope** [comment]
@darshankawar

**Comment by darshankawar** [comment]
Thanks for filing this issue here. 

/cc @russellwheatley The background of this issue is described here: https://github.com/flutter/flutter/issues/97840 and per [this](https://github.com/flutter/flutter/issues/97840#issuecomment-1048292867) issue comment from Flutter team member, this could potentially a plugin issue.

**Comment by atrope** [comment]
Hi @russellwheatley  have you taken a look here?
Thanks

**Comment by atrope** [comment]
@russellwheatley updates on this issue?

**Comment by manhtran-itr** [comment]
My app got the same issue, please check it. My app's plugins cannot send events because of two plugins initialized due to this plugin.

**Comment by atrope** [comment]
Hi, @russellwheatley now that Dart support isolates with plugins, can we check this issue again?

**Comment by russellwheatley** [comment]
Hey @atrope, I followed your [reproduction here](https://github.com/flutter/flutter/issues/97840#issuecomment-1039393732) using  firebase messaging example + path provider dep + local notifications dep but I didn't see the duplicate logs that you observed. Is this still an issue for you?
