### ISSUE TITLE
🐛 [Firebase_messaging][Documentation]:'ChatArguments' isn't defined for the type '_MessagePage'.

### ISSUE THREAD

**Issue by surajsahani** [firebase/flutterfire#8179]
## Bug report

**This is in hand tryout of Ntification Service Mentioned on Documentation* ChatArgument Not found*
I was trying to integrate notification services in my flutter app but while following the documentation i fond ChatArgument was not found. Maybe Some Code scope was not fully disclosed, happy to see if that part will be available.Thank you

### Steps to reproduce

1. Go to Handling Interaction[#](https://firebase.flutter.dev/docs/messaging/notifications/#handling-interaction)
2. Tried copy and paste same to class.
4. See error or incorrect behavior The method 'ChatArguments' isn't defined for the type '_MessagePage'.

### Expected behavior

It should also show What is ChatArgument and so i can add that value also.

**Comment by darshankawar** [comment]
Thanks for the report.
I tried to see if the code snippet is part of the flutter firebase codelab, but it isn't and using it as-is does throw me the same error as you reported, ie, `'ChatArguments' isn't defined for the type '_MessagePage'.`.

I'll label it as a documentation issue.
