### ISSUE TITLE
[Firebase_auth]:Add Documentation for linkWithPopup

### ISSUE THREAD

**Issue by jbryanh** [firebase/flutterfire#8196]
Suggest adding documentation or at least a mention for linkWithPopup, docs don't mention it anywhere and with Flutter web it's a requirement for linking accounts.

**Comment by russellwheatley** [comment]
We have this now in the federated auth setup here: https://firebase.google.com/docs/auth/flutter/federated-auth

Under "Linking an Authentication Provider" header
