### ISSUE TITLE
🐛 [flutterfire_ui] sign up/register failing with social media on RegisterScreen but not on SignInScreen

### ISSUE THREAD

**Issue by DennisKragekjaer** [firebase/flutterfire#8219]
## Bug report

I have just implemented the SIGN IN screen. Available auth methods are email, Facebook, Apple and Google.

Everything works as intended, I can log in with email, social media. (Actually also signup with social media.

But there is a text link saying "Register", and when tapped it show the SIGN UP/Register screen. This screen is **also** showing Facebook and other social media buttons, but an error occurs when tapping these (Exception is about state AuthAction.signUp).

AuthAction.signUp is not supported by OAuthFlow

So what did I misunderstand here or  is it a bug?

**Comment by darshankawar** [comment]
@DennisKragekjaer 
Can you run the plugin [example](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/flutterfire_ui/example) and see if you get same error ? If not, you can cross-check the implementation to see if there's anything you missed at your end.

**Comment by DennisKragekjaer** [comment]
@darshankawar Actually I just had a videochat with another flutter developer, and he is facing the same problem, not on web but on mobile device.
