### ISSUE TITLE
🐛 [firebase_messaging] getInitialMessage() does not work on release mode

### ISSUE THREAD

**Issue by Rizardomon** [firebase/flutterfire#8234]
## Bug report

I am creating a function so that when the user clicks on the notification he is redirected to a specific page of the application, the function works perfectly in debug mode, but when I put it in release mode when I click on the notification there is only a black screen and nothing happens.
Even when the function is empty, the app also only opens the black screen and nothing happens.

I also tried to apply the override, but it didn't change either.

```
dependency_overrides:
  firebase_messaging_platform_interface: 3.1.6
```

```
firebase_core: 1.10.0
firebase_core_web: 1.6.0
firebase_messaging: 11.2.7
firebase_messaging_web: 2.2.8
```

**My getInitialMessage function:**

```
  checkForInitialMessage() async {
    await Firebase.initializeApp();
    RemoteMessage? initialMessage =
        await FirebaseMessaging.instance.getInitialMessage();

    if (initialMessage != null) {
      // Handle data message
      final payload = initialMessage.data;

      final String place = payload['place'];
      final String bookingNumber = payload['booking'];

       await getBookingModelFromPush(place, bookingNumber);
    
    } else {
      throw Exception('Message data not contain data');
    }
  }
```

```
Future getBookingModelFromPush(String place, String bookingNumber) async {
    BookingsModel bookingModel;
    PlaceModel placeModel;

    bookingModel = await FirebaseFirestore.instance
        .collection('place')
        .doc(place)
        .collection('booking')
        .doc(bookingNumber)
        .get()
        .then((value) {
      return BookingsModel.fromJson(value.data()!);
    });

    placeModel = await FirebaseFirestore.instance
        .collection('place')
        .doc(place)
        .get()
        .then((value) {
      return PlaceModel.fromDocument(value);
    });

    await App.fluxStoreNavigatorKey.currentState!.pushNamed(
      RouteList.withdrawBooking,
      arguments: ArgumentsToModalRoute(
        place: place,
        bookingData: bookingModel,
        context: 'retirada',
        unit: bookingModel.unit,
        typePlace: placeModel.typePlace,
        type: placeModel.type,
      ),
    );
  }
```

### Flutter doctor

![image](https://user-images.githubusercontent.com/57680110/157241873-5fe66a8f-18ad-4edf-86ba-c5dbb831f437.png)

**Comment by darshankawar** [comment]
@Rizardomon 
Thanks for the report.
Is this on Android or iOS ?

Also, you seem to be on older version of stable (2.2.0). I suggest you to upgrade to latest stable or master to get latest features available from the plugins. Since you are on older version, the latest versions of the plugin may not work properly on it.

**Comment by Rizardomon** [comment]
This is in Android and I will se about the upgrade to the latest version of stable.
