### ISSUE TITLE
[flutterfire_ui] In sign-in screen, email string value should be auto-trimmed.

### ISSUE THREAD

**Issue by omarelb** [firebase/flutterfire#8267]
In the email field of the sign-in screen, when an input email ends with a whitespace, it is regarded as an invalid email format.

However, this whitespace is usually automatically added by an autofill keyboard. For a user, it is hard to see the error in the email as it is caused by a whitespace. To me, it makes more sense to automatically trim the input email and pass that on to the server instead of giving an error.

**Comment by darshankawar** [comment]
Treating this as an enhancement.

**Comment by alarmatwork** [comment]
A lot of customers get stuck with this.. as autocomplete on Android adds space to the end of email address automatically.

**Comment by omarelb** [comment]
Hi @darshankawar, I'd be happy to make a PR for this, though I've never done so before..

It is probably just a one-line change, so maybe it's easier if an already existing contributor can test it out?

I believe the line to be changed is the following:
https://github.com/FirebaseExtended/flutterfire/blob/945a53b6da9d9b5be34c25a31245370e39ecd2fa/packages/flutterfire_ui/lib/src/auth/widgets/email_form.dart#L100

Here, 
```dart
final email = widget.email ?? emailCtrl.text;
```
should be changed to
```dart
final email = widget.email ?? emailCtrl.text.trim();
```
or alternatively
```dart
final email = (widget.email ?? emailCtrl.text).trim();
```

**Comment by alarmatwork** [comment]
In flutterfire_ui 4.0 release notes it says that email trimming feature is included. 
But it seems that in reality it does not do the job properly with email/password login form. Still says that email is incorrect and colours it error red.
