### ISSUE TITLE
Firebase messaging not working [not receiving notfications] but app connected to firebase

### ISSUE THREAD

**Issue by kavyabhargava** [firebase/flutterfire#8269]
### Discussed in https://github.com/FirebaseExtended/flutterfire/discussions/8257

<div type='discussions-op-text'>

<sup>Originally posted by **kavyabhargava** March 11, 2022</sup>
I was following a tutorial for Firebase push notifications. I followed all the steps: Connecting app to Firebase, and importing packages (Firebase messaging and Firebase push notifications). I tried sending several notifications, but it did not work.

I have added :

Googleservices.json file in android/app
apply plugin: 'com.google.gms.google-services' added this in build.gradle under android/app
classpath 'com.google.gms:google-services:4.3.10' in android/build.gradle

I know my app is connected to Firebase as I am receiving data from Cloud Firestore. Authentication also works and I am also able to write data to storage:

My main.dart:

```
void main() async {
WidgetsFlutterBinding.ensureInitialized();
await Firebase.initializeApp(
// Added actual values
options: const FirebaseOptions(
apiKey: "have added this ",
appId: "have added this",
messagingSenderId: "have added this",
projectId: "have added this",
storageBucket: "have added this",
),
);
runApp(const MyApp());
}

class MyApp extends StatefulWidget {
const MyApp({Key? key}) : super(key: key);

@OverRide
State createState() => _MyAppState();
}

class _MyAppState extends State {
@OverRide
void initState() {
super.initState();

FirebaseMessaging.instance
    .getInitialMessage(); /this helps code below work great

FirebaseMessaging.onMessage.listen((message) {
  if (message.notification != null) {
    print(message.notification!.body);
    print(message.notification!.title);
  }
}); 
FirebaseMessaging.onMessageOpenedApp.listen((message) {
 
  final routeFromMessage = message.data['route'];

  print(routeFromMessage);
});
}

@OverRide
Widget build(BuildContext context) {
return ChangeNotifierProvider(
create: (context) => GoogleSignInProvider(),
child: OverlaySupport(
child: MaterialApp(
title: 'News_App_admin',
theme: ThemeData(
buttonTheme: const ButtonThemeData(minWidth: 80),
primarySwatch: Colors.blue,
secondaryHeaderColor: const Color.fromARGB(255, 75, 177, 78),
),
home: // MyHomePage(title: 'Home page'),
StreamBuilder(
builder: (ctx, userSnapshot) {
if (userSnapshot.hasError) {
Center(
child: Text('Unknown Error'),
);
}
if (userSnapshot.hasData) {

              return bottomNavigationBar();
            }
            return const Auth_Screen();
          },
          stream: FirebaseAuth.instance.authStateChanges(),
        ) 
}
}</div>
```

**Comment by kavyabhargava** [comment]
Posting main.dart again as its not clear in above

`void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    // Added actual values
    options: const FirebaseOptions(
      apiKey: "have added this ",
      appId: "have added this",
      messagingSenderId: "have added this",
      projectId: "have added this",
      storageBucket: "have added this",
    ),
  );
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    super.initState();

    FirebaseMessaging.instance
        .getInitialMessage(); /this helps code below work great

    FirebaseMessaging.onMessage.listen((message) {
      if (message.notification != null) {
        print(message.notification!.body);
        print(message.notification!.title);
      }
    }); 
    FirebaseMessaging.onMessageOpenedApp.listen((message) {
     
      final routeFromMessage = message.data['route'];

      print(routeFromMessage);
    });
  } 

  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider(
      create: (context) => GoogleSignInProvider(),
      child: OverlaySupport(
        child: MaterialApp(
            title: 'News_App_admin',
            theme: ThemeData(
              buttonTheme: const ButtonThemeData(minWidth: 80),
              primarySwatch: Colors.blue,
              secondaryHeaderColor: const Color.fromARGB(255, 75, 177, 78),
            ),
            home: // MyHomePage(title: 'Home page'),
                StreamBuilder(
              builder: (ctx, userSnapshot) {
                if (userSnapshot.hasError) {
                  Center(
                    child: Text('Unknown Error'),
                  );
                }
                if (userSnapshot.hasData) {
                 
                  return bottomNavigationBar();
                }
                return const Auth_Screen();
              },
              stream: FirebaseAuth.instance.authStateChanges(),
            ) 
  }
}`

**Comment by darshankawar** [comment]
@kavyabhargava 
Did you follow all the steps correctly as mentioned in the [document](https://firebase.flutter.dev/docs/messaging/overview/) to set up / config ?

When you say not working, does it throw any error in the console or log that has any error ?
Can you confirm which stream is not working and which one is working (e.g: background, foreground or terminated) ?
Can you also provide `flutter doctor -v` and plugin version you are using ?

**Comment by kavyabhargava** [comment]
[√] Flutter (Channel stable, 2.10.2, on Microsoft Windows [Version 10.0.19044.1586], locale en-US)
    • Flutter version 2.10.2 at D:\flutter_windows_2.5.1-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (4 weeks ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Kavya bhargava\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.65.2)
    • VS Code at C:\Users\Kavya bhargava\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.36.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1586]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 99.0.4844.51
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 99.0.1150.39

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

**Comment by kavyabhargava** [comment]
What is the plugin version??  firebase_messaging: ^11.2.8
  flutter_local_notifications: ^9.3.2, this??

**Comment by darshankawar** [comment]
> Did you follow all the steps correctly as mentioned in the [document](https://firebase.flutter.dev/docs/messaging/overview/) to set up / config ?
> 
> When you say not working, does it throw any error in the console or log that has any error ? Can you confirm which stream is not working and which one is working (e.g: background, foreground or terminated) ?

@kavyabhargava

**Comment by kavyabhargava** [comment]
Yes, I followed steps from this document, when I was setting up my app for notifications.

I can not see any error from firebase, the app is also building fine so no build error. Right at this point, I am not seeing a notification in any state.

**Comment by darshankawar** [comment]
@kavyabhargava 
How are you sending notifications ? Through firebase console, admin SdK or through API (e.g Postman) ?
Does any of the streams such as `onBackgroundMessageHandler`, `onMessageAppOpened` or `onForground` gets called when you send a notification ?
Please read through this and see if you are doing this correctly https://firebase.flutter.dev/docs/messaging/notifications

**Comment by kavyabhargava** [comment]
FlutterFirebaseMessagingBackgroundService started!  : Getting this

I am sending notifications through the firebase console

**Comment by darshankawar** [comment]
@kavyabhargava 
What Android OS version are you using ?

Can you try something like below code and see if it helps ? You'll need to update it as applicable:

<details>
<summary> code sample </summary>

```

Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp();
  print('Handling a background message ${message.messageId}');
}

late AndroidNotificationChannel channel;
late FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

  if (!kIsWeb) {
    channel = const AndroidNotificationChannel(
      'high_importance_channel', // id
      'High Importance Notifications', // title
      //'This channel is used for important notifications.', // description
      importance: Importance.high,
    );
    flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();
    await flutterLocalNotificationsPlugin
        .resolvePlatformSpecificImplementation<
        AndroidFlutterLocalNotificationsPlugin>()
        ?.createNotificationChannel(channel);
    await FirebaseMessaging.instance
        .setForegroundNotificationPresentationOptions(
      alert: true,
      badge: true,
      sound: true,
    );
  }
  runApp(MyApp());
}

class MyApp extends StatefulWidget{
  _MyAppState createState()=>_MyAppState();
}

class _MyAppState extends State<MyApp> {
 
  @override
  void initState() async{
    super.initState();
    RemoteMessage? initialMessage = await FirebaseMessaging.instance.getInitialMessage();
    if (initialMessage != null) {
      _handleMessage(initialMessage);
      print("message not null");
    }
    FirebaseMessaging.onMessageOpenedApp.listen(_handleMessage);

    FirebaseMessaging.onMessage.listen((RemoteMessage message) {
      RemoteNotification? notification = message.notification;
      AndroidNotification? android = message.notification?.android;
      if (notification != null && android != null) {
        flutterLocalNotificationsPlugin.show(
            notification.hashCode,
            notification.title,
            notification.body,
            NotificationDetails(
              android: AndroidNotificationDetails(
                channel.id,
                channel.name,
                //channel.description,
                icon: android.smallIcon,
                // other properties...
              ),
            ));
      }
    });
    FirebaseMessaging.onMessageOpenedApp.listen((RemoteMessage message) {
      print('A new onMessageOpenedApp event was published!');
      // Navigator.pushNamed(context, '/message',
      //     arguments: MessageArguments(message, true));
    });
 }

  @override
  Widget build(BuildContext context) {
    .....
  }
}

```
</details>

In manifest file:
```

<meta-data
           android:name="com.google.firebase.messaging.default_notification_channel_id"
           android:value="high_importance_channel" />

```
