### ISSUE TITLE
[flutterfire_ui] no sign in scopes for Google Sign-In Provider

### ISSUE THREAD

**Issue by TheLonelyNull** [firebase/flutterfire#8270]
We recently moved to flutterfire_ui from our own custom implementation. However, we can no longer access a user's email when signing in with Google Sign-In and the Identifier column in the Firebase console is empty. We suspect this is due to not specifying the email scope when configuring google sign-in. Is there some setup step we are missing or is configuring scopes for google sign-in not possible with flutterfire_ui?

Below is our minimum reproducible example:

```dart
import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutterfire_ui/auth.dart';

class AuthGate extends StatelessWidget {
  final Widget homeScreen;
  const AuthGate({Key? key, required this.homeScreen}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        // User is not signed in
        if (!snapshot.hasData) {
          return SignInScreen(
            providerConfigs: [
              EmailProviderConfiguration(),
              GoogleProviderConfiguration(
                clientId:
                    "XXX-XXX,
              ),
            ],
          );
        }

        // Render your application if authenticated
        return homeScreen;
      },
    );
  }
}
```

To reproduce simply log in with goolge sign-in and inspect the Firebase User object. There is no email directly under user.email or under user.providerData

**Comment by darshankawar** [comment]
@TheLonelyNull 
Can you provide plugin version you are using that shows the behavior ?

**Comment by TheLonelyNull** [comment]
@darshankawar Sure its `flutterfire_ui: ^0.3.6`
