### ISSUE TITLE
🐛 [firebase_messaging] All notifications cleared when app enters foreground or when user interacts with any notification (iOS)

### ISSUE THREAD

**Issue by Petri-Oosthuizen** [firebase/flutterfire#8272]
# Problem

All push notifications (non-data) sent to an iOS app through FCM are cleared when the app enters the foreground. It is similar to the issue fixed in [#6.0.16](https://pub.dev/packages/firebase_messaging/changelog#6016). This is working fine on android. 
Another strange behaviour is when you clear any notification from your app all the notifications from your app are removed.

# Reproduce

1. Send multiple notifications to the app with `apns.payload.aps.badge` set a a number > 0.
3. Swipe down over the left-hand side of the status bar to reveal notification center. The notifications should be listed here.
2. Open the app from the home screen
3. Swipe down over the left-hand side of the status bar to reveal notification center.  The notifications have now been removed.

# Expected behaviour

Notifications should remain in the notification center until the user interacts with them.

Note: I'm not using [flutter_local_notifications](https://pub.dev/packages/flutter_local_notifications) or [awesome_notifications](https://pub.dev/packages/awesome_notifications).

Note 2: I only tested this on iOS 15+

Note 3: I'm not using APNS to send the notifications, I'm relying on FCM to display notifications.

Another strange behaviour is when you clear any notification from your app all the notifications from your app are removed.

**Comment by darshankawar** [comment]
@Petri-Oosthuizen 
Thanks for the detailed report. Looking at the use case you highlighted, it seems to be similar to an old issue: https://github.com/FirebaseExtended/flutterfire/issues/114.
Can you take a look at it and see if any of the comments / solution mentioned still resonates with your case ?

**Comment by Petri-Oosthuizen** [comment]
I have a strong suspicion it has something to do with the app badge being set (to zero?) by firebase messaging. When I have a list of notifications whenever I interact with any of them all of them disappear.

Do we have any control over this through the firebase messaging package API?

The solutions mentioned are [modifying platform code](https://github.com/FirebaseExtended/flutterfire/issues/114#issuecomment-635852425), [firebase files](https://github.com/FirebaseExtended/flutterfire/issues/114#issuecomment-671446794) or [adding an additional package](https://github.com/FirebaseExtended/flutterfire/issues/114#issuecomment-634532793) (flutter_local_notifications), I don't think this should be necessary for my usecase.

**Comment by darshankawar** [comment]
Thanks for the feedback.
i don't see reference to app badge in the latest code here https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/ios/Classes/FLTFirebaseMessagingPlugin.m so I am not sure what could be causing it.

I'm keeping it open and labeling for further insights from the team. Would be interesting to know the root-cause of this.

/cc @russellwheatley

**Comment by russellwheatley** [comment]
hmmm, I did not observe the same behaviour. I sent push notifications via nodejs admin SDK script:

```js
const admin = require('firebase-admin');
// Get service account key from firebase console
const serviceAccount = require('../ff-e2e-service.json');
admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
});
const iosToken = 'TOKEN';
admin
.messaging()
.send(
  {
    token: iosToken,
    data: {
      something:'another',
    },
    notification: {
      title: 'blah',
      body: 'Great content',
    },
    android: {
      // Required for background/terminated app state messages on Android
      priority: 'high',
    },
    apns: {
      payload: {
        aps: {
          // Required for background/terminated app state messages on iOS
          contentAvailable: true,
          badge: 1,
        }
      },
    },
  },
  
)
```


I kept the badge number at one. I also pressed the notification which opened the app, when I returned to the notification centre, the other notifications remained.
