### ISSUE TITLE
🐛 [  firebase_core: ^1.5.0   cloud_firestore: ^3.1.7]  Tremendous READS during Read operations

### ISSUE THREAD

**Issue by officialFlutterDeveloper** [firebase/flutterfire#8276]
## Bug report

**( this was my previous bug report that was partially fixed before if I made a 200 document write operation I would have 201 writes and 1.2k reads / this has been fixed recently BUT if I do a single read operation to get those 200 it the read count sky rockets to 900  I made a update on the previous issue I submitted but after having no update in 4 days I wanted to make a new bug request kindly look into this )**

**Describe the bug**
even if I do write operations let alone read operations the READ counts goes insane

I made a fresh new flutter project and fresh new firebase account so I can monitor from 0 
the whole flutter project had 1 global variable (final fireStoreGlobal = FirebaseFirestore.instance; ) 1 button and that 1 button performed the following function which is a loop to add 200 documents each document with 3 fields 

the widget/function was 

### Center(
  child: ElevatedButton(
      onPressed: () async {
        for (int i = 0; i < 201; i++) {
          String uiD = Uuid().v1();

          fireStoreGlobal.collection('DemoList').doc(uiD).set({
            'Link': 'Link',
            'Description': 'Description',
            'Name': 'Name'
          });
        }
      },
      child: Text('Add')),
),

then I waited an hour and then I went to usage and saw TODAYS usage and it said 200 writes ( that works fine since 200 documents were added ) but then it said **1.2k READS**!!! where did these **READS** come from? 

### Steps to reproduce

1. Create a fresh new firebase project / use a project that isn't use so you can accurately monitor todays usage
2. Create a fresh new flutter project / use a project that does not have perform anyother write read other than the button 
3. Create a button with the following ontap function   onPressed: () async {
        for (int i = 0; i < 201; i++) {
          String uiD = Uuid().v1();

          fireStoreGlobal.collection('DemoList').doc(uiD).set({
            'Link': 'Link',
            'Description': 'Description',
            'Name': 'Name'
          });
        }
4. See your usage  see after an hour or so because the usage comes in gradually not all at once

### Expected behavior

For that loop function only 200 Writes should be made. 0 deletes. 0 reads 

and if I call all those 200 documents then only 200 documents reads not 200*3

### Sample project

NIL

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.5.1 20G80 darwin-arm, locale en-GB)
    • Flutter version 2.0.6 at /Users/farhan/Developer/flutter
    • Framework revision 1d9032c7e1 (10 months ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/farhan/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.



     Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.2
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the webde.app/Contents/Developer
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (2 available)
    • iPhone 12 (mobile) • A0C128D8-E098-412A-8A5B-A7248B6147AE • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5
      (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 98.0.4758.102


• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
  firebase_core: ^1.5.0
  cloud_firestore: ^3.1.7
  uuid: ^3.0.5

```

</details>

---

**Comment by darshankawar** [comment]
@officialFlutterDeveloper 
`Channel stable, 2.0.6`. You are on very old version of framework and using old plugin versions too. 
Please upgrade to latest stable (2.10.3) along with latest plugin versions and try again to see if issue still persists or not.


`See your usage see after an hour or so because the usage comes in gradually not all at once` Can you provide the log spawn of this ?

Thanks.

**Comment by officialFlutterDeveloper** [comment]
@darshankawar 

following is my flutter doctor --verbose


`[✓] Flutter (Channel stable, 2.10.3, on macOS 11.5.1 20G80 darwin-arm, locale en-GB)
    • Flutter version 2.10.3 at /Users/farhanlatif/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (2 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/farhanlatif/Library/Android/sdk
    • Platform android-32, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.65.0)
    • VS Code at /Users/farhanlatif/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • iPhone 13 (mobile) • 0884AC7E-AC91-4552-8D96-707177C53B71 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 99.0.4844.51
   
[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
`


can you guide me on how can I get a log spawn?

**Comment by darshankawar** [comment]
> can you guide me on how can I get a log spawn?

I was referring to your this sentence `See your usage see after an hour or so because the usage comes in gradually not all at once`. Where are you seeing the usage that leads to your claim that you are getting tremendous reads during read / write operations ? Just share those logs.

**Comment by officialFlutterDeveloper** [comment]
<img width="923" alt="158014925-7a7a69af-22c2-4f76-8695-85e02d2ab422" src="https://user-images.githubusercontent.com/82877513/158806109-36a3dc8c-0c63-4db7-b3e0-cdc64ace4e0a.png">


I see the usage from the usage options in firebase console
