### ISSUE TITLE
🐛 [firebase_messaging] Notification is not displayed when in background

### ISSUE THREAD

**Issue by cturn-dev** [firebase/flutterfire#8301]
## Bug report

In android release mode, when compiled with the following options:

flutter build apk --release --split-debug-info=/tmp/sym --tree-shake-icons

In background, app cannot display notifications but logs this error:

Dart Unhandled Exception: NoSuchMethodError: No top-level getter '_firebaseMessagingCallbackDispatcher' declared.

My workaround:
@pragma('vm:entry-point')
void _firebaseMessagingCallbackDispatcher()

---

### Flutter doctor
<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.10.3, on Manjaro Linux 5.15.28-1-MANJARO, locale fr_FR.utf8)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

```

</details>

---

**Comment by darshankawar** [comment]
@cturn-dev 
Does it also occur in debug mode too ? ie, `flutter build apk --debug --split-debug-info=/tmp/sym --tree-shake-icons`.

Also, can you try the same on latest master and see if issue still persists ?

**Comment by cturn-dev** [comment]
> Does it also occur in debug mode too ? ie, `flutter build apk --debug --split-debug-info=/tmp/sym --tree-shake-icons`.

No

> Also, can you try the same on latest master and see if issue still persists ?

Tried latest master, same issue

**Comment by darshankawar** [comment]
@cturn-dev 
Can you provide us a [minimal reproducible code sample](
) that we can use and run to verify this ?
