### ISSUE TITLE
[firebase_remote_config] [WEB] art.global.firebase.remoteConfig is not a function

### ISSUE THREAD

**Issue by sgshivamgarg8** [firebase/flutterfire#8308]
When trying to access FirebaseRemoteConfig in Flutter Web, I am getting this error in console "TypeError: dart.global.firebase.remoteConfig is not a function"

Even though official Docs says that remote config is now supported

Using:
```yaml
firebase_core: ^1.3.0
firebase_remote_config: ^2.0.2
```

in index.html 
I have added this line
```html
  <script src="https://www.gstatic.com/firebasejs/8.10.1/firebase-app.js"></script>
```

Please tell me if I am missing something.

In docs there is no code given for Web specifically.

**Comment by sgshivamgarg8** [comment]
TypeError: dart.global.firebase.remoteConfig is not a function
at Object.getRemoteConfigInstance (http://localhost:11966/packages/firebase_remote_config_web/src/interop/firebase_remote_config.dart.lib.js:314:81)
at firebase_remote_config_web.FirebaseRemoteConfigWeb.new.get [_delegate] (http://localhost:11966/packages/firebase_remote_config_web/firebase_remote_config_web.dart.lib.js:76:75)
at firebase_remote_config_web.FirebaseRemoteConfigWeb.new.setDefaults (http://localhost:11966/packages/firebase_remote_config_web/firebase_remote_config_web.dart.lib.js:168:11)
at firebase_remote_config.FirebaseRemoteConfig.__.setDefaults (http://localhost:11966/packages/firebase_remote_config/firebase_remote_config.dart.lib.js:150:30)
at remoteConfig (http://localhost:11966/packages/torrcrow/helpers/remote_config_helper.dart.lib.js:39:28)
    at remoteConfig.next (<anonymous>)
    at http://localhost:11966/dart_sdk.js:42993:33
    at _RootZone.runUnary (http://localhost:11966/dart_sdk.js:42849:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:11966/dart_sdk.js:37417:29)
    at handleValueCallback (http://localhost:11966/dart_sdk.js:38020:49)
    at Function._propagateToListeners (http://localhost:11966/dart_sdk.js:38058:17)
    at async._AsyncCallbackEntry.new.callback (http://localhost:11966/dart_sdk.js:37776:27)
    at Object._microtaskLoop (http://localhost:11966/dart_sdk.js:43153:13)
    at _startMicrotaskLoop (http://localhost:11966/dart_sdk.js:43159:13)
    at http://localhost:11966/dart_sdk.js:38289:9

**Comment by darshankawar** [comment]
@sgshivamgarg8 
Check [this](https://github.com/FirebaseExtended/flutterfire/pull/8139/files) and see if it helps.

**Comment by jumper423** [comment]
> @sgshivamgarg8 Check [this](https://github.com/FirebaseExtended/flutterfire/pull/8139/files) and see if it helps.

This code is already in version 2.0.2, i.e. this cannot be a solution.

**Comment by jumper423** [comment]
My error

```
ERROR ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  ERROR │   ERROR NoSuchMethodError: tried to call a non-function, such as null: 'dart.global.firebase.remoteConfig'
  ERROR ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
  ERROR │ packages/firebase_remote_config_web/src/interop/firebase_remote_config.dart 13:52  getRemoteConfigInstance
  ERROR │ packages/firebase_remote_config_web/firebase_remote_config_web.dart 29:55          get [_delegate]
  ERROR │ packages/firebase_remote_config_web/firebase_remote_config_web.dart 159:24         setConfigSettings
  ERROR │ packages/firebase_remote_config/src/firebase_remote_config.dart 131:22             setConfigSettings
  ERROR │ packages/hugly/services/config.dart 22:25                                          initialize
  ERROR │ dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                 runBody
  ERROR │ dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                 _async
  ERROR │ packages/hugly/services/config.dart 18:26                                          initialize
  ERROR │ packages/hugly/kernel.dart 62:27                                                   _firstInitialization
  ERROR │ dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                 <fn>
  ERROR │ dart-sdk/lib/async/zone.dart 1434:47                                               _rootRunUnary
  ERROR │ dart-sdk/lib/async/zone.dart 1335:19                                               runUnary
  ERROR │ dart-sdk/lib/async/future_impl.dart 159:18                                         handleValue
  ERROR │ dart-sdk/lib/async/future_impl.dart 766:44                                         handleValueCallback
  ERROR │ dart-sdk/lib/async/future_impl.dart 795:13                                         _propagateToListeners
  ERROR │ dart-sdk/lib/async/future_impl.dart 601:5                                          [_completeWithValue]
  ERROR │ dart-sdk/lib/async/future_impl.dart 639:7                                          <fn>
  ERROR │ dart-sdk/lib/async/zone.dart 1426:13                                               _rootRun
  ERROR │ dart-sdk/lib/async/zone.dart 1328:19                                               run
  ERROR │ dart-sdk/lib/async/zone.dart 1236:7                                                runGuarded
  ERROR │ dart-sdk/lib/async/zone.dart 1276:23                                               callback
  ERROR │ dart-sdk/lib/async/schedule_microtask.dart 40:11                                   _microtaskLoop
  ERROR │ dart-sdk/lib/async/schedule_microtask.dart 49:5                                    _startMicrotaskLoop
  ERROR │ dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15                <fn>
  ```

**Comment by bhavyalatha26** [comment]
@jumper423 I too ran into the same issue. Later after digging through the google firebase sdk docs, I realized that I need to also import `firebase-remote-config.js`  in my **index.html**. 

It would be better if they mention this in the flutterfire docs as well

> NOTE: I currently use 7.14.3, but have not tested this with 8.10.1

```js
 <!-- The core Firebase JS SDK is always required and must be listed first -->
 <script src="https://www.gstatic.com/firebasejs/7.14.3/firebase-app.js"></script>
 <!--  Add the firebase products that you want to use -->
 <script src="https://www.gstatic.com/firebasejs/7.14.3/firebase-remote-config.js"></script>
```

**Comment by darshankawar** [comment]
@sgshivamgarg8 
Check above solution and see if it helps to resolve the issue.

**Comment by sgshivamgarg8** [comment]
> @sgshivamgarg8 Check above solution and see if it helps to resolve the issue.

sure, I will check it and update

**Comment by jumper423** [comment]
For me @bhavyalatha26's suggestion worked. The errors are gone.

**Comment by sgshivamgarg8** [comment]
Yes adding 

```html
<script src="https://www.gstatic.com/firebasejs/8.10.1/firebase-remote-config.js"></script>
```

worked
