### ISSUE TITLE
[📚] https://firebase.flutter.dev/docs/cli/#usage 404s on questionmarks and summary/issues still very unclear

### ISSUE THREAD

**Issue by neiljaywarner** [firebase/flutterfire#8322]
https://firebase.flutter.dev/docs/cli/#usage

1. the question marks are 404s when you click on them - under the crashlytics tab
2a. the first grey box i receive the overall impression 'maybe skip dart only initialization for everything in this table'
2b. the second grey box i receive the overall impression 'maybe it'll be fine, you'll just see some warnings'.

i appreciate the effort at specifics and a table, but crashlytics and analaytics are very core products to pretty much every app. I still can't figure out how to summarize the entire feature of dart-only intialization as a thumbsup or a thumbsdown, and it sounds so awesome, and is awesome for supported use case.

3. If android and ios were to work for analytics and crashlytics but just with some warnings and some mildly unexpected messages in certain places - summary would be yes to new people considering using this.  if not, then it would be "no, wait awhile"

**Comment by darshankawar** [comment]
Clicking question marks for Crashlytics section under usage tries to open https://firebase.flutter.dev/docs/cli/crashlytics/overview#2-optional-platform-integration but gives 404.

/cc @russellwheatley
