### ISSUE TITLE
🐛 [firebase_database] Slow serialization of Java objects in UI thread on the Android native side

### ISSUE THREAD

**Issue by jbxbergdev** [firebase/flutterfire#8326]
## Bug report

In the native part of the plugin on Android, the UI thread can be blocked for significant time when receiving a large number of objects from Firebase. This is caused by object serialization on the Java side taking a long time and because it happens on the main thread. This could be alleviated either by pre-processing the data (e.g. serializing the objects into a byte array), off the main thread, before handing it over to the EventChannel. Or by using a different, more performant way of serializing the Java objects than the default EventChannel mechanism.

### Steps to reproduce

Register an onValue listener to a large (say 10-20k) collection of objects (objects can be fairly simple). UI thread in this case is blocked for 100+ms for each update.

**Comment by darshankawar** [comment]
@jbxbergdev 
Can you provide `flutter doctor -v`, plugin version you are using along with a minimal code sample that shows the issue you are reporting ?

**Comment by jbxbergdev** [comment]
@darshankawar Plugin version is the most current one. You can simply reproduce by registering a listener to a large collection of objects (as I wrote, 10-20k should do) in RTDB. Then register an onValue listener to it or request once() on the collection. With every update event, the UI thread will be blocked for considerable time. You can visually check this with e.g. having a scrollable list that will be unresponsive during the update events.

**Comment by darshankawar** [comment]
@jbxbergdev 
In order to address this issue properly, please provide a minimal code sample that shows the issue you are reporting.

Thanks.

**Comment by jbxbergdev** [comment]
`Column(
      children: [
        StreamBuilder(
          stream: FirebaseDatabase.instance.ref().child('collection_with_many_objects').onValue,
          builder: (context, snapshot) {
            return Container();
          },),
        ListView(children: List.generate(100, (index) => ElevatedButton(onPressed: () {}, child: Text(index.toString()))),)
      ],
    );`
Try scrolling the list while Firebase receives objects.

**Comment by darshankawar** [comment]
Reopening as bot isn't working properly in this repo.

**Comment by darshankawar** [comment]
> In the native part of the plugin on Android, the UI thread can be blocked for significant time when receiving a large number of objects from Firebase

Flutterfire is a wrapper around native firebase sdks and it just sends some data from Dart, which hits the native Firebase SDKs, and sends the data back once they return some data. So I suggest you to open this issue in native firebase sdk github and check what they say about it. https://github.com/firebase/firebase-android-sdk/issues
