### ISSUE TITLE
🐛 [firebase_database ] FirebaseDatabase.instance.purgeOutstandingWrites() this method throws PlatformException

### ISSUE THREAD

**Issue by anilthapa1939** [firebase/flutterfire#8327]
## Bug report

**Describe the bug**
`FirebaseDatabase.instance.purgeOutstandingWrites()`
this method is giving PlatformException saying 

```
----------------FIREBASE CRASHLYTICS----------------
I/flutter (26597): PlatformException(-25, The write was canceled by the user., , null)
```
even try catch block is not catching this exception

**Comment by darshankawar** [comment]
@anilthapa1939 
Is this coming from production or locally from your debug app ?

Can you provide `flutter doctor -v`, plugin version along with complete minimal code sample that triggers this error ?
