### ISSUE TITLE
🐛 [firebase_analytics] Excluding the play-services-ads-identifier

### ISSUE THREAD

**Issue by mericgerceker** [firebase/flutterfire#8337]
## Bug report

**Describe the bug**
Hi, I am using firebase_analytics: ^8.3.1 package. I got a "We found ad SDKs in your app" warning from Google Play, even though my app has no ads. Therefore, I had to add the phrase "Contains ads". I want to remove this phrase.

When I checked I saw that the package uses "play-services-ads-identifier". How can I find a solution?

similar issues:

- https://github.com/invertase/react-native-firebase/issues/3617
- https://github.com/firebase/firebase-android-sdk/issues/2582

**Comment by darshankawar** [comment]
@mericgerceker 
It seems to be issue related to the plugin version you are using. Can you try to upgrade it to latest and try ?
Also see [this](https://stackoverflow.com/questions/33788471/google-play-we-found-ad-sdks-in-your-application) SO link and underlying comments which should help you to fix this behavior.

`Note that the play-services-analytics dependency upon play-services-ads seems to be limited to version 8.1.0. Previous and later versions of play-services-analytics no longer have this transitive dependency, `

Also, closing from here, as this doesn't seem to be specific to firebase_analytics plugin and may be coming from native firebase sdk.
