### ISSUE TITLE
🐛 [FIREBASE_AUTH] Cannot sign in twice with phone number with the emulator

### ISSUE THREAD

**Issue by cedvdb** [firebase/flutterfire#8351]
When using phone authentication with the **firebase emulator and android emulator** the authentication works the first time, the firebase emulator generates an sms code. The second time, if the login is fast enough, no such code is generated and the first code is invalidated.

------------------------

When recording the below gif I noticed the code was actually generated the second time, it is because I did it slowly, keep watching as I tries to do it fast it will fail. Sorry if the gif is a bit slow, I was surprised to see it working at first.

![Recording 2022-03-28 at 16 50 23](https://user-images.githubusercontent.com/22280985/160425246-79ed28a3-0239-40f6-b23a-c9d5947e76c7.gif)

------------------------
I made a repro:

https://github.com/cedvdb/flutter_repros/tree/failing_auth

However it might require some setup:

  - it will require that you remove the firebase configs and initialize with your own project so you can run the emulator . So `firebase init`
  - You'll have to change the values in `firebase_options.dart  android` with the values for firebase config android.
  - Have phone authentication enabled in your fierbase project
  - run emulator with `firebase emulators:start`

 This is blocking for integration testing

**Comment by yuchenshi** [comment]
Let's merge the discussion into https://github.com/firebase/firebase-tools/issues/4290

**Comment by cedvdb** [comment]
I'm not sure if the issue comes from here or the emulator. The issue that I opened in the emulator was originally about something else, ence why I'm issuing one here too as it seemed to fit better.

**Comment by darshankawar** [comment]
@cedvdb 
Thanks for the report and code sample. Can you provide the entire error log ? Its not clear from the gif as exactly the error is. That would help to debug further.

**Comment by cedvdb** [comment]
@darshankawar Do you need more information for me ? This is still in triage, that's why I'm asking.

**Comment by darshankawar** [comment]
Thanks for the update. Keeping it open and labeling it for further insights from the team.

/cc @russellwheatley

**Comment by russellwheatley** [comment]
Hey @cedvdb, as noted by @yuchenshi, this is a `firebase-tools` bug to be resolved. FlutterFire has no control over the issuing of verification codes by the emulator. I'd advise tracking here: https://github.com/firebase/firebase-tools/issues/4290. Thanks.

**Comment by cedvdb** [comment]
@russellwheatley What is related to this repository is that there is no test verifying that it works as expected. There is a test for email authentication but nothing for phone authentication. Also even if there was such  a test it would not have caught it since this happens only on the second try.

Anyway, I think adding some more e2e tests wouldn't hurt here. I did not find those for firestore either.
