### ISSUE TITLE
[firebase_messaging] Notifications are not delivered on iOS device

### ISSUE THREAD

**Issue by PasqualeTotaro** [firebase/flutterfire#8352]
I am trying to implement push Notifications through FlutterFire, on iOS device.

I am using a real device, I followed all the documentation to set up keys, certificates and identifiers.

I tested the app using Firebase "Send Test Message" under Notification. 

I am receiving the message if the app is in Foreground (although not as a push notification) but when the app is in background no push notification appears.

Flutter Doctor as bellow:

`
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3 21E230 darwin-x64, locale en-US)
    • Flutter version 2.10.4 at /Users/-/Documents/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c8----a910 (4 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/-/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • -’s iPhone (mobile) • 00008110-001974160131801E • ios            •
      iOS 15.1.1 19B81
    • Chrome (web)                   • chrome                    • web-javascript •
      Google Chrome 99.0.4844.83

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
`

**Comment by darshankawar** [comment]
@PasqualeTotaro 
Does `onBackgroundHandler` stream gets called or no ? Can you just try to print a text inside the method and see if it gets called or not ?
Can you also provide a sample payload you are sending ?

**Comment by PasqualeTotaro** [comment]
I do have the `onBackgroundHandler` set up, but it is not being called or printing anything (Code pasted below).

```
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  print("Handling a background message: ${message.messageId}");
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  FirebaseMessaging messaging = FirebaseMessaging.instance;

  NotificationSettings settings = await messaging.requestPermission(
    alert: true,
    badge: true,
    sound: true,
    provisional: false,
  );

  await messaging.setForegroundNotificationPresentationOptions(
    alert: true,
    badge: true,
    sound: true,
  );

  messaging.getToken().then((token) {
    print(token); // Print the Token in Console
  });

  FirebaseMessaging.onMessage.listen((RemoteMessage event) {
    print("message recieved");
    print(event.notification.body);
  });

  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

  runApp(MyApp(sheet));
}
```

I am using the default Firebase Messaging online tool to send a test message.
<img width="1028" alt="Screen Shot 2022-03-29 at 11 49 35 AM" src="https://user-images.githubusercontent.com/35729033/160595467-71575e9b-d8e9-4385-aab0-f6b7002ce017.png">

**Comment by darshankawar** [comment]
Is this in debug mode or in release mode ?
See if this issue is similar to yours ? https://github.com/firebase/flutterfire/issues/6290

**Comment by PasqualeTotaro** [comment]
I am testing in debug mode.

The issue is similar, but I also don't see the push notification fired.

To add an another detail, I need to add this line in App Delegate.m

`[FIRApp configure]; `

Otherwise also the onMessage doesn't work.

**Comment by darshankawar** [comment]
@PasqualeTotaro 

Can you also confirm APNs has been setup correctly in your project, iOS/macOS will not work at all without APNs - it must be configured.

Also can you show me how you've setup the onMessage code in your Dart code?

**Comment by PasqualeTotaro** [comment]
I followed the steps here to install all keys and certificates 
https://firebase.flutter.dev/docs/messaging/apple-integration/

<img width="953" alt="Screen Shot 2022-03-30 at 11 50 44 AM" src="https://user-images.githubusercontent.com/35729033/160815365-d02ad630-0ab3-480e-ab42-dfe1a770dbed.png">

The onMessage code is included in the snipped from my previous comment.

Thank you

**Comment by darshankawar** [comment]
@PasqualeTotaro 
Can you try the plugin [example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example) and see using it you still get same behavior ?

**Comment by PasqualeTotaro** [comment]
@google-oss-bot thank you for the message.

I am testing the example now.

Just to make sure I do everything properly, I am assuming I need to create a new App on Firebase and also create new API keys and certificates for iOS. Is that correct?

**Comment by PasqualeTotaro** [comment]
Quick update.

I run tried the example app and I get the same results. I receive messages when the app is in foreground. But no success when the app is in background. 

The Background callback does not get called either.

I need to flag that I could not complete all the steps for iOS configuration. Specifically I cannot register a new App ID.

**Comment by PasqualeTotaro** [comment]
I did more testing with a fresh Flutter App.

Same issue, but I noticed that when send a campaign from Cloud Messaging Dashboard with a badge number, it will be correctly updated on my devise, whether the device is in Foreground or Background.

Very strange. When App is in background, I can see the badge being updated, but still no notification shown or background callback called.

**Comment by darshankawar** [comment]
@PasqualeTotaro 

Try following step by step in firebase.flutter.dev.
https://firebase.flutter.dev/docs/messaging/usage

Are you using `flutter_local_notifications` to show local notifications when received data from FCM ?

**Comment by PasqualeTotaro** [comment]
I already followed the steps in the link provded.

I am not using flutter_local_notifications. Is it needed to display background notifications?

**Comment by PasqualeTotaro** [comment]
Quick update, I have tried to send a notification via Post Man, so I can specify the content_available variable.

The background call back is not called properly, however I still don't see any notification displayed.

Do I need to use flutter_local_notifications for that? Is it not the intended behavior by Cloud Messaging to show the push notification?

**Comment by darshankawar** [comment]
> Do I need to use flutter_local_notifications for that?

Not exactly required but good to have to properly handle heads up notifications.

Do you have `Background fetch` and `remote notifications` checked in XCode ?

**Comment by daisukenagata** [comment]
@darshankawar  

I have the same phenomenon.
It is set in Xcode. Xcode is supported.


<img width="698" alt="スクリーンショット 2022-04-16 22 07 56" src="https://user-images.githubusercontent.com/16457165/163676197-4a1a45c6-0279-4472-8f27-85588697a8e1.png">

It works well in the foreground of iOS.

video rink
https://twitter.com/dbank0208/status/1515315298663997445?s=20&t=br_LcQFwdmf6eCj86ALs7A


This method does not run in the iOS background.

```
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  print('Handling a background message ${message.messageId}');
}
```

**Comment by darshankawar** [comment]
@daisukenagata 
You may be hitting https://github.com/firebase/flutterfire/issues/6290

**Comment by daisukenagata** [comment]
@darshankawar 
Thank you for confirming.
I don't know if it's okay to talk here, 
but let me check. Android has a large Icon image url display method for background and foreground and iOS
I found a way to display the foreground image url, do I need to openly introduce it? If I want to introduce it, 
can I introduce it through Flutter?

The operation is here.
https://user-images.githubusercontent.com/16457165/163712672-a031f7bf-e9f0-4751-b13c-61322a9a7a54.mov

I checked the image image of 300kb or less about 120 times, but it was displayed normally.

**Comment by mariopepe** [comment]
@darshankawar what's the team standing on #6290 do you recognise that there is an issue? Have you been able to reproduce? Is a fix needed? If yes when are you planning to deploy it? Is there a timeline? Thanks

**Comment by PasqualeTotaro** [comment]
Hi everyone, after noodling around I started sending notification from Post Man and find out that in my case the issue was with iOS 15.0.

iOS 15 has now introduced "usage profiles", such as "working", "do not disturb" etc.. That means that beyond giving notification permissions you also need to allow the app **in the current usage profile** to send notifications. Otherwise they will not show.

Maybe it is worth updating the documentation to flag this out, because I am sure a lot of people is encountering the same problem.

**Comment by darshankawar** [comment]
> what's the team standing on #6290 do you recognise that there is an issue?

It has been assigned to the team developer and hopefully it'll be addressed soon.

**Comment by darshankawar** [comment]
@PasqualeTotaro 
Thanks for finding out the root-cause of the issue and sharing the feedback. You can probably create a new issue for documentation purpose so that it can be tracked properly and won't get lost.

Based on your findings, I consider this as resolved.
