### ISSUE TITLE
🐛 [FlutterFirebaseAnalyticsPlugin] Maybe analytics shouldn't be initialized in initInstance, it will cause Firebase to be initialized early

### ISSUE THREAD

**Issue by XXXShaoZi** [firebase/flutterfire#8353]
Maybe analytics shouldn't be initialized in **initInstance**, it will cause Firebase to be initialized early and it will cause a lot of trouble

```
public class FlutterFirebaseAnalyticsPlugin {
  private void initInstance(BinaryMessenger messenger, Context context) {
    //  When Flutter Engine is initialized, Firebase will also be initialized in advance, i
    analytics = FirebaseAnalytics.getInstance(context);
    // ...
  }
}
```

**Comment by darshankawar** [comment]
@XXXShaoZi 
Assuming you are referring to:

https://github.com/firebase/flutterfire/blob/1937f27817acc59dedd85a6d1e0624f49685ef5e/packages/firebase_analytics/firebase_analytics/android/src/main/java/io/flutter/plugins/firebase/analytics/FlutterFirebaseAnalyticsPlugin.java#L35

Can you provide a use case or code sample that shows an issue using this implementation ?
