### ISSUE TITLE
FirebaseMessaging.instance.getInitialMessage() is not triggered when click in terminated state

### ISSUE THREAD

**Issue by Saikiran24** [firebase/flutterfire#8355]
## Bug report

**Describe the bug**

### Steps to reproduce

2. '...'
4. See error or incorrect behavior

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
FirebaseMessaging.instance.getInitialMessage() is not triggered when click in terminated state when we are sending only data{} in message payload without notification {}
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by darshankawar** [comment]
@Saikiran24 
Is this for Android or iOS ?
Can you confirm if you have properly followed all the steps / configuration per document here : https://firebase.flutter.dev/docs/messaging/usage#receiving-messages

Also check this link to understand how the app works when in terminated state. We need to manually open the app if terminated : https://firebase.flutter.dev/docs/messaging/usage#receiving-messages
