### ISSUE TITLE
🐛 [firebase_crashlytics] iOS build error: firebase_app_id_file.json could not be found 

### ISSUE THREAD

**Issue by cuong0993** [firebase/flutterfire#8376]
firebase_crashlytics 2.6.0 could not be built because it needs to read a file firebase_app_id_file.json which is generated by CLI.

https://github.com/firebase/flutterfire/blob/decf2a6bd6259ce4574f399132e571bb3009a5f7/packages/firebase_crashlytics/firebase_crashlytics/ios/crashlytics_add_upload_symbols#L46. (https://github.com/firebase/flutterfire/pull/8157)

I have not used CLI in my project and I think firebase_crashlytics should not depend on CLI.
I prefer a manual setup as in the document https://firebase.flutter.dev/docs/crashlytics/overview#b-ios which gives me more freedom.

If the current implementation is decided, kindly update the website to reflect it.

**Comment by yhong-emporia** [comment]
Also seeing this issue.  To be fair, installing flutterfire cli and running `flutterfire configure` did fix the problem, but I don't think this should have ever been a problem in the first place, especially without any warning or documentation.

**Comment by alexkeramidas** [comment]
Yep, also having this issue.
Locally there is no issue, you can install the CLI and move on but on a CI system its quite a killer of processes.

Because here https://firebase.flutter.dev/docs/manual-installation it says 

```
The new Dart-only initialization is fully backwards compatible with previous versions of FlutterFire - if you have an existing project with manual initialization, this will continue to work.
```

Which is not true.

**Comment by stanleykoz** [comment]
> 

How did you manage to fix this issue? By using flutterfire cli? I am also encountering similar issue when building app via Bitrise

**Comment by alexkeramidas** [comment]
CI for now: I just locked the versions of the packages that are related to flutterfire in pubspec.yaml to the versions of the previous successful build (which was yesterday) just to move on with the build.

Now to update the whole thing for CI, I got two options.

- Wait for a resolution of this ticket and see what should I do. 
- Use the CLI to generate the json files and update every stage build and the build scripts with the corresponding json, after removing the downloaded configurations from the online firebase for each stage (which has a separate application etc).

**Comment by stanleykoz** [comment]
I have managed to resolve this issue simply by running `flutterfire configure` command. Although it's really weird that Google introduces such big changes without any notice. Using CLI simplifies the process of adding firebase to your app but I did my installation some time ago and did it manually.

**Comment by darshankawar** [comment]
Thanks for the report.

https://github.com/firebase/flutterfire/blob/decf2a6bd6259ce4574f399132e571bb3009a5f7/packages/firebase_crashlytics/firebase_crashlytics/ios/crashlytics_add_upload_symbols#L46

https://github.com/firebase/flutterfire/pull/8157

/cc @Salakar

**Comment by petrnymsa** [comment]
Please raise the priority for this. In our app we have integration with flutterfire manually (as it is documented) and now we are experiencing this issue as well.

**Comment by austinn** [comment]
Running `flutterfire configure` doesn't seem to produce `firebase_app_id_file.json` for me. My issue is mainly building for mac. When I run `flutter run -t lib/main_local.dart -d macos`, the build fails. But if I run it in XCode, it works. 

iOS seems to be working just fine

**Comment by cuong0993** [comment]
Please be gentle guys. As @alexkeramidas suggested, you can revert the recent change and specify the 2.5.3 version in the pubspec.yaml file

 firebase_crashlytics: 2.5.3

continue your work and wait for the next change from the team.

**Comment by Turburlar** [comment]
I did not even change my crashlytics version and I got this error. All I did was bump my sdk version in pubspec.yaml, and then bump my cloud_firestore version.

**Comment by cuong0993** [comment]
Please check your pubspec.lock file. It should have 

  firebase_crashlytics:
    dependency: "direct main"
    description:
      name: firebase_crashlytics
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.5.3"
    
 Your configure firebase_crashlytics: ^2.0.6 means that firebase_crashlytics >= 2.0.6.
 You might want to change to firebase_crashlytics: 2.0.6

**Comment by DeToxer** [comment]
@Turburlar I had a similar issue. What i did is that i removed the "^" prefix so that crashlytics is locked to that version. Then I deleted the pubspec.lock file and ran flutter pub get command. Then everything went back to normal.

Like @cuong0993 said, I guess when have to wait for further instructions from the team.

**Comment by WalidChebaro** [comment]
> **FOR USER, HERE IS THE TEMPORARY FIX:**
> 
> ( @petrnymsa , @stanleykoz )
> 
> Steps (with image at the end):
> 
> 0. Open your project on Xcode
> 1. Click on the folder Icon up left
> 2. Then on Runner and then again on Runner Project
> 3. Then go to Build Phases
> 4. Delete or comment out the latest build phase script added by crashlytics....
> 
> **FOR MANTAINERS:**
> 
> @darshankawar every user has a different configuration. Assuming that everyone has a "firebase_app_id_file.json" file at a very specific location in out project is wrong. This bug disrupted my workflow for 1 hour. This is not nice.
> 
> Best
> 
> <img alt="Screenshot 2022-04-01 at 18 11 45" width="500" src="https://user-images.githubusercontent.com/14803862/161302948-640925c6-4954-4e3a-acdf-d15b8e14af06.png">

This might be related to xcode not catching the generated json file maybe an empty firebase_app_id_file.json can fix this issue.

**Comment by elenadoty** [comment]
Hi all - sorry for this issue, we've added an additional check to prevent a Crashlytics run script from being added if the json isn't present. 

Quick question - are you using a Crashlytics script in your Xcode project to upload symbols, or doing it manually?

**Comment by cuong0993** [comment]
Hi @elenadoty, 
Thank you for your prompt action. You don't need to be sorry for anything here :D.

I personally love to do the configuration myself (by writing scripts or even manual).
- Tools like CLI or automatic configuration script will struggle when I have multiple firebase projects for dev/test/prod.
- There are variables (like REVERSED_CLIENT_ID when I use google sign in https://pub.dev/packages/google_sign_in#ios-integration) that need to be available at compile-time and CLI currently cannot handle it.
- I don't want to hard code firebase configurations in my code as CLI does.

This is my thought. I know that tools will help to configure a lot and other people will love it.

**Comment by guinardA** [comment]
Hi,

I updated the firebase crashlytics package to 2.6.1 but I have always this error. 
I also tried downgrading to 2.5.3, but the error remained.

The only solution for now is comment out the latest build phase script added by crashlytics.

**Comment by guinardA** [comment]
@elenadoty, I try with the newest plugin version 2.6.2 and I still have the problem when the script is always added.

**Comment by kkoken** [comment]
I am facing the same issue with `2.6.3`. Downgraded to `2.5.3`

**Comment by elenadoty** [comment]
Hi @guinardA  and @kkoken, can you copy the error logs you're seeing?
