### ISSUE TITLE
🐛 [cloud_firestore] Cloud firestore version 3.1.10 gives error looking for firebase_app_id_file.json

### ISSUE THREAD

**Issue by Turburlar** [firebase/flutterfire#8380]
I just upgraded to cloud_firestore 3.1.11.

Now when I try to run _flutter build ios_ I get the error...

`error: Unable to read file at path /Users/myUser/src/mobile-app/ios/firebase_app_id_file.json`

**Comment by rafaank** [comment]
I managed to get past the issue by installing Flutterfire cli, and then running flutterfire configure which created the required firebase_app_id_file.json

**Comment by parmarravi** [comment]
how to install  Flutterfire cli not able to install on m1 pro MacBook

**Comment by rafaank** [comment]
> Please fix this issue. On Android it works fine while on iOS only we are facing this issue.
> 
> how to install Flutterfire cli not able to install on m1 pro MacBook?

Follow the documentation [here](https://firebase.flutter.dev/docs/cli/) , it worked fine on my MacBook pro

# Install firebase-tools if not already installed
$ npm install -g firebase-tools

# Activate flutterfire-cli
$ dart pub global activate flutterfire_cli

# Run flutterfire configure for your project and it will create a firebase_app_id_file.json in the ios folder
$ flutterfire configure

**Comment by safield** [comment]
Flutter fire cli asked for control of the data of my firebase project. How do I know I can trust this tool not to do some buggy behaviour and jeopardize my data?

**Comment by darshankawar** [comment]
There's a similar open issue describing same issue, https://github.com/firebase/flutterfire/issues/8376

Also, https://github.com/firebase/flutterfire/issues/8376#issuecomment-1086521409

Closing this as duplicate. Please follow-up in linked issue for further updates. If anyone disagrees, write in comments and I'll reopen it.
