### ISSUE TITLE
🐛 [FirebaseDatabaseListView] _CastError

### ISSUE THREAD

**Issue by jneusse** [firebase/flutterfire#8381]
## Bug report

**Describe the bug**
FirebaseDatabaseListView(
        query: usersQuery,
        itemBuilder: (_, snapshot) {
          Map<String, dynamic> user = snapshot.value as Map<String, dynamic>;

          return Text('User name is ${user['name']}');
        },
      )
Trying to cast a Snapshot Im getting this issue

The following _CastError was thrown building:
type '_InternalLinkedHashMap<Object?, Object?>' is not a subtype of type 'Map<String, dynamic>' in type cast

### Steps to reproduce

2. '...'
4. See error or incorrect behavior

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

---

### Flutter doctor

<details><summary>Click To Expand</summary>
```
Run `flutter doctor` and paste the output below:
[✓] Flutter (Channel stable, 2.10.4, on Ubuntu 20.04.4 LTS 5.14.0-1027-oem, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2020.3)
[✓] Android Studio (version 4.2)
[✓] VS Code
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```
</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Could not find a file named "pubspec.yaml" in "/home/jesus-carbon/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.14.0".
```

</details>

---

**Comment by jneusse** [comment]
Forget it... I already solved this
It seems I have to update flutter and Dart.

**Comment by darshankawar** [comment]
Closing this as resolved.
