### ISSUE TITLE
Add e2e tests

### ISSUE THREAD

**Issue by cedvdb** [firebase/flutterfire#8382]
The e2e tests of flutterfire are missing some tests:

  - FirebaseStorage e2e tests are currently commented out
  - There is no e2e tests for Firestore that I could find[ here](https://github.com/firebase/flutterfire/tree/master/tests)
  - Authentication testing is very light (only email authentication)

The tests also use flutter driver but I believe it is soon to be deprecated. So I propose we step up the testing a notch here, it would allow for catching at least most common new issues that arise. When firebase is added to a project, it's essentially responsible for core functionalities, so it being solid is important. 

Also the main idea is that it will prevent a bunch of developers to have to each debug on their own project, essentially all duplicating the work.  Currently flutterfire fails with the emulator on a daily basis for me and it is becoming time consuming, ence this issue (it works very nicely without emulator though).  I could port some of my integration tests to this repository too, that would make failures more apparent as there would be reproducibility.

---------------------------------------------------------------

What I can personally do:

    - uncomment storage tests (duh)
    - add some tests for phone authentication
    
What I probably won't have time for: 

   - fixing existing failing tests
   - firestore tests

**Comment by russellwheatley** [comment]
Hey @cedvdb, we would be happy to review any PR that added more coverage to any of the plugins 💯. Storage tests have been temporarily commented out as there is an issue with the emulator that errors when uploading.

**Comment by cedvdb** [comment]
All right, I will see if my auth tests can be put in here. Note that one of the test will fail.

**Comment by cedvdb** [comment]
@russellwheatley Unfortunately I had little available time to work on those test and could not manage to compile the tests in time (probably something related to java version as I just upgraded to java 11).

If I cannot come back to this shortly I will just leave an hint here that phone_authentication is currently untested, I assume it's because of the emulator. However you can retrieve the sms code from the emulator just by calling its endpoint (which I do in my own integration tests).

Something like this

```dart
  Future<String> retrieveSmsCode() async {
      final Uri endpoint = Uri(
        scheme: 'http',
        host: kIsWeb
            ? 'localhost'
            : '10.0.2.2', // android or localhost for other platforms
        port: 9099,
        path: 'emulator/v1/projects/xxxxx-project-id/verificationCodes',
      );
      final response = await http.get(endpoint);
      if (response.statusCode != 200) {
        throw response.body;
      }
      Map body = jsonDecode(response.body);

      final code = body['verificationCodes'].last['code'];
}
```
