### ISSUE TITLE
🐛Error on update to latest version

### ISSUE THREAD

**Issue by wilson0506** [firebase/flutterfire#8387]
When I tried to embed flutterfire into my project, it shows up error as follow:
is it because Apple M1 or do I miss any step?

pod install
Analyzing dependencies
firebase_analytics: Using Firebase SDK version '8.14.0' defined in 'firebase_core'
firebase_auth: Using Firebase SDK version '8.14.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '8.14.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '8.14.0' defined in 'firebase_core'
/Users/wilson/.gem/ruby/2.6.0/gems/ethon-0.15.0/lib/ethon/curls/classes.rb:36: [BUG] Illegal instruction at 0x0000000104bf0000
ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]

[pubspec.yaml]
 firebase_core: ^1.14.0
  firebase_auth: ^3.3.12
  firebase_messaging: ^11.2.12
  flutter_local_notifications: ^9.4.0

[flutter doctor -v]
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.0.1 21A559 darwin-arm, locale en-HK)
    • Flutter version 2.10.4 at /users/wilson/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (9 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/wilson/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.65.2)
    • VS Code at /Users/wilson/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • iPhone 13 Pro Max (mobile) • F822E737-B8C2-4F0B-ACC5-6F6AEF9D3774 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 100.0.4896.60

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

## Bug report

**Describe the bug**

### Steps to reproduce

2. '...'
4. See error or incorrect behavior

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by darshankawar** [comment]
> /Users/wilson/.gem/ruby/2.6.0/gems/ethon-0.15.0/lib/ethon/curls/classes.rb:36: [BUG] Illegal instruction at 0x0000000104bf0000

This does not seem to be due to updating to latest version, but looks like an issue with cocoapods. See this similar link : https://developer.apple.com/forums/thread/652822

I suggest you to open the issue in cocoapods repo. Closing from here.
