### ISSUE TITLE
firebase_auth not receiving OTP after using phone number for testing

### ISSUE THREAD

**Issue by yendiscart** [firebase/flutterfire#8394]
Firebase not receiving OTP after I used the phone number for testing. I mean the real number. I deleted the user from firebase backend but still cannot receive OTP. Getting `Authentication failed - we have blocked all your requests from this device due to unusual activity. Try again. later,`

**Comment by darshankawar** [comment]
> Authentication failed - we have blocked all your requests from this device due to unusual activity. Try again

This error indicates firebase is blocking your requests and not flutterfire. You'll need to reach out to firebase support or in respective native firebase sdk github for further solution.
Closing from here as this isn't a flutterfire plugin issue.
