### ISSUE TITLE
🐛 [firebase_dynamic_links]  " DynamicLinks.API is not available on this device" exception with API 30 Android Emulator

### ISSUE THREAD

**Issue by canders-rf** [firebase/flutterfire#8397]
## Bug report

App receives an Exception when attempting to use FirebaseDynamicLinks (flutter package) running on an Android Emulator with SDK Level 30: 

The same code works if I use API 32 with the Android Emulator.  My understanding was API 23 is required.  Am I wrong?  Does this API only work for API 32 and newer?

```code

// exception when executing this line 
final PendingDynamicLinkData? initialLink =   await FirebaseDynamicLinks.instance.getInitialLink();

Exception while initializing dynamic links: [firebase_dynamic_links[/unknown]()] com.google.android.gms.common.api.ApiException: 17: API: DynamicLinks.API is not available on this device. Connection failed with: ConnectionResult{statusCode=SERVICE_INVALID, resolution=null, message=null}
```

### Version 
firebase_dynamic_links: ^4.1.2

### Steps to reproduce
Run an Android Emulator at Level 30.  I specifically was using Pixel4 API 30, and Pixel 5 API 30 - same exception.

### Expected behavior
I expected this to work since my understanding is Dynamic Links were available with API 23. 

### Additional Information
[app_level_build.gradle.txt](https://github.com/firebase/flutterfire/files/8418100/app_level_build.gradle.txt)
[flutter_doctor_out.txt](https://github.com/firebase/flutterfire/files/8418101/flutter_doctor_out.txt)
[project_level_build.gradle.txt](https://github.com/firebase/flutterfire/files/8418103/project_level_build.gradle.txt)

**Comment by darshankawar** [comment]
@canders-rf 
Can you provide `flutter doctor -v` alongwith app and project level `build.gradle` files ?

**Comment by canders-rf** [comment]
I updated the issue and attached the requested files.  Thanks!

**Comment by canders-rf** [comment]
@darshankawar , do  you have everything you need?

**Comment by darshankawar** [comment]
@canders-rf 
From your app level build.gradle file, I see that you are using below implementation which may not be required:

`implementation platform('com.google.firebase:firebase-bom:29.1.0') `. Try removing it and see if it helps. You would need that if you absolutely have to have some native dependency resolution.

**Comment by canders-rf** [comment]
@darshankawar 
I removed the line and the exception still happens.  This exception does not happen with the API LEVEL 32 Android emulator.

**Comment by darshankawar** [comment]
Thanks for the feedback. I tried this scenario on Samsung device api 30, but don't see such issue. There have been similar reports of the error as below previously:

https://github.com/firebase/flutterfire/issues/1126#issuecomment-1034029457
https://github.com/firebase/flutterfire/issues/4004#issuecomment-789262715

https://github.com/firebase/flutterfire/issues/6816 and [this](https://github.com/firebase/flutterfire/issues/6816#issuecomment-900196795) solution doesn't seem to help.

https://github.com/firebase/flutterfire/issues/6893

Labeling for further insights from the team.

/cc @russellwheatley

**Comment by canders-rf** [comment]
Hi @russellwheatley , the Play Store icon doesn't appear on the emulators page, however the subtitle for the Nexus 5X API 30 indicates Google  Play and I see the Play Store app when I run the Nexus 5X.   The Pixel 4 API 30 and Pixel 5 API 30 emulators both give the exception when attempting to access the firebase Dynamic Links API.  The other emulators (in the screen shot) work fine.  The Pixel 5 API 32 does not appear to have Play Store yet works fine.  Let me know if you need anything else.

![image](https://user-images.githubusercontent.com/98673138/162439127-f6812b6c-8180-462d-9068-d3082609acd2.png)
