### ISSUE TITLE
🐛 [firebase_auth] Reset password email is not received when using Microsoft business emails

### ISSUE THREAD

**Issue by JorgeDiazz** [firebase/flutterfire#8407]
### Describe the bug

When trying to reset user's password using [password reset email](https://firebase.flutter.dev/docs/auth/manage-users#send-a-password-reset-email) and a Microsoft business email, the email is not sent/received by the user.

Even while using the default email template provided by Firebase.

### Steps to reproduce

1. Create an account using a Microsoft business email, i.e. example@microsoftCustomDomain.com.
2. Send a password reset email using `firebaseAuth.sendPasswordResetEmail(email:"example@microsoftCustomDomain.com")` or Firebase Authentication dashboard.
3. This process does not generate an exception, but the email never reaches the recipient. 

### Expected behavior
The user should receive the password reset email without problems.

### Additional context
We tried getting rid of the HTML tags that were giving format to the email content and it worked when using Microsoft business emails, but the email was received as spam.

**Comment by darshankawar** [comment]
@JorgeDiazz 
Does this behavior occur only using Microsoft domain or happens with other domains too like gmail ?
I doubt if this is related to Microsoft domain itself rather than an issue with Flutterfire, but let's first confirm if this happens with other domains too.

**Comment by Salakar** [comment]
As we're just a wrapper on the official SDKs this isn't something we have control over (especially since you mentioned the method is completing without error), for this type of issue I'd recommend contacting Firebase Support. Thanks

**Comment by JorgeDiazz** [comment]
@darshankawar it occurs only using using Microsoft domain. Gmail works well. I'll contact Firebase Support. Thank you
