### ISSUE TITLE
firebase ios15 cannot receive offline push

### ISSUE THREAD

**Issue by Huangkaiping** [firebase/flutterfire#8434]
firebase ios15 cannot receive offline push,but android and ios15- works well

**Comment by darshankawar** [comment]
> cannot receive offline push

Do you mean when we push a notifications in offline mode, it isn't received on iOS, but received on Android ?



> android and ios15- works well

Did you mean to say iOS 14 or iOS < 15 ?

Can you provide `flutter doctor -v`, messaging plugin version, a sample payload you are sending along with any error log you get while doing so ?

**Comment by darshankawar** [comment]
> Channel beta, 2.2.2

This is very old beta version. Please upgrade to latest beta or master and try again to see if behavior still persists or not.

**Comment by Huangkaiping** [comment]
Sorry, I can't upgrade firebase_ Messaging version, because my fluent SDK needs to be upgraded, which will cause many problems. But now I've figured out that it's not the IOS mobile phone system. It's because some mobile phones can't get tokens. Here are some logs
Failed to fetch default token Error Domain=NSURLErrorDomain Code=-1200 "发生了SSL错误，无法建立与该服务器的安全连接。" UserInfo={NSErrorFailingURLStringKey=https://device-provisioning.googleapis.com/checkin, NSLocalizedRecoverySuggestion=您仍要连接此服务器吗？, _kCFStreamErrorDomainKey=3, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <2E69AB9E-0BDD-4A6F-BE98-0DD8A5CB6D77>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(

**Comment by darshankawar** [comment]
> Failed to fetch default token Error

Are you using vpn ? If so, it could be happening due to it. Try removing the vpn and use regular network and see if it helps.

**Comment by arthas1888** [comment]
I have the same problem
