### ISSUE TITLE
[📚] Link to docs is broken

### ISSUE THREAD

**Issue by tinyCoder32** [firebase/flutterfire#8438]
Please describe your documentation issue or suggested improvement in detail here and provide links to any pre-existing/relevant documentation and screenshots if necessary:

The link to the docs is broken, the current link is:
https://firebase.flutter.dev/docs/dynamic-links/usage

The correct link is:
https://firebase.flutter.dev/docs/dynamic-links/overview

Thanks.

**Comment by Akshit6828** [comment]
Hi @tinyCoder32, @daikini , @anaisbetts , @sethladd , @kevmoo . I also noticed that a few [links](https://github.com/firebase/flutterfire/blob/master/docs/dynamic-links/overview.mdx#next-steps) under **"Next Steps"** heading are broken which are named as:
* creating link with  Flutter Client
* Receive Dynamic Links: 

in the file path :`docs/dynamic-links/overview.mdx`.

Thus, I was wondering can I fix it if you could provide me with the correct link?

Thanks 😃

**Comment by darshankawar** [comment]
@Akshit6828 
Please don't unnecessarily tag people who may not be directly related to this issue or plugin. Please refrain from doing so going forward.

**Comment by Akshit6828** [comment]
Hi, @darshankawar apologies for any inconvenience. Actually, I wasn't sure about who is the right person for it. Thus I thought, to bring it to notice!

**Comment by russellwheatley** [comment]
Closing in favour of tracking this issue [here](https://github.com/firebase/flutterfire/issues/6751). Thanks!
