### ISSUE TITLE
🐛 [cloud_firestore] Firestore data is not being saved right after the user is created on Firebase Authentication (Flutter Web only)

### ISSUE THREAD

**Issue by WiseTap** [firebase/flutterfire#8439]
## Bug report

This problem happens on Flutter Web only
After I create a user on Firebase Authentication, I can't save the Firestore data until the Firebase Authentication auth state changes

### Steps to reproduce

    FirebaseAuth.instance.authStateChanges().listen((auth){
      print('> authStateChanges uid: '+(auth?.uid ?? 'null'));
    });
    print('> firebase user will be created on firebase authentication:');
    final userAuth = await FirebaseAuth.instance
                   .createUserWithEmailAndPassword(email: 'example@example.com', password: '123456');
    print('> user created on firebase authentication, now the data on firestore will be saved:');
    await FirebaseFirestore.instance.collection('example').doc('test_without_delay').set({
      'fullName': 'Example Example'
    });
    print('> firestore data created');

Output on browser's console:

    > firebase user will be created on firebase authentication:
    > authStateChanges uid: null
    > user created on firebase authentication, now the data on firestore will be saved:
    > authStateChanges uid: aZkBuYtIoAOSO56NQkcHOXcG2Vk1

### Expected behavior

The log `> firestore data created` should be printed, but is not
The data `'fullName': 'Example Example'` should  be saved, but is not as well 

---

## Additional context

I think the problem lies on the auth state, because it works fine without any bugs when I add a delay:

    FirebaseAuth.instance.authStateChanges().listen((auth){
      print('> authStateChanges uid: '+(auth?.uid ?? 'null'));
    });
    print('> firebase user will be created on firebase authentication:');
    final userAuth = await FirebaseAuth.instance
                   .createUserWithEmailAndPassword(email: 'example@example.com', password: '123456');
    print('> user created on firebase authentication, waiting 3 seconds...');

    await Future.delayed(Duration(seconds: 3)); // <--

    print('> now the data on firestore will be saved');
    await FirebaseFirestore.instance.collection('example').doc('test_with_delay').set({
      'fullName': 'Example Example'
    });
    print('> firestore data created');

Output on browser's console

    > firebase user will be created on firebase authentication:
    > authStateChanges uid: null
    > user created on firebase authentication, waiting 3 seconds...
    > authStateChanges uid: SuNfH07ePNUfI0f50T3wYqbcYEi2
    > now the data on firestore will be saved
    > firestore data created

---

### Flutter doctor

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.3, on Pop!_OS 20.04 LTS
    5.16.11-76051611-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code
[✓] Connected device (1 available)
[✓] HTTP Host Availability
```

</details>

---

### Flutter dependencies

  cloud_firestore: ^3.1.11
  firebase_auth: ^3.3.13
  firebase_core: ^1.14.0
  firebase_analytics: ^9.1.4
  firebase_app_check: ^0.0.6+8

</details>

---

**Comment by darshankawar** [comment]
Thanks for the report. I do see the same behavior on web platform and on latest mater.

`Channel master, 2.13.0-0.0.pre.497`

**Comment by Ehesp** [comment]
I have a feeling this is more of an underlying JS SDK "issue". 

On web we simply proxy the requests to the underlying SDK, therefore the call to set data goes via the JS SDK, where it uses the authentication credentials within the SDK (not from FlutterFire). Seems like a race condition. 

My suggestion would be to rely on the  `authStateChanges` listener as the source of truth for when the user has been created. Although saying that, I would have expected `createUserWithEmailAndPassword` to resolve once the web sdk has returned a response (which I'm sure it does since it returns a credential).

**Comment by Lyokone** [comment]
Hello @WiseTap, is the issue still present?
