### ISSUE TITLE
.todate() method is not support with timeago.format

### ISSUE THREAD

**Issue by arpanptl** [firebase/flutterfire#8447]
final String timeAgo =
                      timeago.format(msg[TIMESTAMP].toDate()); // error

**Comment by darshankawar** [comment]
@arpanptl 
Which flutterfire plugin are you referring to for this ?
Also, while opening an issue, please use new issue template and fill out requested details so that we'll have enough details to work with.

**Comment by arpanptl** [comment]
firebase_core: ^1.10.0 # Firebase Core package required to use other firebase services
  firebase_auth: ^3.2.0  # Used to Authenticate User Account (e.g. Sign in with Phone number, etc..)
  cloud_firestore: ^3.1.6 # Used to Save User Data in Database
  firebase_messaging: ^11.1.0 # Used to Send Push Notifications (e.g. New like, Visit and Message)
  firebase_storage: ^10.1.0

**Comment by arpanptl** [comment]
mentined above sir

**Comment by arpanptl** [comment]
> @arpanptl Which flutterfire plugin are you referring to for this ? Also, while opening an issue, please use new issue template and fill out requested details so that we'll have enough details to work with.
////
firebase_core: ^1.10.0 # Firebase Core package required to use other firebase services
firebase_auth: ^3.2.0 # Used to Authenticate User Account (e.g. Sign in with Phone number, etc..)
cloud_firestore: ^3.1.6 # Used to Save User Data in Database
firebase_messaging: ^11.1.0 # Used to Send Push Notifications (e.g. New like, Visit and Message)
firebase_storage: ^10.1.0

mentioned above sir

**Comment by darshankawar** [comment]
@arpanptl 
Can you provide a complete minimal reproducible code sample that we can directly use along with current vs expected behavior ?
