### ISSUE TITLE
🐛 [firebase_core] [Cobalt] initializeApp is undefined

### ISSUE THREAD

**Issue by coachj-csedge** [firebase/flutterfire#8451]
## Bug report

While trying to utilize the Firebase Core Web plugin running on Cobalt ver. 22, upon calling `firebase.initializeApp()`
(https://github.com/firebase/flutterfire/blob/master/packages/firebase_core/firebase_core_web/lib/src/firebase_core_web.dart#L279) I receive an error specifying 
`ReferenceError: firebase is undefined` (line 279 of [firebase_core_web.dart](https://github.com/firebase/flutterfire/blob/master/packages/firebase_core/firebase_core_web/lib/src/firebase_core_web.dart#L279))

I believe it is due to the JS interop not finding the JavaScript function correctly on window despite in the Cobalt debug console, I am able to call `window.initializeApp()` directly without issues.

I believe a it would entail updating the plugin to support `9.6.9`? There might be some disconnect with current plugin's expectations of JS definitions and the 9.6.9 JS binary.

I am targeting Firebase Core 9.6.9 since in older versions, `IDBIndex` is required as a Web API and Cobalt doesn't support it. (fixed in `9.6.9`: https://firebase.google.com/support/release-notes/js#version_969_-_march_17_2022).

**Comment by darshankawar** [comment]
@coachj-csedge 
I am not much aware about Cobalt, so not really sure. Does the same error occur without using it ?

Can you provide the entire error log ?

**Comment by coachj-csedge** [comment]
The error does not occur when running the Flutter Web application within a normal Chrome browser. I believe Cobalt would fall under somewhere between the "Other environments" (https://firebase.google.com/docs/web/environments-js-sdk#other_environments).

**Comment by darshankawar** [comment]
Thanks for the update. I am keeping it open and labeling for further insights from the team.

/cc @Salakar

**Comment by coachj-csedge** [comment]
Updated to reflect a more accurate error, included where it it's being thrown, and propose some more thoughts on solutions for the plugin

**Comment by coachj-csedge** [comment]
@darshankawar @Salakar Want to followup on this thread

**Comment by russellwheatley** [comment]
Hi @coachj-csedge, I would recommend not using FlutterFire in an unsupported environment. I imagine this would be the first of many issues, and would advise to use Flutter web in the browser as intended. Thanks.
