### ISSUE TITLE
[📚]  Firebase Analytics without IDFA

### ISSUE THREAD

**Issue by cedvdb** [firebase/flutterfire#8463]
The documentation mention:

 > To use Firebase Analytics without IDFA collection capability, open /ios/Podfile or /macos/Podfile and add the following global variable to the top of the file: `$FirebaseAnalyticsWithoutAdIdSupport = true`
 
 There is no such file in a newly created project

**Comment by darshankawar** [comment]
@cedvdb 
Newly created project doesn't have podfile by default. Once you add any plugin, then you'll see podfile generated. Try that and then you can probably add the global variable in respective podfile.

Closing for now as this isn't an issue. If you disagree, write in comments and I"ll reopen it.

**Comment by cedvdb** [comment]
Well this is a documentation improvement issue. So yeah I disagree .
