### ISSUE TITLE
My Stream Builder takes me to Main Page only when I restart my app but sign out works fine

### ISSUE THREAD

**Issue by hyderali0889** [firebase/flutterfire#8474]
I am unable to create a user login page when user signs in it the stream builder does not recognizes it until hot restart my code is 
```
` void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  return runApp(MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => RootProvider()),
        ChangeNotifierProvider(create: (_) => FirebaseProvider()),
      ],
      child: const MaterialApp(
        home: MyApp(),
      )));
}

//
// ──────────────────────────────────────────────────────── IV ──────────
//   :::::: M A I N   A P P : :  :   :    :     :        :          :
// ──────────────────────────────────────────────────────────────────
//

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: StreamBuilder(
          stream: FirebaseAuth.instance.userChanges(),  //  I've tried with authstatechanged as well
          builder: (context, snapshot) {
            if (snapshot.hasData) {
              return const MainPage();
            } else {
              return const NetworkCheck();
            }
          }),
    );
  }
} `


```

**Comment by darshankawar** [comment]
> MultiProvider(
>       providers:

You seem to be using `provider` package which is third party. Does the same behavior occur without using this package's code ?

**Comment by hyderali0889** [comment]
In a second app it works fine without provider but I wanna use provider in my app

**Comment by hyderali0889** [comment]
could this code 
` if(snapshot.connectionStatus == ConnectionStatus.active){
   return snapshot.data != null ? HomePage() : LoginPage();
} else{
return CircularProgressIndicator();
}  ` 

have a different output than snapshot.hasData()

**Comment by hyderali0889** [comment]
It still doesn't work with 
` 
if(snapshot.connectionStatus == ConnectionStatus.active){ return snapshot.data != null ? HomePage() : LoginPage(); } else{ return CircularProgressIndicator(); } ` && ` snapshot.hasData() `

I tried removing provider package but no result .

Is there any other way I can create an auth system that takes user to home page after authentication .
Or any official way of doing this any other Widget or something other than StreamBuilder

**Comment by hyderali0889** [comment]
I don't know why but creating a material app inside another material app was the problem. I solved the problem by removing the second material app 
` 
   return StreamBuilder(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.active) {
          return snapshot.data != null

              ? const HomeScreen()

              : const RegisterScreen();
        } else {
          return const Center(
            child: CircularProgressIndicator(),
          );
        }
      },
    );
  }
} `

This is how I solved it .
