### ISSUE TITLE
[FlutterFirebaseFirestorePlugin] uses or overrides a deprecated API. Warning

### ISSUE THREAD

**Issue by AriMP** [firebase/flutterfire#8476]
Latest Firebase packages throw some warnings during build.

I could reproduce this on every new flutter project with the added firebase packages.

Note that build doesn't fail, but I'm concerned about these warnings nonetheless. 

``Flutter (Channel master, 2.13.0-0.0.pre.601)``
``Android SDK version 32.1.0``

Firebase package versions:
``` 
  firebase_auth: ^3.3.14
  firebase_database: ^9.0.11
  cloud_firestore: ^3.1.12
```
Sdk versions from build.gradle

    compileSdkVersion 32

        minSdkVersion 23
        targetSdkVersion 32

- Warnings
```

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\UserName\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-3.1.12\android\src\main\java\io\flutter\plugins\firebase\firestore\
FlutterFirebaseFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\UserNamees\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_auth-3.3.14\android\src\main\java\io\flutter\plugins\firebase\auth\Flutter
FirebaseAuthPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\UserName\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_database-9.0.11\android\src\main\java\io\flutter\plugins\firebase\database
\FirebaseDatabasePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

```

I have tried reinstalling flutter sdk, dart and flutter plugins, android sdk. The issue persists!

**Comment by darshankawar** [comment]
They seem to be coming from plugin's code itself:


```
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\UserName\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-3.1.12\android\src\main\java\io\flutter\plugins\firebase\firestore\
FlutterFirebaseFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\UserNamees\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_auth-3.3.14\android\src\main\java\io\flutter\plugins\firebase\auth\Flutter
FirebaseAuthPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\UserName\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_database-9.0.11\android\src\main\java\io\flutter\plugins\firebase\database
\FirebaseDatabasePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

```

**Comment by AliKarimiENT** [comment]
Hey 
I also have these problems in release mode 

  firebase_auth: ^3.3.14
  google_sign_in: ^5.3.0
  path_provider: ^2.0.9


![image](https://user-images.githubusercontent.com/57004354/164187228-24146652-2694-446e-8c1a-732318860381.png)

**Comment by Xanonymous-GitHub** [comment]
Have same issue too.

**Comment by teddy225** [comment]
YES   Envoyé à partir de Courrier pour Windows De : TU-LinEnvoyé le :vendredi 22 avril 2022 02:26À : firebase/flutterfireCc : SubscribedObjet :Re: [firebase/flutterfire] [FlutterFirebaseFirestorePlugin] uses or overrides a deprecated API. Warning (Issue #8476) Have same issue too.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***> 



	
		
			
				
			
		
		
			
				L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
				www.avast.com

**Comment by Ehesp** [comment]
These are only warnings from updating the internal sdks, nothing to worry about.

We'll get around to updating them as part of on going mantanince.

**Comment by jovane21** [comment]
I have the same issue too.
