### ISSUE TITLE
[📚] PerfMon still doesn't support Dart only initialization is not mentioned in getting started section

### ISSUE THREAD

**Issue by DebkanchanSamadder** [firebase/flutterfire#8477]
### Problem
Performance Monitoring still doesn't support Dart only initialization. This is not mentioned in the newly updated (#8448) getting started section giving an illusion everything supports Dart only Initialization.

It is when we go into performance monitoring docs that the fact is mentioned.
<img width="814" alt="Screenshot 2022-04-17 at 4 39 06 PM" src="https://user-images.githubusercontent.com/11326669/163711901-9269e1b0-9576-4872-9ccd-b9ebd2dc675a.png">

Where previously it was mentioned in the getting started section like this:
<img width="869" alt="Screenshot 2022-04-17 at 4 34 20 PM" src="https://user-images.githubusercontent.com/11326669/163711911-5a4341a2-9f10-47d1-96b4-6bf65de05b12.png">

### Consequences
While migrating my code to dart only initialization executing `flutter run`  **ALWAYS** throws
`Error connecting to the service protocol: failed to connect to http://127.0.0.1:50769/a3uk2dDx_Hw=/.`

Running `flutter run -v` made me think the culprit was Crashlytics due to the line:
`Crashlytics could not find Google Services plugin task: processReleaseGoogleServices. Make sure com.google.gms.google-services is applied BEFORE com.google.firebase.crashlytics. If you are not using the Google Services plugin, you must explicitly declare `googleServicesResourceRoot` inputs for Crashlytics upload tasks.`

**It is only after doing a binary search on all the dependencies in a fresh project that I was able to pinpoint it's a perf-mon issue only to go into perf-mon docs to find the warning**

**Comment by darshankawar** [comment]
@DebkanchanSamadder 
Per the linked PR, the usage section / table that previously showed which plugins supported dart initialization, seemed to have been removed altogether and hence you are seeing the same for respective plugin in its usage section as you highlighted.
And if you are not seeing such section for other plugins, I think it indicates, the dart intialization is supported. Hope this answers your query.

**Comment by DebkanchanSamadder** [comment]
Firebase analytics supports full dart only initialization now. Crashlytics also supports dart only initialization now but to catch native crashes you need to add the crashlytics Gradle plugin which does not depend on google-services. These are properly documented and even if they weren't they would work as they aren't strictly dependant on google-services.

However, the problem is perfmon **will not work without** google-services and **will cause the app to not even start-up**.

And although that is documented in perfmon docs I feel it's important to clearly mention it in the getting started guide as an absence of any such warning is misleading and makes it _seem_ like everything supports dart only initialization now which can cause anyone new or migrating serious headaches and potentially days worth of time loss as it happened to me.

**Comment by darshankawar** [comment]
If devs would search for `flutterfire performance monitoring` and click this link https://firebase.flutter.dev/docs/performance/overview/, it shows the note as warning properly:

![Screenshot 2022-04-19 at 3 47 41 PM](https://user-images.githubusercontent.com/67046386/163983063-2dbc99a8-06b7-43af-bbc8-4a6426b20e48.png)

But I think OP wants this section to be here https://firebase.flutter.dev/docs/overview

/cc @russellwheatley

**Comment by DebkanchanSamadder** [comment]
commenting to avoid being stale

**Comment by carlosfiori** [comment]
In the new docs this section doesn’t exist

**Comment by carlosfiori** [comment]
In the new docs this section doesn’t exist

**Comment by DebkanchanSamadder** [comment]
> In the new docs this section doesn’t exist

Yes and it makes it even more confusing

**Comment by russellwheatley** [comment]
Hey @DebkanchanSamadder, please follow the instructions for setting up a Firebase app in the [official documentation](https://firebase.google.com/docs/flutter/setup?platform=ios#configure-firebase). We've released FlutterFire CLI which now writes your google service files for android and iOS into the relevant directory. Be sure to update to the latest FlutterFire CLI (`dart pub global activate flutterfire_cli`), and run `flutterfire configure`. You now don't have to worry about manually setting up config files. Hope this helps.
