### ISSUE TITLE
Post-install instructions and code sample for distributed counter extension.

### ISSUE THREAD

**Issue by Dan1ell** [firebase/flutterfire#8478]
The firebase extension distributed counter requires client-side code to work. In the firebase documentation, there are detailed post-install instructions for web, android, and ios apps. This includes code samples to copy.

[https://github.com/firebase/extensions/blob/master/firestore-counter/POSTINSTALL.md](https://github.com/firebase/extensions/blob/master/firestore-counter/POSTINSTALL.md)

I request flutterfire similarly provide a code sample and post-install instructions for flutter apps.

**Comment by darshankawar** [comment]
@Dan1ell 
Distributed counter snippets are already added as part of this PR https://github.com/firebase/flutterfire/pull/7867
Check that and see if they are helpful and answers your requirement.

**Comment by Dan1ell** [comment]
@darshankawar 
I'm aware of this documentation but no it does not address my request. The mentioned documentation is about writing your own distributed counter that counts inside your app. It does not use the Firebase Distributed Counter extension. 
In my request, I'm referring to code snippets that should be added to your app to make the firebase extension work. 

In the documentation you are referring to it even says that there are 2 ways to implement distributed counters: the way documented there (the PR way) and the Firebase Distributed Counter extension. They are alternatives to each other.

**Comment by darshankawar** [comment]
Thanks for the update.

**Comment by russellwheatley** [comment]
Hey @Dan1ell, I would encourage you to setup the counter extension and learn how it works [here](https://github.com/firebase/extensions/tree/next/firestore-counter). You can also use the dart code sample [here](https://github.com/firebase/extensions/pull/607/files) that is awaiting to be merged alongside the other client samples on the extension's repo. Hope this helps!
