### ISSUE TITLE
🐛 [Flutterfire ui] SignIn Screen : ButtonTheme not working

### ISSUE THREAD

**Issue by Patrick386** [firebase/flutterfire#8480]
The theme is not applied after package update.

 flutter doctor -v
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-arm, locale ko-KR)
    • Flutter version 2.10.5 at /Users/patrick386/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (19 hours ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/patrick386/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 100.0.4896.88

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

<img width="1497" alt="스크린샷 2022-04-19 오후 8 38 27" src="https://user-images.githubusercontent.com/49754877/163995932-70ea601f-a1aa-4763-9c6a-9202c2d17cbe.png">

**Comment by AndrasTimar** [comment]
Possibly the same issue as https://github.com/firebase/flutterfire/issues/8443

**Comment by darshankawar** [comment]
That does look like similar to the linked issue. @Patrick386 Please follow-up in original issue for further updates.
Closing this as duplicate, since the root-cause seems to be same as mentioned in linked issue. Once that is fixed, your case would be fixed as well. If you disagree, write in comments and I'll reopen it.
