### ISSUE TITLE
🐛 [firebase_dynamic_links] Custom long dynamic links are not handled

### ISSUE THREAD

**Issue by lavinov-mercury** [firebase/flutterfire#8483]
## Bug report

The task is to build dynamic link with some params. Previously i used following code to build a short link & it worked like a charm:

```dart
final dynamicLink = await FirebaseDynamicLinks.instance.buildShortLink(
      DynamicLinkParameters(
        link: urlWithParams,
        uriPrefix: 'https://link.example.com', // custom domain
        iosParameters: const IOSParameters(
          bundleId: iosBundleId,
          appStoreId: iosAppStoreId,
        ),
        androidParameters: const AndroidParameters(
          packageName: androidAppId,
        ),
      ),
    );
```

However, i needed to switch to the long dynamic link version and used `buildLink`. Then i've faced the fact, that app doesn't handle these links anymore. Following these links still opens the app, but `getInitialLink` always returns `null` and `onLink` doesn't fire anymore.

With some experiments i've figured out that firebase_dynamic_links can handle only shortened links, created by Firebase, and links registered in Firebase console. So, if i add `https://link.example.com/action` dynamic link in console & build link with `urlPrefix: 'https://link.example.com/action'`, then app will be able to handle such links again, but there is another problem: it will always provides the link which has been used in console, so, i'm not able to pass parameters in this case.

### Steps to reproduce

1. Build a long dynamic link with prefix like `uriPrefix: 'https://link.example.com'`
2. Follow this link on your mobile device with installed app
3. Observe the opened app

### Expected behavior

Dynamic link handled: either `getInitialLink` returned passed link or `onLink` fired

### Actual behavior

Nothing happens

---

## Additional context

This happens on both iOS & Android. Outside of the app these links resolves as expected. Current firebase_dynamic_links version is 4.1.3

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.4, on macOS 11.6 20G165 darwin-arm, locale ru-RU)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[!] Android Studio
    ✗ Unable to find bundled Java version.
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.66.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 2 categories.
```

</details>

**Comment by darshankawar** [comment]
@lavinov-mercury 
Thanks for the detailed report.  Please see [this](https://github.com/firebase/flutterfire/issues/6242#issuecomment-1096084912) issue comment for your reference which hopefully should be able to resolve your issue.

For `getInitialLink` and `onLink` not being called, see [this](https://github.com/firebase/flutterfire/issues/6913) relevant issue and underlying comments and check if it helps.

**Comment by lavinov-mercury** [comment]
@darshankawar Thanks for your reply! As i can see, both these issues are only about iOS, but in my case it happens in Android app as well

**Comment by darshankawar** [comment]
@lavinov-mercury 
I think, since the ios part needed to be fixed at native iOS firebase sdk level, same would be applicable to Android as well. So I suggest you to open this issue in native Android firebase sdk and see what they say about it, because Flutterfire plugins are wrappers around native firebase sdks and they send the data through dart and receive it from them.

https://github.com/firebase/firebase-android-sdk/issues
