### ISSUE TITLE
🐛 [firebase_messaging] When mobile phone lock screen, BackgroundMessage method sometime working, but sometime not be triggered.

### ISSUE THREAD

**Issue by niumj** [firebase/flutterfire#8485]
## Bug report

When mobile phone lock screen, BackgroundMessage method sometime working, but sometime not be triggered.
On Android,When mobile phone lock screen, sometime can receive messages, sometime can't receive messages.
So loged in BackgroundMessage method .
It looks like BackgroundMessage method sometime is triggered , but sometime is not triggered.

However On simulator, it works OK.

**Comment by darshankawar** [comment]
@niumj 
What `flutter doctor -v` version and plugin version are you on ?
A similar issue was fixed a while ago. Check that for your reference : https://github.com/firebase/flutterfire/issues/4369

https://github.com/firebase/flutterfire/pull/6730

**Comment by niumj** [comment]
@[darshankawar]
flutter doctor -v 
[√] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.17763.1577], locale ja-JP)
    • Flutter version 2.10.4 at D:\DevelopTool\Mobile\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (4 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at D:\DevelopTool\Mobile\Android\Sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = D:\DevelopTool\Mobile\Android\Sdk
    • Java binary at: D:\DevelopTool\Mobile\Android\Android StudioBumbleBee\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Professional 2017 15.9.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional
    • Visual Studio Professional 2017 version 15.9.28307.280
    • Windows 10 SDK version 10.0.17763.0
    X Visual Studio 2019 or later is required.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2020.3)
    • Android Studio at D:\DevelopTool\Mobile\Android\Android Studio4
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Android Studio (version 2021.1)
    • Android Studio at D:\DevelopTool\Mobile\Android\Android StudioBumbleBee
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] Android Studio (version 4.1)
    • Android Studio at D:\DevelopTool\Mobile\Android\AndroidStudio3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Android Studio (version 2021.1)
    • Android Studio at D:\DevelopTool\Mobile\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.65.2)
    • VS Code at C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.17763.1577]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 100.0.4896.127
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 100.0.1185.44

**Comment by darshankawar** [comment]
@niumj 
Can you provide code sample as how are you calling `onBackgroundMessage` handler ? Can you print a simple text inside this handler and see if it is triggered after unlocking the screen ?
Does other streams such as foreground or OnMessageAppOpened gets called ?

**Comment by niumj** [comment]
@darshankawar

/// Define a top-level named handler which background/terminated messages will call.
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  //App Initialize
……
  // If you're going to use other Firebase services in the background, such as Firestore,
  // make sure you call `initializeApp` before using other Firebase services.
  await Firebase.initializeApp();

……
}

Future<void> main() async {
   //Firebase FCM 
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();

/// Background messages
  /// Set the background messaging handler early on, as a named top-level function
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
……
}

1.print simple text in onBackgroundMessage，when unlocking the screen，it is not triggered
2.when unlocking the screen，foreground (FirebaseMessaging.onMessage.listen）is triggered.
3.locking the screen, sometimes onBackgroundMessage is not triggered, but then unlochiking the screen foreground is triggered only once(In fact backgroudMessage counts is more than 2 )

**Comment by darshankawar** [comment]
@niumj 
What kind of payload are you sending, is it data-only or notification ? Can you provide a sample payload you are sending which isn't triggered ?

**Comment by niumj** [comment]
@darshankawar
Send Message's code is Java.  using [com.google.firebase.messaging.AndroidConfig.Builder]

	public static void pushSingleToAndroid(String appName, String token, String title, String body) throws FirebaseMessagingException {
		//instance
        FirebaseApp firebaseApp = firebaseAppMap.get(appName);
        if (firebaseApp == null) {
        	return;        	
        }
        androidConfigBuilder.setRestrictedPackageName("XXX.io.telecomm.telecomm");
		androidNotifiBuilder.setColor("#55BEB7");
//		androidNotifiBuilder.setIcon("https://www.shiku.co/images/favicon.png");
		androidNotifiBuilder.setTitle(title);
		androidNotifiBuilder.setBody("");
		androidNotifiBuilder.setPriority(Priority.DEFAULT);
		AndroidNotification androidNotification=androidNotifiBuilder.build();
		androidConfigBuilder.setNotification(androidNotification);
		AndroidConfig androidConfig=androidConfigBuilder.build();
		//message
		Message message = Message.builder()
				.setToken(token)
				.putData("data",body)
				.setAndroidConfig(androidConfig)
				.build();
        String response = FirebaseMessaging.getInstance(firebaseApp).send(message);
        System.out.println("Send Success：　"+response);
	}

**Comment by niumj** [comment]
@darshankawar
Discover：When mobile phone lock screen, three continuous BackgroundMessage Messages are sended one time，
 First time，all messages  can be received.
 Second time, all messages  may be received.
Third time, nothing can be received.
However, in case lock screen  ⇒　Push Messages  ⇒ unlock screen operator  ⇒ lock screen    ⇒ Push Messages ...,
BackgroundMessage can be received.
So when lock screen, Is (can receive )Background message's count  limit?

**Comment by darshankawar** [comment]
I am keeping this issue open for further insights from the team, as I am not sure about the intended behavior when the phone screen is locked / unlocked.

/cc @russellwheatley

**Comment by niumj** [comment]
purpose：When mobile phone screen is locked, BackgroundMessage can be received。
However，When mobile phone lock screen, BackgroundMessage can be received sometime。

In webSite [https://firebase.google.cn/docs/cloud-messaging/android/receive],  
properties [android:directBootAware="true" ] must be used,but it is not be used in firebase_messaging .
Is that any impact？

**Comment by russellwheatley** [comment]
As [documented in the Firebase doc](https://firebase.google.com/docs/cloud-messaging/android/receive), you need to enable the following in your app before you can receive messages when the screen is locked. The device is in direct boot mode when the screen is locked.
