### ISSUE TITLE
🐛 [firebase_database] OrderByChild doesnt return ordered data

### ISSUE THREAD

**Issue by elkhalifte** [firebase/flutterfire#8486]
data fetched using the orderbychild are not ordered properly

i have seen this [pull request ](https://github.com/firebase/flutterfire/pull/5765)

and am using the last version of the plugin [9.0.11](https://pub.dev/packages/firebase_database) but still not working

**Comment by darshankawar** [comment]
@elkhalifte 
Can you provide `flutter doctor -v` and a [complete minimal code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the issue you are reporting ?

**Comment by darshankawar** [comment]
@elkhalifte 
Can you try something like below code and see what you get in output:

```
(await FirebaseDatabase.instance
            .reference()
            .child(subpath)
            .orderByChild('year')
            .limitToFirst(3)
            .onValue
            .first)
        .snapshot
        .value
        .values
        .forEach((v) => debugPrint(v['year'].toString()));
```

**Comment by elkhalifte** [comment]
@darshankawar 
there is no problem with the plugin.
the plugin got the results ordered but in random for the user.
so you always need to order results .

for example your code will give me : 2021,2022,2019
so i always need to reorder results inside the dart code.

**Comment by Deep-Focus-lab** [comment]
I am also facing the same problem.. This is not the code problem because the same code give me the correct output on ( firebase_database: ^8.2.0 ) version.. If I upgrade to 9.x.x it stops working.. 
And I am also configure firebase rules ".indexOn" properly.
