### ISSUE TITLE
Installation stuck forever no matter how many times I tried

### ISSUE THREAD

**Issue by brightchip** [firebase/flutterfire#8488]
### Discussed in https://github.com/firebase/flutterfire/discussions/8487

<div type='discussions-op-text'>

<sup>Originally posted by **brightchip** April 20, 2022</sup>
I can't even install it successfully on my Windows 10.
The command `flutterfire configure` never hit an end. stuck there for half a day and keeps stucking whenever I tried to run the command

The firebase project I had used before with Capacitor which works fine. Now I can't get it installed to auto-generate the file `firebase_options.dart`

```?[A?[2Ki Found 1 Firebase projects.

?[?25h
?[?25l
  <create a new project>
?[A?[2K?[A?[2K?[A?[2K
?[?25h
?[?25l
 ios
  macos
  web
?[A?[2K?[A?[2K?[A?[2K?[A?[2K?[A?[2K?[A?[2K⠦ Fetching registered android Firebase apps for project my-app-258603
?[A?[2Ki Firebase android app com.example.myapp registered.
?[?25h ?[6n 
```

If I press enter consecutively it will print 

```  result.length: 16
  result.length: 16

?[A?[2K
  result.length: 16
  result.length: 16

?[A?[2K?[A?[2K
  result.length: 16
  result.length: 16
```

**Comment by darshankawar** [comment]
@brightchip 

flutterfire cli related issues need to be reported in dedicated repo: https://github.com/invertase/flutterfire_cli/issues

https://firebase.flutter.dev/docs/cli/#reporting-an-issue

Closing from here.
