### ISSUE TITLE
🐛 [cloud_firestore] WhereIn query does not work with numbers

### ISSUE THREAD

**Issue by tgpsantos** [firebase/flutterfire#8491]
Hello guys,

I have a colelction "ratings" and these documents have the following fields:
- user_id [string]
- rating [int]

I'm getting mixed behaviour when using the whereIn query.

**This works:** 
`ratingsQuery = FirebaseFirestore.instance.collection('ratings').where('user_id', whereIn: ["user_x", "user_y"])`

**This doesn't work:** 
`ratingsQuery = FirebaseFirestore.instance.collection('ratings').where('rating', whereIn: [1, 2, 3])`

I've noticed the same behaviour both in flutter web as in mobile.

### Deps

```
  cloud_firestore: 3.1.12
  firebase_core: 1.14.1

```

### Flutter doctor

<details><summary>Flutter Doctor</summary>

```
[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.19044.1645], locale pt-PT)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 4.2)
[√] VS Code (version 1.66.2)
[√] VS Code, 32-bit edition (version 1.32.3)
[√] Connected device (3 available)
[√] HTTP Host Availability
```

</details>

**Comment by darshankawar** [comment]
> where('rating', whereIn: [1, 2, 3])

`rating` in single or double quotes will be treated as `String` and then being compared with int. Probably that's why you are not getting result back. Do you get any error while doing so ?
