### ISSUE TITLE
🐛 [firebase_dynamic_links: ^4.1.3] IOS app is turning to black screen when opening it from dynamic link

### ISSUE THREAD

**Issue by basit192** [firebase/flutterfire#8495]
## Bug report

**Describe the bug**
When ever i open the app the from deep link it turns to black screen although it works fine for Android. I have added all the required configurations for IOS as well

<img width="714" alt="image" src="https://user-images.githubusercontent.com/91729229/164447421-d5d8c503-c2fa-4e7b-a611-c0bd11591ff3.png">

<img width="834" alt="image" src="https://user-images.githubusercontent.com/91729229/164447508-7205d8b2-d328-4e40-8956-4ab4e54adb33.png">

<img width="706" alt="image" src="https://user-images.githubusercontent.com/91729229/164447571-54504a2c-0b1e-4256-8205-fe84292df401.png">

**Comment by darshankawar** [comment]
@basit192 
See this SO answer that is taken from Google itself which should resolve as why you are seeing black screen on iOS.

https://stackoverflow.com/a/42386729

That said, I am going ahead and closing it as WAI.
