### ISSUE TITLE
🐛 [firebase_dynamic_links] The usage link is dead.

### ISSUE THREAD

**Issue by Jay-flow** [firebase/flutterfire#8502]
## Bug report

1. Go to link https://pub.dev/packages/firebase_dynamic_links
2. Please refer to the picture below and click the Usage link.

![image](https://user-images.githubusercontent.com/29420674/164611889-ebb8d21a-1af0-434b-94e1-5797a2f8f50b.png)

### Result
The usage link is dead.
https://firebase.flutter.dev/docs/dynamic-links/usage

![image](https://user-images.githubusercontent.com/29420674/164612091-afce308b-9eed-4ab4-a066-9b2da899e1b2.png)

**Comment by darshankawar** [comment]
Closing this in favor of https://github.com/firebase/flutterfire/issues/6751 to track all broken links.
Please follow-up in it for further updates.
