### ISSUE TITLE
🐛 FirebaseAuth ResetPassword do not send mail

### ISSUE THREAD

**Issue by ctykaya** [firebase/flutterfire#8503]
## Bug report

**Describe the bug**
Our customers trying to reset their password but they do not receive any mail from firebase. Gmail address  receive mail from Firebase but custom mail servers such as myname@example.com.tr doest not receive mails. Any Help? 
In addition to this, we also try to reset password from firebase console but the result is same. It is not code related issue. How can we solve it.

### Steps to reproduce
Register with a mail such as example@mycompany.com.tr

`await FirebaseAuth.instance.sendPasswordResetEmail(email: emailController.text.trim());`

### Expected behavior
Receive a mail from Firebase.

**Comment by darshankawar** [comment]
@ctykaya 
As we're just a wrapper on the official SDKs this isn't something we have control over, for this type of issue I'd recommend contacting [Firebase Support](https://firebase.google.com/support). 

Closing from here, as this isn't flutterfire plugin issue.
