### ISSUE TITLE
ios device did not receive push notification both foreground and background

### ISSUE THREAD

**Issue by LAIMX** [firebase/flutterfire#8508]
Hi, 
I have tried to applied Firebase Messaging, and follow the steps from: [apple-integration](https://firebase.flutter.dev/docs/messaging/apple-integration). 

```
flutter doctor: 
`/Users/acelai/Documents/development/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel beta, 2.13.0-0.2.pre, on macOS 11.6 20G165 darwin-arm (Rosetta), locale en-TW)
    • Flutter version 2.13.0-0.2.pre at /Users/acelai/Documents/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8662e22bac (3 days ago), 2022-04-20 08:21:52 -0700
    • Engine revision 24a02fa5ee
    • Dart version 2.17.0 (build 2.17.0-266.5.beta)
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/acelai/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/acelai/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/acelai/Library/Android/sdk
    • Java binary at: /Users/acelai/Library/Java/JavaVirtualMachines/corretto-11.0.13/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Corretto-11.0.13.8.1 (build 11.0.13+8-LTS)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5486

[✓] Connected device (3 available)
    • SM G960F (mobile) • 221d9c3033027ece          • android-arm64  • Android 10 (API 29)
    • ACE (mobile)      • 00008101-001D2D6E1AB8001E • ios            • iOS 14.4.1 18D61
    • Chrome (web)      • chrome                    • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
Process finished with exit code 0`
```

Also I have cloned the example from [example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example)

It worked at Android devices, but iOS device did receive nothing notification. 

Does anyone could help me with this issue... please

**Comment by LAIMX** [comment]
the below is the pub version
![image](https://user-images.githubusercontent.com/33712418/164887566-e5a1aea2-2fae-46e5-a08f-defff21b85f0.png)

**Comment by tharukachampit** [comment]
I have fixed this issue on my local by changing the firebase_messaging plugin's
 FLTFirebaseMessagingPlugin.m.
after 487 line add below else statement
else {
        [_channel invokeMethod:@"Messaging#onMessage" arguments:notificationDict];
        completionHandler(UIBackgroundFetchResultNoData);
      }
      
     and changing the my AppDelegate.swift as below
     
     import UIKit
import Flutter
import Firebase
import FirebaseAuth
import FirebaseMessaging

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {

  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {

    GeneratedPluginRegistrant.register(with: self)



      if #available(iOS 10.0, *) {
        // For iOS 10 display notification (sent via APNS)
        UNUserNotificationCenter.current().delegate = self

        let authOptions: UNAuthorizationOptions = [.alert, .badge, .sound]
        UNUserNotificationCenter.current().requestAuthorization(
          options: authOptions,
          completionHandler: { _, _ in }
        )
      } else {
        let settings: UIUserNotificationSettings =
          UIUserNotificationSettings(types: [.alert, .badge, .sound], categories: nil)
        application.registerUserNotificationSettings(settings)
      }

      application.registerForRemoteNotifications()

    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }

   //https://firebase.google.com/docs/auth/ios/phone-auth#appendix:-using-phone-sign-in-without-swizzling
        // https://firebase.google.com/docs/cloud-messaging/ios/client#token-swizzle-disabled
        override func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
            // Pass device token to auth
            Auth.auth().setAPNSToken(deviceToken, type: .unknown)

            // Pass device token to messaging
            Messaging.messaging().apnsToken = deviceToken

            return super.application(application, didRegisterForRemoteNotificationsWithDeviceToken: deviceToken)
        }

        // https://firebase.google.com/docs/auth/ios/phone-auth#appendix:-using-phone-sign-in-without-swizzling
        // https://firebase.google.com/docs/cloud-messaging/ios/receive#handle-swizzle
        override func application(_ application: UIApplication,
                                  didReceiveRemoteNotification notification: [AnyHashable : Any],
                                  fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
            // Handle the message for firebase auth phone verification
            if Auth.auth().canHandleNotification(notification) {
                completionHandler(.noData)
                return
            }

            // Handle it for firebase messaging analytics
            if ((notification["gcm.message_id"]) != nil) {
                Messaging.messaging().appDidReceiveMessage(notification)
            }

            return super.application(application, didReceiveRemoteNotification: notification, fetchCompletionHandler: completionHandler)
        }

        // https://firebase.google.com/docs/auth/ios/phone-auth#appendix:-using-phone-sign-in-without-swizzling
        override func application(_ application: UIApplication, open url: URL,
                                  options: [UIApplication.OpenURLOptionsKey : Any]) -> Bool {
            // Handle auth reCAPTCHA when silent push notifications aren't available
            if Auth.auth().canHandle(url) {
                return true
            }

            return super.application(application, open: url, options: options)
        }
}

**Comment by darshankawar** [comment]
@LAIMX 
Are you getting any error in the console when notifications are not being received ?
Can you check your APNs certificate from Firebase, Cloud Messaging,iOS ?

Also check if your debug certificate key has expired or not.

Or try to remove your certficate from Firebase and regenerate the certificate and readd it in Firebase, Cloud Messaging, iOS config.

Also make sure for iOS 9.0+, background mode is enabled in XCode.

**Comment by thiagosf** [comment]
I noticed that the Setting app info had no Notifications item, so I tried to add this method:

```dart
@override
  Widget build(BuildContext context) {
    FirebaseMessaging.instance.requestPermission();
    ...
```

And now it worked for me! I don't know if was the same problem, I hope it can help somebody else.
