### ISSUE TITLE
🐛 [app_check] [macOS] Cannot find type 'UIApplication' in scope

### ISSUE THREAD

**Issue by wliumelb** [firebase/flutterfire#8511]
I was following the documentation to set up debug provider for MacOS
https://firebase.flutter.dev/docs/app-check/debug-provider

/Runner/AppDelegate.swift
```
import Cocoa
import FlutterMacOS
import Firebase

@NSApplicationMain
class AppDelegate: FlutterAppDelegate {
  override func applicationShouldTerminateAfterLastWindowClosed(_ sender: NSApplication) -> Bool {
    return true
  }

  override func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
    let providerFactory = AppCheckDebugProviderFactory()
    AppCheck.setAppCheckProviderFactory(providerFactory)
    return true
  }
}
```

I got this compilation error: cannot find type 'UIApplication' in scope.

**Comment by benjitusk** [comment]
Did you find a solution to this?

**Comment by wliumelb** [comment]
This seems to work. 

```
import Cocoa
import FlutterMacOS
import Firebase

@NSApplicationMain
class AppDelegate: FlutterAppDelegate {
  override func applicationShouldTerminateAfterLastWindowClosed(_ sender: NSApplication) -> Bool {
    return true
  }
    
  override func applicationDidFinishLaunching(
    _ notification: Notification
  ) -> Void {
#if DEBUG
    let providerFactory = AppCheckDebugProviderFactory()
    AppCheck.setAppCheckProviderFactory(providerFactory)
#endif
    super.applicationDidFinishLaunching(notification)
  }
}

```

**Comment by Patrick386** [comment]
The value of 'App Check debug token' is not being output. Is there a way?
https://firebase.google.com/docs/app-check/ios/debug-provider

**Comment by Patrick386** [comment]
https://firebase.flutter.dev/docs/app-check/debug-provider/

desktop: MacOS
Wrong manual about 'MacOS'.
**Error 'UIApplication'   < UIKit is for mobile apps, not MacOS apps.** 

```
AppDelegate.swift
import Cocoa
import FlutterMacOS
import Firebase

@NSApplicationMain
class AppDelegate: FlutterAppDelegate {
  override func applicationShouldTerminateAfterLastWindowClosed(
  _ sender: NSApplication  ) -> Bool {
  FirebaseApp.configure()
    return true
  }
 override func application(_ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
    let providerFactory = AppCheckDebugProviderFactory()
    AppCheck.setAppCheckProviderFactory(providerFactory)
    return true
  }
}
```
**Error:**
<img width="1119" alt="스크린샷 2023-02-13 오후 9 53 30" src="https://user-images.githubusercontent.com/49754877/218463504-7302e6a5-76f0-4953-a9f0-95f2714ea11f.png">

**Comment by Patrick386** [comment]
MacOS: code

**Still no debug token output.**

```
import Cocoa
import FlutterMacOS
import Firebase

@NSApplicationMain
class AppDelegate: FlutterAppDelegate {
  override func applicationShouldTerminateAfterLastWindowClosed(
  _ sender: NSApplication  ) -> Bool {
    FirebaseApp.configure()
    return true
  }
  override func applicationDidFinishLaunching(_ aNotification: Notification) {
  #if DEBUG
        let providerFactory = AppCheckDebugProviderFactory()
        AppCheck.setAppCheckProviderFactory(providerFactory)
  #endif
        super.applicationDidFinishLaunching(aNotification)
    }
}
```
<img width="1187" alt="스크린샷 2023-02-13 오후 10 42 49" src="https://user-images.githubusercontent.com/49754877/218473834-e84f4d89-6bc0-4425-871d-fac2a5ff636f.png">

**Comment by wliumelb** [comment]
I managed to to get the debug token printed after I deleted `GoogleService-Info.plist` in `macos/Runner` folder, added firebase configuration through `flutterfire configure`, and run the program in Xcode instead of `flutter run`.

I think this issue is no longer relevant as the linked documentation has been labeled archived. A new issue should be filed if there if there is any other problems.
