### ISSUE TITLE
🐛 [firebase_messaging] PHONE_REGISTRATION_ERROR

### ISSUE THREAD

**Issue by mohdarslan** [firebase/flutterfire#8524]
## Bug report

**Describe the bug**
While fetching FCM device token in One Plus 9 (Android 12) this Exception is thrown
`[firebase_messaging/unknown] java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: PHONE_REGISTRATION_ERROR
`

**Comment by darshankawar** [comment]
@mohdarslan 
When you open an issue, please use new issue template and fill out requested details so that we'll have enough details to work with.
Only providing error message isn't helpful without providing `flutter doctor -v`, plugin version, complete error log and a minimal code sample, so please provide these details to address it properly.

**Comment by mohdarslan** [comment]
Hi @darshankawar,
I cannot provide flutter doctor -v because this issue has occurred on a user's device on release and I cannot replicate on debug.
We right now can see the error message only on Sentry.

My hypothesis is that this issue is only occurring on One Plus 9 because of OxygenOS.

The plugin version is firebase_messaging: ^10.0.9.

This occurs at 

final fcmToken = await FirebaseMessaging.instance.getToken();

**Comment by darshankawar** [comment]
@mohdarslan 
Thanks for the details. Can you provide the complete error log you get from Sentry ?

Also, the latest plugin version is https://pub.dev/packages/firebase_messaging/changelog#11215, so is it possible for you to upgrade to latest plugin version and check on same user's device if the same error occurs ?

**Comment by mohdarslan** [comment]
Hi @darshankawar ,
We don't have much error logs on Sentry as well.

Please check this, if this helps

FirebaseException: [firebase_messaging/unknown] java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: PHONE_REGISTRATION_ERROR
  File "method_channel_messaging.dart", line 229, in MethodChannelFirebaseMessaging.getToken

**Comment by darshankawar** [comment]
Thanks for the update. I am going to keep this issue open and label for further insights from the team.

A similar error was reported https://github.com/firebase/flutterfire/issues/1471 which was closed sighting updates to the plugin. 

/cc @russellwheatley

**Comment by lakharasachin-qf** [comment]
Hello guys I m facing the issue last day it's working but now it shows me error like

 [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: [firebase_messaging/unknown] java.io.IOException: 
java.util.concurrent.ExecutionException: java.io.IOException: PHONE_REGISTRATION_ERROR

**Comment by russellwheatley** [comment]
Hey folks, this is not something we have control over. It could be an issue with OxygenOs as mentioned by the OP. Or it could be a configuration problem. I'd encourage you to install the latest version of the FlutterFire CLI (`dart pub global activate flutterfire_cli`) which will write your google service files for android & iOS. I would encourage you to read advice from other developers who've experienced similar problems like in this [SO article](https://stackoverflow.com/questions/60698622/java-io-ioexception-fis-auth-error-in-android-firebase) to help you debug. Please double check you've also gone through the [necessary configuration](https://firebase.google.com/docs/cloud-messaging/flutter/client) to setup firebase_messaging. Thanks.
