### ISSUE TITLE
🐛 [firebase_messaging]  Flutter foreground without data-notification iOS not working

### ISSUE THREAD

**Issue by arthas1888** [firebase/flutterfire#8548]
## Bug report

**Describe the bug**
I have a .Net Core Server it sends a msg through firebase using FirebaseAdmin.Messaging The way to send it is something like this:
               
               // Create a list containing up to 500 registration tokens.               
                var message = new MulticastMessage()
                { 
                    Tokens = registrationTokens,                       
                    Data = new Dictionary<string, string>()
                    {
                        { "class_name", request.ClassName.ToLower() },
                        { "action", request.Action.ToString() },
                        { "id", request.Id },
                        { "type", "update_model" },
                        { "all", all.ToString().ToLower() },
                        { "obj", string.IsNullOrEmpty(jsonToSend) ? "" : jsonToSend },
                    },
                };
                await FirebaseMessaging.DefaultInstance.SendMulticastAsync(message);

In flutter I receive the msg:

        FirebaseMessaging.onMessage.listen((RemoteMessage message) {
           generalLog.info('Got a message whilst in the foreground!');
          generalLog.info('Message data: ${message.data}');
          });

As you can see I send the msg without the param Notification, because I use just to update some process in flutter for instance fetch an object and update the local db in flutter for this reason I don't need to show the notification, in Android it works, but in iOS I never see this enter to the method FirebaseMessaging.onMessage.listen((RemoteMessage message)... I realize that if I put the param Notification in C# like this

            var message = new MulticastMessage()
            {
                Tokens = registrationTokens,
                Notification = new Notification
                {
                    Body = "background process",
                    Title = "background",
                },
                Data = new Dictionary<string, string> {
                    { "obj", msgToSend},
                    { "type", "chat" }
                },
            };

The msg gets in iOS, but I don't want this, because in background I receive a lot of notifications

### Steps to reproduce

My phone has the default configuration
IOS 15
iPhone 7 PLUS

### Sample project
the code is the same than this repository https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example
and follow this guide https://firebase.flutter.dev/docs/messaging/apple-integration

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
     dependencies:
            flutter:
              sdk: flutter              
          
            # The following adds the Cupertino Icons font to your application.
            # Use with the CupertinoIcons class for iOS style icons.
            cupertino_icons: ^1.0.2
            firebase_messaging: ^11.2.13
            flutter_local_notifications: ^9.4.0
            http: ^0.13.4
```

</details>

        
### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):

[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3 21E230 darwin-arm, locale

    en-CO)

[✗] Android toolchain - develop for Android devices

    ✗ Unable to locate Android SDK.

      Install Android Studio from:

      https://developer.android.com/studio/index.html

      On first launch it will assist you in installing the Android SDK

      components.

      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup

      for detailed instructions).

      If the Android SDK has been installed to a custom location, please use

      `flutter config --android-sdk` to update to that location.



[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)

[✓] Chrome - develop for the web

[!] Android Studio (not installed)

[✓] VS Code (version 1.66.2)

[✓] Connected device (1 available)

[✓] HTTP Host Availability
```

</details>

---

---

**Comment by darshankawar** [comment]
@arthas1888 Thanks for the report.

> I have a .Net Core Server it sends a msg through firebase using FirebaseAdmin

Does this behavior only occur when using it ? Can you try to send the same payload via Firebase Console or other REST api directly and see if the same behavior persists or not ?

**Comment by arthas1888** [comment]
same behavier, in firebase console is not possible to emulate it because always yo need to set the notification object, in postman I send the following:

     {
    "priority": "high",
    "data": {
        "update": true
    },
    "to": "xxxxxxx.....",
    "notification": {
        "body": "test",
        "title": "test"
      }
   }
I can see the notification in the App
![image](https://user-images.githubusercontent.com/5170748/166252441-d2991a84-4e03-4246-bd85-68c175ed80d0.png)

without notification object same behavior in iOS, the  FirebaseMessaging.onMessage.listen((RemoteMessage message)) method never fires

**Comment by darshankawar** [comment]
Thanks for the update. I am going to keep this issue open and label it for further insights from the team.

/cc @russellwheatley

**Comment by arthas1888** [comment]
thanks

**Comment by victorkwok97** [comment]
Hi, I have the exact same issue. It works on Android, but not firing on iOS when notification is not set

```
import {getMessaging} from "firebase-admin/messaging"

function x() {
    const m = getMessaging()
    m.sendToDevice([
            tokenHere
        ],{
            "data": {
                "a": "b",
            }
        }, {
            "content_available": true,
            "priority": "high"
        }
    ).then(e=>console.log(JSON.stringify(e.results))).catch(e=>console.log(JSON.stringify(e.results)));
}
x()
```

```
FirebaseMessaging.onMessage.listen((RemoteMessage message) {
     // Not firing
      print('Got a message whilst in the foreground!');
    });
```

**Comment by PapyElGringo** [comment]
Still broken check PR comments

**Comment by victorkwok97** [comment]
Still not working for me as well on version 11.4.0 firebase_messaging.

**Comment by victorkwok97** [comment]
@darshankawar 
It is still broken using version 11.4.1 firebase_messaging.

> Hi, I have the exact same issue. It works on Android, but not firing on iOS when notification is not set
> 
> Minimal reproduction script:
> 
> ```
> import {getMessaging} from "firebase-admin/messaging"
> 
> function x() {
>     const m = getMessaging()
>     m.sendToDevice([
>             tokenHere
>         ],{
>             "data": {
>                 "a": "b",
>             }
>         }, {
>             "content_available": true,
>             "priority": "high"
>         }
>     ).then(e=>console.log(JSON.stringify(e.results))).catch(e=>console.log(JSON.stringify(e.results)));
> }
> x()
> ```
> 
> In flutter:
> 
> ```
> FirebaseMessaging.onMessage.listen((RemoteMessage message) {
>      // Not firing
>       print('Got a message whilst in the foreground!');
>     });
> ```
