### ISSUE TITLE
🐛 [flutterfire_ui] twitter_login crash 

### ISSUE THREAD

**Issue by Tom3652** [firebase/flutterfire#8555]
## Bug report

**Describe the bug**

The issue is spotted here in [twitter_login](https://github.com/0maru/twitter_login/issues/86).

### Expected behavior

My app doesn't use twitter_login but uses ```flutterfire_ui```. Also, my app only use email/password login from firebase, not twitter_login.

Would it be possible to not bind all dependencies for people who don't need multiple auth providers and that would lead to errors like this ? 
For now i have to remove this package unfortunately and make my own UI to support only email/password login without dependencies i don't need and that make my production app crashing :/ 

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-x64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.66.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by darshankawar** [comment]
@Tom3652 
What's the flutterfire_ui version are you seeing this on ?
Recently a related issue was fixed and the `twitter_login plugin version was upgraded as part of this fix, https://pub.dev/packages/flutterfire_ui/changelog#0403

https://github.com/firebase/flutterfire/issues/8405. So please upgrade the plugin version if not already and see if it helps to fix this behavior.

**Comment by Tom3652** [comment]
I am seeing this error with the latest version (for now) of the plugin : `0.4.0+4` 
The error is actually described in the twitter_login repo as i have mentioned so it's not up to you to fix it of course. 

However, i was simply wondering if it would be possible to split the flutterfire_ui to not have these useless dependencies for some projects that only support basic authentication and not custom auth providers.

**Comment by darshankawar** [comment]
Thanks for the update and clarifying. Keeping it open and labeling it for further insights from the team on this request.

/cc @lesnitsky

**Comment by lesnitsky** [comment]
we will be decoupling oauth providers from the core UI library, so this won't be an issue anymore
