### ISSUE TITLE
[📚] "Detailed walkthrough involving Realtime Database and Cloud Functions" link is broken.

### ISSUE THREAD

**Issue by gerryau** [firebase/flutterfire#8559]
I am trying to setup flutterfire with emulator suite and was reading through the documentation and unfortunately discovered a broken link here:

https://firebase.flutter.dev/docs/database/read-and-write/#optional-prototype-and-test-with-firebase-emulator-suite

Press link: "Detailed walkthrough involving Realtime Database and Cloud Functions".

**Comment by darshankawar** [comment]
Thanks for the report. Broken links are tracked in this issue: https://github.com/firebase/flutterfire/issues/6751, so I'll close this in favor of the original.
