### ISSUE TITLE
[firebase_storage] GTMSessionFetcher invoking fetch callbacks logs

### ISSUE THREAD

**Issue by loic-hamdi** [firebase/flutterfire#8564]
In `firebase_storage: ^10.2.12` anytime I launch on iPhone 13 physical device:

```dart
imgUrl = await FirebaseStorage.instance.refFromURL('gs://my-great-app-1.appspot.com/$urlToMyImage').getDownloadURL();
```

I receive the log error:

```
GTMSessionFetcher invoking fetch callbacks, data {length = 579, bytes = 0x7b0a2020 226e616d 65223a20 22706174 ... 31356666 63220a7d }, error (null)
```

**Comment by darshankawar** [comment]
@zzterrozz 
Can you provide the entire error log ? Does it show something like `error Error Domain=NSURLErrorDomain Code` ?

The code being returned will be helpful to debug further.

**Comment by zzterrozz** [comment]
@darshankawar   Unfortunately nothing really to share..

Here is the logs when I load 20 images at the same time with 

```dart
imgUrl = await FirebaseStorage.instance.refFromURL('gs://my-great-app-1.appspot.com/$urlToMyImage').getDownloadURL();
```

```dart
FadeInImage.memoryNetwork(
image: imgUrl,
height: 200,
width: 200,
imageErrorBuilder: (context, error, stackTrace) => Image.asset('assets/images/error.jpg', fit: BoxFit.fitWidth),
),
```

<img width="1061" alt="firestore" src="https://user-images.githubusercontent.com/3080026/166465541-e56b68c5-ee80-4cef-8a67-92267bdcd25e.png">

**Comment by darshankawar** [comment]
@zzterrozz 
I tried the official plugin [example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_storage/firebase_storage/example) which uses `getDownloadUrl()` method as below:

```
body: _uploadTasks.isEmpty
          ? const Center(child: Text("Press the '+' button to add a new file."))
          : ListView.builder(
        itemCount: _uploadTasks.length,
        itemBuilder: (context, index) => UploadTaskListTile(
          task: _uploadTasks[index],
          onDismissed: () => _removeTaskAtIndex(index),
          onDownloadLink: () async {
            return _downloadLink(_uploadTasks[index].snapshot.ref);
          },
          onDownload: () async {
            if (kIsWeb) {
              return _downloadBytes(_uploadTasks[index].snapshot.ref);
            } else {
              return _downloadFile(_uploadTasks[index].snapshot.ref);
            }
          },
        ),
      ),
```

Ran it on iPhone 6s device but didn't get the said error log.



> Here is the logs when I load 20 images at the same time with

Does it only occur while executing this case ? 

Also, can you try the same plugin example on same device and see if you still get the log ?

**Comment by zzterrozz** [comment]
Hi @darshankawar 

I was not able to reproduce your example because I don't use firebase emulator.

However I can confirm that I have the same behavior on physical device  `iPhone 11 Pro Max - iOS 15.4.1`, however on emulator `iPhone 13 - iOS 15.4`  it does not show the log error message.

**Comment by darshankawar** [comment]
I am unable to replicate this issue on the device I tried, but looking at the report and error log as, it doesn't show a complete error, keeping it open for further insights from the team.

`GTMSessionFetcher invoking fetch callbacks, data {length = 579, bytes = 0x7b0a2020 226e616d 65223a20 22706174 ... 31356666 63220a7d }, error (null)`

**Comment by russellwheatley** [comment]
@zzterrozz does this occur only when you upload many images? or can you reproduce with just 1?

**Comment by zzterrozz** [comment]
> @zzterrozz does this occur only when you upload many images? or can you reproduce with just 1?

hi @russellwheatley , it happens for any quantity.

**Comment by Lyokone** [comment]
@loic-hamdi Do you still reproduce this error with the latest version of Firebase Storage?
