### ISSUE TITLE
🐛  [firebase_messaging] When mobile phone lock screen, BackgroundMessage method sometime working On Android12

### ISSUE THREAD

**Issue by niumj** [firebase/flutterfire#8590]
## Bug report
Add <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>  in Androidmanifest.xml
Android10 and Android11 , everything works OK, but Android12, when send continous FCM messages , sometimes receive only one message.  
Any permission or settings ?

## Additional context
[
[Add any other context about the problem here.

---](https://github.com/firebase/flutterfire/issues/8485)](https://github.com/firebase/flutterfire/issues/8485)

### Flutter doctor

flutter doctor -v
[√] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.17763.1577], locale ja-JP)
• Flutter version 2.10.4 at H:\DevelopTool\Mobile\flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision c860cba910 (4 weeks ago), 2022-03-25 00:23:12 -0500
• Engine revision 57d3bac3dd
• Dart version 2.16.2
• DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
PASTE OUTPUT INSIDE HERE
```

**Comment by darshankawar** [comment]
> Any permission or settings ?

Check [this](https://developer.android.com/about/versions/12/behavior-changes-12) official Android documentation related to Android 12 and see if it helps.

**Comment by niumj** [comment]
It works OK by the version [11.3.0](https://pub.flutter-io.cn/packages/firebase_messaging/versions/11.3.0).
But the reason is still unknown.

**Comment by niumj** [comment]
From version11.4.0 on, this issue is reopened.

**Comment by darshankawar** [comment]
@niumj 
Please upgrade to latest stable and latest plugin version to confirm if behavior persists or not.
