### ISSUE TITLE
[📚] Analytics manually track screens on firebase.google.com is wrong

### ISSUE THREAD

**Issue by gianmarcocalbi** [firebase/flutterfire#8592]
The documentation as to how manually track screens differs in the Flutterfire docs and Google Firebase docs: the latter is wrong.

### ✅ Flutterfire docs

https://firebase.flutter.dev/docs/analytics/screenviews#manually-track-screens

```dart
await FirebaseAnalytics.instance
  .setCurrentScreen(
    screenName: 'Products'
  );
```

### ❌ Google Firebase docs
https://firebase.google.com/docs/analytics/screenviews#manually_track_screens

```dart
await FirebaseAnalytics.instance.logEvent(
  name: 'screen_view',
  parameters: {
    'firebase_screen': screenName,
    'firebase_screen_class': screenClass,
  },
);
```

From what I can see in the flutter firebase_analytics plugin source code, it's not even allowed to send parameters with the `firebase_` prefix, meaning the docs on firebase.google.com is wrong.

**Comment by darshankawar** [comment]
@gianmarcocalbi 
Since firebase.google.com related issue probably need to be filed using Firebase support https://firebase.google.com/support, so please raise this issue there.

Closing, as, per your comment, the flutterfire document seems to be correct.
