### ISSUE TITLE
🐛 [FCM] Expose android integer id value so notifications can be cancelled.

### ISSUE THREAD

**Issue by Turburlar** [firebase/flutterfire#8596]
The android platform provides a means to cancel notifications by an integer ID.

https://developer.android.com/reference/android/app/NotificationManager#cancel(int)

The flutter_local_notifcations plugin exposes this method and takes an int ID...

https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/AndroidFlutterLocalNotificationsPlugin/cancel.html

But an FCM AndroidNotification class does not expose a notifications int ID...

https://pub.dev/documentation/firebase_messaging_platform_interface/latest/firebase_messaging_platform_interface/AndroidNotification-class.html

It should...

**Comment by darshankawar** [comment]
Thanks for the report. Treating this as an enhancement for the plugin.

**Comment by russellwheatley** [comment]
Hey @Turburlar, thanks for the suggestion! FlutterFire is essentially a thin wrapper around the native Firebase SDKs. 

I'm afraid your suggestion is outside the scope of FlutterFire. It appears you could use another plugin (like the one you linked) or implement yourself for such a purpose 🙏 .
