### ISSUE TITLE
[📚] FlutterFire docs down?

### ISSUE THREAD

**Issue by davidhicks980** [firebase/flutterfire#8607]
All FlutterFire routes redirect to https://firebase.google.com/docs/flutter/setup?platform=ios. My apologies if this is routine maintenance!

**Comment by davidhicks980** [comment]
Hey Elliot,

Thanks for your quick response! Every old link I've used has redirected me to the link I posted. Let me know if this does not happen with you: https://firebase.flutter.dev/docs/ui/overview/. I tried on a few different browsers.

**Comment by davidhicks980** [comment]
Oh -- it looks like this may be a Firebase UI issue...?

**Comment by Ehesp** [comment]
Thanks, I've added a redirect PR for the UI.

For now, you can access them here: https://github.com/firebase/flutterfire/tree/master/packages/flutterfire_ui

**Comment by klartraum-medien** [comment]
I am unable to access the documentation at the moment. "Service Unavailable" for example at [https://firebase.google.com/docs/analytics/events](https://firebase.google.com/docs/analytics/events)

**Comment by Ehesp** [comment]
@klartraum-medien That link is working for me; specifically: https://firebase.google.com/docs/analytics/events?platform=flutter

Could you post a screenshot?

**Comment by klartraum-medien** [comment]
> @klartraum-medien That link is working for me; specifically: https://firebase.google.com/docs/analytics/events?platform=flutter
> 
> Could you post a screenshot?

<img width="1439" alt="Bildschirmfoto 2022-05-06 um 17 09 03" src="https://user-images.githubusercontent.com/99197246/167161262-dc30ab1b-c678-4309-91fb-777c541462ee.png">

**Comment by Ehesp** [comment]
Could be adblocker? I think this is a none issue on our end anyway

**Comment by atsuya** [comment]
I'm trying to go to this page (https://firebase.flutter.dev/docs/firestore-odm/defining-models/), but it's taking me to the wrong page.

**Comment by wespal34** [comment]
Why are all links from the old documentation lead to this url [https://firebase.google.com/docs/flutter/setup?platform=ios](url)?

**Comment by stark87** [comment]
> The documentation is moving to the firebase.google.com - redirects are setup to navigate to the correct location from the old URLs - however if you think one is missing please let us know.

All the old links redirect here [https://github.com/firebase/flutterfire/issues/url](url) and they are not the same docs. At least not written in the same way.

**Comment by maganap** [comment]
Why is this issue closed?
No matter what documentation I'm trying to reach, they all lead to 
https://firebase.google.com/docs/flutter/setup?platform=ios

Where is the "cloud_firestore" documentation, for example, currently located?

I can only reach this from the "API Reference -> Flutter" menu:
https://firebase.google.com/docs/firestore/quickstart
which is a generic site, not the Flutter documentation.

Even if you select the "Dart/Flutter" option in the code samples (which is not available in all cases), you get some (sorry to say, lame) examples which are not even close to the wonderful quickstart and documentation that was previously located at flutterfire website  :-(
Where can we see something similar to the previous documentation?
You shouldn't have migrated to the "new documentation" if it's still so poor, I must say.
