### ISSUE TITLE
🐛 [FirestoreListView] empty property is not exist in flutterfire_ui: ^0.4.0+5

### ISSUE THREAD

**Issue by saveKenny** [firebase/flutterfire#8614]
I want to detect an empty list of items, using `FirestoreListView`, in order to present a Text widget to the screen.

The official `FirestoreListView` dart API documentation mentions that the [empty](https://pub.dev/documentation/app_base/latest/app_base/FirestoreListView/empty.html) property gets a WidgetBuilder in case of empty items.

However, the `FirestoreListView` [constructor](https://github.com/firebase/flutterfire/blob/83e2d455d3a083886168b4c115191b06e307a41f/packages/flutterfire_ui/lib/src/firestore/query_builder.dart#L416) of flutterfire_ui: ^0.4.0+5, does not contain the mentioned `empty` property.

**Comment by saveKenny** [comment]
Any news?

**Comment by k00na** [comment]
I also miss this feature...

**Comment by deonjo** [comment]
yes please fix, I would like to able to display a message explaining why the list is empty to users

**Comment by almogtovim** [comment]
I spent so much time on this. There was no way I would believe it was possible.

**Comment by flikkr** [comment]
Can we prioritize this? Such a small addition should be easy to implement and would have a big upside.

**Comment by almogtovim** [comment]
You can solve it using FirestoreQueryBuilder instead of FirestoreListView.
Here is my code:
` Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Scaffold(
      body: FirestoreQueryBuilder<Dive>(
        query: DivesRepository.myGroupDivesStream(groupID),
        builder: (context, snapshot, _) {
          final docsLength = snapshot.docs.length;
          if (snapshot.isFetching) {
            return const AppLoader();
          }
          if (snapshot.hasError) {
            logError(snapshot.error);
            return Center(child: Text('Sorry,something went wrong!'));
          }
          if (docsLength == 0) {    // <-------- No document case
            return Center(child: Text('No dives are book yet.')); 
          }
          return ListView.builder(
            itemCount: docsLength,
            itemBuilder: (context, index) {
              final dive = snapshot.docs[index].data();
              return SomeWidget();
            },
          );
        },
      ),
    );
  }`
