### ISSUE TITLE
[📚] The flutterfire_ui README links are broken, they point to a folder called 'docs' instead of 'doc' 

### ISSUE THREAD

**Issue by pedrobalao** [firebase/flutterfire#8628]
The flutterfire_ui documentation folder is called 'doc' instead of 'docs'. This breaks the links on the [flutterfire_ui/readme](https://github.com/firebase/flutterfire/tree/master/packages/flutterfire_ui/README.md).

**Comment by kevinthecheung** [comment]
(Same comment as #8629)

Should we fix the README instead? The Dart docs say the [docs directory should be called 'doc/'](https://dart.dev/tools/pub/package-layout#documentation).

**Comment by darshankawar** [comment]
Thanks for the report.

Current link in https://github.com/firebase/flutterfire/blob/master/packages/flutterfire_ui/README.md points to https://github.com/firebase/flutterfire/blob/master/packages/flutterfire_ui/docs/auth.md which gives 404 .

Correct link is : https://github.com/firebase/flutterfire/blob/master/packages/flutterfire_ui/doc/auth.md

Similar issue for tracking : https://github.com/firebase/flutterfire/issues/6751
