### ISSUE TITLE
[📚] FlutterFire was removed and official documentation have nothing about flutter implementation

### ISSUE THREAD

**Issue by d-apps** [firebase/flutterfire#8639]
FlutterFire was removed and official documentation have nothing about implementation using flutter/dart.

https://firebase.google.com/docs/firestore/quickstart

![Screen Shot 2022-05-11 at 18 11 32](https://user-images.githubusercontent.com/20110433/167948516-8a4f8dd1-537c-4553-9046-a957b9461688.png)

**Comment by paviln** [comment]
Yes please bring it back.

**Comment by kevinthecheung** [comment]
Some of the translations were behind, but they're starting to show up now:

![image](https://user-images.githubusercontent.com/11839002/168165636-cbf7c49c-5de0-418b-b17a-9bd23e4cabd7.png)

**Comment by lucascardo12** [comment]
why was all flutter docs removed in firebase?

**Comment by inclu-cat** [comment]
I found out it was back!

**Comment by russellwheatley** [comment]
I think we can close this out now that the Flutter implementations are showing for each plugin. If there is a gap in the documentation, a new issue can be raised here to address that specific aspect of the documentation.
