### ISSUE TITLE
ci: workflow `all_plugins` fails because of Flutter 3.0.0

### ISSUE THREAD

**Issue by nilsreichardt** [firebase/flutterfire#8644]
See: https://github.com/firebase/flutterfire/runs/6398175458?check_suite_focus=true

Blocked by:
* #8645 
* #8646 
* #8647 
* #8648 
* #8649

**Comment by Fieora** [comment]
#8692 might be related

**Comment by nilsreichardt** [comment]
The `all_plugins` workflow should work again because all PRs got merged. Therefore, we can close this ticket.

**Comment by nilsreichardt** [comment]
The `all_plugins` workflow should work again because all PRs got merged. Therefore, we can close this ticket.
