### ISSUE TITLE
🐛 [Firebase_analytics] DebugView do not display event when run project by Flutter CLI

### ISSUE THREAD

**Issue by mrkhanhkhi** [firebase/flutterfire#8662]
## Bug report

**Describe the bug**
After pass the -FIRDebugEnabled argument to Xcode, the DebugView received event when project is built by Xcode, but not by using Flutter CLI
Same as this issues, but I found that its still not be answered properly and can be reproduced
https://github.com/firebase/flutterfire/issues/1586

### Steps to reproduce

1. Integrate Firebase core + Firebase analytics, verify the app keys and configures 
2. Enable debug mode as guideline https://firebase.google.com/docs/analytics/debugview

3. Try to build project by Xcode and by Flutter CLI
4. Check the Debug View and the no event emitted from the project built by Flutter CLI. 

### Expected behavior

Events display properly in DebugView when building project by Flutter CLI

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-x64, locale en-VN)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.67.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

dependencies:

---

**Comment by darshankawar** [comment]
> Flutter CLI

Are you referring to flutterfire CLI tool that you use to configure firebase project with flutter app ? (ex: `flutterfire configure`) ?

**Comment by mrkhanhkhi** [comment]
@darshankawar Nope, I use the `flutter run` command, and after one night, the debug view worked properly. However, it seems like everytime I run the `flutterfire config` command, the debug view halt again.

**Comment by darshankawar** [comment]
@mrkhanhkhi 
Thanks for the update. Can you provide a minimal code sample that shows this behavior ?
