### ISSUE TITLE
🐛 [firebase_core] No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core

### ISSUE THREAD

**Issue by Kirchesch** [firebase/flutterfire#8684]
### Description
The app won't work when building for Windows, it works fine for Android and the Web

### Steps to reproduce
1. Create a new Flutter app
2. Add Firebase to the app following the Firebase guid for Flutter ( Choose Android, Web and Windows )
3. Initialize Firebase on the app entry point before calling runApp
4. Now build for Web and Android to test if it is working
5. If step 4 is working fine build for Windows, you will get the problem on your console and the app will be just a white screen

### Expected behavior
Well the app should just build haha

### Sample project
I think its faster to just use the VS Code extension to create a new project

---

## Additional context
- I have used VS Code to create the Flutter project
- I have used the fluterfire cli to add firebase to the app

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.0, on Microsoft Windows [Version 10.0.22621.1], locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.0)
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.67.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.17.0
Flutter SDK 3.0.0
odin 1.0.0+1

dependencies:
- cupertino_icons 1.0.4
- firebase_auth 3.3.18 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.17.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]

dev dependencies:
- flutter_lints 2.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.16.0
- fake_async 1.3.0 [clock collection]
- firebase_auth_platform_interface 6.2.6 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.3.15 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.4.0 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.6.4 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- js 0.6.4
- lints 2.0.0
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.4
- meta 1.7.0
- path 1.8.1
- plugin_platform_interface 2.1.2 [meta]
- sky_engine 0.0.99
- source_span 1.8.2 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.9 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.1 [collection]
- vector_math 2.1.2
```

</details>

---

**Comment by pr-Mais** [comment]
Hi! Windows isn't supported here, you need to add [firebase_core_desktop](https://pub.dev/packages/firebase_core_desktop) first to get it supported. Please check [this blog](https://invertase.io/blog/announcing-flutterfire-desktop-auth-stable) for more details on how to add it.

**Comment by Kirchesch** [comment]
@pr-Mais but are there plans for Windows to be supported? I mean, the firebase cli now includes Windows in the initialize list

**Comment by pr-Mais** [comment]
Officially no, but Invertase is sponsoring the [FlutterFire Desktop](https://github.com/invertase/flutterfire_desktop) project which add Windows and Linux support using the same platform interface of FlutterFire, this is the [Roadmap](https://github.com/invertase/flutterfire_desktop/issues/52), check[ this discussion](https://github.com/firebase/flutterfire/discussions/5557).
