### ISSUE TITLE
🐛 [cloud_storage] App Check verification request

### ISSUE THREAD

**Issue by tgpsantos** [firebase/flutterfire#8693]
Hello guys,

My app is using Firestore and Storage services. I'm about to implement App Check so that I can enforce it in production in a couple of weeks.

I've followed the guidelines to implement it and it seems that everything's working OK for Firestore; as you can see in the following [picture](https://user-images.githubusercontent.com/48353485/168659060-8a25d1a1-3a7e-4a2a-a65e-fe98fdd22114.PNG), I'm starting to get verified requests as expected.

However, I'm not getting the same results from Cloud Storage - requests are still unverified - as you can see in the following [image](https://user-images.githubusercontent.com/48353485/168659155-a46a8cd2-92e7-4222-a1fc-6009ea66a2b3.PNG). 

Any idea on what might be wrong here? Is it even possible to get validated requests from one service whilst the other remains unverified?

### Flutter dependencies
firebase_core: 1.17.0
firebase_app_check: 0.0.6+12
cloud_firestore: 3.1.15
firebase_storage: 10.2.16

**Comment by darshankawar** [comment]
@tgpsantos 
According to [this](https://firebase.google.com/docs/app-check) document, `app_check` is supported for `cloud_storage` plugin, so it ideally should work for the said plugin.

Do you get any error or log that will help to debug further when it does not verify for cloud_storage ?

**Comment by tgpsantos** [comment]
I've just spotted the mistake in the client code. I'm getting verified requests now. Appreciate your feedback! @darshankawar 

Closing this
