### ISSUE TITLE
🐛 [firebase_remote_config] MethodChannel does not throw the correct error

### ISSUE THREAD

**Issue by TabooSun** [firebase/flutterfire#8716]
## Bug report

**Describe the bug**
On Android, all the remote config platform channel throws `FormatException: Invalid envelope` when there is an exception during the execution of the `Task`.

Version: `firebase_remote_config: ^2.0.7`

In `src/main/java/io/flutter/plugins/firebase/firebaseremoteconfig/FirebaseRemoteConfigPlugin.java:line 175`, null is passed to the `errorCode` arguments.

This is the reason causing this issue.

### Steps to reproduce

The way I test this is by commenting out all the code in callback and run `result.error` directly.

```java
methodCallTask.addOnCompleteListener(
  task -> {
    result.error(null, "", "");
    /*if (task.isSuccessful()) {
      result.success(task.getResult());
    } else {
      Exception exception = task.getException();
      Map<String, Object> details = new HashMap<>();
      if (exception instanceof FirebaseRemoteConfigFetchThrottledException) {
        details.put("code", "throttled");
        details.put("message", "frequency of requests exceeds throttled limits");
      } else if (exception instanceof FirebaseRemoteConfigClientException) {
        details.put("code", "internal");
        details.put("message", "internal remote config fetch error");
      } else {
        details.put("code", "unknown");
        details.put("message", "unknown remote config error");
      }
      result.error(null, exception != null ? exception.getMessage() : null, details);
    }*/
  });
```

### Expected behavior

A proper exception like `FirebaseRemoteConfigFetchThrottledException`, `FirebaseRemoteConfigClientException` or `unknown` should be thrown, instead of `FormatException: Invalid envelope`.

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by darshankawar** [comment]
@TabooSun 
I think this is same issue as https://github.com/firebase/flutterfire/issues/7425 and the root-cause seems to be what is explained here: https://github.com/firebase/flutterfire/issues/7425#issuecomment-1114170974

I suggest you to follow-up in it for further updates. Also the PR you have raised to fix this issue can be updated to link the original one.
Closing this in favor of linked issue. If you disagree, write in comments and I'll reopen it.
