### ISSUE TITLE
🐛 [firebase_core] Old docs recommend which points to a non-existing website

### ISSUE THREAD

**Issue by nilsreichardt** [firebase/flutterfire#8730]
https://user-images.githubusercontent.com/24459435/169665246-6c002e65-a3f0-4e3a-b106-35ed48726b82.mov

https://firebase.flutter.dev/docs/core/usage/ points to https://firebase.google.com/docs/flutter/start

**Comment by nilsreichardt** [comment]
cc: @kevinthecheung

**Comment by nilsreichardt** [comment]
I think the link should be https://firebase.google.com/docs/flutter/setup, right?

@kevinthecheung Where can I find the files for this to create a PR? In the `docs` folders are only the new docs for firebase.google.com

**Comment by kevinthecheung** [comment]
They're  in the [old-docs branch](https://github.com/firebase/flutterfire/tree/old-docs/docs). Thanks a ton for all your work on this!

**Comment by nilsreichardt** [comment]
Ah, get it 😅  Thanks :)

I help where I can ✌️

**Comment by nilsreichardt** [comment]
Implemented in https://github.com/firebase/flutterfire/pull/8775
