### ISSUE TITLE
Foreground Notification onClick/OnTap Not Working

### ISSUE THREAD

**Issue by parmarravi** [firebase/flutterfire#8743]
I am testing FCM on android One Plus 7T 11 Os version API 30

The background notification is working fine and also the tap event . However if app is foreground the notification comes but on tap event is not working. Where will this event trigger exactly?

I have tried sending message from firebase console with following data

```
data : {"click_action": "FLUTTER_NOTIFICATION_CLICK","result":2}

click_action: FLUTTER_NOTIFICATION_CLICK
```

FCM RESPONSE ON APP

`{title: test, titleLocArgs: [], titleLocKey: null, body: message, bodyLocArgs: [], bodyLocKey: null, android: {channelId: 121, clickAction: null, color: null, count: null, imageUrl: https://firebasestorage.googleapis.com/v0/b/test-44565.appspot.com/o/banner.png?alt=media&token=fd87464646-4646-6c8b8a41b, link: null, priority: 0, smallIcon: null, sound: default, ticker: null, tag: campaign_collapse_key_6646698564310595869, visibility: 0}, apple: null, web: null}`

data

` {data: {"click_action": "FLUTTER_NOTIFICATION_CLICK","result":2}, id: 1, click_action: FLUTTER_NOTIFICATION_CLICK, status: done}`

PUBspec

```
  firebase_core: ^1.17.0
  firebase_analytics: ^9.1.8
  firebase_crashlytics: ^2.8.0
  firebase_auth: ^3.3.18
  cloud_firestore: ^3.1.15
  firebase_database: ^9.0.14
  firebase_storage: ^10.2.16
  firebase_app_check: ^0.0.6+12
  firebase_messaging: ^11.4.0
  firebase_dynamic_links: ^4.2.3
  firebase_core_web: ^1.6.4

```

Added in Manifest in Main Activity

      <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>

```

    await flutterLocalNotificationsPlugin.show(
      121,
      remoteNotification.title,
      bodyMsg,
      platformChannelSpecifics,
      payload: "Notification",
    );
```

I would request to add this feature in one listener that is    FirebaseMessaging.onMessageOpenedApp.listen((message) {}  or something same that will trigger when user taps on notifciation

**Comment by darshankawar** [comment]
Check if [this](https://github.com/firebase/flutterfire/issues/6011) issue is similar to yours and the underlying comments helps to get foreground notifications working at your end.

**Comment by parmarravi** [comment]
No this issue is about firing OnMessage Function. That is working fine . 

I am using OnMessage  to show the local notification . 

However when taps on this notification this event is not getting listen anywhere .

So assume I want to redirect the user only if S/he taps on this notification, I just can't do it in Foreground Notification. 

As there is nothing on the code level to listen for tap event when notification is in foreground.
