### ISSUE TITLE
🐛 [firebase_crashlytics] ios/Pods/FirebaseCrashlytics/upload-symbols  --build-phase -ai FIREBASE_APP_ID: No such file or directory

### ISSUE THREAD

**Issue by nilsreichardt** [firebase/flutterfire#8744]
## Bug report

**Describe the bug**
I added `firebase_crashlytics` to my project. I followed steps to upload the `dSYM` files ("If this run script does not exist, you can add it manually:"): https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=flutter&authuser=4&hl=en 

```
NilsMBP13M13:crashlytics_dsym nils$ flutter run
Launching lib/main.dart on iPhone 11 in debug mode...
Running pod install...                                           1,729ms
Running Xcode build...                                                  
 └─Compiling, linking and signing...                      2,101ms
Xcode build done.                                           12.0s
Failed to build iOS app
Error output from Xcode build:
↳
    2022-05-22 22:14:57.580 xcodebuild[3567:2367429] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications
    for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
    2022-05-22 22:14:57.580 xcodebuild[3567:2367429] Requested but did not find extension point with identifier
    Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in
    com.apple.dt.IDEWatchSupportCore
    ** BUILD FAILED **


Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/cm/yrrjl0hd0hb5txbmqb19ft6r0000gn/T/flutter_tools.IAnVYV/flutter_ios_build_temp_dirIGnnzU/temporary_xcresult_bundle

    /Users/nils/Library/Developer/Xcode/DerivedData/Runner-ewwcvjcyaudchgcttdufobgmnmea/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.bu
    ild/Script-29A6B8BB283AD10900E062A0.sh: line 2: /Users/nils/Desktop/Projects/playground/crashlytics_dsym/ios/Pods/FirebaseCrashlytics/upload-symbols
    --build-phase --validate -ai 1:908213459582:ios:bf41d8dc1f56308232d62f: No such file or directory
    /Users/nils/Library/Developer/Xcode/DerivedData/Runner-ewwcvjcyaudchgcttdufobgmnmea/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.bu
    ild/Script-29A6B8BB283AD10900E062A0.sh: line 3: /Users/nils/Desktop/Projects/playground/crashlytics_dsym/ios/Pods/FirebaseCrashlytics/upload-symbols
    --build-phase -ai 1:908213459582:ios:bf41d8dc1f56308232d62f: No such file or directory
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order

    Result bundle written to path:
    	/var/folders/cm/yrrjl0hd0hb5txbmqb19ft6r0000gn/T/flutter_tools.IAnVYV/flutter_ios_build_temp_dirIGnnzU/temporary_xcresult_bundle


Could not build the application for the simulator.
Error launching application on iPhone 11.
```

### Steps to reproduce

1. Run `flutter create issue`
2. Run `cd issue`
3. Run `flutter pub add firebase_core firebase_crashlytics`
4. Run `flutterfire configure` and setup the Firebase
5. Open XCode
6. Follow https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=flutter&authuser=4&hl=en
  a. Create a new script
  b. Copy in the command field 
```
"$PODS_ROOT/FirebaseCrashlytics/upload-symbols --build-phase --validate -ai 1:908213459582:ios:bf41d8dc1f56308232d62f"
"$PODS_ROOT/FirebaseCrashlytics/upload-symbols --build-phase -ai 1:908213459582:ios:bf41d8dc1f56308232d62f"
```

Add the following paths under "Input Files"
```
${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}
$(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)
```

### Expected behavior

The app should build when I use `flutter run`.

### Sample project

https://github.com/nilsreichardt/playground/tree/crashlytics-dsym/crashlytics_dsym

---

## Additional context

I'm using a M1 MacBook.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.2.1 21D62 darwin-arm (Rosetta), locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc5)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[!] Android Studio
    ✗ Unable to find bundled Java version.
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.3)
[✓] VS Code (version 1.67.2)
[✓] Connected device (3 available)
    ! Error: iPhone von Roland is not connected. Xcode will continue when iPhone von Roland is connected. (code -13)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.17.0
Flutter SDK 3.0.0
crashlytics_dsym 1.0.0+1

dependencies:
- cupertino_icons 1.0.4
- firebase_core 1.17.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 2.8.0 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]

dev dependencies:
- flutter_lints 2.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.16.0
- fake_async 1.3.0 [clock collection]
- firebase_core_platform_interface 4.4.0 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.6.4 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.2.6 [collection firebase_core flutter meta plugin_platform_interface]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- js 0.6.4
- lints 2.0.0
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.4
- meta 1.7.0
- path 1.8.1
- plugin_platform_interface 2.1.2 [meta]
- sky_engine 0.0.99
- source_span 1.8.2 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.9 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- vector_math 2.1.2
```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the report @nilsreichardt 
Is that the complete xcode build log you get ? Is there a way for you to run from AS or VSCode and run to see if it shows any other logs such as `UserInfo` that gives `NSLocalizedDescription` that would probably help more to debug this ?

**Comment by nilsreichardt** [comment]
No, running from XCode, VS Code or from the terminal show all the same issue.

**Comment by darshankawar** [comment]
Thanks for the update. Using steps to replicate, I am seeing same error as reported.

Keeping it open and labeling for further insights from the team.

/cc @russellwheatley

**Comment by nilsreichardt** [comment]
But is this always the case? From my understanding, adds the `flutterfire configure` a run script with the name `[firebase_crashlytics] Crashlytics Upload Symbols` to `FLUTTER_PROJECT_NAME/ios/Runner.xcworkspace`. This calls the script that you linked. But I have not used `flutterfire configure` because of the lack of flavors (see https://github.com/invertase/flutterfire_cli/issues/14). So I followed the steps after "If this run script does not exist, you can add it manually:".

<img width="909" alt="image" src="https://user-images.githubusercontent.com/24459435/174126740-cc64aaf6-e1e9-4940-8d5c-682f4b979022.png">

https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=flutter&authuser=4&hl=en

**Comment by russellwheatley** [comment]
@nilsreichardt the script is called in the Crashlytics podspec file [here](https://github.com/firebase/flutterfire/blob/master/packages/firebase_crashlytics/firebase_crashlytics/ios/firebase_crashlytics.podspec#L10). You shouldn't need the manual steps nor flutterfire cli for the scripts.

**Comment by fpbouchard** [comment]
I just had this issue, the problem is that when you copy the script lines from the documentation, they quote the script lines. You have to remove the double-quotes:

```
$PODS_ROOT/FirebaseCrashlytics/upload-symbols --build-phase --validate -ai 1:908213459582:ios:bf41d8dc1f56308232d62f
$PODS_ROOT/FirebaseCrashlytics/upload-symbols --build-phase -ai 1:908213459582:ios:bf41d8dc1f56308232d62f
```

**Comment by russellwheatley** [comment]
@fpbouchard yes, this is correct. Docs need to be updated [here](https://github.com/firebase/flutterfire/blob/aabc4d483695ac2938dac437057270bf35985028/docs/crashlytics/_deobfuscated.md#L63). Although to reiterate, you don't need to add the scripts manually anymore with the latest version of Crashlytics.

**Comment by fpbouchard** [comment]
@russellwheatley I'm using flavors on a working production app already setup with different plist files. While you are right that for new projects that do not use flavors, you shouldn't have to manually add the scripts, the CLI isn't there _yet_ for apps that want to use flavors, hence the manual setup (I'm calling upload-symbols with the `-gsp` parameter)

**Comment by russellwheatley** [comment]
@fpbouchard, thanks for the catch. I've updated documentation
