### ISSUE TITLE
[📚] Cant Find Usage Documentation Firebase Analytics (Missing Documentation Page)

### ISSUE THREAD

**Issue by dimas-ibnu** [firebase/flutterfire#8753]
The Documentation usage of flutter analytics cant find specific Page [Firebase Usage Url](https://firebase.flutter.dev/docs/analytics/usage)

please provide the specific documentation page on pub.dev package (https://pub.dev/packages/firebase_analytics),  thanks

**Comment by Rohithgilla12** [comment]
I think this is the correct link.
https://firebase.flutter.dev/docs/analytics/overview/

**Comment by dimas-ibnu** [comment]
> I think this is the correct link. https://firebase.flutter.dev/docs/analytics/overview/

so the analytics  usage was the same with the analytics overview ?

**Comment by dimas-ibnu** [comment]
> The updated link after merging flutterfire documents with firebase is https://firebase.google.com/docs/analytics/get-started?platform=flutter
> 
> so check if it helps to answer your question.
> 
> > https://firebase.flutter.dev/docs/analytics/overview/
> 
> accessing this link shows it is archived and recommends to access the one I linked above.

thanks for the answer
