### ISSUE TITLE
AppCheck token is not been attached in firestore request

### ISSUE THREAD

**Issue by jaiswalshubham84** [firebase/flutterfire#8762]
### Discussed in https://github.com/firebase/flutterfire/discussions/8761

<div type='discussions-op-text'>

<sup>Originally posted by **jaiswalshubham84** May 24, 2022</sup>
Hi,
I am using Firestore in a flutter web.
In order to add more security to Firestore, I am using the Firebase app check.
The token from app check is correctly been generated but it is not being attached to firestore request call.
Do I need to do anything extra to attach my firebase appCheck token to firestore request call?
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  setPathUrlStrategy();
  var fbApp = await Firebase.initializeApp(
      options: FirebaseOptions(
          apiKey: "AIzaSxxxxxxxxxxx",
          authDomain: "xqdxwedewdedewdw",
          projectId: "dwedewdwedewdwed",
          storageBucket: "dewdewdwedew",
          messagingSenderId: "dewdwedwedweddew",
          appId: "dewdewdewdwdwe",
          measurementId: "dewdwedewdwed"));
 

  FirebaseAppCheck.instanceFor(app: fbApp).activate(
      webRecaptchaSiteKey: '6LedKtxxxxxxxEmbTPcZqNhxxxxxxxxxxx');
  FirebaseAppCheck.instanceFor(app: fbApp).setTokenAutoRefreshEnabled(true);
  var token = await FirebaseAppCheck.instanceFor(app: fbApp).getToken();
  print("till here2 => $token");

 

  runApp(MultiProvider(
    providers: [
      navIndexProvider,
      groupDataProvider,
      eventDataProvider,
      galleryProvider,
      newsProvider,
      ChangeNotifierProvider(create: (ref) => MembershipFormController()),
      ChangeNotifierProvider(create: (ref) => StoreProvider()),
      ChangeNotifierProvider(create: (ref) => DonationProvider()),
      ChangeNotifierProvider(create: (ref) => MembershipCheckoutController()),
    ],
    child: const MyApp(),
  ));
}


```
Please let me know if i am doing anything wrong.

<img width="1051" alt="Screenshot 2022-05-24 at 2 13 31 AM" src="https://user-images.githubusercontent.com/32263293/169902873-44627a76-e568-4353-8eff-36f59e033445.png">
</div>

**Comment by darshankawar** [comment]
Take a look at below links and also app_check plugin example and see if they help:

https://firebase.google.com/docs/app-check
https://firebase.google.com/docs/app-check/flutter/default-providers
https://firebase.google.com/docs/app-check/flutter/debug-provider
https://firebase.google.com/docs/app-check/flutter/custom-resource

https://github.com/firebase/flutterfire/tree/master/packages/firebase_app_check/firebase_app_check/example

**Comment by jaiswalshubham84** [comment]
Hi @darshankawar ,
As i mentioned earlier the app check token is generating fine, the only thing is its not being attached to cloud firestore calls.
So all the request to the firestore is rejected with the reason missing token, when I enforce the service. See the graph picture I posted above

**Comment by darshankawar** [comment]
Thanks for the update. Can you provide the complete error it throws related to `missing token` ?

**Comment by jaiswalshubham84** [comment]
Hi @darshankawar 
Please refer this.
Here is the code 

```
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_app_check/firebase_app_check.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  var fbApp = await Firebase.initializeApp(
      options: FirebaseOptions(
          apiKey: "AIzaxxxxxxxxxxxxxxxxxxxxxxx",
          authDomain: "chxxxxxxxxxxxxxxxxx",
          projectId: "chxxxxxxxxxxxxxxxxx",
          storageBucket: "chxxxxxxxxxxxxxxxxx",
          messagingSenderId: "xxxxxxxxxxxxxxxxx",
          appId: "1:82xxxxxxxxxxxxxxxxx:web:cb876e29exxxxxxxxxxxxxxxxx",
          measurementId: "G-ZWxxxxxxxxxxxxxxxxx"));
  FirebaseAppCheck.instanceFor(app: fbApp).activate(
      webRecaptchaSiteKey: '6LedKt0fAAAAAEmbTPcZqNhO51YZoKnLJlpVY3Hp');
  // FirebaseAppCheck.instanceFor(app: fbApp).setTokenAutoRefreshEnabled(true);
  var token = await FirebaseAppCheck.instanceFor(app: fbApp).getToken();
  print("token => $token");

  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    // TODO: implement initState
    init();
    super.initState();
  }

  init() async {
    try {
      QuerySnapshot snaps =
          await FirebaseFirestore.instance.collection("Random").get();
      print("snaps => $snaps");
    } catch (e) {
      print("error while fetching data => $e");
    }
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(),
    );
  }
}
```
Here is the output for the same

<img width="1440" alt="Screenshot 2022-05-28 at 11 10 26 AM" src="https://user-images.githubusercontent.com/32263293/170811837-18c2d06a-f114-40fd-a88e-1ea88435adfd.png">
<img width="1113" alt="Screenshot 2022-05-28 at 11 11 41 AM" src="https://user-images.githubusercontent.com/32263293/170811876-c0c91956-c84f-4eb2-9de3-031fff35d7c7.png">

**Comment by brouwer** [comment]
I have the same issue. The error `[cloud_firestore/permission-denied] Missing or insufficient permissions` is definitely because of having enabled "Enforced" app checking. My Firestore requests work just fine without enforcing, but they show up in the app check dashboard as "outdated client request". In my case this only happens on the web platform. Android and iOS work fine, and show up as verified requests...

**Comment by ark7** [comment]
we have the same issue, we are able to get Recaptcha V3 Token but unable to get firestore data in enforcement mode. the firestore data retrieve successfully without enforcement

**Comment by binlebin** [comment]
I have the same problem when enforcing appcheck for my web app

**Comment by Faizan770gp** [comment]
Any Update on this issue ?

**Comment by gOzaru** [comment]
@brouwer 
I think in your case, you just need to update the latest version of AppCheck for web using Javascript. 
Try compile again.

**Comment by russellwheatley** [comment]
I have tested this on the latest `firebase_app_check` version and it works as expected. I think there was an issue before we switched to web v9 JS SDK.

**Comment by mono0926** [comment]
@russellwheatley @darshankawar 

> I have tested this on the latest firebase_app_check version and it works as expected. I think there was an issue before we switched to web v9 JS SDK.

As far as I can verify on my end, the error still occurs 🤔 

```
logger.ts:115 [2022-07-29T07:34:44.689Z]  https://www.gstatic.com/firebasejs/9.9.0/firebase-app.js-check: FirebaseError: AppCheck: Fetch server returned an HTTP error status. HTTP status: 400. (appCheck/fetch-status-error).
    at exchangeToken (client.ts:75:25)
    at async ReCaptchaV3Provider.getToken (providers.ts:78:16)
    at async getToken$2 (internal-api.ts:140:13)
    at async Promise.all (/index 1)
```
