### ISSUE TITLE
🐛 [firebase_messaging] notification request popup is not displayed on iOS mobile browser

### ISSUE THREAD

**Issue by deepak786** [firebase/flutterfire#8764]
When the Flutter web app is opened in an iOS mobile browser, there is no notification permission popup.

```
NotificationSettings settings = await FirebaseMessaging.instance.requestPermission(
    alert: true,
    announcement: false,
    badge: true,
    carPlay: false,
    criticalAlert: false,
    provisional: false,
    sound: true,
  );
```

### Expected behavior

It should show the permission popup.

**Comment by darshankawar** [comment]
@deepak786 
Can you try with `provisional: true` and see if it helps ?

**Comment by deepak786** [comment]
@darshankawar I used `provisional: true` and updated the web app. 
It is still not working.

**Comment by deepak786** [comment]
I checked the code of web implementation https://github.com/firebase/flutterfire/blob/a11bd6021a3e915bf36f0db295b45ee8a3f16517/packages/firebase_messaging/firebase_messaging_web/lib/firebase_messaging_web.dart#L145

It is returning the exception if the operation is not supported. So I added a try-catch block around the `requestPermission` and it seems to be working.

It seems that iOS web does not support push notifications yet https://onesignal.com/blog/ios-web-push-notification-support-is-coming-soon/

**Comment by darshankawar** [comment]
Thanks for this update. It seems firebase_messaging can't do anything since the implementation probably needs to be done upstream (firebase-ios-sdk). I suggest you to open this issue in dedicated repo or in firebase support for further resolution.

Closing from here for now.

**Comment by deepak786** [comment]
Maybe a check can be added just like it has been done for the deleteToken and getToken APIs.

https://github.com/firebase/flutterfire/blob/a11bd6021a3e915bf36f0db295b45ee8a3f16517/packages/firebase_messaging/firebase_messaging_web/lib/firebase_messaging_web.dart#L91

https://github.com/firebase/flutterfire/blob/a11bd6021a3e915bf36f0db295b45ee8a3f16517/packages/firebase_messaging/firebase_messaging_web/lib/firebase_messaging_web.dart#L108
