### ISSUE TITLE
🐛 [firebase_crashlytics] Android Build failing : cannot find symbol  FirebaseCrashlytics.getInstance().core.logFatalException(throwable);

### ISSUE THREAD

**Issue by stevenosse** [firebase/flutterfire#8768]
## Bug report

Project build fails after upgrading to Firebase Crashlytics 2.8.0

```
<flutter_path>/.pub-cache/hosted/pub.dartlang.org/firebase_crashlytics-2.8.0/android/src/main/java/io/flutter/plugins/firebase/crashlytics/FlutterFirebaseCrashlyticsPlugin.java:81: warning: [deprecation] Handler() in Handler has been deprecated
    new Handler()
    ^
<flutter_path>/.pub-cache/hosted/pub.dartlang.org/firebase_crashlytics-2.8.0/android/src/main/java/com/google/firebase/crashlytics/FlutterFirebaseCrashlyticsInternal.java:14: error: cannot find symbol
    FirebaseCrashlytics.getInstance().core.logFatalException(throwable);
                                          ^
  symbol:   method logFatalException(Throwable)
  location: variable core of type CrashlyticsCore
1 error
1 warning

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':firebase_crashlytics:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
``` 
### Steps to reproduce

1. Update firebase_crashlytics version to 2.8.0 in `pubspec.yaml`
2. Install dependencies and compile/run project
4. See error or incorrect behavior

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
![Capture d’écran 2022-05-24 à 15 06 12](https://user-images.githubusercontent.com/33069233/170041955-e8b1ee03-1dca-49fc-9747-f53b4dc6922a.png)
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
firebase_core 1.10.2
firebase_analytics 8.3.4
firebase_messaging 11.2.0
firebase_crashlytics 2.8.0
firebase_dynamic_links 3.0.2
```

</details>

---

**Comment by darshankawar** [comment]
@stevenosse 
There's similar open issue describing your case, https://github.com/firebase/flutterfire/issues/8697.
Please check underlying comments / solutions mentioned in it and see if it helps to resolve your issue. If not, you may comment in that issue for better tracking.

Closing this as a duplicate.
