### ISSUE TITLE
🐛 [AUTH] 'emailVerified' state change not triggering any streams

### ISSUE THREAD

**Issue by BrutalCoding** [firebase/flutterfire#8777]
## Bug report

**Describe the bug**
There is an emailVerified property of the currently logged in user that can be accessed by using:
`FirebaseAuth.instance.currentUser.emailVerified`

I would like to listen to changes to this `emailVerified` property, so I've tried to listen the following streams:
- `FirebaseAuth.instance.userChanges()`. Which mentions: "This is a superset of both [authStateChanges] and [idTokenChanges]."
- `FirebaseAuth.instance.authStateChanges()`
- `FirebaseAuth.instance.idTokenChanges()`

These streams have been used in conjunction with the StreamBuilder widget.

When the user goes to verify their email by using the verification link that was sent to their inbox, none of these streams get notified of this state change (of `emailVerified`). 

The workaround that I have been applying is setting up a periodic timer that calls `FirebaseAuth.instance.currentUser.reload();` every 10 seconds. I went for 10 seconds since that was sufficient enough in my use case. By calling `FirebaseAuth.instance.currentUser.reload()` periodically, the `FirebaseAuth.instance.userChanges()` gets triggered soon after (within 10 seconds) the user has verified their email.

### Steps to reproduce

1. Sign into your app with FirebaseAuth, preferable with an email account so that we can verify the email later.
2. Set up a stream listener to `FirebaseAuth.instance.userChanges()`
3. Set up a breakpoint or print within the listener to be aware of when the stream gets triggered
4. Change the `emailVerified` status in Firebase Auth by either using forgot password or email verification link
5. Observe the stream, it should get triggered with new data but it does not.

### Expected behavior

The expected behavior would be that `FirebaseAuth.instance.userChanges()` gets triggered and that the returned value of the stream contains the latest state of the user. The issue here is that the stream does not get triggered at all.

### Sample project

No sample project prepared since this requires to be setup with an active Firebase project, I have not done so.

---

## Additional context

This problem is not unique to Firebase Auth for Flutter, since this issue persists with Firebase Auth for JavaScript as well. A small difference with JavaScript is that their Firebase Auth SDK does not have this a similar (superset) stream:
`FirebaseAuth.instance.userChanges()`

But it does have the following streams taken from the Firebase Auth for JavaScript docs:
- [onIdTokenChanged] https://firebase.google.com/docs/reference/js/v8/firebase.auth.Auth#onidtokenchanged
- [onAuthStateChanged] https://firebase.google.com/docs/reference/js/v8/firebase.auth.Auth#onauthstatechanged

Both of these streams do not get triggered when the `emailVerified` of the currently logged in user changes. 

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by BrutalCoding** [comment]
I would like to mention that this bug (or lacking feature?) is causing another bug in the FirebaseUI plugin, namely the Email Verification screen. Here's an issue of someone facing this bug https://github.com/firebase/flutterfire/issues/8683

**Comment by darshankawar** [comment]
Thanks for the detailed report @BrutalCoding . I was going through similar issues reported earlier and came across this which seem to be closely related : https://github.com/firebase/flutterfire/issues/3461 for which a fix was made in the documentation https://github.com/firebase/flutterfire/issues/3461. Can you please go through it and see if it helps from above issue's point of view ?

Moreover, this also looks closely related : https://github.com/firebase/flutterfire/pull/6301,  https://github.com/firebase/flutterfire/issues/3994 so please check if using `user.reload()` helps to trigger stream ?

**Comment by BrutalCoding** [comment]
> Thanks for the detailed report @BrutalCoding . I was going through similar issues reported earlier and came across this which seem to be closely related : #3461 for which a fix was made in the documentation #3461. Can you please go through it and see if it helps from above issue's point of view ?
> 
> Moreover, this also looks closely related : #6301, #3994 so please check if using `user.reload()` helps to trigger stream ?

hey @darshankawar, thanks for the quick reply. The method `FirebaseAuth.instance.currentUser.reload()` does work, thats the workaround that I have described in this issue already. I was hoping to see the stream getting triggered without calling that method periodically.  

I've gone through your referenced issues and I see that more people expected to have this stream triggered when `emailVerified` changes but it seems that the streams are not designed to do so.

The correct and only way to trigger the stream is by calling `FirebaseAuth.instance.currentUser.reload()` periodically, by doing so, the stream `FirebaseAuth.instance.userChanges()` will get triggered if `emailVerified` has changed.

I will close this issue now
