### ISSUE TITLE
🐛 [firebase_messaging] cannot find symbol         io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService.setPluginRegistrant(this);

### ISSUE THREAD

**Issue by leegiseong20030603** [firebase/flutterfire#8780]
I was able to find out that the FlutterFirebaseMessagingBackgroundService class exists through the autocomplete function in Android Studio... But it is generated with red code and the following error occurs when running....

Package version: firebase_messaging: ^11.2.7

Android related gradle configuration files

```
// android
apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'
dependencies{
    implementation 'com.google.firebase:firebase-messaging'
}

// android:app
buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.3'
        classpath 'com.google.gms:google-services:4.3.10'
    }
}
```

```
==================================================== ======Error

 cannot find symbol
        io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService.setPluginRegistrant(this);
                                                                                       ^
  symbol: method setPluginRegistrant(Application)
  location: class FlutterFirebaseMessagingBackgroundService
```

![스크린샷 2022-05-26 오후 10 51 44](https://user-images.githubusercontent.com/53187258/170502440-de9189d7-2bd9-4160-9506-b4aab398d0ce.png)

**Comment by darshankawar** [comment]
@leegiseong20030603 
Can you provide `flutter doctor -v` ? From your screenshot, I see the `PluginRegistrantCallback` class seems to deprecated. If so, what does it show to replicate with ? Can you try with new one and see if it helps ?

Also check this similar issue and see if it helps. https://github.com/firebase/flutterfire/issues/2077

**Comment by leegiseong20030603** [comment]
@darshankawar 
Sorry for the late reply....
Here is my current version and status.

That method didn't solve my issue

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6 20G165 darwin-x64, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.66.2)
[✓] Connected device (3 available)

• No issues found!

**Comment by darshankawar** [comment]
@leegiseong20030603 
Are you importing all the required packages correctly that requires `cannot find symbol
        io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService`

**Comment by leegiseong20030603** [comment]
@darshankawar 
io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService
It shows in the preview function of android studio that there is a Firebase Cloud Messaging package, but an error occurs saying that there is no function of that class.

**Comment by darshankawar** [comment]
@leegiseong20030603 
Can you provide complete code sample and when are you trying to use this ?
