### ISSUE TITLE
🐛 [flutterfire_ui] Flutter 3.0 migration warning in scheduler binding after version 0.4.1+2

### ISSUE THREAD

**Issue by hashem78** [firebase/flutterfire#8784]
This is an annoying warning that keeps coming up in the logs after the last change to flutterfire_ui

/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutterfire_ui-0.4.1+2/lib/src/auth/screens/email_verification_screen.dart:97:22: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
package:flutter/…/scheduler/binding.dart:1
    SchedulerBinding.instance!.addPostFrameCallback(_sendEmailVerification);

**Comment by darshankawar** [comment]
For warnings, check out [this](https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.0.0#if-you-see-warnings-about-bindings) documentation and see if it helps.

**Comment by hashem78** [comment]
> For warnings, check out [this](https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.0.0#if-you-see-warnings-about-bindings) documentation and see if it helps.

I am well aware of the article you mentioned, as I noted in the OP, this warning was not happening on a previous version of package::flutterfire_ui and that was with flutter 3.0.0, after I did a 'flutter pub upgrade' it seems package:flutterfire_ui got updated and the update has a regression that displays this warning.

**Comment by lesnitsky** [comment]
Fixed in #8949
