### ISSUE TITLE
🐛 [Firebase_app_check] firebase app check is not working in android OS 10  .its working fine in android OS 9

### ISSUE THREAD

**Issue by Nabeelyousaf** [firebase/flutterfire#8786]
## Bug report

**Describe the bug**
I m trying to implement the Firebase app check-in flutter but its package is not helpfull for me i tried to implemet in native in app I follow the firebase app check documentation. its working fine in android OS 9. but I face issues in Android OS 10  the issue is related to Firebase 

`Unhandled Exception: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation`
### Steps to reproduce

I follow the Firebase app check documentation 

```
### Sample project
override fun onCreate(savedInstanceState: Bundle?) {
        FirebaseApp.initializeApp(/*context=*/this)
        val firebaseAppCheck = FirebaseAppCheck.getInstance()
//        DebugAppCheckProviderFactory.getInstance()
        firebaseAppCheck.installAppCheckProviderFactory(
                SafetyNetAppCheckProviderFactory.getInstance()
        )
        super.onCreate(savedInstanceState)
    }

```
Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

### Flutter doctor

```
Run `flutter doctor` and paste the output below:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.1, on macOS 11.6 20G165 darwin-x64, locale
  en-PK)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.64.2)
[✓] VS Code (version 1.64.2)
[✓] Connected device (2 available)
  ! Error: iPhone is not connected. Xcode will continue when iPhone is
   connected. (code -13)
[✓] HTTP Host Availability
```

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies
firebase_app_check: ^0.0.6+12

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by darshankawar** [comment]
> Unhandled Exception: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation

You are getting `permission_denied` which indicates, you need to set Firestore rules properly on your Firebase console. Please double-check the security rules are properly configured.

**Comment by Nabeelyousaf** [comment]
@darshankawar I am also checking  my firebase rules its working fine on android 9 but I'm getting the issue on android 10 only 
if any issue with the firebase rule then why we do not get an exception on android 9 .why we getting an exception on android 10

**Comment by Nabeelyousaf** [comment]
this is the app check token that I get  `token` `eyJlcnJvciI6IlVOS05PV05fRVJST1IifQ==`

**Comment by russellwheatley** [comment]
This exception is coming from the firebase-android-sdk. I suggest you create a reproducible sample and create an issue on [that repo](https://github.com/firebase/firebase-android-sdk), particularly as you're using native code.
