### ISSUE TITLE
🐛 [firebase_messaging] iOS - Existing UNUserNotificationCenterDelegate causes FirebaseMessaging.onMessage to no longer to fire

### ISSUE THREAD

**Issue by jkasten2** [firebase/flutterfire#8792]
### One Line Summary
If a `UNUserNotificationCenterDelegate` is assigned to `UNUserNotificationCenter.currentNotificationCenter.delegate` by the app developer or another plugin / SDK then `FirebaseMessaging.onMessage` doesn't fire in the app's dart code.

### Details
The root of the issue that `FLTFirebaseMessagingPlugin.application_onDidFinishLaunchingNotification` has a `shouldReplaceDelegate` flag that can omit assigning `notificationCenter.delegate` in some cases. This happens if `notificationCenter.delegate != nil` however it also checks if `AppDelegate``conformsToProtocol` `UNUserNotificationCenterDelegate` is `true`. However the latter is always `true` in a Flutter app, it really should be checking for `FlutterAppLifeCycleProvider` on `notificationCenter.delegate` instead.

### Steps to reproduce
1. On a new Flutter project follow the [Add Firebase to your Flutter app](https://firebase.google.com/docs/flutter/setup?platform=ios) guide.
2. Add [`firebase_messaging`](https://firebase.google.com/docs/cloud-messaging/flutter/client) to your app.
3. Add the [`FirebaseMessaging.onMessage.listen`](https://firebase.google.com/docs/cloud-messaging/flutter/receive#foreground_messages) to your app.
4. Send a notification through the Firebase Console, ensure your `FirebaseMessaging.onMessage.listen` fires to ensure you have everything setup.
5. Open the `AppDelegate.m`.
6. Create a new class the implements the `UNUserNotificationCenterDelegate` protocol.
7. Under `application:(UIApplication *)application:didFinishLaunchingWithOptions:(NSDictionary *)launchOptions` add the following to assign it.
```objective-c
myNotifDelegate = [MyUNUserNotificationCenterDelegate new];
UNUserNotificationCenter.currentNotificationCenter.delegate = myNotifDelegate;
```
8. 🐛 Observer `FirebaseMessaging.onMessage.listen` no longer fires.

<details><summary><b>AppDelegate.m</b> <i>(Click To Expand)</i></summary>

```objective-c
@interface MyUNUserNotificationCenterDelegate : NSObject<UNUserNotificationCenterDelegate>
@end
@implementation MyUNUserNotificationCenterDelegate
- (void)userNotificationCenter:(UNUserNotificationCenter *)center
    willPresentNotification:(UNNotification *)notification
  withCompletionHandler:(void (^)(UNNotificationPresentationOptions options))completionHandler
{
    NSLog(@"MyUNUserNotificationCenterDelegate:Handle push from foreground" );
    completionHandler(UNNotificationPresentationOptionAlert
                    | UNNotificationPresentationOptionSound
                    | UNNotificationPresentationOptionBadge);
}

- (void)userNotificationCenter:(UNUserNotificationCenter *)center
didReceiveNotificationResponse:(UNNotificationResponse *)response
  withCompletionHandler:(void (^)())completionHandler
{
    NSLog( @"MyUNUserNotificationCenterDelegate:Handle push from background or closed" );
    NSLog(@"%@", response.notification.request.content.userInfo);
    completionHandler();
}
@end

static MyUNUserNotificationCenterDelegate* myNotifDelegate;

@implementation AppDelegate
- (BOOL)application:(UIApplication *)application
    didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    [GeneratedPluginRegistrant registerWithRegistry:self];

    myNotifDelegate = [MyUNUserNotificationCenterDelegate new];
    UNUserNotificationCenter.currentNotificationCenter.delegate = myNotifDelegate;

    return [super application:application didFinishLaunchingWithOptions:launchOptions];
}
@end
```

</details>

### Expected behavior
Expect `FirebaseMessaging.onMessage.listen` to continue firing, as well as `MyUNUserNotificationCenterDelegate`.

---

## Additional context
Other iOS Notification SDKs to be able to set their own `UNUserNotificationCenterDelegate`. This plugin should not break when other SDKs set their delegate, nor should this SDK break others.

### PR bug introduced in
@Salakar created PR #4043 that [added](https://github.com/firebase/flutterfire/pull/4043/files#diff-8ea85f4350cd917e7a326e91c63d70d0ee1cc9d3d8726a89d58451e6944d9748R234-R239) the following code:
```obejctive-c
if ([GULApplication sharedApplication].delegate != nil &&
     [[GULApplication sharedApplication].delegate
              conformsToProtocol:@protocol(UNUserNotificationCenterDelegate)]) {
    // Note this one only executes if Firebase swizzling is **enabled**.
    shouldReplaceDelegate = NO;
}
```

While this did address an infinite swizzling bug when app developers add `UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate` to their `AppDelegate.swift` it also created the issued outlined here. To address this the `conformsToProtocol` check should be done on `notificationCenter.delegate` and instead of `[GULApplication sharedApplication].delegate` and should check for protocol `FlutterAppLifeCycleProvider` instead of `UNUserNotificationCenterDelegate`. This looks like a mistake in the PR #4043 code, as the title for the PR is "don't replace UNUserNotificationCenter delegate when **protocol conforms to FlutterApplicationLifeCycleDelegate**".

### Related issues
* https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/348

---

### Flutter doctor
<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel unknown, 2.10.5, on macOS 12.3.1 21E258 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2022.1)
[✓] VS Code (version 1.66.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.16.2
Flutter SDK 2.10.5
my_example 1.0.0+1

dependencies:
- cupertino_icons 1.0.4
- firebase_core 1.17.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 11.4.1 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta typed_data vector_math sky_engine]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.15.0
- fake_async 1.2.0 [clock collection]
- firebase_core_platform_interface 4.4.0 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.6.4 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 3.5.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.4.1 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta typed_data vector_math]
- js 0.6.3
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.3
- meta 1.7.0
- path 1.8.0
- plugin_platform_interface 2.1.2 [meta]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.8 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.1
```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the detailed report and analysis. Using steps to replicate, I was able to observe that `FirebaseMessaging.onMessage.listen` isn't triggered.

Maybe this issue is same / related: https://github.com/firebase/flutterfire/issues/8624

/cc @Salakar

**Comment by jkasten2** [comment]
@darshankawar @Salakar I opened a PR to address this bug:
https://github.com/firebase/flutterfire/pull/8822

**Comment by jkasten2** [comment]
PR https://github.com/firebase/flutterfire/pull/8822 has been merged addressing this issue so closing this issue.
