### ISSUE TITLE
[📚] Add link to FlutterFire documentation for FCM

### ISSUE THREAD

**Issue by wujek-srujek** [firebase/flutterfire#8795]
I am experimenting with FCM for the very first time and do so on Flutter. After reading through all of the official docs for Flutter (https://firebase.google.com/docs/cloud-messaging/flutter/client) it seems that a lot is still missing. In my case, it were the `getInitialMessage` and `onMessageOpenedApp` functions because I need to do something when the app is opened via a notification. All of it is actually described here https://firebase.flutter.dev/docs/messaging/notifications#handling-interaction but it took me some time to actually find this resource and look there. Could the https://firebase.google.com/docs/cloud-messaging/flutter documentation somehow explicitly link to FlutterFire?
On the other hand, many of the overview pages in FlutterFire documentation for various products state that they are archived and possibly out of date, so I don't really know what the definitive source of truth is and it makes the experience of working with the plugins more confusing than it should be.

**Comment by nilsreichardt** [comment]
@wujek-srujek Thanks your feedback! Actually, the firebase.google.com are the new docs. It seems so that we should add the missing documentation from firebase.flutter.dev to firebase.google.com.
