### ISSUE TITLE
🐛 [firebase_crashlytics] recordError crash on iOS in version 2.7.0 and up

### ISSUE THREAD

**Issue by vigdora** [firebase/flutterfire#8796]
## Bug report

After upgrading from 2.5.3 to 2.7.2 I noticed the app would crash anytime I call recordError.

it seems like a similar issue to [similar issue](https://github.com/firebase/flutterfire/issues/8554)
but the author of #8554 have closed his issue, and there are many others that it is still reproducing for them! 
so I have opened a new one

Reverting back to 2.5.3 fixes the issue.

Steps to reproduce
Upgrade to version 2.7.2
Call it anywhere:
FirebaseCrashlytics.instance.recordError('some error', null);

those are the crash logs:

> Fatal Exception: NSInvalidArgumentException
> 0 CoreFoundation 0x112b94 __exceptionPreprocess
> 1 libobjc.A.dylib 0x1fbe7 objc_exception_throw
> 2 CoreFoundation 0x121811 +[NSObject(NSObject) instanceMethodSignatureForSelector:]
> 3 CoreFoundation 0x1170ac forwarding
> 4 CoreFoundation 0x1191d8 _CF_forwarding_prep_0
> 5 Runner 0x12e80d -[FLTFirebaseCrashlyticsPlugin recordError:withMethodCallResult:] + 175 (FLTFirebaseCrashlyticsPlugin.m:175)
> 6 Runner 0x12da5d -[FLTFirebaseCrashlyticsPlugin handleMethodCall:result:] + 101 (FLTFirebaseCrashlyticsPlugin.m:101)
> 7 Flutter 0x5a9571 (Missing UUID beaf434b976f3edaba203d480c910d6c)
> 8 Flutter 0x386df (Missing UUID beaf434b976f3edaba203d480c910d6c)
> 9 Flutter 0x3ddf9 (Missing UUID beaf434b976f3edaba203d480c910d6c)
> 10 Flutter 0x47e09b (Missing UUID beaf434b976f3edaba203d480c910d6c)
> 11 Flutter 0x37def0 (Missing UUID beaf434b976f3edaba203d480c910d6c)
> 12 Flutter 0x384324 (Missing UUID beaf434b976f3edaba203d480c910d6c)
> 13 CoreFoundation 0x816b6 CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION
> 14 CoreFoundation 0x811b2 __CFRunLoopDoTimer
> 15 CoreFoundation 0x80771 __CFRunLoopDoTimers
> 16 CoreFoundation 0x7adb0 __CFRunLoopRun
> 17 CoreFoundation 0x7a0f3 CFRunLoopRunSpecific
> 18 GraphicsServices 0x3cd3 GSEventRunModal
> 19 UIKitCore 0xccdf42 -[UIApplication _run]
> 20 UIKitCore 0xcd2b5e UIApplicationMain
> 21 Runner 0xa2ff main + 5 (AppDelegate.swift:5)
> 22 ??? 0x1093b5ee9 (Missing)
> 23 ??? 0x1 (Missing)
> 

followed by this:

> 
> Crashed: com.google.firebase.crashlytics.ios.exception
> 0 FirebaseCrashlytics 0x2e433 FIRCLSProcessGetThreadState + 259
> 1 FirebaseCrashlytics 0x2d901 FIRCLSProcessRecordThread + 385
> 2 FirebaseCrashlytics 0x2d6ba FIRCLSProcessRecordAllThreads + 138
> 3 FirebaseCrashlytics 0x1ecd9 FIRCLSHandler + 57
> 4 FirebaseCrashlytics 0x15461 __FIRCLSExceptionRecord_block_invoke + 145
> 5 libdispatch.dylib 0x383a _dispatch_client_callout + 8
> 6 libdispatch.dylib 0x1193a _dispatch_lane_barrier_sync_invoke_and_complete + 94
> 7 FirebaseCrashlytics 0x1440b FIRCLSExceptionRecord + 363
> 8 FirebaseCrashlytics 0x149eb FIRCLSExceptionRecordNSException + 1131
> 9 FirebaseCrashlytics 0x156e0 FIRCLSCatchAndRecordActiveException(std::type_info*) + 192
> 10 FirebaseCrashlytics 0x13f04 FIRCLSTerminateHandler() + 244
> 11 libc++abi.dylib 0xf9e7 std::__terminate(void (*)()) + 8
> 12 libc++abi.dylib 0x12254 __cxa_rethrow + 99
> 13 libobjc.A.dylib 0x1fd46 objc_exception_rethrow + 37
> 14 CoreFoundation 0x7a219 CFRunLoopRunSpecific + 861
> 15 GraphicsServices 0x3cd3 GSEventRunModal + 139
> 16 UIKitCore 0xccdf42 -[UIApplication _run] + 928
> 17 UIKitCore 0xcd2b5e UIApplicationMain + 101
> 18 Runner 0xa2ff main + 5 (AppDelegate.swift:5)
> 19 ??? 0x1093b5ee9 (Missing)

### Flutter doctor

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.3, on macOS 11.6 20G165 darwin-x64, locale en-IL)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.67.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
Dart SDK 2.16.1
Flutter SDK 2.10.3
flutter_bluevine 9.0.0

dependencies:
- cached_network_image 3.2.0 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- clock 1.1.0
- cookie_jar 3.0.1
- crypto 3.0.1 [collection typed_data]
- cupertino_icons 1.0.4
- device_info_plus 3.2.2 [flutter device_info_plus_platform_interface device_info_plus_macos device_info_plus_linux device_info_plus_web device_info_plus_windows]
- dio 4.0.4 [http_parser path]
- dio_cookie_manager 2.0.0 [cookie_jar dio]
- firebase_analytics 9.1.2 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 1.13.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 2.7.2 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- flutter 0.0.0 [characters collection material_color_utilities meta typed_data vector_math sky_engine]
- flutter_jailbreak_detection 1.8.0 [flutter]
- flutter_secure_storage 5.0.2 [meta flutter flutter_secure_storage_linux flutter_secure_storage_macos flutter_secure_storage_platform_interface flutter_secure_storage_web flutter_secure_storage_windows]
- flutter_segment 3.7.0 [flutter flutter_web_plugins meta]
- flutter_svg 0.22.0 [flutter meta path_drawing vector_math xml]
- get 4.6.1 [flutter]
- google_place 0.4.7 [http]
- html_character_entities 1.0.0+1
- http 0.13.4 [async http_parser meta path]
- http_certificate_pinning 2.0.4 [dio flutter http]
- internet_connection_checker 0.0.1+3
- intl 0.17.0 [clock path]
- json_annotation 4.4.0 [meta]
- launch_review 3.0.1 [flutter]
- local_auth 2.0.0 [flutter intl local_auth_android local_auth_ios local_auth_platform_interface]
- mask_text_input_formatter 2.1.0 [flutter]
- package_info_plus 1.4.0 [flutter package_info_plus_platform_interface package_info_plus_linux package_info_plus_macos package_info_plus_windows package_info_plus_web]
- permission_handler 9.2.0 [flutter meta permission_handler_android permission_handler_apple permission_handler_windows permission_handler_platform_interface]
- pin_code_fields 7.3.0 [flutter]
- plaid_flutter 2.2.0 [flutter plugin_platform_interface flutter_web_plugins js]
- pretty_dio_logger 1.2.0-beta-1 [dio]
- retrofit 3.0.1+1 [dio meta]
- sanitize_html 2.0.0 [html meta]
- timezone 0.8.0 [path]
- url_launcher 6.0.20 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 3.0.6 [crypto]

dev dependencies:
- build_runner 2.1.8 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- build_test 2.1.5 [async build build_config build_resolvers crypto glob html logging matcher package_config path stream_transform test test_core watcher]
- flutter_driver 0.0.0 [file flutter flutter_test fuchsia_remote_debug_protocol path meta vm_service webdriver archive async boolean_selector characters charcode clock collection crypto matcher material_color_utilities platform process source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math]
- flutter_launcher_icons 0.9.2 [args image path yaml]
- flutter_lints 1.0.4 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph typed_data]
- freezed 0.14.5 [analyzer build build_config collection meta source_gen freezed_annotation]
- freezed_annotation 0.14.3 [collection json_annotation meta]
- http_mock_adapter 0.3.1 [collection dio http_parser]
- integration_test 0.0.0 [flutter flutter_driver flutter_test path vm_service archive async boolean_selector characters charcode clock collection crypto fake_async file matcher material_color_utilities meta source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math webdriver]
- json_serializable 6.1.5 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- mockito 5.1.0 [analyzer build code_builder collection dart_style matcher meta path source_gen test_api]
- postman_dio 1.0.4 [flutter dio]
- retrofit_generator 3.0.1+1 [dio source_gen built_collection code_builder tuple retrofit analyzer dart_style build]
- storybook_device_preview 0.2.0+5 [device_preview flutter storybook_flutter]
- storybook_flutter 0.7.0+1 [collection device_frame flutter freezed_annotation provider recase]
- test_cov_console 0.2.2

transitive dependencies:
- _fe_analyzer_shared 31.0.0 [meta]
- analyzer 2.8.0 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 3.1.6 [crypto path]
- args 2.3.0
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.2.1 [analyzer async convert crypto glob logging meta path]
- build_config 1.0.0 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.0.1 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.6 [analyzer async build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.2.3 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.1.4 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 1.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.0.1 [flutter flutter_cache_manager cached_network_image_platform_interface]
- characters 1.2.0
- charcode 1.3.1
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- cli_util 0.3.5 [meta path]
- code_builder 4.1.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- convert 3.0.1 [typed_data]
- coverage 1.0.3 [args logging package_config path source_maps stack_trace vm_service]
- csslib 0.17.1 [source_span]
- dart_style 2.2.1 [analyzer args path pub_semver source_span]
- device_frame 0.4.2 [flutter_svg path_drawing freezed_annotation flutter]
- device_info_plus_linux 2.1.1 [device_info_plus_platform_interface file flutter meta]
- device_info_plus_macos 2.2.2 [device_info_plus_platform_interface flutter]
- device_info_plus_platform_interface 2.3.0+1 [flutter meta plugin_platform_interface]
- device_info_plus_web 2.1.0 [device_info_plus_platform_interface flutter_web_plugins flutter]
- device_info_plus_windows 2.1.1 [device_info_plus_platform_interface ffi flutter win32]
- device_preview 0.7.4 [flutter flutter_localizations provider path_provider device_frame font_awesome_flutter http freezed_annotation json_annotation shared_preferences pedantic path]
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase_analytics_platform_interface 3.1.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.4.0+8 [firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_core_platform_interface 4.4.0 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.6.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.2.6 [collection firebase_core flutter meta plugin_platform_interface]
- fixnum 1.0.0
- flutter_blurhash 0.6.4 [flutter]
- flutter_cache_manager 3.3.0 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path typed_data vector_math]
- flutter_plugin_android_lifecycle 2.0.5 [flutter]
- flutter_secure_storage_linux 1.1.0 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_macos 1.1.0 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_platform_interface 1.0.0 [flutter plugin_platform_interface]
- flutter_secure_storage_web 1.0.2 [flutter flutter_web_plugins flutter_secure_storage_platform_interface js]
- flutter_secure_storage_windows 1.1.2 [flutter flutter_secure_storage_platform_interface]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta typed_data vector_math]
- font_awesome_flutter 9.2.0 [flutter]
- frontend_server_client 2.1.2 [async path]
- fuchsia_remote_debug_protocol 0.0.0 [process vm_service file meta path platform]
- glob 2.0.2 [async collection file path string_scanner]
- graphs 2.1.0 [collection]
- html 0.15.0 [csslib source_span]
- http_multi_server 3.2.0 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 3.1.3 [archive meta xml]
- io 1.0.3 [meta path string_scanner]
- js 0.6.3
- lints 1.0.1
- local_auth_android 1.0.2 [flutter flutter_plugin_android_lifecycle intl local_auth_platform_interface]
- local_auth_ios 1.0.4 [flutter intl local_auth_platform_interface]
- local_auth_platform_interface 1.0.3 [flutter intl plugin_platform_interface]
- logging 1.0.2
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.3
- meta 1.7.0
- mime 1.0.1
- nested 1.0.0 [flutter]
- node_preamble 2.0.1
- octo_image 1.0.1 [flutter flutter_blurhash]
- package_config 2.0.2 [path]
- package_info_plus_linux 1.0.3 [package_info_plus_platform_interface flutter path]
- package_info_plus_macos 1.3.0 [flutter]
- package_info_plus_platform_interface 1.0.2 [flutter meta plugin_platform_interface]
- package_info_plus_web 1.0.4 [flutter flutter_web_plugins http meta package_info_plus_platform_interface]
- package_info_plus_windows 1.0.4 [package_info_plus_platform_interface ffi flutter win32]
- path 1.8.0
- path_drawing 0.5.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.2.1 [vector_math meta]
- path_provider 2.0.9 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- path_provider_android 2.0.12 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.8 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.5 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.5 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.3 [flutter platform plugin_platform_interface]
- path_provider_windows 2.0.5 [ffi flutter path path_provider_platform_interface win32]
- pedantic 1.11.1
- permission_handler_android 9.0.2+1 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.0.3 [flutter permission_handler_platform_interface]
- permission_handler_platform_interface 3.7.0 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.1.0 [flutter permission_handler_platform_interface]
- petitparser 4.4.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- pool 1.5.0 [async stack_trace]
- process 4.2.4 [file path platform]
- provider 5.0.0 [collection flutter nested]
- pub_semver 2.1.1 [collection meta]
- pubspec_parse 1.2.0 [checked_yaml collection json_annotation pub_semver yaml]
- quiver 3.0.1+1 [matcher]
- recase 4.0.0
- rxdart 0.27.3
- shared_preferences 2.0.13 [flutter shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- shared_preferences_android 2.0.11 [flutter shared_preferences_platform_interface]
- shared_preferences_ios 2.1.0 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.1.0 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_macos 2.0.3 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.3 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.1.0 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.2.0 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 3.0.0 [path shelf shelf_static]
- shelf_static 1.1.0 [convert http_parser mime path shelf]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.2.1 [analyzer async build dart_style glob meta path source_span yaml]
- source_helper 1.3.1 [analyzer collection source_gen]
- source_map_stack_trace 2.1.0 [path stack_trace source_maps]
- source_maps 0.10.10 [source_span]
- source_span 1.8.1 [collection path term_glyph]
- sqflite 2.0.2 [flutter sqflite_common path]
- sqflite_common 2.2.1 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- sync_http 0.3.0
- synchronized 3.0.0
- term_glyph 1.2.0
- test 1.19.5 [analyzer async boolean_selector collection coverage http_multi_server io js node_preamble package_config path pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel typed_data web_socket_channel webkit_inspection_protocol yaml test_api test_core]
- test_api 0.4.8 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- test_core 0.4.9 [analyzer async args boolean_selector collection coverage frontend_server_client glob io meta package_config path pool source_map_stack_trace source_maps source_span stack_trace stream_channel vm_service yaml matcher test_api]
- timing 1.0.0 [json_annotation]
- tuple 2.0.0 [quiver]
- typed_data 1.3.0 [collection]
- url_launcher_android 6.0.15 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.15 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.0 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.0.5 [flutter plugin_platform_interface]
- url_launcher_web 2.0.9 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.0 [flutter url_launcher_platform_interface]
- vector_math 2.1.1
- vm_service 7.5.0
- watcher 1.0.1 [async path]
- web_socket_channel 2.1.0 [async crypto stream_channel]
- webdriver 3.0.0 [archive matcher path stack_trace sync_http]
- webkit_inspection_protocol 1.0.0 [logging]
- win32 2.4.1 [ffi]
- xdg_directories 0.2.0+1 [meta path process]
- xml 5.3.1 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]```

</details>

---

**Comment by vigdora** [comment]
another log with a bit different stack: 

> Fatal Exception: NSRangeException
> 0  CoreFoundation                 0x112b94 __exceptionPreprocess
> 1  libobjc.A.dylib                0x1fbe7 objc_exception_throw
> 2  CoreFoundation                 0x192f64 _CFThrowFormattedException
> 3  CoreFoundation                 0xfd15 -[__NSArrayM removeAllObjects]
> 4  UIKitCore                      0x8f0df8 -[UIInputSwitcherView localizedTitleForItemAtIndex:]
> 5  UIKitCore                      0x8fa24c -[UIKeyboardMenuView customizeCell:forItemAtIndex:]
> 6  UIKitCore                      0x8f107a -[UIInputSwitcherView customizeCell:forItemAtIndex:]
> 7  UIKitCore                      0x8f102f -[UIInputSwitcherView tableView:cellForRowAtIndexPath:]
> 8  UIKitCore                      0xf38d24 -[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:]
> 9  UIKitCore                      0xf392c3 -[UITableView _createPreparedCellForGlobalRow:willDisplay:]
> 10 UIKitCore                      0xf68075 -[_UITableViewUpdateSupport _setupAnimationsForNewlyInsertedCells]
> 11 UIKitCore                      0xf71c51 -[_UITableViewUpdateSupport _setupAnimations]
> 12 UIKitCore                      0xf044b6 -[UITableView _updateWithItems:updateSupport:]
> 13 UIKitCore                      0xefb7ff -[UITableView _endCellAnimationsWithContext:]
> 14 UIKitCore                      0xf165d5 -[UITableView _updateSections:withUpdateAction:rowAnimation:headerFooterOnly:usingPresentationValues:]
> 15 UIKitCore                      0xf16b44 -[UITableView reloadSections:withRowAnimation:]
> 16 UIKitCore                      0x8f9ab7 -[UIKeyboardMenuView highlightRow:]
> 17 UIKitCore                      0x8f693b -[UIKeyboardMenuView show]
> 18 UIKitCore                      0x8f73e4 -[UIKeyboardMenuView showAsHUDFromLocation:withInputView:touchBegan:]
> 19 UIKitCore                      0x8ea72e -[UIInputSwitcher showSwitcherShouldAutoHide:]
> 20 UIKitCore                      0x10fdffe -[UIDelayedAction timerFired:]
> 21 Foundation                     0x14d54a __NSFireTimer
> 22 CoreFoundation                 0x816b6 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
> 23 CoreFoundation                 0x811b2 __CFRunLoopDoTimer
> 24 CoreFoundation                 0x80771 __CFRunLoopDoTimers
> 25 CoreFoundation                 0x7adb0 __CFRunLoopRun
> 26 CoreFoundation                 0x7a0f3 CFRunLoopRunSpecific
> 27 GraphicsServices               0x3cd3 GSEventRunModal
> 28 UIKitCore                      0xccdf42 -[UIApplication _run]
> 29 UIKitCore                      0xcd2b5e UIApplicationMain
> 30 Runner                         0x8cef main + 5 (AppDelegate.swift:5)
> 31 ???                            0x1036acee9 (Missing)
> 32 ???                            0x1 (Missing)

**Comment by darshankawar** [comment]
I believe this is similar to https://github.com/firebase/flutterfire/issues/8779, so I suggest you to follow-up in it for further updates. If you disagree, write in comments and I'll reopen it.
