### ISSUE TITLE
🐛 [Crashlytics] New Fatal error API doesn't work on Android

### ISSUE THREAD

**Issue by subzero911** [firebase/flutterfire#8802]
When I added for `FlutterError.onError`:
```dart
FirebaseCrashlytics.instance.recordFlutterFatalError(flutterErrorDetails);
```
and for `Zone`:
```dart
FirebaseCrashlytics.instance.recordError(error, stack, printDetails: false, fatal: true);
```
On Android, build failed with a message:

![image](https://user-images.githubusercontent.com/12999702/170973017-c9d3c7ec-5164-4e4f-8211-40cc9704c7ca.png)

My team mate has the same issue:
![image](https://user-images.githubusercontent.com/12999702/170973096-0aad472d-1df2-457a-904e-5174d3c20fc2.png)

**Comment by darshankawar** [comment]
There's similar open issue describing your case, https://github.com/firebase/flutterfire/issues/8697.
Please go through underlying solutions mentioned in it and see if they help to resolve issue at your end, specifically https://github.com/firebase/flutterfire/issues/8697#issuecomment-1135287338 and https://github.com/firebase/flutterfire/issues/8697#issuecomment-1141041967

Closing this as a duplicate.
