### ISSUE TITLE
🐛 [UI] Forgot Password exception message persisting even after email successfully sent 

### ISSUE THREAD

**Issue by BrutalCoding** [firebase/flutterfire#8804]
## Bug report

**Describe the bug**
When visiting "Forgot Password", you are able to type in an email. In some cases, you will trigger a `FirebaseAuthException` and when that happens, the exception message sticks around on the next screen even though the e-mail has been sent off successfully. 

I have added solutions to fix this bug at the bottom of this post in the section '**Additional context**'.

# Steps to reproduce
## 1. Confirm basic textfield form validation
The email textfield has basic form validation, e.g. typing in "abc" and tapping "Reset password" will display the following textfield validation error: "Provide a valid email", thats good.

Now try the e-mail "john.doe@example", and tap on "Reset password". It will still display "Provide a valid email", so far so good.
<img width="250" alt="image" src="https://user-images.githubusercontent.com/85464739/171007196-8f1735e5-1ca1-408d-bbe2-7bfc6a6be652.png">

### 2.1. Using non-existing Firebase Auth e-mail
Type in an e-mail that you do not have in your Firebase Auth instance, it will trigger the following Exception: "Account doesn't exist" 
<img width="250" alt="image" src="https://user-images.githubusercontent.com/85464739/171009125-f3c814d4-7d09-4106-b04e-666a0e4ddf88.png">

### (Optional) 2.2. - Hardware keyboard
Optionally, you can cause another exception by typing in the e-mail "john.doe@example", select the textfield so that it is in focus, connect a hardware keyboard and hit the "Enter" key. The page will now display the following exception: "This email address is badly formatted." because we are missing ".com" (or any TLD) behind our e-mail address.
<img width="250" alt="image" src="https://user-images.githubusercontent.com/85464739/171007786-370cd7e4-3675-4ce9-8c20-813bd83a1ebe.png">

#### Grammar side note
* The error message "Account doesn't exist" ends the sentence without a period, but "This email address is badly formatted." does. Could be done better!

## The issue
The exception message does not disappear even when the e-mail is corrected and has been sent off successfully. See image below.
<img width="250" alt="image" src="https://user-images.githubusercontent.com/85464739/171008459-9109308f-ce25-4df0-b54c-a9e4faabf325.png">

### Expected behavior

The exception message should not appear on this page:
<img width="250" alt="image" src="https://user-images.githubusercontent.com/85464739/171008459-9109308f-ce25-4df0-b54c-a9e4faabf325.png">

### Sample project

No sample project provided. Please use flutterfire_ui and have it working with e-mail auth. In my case, I used e-mail & password in this example. 

---

## Additional context

The issue can be resolved different ways. The bug lies in the following file: packages/flutterfire_ui/lib/src/auth/views/forgot_password_view.dart

### Solution 1. Set exception to null
On line 52, in the file `forgot_password_view.dart`, the exception gets set but never cleared. A solution would be to write `exception = null;` on line 49. 
<img width="500" alt="image" src="https://user-images.githubusercontent.com/85464739/171013138-80b2a97c-86b1-4710-b333-9a7eb5a4b97d.png">
Permalink: https://github.com/firebase/flutterfire/blob/982bdfb5fbfae4a68e1af6ab62a9bd762891b217/packages/flutterfire_ui/lib/src/auth/views/forgot_password_view.dart#L49

### Solution 2.  Hide exception message when email has been sent
On line 87, the only condition to show the exception message is having one. We could add another condition such as `exception != null && !emailSent`.
<img width="500" alt="image" src="https://user-images.githubusercontent.com/85464739/171012763-cc399c69-ae14-4d41-ba77-9703182250e5.png">
Permalink: https://github.com/firebase/flutterfire/blob/982bdfb5fbfae4a68e1af6ab62a9bd762891b217/packages/flutterfire_ui/lib/src/auth/views/forgot_password_view.dart#L87

---

**Comment by darshankawar** [comment]
Thanks for the detailed report. I was able to replicate this issue using plugin's example as below:

<img width="321" alt="Screenshot 2022-05-31 at 4 07 37 PM" src="https://user-images.githubusercontent.com/67046386/171154978-276d5686-ab1e-4d75-b882-166b7d68d751.png">
