### ISSUE TITLE
[📚] Firebase App Check Usage documentation link not working

### ISSUE THREAD

**Issue by dpedrinha** [firebase/flutterfire#8805]
Pretty much it.

The link for the Firebase App Check Usage documentation is not working.

**Comment by darshankawar** [comment]
@dpedrinha 
Which link are you referring to ?

According to https://firebase.flutter.dev/docs/app-check/overview/, the page is archive and shows new links to refer.

Or are you referring to https://firebase.flutter.dev/docs/app-check/overview/#next-steps ?

**Comment by dpedrinha** [comment]
@darshankawar Sorry, I forgot to tell the links.

This one [https://firebase.flutter.dev/docs/app-check/usage](https://firebase.flutter.dev/docs/app-check/usage) from the pub.dev repository.

And the second one you said ([https://firebase.flutter.dev/docs/app-check/overview/#next-steps](https://firebase.flutter.dev/docs/app-check/overview/#next-steps)).

Neither are working.

And code in the video from your first link doesn't work either.

**Comment by nilsreichardt** [comment]
I fixed this already in #8818 and #8727. The update should already be on pub.dev. We can close this issue :)

**Comment by darshankawar** [comment]
Thanks for the update. Closing per above as fixed.
