### ISSUE TITLE
[📚] Crashlytics recordFlutterFatalError

### ISSUE THREAD

**Issue by ftognetto** [firebase/flutterfire#8815]
Hello, on the new documentation of crashlytics https://firebase.google.com/docs/crashlytics/get-started it is written to use 

`FlutterError.onError = FirebaseCrashlytics.instance.**recordFlutterFatalError**;`

instead on https://pub.dev/packages/firebase_crashlytics it is written to use

`FlutterError.onError = FirebaseCrashlytics.instance.**recordFlutterError**;`

I always used the second one but on the new documentation it use recordFlutterFatalError and this is causing me a lot of trouble on the crashlytics dashboard because every error is marked as a crash.

Why then? Thank you

**Comment by oodavid** [comment]
I came here to ask this very question.

We recently upgraded our various FlutterFire plugins, changed our implementation to match the new documentation and now everything is being logged as fatal.

My `main.dart` looks like this:

```dart
void main() async {
  await runZonedGuarded(() async {
    // Initialise Firebase before rendering the app, see: https://firebase.flutter.dev/docs/overview/#initializing-flutterfire
    WidgetsFlutterBinding.ensureInitialized();
    await Firebase.initializeApp();
    // Error logging
    FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterFatalError;
    Isolate.current.addErrorListener(RawReceivePort((pair) async {
      final List<dynamic> errorAndStacktrace = pair;
      await FirebaseCrashlytics.instance.recordError(
        errorAndStacktrace.first,
        errorAndStacktrace.last,
      );
    }).sendPort);
    // Get cracking
    runApp(MyApp());
  }, (error, stack) {
    FirebaseCrashlytics.instance.recordError(error, stack, fatal: true);
  });
}
```

Possibly related: #8779

**Comment by maximveksler** [comment]
> My `main.dart` looks like this:

@oodavid is 

```dart
    Isolate.current.addErrorListener(RawReceivePort((pair) async {
      final List<dynamic> errorAndStacktrace = pair;
      await FirebaseCrashlytics.instance.recordError(
        errorAndStacktrace.first,
        errorAndStacktrace.last,
      );
    }).sendPort);
```

Actually working for?

I'm compilation errors

![image](https://user-images.githubusercontent.com/550550/183710268-cd651179-5e79-4f7e-b7b0-dc77a799bae0.png)

**Comment by niklaesAtMonta** [comment]
Having the same issue, 
I might switch back to recordFlutterError since I do not want the errors as crashes
