### ISSUE TITLE
[📚] Remote Config Index > Getting Started link redirects to 404

### ISSUE THREAD

**Issue by crtl** [firebase/flutterfire#8828]
On the page https://firebase.flutter.dev/docs/remote-config/overview/
The "Getting Started" link redirects to a 404 page (https://firebase.flutter.dev/docs/remote-config/overview/get-started).
Instead it should be https://firebase.flutter.dev/docs/remote-config/get-started/

Also the "Edit this page" link is broken and redirects to 404 not found too.

**Comment by darshankawar** [comment]
@crtl 
The `notice` section on that page has `get-started` link which works and re-directs you to firebase page: https://firebase.google.com/docs/remote-config/get-started?platform=flutter 
See if this helps.

Ideally, we should now follow the new links mentioned in the `notice` section as the link you are accessing has been archived as mentioned:


<img width="838" alt="Screenshot 2022-06-06 at 3 43 49 PM" src="https://user-images.githubusercontent.com/67046386/172141896-018d4485-b0e3-4176-b762-4afeb51f94c8.png">

Let us know if the link on `firebase.google.com` works for you or not.
