### ISSUE TITLE
🐛 FirebaseMessaging: onMessage doesn't work on android

### ISSUE THREAD

**Issue by z85510** [firebase/flutterfire#8831]
## Bug report

**onMessage doesn't work on andorid**

when app is running notification doesn't show but backgroundMessage is working great.

when a notification received this message will display on terminal : 

`D/FLTFireMsgReceiver(32764): broadcast received for message`

my code : 
```

    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    FirebaseMessaging.onBackgroundMessage(myBackgroundMessageHandler);
    final FirebaseMessaging fcm = FirebaseMessaging.instance;
    await fcm.getToken().then((token) async {
      printLogger(token);
      await settingService.setData('fcmToken', token ?? '');
    });

    FirebaseMessaging.onMessage.listen((RemoteMessage message) {
      print('$message');
    }
    
```

```

  firebase_analytics: ^9.1.9
  firebase_core: ^1.17.1
  firebase_messaging: ^11.4.1
```

**Comment by AhmedAbogameel** [comment]
i have the same issue did you get any solution ?

**Comment by AhmedAbogameel** [comment]
https://github.com/firebase/flutterfire/issues/6011#issuecomment-841861077

this worked for me

**Comment by darshankawar** [comment]
@z85510 
Check if above linked solution works for you or not.
