### ISSUE TITLE
GoogleService-Info.plist required with Google_Sign_In package in Flutter for iOS

### ISSUE THREAD

**Issue by bichoalexis** [firebase/flutterfire#8848]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.4.1
  * Firebase Component: Auth, Core, FireStorage, Storage
  * Target platform(s): `iOS`

### [REQUIRED] Step 2: Describe the problem

I follow the Firebase Flutter guide to install firebase, everything works properly including android (using google sign in). But the problem occurs when I tried to authenticated using Google Sign in. They throw me an error which saids "GoogleService-Info required".

Of course If I manually install the file, everything works properly, but the point is that it suppose to be automatically assigned, alright? 

I run Flutter Doctor and everything it's ok.

**Comment by darshankawar** [comment]
@bichoalexis 
Thanks for the report. Have you configured your firebase project using FlutterFire CLI tool, ie, using dart-only initialization ?

If so, you are probably hitting https://github.com/flutter/flutter/issues/96391. Please check and confirm.

**Comment by bichoalexis** [comment]
Yeah! That’s exactly what I hitting.
Thanks for referring me.

I will appreciate if you add this problem in the oficial firebase documentation :)

**Comment by darshankawar** [comment]
Thanks for confirming. Please follow-up in linked issue for further updates.
Closing this as a duplicate.
