### ISSUE TITLE
🐛 [firebase_database] MissingPluginException

### ISSUE THREAD

**Issue by jbxbergdev** [firebase/flutterfire#8850]
The problem has already been reported in #7795 and #8015 . However, these issues got locked by a bot.
This problem still exists. I think the information that is possible to give was already given in the two tickets mentioned above. As already noted, it is not reliably reproducible, and there isn't a very meaningful stack trace.

Please look into the problem. I'd suggest not locking it because gathering more information may not be possible within the time limit.

@deepak786 @AlaaCherbib

**Comment by darshankawar** [comment]
Thanks for the update. Yes, a sample code would be helpful to know usage of `once()` and to debug further.

**Comment by jbxbergdev** [comment]
@darshankawar I have to correct myself: On the collection mentioned in the stack trace, we both get values with `once()` an then listen with `onChildAdded`. From the crash report, I cannot see which call is the offending one. I'll post both code snippets:

```
FirebaseDatabase.instance
        .ref()
        .child('our_collection')
        .orderByKey()
        .startAt(keyToStartAt)
        .once()
        .then((event) => print((event.snapshot.value as Map)[someField]));
``` 
and

```
 FirebaseDatabase.instance
        .ref()
        .child('our_collection')
        .orderByKey()
        .startAt(keyToStartAt)
        .onChildAdded
        .listen((event) => print((event.snapshot.value as Map)[someField]) );
```

**Comment by jbxbergdev** [comment]
Here's a screenshot of the crash report (database URL and data path censored):
![image](https://user-images.githubusercontent.com/12424161/172596815-a5dc176f-f7b9-4758-92a4-6d93e1f45ccd.png)

**Comment by darshankawar** [comment]
By that I meant to ask if there's a clash between data that was returned by `once()` which is fetched from local disk cache, but if you are also updating your database after some point and comparing, there might be a conflict between them, ie the data you updated in database and the one you have in local cache using `once()`. Are you using stream to fetch the data ?

**Comment by jbxbergdev** [comment]
@darshankawar We only retrieve the objects. The objects only get added to the collection and from then aren't modified any more. 

We fetch the data (once()) and then listen for additions with onChildAdded.

**Comment by darshankawar** [comment]
Thanks for the update. I am going ahead and reopening https://github.com/firebase/flutterfire/issues/7795 and will link this issue there for team's reference. you may also share your findings in it.
Closing this as a duplicate.
