### ISSUE TITLE
🐛 [firebase_auth] userChanges() stream old data after linkWithCredential on chrome

### ISSUE THREAD

**Issue by Kirchesch** [firebase/flutterfire#8856]
## Bug report

**Describe the bug**
userChanges is streamed when we call linkWithCredential on the user, and it works fine on android, but when on chrome it streams data before the link happens, so if you check if the user isAnonymous on a listener you will see it will still be anonymous

### Steps to reproduce
1. Initialize firebase as you would
2. Listen to the userChanges stream `FirebaseAuth.instance.userChanges().listen((event) { print("User updated: ${event}"); });`
3. SignIn anonymously `auth.FirebaseAuth.instance.signInAnonymously();`
4. Link the anonymous account `auth.FirebaseAuth.instance.currentUser!.linkWithCredential(EmailAuthProvider.credential(email: "dsadsa@dasdas.dasdsa", password: "dasdsadsa",),);`
5. Now build for android and see it working as expected
6. Then build for chrome and see that after linking the account you will receive an update on the stream but the account they give you on the stream will still not be linked

### Expected behavior
For the stream be updated after the user get linked not before

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the report @Kirchesch. I think your case is same / similar to https://github.com/firebase/flutterfire/issues/3356. Can you check that and confirm ?

**Comment by Kirchesch** [comment]
It appears to be related
But i am not having the issues they do, i receive only one update on each listener as it should, and it sinks with the right data, the only problematic one ( Of the ones i use ) is when i link an account with credentials, then it sinks in the userChanges() before actually updating the user, so:

Line 1: await auth...linkWithCredentials(...) // Right here at some point the userChanges is called and it provides old data, data before linking the account
Line 2: print(auth...currentUser) // Right here the user has been linked already and you can see its not anonymous anymore

So the problem is that the logic for handling userChanges is in the delegate bound to userChanges and not in the specific area who calls linkWithCredentials

**Comment by darshankawar** [comment]
Thanks for the update. Can you provide a minimal reproducible code sample that we can use directly to analyze this further ?

**Comment by Kirchesch** [comment]
@darshankawar forgot to mention you last comment, in case you haven't been notified im just letting you know i created a repository to test this issue: https://github.com/KircheschContributions/FlutterIssues

**Comment by darshankawar** [comment]
Thanks for the repo. I cloned it and first ran it on mobile which gave me below result:

`flutter: user state updated AsyncSnapshot<User?>(ConnectionState.active, User(displayName: null, email: 9855@fakemail.com, emailVerified: false, isAnonymous: true, metadata: UserMetadata(creationTime: 2022-06-09 12:01:56.552, lastSignInTime: 2022-06-09 12:01:56.552), phoneNumber: null, photoURL: null, providerData, [], refreshToken: , tenantId: null, uid: 0LvswJ1Ys9dUz5tgoH6lSYMR7t52), null, null)`

That shows `email: 9855@fakemail.com`

Then I ran the same on chrome which gave me below:

```
user state updated AsyncSnapshot<User?>(ConnectionState.active, User(displayName: null, email: null, emailVerified: false, isAnonymous: true, metadata: UserMetadata(creationTime: 2022-06-09
06:34:10.000, lastSignInTime: 2022-06-09 06:34:10.000), phoneNumber: null, photoURL: null, providerData, [], refreshToken:
AIwUaOmqT8u1g20OJuzK-WIzZNQ7oX08CTJqMLc_FLcZeMWKKt0bvc8Y8de5znEWuH5RA8-xISQIQminEnzUARDZhslOi-GWEqe8fKekJRhFLgSv_QgHLFtntH1aA5eDD-Mz_VU3F-YISe8hgAxvk-E879kwThyhldqpqWgHTrV5gzxsNqaJMOzG-uqWtKY
rS0SRtATArIzsIc4UC3rQBpsIiWrw3npgznJ069fXfX3WIDEu96EcIc8, tenantId: null, uid: xHdvGu8aTEgjJ7IwxfYGwZfGYXD2), null, null)
```
that shows `email: null`, but the expected result is that web should capture the current email being logged in, as shown in mobile. Is this a correct interpretation of the issue ?

**Comment by Kirchesch** [comment]
yes, that is correct

**Comment by darshankawar** [comment]
Thanks for the update. Based on my findings https://github.com/firebase/flutterfire/issues/8856#issuecomment-1150730647, keeping this issue open and labeling.

**Comment by Lyokone** [comment]
We fixed a difference between native and web in https://github.com/firebase/flutterfire/pull/10028

It will be released today, let us know if it solves your issue
