### ISSUE TITLE
🐛 [flutterfire_ui] Facebook sign in error gets swallowed when user is associated with google account

### ISSUE THREAD

**Issue by AndrasTimar** [firebase/flutterfire#8879]
## Bug report

If you have previously signed in with a google account, and then want to sign in with a facebook account with the same e-mail address, using the FacebookSignInButton, Firebase responds with an error (An account already exists with the same email address but different sign-in credentials. Sign in using a provider associated with this email address.). This error is then swallowed inside the plugin, and neither the user, nor the developer are notified, the view only resets the FacebookSignInButton without any error messages. 
The error message is not shown, because this specific error gets transformed to a DifferentSignInMethodsFound AuthState before it reaches the _ErrorHandler of the button.

One account per email address is turned on in firebase settings.

### Steps to reproduce

1. Authenticate with GoogleSignInButton
2. Log out.
3. Try authenticating with FacebookSignInButton.
4. Facebook authentication fails, without any error messages.

Expected behavior

If firebase is capable of handling it somehow, the user should be able to log in with facebook after logging in with google. If that's not a possibility, the user should at least get an error message describing the situation.

**Comment by AndrasTimar** [comment]
I have since managed to get the DifferentSignInMethodsFound AuthState via wrapping the FacebookSignInButton with a FlutterFireUIActions widget. I still think the button should in itself somehow signal the issue to the user, as it does with all other errors.

**Comment by maheshmnj** [comment]
Hi @AndrasTimar, Thanks for filing the issue. Can you please share a minimal and complete code sample to investigate the issue further ?

Thanks

**Comment by MarcVanDaele90** [comment]
Some additional observations listed in #8912: 
- the same is observed when the user first authenticates with a EmailProviderConfiguration
- authenticating with Google after authenticating with Email or Facebook does work

@AndrasTimar I'm using a registerScreen right now: Any idea whether your FlutterFireUIActions would also work here?

**Comment by AndrasTimar** [comment]
Hi! I don't have much to add, but to reiterate:
The problem arises when a user registers with Google/Email and password/(probably Apple, did not test), and then tries to sign in with a Facebook account. In this case the Facebook account does not get automatically linked to the firebase user account (as it does when you e.g. sign in with Apple after registering with Google), and the sign in fails silently, without the FacebookSignInButton showing any errors.
A complete example of this issue can be constructed using a GoogleSignInButton and a FacebookSignInButton. 
The built-in SignInScreen solves this problem by calling showDifferentMethodSignInDialog(..), but the simple FacebookSignInButton does not react to the DifferentSignInMethodsFound AuthState.
Proposed solution is showing an error message below the FacebookSignInButton when it encounters a DifferentSignInMethodsFound AuthState.

**Comment by darshankawar** [comment]
Thanks for the update. I verified this using flutterfire_ui plugin [example](https://github.com/firebase/flutterfire/blob/master/packages/flutterfire_ui/example/lib/stories.dart) which has `FacebookSignInButton` and `GoogleSignInButton` example.

When you follow order, ie, authenticate with Google first and then use same email to sign in with Facebook, which fails silently without throwing error. 

/cc @lesnitsky

**Comment by lesnitsky** [comment]
This is no longer reproducible on the latest version of the `firebase_ui_auth`.
