### ISSUE TITLE
[firebase_messaging] How to group notifications when App is in Background

### ISSUE THREAD

**Issue by Nidal-Bakir** [firebase/flutterfire#8884]
While creating the Messaging App. If the User is not on the App and gets the message from the other device, the device receives notifications but gets different notifications for each message for the same user. There is no such option to group/combine notifications & cancel the old notifications with the new ones.
the #1736 and #1770 are closed without the right solution!! by reading the docs for [collapsekey](https://firebase.google.com/docs/reference/admin/node/firebase-admin.messaging.messagingoptions.md#messagingoptionscollapsekey)
the solution offered by @Salakar  [this comment ](https://github.com/firebase/flutterfire/issues/1770#issuecomment-722285841) is not applicable in this scenario.
what I need to achieve 👇️

![FvglK](https://user-images.githubusercontent.com/29513372/173126361-3ac879c1-c285-498b-8f68-09ada0159be5.png)
</div>

**Comment by MROOT-user** [comment]
check desktop .first 
  --  clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev

**Comment by maheshmnj** [comment]
@Nidal-Bakir Did you try using local notification as mention in that comment https://github.com/firebase/flutterfire/issues/1770#issuecomment-722285841 ?

**Comment by maheshmnj** [comment]
thanks for the info @Nidal-Bakir, labeling this issue for further insights from the team.

**Comment by Lyokone** [comment]
Hello @Nidal-Bakir, we currently don't support anyway of grouping notification. You can follow [this guide](https://pub.dev/packages/flutter_local_notifications#grouping-notifications) to see how to handle grouping notifications.
