### ISSUE TITLE
🐛 [firebase_messaging]Support for Android 13

### ISSUE THREAD

**Issue by vohoangtuit** [firebase/flutterfire#8892]
i intergated firebase_messaging 11.4.1, and run function getToken() on android api 32 (Tiramisu) with Error:

FirebaseMessaging java.io.IOException: AUTHENTICATION_FAILED

- I run on other devices working

**Comment by maheshmnj** [comment]
Hi @vohoangtuit, Thanks for filing the issue. Android Tiramisu is still in developer preview, I am quite not sure if the firebase plugins are ready to support the new android version or it requires updating the SDK and the plugins. I am labeling the issue for further insights from the team.

cc: @russellwheatley

**Comment by darshankawar** [comment]
@vohoangtuit 
This seem to have been fixed as part of this PR: https://github.com/firebase/flutterfire/pull/9348, so I suggest you to upgrade plugin version to latest and try again to see if you still get the same error or not.

**Comment by russellwheatley** [comment]
We have implemented support for android 13 notifications as mentioned by @darshankawar.
