### ISSUE TITLE
🐛 [firebase_core] Firebase.initializeApp fails with error when using Firebase Emulator demo project.

### ISSUE THREAD

**Issue by Turburlar** [firebase/flutterfire#8898]
I am using the Firebase Emulator to develop.

I am using a Firebase Emulator demo project that has no associated firebase/gcp cloud project actually created.

A demo project is defined here: https://firebase.google.com/docs/emulator-suite/connect_firestore

I use the following command to start the emulator with a specific demo project name...

`firebase emulators:start --project demo-test --only firestore`

The emulator successfully starts and hosts at localhost:8080.

Then when I try to run initializeApp in my Firebase Project as follows...

```
await Firebase.initializeApp(name: "demo-test");
    FirebaseFirestore.instance.settings = const Settings(
      host: 'localhost:8080',
      sslEnabled: false,
      persistenceEnabled: false,
    );
```

I get the following error...

```
Restarted application in 2,058ms.
E/flutter ( 7724): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: [core/not-initialized] Firebase has not been correctly initialized.
E/flutter ( 7724):
E/flutter ( 7724): Usually this means you've attempted to use a Firebase service before calling `Firebase.initializeApp`.
E/flutter ( 7724):
E/flutter ( 7724): View the documentation for more information: https://firebase.flutter.dev/docs/overview#initialization
E/flutter ( 7724):
E/flutter ( 7724): #0      MethodChannelFirebase.initializeApp
package:firebase_core_platform_interface/…/method_channel/method_channel_firebase.dart:113
E/flutter ( 7724): <asynchronous suspension>
E/flutter ( 7724): #1      Firebase.initializeApp
package:firebase_core/src/firebase.dart:40
E/flutter ( 7724): <asynchronous suspension>
E/flutter ( 7724): #2      _MyHomePageState._asyncInit
package:mobile_app/main.dart:53
E/flutter ( 7724): <asynchronous suspension>
E/flutter ( 7724):
```

The expected behaviour is that Firebase should be able to be initialized with a pure emulator demo project.

**Comment by maheshmnj** [comment]
Hi @Turburlar, Thanks for filing the issue After firebase initialization can you please try defining your settings by running
```
```

**Comment by Turburlar** [comment]
I have updated my code to take into account your suggestion.

The following code gives the same error...

```
    await Firebase.initializeApp();
    FirebaseFirestore.instance.useFirestoreEmulator('localhost', 8080, sslEnabled: false);
```

**Comment by Turburlar** [comment]
@maheshmnj Can you remove the blocked:customer-response tag please.

**Comment by maheshmnj** [comment]
@Turburlar It was removed when you commented.

**Comment by darshankawar** [comment]
@Turburlar 
Try by calling `WidgetsFlutterBinding.ensureInitialized();` before initializing your app.
ie
 ```
WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
 
```

**Comment by darshankawar** [comment]
Thanks for the update. Using the code sample above and initiating firebase emulator with the command provided above, I am getting same error as reported:

```
Launching lib/main.dart on iPhone 13 in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                           55.8s
Debug service listening on ws://127.0.0.1:50903/UT_SjCI4aPo=/ws
Syncing files to device iPhone 13...
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: [core/not-initialized] Firebase has not been correctly initialized.

Usually this means you've attempted to use a Firebase service before calling `Firebase.initializeApp`.

View the documentation for more information: https://firebase.flutter.dev/docs/overview#initialization

#0      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:113:9)
<asynchronous suspension>
#1      Firebase.initializeApp (package:firebase_core/src/firebase.dart:40:31)
<asynchronous suspension>
#2      main (package:testdemo/main.dart:7:3)
<asynchronous suspension>
```

<img width="569" alt="Screenshot 2022-06-21 at 12 57 35 PM" src="https://user-images.githubusercontent.com/67046386/174741415-32003436-ff61-40b9-821b-c25787ec4535.png">

**Comment by russellwheatley** [comment]
You haven't setup Firebase correctly. Ensure you have ran `flutterfire configure` in the root of your app directory and setup the platforms you require.
