### ISSUE TITLE
ci: `analyze` job is 15.00% flaky

### ISSUE THREAD

**Issue by nilsreichardt** [firebase/flutterfire#8913]
I ran in a matrix 100x times the `analzye` job 

![image](https://user-images.githubusercontent.com/24459435/173687773-2a2336a0-aee3-4b94-8247-7bace9772a6b.png)

Output: https://github.com/nilsreichardt/flutterfire/runs/6887635342?check_suite_focus=true

**Results:**
* 10x `The analysis server shut down unexpectedly.`
* 5x `melos bootstrap` timed out

**Comment by nilsreichardt** [comment]
I found a fix for the `The analysis server shut down unexpectedly.` problem. I will create a PR in the next days 👍

**Comment by maheshmnj** [comment]
cc: @russellwheatley
