### ISSUE TITLE
[📚] The docs should return the manual setup since the CLI doesn't cover flavors

### ISSUE THREAD

**Issue by feinstein** [firebase/flutterfire#8918]
As shown in [this issue](https://github.com/invertase/flutterfire_cli/issues/14) the CLI doesn't support Android Flavors and Dimensions or iOS Schemes and Targets, so we can't use the CLI to setup our Firebase projects.

Until recently the setup docs included manual instructions and automated instructions, but now there's only the automated option through the CLI, leaving everyone with flavors/schemes incapable of adopting Firebase with Flutter, or updating the libraries to get the benefits, like better Crashlytics behavior with Flutter.

I believe the manual configuration option should return while the CLI doesn't cover this use cases.

**Comment by neiljaywarner** [comment]
@feinstein @darshankawar  is this correct?  If this is correct this influces whether flavors should be used at all imho.
Is there any documentation about best practice about if flavors are "critical" or if environment switcher and specific crashlytics/analytics urls and filtering are sufficient?

**Comment by neiljaywarner** [comment]
right, but the question is how many of those use cases would be taken care
of by a quick change at runtime, yes that would have some disadvantages (eg
crashes on launch) but maybe some simplicity especially if ther'es issues
with dart-only initialization..

**Comment by feinstein** [comment]
Well, do you see how this would be possible for my use case?

I have 6 different white label apps (and growing), that I want to share the same Firebase, so I can have all the Crashlytics and remote configs at the same place.

Also, I want them to have a separate environment for development and production.

This works fine right now, and that's a functionality that Firebase supports, I am not inventing anything new, Firebase allows me to connect as many Android apps to one project as I want, so why the CLI shouldn't support something that Firebase already supports?

Also, there are many production apps like this, should we try to see how to change them all? How about data migrations for all of them?

I think it's simpler to just change the CLI, and while it doesn't get fixed, we rollback the manual configuration tutorials.

**Comment by neiljaywarner** [comment]
Yes, I agree.
I'm just trying to evaluate

....sent from my phone

**Comment by russellwheatley** [comment]
We do have this on the radar for the FlutterFire CLI. You can follow the [issue here](https://github.com/invertase/flutterfire_cli/issues/14)
