### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core)

### ISSUE THREAD

**Issue by roygwsidev** [firebase/flutterfire#8923]
face error when initialize firebase.

**Comment by maheshmnj** [comment]
Hi @roygwsidev, Could you please share more info about what plugins you are using and the device on which this issue occurs along with the output of `flutter doctor -v`?

**Comment by darshankawar** [comment]
Please use new issue template and fill out requested details so that we'll have enough details to work with. Closing for now, as no details provided.
