### ISSUE TITLE
Not show notification on a firebase project from git

### ISSUE THREAD

**Issue by parisa7103** [firebase/flutterfire#8932]
My teammate configured firebase on the projects. I pull the project from git, but the push notification doesn't work on my project! the firebase_options exists and this is our initialization: 
`    await Firebase.initializeApp(
          name: "access",
          options: isDev
               ? FirebaseAbTest.DefaultFirebaseOptions.currentPlatform
                : FirebaseProduction.DefaultFirebaseOptions.currentPlatform,
    );
`

**Comment by darshankawar** [comment]
@parisa7103 
Your question is better suited for support channels like StackOverflow, so please ask the same there.
If you think there's a genuine bug in the messaging plugin, use new issue template and fill out requested details so that we'll have enough details to work with.
Closing for now.
