### ISSUE TITLE
🐛 [firebase_crashlytics] Stacktrace is obfuscated [Android] [iOS]

### ISSUE THREAD

**Issue by DjordjeMancic97** [firebase/flutterfire#8934]
## Bug report

Stacktrace's inside Firebase Crashlytics are obfuscated unless they are coming from native SDK's or functions.

### Steps to reproduce

1. Build your app with '--obfuscate' flag
2. Produce error in the built version of you app
3. Go to Crashlytics, stacktrace is not readable

### Expected behavior

Instead of:

```
`  at .    #00 abs 0 virt 0082e7a7 _kDartIsolateSnapshotInstructions+0x54ec47()
       at .    #01 abs 0 virt 00871cfb _kDartIsolateSnapshotInstructions+0x59219b()
       at .    #02 abs 0 <invalid Dart instruction address>()`
```

I should see a readable error with paths to problematic files and lines.

### Flutter doctor

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3 21E230 darwin-arm, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.68.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

---

**Comment by darshankawar** [comment]
@DjordjeMancic97 
Thanks for the report. Is this happening in debug mode or in release mode only ?
There was a [similar](https://github.com/firebase/flutterfire/issues/6925) issue reported. Can you take a look and see if it helps ?

**Comment by DjordjeMancic97** [comment]
@darshankawar 
Happening in release mode only. From looking at the issue I am not seeing any helpful information, it's unclear wether this was solved for them. 

Also version of the Firebase packages are: 

firebase_core: 1.17.0
firebase_crashlytics: 2.8.0

**Comment by darshankawar** [comment]
Thanks for the update. This behavior was fixed per [this](https://github.com/firebase/flutterfire/issues/5815#issuecomment-822568080) comment and [issue](https://github.com/firebase/flutterfire/issues/5815). 
Also, original issue at firebase sdk side was reported here : https://github.com/firebase/quickstart-android/issues/897 and per most latest comment from it, it has been fixed: https://github.com/firebase/quickstart-android/issues/897#issuecomment-1134489332

Please see the documentation as mentioned in above comment and see if it helps.

**Comment by DjordjeMancic97** [comment]
So another update, I got past this error. Enabled R8, added ProGuard rules mentioned in the docs, everything is as described there but stacktrace still looks the same :(

**Comment by darshankawar** [comment]
> can't the stacktrace be deobfuscated automatically inside Firebase Crashlytics dashboard?

This probably need to be implemented at firebase crashlytics side because Flutterfire plugins are wrappers around native sdks and leverage their implementation.

**Comment by darshankawar** [comment]
Thanks for the feedback. I'll keep this issue open for further insights from the team.

/cc @russellwheatley

**Comment by RobertApikyan** [comment]
Hi, is this solved? Can we now see deobfuscated dart stack traces on the Firebase dashboard?

**Comment by a1573595** [comment]
Same issue.
I have added the following dependencies：
`com.google.firebase:firebase-crashlytics-gradle`
`apply plugin: 'com.google.firebase.crashlytics'`
`firebaseCrashlytics { mappingFileUploadEnabled true }`
Use `flutter symbolize` still can't see non-obfuscated dart code
<img width="838" alt="截圖 2023-01-11 上午10 18 46" src="https://user-images.githubusercontent.com/25738593/211702602-2d196cc8-b988-43c0-8761-879dac4f5b99.png">

**Comment by russellwheatley** [comment]
Crashlytics now has upload symbol support for both iOS (it has an upload symbol script shipped with the the FirebaseCrashlytics pod) and android (running a command using the Firebase CLI), I have tested on both platforms. 

### Android
It requires the debug symbols to be uploaded before any crashes are logged. If any are logged before the symbols are uploaded, it appears they will remain obfuscated (I believe this is the case, it might be that there is a significant delay in the Firebase console updating).

### iOS
I was not able to get the stack trace de-obfuscated. I've tried using the build phase script, manual uploading via the FirebaseCrashlytics pod, and finally, I zipped the symbols and uploaded. The zip upload curiously prompted this popup box:
<img width="598" alt="Screenshot 2023-01-31 at 16 54 26" src="https://user-images.githubusercontent.com/16018629/215833650-f4107e92-31ce-4dc3-89bb-3331aac3e855.png">

But it has been a lot longer than 10 minutes, and still the stack trace remains obfuscated. I will check the logs again tomorrow.

I was able to run the `flutter symbolize` function on the CLI successfully to de-obfuscate the iOS stack traces. So, for both platforms, it is possible to receive a de-obfuscated stack trace.

## Going forward
- I will escalate the iOS Crashlytics debug symbols issue to the relevant Firebase team and see if we can get that resolved.
- For android, I will update the documentation. At the moment, the upload symbol documentation is [here](https://firebase.google.com/docs/crashlytics/get-started?platform=flutter#add-sdk) in the "Get started" guide. I believe it should be on [this page](https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=flutter), "Get readable crash reports".
- We're assessing the possibility of including the android upload symbol step to FlutterFire CLI as part of running `flutterfire configure` to make it easier for folks. Hypothetically speaking, we could update the app's `build.gradle` to upload the debug symbols by running the Firebase CLI upload-symbol script 🤔 . We shall see.

**Comment by rohansohonee1** [comment]
@russellwheatley 

Used the CLI command `firebase crashlytics:symbols:upload` to upload debug symbols for Android. 
![Screen Shot 2023-02-08 at 8 09 58 PM](https://user-images.githubusercontent.com/120708465/217574632-16728053-0b28-44ed-be09-9bf235da0ef7.png)


- performed a test crash after successfully uploading the symbols.

but the stack traces is still obfuscated in firebase crashlytics.
```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Test crash >> open new order screen. Error thrown Instance of 'Gla'.
BuildId: 4269d600ba1e47d75f35d985bf50c9af
#00 abs 0 virt 0000000000781fe2 _kDartIsolateSnapshotInstructions+0x485842
#01 abs 0 virt 00000000008a16d8 _kDartIsolateSnapshotInstructions+0x5a4f38
#02 abs 0 virt 00000000008a1441 _kDartIsolateSnapshotInstructions+0x5a4ca1
#03 abs 0 virt 0000000000bd5981 _kDartIsolateSnapshotInstructions+0x8d91e1
#04 abs 0 virt 00000000009ea565 _kDartIsolateSnapshotInstructions+0x6eddc5
#05 abs 0 virt 0000000000476972 _kDartIsolateSnapshotInstructions+0x17a1d2
#06 abs 0 virt 00000000004768b1 _kDartIsolateSnapshotInstructions+0x17a111
#07 abs 0 virt 000000000044ef7e _kDartIsolateSnapshotInstructions+0x1527de
#08 abs 0 virt 000000000045c9a1 _kDartIsolateSnapshotInstructions+0x160201
#09 abs 0 virt 0000000000bbfddc _kDartIsolateSnapshotInstructions+0x8c363c
#10 abs 0 virt 0000000000353269 _kDartIsolateSnapshotInstructions+0x56ac9
#11 abs 0 virt 00000000003531c0 _kDartIsolateSnapshotInstructions+0x56a20
#12 abs 0 virt 0000000000352b61 _kDartIsolateSnapshotInstructions+0x563c1
#13 abs 0 virt 00000000005d0c52 _kDartIsolateSnapshotInstructions+0x2d44b2
#14 abs 0 virt 00000000005d0b60 _kDartIsolateSnapshotInstructions+0x2d43c0
#15 abs 0 virt 000000000031bf98 _kDartIsolateSnapshotInstructions+0x1f7f8
#16 abs 0 virt 000000000031becd _kDartIsolateSnapshotInstructions+0x1f72d
#17 abs 0 virt 000000000031be56 _kDartIsolateSnapshotInstructions+0x1f6b6
```

**Comment by russellwheatley** [comment]
@rohansohonee1  Did you upload before or after the crash?

**Comment by rohansohonee1** [comment]
@russellwheatley uploaded before the crash

**Comment by rohansohonee1** [comment]
@russellwheatley It is still obfuscated

**Comment by russellwheatley** [comment]
I tried a couple of times and was able to de-obfuscate the symbols. If you don't mind, would you  clean out your build folders `flutter clean`, and start again? Please note down every step you took so I can take a look. Thanks.

**Comment by rohansohonee1** [comment]
@russellwheatley 

We are using the code magic ci to build appbundle & then upload the symbols.
The screenshot shared in previous comments is from code magic. Their you can see that the symbols are being uploaded successfully.

After some period of time, we are testing the crashes, but the stack traces are still obfuscated.

The next step we tried is to only upload the symbols from local machine. We exported the symbol files from code magic ci and downloaded them onto our local machine. The upload is also successful.

After some period of time, we are testing the crashes & it worked. Stack traces are deobfuscated.


We want to perform this upload via code magic ci. What can be the issue in this case?

**Comment by russellwheatley** [comment]
@rohansohonee1 If we have both got it working from our local machines, and it isn't working from remote. I would assume the locale of the problem is there. 

The first step is to be sure the correct symbols are being uploaded. If you're positive that is the case, the next step would be to take the issue to CodeMagic and find out what the cause could possibly be. I have no experience using CodeMagic I'm afraid.

**Comment by themiswang** [comment]
Hey folks,

First thanks everyone for the report! We've been able to reproduce the issue on iOS which mentioned by @russellwheatley in this [thread](https://github.com/firebase/flutterfire/issues/8934#issuecomment-1410781888). There is a backend fix that's being tested now. We'll update this issue once we validate the fix and it's live.

**Comment by alvarisi** [comment]
Thank you @themiswang 
if the fix also includes this issue during the upload of the flutter symbol to the crashlytics in the iOS app?

I got the issue while running this command
`firebase crashlytics:symbols:upload --app=[FIREBASE_IOS_APP_ID]  app.ios-arm64.symbols`
```
java.io.IOException: Breakpad symbol generation failed (exit=1), see STDERR
	at com.google.firebase.crashlytics.buildtools.ndk.internal.breakpad.BreakpadSymbolGenerator.generateSymbols(BreakpadSymbolGenerator.java:133)
	at com.google.firebase.crashlytics.buildtools.Buildtools.generateNativeSymbolFiles(Buildtools.java:273)
	at com.google.firebase.crashlytics.buildtools.CommandLineHelper.executeGenerateSymbols(CommandLineHelper.java:185)
	at com.google.firebase.crashlytics.buildtools.CommandLineHelper.executeCommand(CommandLineHelper.java:118)
	at com.google.firebase.crashlytics.buildtools.CommandLineHelper.main(CommandLineHelper.java:65)
	at com.google.firebase.crashlytics.buildtools.Buildtools.main(Buildtools.java:111)
```

**Comment by fotiDim** [comment]
> > Thank you @themiswang if the fix also includes this issue during the upload of the flutter symbol to the crashlytics in the iOS app?
> > I got the issue while running this command `firebase crashlytics:symbols:upload --app=[FIREBASE_IOS_APP_ID] app.ios-arm64.symbols`
> > ```
> > java.io.IOException: Breakpad symbol generation failed (exit=1), see STDERR
> > 	at com.google.firebase.crashlytics.buildtools.ndk.internal.breakpad.BreakpadSymbolGenerator.generateSymbols(BreakpadSymbolGenerator.java:133)
> > 	at com.google.firebase.crashlytics.buildtools.Buildtools.generateNativeSymbolFiles(Buildtools.java:273)
> > 	at com.google.firebase.crashlytics.buildtools.CommandLineHelper.executeGenerateSymbols(CommandLineHelper.java:185)
> > 	at com.google.firebase.crashlytics.buildtools.CommandLineHelper.executeCommand(CommandLineHelper.java:118)
> > 	at com.google.firebase.crashlytics.buildtools.CommandLineHelper.main(CommandLineHelper.java:65)
> > 	at com.google.firebase.crashlytics.buildtools.Buildtools.main(Buildtools.java:111)
> > ```
> 
> That firebase CLI command is for android. To upload debug symbols for iOS, follow the instructions [here](https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=flutter#apple)

@russellwheatley Does that also upload the mapping file for the Dart code obfuscation?

**Comment by russellwheatley** [comment]
Yes, Dart should be de-obfuscated.

**Comment by themiswang** [comment]
Hey all, quick update on the fix. While validating our initial approach we uncovered some additional complexity that we need to address. We're working on this now and are aiming to have the fix in place in the coming weeks. I'll keep updating the GitHub issue as we make progress and learn more. Thank you for everyone's patient 🙏

**Comment by VictorMoreira98** [comment]
@russellwheatley  I tried sending the symbols and waited more 10 hours before testing my app version ofuscated, but when an exception occurred, the exception in crashlytics remained obfuscated. I already excuted flutter clean. How many hours did you wait before taking the test? And other exceptions from different versions of my application cannot occur during this time as well?

**Comment by russellwheatley** [comment]
@VictorMoreira98 which platform?

**Comment by VictorMoreira98** [comment]
> @VictorMoreira98qual plataforma?
Android

**Comment by VictorMoreira98** [comment]
@russellwheatley I tryed again with all steps, and that work well, thanks!!

**Comment by otopba** [comment]
Guys, do you have this eror?

```
firebase crashlytics:symbols:upload --app=XXX build/app/outputs/symbols
error: unknown option '--app'
```

**Comment by russellwheatley** [comment]
@otopba check your Firebase CLI version maybe? It should have that argument

**Comment by agonzalezpuerta** [comment]
> ## Going forward
> * I will escalate the iOS Crashlytics debug symbols issue to the relevant Firebase team and see if we can get that resolved.
> * For android, I will update the documentation. At the moment, the upload symbol documentation is [here](https://firebase.google.com/docs/crashlytics/get-started?platform=flutter#add-sdk) in the "Get started" guide. I believe it should be on [this page](https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=flutter), "Get readable crash reports".
> * We're assessing the possibility of including the android upload symbol step to FlutterFire CLI as part of running `flutterfire configure` to make it easier for folks. Hypothetically speaking, we could update the app's `build.gradle` to upload the debug symbols by running the Firebase CLI upload-symbol script 🤔 . We shall see.

@russellwheatley, just to confirm, is this the latest status regarding this issue?

I've successfully uploaded the symbols for iOS using the upload-symbols POD script and:
- I am no longer getting dSYM warnings.
- The stack is still obfuscated.

Which would be aligned with your message quoted above.

**Comment by russellwheatley** [comment]
Hey @agonzalezpuerta, this is the latest update from the Firebase team regarding the server side fix https://github.com/firebase/flutterfire/issues/8934#issuecomment-1457167998.  Once it is fixed, we will update this channel 👌

**Comment by agonzalezpuerta** [comment]
> Hey folks,
> 
> Thanks for your patience and reports while we’ve looked into this. `split-debug-info` is supported for release builds as of FlutterFire firebase_crashlytics 2.9.0+ for Android and as of Flutter 3.7.0+, FlutterFire firebase_crashlytics 3.1.1+ for iOS. If you also build with the `--obfuscate` option, there are caveats on Android and iOS.
> 
> For Android, when building with `--split-debug-info`, if there are no changes to the source code, Flutter will not generate and output new symbols if only the build mode changes (i.e. add `--obfuscate`). We have filed an issue ([flutter/flutter#124141](https://github.com/flutter/flutter/issues/124141)) with the Flutter team to see if we can change this behavior. A work around for this is to force Flutter to output new symbols files by touching a source file before the final build that uses the `--split-debug-info` and `--obfuscate` options.
> 
> For iOS, when building with `--obfuscate`, the symbols table in dSYM still contains the obfuscated symbols, while the DWARF data contains the unobfuscated symbols. Since the obfuscated symbols are uploaded by the upload-symbol script, symbolicated events are still being obfuscated. We have also filed this issue ([flutter/flutter#124715](https://github.com/flutter/flutter/issues/124715)) with the Flutter team. Modifying the upload-symbols scripts to upload the DWARF data is a bigger change that is on our roadmap, but a workaround for now is to use the Crashlytics web dSYM uploader to upload Flutter dSYMs when building with both `--obfuscate` and `--split-debug-info`
> 
> Let us know if you have any questions or open a new issue if a new problem comes up, thank you!

Thanks for the work and update,
I'm a bit puzzled by the answer. What difference does it make to upload the dSYM with the Crashlytics web interface if the dSYM contains obfuscated symbols? Building with `--split-debug-info` will generate a `app.ios-arm64.symbols`. Does this need to be uploaded to Crashlytics somehow?
Thank you.

**Comment by themiswang** [comment]
Hey @agonzalezpuerta,

1. For the first question, a short answer, there are two sections within dSYM file that contain symbol information. Web interface use a completely different section in dSYM to do symbolication compare with the `upload-symbol` run script in SDK . The section used by upload-symbol run script contains obfuscated symbol if you have `--obfuscate` build option on. The [issue](https://github.com/flutter/flutter/issues/124715) filed with flutter team might have more detailed description if you are interested to learn!
2. For the second question, Crashlytics only use dSYM files for symbolication, no need to upload `.symbol` file.

Let me know if you have other questions and happy to help :)

**Comment by alvarisi** [comment]
Hi @themiswang 
thank you for the feedback and findings.
my app is using Flutter `3.3.9` and firebase_crashlytics  `2.9.0`, and is able to generate the .symbol and dSYM file.
the question is if I require my flutter to be 3.7.0+ and firebase_crashlytics 3.1.1+?

**Comment by jonathanellis** [comment]
Having upgraded everything to the latest versions in the hope of getting this working for iOS symbols, I've now run into [this issue](https://github.com/firebase/flutterfire/issues/10994).
