### ISSUE TITLE
[OnlineStateTracker]: Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: Status{code=UNAVAILABLE, description=Unable to resolve host firestore.googleapis.com, cause=java.lang.RuntimeException: java.net.UnknownHostException: Unable to resolve host "firestore.googleapis.com": No address associated with hostname

### ISSUE THREAD

**Issue by kavyabhargava** [firebase/flutterfire#8940]
Hey guys, I am getting this error suddenly. The app was running fine . Then suddenly I opened back the emulator, I was getting this error .

It is happening for all my screens where I have integrated firebase too

**Comment by darshankawar** [comment]
This probably indicates a network connection error or a glitch at firebase server side, so I don't think Flutterfire can do anything about it.
I suggest you to look at https://github.com/firebase/firebase-android-sdk/issues for similar issue or raise it there or reach out to firebase support for further resolution. https://firebase.google.com/support/troubleshooter/contact

Closing from here, as this doesn't look like flutterfire / cloud_firestore issue.
