### ISSUE TITLE
🐛 [flutterfire_ui] Phone login fails

### ISSUE THREAD

**Issue by sgehrman** [firebase/flutterfire#8942]
![image](https://user-images.githubusercontent.com/287137/174777540-0110d3fb-1bb6-45db-85fd-27d9b4fead33.png)

**Comment by darshankawar** [comment]
@sgehrman 
Using the flutterfire_ui plugin example, I am not seeing the error you reported.
Can you provide a code sample and steps to replicate ?
Also, is this on Android or iOS ?
