### ISSUE TITLE
get() after set() with merge:true has different results between iOS and Android

### ISSUE THREAD

**Issue by apgiorgi** [firebase/flutterfire#8982]
Hi!

While debugging a customer's app, it became clear that a `get()` operation after `set()` with `merge: true` will result in different outcomes depending on the platform:
- iOS will return the fully merged document (local + server);
- **Android will return just the set() to-be-merged field (local only).**;

Important details:
- Using `.get(const GetOptions(source: Source.server))` doesn't change this behaviour.
- Adding a pause of a few seconds between `set()` and `get()` will give enough time for sync and result in the correct fully merged document.
- Doing a pre-fetch of the document before the set() will correctly get the whole document and result in a fully merged document afterwards.

I've tried tracking down what could be happing on the source code but lost my way.

Is this an expected behaviour?

Thanks!

**Comment by darshankawar** [comment]
Thanks for the report @apgiorgi 
Can you provide a complete minimal reproducible code sample that shows this behavior along with plugin version ?
