### ISSUE TITLE
🐛 [Realtime Database] Persistence cache directory directly visible to/accessible for the user on iOS

### ISSUE THREAD

**Issue by hm122** [firebase/flutterfire#8986]
## Bug report

**Describe the bug**
Currently it looks like for FirebaseDatabase, when persistence is enabled, `getApplicationDocumentsDirectory` is used to set the path for the cached data. 
On iOS, this folder is fully accessible in the "Files" app for the user. It would be better to either use `getApplicationSupportDirectory` for iOS or make the path of the cache directory dynamic.

### Steps to reproduce

Steps to reproduce the behaviour (also works in the iOS Simulator):

1. `FirebaseDatabase.instance.setPersistenceEnabled(true);`
2. Sync some data
3. Check "Files" app on iOS 

### Expected behaviour

The folder is not visible for the user and can not be accessed by the user. Either use `getApplicationSupportDirectory` for iOS or make the path of the persistence cache directory dynamic.

**Comment by Lyokone** [comment]
Hello, 
We directly use the iOS SDK for the persistence, you can raise an issue in https://github.com/firebase/firebase-ios-sdk for this feature.

**Comment by hm122** [comment]
Thanks. Raised the issue: https://github.com/firebase/firebase-ios-sdk/issues/10036
