### ISSUE TITLE
🐛 [firebase_crashlytics] not able to run the example app:`[core/duplicate-app] A Firebase App named "[DEFAULT]" already exists`

### ISSUE THREAD

**Issue by nilsreichardt** [firebase/flutterfire#8988]
## Bug report

**Describe the bug**
I'm not able to run the example app for Firebase Crashlytics.

### Steps to reproduce

1. Clone this repo
2. `cd packages/firebase_crashlytics/firebase_crashlytics/example`
4. Run `flutter run`

I used the iOS Simulator.

### Expected behavior

No errors.

### Sample project

https://github.com/firebase/flutterfire/tree/master/packages/firebase_crashlytics/firebase_crashlytics/example

---

## Additional context

```
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: [core/duplicate-app] A Firebase App named "[DEFAULT]" already exists
flutter: 
#0      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:127:11)
<asynchronous suspension>
#1      Firebase.initializeApp (package:firebase_core/src/firebase.dart:40:31)
<asynchronous suspension>
#2      main.<anonymous closure> (package:firebase_crashlytics_example/main.dart:26:5)
<asynchronous suspension>
#3      main (package:firebase_crashlytics_example/main.dart:24:3)
<asynchronous suspension>
flutter: ----------------------------------------------------
```

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.2.1 21D62 darwin-arm (Rosetta), locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc5)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[!] Android Studio
    ✗ Unable to find bundled Java version.
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.3)
[✓] VS Code (version 1.68.1)
Scanning for devices is taking a long time...[✓] Connected device (3 available)
    ! Error: iPhone von Roland is not connected. Xcode will continue when iPhone von Roland is connected. (code -13)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

---

**Comment by nilsreichardt** [comment]
@russellwheatley I looked into that but I couldn't find the issue. Even running the following code in the [`main.dart`](https://github.com/firebase/flutterfire/blob/master/packages/firebase_crashlytics/firebase_crashlytics/example/lib/main.dart) of the `firebase_crashlytics` is enough to reproduce the issue:

```dart
import 'dart:async';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'package:flutter/material.dart';

import 'firebase_options.dart';

Future<void> main() async {
  await runZonedGuarded(() async {
    WidgetsFlutterBinding.ensureInitialized();
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    runApp(const MaterialApp(home: Scaffold(body: Text('App'))));
  }, (error, stackTrace) {
    FirebaseCrashlytics.instance.recordError(error, stackTrace);
  });
}
```

**Comment by russellwheatley** [comment]
Thanks, @nilsreichardt. There's an internal ticket to go through all the examples and ensure they're working as intended. This really shouldn't happen though, as we check if already [initialized here](https://github.com/firebase/flutterfire/blob/master/packages/firebase_core/firebase_core_platform_interface/lib/src/method_channel/method_channel_firebase.dart#L66-L181) 🤔

**Comment by nilsreichardt** [comment]
Looking at the implementation of `firebase_core` that you mentioned makes it easy to find the issue: The [`GoogleServices.json`](https://github.com/firebase/flutterfire/blob/master/packages/firebase_crashlytics/firebase_crashlytics/example/ios/GoogleService-Info.plist) has different configuration than the Dart only config in [`firebase_options.dart`](https://github.com/firebase/flutterfire/blob/master/packages/firebase_crashlytics/firebase_crashlytics/example/lib/firebase_options.dart)

**Comment by nilsreichardt** [comment]
> There's an internal ticket to go through all the examples and ensure they're working as intended.

Nice! The reason I wanted to use the example was to test if there is the same issue I have in my app where the app on iOS crashes when Crashlytics wants to report an error, to make the issue reproducible. I though #8744 will fix it, but it wasn't the case. Will open a ticket for this in the days when I found information about the bug.

**Comment by nilsreichardt** [comment]
> Looking at the implementation of firebase_core that you mentioned makes it easy to find the issue: The [GoogleServices.json](https://github.com/firebase/flutterfire/blob/master/packages/firebase_crashlytics/firebase_crashlytics/example/ios/GoogleService-Info.plist) has a different configuration than the Dart only config in [firebase_options.dart](https://github.com/firebase/flutterfire/blob/master/packages/firebase_crashlytics/firebase_crashlytics/example/lib/firebase_options.dart)

Opened a PR: #8991
