### ISSUE TITLE
[cloud_firestore] FirebaseFirestore.instance.useFirestoreEmulator does not work.

### ISSUE THREAD

**Issue by lukaszciastko** [firebase/flutterfire#9001]
**** summary of issue ******

```
To sum up:

Firestore doesn't throw a meaningful error when cleartext is not enabled (as does Firebase Auth).
There is a different behaviour on iOS/macOS vs Android.

```

**********

Hi. I'm also trying to use Firebase Emulator in my project, but it doesn't work.

I am initialising Firebase passing the options (I configured Firebase using the CLI tool):

```dart
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
```

Now, when I try to enable the emulator, **the app still connects to the online production server**:

```dart
FirebaseFirestore.instance.useFirestoreEmulator('localhost', 8080);
```

I also tried the following, and, while the app doesn't connect to the online server, no requests hit the emulator:

```dart
  FirebaseFirestore.instance.settings = const Settings(
    host: 'localhost:8080',
    sslEnabled: false,
    persistenceEnabled: false,
  );
```

Another thing I tried:

```dart
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  final app = await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  final db = FirebaseFirestore.instanceFor(app: app)
    ..useFirestoreEmulator('localhost', 8080);

  // This never completes.
  final result = await db.collection('items').add({'name': 'test'});

  print(result);
}
```

It gets stuck waiting for the result - the add method never returns.

## Update

I tried to initialise Firebase Authentication to see if that works, and this time I got a meaningful error - cleartext wasn't enabled.

I added the following to my Info.plist on macOS and iOS:

```
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
```

I also enabled Outgoing Connections on macOS, and **the following setup works on both platforms**:

```dart
  final app = await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  FirebaseFirestore.instance.useFirestoreEmulator('localhost', 8080);
```

I also enabled cleartext on Android, however, the above code does not work. What does work instead is this (passing the app explicitly):

```dart
  final app = await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  final db = FirebaseFirestore.instanceFor(app: app)
    ..useFirestoreEmulator('localhost', 8080);
```

To sum up:

- Firestore doesn't throw a meaningful error when cleartext is not enabled (as does Firebase Auth).
- There is a different behaviour on iOS/macOS vs Android.

### Flutter doctor

```
[✓] Flutter (Channel stable, 3.0.3, on macOS 12.4 21F79 darwin-arm, locale
    en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2021.3.3)
[✓] VS Code (version 1.68.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

</details>

---

### Flutter dependencies

```
Dart SDK 2.17.5
Flutter SDK 3.0.3
my_app 1.0.0+1

dependencies:
- built_collection 5.1.1
- built_value 8.3.3 [built_collection collection fixnum meta]
- cloud_firestore 3.1.17 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.4
- firebase_core 1.17.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- freezed_annotation 2.0.3 [collection json_annotation meta]
```

**Comment by darshankawar** [comment]
Thanks for the detailed report @lukaszciastko 


> this time I got a meaningful error - cleartext wasn't enabled.

Can you provide complete error message for reference ?

Can you also take a look at plugin's example and see if it helps or gives same behavior ?

https://github.com/firebase/flutterfire/blob/master/packages/cloud_firestore/cloud_firestore/example/lib/main.dart

**Comment by Scott-Tenera** [comment]
I am seeing the same issue with FirebaseAuth emulator and Android. Can this be reopened?
