### ISSUE TITLE
🐛 [firebase_dynamic_links] buildShortLink returns Unhandled Exception: [firebase_dynamic_links/unknown] com.google.android.gms.common.api.ApiException: 8: 

### ISSUE THREAD

**Issue by Kravchenko1996** [firebase/flutterfire#9002]
Hello everyone!
I am using firebase_core: ^1.18.0 along with firebase_dynamic_links: ^4.2.6 (latest versions); flutter version is 2.10.5.
Method buildShortLink returns error while buildLink is generating proper dynamic link.
Here are my function and response on screenshots:
![image](https://user-images.githubusercontent.com/63616961/176629711-821daec7-3176-4be2-a5e1-c16ce90a9b02.png)
![image](https://user-images.githubusercontent.com/63616961/176629888-0b878869-1bbd-4c99-a235-185eeb71de0e.png)

**Comment by darshankawar** [comment]
This is similar to https://github.com/firebase/flutterfire/issues/7911, so please follow-up in it for further updates.
Closing as duplicate.
