### ISSUE TITLE
🐛 [firebase_analytics] `FirebaseAnalytics.setDefaultEventParameters()` should accept `Map<String, Object?>?`

### ISSUE THREAD

**Issue by ueman** [firebase/flutterfire#9005]
## Bug report

In order to reset default event parameters, you should set the corresponding key to null. In order to reset all parameters, you should pass `null`.
That's what the documentation for [Android](https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics#setDefaultEventParameters(android.os.Bundle)) and [iOS](https://firebase.google.com/docs/reference/swift/firebaseanalytics/api/reference/Classes/Analytics#setdefaulteventparameters_:) says.

> Android:
> Parameters to be added to the map of parameters added to every event. They will be added to the map of default event parameters, replacing any existing parameter with the same name. Valid parameter values are String, long, and double. Setting a key's value to null will clear that parameter. Passing in a null bundle will clear all parameters.

> iOS:
> Parameters to be added to the dictionary of parameters added to every event. They will be added to the dictionary of default event parameters, replacing any existing parameter with the same name. Valid parameters are String, Int, and Double. Setting a key’s value to NSNull() will clear that parameter. Passing in a nil dictionary will clear all parameters.

However, the Dart code only accepts `Map<String, Object>` according to the [docs](https://pub.dev/documentation/firebase_analytics/latest/firebase_analytics/FirebaseAnalytics/setDefaultEventParameters.html). 

### Steps to reproduce

1. Try to reset default event parameter

```dart
FirebaseAnalytics().setDefaultEventParameters(null); // compiler warning
FirebaseAnalytics().setDefaultEventParameters({'foo': null}); // compiler warning
```

### Expected behavior

I'm able to reset default parameter
```dart
FirebaseAnalytics().setDefaultEventParameters(null); // no compiler warning
FirebaseAnalytics().setDefaultEventParameters({'foo': null}); // no compiler warning
```

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.3, on macOS 12.4 21F79 darwin-arm, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.68.1)
[✓] Connected device (4 available)
    ! Error: iPhone-GWTGT1UTPLJQ is not connected. Xcode will continue when iPhone-GWTGT1UTPLJQ is connected. (code -13)
[✓] HTTP Host Availability

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
firebase_analytics: 9.1.9
```

</details>

---

**Comment by victor-tinoco** [comment]
It's a probably duplicated issue, related to #8861.

**Comment by ueman** [comment]
Do you mind explaining why it's possibly a duplicate?

**Comment by victor-tinoco** [comment]
Sorry, I got it wrong. Fridays 😅
