### ISSUE TITLE
🐛 [firebase_storage] Swift Compiler Error (Xcode): Concurrency is only available in iOS 15.0.0 or newer

### ISSUE THREAD

**Issue by aytunch** [firebase/flutterfire#9021]
I am using the latest Flutter Fire versions which were released 1 hour ago. You can see the pubspec.yaml in the image below
I increased iOS sdk version from 11 to 12
I am also using Invertase 9.2.0 iOS SDK version as suggested in other issues.

_App works fine in Android_

Did all cleaning, pug getting, rm Podfile.rm, pod repo update, pod update/install

If you need further info, please state.

<img width="1216" alt="Screen Shot 2022-07-01 at 18 25 33" src="https://user-images.githubusercontent.com/6442915/176924676-75573236-9881-4256-9854-e091c2b34690.png">

```
  cloud_firestore: ^3.2.1
  cloud_functions: ^3.3.1
```

<img width="1727" alt="Screen Shot 2022-07-01 at 18 24 39" src="https://user-images.githubusercontent.com/6442915/176924800-d317d7d7-8117-4bbf-a606-024d07ab5039.png">

> 
> [flutter] flutter doctor -v
> [✓] Flutter (Channel stable, 3.0.3, on macOS 12.1 21C52 darwin-x64, locale en)
>     • Flutter version 3.0.3 at /Users/aytunc/development/flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision 676cefaaff (9 days ago), 2022-06-22 11:34:49 -0700
>     • Engine revision ffe7b86a1e
>     • Dart version 2.17.5
>     • DevTools version 2.12.2
> 
> [!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
>     • Android SDK at /Users/aytunc/Library/Android/sdk
>     ✗ cmdline-tools component is missing
>       Run `path/to/sdkmanager --install "cmdline-tools;latest"`
>       See https://developer.android.com/studio/command-line for more details.
>     ✗ Android license status unknown.
>       Run `flutter doctor --android-licenses` to accept the SDK licenses.
>       See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 13.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • CocoaPods version 1.11.3
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 2020.3)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
> 
> [✓] VS Code (version 1.68.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.42.0

**Comment by aytunch** [comment]
Small update;
I saw somewhere that the issue might be related to Xcode version
Currently I am attempting to upgrade from 13.1 ==> 13.4.1
12GB download, wish me luck

**Comment by Marvioso** [comment]
> Small update; I saw somewhere that the issue might be related to Xcode version Currently I am attempting to upgrade from 13.1 ==> 13.4.1 12GB download, wish me luck

How did it go? Any success?

**Comment by aytunch** [comment]
xCode finished installing just now :(((
After installing, I did
```
pod repo update
pod update
```
And it compiled and ran in the simulator without a problem.
However the first line of debugging states this;
`2022-07-02 04:52:40.570119+0300 Runner[14241:173548] 9.2.0 - [FirebaseCore][I-COR000005] No app has been configured yet.`
and we don't fetch the usual full data from FB for some reason. I will investigate it more. At least it runs now.

@Marvioso good luck insalling xCode. I dont recommend installing xCode from App Store. So people talk about other alternatives like downloading from developer portal via link

**Comment by Marvioso** [comment]
> et.

Hey, thanks for the update. What do you mean by "we don't fetch the usual full data from FB for some reason"?

**Comment by aytunch** [comment]
After a clean install that problem never happened again @Marvioso 
Just upgrade your Xcode and use the latest FB packages + 9.2.0 ios SDK and all should be fine for now

**Comment by Marvioso** [comment]
> After a clean install that problem never happened again @Marvioso Just upgrade your Xcode and use the latest FB packages + 9.2.0 ios SDK and all should be fine for now

It works! Thanks man
