### ISSUE TITLE
🐛 [firebase_crashlytics] Handling exception in Image.network

### ISSUE THREAD

**Issue by sukhcha-in** [firebase/flutterfire#9026]
## Bug report
I'm using `Image.network` with `errorBuilder` but crashlytics is still filled with exceptions. Because of these exceptions, I'm unable to see real issues in the firebase dashboard, because thousands of exceptions are related to `Image.network` only. I would like not to get any of the `Image.network` exceptions, even if the image URL throws 404 or some other invalid status codes. Even if internet was not available at that time, it should not throw exception. I just want to show `Image.asset` if an image was not found on `Image.network`.

### Steps to reproduce
```
Image.network(
    "https://example.com/404.png",
    errorBuilder: (BuildContext context, Object exception, StackTrace? stackTrace) {
        return Image.asset("assets/noImage.png");
    },
)
```

### Expected behaviour
Crashlytics should not pick up exception because we are already handling it with "errorBuilder"

**Comment by darshankawar** [comment]
@sukhcha-in 
Can you provide `flutter doctor -v`, plugin version and the exceptions you are receiving in crashlytics ?

**Comment by darshankawar** [comment]
Thanks for the update. I see same behavior using code sample provided and logs from crashlytics.
Keeping it open and labeling for further insights from the team.

**Comment by HardyNapses** [comment]
Same here as well. We cannot tell any backing guys to update image and all because we are already handling these in error builder and we do not want that in our firebase crashlogs

**Comment by CPMoviePHil** [comment]
face same issue here

**Comment by HardyNapses** [comment]
Same here , we should not report error on firebase crashlytics if we are already handling them through image view

**Comment by sukhcha-in** [comment]
Still waiting for an update.

**Comment by hubdestro** [comment]
We are still facing this issue, waiting for update.

**Comment by russellwheatley** [comment]
Are you sure the error isn't coming from inside the `errorBuilder`? I've just tested this and it does not log the error if you actually have an asset. For illustration:

If you have this setup:

```dart
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  FlutterError.onError = (errorDetails) {
	// ERROR HANDLER THAT SENDS UNCAUGHT ERRORS TO CRASHLYTICS
    FirebaseCrashlytics.instance.recordFlutterFatalError(errorDetails);
  };
  runApp(MyApp());
```

The exception will make its way to the error handler if your asset does not exist:
```dart
Image.network(
    "https://example.com/404.png",
    errorBuilder: (BuildContext context, Object exception, StackTrace? stackTrace) {
		// THIS WILL MAKE ITS WAY TO THE ERROR HANDLER IF IT DOES NOT EXIST
        return Image.asset("assets/noImage.png");
    },
)
```

If the asset exists, no error in the error handler.

**Comment by sukhcha-in** [comment]
@russellwheatley 

I have `recordFlutterError` instead of `recordFlutterFatalError` just like documentation suggests.
```
FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterError;
```

**Comment by russellwheatley** [comment]
It doesn't matter which one you use, it has to reach `FlutterError.onError` for either `recordFlutterError` or `recordFlutterFatalError ` to be called.

**Comment by sukhcha-in** [comment]
@russellwheatley Okay! I think there is no reason to close this issue, Console is full of image errors even when using `errorBuilder`.

**Comment by russellwheatley** [comment]
Did you [read this](https://github.com/firebase/flutterfire/issues/9026?notification_referrer_id=NT_kwDOAPRsxbMzOTIyOTQ4NjU5OjE2MDE4NjI5&notifications_query=reason%3Amention#issuecomment-1267014667)?  

Please [provide a reproduction](https://stackoverflow.com/help/minimal-reproducible-example) as I can't reproduce. Preferably a github repo. Thanks.

**Comment by sukhcha-in** [comment]
@russellwheatley I have the exact code mentioned in this snippet.

**Comment by sukhcha-in** [comment]
> if you're still experiencing this problem

Yes

**Comment by darshankawar** [comment]
Reopening based on above comment and for further action.

/cc @russellwheatley

**Comment by deepak786** [comment]
I have the same issue with network images but using the CachedNetworkImage
See 
https://github.com/flutter/flutter/issues/102494

**Comment by russellwheatley** [comment]
I'm closing this out as I have already requested a reproduction which the OP has not provided. If you're seeing exceptions it is highly likely that your asset does not exist or you have not specified it in your `pubspec.yaml` as I have already explained [here](https://github.com/firebase/flutterfire/issues/9026#issuecomment-1267014667).
