### ISSUE TITLE
🐛 [firebase_auth] 3.4.1 Unable to establish connection on channel

### ISSUE THREAD

**Issue by apoleo88** [firebase/flutterfire#9028]
## Bug report

Bug presented After updating to `firebase_auth: 3.4.1` (from firebase_auth: 3.3.19)

**Describe the bug**
Tested on Android, App doesn't start stuck on the first colored splash screen.

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
#0      FirebaseCoreHostApi.initializeCore (package:firebase_core_platform_interface/src/pigeon/messages.pigeon.dart:205:7)
<asynchronous suspension>
#1      MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:29:44)
<asynchronous suspension>
#2      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:73:7)
<asynchronous suspension>
#3      Firebase.initializeApp (package:firebase_core/src/firebase.dart:40:31)
<asynchronous suspension>
#4      main (package:smartUser/main.dart:67:3)
<asynchronous suspension>
```

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.3, on Microsoft Windows [Versione 10.0.19044.1766], locale it-IT)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.3)
[√] Android Studio (version 2021.2)
[√] IntelliJ IDEA Community Edition (version 2022.1)
[√] IntelliJ IDEA Ultimate Edition (version 2022.1)
[√] VS Code (version 1.68.0)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!

```

</details>

**Comment by ajmal-edurupt** [comment]
Same issue for `  cloud_firestore: ^3.2.1` 

`E/flutter (24389): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (24389): #0      FirebaseCoreHostApi.initializeCore (package:firebase_core_platform_interface/src/pigeon/messages.pigeon.dart:205:7)
E/flutter (24389): <asynchronous suspension>
E/flutter (24389): #1      MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:29:44)
E/flutter (24389): <asynchronous suspension>
E/flutter (24389): #2      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:73:7)
E/flutter (24389): <asynchronous suspension>
E/flutter (24389): #3      Firebase.initializeApp (package:firebase_core/src/firebase.dart:40:31)
E/flutter (24389): <asynchronous suspension>
E/flutter (24389): #4      main (package:edurupt/main.dart:13:3)
E/flutter (24389): <asynchronous suspension>
E/flutter (24389): `

I had to enable multidex when I added the   cloud_firestore: ^3.2.1 package as well.

**Comment by aj-ed** [comment]
Issue fixed after upgrading all other firebase dependencies.

See https://stackoverflow.com/a/72835948

**Comment by apoleo88** [comment]
Yes, after updating everything to the last version the issue disappeared.

> Issue fixed after upgrading all other firebase dependencies.
> 
> See https://stackoverflow.com/a/72835948
