### ISSUE TITLE
 [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'Null' is not a subtype of type 'String' E/flutter ( 1180): #0      MethodChannelFirebaseAuth.verifyPhoneNumber.<anonymous closure> 

### ISSUE THREAD

**Issue by CoderAravind** [firebase/flutterfire#9032]
While initiate firebase otp this error occurs

my code 

```
 try {
      await firebaseAuth.verifyPhoneNumber(
          phoneNumber: "+91$phone",
          timeout: const Duration(seconds: 120),
          verificationCompleted: (e)async{
            try {
              await firebaseAuth.signInWithCredential(e);
            }catch(e){
              print("signin firebase code error $e");
            }
            showVerifyNumberWidget = false;
            showVerificationCodeWidget = false;
            showSuccessWidget = true;
          },
          verificationFailed: (FirebaseAuthException? authException){
            Get.back();
            print(
                'Phone number verification is failed.');

            // commonErrorPopUp(Get.context!,
            //     "Phone number verification is failed. Code: ${authException.code}\nMessage: ${authException.message}");
            commonSnackBar(
                title: "Please Check",
                msg:
                "Phone number verification is failed.");

          },
          codeSent: (e,i){
            Get.back();
            print('Please check your phone for the verification code.');
            commonSnackBar(
                title: "Please Check",
                msg: "Code Sent to ${astro_phoneNumber_controller.text}");
            // commonErrorPopUp(
            //     Get.context!, "Code Sent to ${astro_phoneNumber_controller.text}");
            if(e==null){
              print('verification id error.');
            }else{
              strVerificationId = e;
              showVerifyNumberWidget = false;
              showVerificationCodeWidget = true;
            }
          },
          codeAutoRetrievalTimeout: (e){
            try{
              print("verification code:  $e");
              showVerifyNumberWidget = false;
              showVerificationCodeWidget = false;
              showSuccessWidget = true;
            }catch(e){
              print("error on phone code retreival ");
            }
          });
    } catch (e) {
      print("Failed to Verify Phone Number: $e");
    }
```

**Comment by darshankawar** [comment]
@CoderAravind 
Are you using firebase emulator for this or physical device ?
Is this on Android or iOS ? Can you provide complete error log along with `flutter doctor -v` ?

**Comment by CoderAravind** [comment]
> @CoderAravind Are you using firebase emulator for this or physical device ? Is this on Android or iOS ? Can you provide complete error log along with `flutter doctor -v` ?

No, I am not using any emulator. Using Android device

error: [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'Null' is not a subtype of type 'String' E/flutter ( 1180): #0 MethodChannelFirebaseAuth.verifyPhoneNumber.<anonymous closure>

**Comment by darshankawar** [comment]
Can you provide `flutter doctor -v`, `pubspec.yaml` and complete minimal reproducible code sample ?

**Comment by CoderAravind** [comment]
> Can you provide `flutter doctor -v`, `pubspec.yaml` and complete minimal reproducible code sample ?
Pubspec.yaml

name: astro
description: Astro Project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 4.0.1+6

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.5.1
  permission_handler: ^8.3.0
  connectivity: ^3.0.6
  flutter_rating_bar: ^4.0.0
  line_icons: ^2.0.1
  image_picker: ^0.8.4+4
  carousel_slider:
  dots_indicator:
  flutter_svg:
  pie_chart: ^5.1.0
  date_picker_timeline: ^1.2.3
  camera: ^0.9.4+6
  path_provider: ^2.0.8
  file_picker: ^4.3.2
  image_cropper: ^1.4.1
  utility: ^1.0.1
  http: ^0.13.4
  shared_preferences: ^2.0.12
  get_storage: ^2.0.3
  intl: ^0.17.0
  pinput: ^1.2.2
  dio: ^4.0.4
  flutter_slidable: ^1.2.0
  jitsi_meet: ^4.0.0
  jitsi_meet_web_plugin: ^2.0.0
  flutter_form_builder: ^7.1.1
  introduction_screen: ^3.0.0
  simple_ripple_animation: ^0.0.3
  firebase_core: ^1.19.1
  firebase_auth: ^3.4.1
  firebase_auth_web: ^3.3.9
  firebase_core_web: ^1.6.1
  sms_autofill: ^2.2.0
  firebase_messaging: ^11.2.11
  flutter_local_notifications: ^9.4.0
  sentry_flutter: ^6.4.0
  cached_network_image:
  badges:
  photo_view:
  day_night_time_picker: ^1.0.5
  toggle_switch: ^1.4.0
  webview_flutter: ^3.0.2
  flutter_automation:
  firebase_remote_config: ^2.0.9
  package_info_plus: ^1.0.6
  url_launcher: ^6.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svgs/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages




//flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.4, on Ubuntu 20.04.4 LTS 5.13.0-52-generic, locale en_IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Android Studio
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

**Comment by CoderAravind** [comment]
This issue only we got in release mode...
In debug mode we got result successfully as below
W/System  ( 3512): Ignoring header X-Firebase-Locale because its value was null.
I/System.out( 3512): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out( 3512): (HTTPLog)-Static: isSBSettingEnabled false
I/flutter ( 3512): codeSent AJOnW4Q4wEtvgRC1WM8UXJ3_z_Hucv25weyRTc0tYDUBTBLdAnsQ3h8yfPeyXKeEvyxU5N6m9t-DmHTapkGvo8huUXNP4x8HdWOccsqbdAE7iw94Ys2aKbxPkvRAr54tZUYek6UQ0jrQJ67LZKrIWF6BH5EcKa66wJxUD9yh0-21kfem0bYaQfFzPhP7nV3NQa3KpXD9O8HBjZoX8zxlG23KQT1TpL4adjrDTdvkxXLL_auFmjxMsQk: 237420909

**Comment by darshankawar** [comment]
From your code sample, I see that you are using `get` community plugin code which is third party. Can you replicate the same error without using any third party plugin ? If so, can you provide updated code sample that is independent of any community plugins ?
