### ISSUE TITLE
[firebase_storage] my app gives error and do not open when I add this package to pubspec.yaml

### ISSUE THREAD

**Issue by ysahin20** [firebase/flutterfire#9033]
So I am building an app and I want to save some photos of the user in the firebase DB. For this purpose, i added the package however, when i add this package and run the app, the app gives error and do not open.

Here is the error;

```
E/eglCodecCommon( 2714): glUtilsParamSize: unknow param 0x000082da
E/eglCodecCommon( 2714): glUtilsParamSize: unknow param 0x000082da
E/flutter ( 2714): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 2714): #0      FirebaseCoreHostApi.initializeCore (package:firebase_core_platform_interface/src/pigeon/messages.pigeon.dart:205:7)
E/flutter ( 2714): <asynchronous suspension>
E/flutter ( 2714): #1      MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:29:44)
E/flutter ( 2714): <asynchronous suspension>
E/flutter ( 2714): #2      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:73:7)
E/flutter ( 2714): <asynchronous suspension>
E/flutter ( 2714): #3      Firebase.initializeApp (package:firebase_core/src/firebase.dart:42:31)
E/flutter ( 2714): <asynchronous suspension>
E/flutter ( 2714): #4      main (package:falabella/main.dart:31:3)
E/flutter ( 2714): <asynchronous suspension>
E/flutter ( 2714): 
```

**Comment by iandis** [comment]
For me, downgrading to `firebase_core_platform_interface` to 4.4.1 resolves the issue

**Comment by darshankawar** [comment]
> FirebaseCoreHostApi.initializeCore (package:firebase_core_platform_interface/src/pigeon/messages.pigeon.dart:205:7)

@ysahin20 What version of `firebase_core` and `firebase_core_platform_interface` are you using ?

Can you try upgrading `firebase_core` to latest and `firebase_core_platform_interface` and see if these help ?

https://pub.dev/packages/firebase_core_platform_interface/changelog

**Comment by ysahin20** [comment]
@darshankawar My firebase_core version is 1.12.0 on pubspec.yaml but i do not have the firebase_core_platform_interface. I will try adding firebase_core_platform_interface now.

**Comment by ysahin20** [comment]
Well, when i was trying to upgrade a specific plugin, i accidently upgrade all of the plugins and then the code startes without error. Most probably, the version of the firebase_core was the problem. Anyway my problem has solved. Thanks for your comments and suggestions.

**Comment by deepsan98** [comment]
Still getting this error, even if I update all firebase packages to last version, and also if I pin `firebase_core_platform_interface` to 4.4.1 (note that it is `dependency_overrides`).
