### ISSUE TITLE
🐛 [firebase_core] Android push notifications don't work with account switching, also unreliable.

### ISSUE THREAD

**Issue by ollydixon** [firebase/flutterfire#9040]
********** updated request from OP *********************

`I would suggest, just like the Js library that Flutter Firebase makes it's dart version, you will be free of the countless bugs from the native libraries that have existed for more than half a decade.`

*********************************************************

**** original post *****

We have multiple environments (like most tech teams).

Using 
```
firebase_core: ^1.19.1
firebase_messaging: ^11.4.4
```

Our QA team picks the correct environment at the start screen, switching between them, standard.
![IMG_1363](https://user-images.githubusercontent.com/6940726/177493849-6570679b-9103-4dfa-883e-23e6f732ffaa.PNG)

I have been using Firebase with various projects for more than 5 years now and this crucial feature has always sucked. We were using GCM before Firebase which was great because everything was code, and the environment didn't matter, no need for weird service.json files inside the app project!

We use the following code to switch

```
/**
 * Inits the background Firebase service which is a bridge.
 * Can be used with multiple accounts
 * If switch env then the app needs a full restart (not just hot relate)
 * Unfortuntely we are forced to use this unreliable 
 * service from Google for Push notificaitons now
 */
initPushNotifs() async {
  if (isPushNotificationsSupported() && Firebase.apps.isEmpty) {
    try {
      if (EnvironementProvider.isProd()) {
        // Prod
        await Firebase.initializeApp(
          // Class generated from Firebase plugin
          options: ProdFirebaseOptions.currentPlatform,
        );
      } else {
        // Dev and local
        await Firebase.initializeApp(
          // Class generated from Firebase plugin
          options: DevFirebaseOptions.currentPlatform,
        );
      }
      _initPushNotifications();
    } catch (e) {
      if (kDebugMode) {
        print("Failed to init push notifs");
        print(e);
      }
    }
  } else {
    if (kDebugMode) {
      print("Already init Firebase. Need to restart app completely to refresh.");
    }
  }
}
```

This works on iOS (Although sometimes it fails and you need to restart the app)

On Android this always fails no matter what. Looks like it's loading the default json file and forcing that.

This is a fairly critical feature that blocks are notification testing on Android for Flutter. I would considering that Flutter firebase becomes a dart only library with configurations loaded via code and not file.

**Comment by darshankawar** [comment]
Thanks for the report @ollydixon 
If I understand this issue correctly, when your team is selecting / switching to an environment and triggering a push notification, it isn't getting triggered or not getting delivered in selected env ?

From the code you shared, I see that you are using flavored / customized `FirebaseOptions`, which I am not completely sure if flutterfire configure CLI tool supports it or not.

Does the push notifications work correctly and consistently  if you stay on one environment only and behaves inconsistently only while switching to different env ?

Is there a way for you to check / test this behavior without using `FirebaseOptions` on Android and use traditional flavored app ?

**Comment by ollydixon** [comment]
@darshankawar it's in the example project and docs, can't find them again (so many docs that go no where 🙈)

It works consistently on iOS. On Android the native library is loading the .json config and locking to it.

This is a fairly critical feature and something that developers hate about Firebase, the lack of env switching is really bad for Devs and QA teams.

**Comment by darshankawar** [comment]
> the lack of env switching is really bad for Devs and QA teams.

I think this all comes down to / similar to https://github.com/firebase/flutterfire/discussions/5626 for which I am not completely sure if this falls under flutterfire or with native firebase sdks, I am guessing the latter because that way Flutterfire can levarage the implementation. I suggest you to open an issue https://github.com/firebase/firebase-android-sdk/issues and also reach out to [firebase support](https://firebase.google.com/support).

**Comment by ollydixon** [comment]
@darshankawar yes we are now forced to use Firebase as mobile developers because Google has ditched GCM and forces us to use FCM which is horrible especially given that environmental support barely works.

I would suggest, just like the Js library that Flutter Firebase makes it's dart version, you will be free of the countless bugs from the native libraries that have existed for more than half a decade.

**Comment by darshankawar** [comment]
> just like the Js library that Flutter Firebase makes it's dart version,

you may open a new issue as an enhancement so that we can track it properly.

For your current issue, as I suggested earlier, 

> to open an issue https://github.com/firebase/firebase-android-sdk/issues and also reach out to [firebase support](https://firebase.google.com/support).

**Comment by darshankawar** [comment]
should be ok, but you may need to update your original description to reflect what `enhancement` you would like to propose, accordingly I'll update the status of this issue.
Thanks.

**Comment by ollydixon** [comment]
@darshankawar it’s already explained in the ticket ☺️

**Comment by russellwheatley** [comment]
Hey @ollydixon, we tried to go down the route of dart initialization, but this caused problems as some of the Firebase products for native platforms (out of the control of FlutterFire) still rely on having the service file available . This is why we now write the service files for iOS, android & macOS when you use the FlutterFire CLi (`flutterfire configure`). We're looking to support multiple environments using the FlutterFire CLI ([see this issue](https://github.com/invertase/flutterfire_cli/issues/14)) which would involve writing service files for different environments.
