### ISSUE TITLE
🐛 [App Check] App Check Returns Same Token Value

### ISSUE THREAD

**Issue by sithu-aung** [firebase/flutterfire#9050]
## Bug report

App Check Returns Same Token Value of "eyJlcnJvciI6IlVOS05PV05fRVJST1IifQ==" in getToken Function.

### Steps to reproduce

1. Even using flutter app check example code make getToken() function return same value.
### Sample project

https://pub.dev/packages/firebase_app_check/example

--

### Flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.4 21F5058e darwin-arm, locale en-MM)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[!] Android Studio
    ✗ Unable to find bundled Java version.
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.68.1)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.

**Comment by sithu-aung** [comment]
Yes @darshankawar . Please let me know if you found any fix or trick to this issue.

**Comment by KoheiKanagu** [comment]
A different token might be generated if the apk is signed by the Google PlayStore.
https://github.com/firebase/flutterfire/discussions/7998#discussioncomment-2815263

**Comment by ousanjp** [comment]
I have the same problem on Android, but when using the **DebugAppCheckProviderFactory** and **debug token**, I can get the normal token.

**Comment by letthewookieewin** [comment]
I ran into the same problem and this fixed it for me: https://stackoverflow.com/a/73330541/4595843

@sithu-aung @darshankawar

**Comment by russellwheatley** [comment]
Please use the latest API for activating app check: https://github.com/firebase/flutterfire/pull/9646.  In any event, the same token being returned is coming from the native SDK, so I'd assume it is a user setup issue.

**Comment by letthewookieewin** [comment]
> Please use the latest API for activating app check: #9646. In any event, the same token being returned is coming from the native SDK, so I'd assume it is a user setup issue.

Thank you!
