### ISSUE TITLE
🐛 firebase_core_platform_interface Error on launch makes app stuck on launch screen

### ISSUE THREAD

**Issue by marnberg** [firebase/flutterfire#9056]
## Bug report
Crashlytics updated firebase_core_platform_interface to 4.4.1 to 4.4.3 and this broke our app 
It builds fine on both Intel and Apple Silicon Macs.
On apks and ipas built with Apple Silicon works fine but if built with Intel the app size is smaller and does not launch correctly. 
It gets stuck on 
  await Firebase.initializeApp();
and the log output is:

`07-07 11:39:49.411 13563 13612 E flutter : [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
07-07 11:39:49.411 13563 13612 E flutter : Warning: This VM has been configured to produce stack traces that violate the Dart standard.
07-07 11:39:49.411 13563 13612 E flutter : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-07 11:39:49.411 13563 13612 E flutter : pid: 13563, tid: 13612, name 1.ui
07-07 11:39:49.411 13563 13612 E flutter : build_id: 'aed21ea82df6148fa452a69e0933a7c4'
07-07 11:39:49.411 13563 13612 E flutter : isolate_dso_base: 783c2c5000, vm_dso_base: 783c2c5000
07-07 11:39:49.411 13563 13612 E flutter : isolate_instructions: 783c5c9d70, vm_instructions: 783c5c5000
07-07 11:39:49.411 13563 13612 E flutter :     #00 abs 000000783cc6bccb virt 00000000009a6ccb _kDartIsolateSnapshotInstructions+0x6a1f5b
07-07 11:39:49.411 13563 13612 E flutter : <asynchronous suspension>
07-07 11:39:49.411 13563 13612 E flutter :     #01 abs 000000783cc6d067 virt 00000000009a8067 _kDartIsolateSnapshotInstructions+0x6a32f7
07-07 11:39:49.411 13563 13612 E flutter : <asynchronous suspension>
07-07 11:39:49.411 13563 13612 E flutter :     #02 abs 000000783cc6c5ef virt 00000000009a75ef _kDartIsolateSnapshotInstructions+0x6a287f
07-07 11:39:49.411 13563 13612 E flutter : <asynchronous suspension>
07-07 11:39:49.411 13563 13612 E flutter :     #03 abs 000000783cc6de9b virt 00000000009a8e9b _kDartIsolateSnapshotInstructions+0x6a412b
07-07 11:39:49.411 13563 13612 E flutter : <asynchronous suspension>
07-07 11:39:49.411 13563 13612 E flutter :     #04 abs 000000783cdbd783 virt 0000000000af8783 _kDartIsolateSnapshotInstructions+0x7f3a13
07-07 11:39:49.411 13563 13612 E flutter : <asynchronous suspension>
07-07 11:39:49.411 13563 13612 E flutter : 
`
Pinning the 
firebase_core_platform_interface to version 4.4.1 fixes issue. 

### Steps to reproduce

1. Include latest Crashlytics in app with firebase_core_platform_interface 4.4.3
2. Build apk or ipa with an Intel based mac.
3. run application.
4. see error output included above.

### Expected behavior

Should launch.

### Sample project

Flutter create and include Crashlytics

### Flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.4, on macOS 11.6 20G165 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2020.3)
[✓] Connected device (1 available)
[✓] HTTP Host Availability

### Flutter dependencies

proprietary info

**Comment by darshankawar** [comment]
Can you try [this](https://github.com/firebase/flutterfire/issues/9033#issuecomment-1175249144) solution and see if it works for you ?
