### ISSUE TITLE
Query parameters not being passed back in Dynamic Link Data when using sendPasswordResetEmail function

### ISSUE THREAD

**Issue by AdamMoroff75** [firebase/flutterfire#9061]
### Discussed in https://github.com/firebase/flutterfire/discussions/9025

<div type='discussions-op-text'>

<sup>Originally posted by **AdamMoroff75** July  2, 2022</sup>
Hi all,
I was hoping somone could help me with an issue Im facing using Firebase Dynamic Links.  Im raising this as a question first, rather than an issue because Im hoping its just me missing something rather than an actual bug.

**What am I trying to do?**
I am trying to use Dynamic Links to allow a user to reset their password by clicking a Dynamic Link from an email which is sent to the user using the  `FirebaseAuth.instance.sendPasswordResetEmail` function.   Refer [https://firebase.google.com/docs/auth/flutter/manage-users#send_a_password_reset_email](https://firebase.google.com/docs/auth/flutter/manage-users#send_a_password_reset_email)

**Whats the problem?**
When the `sendPasswordResetEmail` is executed it generates a number of addtional query parameters such as `method, oobCode, continueUrl` amongst others.   When the email is sent to the user it contains the dynalic link domain, android package name and the query parameters that are generated by the sendPasswordResetEmail, so far, so good.   See below.

![image](https://user-images.githubusercontent.com/84904483/176988503-391c0dcf-2d74-4f84-a42b-32b38dd6960b.png)

The problem is when the user clicks the link, the only data that is passed to the app is the deeplink and the API key, **the other query parameters are missing or not passed in (ie, the oobCode, method and continueURL are not passed in.**.  See below.  This is preventing me from actually redirecting the user to the password reset page in my mobile app. 

![image](https://user-images.githubusercontent.com/84904483/176988749-0e3ba740-cbca-4bf1-9b67-c6f60c57652b.png)

**What are the steps to recreate the problem?**
1. Modify AndroidManifest.XML to enable deep linking
```<!-- Deep linking -->
            <meta-data android:name="flutter_deeplinking_enabled" android:value="true" />
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="https" android:host="tastelikehome1.page.link" />
```

2. Add code to handle incoming deep links from the terminated state and background state.  Refer [https://firebase.google.com/docs/dynamic-links/flutter/receive]()

```
 void _initDynamicLink() async {
    FirebaseDynamicLinks.instance.onLink.listen((dynamicLinkData) async {
      print('The link is: ' + dynamicLinkData.link.toString());
      print('The path is: ' + dynamicLinkData.link.path);
      print('The query is: ' + dynamicLinkData.link.query);

      //check to see if the user is logged in
      Navigator.pushNamed(context, dynamicLinkData.link.path);
    }).onError((error) {
      print('Error whilst processing a deep link');
    });

    // Get any initial links
    PendingDynamicLinkData? initialLink =
        await FirebaseDynamicLinks.instance.getInitialLink();

    if (initialLink != null) {
      final Uri deepLink = initialLink.link;
      print('The link is: ' + deepLink.toString());
      print('The path is: ' + deepLink.path);
      print('The query is: ' + deepLink.query);
      if (!mounted) return;
      Navigator.pushNamed(context, deepLink.path);
    }
  }
```
4. When the user clicks the 'Forgot my password' button in the app, the user is taken to a screen to enter their email address, when the user clicks the 'Reset my password' button the following code is executed which programmatically creates a dynamic link, then I created an ``ActionCodeSettings`` object then finally I execute the `FirebaseAuth.instance.sendPasswordResetEmail(email: _email, actionCodeSettings: actionCodeSettings);` with the settings and email address.

```
 Future<void> _sendResetPasswordEmail() async {
    setState(() {
      _isLoading = true;
    });
    final isValid = _form.currentState!.validate();
    if (!isValid) {
      setState(() {
        _isLoading = false;
        return;
      });
    }
    _form.currentState!.save();

    try {
//build alink
      final dynamicLinkParams = DynamicLinkParameters(
        link: Uri.parse(
            "https://tastelikehome.com.au/resetpassword?email=$_email"),
        uriPrefix: "https://tastelikehome1.page.link",
        androidParameters:
            const AndroidParameters(packageName: "au.com.tasteslikehome"),
      );
      final dynamicLink =
          await FirebaseDynamicLinks.instance.buildShortLink(dynamicLinkParams);

      final actionCodeSettings = ActionCodeSettings(
          url: "https://tastelikehome.com.au/resetpassword?email=$_email",
          handleCodeInApp: true,
          androidInstallApp: true,
          dynamicLinkDomain: 'tastelikehome1.page.link',
          androidPackageName: "au.com.tasteslikehome");

      print('Sending to email: ' + _email);
      await FirebaseAuth.instance.sendPasswordResetEmail(
          email: _email, actionCodeSettings: actionCodeSettings);
    } on FirebaseAuthException catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Incorrect email'),
        ),
      );
      print('Error with sending reset password email: ${e.message}');
    }
    setState(() {
      _isLoading = false;
    });
  }
```

5. The user receives an email with the dynamic link.  
![image](https://user-images.githubusercontent.com/84904483/176989172-9900adf9-4bb1-457f-86f0-2526c7c3849d.png)

6. After clicking the link the app opens and is processed by the code in Step 2 above, but the query paramaters from the deep link **are NOT passed in**.  

Am I Missing something here - why is the API Key the only query parameter being passed in?  

Any help would be greatly appreciated.

Adam
</div>

**Comment by darshankawar** [comment]
Thanks for the report @AdamMoroff75 . I think your case seems similar to https://github.com/firebase/flutterfire/issues/8842 so please check that and confirm. If so, we can track this in linked issue.

**Comment by AdamMoroff75** [comment]
Hi @darshankawar - yes I think this is a similar issue.

**Comment by darshankawar** [comment]
Thanks for confirming. Closing this in favor of https://github.com/firebase/flutterfire/issues/8842. Please follow-up in it for further updates.
