### ISSUE TITLE
[flutterfire_ui] Social media failing on RegisterScreen

### ISSUE THREAD

**Issue by kevin-induro** [firebase/flutterfire#9064]
## Bug report

This was previously reported in https://github.com/firebase/flutterfire/issues/8219

I don't have much to add to the bug beyond what was initially reported. 

### Steps to reproduce

I experienced this while working with Google Sign In, but it should how true to anything using the AuthFlow class.
1. Download the [FlutterFire UI example](https://github.com/firebase/flutterfire/tree/master/packages/flutterfire_ui/example).
2. Update project with the appropriate Firebase/Google Sign In configurations
3. Sign In works as expected, Register Shows "An unknown error occurred"

### Expected behavior

This depends on how we want to semantically consider things. On one hand, you could consider that `AuthAction.signIn` and `AuthAction.signUp` should be the same thing in these cases because there is no difference in implementation.

On the other hand, you could argue that they are different. In that case, either we could continue to block signup, or we could implement a signup. If we continue to block signup, that necessitates a change to the RegisterScreen - it shouldn't present the social options if they're always going to error.

### Sample project

https://github.com/firebase/flutterfire/tree/master/packages/flutterfire_ui/example

**Comment by darshankawar** [comment]
@kevin-induro 
Thanks for the report. I tried the flutterfire_ui example using latest flutter master version and ran it on iphone simulator with which I was able to register properly as shown below:

<img width="358" alt="Screenshot 2022-07-11 at 1 23 31 PM" src="https://user-images.githubusercontent.com/67046386/178215968-a941b95f-172b-4932-b9e2-7b0bb1aa74c5.png">

In your case, is it happening on Android or iOS ?

**Comment by darshankawar** [comment]
Thanks for the update. After I updated the plugin example with my configuration, ie, app name and firebaseOptions and running on Android, I am seeing same behavior as reported. The sign-in is working as expected, but with Register, it seems to be throwing `an unknown error occured`.

**Comment by ronnicknachok** [comment]
This is quite a big annoying bug preventing apps from passing reviews in the AppStore. Any chance we can get the progress of this? @darshankawar @lesnitsky or how can I be of help to help sort out this bug as it affects all the federated social logins including Apple Sign In etc.
