### ISSUE TITLE
firebaseMessagingInstance.getToken() gives error when system date time is changed

### ISSUE THREAD

**Issue by arav121** [firebase/flutterfire#9074]
## Bug report

**Describe the bug**
If i manually change the system date time to a previous date and run the app , fcm getToken function gives error.
The problem usually occurs when token is fetched for the first time.
The stack trace is described below - >

```
flutter (30260): [firebase_messaging/unknown] java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: FIS_AUTH_ERROR
I/flutter (30260): #0      MethodChannelFirebaseMessaging.getToken
package:firebase_messaging_platform_interface/…/method_channel/method_channel_messaging.dart:229
```

### Steps to reproduce
1. Change the system date time (1-2 months back).
2. Install the app.
3. Try calling the function getToken of firebase messaging manager.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

[✓] Flutter (Channel unknown, 2.10.5, on macOS 12.1 21C52 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.69.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

</details>

---

### Flutter dependencies

Pubspec dependency version-> 

 firebase_messaging: 10.0.5

---

**Comment by darshankawar** [comment]
@arav121 
Can you try the same scenario by upgrading framework version to latest stable (3.0.4) and also using latest plugin [version](https://pub.dev/packages/firebase_messaging/changelog#1144) and see if the error still persists or not ?

**Comment by arav121** [comment]
yes, it is happening in the latest version as well

**Comment by darshankawar** [comment]
@arav121 
I tried with firebase_messaging plugin example on iOS simulator and changed the machine's datetime to June 1st and then tried generating token which was properly generated and didn't get the error you reported.

```
Launching lib/main.dart on iPhone 13 in debug mode...
Running Xcode build...
Xcode build done.                                           14.6s
remote notifications are not supported in the simulator
Debug service listening on ws://127.0.0.1:50698/ucZm1XlPUk4=/ws
Syncing files to device iPhone 13...
flutter: Token monitor set null
flutter: FCM Token: enra2hI9LEePnMFqHJyjD4:APA91bEatYNrO3swZXL9IQACf8BadSpDbhOsxJx4gU_rrCo-9VYL1DSRrc3dZxXB8LgiCzcTJ29aUGSW9VNgh7c_AJOpsPvIqB1uqPihtbSs0p2dMQwg7it73WswARghD8Hm36pt4XwM
flutter: Token monitor set null
[VERBOSE-2:profiler_metrics_ios.mm(203)] Error retrieving thread information: (os/kern) invalid argument
flutter: Before: enra2hI9LEePnMFqHJyjD4:APA91bEatYNrO3swZXL9IQACf8BadSpDbhOsxJx4gU_rrCo-9VYL1DSRrc3dZxXB8LgiCzcTJ29aUGSW9VNgh7c_AJOpsPvIqB1uqPihtbSs0p2dMQwg7it73WswARghD8Hm36pt4XwM
flutter: After: enra2hI9LEePnMFqHJyjD4:APA91bEatYNrO3swZXL9IQACf8BadSpDbhOsxJx4gU_rrCo-9VYL1DSRrc3dZxXB8LgiCzcTJ29aUGSW9VNgh7c_AJOpsPvIqB1uqPihtbSs0p2dMQwg7it73WswARghD8Hm36pt4XwM
```

Can you provide exact steps to replicate along with which platform you see this error on ? (android or ios) ?

**Comment by arav121** [comment]
The exact steps to replicate  are ->
1. Uninstall previous build if present.
2. Change the date to 10th May.
3.  Install the build again.
4. Then after logging in , error comes in both android and iOS devices (not tested on simulator) while generating the token, but the error message is different in case of iOS  . For that, the stack trace is  ->


flutter: [firebase_messaging/unknown] An SSL error has occurred and a secure connection to the server cannot be made.
flutter: 
#0      MethodChannelFirebaseMessaging.getToken (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:229:7)

**Comment by darshankawar** [comment]
Thanks for the update. I verified this on iOS by running firebase_messaging example using latest master. Changed machine's system date to June 01 and then ran the app which gave me below error in the console log:

<details>
<summary> console error log </summary>

```

Launching lib/main.dart on iPhone 13 in debug mode...
Running Xcode build...
Xcode build done.                                           15.2s
remote notifications are not supported in the simulator
Debug service listening on ws://127.0.0.1:54768/_VsKF5hiG28=/ws
Syncing files to device iPhone 13...
flutter: Token monitor set null
FLTFirebaseMessaging: An error occurred while calling method Messaging#getToken, errorOrNil => {
    NSErrorClientCertificateStateKey = 0;
    NSErrorFailingURLKey = "https://device-provisioning.googleapis.com/checkin";
    NSErrorFailingURLStringKey = "https://device-provisioning.googleapis.com/checkin";
    NSErrorPeerCertificateChainKey =     (
        "<cert(0x7fa603109c00) s: upload.video.google.com i: GTS CA 1C3>",
        "<cert(0x7fa60310a600) s: GTS CA 1C3 i: GTS Root R1>",
        "<cert(0x7fa603109400) s: GTS Root R1 i: GlobalSign Root CA>"
    );
    NSLocalizedDescription = "An SSL error has occurred and a secure connection to the server cannot be made.";
    NSLocalizedRecoverySuggestion = "Would you like to connect to the server anyway?";
    NSURLErrorFailingURLPeerTrustErrorKey = "<SecTrustRef: 0x6000038c5a40>";
    NSUnderlyingError = "Error Domain=kCFErrorDomainCFNetwork Code=-1200 \"(null)\" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrustRef: 0x6000038c5a40>, _kCFNetworkCFStreamSSLErrorOriginalValue=-
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: [firebase_messaging/unknown] An SSL error has occurred and a secure connection to the server cannot be made.

#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
<asynchronous suspension>
#2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:499:43)
<asynchronous suspension>
#3      MethodChannelFirebaseMessaging.getToken (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:224:11)
<asynchronous suspension>

#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
<asynchronous suspension>
#2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:499:43)
<…>

```

</details>

The token doesn't load:

<img width="356" alt="Screenshot 2022-06-01 at 3 24 44 PM" src="https://user-images.githubusercontent.com/67046386/178706657-3cdfc36a-a3ea-41bc-b7dc-6aaa26aa377c.png">

But I am not sure if this is expected or intended because I don't think flutterfire has any control over machine's system date changes or how should that be tracked, so I am leaving this issue open for further insights from the team on expected behavior.

/cc @russellwheatley

**Comment by russellwheatley** [comment]
Hi @arav121, this isn't a FlutterFire issue. The error is coming from the Firebase Server. No idea what is causing it but I imagine an issue with token validation if you're changing the time on the system. It is not something I'd recommend personally.
