### ISSUE TITLE
🐛 [firebase_messaging] FirebaseMessaging.onMessageOpenedApp and FirebaseMessaging.instance.getInitialMessage() both called at same time only in iOS 15.5

### ISSUE THREAD

**Issue by jaydeep-concetto-android** [firebase/flutterfire#9077]
`FirebaseMessaging.onMessageOpenedApp` and `FirebaseMessaging.instance.getInitialMessage()` both called at same time only in iOS 15.5 when clicked on notification, working fine in android

```
FirebaseMessaging.onMessageOpenedApp.listen((message) async {
      //_onLaunchNotification(message);
    });
```

    FirebaseMessaging.instance
        .getInitialMessage()
        .then((RemoteMessage? message) async {
      if (message != null) {
       // _onLaunchNotificationFromTerminateState(message);
      }
    });

**Comment by darshankawar** [comment]
Thanks for the report @jaydeep-concetto-android 
Can you provide `flutter doctor -v`, plugin version and complete minimal reproducible code ?

**Comment by jaydeep-concetto-android** [comment]
hello @darshankawar i am big fan of yours

`flutter doctor -v`

[✓] Flutter (Channel stable, 3.0.1, on macOS 12.1 21C52 darwin-x64, locale en-GB)
    • Flutter version 3.0.1 at /Users/concettolabs/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (8 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/concettolabs/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.69.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPhone (mobile) • f365b8cac883fc6e7f6591dd46a3469d0ca67bf7 • ios            • iOS 15.1 19B74
    • macOS (desktop) • macos                                    • darwin-x64     • macOS 12.1 21C52 darwin-x64
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

plugin version

```
firebase_messaging: ^11.4.4
firebase_core: ^1.19.1
```
```
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp();
  print("i am doing my stuff here");
}

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
  runApp(const MyApp());
}
```
and this is my firebase messeging setup

```
@override
  void initState() {
    initFirebase();
    super.initState();
  }

Future<void> initFirebase() async {
    await FirebaseMessaging.instance
        .requestPermission(
            announcement: true, carPlay: true, criticalAlert: true)
        .then((value) {
      debugPrint("Firebase status::" + value.authorizationStatus.toString());
    });

    _firebaseMessaging.getToken().then((token) {
      debugPrint("Firebase token : $token"); // Print the Token in Console
    });

    await flutterLocalNotificationsPlugin
        .resolvePlatformSpecificImplementation<
            AndroidFlutterLocalNotificationsPlugin>()
        ?.createNotificationChannel(channel);

    var initializationSettingsAndroid =
        const AndroidInitializationSettings('ic_f');

    var initializationSettingsIOS = const IOSInitializationSettings();
    var initializationSettings = InitializationSettings(
        android: initializationSettingsAndroid, iOS: initializationSettingsIOS);
    flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();
    flutterLocalNotificationsPlugin.initialize(initializationSettings,
        onSelectNotification: _onNotificationSelect);

    FirebaseMessaging.onMessage.listen((message) {
      //showNotification(message);
    });

    FirebaseMessaging.onMessageOpenedApp.listen((message) async {
      //_onLaunchNotification(message);
    });

    FirebaseMessaging.instance
        .getInitialMessage()
        .then((RemoteMessage? message) async {
      if (message != null) {
       // _onLaunchNotificationFromTerminateState(message);
      }
    });
  }
```

and `onMessageOpenedApp` and `getInitialMessage()` only being called when i click on notification but both called at same time, in iOS 15.1(iPhone 7) working fine, but not working in 15.5(iPhone XR)

**Comment by darshankawar** [comment]
Thanks for the update @jaydeep-concetto-android.

 

> in iOS 15.1(iPhone 7) working fine also working fine in android, but not working in 15.5(iPhone XR)

This is quite strange. What is the state of your app when this behavior occurs ? Is it in background or in terminated state ?

Note that, `onMessageOpenedApp` gets called when app is in background and notification is tapped, while `getInitialMessage()` is called when app is in terminated state, so I am not sure how is it possible that both these methods are getting called at the same time.

Also, per your findings, since it works on iOS 15.1 but not on 15.5, there may have been some changes at iOS level which might be affecting this behavior.

Is it possible for you to run the firebase_messaging plugin [example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example) on affected device and see if you still get same behavior ? I don't have the specific device to verify.

**Comment by jaydeep-concetto-android** [comment]
problem is with terminated state, works fine when app is in background, but when app is killed and tap on notification both `onMessageOpenedApp()` and `getInitialMessage()` is called at same time.

and yes i know that `onMessageOpenedApp()` called when app is in background, and `getInitialMessage()` called when app is killed on the tap of notification.

> Is it possible for you to run the firebase_messaging plugin [example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example) on affected device and see if you still get same behavior ? I don't have the specific device to verify.

sure will try official firebase_messaging plugin example

**Comment by darshankawar** [comment]
> problem is with terminated state, works fine when app is in background, but when app is killed and tap on notification both `onMessageOpenedApp()` and `getInitialMessage()` is called at same time.

On iOS, if the app is terminated specially by swiping away, then, per following documentation, you need to manually reopened again for background messages to start working again:

https://firebase.flutter.dev/docs/messaging/usage/

`On iOS, if the user swipes away the application from app Switcher, it must be manually reopened again for background messages to start working again.
`

**Comment by jaydeep-concetto-android** [comment]
> On iOS, if the app is terminated specially by swiping away, then, per following documentation, you need to manually reopened again for background messages to start working again

sir i am getting the notification whether it is in background or killed, my problem is if app is killed and i tap on notification both `onMessageOpenedApp()` and `getInitialMessage()` is being called at same time, if app is killed then, only` getInitialMessage()` should be called.

are you getting my point?

**Comment by darshankawar** [comment]
Thanks for the update. Did you get a chance to verify the same using plugin example ?
