### ISSUE TITLE
🐛 [cloud_firestore] Upgrading to 3.2.1 downgrades a bunch of other dependencies

### ISSUE THREAD

**Issue by larssn** [firebase/flutterfire#9078]
## Bug report

**Describe the bug**
So upgrading from `3.1.18` to `3.2.1` downgrades the following in my `pubspec.lock`:

- async: from `2.9.0` to `2.8.2`
- matcher: from `0.12.12` to `0.12.11`
- source_span: from `1.9.0` to `1.8.2`
- string_scanner: from `1.1.1` to `1.1.0`
- term_glyph: from `1.2.1` to `1.2.0`

Also, having a loose version constraint on `cloud_firestore` (`^3.0.0`) caused it to only download `3.2.0` and not `3.2.1` (which is why I tried hardcoding the version to `^3.2.1`). This is probably due to the way `dart pub` tries to minimise downgrading of deps.

**FYI `3.2.0` and the related dependencies gave me the following issue:**
https://github.com/firebase/flutterfire/issues/4997

`3.2.1` made the above issue go away.

### Steps to reproduce

I'll leave out the rest since there isn't much point.

EDIT:
I should clarify that I did a `flutter clean` between the above experiments.

**Comment by darshankawar** [comment]
Thanks for the report. I am not sure why would upgrading a plugin would downgrade others. I tried to replicate this using plugin's example, but after upgrading version to latest, I don't see any changes in `pubspec.lock` file in the example.

I also looked at affected plugin you mentioned, for example, `source_span` which doesn't seem to depend on `cloud_firestore` and vice versa.

To get more clarity on this behavior, I am keeping this issue open and labeling for further insights from the team.

/cc @russellwheatley

**Comment by larssn** [comment]
But `source_span` is in `cloud_firestore`'s dependency graph:

```
|-- cloud_firestore 3.2.1
|   |-- firebase_core_platform_interface 4.4.3
|   |   |-- flutter_test 0.0.0
|   |   |   |-- async...
|   |   |   |-- boolean_selector 2.1.0
|   |   |   |   |-- source_span...
|   |   |   |-- source_span...
```

I'm sure the rest of the downgrades are also _very_ indirect dependencies.

**Comment by larssn** [comment]
This still happens with 3.3.0:
- If I force the version to 3.3.0 I experience downgrades.
- If I have the version constraint set to ^3.0.0, the highest version it downloads is 3.2.0.

**Comment by Lyokone** [comment]
> But `source_span` is in `cloud_firestore`'s dependency graph:
> 
> ```
> |-- cloud_firestore 3.2.1
> |   |-- firebase_core_platform_interface 4.4.3
> |   |   |-- flutter_test 0.0.0
> |   |   |   |-- async...
> |   |   |   |-- boolean_selector 2.1.0
> |   |   |   |   |-- source_span...
> |   |   |   |-- source_span...
> ```
> 
> I'm sure the rest of the downgrades are also _very_ indirect dependencies.

It seems that those indirect dependencies are from flutter_test, are you running the latest version of Flutter?
Otherwise, it should be a PR in the main flutter directory.

The latest `firebase_core_platform_interface` exports a way to mock the dependency, hence the flutter_test dependency.

**Comment by Lyokone** [comment]
You can find here the source: https://github.com/flutter/flutter/blob/master/packages/flutter_test/pubspec.yaml

**Comment by larssn** [comment]
> > But `source_span` is in `cloud_firestore`'s dependency graph:
> > ```
> > |-- cloud_firestore 3.2.1
> > |   |-- firebase_core_platform_interface 4.4.3
> > |   |   |-- flutter_test 0.0.0
> > |   |   |   |-- async...
> > |   |   |   |-- boolean_selector 2.1.0
> > |   |   |   |   |-- source_span...
> > |   |   |   |-- source_span...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'm sure the rest of the downgrades are also _very_ indirect dependencies.
> 
> It seems that those indirect dependencies are from flutter_test, are you running the latest version of Flutter? Otherwise, it should be a PR in the main flutter directory.
> 
> The latest `firebase_core_platform_interface` exports a way to mock the dependency, hence the flutter_test dependency.

We have no reference to flutter_test (or any test for that matter) in our pubspec. So I don't think it's that.

We're running Flutter 3.0.5.

**Comment by Lyokone** [comment]
I'll repeat myself, but it's `firebase_core_platform_interface` that depends on flutter_test
> The latest firebase_core_platform_interface exports a way to mock the dependency, hence the flutter_test dependency.

**Comment by larssn** [comment]
Sure, but I thought you meant that we had a different version of `flutter_test` referenced, which could cause the problem, which I why I elaborated on that part.

If there's nothing actionable from your side, we can close it. I'll figure out what's going on. Just thought it was weird that upgrading one dependency would downgrade others.

**Comment by russellwheatley** [comment]
Closing as there is nothing actionable.
