### ISSUE TITLE
[Firebase Auth] UserMetadata is old anonymous user after sign-in.

### ISSUE THREAD

**Issue by codyfilatov** [firebase/flutterfire#9079]
After signing into a non-anonymous user the previously signed in anonymous user's MetaData can be seen on user.metadata. Only after the app is closed and opened again.

**Steps to reproduce**
1. Sign into anonymous user.
2. Sign into non-anonymous user.
3. Close app. Open app.
4. View user.metadata still showing previous anonymous user despite user.uid being of the non-anonymous user.

**Tracked output:**

```
*Initial sign in as anonymous.*
UserId WTYsoioHMMTIZ0Y50eJciowLiRE3
userMetaData UserMetadata(creationTime: 2022-07-11 08:21:53.762, lastSignInTime: 2022-07-11 08:21:53.762)

*Sign into non anonymous account.*
UserId OZV5fx3UnnQmw3rRwP9rEoBNXrK2
userMetaData UserMetadata(creationTime: 2022-07-11 08:20:54.979, lastSignInTime: 2022-07-11 08:22:39.799)

*After closing and reopening app. Recovered meta data is of old anonymous user with non-anonymous userid.*
UserId OZV5fx3UnnQmw3rRwP9rEoBNXrK2
userMetaData UserMetadata(creationTime: 2022-07-11 08:21:53.762, lastSignInTime: 2022-07-11 08:21:53.762)
```

I do not have sample. But this only occur if the anonymous user is not signed out. Meaning... If you call FirebaseAuth.instance.signInWithCredential(authCredential) without calling FirebaseAuth.instance.signOut() beforehand this issue will occur.

**Comment by darshankawar** [comment]
Thanks for the report @codyfilatov 
Can you provide your `flutter doctor -v` and plugin version you are using that shows this behavior ?
