### ISSUE TITLE
🐛 [UI] E-mail sign up page behaving in "LOG IN" state instead of "SIGN UP" state

### ISSUE THREAD

**Issue by BrutalCoding** [firebase/flutterfire#9083]
## Bug report

**Describe the bug**
Upon registering a new account, navigating away after successful sign up and popping back to this e-mail sign up page will confuse the page. 

This email sign up page now thinks that we're in a log in state instead of sign up, causing an issue with the UI and an issue with signing up again.
 

### Steps to reproduce

1. Visit the email log in page > now tap on `Sign up` to navigate to the sign up page
2. Complete the form with the email, password & confirm password fields
3. Hit the `SIGN UP` button to complete your registration
4. In your SignInScreen() widget, add `AuthStateChangeAction<SignedIn>`  to the `actions` property.
5. Push to a new page when this `SignedIn` event has trigged
6. Pop back to previous page. This can be done through a gesture or programmatically.
7. You are now back at the e-mail sign up page, but with log in state. 

This sign up page is now thinking that it is in the `log in` state. The primary button now says `LOG IN` instead of `SIGN UP`, and upon tapping this button it will try to sign you in instead of signing you up.

The user can fix this by going to the log in page and back to sign up, or by restarting the app of course.

### Expected behavior

Upon popping back to the sign up page, the page should either pop back to log in or (preferably) set the correct state to be sign up instead of log in.

### Screenshot
<img width="447" alt="image" src="https://user-images.githubusercontent.com/5500332/178477792-718dcc5c-9ba4-4aaa-b96e-ae7395aaf6a9.png">

**Comment by darshankawar** [comment]
Thanks for the detailed report. Using the plugin example and making changes as mentioned above in steps to replicate, I am seeing same behavior as reported.

**Comment by lesnitsky** [comment]
This should be configured on app-level routing and is not the responsibility of the `firebase_ui_auth` library.
For example, you can use [go_router](https://pub.dev/documentation/go_router/latest/topics/Redirection-topic.html) and use `redirect:` as per [documentation](https://pub.dev/documentation/go_router/latest/topics/Redirection-topic.html), so essentially each screen should have it's own route guard, checking for the authentication state and redirecting to the appropriate screen.
