### ISSUE TITLE
🐛 [cloud_firestore/internal] If you see one of these errors, something is very broken

### ISSUE THREAD

**Issue by frank06** [firebase/flutterfire#9100]
## Bug report

FirebaseException: [cloud_firestore/internal] Internal errors. Means some invariants expected by underlying system has been broken. If you see one of these errors, something is very broken.

### Steps to reproduce

It was automatically reported by one of our users' app.

### Expected behavior

That your code is not broken.

### Sample project

No

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

No access to user's device.

**Comment by darshankawar** [comment]
Thanks for the report. Looking at the error, it seems to be coming from Firebase itself and not exactly from flutterfire, so I suggest you to reach out to [firebase support](https://firebase.google.com/support) for further resolution.
Closing from here. If you disagree, write in comments and I'll reopen it.
