### ISSUE TITLE
🐛 [firebase_core] Outdated Android BoM version causes Authentication errors

### ISSUE THREAD

**Issue by bhumkong** [firebase/flutterfire#9107]
## Bug report

**Describe the bug**
As seen [here](https://github.com/firebase/flutterfire/blob/master/packages/firebase_core/firebase_core/android/gradle.properties), `firebase_core` depends on BoM 30.1.0. It contains Authentication plugin version which suffers from OutOfMemoryError and related errors. Here is [the resolved issue](https://github.com/firebase/firebase-android-sdk/issues/3617) for `firebase-android-sdk`, and here is [a closed issue](https://github.com/firebase/flutterfire/issues/8444) for Flutter. While the Flutter issue is closed, people are still experiencing related [errors](https://github.com/firebase/firebase-android-sdk/issues/3617#issuecomment-1184632217) because as you can see [here](https://firebase.google.com/support/release-notes/android#auth_v21-0-6), Authentication crashes are fixed in BoM 30.2.0.

### Steps to reproduce

It's hard to reproduce, but you can see the evidence in the issues mentioned above.

### Solution

Bump Firebase Android SDK to 30.2.0 or later in `firebase_core`;
Bump the minimum version of `firebase_core` in `firebase_auth`'s pubspec.yaml to the version containing this fix.

**Comment by darshankawar** [comment]
Thanks for the report.

/cc @russellwheatley

**Comment by hukusuke1007** [comment]
When will it be released? We're getting crash reports from users.

**Comment by russellwheatley** [comment]
This will be gettin release tomorrow. [See this PR](https://github.com/firebase/flutterfire/pull/9161)

**Comment by Lyokone** [comment]
It was released yesterday so I'm closing this
