### ISSUE TITLE
[firebase_crashlytics] add `instanceFor(FirebaseApp app)` method in FirebaseCrashlytics

### ISSUE THREAD

**Issue by thomas-stockx** [firebase/flutterfire#9109]
### Discussed in https://github.com/firebase/flutterfire/discussions/8920

<div type='discussions-op-text'>

<sup>Originally posted by **wferem1** June 16, 2022</sup>
I'm building an application where we have different backend stages (development, testing, production, ...), which I want to access and switch to in the application. 
For each of these stages, there is a firebase project, and when we switch stage, I want to switch to that firebase project for crashlytics, so that we can keep the error reporting separated for these stages.

My proposal is to add the static method to FirebaseCrashlytics
```dart
static FirebaseCrashlytics instanceFor({
    FirebaseApp? app,
 })
```
so that I can specify which Firebase project I can send Error logs to</div>

This is related to https://firebase.flutter.dev/docs/core/usage#secondary-firebase-apps

`Some FlutterFire plugins allow the usage of secondary Firebase apps, letting you interchange the project the plugin uses. Currently, the Firebase SDKs provide functionality for using secondary apps with the following services:

Authentication.
Realtime Database.
Cloud Firestore.
Cloud Functions.
Cloud Storage.
Instance ID.
ML Kit Natural Language.
ML Kit Vision.
Remote Config.`

Crashlytics is currently not supported in this manner.

**Comment by russellwheatley** [comment]
Crashlytics on native platforms only support initializing with the default app instance I'm afraid.
