### ISSUE TITLE
🐛 [firebase_analytics] How to enable  real-time DebugView in flutter

### ISSUE THREAD

**Issue by shuimunianhua99** [firebase/flutterfire#9112]
There is no method to enable real-time DebugView in the flutter documentation, only the method of opening java. Currently using firebase_analytics, it is too difficult to see real-time data. If there is a method, please tell me, if not, please add it in flutter.

**Comment by darshankawar** [comment]
@shuimunianhua99 
Are you looking to have it enabled for web or for mobile ?
If it is for web, then you can do it by opening chrome dev tools console and turn on enable debug view logging. 
See if that helps and answers your question.
