### ISSUE TITLE
Critical issues have been reported with the following SDK versions: com.google.android.gms:play-services-safetynet:17.0.0 firebase_auth package

### ISSUE THREAD

**Issue by jMureByon** [firebase/flutterfire#9119]
Firebase_auth package: 
The developer of play-services-safetynet (com.google.android.gms:play-services-safetynet) has reported critical issues with version 17.0.0. Consider upgrading before publishing a new release.

Here's what the SDK developer told us: The SafetyNet Attestation API is being discontinued and replaced by the new Play Integrity API. Begin migration as soon as possible to avoid user disruption. The Play Integrity API includes all the integrity signals that SafetyNet Attestation offers and more, like Google Play licensing and better error messaging. Learn more and start migrating at https://developer.android.com/training/safetynet/deprecation-timeline

Hi while attempting to publish our app to play store we recieved this critical error. Seems safety net is used in this package attempting to upgrade the package led to same error but with version 18.0.0. Not sure if this is getting worked on in next release and what solutions we can use to remedy in the meantime. Have also found others facing the issue in stackverflow in link below
https://stackoverflow.com/questions/72904471/reported-critical-issues-with-version-17-0-0-google-play-warning
![image](https://user-images.githubusercontent.com/95635465/179350971-2a9834e6-2783-43d4-90c6-2a02c03c684e.png)

**Comment by darshankawar** [comment]
@jMureByon 
This issue need to be handled and fixed by native firebase sdk itself, so flutterfire plugins can't do much about it.
There's similar issue open in android firebase sdk github in which you can follow-up for further updates: https://github.com/firebase/firebase-android-sdk/issues/3890

Closing from here.
