### ISSUE TITLE
Migrate packages into submodules to allow developers to tweak the packages like [flutterfire_ui](https://github.com/firebase/flutterfire/tree/master/packages/flutterfire_ui) to their liking

### ISSUE THREAD

**Issue by richard457** [firebase/flutterfire#9121]
## Bug report

**Describe the bug**
I want to customize [flutterfire_ui](https://github.com/firebase/flutterfire/tree/master/packages/flutterfire_ui)  and keeping up with the main repo is impossible since this is not a standalone git repo,
### Steps to reproduce

---

## Additional context

I think migrating each packages as standalone submodule git repo will not kill the current structure but will improve the developer experience and alow us to extend packages as we want and keep the update with the main repo as well.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by richard457** [comment]
It is not a bug but a request

**Comment by darshankawar** [comment]
> I want to customize [flutterfire_ui](https://github.com/firebase/flutterfire/tree/master/packages/flutterfire_ui) and keeping up with the main repo is impossible

Can you provide an example as what customization are you looking for in the plugin ?



> I think migrating each packages as standalone submodule

Can you provide example of this as what exactly you mean by migrating each package as standalone ?

See [this](https://github.com/firebase/flutterfire/pull/8763) draft PR and check if it is similar to your request or not.

**Comment by richard457** [comment]
For example, in flutterfire_ui I want to add a carousel to the SignInScreen widget, and plus other customizations, I want to do this but am also able to keep up with updates from the upstream.

**Comment by darshankawar** [comment]
You can already customize your screens using the plugin, so I am not sure if the feature request you are proposing is feasible.
