### ISSUE TITLE
Can't use phone auth on newest version in flutter web

### ISSUE THREAD

**Issue by Ipicon** [firebase/flutterfire#9123]
Once I try to run `signInWithPhoneNumber()` I get an error:
![image](https://user-images.githubusercontent.com/43734511/179371559-a28509ac-e4a1-4373-9131-9a4709fffac7.png)
I understand the js module is getting auth as unidentified.

**Comment by cyberpwnn** [comment]
Same with signInWithPopup() #9124 `^3.4.2` busted

**Comment by Ipicon** [comment]
![image](https://user-images.githubusercontent.com/43734511/179371690-b332a749-5bc4-4c35-800d-1e5b57270e00.png)
`authExtern is unidentified`

**Comment by Faizan770gp** [comment]
Also problem with web FirebaseAuth.instance.authStateChanges(). Not Persisting user anymore instead logs back out. 
authStateChanges() returns null once the app reloads.

**Comment by darshankawar** [comment]
There's similar open issue describing this case, https://github.com/firebase/flutterfire/issues/9097
Please follow-up in it for further updates. Closing this as a duplicate.
