### ISSUE TITLE
Persisting authentication state on Flutter Web not working

### ISSUE THREAD

**Issue by visign3d** [firebase/flutterfire#9139]
The same code has AUTH persistence on Android , but not on web.  I have a simple GoogleSignIn() auth process . After browser refresh/APP restart the AUTH state is lost on web, and persisted on Android.
```
signIn() async {
    await GoogleSignIn().signIn().then((value) => googleSignInAccount = value);

    final GoogleSignInAuthentication googleAuth = await googleSignInAccount!.authentication;

    final credential = GoogleAuthProvider.credential(
      accessToken: googleAuth.accessToken,
      idToken: googleAuth.idToken,
    );

    return await FirebaseAuth.instance.signInWithCredential(credential);
  }
```

the authstate is provided by 
```
FirebaseAuth.instance.authStateChanges();
```

The FlutterFire docs says:
'The Firebase SDKs for all platforms provide out of the box support for ensuring that your user's authentication state is persisted across pp restarts or page reloads.'

plugins in pubspec:
```
firebase_core: ^1.19.2
firebase_auth: ^3.4.2
cloud_firestore: ^3.3.0
flutterfire_ui: ^0.4.2+3
google_sign_in: ^5.4.0
```

**Comment by ernysans** [comment]
Hi @visign3d. this is a duplicated issue, close this issue and follow the conversation there 👍 

https://github.com/firebase/flutterfire/issues/9089
