### ISSUE TITLE
🐛 [flutterfire_ui] deletion of a user throws an exception

### ISSUE THREAD

**Issue by gidrokolbaska** [firebase/flutterfire#9145]
## Bug report

Hello!
So I have social authentication implemented in my app (Google and Apple).
Apple reviewers required me to create a button that handles user deletion from the app.
Docs say that to delete a user you can simply call FirebaseAuth.instance.currentUser!.delete();
But sometimes it may throw the following exception:
**flutter: [firebase_auth/requires-recent-login] This operation is sensitive and requires recent authentication. Log in again before retrying this request.**
Well, the exception is straightforward and I have to reauthenticate but how do I actually call **FirebaseAuth.instance.currentUser!.reauthenticateWithCredential(_credential_);** when _credential_ is not exposed by flutterfire_ui?

### Expected behavior

A clear way to reauthenticate the user signed in with Apple/Google using flutterfire_ui

### Flutter doctor

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1468, on macOS 12.1 21C52 darwin-arm, locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.69.1)
[✓] Connected device (3 available)
    ! Error: iPhoneAndrey is busy: Preparing the watch for development via iPhoneAndrey. Xcode will continue when iPhoneAndrey is finished. (code -10)
[✓] HTTP Host Availability

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
> **FirebaseAuth.instance.currentUser!.reauthenticateWithCredential(_credential_);**

@gidrokolbaska Can you provide what are you passing in `credential` ?
Can you try something like below and see if it helps ?

```
await user.reauthenticateWithCredential(
  EmailAuthProvider.getCredential(
    email: user.email,
    password: password,
  ),
);
```
And then use the re-authenticated user ?

**Comment by gidrokolbaska** [comment]
> > **FirebaseAuth.instance.currentUser!.reauthenticateWithCredential(_credential_);**
> 
> @gidrokolbaska Can you provide what are you passing in `credential` ? Can you try something like below and see if it helps ?
> 
> ```
> await user.reauthenticateWithCredential(
>   EmailAuthProvider.getCredential(
>     email: user.email,
>     password: password,
>   ),
> );
> ```
> 
> And then use the re-authenticated user ?

That's the question :)  What should I pass inside the `credential`? I think this value should be available for users by default when using `flutterfire_ui`.
In any case, I've found a workaround by diving inside the code which is responsible for authentication (Apple example below):
```dart
try {
      var appleCredentials = await signIn();
      await FirebaseAuth.instance.currentUser!
      .reauthenticateWithCredential(appleCredentials);                             
      } on SignInWithAppleAuthorizationException {
//do nothing if user presses Cancel on native apple sign-in bottomsheet
        return;         
```
and the `signIn()` method looks like this, basically a copy-paste from [here](https://github.com/firebase/flutterfire/blob/1937f27817acc59dedd85a6d1e0624f49685ef5e/packages/flutterfire_ui/lib/src/auth/oauth/providers/apple_provider.dart):
```dart
Future<OAuthCredential> signIn() async {
  final rawNonce = generateNonce();
  final nonce = sha256ofString(rawNonce);

  // Request credential for the currently signed in Apple account.
  final appleCredential = await SignInWithApple.getAppleIDCredential(
    scopes: [
      AppleIDAuthorizationScopes.email,
      AppleIDAuthorizationScopes.fullName,
    ],
    nonce: nonce,
  );

  // Create an `OAuthCredential` from the credential returned by Apple.
  final oauthCredential = OAuthProvider('apple.com').credential(
    idToken: appleCredential.identityToken,
    rawNonce: rawNonce,
  );

  return oauthCredential;
}

```

So, I have to write the boilerplate code in order to re-authenticate the user. Maybe this is done by design, but for me it seems unnatural. What do you think?

**Comment by darshankawar** [comment]
Thanks for the feedback. Labeling it for further insights from the team.

/cc @lesnitsky

**Comment by lesnitsky** [comment]
@gidrokolbaska are you using a `ProfileScreen` from flutterfire_ui or have you built a custom screen?

**Comment by gidrokolbaska** [comment]
> @gidrokolbaska are you using a `ProfileScreen` from flutterfire_ui or have you built a custom screen?

Hello!
I'm using the custom screen since the default `ProfileScreen` is not what I need in my app

**Comment by lesnitsky** [comment]
there's `showReauthenticateDialog` and `DifferentMethodSignInView` that could be used to handle `requires-recent-login` error.

**Comment by gidrokolbaska** [comment]
> there's `showReauthenticateDialog` and `DifferentMethodSignInView` that could be used to handle `requires-recent-login` error.

Oh! That's exactly what I was looking for. Should be included in documentation though

**Comment by gidrokolbaska** [comment]
@lesnitsky Understood. Anyway, thanks for pointing me in the right direction, closing this issue.
Cheers.
