### ISSUE TITLE
[Dynamic_link] [iOS, Android] Receive two links in onGenerateRoute one by one - opened from Instagram Story

### ISSUE THREAD

**Issue by lalitf** [firebase/flutterfire#9148]
## Bug report

**Describe the bug**
Uploaded a dynamic link on Instagram story,
In app we use onGenerateRoute to navigate between pages, after clicking on the link on instagram story a long url 

something starting with this =  /?link= **--** &apn= **--** &isi= **--** &ibi=**--**&_osl=**--**&_**--**==_cpb=1

comes in onGenerateRoute 1st and then the actual deeplink receive on dynamicLink listner FirebaseDynamicLinks.instance.onLink.listen Actual Deeplink 

which causes opening 2 screen 
1st screen is wrong becuase Uri.dataFromString(path) give wrong Uri because of the long and wrong url
2nd screen is the right screen 

### Steps to reproduce

1. Use onGenerateRoute to navigate 
2. Upload a dynamic link in Instagram stories 
3. Open it in iOS or Android - i suggest iOS because each time i am able to reproduce
4. App will receive the two links one by one in onGenerateRoute
    a. First link will be the long one with lots of details
    b. Second is the actual deeplink - here onGenerateRoute will called from FirebaseDynamicLinks.instance.onLink.listen listener

### Expected behavior

I want to receive the deeplink only in firebase onLink listener not on directly on onGenerateRoute 

## Additional Details 
Frames in first link appear before onGenerateRoute called

<img width="867" alt="image" src="https://user-images.githubusercontent.com/107466053/179764300-d63c6a85-a81b-48a1-b889-c97088156924.png">

### Flutter doctor
```

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.3, on macOS 12.3.1 21E258 darwin-x64, locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability


```

**Comment by darshankawar** [comment]
@lalitf 
Can you provide `flutter doctor -v`, plugin version along with complete minimal reproducible code sample ?

**Comment by lalitf** [comment]
`
[✓] Flutter (Channel stable, 3.0.3, on macOS 12.3.1 21E258 darwin-x64, locale en-IN)
    • Flutter version 3.0.3 at /Users/flipitnews/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (4 weeks ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/flipitnews/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     • macOS 12.3.1 21E258 darwin-x64
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
`

**Comment by lalitf** [comment]
@darshankawar  here hope this help please let me know for anything else

```

import 'package:flutter/material.dart';

runApp(MyApp());

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
@override
  void didChangeDependencies() {
dynamic link here.
    DynamicLinkHelper.setupListener();
    super.didChangeDependencies();
  }


  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      navigatorObservers: [
      ],
      onGenerateInitialRoutes: (String path) {
       var _rt = <Route>[];

       _rt.add(CupertinoPageRoute(
                      builder: route[HOME]!,
                      settings: RouteSettings(name: HOME),
                    ));
        return _rt;
      },
      onGenerateRoute: (settings) {
        /// returning here CupertinoPageRoute() on basis of deeplink
      },
   
    );
  }
}

              
              
              
class DynamicLinkHelper {

  static handleInitLink(BuildContext context) {
    // Get any initial links
    return FirebaseDynamicLinks.instance.getInitialLink().then((initialLink) {
      if (initialLink != null) {
        final Uri deepLink = initialLink.link;
        print(deepLink.path);
        Navigator.pushNamed(context, deepLink.path);
      }
    }).onError((error, stackTrace) {
      FirebaseCrashlytics.instance.recordError(error, stackTrace);
    });
  }

  static void setupListener() {
    return FirebaseDynamicLinks.instance.onLink.listen((dynamicLinkData) {
      Navigator.pushNamed(navigatorKey.currentContext!, dynamicLinkData.link.path);
    }).onError((error, stackTrace) {
      FirebaseCrashlytics.instance.recordError(error, stackTrace);
    });
  }
}
```

**Comment by darshankawar** [comment]
Thanks for the update. 
> * Upload a dynamic link in Instagram stories
> * Open it in iOS or Android - i suggest iOS because each time i am able to reproduce

By this, do you mean open the Instagram ios or android app ?  If so, can you try by uploading or sending the dynamic link to Gmail for example and then try to open it from there and see if you get expected behavior or not ? 
With this, I am trying to figure out if this is specific to Instagram or happens with other domains or apps as well.

**Comment by lalitf** [comment]
I mean open open Instagram iOS  , and I tried with other platform gmail, WhatsApp , Facebook posts, it is working fine

**Comment by darshankawar** [comment]
> and I tried with other platform gmail, WhatsApp , Facebook posts, it is working fine

This indicates it could be an issue as how Instagram handles dynamic_links from their side and the behavior you are seeing with it may not be in FltuterFire's control. I suggest you to reach out to Firebase support for further resolution.

Closing this. If you disagree, write in comments and I'll reopen it.

**Comment by lalitf** [comment]
@darshankawar please don't close this can you add firebase dynamic label in it so they can look into it.

**Comment by darshankawar** [comment]
Check [this](https://github.com/firebase/flutterfire/issues/8926#issuecomment-1196653932) and see if it helps.

**Comment by lalitf** [comment]
haven't seen any response there its been 3 days, do we have another solution?
