### ISSUE TITLE
🐛 Firebase Dynamic Links Im Receiving the Dynamic Short Link with the passed parameters but cant access the passed paramters

### ISSUE THREAD

**Issue by omargalal199** [firebase/flutterfire#9149]
## Bug report

So Im Trying to Retreive and Store the Passed paramters from the dynamic short link created (which has the paramters im trying to access) but when im trying to do that, the paramters show up as null in the app. Ill post a snippet of the code explaining the problem

This is the Function that retreives the dynamic link if Clicked

 Future<void> retrieveDynamicLink() async {
    try {
      final PendingDynamicLinkData data =
          await FirebaseDynamicLinks.instance.getInitialLink();
      final Uri deepLink = data?.link;

//hadles the scenario if the user clicked on a dynamic link when the app is terminated
      if (deepLink != null) { 
          print("Link: ${deepLink ");  //shows : "Link: https://mywebsite.com/#/home?gCode=O70316"
          print("Link: ${deepLink .queryParameters}");  //shows : "Link: "
         

          print(deepLink .queryParameters['gCode']);  //shows: "null"

        if (deepLink.queryParameters.containsKey("gCode")) { //false always
   
          print("reached here 1");
        } else {
        

          print("reached here 2");
        }
      } else {
        //handles the scenario if a user clicked on dynamic link when the app is in the background
        FirebaseDynamicLinks.instance.onLink.listen((dynamicLinkData) {
          print("Link: ${dynamicLinkData.link}");   //shows : "Link: https://mywebsite.com/#/home?gCode=O70316"
          print("Link: ${dynamicLinkData.link.queryParameters}"); //shows : "Link: "
         

          print(dynamicLinkData.link.queryParameters['gCode']); //shows: "null"

          if (dynamicLinkData.link.queryParameters.containsKey("gCode")) { //false always
      
            print("reached here 3");
          } else {
   
            print("reached here 4");
          }
        });
  
        print("reached here 5");
      }
    } catch (e) {
      print(e.toString());
    }
  }

This Problem has been with me for 3 days and i really dont understand what is wrong, i even tried Uri.parse the Link even though it is Uri type and still the same problem. Please help me.

Thank you.

**Comment by darshankawar** [comment]
@omargalal199 
Can you check this issue and underlying comments and see if it helps in your case ? https://github.com/firebase/flutterfire/issues/1740
https://github.com/firebase/flutterfire/discussions/5579
