### ISSUE TITLE
[📚] `phone-number-already-exists` error is undocumented

### ISSUE THREAD

**Issue by spencerwilson** [firebase/flutterfire#9156]
The error `phone-number-already-exists` documented at https://firebase.google.com/docs/auth/admin/errors is not documented as possibly being thrown by `updatePhoneNumber` in firebase_auth 3.4.2: https://github.com/firebase/flutterfire/blob/firebase_auth-v3.4.2/packages/firebase_auth/firebase_auth/lib/src/user.dart#L380-L384

It would be good if this error condition was documented. AFAICT nowhere but that first link is it documented that all users must have a unique phone number.

**Comment by darshankawar** [comment]
Thanks for the report.

**Comment by russellwheatley** [comment]
This is now documented that link you pasted.
