### ISSUE TITLE
🐛 [cloud_firestore] Pagination bug on web release mode only

### ISSUE THREAD

**Issue by LiangHuangBC** [firebase/flutterfire#9166]
## Bug report

**Describe the bug**
query.startAfterDocument(lastDocSnapshot); is not working some time on release mode only. In my app, there are five pages in my firestore which can be fetched on dev mode correctly, but on release mode, there are only two pages.

### Steps to reproduce

'''
  firebase_core: ^1.19.2
  firebase_auth: ^3.4.2
  cloud_firestore: ^3.3.0
'''

Seems like latest V9.8.1 js sdk is buggy, similar issues :
#8235 
#9089 

I fixed #9089 by set persistence manually as #9117 mentioned. But after found this issue, the right thing is to roll back to previous version.

**Comment by LiangHuangBC** [comment]
I passed around by roll back to previous version in both pubspec.yaml and index.html
'''
dependencies:
  flutter:
    sdk: flutter
  # firebase_core: ^1.19.2
  firebase_core: 1.19.1
  #https://github.com/firebase/flutterfire/issues/9166
  firebase_core_web: 1.6.6
  firebase_auth: any
  cloud_firestore: any
  cloud_functions: any
  firebase_storage: any
  firebase_analytics: any
  firebase_messaging: 11.4.4
  firebase_crashlytics: any
  firebase_performance: any
  firebase_app_check: any
'''

'''
<script>window.flutterfire_web_sdk_version = '8.10.1';</script>
'''

**Comment by darshankawar** [comment]
@LiangHuangBC 
Can you provide a complete minimal reproducible code sample alongwith actual vs expected results ?
Also please provide your `index.html` where you are using latest V9.8.1 js sdk.

**Comment by LiangHuangBC** [comment]
My JS SDK is injected by dart, there is nothing in my index.html.

**Comment by darshankawar** [comment]
> Can you provide a complete minimal reproducible code sample alongwith actual vs expected results ?

**Comment by russellwheatley** [comment]
We have a release to fixing web persistence coming out today. Thanks.
