### ISSUE TITLE
[📚] missing import 

### ISSUE THREAD

**Issue by graemep-nz** [firebase/flutterfire#9171]
On this page there is a missing import
https://firebase.flutter.dev/docs/ui/auth/integrating-your-first-screen
[https://firebase.flutter.dev/docs/ui/auth/integrating-your-first-screen](https://firebase.flutter.dev/docs/ui/auth/integrating-your-first-screen)

This import is needed to get SignInScreen widget

import 'package:flutterfire_ui/auth.dart';

**Comment by darshankawar** [comment]
@graemep-nz 
The links you shared are archived and no longer maintained. You should refer below link which shows the import:

https://github.com/firebase/flutterfire/blob/master/packages/flutterfire_ui/doc/auth/integrating-your-first-screen.md#constructing-a-signinscreen-widget

Closing.
