### ISSUE TITLE
🐛 [FLUTTERFIRE] missing files firebase.json and .firebaserc when using firebase emulators

### ISSUE THREAD

**Issue by graemep-nz** [firebase/flutterfire#9172]
When following the docs to initialise a firebase project using "flutterfire configure", if you try to run the firebase emulators using the command
```
firebase emulators:start
```
it complains that firebase.json and .firebaserc files are missing from the project root folder.

I copied these two files from another project and modified the rc file

firebase.json has as below  - it allowed the emulators to run - it did report that firestore.rules file was missing though.

```
{
  "firestore": {
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json"
  },
  "emulators": {
    "auth": {
      "port": 9099
    },
    "firestore": {
      "port": 8080
    },
    "ui": {
      "enabled": true
    }
  }
}
```

**Comment by Lyokone** [comment]
Hello,
Currently `flutterfire configure` is just setting up your Flutter App.
If you want to use the emulator, you need to run `firebase init` first as stated in the documentation: https://firebase.google.com/docs/emulator-suite/connect_and_prototype

**Comment by Lyokone** [comment]
If you think that it should be a feature, you can open a new feature request on the [flutterfire_cli repo](https://github.com/invertase/flutterfire_cli/)

**Comment by graemep-nz** [comment]
The page you linked to says this
<quote> If you haven't already done so, initialize the current working directory as a Firebase project ... firebase init</>

So if you've already run flutterfire configure, you're not going to run "firebase init" because you've already initialised the project as a firebase project.

If running "firebase init" is the correct thing to do then the documentation on the following two pages should be updated to say you need to do that and at what point you do it.

https://firebase.google.com/docs/flutter/setup?platform=android
https://firebase.flutter.dev/docs/cli
