### ISSUE TITLE
[📚]explain that firebase init needs to be called

### ISSUE THREAD

**Issue by graemep-nz** [firebase/flutterfire#9173]
Refer to  https://github.com/firebase/flutterfire/issues/9172

These two pages should say that you need to call firebase init if you want to use firebase emulators

https://firebase.google.com/docs/flutter/setup?platform=android
https://firebase.flutter.dev/docs/cli

**Comment by graemep-nz** [comment]
ok I couldn't disagree more.  It's true I'm knew to firebase but I'm an experienced developer and even now I still don't know when the firebase init has to be done and it certainly seems to do a a lot of stuff that flutterfire configure has already done, plus the docs explicitly say to only do the firebase init if your project is not already a firebase app.  The fact that some docs say to do firebase init and some say to do flutterfire configure is in itself very confusing.

**Comment by darshankawar** [comment]
> The fact that some docs say to do firebase init and some say to do flutterfire configure is in itself very confusing.

Can you please provide doc link you are referring to which states these ?

**Comment by graemep-nz** [comment]
Here's one  - I followed the steps in here several times in the course of trying to get a firebase project working and I had a ton of problems 
https://firebase.google.com/docs/cli

the page is linked to from here
https://firebase.google.com/docs/flutter/setup?platform=android

Also this video doesn't say to use either of flutterfire configure or firebase init.
https://www.youtube.com/watch?v=EXp0gq9kGxI&t=2s

There's probably lots of websites that also say to do firebase init e.g.
https://www.tutorialspoint.com/firebase/firebase_deploying.htm

**Comment by darshankawar** [comment]
Ok, I also looked at Flutter's firebase codelab wherein, it doesn't say to use `firebase init`, but mentions `flutterfire configure`. https://firebase.google.com/codelabs/firebase-get-to-know-flutter#0. Maybe you can take a look at these steps and see if they help ?
