### ISSUE TITLE
how to customise localization in FlutterFire_ui ?

### ISSUE THREAD

**Issue by JosephIfergan** [firebase/flutterfire#9176]
I'm trying to customise the localization of FlutterFire_ui using the [CupertinoLocalizationFr class](https://github.com/flutter/flutter/blob/f1875d570e/packages/flutter_localizations/lib/src/l10n/generated_cupertino_localizations.dart#L3984).

So I added this class in my project but how do I add it in `localizationsDelegates: []` ?

**Comment by darshankawar** [comment]
@JosephIfergan 
Please ask this question in this ongoing discussion thread for the plugin: https://github.com/firebase/flutterfire/discussions/6978

Closing from here.
