### ISSUE TITLE
🐛 [Firebase-Core] Upgrade Android SDK version to pull in upstream bugfix

### ISSUE THREAD

**Issue by zmeggyesi** [firebase/flutterfire#9179]
In light of firebase/firebase-android-sdk#3757, the Android SDK dependency should be upgraded to the latest version (`30.3.0` as of writing), in order to pull in the fix released in that version.

I see the _change itself_ is already done, but is awaiting release, I guess? When is the next scheduled (or unscheduled) release due?

**Comment by darshankawar** [comment]
https://github.com/firebase/flutterfire/pull/9161
This should be released I think per [this](https://github.com/firebase/flutterfire/issues/9107#issuecomment-1190017204) comment.

Closing, as above links should address your question.
