### ISSUE TITLE
[📚] Web page on setting up the emulators needs updating for flutter users

### ISSUE THREAD

**Issue by graemep-nz** [firebase/flutterfire#9186]
https://firebase.google.com/docs/emulator-suite/install_and_configure
The above web page below says this
<>
If you haven't already done so, initialize the current working directory as a Firebase project, following the onscreen prompts to specify which products to use:

firebase init
</>

This needs updating for flutter users who have used "flutterfire configure" (instead of firebase init) to create their project.

According to this _archived page_ there is some conflict between the "flutterfire configure" method and the "firebase init" method so the solution for flutterfire users is probably not as simple as just calling firebase init.
https://firebase.flutter.dev/docs/migration

The "flutterfire configure" method results in two missing files that you need to have for the emulator  - firebase.json and .firebaserc.  firebase.json needs to be updated when the services being used are changed.

**Comment by darshankawar** [comment]
> The "flutterfire configure" method results in two missing files that you need to have for the emulator - firebase.json and .firebaserc. firebase.json needs to be updated when the services being used are changed.

Please file this issue in dedicated repo: https://github.com/invertase/flutterfire_cli/issues

**Comment by russellwheatley** [comment]
Thanks for filing an issue in the correct repository. Closing as there is nothing actionable for FlutterFire.
