### ISSUE TITLE
[📚] Firebase Storage SSL Certificate Verification Issue

### ISSUE THREAD

**Issue by MuhdMusab** [firebase/flutterfire#9187]
My project requires viewing images stored on Firebase Storage and my HTTP requests started to fail yesterday, with an error:

Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: self signed certificate in certificate chain(handshake.cc:393))

I have discovered that I am only able to view the images in my app when using a VPN (I am currently living in Singapore).
Also, I receive a "NET::ERR_CERT_AUTHORITY_INVALID" issue when assessing the link directly on my browser. (Attached in the screenshot below). Is there a way to fix this issue or have I not configured Firebase Storage correctly. Thank you in advance for the help!

<img width="1006" alt="Screenshot 2022-07-22 at 1 00 58 PM" src="https://user-images.githubusercontent.com/70519015/180366218-85d18d20-607f-447c-af0c-3d0c26419a08.png">

**Comment by Lyokone** [comment]
Hey, 
If you're using a custom domain, please check https://stackoverflow.com/a/37765371.
It doesn't seem related to FlutterFire tho, so I'll close this.
