### ISSUE TITLE
🐛 [firebase_messaging] Unable to install pod on while executing on iOS

### ISSUE THREAD

**Issue by Adithyan2295** [firebase/flutterfire#9191]
## Bug report

While executing pod install the following error is shown -

[!] CDN: trunk Repo update failed - 56 error(s):
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/6.2.0/Firebase.podspec.json Response: Timeout was reached

### Steps to reproduce

1. change directory to the iOS folder of the app
2.  run pod install
4. See error or incorrect behavior

![Screenshot 2022-07-22 at 5 05 09 PM](https://user-images.githubusercontent.com/94591962/180431138-7069c4e0-130d-4604-b49d-3a3cb4626ee7.png)

Cocoapods provided a temporary solution - https://github.com/CocoaPods/CocoaPods/issues/11355.
But it is time consuming sometimes as it have a delay while downloading pod file.

### Flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.3.1 21E258 darwin-arm, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.69.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!

</details>

---

### Flutter dependencies

Dart SDK 2.17.6
Flutter SDK 3.0.5
crashlitics 1.0.0+1

dependencies:
- cupertino_icons 1.0.4
- firebase_core 1.20.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 2.8.6 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_messaging 12.0.1 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_local_notifications 9.7.0 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_native_timezone 2.0.0 [flutter_web_plugins flutter js]
- get 4.6.5 [flutter]
- signature 5.1.0 [flutter image]

dev dependencies:
- flutter_lints 2.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- archive 3.3.0 [crypto path]
- args 2.3.1
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.16.0
- crypto 3.0.2 [typed_data]
- dbus 0.7.5 [args ffi meta xml]
- fake_async 1.3.0 [clock collection]
- ffi 2.0.0
- file 6.1.2 [meta path]
- firebase_core_platform_interface 4.5.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 1.7.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.2.12 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.1.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.1.0 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flutter_local_notifications_linux 0.5.0+1 [flutter flutter_local_notifications_platform_interface dbus path xdg_directories]
- flutter_local_notifications_platform_interface 5.0.0 [flutter plugin_platform_interface]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- image 3.2.0 [archive meta xml]
- js 0.6.4
- lints 2.0.0
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.4
- meta 1.7.0
- path 1.8.1
- petitparser 5.0.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- process 4.2.4 [file path platform]
- sky_engine 0.0.99
- source_span 1.8.2 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.9 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.8.0 [path]
- typed_data 1.3.1 [collection]
- vector_math 2.1.2
- xdg_directories 0.2.0+1 [meta path process]
- xml 6.1.0 [collection meta petitparser]

**Comment by darshankawar** [comment]
@Adithyan2295 
Can you provide the complete error log in properly formatted text instead of screenshot ?

**Comment by Adithyan2295** [comment]
> @Adithyan2295 Can you provide the complete error log in properly formatted text instead of screenshot ?
Updating local specs repositories
Analyzing dependencies
firebase_core: Using Firebase SDK version '9.3.0' defined in 'firebase_core'
Warning: firebase_app_id_file.json file does not exist. This may cause issues in upload-symbols. If this error is unexpected, try running flutterfire configure again.
firebase_crashlytics: Using Firebase SDK version '9.3.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '9.3.0' defined in 'firebase_core'
[!] CDN: trunk Repo update failed - 56 error(s):
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/6.2.0/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/6.20.0/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/6.21.0/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/6.22.0/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/6.23.0/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/6.24.0/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/6.25.0/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/6.26.0/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/6.27.0/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/6.27.1/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/6.28.0/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/6.28.1/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/6.29.0/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/6.3.0/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/6.30.0/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/6.31.0/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/6.31.1/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/6.32.0/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/6.32.2/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/6.33.0/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/6.34.0/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/6.4.0/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/6.5.0/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/6.6.0/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/6.7.0/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/6.8.0/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/6.8.1/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/6.9.0/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/7.0.0/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/7.1.0/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/7.10.0/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/7.11.0/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/7.2.0/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/7.2.0-M1/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/7.3.0/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/7.3.0-M1/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/7.4.0/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/7.4.0-M1/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/7.5.0/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/7.6.0/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/7.7.0/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/7.8.0/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/7.8.1/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/7.9.0/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/7.9.0-k1/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/7.9.0-k2/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/8.0.0/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/8.1.0/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/8.1.1/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/8.10.0/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/8.11.0/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/8.12.1/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/8.6.1/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/8.7.0/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/8.9.0/Firebase.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/8.9.1/Firebase.podspec.json Response: Timeout was reached

**Comment by darshankawar** [comment]
> Response: Timeout was reached

This indicates a network related error. The request doesn't seem to be reaching server and hence you might be getting this error. Try with another or a stable / fast network. See if you are behind a proxy wall / firewall which might be preventing to download the said file.

Also, check for similar errors on stackoverflow and see if any of the solutions mentioned helps.
Closing from here, as this isn't a plugin issue.
