### ISSUE TITLE
cloud functions callable  functions  code: invalid-argument

### ISSUE THREAD

**Issue by Louna-akkad1** [firebase/flutterfire#9206]
## Bug report

**Describe the bug**
After  upgrade cloud function  to 3.3.3 in my flutter app my callable  functions  throughs errors
PlatformException (PlatformException(invalid-argument, INVALID ARGUMENT, {message: INVALID ARGUMENT, code: invalid-argument}, null))
### Steps to reproduce

```

  final HttpsCallable getContentImages =
      FirebaseFunctions.instance.httpsCallable('getContentImages');

  Future<HttpsCallableResult> fetchActiviesData() async {
    return getContentImages.call(<String, dynamic>{});
  }

```
calling > fetchActiviesData()

**Comment by darshankawar** [comment]
@Louna-akkad1 
Can you provide `flutter doctor -v` ? and platform on which you are getting this error ?
I tried the plugin's example using latest firebase_core and cloud_functions plugin versions and ran it on iOS device in which the data was retrieved properly as below:

<img width="346" alt="Screenshot 2022-07-25 at 5 00 10 PM" src="https://user-images.githubusercontent.com/67046386/180767907-3f0a26c0-ea52-48f6-b3f4-a901908131ae.png">


Can you try the same and see if using plugin example, you get same error or not ?
