### ISSUE TITLE
[📚] `cloud_firestore` docs should mention the workaround for faster macOS builds

### ISSUE THREAD

**Issue by nilsreichardt** [firebase/flutterfire#9220]
When adding this line to your `macos/Podfile`, you are getting faster builds:
```ruby
pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => "#{firebase_sdk_version}"
```

See #3185 for more details.

The `example` for `cloud_firestore` is also using the workaround: https://github.com/firebase/flutterfire/blob/641ece1ad30f8224b33fb4815c1db01285736c5b/packages/cloud_firestore/cloud_firestore/example/macos/Podfile#L53

It would be helpful for new customers to mention this workaround in the docs.

**Comment by Jonas-Sander** [comment]
See also #7467

**Comment by darshankawar** [comment]
I think the linked issue will also address this issue, so its better to track it in https://github.com/firebase/flutterfire/issues/7467. The same has been acknowledge that the document can be updated to reflect the usage.

Closing this as duplicate.
