### ISSUE TITLE
🐛 [firebase_core_platform_interface] firebase_core_platform_interface depends on flutter_test

### ISSUE THREAD

**Issue by boskokg** [firebase/flutterfire#9224]
## Bug report

**Describe the bug**
firebase_core_platform_interface 4.5.0 depends on flutter_test. flutter_test should be defined only as dev_dependencies. please find a way to remove it from dependencies definition.

**Comment by darshankawar** [comment]
@boskokg 
`flutter_test` need to be defined inside `dev_dependencies`, as shown below:

<img width="434" alt="Screenshot 2022-07-26 at 1 26 55 PM" src="https://user-images.githubusercontent.com/67046386/180955210-7335a78e-9d78-4661-a8e7-19ac3c559c16.png">

Can you try moving it under `dev_dependencies` which should not throw the error you are reporting.

**Comment by russellwheatley** [comment]
It is used to export the mocks as mentioned in the `pubspec.yaml` file: https://github.com/firebase/flutterfire/blob/328b40aadd7d7a5f3a2ee18e1bb6685bd9fb3552/packages/firebase_core/firebase_core_platform_interface/pubspec.yaml#L17
