### ISSUE TITLE
🐛 [cloud_firestore_odm] Wrong firestoreJsonConverters auto inferred type 

### ISSUE THREAD

**Issue by imsamgarg** [firebase/flutterfire#9232]
Dart is auto inferring firestoreJsonConverters type to be "List<Object>" 

![error](https://user-images.githubusercontent.com/34547038/181115042-913c8ab0-d790-4707-abb0-fdfb3bac6d3d.png)

It works after manually defining type

```dart
const List<JsonConverter> firestoreJsonConverters = [
  FirestoreDateTimeConverter(),
  FirestoreTimestampConverter(),
  FirestoreGeoPointConverter(),
];
```

**Comment by rrousselGit** [comment]
Now that's embarrassing. Let me quickly fix it.
