### ISSUE TITLE
🐛 [firebase-config] Unknown permission `com.google.android.gms.permission.AD_ID`

### ISSUE THREAD

**Issue by Zazo032** [firebase/flutterfire#9237]
## Bug report

**Describe the bug**
Some Firebase plugin is probably declaring this permission internally, and according to Manifest Merger:
```
		ADDED from [com.google.firebase:firebase-config:21.1.1] <elided>\.gradle\caches\transforms-3\bfc29b0b0c8e604f1d064799fd671377\transformed\firebase-config-21.1.1\AndroidManifest.xml:33:17-117
uses-permission#com.google.android.gms.permission.AD_ID
```
![image](https://user-images.githubusercontent.com/2807712/181242085-f7fd3010-49a6-483b-89dd-540dd46fe856.png)
![image](https://user-images.githubusercontent.com/2807712/181242157-a1312887-d67f-4e79-8561-c6e6e05c6ec3.png)

### Steps to reproduce

1. Change target sdk version to Android 13
2. Include some Firebase plugins
3. Upload to Play Store

### Expected behavior

We're not using any Advertising ID, so it shouldn't be added automatically

---

## Additional context

This is a blocker to publish updates with an app targeting Android 13 and using Firebase plugins

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Versi¢n 10.0.22000.832], locale es-ES)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.68.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

**Comment by deepak786** [comment]
It seems that this permission is added automatically by the firebase analytics SDK
https://firebase.google.com/support/release-notes/android#analytics_v20-1-1

But I don't know about the firebase_config.

**Comment by darshankawar** [comment]
@Zazo032 
Please check below links for further details and see if they help further:

https://developers.google.com/interactive-media-ads/docs/sdks/android/dai/android-12
https://support.google.com/googleplay/android-developer/answer/6048248

**Comment by Zazo032** [comment]
Those articles were not very helpful, since they always refer to the Google Mobile Ads SDK, but we're not using it. We're using the following Firebase plugins

```yaml
firebase_analytics: ^9.3.0
firebase_core: ^1.20.0
firebase_crashlytics: ^2.8.6
firebase_performance: ^0.8.2+1
```

**Comment by darshankawar** [comment]
This most probably belongs upstream. See similar issue open : https://github.com/firebase/firebase-android-sdk/issues/2582
I suggest you to follow-up in that issue for further updates.
Closing from here, as this doesn't seem to be actionable from Flutterfire.
