### ISSUE TITLE
🐛 [firebase_core_web] No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp()

### ISSUE THREAD

**Issue by sgehrman** [firebase/flutterfire#9256]
This has been happening for a while, but never reported it. 

I set breakpoints for All Exceptions and Uncaught Exceptions and I get this every time.  Latest flutter, packages etc.

![gnome-shell-screenshot-MA33P1](https://user-images.githubusercontent.com/287137/181654238-00cbb1b0-c3ef-4cd3-94d4-2b3f02f7b311.png)

**Comment by Lyokone** [comment]
Hey, I used the latest version and everything is working properly on web.
Have you added the proper config in your main?
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MyApp());
}
```
Without any reproduction we will not be able to help you.

**Comment by Ahmadre** [comment]
> Hey, I used the latest version and everything is working properly on web.
> 
> Have you added the proper config in your main?
> 
> ```
> 
> void main() async {
> 
>   WidgetsFlutterBinding.ensureInitialized();
> 
> 
> 
>   await Firebase.initializeApp(
> 
>     options: DefaultFirebaseOptions.currentPlatform,
> 
>   );
> 
> 
> 
>   runApp(const MyApp());
> 
> }
> 
> ```
> 
> Without any reproduction we will not be able to help you.

I had the same errors. Please see: https://github.com/firebase/flutterfire/issues/9269

My solution was to completely delete that init for web in dart and do the init in index.html.
