### ISSUE TITLE
🐛 [firebase_core] Fails when changing storageBucket in firebase_options.dart

### ISSUE THREAD

**Issue by makoto-ishibashi** [firebase/flutterfire#9257]
## Bug report
If you change the configuration after using `flutterfire configure`, an error will occur when calling the `initializeApp` method.

### Steps to reproduce
1. Create a new flutter project.
2. Run `flutter pub add firebase_core`
3. Run `flutterfire configure`
4. Make the main function according to the official doc.
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}
```
5. Run the app --> success
6. Next, in the `firebase_options.dart`, change the android's `storageBucket` to another my own storage bucket address.
7. Run app -->  **Unhandled Exception: [core/duplicate-app] A Firebase App named "[DEFAULT]" already exists**

### Expected behavior
Reflecting the changed settings and working properly.

---

## Additional context

`flutterfire configure` creates both firebase_options.dart and google-services.json (which also confuses me), it works correctly if I avoid using firebase_options.dart.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.0.3, on macOS 12.3.1 21E258 darwin-arm, locale
    en-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.17.5
Flutter SDK 3.0.3
firebaseoptions_bug 1.0.0+1

dependencies:
- cupertino_icons 1.0.5
- firebase_core 1.20.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]

dev dependencies:
- flutter_lints 2.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.16.0
- fake_async 1.3.0 [clock collection]
- firebase_core_platform_interface 4.5.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 1.7.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- js 0.6.4
- lints 2.0.0
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.4
- meta 1.7.0
- path 1.8.1
- plugin_platform_interface 2.1.2 [meta]
- sky_engine 0.0.99
- source_span 1.8.2 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.9 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- vector_math 2.1.2

```

</details>

---

**Comment by Lyokone** [comment]
Hello,
When you use `flutterfire condigure`, it also adds a `google-services.json` file in your `android` folder.
You probably need to modify the bucket here too.

**Comment by makoto-ishibashi** [comment]
@Lyokone 
Thanks. I also changed `google-services.json`.  But the result was the same.

**Comment by Lyokone** [comment]
Did you add the bucket you want to add to your Firebase project? 
You need to go to your Firebase console, on storage and click on the 3 dots to add it.
![Screenshot_20220729-072552_Chrome.png](https://user-images.githubusercontent.com/3680002/181688771-4f5a1721-23c4-491a-9c62-4b8d9f7df807.png)

**Comment by makoto-ishibashi** [comment]
@Lyokone 
The sample above is using the free version of firebase, so I didn't actually add the bucket.
However, the same phenomenon occurs in the actual product (where an added bucket exists).
And, I don't think `flutterfire` checks if the bucket exists at initializeApp.

**Comment by makoto-ishibashi** [comment]
It seems to have been resolved.

1. Change `firebase_options.dart`
2. Change the corresponding part of `google-services.json`
3. Run **flutter clean**
4. Run the app --> success!

@Lyokone 's information was helpful.
