### ISSUE TITLE
[cloud_firestore] Have snapshots() method emit errors for devs to handle!

### ISSUE THREAD

**Issue by sentd94** [firebase/flutterfire#9261]
### Discussed in https://github.com/firebase/flutterfire/discussions/9260

<div type='discussions-op-text'>

<sup>Originally posted by **sentd94** July 29, 2022</sup>
When listening to realtime updates of a collection, no errors / exceptions are emitted to the stream (for example if the client cannot get a connection to the server):

```
db
    .collection('stuff')
    .where("someBool", isEqualTo: false)
    .snapshots()
    .listen((snap) { ...  }, onError: (e) {
         //never called...
         debugPrint(e.toString());
     });
```

**Why is this important?**

Sometimes you need to differentiate if a collection currently has no documents OR the internet is down and therefore your snapshot is empty.

**Note**

For getting data just once using `get()` method there is a `getOptions` parameter which you can use to enable error throwing (by passing `GetOptions(source: Source.server)`).  For `snapshots()` you don't have that option.</div>

**Comment by darshankawar** [comment]
Thanks for the report. Treating this as an enhancement.

**Comment by Lyokone** [comment]
Hi @sentd94, we have heavily change how the data is passed in Firestore,  do you still see this issue?
