### ISSUE TITLE
🐛 [firebase_app_check] Error When Using iOS

### ISSUE THREAD

**Issue by rlee1990** [firebase/flutterfire#9266]
## Bug report
I get the below error when trying to use Firebase Appcheck with iOS in Flutter.
```9.3.0 - [FirebaseFirestore][I-FST000001] AppCheck failed: 'The operation couldn’t be completed. Too many attempts. Underlying error: The operation couldn’t be completed. The server responded with an error:
 - URL: https://firebaseappcheck.googleapis.com/v1/projects/fire-snab/apps/1:263805889966:ios:488c6251dd683d2b3d6c3f:exchangeDeviceCheckToken
 - HTTP status code: 400
 - Response body: {
  "error": {
    "code": 400,
    "message": "App not registered: 1:263805889966:ios:488c6251dd683d2b3d6c3f.",
    "status": "FAILED_PRECONDITION"
  }
}
'```
**Describe the bug**
A clear and concise description of what the bug is.
When enforced is enabled the firestore data is not accessible.

running ios 15.4 using firebase_app_check: ^0.0.6+18

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.4 21F79 darwin-arm, locale
    en-US)
    • Flutter version 2.10.5 at /Users/rickeylee/Desktop/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (3 months ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version
    33.0.0-rc1)
    • Android SDK at /Users/rickeylee/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (4 available)
    • SM F926U (mobile)            • RFCR802EMHY                              •
      android-arm64  • Android 12 (API 31)
    • SM N950U (mobile)            • ce061716d1923703017e                     •
      android-arm64  • Android 9 (API 28)
    • rickey lee’s iPhone (mobile) • d0545eb2ff26e1c087d1b29c26f8e15da19284bb •
      ios            • iOS 15.5 19F77
    • Chrome (web)                 • chrome                                   •
      web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by darshankawar** [comment]
@rlee1990 
Can you upgrade to latest stable (3.0.5) along with plugin's latest version and try again ?

**Comment by rlee1990** [comment]
@darshankawar the reason I haven't used 3.5 was that a fix for the native view on android hasn't been deployed. I will save a version of the project to GitHub then upgrade to see if that does indeed fix the issue.

**Comment by rlee1990** [comment]
@darshankawar I still get the same error.
```[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale
    en-US)
    • Flutter version 3.0.5 at /Users/rickeylee/Desktop/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (3 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version
    33.0.0-rc1)
    • Android SDK at /Users/rickeylee/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (4 available)
    • SM N950U (mobile)            • ce061716d1923703017e                     •
      android-arm64  • Android 9 (API 28)
    • rickey lee’s iPhone (mobile) • d0545eb2ff26e1c087d1b29c26f8e15da19284bb •
      ios            • iOS 15.6 19G71
    • macOS (desktop)              • macos                                    •
      darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)                 • chrome                                   •
      web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by rlee1990** [comment]
@rlee1990 so I enabled device check in the firebase console and I don't get the error. It's odd I thought we only needed to enable App Attest and that would work. If that is not the case then the firebase docs need to be updated to say that both are required.

**Comment by darshankawar** [comment]
Good to know your issue is resolved. I think the current document mentions how to enable device check on Apple, as below:

`SafetyNet on Android, Device Check on Apple platforms, and reCAPTCHA v3 on web. `



> the firebase docs need to be updated to say that both are required.

You may open a new documentation bug for this and we'll address it.

Closing this issue, as it has been resolved per your comment.
