### ISSUE TITLE
Android Emulator cannot access Firebase with App Check in Enforcement mode

### ISSUE THREAD

**Issue by lukertaylor** [firebase/flutterfire#9291]
### Discussed in https://github.com/firebase/flutterfire/discussions/9284

<div type='discussions-op-text'>

<sup>Originally posted by **lukertaylor** August  1, 2022</sup>
Hello,

I have set-up App Check and followed the instructions (https://firebase.google.com/docs/app-check/android/debug-provider#kotlin+ktx_1) to successfully generate debug secrets on a physical Android device and the Android Emulator.

After installing the Debug Tokens in the Android Firebase app, the physical Android device works fine, but the Android Emulator cannot access Firestore:

/Firestore(): (24.2.1) [WriteStream]: () Stream closed with status: Status{code=PERMISSION_DENIED, description=Missing or insufficient permissions., cause=null}.
W/Firestore(): (24.2.1) [Firestore]: Write failed at _[path removed]_ 3: Status{code=PERMISSION_DENIED, description=Missing or insufficient permissions., cause=null}
E/flutter (): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.

Is there a workaround? Or can I only debug on a physical Android device?

Thank you for any help received.

Luke
</div>

**Comment by lukertaylor** [comment]
I have found a workaround, which is to only load the App Check plug-in when building in release mode:

`
if (kReleaseMode) {
    await FirebaseAppCheck.instance.activate();
}
`

**Comment by darshankawar** [comment]
@lukertaylor 
Currently it seems the app_check only works on real device and not on emulators. See [this](https://github.com/firebase/flutterfire/issues/9060#issuecomment-1185664921) issue comment and see if it helps in your case.

**Comment by lukertaylor** [comment]
@darshankawar I found a different, and much simpler, workaround that I thought others might find helpful.

**Comment by darshankawar** [comment]
@lukertaylor 
Can you also try [this](https://stackoverflow.com/a/72931246) solution and see if it helps ?

**Comment by lukertaylor** [comment]
@darshankawar sorry but that isn't helpful. I am not using a Cloud Function.

I posted the issue and a workaround.

**Comment by rohan20** [comment]
I was able to get it to work using a `MethodChannel`: https://stackoverflow.com/a/73330541/5066615

**Comment by duduBaiao** [comment]
> I have found a workaround, which is to only load the App Check plug-in when building in release mode:
> 
> `if (kReleaseMode) { await FirebaseAppCheck.instance.activate(); }`

I guess your app will stop working as soon as you enable the AppCheck in the Firebase Console, since the backend will expect the token.

**Comment by lukertaylor** [comment]
No that is not the case. As long as the debug token has been registered.
