### ISSUE TITLE
[firebase_database] [iOS] CocoaPods could not find compatible versions for pod "Firebase/Database":

### ISSUE THREAD

**Issue by mvpires** [firebase/flutterfire#9298]
I'm having this problema for some time now. I can't run pod install. 
     This error always pop up:

 [!] CocoaPods could not find compatible versions for pod "Firebase/Database":

  In Podfile:
    firebase_database (from `.symlinks/plugins/firebase_database/ios`) was resolved to 9.1.0, which depends on
      Firebase/Database (= 9.3.0)

    flutter_geofire (from `.symlinks/plugins/flutter_geofire/ios`) was resolved to 0.0.1, which depends on
      GeoFire (~> 4.0) was resolved to 4.1.0, which depends on
        Firebase/Database (~> 6.0)
      
      
I've tried every suggestion posted on a [similar issue](https://github.com/firebase/flutterfire/issues/9015) without success.
      
 This is my podfile

======================================

 platform :ios, '13.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

    pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '9.3.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
    flutter_additional_ios_build_settings(target)
  end
 end

  target 'OneSignalNotificationServiceExtension' do
    use_frameworks!
    pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'
  end

======================================

The project uses a framework (quickblox) and it depends on iOS 13.

These are the dependencies related the project uses

  firebase_core: ^1.20.0
  firebase_storage: ^10.3.4
  firebase_database: ^9.1.0
      
and the Flutter/Dart version

Flutter 3.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f1875d570e (3 weeks ago) • 2022-07-13 11:24:16 -0700
Engine • revision e85ea0e79c
Tools • Dart 2.17.6 • DevTools 2.12.2

It's working fine on Android.

**Comment by darshankawar** [comment]
@mvpires 
You'll probably need to report this in `flutter_geofire` repo for further resolution. See a similar issue for your reference: https://github.com/mrdishant/flutter_geofire/issues/23

Closing from here.

**Comment by mvpires** [comment]
> @mvpires You'll probably need to report this in `flutter_geofire` repo for further resolution. See a similar issue for your reference: [mrdishant/flutter_geofire#23](https://github.com/mrdishant/flutter_geofire/issues/23)
> 
> Closing from here.

Thank you, @darshankawar. I'll do that!
