### ISSUE TITLE
How to decode string with emojis from Firestore?

### ISSUE THREAD

**Issue by jefrrey017** [firebase/flutterfire#9307]
![image](https://user-images.githubusercontent.com/93859692/183238381-a054dd0f-25aa-4f9e-bce7-c0e799a218c0.png)

I have this string with emojis stored in the Firestore. When I query them on my app and try to render it on a `Text` widget, it throws
`Invalid argument(s) : string is not well-formed UTF-16`.

Rather than showing the emojis, the `Text` widget renders this

![image](https://user-images.githubusercontent.com/93859692/183238433-e9f66914-018d-4ea1-bc07-cc42112b0639.png)

Could somebody suggest a workaround for this?

_Originally posted by @jefrrey017 in https://github.com/firebase/flutterfire/discussions/9306_

**Comment by imeDevelopers** [comment]
`String.fromCharCodes('My emoji'.codeUnits);`

**Comment by darshankawar** [comment]
@jefrrey017 
Your question is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here, as this is not a bug report or a feature request.
