### ISSUE TITLE
🐛 [firebase_core_platform_interface] Android App doesn't start in release mode

### ISSUE THREAD

**Issue by spiderion** [firebase/flutterfire#9311]
The android app launches fine in debug mode but doesn't launch in release mode

The app crashes at the start when calling Firebase.initializeApp()
with this error:

E/flutter (10005): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(null-error, Host platform returned null value for non-null return value., null, null)
E/flutter (10005): #0      FirebaseCoreHostApi.optionsFromResource (package:firebase_core_platform_interface/src/pigeon/messages.pigeon.dart:242)
E/flutter (10005): <asynchronous suspension>
E/flutter (10005): #1      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:89)
E/flutter (10005): <asynchronous suspension>
E/flutter (10005): #2      Firebase.initializeApp (package:firebase_core/src/firebase.dart:40)
E/flutter (10005): <asynchronous suspension>
E/flutter (10005): #3      initializeApp (package:discuvur_app_package/app_Initialization.dart:17)
E/flutter (10005): <asynchronous suspension>
E/flutter (10005): #4      main (package:discuvur_app_package/main.dart:6)
E/flutter (10005): <asynchronous suspension>
E/flutter (10005):

FLUTTER DOCTOR : 

[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-arm, locale en-GB)
    • Flutter version 3.0.5 at /users/ionolaru/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (4 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
    • Android SDK at /Users/ionolaru/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 32) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

USING THIS FIREBASE DEPENDENCIES:

  firebase_auth: ^3.6.2
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.3
  firebase_analytics: ^9.3.0
  cloud_functions: ^3.3.3
  firebase_storage: ^10.3.4
  firebase_crashlytics: ^2.8.6
  firebase_remote_config: ^2.0.13
  firebase_messaging: ^12.0.1

**Comment by darshankawar** [comment]
@spiderion 
Please check [this](https://stackoverflow.com/questions/72895721/firebasecloudmessaging-platformexception-platformexceptionnull-error-host-p) link and see if it helps.

**Comment by spiderion** [comment]
Already checked before creating the issue here. Could not find a solution.

**Comment by spiderion** [comment]
Ok I found the issue. 

Flutter initialize needs to be called this way. 
 await FirebaseRemoteConfigImpl.getActivatedRemoteConfig(FirebaseRemoteConfig.instance);

And a file needs to be generated first firebase_options.dart
Which is generated by  this part
https://firebase.google.com/docs/flutter/setup?platform=android#:~:text=From%20your%20Flutter%20project%20directory%2C%20run%20the%20following%20command%20to%20install,flutter%20run
