### ISSUE TITLE
[📚] How to change "Sign In" string or the "Don't Have an account? Register" Text.

### ISSUE THREAD

**Issue by mikejones3** [firebase/flutterfire#9329]
Not sure how to Remove the Default "Sign In" string or the "Don't Have an account? Register" Text. 

If you are using Google and Apple sign in only for example then you do not need the "Don't Have an account? Register" Text. 

<img width="321" alt="image" src="https://user-images.githubusercontent.com/13171497/183743919-0b1b490d-71e1-4d79-b232-ed08432af0aa.png">

**Comment by graemep-nz** [comment]
I think you can do it like this but I haven't tried it - set showAuthActionSwitch false.  login_view.dart writes the text if showAuthActionText is true.

```
            return SignInScreen(
              showAuthActionSwitch: false,

```

**Comment by darshankawar** [comment]
Please use this discussion thread : https://github.com/firebase/flutterfire/discussions/6978 for questions like these.

Closing from here.
