### ISSUE TITLE
🐛 [Firebase_messaging] There is a delay when send FCM via firebase console, but no delay via Postman use FCM API

### ISSUE THREAD

**Issue by FortySL** [firebase/flutterfire#9336]
## Bug report

**Describe the bug**
I use FCM to send notifications when new messages coming in my flutter app's chat module. In the early implementation, I send FCM manually via firebase console and with whatever I did, there were always nearly 3 - 10 mins delay when receive notifications on my devices (simulator or physical device). I even tried to create a new clean flutter app used for receiving notifications, the delay still exists.

### Steps to reproduce

1. Create a new flutter app and new firebase project
2. Set up firebase messaging on the newly created app
3. Go to firebase console and send notifications manually
4. There is a delay between FCM sent in console and received on device

### Expected behavior

I have tired FCM early 2022, there is no delay when use firebase console to send FCM, but the delay exist now

### Sample project

No sample project

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```

 flutter doctor -v
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-arm, locale en-AU)
    • Flutter version 3.0.1 at /Applications/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 months ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /xxx/xxx/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (4 available)
xxx

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by darshankawar** [comment]
@FortySL 
Flutterfire doesn't control the behavior / timing of the notifications being sent / received, so you'll need to reach out to [Firebase support](https://firebase.google.com/support/) for further resolution.
Closing from here, as this isn't a plugin issue.
