### ISSUE TITLE
🐛 [cloud_firestore] GetOptions default source when  Settings( persistenceEnabled: false)

### ISSUE THREAD

**Issue by MdSaLaMa** [firebase/flutterfire#9351]
what about setting **_GetOptions_** default **_source_** to be
 `get(GetOptions(
            source: Source
                .server))`
in case of
` FirebaseFirestore.instance.settings =
      const Settings(persistenceEnabled: false);`</div>

**Comment by darshankawar** [comment]
> what about setting **_GetOptions_** default **_source_** to be
> `get(GetOptions( source: Source .server))`

For getting data just once using `get()` method there is a `getOptions` parameter which you can use to enable error throwing (by passing `GetOptions(source: Source.server`))


In your case, can you elaborate what are you trying to achieve ?
