### ISSUE TITLE
🐛 [firebase_messaging] Firebase Messaging component is not present (Android)

### ISSUE THREAD

**Issue by jugamir** [firebase/flutterfire#9355]
## Bug report

**Describe the bug**
`FirebaseMessaging.instance.getToken();` 
on android it throws error:
` [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: [firebase_messaging/unknown] Firebase Messaging component is not present`

### Steps to reproduce

- Configure a firebase project, add cloud_messaging plugin.
- add  ` <application android:usesCleartextTraffic="true"/>` to src/main/AndroidManifest.xml
- call `FirebaseMessaging.instance.getToken();` in the code

### Expected behavior

If this is expected behavior, the documentation, and the error message should point out that you can't include this line in your AndroidManifest.xml. 

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-x64,
    locale en-HU)
[✓] Android toolchain - develop for Android devices (Android SDK version
    30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.70.1)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.17.6
Flutter SDK 3.0.5
temp 1.0.0+1

dependencies:
- cupertino_icons 1.0.5
- firebase_core 1.20.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 12.0.2 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]

dev dependencies:
- flutter_lints 2.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.16.0
- fake_async 1.3.0 [clock collection]
- firebase_core_platform_interface 4.5.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 1.7.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 4.1.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.1.1 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- js 0.6.4
- lints 2.0.0
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.4
- meta 1.7.0
- path 1.8.1
- plugin_platform_interface 2.1.2 [meta]
- sky_engine 0.0.99
- source_span 1.8.2 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.9 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- vector_math 2.1.2
```

</details>

---

**Comment by darshankawar** [comment]
> * add  ` <application android:usesCleartextTraffic="true"/>` to src/main/AndroidManifest.xml

@jugamir This, according to Flutter documentation is only added if you want to allow HTTP connections for Android debug builds: https://docs.flutter.dev/release/breaking-changes/network-policy-ios-android#allowing-cleartext-connection-for-debug-builds

If you are not looking to do so, does removing this property still gives you same error ?

Also, from plugin's official example, in manifest file, there's this property added:

https://github.com/firebase/flutterfire/blob/2937fb8ec2abd5d823f5434150383e81fec80a05/packages/firebase_messaging/firebase_messaging/android/src/main/AndroidManifest.xml#L25

which seems to be also mentioned in [this](https://stackoverflow.com/questions/67007399/firebase-messaging-component-is-not-present-in-android-studio) SO link.

Try the same and see if it works in your case.

**Comment by jugamir** [comment]
@darshankawar 
Thanks for the quick response! Yes it is working fine if I remove this line

`<application android:usesCleartextTraffic="true"/>`

But I need this,  because I am working with local backend builds as well.  It is also independent from this [https://stackoverflow.com/questions/67007399/firebase-messaging-component-is-not-present-in-android-studio](url)

You can close the issue if you think it's expected behavior. I would put this info somewhere in the docs.

**Comment by darshankawar** [comment]
Thanks for the feedback @jugamir. That probably doesn't seem like expected behavior, because it is throwing an unhandled exception, so it surely must be handled, but I am not sure if that will be done at client side or native android firebase sdk.

Can you provide your app level and project level `build.gradle` files ? Maybe also try to add `minifyEnabled false` and see if it helps.
