### ISSUE TITLE
java.io.IOException: FIS_AUTH_ERROR Issue in release build.

### ISSUE THREAD

**Issue by panchalAlpit** [firebase/flutterfire#9372]
Hello I'm getting the "FIS_AUTH_ERROR" when build install from Google Play store but when directly installed the Signed APK so it's working the completely, this issue come after update latest plugin, it's completely working before "firebase_messaging: ^12.0.2" this version. 

below the code I'm getting this error.

`var _deviceToken = await FirebaseMessaging.instance.getToken();`

Thanks in Advance

**Comment by Lyokone** [comment]
Hello, can you confirm which version was working before?
12.0.1 or 11.x?

**Comment by darshankawar** [comment]
@panchalAlpit 
Can you provide complete error log ?
Also, can you confirm that your `API_Key` is not restricted and the release SHA-1 certificate is added properly ?

**Comment by panchalAlpit** [comment]
> Hello, can you confirm which version was working before? 12.0.1 or 11.x?

11.2.13 version I'm using

**Comment by panchalAlpit** [comment]
> @panchalAlpit Can you provide complete error log ? Also, can you confirm that your `API_Key` is not restricted and the release SHA-1 certificate is added properly ?

getting only "java.io.IOException: FIS_AUTH_ERROR"

**Comment by darshankawar** [comment]
> can you confirm that your `API_Key` is not restricted and the release SHA-1 certificate is added properly ?

**Comment by panchalAlpit** [comment]
> > can you confirm that your `API_Key` is not restricted and the release SHA-1 certificate is added properly ?

Thank you  @darshankawar for giving the idea. last 3 day's and lot's of searching I have fix this issue. I have take SHA-1 from Google developer console(App integrity) and add in Google cloud console project and also set inside Firebase project.
