### ISSUE TITLE
🐛 [FIREBASE_MESSAGGING] App Bundle which has an activity, activity alias, service or broadcast receiver with intent filter, but without 'android:exported' property set

### ISSUE THREAD

**Issue by ri3tykity** [firebase/flutterfire#9386]
## Bug report

**Describe the bug**
I am using Firebase_Messagging and other firebase plugin for flutter project.
Local when I build and run application it is working fine.
I am facing issue when I deployed appbundle to play store. It is showing below error and not accepting the bundle:
You uploaded an APK or Android App Bundle which has an activity, activity alias, service or broadcast receiver with intent filter, but without 'android:exported' property set. This file can't be installed on Android 12 or higher. See: developer.android.com/about/versions/12/behavior-changes-12#exported

I made changes in manifest file but not working...

### Steps to reproduce
\build\firebase_messaging\intermediates\library_manifest\release\AndroidManifest.xml
```
<service android:name="com.google.firebase.components.ComponentDiscoveryService" >
            <meta-data
                android:name="com.google.firebase.components:io.flutter.plugins.firebase.messaging.FlutterFirebaseAppRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
        </service>
```

above services is not set export property. Others are OK.

### Expected behavior
Please fix the issue.

**Comment by ri3tykity** [comment]
For the time being I removed Firebase_Messaging and Flutter_Local_Notification package from pubspec.yaml file and release the app. 
It is working. But it is temporary solution.

**Comment by darshankawar** [comment]
@ri3tykity 
Can you try [this](https://stackoverflow.com/a/70697686) solution and see if it works for you ?
If above doesn't work, can you try to add the missing property `android:exported=true` below and check if it helps ?

At native firebase side, the property seems to be present already:

https://github.com/firebase/firebase-android-sdk/blob/58c167795980b296c737ffce044c29c7ff1926d3/firebase-messaging/src/main/AndroidManifest.xml#L44

But not at client side:

https://github.com/firebase/flutterfire/blob/5b5f477d6e633a38bea561cee35db3f628719666/packages/firebase_messaging/firebase_messaging/android/src/main/AndroidManifest.xml#L25
