### ISSUE TITLE
🐛 [firebase_crashlytics] [iOS] Problem with upload-symbols dSYM when building under a corporate proxy

### ISSUE THREAD

**Issue by MaximMonakhov** [firebase/flutterfire#9388]
## Bug report

**Describe the bug**

I'm trying to set up Firebase Crashlytics on iOS since it's a great tool, but I'm having problems because the build is running under a corporate proxy with authentication.
During the build, the following problem occurs.
From what I understand, these dSYMs are needed to catch bugs in iOS, but I don't need that and am only interested in Flutter bugs. How to disable sending dSYMs or make the package look in the system settings for proxy settings, I have not found.
The only option I've found is to fork the package and cut out the insertion script in the upload-symbols build phase. But this is not a solution.

<details><summary>Error</summary>

```
Running upload-symbols in Build Phase mode
Validating build environment for Crashlytics...
Processing dSYMs...
error: Failed uploading cSYMs due to error: Error Domain=com.google.firebase.crashlytics.FIRCLSCompoundOperation.error Code=4294967293 "(null)"
An SSL error has occurred and a secure connection to the server cannot be made
```

</details>

Any help, please?

**Comment by darshankawar** [comment]
> An SSL error has occurred and a secure connection to the server cannot be made

This indicates a general SSL failure and as you mentioned, you are behind a corporate proxy, hence, flutterfire may not have any control over the proxy settings. 
Can you provide the `UserInfo` part of the error message ?

Also try to set the http_proxy and https_proxy in wifi config instead of in shell and see if it helps.
