### ISSUE TITLE
[firebase_auth] sms code auto retrieval (auto detect and login) not working, I got an error,  [SmsRetrieverHelper] Timed out waiting for SMS.

### ISSUE THREAD

**Issue by like-github1** [firebase/flutterfire#9391]
## Bug report

**Describe the bug**
I am using Firebase OTP to verify the phone number, but I got this error when I trying to get  OTP SMS code to my phone, [SmsRetrieverHelper]. I timed out. I got this error when I tried waiting for an SMS.

[](https://i.stack.imgur.com/fiUZ0.png)
![otp](https://user-images.githubusercontent.com/92579234/185761145-0b3204e5-cacd-4e85-86b1-f43475dd421c.PNG)

**Comment by darshankawar** [comment]
@like-github1 
Looking at the error : `[SmsRetrieverHelper] Timed out waiting for SMS.`, it seems to be same as https://github.com/firebase/flutterfire/issues/4916, so I suggest you to go through underlying comments and see if they help.

Also, based on [this](https://github.com/firebase/flutterfire/issues/4916#issuecomment-919124231) comment, it doesn't seem to be specific to flutterfire, but seems to be coming from native firebase sdk. See below similar issues for your reference:

https://github.com/firebase/firebase-android-sdk/issues/2688
https://github.com/firebase/firebase-android-sdk/issues/2318

Closing from here.
