### ISSUE TITLE
🐛 [firebase_messaging] Notification images are not displayed

### ISSUE THREAD

**Issue by themisir** [firebase/flutterfire#9416]
## Bug report

It might be not an actual bug rather a missing feature. I've implemented all the steps on usage page and tested notifications, it turns out everything works expect when I send notification with image on iOS image is not displayed on notifications. I have tested both from API and firebase console.

Then I've checked [firebase documentation](https://firebase.google.com/docs/cloud-messaging/ios/send-image) and it says that to handle notification with images on iOS we need to add notification service extension. I wonder if this has already been done in firebase_messaging package or needs to be done by ourselves.

**Comment by darshankawar** [comment]
@themisir 
The plugin does support the integration to add notification service extension as mentioned in the document. We need to follow the steps as mentioned in it. See [this](https://github.com/firebase/flutterfire/issues/4133) similar but old issue and check underlying comments which has solutions discussed to make it working.

**Comment by themisir** [comment]
Oh thanks, sorry I totally missed this section of the docs: https://firebase.flutter.dev/docs/messaging/apple-integration#advanced-optional-allowing-notification-images

Have a great day!
