### ISSUE TITLE
🐛 [FirebaseStorage] Modules Issue (Xcode): Declaration of 'FIRStorageHandle' must be imported from module 'FirebaseStorage.FIRStorageTypedefs' before it is required

### ISSUE THREAD

**Issue by cyiboy** [firebase/flutterfire#9420]
## Bug report

**Describe the bug**
trying to build for ios but have this issue
 
```
Modules Issue (Xcode): Declaration of 'FIRStorageHandle' must be imported from module 'FirebaseStorage.FIRStorageTypedefs' before it is required
/Users/builder/programs/flutter_3_0_5/.pub-cache/hosted/pub.dartlang.org/firebase_storage-8.1.3/ios/Classes/FLTFirebaseStoragePlugin.m:410:14
```

version 
 firebase_storage: ^10.2.18

**Comment by darshankawar** [comment]
@cyiboy 
Can you provide `flutter doctor -v` and `pubspec.yaml` ?
Can you also try to upgrade the plugin to latest version and see if it helps or still gives same error ?

The error seems to be pointing to plugin's 8.1.3 version : `pub-cache/hosted/pub.dartlang.org/firebase_storage-8.1.3/ios/Classes/FLTFirebaseStoragePlugin.m:410:14`

So, can you try to clear the pub cache, remove `podfile.lock` and then run `pod install` to see if it helps ?
