### ISSUE TITLE
🐛 [firebase_messaging] App crashes on Android 13 during permission request

### ISSUE THREAD

**Issue by TatsuUkraine** [firebase/flutterfire#9430]
## Bug report

App crashes on devices with Android 13 during permission request with plugin v13 and targetSDK less than 33

### Steps to reproduce

- follow the instructions for installation
- ensure that you have a `firebase_messaging` plugin with v13.0
- ensure that your app has targetSdk 32
- ensure that the app doesn't have notification permissions granted yet (first install or manually revoked)
- request permission with `FirebaseMessaging.instance.requestPermission(...)`

App crashes with an exception
```
D/AndroidRuntime(28872): Shutting down VM
E/AndroidRuntime(28872): FATAL EXCEPTION: main
E/AndroidRuntime(28872): Process: com.example.mobile, PID: 28872
E/AndroidRuntime(28872): java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=24, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.example.mobile/com.example.mobile.MainActivity}: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
E/AndroidRuntime(28872): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5347)
E/AndroidRuntime(28872): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5386)
E/AndroidRuntime(28872): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
E/AndroidRuntime(28872): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/AndroidRuntime(28872): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(28872): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(28872): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
E/AndroidRuntime(28872): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(28872): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(28872): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(28872): 	at android.app.ActivityThread.main(ActivityThread.java:7898)
E/AndroidRuntime(28872): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(28872): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(28872): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/AndroidRuntime(28872): Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
E/AndroidRuntime(28872): 	at io.flutter.plugins.firebase.messaging.FlutterFirebasePermissionManager.onRequestPermissionsResult(FlutterFirebasePermissionManager.java:32)
E/AndroidRuntime(28872): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:777)
E/AndroidRuntime(28872): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:409)
E/AndroidRuntime(28872): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:752)
E/AndroidRuntime(28872): 	at io.flutter.embedding.android.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:748)
E/AndroidRuntime(28872): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8759)
E/AndroidRuntime(28872): 	at android.app.Activity.dispatchActivityResult(Activity.java:8617)
E/AndroidRuntime(28872): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5340)
E/AndroidRuntime(28872): 	... 13 more
```

If notification permissions are already granted all works fine

### Expected behavior

App shouldn't crash on permission request if the target SDK is less than 33

**Comment by darshankawar** [comment]
@TatsuUkraine 
Thanks for the report. Do you have `android:exported=true` in manifest file as mentioned in this merged PR ?

https://github.com/firebase/flutterfire/pull/9348

`Users will also need to have the android:exported="true" property set in app manifest on apps running on android 12 or higher.`

**Comment by TatsuUkraine** [comment]
@darshankawar yes I do have it

**Comment by russellwheatley** [comment]
@TatsuUkraine yes, this is why it is a breaking change. You need to target API level 33. See the [CHANGELOG](https://github.com/firebase/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/CHANGELOG.md#1300) for details.

**Comment by TatsuUkraine** [comment]
@russellwheatley in the gradle I have compileSdkVersion 33, but targetSdkVersion is 32 (as I mentioned in the ticket), and it causing issues I can assume, but targetSdk shouldn't be a blocker, for example it's not a blocker for flutter_local_notification plugin to work properly with targetSDK less than 33

**Comment by TatsuUkraine** [comment]
@darshankawar @russellwheatley you can check how they did solve exception with empty array as far as I can see from the diff, you just need to add check if permission array is not empty [here](https://github.com/firebase/flutterfire/pull/9348/files#diff-ea31346b859bd190ddc36ce7aadf1b0d7cdc935de9d0c7f38c237dce42e0a10aR32)

**Comment by TatsuUkraine** [comment]
not sure if it's the best way to do it though))

**Comment by TatsuUkraine** [comment]
here is how they solved this problem - https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java#L1574

**Comment by darshankawar** [comment]
Keeping it open for further insights from the team.

**Comment by darshankawar** [comment]
Another report, probably similar : https://github.com/firebase/flutterfire/issues/9429

**Comment by TatsuUkraine** [comment]
Thought about this issue more, maybe another option could be - add note to the docs, if application target SDK is less than 33, devs should try to request permissions if app runs on Android device. Since it's sort of redundant for Android 12 and less, and doesn't work on Android 13

**Comment by nachikamod** [comment]
Getting similar kind of issue with update 13.0.0
target and compile sdk version 33

```console
E/AndroidRuntime(26033): java.lang.AssertionError
E/AndroidRuntime(26033):    at io.flutter.plugins.firebase.messaging.FlutterFirebasePermissionManager.onRequestPermissionsResult(FlutterFirebasePermissionManager.java:33)
E/AndroidRuntime(26033):    at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:777)
E/AndroidRuntime(26033):    at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:409)
E/AndroidRuntime(26033):    at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:752)
E/AndroidRuntime(26033):    at io.flutter.embedding.android.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:748)
E/AndroidRuntime(26033):    at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8421)
E/AndroidRuntime(26033):    at android.app.Activity.dispatchActivityResult(Activity.java:8266)
E/AndroidRuntime(26033):    at android.app.ActivityThread.deliverResults(ActivityThread.java:4931)
E/AndroidRuntime(26033):    at android.app.ActivityThread.handleSendResult(ActivityThread.java:4979)
E/AndroidRuntime(26033):    at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(26033):    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(26033):    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(26033):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
E/AndroidRuntime(26033):    at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(26033):    at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(26033):    at android.app.ActivityThread.main(ActivityThread.java:7562)
E/AndroidRuntime(26033):    at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(26033):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/AndroidRuntime(26033):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
I/Process (26033): Sending signal. PID: 26033 SIG: 9
Lost connection to device.
```

**Comment by Tom3652** [comment]
Actually guys i came across this crash few minutes ago on my Android 11 device with the `firebase_messaging: 13.0.0`. 
I am also targeting and compiling against sdk 33 (both) : 

```
D/AndroidRuntime(13706): Shutting down VM
E/AndroidRuntime(13706): FATAL EXCEPTION: main
E/AndroidRuntime(13706): Process: com.my_app_name.android, PID: 13706
E/AndroidRuntime(13706): java.lang.AssertionError
E/AndroidRuntime(13706): 	at io.flutter.plugins.firebase.messaging.FlutterFirebasePermissionManager.onRequestPermissionsResult(FlutterFirebasePermissionManager.java:33)
E/AndroidRuntime(13706): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:777)
E/AndroidRuntime(13706): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:409)
E/AndroidRuntime(13706): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:752)
E/AndroidRuntime(13706): 	at io.flutter.embedding.android.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:748)
E/AndroidRuntime(13706): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8549)
E/AndroidRuntime(13706): 	at android.app.Activity.dispatchActivityResult(Activity.java:8397)
E/AndroidRuntime(13706): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5073)
E/AndroidRuntime(13706): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5121)
E/AndroidRuntime(13706): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(13706): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(13706): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(13706): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2115)
E/AndroidRuntime(13706): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(13706): 	at android.os.Looper.loop(Looper.java:250)
E/AndroidRuntime(13706): 	at android.app.ActivityThread.main(ActivityThread.java:7755)
E/AndroidRuntime(13706): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13706): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(13706): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
```

**Comment by nachikamod** [comment]
> Actually guys i came across this crash few minutes ago on my Android 11 device with the `firebase_messaging: 13.0.0`. I am also targeting and compiling against sdk 33 (both) :
> 
> ```
> D/AndroidRuntime(13706): Shutting down VM
> E/AndroidRuntime(13706): FATAL EXCEPTION: main
> E/AndroidRuntime(13706): Process: com.my_app_name.android, PID: 13706
> E/AndroidRuntime(13706): java.lang.AssertionError
> E/AndroidRuntime(13706): 	at io.flutter.plugins.firebase.messaging.FlutterFirebasePermissionManager.onRequestPermissionsResult(FlutterFirebasePermissionManager.java:33)
> E/AndroidRuntime(13706): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:777)
> E/AndroidRuntime(13706): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:409)
> E/AndroidRuntime(13706): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:752)
> E/AndroidRuntime(13706): 	at io.flutter.embedding.android.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:748)
> E/AndroidRuntime(13706): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8549)
> E/AndroidRuntime(13706): 	at android.app.Activity.dispatchActivityResult(Activity.java:8397)
> E/AndroidRuntime(13706): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5073)
> E/AndroidRuntime(13706): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5121)
> E/AndroidRuntime(13706): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
> E/AndroidRuntime(13706): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
> E/AndroidRuntime(13706): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
> E/AndroidRuntime(13706): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2115)
> E/AndroidRuntime(13706): 	at android.os.Handler.dispatchMessage(Handler.java:106)
> E/AndroidRuntime(13706): 	at android.os.Looper.loop(Looper.java:250)
> E/AndroidRuntime(13706): 	at android.app.ActivityThread.main(ActivityThread.java:7755)
> E/AndroidRuntime(13706): 	at java.lang.reflect.Method.invoke(Native Method)
> E/AndroidRuntime(13706): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
> E/AndroidRuntime(13706): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
> ```

Solution for me was to rollback to 12.0.3

**Comment by vbuberen** [comment]
Can confirm the issue on version `13.0.0`. I have both `targetSDK` and `compileSDK` set to 33.

I use `permission_handler` to request new notifications permission. However, as soon as I grant the permission via the dialog I see the crash with the same stacktrace as in report above:
```
E/AndroidRuntime( 7328): java.lang.AssertionError
E/AndroidRuntime( 7328): 	at io.flutter.plugins.firebase.messaging.FlutterFirebasePermissionManager.onRequestPermissionsResult(FlutterFirebasePermissionManager.java:33)
E/AndroidRuntime( 7328): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:777)
E/AndroidRuntime( 7328): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:409)
E/AndroidRuntime( 7328): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:752)
E/AndroidRuntime( 7328): 	at io.flutter.embedding.android.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:748)
E/AndroidRuntime( 7328): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8759)
E/AndroidRuntime( 7328): 	at android.app.Activity.dispatchActivityResult(Activity.java:8617)
E/AndroidRuntime( 7328): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5340)
E/AndroidRuntime( 7328): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5386)
E/AndroidRuntime( 7328): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
E/AndroidRuntime( 7328): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/AndroidRuntime( 7328): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 7328): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 7328): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
E/AndroidRuntime( 7328): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 7328): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime( 7328): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime( 7328): 	at android.app.ActivityThread.main(ActivityThread.java:7898)
E/AndroidRuntime( 7328): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7328): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime( 7328): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by quiquegarcia** [comment]
> > Actually guys i came across this crash few minutes ago on my Android 11 device with the `firebase_messaging: 13.0.0`. I am also targeting and compiling against sdk 33 (both) :
> > ```
> > D/AndroidRuntime(13706): Shutting down VM
> > E/AndroidRuntime(13706): FATAL EXCEPTION: main
> > E/AndroidRuntime(13706): Process: com.my_app_name.android, PID: 13706
> > E/AndroidRuntime(13706): java.lang.AssertionError
> > E/AndroidRuntime(13706): 	at io.flutter.plugins.firebase.messaging.FlutterFirebasePermissionManager.onRequestPermissionsResult(FlutterFirebasePermissionManager.java:33)
> > E/AndroidRuntime(13706): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:777)
> > E/AndroidRuntime(13706): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:409)
> > E/AndroidRuntime(13706): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:752)
> > E/AndroidRuntime(13706): 	at io.flutter.embedding.android.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:748)
> > E/AndroidRuntime(13706): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8549)
> > E/AndroidRuntime(13706): 	at android.app.Activity.dispatchActivityResult(Activity.java:8397)
> > E/AndroidRuntime(13706): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5073)
> > E/AndroidRuntime(13706): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5121)
> > E/AndroidRuntime(13706): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
> > E/AndroidRuntime(13706): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
> > E/AndroidRuntime(13706): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
> > E/AndroidRuntime(13706): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2115)
> > E/AndroidRuntime(13706): 	at android.os.Handler.dispatchMessage(Handler.java:106)
> > E/AndroidRuntime(13706): 	at android.os.Looper.loop(Looper.java:250)
> > E/AndroidRuntime(13706): 	at android.app.ActivityThread.main(ActivityThread.java:7755)
> > E/AndroidRuntime(13706): 	at java.lang.reflect.Method.invoke(Native Method)
> > E/AndroidRuntime(13706): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
> > E/AndroidRuntime(13706): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
> > ```
> 
> Solution for me was to rollback to 12.0.3

This worked for me, thanks!

**Comment by quiquegarcia** [comment]
> Can confirm the issue on version `13.0.0`. I have both `targetSDK` and `compileSDK` set to 33.
> 
> I use `permission_handler` to request new notifications permission. However, as soon as I grant the permission via the dialog I see the crash with the same stacktrace as in report above:
> 
> ```
> E/AndroidRuntime( 7328): java.lang.AssertionError
> E/AndroidRuntime( 7328): 	at io.flutter.plugins.firebase.messaging.FlutterFirebasePermissionManager.onRequestPermissionsResult(FlutterFirebasePermissionManager.java:33)
> E/AndroidRuntime( 7328): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:777)
> E/AndroidRuntime( 7328): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:409)
> E/AndroidRuntime( 7328): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:752)
> E/AndroidRuntime( 7328): 	at io.flutter.embedding.android.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:748)
> E/AndroidRuntime( 7328): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8759)
> E/AndroidRuntime( 7328): 	at android.app.Activity.dispatchActivityResult(Activity.java:8617)
> E/AndroidRuntime( 7328): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5340)
> E/AndroidRuntime( 7328): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5386)
> E/AndroidRuntime( 7328): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
> E/AndroidRuntime( 7328): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
> E/AndroidRuntime( 7328): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
> E/AndroidRuntime( 7328): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
> E/AndroidRuntime( 7328): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
> E/AndroidRuntime( 7328): 	at android.os.Handler.dispatchMessage(Handler.java:106)
> E/AndroidRuntime( 7328): 	at android.os.Looper.loopOnce(Looper.java:201)
> E/AndroidRuntime( 7328): 	at android.os.Looper.loop(Looper.java:288)
> E/AndroidRuntime( 7328): 	at android.app.ActivityThread.main(ActivityThread.java:7898)
> E/AndroidRuntime( 7328): 	at java.lang.reflect.Method.invoke(Native Method)
> E/AndroidRuntime( 7328): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
> E/AndroidRuntime( 7328): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
> ```

Confirmed!

**Comment by otopba** [comment]
I have this problem in release =(

**Comment by mohammedX6** [comment]
I have this proplem too

**Comment by zitob9** [comment]
i have this problem also

**Comment by sagnik-sanyal** [comment]
i am also having this same issue. is there any fix available for the same ?

**Comment by Hwan-seok** [comment]
This crash is not only for notification permission but also for any permission requests.

**Comment by sagnik-sanyal** [comment]
> 

Yes the app crashes for any kind of permission request. Did you find any kind of temporary solution yet ?

**Comment by TatsuUkraine** [comment]
v12 works fine, so we're using it for now

**Comment by feelsoftware** [comment]
It crashed doe to check in `io.flutter.plugins.firebase.messaging.FlutterFirebasePermissionManager`
```java
assert this.successCallback != null;
```

the temporary solution is to extend your `MainActivity` like this:
```kotlin
override fun onRequestPermissionsResult(
    requestCode: Int,
    permissions: Array<out String>,
    grantResults: IntArray,
) {
    try {
        /**
         * java.lang.AssertionError at io.flutter.plugins.firebase.messaging.FlutterFirebasePermissionManager.onRequestPermissionsResult(FlutterFirebasePermissionManager.java:33)
         */
        super.onRequestPermissionsResult(requestCode, permissions, grantResults)
    } catch (error: Throwable) {
        error.printStackTrace()
    }
}
```

**Comment by TatsuUkraine** [comment]
It seems that a lot of people actually having [assert exception](https://github.com/firebase/flutterfire/issues/9429) , rather than `ArrayIndexOutOfBoundsException` described in this ticket

**Comment by russellwheatley** [comment]
Hey folks, sorry for the delay responding to this issue. It appears there are two bugs:

1. We need to check the grants array as initially described by @TatsuUkraine. This is an easy fix.
2. The [assert](https://github.com/firebase/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebasePermissionManager.java#L33) is being triggered because there is no callback. This is quite confusing as we only call `requestPermission()` [here](https://github.com/firebase/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java#L328-L336) which always passes the callback.

@here
I'll create a PR to fix the first bug. Is someone able to provide a repro for the second bug?

**Comment by feelsoftware** [comment]
@russellwheatley to reproduce the second bug try to request permission by using `permission_handler`

in this case `Activity#onRequestPermissionResult` is called and [this assert](https://github.com/firebase/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebasePermissionManager.java#L33) crashes the app because we haven't set [the success callback](https://github.com/firebase/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebasePermissionManager.java#L54)

**Comment by russellwheatley** [comment]
@feelsoftware Thanks, I think I understand why the assertion is being triggered now 👍

**Comment by lucasvaudey** [comment]
> @feelsoftware Thanks, I think I understand why the assertion is being triggered now 👍

Removing assertion work but when I try with `permission_handler` to request camera permission I have the following error

```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=24, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.example.ok/com.example.ok.MainActivity}: com.google.android.gms.tasks.DuplicateTaskCompletionException: Complete with: result {authorizationStatus=1}
E/AndroidRuntime(14376): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5347)
E/AndroidRuntime(14376): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5386)
E/AndroidRuntime(14376): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
E/AndroidRuntime(14376): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/AndroidRuntime(14376): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(14376): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(14376): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
```

**Comment by feelsoftware** [comment]
> > @feelsoftware Thanks, I think I understand why the assertion is being triggered now 👍
> 
> Removing assertion work but when I try with `permission_handler` to request camera permission I have the following error
> 
> ```
> java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=24, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.example.ok/com.example.ok.MainActivity}: com.google.android.gms.tasks.DuplicateTaskCompletionException: Complete with: result {authorizationStatus=1}
> E/AndroidRuntime(14376): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5347)
> E/AndroidRuntime(14376): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5386)
> E/AndroidRuntime(14376): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
> E/AndroidRuntime(14376): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
> E/AndroidRuntime(14376): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
> E/AndroidRuntime(14376): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
> E/AndroidRuntime(14376): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
> ```

You should not only remove that [assert](https://github.com/firebase/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebasePermissionManager.java#L33), but also check if [requestInProgress](https://github.com/firebase/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebasePermissionManager.java#L27).

The exception says you are trying to [complete](https://github.com/firebase/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java#L332) the task twice.

I haven't check the code, but it should cover your case, `FlutterFirebasePermissionManager`:
```java
@Override
public boolean onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
    if (requestCode != permissionCode || !requestInProgress) {
        requestInProgress = false;
        return false;
    }
    requestInProgress = false;

    int grantResult = grantResults[0];
    if (this.successCallback != null) {
        this.successCallback.onSuccess(grantResult == PackageManager.PERMISSION_GRANTED ? 1 : 0);
    }
    return true;
}
```

**Comment by lucasvaudey** [comment]
@feelsoftware Thank's for your answer this help me solved the problem 
Here's the final onRequestPermissionsResult in firebase_messaging package :

```Java
@Override
  public boolean onRequestPermissionsResult(
      int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
    if (requestCode != permissionCode || successCallback == null || !requestInProgress) {
      return false;
    }
    requestInProgress = false;
    int grantResult = grantResults[0];
    this.successCallback.onSuccess(grantResult == PackageManager.PERMISSION_GRANTED ? 1 : 0);
    return true;
  }
```

**Comment by xkxeeshankhan** [comment]
Any est. on when the above fix will be available 🙏 , I've to roll-out the new version for my app, with this fix asap, as the app crash rate is going up :)

**Comment by russellwheatley** [comment]
@xkxeeshankhan  This will be released tomorrow. I have a fix but I'm having issues locally which is holding up the PR.

**Comment by NaagAlgates** [comment]
Thanks @nachikamod  , rolling back to 12.0.3 did work.
