### ISSUE TITLE
Firebase exceptions are useless

### ISSUE THREAD

**Issue by JCKodel** [firebase/flutterfire#9434]
Using the Flutter Crashlytics plugin and having some devices with issues on layout (width or height overflow), Firebase shows us this:

![image](https://user-images.githubusercontent.com/379339/186757091-229008d7-cfcc-4f0c-85bf-ca1380186229.png)

But there is no information whatsoever what widget is to blame (that would be our code), making this issue hard to track and utterly useless.

**Comment by darshankawar** [comment]
@JCKodel 
Can you provide the stacktrace in properly formatted text along with what exactly are you looking in the logs when Firebase exception occurs ?

Also, would be good to have a minimal code sample that will trigger the current exception along with expected entries in the log you are looking for.

**Comment by JCKodel** [comment]
The whole point of this bug is: I don't know where the exception is.

Clearly, is when a widget is drawn in a space where it doesn't fit (then, in debug, it draws on the screen that the widget was overflown by N pixels).

The bug is: it really doesn't matter exceptions or stack trace of Flutter framework, but only our code (or, at least, the user class that caused the bug).

This is a sample causing an overflow:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Card(
          child: Padding(
            padding: const EdgeInsets.all(16),
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Padding(
                  padding: const EdgeInsets.symmetric(horizontal: 16),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: const [
                      Text("Flutter Clutter", style: TextStyle(fontSize: 18)),
                      Text("Internationalization (i18n) in Flutter: an easy and quick approach"),
                    ],
                  ),
                ),
                const Spacer(),
                const Text("03.03.2020"),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```

There are no stack trace because it is not an exception we can handle (it doesn't trigger the debugger, even with breakpoint at all exceptions). Only a log is displayed:

```
════════ Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during layout:
A RenderFlex overflowed by 182 pixels on the right.

Widget creation tracking is currently disabled. Enabling it enables improved error messages. It can be enabled by passing `--track-widget-creation` to `flutter run` or `flutter test`.
The overflowing RenderFlex has an orientation of Axis.horizontal.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.

Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the RenderFlex to fit within the available space instead of being sized to their natural size.
This is considered an error condition because it indicates that there is content that cannot be seen. If the content is legitimately bigger than the available space, consider clipping it with a ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex, like a ListView.
```

But the exception, with the Flutter internal stack trace, goes to Firebase anyway (without any kind of information about offending user code).

I'm pretty sure this is a Flutter bug (or lack of decent information), but they told me to open a bug here instead =\

**Comment by darshankawar** [comment]
Thanks for the update. I think what you are looking for is to see widget details in the stacktrace, something like https://github.com/flutter/flutter/issues/103264, so I suggest you to follow-up in it for further updates. The logs are triggered by framework itself and displayed using flutter_tool in the console, so, this use case is not specific to flutterfire.

Closing from here and sorry for inconvenience on going back and forth between repos.
