### ISSUE TITLE
🐛 [firebase_messaging] getInitialMessage() returns RemoteMessage.notification only first time.

### ISSUE THREAD

**Issue by tania628** [firebase/flutterfire#9438]
## Bug report

**Describe the bug**
When have multiple notifications and open app from each notification on app terminated state,  getInitialMessage() returns RemoteMessage.notification only first time.  

https://user-images.githubusercontent.com/65319868/187142147-bb8a3247-b280-4343-9d9d-b648b29c64dc.mp4

### Expected behavior
I thought the return value of getInitialMessage() always contained the Notification.

### Sample code
<details><summary>Click To Expand</summary>

```
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';

import 'firebase_options.dart';

void main() async{
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  final token = await FirebaseMessaging.instance.getToken();

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'SAMPLE',
      home: Home(),
    );
  }
}

class Home extends StatefulWidget{
  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('SAMPLE'),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            FirebaseMessaging.instance.getInitialMessage().then((message){

              if (message == null) {
                showDialog(
                    context: context,
                    builder: (context)
                    => AlertDialog(
                      content: Text('NO initialMessage.'),
                    ));
                return;
              }

              if(message.notification == null) {
                showDialog(
                    context: context,
                    builder: (context) =>
                        AlertDialog(
                          title: Text('message.notification IS NULL'),
                          content: Text(message.data['test']),
                        ));
                return;
              }

              showDialog(
                  context: context,
                  builder: (context) =>
                      AlertDialog(
                        title: Text(message.notification!.title ?? 'null'),
                        content: Text(message.notification!.body ?? 'null'),
                      ));
            });
          },
          child: Text('getInitialMessage()'),
        ),
      ),
    );
  }
}
```
</details>

---

### Flutter doctor

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel stable, 3.0.4, on Microsoft Windows [Version 10.0.19043.1889], locale ja-JP)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.70.2)
[√] Connected device (3 available)
[√] HTTP Host Availability
```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
Dart SDK 2.17.5
Flutter SDK 3.0.4
SAMPLE 1.0.0+1

dependencies:
- firebase_core 1.21.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 13.0.0 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]

dev dependencies:
- build_runner 2.2.0 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server
 io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channe
l string_scanner term_glyph]

transitive dependencies:
- _fe_analyzer_shared 46.0.0 [meta]
- analyzer 4.6.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- args 2.3.1
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.3.0 [analyzer async convert crypto glob logging meta path]
- build_config 1.1.0 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.1.0 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.9 [analyzer async build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.2.3 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.4.1 [built_collection collection fixnum meta]
- characters 1.2.0
- charcode 1.3.1
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- clock 1.1.0
- code_builder 4.2.0 [built_collection built_value collection matcher meta]
- collection 1.16.0
- convert 3.0.2 [typed_data]
- crypto 3.0.2 [typed_data]
- dart_style 2.2.3 [analyzer args path pub_semver source_span]
- fake_async 1.3.0 [clock collection]
- file 6.1.4 [meta path]
- firebase_core_platform_interface 4.5.1 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 1.7.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 4.1.3 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.1.3 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- fixnum 1.0.1
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- frontend_server_client 2.1.3 [async path]
- glob 2.1.0 [async collection file path string_scanner]
- graphs 2.1.0 [collection]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- io 1.0.3 [meta path string_scanner]
- js 0.6.4
- json_annotation 4.6.0 [meta]
- logging 1.0.2
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.4
- meta 1.7.0
- mime 1.0.2
- package_config 2.1.0 [path]
- path 1.8.1
- plugin_platform_interface 2.1.2 [meta]
- pool 1.5.1 [async stack_trace]
- pub_semver 2.1.1 [collection meta]
- pubspec_parse 1.2.1 [checked_yaml collection json_annotation pub_semver yaml]
- shelf 1.3.2 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.2 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_span 1.8.2 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.9 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timing 1.0.0 [json_annotation]
- typed_data 1.3.1 [collection]
- vector_math 2.1.2
- watcher 1.0.1 [async path]
- web_socket_channel 2.2.0 [async crypto stream_channel]
- yaml 3.1.1 [collection source_span string_scanner]
```

</details>

---

**Comment by darshankawar** [comment]
@tania628 
Thanks for the report. I think, the `null` you are getting could be expected, because, `getInitialMessage()` is an asynchronous method that returns a `RemoteMessage` if the app was opened from a terminated state which in true in your case. 
The method also consumes the initial `RemoteMessage` and any calls to it after the first will return `null`.

Can you also try the official plugin [example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example) and see if, using it still gives you same behavior ?

**Comment by tania628** [comment]
@darshankawar 
Thank you for your comment.
I tried the official plugin example and I got same bihavior.

https://user-images.githubusercontent.com/65319868/187326422-9d5f09a2-5c2a-4d84-9b92-f32ae14af691.mp4


Steps to reproduce the behavior:

1. Confirm app is terminated state.
2. Send two messages from Firebase Console.
3. Open app from a notification.
4. Tap [getInitialMessage()] button.
5. RemoteMessage.notification **exists** this time.
6. Exit the app.
7. Open app from another notification.
8. Tap [getInitialMessage()] button.
9. RemoteMessage exists, but RemoteMessage.notification **not exists** this time.
In addition, it seems that "From", "Sent Time", and "Android Properties" cannot be obtained.

As a side note, I used "Send Test Message" in Firebase Console to send messages,
only changed notification title and body.

**Comment by darshankawar** [comment]
Thanks for the details. Can you try [this](https://github.com/firebase/flutterfire/issues/7580#issuecomment-996399213) solution and see if it works in your case ?

**Comment by tania628** [comment]
What should I check with [this](https://github.com/firebase/flutterfire/issues/7580#issuecomment-996399213)?

I think these notifications are being displayed by Android OS because app state is terminated.
I tried that but `notificationAppLaunchDetails.didNotificationLaunchApp` was `false` any time.

**Comment by darshankawar** [comment]
Thanks for feedback. I am wondering if this has to do with the fact that you have multiple notifications and then tapping on it one by one.
Does it show `null` if you send one notification in terminated state, tap on it (which should show value), then send another notification and then tap on it ?

Just make there there are no earlier notifications already present and start from scratch.

**Comment by tania628** [comment]
> I am wondering if this has to do with the fact that you have multiple notifications and then tapping on it one by one.

Yes, I think this has to do with the fact I have multiple notifications.

> Does it show `null` if you send one notification in terminated state, tap on it (which should show value), then send another notification and then tap on it ?

No, it doesn't show `null`. In the following order, it not be `null`.
1. Confirm app is terminated state.
2. Send first message from Firebase Console.
3. Open app from a notification.
4. Tap [getInitialMessage()] button.
5. **RemoteMessage.notification exists.**
6. Exit the app, and confirm app is terminated state and no notifications.
7. Send second message from Firebase Console.
8. Open app from a notification.
9. Tap [getInitialMessage()] button.
10. **RemoteMessage.notification also exists.**

incidentally, when I send two notifications in terminated state, 
open app from one notification and the other open in background state, 
(second notification should be handled in `onMessageOpenedApp`)
I can get `RemoteMessage.notification`.

**Comment by tania628** [comment]
I also found a similar issue with the following steps.

1. Open app from launch icon and put app in background (e.g. show home screen).
2. Send a notification from Firebase Console.
3. Exit the app from task manager.
4. Open app from a notification (sent in step 2).
5. Tap [getInitialMessage()] button.
6. RemoteMessage exists, but RemoteMessage.notification **_not exists_**.

**Comment by darshankawar** [comment]
> Yes, I think this has to do with the fact I have multiple notifications and then tapping on it one by one in terminated state.
> 
> > Does it show `null` if you send one notification in terminated state, tap on it (which should show value), then send another notification and then tap on it ?
> 
> No, it doesn't show `null`. In the following order, it not be `null`.

Thanks for confirming this behavior. Since it works properly per notification, I am not sure if in the case of multiple notifications and then tapping on them one by one, the behavior you are seeing is not expected or is WAI.



> * Open app from launch icon and put app in background (e.g. show home screen).
> * Send two notifications from Firebase Console.
> * Exit the app from task manager.
> * Open app from one notification (sent in step 2).
> * Tap [getInitialMessage()] button.
> * RemoteMessage exists, but RemoteMessage.notification **_not exists_**.
> * Open the other notification (it should be handled in onMessageOpenedApp).
> * RemoteMessage exists, but RemoteMessage.notification **_not exists_**.

Here you are sending two notifications back to back and then tapping on them one by one. In such case, the `RemoteMessage` is already consumed when you tap on first notification and will be null as it is consumed already, and then tapping on another notification when app is in same state, the `RemoteMessage` is `null` and hence you are getting `null` which is expected.



> 1. Open app from launch icon and put app in background (e.g. show home screen).
> 2. Send a notification from Firebase Console.
> 3. Exit the app from task manager.
> 4. Open app from a notification (sent in step 2).
> 5. Tap [getInitialMessage()] button.
> 6. RemoteMessage exists, but RemoteMessage.notification **_not exists_**.

I think, in this case, since you are exiting / quitting the app from settings / task manager, it is considered to be terminated and in that case, according to the documentation:

`On Android, if the user force quits the app from device settings, it must be manually reopened again for messages to start working.`

**Comment by tania628** [comment]
I know that document, and the documentation says, `if the user force quits the app from device settings`.
Actually, all function at FCM doesn't work when I do a [FORCE STOP] in [Settings]->[Apps]->[(this app)]->[App Info].

I've said many time, `RemoteMessage` **IS NOT NULL**, `notification` in `RemoteMessage` **IS NULL**.

I understood that it's a trivial issue for you.
I’ll refrain from telling you any more about this issue. Thank you.
