### ISSUE TITLE
🐛 [cloud firestore web] some time(40%) query by timestamp return empty, but on mobile it is working well

### ISSUE THREAD

**Issue by LiangHuangBC** [firebase/flutterfire#9447]
## Bug report

**Describe the bug**
 ```
Query query = org
        .collection("myCol")
        .doc("docId")
        .collection('subCol')
        .where("readTimes", arrayContains: timestamp);
```
"timestamp" after arrayContains is from doc fetched by other query, and then put it here as a condition.\
On android and ios it is working as expected, but on web, it cannot fetch any doc.

Tested on it many times, about 40% it is doesn't work, and if a doc cannot be fetched, it is same result among different tests.
And also printed timestamp and compare between web and android, exactly same value.....  so weird.
---

### Flutter dependencies

My pubspec.yaml
 firebase_core: ^1.20.1
 cloud_firestore: ^3.4.4

Also tried core 1.21.1 and cloud_firestore 3.4.6, doesn't work.
 
---

**Comment by darshankawar** [comment]
@LiangHuangBC 
Thanks for the report. Can you provide `flutter doctor -v`, expected vs actual result you are getting in prooperly formatted text along with a minimal code sample ?

**Comment by LiangHuangBC** [comment]
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.5.1 21G83 darwin-x64, locale en-CA)
    • Flutter version 3.3.0 on channel stable at /Users/lianghuang/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (8 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/lianghuang/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • ANDROID_HOME = /Users/lianghuang/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/lianghuang/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.5.1 21G83 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by LiangHuangBC** [comment]
BTW, on my web app, there is no local cache.  No index.html changed either, all injected.

**Comment by darshankawar** [comment]
Thanks for the update. I am unable to replicate this behavior using plugin's [example](https://github.com/firebase/flutterfire/tree/master/packages/cloud_firestore/cloud_firestore/example) and running on web.





> "timestamp" after arrayContains is from doc fetched by other query, and then put it here as a condition.

Is it possible to directly pass the `timestamp` rather than using the result of other query and see if you still get same behavior or not ?

Also, since you said it is not consistent and happens only sometimes, it probably may not be an issue from client side.

**Comment by LiangHuangBC** [comment]
Thanks for your reply.

timestamp is generate by FieldValue, it is hard to get its value without query.
On Android,  query by timestamp is always working well, seams like JavaScript package did something wrong....

**Comment by darshankawar** [comment]
Thanks for the feedback. I am unable to replicate this behavior using the plugin example running on web, so I am keeping this issue open and labeling for further insights from the team.

**Comment by russellwheatley** [comment]
Hey @LiangHuangBC, If you can provide a repro that would be helpful, otherwise there isn't much we can do.

**Comment by Lyokone** [comment]
We updated how Timestamp are being handled on Web for Firestore, please update to the latest cloud_firestore version. Feel free to reopen if it's still happening.
