### ISSUE TITLE
🐛 [firebase_auth] auth stream changing value when it's not suposed to change - web

### ISSUE THREAD

**Issue by Macacoazul01** [firebase/flutterfire#9451]
When I change my web navigator's size, the user stream changes it's value, making my whole app rebuild (as it looks for the signed state of the user).

I don't know when it started happening, but this wasn't always here (maybe it's related to some recent updates).

Seems related to `ScreenUtilInit` as if I don't wrap the app with it, the error doesn't occur

Here is a sample project with the error that simulates my app's behavior (there's only the need to set up firebase config):
[firebase auth.zip](https://github.com/firebase/flutterfire/files/9465770/firebase.auth.zip)

package versions:
`firebase_core: 1.21.1`
`firebase_auth: 3.7.0`

my flutter doctor:

```
[√] Flutter (Channel unknown, 3.0.5, on Microsoft Windows [versao 10.0.22000.918], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.70.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.
```

**Comment by Macacoazul01** [comment]
related to https://pub.dev/packages/flutter_screenutil 5.5.1 to 5.5.2 transition

**Comment by darshankawar** [comment]
Thanks for the report @Macacoazul01.



> Seems related to `ScreenUtilInit` as if I don't wrap the app with it, the error doesn't occur

Per this, would be good to follow-up in dedicated repo. If this is happening without any third party plugin, then we would taken this issue forward, or if you are able to replicate the same only with `firebase_auth` and `firebase_core` on web, then, please provide an updated code sample that we can use to analyze further.

**Comment by Macacoazul01** [comment]
@darshankawar the problem happens because the package does some sort of "set state" on the app with the navigator size's change, to force the variables to refresh.

I've forced a set state after some seconds to replicate what occurs after the size changes and this is the log ('changed' in the log means that the user stream `authStateChanges()` was executed):

![image](https://user-images.githubusercontent.com/57464965/188290280-6267aefa-6843-4a82-9ba5-69b1c0165507.png)

this issue is more like a "where should I put the user stream" than a firebase problem.

Here's the sample code:
[firebase auth.zip](https://github.com/firebase/flutterfire/files/9483534/firebase.auth.zip)

**Comment by darshankawar** [comment]
Thanks for the update. Keeping this issue open for further insights from the team.

/cc @russellwheatley

**Comment by Macacoazul01** [comment]
The tree on the real project is like:

Size handler {
  Material app{
    User stream {
      Rest of the app{}
    }
  }
}

**Comment by Lyokone** [comment]
Hello, we released [firebase_auth_web](https://pub.dev/packages/firebase_auth_web/changelog) 5.2.0 that should fix this. Please update firebase_auth.
