### ISSUE TITLE
🐛 [cloud_firestore_odm] Support reusing the same class for multiple collections

### ISSUE THREAD

**Issue by Rexios80** [firebase/flutterfire#9452]
## Bug report

Attempting to use the same class for multiple sub collections creates duplicate generated classes

### Steps to reproduce

Run the ODM generator on the following code:
```dart
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:cloud_firestore_odm/cloud_firestore_odm.dart';
import 'package:json_annotation/json_annotation.dart';

part 'firestore.g.dart';

@JsonSerializable()
class Data {}

@Collection<Data>('data')
@Collection<Data>('data/*/data1')
@Collection<Data>('data/*/data2')
final dataRef = DataCollectionReference();
```

### Expected behavior

Give a way to provide your own class name prefixes

### Sample project

Making my own PR

**Comment by rrousselGit** [comment]
That's not really a bug but rather a new feature

**Comment by Rexios80** [comment]
Closed with the mentioned PR
