### ISSUE TITLE
🐛 [cloud_firestore] `collectionGroup` using `get()` throws `[cloud_firestore/unavailable] The service is currently unavailable.`

### ISSUE THREAD

**Issue by Shawn-sudo** [firebase/flutterfire#9457]
Fetching documents using collectionGroup() throws "unavailable" error in certain circumstances.

This results in an error:
1. Turn off wifi and cellular data (no internet connection) before the app is opened
2. Launch the app
3. Call `FirebaseFirestore.instance.collectionGroup("helloo").where(abcde).limit(1234).get()`
4. [cloud_firestore/unavailable] The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff.

Weirdly, if I do step 1. after doing 2. and 3. (2 --> 3 --> 1 --> ...), further `collectionGroup(...).get()` calls don't result in the error and gets docs from the cache as expected.

**Comment by darshankawar** [comment]
> 1. Turn off wifi and cellular data (no internet connection) before the app is opened

@Shawn-sudo Any network related operation / behavior is not likely to be a Flutterfire issue, because the plugin is a wrapper around native Firebase sdks and send, receive data through Dart.

I suggest you to raise this issue in underlying Firebase sdk (ios, web or android).



> 4\. [cloud_firestore/unavailable] The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff.

For this, please follow-up in similar / related discussion thread: https://github.com/firebase/flutterfire/discussions/5708

Closing from here. For network related behavior, if you get directed here, write in comments and I'll reopen this issue.

**Comment by Shawn-sudo** [comment]
@darshankawar Umm so hi again!
I was trying to work it out at https://github.com/firebase/firebase-ios-sdk/issues/10164 , but we couldn't find a way to solve it.
While hanging around there, I also tested it on Android with Flutter, and figured out that fetching documents from cache using `collectionGroup query` (no internet) also fails on Android. Just like on iOS, fetching documents from cache using `collection query` worked well. It was only `collectionGroup query` that didn't work.
I'm not sure if collectionGroup offline fetching works well on native iOS and native Android, but since it didn't work on both platforms with flutter, I'm guessing that this is an issue of flutterfire.

**Comment by darshankawar** [comment]
Thanks for feedback. Reopening.

**Comment by darshankawar** [comment]
@Shawn-sudo 
Can you try below and see if it helps ?

`get(GetOptions(source: Source.cache))`

**Comment by Shawn-sudo** [comment]
@darshankawar No luck :/
<img src="https://user-images.githubusercontent.com/60294318/190948466-27971183-4acf-459f-a71d-de96d699bf57.PNG" width=300 />
I experienced the same error with the option set.

**Comment by darshankawar** [comment]
@Shawn-sudo 
I tried the scenario and ran it on iOS device which gave me proper results without throwing the reported error.

1. Firestore db setup:

<img width="722" alt="Screenshot 2022-09-19 at 2 06 00 PM" src="https://user-images.githubusercontent.com/67046386/190979562-8a15bdd9-1e85-4296-ae1e-28070a25b656.png">

2. `final Stream<QuerySnapshot> _usersStream = FirebaseFirestore.instance.collectionGroup('testCollection').where('1').limit(1).snapshots();`

3. Used it in `StreamBuilder` as below:

```
body: StreamBuilder<QuerySnapshot>(
        stream: _usersStream,
        builder: (BuildContext context, AsyncSnapshot<QuerySnapshot> snapshot) {
        //  print(snapshot);
          if (snapshot.hasError) {
            return Text('wrong');
          }
          return ListView(
            children: snapshot.data!.docs.map((DocumentSnapshot document) {
              Map<String, dynamic> data = document.data()! as Map<String, dynamic>;
              return ListTile(
                title: Text(data['name'].toString()),
                subtitle: Text(data['uid'].toString()),
              );
            }).toList(),
          );
        },
      )
```

4. Turned OFF cellular and wifi on the device and ran the app which gave me below result in UI:

<img width="750" alt="Screenshot 2022-09-19 at 2 09 32 PM" src="https://user-images.githubusercontent.com/67046386/190980139-7bf0bc5f-083e-411b-bcc0-7bc374df83c8.png">

Please try the same and see if it helps. I am on latest master version of the framework.

**Comment by darshankawar** [comment]
> @darshankawar No luck :/ <img alt="" width="300" src="https://user-images.githubusercontent.com/60294318/190948466-27971183-4acf-459f-a71d-de96d699bf57.PNG"> I experienced the same error with the option set.

Also check if this helps https://github.com/firebase/flutterfire/issues/6076#issuecomment-1090035730

**Comment by Shawn-sudo** [comment]
Hi @darshankawar, thanks for your efforts!

You used `collectionGroup.snapshot()` while I used `collectionGroup.get()`. I wondered if `.get()` is the only case that causes this issue, so I tested it. I figured out that `collectionGroup.get()` fails while `collectionGroup.snapshot()` (realtime listening) succeeds with no internet connection.

**Comment by darshankawar** [comment]
Thanks for the update. I see that using `collectionGroup.get()` shows the error as reported, but I am not sure if this would fall under client sdk or at native level.

Keeping this issue open and labeling for expected behavior for this scenario.

**Comment by loolooii** [comment]
I don't think this is only limited to `collectionGroup` queries. I don't have any collectinGroup queries and I'm getting the same error using iOS simulator. I'm using `4.3.1`.

**Comment by loolooii** [comment]
Update: `Erase All Content and Settings...` in `Menu` -> `Device` "solved" this problem for now. Could be a temporary solution. Nevertheless, should be looked at I guess.

**Comment by Lyokone** [comment]
hey 👋 we have heavily reworked Cloud Firestore implementation, do you still experience this issue?
