### ISSUE TITLE
🐛 [firebase_messaging] `getInitialMessage` returns `null` on iOS

### ISSUE THREAD

**Issue by Tom3652** [firebase/flutterfire#9462]
## Bug report

**Describe the bug**

I am calling `RemoteMessage? message = await  FirebaseMessaging.instance.getInitialMessage();` on my app to open a specific page when the user clicks on the push notification. 

On Android the `message` var above is not `null` and the page is pushed. 
On iOS, the `message` var above is `null` when the user opens the app after touching a push notification.

I am using the `firebase_messaging: 13.0.0` version.

### Steps to reproduce

1. Setup Firebase FCM to work with iOS
2. Run the sample code
3. Send a remote notification
4. Tap on the notification on your device with the app `terminated`
5. See that it doesn't push the new page

### Expected behavior

The method should not return null as it is done on Android when there is an actual `RemoteMessage`.

### Sample project

```dart
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';


Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(const TestApp());
}

class TestApp extends StatelessWidget {
  const TestApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: HomePage()
    );
  }
}

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {

  Future<void> test() async {
    RemoteMessage? message = await FirebaseMessaging.instance.getInitialMessage();
    if (message != null) {
      Navigator.push(context, MaterialPageRoute(builder: (ctx) =>
          Scaffold(body: Center(
            child: Text("Page pushed from getInitialMessage"),),)));
    }
  }

  @override
  void initState() {
    test();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold();
  }
}
```

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.5.1 21G83 darwin-x64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.70.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

---

**Comment by Tom3652** [comment]
I must say that it's working half of the time on iOS. 

Yesterday i could see that it's working on 1/2 notifications in `release` mode. 

I am sending push notifications from my server with the admin sdk in python.
I have setup the `notification` and the `data` in the `RemoteMessage` the same way for Android and iOS.

**Comment by darshankawar** [comment]
@Tom3652 
Can you take a look at this PR https://github.com/firebase/flutterfire/pull/9292, wherein, the plugin example was updated to confirm that messaging handlers work as expected. 

I had also used the plugin example and verified that, in terminated state, when a notification is triggered using the `script` added in the plugin and run using node js, the notification is received and tapping on it directs the user towards an app screen.

**Comment by Tom3652** [comment]
Hey @darshankawar, it's working with the PR and also in my app (half of the time) so i don't know what else to try. 
Note : i have checked the PR and i see it fixes especially background messaging not invoked and `onMessageOpenedApp` (both methods that always worked in my app) 

I am guessing there is some race condition maybe using `getInitialMessage()` from a terminated state but i can't reproduce it 100% so... It's not a blocking feature in my app either but i prefer raise the ticket in case there is something beneath. 

I will try to catch the error if there is any

**Comment by hatemragab** [comment]
I have run the example provided with the package and same problem!
