### ISSUE TITLE
File google-services.json is missing.

### ISSUE THREAD

**Issue by sderungs99** [firebase/flutterfire#9468]
Hi,

Not sure if this is missing in the documentation, or there is something wrong with my project, but when configuring my app using the flutterfire CLI, I keep getting the following error during Android building:

```
 File google-services.json is missing. The Google Services Plugin cannot function without it. 
```
My understanding was the this was required before the app could be configured for Firebase via the flutterfire CLI, but maybe I am wrong and in fact I still need to google-services.json file? If that is the case, then certainly this is not mentioned in the documentation :-)

Anybody can advise?

**Comment by darshankawar** [comment]
> My understanding was the this was required before the app could be configured for Firebase via the flutterfire CLI,

This correct. With new dart only initialization, we don't need to do manual installation, as `flutterfire configure` writes the native config files to the root of our app.


> File google-services.json is missing. The Google Services Plugin cannot function without it.

This isn't actually an error, but a warning log coming from native firebase sdk which you can safely ignore.

See [this](https://firebase.flutter.dev/docs/cli/#usage) document for your reference.

With this, I am going ahead and closing. If you disagree, write in comments and I'll reopen it.

**Comment by sderungs99** [comment]
Hi @darshankawar  , thanks for coming back so quickly! The link you added refers to the iOS warning. I have no issue with building for iOS (without the google services file). What I am quoting above is an actual error while building for Android (`flutter build appbundle`). Here is a bigger snippet of the output:

```
💪 Building with sound null safety 💪

Running Gradle task 'bundleRelease'...                          

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processReleaseGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  /home/runner/work/sglandtransport/sglandtransport/android/app/src/release/google-services.json
  /home/runner/work/sglandtransport/sglandtransport/android/app/src/google-services.json
  /home/runner/work/sglandtransport/sglandtransport/android/app/src/Release/google-services.json
  /home/runner/work/sglandtransport/sglandtransport/android/app/google-services.json
```

If google-services.json is truly not required anymore when using dart initialization, maybe someone could point me to what might be responsible for it to still look for this file?

**Comment by darshankawar** [comment]
Thanks for the feedback. Reopening.

**Comment by darshankawar** [comment]
Can you provide your `flutter doctor -v`, `pubspec.yaml` ?

**Comment by enveraltin** [comment]
Having the same problem.

**Comment by darshankawar** [comment]
Thanks for the update. I looked at the setup documentation but didn't find reference for that issue: https://firebase.google.com/docs/flutter/setup?platform=android

The one that I found and referenced above is from old documentation and mostly for iOS: https://firebase.flutter.dev/docs/cli/#usage

Also, since this is occuring on Android, according to [this](https://firebase.flutter.dev/docs/overview#using-the-flutterfire-cli) old reference documentation, after initializing Flutterfire, it adds the `Google services Gradle plugin` automatically in `build.gradle` file.


Keeping this issue open for further insights on this behavior.

/cc @kevinthecheung  @russellwheatley

**Comment by erf** [comment]
I'm experiencing the same issue: missing `google-services.json` file.

I'd like to support multiple environments via the code generated from the `flutterfire configure` command.

Now if i leave the `google-services.json` file in, and pass the generated options, i get a `duplicateApp` exception thrown in `method_channel_firebase.dart` line 134, because the apiKeys differs.

**Comment by russellwheatley** [comment]
Have you updated the FF CLI? 

Run: `dart pub global activate flutterfire_cli`. 

The service files are now written to the project for android & iOS as dart initialization was causing unforeseen problems.

**Comment by sderungs99** [comment]
Hi @russellwheatley , I was on 0.2.4 and have now upgrade to the latest, which seems to be 0.2.6. However, running `flutterfire configure` on my project does not update anything. I guess that means it is still trying to do the same configuration. Can you elaborate more on your comment around "service files are now written to the project..."?

**Comment by russellwheatley** [comment]
Your service file ought to be here `android/app/google-services.json` in your project directory after running `flutterfire configure`. Do you see it, @sderungs99?

**Comment by sderungs99** [comment]
Oh, the CLI creates the google-services.json file in addition to the firebase_options.dart file now! Yes, I can see how it generates that file.

So in summary, to confirm my understanding:
- For Android, both google-services.json as well as firebase_options.dart are needed, and the CLI creates both
- For iOS, both GoogleService-Info.plist as well as firebase_options.dart are needed, and the CLI creates both

Correct?

And somehow related, is it safe to check-in the google-services.json and the GoogleService-Info.plist in my public repo? Or should `flutterfire configure` be executed as part of the build pipeline so the files get generated when building?

**Comment by russellwheatley** [comment]
>So in summary, to confirm my understanding:

>For Android, both google-services.json as well as firebase_options.dart are needed, and the CLI creates both
>For iOS, both GoogleService-Info.plist as well as firebase_options.dart are needed, and the CLI creates both

`firebase_options.dart` - you can remove the android & iOS initialization code from here if you wish as your app will use the service files instead. You will need to keep web initialization config though if you have a web app.

>And somehow related, is it safe to check-in the google-services.json and the GoogleService-Info.plist in my public repo? Or >should flutterfire configure be executed as part of the build pipeline so the files get generated when building?

Yes, the service files can be checked in. They don't hold any secrets. You ought to provide rules on your Firebase console to protect your services (e.g. Firestore, Storage, etc).

**Comment by sderungs99** [comment]
Thank you, @russellwheatley! As far as I am concerned, this issue can be closed, unless you want to address @erf 's issue here has well?

**Comment by darshankawar** [comment]
Closing this based on above comment. 

> unless you want to address @erf 's issue here has well?

That sounds like an enhancement for `flutterfire configure` cli tool which is tracked in different repo.

**Comment by balaji101010** [comment]
What's the solution? Can someone mention it please?
