### ISSUE TITLE
🐛 [firebase_app_check] AppCheck not working for iOS after following documentation - all 'Unverified: Invalid requests'.

### ISSUE THREAD

**Issue by lukertaylor** [firebase/flutterfire#9484]
### Steps to reproduce
1. Create simple app that writes to Firestore
2. Add Firebase to your Flutter app - https://firebase.google.com/docs/flutter/setup?platform=ios
3. Configure DeviceCheck on Apple platforms - https://firebase.google.com/docs/app-check/ios/devicecheck-provider
4. Add the App Check to your app - https://firebase.google.com/docs/app-check/flutter/default-providers

Test by running app with 'flutter run --release' with a connected physical iPhone 6s device.

### Expected behavior

App requests to Firestore would be verified. But instead they are all 'Unverified: Invalid requests'.

### Sample project

[Sample project on GitHub](https://github.com/lukertaylor/app_check_test)

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
luke@Lukes-Air app_check_test % flutter doctor -v
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.5.1 21G83 darwin-arm, locale en-GB)
    • Flutter version 3.3.0 on channel stable at /Users/luke/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (8 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/luke/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13A1030d
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at /Users/luke/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-arm64 • macOS 12.5.1 21G83 darwin-arm

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
luke@Lukes-Air app_check_test % flutter pub deps -- --style=compact
Dart SDK 2.18.0
Flutter SDK 3.3.0
app_check_test 1.0.0+1

dependencies:
- cloud_firestore 3.4.6 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.5
- device_info_plus 4.1.2 [flutter device_info_plus_platform_interface device_info_plus_macos device_info_plus_linux device_info_plus_web device_info_plus_windows]
- firebase_app_check 0.0.7 [firebase_app_check_platform_interface firebase_app_check_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 1.21.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]

dev dependencies:
- flutter_lints 2.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- async 2.9.0 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.1
- clock 1.1.1
- cloud_firestore_platform_interface 5.7.3 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.8.6 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.16.0
- device_info_plus_linux 3.0.0 [device_info_plus_platform_interface file flutter meta]
- device_info_plus_macos 3.0.0 [device_info_plus_platform_interface flutter]
- device_info_plus_platform_interface 3.0.0 [flutter meta plugin_platform_interface]
- device_info_plus_web 3.0.0 [device_info_plus_platform_interface flutter_web_plugins flutter]
- device_info_plus_windows 4.0.0 [device_info_plus_platform_interface ffi flutter win32]
- fake_async 1.3.1 [clock collection]
- ffi 2.0.1
- file 6.1.4 [meta path]
- firebase_app_check_platform_interface 0.0.4+15 [firebase_core flutter meta plugin_platform_interface]
- firebase_app_check_web 0.0.6+4 [firebase_app_check_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_core_platform_interface 4.5.1 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 1.7.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- js 0.6.4
- lints 2.0.0
- matcher 0.12.12 [stack_trace]
- material_color_utilities 0.1.5
- meta 1.8.0
- path 1.8.2
- plugin_platform_interface 2.1.2 [meta]
- sky_engine 0.0.99
- source_span 1.9.0 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.1 [source_span]
- term_glyph 1.2.1
- test_api 0.4.12 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- vector_math 2.1.2
- win32 2.7.0 [ffi]
```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the report @lukertaylor 

Can you also confirm that you have registered your debug token on Firebase console ? https://firebase.google.com/docs/app-check/ios/debug-provider


Also, from the error log you provided, it seems to be coming from `exchangeDeviceCheckToken` endpoint which seems to be different from `exchangeDebugToken` which usually is the first step followed by `DevicCheckToken`

**Comment by lukertaylor** [comment]
Hi @darshankawar 

Thank you for responding.

With the app that I am developing, I have been trying to get AppCheck for iOS working for about 3 weeks now.

I realise now that my bug report was wrong because I was running in debug mode rather than release mode.

As an aside, I have tested with a debug token for the device, and that works fine.

But running the above simple app in release mode does not work. Neither does my app when deploying via TestFlight.

I have now amended this issue title and bug description. Apologies for the initial confusion.

**Comment by darshankawar** [comment]
Thanks for the feedback and update. Using the sample project and integrating with local Firebase project, I seem to be getting same error as reported, ie, `'Unverified: Invalid requests'.`.

There was a similar / related issue but for Android, ie, following the documentation, the appCheck debug token was not getting activated: https://github.com/firebase/flutterfire/issues/9060

**Comment by lukertaylor** [comment]
Hello @darshankawar 

I don't think issue you reference will help me.

Do you think anyone will have time to look into this? Or should I look at backing-out all AppCheck and relying only on Firestore rules?

Luke

**Comment by darshankawar** [comment]
> I don't think issue you reference will help me.

That issue  is more for team's reference.


> Do you think anyone will have time to look into this? Or should I look at backing-out all AppCheck and relying only on Firestore rules?

I will try to forward it for their quick look.

**Comment by lukertaylor** [comment]
Thanks.

I have removed App Check from my app for now because it was holding me back from releasing to the App Store.

I'll add it back in if/when there is a solution.

**Comment by HSCOGT** [comment]
Currently experiencing the same issue with App Check and Firebase Callable Functions, AppCheck was configured with App Attest. Whenever I call the function `context.app` is always undefined, hence failing the verification.

**Comment by HSCOGT** [comment]
Ok, for anyone experiencing the same issue, this might help. I'm currently using an older version of App Check (v0.0.6+12, I can't spend time updating my entire dependency tree at the moment due to business goals), that being said, it looks like:

1. This version does not support App Attest and you must opt for DeviceCheck
2. Both services should be enabled ([Reference for this theory](https://github.com/firebase/flutterfire/issues/9266#issuecomment-1201368910))

In any case, I'll suggest an update to the docs, for the former, a disclaimer indicating what version App Attest is supported from, and for the latter, remove any reference to optionality from the texts. Currently, all the docs propose that you can choose only one, the configuration in the console even says:
> Register your app by choosing one or more attestation providers below. Can't decide?

**Comment by russellwheatley** [comment]
The documentation on the Firebase website will be updated soon on how to get iOS debug provider working for Flutter apps. [Here is the documentation](https://github.com/firebase/flutterfire/pull/9445/files#diff-083ecb65b95e80f5073c0f5934e0cac67d95947761a679958a47a07aa3f1152dR21-R79)  which will ultimately appear on the website.
