### ISSUE TITLE
🐛 [firebase_auth] verificationCompletedHandler returns a verificationId with a null value

### ISSUE THREAD

**Issue by gonzalogauto** [firebase/flutterfire#9500]
## Bug report

**Describe the bug**
verificationCompletedHandler inside verifyPhoneNumber function returns a verificationId with a null value inside, but inside codeSentHandler the verificationId is not-null.
### Steps to reproduce

1. Install `firebase_auth: ^3.8.0`.
2. call the verifyPhoneNumber function.
3. add breakpoints inside codeSentHandler() and verificationCompletedHandler() to check the values.

### Expected behavior

verificationCompletedHandler should return a verificationId with a non-null value like codeSentHandler() does. This is needed to do the login without putting the verification code by hand.
### Sample project

```
await _firebaseAuth.verifyPhoneNumber(
  _phoneNumber,
  codeSentHandler: (verificationId, code) {
    print(verificationId); /// here verificationId is not null.
  },
  codeAutoRetrievalTimeoutHandler: (verificationId){

  },
  verificationFailedHandler: (verificationException){
    
  },
  verificationCompletedHandler: (phoneCredentials) {
    print(phoneCredentials.verificationId); /// here verificationId is null.
  },
```

## Additional context

I'm using the latest version of firebase_auth. (`firebase_auth: ^3.8.0`)

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.4 21F79 darwin-arm, locale en-AR)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.70.1)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!```

</details>

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.18.0
Flutter SDK 3.3.0
authentication_repository 1.0.0

dependencies:
- analytics_service 0.0.1 [flutter firebase_analytics]
- chptr_logger 0.0.1 [flutter exception_handling get_it]
- cloud_firestore 3.4.7 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- equatable 2.0.5 [collection meta]
- firebase_auth 3.8.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_database 9.1.4 [firebase_core firebase_core_platform_interface firebase_database_platform_interface firebase_database_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- get_it 7.2.0 [async collection]
- google_sign_in 5.4.1 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- meta 1.8.0
- sign_in_with_apple 4.1.0 [flutter meta sign_in_with_apple_platform_interface sign_in_with_apple_web]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]
- mocktail 0.3.0 [collection matcher test]
- very_good_analysis 3.0.1

transitive dependencies:
- _fe_analyzer_shared 47.0.0 [meta]
- analyzer 4.7.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- args 2.3.1
- async 2.9.0 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.1
- clock 1.1.1
- cloud_firestore_platform_interface 5.7.4 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.8.7 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.16.0
- convert 3.0.2 [typed_data]
- coverage 1.5.0 [args logging package_config path source_maps stack_trace vm_service]
- crypto 3.0.2 [typed_data]
- exception_handling 0.0.1 [firebase_crashlytics flutter]
- fake_async 1.3.1 [clock collection]
- file 6.1.4 [meta path]
- firebase_analytics 9.3.4 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_analytics_platform_interface 3.3.4 [firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.4.2+4 [firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 6.7.0 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 4.4.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core 1.22.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_core_platform_interface 4.5.1 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 1.7.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics 2.8.10 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_crashlytics_platform_interface 3.2.16 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_database_platform_interface 0.2.2+4 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_database_web 0.2.1+6 [firebase_core firebase_core_web firebase_database_platform_interface flutter flutter_web_plugins js]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- frontend_server_client 2.1.3 [async path]
- glob 2.1.0 [async collection file path string_scanner]
- google_sign_in_android 6.1.0 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.5.0 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.3.0 [flutter plugin_platform_interface quiver]
- google_sign_in_web 0.10.2 [flutter flutter_web_plugins google_sign_in_platform_interface js]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- io 1.0.3 [meta path string_scanner]
- js 0.6.4
- logging 1.0.2
- matcher 0.12.12 [stack_trace]
- material_color_utilities 0.1.5
- mime 1.0.2
- node_preamble 2.0.1
- package_config 2.1.0 [path]
- path 1.8.2
- plugin_platform_interface 2.1.2 [meta]
- pool 1.5.1 [async stack_trace]
- pub_semver 2.1.1 [collection meta]
- quiver 3.1.0 [matcher]
- shelf 1.3.2 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 3.0.1 [path shelf shelf_static]
- shelf_static 1.1.1 [convert http_parser mime path shelf]
- shelf_web_socket 1.0.2 [shelf stream_channel web_socket_channel]
- sign_in_with_apple_platform_interface 1.0.0 [flutter plugin_platform_interface meta]
- sign_in_with_apple_web 1.0.1 [flutter flutter_web_plugins sign_in_with_apple_platform_interface js]
- sky_engine 0.0.99
- source_map_stack_trace 2.1.0 [path stack_trace source_maps]
- source_maps 0.10.10 [source_span]
- source_span 1.9.0 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.1 [source_span]
- term_glyph 1.2.1
- test 1.21.4 [analyzer async boolean_selector collection coverage http_multi_server io js node_preamble package_config path pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel typed_data web_socket_channel webkit_inspection_protocol yaml test_api test_core]
- test_api 0.4.12 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- test_core 0.4.16 [analyzer async args boolean_selector collection coverage frontend_server_client glob io meta package_config path pool source_map_stack_trace source_maps source_span stack_trace stream_channel vm_service yaml matcher test_api]
- typed_data 1.3.1 [collection]
- vector_math 2.1.2
- vm_service 9.4.0
- watcher 1.0.1 [async path]
- web_socket_channel 2.2.0 [async crypto stream_channel]
- webkit_inspection_protocol 1.2.0 [logging]
- yaml 3.1.1 [collection source_span string_scanner]
```

</details>

---

**Comment by darshankawar** [comment]
@gonzalogauto 
Thanks for the report. Can you provide which device are you are seeing this behavior on ?
Can you also confirm if the user is already signed in and `verificationCompleted` function gets called ? If it does get called, it automatically signs in and hence you don't need `verificationId`.

**Comment by gonzalogauto** [comment]
After reading this in your comment **"verificationCompleted function gets called ? If it does get called, it automatically signs in and hence you don't need verificationId"** I found out that we made a mistake, we parse PhoneAuthCrendential in a custom object with other name and then when we need to create the PhoneAuthCredential again needs a non-null verificationId. After changing all the code to use only the original PhoneAuthCredential of the package I was able to do the login. Thanks 😄  !

**Comment by darshankawar** [comment]
Glad to help and to know your issue is resolved. Closing.
