### ISSUE TITLE
🐛 [firebase_messaging] FirebaseMessaging.onBackgroundMessage doesn't work with new Flutter versions

### ISSUE THREAD

**Issue by awaik** [firebase/flutterfire#9519]
## Bug report

`FirebaseMessaging.onBackgroundMessage` gives a error in a RELEASE app mode with new Flutter versions.

### Steps to reproduce

1. Create a sample app.
2. It works in debug and profile modes.
4. Run the app in a release moe
5. App receives notifications if it is open - in the foreground mode (so the keys are correct)
6. If you dismiss the app, `FirebaseMessaging.onBackgroundMessage` stops working. Give some weird errors, that you can see with ADB.
7. If you downgrade the Flutter version to 3.0.2 it starts to work.

### Expected behavior

`FirebaseMessaging.onBackgroundMessage` should

**Comment by darshankawar** [comment]
Thanks for the report @awaik.

I believe this is similar to https://github.com/firebase/flutterfire/issues/9446, so solution is as mentioned https://github.com/firebase/flutterfire/issues/9446#issuecomment-1240554285.

Try the same and confirm. Closing for now as this is already fixed. If you disagree, write in comments and I'll reopen it.
