### ISSUE TITLE
🐛 [flutterfire_ui / FirestoreListView & FirestoreQueryBuilder] Limit on Query is ignored

### ISSUE THREAD

**Issue by appleist-a** [firebase/flutterfire#9524]
I am employing both FirestoreListView and FirestoreQueryBuilder in different stages of my application and in both of them the query is required to **`limit`** the amount of documents to load:

1. **FirestoreListView's Query**;
```
_query = FirebaseFirestore.instance
        .collection('Users')
        .doc(authController.auth.currentUser!.uid)
        .collection('Favorites')
        .limit(1)
        .orderBy('FavoriteTimestamp', descending: true)
        .withConverter<MenuModel>(
          fromFirestore: (snapshot, _) => MenuModel.fromJson(snapshot.data()!),
          toFirestore: (favorite, _) => favorite.toJson(),
        );
```

2. **FirestoreQueryBuilder's Query**;

```
FirebaseFirestore.instance
          .collection('Menu')
          .limit(1)
          .orderBy('Timestamp', descending: true)
          .withConverter<MenuModel>(
            fromFirestore: (snapshot, _) =>
                MenuModel.fromJson(snapshot.data()!),
            toFirestore: (favorite, _) => favorite.toJson(),
          ),
```

As mentioned in the title of this topic, no matter if the limit is 1 or another number, the entire collections documents are loaded. As I have managed to replicate the same issue in different projects with the same code I have created this topic in "Bug" category.

**Comment by darshankawar** [comment]
Thanks for the report @appleist-a 
I tried the scenario using plugin's [example](https://github.com/firebase/flutterfire/tree/master/packages/cloud_firestore/cloud_firestore/example) on iOS simulator as below:

```
final moviesRef = FirebaseFirestore.instance
    .collection('firestore-example-app').limit(1)
    .withConverter<Movie>(
  fromFirestore: (snapshots, _) => Movie.fromJson(snapshots.data()!),
  toFirestore: (movie, _) => movie.toJson(),
);
```

Which gave me the correct result, ie, only 1 document as below:

<img width="366" alt="Screenshot 2022-09-13 at 6 42 08 PM" src="https://user-images.githubusercontent.com/67046386/189910123-34c20184-6eaa-4b1f-8531-d9d6b4775284.png">

With `limit(2)`, it gave me 2 values as expected.

Can you try the same plugin example and see if it helps to see if it could be an implementation issue ?

**Comment by appleist-a** [comment]
Thanks for the fast answer @darshankawar 

As far as I have observed the example provided is implementing **`StreamBuilder`** instead of **`FirestoreListView`** or **`FirestoreQueryBuilder`**. If I implement it the same way of the example provided then I am losing the pagination logic that comes with the widgets that are attached in FlutterFire UI dependency; **`FirestoreListView`** or **`FirestoreQueryBuilder`**.

**Comment by appleist-a** [comment]
Thanks for the fast answer @darshankawar 

As far as I have observed the example provided is implementing **`StreamBuilder`** instead of **`FirestoreListView`** or **`FirestoreQueryBuilder`**. If I implement it the same way of the example provided then I am losing the pagination logic that comes with the widgets that are attached in FlutterFire UI dependency; **`FirestoreListView`** or **`FirestoreQueryBuilder`**.

**Comment by darshankawar** [comment]
Thanks for the feedback. I verified this by using `FirestoreListView` and observed same behavior, ie, providing `limit()` parameter doesn't actually limit the data, but shows all data.

Code sample: using plugin [example](https://github.com/firebase/flutterfire/tree/master/packages/cloud_firestore/cloud_firestore/example) and added below:

`final usersQuery = FirebaseFirestore.instance.collection('firestore-example-app').orderBy('title').limit(1);`

```
FirestoreListView<Map<String, dynamic>>(query: usersQuery,itemBuilder: (context, snapshot) {
              Map<String, dynamic> user = snapshot.data();
              return Text('Title is: ${user['title']}');
            },)
```

<img width="363" alt="Screenshot 2022-09-14 at 1 55 30 PM" src="https://user-images.githubusercontent.com/67046386/190101901-bd676ea3-6d76-4b2c-b024-07ed83b17e9b.png">

**Comment by appleist-a** [comment]
I would like to share the workaround I found for this case;

First of all I had to switch **`FirestoreListView`** to **`FirestoreQueryBuilder`** for this workaround to take effect.

**Query**; 

```
_query = FirebaseFirestore.instance
        .collection('Users')
        .doc(authController.auth.currentUser!.uid)
        .collection('Favorites')
        // .limit(isPremium ? 999 : 15) // ! Doesn't work
        .orderBy('FavoriteTimestamp', descending: true)
        .withConverter<MenuModel>(
          fromFirestore: (snapshot, _) => MenuModel.fromJson(snapshot.data()!),
          toFirestore: (favorite, _) => favorite.toJson(),
        );
```
**Widget**;

```
FirestoreQueryBuilder<MenuModel>(
        pageSize: 10, // This is the default
        query: _query,
        builder: (context, snapshot, child) {
          if (snapshot.isFetching) {
            // Loading
           
          } else if (snapshot.docs.isEmpty) {
            // Loaded but empty
            
          } else {
            // Loaded successfully

            return ListView.builder(
              itemCount: snapshot.docs.length,
              itemBuilder: (context, index) {
                // Here it checks if the first pageSize of 10 documents is loaded
                final hasEndReached = snapshot.hasMore &&
                    index + 1 == snapshot.docs.length &&
                    !snapshot.isFetchingMore;
                // Here if the first 10 documents are loaded decides if the next 10 documents should be loaded or not
                if (hasEndReached) {
                  isPremium ? snapshot.fetchMore() : null;
                }

                // Build your widget

              },
            );
          }
        },
      ),
```

**Comment by rrousselGit** [comment]
Hello!

`limit` isn't for restricting the total number of items fetched. It's for configuring how many items per page there are

**Comment by rrousselGit** [comment]
In that sense, I would say that the current behavior is expected.

Your solution of not fetching more items is a good one. Alternatively maybe you don't want a FirestoreListView and instead want a plain FirestoreBuilder + ListView
