### ISSUE TITLE
🐛 [cloud_functions]: Deadline Exceeded

### ISSUE THREAD

**Issue by niklasbartsch** [firebase/flutterfire#9539]
## Bug report

I'm calling a http cloud function from my Flutter App and it doesn't everything correct in the backend, but my Flutter app throws a "deadline-exceeded" error. 

This happens only on the first time I call the function in the session. Every other call runs without an exception.

Does anybody has an idea?

**Comment by darshankawar** [comment]
@niklasbartsch 
Can you provide `flutter doctor -v`, plugin version, a minimal code sample along with complete error log ?
Thanks.
