### ISSUE TITLE
🐛 [all_plugins] why objective c!

### ISSUE THREAD

**Issue by hatemragab** [firebase/flutterfire#9562]
I am really disappointed when I saw all flutterfire ios plugins written in objective c 
since swift should be used !!

**Comment by Ehesp** [comment]
Mainly legacy reasons. The project was started in objectivec thus during the rewrite to stable it made more sense to continue the existing codebase than rewrite in swift.

**Comment by hatemragab** [comment]
@Ehesp 
Okay but us there any future plans to update this legacy packages?
