### ISSUE TITLE
🐛 [auth_ui] FlutterFire Auth UI takes ~5minutes to actually register/login on Android ONLY.

### ISSUE THREAD

**Issue by GhilesKo** [firebase/flutterfire#9572]
## Bug report

Followed Flutterfire Auth UI documentation from A to  Z. When registering/logging in it, the button signup/sign in just loads forever. If I start the app on the Web, no issue everything works fine right away. 

It happens only on android (I have only set up Web/android). However, after a while of just waiting (maybe 5 minutes). It will actually register the user and redirect to the logged Page until I restart the app.
No error is showing, no Logcat, except for a warning message when pressing the register/button.
Debug warning message:  "W/System  ( 7457): Ignoring header X-Firebase-Locale because its value was null.".

After googling the warning message, I tried to give android permission to the internet to fix that warning but still happened. 
Having to wait 5minutes every time I refresh the app using Play/Debug is a pain

### Steps to reproduce

Follow Flutterfire Auth UI docs.

### Flutter doctor

Run `flutter doctor` and paste the output below:

 everything fine

### Flutter dependencies

dependencies:
- cupertino_icons 1.0.5
- firebase_auth 3.9.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.22.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutterfire_ui 0.4.3+9 [cloud_firestore collection crypto desktop_webview_auth email_validator firebase_auth firebase_core firebase_database firebase_dynamic_links flutter flutter_facebook_auth flutter_localizations flutter_svg google_sign_in sign_in_with_apple twitter_login]

**Comment by darshankawar** [comment]
@GhilesKo 
Can you provide a short video of the behavior you are seeing along with `flutter doctor -v` ?
Also, what device and OS version are you using ? Does it show same behavior on other android devices / emulators too ?
