### ISSUE TITLE
🐛 [firebase_analytics] Screen resolution not set

### ISSUE THREAD

**Issue by ktnishide** [firebase/flutterfire#9579]
Bug report
Analytics doesn't send screen resolution and you can't see information about resolutions in Google Analytics. Other parameters - Device, OS, etc, - is presented.

Checked with the last versions of Firebase libs.

Steps to reproduce

Add analytics in project.
Run application.
Go to Google Analytics, Reports -> User -> Tech Details
Select "Screen resolution"
See 1 line "(not set)"
![image](https://user-images.githubusercontent.com/39504484/191400775-69e5ce06-53c1-438c-a19b-78e538d6733f.png)

Expected behavior
Expected see resolutions of user's devices.

**Comment by ktnishide** [comment]
Reposting as it is a current issue for our business
[#7220](https://github.com/firebase/flutterfire/issues/7220)

**Comment by ktnishide** [comment]
Moreover, from GA4 docs:
https://support.google.com/analytics/answer/9143382#zippy=%2Cplatform-device

![image](https://user-images.githubusercontent.com/39504484/191407143-518b4ae9-0928-430a-b4fc-42793240b9a8.png)

**Comment by darshankawar** [comment]
Thanks for the report @ktnishide 
There was a similar issue reported in native SDK about it: https://github.com/firebase/firebase-android-sdk/issues/3334 for which the resolution was to reach out to backend firebase support, so I suggest you to do the same.

Also, does `mobile model` get set ?
