### ISSUE TITLE
🐛 [Storage] A required service account is missing necessary permissions.

### ISSUE THREAD

**Issue by Nijinsha** [firebase/flutterfire#9588]
## Bug report

`{  "error": {    "code": 412,    "message": "A required service account is missing necessary permissions. Please resolve by visiting the Storage page of the Firebase Console and re-linking your Firebase bucket or see this FAQ for more info: https://firebase.google.com/support/faq#storage-accounts"  }}`

All the images are missing with this error.

version

firebase_storage: ^10.2.5

### Expected behavior

Should load all the media

## Additional context

Started happening yesterday night IST. No code changes.

**Comment by darshankawar** [comment]
@Nijinsha 
As the error indicates, it could be a glitch at the backend and you need to reach out to firebase support as mentioned in the log.

Closing from here as this isn't an issue at client side. If you disagree, write in comments and I'll reopen it.

**Comment by purelydeft** [comment]
Hello @darshankawar,
How do we fix this? Any clue?

**Comment by jlc92130** [comment]
I have the same issue

**Comment by kabir-ibi** [comment]
I am having the same issue too.

**Comment by suraj-singhsu** [comment]
Hello @purelydeft, @kabir-ibi, @jlc92130,
I have also facing same issue. If someone fix this issue, please let us know the steps.

Thank you all.

**Comment by Nijinsha** [comment]
For security improvement, a service account was removed from the google cloud. (Go to firebase storage to see the link for the fix.). So what I basically did is added this service account.
service-`project number`@gcp-sa-firebasestorage.iam.gserviceaccount.com as a principle, `Cloud Storage for Firebase Service Agent` as role.

**Comment by morganp2** [comment]
Hello @Nijinsha,
When you created the service account, did you use
service-XXXXXXXX@gcp-sa-firebasestorage.iam.gserviceaccount.com in the Name field or in the Service Account ID field.
If I try to use the Service Account ID it complains: 
_Service account ID must be between 6 and 30 characters.
Service account ID must start with a lower case letter, followed by one or more lower case alphanumerical characters that can be separated by hyphens._
Thx

**Comment by Nijinsha** [comment]
https://console.cloud.google.com/iam-admin/iam
Not as the name but as principal on this page.

**Comment by n0tc0ding** [comment]
@Nijinsha Thank you, it worked. For those who are trying just wait for like 5 minutes or less for the change to take effect.

**Comment by morganp2** [comment]
Hi,
I must be doing something stupid because it will not allow me to create the principle using the format that Google says:
Note the email address it creates from this service-project number@gcp-sa-firebasestorage.iam.gserviceaccount.com:

![image](https://user-images.githubusercontent.com/75624255/191776046-1f189cfc-c220-4b93-b43a-14170a69520e.png)

**Comment by Nijinsha** [comment]
@morganp2  this is not the page. Check IAM in the sidebar of google cloud

**Comment by morganp2** [comment]
Hi @Nijinsha,
I am on the IAM page but how do I create the principle - do I use 'Grant Access'?

**Comment by suraj-singhsu** [comment]
@Nijinsha, @morganp2 
I thing we need to create from here by the owner account.
![image](https://user-images.githubusercontent.com/68230051/191780810-1e9c7ca2-2cb2-49dd-9c5c-9d0c44e4c45b.png)

**Comment by suraj-singhsu** [comment]
@Nijinsha, @morganp2 
I thing we need to create from here by the owner account.
![image](https://user-images.githubusercontent.com/68230051/191782034-46b9c538-a993-4dca-b2ab-9febeb468202.png)

Me unable to do this because I have editor role in the my project.

**Comment by morganp2** [comment]
Hi, @Nijinsha, @suraj-singhsu,

On the IAM page as the project owner I had the option to **Grant Access**. 
Here I created the principle - as detailed by Nijinsha - assigned the role: 'Cloud Storage for Firebase Service Agent' and it worked!!
Thanks all.

**Comment by suraj-singhsu** [comment]
Great @morganp2, 
Hopefully, It will also work for me once I get access of owner account.
I'll update here asap.

**Comment by malcam** [comment]
I am having the same issue too. I'll try to do what @Nijinsha said.

**Comment by jorsoc86** [comment]
Dear
I have the same problem, what would be the steps of the solution?
Thanks in advance

**Comment by douglas-wc** [comment]
Hi I have the same problems i tried @nijinsha solutions but when i try to add principal I can't find with that name @gcp-sa-firebasestorage.iam.gserviceaccount.com. Instead, just have the @gcp-sa-firestore.iam.gserviceaccount.com option. Is there something I have to do first?

**Comment by darshankawar** [comment]
Please reach out to https://firebase.google.com/support for further resolution.

**Comment by purelydeft** [comment]
@Nijinsha Thank you.
Your solution works for me.

Thank you all

**Comment by eko-prog-code** [comment]
Hello i try it, but no change in my storage... still error' preview...any solution?

**Comment by alvintankc** [comment]
@Nijinsha's solution definitely works.

I was getting the 412 error as well. 

Updated my app's Permissions through the IAM > GRANT ACCESS: 
![Firebase Cloud Storage](https://user-images.githubusercontent.com/85146944/191934848-2e161824-66fc-4530-8fe4-07454468f1c1.png)

**Comment by eko-prog-code** [comment]
![IMG_20220923_165101](https://user-images.githubusercontent.com/67722191/191936734-affc0972-9f75-4bba-8fbc-b72e9eaab3aa.jpg)

**Comment by kunbeg** [comment]
@Nijinsha's solution definitely works.
I was getting the 412 error as well.

**Comment by adamgrabarczyk** [comment]
> Hi, @Nijinsha, @suraj-singhsu,
> 
> On the IAM page as the project owner I had the option to **Grant Access**. Here I created the principle - as detailed by Nijinsha - assigned the role: 'Cloud Storage for Firebase Service Agent' and it worked!! Thanks all.

@morganp2 

what do you mean **as project owner**? 
I try to follow your solution but it didn't works.

**Comment by suraj-singhsu** [comment]
Project owner means you need to add a principal by using the account which you created app.

**Comment by morganp2** [comment]
Hi @adamgrabarczyk ,

The project owner is the person who created your Firebase project. It is a Role. 
The project owner role can make other users a 'project owner'.
Once you have the project owner role you can then Grant a new principal.
A principle is like a 'user' - which can be a machine entity or a human entity.
The principle you require is:
service-**project number**@gcp-sa-firebasestorage.iam.gserviceaccount.com
When you create the principle you can assign it one or more Roles.
The Role you need is:
Cloud Storage for Firebase Service Agent

**Comment by Ninonino82** [comment]
hi 
this in my problem
can someone help me?

![Immagine 2022-09-26 130001](https://user-images.githubusercontent.com/114401723/192260564-3a62801d-51f9-434b-811f-e9c5ecde7ad1.jpg)

**Comment by morganp2** [comment]
I think you are on the wrong page.

Below is a view of the page I used to create a principal.
Stuff I have hidden in Blue pen indicates the name of my Firebase Project.
The red highlights shows what I do to add a principle.

To be honest we should be using the Google Firebase support to comment and discuss as this has nothing to do with flutterfire.


![image](https://user-images.githubusercontent.com/75624255/192269178-9b71a3a5-7a67-4198-aca6-1f5e91845c8a.png)

**Comment by tonyjhuang** [comment]
If anyone is having trouble adding the service account (`service-<project number>@gcp-sa-firebasestorage.iam.gserviceaccount.com`) to their project, it's possible that Cloud Storage for Firebase has not created it yet. 

**Solution:** Try using the AddFirebase API to relink a bucket to your project and try again: https://firebase.google.com/docs/reference/rest/storage/rest/v1beta/projects.buckets/addFirebase


**Example error:**
![image](https://user-images.githubusercontent.com/1237337/192326860-23e6da37-3608-4018-be43-7d27202a9240.png)

**Example solution:**
![image](https://user-images.githubusercontent.com/1237337/192328368-335059a5-0015-46d3-82f7-4caf205b2c26.png)

**Comment by tonyjhuang** [comment]
@Ninonino82 See my comment above ^

**Comment by Ninonino82** [comment]
@tonyjhuang wonderful! this is the solution for me! thanks...

**Comment by jSkrills** [comment]
> 🔥 Firebaser here! Thanks everyone for chiming in, [#9588 (comment)](https://github.com/firebase/flutterfire/issues/9588#issuecomment-1255055456) is definitely the right fix for this issue.
> 
> If anyone is having trouble adding the service account (`service-<project number>@gcp-sa-firebasestorage.iam.gserviceaccount.com`) to their project, it's possible that Cloud Storage for Firebase has not created it yet.
> 
> **Solution:** Try using the AddFirebase API to relink a bucket to your project and try again: https://firebase.google.com/docs/reference/rest/storage/rest/v1beta/projects.buckets/addFirebase
> 
> **Example error:** ![image](https://user-images.githubusercontent.com/1237337/192326860-23e6da37-3608-4018-be43-7d27202a9240.png)
> 
> **Example solution:** ![image](https://user-images.githubusercontent.com/1237337/192328368-335059a5-0015-46d3-82f7-4caf205b2c26.png)

This worked for me except that I had to use my project id in one spot then my bucket name in the next spot.

**Comment by devarsh-mavani-19** [comment]
I also got this error all of sudden out of no where. Any idea why it could have happend. It happend with me on a live project and i incurred financial loss as well. so this is really pissing me off. @darshankawar  @Nijinsha
