### ISSUE TITLE
Firebase APNS device token not set before retrieving FCM Token for Sender ID - XXX Flutter iOS

### ISSUE THREAD

**Issue by rak54** [firebase/flutterfire#9589]
Hello
Push notifications were working fine before but now all of sudden getting " [Firebase APNS device token not set before retrieving FCM Token for Sender ID - Flutter iOS] . I am using latest version and 11.2.5 for my other project . 

Is this issue related to firebase_messaging . ? 

Please help .

**Comment by darshankawar** [comment]
@rak54 
If you try on any other iOS device, do you get same error ?
Also, there's a [discussion](https://github.com/firebase/flutterfire/discussions/5705) thread on this issue, that you need to follow-up in and check underlying comments to see if they help.
Closing from here.

**Comment by rak54** [comment]
Yes I am not getting messages on other devices too

**Comment by rak54** [comment]
Yes I have seen that discussion and everything thing is fine by my side
still won't work
