### ISSUE TITLE
🐛 [firebase_messaging] failed-service-worker-registration, The script has an unsupported MIME type

### ISSUE THREAD

**Issue by dumabg** [firebase/flutterfire#9592]
I've deployed a new version of a flutter 3.3.2 web application.

Like the web application was started with a lower Flutter version and index.html and FlutterFire plugins registration has changed, I've created a new sample web flutter application, and have copied the new index.html:
[index.html.txt](https://github.com/flutter/flutter/files/9620447/index.html.txt)
and have done all the steps related on [https://firebase.google.com/docs/flutter/setup?platform=web](https://firebase.google.com/docs/flutter/setup?platform=web).

All works well, but there is one customer than can't load the application. Appears this error:

[firebase_messaging/failed-service-worker-registration] Messaging: We are unable to register the default service worker. Failed to register a ServiceWorker for scope ('https://_host_/firebase-cloud-messaging-push-scope') with script ('https://_host_/firebase-messaging-sw.js'): The script has an unsupported MIME type ('text/html'). ., )

On the message error above, I've changed the real host name with the word _host_.

Nothing works, he already have pressed the refresh button, F5 and Ctrl+F5. Even I've included a page error with a button:
`
 IconButton(
                             onPressed: () => window.location.reload(),
                                icon: const Icon(Icons.refresh))
                          ],
`

He is using Chrome 105.0.5195.127

**Comment by darshankawar** [comment]
@dumabg 
As the error says `The script has an unsupported MIME type ('text/html')`, indicating wrong MIME type of file in your server.  You may want to check the format / config of the said file on your local dev server and on release build if that helps ?

**Comment by dumabg** [comment]
On previous FlutterFire versions, I need to create this file for configuring messaging, but now doesn't exist. I suppose that the browser is caching the file and the old index.html. I don't know. 

The new build hasn't this file.

It seems a cache problem, but it isn't resolved deploying a new version nor Ctrl+F5. It seems that the browser doesn't invalidated the cache. But only in this customer, in others works well.

**Comment by darshankawar** [comment]
I am not sure if there's anything can be done from client (Flutterfire) side on it. I suggest you to reach out to [firebase support](https://firebase.google.com/support) for further resolution since this looks to be setup / config issue and that too happening in one customer's end.

**Comment by dumabg** [comment]
I had a component that was using messaging 12. On my project, all other Firebase component are using the last version (core 1.23). I have changed that component and now messaging is in the last version (13.0.3).

After upgrade, I have another errors, only on Firefox and only if are new browsers (not acceded previously). If use incognito, also appears. Appears one of these errors:
- [firebase_messaging/failed-service-worker-registration] Messaging: We are unable to register the default service worker. The operation is insecure. ., ).
  In some the phrase "The operation is insecure" appears and in others no.
- FirebaseError: Messaging: This browser doesn't support the API's required to use the Firebase SDK. (messaging/unsupported-browser).

The Firefox version is 105.0

On Chromium, continues with the MIME type error.

**Comment by dumabg** [comment]
Reading again the documentation on https://firebase.google.com/docs/cloud-messaging/flutter/receive,
I created again _firebase-messaging-sw.js_, but where put _navigator.serviceWorker.register('/firebase-messaging-sw.js');_?

Now index.html is completely different.

I put in all these places:

```
 window.addEventListener('load', function(ev) {
      navigator.serviceWorker.register('/firebase-messaging-sw.js');   // HERE
      // Download main.dart.js
      _flutter.loader.loadEntrypoint({
      ...
```

      
```
 window.addEventListener('load', function(ev) {      
      // Download main.dart.js
      _flutter.loader.loadEntrypoint({
        serviceWorker: {
          serviceWorkerVersion: serviceWorkerVersion,
        }
      }).then(function(engineInitializer) {
        navigator.serviceWorker.register('/firebase-messaging-sw.js');      // HERE   
        return engineInitializer.initializeEngine();
      }).then(function(appRunner) {    
        return appRunner.runApp();
      });
    });
```
    
      
```
 window.addEventListener('load', function(ev) {      
      // Download main.dart.js
      _flutter.loader.loadEntrypoint({
        serviceWorker: {
          serviceWorkerVersion: serviceWorkerVersion,
        }
      }).then(function(engineInitializer) {
        return engineInitializer.initializeEngine();
      }).then(function(appRunner) {
        navigator.serviceWorker.register('/firebase-messaging-sw.js');   // HERE
        return appRunner.runApp();
      });
    }); 
```     
      
But always apperas this error: navigator.serviceWorker is undefined

**Comment by darshankawar** [comment]
Check [this](https://github.com/firebase/flutterfire/issues/5515) similar issue and underlying comments and see if it helps.

**Comment by dumabg** [comment]
I have restored the index.html that was created in Flutter 2. After that, all works again. The new index.html seems to have some problems.
