### ISSUE TITLE
🐛 [firebase_storage] "An unknown error occurred, please check the server response" on macOS only

### ISSUE THREAD

**Issue by yaozhang-this** [firebase/flutterfire#9603]
## Bug report

Firebase with flutter running on macOS throws below error while attempting to access firebase_storage in anyway, including getData, getMetadata, etc.

```
2022-09-22 21:03:36.644 test_mac_firebase[88627:2486824] FLTFirebaseStorage: An unknown error occurred while calling method Reference#getData
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(unknown, An unknown error occurred, please check the server response., {code: unknown, message: An unknown error occurred, please check the server response., nativeErrorMessage: An unknown error occurred, please check the server response., nativeErrorCode: -13000}, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
<asynchronous suspension>
#2      _MyHomePageState._incrementCounter (package:test_mac_firebase/main.dart:67:38)
<asynchronous suspension>
```

### Steps to reproduce

1. Create a blank flutter app targeting macOS.
2. Create a new firebase project from scratch, add any file to firebase_storage.
3. Edit the rule to public access like below to ensure this app can access the storage without authentication
```
rules_version = '2';
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read, write;
    }
  }
}
```
4. Add required firebase plugins using `flutter pub add`, this includes firebase_core, firebase_storage. Log in to Firebase in CLI, etc. Run `flutterfire configure` etc, you know the drill.
5. Check to make sure that `Podfile` in `macOS/` folder is supporting minimum version of `platform :osx, '10.12'`.
6. From newly created blank flutter app `main.dart`, in its increment counter function, initialize the app as described in the documentation and create a storage reference to the file you just uploaded using `getData()` method as described in the documentation.
7. Run the app, click the plus FAB button will trigger an access to firebase_storage. 
8. Error thrown with provided message. No details are given.

### Expected behavior

When FAB is clicked, the app should be able to access the file on firebase_storage and download it to memory.

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

I looked in to #9506 and #7706 to no avail. #7706 says this is about network issue. But I checked network tab there is no network connection whatsoever each time I press the button to initiate the access call. In the Firebase web console, there is also no recorded access attempt as it would have shown up if access is denied in any forms. In fact, if I intensionally modify the storage rule with access restrictions, the same unspecified error gets thrown regardless. This means the error is thrown before any connections attempt are made.

It also should be mentioned that in my multiplatform app (iOS, macOS, android) with the same codebase, all other platforms are working fine with firebase_storage except macOS. In other word, this is most likely a macOS firebase only bug. I am also not sure if anyone have suspected anything about ARM architecture or have tested it with firebase.

Please investigate as I am seeing multiple issues like this but none are getting addressed and are simply ignored without trying. 

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5.1 21G83 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2021.3.2)
[✓] VS Code (version 1.71.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.17.6
Flutter SDK 3.0.5
test_mac_firebase 1.0.0+1

dependencies:
- csv 5.0.1
- cupertino_icons 1.0.5
- firebase_core 1.23.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_storage 10.3.9 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]

dev dependencies:
- flutter_lints 2.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.16.0
- fake_async 1.3.0 [clock collection]
- firebase_core_platform_interface 4.5.1 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 1.7.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 4.1.17 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.3.7 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- http 0.13.5 [async http_parser meta path]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- js 0.6.4
- lints 2.0.0
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.4
- meta 1.7.0
- path 1.8.1
- plugin_platform_interface 2.1.3 [meta]
- sky_engine 0.0.99
- source_span 1.8.2 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.9 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.1 [collection]
- vector_math 2.1.2

```

</details>

---

### Operating System Version
```
macOS 12.5.1
ARM m1 chip
```

**Comment by darshankawar** [comment]
@yaozhang-this Thanks for the report.

I tried using the steps to replicate and used below code to read the data that is present in the storage db which returned properly without the error you reported.
```

final storageRef = FirebaseStorage.instance.ref();
    final pathRef = storageRef.child('images/dash.png');


    return MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: Scaffold(
          body: Center(
            child: ElevatedButton(
                onPressed: () {
                  pathRef.getData();
                  print('success');
                },
                child: Text("run")),
          )
        ));
```

Console log:

```
Building macOS application...                                           
Syncing files to device macOS...                                    81ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

Running without sound null safety ⚠️
Dart 3 will only support sound null safety, see https://dart.dev/null-safety

An Observatory debugger and profiler on macOS is available at: http://127.0.0.1:51976/xTVuWHurJFk=/
The Flutter DevTools debugger and profiler on macOS is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:51976/xTVuWHurJFk=/
flutter: success

```

I am on latest master version of the framework, `Channel master, 3.4.0-28.0.pre.123`

```
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.23.0
  firebase_storage: ^10.3.9
```

`ARM m1 chip`, I am on Intel chip, but doubt if it will make any difference.


Can you try above code sample I shared and see if using it, you get same error or not ?

**Comment by yaozhang-this** [comment]
@darshankawar I created a new project using your code, and run `flutter run` with the same error when button is pressed.

```
2022-09-23 12:28:37.413 test_mac_firebase[6917:2765519] FLTFirebaseStorage: An unknown error occurred while calling method Reference#getData
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(unknown, An unknown error occurred, please check the server response., {code: unknown, message: An unknown error occurred, please check the server response., nativeErrorMessage: An unknown error occurred, please check the server response., nativeErrorCode: -13000}, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
<asynchronous suspension>
```

Do you have any m1 machine available to test? Or could you try it on a different machine?

**Comment by yaozhang-this** [comment]
@darshankawar I updated flutter to the latest master channel with version 
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.4.0-28.0.pre.128, on macOS 12.5.1 21G83 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2021.3.2)
[✓] VS Code (version 1.71.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

```

and still get
```
2022-09-23 12:44:05.149 test_mac_firebase[12779:2801407] FLTFirebaseStorage: An unknown error occurred while calling method Reference#getData
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(unknown, An unknown error occurred, please check the server response., {code: unknown, message: An unknown error occurred, please check the server response., nativeErrorMessage: An unknown error occurred, please check the server response., nativeErrorCode: -13000}, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
<asynchronous suspension>


```

**Comment by darshankawar** [comment]
Also, see [comment](https://stackoverflow.com/questions/73067853/unhandled-exception-firebase-storage-unknown-an-unknown-error-occurred-pleas) from Firebaser and [answer](https://stackoverflow.com/a/73083034) from him and see if it helps.

**Comment by yaozhang-this** [comment]
> > Also what is your Xcode version?
> 
> 
> 
> 13.2.1
> 
> 
> 
> Not sure if it has to do with security rules, but can you try below in your rules and see if it helps ?
> 
> 
> 
> `allow read, write: if true;`

Yes, I tried.
Security rule is not the issue. I made another test project on a different mac (still m1) and obtained the same result.

**Comment by darshankawar** [comment]
Thanks for the update and patience. I am now able to replicate this error (intel chip) using below code sample running with latest master version on macOS desktop:

```
void _incrementCounter() {

    final storageRef = FirebaseStorage.instance.ref();
    final pathRef = storageRef.child('images/dash.png');
    pathRef.getData();
    print('success');

    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }
```

```
2022-09-27 15:49:43.926 storage_macos[22980:210447] FLTFirebaseStorage: An unknown error occurred while calling method Reference#getData
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(unknown, An unknown error occurred, please check the server response., {code: unknown, message: An unknown error occurred, please check the server response., nativeErrorMessage: An unknown error occurred, please check the server response., nativeErrorCode: -13000}, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
<asynchronous suspension>
```

Tried the same on web wherein I get `success` output along with `Error: XMLHttpRequest error.`

**Comment by yaozhang-this** [comment]
@darshankawar could you share to @russellwheatley of what you changed on the second run that replicated this error? I never did this successively on macOS so I couldn't help beyond providing what I have. 
I tried both 3.0.5 and 3.4.0 flutter versions. below is also what I used 
```
  firebase_storage: ^10.3.9
  firebase_core: ^1.23.0
```
Also you mentioned you replicated this error on intel chip Mac I think that also rules out that variable.

**Comment by darshankawar** [comment]
> I'm going to need more details. I was not using the emulator for instance.

@russellwheatley Hi, 

Below are the steps that I took that helped me to replicate the error:

1. Created a new Flutter project named `storage_macos`.
2. Integrated an existing triage Firebase project by running `dart pub global activate flutterfire_cli` followed by `flutterfire configure`.
3. Added `firebase_core` and `firebase_storage`.
4. In `main.dart`, added the code sample as described in https://github.com/firebase/flutterfire/issues/9603#issuecomment-1259303781
5. Ran `flutter run -d macos` and tapping on FAB although increments the counter, but throws the error as described.

Here's the video of the entire process:


https://user-images.githubusercontent.com/67046386/193211079-b1e5750c-f045-4379-9cb9-878ee61c19da.mov

I see this error on latest stable (3.3.3) and on latest master version of the framework.

Interestingly, if I use plugin example `flutter_storage_example` which has same Firebase project integrated as mentioned in step 2 above and use below code sample, it runs as expected and prints `success` without throwing the reported error:

```
class MyApp extends StatelessWidget {
 // const MyApp({super.key});
  @override
  Widget build(BuildContext context) {

    final storageRef = FirebaseStorage.instance.ref();
    final pathRef = storageRef.child('images/dash.png');


    return MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: Scaffold(
          body: Center(
            child: ElevatedButton(
                onPressed: () {
                  pathRef.getData();
                  print('success');
                },
                child: Text("run")),
          )
        ));
  }
}
```

Here's the video of such example:


https://user-images.githubusercontent.com/67046386/193211692-729ba110-346e-4af3-af54-811e4335f99c.mov

**Comment by AnassErraidi** [comment]
hello Mister,
found a solution that work for me
Answer of mister Adam Boostani did work after I change the json file code line from :

    https://firebase.google.com/docs/storage/web/download-files#cors_configuration

Firebase is using the same storage infrastructure as google cloud and even though there is no firebase method to set the cors rules, you can use gc set up. First you need to install google cloud sdk:

    curl https://sdk.cloud.google.com | bash

Restart your shell:

    exec -l $SHELL

Initialize gcloud. This will ask you to select your account and authenticate.

    gcloud init

Then create a json file with the following content

    [
        {
          "origin": ["*"],
        "method": ["GET"],
        "maxAgeSeconds": 3600
        }
    ]

And run this with your firebase storage gc: endpoint

    gsutil cors set yourFile.json gs://yourProject

That should fixe the problem for you as well.
it fixed it Thank you Mister Adam Boostani

**Comment by OutdatedGuy** [comment]
Yo @yaozhang-this, just a question. Have you added permission to access internet for macOS app as mentioned in the [Flutter Networking Docs](https://docs.flutter.dev/data-and-backend/networking#macos)?

**Comment by russellwheatley** [comment]
@OutdatedGuy is correct. I tried with/without this entitlement:

```xml
<key>com.apple.security.network.client</key>
<true/>
```
I reproduced the exception without it. When I added it back into the entitlements, the request was successful.
