### ISSUE TITLE
🐛 [Firestore] Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds

### ISSUE THREAD

**Issue by zubeirom** [firebase/flutterfire#9607]
## Receiving this error when starting up my flutter app using firestore.

Getting this error:

```
W/Firestore(26053): (24.2.2) [OnlineStateTracker]: Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds
W/Firestore(26053): 
W/Firestore(26053): This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.
```

**Describe the bug**

Currently when connecting to firestore, the above error is appearing on the debug console. So, executing queries is currently not possible. I've tried adding app check which didn't help and changing access rules didn't help as well.

Device: Pixel 4XL Emulator

### Steps to reproduce

1. Create flutter app
2. Install firebase core and firestore

### Flutter doctor

Run `flutter doctor` and paste the output below:
```
➜ flutter doctor -v
[✓] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.22000.978], locale en-US)
    • Flutter version 3.0.5 at C:\Users\t-zmohamed\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (2 months ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\t-zmohamed\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.11.19)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    • Visual Studio Enterprise 2019 version 16.11.32901.82
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at C:\Users\t-zmohamed\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.978]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 105.0.5195.127
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 105.0.1343.42

[✓] HTTP Host Availability
    • All required HTTP hosts are available

<details><summary>Click To Expand</summary>

```

**Comment by fleckdalm** [comment]
I have the same error but only in the Android emulator. On a physical device everything works fine

**Comment by zubeirom** [comment]
@fleckdalm Correct, it's happening on my emulator too, didn't tested on real device

**Comment by darshankawar** [comment]
Thanks for the report @zubeirom 
There's a discussion thread on this issue that you can refer for updates on the issue. https://github.com/firebase/flutterfire/discussions/5546. Also see this issue comment and check if it helps in your case: https://github.com/firebase/flutterfire/discussions/5546#discussioncomment-1887990

If it works on physical device but not on emulator / simulator, it doesn't likely to be an issue of the plugin, because the flutterfire plugins are just wrappers around native Firebase sdks and send, receive data through Dart, so, at the client side, we are not checking / doing anything from device specific point of view.

I suggest you to please share your findings in the discussion thread and / or also reach out to firebase support to see what they have to say about it.

Closing for now, as this doesn't seem to be a plugin issue. If you disagree, write in comments and I'll reopen it.

**Comment by zubeirom** [comment]
Thanks @darshankawar

**Comment by Ahsan161815** [comment]
> @fleckdalm Correct, it's happening on my emulator too, didn't tested on real device

For me it works on real device.

for emulators
I have tried different emulators, reinstalling android studio, updating android studio, reinstalling windows, trying out different plugins but nothing worked.

On emulator sometimes turning to airplane mode than back works. just sometimes not anymore.

last thing remaining is to use old version of flutter.
Please fix this Flutter Team.

**Comment by Ahsan161815** [comment]
> I have the same error but only using the Android emulator. On a physical device everything works fine. So the issue seems to be somehow related to the emulator. The emulator has an active internet connection and every other online service works fine with it. My dependencies: firebase_core: "^1.21.1" firebase_analytics: "^9.3.3" firebase_auth: "^3.8.0" firebase_crashlytics: "^2.8.9" cloud_firestore: ^3.4.7 firebase_storage: ^10.3.7 cloud_functions: ^3.3.6 google_sign_in: ^5.4.1 firebase_messaging: ^13.0.0 firebase_remote_config: ^2.0.16

> @fleckdalm Correct, it's happening on my emulator too, didn't tested on real device

Same here 
it works on real device.

for emulators
I have tried different emulators, reinstalling android studio, updating android studio, reinstalling windows, trying out different plugins but nothing worked.

On emulator sometimes turning to airplane mode than back works. just sometimes not anymore.

last thing remaining is to use old version of flutter.
Please fix this Flutter Team.

**Comment by fleckdalm** [comment]
According to this its related to the newest version of the android emulator and downgrading helps: https://stackoverflow.com/questions/73370728/firebase-doesnt-work-on-android-studio-emulator/73584389#73584389

**Comment by NWScheduler** [comment]
This issue is NOT closed at all. Read the description of the problem. https://stackoverflow.com/questions/73370728/firebase-doesnt-work-on-android-studio-emulator/73584389#73584389

**Comment by Ahsan161815** [comment]
> According to this its related to the newest version of the android emulator and downgrading helps: https://stackoverflow.com/questions/73370728/firebase-doesnt-work-on-android-studio-emulator/73584389#73584389

after many days of struggle here is how i fixed.
I was using emulator version something like 31.3.10 and upgraded it to 31.3.11. now problem is solved.
Downgrading will also work but i like upgrading :)

Below i have attached the screenshot to make is easy for you.
Hope this will save you time.

![help](https://user-images.githubusercontent.com/96950460/193184898-28e24140-8b12-4c80-8900-c56d4776619b.png)
