### ISSUE TITLE
Locations: No module for.... with CollectionReference.get() in Flutter Web

### ISSUE THREAD

**Issue by jason-downs** [firebase/flutterfire#9612]
I'm using cloud firestore in a Flutter web project. Whenever I call get() on an entire collection (rather than on a single document in the collection), I get the following error:

`Locations: No module for https://www.gstatic.com/firebasejs/9.9.0/firebase-firestore.js`

This happens on a collection with about 425 documents - if I limit the results, or call get on a smaller collection it works fine.

This is a valid operation according to the official docs: https://firebase.google.com/docs/firestore/query-data/get-data#get_all_documents_in_a_collection with no indication that it's limited by number of docs, etc. Also this same code was working fine (with the same number of docs) when I was doing the same thing on a Flutter macOS app, until recently I switched it to web.

I'm initializing Firebase in the flutter main() instead of in index.html, as now recommended by the most recent documentation. All firebase-related packages are their latest versions.

If this is indeed an issue related to too many documents then it would at least be nice if the documentation mentioned this limitation or the error message mentioned that, but that is not the case, and really it's not THAT much data, which leads me to believe there is some sort of bug or I'm doing something wrong.

**Comment by darshankawar** [comment]
@jason-downs Thanks for the report.
Can you provide `flutter doctor -v`, plugin version along with complete error log ?

**Comment by darshankawar** [comment]
@jason-downs 
Revisiting this issue, I created 430+ documents in a sample collection. Retrieved it using below code sample which gave me correct results with all data without throwing the error you reported:

```
Future<void> addUser() async {

    CollectionReference add = FirebaseFirestore.instance.collection('basic-example');
    await add.get().then((event) {
      print(event.docs.length);
      for (final doc in event.docs) {
        print('${doc.id} => ${doc.data()}');

      }
    });
  }
```

```
  Flutter Web Bootstrap: Auto
The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:51418/9JK_4KByZqo=
434
05jWwqBZxC0BXXbGz2dC => {}
0CXKfUCbKI9EocGozLdA => {}
0GBytkK5IqbElwQDhpMw => {}
0NSz3nLR5Tady5UbHXcF => {}
0OzTmfyoh3TgBgObgH4A => {}
...

```

The browser devtools also doesn't show any error.

Can you provide more details as asked earlier ?

**Comment by jason-downs** [comment]
Sorry for the delay, for some reason my notifications weren't working - anyway here is flutter doctor -v output:

```[✓] Flutter (Channel stable, 3.3.3, on macOS 12.6 21G115 darwin-arm, locale en-US)
    • Flutter version 3.3.3 on channel stable at /Users/jason/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18a827f393 (6 days ago), 2022-09-28 10:03:14 -0700
    • Engine revision 5c984c26eb
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/jason/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 106.0.5249.91

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!```

Will post more diagnostic info in a moment.

**Comment by darshankawar** [comment]
@jason-downs 
Thanks for coming back. Can you provide snapshot of the type of document data you have in that collection ? That way, I'll try to recreate the data and see if it is replicable at our end or not.

**Comment by darshankawar** [comment]
Moreover, please also try the same on latest master and see if you get same error log or not.

**Comment by alvarogabrielgomez** [comment]
Please, i have the same error

**Comment by alvarogabrielgomez** [comment]
Please dont close

**Comment by darshankawar** [comment]
@alvarogabrielgomez 
I suggest you to go through https://github.com/flutter/flutter/issues/111136 and see if underlying comments / solutions mentioned in it, helps in your case too or not.
