### ISSUE TITLE
🐛 [firebase_messaging] Firebase messaging adds AD_ID permission

### ISSUE THREAD

**Issue by AAverin** [firebase/flutterfire#9618]
## Bug report

**Describe the bug**
Browsing through the merged manifest it can be seen that firebase_messaging is reported to add AD_ID permission.

### Steps to reproduce

1. Go to build folder
2. find `manifest-merged-blame-debug-report.txt`
3. Search for AD_ID usage
4. Find firebase_messaging adding unnecessary permission
```
33-->[com.google.firebase:firebase-messaging:23.0.8] /Users/.../.gradle/caches/transforms-3/c9ffe383d585c72fdd485b230afb7e10/transformed/jetified-firebase-messaging-23.0.8/AndroidManifest.xml:29:22-79
34    <uses-permission android:name="com.google.android.gms.permission.AD_ID" />
```

### Expected behavior

firebase_messaging is not related to ads, so it shouldn't add AD_ID permission.

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
- firebase_analytics 9.3.6 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 1.23.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 2.8.11 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_messaging 13.0.3 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_performance 0.8.3+1 [firebase_core firebase_core_platform_interface firebase_performance_platform_interface firebase_performance_web flutter]
- firebase_remote_config 2.0.18 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]

```

</details>

---

**Comment by darshankawar** [comment]
@AAverin 
I think this will need to be reported in native firebase sdk repo. I see a similar issue open in it for `analytics`: https://github.com/firebase/firebase-android-sdk/issues/2582

Closing from here. If you disagree, write in comments and I'll reopen it.
