### ISSUE TITLE
🐛 [firebase_database] Consecutive word/letter duplication in dart doc comments

### ISSUE THREAD

**Issue by OutdatedGuy** [firebase/flutterfire#9619]
### Steps to reproduce

1. Go [here][file-link]
2. See the letter `a` is duplicated on line **95** and **119**

[file-link]: https://github.com/firebase/flutterfire/blob/d834b90f29fc1929a195d7d546170e4ea03c6ab1/packages/firebase_database/firebase_database/lib/src/query.dart#L95

**Comment by darshankawar** [comment]
Thanks for catching this :)
