### ISSUE TITLE
🐛 [firebase_auth] MissingPluginException(No implementation found for method Auth#signInWithProvider on channel plugins.flutter.io/firebase_auth)

### ISSUE THREAD

**Issue by vanhuugiakien** [firebase/flutterfire#9621]
## Bug report

An error occurred when using the signInWithProvider() method with GoogleAuthProvider. This error arises when building the application in iOS

### Steps to reproduce

1. Login with FirebaseAuth.instance.signInWithProvider(GoogleAuthProvider()); 
2. Application crash and lost connect with flutter 

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.3.2, on macOS 13.0 22A5342f darwin-arm, locale en-VN)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.71.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 2 categories.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
dependencies:
- cupertino_icons 1.0.5
- dio 4.0.6 [http_parser path]
- firebase_auth 3.10.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.23.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 11.4.4 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_storage 10.3.9 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_local_notifications 9.9.1 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_rating_bar 4.0.1 [flutter]
- flutter_spinkit 5.1.0 [flutter]
- get 4.6.5 [flutter]
- get_storage 2.0.3 [flutter get path_provider]
- image_picker 0.8.5+3 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_platform_interface]
- intl 0.17.0 [clock path]
- shared_preferences 2.0.15 [flutter shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- table_calendar 3.0.7 [flutter intl simple_gesture_detector]
- url_launcher 6.1.5 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]

dev dependencies:
- flutter_lints 2.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- args 2.3.1
- async 2.9.0 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.1
- clock 1.1.1
- collection 1.16.0
- cross_file 0.3.3+2 [js meta]
- dbus 0.7.8 [args ffi meta xml]
- fake_async 1.3.1 [clock collection]
- ffi 2.0.1
- file 6.1.4 [meta path]
- firebase_auth_platform_interface 6.9.0 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 4.5.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.5.1 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 1.7.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 3.5.4 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.4.4 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 4.1.17 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.3.7 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_local_notifications_linux 0.5.1 [flutter flutter_local_notifications_platform_interface dbus path xdg_directories]
- flutter_local_notifications_platform_interface 5.0.0 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 2.0.7 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- http 0.13.5 [async http_parser meta path]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- image_picker_android 0.8.5+3 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 2.1.8 [flutter flutter_web_plugins image_picker_platform_interface]
- image_picker_ios 0.8.6+1 [flutter image_picker_platform_interface]
- image_picker_platform_interface 2.6.1 [cross_file flutter http plugin_platform_interface]
- js 0.6.4
- lints 2.0.0
- matcher 0.12.12 [stack_trace]
- material_color_utilities 0.1.5
- meta 1.8.0
- path 1.8.2
- path_provider 2.0.11 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- path_provider_android 2.0.20 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.11 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.6 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.4 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.3 [ffi flutter path path_provider_platform_interface win32]
- petitparser 5.0.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.3 [meta]
- process 4.2.4 [file path platform]
- shared_preferences_android 2.0.13 [flutter shared_preferences_platform_interface]
- shared_preferences_ios 2.1.1 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.1.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_macos 2.0.4 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.1.0 [flutter plugin_platform_interface]
- shared_preferences_web 2.0.4 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.1.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- simple_gesture_detector 0.2.0 [flutter]
- sky_engine 0.0.99
- source_span 1.9.0 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.1 [source_span]
- term_glyph 1.2.1
- test_api 0.4.12 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.8.0 [path]
- typed_data 1.3.1 [collection]
- url_launcher_android 6.0.19 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.0 [flutter plugin_platform_interface]
- url_launcher_web 2.0.13 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.1 [flutter url_launcher_platform_interface]
- vector_math 2.1.2
- win32 3.0.0 [ffi]
- xdg_directories 0.2.0+2 [meta path process]
- xml 6.1.0 [collection meta petitparser]```

</details>

---

**Comment by darshankawar** [comment]
@vanhuugiakien Thanks for the report.
Using steps to replicate you mentioned above, I used below code sample and ran on iOS device and after tapping on `Login` button, I get different log, but not the error you reported.

```
return MaterialApp(
      title: 'Firebase Example App',
      theme: ThemeData(primarySwatch: Colors.amber),
      home: Scaffold(
        body: ElevatedButton(
          child: Text('Login'),
          onPressed: () {
            FirebaseAuth.instance.signInWithProvider(GoogleAuthProvider());
          },
        )
      ),
    );
```



```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: [firebase_auth/web-context-cancelled] The interaction was cancelled by the user.
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
<asynchronous suspension>
#2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:518:43)
<asynchronous suspension>
#3      MethodChannelFirebaseAuth.signInWithProvider (package:firebase_auth_platform_interface/src/method_channel/method_channel_firebase_auth.dart:585:12)
<asynchronous suspension>
#4      FirebaseAuth.signInWithProvider (package:firebase_auth/src/firebase_auth.dart:636:9)
<asynchronous suspension>
```

`[firebase_auth/web-context-cancelled] The interaction was cancelled by the user.` Seems to be expected log and self-explanatory after tapping on `done` button.

I used latest version of `firebase_auth` and `firebase_core` available.

Can you run above code and see if you still get same error as you reported or not ? If yes, please provide complete error log.

**Comment by vanhuugiakien** [comment]
I tried the _**signInWithEmailAndPassword**_ method, everything is fine.
However, using the same _**FirebaseAuth.instance.signInWithProvider(GoogleAuthProvider())**_ method as you used. The application will crash immediately. And without any log.

`💪 Running with sound null safety 💪

An Observatory debugger and profiler on iPhone 14 Pro Max is available at:
http://127.0.0.1:62904/8guBlh4rxRY=/
flutter: User granted permission
The Flutter DevTools debugger and profiler on iPhone 14 Pro Max is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:62904/8guBlh4rxRY=/
Lost connection to device.`

I tried debugging with Xcode and got this error.

`2022-09-28 15:05:02.603818+0700 Runner[41984:1297055] [plugin] AddInstanceForFactory: No factory registered for id <CFUUID 0x600001b9dd40> F8BB1C28-BAE8-11D6-9C31-00039315CD46
2022-09-28 15:05:02.655465+0700 Runner[41984:1297055] [ddagg]        AggregateDevice.mm:878   couldn't get default input device, ID = 0, err = 0!
2022-09-28 15:05:19.899576+0700 Runner[41984:1295717] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Please register custom URL scheme 'app-1-450818758671-ios-06cbbeb4babe07b50e6b7a' in the app's Info.plist file.'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000018040c304 __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x000000018005131c objc_exception_throw + 56
	2   CoreFoundation                      0x000000018040c214 -[NSException initWithCoder:] + 0
	3   FirebaseAuth                        0x00000001011ccce8 -[FIROAuthProvider getCredentialWithUIDelegate:completion:] + 148
	4   Runner                              0x0000000100b1eb38 -[FLTFirebaseAuthPlugin signInWithProvider:withMethodCallResult:] + 740
	5   Runner                              0x0000000100b1ad80 -[FLTFirebaseAuthPlugin handleMethodCall:result:] + 3080
	6   Flutter                             0x000000010522c250 __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 112
	7   Flutter                             0x0000000104c9ab5c ___ZN7flutter25PlatformMessageHandlerIos21HandlePlatformMessageENSt3__110unique_ptrINS_15PlatformMessageENS1_14default_deleteIS3_EEEE_block_invoke + 104
	8   libdispatch.dylib                   0x0000000101a90594 _dispatch_call_block_and_release + 24
	9   libdispatch.dylib                   0x0000000101a91d5c _dispatch_client_callout + 16
	10  libdispatch.dylib                   0x0000000101aa2808 _dispatch_main_queue_drain + 1316
	11  libdispatch.dylib                   0x0000000101aa22d4 _dispatch_main_queue_callback_4CF + 40
	12  CoreFoundation                      0x0000000180370b88 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
	13  CoreFoundation                      0x000000018036b318 __CFRunLoopRun + 1956
	14  CoreFoundation                      0x000000018036a75c CFRunLoopRunSpecific + 584
	15  GraphicsServices                    0x0000000188f60c98 GSEventRunModal + 160
	16  UIKitCore                           0x000000010e1acb74 -[UIApplication _run] + 868
	17  UIKitCore                           0x000000010e1b0b1c UIApplicationMain + 124
	18  Runner                              0x0000000100b18f5c main + 64
	19  dyld                                0x0000000100e55fa0 start_sim + 20
	20  ???                                 0x0000000100c01e50 0x0 + 4307557968
	21  ???                                 0x853f800000000000 0x0 + 9601533668065542144
)
libc++abi: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Please register custom URL scheme 'app-1-****************-ios-06cbbe****************' in the app's Info.plist file.'
CoreSimulator 857.7 - Device: iPhone 14 Pro (1885FF1D-14A5-43A0-AB08-4251D25503FE) - Runtime: iOS 16.0 (20A360) - DeviceType: iPhone 14 Pro
terminating with uncaught exception of type NSException`

I tried adding Info.plist URL Scheme like the log above. And it doesn't crash anymore.

However, I setup flutterfire for my app with **_flutterfire cli_**. 
I have checked and the file firebase_options.dart is not missing any information.

Thank you for reviewing my issue

**Comment by darshankawar** [comment]
@vanhuugiakien 
I think the error is self-explanatory as it indicates, you need to add the missing config in your info.plist file:

`reason: 'Please register custom URL scheme 'app-1-****************-ios-06cbbe****************' in the app's Info.plist file.`

Since I already have that entry in my file, hence I was unable to replicate the error. But for testing, I removed that entry from the file and ran the app, tapping on Login button throws same error as you reported:

`*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Please register custom URL scheme 'app-1-486685679562-ios-12da9eb8a5b245f9197933' in the app's Info.plist file.'
`

Adding back the entry didn't throw the error as expected.

So the solution is to have that entry in your `info.plist` file. Since you added that and no longer see the crash, I am going ahead and closing this as resolved.
