### ISSUE TITLE
Flutter Firebase Web - how to unsubscribe the Firebse messaging 

### ISSUE THREAD

**Issue by Vedsaga** [firebase/flutterfire#9623]
I compiled my android app to web. When, user logout I am calling below function to clean the token.
```dart

  Future<bool> unsubscribeForCurrentUser({bool esUnsubscribe = false}) async {
    isListeningToNotifications = false;
    esdyPrint.debug("unsubscribeForCurrentUser");
    try {
      await this._firebaseMessaging.deleteToken();
      return true;
    } catch (e) {
      return false;
    }
  }```

And, it does work for Android.
However, above code doesn't seems to clear token due that even when user logout user keep receiving the notification in `WEB`. So, in the existing doc it is not clean how to clean token when we compile Flutter code to Web?

**Comment by Vedsaga** [comment]
Actually, notification does work on web as expected in the web.

 But, the concern is once I subscribed to it then, I can't seems to find anyway to unsubscribe it. Even when user logout, above function which I shared try to clear the token but, it doesn't to unsubscribe the browser.

**Comment by darshankawar** [comment]
> the concern is once I subscribed to it then, I can't seems to find anyway to unsubscribe it.

Yes, it is something not supported by `firebase_messaging` at client side and you will probably need to use admin sdk for it.

I suggest you to ask this question on support channels like StackOverflow or reach out to Firebase support for further resolution.

Closing from here, as I don't think anything is actionable from plugin side on it.
