### ISSUE TITLE
[firebase_messaging]: iOS background message not invoked when app is terminated and user switches to different app afterward

### ISSUE THREAD

**Issue by iosephmagno** [firebase/flutterfire#9625]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you aware of the differences between iOS and Android background message handling?

- [X] I understand that iOS and Android background messages behave differently, and I've designed my application with that in mind.

### Do you have an active Apple Developer account?

- [X] I have an active Apple Developer account.

### Are you using a physical iOS device to test background messages?

- [X] I am using a physical iOS device to test background messages.

### Have you enabled "Remote Notifications" & "Background Mode" (Checking options for "Background Processing" & "Remote Notifications") in your app's Xcode project?

Yes, pic below.

<img width="858" alt="Screenshot 2022-09-27 at 12 52 00" src="https://user-images.githubusercontent.com/83366073/192507172-be82f86c-0fef-4ea0-9d5b-4ddeef969c28.png">

### Have you created an APNs key in your Apple Developer account & uploaded this APNs key to your Firebase console?

Yes, pic below.

<img width="1034" alt="Screenshot 2022-09-27 at 12 54 33" src="https://user-images.githubusercontent.com/83366073/192507506-35ae7929-0a09-4df0-be6f-7ef70564a798.png">

### Have you disabled method swizzling for Firebase in your app?

Yes, pic below.

<img width="695" alt="Screenshot 2022-09-27 at 12 56 17" src="https://user-images.githubusercontent.com/83366073/192507824-fa1d9be3-e831-45c4-889e-86bf568112d9.png">

### Are you sending messages to your app from the Firebase Admin SDK?

Yes, our code below:

admin
  .messaging()
  .send({
    data: {...data, notificationType: 'chat'},
    token: deviceToken,
    android: {
      priority: 'high',
      data, // without it, badge is not displayed in foreground
    },
    apns: {
      payload: {
        aps: {
          contentAvailable: true,
        },
      },
      headers: {
        'apns-push-type': 'background',
        'apns-priority': '5', // Must be `5` when `contentAvailable` is set to true.
        'apns-topic': 'com.backend.presence', // bundle identifier
      },
    },
  })

### Have you requested permission from the user to receive notifications?

- [X] I have the relevant permission to receive notifications.

### Have you used the 'Console' application on your macOS device to check if the iOS device's system is throttling your background messages?

From Console, we see that data-only notifications are always cancelled if app is terminated and user opens a different app.
**"CANCELED: com.apple.pushLaunch.com.backend.presence:A680C5 at prioritv 5 <private>!" (pic below).**

As we wrote in #9300, our comment here https://github.com/firebase/flutterfire/issues/9300#issuecomment-1210349576 ,
Apple told us that silent notifications on iOS are not meant to be used as on Android and we should use "notification" , which are never throttled and arrive quickly. Ofc, since most time content is encrypted, Apple provides the possibility to modify content (decrypt it) before displaying the badge. As mentioned, this is done by using "mutable-content:1" + a Service App Extension.

<img width="1424" alt="Screenshot 2022-09-27 at 15 28 57" src="https://user-images.githubusercontent.com/83366073/192539834-4deeaaf1-4e37-444c-9af9-f38b68b0b9cc.png">

### Additional context and comments

Hello and thanks for the investigation!

Our understanding is that firebase_messaging should integrate "notification" with "mutable-content:1" and "Service App Extension". Without this feature, it is not possible to use the plugin for apps that send **high priority encrypted notifications** (eg. financial or trading apps, chat and social media apps, banks apps). In these cases, app might send encrypted content that should be decrypted before displaying the badge.

**Why we cannot use "data-only notification" as is it now?**
Beyond the throttling, they don't work at all when "app is terminated and user opens another app". This is not a bug of firebase_messaging but Apple's policy. 

**Why we cannot use "notification" as it is now?**
Because without mutable-content and Service App Extension, badges will be displayed before having the opportunity to decrypt notifications' content.

Hope this will be helpful.

**Comment by iosephmagno** [comment]
We just noticed that OneSignal provides the feature. Please see Step 3 of follow documentation:
https://documentation.onesignal.com/docs/flutter-sdk-setup

**Comment by hatemragab** [comment]
@iosephmagno 
Is one signal notifications extension
Will let the ios background handler to be invoked for ios?

**Comment by iosephmagno** [comment]
@hatemragab we are investigating. The idea is, if we get to modify remote notification content before diplaying headup on iOS, we can have Redis that maps users’ devices so that:
- To android devices, we will send data-only notifications.
- To ios devices, we will send remote notifications.

As of now, it seems that this is the only way to deal with notifications when content decryption and 100% delivery is required on iOS.

If firebase_messaging adds a Notification Extension, above idea will require with minimal code on our side. Otherwise, we must use a different plugin on iOS and use firebase_messaging on android only.

**Comment by darshankawar** [comment]
Thanks for the detailed report. Based on the details provided and also additional context provided, I am keeping this issue open and treating as a potential enhancement and to know team's insights on it.

/cc @russellwheatley

**Comment by ben-xD** [comment]
I took a look since @iosephmagno emailed me about this issue. 

Some challenges to support this include:
- launching the Flutter application (or a separate Dart entrypoint) when message is received by notification extension (the Flutter app doesn't always exist when it is received), to allow users to write Dart to e.g. decrypt messages.
- send message (`UNNotificationContent`) from Notification extension to iOS host app (e.g. using [MMWormhole](https://github.com/mutualmobile/MMWormhole)), then send a message from iOS host app to Flutter app (Method channels), and all the way back again, from Flutter, to iOS host, to extension.

**Comment by awaik** [comment]
Hi!
Are there is any news about this issue? For us, it is a blocking thing and we are going to switch to direct APN from the Firebase.

**Comment by iosephmagno** [comment]
@awaik unfortunately you must use iosNotificationExtension. At least, by doing so you will have ios Communication Notification layout on your app.

I'm closing this issue on my side. Maybe explaining this issue in official doc might help devs. We wasted weeks only to understand it.

To Recap:

**Does your app send clear data and you don't need ios Communication Notification layout on iphone?**
Then use firebase_messaging with remote notification. Notifications will work on all app states.

**Does your app send encrypted data or you need ios Communication Notification layout on iphone?**
Then use iosNotificationExtension and remote notification. The Extension will decrypt field and display badge on background state. On foreground state, Extension will decrypt field and firebase_messaging handler will be triggered.

Never use silent notifications on ios because they are throttled and cancelled most of time. This is why they don't work when app is terminated, it is not firebase_messaging issue, it is os that cancels them. 

Keep using silent notification on Android. This means duplicate data in your notification json (one for android using silent notification and one for ios using remote notification + mutableContent:1)

**Comment by awaik** [comment]
@iosephmagno Maybe you have some hints on how to create this extension for the Flutter app?
I tried different ways and still, can't display the message in the background.
I appreciate any hints a lot.

**Comment by CaliforniaGal** [comment]
>   #@`
![IMG_1280 Small](https://user-images.githubusercontent.com/102216433/196098360-3e32022d-a76e-498c-b35d-aed4de3420d8.jpeg)
`
