### ISSUE TITLE
🐛 [FIRESTORE] Number field without decimals is integer if posted from web and double from native

### ISSUE THREAD

**Issue by chbloca** [firebase/flutterfire#9626]
## Bug report

Number fields without decimals are fetched as integers if posted from flutter web and double if posted from native. 

These should be the same type, since it would break native apps if integers are not converted to double if doubles are the desired type.

**Comment by darshankawar** [comment]
Thanks for the feedback. I was able to replicate the current behavior.

1. Data setup at backend:

Added a document field named `age` with `number` as data type:

<img width="178" alt="Screenshot 2022-09-29 at 5 04 35 PM" src="https://user-images.githubusercontent.com/67046386/193021097-f5b66511-e047-4348-8670-153897f01287.png">

2. Retrieved this data on web as below by declaring a var as `double`:

```
CollectionReference collection = FirebaseFirestore.instance.collection('grouptest');
    await collection.doc('user3').get().then((doc) {
      final data = doc.data()! as Map<String,dynamic>;
      print(data);
      double numCheck = data['age'];
      print(numCheck);
```

Running above code printed the value as `20` properly:

<img width="60" alt="Screenshot 2022-09-29 at 5 06 59 PM" src="https://user-images.githubusercontent.com/67046386/193021490-3cdd04ec-716b-4063-b003-8484bc85850b.png">

3. Running same code mobile (ios) throws below error:

```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: type 'int' is not a subtype of type 'double'
#0      _FilmListState.addUser.<anonymous closure> (package:triage/main.dart:112:14)
<asynchronous suspension>
#1      _FilmListState.addUser (package:triage/main.dart:109:5)
<asynchronous suspension>
```

**Comment by russellwheatley** [comment]
If you read the documentation on numbers, there is a difference between how numbers work on the web and native platforms. See: https://dart.dev/guides/language/numbers

Note the way a `double` can also be an `int` when running on the web platform:
<img width="699" alt="Screenshot 2022-09-29 at 15 15 44" src="https://user-images.githubusercontent.com/16018629/193055752-9e4c18f8-894b-4914-b589-ac83a6314960.png">
