### ISSUE TITLE
🐛 [cloud_firestore] Cloud Firestore on web fires two times with wrong data in first snapshot

### ISSUE THREAD

**Issue by OutdatedGuy** [firebase/flutterfire#9630]
## Bug report

**Describe the bug**
I have made a plugin to make firestore coming data paginate nicely. It was running fine before, but right now there some issue with cloud firestore on _web_.

**How my package works:**
1. It sets a query with a limit provided by the user.
2. Then snapshots are being listened to.
3. If the number of docs read are less than query limit, pagination is ended and all listeners are cancelled.
4. After the users scrolls to the bottom of list the limit to the query is increased.
5. Then the previous subscription to snapshots is cancelled.
6. And repeats from step 2

The package is working fine on _android_ but on the _web_ when query limit is increased, the snapshot listener fires two times with
1. docs with size of previous limit
2. docs with size of new limit

As on _web_ it fires two times, due to the first snapshot with old size limit, pagination is ended due to step 3 of how package works.

### Steps to reproduce

1. Go to [package repo](https://github.com/OutdatedGuy/firebase_pagination)
2. Clone the project
3. Create a firebase demo project and set firestore rules to all true
4. Add firebase project credentials in the main function inside `example\lib\main.dart`
5. Run the app in **browser** and click button `Firestore Pagination Example`
6. Add around 25 messages and then go back
7. Again open the `Firestore Pagination Example` and scrolling up
8. You'll see only the last `12` messages are loaded (as default limit setted is `6`)

Do the same on _android_ and you'll see all messages are loaded.

### Expected behavior

All the messages should load in the _web_ app just like it does in the _android_ app.
Meaning the query should not fire twice with 1 snapshot having the wrong data.

### Sample project

https://github.com/OutdatedGuy/firebase_pagination

Firestore Example App Code: `example\lib\firestore_pagination_example.dart`
Firestore Pagination Plugin Code: `lib\src\firestore_pagination.dart`

---

### Example App Demo Video

|  Android | Web |
|--|--|
| <video src="https://user-images.githubusercontent.com/74326345/192822916-f77c6141-031f-4ab1-8638-14d28b0111b3.mp4" /> | <video src="https://user-images.githubusercontent.com/74326345/192822963-59db5e36-2d2f-4675-aa01-c4e486a1f0a5.mp4" /> |

### This is how the example app is supposed to work on web:
> This is with Realtime Database of firebase and not the Firestore

https://user-images.githubusercontent.com/74326345/192826480-2f895ac9-5adc-40e4-8937-51d543c2dd8b.mp4

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.2, on Microsoft Windows [Version 10.0.22622.601], locale en-IN)
Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.3)
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.71.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.18.1
Flutter SDK 3.3.2
firebase_pagination 1.1.3

dependencies:
- cloud_firestore 3.4.7 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- firebase_database 9.1.4 [firebase_core firebase_core_platform_interface firebase_database_platform_interface firebase_database_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]
- very_good_analysis 3.0.2

transitive dependencies:
- async 2.9.0 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.1
- clock 1.1.1
- cloud_firestore_platform_interface 5.7.4 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.8.7 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.16.0
- fake_async 1.3.1 [clock collection]
- firebase_core 1.22.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_core_platform_interface 4.5.1 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 1.7.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_database_platform_interface 0.2.2+4 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_database_web 0.2.1+6 [firebase_core firebase_core_web firebase_database_platform_interface flutter flutter_web_plugins js]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- js 0.6.4
- matcher 0.12.12 [stack_trace]
- material_color_utilities 0.1.5
- meta 1.8.0
- path 1.8.2
- plugin_platform_interface 2.1.2 [meta]
- sky_engine 0.0.99
- source_span 1.9.0 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.1 [source_span]
- term_glyph 1.2.1
- test_api 0.4.12 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- vector_math 2.1.2
```

</details>

---

[Firestore Pagination Example Android]: https://user-images.githubusercontent.com/74326345/192822916-f77c6141-031f-4ab1-8638-14d28b0111b3.mp4
[Firestore Pagination Example Web]: https://user-images.githubusercontent.com/74326345/192822963-59db5e36-2d2f-4675-aa01-c4e486a1f0a5.mp4

**Comment by darshankawar** [comment]
Thanks for the detailed report and code sample. I cloned the project, added sample firebase project to it, ran it on web and added test data and observed that not all data is retrieved:


https://user-images.githubusercontent.com/67046386/192976870-4969e7ef-99bd-4c00-8d31-5863b244a824.mov


In backend, I see the data I added is created, for example:

<img width="439" alt="Screenshot 2022-09-29 at 1 42 17 PM" src="https://user-images.githubusercontent.com/67046386/192977692-6bbe3dad-553c-4eec-8da2-087c72526210.png">


> 8\. You'll see only the last `12` messages are loaded (as default limit setted is `6`)

Can you tell us where and how you have set it rule ?

**Comment by darshankawar** [comment]
I would also suggest to try out a community plugin https://pub.dev/packages/paginate_firestore and see if using it, you get same behavior or not.

Please note that, this isn't an endorsement of the plugin, but just to check if the same behavior occurs with external library as well, or is it just specific to `cloud_firestore`.

**Comment by OutdatedGuy** [comment]
> Can you tell us where and how you have set it rule ?

For example app, the limit is setted here: `example\lib\firestore_pagination_example.dart:36:15` (go to this location in the repo)

And as for the plugin itself, its here: `lib\src\firestore_pagination.dart:183:3` (the function to add more data and set query)

**Comment by darshankawar** [comment]
Thanks for the update. Based on my verification https://github.com/firebase/flutterfire/issues/9630#issuecomment-1261926374, and observing same behavior as reported, keeping this issue open and labeling.

**Comment by OutdatedGuy** [comment]
Yo @darshankawar, any updates here?

**Comment by russellwheatley** [comment]
Hey @OutdatedGuy, could you please provide a small repro of the query you are using that differs between web and android? Happy to look into this issue without the third party dependency, `firebase pagination`. Thanks.

**Comment by OutdatedGuy** [comment]
Yo @russellwheatley, the issue is so old I forgot where the problem exactly occurs. I seem to have fixed my personal issue with some hack.

 Also,

> Happy to look into this issue without the third party dependency, `firebase pagination`

[firebase_pagination](https://github.com/OutdatedGuy/firebase_pagination) is my own package which is having this problem, not a 3rd Party Package.

But anyways, as I have found a [hack](https://github.com/OutdatedGuy/firebase_pagination/commit/c058613786ec2afaae8e5a9a1955e837db1b65bb) to fix my issue, you can go ahead and close this issue.

**Comment by russellwheatley** [comment]
Thanks for the update, @OutdatedGuy 🙏
