### ISSUE TITLE
🐛 [firebase_database] Cannot cast `DataSnapshot` value to `Map<String, dynamic>` on android

### ISSUE THREAD

**Issue by OutdatedGuy** [firebase/flutterfire#9631]
## Bug report

**Describe the bug**
On _android_ cannot cast `DataSnapshot.value` to `Map<String, dynamic>?` even when data is in Map/Json format.
Works perfectly fine on _web_ but not on _android_.

### Steps to reproduce

1. Go to [package repo](https://github.com/OutdatedGuy/firebase_pagination)
2. Clone the project
3. Create a firebase demo project and set realtime database rules to all true
4. Add firebase project credentials in the main function inside `example\lib\main.dart`
5. Run the app in **browser** and click button `RealtimeDB Pagination Example`
6. Add some messages and then go back
7. Again open the `RealtimeDB Pagination Example` and scrolling up
8. See everything works fine.
9. Now repeat all steps on android and see error thrown

### Expected behavior

`DataSnapshot.value` should be type casted into `Map<String, dynamic>` on android just like in web.

### Sample project

https://github.com/OutdatedGuy/firebase_pagination

RealtimeDB Example App Code: `example\lib\realtimedb_pagination_example.dart`
RealtimeDB Pagination Plugin Code: `lib\src\realtime_db_pagination.dart`

---

## Additional context

**Error Message:**

![image](https://user-images.githubusercontent.com/74326345/192836292-b4e92abe-545e-4088-8f41-709e9b57cff8.png)

**Error Log:**

```shell
W/PersistentConnection(14972): pc_0 - Using an unspecified index. Your data will be downloaded and filtered on the client. Consider adding '".indexOn": "createdAt"' at messages to your security and Firebase Database rules for better performance
E/flutter (14972): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type '_InternalLinkedHashMap<Object?, Object?>' is not a subtype of type 'Map<String, dynamic>?' in type cast
E/flutter (14972): #0      _RealtimeDBPaginationState._loadData
package:firebase_pagination/src/realtime_db_pagination.dart:209
E/flutter (14972): #1      _RealtimeDBPaginationState._loadData.<anonymous closure>
package:firebase_pagination/src/realtime_db_pagination.dart:234
E/flutter (14972): <asynchronous suspension>
E/flutter (14972):
```

**RealtimeDB data structure:**

![image](https://user-images.githubusercontent.com/74326345/192837654-ecf50edf-4496-44a7-a007-a18c03456b10.png)

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```shell
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.2, on Microsoft Windows [Version 10.0.22622.601], locale en-IN)
Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.3)
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.71.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```shell
Dart SDK 2.18.1
Flutter SDK 3.3.2
firebase_pagination 1.1.3

dependencies:
- cloud_firestore 3.4.7 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- firebase_database 9.1.4 [firebase_core firebase_core_platform_interface firebase_database_platform_interface firebase_database_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]
- very_good_analysis 3.0.2

transitive dependencies:
- async 2.9.0 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.1
- clock 1.1.1
- cloud_firestore_platform_interface 5.7.4 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.8.7 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.16.0
- fake_async 1.3.1 [clock collection]
- firebase_core 1.22.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_core_platform_interface 4.5.1 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 1.7.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_database_platform_interface 0.2.2+4 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_database_web 0.2.1+6 [firebase_core firebase_core_web firebase_database_platform_interface flutter flutter_web_plugins js]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- js 0.6.4
- matcher 0.12.12 [stack_trace]
- material_color_utilities 0.1.5
- meta 1.8.0
- path 1.8.2
- plugin_platform_interface 2.1.2 [meta]
- sky_engine 0.0.99
- source_span 1.9.0 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.1 [source_span]
- term_glyph 1.2.1
- test_api 0.4.12 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- vector_math 2.1.2
```

</details>

---

**Comment by darshankawar** [comment]
@OutdatedGuy 
It's a bit hard to go through the entire project you shared in order to spot the code that throws the error.
Can you extract and provide the related code snippet here that will help us to analyze the issue better ?

**Comment by OutdatedGuy** [comment]
> I also suggest to take a look at existing questions asked on support channels for the error: `Unhandled Exception: type '_InternalLinkedHashMap<Object?, Object?>' is not a subtype of type 'Map<String, dynamic>?' in type cast` and see if it helps.

Can you provide the link?

**Comment by OutdatedGuy** [comment]
> It's a bit hard to go through the entire project you shared in order to spot the code that throws the error.
> Can you extract and provide the related code snippet here that will help us to analyze the issue better ?

The main problem code is here: `lib\src\realtime_db_pagination.dart:209:9` (open this location in repo)
The function logic is this: `lib\src\realtime_db_pagination.dart199:3`

Code Snippet:
```dart
final List<DataSnapshot> _data = [];

final docsLimit = _data.length + (getMore ? widget.limit : 0);
    var docsQuery = widget.query.limitToFirst(docsLimit);
    if (_data.isNotEmpty) {
      docsQuery = docsQuery.startAt(
        (_data.first.value as Map<String, dynamic>?)?[widget.orderBy],
      );
    }
```

The error line:
```dart
(_data.first.value as Map<String, dynamic>?)?[widget.orderBy],
```

**Comment by darshankawar** [comment]
@OutdatedGuy 
Usually the cast need to be done by dev themselves as the plugin doesn't explicitly does it.
The error you are getting is:

`_InternalLinkedHashMap<Object?, Object?>' is not a subtype of type 'Map<String, dynamic>?'`

Since the value is coming through as `_InternalLinkedHashMap <Object?, Object?>` which is nothing but `Map <Object?, Object?>`

If you wish to cast it to the Map of your choice, you can do this:

```
final value = Map<String, dynamic>.from(event.snapshot.value! as Map<Object?, Object?>);

// or if you know the value of the Map properties are `String`:
final value = Map<String, String>.from(event.snapshot.value! as Map<Object?, Object?>);
```

Closing this for now based on above explaintation and should resolve the error you are getting. If you disagree, write in comments and I'll reopen it.
