### ISSUE TITLE
Show Firebase config when opening "Inspect" in web app running in Flutter

### ISSUE THREAD

**Issue by mycar98765** [firebase/flutterfire#9634]
When I right-clicked and clicked the **"Inspect"** button in the Flutter web app, I unexpectedly discovered that my Firebase configuration was exposed, as shown in the image below:

[![Inspect][1]][1]

[This answer][2] says that the disclosure of API keys is not a security risk, but anyone can put your credentials on their website. So, if someone checks my Flutter web **"inspect"**, someone might put my credentials on his website. Is this not secure, or does this only happen in localhost? If this doesn't just happen in localhost , is there a way to prevent it from being hacked and someone might put my credentials on his site.

Appreciate if someone can advise. Thank you in advance!

  [1]: https://i.stack.imgur.com/iXAfX.png
  [2]: https://stackoverflow.com/a/65310562/16124033

**Comment by darshankawar** [comment]
@mycar98765 
I don't think this is a correct platform to raise this issue / question. I suggest you to reach out to Firebase support and / or StackOverflow for further resolution.

Closing from here.
