### ISSUE TITLE
🐛 [Firebase Auth Flutter] Sign in with Apple crash on ^3.11.0

### ISSUE THREAD

**Issue by alphasuns** [firebase/flutterfire#9645]
## Bug report

**Describe the bug**
When I sign in with apple, after the authentication from apple part, the app just crashes.
After some dig-ins, I found the error is caused by giving a nil value to the NSDictionary object.

![eRqqJWgQcm](https://user-images.githubusercontent.com/34201520/193298010-17da3ab5-e21c-49f7-8305-872ae8760160.jpg)
![pAIydw3PBo](https://user-images.githubusercontent.com/34201520/193298046-bdcda572-f7ad-4702-8e1c-924e925148b8.jpg)

The current version has added a fourth field (`kArgumentAccessToken`) to the `getNSDictionaryFromAuthCredential` result, but the `accessToken` is always nil, so it throws the error.

![img_v2_3c76990b-e955-4162-bb08-99f31f6dac9h](https://user-images.githubusercontent.com/34201520/193298349-a4dfd77c-80e9-4125-8fca-9273432d49d1.jpg)

### Steps to reproduce

1. Tap sign in with apple,
2. After apple authentication, the app just crashed,
3. The log indicates:
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason:
****
-L.
__NSPlaceholderDictionary initWithobjects: forKeys:count:]: attempt to insert nil object from objects[3]'

### Expected behavior

Should not crash and must work as before.

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by CalHoll** [comment]
I just hit this today - please resolve quickly!

**Comment by AndrewPiterov** [comment]
The same issue with me. Tested in real device iPhone 7.

Notice, in line 496 we have a `OAuthCredential` without `accessToken`. But in case you sign in with Google there will be `accessToken`. The question is "Why we do not have access token is case with Apple?" 

![2022-10-02_14-22-33](https://user-images.githubusercontent.com/10525569/193453737-a5405186-a3d6-4240-a390-a89d2485a3ea.png)

**Comment by lovelessX** [comment]
Same issue here with iPhone SE 2.

Flutter 3.3.3.

firebase_core: 1.24.0
firebase_auth: 3.11.0

Works fine with Auth 3.9 or 3.10.

**Comment by Lyokone** [comment]
Already being worked here: https://github.com/firebase/flutterfire/issues/9638
