### ISSUE TITLE
When I build a release app and then install it on the actual device, when there is an error [Exception caught by image resource service], the app crashes and shuts down the app. But the remaining projects do not have this error. Can anyone help me? Thank you very much.

### ISSUE THREAD

**Issue by AnhPhon** [firebase/flutterfire#9661]
<img width="932" alt="image" src="https://user-images.githubusercontent.com/86840994/193542703-41cf9a4e-c6fb-44bb-be56-5cd44e01dc2b.png">
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/86840994/193544034-9dba2519-ce93-4347-90ad-c5dfdb4a6a55.png">

**Comment by darshankawar** [comment]
I don't think this is related to Flutterfire, please search for similar errors on support channels like StackOverflow.
Closing from here.
