### ISSUE TITLE
🐛 [firebase_messaging] Disable Push Notifications permission pop up on iOS startup

### ISSUE THREAD

**Issue by esentis** [firebase/flutterfire#9665]
## Bug report

**Describe the bug**
The bug has already been described on those issues #4576 & #5897. 
However, the solution provided doesn't apply to me since i'm **NOT** using the `flutter_local_notifications` package. 

The issue is that on iOS notifications permissions window is toggled on app startup without calling explicitly the `requestPermission` method.

### Expected behavior

The notifications permission dialog should be prompted when user wants to.

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-arm (Rosetta), locale en-GR)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.71.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
dependencies:
- appsflyer_sdk 6.8.2 [flutter]
- cached_network_image 3.2.1 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- carousel_slider 4.0.0 [flutter]
- collection 1.16.0
- connectivity_plus 2.3.6 [flutter connectivity_plus_platform_interface connectivity_plus_linux connectivity_plus_macos connectivity_plus_web connectivity_plus_windows]
- cupertino_icons 1.0.4
- device_info_plus 4.1.2 [flutter device_info_plus_platform_interface device_info_plus_macos device_info_plus_linux device_info_plus_web device_info_plus_windows]
- facebook_app_events 0.17.1 [flutter]
- firebase_analytics 9.3.6 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_messaging 13.0.4 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_performance 0.8.3+1 [firebase_core firebase_core_platform_interface firebase_performance_platform_interface firebase_performance_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_idensic_mobile_sdk_plugin 1.19.5 [flutter]
- flutter_inappwebview 5.4.3+8 [flutter]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_picker 2.0.5 [flutter]
- flutter_screenutil 5.5.3+2 [flutter]
- flutter_secure_storage 6.0.0 [flutter flutter_secure_storage_linux flutter_secure_storage_macos flutter_secure_storage_platform_interface flutter_secure_storage_web flutter_secure_storage_windows meta]
- flutter_switch 0.3.2 [flutter]
- flutter_widget_from_html 0.8.5 [flutter flutter_widget_from_html_core fwfh_cached_network_image fwfh_chewie fwfh_just_audio fwfh_selectable_text fwfh_svg fwfh_url_launcher fwfh_webview html]
- get 4.6.5 [flutter]
- get_storage 2.0.3 [flutter get path_provider]
- http 0.13.4 [async http_parser meta path]
- image_cropper 3.0.0 [flutter image_cropper_platform_interface image_cropper_for_web]
- image_picker 0.8.5 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_platform_interface]
- in_app_review 2.0.4 [flutter in_app_review_platform_interface]
- infinite_scroll_pagination 3.2.0 [flutter sliver_tools]
- internet_connection_checker 0.0.1+3
- intl 0.17.0 [clock path]
- intl_phone_field 3.1.0 [flutter]
- lint 1.8.2
- load_switch 1.1.0 [flutter]
- local_auth 2.1.2 [flutter intl local_auth_android local_auth_ios local_auth_platform_interface local_auth_windows]
- logger 1.1.0
- lottie 1.2.2 [archive flutter path vector_math]
- moengage_flutter 5.0.0 [flutter]
- package_info_plus 1.4.3+1 [flutter package_info_plus_platform_interface package_info_plus_linux package_info_plus_macos package_info_plus_windows package_info_plus_web]
- path_provider 2.0.11 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- pdf 3.8.2 [archive barcode crypto image meta path_parsing vector_math xml]
- pdfx 2.2.0 [flutter flutter_web_plugins plugin_platform_interface js device_info_plus uuid meta extension synchronized universal_platform photo_view vector_math]
- pie_chart 5.3.0 [flutter]
- pin_code_fields 7.4.0 [flutter]
- pusher_client 2.0.0 [flutter]
- scroll_to_index 3.0.1 [flutter]
- sentry_flutter 6.9.0 [flutter flutter_web_plugins sentry package_info_plus meta]
- share_plus 4.4.0 [meta mime flutter share_plus_platform_interface share_plus_linux share_plus_macos share_plus_windows share_plus_web]
- shimmer 2.0.0 [flutter]
- simple_rc4 0.2.0
- smooth_page_indicator 1.0.0+2 [flutter]
- string_extensions 0.6.2 [convert crypto flutter intl test]
- string_validator 0.3.0
- url_launcher 6.0.20 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 3.0.6 [crypto]
- visibility_detector 0.3.3 [flutter]
- webview_flutter 3.0.4 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]
```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the report @esentis 
I looked at the `firebase_messaging` plugin example and in it, the `FirebaseMessaging.instance.requestPermission` is implemented using `firebase_messaging_platform_interface` plugin as below:

https://github.com/firebase/flutterfire/blob/39ca00299ec5c6e0f2dc9b0b5a8d71b8d59d51d4/packages/firebase_messaging/firebase_messaging/example/lib/permissions.dart#L23

Running that example, I didn't observe the permission popup being shown without explicitly calling the method:

<img width="357" alt="Screenshot 2022-10-04 at 12 48 53 PM" src="https://user-images.githubusercontent.com/67046386/193758958-6d2afeff-2e17-4526-be64-df77291eab52.png">

Can you try the same example and check using it, you still get same behavior as you reported ?

**Comment by esentis** [comment]
Thanks a lot for the quick response. The example provided indeed doesn't prompt the permissions dialog, however I don't see anything different implemented code-wise. 
I still get the dialog in my code as soon as the app is installed, in fact the dialog pops in splash screen without even Firebase being initialized yet. Any tip is more than welcome !

**Comment by darshankawar** [comment]
> I still get the dialog in my code as soon as the app is installed, in fact the dialog pops in splash screen without even Firebase being initialized yet.

Are you using any other community plugin that might be requesting the permission ? such as `flutter_app_badger` or `local_notifier` or any other ? If so, that might most probably be the reason why you are seeing the dialog in splash screen.

**Comment by esentis** [comment]
I have gone through all my libraries one by one but without any success. I was using OneSignal (still using in production) before trying to refactor to FCM and the permissions dialog was (is) toggled explicitly correctly so it's not like the app never used push notifications before.

**Comment by esentis** [comment]
@darshankawar After further investigation I found the conflicting library, it was moEngage. For some reason their SDK is prompting the dialog ! Closing this as it is not FCM's issue.
