### ISSUE TITLE
🐛 [firebase_core] Subscribers not Receiving Notifications

### ISSUE THREAD

**Issue by mado-bohsali** [firebase/flutterfire#9676]
My subscribers aren't receiving notifications although I didn't change my code since Spring 2021. The flutter dependencies I rely on are:
firebase_messaging: ^10.0.4
firebase_core: ^1.4.0

**Comment by mado-bohsali** [comment]
No implementation found for method Messaging#requestPermission on channel plugins.flutter.io/firebase_messaging

**Comment by darshankawar** [comment]
Please don't open multiple issues for same reason. Let's follow-up in https://github.com/firebase/flutterfire/issues/9675
