### ISSUE TITLE
🐛 [firebase_messaging] Not receiving notification when app is terminated

### ISSUE THREAD

**Issue by anmolguptach** [firebase/flutterfire#9685]
## Bug report

**Describe the bug**
When sending a notification request from postman the app is not able to receive the notification only in the killed state.

### Expected behavior
Must receive notification in the killed state as well.

JSON Request:
```
{
    "registration_ids": [
        "fcz5wrOTRBOzcYZHplzIWY:APA91bGch5MlcgN9fS5pLUd9O4gZYHi3Njhae1T0IxPYTwIQ9qllwqfwebUoZBZ22qZRnDFD53U0PoLsYEh1n4FKmlVb4BRxsyWcSdoXn8o3FJ6CGwFOE0eyCACi1VWff6ioCHhveRyr"
    ],
    "notification": {
        "body": "notification body",
        "title": "Background title",
        "android_channel_id": "push_notification",
        "sound": false
    },
    "data": {
        "body": "data body",
        "title": "Data",
        "_id": 1338
    },
    "android": {
        "priority": "high"
    }
}
```
Response:
```
{
    "multicast_id": 1022217697461827192,
    "success": 1,
    "failure": 0,
    "canonical_ids": 0,
    "results": [
        {
            "message_id": "0:1665057900190978%ca8a4049ca8a4049"
        }
    ]
}
```
Api:
`https://fcm.googleapis.com/fcm/send`

main.dart

```
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:firebase_push_notification/home_screen.dart';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'firebase_options.dart';
import 'package:firebase_core/firebase_core.dart';

import 'local_notification.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  LocalNotificationService.initialize();

  FirebaseMessaging.onBackgroundMessage(backGroundHandler);
  FirebaseMessaging.instance.getInitialMessage();
  await FirebaseMessaging.instance.setForegroundNotificationPresentationOptions(
    alert: true,
    badge: true,
    sound: true,
  );

  runApp(const MyApp());
}

Future<void> backGroundHandler(RemoteMessage message) async {
  LocalNotificationService.initialize();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  SharedPreferences sharedPreferences = await SharedPreferences.getInstance();
  await sharedPreferences.setString(
    "notification",
    message.toMap().toString(),
  );
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: HomeScreen(),
    );
  }
}
```

local notification.dart

```
import 'dart:math';

import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';

class LocalNotificationService {
  static final FlutterLocalNotificationsPlugin _notificationsPlugin =
      FlutterLocalNotificationsPlugin();

  static void initialize() {
    const InitializationSettings initializationSettings =
        InitializationSettings(
      android: AndroidInitializationSettings("@mipmap/ic_launcher"),
    );

    _notificationsPlugin.initialize(initializationSettings);
  }

  static void displayNotification(RemoteMessage message, String number) async {
    print("notification received");
    print(message.data.toString());

    try {
      final id = Random().nextInt(20000);
      const NotificationDetails notificationDetails = NotificationDetails(
        android: AndroidNotificationDetails(
            "push_notification", "push_notification_channel",
            priority: Priority.high),
      );
      await _notificationsPlugin.show(
        id,
        message.notification!.title.toString() + number,
        message.notification!.body.toString(),
        notificationDetails,
        payload: message.data['_id'],
      );
    } on Exception catch (e) {}
  }
}
```

homescreen.dart

```
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:firebase_push_notification/screens/second_screen.dart';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'local_notification.dart';

class HomeScreen extends StatefulWidget {
  const HomeScreen({
    Key? key,
  }) : super(key: key);

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  getDeviceToken() async {
    FirebaseMessaging firebaseMessaging = FirebaseMessaging.instance;
    String? token = await firebaseMessaging.getToken();
    debugPrint(token.toString());
    SharedPreferences sharedPreferences = await SharedPreferences.getInstance();
    data = sharedPreferences.get("notification").toString();
    setState(() {});
  }

  String data = "";
  String id = "";
  @override
  void initState() {
    getDeviceToken();
    super.initState();
    FirebaseMessaging.instance.getInitialMessage().then((message) {
      if (message != null) {
        LocalNotificationService.displayNotification(message, "1");
        setState(() {
          id = "getInitialMessage${message.data['_id']}";
        });
      }
    });

    //called when the app is opened
    FirebaseMessaging.onMessage.listen((message) {
      LocalNotificationService.displayNotification(message, "2");
      debugPrint(message.toMap().toString());
      setState(() {
        id = "onMessage${message.data['_id']}";
        notificationNumber++;
      });
    });

    FirebaseMessaging.onMessageOpenedApp.listen(
      (message) {
        debugPrint("onMessageOpenedApp");
        debugPrint(message.toMap().toString());

        Navigator.of(context)
            .push(MaterialPageRoute(builder: (_) => const SecondScreen()));
        setState(() {
          id = "onMessageOpenedApp${message.data['_id']}";
        });
      },
    );
  }

  int notificationNumber = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(actions: [
        GestureDetector(
          onTap: () {
            Navigator.push(
              context,
              MaterialPageRoute(
                builder: (_) => const SecondScreen(),
              ),
            );
          },
          child: CircleAvatar(
            child: Text(notificationNumber.toString()),
          ),
        )
      ]),
      body: Center(
        child: Column(
          children: [
            Text(data),
            Text(id),
          ],
        ),
      ),
    );
  }
}

```
meta data

```
  <meta-data
                android:name="com.google.firebase.messaging.default_notification_channel_id"
                android:value="push_notification"/>
```

**Comment by darshankawar** [comment]
Thanks for the report @anmolguptach 
Can you provide `flutter doctor -v` and plugin version ?
I also suggest you to check the [official plugin example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example) and see if using it, you get same behavior or not.

**Comment by anmolguptach** [comment]
> Thanks for the report @anmolguptach Can you provide `flutter doctor -v` and plugin version ? I also suggest you to check the [official plugin example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example) and see if using it, you get same behavior or not.

not getting a notification for the very first time only in the killed state, but when I open the for the second time and close the app, and then try to send the notification for the second time using postman in the background state it works.

```
  firebase_messaging: ^13.0.4
  flutter_local_notifications: ^11.0.1

```

```
anmolgupta@anmols-mbp firebase_push_notification % flutter doctor -v
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.3.2 on channel stable at /Users/anmolgupta/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (3 weeks ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/anmolgupta/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.68.1)
    • VS Code at /Users/anmolgupta/Desktop/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • RMX3242 (mobile) • SOT4RKPRMJWCKRJF • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos            • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
anmolgupta@anmols-mbp firebase_push_notification % 

```

**Comment by anmolguptach** [comment]
> > when I open the for the second time and close the app, and then try to send the notification for the second time using postman in the background state it works.
> 
> Does this happen consistently when you try eveytime ? That, only first time the notification is not received, but works second time onwards ? If first time, the notification is not received, do you not get it in the system tray as well ?, ie, in notification popup and second time onwards, you get it in system tray ?

Installing the app for the first time(through debugging):
1. Getting notification in the foreground
2. Getting notifications in the background
3. Not getting a notification in the killed state

Opening the app for the second time after killing the app:
1. Getting notifications in the foreground
2. Getting notifications in the background
3. Getting a notification in the killed state

**Comment by anmolguptach** [comment]
> > > when I open the for the second time and close the app, and then try to send the notification for the second time using postman in the background state it works.
> > 
> > 
> > Does this happen consistently when you try eveytime ? That, only first time the notification is not received, but works second time onwards ? If first time, the notification is not received, do you not get it in the system tray as well ?, ie, in notification popup and second time onwards, you get it in system tray ?
> 
> Installing the app for the first time(through debugging):
> 
> 1. Getting notification in the foreground(getting notification in system tray)
> 2. Getting notifications in the background(getting notification in system tray)
> 3. Not getting a notification in the killed state(not getting notification in system tray)
> 
> Opening the app for the second time after killing the app:
> 
> 1. Getting notifications in the foreground(getting notifications in the system tray)
> 2. Getting notifications in the background(getting notifications in the system tray)
> 3. Getting a notification in the killed state(getting a notification in the system tray)

its weird but this issue is coming only when I am debugging, but when I install the app through the release version everything is working fine.

**Comment by anmolguptach** [comment]
`GCM-DMM : broadcast intent callback: result=CANCELLED
`
this is the issue I am getting in the below case


Installing the app for the first time(through debugging):
**Not getting a notification in the killed state(not getting notification in system tray)**

**Comment by mDNA1198** [comment]
When you install app for the first time, and then kill the app; The android debugger is still attached to it and it somehow restricts background services from running. That's not a firebase issue. If you try to run the app in release mode, this behaviour does not repeats. 

But in debug you have to kill the app and then open app and then kill again to start the background services.

For more info try below steps:

- Run app in debug mode.
- Remove from recent
- Go into "App info" 
- You will see that "Force stop" option is not available because app is completely killed along with its services.

Now open the same debug app without running it from IDE.
- Remove from recent
- Go into "App info" 
- You will see that "Force stop" option is now available because app has services running.

**Comment by anmolguptach** [comment]
> > GCM-DMM : broadcast intent callback: result=CANCELLED
> 
> This doesn't seem to be due to plugin's behavior / issue. See [this](https://stackoverflow.com/questions/39480931/error-broadcast-intent-callback-result-cancelled-forintent-act-com-google-and) link and underlying comments for more details on the error.
> 
> Also take a look at above comment for your further reference.

yes we ¸can close this issue @darshankawar
