### ISSUE TITLE
🐛 [firestore] Firestore reference documentation AWOL

### ISSUE THREAD

**Issue by puf** [firebase/flutterfire#9691]
## Bug report

**Describe the bug**
The [Firebase reference documentation](https://firebase.google.com/docs/reference) links for Firestore on Flutter to https://pub.dev/documentation/cloud_firestore/latest/, which is not working at the moment. I typically use this direct link myself https://pub.dev/documentation/cloud_firestore/latest/cloud_firestore/cloud_firestore-library.html, which is also missing.

### Steps to reproduce

1. Go to the Firebase reference documentation I linked above
2. Click the Flutter node in the leftnav, and then on Firestore (the first child)
4. See that you don't get to the Firestore reference documentation for Flutter

### Expected behavior

I expect to get to the Firestore reference documentation for Flutter.

**Comment by darshankawar** [comment]
Thanks for the report @puf

**Comment by Lyokone** [comment]
Hello @puf,
The link is currently working, it's an issue with pub.dev. The documentation gets triggered again automatically if it fails.  
I'll close this :)
