### ISSUE TITLE
[📚] Firebase Messaging documentation is incomplete

### ISSUE THREAD

**Issue by masteradit** [firebase/flutterfire#9695]
I followed all the steps mentioned on https://firebase.google.com/docs/cloud-messaging/flutter/client, but I was getting some errors on web related to `firebase-messaging-sw.js`. After searching a bit, I went back to the old documentation on https://firebase.flutter.dev/docs/messaging/usage and realised I need to manually create the file and make some changes in the `web` folder. This is not mentioned anywhere in the current documentation.

**Comment by masteradit** [comment]
I think I can contribute to this by updating the docs. Should I create a PR for this?

**Comment by darshankawar** [comment]
Thanks for the report. Feel free to open a PR.

**Comment by Joseph-Nathan** [comment]
hi there , do you now any trick to display data message in web ?

**Comment by ycherniavskyi** [comment]
@masteradit, it appears that the documentation already exists [here](https://firebase.google.com/docs/cloud-messaging/flutter/receive#web). With that in mind, it seems appropriate to close this issue.

**Comment by russellwheatley** [comment]
as mentioned above, this is now documented.
