### ISSUE TITLE
[📚] Wrong docs for cloud_functions region specific example code

### ISSUE THREAD

**Issue by OutdatedGuy** [firebase/flutterfire#9701]
The example code to get the callable function for _specific region_ is wrong [here](https://firebase.flutter.dev/docs/functions/usage#specifying-regions).

<img width="747" alt="image" src="https://user-images.githubusercontent.com/74326345/194882818-25a0bccd-362a-461c-ba13-3ef4a822c10b.png">

The code should instead be like this:
```dart
HttpsCallable callable = FirebaseFunctions
  .instanceFor(region: 'europe-west1')
  .httpsCallable('getName');
```

**Comment by OutdatedGuy** [comment]
@darshankawar any updates?

**Comment by russellwheatley** [comment]
That documentation website is now archived, you can see it is correct in the example app demonstration here: https://github.com/firebase/flutterfire/blob/master/packages/cloud_functions/cloud_functions/example/lib/main.dart#L67
