### ISSUE TITLE
🐛  Add GitHub Action workflow to check that every file has a license header

### ISSUE THREAD

**Issue by nilsreichardt** [firebase/flutterfire#9702]
I noticed that some files has no license header. We could add a GitHub Action workflow to check that every file has a license header. We could use [addlicense](https://github.com/google/addlicense) by Google to check if every file has a license header.

**Comment by nilsreichardt** [comment]
I'm going to add this 👍

**Comment by russellwheatley** [comment]
We can close this now as we have a check for license headers.
