### ISSUE TITLE
🐛 [ALL] Failed to read `firebase_sdk_version` if Pods libraries are not linked by the default symlink method

### ISSUE THREAD

**Issue by AlexV525** [firebase/flutterfire#9716]
## Bug report

When Pods libraries are not linked by the default symlink method, `firebase_sdk_version` cannot be obtained from the base script.

### Steps to reproduce

Use https://github.com/fluttercandies/flutter_wechat_assets_picker/blob/main/example/ios/Podfile to reproduce.

```
Analyzing dependencies
[!] Failed to load 'firebase_analytics' podspec: 
[!] Invalid `firebase_analytics.podspec` file: [!] Unsupported version requirements. [nil] is not valid..

 #  from /xxx/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-9.3.8/ios/firebase_analytics.podspec:41
 #  -------------------------------------------
 #    s.dependency 'firebase_core'
 >    s.dependency firebase_analytics, firebase_sdk_version
 #  
 #  -------------------------------------------
```

**Comment by AlexV525** [comment]
We might figure out another elegant way to detect libraries, rather than read them by fixed paths.

**Comment by darshankawar** [comment]
Thanks for the report @AlexV525. Using the podfile provided, seeing same behavior.

```
Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `firebase_analytics` from `/Users/dhs/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-9.3.6//ios/firebase_analytics.podspec`
    [!] Failed to load 'firebase_analytics' podspec: 
    [!] Invalid `firebase_analytics.podspec` file: [!] Unsupported version requirements. [nil] is not valid..

     #  from /Users/dhs/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-9.3.6/ios/firebase_analytics.podspec:41
     #  -------------------------------------------
     #    s.dependency 'firebase_core'
     >    s.dependency firebase_analytics, firebase_sdk_version
     #  
     #  -------------------------------------------
```

**Comment by AlexV525** [comment]
The problem, as I observe, is caused by:

https://github.com/firebase/flutterfire/blob/75cd372b110fb5ca65ec684f525a4333e50c450c/packages/firebase_analytics/firebase_analytics/ios/firebase_analytics.podspec#L15

The check might fail which you can see below codes do not strictly force it to succeed, then the version will be `nil`able eventually. The code only implements the path that Flutter implemented by default.

Additionally, the example `Podfile` solves the symlink issue which causes the directory relationship to be too heavy when opening projects from Xcode.

**Comment by TarekkMA** [comment]
Hi @AlexV525  ,

Thank you for your report! Since this issue was opened, the implementation details have changed significantly. If you feel that this issue is still relevant, please feel free to open a new issue with updated context. We appreciate your understanding and support.
