### ISSUE TITLE
🐛 FIREBASE_AUTH The supplied auth credential is malformed or has expired

### ISSUE THREAD

**Issue by Syscomp-Software** [firebase/flutterfire#9736]
I'm trying to login with facebook credentials, and I'm getting the return:

`[firebase_auth/invalid-credential] The supplied auth credential is malformed or has expired. [ Unable to retrieve user's identity from facebook.com response, JSON response does not contain id: {"picture":{"data":{"is_silhouette":false,"width":100,"url":"https://platform-lookaside.fbsbx.com/platform/profilepic/?asid=5300155540111150&height=100&width=100&ext=1668284612&hash=AeRnXj5Vc2DfvPh1yV4","height":100}}} ]`

this only happens with facebook, when I use authentication with google it works normal.

Version 
firebase_auth: ^3.11.2  
flutter_facebook_auth: ^4.4.1+1
google_sign_in: ^5.4.2

**Comment by darshankawar** [comment]
> [ Unable to retrieve user's identity from facebook.com response, JSON response does not contain id: {"picture":{"data":{"is_silhouette":false,"width":100,"url":"https://platform-lookaside.fbsbx.com/platform/profilepic/?asid=5300155540111150&height=100&width=100&ext=1668284612&hash=AeRnXj5Vc2DfvPh1yV4","height":100}}} ]

@Syscomp-Software  Looking at the error, it seems to be coming from facebook.com api and not from `firebase_auth`. I suggest you to reach out to plugin owner's repo for further resolution.

Closing from here.

**Comment by noinskit** [comment]
Interesting, I got the same error today in production, it does suggest some change on the server side (as opposed to Facebook or Firebase Auth plugins).
