### ISSUE TITLE
🐛 [flutterfire_ui] sign_in_with_apple dependency

### ISSUE THREAD

**Issue by alanguodev** [firebase/flutterfire#9740]
## Bug report

**Describe the bug**
After I upgrade to Flutter 3.3 I got the following build error for Android by using flutterfire_ui:
```
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':sign_in_with_apple' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50
```

How can I fix this? 

### Steps to reproduce

2. '...'
4. See error or incorrect behavior

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by darshankawar** [comment]
@alanguodev 
The plugin has been updated just yesterday : https://github.com/firebase/flutterfire/pull/9343, so I suggest you to use the updated plugin version when it will be available on `pub.dev` and see if using it, the error you reported gets resolved or not.
