### ISSUE TITLE
🐛 [uses or overrides a deprecated API.] uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by mehdiRTH** [firebase/flutterfire#9741]
hello, I was using my app normally then when I decided to run it again it showed me this error I tried every solution on the internet but it didn't solve my problem .

 and when I tried to rebuild my application it showed me this error

<details><summary>Click To Expand</summary>

```
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: D:\flutter_conf\flutter\.pub-cache\hosted\pub.dartlang.org\native_device_orientation-1.1.4\android\src\main\java\com\github\rmtmckenzie\native_device_orientation\NativeDeviceOrientationPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: D:\flutter_conf\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_database-9.1.7\android\src\main\java\io\flutter\plugins\firebase\database\FirebaseDatabasePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.


FAILURE: Build failed with an exception.

* Where:
Script 'D:\flutter_conf\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1159

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'D:\flutter_conf\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
```

</details>

**Comment by darshankawar** [comment]
@mehdiRTH 
Can you provide `flutter doctor -v`, `pubspec.yaml`, command you were running that throws this error ?
Also provide verbose log of the command by adding `-v` to it and share it here.

**Comment by mehdiRTH** [comment]
> @mehdiRTH Can you provide `flutter doctor -v`, `pubspec.yaml`, command you were running that throws this error ? Also provide verbose log of the command by adding `-v` to it and share it here.
this is what flutter doctor showed me
`flutter doctor -v
[√] Flutter (Channel stable, 3.3.4, on Microsoft Windows [version 10.0.19041.264], locale fr-FR)
    • Flutter version 3.3.4 on channel stable at D:\flutter_conf\flutter    
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (2 weeks ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\DELL\AppData\Local\Android\sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio2\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)


[√] VS Code (version 1.72.2)
    • VS Code at C:\Users\DELL\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.50.0

[√] Connected device (3 available)
    • SM N976N (mobile) • 127.0.0.1:62001 • android-x86    • Android 7.1.2 (API 25)
    • Windows (desktop) • windows         • windows-x64    • Microsoft Windows [version 10.0.19041.264]
    • Chrome (web)      • chrome          • web-javascript • Google Chrome 106.0.5249.119

[√] HTTP Host Availability
    • All required HTTP hosts are available

`

and this is my pubspec.yaml 


`
name: flutter_ui
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  syncfusion_flutter_datepicker: ^20.3.48
  simple_animations: ^5.0.0+2
  firebase_auth: ^3.11.2
  cloud_firestore: ^3.5.1
  firebase_core: ^1.24.0
  flutter_svg: ^1.1.5
  curved_navigation_bar: ^1.0.3
  barcode_widget: ^2.0.1
  flutter_qr_bar_scanner: ^3.0.2
  flutter_cache_manager: ^3.3.0
  firebase_database: ^9.1.7
  firebase_storage: ^10.3.11
  qr_flutter: ^4.0.0
  path_provider: ^2.0.11
  flutter_plugin_android_lifecycle: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0



# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

`

**Comment by darshankawar** [comment]
@mehdiRTH 
The flutterfire plugins have recently upgraded to latest versions, so can you try upgrading them to latest versions and see if it helps ?

**Comment by mehdiRTH** [comment]
> @mehdiRTH The flutterfire plugins have recently upgraded to latest versions, so can you try upgrading them to latest versions and see if it helps ?

i did that and nothing changed, i created another app to test and i found  Path Provider give me this error can you please tell me why

**Comment by darshankawar** [comment]
Thanks for digging in. Can you provide the latest error log ? Does it throw the error only using `path_provider` or with combination of flutterfire plugins ?

**Comment by mehdiRTH** [comment]
> Thanks for digging in. Can you provide the latest error log ? Does it throw the error only using `path_provider` or with combination of flutterfire plugins ?

i find another way to my problem i will not use path provider i will use api's thank you sir for your help

**Comment by darshankawar** [comment]
Closing based on above comment.
