### ISSUE TITLE
firebase_app_check throws error

### ISSUE THREAD

**Issue by Anonymousgaurav** [firebase/flutterfire#9743]
## Bug report

**Describe the bug**
After installing all the dependencies of flutter firebase i'm getting exception from firebase_app_check

### Steps to reproduce

1. Go to 'pubysec.yaml and add dependecies.

2.   # Firebase
  firebase_core: ^1.11.0
  firebase_analytics: ^9.0.5
  firebase_auth: ^3.3.5
  firebase_messaging: ^11.2.5
  firebase_crashlytics: ^2.4.5
  firebase_app_check: ^0.0.6+6

3.  initialize in main.dart 
main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  await FirebaseAppCheck.instance.activate();

4. add in build.gradle.
    implementation 'com.google.firebase:firebase-appcheck-playintegrity:16.0.2'

5. run the app
7. See error or incorrect behavior

../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_app_check_platform_interface-0.0.4/lib/src/method_channel/utils/exception.dart:13:11: Error: Method not found: 'Error.throwWithStackTrace'.
    Error.throwWithStackTrace(exception, stackTrace);
          ^^^^^^^^^^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_app_check_platform_interface-0.0.4/lib/src/method_channel/utils/exception.dart:16:9: Error: Method not found: 'Error.throwWithStackTrace'.
  Error.throwWithStackTrace(
        ^^^^^^^^^^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_app_check_platform_interface-0.0.4/lib/src/method_channel/utils/exception.dart:11:7: Error: A non-null value must be returned since the return type 'Never' doesn't allow null.
Never convertPlatformException(Object exception, StackTrace stackTrace) {

[✓] Flutter (Channel stable, 2.5.0, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 2.5.0 at /Users/gauravswarankar/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (1 year, 1 month ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

**Comment by darshankawar** [comment]
@Anonymousgaurav 
You are on very old version of the framework along with plugins, so I recommend to upgrade all dependencies to latest and framework to latest stable, which should resolve the issue you are facing.

Closing for now. If, after upgrading, you see same behavior, write in comments and I'll reopen it.
