### ISSUE TITLE
🐛 [firebase_core] Unable to upgrade to 2.0.0

### ISSUE THREAD

**Issue by freakness** [firebase/flutterfire#9749]
## Bug report

**Describe the bug**
Can not upgrade to latest version of firebase_core (2.0.0) in combination with another dependency from flutterfire.

Following error is given by flutter pub get:

```
flutter pub upgrade
Resolving dependencies...
Because firebase_remote_config >=1.0.0-dev.2 depends on firebase_core ^1.10.0 and picky depends on firebase_core ^2.0.0, firebase_remote_config >=1.0.0-dev.2 is forbidden.
So, because picky depends on firebase_remote_config ^3.0.0, version solving failed.
```

### Steps to reproduce

In pubspec.yaml: update firebase_core to 2.0.0 and update firebase_remote_config to 3.0.0

### Expected behavior

No errors during flutter pub get. Dependencies resolve. 

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-arm, locale en-BE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.72.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

---

### Flutter dependencies
Unable to run it as dependency resolution fails. Adding relevant part of pubspec.yaml

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
  firebase_core: ^2.0.0
  firebase_analytics: ^10.0.0
  firebase_auth: ^4.0.0
  firebase_messaging: ^14.0.0
  firebase_dynamic_links: ^5.0.0
  firebase_storage: ^11.0.0
  cloud_functions: ^4.0.0
  cloud_firestore: ^4.0.0
  firebase_crashlytics: ^3.0.0
  firebase_remote_config: ^3.0.0

```

</details>

---

**Comment by AlmogRnD** [comment]
Same issue, following

**Comment by Purus** [comment]
This happens with other packages like flutterfire, etc too.

**Comment by darshankawar** [comment]
@freakness and everyone facing this issue:

I tried the same on `firebase_remote_config` plugin example which currently has below dependencies and versions:

`firebase_core: ^1.24.0`
`firebase_remote_config: ^2.0.13`

After upgrading `firebase_core` to latest, ie, `^2.0.0`, I get the same compile error as reported:

```
Running "flutter pub get" in firebase_remote_config_example...     
Because firebase_remote_config >=1.0.0-dev.2 <3.0.1 depends on firebase_core ^1.10.0 and triage depends on firebase_core ^2.0.0, firebase_remote_config >=1.0.0-dev.2 <3.0.1 is forbidden.
So, because triage depends on firebase_remote_config ^2.0.13, version solving failed.
pub get failed (1; So, because triage depends on firebase_remote_config ^2.0.13, version solving failed.)
Process finished with exit code 1
```

Upgrading `firebase_remote_config` to latest version, ie, `^3.0.1`, the compilation was successful and didn't throw above error:

```
Running "flutter pub get" in firebase_remote_config_example...      1,339ms
Process finished with exit code 0
```

The idea is to make sure to use all latest versions of all FlutterFire plugins that have been updated very recently, as below:

```
  firebase_core: ^2.0.0
  firebase_remote_config: ^3.0.1
  firebase_analytics: ^10.0.0
  firebase_auth: ^4.0.0
  firebase_messaging: ^14.0.0
  firebase_dynamic_links: ^5.0.0
  firebase_storage: ^11.0.0
  cloud_functions: ^4.0.0
  cloud_firestore: ^4.0.0
  firebase_crashlytics: ^3.0.0
```

With above versions of plugins, I didn't get the compile error.

Also, since this is a breaking change per latest changelog, https://pub.dev/packages/firebase_core/changelog#200.

So I suggest you all to update all FF plugins to latest and confirm if you still see the same error or not.

**Comment by freakness** [comment]
The latest patch updates to the packages indeed fix this issue. Closing, thanks for the swift fix.

**Comment by Purus** [comment]
I guess there are still some issues, athough most of them are fixed.

```
Because mozhli depends on flutterfire_ui ^0.4.3+16 which depends on firebase_auth ^3.10.0, firebase_auth ^3.10.0 is required.
So, because mozhli depends on firebase_auth ^4.0.1, version solving failed.
pub get failed (1; So, because mozhli depends on firebase_auth ^4.0.1, version solving failed.)
```
