### ISSUE TITLE
🐛 [flutterfire_ui] Dependency resolution conflict with firebase_auth: ^4.0.0

### ISSUE THREAD

**Issue by AlmogRnD** [firebase/flutterfire#9752]
## Bug report

**Describe the bug**
Getting dependency issues when trying to upgrade to the latest version, "0.4.3+16" 

### Steps to reproduce

1.Add flutterfire_ui: ^0.4.3+16 to pub file 
2. run flutter pub get 
3. you will get the following error 

```
[dogbase-mobile-app] flutter pub get
Running "flutter pub get" in dogbase-mobile-app...              
Because flutterfire_ui >=0.4.3+10 depends on firebase_auth ^3.10.0 and dogbase_app depends on firebase_auth ^4.0.0, flutterfire_ui >=0.4.3+10 is forbidden.
So, because dogbase_app depends on flutterfire_ui ^0.4.3+16, version solving failed.
pub get failed (1; So, because dogbase_app depends on flutterfire_ui ^0.4.3+16, version solving failed.)
exit code 1
```

### Expected behavior

Be able to upgrade to the latest version supporting firebase_auth latest version. 

---

**Comment by danagbemava-nc** [comment]
I can reproduce the issue with the latest versions of `firebase_auth` and `flutterfire_ui` with the latest version of flutter stable `3.3.4`

### Steps to reproduce
- Add `flutterfire_ui: ^0.4.6+13` and `firebase_auth: ^4.0.1` to your project
- Run flutter pub get

```
Running "flutter pub get" in fui_deps...                        
Because flutterfire_ui >=0.4.3+10 depends on firebase_auth ^3.10.0 and fui_deps depends on firebase_auth ^4.0.1, flutterfire_ui >=0.4.3+10 is forbidden.
So, because fui_deps depends on flutterfire_ui ^0.4.3+16, version solving failed.
pub get failed (1; So, because fui_deps depends on flutterfire_ui ^0.4.3+16, version solving failed.)
exit code 1
```

From what I see `flutterfire_ui` still depends on `firebase_auth: ^3.10.0`

https://github.com/firebase/flutterfire/blob/07279cb1005ebbf5c223aa8cb6b12fba34398042/packages/flutterfire_ui/pubspec.yaml#L20

Labeling for further investigation.

**Comment by AlmogRnD** [comment]
Any news on this? I'm thinking I might need to remove Flutter Fire UI?

**Comment by russellwheatley** [comment]
Hey folks, we have updated the problem dependencies and a new version of `flutterfire_ui` will go out in the next release. 

Please note however; `flutterfire_ui` is now in a deprecated state. As such, this will be its last release. Do not worry though, It has just been replaced by `firebase_ui_*` packages which you can read more about how to migrate [here](https://github.com/firebase/flutterfire/blob/master/packages/flutterfire_ui/README.md). Once the release goes out, this documentation will be reflected in the [flutterfire_ui pub.dev documentation](https://pub.dev/packages/flutterfire_ui).
