### ISSUE TITLE
PlatformException(sign_in_failed, com.google.GIDSignIn, keychain error, null

### ISSUE THREAD

**Issue by yunusdtarla** [firebase/flutterfire#9769]
Hello everyone two days ago I was able to connect to the Firebase system without any problems, but now I can't login to the application. Although the accounts are correct in Google and email entries, it gives an error. Which setting do you think is broken?

PlatformException(sign_in_failed, com.google.GIDSignIn, keychain error, null

<img width="1022" alt="B156A0ED-6EF0-4E5C-82DE-5168C259F213" src="https://user-images.githubusercontent.com/72821593/197057171-a7405568-7db8-442c-8ab9-ae3fb717b77e.png">

**Comment by danagbemava-nc** [comment]
Hi @yunusdtarla, please provide the following information: 

- The platform(s) & device(s) you're experiencing this issue on
- The versions of the firebase dependencies you're using
- Your flutter doctor -v

Thank you

**Comment by yunusdtarla** [comment]
hi @danagbemava-nc 

- platform: iOS, emulator, İos Deployment Target 12.O, Xcode 11.0
- Firebase SDK :8.0.0, 
- dependencies: cloud_firestore: ^3.5.1, firebase_auth: ^3.3.7, firebase_core: ^1.24.0, google_sign_in: ^5.2.4, 
- flutter doctor -v: 
Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.72.2)
    • VS Code at /Users/yunusdtarla/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

- the complete error message: PlatformException(sign_in_failed, com.google.GIDSignIn, keychain error, null

Not: I'm getting an error not only in gmail logins, but also in email registration and email login.

thank you.

**Comment by yunusdtarla** [comment]
I solved the problem here thank you 

https://developer.apple.com/forums/thread/674415
