### ISSUE TITLE
🐛 [flutter_crashlytic] Android - Crashlytic stacktrace on Firebase console is in wrong format

### ISSUE THREAD

**Issue by suesitran** [firebase/flutterfire#9782]
## Bug report

**Describe the bug**
Crashlytic stacktrace in Firebase console is in wrong format, so I'm unable to de-symbolise it

### Steps to reproduce

1. Update firebase_core to 2.1.0
2. Update firebase_crashlytics to 3.0.2
4. Stacktrace in crashlytic shows only AppID and unable to symbolize it

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError :  [firebase_messaging/unknown] java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: FIS_AUTH_ERROR. Error thrown null.
#00 pc 0x0 com.example.crashlytic_test
#01 pc 0x0 com.example.crashlytic_test
#02 pc 0x0 com.example.crashlytic_test
#03 pc 0x0 com.example.crashlytic_test
#04 pc 0x0 com.example.crashlytic_test
#05 pc 0x0 com.example.crashlytic_test
#06 pc 0x0 com.example.crashlytic_test
#07 pc 0x0 com.example.crashlytic_test
#08 pc 0x0 com.example.crashlytic_test
#09 pc 0x0 com.example.crashlytic_test
#10 pc 0x0 com.example.crashlytic_test
#11 pc 0x0 com.example.crashlytic_test
#12 pc 0x0 com.example.crashlytic_test
#13 pc 0x0 com.example.crashlytic_test
#14 pc 0x0 com.example.crashlytic_test
#15 pc 0x0 com.example.crashlytic_test
#16 pc 0x0 com.example.crashlytic_test
#17 pc 0x0 com.example.crashlytic_test
```
Command I used
```
 flutter symbolize -i <stack trace file> -d <symbols file>  
```

### Expected behavior

to be able to symbolize the stacktrace, stacktrace should be ike this 

```
isolate_instructions: 744ebbb1f0, vm_instructions: 744ebb6000
    #00 abs 000000744f4c0f47 virt 0000000000c82f47 _kDartIsolateSnapshotInstructions+0x905d57
    #01 abs 000000744f588e8f virt 0000000000d4ae8f _kDartIsolateSnapshotInstructions+0x9cdc9f
    #02 abs 000000744f5015f3 virt 0000000000cc35f3 _kDartIsolateSnapshotInstructions+0x946403
```

### Sample project

```
void main() async {
   await Firebase.initializeApp(options: options);

  FlutterError.onError = (details) {
      FirebaseCrashlytics.instance.recordFlutterError(details);
    }
}
```

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-x64, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @suesitran, using the setup from the example project and your sample above, I cannot seem to reproduce the issue. 

Can you share a complete sample along with steps that we can use to reproduce this issue? 

Thank you

**Comment by Ali1Ammar** [comment]
I also has the same  problem 
before I was able to symbolize the error but now I can not 
I also see that there is a different between the error between text tab and formatted tab 
<img width="1320" alt="image" src="https://user-images.githubusercontent.com/18378766/197552153-75f8959e-878c-4c5e-92bd-f1a1a0ebf4ba.png">
<img width="856" alt="image" src="https://user-images.githubusercontent.com/18378766/197552262-90ceaac5-a928-4d62-8520-082653971002.png">

**Comment by Ali1Ammar** [comment]
reprodcution step:
1- create new flutter project
2- run 
flutter pub add firebase_core
flutter pub add firebase_crashlytics
flutterfire configure
3- add the following code into main.dart
```dart
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'package:flutter/material.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp();

  FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterFatalError;

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        floatingActionButton: FloatingActionButton(onPressed: () {
          throw Exception("test 2firebase");
        }),
      ),
    );
  }
}
```
4- build the app with the following command
flutter build apk --obfuscate --split-debug-info=./debug-info/apk/current
5- run
flutter install
6- open  the app and press the button

<img width="1326" alt="image" src="https://user-images.githubusercontent.com/18378766/197591156-d5077eed-57b7-4c2b-96d6-26c5a57731f4.png">

**Comment by Ali1Ammar** [comment]
i see in the documtions that we need to upload symbol manually so i run the followings command
```
mac@alimac test_crash %  firebase crashlytics:symbols:upload --app=1:328385607037:android:8cc44c0493ef8613410814  ./debug-info/apk/current/app.android-arm.symbols
i  Generating symbols for ./debug-info/apk/current/app.android-arm.symbols
i  Generated symbols for ./debug-info/apk/current/app.android-arm.symbols
i  Output Path: /var/folders/yv/3w2_jdbd573867wwh99hn3hc0000gn/T/crashlytics-7240c31d-0951-4e8f-b53e-026ee493df0e/nativeSymbols/1-328385607037-android-8cc44c0493ef8613410814/breakpad
i  Uploading all generated symbols...
i  Successfully uploaded all symbols
mac@alimac test_crash %  firebase crashlytics:symbols:upload --app=1:328385607037:android:8cc44c0493ef8613410814  ./debug-info/apk/current/app.android-arm64.symbols
i  Generating symbols for ./debug-info/apk/current/app.android-arm64.symbols
i  Generated symbols for ./debug-info/apk/current/app.android-arm64.symbols
i  Output Path: /var/folders/yv/3w2_jdbd573867wwh99hn3hc0000gn/T/crashlytics-6e6696d0-b25d-450c-8a88-fb9f0fbd3ca5/nativeSymbols/1-328385607037-android-8cc44c0493ef8613410814/breakpad
i  Uploading all generated symbols...
i  Successfully uploaded all symbols
mac@alimac test_crash %  firebase crashlytics:symbols:upload --app=1:328385607037:android:8cc44c0493ef8613410814  ./debug-info/apk/current/app.android-x64.symbols  
i  Generating symbols for ./debug-info/apk/current/app.android-x64.symbols
i  Generated symbols for ./debug-info/apk/current/app.android-x64.symbols
i  Output Path: /var/folders/yv/3w2_jdbd573867wwh99hn3hc0000gn/T/crashlytics-8d2f4730-c315-478d-9014-ffa0c08545a7/nativeSymbols/1-328385607037-android-8cc44c0493ef8613410814/breakpad
i  Uploading all generated symbols...
i  Successfully uploaded all symbols
```

and the new error are now automatically de-obfuscate but any old error before the upload still can not be readed or manually de-obfuscate

**Comment by suesitran** [comment]
hi @danagbemava-nc,
Please check response from @Ali1Ammar above, however I tried his solution, and it does not work for my case.

**Comment by danagbemava-nc** [comment]
Hi @Ali1Ammar, Thanks for the detailed steps. 

I can reproduce the issue now

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError :  Exception: test 2firebase. Error thrown Instance of 'Rr'.
#00 pc 0x14e96b com.example.crasht 
#01 pc 0x108c83 com.example.crasht 
#02 pc 0x10a137 com.example.crasht 
#03 pc 0x22dedb com.example.crasht 
#04 pc 0x1e77f7 com.example.crasht 
#05 pc 0x1d2b07 com.example.crasht 
#06 pc 0x1de6af com.example.crasht 
#07 pc 0x1d3d73 com.example.crasht 
#08 pc 0x1d3ab7 com.example.crasht 
#09 pc 0x22562b com.example.crasht 
#10 pc 0xf3583 com.example.crasht 
#11 pc 0x1f87e7 com.example.crasht 
#12 pc 0xf34eb com.example.crasht 
#13 pc 0xf345f com.example.crasht 
#14 pc 0x111287 com.example.crasht 
#15 pc 0x225587 com.example.crasht 
#16 pc 0xf3357 com.example.crasht 
#17 pc 0xf329f com.example.crasht 
#18 pc 0xf2db7 com.example.crasht 
#19 pc 0x20b277 com.example.crasht 
#20 pc 0x20b17b com.example.crasht 
#21 pc 0x95e4b com.example.crasht 
#22 pc 0x95d7f com.example.crasht 
#23 pc 0x95cfb com.example.crasht 
```

**Comment by biswa1751** [comment]
I was facing the same issue , and then I uploaded the debug symbols but it did not work.
But after 1 or 2 days now errors are de-obfuscated.

It seems after uploading symbols it needs some time , then it will be de-obfuscated.

But there are still two issues
The exception names are still obfuscated , like Error thrown Instance of 'jC'.
Sometimes the Exceptions are a combination of de-obfuscated and obfuscated.

**Comment by suesitran** [comment]
still having same issue for me.

Any update please?

**Comment by russellwheatley** [comment]
I'm closing this issue in favour of https://github.com/firebase/flutterfire/issues/8934. It is the same issue - trying to deobfuscate obfuscated stack trace. 

If users could thumb up that issue for more visibility that would be great. 

> i see in the documtions that we need to upload symbol manually so i run the followings command
> 
> ```
> mac@alimac test_crash %  firebase crashlytics:symbols:upload --app=1:328385607037:android:8cc44c0493ef8613410814  ./debug-info/apk/current/app.android-arm.symbols
> i  Generating symbols for ./debug-info/apk/current/app.android-arm.symbols
> i  Generated symbols for ./debug-info/apk/current/app.android-arm.symbols
> i  Output Path: /var/folders/yv/3w2_jdbd573867wwh99hn3hc0000gn/T/crashlytics-7240c31d-0951-4e8f-b53e-026ee493df0e/nativeSymbols/1-328385607037-android-8cc44c0493ef8613410814/breakpad
> i  Uploading all generated symbols...
> i  Successfully uploaded all symbols
> mac@alimac test_crash %  firebase crashlytics:symbols:upload --app=1:328385607037:android:8cc44c0493ef8613410814  ./debug-info/apk/current/app.android-arm64.symbols
> i  Generating symbols for ./debug-info/apk/current/app.android-arm64.symbols
> i  Generated symbols for ./debug-info/apk/current/app.android-arm64.symbols
> i  Output Path: /var/folders/yv/3w2_jdbd573867wwh99hn3hc0000gn/T/crashlytics-6e6696d0-b25d-450c-8a88-fb9f0fbd3ca5/nativeSymbols/1-328385607037-android-8cc44c0493ef8613410814/breakpad
> i  Uploading all generated symbols...
> i  Successfully uploaded all symbols
> mac@alimac test_crash %  firebase crashlytics:symbols:upload --app=1:328385607037:android:8cc44c0493ef8613410814  ./debug-info/apk/current/app.android-x64.symbols  
> i  Generating symbols for ./debug-info/apk/current/app.android-x64.symbols
> i  Generated symbols for ./debug-info/apk/current/app.android-x64.symbols
> i  Output Path: /var/folders/yv/3w2_jdbd573867wwh99hn3hc0000gn/T/crashlytics-8d2f4730-c315-478d-9014-ffa0c08545a7/nativeSymbols/1-328385607037-android-8cc44c0493ef8613410814/breakpad
> i  Uploading all generated symbols...
> i  Successfully uploaded all symbols
> ```
> 
> and the new error are now automatically de-obfuscate but any old error before the upload still can not be readed or manually de-obfuscate

@Ali1Ammar - I also successfully uploaded debug symbols, but my stack trace is still obfuscated on the Firebase console. Out of curiosity, how long did you wait? If you want, we can continue the discussion over at https://github.com/firebase/flutterfire/issues/8934
