### ISSUE TITLE
🐛 [firebase_analytics] missing google_app_id even with flutterfire configure on Android

### ISSUE THREAD

**Issue by absar** [firebase/flutterfire#9785]
## Bug report

**Describe the bug**
After successfully configuring firebase using `flutterfire configure`, crashlytics works fine but `Analytics` is not working on Android and showing this log `Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI` there are many similar issues reported in this repo but all are closed mentioning to configure it with `flutterfire configure` however it's not working, even though `firebase_options.dart` file is generated with FirebaseOptions for Android.

- We need some concrete info whether `Analytics` is supported on `Android` or not, as per the readme at this repo's root it is supported
- If it is not supported using `flutterfire configure` what are the workarounds

### Steps to reproduce

1. Create any app and registered it as an android app in firebase
2. Configure firebase using `flutterfire configure`
3. It will generate `firebase_options.dart` file with `FirebaseOptions` for Android
4. Run the app, it will show log `Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI`

<details><summary>Full log - Click To Expand</summary>

```
I/FirebaseApp(12345): Device unlocked: initializing all Firebase APIs for app [DEFAULT]
I/FirebaseCrashlytics(12345): Initializing Firebase Crashlytics 18.3.1 for com.abc.xyz
D/FirebaseCrashlytics(12345): Crashlytics automatic data collection ENABLED by API.
D/FirebaseCrashlytics(12345): AnalyticsConnector now available.
D/FirebaseCrashlytics(12345): Registered Firebase Analytics listener.
D/FirebaseCrashlytics(12345): Mapping file ID is: null
D/FirebaseCrashlytics(12345): Checking for cached settings...
D/FirebaseCrashlytics(12345): Loaded cached settings: {"settings_version":3,"cache_duration":86400,"features":{"collect_logged_exceptions":true,"collect_reports":true,"collect_analytics":false,"prompt_enabled":false,"push_enabled":false,"firebase_crashlytics_enabled":false,"collect_anrs":true,"collect_metric_kit":false},"app":{"status":"activated","update_required":false,"report_upload_variant":2,"native_report_upload_variant":2},"fabric":{"org_id":"THIS_IS_REPLACED","bundle_id":"com.abc.xyz"},"on_demand_upload_rate_per_minute":10,"on_demand_backoff_base":1.2,"on_demand_backoff_step_duration_seconds":60,"expires_at":1666710695025}
D/FirebaseCrashlytics(12345): Crashlytics automatic data collection ENABLED by API.
D/FirebaseCrashlytics(12345): Opening a new session with ID XXXXXXTHIS_IS_REPLACED
D/FirebaseCrashlytics(12345): Successfully configured exception handler.
D/FirebaseCrashlytics(12345): Registered Firebase Analytics event receiver for breadcrumbs
D/FirebaseCrashlytics(12345): Loaded userId THIS_IS_REPLACED for session THIS_IS_REPLACED
E/FA      (12345): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
E/FA      (12345): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
```

</details>

### Expected behavior

Android app should be able to log Analytics

### Sample project

Any Android project configured with `flutterfire configure`

---

### Flutter doctor

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel stable, 3.3.5, on Microsoft Windows [Version 10.0.19044.2130], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
[√] Chrome - develop for the web
[√] Android Studio (version 2021.3)
[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
[√] Connected device (3 available)
[√] HTTP Host Availability

```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand, adding only firebase related deps</summary>

```
- firebase_analytics 10.0.2 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 2.1.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 3.0.2 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]

```

</details>

---

**Comment by danagbemava-nc** [comment]
Hi @absar, I just want to confirm something. 

In Step 1, do you go through the setup process on firebase after creating the firebase project or do you leave everything to flutterfire_configure?

**Comment by absar** [comment]
Hi @danagbemava-nc, first creating the firebase project, in Project settings=>integrations integrating the project to analytics, setting SHA certificate fingerprints in firebase and then running `flutterfire configure` which is creating google-services.json and firebase_options.dart. Let me know if I misunderstood what you mean by setup process

**Comment by danagbemava-nc** [comment]
Hi @absar, I can't seem to reproduce your issue. 

> Let me know if I misunderstood what you mean by setup process

That's what I wanted to know

Below are the steps I used

- Create firebase project(Analytics was enabled as part of this process)  && create flutter project
- Add dependencies (firebase_core, firebase_analytics & firebase_crashlytics)
- Start registering android app so I can add the SHA-1 key
- Close firebase setup and checked project settings to see that android has been registered with SHA-1 key present
- Run `flutterfire_configure` in flutter project
- Use code sample from the `firebase_analytics` package
- Run the app

These are my logs and see a screenshot of my analytics dashboard

```
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
lib/main.dart:1
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:59381/emYcbynGl80=/ws
E/SurfaceSyncer(10710): Failed to find sync for id=0
W/Parcel  (10710): Expecting binder but got null!
D/EGL_emulation(10710): app_time_stats: avg=2265.18ms min=30.48ms max=6093.92ms count=3
D/EGL_emulation(10710): app_time_stats: avg=591.89ms min=14.05ms max=2885.04ms count=5
D/EGL_emulation(10710): app_time_stats: avg=202.89ms min=4.34ms max=2174.77ms count=12
D/EGL_emulation(10710): app_time_stats: avg=247.36ms min=5.23ms max=2480.45ms count=11
D/EGL_emulation(10710): app_time_stats: avg=127.93ms min=1.81ms max=1648.53ms count=14
D/EGL_emulation(10710): app_time_stats: avg=93.48ms min=1.60ms max=1295.79ms count=15
D/EGL_emulation(10710): app_time_stats: avg=99.34ms min=1.43ms max=1360.83ms count=15
I/om.nexus.lytics(10710): Background concurrent copying GC freed 33254(2459KB) AllocSpace objects, 51(1532KB) LOS objects, 49% free, 3089KB/6178KB, paused 90us,58us total 230.657ms
```

<img width="500" alt="Screenshot 2022-10-26 at 07 22 59" src="https://user-images.githubusercontent.com/88313112/197960993-2293f7dd-5391-49b9-bf20-e2d2bafea9ba.png">


Was there something I missed in trying to reproduce the bug?

**Comment by absar** [comment]
Hi @danagbemava-nc thank you for the details. Could you share these details:

- The version of firebase_core, firebase_analytics & firebase_crashlytics you are using
- Are you modifying any build.gradle files manually?
- Are you changing anything in Firebase Project settings apart from adding the SHA fingerprints
- Are you doing any extra Analytics setups apart from just linking it to firebase
- Would it be possible to share the generated file contents `google-services.json` and `firebase_options.dart`, of course by replacing with fake IDs

Do you have any other suggestions to look for and compare, we are not sure why crashlytics is working but analytics is always throwing `Missing google_app_id` for the same App

**Comment by russellwheatley** [comment]
It's saying your app id is missing. check your `google-services.json` file. It is here:

```
"client_info": {
        "mobilesdk_app_id": "1:406099696497:android:a241c4b471513a203574d0", //app id
        "android_client_info": {
          "package_name": "io.flutter.plugins.firebase.appcheck.example"
        }
      },
```

Also make sure you're applying this at the bottom of your `app/build.gradle`:

```
apply plugin: 'com.google.gms.google-services'
```

You will also need this:
```
classpath 'com.google.gms:google-services:4.3.10'
```

as a dependency in your `android/build.gradle`.

**Comment by absar** [comment]
@russellwheatley thank you very much, app id was already there however `build.gradle` entries you mentioned were missing, adding these two `apply plugin: 'com.google.gms.google-services'` `classpath 'com.google.gms:google-services:4.3.10'` and re-running `flutterfire configure` fixed the issue.
I wonder would it be nice if `flutterfire configure` adds the two entries as well then we can say it's dart only config(if there is no reason not to do so), since it is already auto adding these:
```
classpath 'com.google.firebase:firebase-crashlytics-gradle:2.8.1'
apply plugin: 'com.google.firebase.crashlytics'
```

**Comment by russellwheatley** [comment]
That's exactly what `flutterfire configure` does 🤔. You probably need to update your FlutterFire CLI. Run this:

```
dart pub global activate flutterfire_cli
```

**Comment by absar** [comment]
Probably you misunderstood my last statement, I am saying it should auto add these two:
```
apply plugin: 'com.google.gms.google-services' 
classpath 'com.google.gms:google-services:4.3.10'
```

Like it is adding these:
```
classpath 'com.google.firebase:firebase-crashlytics-gradle:2.8.1'
apply plugin: 'com.google.firebase.crashlytics'
```

We are already using the latest `flutterfire_cli 0.2.6` which doesnt auto add `apply plugin: 'com.google.gms.google-services'` `classpath 'com.google.gms:google-services:4.3.10'`

**Comment by Purus** [comment]
I have the same issue as I have followed the instructions as-is. Using latest firebase cli too.
