### ISSUE TITLE
🐛 [firebase_analytics] AppMeasurementJobService is called multiple times

### ISSUE THREAD

**Issue by luckbuff** [firebase/flutterfire#9801]
“com.google.android.gms.measurement.AppMeasurementJobService”，This class will be called many times. Is there any way to stop it

**Comment by danagbemava-nc** [comment]
Hi @luckbuff, that message comes from the underlying native SDK as such there's nothing for flutterfire to do in that regard. 
You can try to filter it out from your logs so you do not see it, but since this is a call from the underlying native SDK, I'll be closing this issue. 

Thank you
