### ISSUE TITLE
🐛 [firebase_analytics] Unble to build for ios after upgrading to latest version.

### ISSUE THREAD

**Issue by oke007** [firebase/flutterfire#9807]
Getting error while building for ios using `pod install` or `arch -x86_64 pod install ` or `arch -x86_64 pod repo update `. Any help? i tried all the solution.

### Error:

```
firebase_analytics: Using Firebase SDK version '10.0.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '10.0.0' defined in 'firebase_core'
firebase_dynamic_links: Using Firebase SDK version '10.0.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '10.0.0' defined in 'firebase_core'
[!] CocoaPods could not find compatible versions for pod "firebase_analytics":
  In Podfile:
    firebase_analytics (from `.symlinks/plugins/firebase_analytics/ios`)

Specs satisfying the `firebase_analytics (from `.symlinks/plugins/firebase_analytics/ios`)` dependency were found, but they required a higher minimum deployment target.

```
---

### Flutter doctor

[✓] Flutter (Channel stable, 3.3.6, on macOS 12.6.1 21G217 darwin-arm, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.72.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

---

### Flutter dependencies

Dart SDK 2.18.2
Flutter SDK 3.3.6
novelo 1.3.1+7

dependencies:
  firebase_core: ^2.1.1
  firebase_messaging: ^14.0.3
  firebase_analytics: ^10.0.3
  firebase_dynamic_links: ^5.0.3

---

**Comment by danagbemava-nc** [comment]
Hi @oke007, can you share your `Podfile`? 

> `Specs satisfying the `firebase_analytics (from `.symlinks/plugins/firebase_analytics/ios`)` dependency were found, but they required a higher minimum deployment target.`

This error usually means that your deployment target is lower than the version that is compatible with what was resolved by cocoapods. Can you try setting your iOS deployment target in the Podfile to `11` to see if you're able to build it?

It will be the `platform :ios, '**'` entry in the `Podfile` where ** stands for the version that is currently in your Podfile.

**Comment by oke007** [comment]
Updated iOS deployment target in the Podfile to `platform :ios, '11.0'`. Build flutter again for ios.

same issue for me with latest firebase. 

dependencies
  firebase_core: ^2.1.1
  firebase_messaging: ^14.0.3
  firebase_analytics: ^10.0.3
  firebase_dynamic_links: ^5.0.3
  google_mobile_ads: ^2.1.0

Error:
[!] CocoaPods could not find compatible versions for pod "GoogleAppMeasurement":
      In Podfile:
        firebase_analytics (from `.symlinks/plugins/firebase_analytics/ios`) was resolved to 10.0.3, which depends on
          Firebase/Analytics (= 10.0.0) was resolved to 10.0.0, which depends on
            Firebase/Core (= 10.0.0) was resolved to 10.0.0, which depends on
              FirebaseAnalytics (~> 10.0.0) was resolved to 10.0.0, which depends on
                FirebaseAnalytics/AdIdSupport (= 10.0.0) was resolved to 10.0.0, which depends on
                  GoogleAppMeasurement (= 10.0.0)

        google_mobile_ads (from `.symlinks/plugins/google_mobile_ads/ios`) was resolved to 0.0.1, which depends on
          Google-Mobile-Ads-SDK (= 9.10.0) was resolved to 9.10.0, which depends on
            GoogleAppMeasurement (< 10.0, >= 7.0)

**Comment by oke007** [comment]
I found this error caused by `google_mobile_ads: ^2.1.0` with latest firebase version which depends on GoogleMeasurement 10.0. The current podspec depends on GoogleMobileAdsSDK pod which is < 10.0.

**Comment by danagbemava-nc** [comment]
Hi @oke007, if you remove `google_mobile_ads`, are you able to build your app successfully?

**Comment by oke007** [comment]
> Hi @oke007, if you remove `google_mobile_ads`, are you able to build your app successfully?

Yes

**Comment by oke007** [comment]
Update: there is a open discussion on `google_mobile_ads` git issue tracking page with some temporary workaround: https://github.com/googleads/googleads-mobile-flutter/issues/673

**Comment by danagbemava-nc** [comment]
Kindly follow up there as this will need to be fixed on their end. 

Closing from here. 

Thank you
