### ISSUE TITLE
🐛 [firebase_messaging] Should not spawn new isolate groups

### ISSUE THREAD

**Issue by dnfield** [firebase/flutterfire#9816]
https://github.com/firebase/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingBackgroundExecutor.java#L141 causes new isolate groups to be spawned. Instead, this should use FlutterEngine.spawn, which is more performant and allows for a shared heap.

@gaaclarke @aam FYI

**Comment by Lyokone** [comment]
Hello @dnfield ,
Thanks for your suggestion, it seems that `FlutterEngine.spawn` is not public and cannot be used in this context. Have I misunderstood your suggestion?
![Screenshot 2022-11-02 at 14 08 51](https://user-images.githubusercontent.com/3680002/199498066-16a8d71e-5317-4c6a-8a48-c0b6922bc48f.png)

**Comment by dnfield** [comment]
Ahh sorry, you'll want to use `FlutterEngineGroup#createAndRunEngine`

**Comment by TarekkMA** [comment]
Hi @dnfield ,

Thank you for your report! Since this issue was opened, the implementation details have changed significantly. If you feel that this issue is still relevant, please feel free to open a new issue with updated context. We appreciate your understanding and support.
