### ISSUE TITLE
[Firebase Auth] Signin with Apple does not provide email and fullName. How to retreive them using firebase?  

### ISSUE THREAD

**Issue by ExpertKiD** [firebase/flutterfire#9836]
Hi, I am trying to signinwith Apple on native platforms.

```dart
import 'package:firebase_auth/firebase_auth.dart';

Future<UserCredential> signInWithApple() async {
  final appleProvider = AppleAuthProvider();
  if (kIsWeb) {
    await FirebaseAuth.instance.signInWithPopup(appleProvider);
  } else {
    await FirebaseAuth.instance.signInWithProvider(appleProvider);
  }
}
```

Source: [Firebase Federation Auth & Social Login](https://firebase.google.com/docs/auth/flutter/federated-auth)

I have added scopes to appleProvider as well as below:

```dart
import 'package:firebase_auth/firebase_auth.dart';

Future<UserCredential> signInWithApple() async {
  final appleProvider = AppleAuthProvider();

    appleProvider.addScope('email');
    appleProvider.addScope('name');

  if (kIsWeb) {
    await FirebaseAuth.instance.signInWithPopup(appleProvider);
  } else {
    await FirebaseAuth.instance.signInWithProvider(appleProvider);
  }
}

```

Even still, I am only able to fetcha the email but no display name comes at all. How can I request for email and fullname for user? It is required for us to register a new user to our backend.

The documentation lacks the details on how to request those details.

**Comment by darshankawar** [comment]
I think this is similar to https://github.com/firebase/flutterfire/issues/9662 so please follow up in it for further updates.
Closing as duplicate. If you disagree, write in comments and I'll reopen it.
