### ISSUE TITLE
Update all pods Updating local specs repositories Analyzing dependencies cloud_firestore: Using Firebase SDK version '10.0.0' defined in 'firebase_core' firebase_analytics: Using Firebase SDK version '10.0.0' defined in 'firebase_core' firebase_auth: Using Firebase SDK version '10.0.0' defined in 'firebase_core' firebase_core: Using Firebase SDK version '10.0.0' defined in 'firebase_core' firebase_messaging: Using Firebase SDK version '10.0.0' defined in 'firebase_core' firebase_storage: Using Firebase SDK version '10.0.0' defined in 'firebase_core'

### ISSUE THREAD

**Issue by Kumarbarath** [firebase/flutterfire#9842]
Update all pods
Updating local specs repositories
Analyzing dependencies
cloud_firestore: Using Firebase SDK version '10.0.0' defined in 'firebase_core'
firebase_analytics: Using Firebase SDK version '10.0.0' defined in 'firebase_core'
firebase_auth: Using Firebase SDK version '10.0.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '10.0.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '10.0.0' defined in 'firebase_core'
firebase_storage: Using Firebase SDK version '10.0.0' defined in 'firebase_core'

**Comment by darshankawar** [comment]
@Kumarbarath 
When you open an issue, please try to use new issue template and fill out requested details so that we'll have enough details to work with.
Currently it is not clear what exactly is the issue are you reporting.
Closing.
