### ISSUE TITLE
🐛 [firebase_crashlytics] Crashlytics not showing iOS crash reports

### ISSUE THREAD

**Issue by dr953** [firebase/flutterfire#9846]
Crash reporting works flawlessly on Android, but on iOS there are no reports.

I've been through the documentation several times, done all the setup steps and still nothing. 

Is there any way to investigate the problem - some Firebase side logs, or whatever?

Any steps not in the official docs?

Using firebase_crashlytics 2.9.0., XCode 14, flutter 3.3.6

**Comment by darshankawar** [comment]
@dr953 
Please check [this](https://github.com/firebase/flutterfire/issues/8934) issue and see if it helps.

**Comment by dr953** [comment]
Unfortunately not - it is not about crash reports being obfuscated, but about not appearing at all.

All I get on the Crashlytics page is: " App detected and we're waiting for a crash! "

**Comment by darshankawar** [comment]
Thanks for the update. Can you try with latest version of the plugin ?
Also, have you looked at https://firebase.google.com/docs/crashlytics/test-implementation?platform=flutter#expandable-1 and see if it helps ?

If that doesn't help, please provide complete minimal reproducible code sample that we can use to verify the behavior.

**Comment by dr953** [comment]
I've done that already, it did not help.

I created a sample project from scratch and it worked fine with the latest core/crashlytics version. However, because of some dependencies (ML Kit), we have to use previous versions, based on SDK 9.6.0. 

Next, I went to versions core:1.24.0 and crashlytics:2.9.0. This time I cannot compile the sample project at all. When I import firebase packages and try flutter run (or from XCode, no difference), the build fails with "PhaseScriptExecution failed with a non-zero exit code"

**Comment by dr953** [comment]
flutter create --platform ios .
flutter run (ok)
flutter pub add firebase_core:1.24.0
flutter pub add firebase_crashlytics:2.9.0
flutter run (ok)
in main.dart, add imports for the firebase packages
flutter run (build fails with the above messages)

**Comment by dr953** [comment]
Ok, solved that one - it seems some breaking changes were introduced in firebase_core_platform_interface 4.5.2 so I had to add a dependency for 4.5.1.

Starting from scratch, everything works fine.

I will try to strip our production project and see if I can somehow pinpoint some setting or whatever that prevents crash reports from being sent.

**Comment by dr953** [comment]
Finally gotten to the bottom of it.

We use the path_provider package to get application directories. For temp data, we use _getTemporaryDirectory()_ for which the docs say: 
> Files in this directory may be cleared at any time. This does *not* return a new temporary directory. Instead, the caller is responsible for creating (and cleaning up) files or directories within this directory.

Unfortunately, we decided to clear it on each start. That is fine on Android as Crashlytics stores its reports in the _getApplicationSupportDirectory()_, however on iOS, they are stored inside the _getTemporaryDirectory()_. In effect, we were deleting our crash reports on each start...

The problem we had is definitely not a bug, but I think some clarifications are needed in the official docs. At minimum in "getting started" tutorials, but also in other docs, the report storage location should be mentioned and brought to attention.

**Comment by darshankawar** [comment]
Thanks for the update and digging in to identify the root-cause. I suggest you to open a new documentation issue so that we can track it properly instead of considering this issue for documentation.

I am going ahead and closing this as resolved based on above comment.
