### ISSUE TITLE
[cloud_firetore] ServerTimestampBehavior implementation details

### ISSUE THREAD

**Issue by Ehesp** [firebase/flutterfire#9859]
Related: https://github.com/firebase/flutterfire/issues/8431

## Issue

At present, it is not possible to change the server timestamp behaviour of a Document Snapshot. On other platforms such as web, the timestamp behaviour can be modified via the `data()` method on a snapshot, e.g.:

```
const data = snapshot.data({ serverTimestamps: 'estimate' });
```

On Dart however, this is not possible as the underlying native snapshots are first serialised and then reconstructed into a Dart class. This means the underlying native `data()` method has already been called with the default value (in order to serialise the snapshot) and the native snapshot is lost.

#### Option 1: Pass the behaviour to "Get Options"

This would allow developers to define the behaviour before the query executes, and use the behavioural value during serialisation:

```dart
// Example api for demonstration
var snapshot = await FirebaseFirestore.instance.doc('.../...').get(serverTimestamps: 'estimate', source: 'cache');
```

#### Option 2: Global options

Provide a global API for a default behaviour across every query

```dart
// Example api for demonstration
FirebaseFirestore.instance.settings = Settings(serverTimestamps: 'estimate');
```

This could be also used alongside option 1.

#### Option 3: Mimic native (breaking change)

Not recommended as this would be a breaking change, however in order to mimic the native APIs the `data()` method on a snapshot could be made asynchronous allowing for the native snapshots to return the data when required:

```dart
// Currently synchronous 
var data = await snapshot.data(serverTimestamps: 'estimate');
```

**Comment by puf** [comment]
Can't we add an optional parameter for the settings in Option 3?

If that's not possible, we should go with Option 1, as it's closest to what the other SDKs do - and is arguably a better API as the behavior of a snapshot should be fixed upon its creation.

While option 2 is arguably a better developer experience for the majority of cases, it's too far from the current behavior of the other SDKs. We could/should create an API proposal for it.

**Comment by andirihs** [comment]
How could I get the estimate timestamp when working with streams coming from firebase? 
`` ``

**Comment by Lyokone** [comment]
Hello @andirihs, it's not currently supported by the native SDKs, so FlutterFire doesn't support it either.
