### ISSUE TITLE
🐛 [firebase_auth] invalid-app-credential/Token mismatch in Flutter firebase_auth

### ISSUE THREAD

**Issue by peternagy1332** [firebase/flutterfire#9871]
## Bug report

**Describe the bug**
I've started to setup Firebase Phone authentication in Flutter based on the [official documentation](https://firebase.google.com/docs/flutter/setup?platform=ios). Unfortunately, no matter how I try, I get a `FirebaseAuthException` in the `verificationFailed` callback of the `verifyPhoneNumber` method with these values:
```
code: "invalid-app-credential"
credential: null
email: null
message: "Token mismatch"
phoneNumber: null
plugin: "firebase_auth"
stackTrace: null
tenantId: null
```
I've originally asked the question on [stackoverflow](https://stackoverflow.com/questions/74340881/invalid-app-credential-token-mismatch-in-flutter-firebase-auth), but since another user mentioned that this problem occurs when using email sign in as well, it is probably a bug.

### Steps to reproduce

1. I used `flutterfire configure` to add the app to an existing Firebase project and create the IOS application there.
2. I've added `firebase_core@2.1.1` and `firebase_auth@4.1.1`
3. I've enabled the Phone sign-in method on Firebase and added +44 7123 123 456 as a test number, and the code is 000000
4. I've added the `Push notification` and `Background modes` capability with `Background fetch` and `Remote notifications` options.
5. I've added the the `REVERSED_CLIENT_ID` from `GoogleService-Info.plist` as an `URL Scheme`.
6. On the Apple Developer page, I've generated a new key with `Apple Push Notifications service (APNs) service` and uploaded it as an `APNs Authentication Key` to Firebase.

The [setup section](https://firebase.google.com/docs/auth/flutter/phone-auth#setup) of the official documentation points me to [this documentation](https://firebase.google.com/docs/cloud-messaging/ios/certs). This indicates that additional modifications in the Swift code might be needed, but it's really unclear. I'm a Flutter developer and not a native IOS developer, I don't think I actually need to do all that.

### Expected behavior

The codeSent callback should be called instead of verificationFailed.

### Sample project

---

## Additional context

I've created a simple repository to reproduce the issue: https://github.com/peternagy1332/basic_phone_auth

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.7, on macOS 13.0 22A380 darwin-arm, locale en-HU)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.73.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

</details>

I'm focusing on iOS only for now.

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.18.4
Flutter SDK 3.3.7
basic_phone_auth 1.0.0+1

dependencies:
- cupertino_icons 1.0.5
- firebase_auth 4.1.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.1.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]

dev dependencies:
- flutter_lints 2.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- _flutterfire_internals 1.0.7 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.9.0 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.1
- clock 1.1.1
- cloud_firestore_platform_interface 5.8.4 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.0.4 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.16.0
- fake_async 1.3.1 [clock collection]
- firebase_auth_platform_interface 6.11.1 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.1.1 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.5.2 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.0.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- js 0.6.4
- lints 2.0.1
- matcher 0.12.12 [stack_trace]
- material_color_utilities 0.1.5
- meta 1.8.0
- path 1.8.2
- plugin_platform_interface 2.1.3 [meta]
- sky_engine 0.0.99
- source_span 1.9.0 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.1 [source_span]
- term_glyph 1.2.1
- test_api 0.4.12 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.1 [collection]
- vector_math 2.1.2
```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the detailed report @peternagy1332. There's a similar issue open describing your case, https://github.com/firebase/flutterfire/issues/9795 in which you can follow-up for further updates. You may also share your findings in that issue for better tracking.
From underlying comments in that issue, it seems to be related to macOS version upgrade and iOS simulator version https://github.com/firebase/flutterfire/issues/9795#issuecomment-1296240084

Closing this as duplicate.
