### ISSUE TITLE
'User' class and its previous name 'FirebaseUser'

### ISSUE THREAD

**Issue by Dogorshom** [firebase/flutterfire#9875]
I hope you rename the '**User**' class to its previous name '**FirebaseUser**' or **another**. This is because most developers name the user's class in the model's folder by '**User**', which is a bad thing. 
You **can't** call both classes in the same function which is a bad thing because they have the same name.

**Comment by darshankawar** [comment]
@Dogorshom 
There are couple of old discussion threads on same topic in which you can share your findings:

https://github.com/firebase/flutterfire/discussions/3555
https://github.com/firebase/flutterfire/discussions/3238

As a workaround, you can extend a user-defined CustomFirebaseUser Class from the 'User' class

Closing.
