### ISSUE TITLE
🐛 [firebase_messaging] An error occurred while calling method Messaging#getToken

### ISSUE THREAD

**Issue by Tom3652** [firebase/flutterfire#9878]
## Bug report

**Describe the bug**

Logs : 

```
FLTFirebaseMessaging: An error occurred while calling method Messaging#getToken, errorOrNil => {
    NSLocalizedFailureReason = "Invalid fetch response, expected 'token' or 'Error' key";
}
flutter: Error from outside Flutter : [firebase_messaging/unknown] An unknown error has occurred.
flutter:  #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
flutter: #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
flutter: <asynchronous suspension>
flutter: #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:499:43)
flutter: <asynchronous suspension>
flutter: #3      MethodChannelFirebaseMessaging.getToken (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:224:11)
flutter: <asynchronous suspension>
```

This happens using `firebase_messaging: ^14.0.4`

### Steps to reproduce

1. Setup a new flutter project with firebase messaging
2. Call the `FirebaseMessaging.instance.getToken()` in the `main.dart` file after `await Firebase.initializeApp()`
3. See the error

### Expected behavior

The token should be fetched and no error thrown.

### Sample project

The example project

## Additional context

I have seen this issue : https://github.com/firebase/flutterfire/issues/9874 and i must specify that i am using Xcode 14.1 and flutter 3.3.7 but anyway seeing this issue on my iOS 16+ devices but i am getting this issue anyway. 
I am not subscribing to any topic so i don't know about it 

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.7, on macOS 13.0 22A380 darwin-x64, locale
    fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.73.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

**Comment by chihuy105** [comment]
+1

**Comment by darshankawar** [comment]
Thanks for the report @Tom3652 
I tried the code sample you mentioned in plugin's example like below: and ran it on iPhone 6s (15.3) and iOS simulator (15.2), but didn't get the reported error.

I am on stable 3.3.7 but Xcode version is a bit old as compared to yours, (12.3).

Can you use the code sample in the plugin example and see if using it, you still get same error or not ?

@chihuy105 Same for you to verify as well.

**Comment by Tom3652** [comment]
Hi @darshankawar, thanks for the reply. 

However i am unable to run the example code because i can't use my apple developper membership to register io.plugins.firebase.messaging as a bundle identifier as it's already taken.. 

I am not sure how to do, but what i did is taken an empty project, setup firebase and just call `FirebaseMessaging.instance.getToken()` and i see the error :/

**Comment by chihuy105** [comment]
After I check if you switch to other VPN or network it'll work

**Comment by darshankawar** [comment]
Thanks for the update. Based on the error report and it being similar / related to https://github.com/firebase/flutterfire/issues/9874, keeping this issue open and labeling for further insights from the team.

**Comment by Tom3652** [comment]
I have switched to another network as you said but it didn't change anything. 
However i have tried on my iPhone 8+ and it's working fine (under iOS 16.1) 

My iPhone XS Max, 11 pro max and 12 throw this error on the same network that the iPhone 8+

**Comment by Tom3652** [comment]
hi @russellwheatley just to let you know that this is not happening in the latest version `firebase_messaging: ^14.1.2` !

**Comment by russellwheatley** [comment]
Hey @Tom3652, thanks for letting us know!

**Comment by xTanveerAhmad** [comment]
some case emulator desn't not work. try real device.
