### ISSUE TITLE
[📚] Firebase Analytics for Flutter Web

### ISSUE THREAD

**Issue by pawelpetruch** [firebase/flutterfire#9881]
What is the latest guideline for implementing Firebase Analytics for Flutter Web? Could some up-to-date documentation be created and added?

**Comment by darshankawar** [comment]
@pawelpetruch 
Are you facing any issue while implementing analytics on web ?

**Comment by pawelpetruch** [comment]
@darshankawar yes, please see: https://github.com/firebase/flutterfire/discussions/9882

Plus the overall experience is not great when implementing Firebase Analytics with Flutter Web, not sure what needs to be done from the standard web implementation and what comes from the package.

**Comment by darshankawar** [comment]
Thanks for the feedback.

**Comment by pawelpetruch** [comment]
No problem but could you point me to the right docs? :D

**Comment by Lyokone** [comment]
Hey @pawelpetruch, the official documentation is on the official website under the Flutter section: https://firebase.google.com/docs/analytics/get-started?platform=flutter
