### ISSUE TITLE
🐛 [cloud_firestore] You cannot use 'not-in' filters with '!=' filters.

### ISSUE THREAD

**Issue by cerenyasa97** [firebase/flutterfire#9886]
## Bug report

I have two enums for a record status, one of them for app user and the other one for customer. Then I save their indexes to Firestore to save status. Then I get them with isNotEqual in where queries for these parameters are not equal 'Cancel' status. And then I got below error. How can I filter these different parameters for status with isNotEqual in where condition?

"You cannot use 'not-in' filters with '!=' filters."

### Query 

<details><summary>Click To Expand</summary>

```
await FirebaseFirestore.instance
        .collection(FirebaseConstants.appointmentsCollection)
        .where(FirebaseConstants.userId, isEqualTo: user?.id)
        .where(
          // RSVP status is an enum. The enum index saved to Firestore.
          'rsvp_status',
          isNotEqualTo: 2,
        )
        .where(
          // Appointment status is an enum. The enum index saved to Firestore.
          'appointment_status',
          isNotEqualTo: 3,
        )
        .withConverter(
          fromFirestore: (snapshot, _) => snapshot.data() != null
              ? Appointment.fromJson(snapshot.data()!)
              : null,
          toFirestore: (appointment, _) => appointment?.toJson() ?? {},
        )
        .get();
```

</details>

---

**Comment by darshankawar** [comment]
@cerenyasa97 
Can you check [this](https://cloud.google.com/firestore/docs/query-data/queries#in_not-in_and_array-contains-any) documentation link and see if it helps in your case ?

If not, can you provide [complete minimal code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can use to verify this behavior ?

**Comment by cerenyasa97** [comment]
I solve the problem with a different approach. Thanks for your helps...
