### ISSUE TITLE
[firebase_messaging]: didReceiveRemoteNotification from FLTFirebaseMessagingPlugin.m is not invoked

### ISSUE THREAD

**Issue by tomk9** [firebase/flutterfire#9902]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you aware of the differences between iOS and Android background message handling?

- [X] I understand that iOS and Android background messages behave differently, and I've designed my application with that in mind.

### Do you have an active Apple Developer account?

- [X] I have an active Apple Developer account.

### Are you using a physical iOS device to test background messages?

- [X] I am using a physical iOS device to test background messages.

### Have you enabled "Remote Notifications" & "Background Mode" (Checking options for "Background Processing" & "Remote Notifications") in your app's Xcode project?

![image](https://user-images.githubusercontent.com/15803067/201100776-600450ca-7c0f-4f27-b4d3-f1b8110e1dcc.png)

### Have you created an APNs key in your Apple Developer account & uploaded this APNs key to your Firebase console?

![Screenshot 2022-11-10 at 14 15 41](https://user-images.githubusercontent.com/15803067/201101788-41764fcc-674c-4978-bc20-20bc6827da01.png)

### Have you disabled method swizzling for Firebase in your app?

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CADisableMinimumFrameDurationOnPhone</key>
	<true/>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleDisplayName</key>
	<string>$(APP_DISPLAY_NAME)</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleLocalizations</key>
	<array>
		<string>en</string>
		<string>pl</string>
		<string>pt</string>
		<string>ru</string>
		<string>zh_CN</string>
		<string>zh</string>
		<string>de</string>
		<string>fr_CA</string>
		<string>fr</string>
		<string>ar</string>
		<string>it</string>
		<string>es</string>
		<string>cs</string>
	</array>
	<key>CFBundleName</key>
	<string>td_mobile_v2</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
	<key>FirebaseAppDelegateProxyEnabled</key>
	<true/>
	<key>FlutterDeepLinkingEnabled</key>
	<true/>
	<key>ITSAppUsesNonExemptEncryption</key>
	<false/>
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>https</string>
	</array>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSCameraUsageDescription</key>
	<string>We require camera for video consultations.</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>We require microphone for video consultations.</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>We require access to library for medical files upload.</string>
	<key>UIBackgroundModes</key>
	<array>
		<string>audio</string>
		<string>fetch</string>
		<string>processing</string>
		<string>remote-notification</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<true/>
</dict>
</plist>
```

### Are you sending messages to your app from the Firebase Admin SDK?

```js
const topic = '09fc2739-07e2-42c4-9f08-18604732320b';
const message = {
  data: {
    scope: 'appointment',
    status: '3'
  },
  apns: {
    payload: {
      aps: {
        contentAvailable: true,
      },
    },
  },
  topic: topic
};
getMessaging().send(message)
  .then((response) => {
    console.log('Sent message:', response);
  })
```

### Have you requested permission from the user to receive notifications?

- [X] I have the relevant permission to receive notifications.

### Have you used the 'Console' application on your macOS device to check if the iOS device's system is throttling your background messages?

![image](https://user-images.githubusercontent.com/15803067/201104098-ddfeccea-1025-4602-b3ed-6d694cd022b7.png)

### Additional context and comments

`didReceiveRemoteNotification` from `FLTFirebaseMessagingPlugin.m` is not invoked. But when I implement `didReceiveRemoteNotification` in `AppDelegate.swift` it is invoked
```swift
override func application(_ application: UIApplication,
                          didReceiveRemoteNotification userInfo: [AnyHashable : Any],
                          fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
}
```

**Comment by mazen930** [comment]
@tomk9 from payload this is silent notification, no ? isn't `contentAvailable: true,` should be => `content_available : true` ,
i also want to ask about the behaviour  of the `didReveiveRemoteNotification` does it always not invoked or when sent to background or screen is locked only ?

**Comment by tomk9** [comment]
@mazen930 `contentAvailable` is in docs https://firebase.google.com/docs/reference/admin/node/firebase-admin.messaging.messagingoptions.md#messagingoptionscontentavailable
`didReceiveRemoteNotification` is always not invoked.

**Comment by mazen930** [comment]
Tbh , i am always confused by firebase docs as they have million docs for same thing , anyway i used this https://firebase.google.com/docs/cloud-messaging/xmpp-server-ref , also if it work can you update me wether it working or not , as i have it working but after a time from being in background it stops
also depend on notificaiton type you want this method should be invoked in my case i used silent notificaiton , here is the sample
    {
        "to": "fcm_token",
        "data": {
            "clear_data": true
        },
        "content_available": true,
        "apns-priority": 5
    };

**Comment by tomk9** [comment]
I created a new project and now everything works. It occurs that in my old project the file `GoogleService-Info.plist` was not generated by `flutterfire config`. Now I updated to `flutterfire_cli 0.2.7` and this file is generated.
I close the issue.
