### ISSUE TITLE
🐛 [firebase_app_check] Play Integrity API responses not received

### ISSUE THREAD

**Issue by mzkai** [firebase/flutterfire#9905]
## Bug report
With firebase_app_check version ^0.1.1+3, Play Integrity is default for Android. However, with Google Play Store Integrity API responses set to ON, then I am still not receiving any of the device integrity responses back, i.e., MEETS_DEVICE_INTEGRITY, MEETS_BASIC_INTEGRITY, MEETS_STRONG_INTEGRITY. This makes it difficult to support legitimate users that might fail one of the integrity checks.

I tried checking the documentation at https://firebase.google.com/docs/app-check/flutter/default-providers, however it doesn't seem to mention how to receive Integrity API responses.

# Firebase Authentication
```
await FirebaseAppCheck.instance.activate(
    webRecaptchaSiteKey: 'site-key',
    // androidProvider: AndroidProvider.playIntegrity,
);
```

# Versions
flutter: 3.3.8
firebase_app_check: ^0.1.1+3

**Comment by darshankawar** [comment]
@mzkai 
Please check this merged PR and see if it helps in your case : https://github.com/firebase/flutterfire/pull/9646
