### ISSUE TITLE
🐛 [firebase_messaging] FirebaseException: [firebase_messaging/unknown]  The request timed out.

### ISSUE THREAD

**Issue by Lawati97** [firebase/flutterfire#9917]
` if (Platform.isIOS) {
      await _fcm.requestPermission();
    }
    await _fcm.getToken().then(
      (String? fcm) {
        assert(fcm != null);
        locator<AppInfo>().updateFCM(fcm as String);
      },
    );`

this is the code am using need your support to avoid this issue

all of my issues are with Ios devices not android

**Comment by darshankawar** [comment]
> locator<AppInfo>()

@Lawati97  Is this a third party plugin ? If so, can you just try without any third party plugin code and just use `firebase_messaging` code from the [plugin example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example) and try again to see if you still get same error or not ?

**Comment by Lawati97** [comment]
Will give a try but the locator just stores the variable as global so am not sure how it can be related @darshankawar

**Comment by darshankawar** [comment]
@Lawati97 
Can you provide `flutter doctor -v`, plugin version and complete minimal reproducible code sample along with steps to replicate that shows the reported behavior ?

**Comment by Lawati97** [comment]
Flutter 2.8.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision cf44000065 (11 months ago) • 2021-12-08 14:06:50 -0800
Engine • revision 40a99c5951
Tools • Dart 2.15.0

firebase_messaging: 10.0.9

class PushNotificationService {
final FirebaseMessaging _fcm = FirebaseMessaging.instance;
Future initialise(BuildContext context) async {
if (Platform.isIOS) {
      // request permissions if we're on ios
      await _fcm.requestPermission();
    }
    await _fcm.getToken().then(
      (String? fcm) {
        assert(fcm != null);
//store in a global variable
      },
    );


    FirebaseMessaging.onMessage.listen((RemoteMessage message) {
}
}
}

**Comment by darshankawar** [comment]
Your framework version and plugin version, both are old. I recommend to upgrade both to latest and try again to see if you still get same behavior or not.
