### ISSUE TITLE
🐛 [firebase_auth] error.credential returns null when converting anonymous user to google user flutter web

### ISSUE THREAD

**Issue by mcradha** [firebase/flutterfire#9920]
## Bug report

**Describe the bug**
I recently upgraded my Flutter to 3.3.8  and firebase packages as below:
firebase_core: ^2.1.1 firebase_auth: ^4.1.1 google_sign_in: ^5.4.1 firebase_database: ^10.0.4 firebase_analytics: ^10.0.4

I use linkwithPopup to convert the anonymous user into a google sign in

UserCredential? gCredential;

if (kIsWeb) {
  GoogleAuthProvider authProvider = GoogleAuthProvider();

  try {
 gCredential = await anonUser?.linkWithPopup(authProvider);

If the user is already linked before to another anonymous user, I get the exception "credential-already-in-use". However error.credential is null

### Steps to reproduce

1. Sign up a user anonymously using Firebase Authentication
2. Login with a gmail address so the anonymous user is linked to the google credential
3. Restart the app so there is a new anonymous sign in. 
4. Now try to login again with the same email address. 
5. The error is thrown but error.credential is null. 

This same code was working fine with my older configuration of firebase packages which was:
firebase_core: 1.12.0 firebase_auth: ^3.3.6

### Expected behavior

error.credential should be populated with the correct credentials for switching back the user to the previously linked credential. 

---

## Additional context

Also raised a SOF which describes the problem in more detail: https://stackoverflow.com/questions/74427446/after-upgrading-firebase-auth-for-credential-already-in-use-error-error-creden 
---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel stable, 3.3.8, on Microsoft Windows [Version 10.0.19045.2251], locale en-IN)
    • Flutter version 3.3.8 on channel stable at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (5 days ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Radha\AppData\Local\Android\sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.0.32126.317
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.73.1)
    • VS Code at C:\Users\Radha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2251]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 107.0.5304.107
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 107.0.1418.42

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.18.4
Flutter SDK 3.3.8
jwdaily 1.0.0+1

dependencies:
- circular_countdown_timer 0.2.3 [flutter]
- confetti 0.7.0 [flutter vector_math]
- cupertino_icons 1.0.5
- date_picker_timeline 1.2.3 [flutter intl]
- device_info_plus 8.0.0 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta win32]
- firebase_analytics 10.0.4 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 4.1.2 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.2.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_database 10.0.4 [firebase_core firebase_core_platform_interface firebase_database_platform_interface firebase_database_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- fluttertoast 8.1.1 [flutter flutter_web_plugins]
- google_sign_in 5.4.2 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- http 0.13.5 [async http_parser meta path]
- image_gallery_saver 1.7.1 [flutter]
- intl 0.17.0 [clock path]
- path_provider 2.0.11 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- provider 6.0.4 [collection flutter nested]
- screenshot 1.2.3 [flutter]
- seo_renderer 0.6.0 [flutter]
- share_plus 6.2.0 [cross_file meta mime flutter flutter_web_plugins share_plus_platform_interface file url_launcher_web url_launcher_windows url_launcher_linux url_launcher_platform_interface ffi win32]
- shared_preferences 2.0.15 [flutter shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- universal_html 2.0.8 [async csslib charcode collection html meta source_span typed_data universal_io]
- url_launcher 6.1.6 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]

dev dependencies:
- flutter_launcher_icons 0.10.0 [args checked_yaml cli_util image json_annotation path yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- _flutterfire_internals 1.0.7 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta] 
- archive 3.3.2 [crypto path]
- args 2.3.1
- async 2.9.0 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.1
- charcode 1.3.1
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- cli_util 0.3.5 [meta path]
- clock 1.1.1
- cloud_firestore_platform_interface 5.8.4 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.0.4 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.16.0
- cross_file 0.3.3+2 [js meta]
- crypto 3.0.2 [typed_data]
- csslib 0.17.2 [source_span]
- device_info_plus_platform_interface 7.0.0 [flutter meta plugin_platform_interface]
- fake_async 1.3.1 [clock collection]
- ffi 2.0.1
- file 6.1.4 [meta path]
- firebase_analytics_platform_interface 3.3.12 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.1+3 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js] 
- firebase_auth_platform_interface 6.11.1 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.1.2 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.5.2 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.0.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_database_platform_interface 0.2.2+12 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_database_web 0.2.1+14 [firebase_core firebase_core_web firebase_database_platform_interface flutter flutter_web_plugins js]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- google_sign_in_android 6.1.1 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.5.0 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.3.0 [flutter plugin_platform_interface quiver]
- google_sign_in_web 0.10.2 [flutter flutter_web_plugins google_sign_in_platform_interface js]
- html 0.15.1 [csslib source_span]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image 3.2.2 [archive meta xml]
- js 0.6.4
- json_annotation 4.7.0 [meta]
- matcher 0.12.12 [stack_trace]
- material_color_utilities 0.1.5
- meta 1.8.0
- mime 1.0.2
- nested 1.0.0 [flutter]
- path 1.8.2
- path_provider_android 2.0.21 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.11 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.6 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.5 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.3 [ffi flutter path path_provider_platform_interface win32]
- petitparser 5.1.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.3 [meta]
- process 4.2.4 [file path platform]
- quiver 3.1.0 [matcher]
- share_plus_platform_interface 3.2.0 [cross_file flutter meta mime plugin_platform_interface path_provider uuid]
- shared_preferences_android 2.0.14 [flutter shared_preferences_platform_interface]
- shared_preferences_ios 2.1.1 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.1.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_macos 2.0.4 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.1.0 [flutter plugin_platform_interface]
- shared_preferences_web 2.0.4 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.1.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sky_engine 0.0.99
- source_span 1.9.0 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.1 [source_span]
- term_glyph 1.2.1
- test_api 0.4.12 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.1 [collection]
- universal_io 2.0.4 [collection crypto meta typed_data]
- url_launcher_android 6.0.21 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.1 [flutter plugin_platform_interface]
- url_launcher_web 2.0.13 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.1 [flutter url_launcher_platform_interface]
- uuid 3.0.6 [crypto]
- vector_math 2.1.2
- win32 3.1.1 [ffi]
- xdg_directories 0.2.0+2 [meta path process]
- xml 6.1.0 [collection meta petitparser]
- yaml 3.1.1 [collection source_span string_scanner]```

</details>

---

**Comment by darshankawar** [comment]
> * Restart the app so there is a new anonymous sign in.
> * Now try to login again with the same email address.

@mcradha  What happens if you sign out as anonymous and then try to login again with same email address ? Do you still get null or not ?
Can you also provide the complete `error.credential` response ?

**Comment by mcradha** [comment]
@darshankawar I havent tried signing out as anonymous user but if there is no user associated with the gmail address, then it associates the current anonymous user with the gmail address and it works fine. The issue is only happening in case where the gmail is already associated with another anonymous user and it goes into the "credential-already-in-use" exception

error.credential is null - there is nothing in it. Did you get a chance to see the SOF? I have pasted my code in there

**Comment by darshankawar** [comment]
Thanks for the update @mcradha 


> Did you get a chance to see the SOF? I have pasted my code in there

Yes I saw that and have been trying to see how your use case works exactly by comparing it with `firebase_auth` [plugin example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_auth/firebase_auth/example). Can you try the same, use the code from it and see if using it, you still get same behavior as or not.

**Comment by mcradha** [comment]
Hi @darshankawar - thanks for your response

The plugin example uses signinWithCredential which is used for a first time sign in  of the user directly using Google credential. There is no conversion from anonymous user to Google user there. Secondly, the issue I am facing is actually happening when the Google user is previously linked to another anonymous user. I use the linkWithPopup function, which I could not see being used in that example

**Comment by darshankawar** [comment]
Thanks for the update. I am keeping this issue open and labeling for further insights from the team on expected behavior on the use case described, specifically `when the Google user is previously linked to another anonymous user.`

**Comment by mcradha** [comment]
Just for reference - here are my anonymous sign in and google sign in functions

Future<bool> anonymousSignIn() async {
    try {
      userCredential = await FirebaseAuth.instance.signInAnonymously();
      anonUser = userCredential?.user ?? null;
      _userId = anonUser?.uid;
    } catch (e) {
      debugPrint('Failed anonymous sign in $e');
      return false;
    }

Future<bool> signInWithGoogle({required BuildContext context}) async {
    UserCredential? gCredential;

    if (kIsWeb) {
      GoogleAuthProvider authProvider = GoogleAuthProvider();

      try {
        debugPrint('Inside sign in with Google');
        gCredential = await anonUser?.linkWithPopup(authProvider);
        guser = gCredential?.user;

        FirebaseAuth.instance.setPersistence(Persistence
            .LOCAL); // in order to maintain session when user closes browser and opens again

        if (guser != null) {
          email = guser?.email ?? '';
          _token = await guser?.getIdToken();
          gname = guser?.displayName ?? '';
          guid = guser?.uid ?? '';
          gimage = guser?.photoURL ?? '';
          _userId = guid;
          googleSignIn = true;
        }

        debugPrint('***Google user is $guser and name is $gname');
      } on FirebaseAuthException catch (error) {
        switch (error.code) {
          case "provider-already-linked":
            debugPrint("The provider has already been linked to the user.");
            break;
          case "invalid-credential":
            debugPrint("The provider's credential is not valid.");
            break;
          case "credential-already-in-use":
            {
              debugPrint(
                  'In credential in use ${error.credential} ${error.email}');

              if (error.credential != null) {
                gCredential = await FirebaseAuth.instance
                    .signInWithCredential(error.credential!);
                debugPrint('After sign in with credential');

                guser = gCredential.user;
              }
              FirebaseAuth.instance.setPersistence(Persistence
                  .LOCAL); // in order to maintain session when user closes browser and opens again

              if (guser != null) {
                await guser?.reload(); // reloading to fix firebase bug

                guser = FirebaseAuth.instance.currentUser;
                email = guser?.email ?? '';
                _token = await guser?.getIdToken();
                gname = guser?.displayName ?? '';
                guid = guser?.uid ?? '';
                gimage = guser?.photoURL ?? '';
                _userId = guid;
                googleSignIn = true;
                await readStats();
              }

              debugPrint(
                  "The account corresponding to the credential already exists, "
                  "or is already linked to a Firebase User $guser and ${anonUser?.uid}. ${error.email} ${error.credential} ${guser?.displayName}");
            }
        }
      }

In google sign in, first time sign in to a google account works since there is no anonymous id already linked to the google account. However, second time you try to sign in using the same google credentials, it does not work.

**Comment by Lyokone** [comment]
Hey @mcradha, looking at your code, we're not supporting linking with a GoogleAuthProvider directly.
You are supposed to create a credential first:
```
      final credential = GoogleAuthProvider.credential(
        accessToken: googleAuth.accessToken,
        idToken: googleAuth.idToken,
      );
``` 

then you can `linkWithCredential` on the current user.

**Comment by Lyokone** [comment]
I'll close this, feel free to reopen if it doesn't work as expected :)
