### ISSUE TITLE
🐛 [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.

### ISSUE THREAD

**Issue by hieuvh3011** [firebase/flutterfire#9921]
## Bug report

**Describe the bug**
When I use Cloud Firestore, this bug continues to happen. I use very simple code:
```
    CollectionReference userCollectionRef =
        FirebaseFirestore.instance.collection('users').withConverter<Users>(
            fromFirestore: (snapshot, _) => Users.fromMap(snapshot.data()!),
            toFirestore: (user, _) => user.toMap(),
        );
    var firebaseUser = await userCollectionRef
        .doc(userProfile.userId)
        .get()
        .then((qs) => qs.exists ? qs.data() : null);
      if (firebaseUser == null) {
        await userCollectionRef.doc(user.id).set(user);
    }
```

My Cloud Store rules:
```
    rules_version = '2';
    service cloud.firestore {
      match /databases/{database}/documents {
        match /{document=**} {
          allow read, write: if request.time < timestamp.date(2024, 1, 1);
        }
      }
    }
```

### Expected behavior

Cloud Firestore will do the function normally

### Flutter doctor

Run `flutter doctor` and paste the output below:

```
[✓] Flutter (Channel stable, 3.3.7, on macOS 13.0.1 22A400 darwin-arm (Rosetta), locale
    en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.2)
[✓] VS Code (version 1.73.1)
[✓] Connected device (4 available)
    ! Error: Hieu’s iphone xs is busy: Fetching debug symbols for Hieu’s iphone xs.
      Xcode will continue when Hieu’s iphone xs is finished. (code -10)
[✓] HTTP Host Availability
```

**Comment by hieuvh3011** [comment]
The error that I received:

```
9.5.0 - [FirebaseFirestore][I-FST000001] Listen for query at users/U1bbf71227836b41b9d4c5bd1a0ffbedc failed: Missing or insufficient permissions.
flutter: Login Line Error = [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.
```

**Comment by darshankawar** [comment]
@hieuvh3011 Thanks for the report.

`[cloud_firestore/permission-denied]` means you need to set Firestore rules properly on your Firebase console. 

> allow read, write: if request.time < timestamp.date(2024, 1, 1);

Do you get same error if you remove the `if` condition ? i,e try like this and confirm: `allow read, write: if false;`

**Comment by hieuvh3011** [comment]
@darshankawar thank you for the quick response. I tried a lot of other conditions, such as `if true`, `if false`, `if request.auth != null`, etc. All of them not work. I really don’t know why

**Comment by darshankawar** [comment]
Can you try `allow read, write: if request.auth.uid != null;` instead of `allow read, write : if auth != null ;` and see if it helps ?

**Comment by AlmogRnD** [comment]
This is a firestore rules error. The issue is here `if request.time < timestamp.date(2024, 1, 1);` recommend you try what @darshankawar and suggest first

**Comment by hieuvh3011** [comment]
I tried it and it was really an error from Firebase console. Thank you guys for your support
