### ISSUE TITLE
🐛 [cloud_firestore] Flutter web - Failed to obtain exclusive access to the persistence layer when multi-tab && synchronizeTabs: true

### ISSUE THREAD

**Issue by pldelattre** [firebase/flutterfire#9929]
### [REQUIRED] Describe your environment

  * Operating System version: MacOs Monterey 12.6.1
  * Browser version: Chrome 107.0.5304.110 and Safari 16.1
  * Firebase SDK version: 9.11
  * Firebase Product: firestore 

### [REQUIRED] Describe the problem

I have built a flutter web app with persistence enabled and synchronizeTabs: true. 
It works when opening the first chrome tab but it fails when loading the app on another tab with the following error in chrome console. 

> @firebase/firestore: Firestore (9.11.0): Error enabling offline persistence. Falling back to persistence disabled: FirebaseError: [code=failed-precondition]: Failed to obtain exclusive access to the persistence layer. To allow shared access, multi-tab synchronization has to be enabled in all tabs. If you are using `experimentalForceOwningTab:true`, make sure that only one tab has persistence enabled at any given time.

#### flutter packages 
```
  firebase_core: ^2.2.0
  firebase_auth: ^4.1.2
  cloud_firestore: ^4.0.5
  firebase_storage: ^11.0.5
```

#### Flutter code  to reproduce:

```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
 
  if (kIsWeb) {
    await FirebaseFirestore.instance
        .enablePersistence(const PersistenceSettings(synchronizeTabs: true));
  }

  runApp(const MyApp());
}
```

**Comment by darshankawar** [comment]
Thanks for the report @pldelattre 
Looking at the error received, it is related and coming from `firebase-js-sdk` platform itself and not with flutterfire, as the flutterfire plugin is just a wrapper around native SDKs. See [this](https://github.com/firebase/flutterfire/issues/3561#issuecomment-877090526) response from Flutterfire team.

Closing from here.

**Comment by pldelattre** [comment]
@darshankawar 
see issue https://github.com/firebase/firebase-js-sdk/issues/6792 on firebase-js-sdk
They are telling the issue is with flutterfire and not with the js SDK. 
Can we reopen ?

**Comment by darshankawar** [comment]
Thanks for the feedback. Reopening.

**Comment by darshankawar** [comment]
I am able to replicate this behavior running `cloud_firestore` plugin example and including code snippet provided above. When we open another tab and try to access same url, it shows the reported error in browser console.

<img width="1198" alt="Screenshot 2022-11-16 at 12 49 13 PM" src="https://user-images.githubusercontent.com/67046386/202112790-66512a53-0cdf-49f7-9225-8b32b6aee611.png">

Earlier I had close this issue based on [this](https://github.com/firebase/flutterfire/issues/3561#issuecomment-877090526) comment, but per [this](https://github.com/firebase/firebase-js-sdk/issues/6792#issuecomment-1314597764) comment from native repo, reopened this and labeling for further insights from team.

/cc @russellwheatley
