### ISSUE TITLE
🐛 [firebase_messaging] Significant decrease in number of received data messages on Android

### ISSUE THREAD

**Issue by apaolino** [firebase/flutterfire#9930]
Since 8 of November 2022 I've started to have a significant decrease in the number of received data messages sent using firebase admin from a firebase function.
I'm experiencing this regardless firebase_messaging or android version (using firebase_messaging 14.0.4, 14.0.2, 13.0.4).
Are you aware of something changed on backend side perhaps?

![image](https://user-images.githubusercontent.com/4774846/201726757-14eea09f-44f1-400a-83aa-1cbbe4c894d2.png)

**Comment by darshankawar** [comment]
@apaolino 
I think you will need to report this in [firebase support](https://firebase.google.com/support) for further resolution, as I don't think flutterfire would have any control over this behavior.
Closing from here. If you get directed here, write in comments and I'll reopen it.
