### ISSUE TITLE
🐛 [firebase_core_web] Error: Expected a value of type 'Object', but got one of type 'Null'

### ISSUE THREAD

**Issue by yurrpt** [firebase/flutterfire#9934]
Error while running flutter on web
I think the error is coming from firebase core. my project runs smoothly on android.

Error output
**Error: Expected a value of type 'Object', but got one of type 'Null**

logs

> C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49 throw_ C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 99:3 castError C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 470:10 cast C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 73:24 as packages/firebase_core_web/src/firebase_core_web.dart 64:20 get [_ignoredServiceScripts] packages/firebase_core_web/src/firebase_core_web.dart 115:28 _initializeCore C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 85:54 runBody C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 124:5 _async packages/firebase_core_web/src/firebase_core_web.dart 107:31 [_initializeCore] packages/firebase_core_web/src/firebase_core_web.dart 149:11 initializeApp C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 85:54 runBody C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 124:5 _async packages/firebase_core_web/src/firebase_core_web.dart 145:44 initializeApp packages/firebase_core/src/firebase.dart 43:47 initializeApp C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 85:54 runBody C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 124:5 _async packages/firebase_core/src/firebase.dart 39:43 initializeApp packages/swivenetworkproject/main.dart 28:18 main C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 85:54 runBody C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 124:5 _async packages/swivenetworkproject/main.dart 26:18 main$ web_entrypoint.dart 24:31 <fn> C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 352:37 _checkAndCall C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 357:39 dcall C:/b/s/w/ir/cache/builder/src/out/host_debug/lib/ui/initialization.dart 77:15 <fn> C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 46:50 <fn> C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1660:54 runUnary C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 147:18 handleValue C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 767:44 handleValueCallback C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 796:13 _propagateToListeners C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 567:5 [_completeWithValue] C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 640:7 callback C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 40:11 _microtaskLoop C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 49:5 _startMicrotaskLoop C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 167:15

**Flutter doctor -v output**

`

```
[√] Flutter (Channel master, 3.5.0-10.0.pre.58, on Microsoft Windows [Version 10.0.19043.2251], locale
    tr-TR)
    • Flutter version 3.5.0-10.0.pre.58 on channel master at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0c14308404 (3 weeks ago), 2022-10-24 14:31:17 -0700
    • Engine revision f445898c1a
    • Dart version 2.19.0 (build 2.19.0-330.0.dev)
    • DevTools version 2.18.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\monst\AppData\Local\Android\sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Derleme Araçları 2019 16.11.18)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Derleme Araçları 2019 version 16.11.32802.440
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the
      "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.73.1)
    • VS Code at C:\Users\monst\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.52.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.2251]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 107.0.5304.107
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 107.0.1418.42

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
`

My pubspec.yaml packages

```
#db
 firebase_auth: ^4.1.2
 firebase_core: ^2.2.0
 firebase_crashlytics: ^3.0.5
 cloud_firestore: ^4.0.2
 firebase_database: ^10.0.1
 firebase_messaging: ^14.1.0

```

Err
![image](https://user-images.githubusercontent.com/117461048/201888741-18478ad5-2e0e-43a1-b914-371a1d83af99.png)

![image](https://user-images.githubusercontent.com/117461048/201887612-71269dc9-0f53-4ac3-903e-1cda737432b8.png)

**Comment by darshankawar** [comment]
@yurrpt 
Can you upgrade to latest master and try again ?
Also, if error persists, please provide complete code sample and error log.

**Comment by yurrpt** [comment]
@darshankawar Hi , I updated the packages, the error still persists. 

I think the error is coming from `firebase_core_web.`

main.dart
```
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform, // **The error occurs on this line**
  );
  // Pass all uncaught "fatal" errors from the framework to Crashlytics
  FlutterError.onError = (errorDetails) {
    FirebaseCrashlytics.instance.recordFlutterFatalError(errorDetails);
  };
  // Pass all uncaught asynchronous errors that aren't handled by the Flutter framework to Crashlytics
  PlatformDispatcher.instance.onError = (error, stack) {
    FirebaseCrashlytics.instance.recordError(error, stack, fatal: true);
    return true;
  };

 

  await FirebaseMessaging.instance.setForegroundNotificationPresentationOptions(
    alert: true, // Required to display a heads up notification
    badge: true,
    sound: true,
  );
  FirebaseMessaging.onMessage.listen((message) {
    if (kDebugMode) {
      print('Got a message whilts in the foreground!');
    }
    if (kDebugMode) {
      print('Message data ${message.data}');
    }
    if (message.notification != null) {
      if (kDebugMode) {
        print('${message.notification}');
      }
    }
  });
  

  final prefs = await SharedPreferences.getInstance();

 

  runApp(
    ChangeNotifierProvider(
      child: const MyApp(),
      create: (BuildContext context) => ThemeProvider(
        isDarkMode: prefs.getBool('isDarkTheme'),
      ),
    ),
  );
}
```

my stack trace 
![image](https://user-images.githubusercontent.com/117461048/202003795-75b923fe-46c8-492f-bdbe-de2719b978b6.png)
```
An exception has occurred.
Error: Expected a value of type 'Object', but got one of type 'Null'
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49      throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 99:3        castError
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 470:10  cast
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 73:24                 as
packages/firebase_core_web/src/firebase_core_web.dart 64:20                                                                    get [_ignoredServiceScripts]
packages/firebase_core_web/src/firebase_core_web.dart 115:28                                                                   _initializeCore
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 85:54                runBody
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 124:5                _async
packages/firebase_core_web/src/firebase_core_web.dart 107:31                                                                   [_initializeCore]
packages/firebase_core_web/src/firebase_core_web.dart 149:11                                                                   initializeApp
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 85:54                runBody
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 124:5                _async
packages/firebase_core_web/src/firebase_core_web.dart 145:44                                                                   initializeApp
packages/firebase_core/src/firebase.dart 43:47                                                                                 initializeApp
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 85:54                runBody
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 124:5                _async
packages/firebase_core/src/firebase.dart 39:43                                                                                 initializeApp
packages/swivenetworkproject/main.dart 28:18                                                                                   main
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 85:54                runBody
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 124:5                _async
packages/swivenetworkproject/main.dart 26:18                                                                                   main$
web_entrypoint.dart 24:31                                                                                                      <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 352:37  _checkAndCall
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 357:39  dcall
C:/b/s/w/ir/cache/builder/src/out/host_debug/lib/ui/initialization.dart 77:15                                                  <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 46:50                <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1660:54                                              runUnary
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 147:18                                        handleValue
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 767:44                                        handleValueCallback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 796:13                                        _propagateToListeners
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 567:5                                         [_completeWithValue]
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 640:7                                         callback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 40:11                                  _microtaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 49:5                                   _startMicrotaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 167:15               <fn>
```

my console 
![image](https://user-images.githubusercontent.com/117461048/202004120-02953bda-cfed-4e70-a54e-852b79f05442.png)

**Comment by darshankawar** [comment]
@yurrpt I tried with `firebase_core` plugin example and ran it on web which compiled properly without the said issue:

<img width="1307" alt="Screenshot 2022-11-16 at 1 34 15 PM" src="https://user-images.githubusercontent.com/67046386/202123447-e0c3bf6b-d585-4960-8663-555158edbd20.png">

Can you run `dart pub global activate flutterfire_cli` followed by `flutterfire configure` again and see if it helps ? This command writes the native service files in your project so you don't need to manually add it.
I guess there's a conflict between firebase intialization in your project config which could be leading to the error.



> I updated the packages,

I meant the master version you are on.

**Comment by yurrpt** [comment]
Hi,  dart pub global activate flutterfire_cli and flutterfire configure I tried the commands but the error persists. I'm already on the master version
![image](https://user-images.githubusercontent.com/117461048/202156956-176a16f2-cff8-467b-83ef-76b172f7e53b.png)

**Comment by yurrpt** [comment]
@darshankawar Hello again, i create a new flutter project , added firebase_core and make initialize but error is running
here is 
![image](https://user-images.githubusercontent.com/117461048/202161156-0a0b0c27-ed00-493b-b99a-094155e48848.png)

**Comment by darshankawar** [comment]
@yurrpt From [this](https://github.com/firebase/flutterfire/issues/9934#issuecomment-1316796149) details you provided, you don't seem to be using firebase options to initialize. Please use as below:

`await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);` 

Also, FlutterFire now uses web JS SDK > v9. So if you have Firebase.initializeApp in your "index.html" file, please remove it and try again.



> ChromeProxyService: Failed to evaluate expression 'Colors': InternalError: Expression evaluation in async frames is not supported. No frame with index 39..
> ChromeProxyService: Failed to evaluate expression 'Colors.red': InternalError: Expression evaluation in async frames is not supported. No frame with index 39..
> ChromeProxyService: Failed to evaluate expression 'Firebase.initializeApp': InternalError: Expression evaluation in async frames is not supported. No frame with index 39..
> ChromeProxyService: Failed to evaluate expression 'backgroundColor': InternalError: Expression evaluation in async frames is not supported. No frame with index 39..

This doesn't seem to be related to FlutterFire. See below similar links for issues raised like these for further resolution:

https://stackoverflow.com/questions/71268721/chromeproxyservice-failed-to-evaluate-expression

**Comment by yurrpt** [comment]
in my case await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform); not working 

here is my solution 
 ```
WidgetsFlutterBinding.ensureInitialized();
  if (kIsWeb) {
    await Firebase.initializeApp(
      options: const FirebaseOptions(
          apiKey: "",
          authDomain: "",
          databaseURL: "", // **DATABASEURL MUST BE GIVEN.**
          projectId: "",
          storageBucket: "",
          messagingSenderId: "",
          appId: ""),  
    );
  } else {
    await Firebase.initializeApp();
```

Thanks,

**Comment by darshankawar** [comment]
Thanks for the update. Closing as resolved based on above comment.

**Comment by pawinlian** [comment]
I use all of the methods but it still does not work.

**Comment by yurrpt** [comment]
> I use all of the methods but it still does not work.
still going this week. Topic can be opened. ++
