### ISSUE TITLE
[flutter firebase messaging] 14.1.0 runApp call twice

### ISSUE THREAD

**Issue by saharvx9** [firebase/flutterfire#9941]
## Bug report

main first function and runApp call twice

### Steps to reproduce

1. void main call
2. initilize firebase
3. runapp
4. after couple of seconds main + runapp call again

### Expected behavior

call once

### Flutter doctor

Run `flutter doctor` and paste the output below:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.8, on macOS 12.6 21G115 darwin-arm, locale en-IL)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Community Edition (version 2021.3.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

### Flutter dependencies

flutter_core 2.2.0
firebase_messaging 14.1.0

**Comment by nirbar89** [comment]
i faced the same issue after upgrading to 14.1.0
