### ISSUE TITLE
🐛 [firebase_dynamic_links 5.0.5] Get initial link does not run when app is launched from a cold state on both android and ios

### ISSUE THREAD

**Issue by Henrydykee** [firebase/flutterfire#9949]
## Bug report

**Describe the bug**
when app is launched from a cold state using a deeplink getInitial link function doesn't run, but when app is running on the background and app is launched with a deeplink getInitial link works fine.

**Comment by darshankawar** [comment]
Thanks for the report @Henrydykee 

Check [this](https://github.com/firebase/flutterfire/issues/9110) similar issue and see if it helps in your case with underlying comments mentioned in it.
