### ISSUE TITLE
some links are broken in the documentation, it shows "Page Not Found"

### ISSUE THREAD

**Issue by anasfik** [firebase/flutterfire#9966]
Hi,
I tried following the documentation for implementing the Google social authentication.

Trying to generate a SHA1 key following the inlined support installation link which is https://firebase.flutter.dev/docs/auth/manual-installation/android#generating-firebase-credentials

[broken link screenshot](https://imgur.com/PuMT6dy)

and the page is not found, and I don't know how to generate the SHA1 key, is this documentation link replaced with something else?

**Comment by darshankawar** [comment]
@anasfik 
The link you shared is archived and not to refer anymore. The Flutterfire documentation has been merged with firebase documentation. So you'll need to refer https://firebase.google.com/docs/auth/flutter/start going forward.

Closing from here. If you face other issues from migrated documentation, please raise new issue.
