### ISSUE TITLE
🐛 [PLUGIN_NAME_HERE] Local module descriptor class for com.google.android.gms.providerinstaller.dynamite not found.

### ISSUE THREAD

**Issue by abdoul-kader1** [firebase/flutterfire#9967]
## Bug report

**Describe the bug**
i have been experiencing a problem for a few days on my flutter application, when setting up FireBase in my application:

"Local module descriptor class for com.google.android.gms.providerinstaller.dynamite not found."

I tested several solutions found on forums:

Clean project - Rebuilt - Invalidate cache on android studio
Uninstall my application completely from my phone (sufficient storage and active internet connection)
Added internet and access_network_state permissions in the android manifest before <application ()
I use the latest version of the Firebase package. My googles play services are up to date, and my phone is recent.

### Steps to reproduce

2. '...'
4. See error or incorrect behavior

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

W/DynamiteModule(17483): Local module descriptor class for com.google.android.gms.providerinstaller.dynamite not found.
I/DynamiteModule(17483): Considering local module com.google.android.gms.providerinstaller.dynamite:0 and remote module com.google.android.gms.providerinstaller.dynamite:0
W/ProviderInstaller(17483): Failed to load providerinstaller module: No acceptable module com.google.android.gms.providerinstaller.dynamite found. Local version is 0 and remote version is 0.
W/ResourceType(17483): ResTable_typeSpec entry count inconsistent: given 77, previously 79
W/ResourceType(17483): ResTable_typeSpec entry count inconsistent: given 77, previously 79
W/ResourceType(17483): ResTable_typeSpec entry count inconsistent: given 3285, previously 3308
W/ResourceType(17483): ResTable_typeSpec entry count inconsistent: given 518, previously 4356
I/zygote  (17483): The ClassLoaderContext is a special shared library.
I/zygote  (17483): The ClassLoaderContext is a special shared library.
V/NativeCrypto(17483): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 295 native methods...
I/ProviderInstaller(17483): Installed default security provider GmsCore_OpenSSL
---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.8, on Microsoft Windows [version 10.0.19044.2251], locale fr-CI)
Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web                                                                                                                
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.73.1)
[√] Connected device (4 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```
Dart SDK 2.18.4                                      
Flutter SDK 3.3.8                                    
reseausocial 1.0.0+1                                 
|-- cloud_firestore 4.0.5                            
|   |-- cloud_firestore_platform_interface 5.8.5     
|   |   |-- _flutterfire_internals 1.0.8             
|   |   |   |-- cloud_firestore_platform_interface...
|   |   |   |-- cloud_firestore_web...               
|   |   |   |-- collection...                        
|   |   |   |-- firebase_core...
|   |   |   |-- firebase_core_platform_interface...
|   |   |   |-- flutter...
|   |   |   '-- meta...
|   |   |-- collection...
|   |   |-- firebase_core...
|   |   |-- flutter...
|   |   |-- meta...
|   |   '-- plugin_platform_interface 2.1.3
|   |       '-- meta...
|   |-- cloud_firestore_web 3.0.5
|   |   |-- _flutterfire_internals...
|   |   |-- cloud_firestore_platform_interface...
|   |   |-- collection...
|   |   |-- firebase_core...
|   |   |-- firebase_core_web...
|   |   |-- flutter...
|   |   |-- flutter_web_plugins 0.0.0
|   |   |   |-- characters...
|   |   |   |-- collection...
|   |   |   |-- flutter...
|   |   |   |-- js...
|   |   |   |-- material_color_utilities...
|   |   |   |-- meta...
|   |   |   '-- vector_math...
|   |   '-- js 0.6.4
|   |-- collection...
|   |-- firebase_core...
|   |-- firebase_core_platform_interface 4.5.2
|   |   |-- collection...
|   |   |-- flutter...
|   |   |-- flutter_test...
|   |   |-- meta...
|   |   '-- plugin_platform_interface...
|   |-- flutter...
|   '-- meta...
|-- cupertino_icons 1.0.5
|-- firebase_auth 4.1.2
|   |-- firebase_auth_platform_interface 6.11.2
|   |   |-- _flutterfire_internals...
|   |   |-- collection...
|   |   |-- firebase_core...
|   |   |-- flutter...
|   |   |-- meta...
|   |   '-- plugin_platform_interface...
|   |-- firebase_auth_web 5.1.2
|   |   |-- firebase_auth_platform_interface...
|   |   |-- firebase_core...
|   |   |-- firebase_core_web...
|   |   |-- flutter...
|   |   |-- flutter_web_plugins...
|   |   |-- http_parser 4.0.2
|   |   |   |-- collection...
|   |   |   |-- source_span...
|   |   |   |-- string_scanner...
|   |   |   '-- typed_data 1.3.1
|   |   |       '-- collection...
|   |   |-- intl 0.17.0
|   |   |   |-- clock...
|   |   |   '-- path...
|   |   |-- js...
|   |   '-- meta...
|   |-- firebase_core...
|   |-- firebase_core_platform_interface...
|   |-- flutter...
|   '-- meta...
|-- firebase_core 2.2.0
|   |-- firebase_core_platform_interface...
|   |-- firebase_core_web 2.0.1
|   |   |-- firebase_core_platform_interface...
|   |   |-- flutter...
|   |   |-- flutter_web_plugins...
|   |   |-- js...
|   |   '-- meta...
|   |-- flutter...
|   '-- meta...
|-- firebase_storage 11.0.5
|   |-- firebase_core...
|   |-- firebase_core_platform_interface...
|   |-- firebase_storage_platform_interface 4.1.23
|   |   |-- collection...
|   |   |-- firebase_core...
|   |   |-- flutter...
|   |   |-- meta...
|   |   '-- plugin_platform_interface...
|   |-- firebase_storage_web 3.3.15
|   |   |-- _flutterfire_internals...
|   |   |-- async...
|   |   |-- firebase_core...
|   |   |-- firebase_core_web...
|   |   |-- firebase_storage_platform_interface...
|   |   |-- flutter...
|   |   |-- flutter_web_plugins...
|   |   |-- http 0.13.5
|   |   |   |-- async...
|   |   |   |-- http_parser...
|   |   |   |-- meta...
|   |   |   '-- path...
|   |   |-- js...
|   |   '-- meta...
|   '-- flutter...
|-- flutter 0.0.0
|   |-- characters 1.2.1
|   |-- collection 1.16.0
|   |-- material_color_utilities 0.1.5
|   |-- meta 1.8.0
|   |-- sky_engine 0.0.99
|   '-- vector_math 2.1.2
|-- flutter_lints 2.0.1
|   '-- lints 2.0.1
'-- flutter_test 0.0.0
    |-- async 2.9.0
    |   |-- collection...
    |   '-- meta...
    |-- boolean_selector 2.1.0
    |   |-- source_span...
    |   '-- string_scanner...
    |-- characters...
    |-- clock 1.1.1
    |-- collection...
    |-- fake_async 1.3.1
    |   |-- clock...
    |   '-- collection...
    |-- flutter...
    |-- matcher 0.12.12
    |   '-- stack_trace...
    |-- material_color_utilities...
    |-- meta...
    |-- path 1.8.2
    |-- source_span 1.9.0
    |   |-- collection...
    |   |-- path...
    |   '-- term_glyph...
    |-- stack_trace 1.10.0
    |   '-- path...
    |-- stream_channel 2.1.0
    |   '-- async...
    |-- string_scanner 1.1.1
    |   '-- source_span...
    |-- term_glyph 1.2.1
    |-- test_api 0.4.12
    |   |-- async...
    |   |-- boolean_selector...
    |   |-- collection...
    |   |-- matcher...
    |   |-- meta...
    |   |-- source_span...
    |   |-- stack_trace...
    |   |-- stream_channel...
    |   |-- string_scanner...
    |   '-- term_glyph...
    '-- vector_math...

</details>

---

**Comment by darshankawar** [comment]
@abdoul-kader1 
We need a proper steps to replicate alongwith minimal code sample that is requested in the issue template, so that it can help us to address the issue. Please provide same.

**Comment by abdoul-kader1** [comment]
and if i give you the source code of the project which is on github?

**Comment by abdoul-kader1** [comment]
https://github.com/abdoul-kader1/reseau-social.git

**Comment by darshankawar** [comment]
@abdoul-kader1 
From the github repo, there doesn't seem to be any issues with the code.

> when setting up FireBase in my application:

You seem to have `firebase_options` in the repo indicating you must have initialized firebase using `flutterfire configure`. Correct ?
When you say while setting up firebase, what exactly are you trying to set ?

Also, looking at the error, it doesn't seem to be specific to flutterfire, but seem to be coming from native android SDK. Can you try a new Flutter project, link the same firebase app you have using `flutterfire configure` and see if using it, you still get same error or not ?

**Comment by abdoul-kader1** [comment]
I configured my project with the flutterfire configure command, and my application is well connected to the console but I can't send data to the cloud firestore I get this error "Local module descriptor class for com.google .android.gms.providerinstaller.dynamite not found."

**Comment by abdoul-kader1** [comment]
my repository updated
https://github.com/abdoul-kader1/reseau-social.git

**Comment by darshankawar** [comment]
Check [this](https://stackoverflow.com/questions/73399202/firebase-data-not-displaying-in-flutter-app) link and underlying comments and see if it helps in your case.

**Comment by abdoul-kader1** [comment]
no it does not help me but I think the problem comes from the emulator because I launched my project on a chrome browser and I was able to send the data correctly in the console

**Comment by darshankawar** [comment]
Please try with another emulator or a physical device and see if you get same error or not.
