### ISSUE TITLE
🐛 [firebase_analytics] shows wrong engagement time

### ISSUE THREAD

**Issue by PranayDosii** [firebase/flutterfire#9970]
In my project, I have implemented custom events. I have added  ` firebaseAnalytics.logEvent`  in my second screen when I try to visit the second screen it shows the wrong engagement time. If I spent 5 or more seconds on the second screen it shows 1 millisecond every time.

You can see in the below Image
<img width="378" alt="Screenshot 2022-11-21 at 3 00 47 PM" src="https://user-images.githubusercontent.com/95602652/203015531-c30a2932-e7ce-4651-9f53-3075f79da401.png">

Here is my code

```
@override
  void initState() {
    super.initState();
    firebaseAnalytics.logEvent(name: "second_screen");
   }

```
dependency  : `firebase_analytics: ^10.0.6`

` flutter doctor -v`

```
[✓] Flutter (Channel stable, 3.3.6, on macOS 12.3.1 21E258 darwin-arm, locale en-IN)
    • Flutter version 3.3.6 on channel stable at /Users/dosii/Documents/flutter_3.3.6
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6928314d50 (4 weeks ago), 2022-10-25 16:34:41 -0400
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/dosii/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by darshankawar** [comment]
@PranayDosii 
Check below links and see if they helps in your case.

https://stackoverflow.com/questions/68937460/is-there-a-way-to-track-engagement-time-for-custom-events-in-firebase-analytics
https://stackoverflow.com/questions/58311045/firebase-analytics-events-currentscreen-is-always-screen-view

**Comment by PranayDosii** [comment]
I tried both but the thing is in flutter web `_analytics.setCurrentScreen(screenName: name)` doest not work have to use `analytics.logEvent(name: 'video_screen');`  instead of it. The custom log event is working but the engagement time is not showing correctly If I try to open any screen for 10 sec or more it still is showing 1 millisecond

**Comment by PranayDosii** [comment]
I reproduced this issue you can see in the video I am spending about 3-4 seconds on the second screen. But you can see in the console it shows 2 milliseconds. I am using the `logEvent` method to log my custom event.

Here is a sample video 

[Video url](https://drive.google.com/file/d/1kXyGAWe9Z4z8G0r5L_GH5XGIJ-Clikv2/view?usp=share_link)


Here is my sample code

```
 firebaseAnalytics
        .logEvent(name: "second_screen_engagement", parameters: {"id":iid});
```
Version

`firebase_analytics: ^10.0.6`

**Comment by darshankawar** [comment]
Thanks for the update. I am not completely sure if the incorrect / mismatch of engagement time is client side issue or native, so keeping this issue open and labeling for team's attention and insights on expected behavior.

**Comment by russellwheatley** [comment]
Hey @PranayDosii - It is not clear to me the steps you're taking. Are you saying you are logging a custom event for every screen change in your Flutter code? 

Something else that is unclear - is there documentation that specifies that custom events ought to have the `engagement_time_msec` property? I can't find the relevant documentation so if you could post a relevant link that would be helpful. Thanks.

You might want to use `logScreenView` which allows you to set `screenClass` and `screenName` properties.
