### ISSUE TITLE
🐛 [firebase_ui_auth] Google sign in functionality broken

### ISSUE THREAD

**Issue by autolainen** [firebase/flutterfire#9971]
firebase_ui_auth 1.0.6  introduced some bug which broke Google sign in button. As you tap on that button and choose google account, some error occur and it won't let you in. I rolled back to 1.0.5 and it works fine.

**Comment by darshankawar** [comment]
@autolainen 
What error do you get after choosing google account ?

**Comment by darshankawar** [comment]
Yes, please send the logs and also please provide what platform (android or iOS) you are seeing this error on.

**Comment by autolainen** [comment]
I am using Android v11 but mu colleagues have experienced the same on other phones which might have other versions. 'ru_RU' locale if it makes any difference.

This is all the log appears after I choose google account:

I/ViewRootImpl@e0c1a4f[SignInHubActivity]( 8019): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager( 8019): prepareNavigationBarInfo() DecorView@8cc8e7b[SignInHubActivity]
D/InputMethodManager( 8019): getNavigationBarColor() -855310
D/InputMethodManager( 8019): prepareNavigationBarInfo() DecorView@8cc8e7b[SignInHubActivity]
D/InputMethodManager( 8019): getNavigationBarColor() -855310
V/InputMethodManager( 8019): Starting input: tba=com.orderx.app_builder ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager( 8019): startInputInner - Id : 0
I/InputMethodManager( 8019): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport( 8019): Input channel constructed: 'ClientS', fd=192
I/ViewRootImpl@1b4e8c0[MainActivity]( 8019): stopped(false) old=false
I/ViewRootImpl@e0c1a4f[SignInHubActivity]( 8019): stopped(true) old=false
I/SurfaceControl( 8019): nativeRelease nativeObject s[480946666048]
I/SurfaceControl( 8019): nativeRelease nativeObject e[480946666048]
W/libEGL  ( 8019): EGLNativeWindowType 0x6ffab6f010 disconnect failed
I/ViewRootImpl@e0c1a4f[SignInHubActivity]( 8019): dispatchDetachedFromWindow
D/InputTransport( 8019): Input channel destroyed: '20fbc2a', fd=172
I/SurfaceControl( 8019): nativeRelease nativeObject s[496347851392]
I/SurfaceControl( 8019): nativeRelease nativeObject e[496347851392]
I/SurfaceControl( 8019): nativeRelease nativeObject s[496347850912]
I/SurfaceControl( 8019): nativeRelease nativeObject e[496347850912]
E/ViewRootImpl( 8019): sendUserActionEvent() mView returned.
E/ViewRootImpl( 8019): sendUserActionEvent() mView returned.
I/SurfaceControl( 8019): nativeRelease nativeObject s[494768809600]
I/SurfaceControl( 8019): nativeRelease nativeObject e[494768809600]
I/SurfaceControl( 8019): assignNativeObject: nativeObject = 0 Surface(name=null)/@0xcb0352 / android.view.SurfaceControl.readFromParcel:1117 android.view.IWindowSession$Stub$Proxy.relayout:1836 android.view.ViewRootImpl.relayoutWindow:9005 android.view.ViewRootImpl.performTraversals:3360 android.view.ViewRootImpl.doTraversal:2618 android.view.ViewRootImpl$TraversalRunnable.run:9971 android.view.Choreographer$CallbackRecord.run:1010 android.view.Choreographer.doCallbacks:809 android.view.Choreographer.doFrame:744 android.view.Choreographer$FrameDisplayEventReceiver.run:995 
I/SurfaceControl( 8019): nativeRelease nativeObject s[496347853408]
I/SurfaceControl( 8019): nativeRelease nativeObject e[496347853408]
I/SurfaceControl( 8019): nativeRelease nativeObject s[496347853312]
I/SurfaceControl( 8019): nativeRelease nativeObject e[496347853312]
I/ViewRootImpl@1b4e8c0[MainActivity]( 8019): Relayout returned: old=(0,0,1080,2340) new=(0,0,1080,2340) req=(1080,2340)0 dur=15 res=0x1 s={true 496362827776} ch=false fn=34
I/ViewRootImpl@1b4e8c0[MainActivity]( 8019): updateBoundsLayer: shouldReparent = false t = android.view.SurfaceControl$Transaction@60e6699 sc = Surface(name=Bounds for - com.orderx.app_builder/com.orderx.app_builder.MainActivity@0)/@0xaba7d5e frame = 34
I/ViewRootImpl@1b4e8c0[MainActivity]( 8019): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager( 8019): prepareNavigationBarInfo() DecorView@5967766[MainActivity]
D/InputMethodManager( 8019): getNavigationBarColor() -855310
D/InputMethodManager( 8019): prepareNavigationBarInfo() DecorView@5967766[MainActivity]
D/InputMethodManager( 8019): getNavigationBarColor() -855310
V/InputMethodManager( 8019): Starting input: tba=com.orderx.app_builder ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager( 8019): startInputInner - Id : 0
I/InputMethodManager( 8019): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport( 8019): Input channel constructed: 'ClientS', fd=171
D/InputTransport( 8019): Input channel destroyed: 'ClientS', fd=192
I/SurfaceControl( 8019): nativeRelease nativeObject s[496347855616]
I/SurfaceControl( 8019): nativeRelease nativeObject e[496347855616]
I/SurfaceControl( 8019): nativeRelease nativeObject s[496347851392]
I/SurfaceControl( 8019): nativeRelease nativeObject e[496347851392]
I/SurfaceControl( 8019): nativeRelease nativeObject s[494768809600]
I/SurfaceControl( 8019): nativeRelease nativeObject e[494768809600]

**Comment by zachary-russell** [comment]
Please note I can also replicate this on an Android app after migrating to the individual flutterfire_ui packages for auth.  Pinning `1.0.5` resolves it for me as well.

**Comment by lesnitsky** [comment]
the only suspect I have is this one https://github.com/firebase/flutterfire/commit/343e6ed1ae27229b243d942e21c03ea310d57015

Can you try to provide a client id and see if the error still there?
Also: are you using `google-services.json` or `firebase_options.dart` generated by `flutterfire_cli` to configure firebase?

**Comment by zachary-russell** [comment]
In my case I have both as I started the project prior to `flutterfire_cli` existing. It could definitely be related to my particular issue.

**Comment by autolainen** [comment]
> are you using `google-services.json` or `firebase_options.dart` generated by `flutterfire_cli` to configure firebase?

I also have both. I didn't see any document clearly stated that I can remove google-services.json if I use flutterfire_cli.

**Comment by lesnitsky** [comment]
Fixed in #10017
