### ISSUE TITLE
🐛 [firebase_messaging]  above targetSdkVersion 20 does not show notification icon a white ⏹️ is shown !!

### ISSUE THREAD

**Issue by Shiba-Kar** [firebase/flutterfire#9979]
## Bug report

I am building  `minSdkVersion 21` `targetSdkVersion 33` and  `compileSdkVersion 33` Notification try does not show the logo a white square is shown

But building with `targetSdkVersion 20` the notification shows the logo

**Comment by danagbemava-nc** [comment]
Hi @Shiba-Kar, please provide a minimal complete reproducible code sample along with the version of `firebase_messaging` that you're using. 

Please also provide the output of `flutter doctor -v`. 

Thank you

**Comment by Shiba-Kar** [comment]
```pwsh

[√] Flutter (Channel stable, 3.3.8, on Microsoft Windows [Version 10.0.22623.891], locale en-US)
    • Flutter version 3.3.8 on channel stable at C:\Users\shiba\fvm\default
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (2 weeks ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\shiba\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = C:\Users\shiba\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32630.192
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.73.1)
    • VS Code at C:\Users\shiba\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.52.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22623.891]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 107.0.5304.107
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 107.0.1418.52

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by Shiba-Kar** [comment]
``` firebase_messaging: ^14.1.1 ```

**Comment by Shiba-Kar** [comment]
1. no code is used just added the plugin and followed the setup guide in https://firebase.flutter.dev/docs/messaging/notifications/ and https://firebase.google.com/docs/cloud-messaging/flutter/client .
2. fetched the device token and send a test notification from firebase console while the android app is in the background.

3. Notification received with ⏹️ while the app is run on `targetSdkVersion 33` but it works correctly in `targetSdkVersion 20`

**Comment by Shiba-Kar** [comment]
![image](https://user-images.githubusercontent.com/24454722/203936190-aa6ef1a7-4820-4d6e-b72a-624e0f07d67c.png)

![image](https://user-images.githubusercontent.com/24454722/203936419-5d51cc23-c692-4dd2-869a-f8bdebe624c1.png)

The two notifications are received on just one send request !!

**Comment by Lyokone** [comment]
@Shiba-Kar On Android, the notification is automatically displayed if it contains a `title` and `body` key.
On the example app we also use the LocalNotificationPlugin to display the notification manually.
That's why you are seeing 2 notifications on the app.

**Comment by Shiba-Kar** [comment]
It was a icon problem :( fixed !!
