### ISSUE TITLE
🐛 Firebase messaging getting initialization error on registering background handler.

### ISSUE THREAD

**Issue by kjawadDeveloper** [firebase/flutterfire#9980]
## Bug report

When the app tries to register the background listener before the first frame. I get this error 
`Attempted to run a DartExecutor that is already running.`
`PlatformException(activity_not_set, Activity is not set, make sure to call this method only from a foreground UI process., null, null)`

### Steps to reproduce

1) Try to register the listener before the first frame. 

## Additional context

I think this has something to do with the POST_NOTIFICATION permission checking. 
Its happening on firebase_messaging: 14.1.1
Works fine on firebase_messaging: 14.0.2

**Comment by Lyokone** [comment]
Hello, thanks for the report, do you have any code to help with the reproduction?

**Comment by kjawadDeveloper** [comment]
@Lyokone  i will try making a minimal sample.

**Comment by kjawadDeveloper** [comment]
Its also working fine on 14.0.4

**Comment by Lyokone** [comment]
14.1.1 and 14.0.4 are the same version, we reverted the changes in 14.1.0. 
Can you run `flutterfire update` to check it you're using the latest version?

**Comment by kjawadDeveloper** [comment]
14.1.1 solved this issue.
