### ISSUE TITLE
🐛 [cloud_firestore] Error: [cloud_firestore/already-exists] Target ID already exists: {random number}

### ISSUE THREAD

**Issue by hmbenhaim** [firebase/flutterfire#9986]
Hi,
Recently I started to get issues on the web platform only (android working just fine)

Error: [cloud_firestore/already-exists] Target ID already exists: {random number}
you can see the full error below.

I contacted firebase support and they said is something to do with connectivity, however, it is working just fine on the same network and it throwing an error if there is an issue with the connectivity it should use the cache

I can't get any work done on the web.

## Error log
```
Error: [cloud_firestore/already-exists] Target ID already exists: 2
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 299:10  createErrorWithStack
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 341:28            _throw
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/core/errors.dart 116:5                                           throwWithStackTrace
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1378:11                                          callback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>
```

## flutter doctor 
```
[√] Flutter (Channel stable, 3.3.8, on Microsoft Windows [Version 10.0.22621.169], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Professional 2022 17.4.0 Preview 6.0)
[!] Android Studio (not installed)
[√] VS Code (version 1.73.1)
[√] Connected device (4 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.
```

Thank you indeed

**Comment by darshankawar** [comment]
@hmbenhaim 
Check [this](https://github.com/firebase/flutterfire/issues/7197#issuecomment-948689963) response from Flutterfire team and see if it helps in your case.

Also, based on [this](https://github.com/firebase/flutterfire/issues/7197#issuecomment-1000370096) response, I am going ahead and closing it.

**Comment by hmbenhaim** [comment]
Hi, there is a bug in the SDK I'm not trying to create any document, I just trying to get a document and it throws this error. I don't have an access to the js SDK I'm using flutter.
I have checked the related issue and non of them give me a solution for that. 
Not sure what to do.

**Comment by darshankawar** [comment]
@hmbenhaim 
Can you provide a complete minimal reproducible code sample that triggers the reported error ?

**Comment by hmbenhaim** [comment]
> @hmbenhaim 
> Can you provide a complete minimal reproducible code sample that triggers the reported error ?
> 

Hi, so as you can see in my edit I manage to solve the issue with help of Firebase support team 
I'll explain what I have done and what makes the issue.
Basically I have listener for network connectivity If there is no internet I disable the network on the firestore and work offline, otherwise enabled,  for some reason this code makes another firestore method to throw error for some reason, so if I requested a document it throws error that target id already exist.
And it's happening only on the web and mobile it works just fine.

**Comment by darshankawar** [comment]
> So I remove the `disableNetwork` on the web

Where is this setting ? and how to remove it ?
