### ISSUE TITLE
flutterfire configure -> firebase_options.dart has wrong keys

### ISSUE THREAD

**Issue by tomazbracic** [firebase/flutterfire#9990]
## Bug report

**Describe the bug**
Using `flutterfire configure` I ended up with `firebase_options.dart` file which has firebase option entries at the end of the file  for each of the apps that I created/selected during `flutterfire configure` (web, android, ios and macos). 

But keys that are used there are wrong. It looks like their names changed during time. And for one of them I can't seems to find appropriate key. (See below). 

They should be (those are keys expected)
```
# code prior to this is left out
# 
(const) FirebaseOptions* FirebaseOptions({
  String* apiKey,
  String* bundleID,
  String* clientID,
  String* trackingID,
  String* gcmSenderID,
  String* projectID,
  String* androidClientID,
  String* googleAppID,
  String* databaseURL,
  String* deepLinkURLScheme,
  String* storageBucket,
})
```

But instead of this I get a file created with keys like `appId`, `messagingSenderId`, `projectId`, `iosClientId`, `iosBundleId` and this last one `authDomain` **doesn't even exist anymore** if I am not mistaken. (see below)

```
# the rest of the code is omitted 

static const FirebaseOptions web = FirebaseOptions(
    apiKey: '<deleted>',
    appId: '<deleted>',
    messagingSenderId: '<deleted>',
    projectId: '<deleted>',
    authDomain: '<deleted>',
    storageBucket: '<deleted>',
  );
```

Looks like some change occurred and was not followed. 

### Steps to reproduce

1. firebase login
2. flutterfire configure

### Expected behavior

Generated values would be equal to what library is using. And I don't know about `authDomain` which is missing in FirebaseOptions. 

I am still learning Flutter so there might be a small chance that I missed something, but don't think so :)

**Comment by danagbemava-nc** [comment]
Hi @tomazbracic, what flutterfire dependencies did you have in your project? 

Please also provide the version of flutterfire_cli you're using and lastly, please provide your complete firebase_options.dart file. 

Thank you

**Comment by tomazbracic** [comment]
Hi, 

This was totally my bad. I appologize. Was following some specs and forgot to double-check pub.dev for the latest version of `firebase_core`. Version that I used was way too old. After fixing this everything worked smoothly.
